### PR TITLE
imageop: Properly ellipsise the module instance name.

### LINKED ISSUE #13762: Presets name are not ellipsized: this could make panel size change on long ones
**Describe the bug/issue**

1. Have a not too wide panel (it should be smaller that what is needed to display preset name)
2. Go to Tone equalizer module
3. Select preset with long name (those starting by compress)
4. See that panel size has changed to allow all preset name to appears.
5. Change a setting on tone equalizer, preset name disappear and panel is restored too previous smaller size.

This is probably related to PR #13149. So @TurboGit: should probably another one for you.

**Expected behavior**

Panel size should not changed and so preset name should be ellipsized.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : master

### PR DESCRIPTION
**Pull request by TurboGit**
Fixes #13762.

### CODE REVIEW

**Comment by TurboGit** [comment]
Probably a merge issue at some point as this code was made when implementing this part.

**Review by Nilvus — APPROVED** [review]
All good! Thanks for the quick fix.

**Comment by Nilvus** [comment]
Oh, just a thing: is it normal that you are on your master and not on a branch for that PR?

**Comment by TurboGit** [comment]
> Oh, just a thing: is it normal that you are on your master and not on a branch for that PR?

Yes, that's a quick fix so I didn't create a branch for this. Thanks for the review.

**Pull request merged**
