### PR TITLE
thumbtable : rework filemanager exit

### LINKED ISSUE #6637: flag selected thumb (triangle on top) visible on lighttable
**Describe the bug**
flag selected thumb (triangle on top) visible on lighttable

**To Reproduce**
1. Go to lighttable
2. Click X to enter the culling mode
3. Click X to leave the culling mode
4. Fly over the 2 thumbs which where displayed in culling view (to refresh the display)
5. You'll see the little triangle on top

This triangle should only be displayed on the filmstrip.

**Expected behavior**
no triangle visible on lightatble

**Screenshots**

image

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS:GNU/Debian

### PR DESCRIPTION
**Pull request by AlicVB**
by putting thumbtable in a "none" state
this fix #6637

### CODE REVIEW

**Comment by AlicVB** [comment]
seems that there's errors, but as far as I can tell (always hard to read details) it's due to new channelmixer... Just ask if I can do anything !

**Comment by johnny-bit** [comment]
Just push an empty commit or rebase on master and it'll be fine. Aurelien fixed channelmixer problems in CI :)

**Comment by aurelienpierre** [comment]
I have restarted the CI jobs, don't bother.

**Review by TurboGit — APPROVED** [review]
Works for me. Thanks!

**Pull request merged**
