### PR TITLE
Preliminary D7200 support

### PR DESCRIPTION
**Pull request by ralfbrown**
Here are the changes needed to support the new Nikon D7200, under the assumption that it is using the same sensor as the D7100 (so I'm just reusing the adobe_coeff and noise profiles).

(If someone can tell me how to drop that first commit of a personal change from this pull request, I'll remove it; otherwise, I'll undo it in some fashion.)

### CODE REVIEW

**Comment by ralfbrown** [comment]
This is in response to Camera Support request #10382.

**Comment by moy** [comment]
To remove a commit, use "git rebase -i", delete the line corresponding to this commit in the todo-list, and let git do the job. You'll need to do a force-push to overwrite your previous pull-request.

**Comment by ralfbrown** [comment]
I hope I didn't just make things worse....  Is there a "git rebasing for dummies" guide anywhere? :-)

**Comment by moy** [comment]
http://git-scm.com/book/en/v2/Git-Branching-Rebasing

Do read the part http://git-scm.com/book/en/v2/Git-Branching-Rebasing#The-Perils-of-Rebasing

Then read the "interactive mode" section from the manpage http://git-scm.com/docs/git-rebase (but you don't want to start with the manpage)

**Comment by ralfbrown** [comment]
To clean things up, I'm going to close this pull request and open another one in its place.

**Pull request closed without merging**
