### PR TITLE
fixes 6552, DATADIR==SHAREDIR

### LINKED ISSUE #6552: Missing icon in about dialog window since 15th october
Just a simple one: missing icon in about dialog windows. This is since 15th october. Commit ac58d22a1e9836459f895c93401c04608a758504 is good and commit 3165deaed7022f68a2d1c2b0d867583f4183b0a9 don't have that icon. The issue is somewhere between those commits (can't compile them without adding fix added on last cited commit.

@AlicVB and @TurboGit: most updates are from you, so maybe you will see quickly how to fix that.

### PR DESCRIPTION
**Pull request by codingdave**
Fixes #6552

### CODE REVIEW

**Comment by codingdave** [comment]
waiting for feedback from @AlicVB and @Nilvus

**Comment by codingdave** [comment]
$ ~/unstable/darktable_fix/6552_DATADIR_SHAREDIR/bin/darktable -d dev --library foo.db --configdir .
0.000118 application_directory: /home/david/unstable/darktable_fix/6552_DATADIR_SHAREDIR/bin
0.000170 darktable.datadir: /home/david/unstable/darktable_fix/6552_DATADIR_SHAREDIR/share/darktable
0.000192 darktable.plugindir: /home/david/unstable/darktable_fix/6552_DATADIR_SHAREDIR/lib/darktable
0.000213 darktable.localedir: /home/david/unstable/darktable_fix/6552_DATADIR_SHAREDIR/share/locale
0.000240 darktable.configdir: /home/david/workspace/darktable.git
0.000258 darktable.cachedir: /home/david/.cache/darktable
0.000276 darktable.sharedir: /home/david/unstable/darktable_fix/6552_DATADIR_SHAREDIR/share
0.000289 darktable.tmpdir: /tmp
0.000304 new_xdg_data_dirs: /home/david/unstable/darktable_fix/6552_DATADIR_SHAREDIR/share:/home/david/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop
0.143286 kernel directory: /home/david/unstable/darktable_fix/6552_DATADIR_SHAREDIR/share/darktable/kernels

**Comment by AlicVB** [comment]
yep, I confirm that it fix the issue for me. Thanks !

**Comment by Nilvus** [comment]
Same for me, that PR fix the issue. Thanks @parafin and @codingdave.

**Comment by codingdave** [comment]
Thank you too.

**Comment by codingdave** [comment]
@TurboGit seems this PR is working fine. Thanks for signaling me.

**Comment by TurboGit** [comment]
Thanks all for the detective work and fix !

**Pull request merged**
