### PR TITLE
Fix blending for feathering input

### LINKED ISSUE #10422: crash when using new crop module with retouch and blend by parametric masks
**Describe the bug/issue**
when using retouch (using path and clone - havn't seen that in other constellations) with using later cropped areas darktable crashes.
not in any case, but frequently

scenario:
image: [20210530-IMG_0112.CR3](https://mega.nz/file/mTRxTS5T#SYfb4G116pnEFJq1ATordyk9DyFbrxKmRcqdJefthhc)
xmp: [20210530-IMG_0112_01.CR3.xmp.txt](https://github.com/darktable-org/darktable/files/7540766/20210530-IMG_0112_01.CR3.xmp.txt)

if crop module is moved below retouch the issue is not reproducible

**To Reproduce**
1. apply retouch in clone mode using drawn path 
2. crop so parts of the path are out of frame
3. switch image - switch back (maybe after restart of darktable)
4. if that doesn't result in an crash: reset pipeline order to default
5. See error
6. drag crop via ctrl-shift below retouch
7. switch image and switch back - no crash expected
8. reset pipeline order
9. get crash 

bt on win10:
```
Thread 1043 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 22904.0x34d0]
0x00007ff946e744c9 in msvcrt!memmove () from C:\WINDOWS\System32\msvcrt.dll
(gdb) bt
#0  0x00007ff946e744c9 in msvcrt!memmove ()
   from C:\WINDOWS\System32\msvcrt.dll
#1  0x00007ff8fe39c45b in _develop_blend_process_copy_region._omp_fn.0 ()
    at C:/msys64/home/SHM/darktable/src/develop/blend.c:358
#2  0x00007ff92e02de30 in ?? () from C:\msys64\mingw64\bin\libgomp-1.dll
#3  0x00007ff931604f33 in ?? () from C:\msys64\mingw64\bin\libwinpthread-1.dll
#4  0x00007ff946e3af5a in msvcrt!_beginthreadex ()
   from C:\WINDOWS\System32\msvcrt.dll
#5  0x00007ff946e3b02c in msvcrt!_endthreadex ()
   from C:\WINDOWS\System32\msvcrt.dll
#6  0x00007ff948b37034 in KERNEL32!BaseThreadInitThunk ()
   from C:\WINDOWS\System32\kernel32.dll
#7  0x00007ff948e22651 in ntdll!RtlUserThreadStart ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#8  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

issue is also reproducible on osx here the bt

```
lldb) bt
* thread #55, stop reason = EXC_BAD_ACCESS (code=1, address=0x196665a50)
  * frame #0: 0x00007ff80356f1c9 libsystem_platform.dylib`_platform_memmove$VARIANT$Haswell + 41
    frame #1: 0x000000010092f4ae libdarktable.dylib`.omp_outlined..30 at blend.c:358:5 [opt]
    frame #2: 0x000000010092f3e4 libdarktable.dylib`.omp_outlined..30(.global_tid.=<unavailable>, .bound_tid.=<unavailable>, oheight=<unavailable>, iwidth=<unavailable>, ioffset=<unavailable>, owidth=<unavailable>, output=0x00000001b2986000, input=0x000000018e59a000) at blend.c:351:1 [opt]
    frame #3: 0x00000001002dd573 libomp.dylib`__kmp_invoke_microtask + 147
    frame #4: 0x000000010029027f libomp.dylib`__kmp_invoke_task_func + 191
    frame #5: 0x000000010028f343 libomp.dylib`__kmp_launch_thread + 131
    frame #6: 0x00000001002cb080 libomp.dylib`__kmp_launch_worker(void*) + 304
    frame #7: 0x00007ff80355c514 libsystem_pthread.dylib`_pthread_start + 125
    frame #8: 0x00007ff80355802f libsystem_pthread.dylib`thread_start + 15
(lldb) up
libdarktable.dylib was compiled with optimization - stepping may behave oddly; variables may not be available.
frame #1: 0x000000010092f4ae libdarktable.dylib`.omp_outlined..30 at blend.c:358:5 [opt]
   355 	  {
   356 	    const size_t iindex = y * iwidth + ioffset;
   357 	    const size_t oindex = y * owidth;
-> 358 	    memcpy(output + oindex, input + iindex, sizeof(float) * owidth);
   359 	  }
   360
   361 	  return output;
(lldb)
frame #2: 0x000000010092f3e4 libdarktable.dylib`.omp_outlined..30(.global_tid.=<unavailable>, .bound_tid.=<unavailable>, oheight=<unavailable>, iwidth=<unavailable>, ioffset=<unavailable>, owidth=<unavailable>, output=0x00000001b2986000, input=0x000000018e59a000) at blend.c:351:1 [opt]
   348 	  }
   349
   350 	#ifdef _OPENMP
-> 351 	#pragma omp parallel for default(none) \
   352 	        dt_omp_firstprivate(input, output, iwidth, ioffset, owidth, oheight)
   353 	#endif
   354 	  for(size_t y = 0; y < oheight; y++)
(lldb)
frame #3: 0x00000001002dd573 libomp.dylib`__kmp_invoke_microtask + 147
libomp.dylib`__kmp_invoke_microtask:
->  0x1002dd573 <+147>: movq   $0x1, %rax
    0x1002dd57a <+154>: movq   -0x8(%rbp), %rbx
    0x1002dd57e <+158>: movq   %rbp, %rsp
    0x1002dd581 <+161>: popq   %rbp
```

**Platform**
* darktable version : darktable 3.7.0+1493~g4a7774f95-dirty
* OS                : Win10 / OSx

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
This feature has been broken for some versions if a module expanded it's roi_in.

The reasons for this were basically
a) incorrect testing for identical roi areas
b) testing for roi_in fully includes roi_out

While being here
- make use of dt_iop_copy_image_roi()
- code maintenance
- some minor improvements
- reformatting

Fixes #10422

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Comment by TurboGit** [comment]
Just need an entry for the release notes please.

**Comment by jenshannoschwalm** [comment]
Release note: Feathering input fixed while using distorting modules like retouch or lens.

**Comment by TurboGit** [comment]
Thanks!

**Pull request merged**
