### PR TITLE
lighttable: make lighttable faster on High DPI screen.

### PR DESCRIPTION
**Pull request by TurboGit**
Maybe mouse_moved events are now filtered out (some measurement shows that
only 10% of the mouse_move are actually handled).

This is WIP, to be tested on HDPI screen (4k & 5k). This breaks the zoomable lighttable rating for
now.

### CODE REVIEW

**Comment by cryptomilk** [comment]
It is not perfect yet, but definitely an improvement!

**Comment by TurboGit** [comment]
A bit vague. Was it on a 4k screen? Was it quite unusable before and do you feel that with this patch it makes the lightable bearable or even usable? Somehow as fast as on a full HD screen?

**Comment by TurboGit** [comment]
Here report that there is no change:
https://redmine.darktable.org/issues/10764#note-18

That's my second attempt, looks like it fails again :)

Maybe there is some other events that take CPU cycle... I don't own a 4k display, so this will probably have to wait.

**Comment by TurboGit** [comment]
@cryptomilk : can you test the new version I just pushed? Thanks.

**Comment by cryptomilk** [comment]
* Yes, I have a 4K display
* Yes, this is a small improvement but not as snappy as it could be.
* No, it is not perfect yet.

**Comment by cryptomilk** [comment]
2b24086bdcae7b9a988f081ea7825862ee22ea75 seems to work!

**Comment by TurboGit** [comment]
Ah ah... Is that fast now? How usable?

**Comment by cryptomilk** [comment]
Moving the mouse is fast, the selection follows instantly However scrolling is broken with 2b24086bdcae7b9a988f081ea7825862ee22ea75. Only two thumbnails are changing. If I scroll more it is refreshed after some time ...

**Comment by TurboGit** [comment]
Right, this is fixed in the new version, I'll push now.

**Comment by TurboGit** [comment]
I've just pushed a new version that should fix most issues and handle also the zoomable lighttable.

**Comment by cryptomilk** [comment]
Now scrolling works again but the borders for the thumbnails are gone :-)

**Comment by cryptomilk** [comment]
Scrolling works, it is super fast but the borders of the thumbnails are gone, we are close :-)

**Comment by TurboGit** [comment]
What do you mean by borders of the thumbs? Can you send a screenshot? Thanks.

**Comment by cryptomilk** [comment]
https://xor.cryptomilk.org/darktable/darktable.png

**Comment by aurelienpierre** [comment]
Sounds like a CSS rule gone.

**Comment by aurelienpierre** [comment]
Wow ! Just tested, indeed the borders are gone in the lighttable (I won't miss them), but that's some blazing speed-up !

**Comment by TurboGit** [comment]
Are the borders there during first display and disappear after? Or are they never there? I cannot reproduce that. But this will get fixed and should not degrade the perfs.

**Comment by cryptomilk** [comment]
They are gone on startup.

**Comment by cryptomilk** [comment]
29caefec7d8d83ce424cfaf3fc35104f90e8a6b9 doesn't fix it ... :-)

**Comment by TurboGit** [comment]
Ok, don't really know what is happening :( I'll sleep on that.

**Comment by aurelienpierre** [comment]
Also, when we delete pictures, there is a sort of lag before the thumbnails are updated and reordered. Rating them with stars is still a bit random (needs to be done twice), and laggy too (there is some sort of delay between the click and the actual stars update).

**Comment by nilsholle** [comment]
screenshot_20190106_104427
This happens on zooming in/out using Ctrl+/Ctrl- (should be reproducible on standard 1080p displays).

**Comment by TurboGit** [comment]
@nilsholle : this should be fixed.

**Comment by TurboGit** [comment]
@aurelienpierre : yes the lag is there because when reordering we need to redraw everything. So I do expect some lag for some actions and have this at least "usable" in 4k or 5k display.

**Comment by TurboGit** [comment]
@cryptomilk : about the borders, do you see the yellow ones when you have a group selected?

**Comment by cryptomilk** [comment]
@TurboGit Yes, if I hover a group I get the yellow group selection border.

**Comment by cryptomilk** [comment]
As soon as I use a custom darktable.css it stops working. It looks like the darkroom_bg_color gets applied to the lighttable.

**Comment by cryptomilk** [comment]
Ah ok, I see I need to change the lightable background color to be different form my darkroom backround color.

**Comment by cryptomilk** [comment]
We are good to go. Just looking at the patch it looks like a few things should be size_t like max_cols and max_rows and then some rows and cols variables dealing with it. But such cleanup could be done later ...

**Comment by TurboGit** [comment]
As I write in Redmine:

> For 2.6.1, maybe will see but then this needs a quite extensive testing phase. Even if the patch is not that big, it is quite delicate and in a part that we cannot break (think about all filtering settings, the stars, local copies...). So please do as much testing as possible (and any dev around). It will be easier when merged to master, and report issues preferably in GitHub. Thanks.

**Comment by PaoloAst** [comment]
I'd like to test this branch, but I don't know how to do it via git commands.

$> git fetch
$> git checkout <branch name>

and 

./build.sh

Am I missing something?

**Comment by TurboGit** [comment]
$ git fetch origin
$ git checkout faster-lighttable-2

and yes,

./build.sh

plus the command to install the compiled version as displayed after the compilation succeeds.

**Comment by PaoloAst** [comment]
Thanks, probably I forgot to call "git config". Now it works and it seems very faster than before. I'll make some test

**Comment by nilsholle** [comment]
Two things go wrong when showing a single image in lighttable:
1. I think the image position is wrong. On the left, there is a small space (slightly lighter gray) that shouldn't be there.
2. When switching to darkroom and back, the top of the lighttable should be redrawn.
screenshot_20190106_190550

**Comment by aurelienpierre** [comment]
Now, navigating with keyboard arrows is broken, only the active thumbnail in the lighttable is updated, not the full rows.

**Comment by aurelienpierre** [comment]
>  yes the lag is there because when reordering we need to redraw everything. So I do expect some lag for some actions and have this at least "usable" in 4k or 5k display.

The lag was on HD 1080 screen. I did not have it before (even on 4K).

**Comment by TurboGit** [comment]
@aurelienpierre : thanks I can reproduce the redraw issue with keyboard. will fix.

**Comment by TurboGit** [comment]
I consider this last version as usable and should be working fine. I have made many tests. Please try it and report issues. Again, this is a very delicate part with many many possible interactions.

**Comment by cryptomilk** [comment]
@TurboGit I will test this asap, probably tomorrow morning. I have to edit some pictures.

**Comment by TurboGit** [comment]
@aurelienpierre  : I can reproduce the first two points. Not the others.

**Comment by nilsholle** [comment]
Are the changes already implemented for the thumbnail view at the bottom of the darkroom? Feel like that is still a little slow.

**Comment by TurboGit** [comment]
No, for now the filmstrip is still slow. This is next step.

**Comment by TurboGit** [comment]
@nilsholle : the filmstrip should now be fast too.

**Comment by cryptomilk** [comment]
This looks good, I didn't find any issue when testing.

**Comment by TurboGit** [comment]
@cryptomilk : just checking... you've tested the last version with the filmstrip?

**Comment by cryptomilk** [comment]
Yes, I did

**Comment by homer3018** [comment]
Hi guys,

I'd be happy to assist and do some further testing on my newly bought iMac 5k, but as I'm new to mac I have some (possibly dumb) questions like is it ok to have the regular 2.6 DT installed along with the dev version ? If someone would be kind enough to guide me through that that'd be great. Once up and running I hope I can help further with some coding but we'll see to that at a later stage :)
Thanks and keep up the good work !

**Comment by TurboGit** [comment]
@homer3018: this is now merged. I cannot help you with building on MacOS. You'll probably get helps on the mailing-list.

**Comment by homer3018** [comment]
All good Pascal, thanks for assisting.

**Pull request closed without merging**
