### PR TITLE
Smarter tagging

### PR DESCRIPTION
**Pull request by piterdias**
This smart tagging feature works in the following way:
1) Searching for tags;
1.1) While searching for similar tags, order the results in alphabetic order and show then first;
1.2) While searching the related tags (tags that are not similar, but was used in pictures that have similar tags), order the results in alphabetic order and show after the similar tags;
2) Adding a tag to photo will add from the root of the tag until the tag itself, including all the intermediaries. Adding A|B|C will add A, A|B and A|B|C;
3) Deleting a tag from a picture will delete from the tag until the last leaf, including all the intermediaries. Giving the tags A, A|B and A|B|C, deleting A|B will delete A|B|C as well, but leaves A;
4) Creating a tag creates all the non-existing nodes. If the tags A|B exists and someone tries to create A|B|C|D, the tags A|B|C and  A|B|C|D are created and added to the picture. If for some reason the tag A doesn’t exist, it will be created as well.

### CODE REVIEW

**Comment by houz** [comment]
What purpose does adding all the intermediate parts as individual tags serve?

**Comment by TurboGit** [comment]
> Adding A|B|C will add A, A|B and A|B|C

I'm certainly not for this. It will just add noise in the list of tags. And I'm not sure what it is supposed to fix?

**Comment by piterdias** [comment]
I used to work with digiKam and the tag filtering (right panel) only works properly if all nodes are added. If I add A|B|C to the sidecar, digiKam doesn't show any picture if I filter by A or A|B. I need to add A, A|B and A|B|C to make good use of tag filtering.
darktable tag filtering is much better, but I decided to add this feature to help using the sidecar files in digiKam.

**Comment by TurboGit** [comment]
I'm not sure we want to mess darktable for the sake of fixing digikam. frankly having all those unneeded tags in dt tag view is not something I want to see.

**Comment by piterdias** [comment]
Not a problem. Compiling darktable is so easy that I can keep the change for myself. 😊
Should I cancel the request to clean up the list of pull requests?

**Comment by TurboGit** [comment]
Ok, I'll close the PR we can reopen at anytime if needed anyway. Thanks.

**Pull request closed without merging**
