### PR TITLE
Revert lighter font-weight

### LINKED ISSUE #9102: Recent CSS changes cause font legibility problems
**Describe the bug/issue**

PR #9074 changed font weights which (at least on my system) impacted their legibility. The problem affects all default themes. I've made NO css changes to my user.css and I tried with empty config just to make sure.

@Nilvus can you take this one?

**To Reproduce**
1. Open up darktable
2. See very low contrast fonts

**Expected behavior**

Fonts should be easily readable

**Screenshots**

What I see:
Zrzut ekranu z 2021-05-29 14-42-42

commenting out line 246 in darktable.css makes the problem go away:
Zrzut ekranu z 2021-05-29 14-43-20

**Which PR introduced the error**
PR #9074

**Platform**

* darktable version : e.g. 3.5.0+2391~g0aaee290b
* OS                : Linux - kernel 5.10.27
* Linux - Distro    :  Gentoo
* Memory            : 24G
* Graphics card     : nVidia GeForce GTX 1060 6GB
* Graphics driver   : nvidia-drivers-465.31
* OpenCL installed  : YES
* OpenCL activated  :  NO
* Xorg              : xorg-server-1.20.11
* Desktop           : Gnome 40
* GTK+              : 3.24.29
* gcc               :  gcc version 10.2.0 (Gentoo 10.2.0-r5 p6)
* cflags            :  ?
* CMAKE_BUILD_TYPE  : RelWithDebInfo

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **no**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

### PR DESCRIPTION
**Pull request by Nilvus**
Fix #9102

@elstoc and @johnny-bit: could you check if it's good for all themes now?
@lhietal: unfortunately, by now I don't see any way to deal with your font face issue while not having #9102 issue (and that last one is more important to fix than yours). Hope it's good for you.

### CODE REVIEW

**Review by johnny-bit — APPROVED** [review]
This change looks good to me. fixes all problems :)

interestingly enough - i don't see difference between `fg_color` being either `grey_80` or `grey_70`...

**Comment by Nilvus** [comment]
> This change looks good to me. fixes all problems :)
> 
> interestingly enough - i don't see difference between `fg_color` being either `grey_80` or `grey_70`...

Quite interesting. I see one on my side!

**Review by elstoc — APPROVED** [review]
All good for me

**Review by lhietal — APPROVED** [review]

**Review by TurboGit — APPROVED** [review]
Thanks !

**Pull request merged**
