### PR TITLE
Chinese README

### PR DESCRIPTION
**Pull request by TC999**

### CODE REVIEW

**Comment by kmilos** [comment]
Depending on whether this is simplified or traditional, [I suggest changing the label from only "ZH" to "zh-Hans" or "zh-Hant" (also note the case please)](https://unicode-org.github.io/icu-docs/design/language_code_issues.html).

One major thing I see with this: how do we ensure continuous maintainance of this translation (i.e. keep always up to date when the original changes)?

**Comment by TC999** [comment]
OK,already edited

**Comment by victoryforce** [comment]
First of all, thank you for your contribution @TC999 ! But such a contribution cannot be one-time. The Readme file may change over time and we would like the translations to not contain outdated text. I hope you will be available to update the Chinese translation if needed.

**Comment by TC999** [comment]
> First of all, thank you for your contribution @TC999 ! But such a contribution cannot be one-time. The Readme file may change over time and we would like the translations to not contain outdated text. I hope you will be available to update the Chinese translation if needed.

OK

**Comment by TurboGit** [comment]
As highlighted above, this README file is updated regularly and we certainly can't maintain the Chinese version in sync with the English one ourselves. This is an issue for the quality of the project.

@TC999: So we didn't expected just a OK. The really question is **are you ready for a long term commitment** to translate the future changes in README.md.

My view is that this is not a good idea and I'm not in favor if this PR. If we get a README translated in all languages supported by dt we can be sure that the translations will diverge pretty soon and some README will get obsolete pretty quickly.

Isn't an automatic translation service not sufficient?

**Comment by kmilos** [comment]
> So we didn't expected just a OK. The really question is **are you ready for a long term commitment** to translate the future changes in README.md.

Not only this, but a proposal on how this will be ensured?

**Comment by victoryforce** [comment]
@TC999 I have a suggestion for you that will help both Chinese users and the darktable project much more. Normal users are unlikely to read the README on the application's GitHub page. But since darktable is quite a complex program, many people would benefit from first reading the user manual, which both explains the basic concepts of photographic image processing and documents the entire user interface.

We have a project to crowdsource [the translation of the user manual into other languages](https://weblate.pixls.us/projects/darktable/dtdocs/). As you can see, the translation into Chinese (Traditional) is already 27% done. This is a lot, but it seems that the previous translator lacked the energy/time/motivation to complete this translation.

I understand that the volume of work here is much larger. After all, I translated this manual into Ukrainian, so I know how long it takes for one translator. But you could get other translators interested and involved, then the amount of work for each will not be too big. In this way, the translation work already done by someone will not be in vain, and it will be easier for Chinese users to master the program.

**Pull request closed without merging**
