### PR TITLE
Updates to pt_BR

### PR DESCRIPTION
**Pull request by jpellegrini**

### CODE REVIEW

**Comment by aurelienpierre** [comment]
Please rebase your branch on master. Something like `git rebase upstream/master` should do. That will remove all the merging commits that we don't want in master's history.

**Comment by jpellegrini** [comment]
> Please rebase your branch on master. Something like `git rebase upstream/master` should do. That will remove all the merging commits that we don't want in master's history.

I'm sorry! Fixed it now.

**Comment by aurelienpierre** [comment]
You don't need to merge branches like that at all. You can only use `git fetch upstream master` then rebase.

**Comment by jpellegrini** [comment]
> You don't need to merge branches like that at all. You can only use `git fetch upstream master` then rebase.

That's what I always do (I have a remote branch set to the darktable main repo), except I do pull (which does merge) instead of fetch. But it makes sense to only fetch -- I'll start doing that.

(I remember when git and other distributed version control systems were in their infancy. git was absolutely not the one I liked most, because its usage was too confusing. But anyway, it became the standard...)

**Comment by aurelienpierre** [comment]
You still have one merging commit ;-)

**Comment by TurboGit** [comment]
I'll squash and merge from there.

**Pull request merged**
