### PR TITLE
Added shuffle option to sorting -- Looking for opinions

### PR DESCRIPTION
**Pull request by mondoman712**
I added the ability to shuffle your images in the light table.

### CODE REVIEW

**Comment by TurboGit** [comment]
Do you have a usage of this or is that just for the challenge :) ?

**Comment by mondoman712** [comment]
I was just scrolling through my images looking for any pairs of visually similar images from different places and thought this would be a better way to find some, but also just an interesting way to look through a collection of images. Once I came up with the idea I did then just want to see if I could implement it and I thought I'd just do it and make a PR and we can discuss whether anyone else might find it useful here.

**Comment by TurboGit** [comment]
Ok, let's see what others think about this. Not a large piece of code, so probably not disruptive, but yet I do want to be sure it is useful enough to be integrated.

**Comment by aurelienpierre** [comment]
I can actually see a use for that.

**Comment by TurboGit** [comment]
Oki, let's plan this for 2.8.

**Comment by TurboGit** [comment]
manually merged.

**Pull request closed without merging**
