### PR TITLE
highlights: Remove superfluous code after introspection fixed.

### PR DESCRIPTION
**Pull request by TurboGit**
Continued work for #14050.

### CODE REVIEW

**Comment by ralfbrown** [comment]
At least the `d->` override in `gui_reset` is also superfluous, maybe both.

**Comment by jenshannoschwalm** [comment]
Right again. Tested and via reading source looks good to me.

**Comment by TurboGit** [comment]
Sadly the previous change for PR #14050 (a5ddca9c202c0918d3825704ba199be42c1ec21f) introduces 26 regressions tonight. This is due to the fact that some old edits don't necessary have highlights module recorded into the XMP. So when reloaded them the new default is changed from CLIP to OPPOSED.

I don't have a better idea for now, so I'll probably revert this change. Any idea?

**Comment by jenshannoschwalm** [comment]
Nope.

**Comment by ralfbrown** [comment]
Rock & hard place....  I suppose the only way to handle both new edits and those old sidecars is to have the sidecar loader add HLR-clip if there's no HLR listed.

**Comment by TurboGit** [comment]
> Rock & hard place.... I suppose the only way to handle both new edits and those old sidecars is to have the sidecar loader add HLR-clip if there's no HLR listed.

I came to the same conclusion... Looks something not easy, but I'll try.

**Comment by TurboGit** [comment]
@ralfbrown @jenshannoschwalm : I'm closing this, see #14870. I'd like your review on this one. TIA.

I'll check all the tests now, but some regressions are now fixed.

**Pull request closed without merging**
