### PR TITLE
Do final downsampling late in-pipe (if HQ is on). Fixes #10326

### LINKED ISSUE #10326: multiple parametric masks
**Is your feature request related to a problem? Please describe.**

Occasionally one would like to select a union of various properties that can be described by parametric masks (eg skin color and blue for eyes, nothing else).

**Describe the solution you'd like**

Multiple parametric masks in a module instance, to be combined under the same [rules](https://docs.darktable.org/usermanual/3.6/darkroom/masking-and-blending/masks/drawn-and-parametric/) as drawn elements and parametric masks.

**Alternatives**

For some transformations, it is possible to work around this problem by using multiple module instances with the parametric mask elements that would form the union above. However, that becomes tedious when information would be lost by a transformation (eg desaturate some colors), or the transformations are nonlinear.

For example, to desaturate everything but skin tones and blue, one would currently desaturate from red to skin tones, then from skin tones to blue, then from blue onwards. This requires 3 module instances, but all that changes is the mask.

Naturally, drawn masks can be a workaround too and are very powerful, but address a different problem.

**Additional context**

[Discussion](https://discuss.pixls.us/t/combine-parametric-masks/27711).

### PR DESCRIPTION
**Pull request by LebedevRI**
It is better to do it as an iop late in pipe because that way we can control the point of downsampling.
So we can avoid downsampling borders and watermark iops.

### CODE REVIEW

**Comment by edgomez** [comment]
Does the rescaling happen with the color data still being linear in hq case ?

Because current scaling doesn't take care to linearize the data itself so it can't be done after any gamma is applied.

**Comment by LebedevRI** [comment]
@edgomez well, in git master, in hq case, rescaling happens after the pipe, and gamma is applied at the end of the pipe.

With this PR, the order of modules will be following:
```
1000 gamma
983 dither
967 watermark
951 borders
935 finalscale
919 overexposed
...
```
In other words, gamma will always be applied after rescaling.

**Comment by LebedevRI** [comment]
Though, i should add that in git master, "after-pipe scaling" is only done after dt_dev_pixelpipe_process_no_gamma() call, which means, the data is not gamma-corrected in the first place.

**Comment by houz** [comment]
Just for the record, gamma.c doesn't do gamma correction. The file name is just a historical curiosity that's not worth fixing (leaving old libgamma.so in people's installations, requiring a bump of the iop version, ...).

**Pull request merged**
