### PR TITLE
deprecate channelmixer.c

### PR DESCRIPTION
**Pull request by aurelienpierre**
No need for 2. There is a "basic channel mixer" preset in color calibration / channelmixerrgb.c for the ones missing the simple UI.

### CODE REVIEW

**Comment by chhil** [comment]
Please can you make the presets available in channel mixer available in color calibration?

**Comment by TurboGit** [comment]
Let's vote:

<p><a href="https://api.gh-polls.com/poll/01EQ06KPJADNMF3BVKZGYZ1QPX/never%20used%20it%2C%20deprecate%20it/vote"></a>
<a href="https://api.gh-polls.com/poll/01EQ06KPJADNMF3BVKZGYZ1QPX/almost%20nerver%20used%20it%2C%20don&#39;t%20care%20baout%20the%20final%20choice/vote"></a>
<a href="https://api.gh-polls.com/poll/01EQ06KPJADNMF3BVKZGYZ1QPX/this%20is%20an%20important%20module%20for%20me%2C%20keep%20it%20active/vote"></a></p>

**Comment by TurboGit** [comment]
Let's vote:

<p><a href="https://api.gh-polls.com/poll/01EQ06QCPB1CVT2X9VNE5HBA3A/never%20used%20it%2C%20or%20prefer%20new%20color%20calibration%2C%20deprecate%20it/vote"></a>
<a href="https://api.gh-polls.com/poll/01EQ06QCPB1CVT2X9VNE5HBA3A/almost%20nerver%20used%20it%2C%20don&#39;t%20care%20baout%20the%20final%20choice/vote"></a>
<a href="https://api.gh-polls.com/poll/01EQ06QCPB1CVT2X9VNE5HBA3A/this%20is%20an%20important%20module%20for%20me%2C%20keep%20it%20active/vote"></a></p>

**Comment by aurelienpierre** [comment]
> Please can you make the presets available in channel mixer available in color calibration?

What presets ? There are already film and basic channel mixer ?

**Comment by chhil** [comment]
image

**Comment by aurelienpierre** [comment]
The B&W presets are bogus though. I added them because the coeffs were in the code as comments, but they have no relationship with anything real.

The color boosters need HSL, so they can't be translated. 

Channel swaping is really easy.

**Comment by aurelienpierre** [comment]
20 for, 6 against, 6 don't care. Motion carries.

**Pull request merged**
