### PR TITLE
Optical balance: blending tabs icons

### PR DESCRIPTION
**Pull request by Mark-64**
Optical balance of another group of icons, blending tabs.
Hopefully the last one

Screenshot from 2020-06-04 21-13-50

### CODE REVIEW

**Comment by Nilvus** [comment]
I update hover effects on those buttons in my #5303 PR (see blending-tabs and modules-tabs line to remove not wanted margins seeing in hover effect and not apply border-radius. Could you check if on your system (and especially Hidpi) if it remains good with my tweaks?

**Comment by Nilvus** [comment]
Tested on my side and ok for me and with my CSS tweaks.

**Comment by TurboGit** [comment]
Looks good to me too. Merging. Thanks!

**Comment by aurelienpierre** [comment]
@Mark-64 could you hold on styles changes for maybe 1-2 days ? I'm in the process of rewriting the `paint.c` file so the boilerplate Cairo code gets in a macro such that drawing functions become :
```
void dtgtk_cairo_paint_masks_uniform(cairo_t *cr, gint x, gint y, gint w, gint h, gint flags, void *data)
{
  PREAMBLE(0.95, 0, 0)

  cairo_arc(cr, 0.5, 0.5, 0.5, -M_PI, M_PI);
  cairo_stroke(cr);

  FINISH
}
```

with

```
#define PREAMBLE(scaling, x_offset, y_offset) {                                                        \
                            cairo_save(cr);                                                            \
                            cairo_set_line_cap(cr, CAIRO_LINE_CAP_ROUND);                              \
                            const float s = ((w < h) ? w : h) * scaling;                               \
                            cairo_translate(cr, x + (w / 2.0) - (s / 2.0), y + (h / 2.0) - (s / 2.0)); \
                            cairo_scale(cr, s, s);                                                     \
                            cairo_translate(cr, x_offset, y_offset);                                   \
                            cairo_matrix_t matrix;                                                     \
                            cairo_get_matrix(cr, &matrix);                                             \
                            cairo_set_line_width(cr, 1.618 / hypot(matrix.xx, matrix.yy)); }

#define FINISH { cairo_identity_matrix(cr); \
                 cairo_restore(cr); }
```
So, basically, all your tuning work will be achievable in `PREAMBLE(a, b, c)` (scaling factor, x offset and y offset).

**Comment by Mark-64** [comment]
@aurelienpierre Sorry, I didn't know you were working on this. Excellent idea, by the way.
Anyway I should have finished with icon tuning.

**Comment by Mark-64** [comment]
> 
> 
> I update hover effects on those buttons in my #5303 PR (see blending-tabs and modules-tabs line to remove not wanted margins seeing in hover effect and not apply border-radius. Could you check if on your system (and especially Hidpi) if it remains good with my tweaks?

Tested on Windows HiDPI and it looks good.

**Pull request merged**
