### PR TITLE
tags: fix darktable tags table initialization

### PR DESCRIPTION
**Pull request by phweyland**
as this table is now correctly initialized it can be used to complete the PR #9030 "speed up tag filter rule SQL query": dbe2aa2015ae76788f0b928cfa052be77df78aab

### CODE REVIEW

**Comment by ralfbrown** [comment]
I don't think this is sufficient to completely avoid problems.  When a "darktable|%" tag gets attached to an image, `memory.darktable_tags` is entirely erased and left that way until one of the existing lazy init calls is invoked by some other action.  Probably easiest to cause this by creating a new location in the maps module.

Moving the deletion a little further down inside `dt_tag_new` (after the "INSERT INTO data.tags") and then immediately calling `dt_set_darktable_tags` inside the same `if` may be sufficient in conjunction with the global init, in which case the lazy-init calls should be superfluous.

**Comment by phweyland** [comment]
I see. I'll fix this. Thanks.

**Comment by phweyland** [comment]
I hope I don't create any other issue. A bit tricky to test because there is always a darktable tag ...
But that seems to work for me. @ralfbrown your eye on this is welcome.

**Comment by ralfbrown** [comment]
Looks OK, and a much cleaner approach than clearing and rebuilding the table whenever a new darktable tag is added.  I won't be able to test this for a few hours, but it will be quite apparent if there's an error (I'm not expecting any problems) since my personal library somehow wound up with a couple of images that have no tags whatsoever.

**Comment by ralfbrown** [comment]
All good here, I wasn't able to trigger any obvious misbehavior.

**Comment by phweyland** [comment]
@ralfbrown a big thanks for testing !

**Review by TurboGit — APPROVED** [review]
Thanks !

**Pull request merged**
