### PR TITLE
Major french update from manu-p and minor fixes

### PR DESCRIPTION
**Pull request by Nilvus**
French update: major changes from @manu-p plus few minor updates.

When merged, #12206 should be closed.

### CODE REVIEW

**Comment by Nilvus** [comment]
@TurboGit: last commit update fr.po with latest UI updates translation from PR about segmentation based highlights recovery. I can't include darktable.pot update I made on my side. Seems that I'm not able to provide update for that file, so I let you update it.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by Nilvus** [comment]
@TurboGit: I just remember that 2nd commit of this PR should be for 4.2 (as related segmentation based feature is planned for 4.2) and not for 4.0.1? Could you change target of that merged commit?

**Comment by TurboGit** [comment]
Both are already merged into 4.0.1, not a big deal as the added strings won't break anything there.

**Pull request merged**
