### PR TITLE
Fix build with OpenEXR 3

### PR DESCRIPTION
**Pull request by antonio-rojas**
Try to find openexr 3 via the upstream cmake config first, and fall back to using our FindOpenEXR.cmake

### CODE REVIEW

**Comment by TurboGit** [comment]
Looks good to me but I'm no expert on CMake, @parafin can you check ? TIA.

**Comment by parafin** [comment]
I'm not sure why this is needed. Simple find_package doesn't work?

**Comment by antonio-rojas** [comment]
> I'm not sure why this is needed. Simple find_package doesn't work?

No. Simple find_package would pick up your FindOpenEXR.cmake which doesn't work with OpenEXR 3 since the libraries have been renamed. And rewriting it doesn't make much sense given that upstream already provides a perfectly working cmake config file.

**Comment by parafin** [comment]
Was cmake config file provided for older OpenEXR versions? Why 3.0 version if specified for CONFIG mode find_package? Honestly I would hide this logic inside FindOpenEXR.cmake instead of main CMakeLists.txt file.

**Comment by antonio-rojas** [comment]
> Why 3.0 version if specified for CONFIG mode find_package?

So as not to modify the current behavior for openexr 2.x. I am just contributing the downstream patch I'm using in case you find it useful - feel free to take it, leave it or modify it, I don't plan to work on it any further.

**Comment by parafin** [comment]
Then it’s up to you, @TurboGit, I suppose this patch works, it’s not how I would have done it, but I’m not going to work on it either.

**Comment by TurboGit** [comment]
Ok, I'll merge then.

**Review by TurboGit — APPROVED** [review]
Thanks !

**Pull request merged**
