### PR TITLE
po/db camera - DB table refactoring for better DB structure

### PR DESCRIPTION
**Pull request by TurboGit**
**BEWARE: This is doing a DB migration, do a backup if you test.**

Migrate database to use a makers/models/lens table.
    
This is needed to avoid duplicated strings in the DB and move the DB
more into a normal form.

EDIT: I have added a views on the  table v_images which displays the main information as plain text (that is with the lens, maker, model, cameras and folder, so referencing all the ids in images table). It also displays the datetime_taken as human readable value instead of a plain int64_t (number of nanosec since "0001-01-01 00:00:00".

EDIT: Final testing on my real DB, 64_311 images. The DB upgrade took 7 seconds.
As expected the size went down from 434_503_680 to 418_152_448 so about 15MB saved.

To me this is ready to go.

### CODE REVIEW

**Comment by AlicVB** [comment]
What would be great is to also store the "normalized" camera names (or whatever you want to call them). That would simplify and optimize a lot sorting, searching and image info code.

For searching (collection module), for example, what we are doing currently is : 
- get all different maker-model values present in the database.
- for each maker-model value, pass them to rawspeed (what I call normalize) and store the result in a glist
- for each item in the list, concatenate "normalized" maker and model value and compare it to the search text

But what we need to ensure is : 
- is rawspeed return susceptible to change ?
- we also use libraw or imagemagick for some files. Is that a problem ?
- once the database updated with this values, we need to ensure that all newly imported images will store the value at the beginning

How does that sound ?

**Comment by wpferguson** [comment]
This will break the Lua API.

Currently maker, model and lens are strings, writable from the Lua API in src/lua/image.c.  

While I've never updated maker or model, I have a script that corrects the lens data when lenses are misdetected.  If a lens is misdetected, you don't discover it until after the fact.  So in that case, incorrect data would be written to the lens table and the id of the entry stored in the image record.  Unfortunately, most (all?) of the times that lenses are misdetected, a valid lens string is substituted.  In order to fix the misdectection, you would have to create a new entry in the lens table, because the misdetected entry is actually a valid lens and might be used by other rectords.  Then, the records with the misdetection need to be updated to the correct lens record.

In order to do this from the Lua API I'd need functions to read and create makers, models, and lenses.  I don't think there should be functions to delete or update since that could be a real good way to shoot oneself in the foot.

**Comment by wpferguson** [comment]
I'll code up an example of how it currently works, and I'll start working on changesn to src/lua/image.c.  I'm at work right now, so it might be a few hours

**Comment by wpferguson** [comment]
Here's a script to show how it currently works.  The destructive part (changing the maker, model, and lens) is commented out, but you can uncomment it and run it.  You may have to restart darktable to see the changes (for me lens showed up immediately but I had to restart to see maker and model updated).  You can remove the image, then reimport it to restore the data.  Run it with -d lua as it prints to the log.

[changemml.zip](https://github.com/darktable-org/darktable/files/12611500/changemml.zip)

**Comment by wpferguson** [comment]
@TurboGit it seems I was mistaken.  I just tested the script against last nights commits and it seems to work.  I'll pull the updated commits and test again.

**Comment by wpferguson** [comment]
Tested against current set of commits and it works fine.  The Lua API appears to be fine. :smile:

Sorry for the noise (should have tested first, but sometimes you move too fast for me ;-)).

On the bright side, you now have a test script :-D

**Comment by TurboGit** [comment]
> Tested against current set of commits and it works fine. The Lua API appears to be fine. 😄

No problem, as I thought the mapping is in dt_image_t and there we still have the maker/model/lens.

> On the bright side, you now have a test script :-D

Sure :)

**Pull request merged**
