### PR TITLE
[5926] Icons for lighttable-modes

### PR DESCRIPTION
**Pull request by quovadit**
Icons to replace layout_combo for selecting lighttable-mode (see #5926)
icons-committed

### CODE REVIEW

**Comment by johnny-bit** [comment]
You also have to add definitions with comments in `paint.h` :)

**Comment by TurboGit** [comment]
Looks good, maybe the middle icon is a bit too small, at least smaller than the others. I would try to have the height of the X and Y box expanded a bit.

**Comment by AlicVB** [comment]
good work ! 
- I also find the third icon a little bit small.
- There's also the arrows in the last one. I would have put them in the corners, but in that case this will break alignment... maybe try to push them just a little bit aside ? or even remove them completely ? (that's just ideas, I can live with the current one too)

For my part of work, I'll try to do it once #7719 is sorted out...

**Comment by quovadit** [comment]
culling too small:
Of course I could scale culling_fixed to 2.0 instead of 1.4, so it would be the same size as culling_dynamic, but would not fit into the square icon-space anymore...

fullscreen:
I think arrows in the corners look strange, so here are 4 alternatives:
fullscreen-variants

**Comment by johnny-bit** [comment]
I personally would vote for either arrows in corners or the 4 arrows one.

**Comment by AlicVB** [comment]
culling : what about adding a little more height to the rectangles and make culling_dynamic rectangle same size (ie : smaller than now) ?
preview : I prefer n°1 and 2. I don't like 3 as screen are never square, and find the 2 others too detailed... maybe we can try n°4 without the center rectangle too...

**Comment by TurboGit** [comment]
I don't like this last proposal. Not readable to me

**Comment by quovadit** [comment]
thanks a lot for the continued feedback!
So here's the next iteration:
fullscreen-variants-2
(1+2 are the same, 3 was the old version, 4+5 are simplified)

**Comment by TurboGit** [comment]
I still prefer the first version posted here with the 3rd icon a bit bigger.

**Comment by AlicVB** [comment]
@TurboGit : to be sure we speak about the same things : the 2 last screenshots are different proposals for the preview icons only... iiuc @quovadit hasn't rework the culling icons for instance.

**Comment by TurboGit** [comment]
Ah yes sorry, I was reading from my phone, not easy to follow proper on a small screen.

**Comment by TurboGit** [comment]
> Of course I could scale culling_fixed to 2.0 instead of 1.4, so it would be the same size as culling_dynamic, but would not fit into the square icon-space anymore...

I was proposing to only resize the height of the X & Y box. To the icon is more 16:9, keep the width but rework the height a bit.

**Comment by TurboGit** [comment]
For the preview icon I would vote for the 4th or 5th so:
image

**Comment by quovadit** [comment]
culling is now 16:9, preview has 4 arrows:
icons-v4

**Comment by TurboGit** [comment]
This last proposal seems good to me. No more comment, each icon convey well the actual tool. I vote for it !

**Comment by Nilvus** [comment]
> This last proposal seems good to me. No more comment, each icon convey well the actual tool. I vote for it !

Me too, good work @quovadit and thanks for this improvement.

**Comment by quovadit** [comment]
@Nilvus : i did just the icons, @AlicVB will add the functionality

**Comment by Nilvus** [comment]
> @Nilvus : i did just the icons, @AlicVB will add the functionality

Ok, so I suppose add also tooltips and hover effect. Will wait so to test.

**Comment by AlicVB** [comment]
All good for me too. Thanks for your patience ;)
At that point, I propose that we merge it soon, so I can start my work with the right icons directly...

**Comment by TurboGit** [comment]
Merged then :)

**Comment by TurboGit** [comment]
@quovadit : Thanks for the design work !

**Pull request merged**
