### PR TITLE
filmicrgb: disable color picker when switching notebook pages

### LINKED ISSUE #10984: filmic: disable pickers when changing tab
When using pickers on the scene tab, the picker remains active until deselected or until another slider is changed. Pickers should also be deactivated when changing to another tab.

### PR DESCRIPTION
**Pull request by elstoc**
Resolves #10984

### CODE REVIEW

**Comment by TurboGit** [comment]
Should we really do that? I don't find this behavior irritating, I can switch tab so see other settings and be back on the scene tab.

**Comment by elstoc** [comment]
> Should we really do that? I don't find this behavior irritating

I'm trying to remember what I was doing where it irritated me but it was something that needed on-screen interaction, perhaps the snapshot or global colour picker - I'd moved to another tab but not changed anything and I had to tab back to turn it off. I would have encountered it a couple of times to have been bothered to raise the bug.

If you don't think it's worth changing though, I'm ok with that. It was a minor irritation.

**Comment by TurboGit** [comment]
I've been thinking a bit more to this and I don't think we should do that. We can revisit that if there is a scenario where it is very annoying, but at this stage the current behavior is about right to me.

**Comment by elstoc** [comment]
Ok no problem

**Pull request closed without merging**
