### PR TITLE
Color picker fixes. Fixes #11163. Fixes #11164

### LINKED ISSUE #11163: darktable does not connect to my Sony A7 camera
gphoto does recognize my camera, I can even shoot with the --capture-tethered command, but darktabkle doesn't work.
attached details
env LANG=C gphoto2 --auto-detect
Model                          Port                                            
----------------------------------------------------------
Sony Alpha-A7 (Control)        usb:001,007 

env LANG=C gphoto2 --port usb: --abilities
Abilities for camera             : Sony Alpha-A7 (Control)                     
Serial port support              : no
USB support                      : yes
Capture choices                  :
                                 : Image
                                 : Trigger Capture
Configuration support            : yes
Delete selected files on camera  : yes
Delete all files on camera       : no
File preview (thumbnail) support : yes
File upload support              : yes

camctl.log
1,002685 [camera_control] creating new context 0x562fa45fc700
1,016947 [camera_control] loaded 2498 camera drivers.
3,586050 [camera_control] loaded 37 port drivers.
3,600534 [camera_control] 0 cameras connected
6,414672 [camera_control] loaded 38 port drivers.
6,425989 [camera_control] 1 cameras connected
6,426022 [camera_control] found new Sony Alpha-A7 (Control) on port usb:001,013
40,061223 [camera_control] destroy darktable camcontrol

### LINKED ISSUE #11164: Nonsensical casts in iop process functions
Not really a bug report, more an observation of a (possibly) bad pattern that can be observed in all image processing modules:

In all image processing modules we find in the `process` function:

```C
  const float *const restrict in = DT_IS_ALIGNED((float*)ivoid);
  float *const restrict out = DT_IS_ALIGNED((float*)ovoid);
```

where `DT_IS_ALIGNED` is defined as 

```C
#define DT_IS_ALIGNED(x) __builtin_assume_aligned(x, 64)
```

with

```
void * __builtin_assume_aligned (const void *exp, size_t align, ...)
```

Thus,
```C
  const float *const restrict in = DT_IS_ALIGNED((float*)ivoid);
```
casts the `void` pointer `ivoid` explicitly to a pointer to `float`, which is then implicitly converted to a pointer to `void` by passing it to `__builtin_assume_aligned`, which returns a pointer to `void`, which eventually is converted to a pointer to `float`.

I wonder, shouldn't this be just

```C
  const float *const restrict in = DT_IS_ALIGNED(ivoid);
  float *const restrict out = DT_IS_ALIGNED(ovoid);
```
(or
```C
  const float *const restrict in = (const float*)DT_IS_ALIGNED(ivoid);
  float *const restrict out = (float*)DT_IS_ALIGNED(ovoid);
```
when one wants to be verbose)?

### PR DESCRIPTION
**Pull request by LebedevRI**
Aftermath of preview pipe going mosaiced.

Note that i have no ability to test opencl changes.

Also, no clue if invert iop does the right thing for 4bayer mosaic.

### CODE REVIEW

**Comment by upegelow** [comment]
I tested with OpenCL using an NVIDIA device and an AMD device, respectively. No problems with the color picker so far.

The "manual" mode in white balance still does not work with OpenCL.

**Comment by LebedevRI** [comment]
There is some deadlock, looks like in last commit in src/iop/invert.c changes
Trying to figure it out...

> The "manual" mode in white balance still does not work with OpenCL.
Not sure what that is about, but since you used word "still", i'm guessing it is not a regression, so i can skip it.

**Comment by upegelow** [comment]
> Not sure what that is about, but since you used word "still", i'm guessing it is not a regression, so i can skip it.
It's certainly a regression. Just checked and it works in the 2.0.x branch. Will need to bisect to find the point where it got lost.

**Comment by LebedevRI** [comment]
> > Not sure what that is about, but since you used word "still", i'm guessing it is not a regression, so i can skip it.

> It's certainly a regression. Just checked and it works in the 2.0.x branch. Will need to bisect to find the point where it got lost.

What "manual" mode in white balance do you mean?

**Comment by upegelow** [comment]
It's "spot" mode in preset. Special case here is: I am running also the preview pipe on GPU (a different one than the full pipe). I will try to bisect tomorrow.

**Comment by LebedevRI** [comment]
> It's "spot" mode in preset. Special case here is: I am running also the preview pipe on GPU (a different one than the full pipe). I will try to bisect tomorrow.

Ah, ok.
Then just read `pixelpipe_picker_cl()` in `src/develop/pixelpipe_hb.c` and make sure that it makes sense.
Indeed, i can not test opencl things...
https://github.com/darktable-org/darktable/pull/1279/files#diff-8ea5aadb7471f5d0f720787aeea12288R496

The cpu part does work.

**Comment by LebedevRI** [comment]
@upegelow 
(hint: spot whitebalance and spot invert is broken in git master since the un-demosaicing of preview pipe. this commit fixes that. but i guess i missed something in opencl part)

**Comment by upegelow** [comment]
@LebedevRI 
OK, I see. Obviously the OpenCL code needs to be adapted according to the CPU code. I'll take care.

BTW: a small naming issue: IMHO we should rename pixelpipe_picker_helper() as its name obfuscates its function. The "helper" suffix should better be reserved to the functions in color_picker.c

**Comment by LebedevRI** [comment]
Functions in `color_picker.c` should be static, so they will not clutter libdarktable namespace.

**Pull request merged**
