### PR TITLE
filter (text & colors label): save their state between dt sessions

### LINKED ISSUE #11299: colorlabel and search filters should saved their state
**Is your feature request related to a problem? Please describe.**
The state of the new filters in the top bar are not saved across sessions : 
- click on some color labels in the top bar
- close dt
- restart dt

=> the colors icons are not toggle on and the list of images is not filtered anymore
Same apply for the "multisearch" entry

**Describe the solution you'd like**
The filtering state should be saved and restored, like what is done for rating

@phweyland : sorry to give you more work ;)

### PR DESCRIPTION
**Pull request by phweyland**
fixes #11299

Still a glitch . The text filter doesn't save the character `"` used to avoid the automatic wildcard `%`
@quovadit, any idea to solve this ?
Another option would not to save the text filter ?

### CODE REVIEW

**Comment by TurboGit** [comment]
> Still a glitch . The text filter doesn't save the character `"` used to avoid the automatic wildcard `%`

You probably want to encode it, maybe using URL encoding routine.

**Comment by TurboGit** [comment]
Or `g_base64_encode()` & `g_base64_decode()` maybe.

**Comment by phweyland** [comment]
> Or `g_base64_encode()` & `g_base64_decode()` maybe.

I'll make a try with this. Thanks !

**Comment by phweyland** [comment]
Thanks, learnt something about g_base64...
No need to encode, just to decode the text filter to display the corresponding entry.
Hoping this is good now.

**Review by TurboGit — CHANGES_REQUESTED** [review]
The color label is not saved between session on my side.

**Comment by phweyland** [comment]
> The color label is not saved between session on my side.

I can reproduce this on an empty db. However:
dt_conf_set_int: -2147483646 80000002, which is correct and I can see the decimal value in darktablerc
dt_conf_get_int: -2147483648 80000000, when dt is restarted.
Investigating.

**Review by TurboGit — CHANGES_REQUESTED** [review]
This is still not working on my side. Since we do not need the calculator here, but we just want to store and get a set of color flags I propose that the pref `plugins/collection/color_filter` be a string and encode the data in this string avoid the int causing problem.

The encoding could be for each color in a given order use `.` `x` `o` to mean unset, rejected, selected. So we will end up for example with `.o.x..` which will mean:

- red : not selected
- yellow: selected
- green : not selected
- blue : rejected
- purple : not selected
- grey : not selected

That's only a proposal of course, maybe you'll find something easier to handle.

**Comment by phweyland** [comment]
> This is still not working on my side.

Did you start from a fresh db or removed plugins/xxx/colors_filter from darktablerc ?

**Comment by phweyland** [comment]
> Don't you think still that this is a bit fragile and that my proposal will make this work even in future implementation (adding filters, changing the values... who knows!)

I won't say that, currently it's the calculator which fails. :smile: 
The mask is also used in collection and in the UI. It is very handy for that. 
About the colors number extension, I agree, we can keep more room (considering the fragile calculator):

- 0x40000000 for the operator (instead of 0x800000)
- 0x1FFF8000 for exclusion mask and 14 colors (instead of 0x1F00 and 5 colors)
- 0x00003FFF for inclusion mask and 14 colors (instead of 0x1F and 5 colors)

Do you want me to preserve the max of room ?

**Comment by phweyland** [comment]
Seen the @ralfbrown input, the usage of conf_int is really fragile for a large mask.
I'll save the hexadecimal mask as a string.

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Pull request merged**
