### PR TITLE
Draft: Fix #17178 JzCzhz color picker

### LINKED ISSUE #17178: Jz masks
### Describe the bug

In some modules (perhaps those not native to the scene-referred workflow?) the Jz picker picks outlandish values, which actually don't select anything in the image.

### Steps to reproduce

1. Get the files from https://tech.kovacs-telekes.org/files/2024-07-21-darktable-Jz-masks/
2. Activate the _exposure_ instance called _no-op, masking only_.
3. Select parametric masking based on the Jz channel, and pick an area from the flower. You'll get values like this, and the mask will cover the flower:
  exposure-Jz-mask
4. Now enable the _contrast equalizer_ instance. Confirm that it's set to scene-referred working space.
5. Try to repeat picking on the Jz channel. I got this:
  contrastEq-Jzg-picking
6. The resulting mask does not actually cover anything in the image:
  contrastEq-Jzg-mask-display
7. Manually copying the values from the no-op _exposure_ instance selects the expected part of the image:
  contrastEq-Jzg-with-values-from-exposure

OpenCL on/off does not influence the behaviour.

### Expected behavior

Jz mask should work for all modules

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you obtain darktable from?

self compiled

### darktable version

4.9.0+72~g517889efe0

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 24.04

### Describe your system?

_No response_

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by kofa73**

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
1. Looking at the right spot :-)
2. It would be better to have the impossible conversions reported in a readable form
```
// fallback, but this shouldn't happen
      dt_print(DT_DEBUG_ALWAYS,
               "[colorpicker] unknown colorspace conversion from %s to %s\n",
               dt_iop_colorspace_to_name(image_cst), dt_iop_colorspace_to_name(picker_cst));
      _color_picker_work_4ch(source, roi, box, pick, NULL, _color_picker_rgb_or_lab, 100);
```
you will notice while playing with the pickers in the blending gui that there are more conversions requiring support.

3. Your check `(effective_cst == IOP_CS_JZCZHZ && picker_cst == IOP_CS_LAB)` seems wrong to me. I think we must test for all cases `effective_cst == IOP_CS_LAB` and convert according to the chosen `picker_cst`. 
It would be correct and also might be the easiest way to convert IOP_CS_LAB data to IOP_CS_RGB exactly as we do for the pixelpipe (see pixelpipe_hb.c around line 1130) and use those converted data for processing.

**Comment by kofa73** [comment]
I can start working on it on 1 August, but just a little bit every day (I'm supposed to be on vacation then). I not done by the 7th, I won't be able to touch it for a week (will be away from my computer).

**Comment by jenshannoschwalm** [comment]
This is something new for 5.0 so no reason to make haste

**Comment by kofa73** [comment]
@jenshannoschwalm I only got some time to sit down and have another look now.

With your suggested formatted debug message, I get:
`unknown colorspace conversion from IOP_CS_LAB to IOP_CS_JZCZHZ`, and you are right, I mixed them up.

With that fix, I do get a usable mask:
image

I don't yet get how to implement your suggestion regarding RGB, but I'll check more later.

Regarding comments like
```c
// FIXME: the mean calculation of hue isn't always right, use circular mean calc instead?
```

Wouldn't it be better to convert the whole selected area into linear RGB, calculate the mean there, and convert that to the picker space?

**Comment by jenshannoschwalm** [comment]
The problem here is the "range" calculation around hue zero. So if the picker finds data around red the range should be marked correctly. 

You will find code in the area picker representation in color equalizer.

**Comment by jenshannoschwalm** [comment]
Are you still working on this or would you want me to take over?

**Comment by kofa73** [comment]
I have not touched it in a while. I hope to get back to it. Give me two weeks, and if still nothing, please take over.

**Comment by jenshannoschwalm** [comment]
I think i may have put you on a not-so-good track. 

For the RGB it's probably fine to convert each pixel (as you did for the Jz stuff) via dt_XYZ_to_Rec709_D50() after dt_Lab_to_XYZ().

**Comment by kofa73** [comment]
Added, but source = Lab conversions seem broken:
_local_contrast_ with _scene referred_ blending space:

'g' channel_
This looks reasonable:
image
But this does not:
image

'R' channel:
image

'Jz':
image
image

'Cz':
image

'hz':
image
but
image

Here is the colour wheel used for testing:
colour_wheel

**Comment by kofa73** [comment]
Hi @jenshannoschwalm , not urgent, but if you could give me a hint where to continue investigating the weird selection issues I posted above, I'd much appreciate it. I'll have some time during the weekend. If you have no idea / no time, that's also OK.
I wondered about the Rec709 that you mentioned -- how come always Rec709 has to be used, not e.g. the working space?

**Comment by jenshannoschwalm** [comment]
@kofa73 i was deeply in gaussian code, will likely have a look tonight.

**Comment by jenshannoschwalm** [comment]
Still not sure about this. I didn't check all involved code but the blending part should get the **converted** colorspace. That has to be checked carefully, `-d pipe` should tell you about blending and colorspace.

**Comment by kofa73** [comment]
Unfortunately, I'm stuck. I got this from `-d pipe`:
```text
   538.8808 pipe cache check              [preview]                               12 lines (important=4, used=9). Freed 0MB. Using using 28MB, limit=0MB
   538.8808 pipe starting             CPU [preview]                               (   0/   0)  450x 450 scale=1.0000 --> (   0/   0)  450x 450 scale=1.0000 ID=6437
   538.8809 pipe data: full               [preview]                               (   0/   0)  450x 450 scale=1.0000 --> (   0/   0)  450x 450 scale=1.0000 
   538.8809 process                   CPU [preview]        colorin                (   0/   0)  450x 450 scale=1.0000 --> (   0/   0)  450x 450 scale=1.0000   9 IOP_CS_RGB -> IOP_CS_LAB 6MB
   538.8933 process                   CPU [preview]        bilat                  (   0/   0)  450x 450 scale=1.0000 --> (   0/   0)  450x 450 scale=1.0000  67 IOP_CS_LAB 28MB
   538.9527 pixelpipe picker          CPU [preview]        bilat                  (   0/   0)  450x 450 scale=1.0000 IOP_CS_LAB -> IOP_CS_RGB, box 382/172 -- 406/198
   538.9527 [colorpicker] @@@kofa DEBUG colorspace conversion from IOP_CS_LAB to IOP_CS_RGB
   538.9531 pixelpipe picker          CPU [preview]        bilat                  (   0/   0)  450x 450 scale=1.0000 IOP_CS_LAB -> IOP_CS_RGB, box 382/172 -- 406/198
   538.9531 [colorpicker] @@@kofa DEBUG colorspace conversion from IOP_CS_LAB to IOP_CS_RGB
   538.9583 blend with form           CPU [preview]        bilat                  (   0/   0)  450x 450 scale=1.0000 --> (   0/   0)  450x 450 scale=1.0000 IOP_CS_RGB, BLEND_CS_RGB_SCENE, no form
   538.9602 importance hints          CPU [preview]        bilat                  (   0/   0)  450x 450 scale=1.0000 input_hint focus 
   538.9603 transform colorspace      CPU [preview]        colorout               (   0/   0)  450x 450 scale=1.0000 IOP_CS_RGB -> IOP_CS_LAB `linear Rec2020 RGB'
   538.9630 process                   CPU [preview]        colorout               (   0/   0)  450x 450 scale=1.0000 --> (   0/   0)  450x 450 scale=1.0000  82 IOP_CS_LAB -> IOP_CS_RGB 6MB
   538.9711 process                   CPU [preview]        gamma                  (   0/   0)  450x 450 scale=1.0000 --> (   0/   0)  450x 450 scale=1.0000  90 IOP_CS_RGB 6MB
   538.9725 pixelpipe pick samples                         gamma                  (   0/   0)  450x 450 scale=1.0000 box 382/172 -- 406/198
   538.9725 [colorpicker] @@@kofa DEBUG colorspace conversion from IOP_CS_RGB to IOP_CS_RGB
   538.9763 dt_ioppr_transform_image_colorspace_rgb_lcms2 `system display profile' -> `linear Rec709 RGB' [primary picker]
   538.9857 dt_ioppr_transform_image_colorspace_rgb_lcms2 `system display profile' -> `linear Rec709 RGB' [final histogram]
   538.9934 cache report                  [preview]                               12 lines (important=5, used=9, invalid=5). Using 28MB, limit=0MB. Hits/run=0.36. Hits/test=0.045
   538.9934 pipe finished             CPU [preview]                               (   0/   0)  450x 450 scale=1.0000 --> (   0/   0)  450x 450 scale=1.0000 ID=6437

   539.1489 blend with form           CPU [full]           bilat                  (   0/   0) 1902x1902 scale=1.8574 --> (   0/   0) 1902x1902 scale=1.8574 IOP_CS_RGB, BLEND_CS_RGB_SCENE, no form
   539.1651 importance hints          CPU [full]           bilat                  (   0/   0) 1902x1902 scale=1.8574 input_hint focus 
   539.1651 transform colorspace      CPU [full]           colorout               (   0/   0) 1902x1902 scale=1.8574 IOP_CS_RGB -> IOP_CS_LAB `linear Rec2020 RGB'
   539.1901 process                   CPU [full]           colorout               (   0/   0) 1902x1902 scale=1.8574 --> (   0/   0) 1902x1902 scale=1.8574  82 IOP_CS_LAB -> IOP_CS_RGB 116MB
   539.2517 process                   CPU [full]           gamma                  (   0/   0) 1902x1902 scale=1.8574 --> (   0/   0) 1902x1902 scale=1.8574  90 IOP_CS_RGB 116MB
   539.2613 [dt_image_update_final_size] for ID=6437, updated to 1024x1024
   539.2628 cache report                  [full]                                  64 lines (important=11, used=7, invalid=0). Using 497MB, limit=1003MB. Hits/run=0.87. Hits/test=0.198
   539.2628 pipe finished             CPU [full]                                  (   0/   0) 1902x1902 scale=1.8574 --> (   0/   0) 1902x1902 scale=1.8574 ID=6437
```
In the debugger, I see Rec2020, so maybe the matrices from that profile should be used instead of Rec709?
image

But even if I set the working space to Rec709, the picker readings are off (they don't always select the region indicated by the relection rectangle).

**Comment by jenshannoschwalm** [comment]
Hi @kofa - i will take a week or two off-darktable from now on. Some of this i mentioned before but i don't remember if this is valid (just from memory when i did the CE picker, you might find relevant code while searching for "picker" there.)
Leaving you out in the cold a bit ...

**Comment by jenshannoschwalm** [comment]
Hmm, just had a last look ... 

```
    38,5960 transform colorspace      CL0 [full]           atrous                 (   0/   0)  976x 976 scale=0,9531 IOP_CS_RGB -> IOP_CS_LAB `Linear Rec709 RGB'
    38,5983 process                   CL0 [full]           atrous                 (   0/   0)  976x 976 scale=0,9531 --> (   0/   0)  976x 976 scale=0,9531  42 IOP_CS_LAB 152,4MB
    38,6127 blend with form           CL0 [full]           atrous                 (   0/   0)  976x 976 scale=0,9531 --> (   0/   0)  976x 976 scale=0,9531 IOP_CS_RGB, BLEND_CS_RGB_SCENE, no form
```

In the pipe the data are already converted to IOP_CS_RGB - or they should be - if the module does processing in Lab space.
In short - before talking - i/we would have to analyse in depth what could go wrong here.

**Comment by jenshannoschwalm** [comment]
@kofa i had another look right now at your code and how it works in the current code.

1. Whatever we do exactly while converting lab->rgb is debatable to me. You mentioned it above - we might need to correct the data presented to the picker exactly as we convert the data for blending. 
2. About your not correct looking mask - it looks splitted. That should and can be fixed by adding ` pick[3] = pick[0] < 0.5f ? pick[0] + 0.5f : pick[0] - 0.5f;` also to the `_color_picker_Lab_2_rgb()`

Please test :-)

**Comment by kofa73** [comment]
Oh, I missed that, thanks! I'll try it tomorrow.

**Comment by jenshannoschwalm** [comment]
One more: see `rgb_to_JzCzhz()` and how it handles the current work profile. I think we must do this alike ...

**Comment by kofa73** [comment]
> 2\. About your not correct looking mask - it looks splitted. That should and can be fixed by adding **` pick[3] = pick[0] < 0.5f ? pick[0] + 0.5f : pick[0] - 0.5f;` also to the `_color_picker_Lab_2_rgb()`**

Hanno, I don't get this. Yesterday evening I thought I missed something, but for the Lab -> RGB conversion wouldn't this mean checking the R coordinate (pick[0]), and mapping [0 .. 0.5) -> [0.5, 1), while mapping [0.5 .. +infinity) to [0 .. +infinity) (this transformation is no longer 1:1, as 0.4 -> 0.9, but also 1.4 -> 0.9), then storing it in pick[3] which is normally used for hue? There the swapping of [0 .. 0.5) with [0.5 .. 1) makes sense (I haven't read the code to figure out why that's needed), but for the singled-out red channel, not bounded to [0, 1)?

**Comment by jenshannoschwalm** [comment]
I'd have to recheck but i thought that would remove the "split-range-issue". At least it seemed to work here.

**Comment by kofa73** [comment]
> it seemed to work here.

Then maybe I misunderstood. This makes no sense to me (singling out R, and swapping the value ranges):
```c
static inline void _color_picker_Lab_2_rgb(dt_aligned_pixel_t acc,
                                     dt_aligned_pixel_t low,
                                     dt_aligned_pixel_t high,
                                     const float *const pixels,
                                     const size_t width,
                                     const void *const data)
{
  for(size_t i = 0; i < width; i += 4)
  {
    dt_aligned_pixel_t pick;
    dt_Lab_2_Rec709_D50(pixels + i, pick);
    pick[3] = pick[0] < 0.5f ? pick[0] + 0.5f : pick[0] - 0.5f;    
    _update_stats_4ch(acc, low, high, pick);
  }
}
```

**Comment by jenshannoschwalm** [comment]
Hold on, i think i found an easier way. We can take the already transformed data for blending without additional conversions.

**Comment by kofa73** [comment]
Fixed by the other PR, closing. Thanks!

**Pull request closed without merging**
