### PR TITLE
add sony alpha 7R2 basecurve

### PR DESCRIPTION
**Pull request by amueller**
Please let me know if this is the right format and if there's a convention for the camera names.
I figure the first entry is the human readable name and the third the machine readable one?

This is much punchier than the "Sony Alpha-like" and much closer to the JPEGs produced by the camera.

### CODE REVIEW

**Comment by amueller** [comment]
I just realized that this is the curve applied for "vivid". The standard one is somewhat less contrasty. I imagine you would want to add the standard one instead?

**Comment by LebedevRI** [comment]
@amueller
Thank you for your contribution!
However, we have no means of checking the validity of the these custom base/tone curves, and we do not think it's a good idea to merge them as is, because IIRC we have already seen broken curves.
Once we do, we will announce it.

**Comment by amueller** [comment]
Thanks. Is there a way I could provide the data that generated the curve?

**Comment by choller** [comment]
I know this PR is quite old but I am glad I found it. The neutral base curve in the second comment gives me significantly better results on my 7R2 compared to the "Sony Alpha-like", almost equal to the JPG directly produced by the camera. I am glad I found this and so might be others that are looking for a better base curve.

**Comment by choller** [comment]
@LebedevRI Has there been any update to the base curves for Sony Alpha in darktable since this PR?

The original poster is absolutely right, the "Sony Alpha-like" base curve in darktable is off at least for the A7R models. Only using the neutral base curve from this PR, I was able to develop a RAW that looks entirely like the JPEG produced in-camera.

I used to shoot with the Sony A7R2, now I switched to the A7R3 and this base curve still works out just fine. I highly suggest that we try to correct this and I'd be glad to provide any kind of test RAWs/JPEGs you might need to confirm this.

**Comment by LebedevRI** [comment]
> @LebedevRI Has there been any update to the base curves for Sony Alpha in darktable since this PR?

I don't know.
Nowadays i only handle basic camera support here and gave up on everything else.

**Comment by choller** [comment]
@LebedevRI can you suggest/tag someone else who might be responsible for this area then?

Thanks!

**Comment by amueller** [comment]
Also happy to share the data or capture any new data or anything like that.

**Comment by choller** [comment]
@amueller I just recently upgraded from the 7RM2 to 7RM3 and although that is the same sensor, it seems that Sony has very slightly altered the in-camera base curve (I think they mentioned something about wanting to prefer skin tone colors more like Canon does).

Can you provide me with the exact steps to get the profiles out of my new camera? Then we can provide them in addition to yours. Thanks!

**Comment by choller** [comment]
@TurboGit Salue Pascal. Can you help us escalate the matter we are trying to address in this PR or assign us someone we can work with to get the correct Sony base curves into DT? I just recently upgraded to DT3 and while a lot of things are really great, it still doesn't (even nearly) have the right Sony base curves builtin. I can send you comparison pictures if you want to see how it looks here for my 7RM3 if you wish. Imho DT is currently unusable for the high-end Sony cameras without manually adding/defining the correct curves and I would like to help fix that. Thanks!

**Comment by TurboGit** [comment]
Can you recap the status here?

Do you want a basecurve or tonecurve ?

What is the status of the tonecurve proposed above ? https://github.com/darktable-org/darktable/pull/1490#issuecomment-301653371

Anyway, this is old so we really need a status update and see at least someone ready to test/propose a proper curve for this camera.

**Comment by TurboGit** [comment]
Reopened, waiting for feedback and see if we can have this moving or not (and I'll close again).

**Comment by amueller** [comment]
@TurboGit you mean you need someone familiar with the project, not a new contributor, right?

From my end the status was: I was using a 7R2, the in-camera jpeg was very different from the alpha-like, and I created a basecurve that I've been using since. I thought it might be useful as it's a very popular camera and so I sent a PR.

I think I followed this tutorial:
https://www.darktable.org/2013/10/about-basecurves/

I made a tone curve and a base curve but I have only been using the base curve. The alpha-like is very washed-out and gray compared to this one.

Given how long ago this was, I don't think I can find the images any more but it's probably pretty easy to reproduce.

**Comment by TurboGit** [comment]
@amueller : I'm familiar with the project, but that was not my question.

I need a status update because things are not clear. You are talking about a basecurve, fine bu the PR commit is for a tonecurve. The basecurve is "described" into the following comment https://github.com/darktable-org/darktable/pull/1490#issuecomment-301653371. Is that the one you are using ? Can you double check ? I don't have this camera, so I need at least someone with the camera doing so testing and asserting that this "old" PR is still valid with today darktable.

If you reply yes. Fine, then could you please create a PR for basecurve.c ?

See src/iop/basecurve.c on how this is integrated.

That being said we do not favor basecure those days and prefer either a tonecurve or better yet, nothing and use the FilmicRGB module. But I don't want to impose this to everyone, so if you propose a basecure and your assert that it gives good results I'll merge.

Something nice you be do post here a jpeg with about without the basecure.

Hope this is clearer.

**Comment by choller** [comment]
I did not have time yet to the procedure outlined in the blog post that @amueller linked, but here are some example JPEGs (camera vs. developed sonylike-basecurve vs. developed amueller-basecurve):

ILCE-7RM2 Camera JPEG:

ILCE-7RM2-Camera

ILCE-7RM2 RAW with default Sony-like base curve from DT2:

ICLE-7RM2-RAW-sonylike-basecurve

ILCE-7RM2 RAW with amueller neutral base curve from comment 2:

ILCE-7RM2-RAW-amueller-basecurve

ILCE-7RM3 Camera JPEG:

ICLE-7RM3-Camera

ILCE-7RM3 RAW with default Sony-like base curve from DT2:

ICLE-7RM3-RAW-sonylike-basecurve

ILCE-7RM3 RAW with amueller neutral base curve from comment 2:

ILCE-7RM3-RAW-amueller-basecurve

I've been using the base curve mentioned in the second comment of this PR for all my pictures on the ILCE-7RM2 and also now for the ILCE-7RM3. Although these are just example JPEGs, I think this illustrates pretty well that the Sonylike base curve in DT has a somewhat "dull" look and isn't close to what the Camera JPEG is. And I would very much like to help make Darktable a better experience for Sony pro-gear users.

If a tone curve or FilmicRGB preset is preferred, I will be glad to help with that. I don't have extensive knowledge on how to create these, but I'll be happy to try out some instructions. Unfortunately, I sold my ILCE-7RM2 and only have the ILCE-7RM3 now, but the sensor is the same and the only difference seems to be that Sony slightly adjusted it's color science to be more portrait friendly. So I assume we could base a 7R basecurve for both models on the ILCE-7RM3. Maybe someone who has the 7RM4 (which has a newer sensor) can also compare the results to their camera.

**Comment by TurboGit** [comment]
@choller : Indeed the tuned basecure is looking better. 

The tonecurve is in this PR's commit. Have you tested it? If it is as good as the basecurve we can just merge this PR.

For FilmicRGB there is nothing to do, and that's the point of Aurélien work. Providing a module that can be use to get good results for any camera & model.

**Comment by amueller** [comment]
I don't think you should hit merge as the tone curve was the 'vivid' not the 'neutral' setting. Sorry I was busy with some stuff. I can send a PR for the base curve.

**Comment by TurboGit** [comment]
Closing at this stage. You can create a new PR if needed.

**Pull request closed without merging**
