### PR TITLE
Update french manual

### PR DESCRIPTION
**Pull request by Nilvus**
Here is the last update of french manual, adding translation of last manual PR..

### CODE REVIEW

**Comment by TurboGit** [comment]
Can you double check your preference when editing this file?

All the references have now a full pathname:

```
-#: ../build/doc/usermanual/po/darktable-usermanual_profiled.xml:290(para)
+#: /home/nico/Projets/darktable/build/doc/usermanual/po/darktable-usermanual_profiled.xml:290(para)
```

**Comment by Nilvus** [comment]
Tanks, and not the first time I forgot to change that. Poedit change to full pathname automatically. I will update it now.

**Comment by TurboGit** [comment]
Strange, poedit does not do that for me on GUI translation file.

**Comment by TurboGit** [comment]
Thanks, will squash & merge now.

**Comment by Nilvus** [comment]
> Strange, poedit does not do that for me on GUI translation file.

I don't why it change that pathname. I've searched on the software and didn't find any options.

**Pull request merged**
