### PR TITLE
imageio/rawspeed: always read additional exif tags

### LINKED ISSUE #12804: Improved user experience when images require exif metadata refreshing.
### Preamble
Features implemented in #10289 and #12714 relies on additional exif metadata not stored inside the db. Inside the db, when on image import additional required exif tags are detected, a flag `DT_IMAGE_HAS_ADDITIONAL_DNG_TAGS` is set. When such flag is set on image open (currently only in `imageio_rawspeed.c`) additional exif tags are read from the file (`dt_exif_img_check_additional_tags(img, filename);`).
So the above PRs reused an implementation used only for the DNG user crop but now expanded also to images that aren't dng (so also the flag name should be changed for consistency).

### Current state 
This means that if a user already imported images with a darktable version without these PRs merged the flag will be false and that features will not be available until it refresh the images with the "refresh exif metadata" button.
Additionally, this isn't something required only for darktable 4.2 but if new features that require new exif tags will be implemented in future, the refresh should be required again for images that until that point didn't required new exif tags.

**SIDE NOTE**: Additionally this "refresh exif metadata" could have a negative effect since it could also reset the "star rating" if user haven't explicitly flagged in the "import module" the `ignore EXIF rating` option (by default not visible since it's in the "parameters" sections closed by default) (perhaps this is another issue)

So this could cause some bad user experience and issues for users since it's not clear why these new features reported in the release notes doesn't work or why they work only for newly imported images.

### Proposed solution

I see two options:
1. Only document this in the manual/release notes and perhaps somewhere in the gui. But this will always require user interaction and a full library exif metadata refresh (and probably issues like the above side note).
2. Always call `dt_exif_img_check_additional_tags(img, filename);` in `imageio_rawspeed.c` regardless of the DT_IMAGE_HAS_ADDITIONAL_DNG_TAGS. This means that the image will be opened two times (one by rawspeed and one by exiv2 library) but not read two times since exiv2 will seek and only read the exif data. So I'm not sure if this will have a performance impact and how much.

Personally I'm totally in favor of option **2** (if the performance penalty will be negligible).

cc @paolodepetrillo

### PR DESCRIPTION
**Pull request by sgotti**
* Rename `DT_IMAGE_HAS_ADDITIONAL_DNG_TAGS` to `DT_IMAGE_HAS_ADDITIONAL_EXIF_TAGS` (cosmetic change)

* Always read additional exif tags instead of relying on the img flag `DT_IMAGE_HAS_ADDITIONAL_EXIF_TAGS`.

@TurboGit With this change there's no other code that has logic based on `DT_IMAGE_HAS_ADDITIONAL_EXIF_TAGS`.
I kept the flag anyway since removing will require many changes if we want to reuse this bit for other purposes.

Fixes #12804 

On my system (that is quite fast) I don't see any visible performance penalty also with images stored on my NAS on my local network.

I tried to collect some timing data on the call to method `dt_exif_img_check_additional_tags` and `dt_imageio_open_rawspeed ` (that also contains the time used by `dt_exif_img_check_additional_tags`), cleaning the os caches before opening them:

### local SSD

```
dt_exif_img_check_additional_tags took 0.015 secs (0.001 CPU)
dt_imageio_open_rawspeed took 0.066 secs (0.021 CPU)
```

```
dt_exif_img_check_additional_tags took 0.014 secs (0.000 CPU)
dt_imageio_open_rawspeed took 0.084 secs (0.044 CPU)
```

### NAS

```
dt_exif_img_check_additional_tags took 0.011 secs (0.000 CPU)
dt_imageio_open_rawspeed took 0.203 secs (1.039 CPU)
```

```
dt_exif_img_check_additional_tags took 0.012 secs (0.005 CPU)
dt_imageio_open_rawspeed took 0.184 secs (0.927 CPU)
```

looks like `dt_exif_img_check_additional_tags` isn't i/o bound (probably due to the fact that the exif part is already being read by rawspeed and so is in os buffer cache).

`dt_exif_img_check_additional_tags` has a fixed contribution to the total time used by `dt_imageio_open_rawspeed`

### CODE REVIEW

**Comment by TurboGit** [comment]
Sounds a good move to me, @kmilos you probably want to cast a vote on this. TIA.

**Comment by kmilos** [comment]
All I can say is that there is in fact [overhead in opening and reading](https://github.com/darktable-org/darktable/blob/17c8d54f07a8ad6a5ce82d66ac94530be71082ec/src/common/exif.cc#L824-L827) the file.

**Comment by TurboGit** [comment]
> All I can say is that there is in fact [overhead in opening and reading](https://github.com/darktable-org/darktable/blob/17c8d54f07a8ad6a5ce82d66ac94530be71082ec/src/common/exif.cc#L824-L827) the file.

Sure, and the figures are given in the original comment. Seems like the time penalty is not terrible to me.

**Comment by jenshannoschwalm** [comment]
I would also accept the penalty having this comfort. Plus  we wouldn't have to worry about reading other exif data.

**Review by TurboGit — APPROVED** [review]
Ok, let's bit the bullet... we still have quite some field testing in case this breaks something not anticipated. Thanks.

**Comment by EC1000** [comment]
I have a question about this PR (sorry, I didn't test it yet): does it mean, that an exif data that was not defined in an old darktable version, and thus is still not defined for photos that were imported at that time, will be automatically update? 

If yes, that's great, but that could be a problem if 'exposure bias' is update while 'exposure bias compensation' is activated in exposure module. 

If no, sorry for the noise.

**Comment by TurboGit** [comment]
> will be automatically update?

No, if you want to read the exif data you must do it from the lighttable `selected image[s]` module (metadata tab you have a `[refresh EXIF]` button.

**Comment by EC1000** [comment]
Ok, thanks! I will continue to use `[refresh EXIF]` (with the benefit of #12744 regarding stars!)

**Pull request merged**
