### PR TITLE
po/fix masks

### PR DESCRIPTION
**Pull request by TurboGit**

### CODE REVIEW

**Comment by aurelienpierre** [comment]
Works here.

**Comment by jenshannoschwalm** [comment]
I just saw the open issue.

Do you really think this fix is the best one?
1. Doesn't this mean a mask visualizer might be shown even if the module is not "active"? So you might be confused ...

2. Should we better show after test for the existing condition **or** the mask manager being active?

**Comment by TurboGit** [comment]
@jenshannoschwalm : ok on both count ! the mask manager is always enabled so the check need to be refined.

**Comment by jenshannoschwalm** [comment]
mask manager widget extended?

**Comment by TurboGit** [comment]
@jenshannoschwalm : new version should be better. ok for you ?

**Comment by jenshannoschwalm** [comment]
Looks good for me.

**Pull request merged**
