### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by mmardegan**
the file update the italian translation.

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by mmardegan** [comment]
> Shouldn't it be Interpolatore invece di Intepolatore? (occurs more than once)

Thank you: added this PR #14912 for the 4.4.2 revision

**Comment by MauDarktable** [comment]
Hi guys, may I help with italian translations? I would like to be helpful in restoring of italian language for darktable. Please let me know. It's the first time for me, I've already installed poedit software. Thanks!

**Comment by mmardegan** [comment]
> Hi guys, may I help with italian translations? I would like to be helpful in restoring of italian language for darktable. Please let me know. It's the first time for me, I've already installed poedit software. Thanks!

Sure, let write me your email in private message or in the developer mailing list. For now the translation project is managed here: https://github.com/mmardegan/darktableITA/

**Pull request merged**
