### PR TITLE
retouch auto levels

### PR DESCRIPTION
**Pull request by edgardoh**
When display wavelet scale is first used on retouch, and levels has default parameters, run auto levels so the image is not black.

### CODE REVIEW

**Comment by TurboGit** [comment]
Sounds fine to me. Thanks.

**Comment by edgardoh** [comment]
Auto levels are executed only the first time the display wavelet scale button is used, and only if levels have default settings. Otherwise it will affect performance and may not be what the user wants. Once the levels are set they usually work fine for all the scales. If not the auto levels button can be used.

That's how the algorithm works, there's a gay line on top of each scale indicating if the scale is visible at current zoom level.

**Comment by aurelienpierre** [comment]
Ok I didn't got the gray bar.

So I would say, for now, the only thing I'm missing in your module is a copy/paste function to duplicate masks from one scale to another (ideally, I would like to share the mask without duplication, but I feel it might need more work).

Thanks again !

**Comment by edgardoh** [comment]
Is not really about the amount of work, I just don't find the share/copy
useful. Different scales have different size/shape for the same feature, so
the same mask won't do it. And when using the merge from option I do all
the edits on a single scale, so no share/copy are needed.

Maybe is my workflow or editing stile, can you describe a scenario where
this can be useful?

2018-09-10 17:35 GMT-03:00 Aurélien PIERRE <notifications@github.com>:

**Comment by aurelienpierre** [comment]
I'm using it on skin retouch, in portrait photography. Say you have a spot on the face, you want to remove it but not smooth the skin texture too much and you want to keep (some of) the noise to blend it better if you are at high ISO. To do that, I find that using the global scale blending is not accurate enough, so I do it in an iterative way, using the relevant scales (usually, between the scales number 3 to 6). So, basically, I duplicate the same mask on 3-4 non contiguous scales, sometimes with different opacities.

**Comment by edgardoh** [comment]
I'm assuming that by global scale blending you mean merge from option.

On 4 scales range the size of the feature will be very different, so the
mask will need some adjustment, so the share is out of the question. Based
on the amount of work that you describe, copy-resize a mask instead of
create a new one doesn't save much work, even for complex shapes, much less
for a spot, at least that's my experience using the cut/paste.

Let's see what other people say, maybe a copy option is more useful that I
think.


2018-09-10 18:55 GMT-03:00 Aurélien PIERRE <notifications@github.com>:

**Comment by aurelienpierre** [comment]
I did a short video to show you my workflow : https://youtu.be/SenONuZIq2Q

**Comment by edgardoh** [comment]
I understand your workflow (and I know what this editing technique is
about), that's not what I'm talking about, my point is that the copy option
don't save a lot of work/time.

About the merge option vs single scale, if you share your raw I can play a
bit with it and see what I can do. If you can't upload here maybe create a
post on pixl.us?

2018-09-10 21:38 GMT-03:00 Aurélien PIERRE <notifications@github.com>:

**Comment by aurelienpierre** [comment]
It saves a lot of time if you need to repeat it a lot, depending of the state of what you clean.

You can download the RAW + XMP from here : https://www.dropbox.com/sh/8wbgbj1tq9dnr7d/AAC7ZBampOELIZRgso5jlKdva?dl=1 Please don't put it into the wild since it's still production work.

**Pull request merged**
