### PR TITLE
Collect single-click

### PR DESCRIPTION
**Pull request by AlicVB**
This add an option in preferences to use single-click selection in the collect module (default remain to double-click)
As a side effect, this allow to directly select ranges with Shift-click (only works for ISO, aperture, exposure, focal-length, date and datetime)

### CODE REVIEW

**Comment by TurboGit** [comment]
Looks good and works fine. Thanks for reviving this, it is lot better to use the single click here. Do you think it would be possible to add aspect ratio ranges?

**Comment by AlicVB** [comment]
done for aspect ratio :)
One little glitch I've found is that with single click, it's now impossible to expand a node without selecting it. I've not managed to determine if the click append on the arrow or in the text...

**Comment by TurboGit** [comment]
A glitch or a feature. Clicking on the line open the children and select the parent. I find this ok.

Thanks a lot for handling the apsect filter.

And, yes almost 3 years after your first PR on this it will get merged right now!

**Comment by TurboGit** [comment]
Just found an issue with this. You cannot open a folder in the folder view in the single click mode.

Can you have a look? Thanks.

**Comment by AlicVB** [comment]
oops... should be fixed in #2084

**Pull request merged**
