### PR TITLE
Rework tagging

### PR DESCRIPTION
**Pull request by ChristianBirzer**
Hi to everyone,

I tried to improve the keyboard handling in the tagging module a bit. It's not completed by now but I'd like have your feedback if I'm on the right way or better stop continuing...

Maybe merging to master is not so good at this point, but I don't have an other target branch... Therefore it's a draft PR.

My ideas about the workflow:

- When finished: Hitting Ctrl-T opens the tagging side panel and sets the focus to the entry field (not implemented yet because this should only be done when the panel is available and I don't now yet how to open it ....). Currently you have to click the entry field like before.
- start typing a tag name, the dictionary tree or list (mode doesn't matter) will be filtered according to the entry
- with arrow down you can switch the focus to the dictionary and select the tag
- hitting enter/return there will attach the tag and jump back to the entry field which is cleared and ready for the next tag
- hitting shift-enter in the dictionary will add the tag but leave the focus in the dictionary to select another tag
- hitting escape in the dictionary will set the focus back to the entry field without attaching the tag.
- from the tag entry, the arrow up moves the focus to the list of attached tags
- here you can hit delete key to detach the selected (currently also the internal ones..., todo is in the comments)
- hitting escape in the attached list moves the focus back to the entry field
- when detatching the last tag from the list of attached ones the focus is also set back to the entry field.

What also needs to be done: Disable the built-in search in the tree view.

With this modifications I can really add a lot of tags to the images quite quick.

Please let me know what you think about this and if it makes sense to continue the work.

### CODE REVIEW

**Comment by phweyland** [comment]
I like most of your ideas and have implemented some of them on #10784 from your suggestions on dev mailing list.

Ctrl-T. I don't know enough the shortcuts but there may be a possibility to do that by preferences. Pinging @dterrahe.

> start typing a tag name, the dictionary tree or list (mode doesn't matter) will be filtered according to the entry

The filtering is already done, right ?

> What also needs to be done: Disable the built-in search in the tree view.

Do you talk about the completion feature (giving the list of matching tags) ? If yes, this can be done in preferences/miscellaneous. Otherwise please elaborate a bit more.

**Comment by dterrahe** [comment]
> * When finished: Hitting Ctrl-T opens the tagging side panel and sets the focus to the entry field (not implemented yet because this should only be done when the panel is available and I don't now yet how to open it ....). Currently you have to click the entry field like before.

You can already assign a shortcut to open/close the module but currently that doesn't automatically focus the entry field.

To turn the entry field into a shortcuttable action, something like
'  dt_action_define(DT_ACTION(self), NULL, "entry", w, NULL);
'
should work (haven't tested, but that's how you can switch to modulegroup search). That would not automatically expand the lib (or unhide the panel).
If you are making changes here anyway, you might want to turn the entrybox into a gtk_search_entry (again, like modulegroups).

> * with arrow down you can switch the focus to the dictionary and select the tag
> * from the tag entry, the arrow up moves the focus to the list of attached tags

Normally moving to the next or previous field is done with (Shift-)Tab. This is standard gtk functionality, but unfortunately the first tab will switch to a button and the second will no longer be caught by gtk (and the default shortcut is to (un)hide panels). There are several other modules (export/import/geotagging) where this nonetheless works as intended by calling
gtk_widget_set_can_focus FALSE for each of the intervening widgets. It would be nice to be consistent.

**Comment by ChristianBirzer** [comment]
> I like most of your ideas and have implemented some of them on #10784 from your suggestions on dev mailing list.

Thanks a lot for that. In case we get into conflicts, I absolutely prefer your solution as you are the experienced dt developer. I just began to play around with the code and it's completely ok for me if my changes won't find their way into the upstream. I learn a lot though.

> Normally moving to the next or previous field is done with (Shift-)Tab. This is standard gtk functionality, but unfortunately the first tab will switch to a button and the second will no longer be caught by gtk (and the default shortcut is to (un)hide panels). There are several other modules (export/import/geotagging) where this nonetheless works as intended by calling
> gtk_widget_set_can_focus FALSE for each of the intervening widgets. It would be nice to be consistent.

I fully agree that consistent behavior should be preferred. The reason why I used arrow down to select the tree/list is, that this would change nothing compared to the current pop-up tagging entry (ctrl-t like it is now). At least in case of list dictionary, the behavior is exactly the same, just in the side panel. Additionally it woks with tree dictonary too.

I'm not sure if it makes sense to have the tab shortcut available for hiding the side panel while adding tags in the side panel at all. So it also could be used to move focus between the fields. (btw: in LR, tab moves focus when you are in a focus-enabled field (entry, list etc.), otherwise it enables/disables side panels)

>The filtering is already done, right ?

Right. I did not change anything there. I just mentioned it because it's important to filter the dictionary so it behaves like the pop up tag entry.

>Do you talk about the completion feature (giving the list of matching tags) ? If yes, this can be done in preferences/miscellaneous. Otherwise please elaborate a bit more.

I talk about the "search" entry that opens when the focus is on the dictionary tree/list and you start to type here:
grafik
I think it doesn't make sense to have this in addition to the filter function from the entry field above. Could be disabled by a call to `g_object_set(view, "enable-search", 0);`

BTW: I could not find out what completion feature is turned off by the preference setting. May this be broken? All things I know and I tested behave the same no matter if I set the check or not (restarted dt after changing the setting)

**Comment by dterrahe** [comment]
> (btw: in LR, tab moves focus when you are in a focus-enabled field (entry, list etc.), otherwise it enables/disables side panels)

This is how it is supposed to work in dt as well, except it isn't necessarily consistently implemented everywhere and if there are any other widgets in between that can grab focus (sliders etc) but don't handle Tab to move focus, you kind of get stuck there. So it is really only useful for modules that mainly serve for text input, like tagging.

> `g_object_set(view, "enable-search", 0);`

Or `gtk_tree_view_set_enable_search(view, FALSE);`

**Comment by ChristianBirzer** [comment]
> > I could not find out what completion feature is turned off by the preference setting.
> 
> image

Ah, sorry, I wasn't clear enough. I know this checkbox but I don't know yet what it will switch off. Everything seems to be unchanged...

**Comment by dterrahe** [comment]
If you start typing in the entry field, it will generate a dropdown with the available matches. You can click on them or select one with arrow keys. It is not that obvious, because it overlays the treeview below, which basically shows the same filtered selection.

You need to restart after switching the check-box on/off for the change to become active.

**Comment by phweyland** [comment]
This affects only the list view. This is the same list as for the pop up (Ctrl+t):
image
As it covers the listview it could be annoying.

**Comment by ChristianBirzer** [comment]
> If you start typing in the entry field, it will generate a dropdown with the available matches. You can click on them or select one with arrow keys. It is not that obvious, because it overlays the treeview below, which basically shows the same filtered selection.
> 
> You need to restart after switching the check-box on/off for the change to become active.

Ah, thanks a lot. Now at least I know how it is supposed to work.
But: When I enable the completion and have the dictionary in list view and begin to type, the list opens and I can arrow-down to the entry end press enter. And: the half typed tag is added to both the attached and dictionary but not the selected one in the list. 
3.8.0 official build on windows 10. 
grafik
-> press enter:
grafik

When I click on the entry with the mouse, the (tag) text is set into the entry field. From here I can hit enter to use it. But I have to use the mouse in between.

Still, I vote for eliminating the additional drop down in the side panel completely and filter the list/tree instead and add full keyboard support for that.

I still have no idea what to do in culling or preview mode. I guess, the current popup entry field would be best (or pop up a full featured "side panel tagging" dialog?? Hmmm...

**Comment by phweyland** [comment]
I'm sorry, as you haven't answered my review suggestion I've completed (mostly I think) the work on #10784.
If you wanted you could check if that covers your need.

**Comment by ChristianBirzer** [comment]
> I'm sorry, as you haven't answered my review suggestion I've completed (mostly I think) the work on #10784.
> If you wanted you could check if that covers your need.

Ah, sorry, was a bit busy with other things. An hour ago I pulled your branch and took a look at it. I like it! I haven't caught your last commit yet but I guess I will try this later today.

I just pushed a small change to my PR in the hope to fix the compile error. Local build was fine but CI noticed missing parenthesis. (I'm still learning on this project 😊 )

I will close my PR after that and wait for yours to be merged. If I still have some ideas, I can continue then.

Thanks a lot for the work done!

**Comment by ChristianBirzer** [comment]
Closing this PR since it was done with #10784

**Pull request closed without merging**
