### PR TITLE
collect: refresh the folders' status after relocating a lost folder

### PR DESCRIPTION
**Pull request by phweyland**
fixes partially #9931

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Thanks !

**Comment by TurboGit** [comment]
@phweyland : this is probably also for 3.6.1, no?

**Comment by phweyland** [comment]
> @phweyland : this is probably also for 3.6.1, no?

Yes, I think there is not risk here.

**Comment by TurboGit** [comment]
Tested but the routine `dt_film_set_folder_status()` is not present on 3.6. Probably not worth it.

**Comment by phweyland** [comment]
Sorry, you are right this code is only on 3.7. My mistake

**Pull request merged**
