### PR TITLE
Convert lensfun implementation to pure C code

### PR DESCRIPTION
**Pull request by cryptomilk**
This converts our lensfun implementation to pure C code.

### CODE REVIEW

**Comment by parafin** [comment]
Why? It was changed to C++ for a reason.

**Comment by parafin** [comment]
Specifically this breaks compilation with lensfun 0.3.95 (see LF_0395 macros).

**Comment by cryptomilk** [comment]
What's the reason for C++?

**Comment by parafin** [comment]
C API is broken in lensfun 0.3.95. They probably fixed it in git version, but C++ API is native for lensfun, so it's better tested and supported.

**Comment by parafin** [comment]
That decision was already made when that PR was merged, you are basically reverting it, so what's the reason for the revert?

**Comment by jakubfi** [comment]
@cryptomilk lensfun API has been switched from C to C++ due to the fact that C++ is the native API of the library, while C API was found to be sometimes not up to date and buggy. Using the native API is always a good idea, especially that in this case it doesn't harm the code in any way.

Support for (pre-)alpha version of lensfun (0.3.95) is experimental and was added to make the transition to lensun-next easier and allow for early compatibility testing. As 0.3.95 is alpha, it is expected to never be a generally available version in any distro, thus no regular user will use this combination. But if user wants to test it, dt can be compiled against it and should work.

If there are any concerns whether dt should even compile against 0.3.95, support for it can be disabled (#undef LF_0395 or something similar), but I would be against completely removing the 0.3.95 related code.

**Comment by TurboGit** [comment]
I agree, this decision was made to avoid the buggy C API. We certainly don't want to go back at this stage. @cryptomilk : I let you close?

**Pull request closed without merging**
