### PR TITLE
[CI] Attempt to fix broken macOS CI build

### PR DESCRIPTION
**Pull request by victoryforce**
This fix worked when the problem was caused by the lensfun package. Now, this problem is caused by dependencies in a different place, but the core of the problem is the same. This fix I think should work for now too, let's try it…

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
CI has passed, thanks!

**Comment by kmilos** [comment]
Isn't there a better way to handle this? Are any problems reported upstream, or advice asked from Homebrew experts? This is way to much overhead to keep maintaining and worrying about all the time, the CI gets broken too frequently 😟

**Comment by victoryforce** [comment]
> Isn't there a better way to handle this?

No, there isn't.

> Are any problems reported upstream, 

For me, this is too much of a distraction and a waste of time to communicate and, quite possibly, to convince people that they really have a fundamental problem (which can be difficult, long and possibly unsuccessful). Sorry.

I would like to emphasize that reporting __specific__ problems to upstream does not fundamentally solve anything, because in this way we only increase our overhead costs.

> or advice asked from Homebrew experts?

What advice? This is their problem. A lensfun package that cannot be installed cleanly without an error code as a return value? It's their fault, just a fault of insufficient verification. And no, I don't want to add "|| true" to the end of the bundle install command to avoid failure. I'd rather spend half an hour guessing and checking what's broken in their packages next.

> This is way to much overhead to keep maintaining and worrying about all the time, the macOS CI gets broken too frequently 😟

I agree, too much. Too often. But if we support building using Homebrew, we have to accept this. We have no other choice. Support for the package base as a system without internal contradictions is too weak and imperfect in Homebrew.

I've been one of the lead maintainers for two Linux distros, so I can confidently say that Homebrew's package system is far from a quality-assured package base. Can we do something about it? Yes, we can take over their project and improve it. It was a joke, we can't.

**Comment by parafin** [comment]
Is it feasible to use macports in GitHub actions? macports seems to be more stable-ish (though I've never used homebrew outside of looking at darktable CI).

**Comment by victoryforce** [comment]
Yes, it is feasible. See for example https://github.com/GiovanniBussi/macports-ci

On the negative side, it will slow down the execution of macOS builds a little more, because we must first additionally install MacPorts in the system. So, you will have to wait longer for the CI to complete to check for success. On the other hand, it is not so significant, and if we want faster feedback, this can only be achieved by reducing the number of CI jobs.

Since I'm not an apple user, I don't really want to mess with it. So far, the time spent on fixing occasional homebrew problems isn't big enough to motivate experimenting with macports.

**Pull request merged**
