### PR TITLE
Nikon D5100 Basecurve and Tonecurve (#10462)

### PR DESCRIPTION
**Pull request by superdachs**
According to my ticket about the bad imports from Nikon D5100 i made a basecurve and a tonecurve from 22 sample images.
Quality is now much more better even if it isn't perfect.
Especially at darker, slightly underexposed parts of an image details where missing and dark colors, especially blue, are a bit bloched.
I think that curves are nearly best result with extended color matrix.
A dedicated input profile for D5100 would do the rest i think.

### CODE REVIEW

**Comment by superdachs** [comment]
I will collect more Data today and check if the curves even become better (thinking the color curve could be)

**Comment by TurboGit** [comment]
So is it better? Also you'll need to rebase this pull-request.

**Comment by fulldecent** [comment]
Have tested, works decent. Recommend to merge.

**Comment by superdachs** [comment]
Don't know what you mean with "rebase this pull-request"

**Comment by pmjdebruijn** [comment]
We can't automatically merge this request now... But it's easy enough to manually pick, so nevermind, committed:
4d73c5b53ab7f349279c4f132e3816a785f28133
541a7f9a229e044b0e9865aa6d50fe3e81d91da1

So effectively this request is merged now.

**Comment by pmjdebruijn** [comment]
Thanks!

**Comment by superdachs** [comment]
cool, thank you

**Comment by tuxflo** [comment]
Thanks a lot for the patch keep! I tested it using the snapshot feature and the difference is amazing. Just a little issue: I was not able to compile the masterbranch at a 32bit environment without a small change (cast a error message value to long int) Should I do a pull request for that here?

**Pull request closed without merging**
