### PR TITLE
MacOS: remap Control bit to Cmd for key accelerators

### LINKED ISSUE #4384: MacOs - Replace unhandy Modifier key CTRL with CMD
**Describe the bug**

Shortcuts - Modifier key on Mac is CMD (ex-Apple) not CTRL
Using the Control (Ctrl) key is unnatural and cumbersome on Apple Keyboards.  
CTRL is on the extreme left / extreme right on the last line of my keyboard and not side by side to the spacebar button.
I tried to add CMD to as Modifier key to the shortcuts i use, but Darktable is unable to detect CMD. If i press CMD+F, then DT registers only F. 

**Expected behavior**

Please re-place the modifier Key CTRL with CMD for Apple Users. 

**Platform:**
 - Darktable Version: 3.0.0
 - OS: MacOs: 10.14.6
 - OpenCL activated :  no
 - AMD Radeon HD 7970 3 GB

### PR DESCRIPTION
**Pull request by ralfbrown**
May fix #4384.  Will work for mouse actions including mask drawing even if #8078 does not.  I'll need someone with a Mac to test, as I've gone solely by what I could find in the Gdk documentation (at https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#GdkModifierIntent)

For 3.8, since this would require documentation changes.

### CODE REVIEW

**Comment by MStraeten** [comment]
i checked this on osx; the result is very inconsistent:
**in lighttable:**
cmd+scroll replaces ctrl+scroll
**for keyboard actions:**
shortcuts remains working by using ctrl key. 
**for mouse actions on drawn masks:**
cmd is not recognized
ctrl+scroll = cmd+scroll = scroll, so changing opacity is no longer possible
ctrl+click = cmd+click = just a left click

**Comment by ralfbrown** [comment]
It figures that it wouldn't be as simple as adjusting `dt_modifier_is`.  On reviewing all of the occurrences of `GDK_CONTROL_MASK`, it looks like I also need to adjust `dt_accel_register_*`, `dt_masks_events_mouse_scrolled`, `dt_mouse_action_create_*` (for the help screen,  but that I knew about), and a few bare uses of the mask. 

Hopefully the push I make in just a moment will fix things (except for showing something like "Mod2" on the help screen).

**Comment by MStraeten** [comment]
now key accels are fine
opacity of drawn mask is changed by ctrl-scroll
ctrl+click and also cmd+click aren't available for adding a node or changing a node mode smooth/sharp 

i doubt it's necessary to change the modifier for mouse events. While it's consistent ux to have key accels similar to the system (e.g. cmd c/v for copy paste) it doesn't make sense for mouse events since these are  highly darktable specific

**Comment by ralfbrown** [comment]
I think I have a fix for opacity, but I can't figure out why Ctrl/Cmd-Click for nodes doesn't work....

Doing the mapping only for accels would substantially simplify things -- I could drop all the changes except `dt_map_ctrl_bit_to_cmd` and its calls from `dt_accel_register_*`.

**Comment by dterrahe** [comment]
> I've gone solely by what I could find in the Gdk documentation (at https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#GdkModifierIntent)

Since you are already quoting the relevant documentation, any particular reason why you have decided not to use
`gdk_keymap_get_modifier_mask`  and `GDK_MODIFIER_INTENT_PRIMARY_ACCELERATOR` but are using an `ifdef APPLE` instead?

The way I was going to approach this was to consistently use GDK_CONTROL_MASK in the code and only when comparing to actual modifier inputs received match that with MOD2s on Mac (well, basically whatever received from `gdk_keymap_get_modifier_mask` at startup). That would require the least number of code changes. This is slightly different from what's currently in #8078, which I didn't manage to receive any feedback on, which basically blocked me from continuing working on this. Now that we have an apple user here; @MStraeten would it be unwelcome if CTRL and CMD on Mac would be treated as interchangeable (i.e. _both_ work)?

Another reason I postponed this, was that I wanted to solve it together with implementation of "modifier" keys on MIDI (and other devices) and tablets.

**Comment by ralfbrown** [comment]
Quick&dirty....   If we go with keeping mouse actions using Control and only remapping key accels, I'll do the more correct (but slower) get_modifier_mask version.

**Comment by MStraeten** [comment]
A mixture between cmd and ctrl commands are also present in final cut so using the ctrl key is no pain for mac users in general ;)
Having cmd based accels is mainly relevant for the common used key accels: ctrl-x, ctrl-c, ctrl-v, ctrl+z  - supporting both (ctrl and cmd as modifier as well) at least simplifies stuff for just mac users - but there's a price for this: it reduces the room to define user specific key accels. 
But even replacing ctrl by cmd has its price: There's at least one darktable key accel that doesn't work when using just cmd as modifier: ctrl+H (cmd+H is an osx accel and hides the whole window)

i'm not aware of commonly used cmd modifier for the mouse, so keeping ctrl there is ok in my opinion.

**Comment by ralfbrown** [comment]
OK, remapping key accels only and using the recommended method of getting the <Primary> modifier.

**Comment by dterrahe** [comment]
> OK, remapping key accels only and using the recommended method of getting the modifier.

This now basically looks identical, apart from the additional bugfixes and the significant restructuring in that PR, to what has been in #8078 for a while (https://github.com/darktable-org/darktable/pull/8078#issuecomment-775129655). Untested.

**Comment by ralfbrown** [comment]
In that case, I guess we should skip this PR since 8078 is about to be merged.  @MStraeten might still want to let you know whether the remapping in this PR works correctly.

**Comment by dterrahe** [comment]
That would be nice, but If 8078 gets merged early, there should be enough time to deal with complaints.

The bugfixes in thumbnail and vignette are still good to have; would you mind submitting those separately please? Or rename this PR to reflect it is reduced to just those fixes?

I'm sorry you wasted time on this. Had I known you were working on it, I would have made clearer that 8078 included some "fixes" already. But I also assumed that (much) more work would be needed, which now does not seem to be the case. Let's see whether the feedback from other mac users is different.

**Comment by TurboGit** [comment]
@dterrahe : There is no "if it gets merged early", we agreed on that, this is modifying so many parts of the code that I'll merge as soon as possible to be sure we get a lot of field testing.

**Comment by dterrahe** [comment]
@TurboGit of course! But I assume you'll still do a _little_ testing yourself before you dump it in master? ;-)

I've not seen a lot of feedback that included hard testing recently (except @johnny-bit; thank you!) so I wouldn't be surprised if you manage to make it fall over the first second you breath on it. Yes, that can be fixed once it is merged, but if the first impression people get is that it broke _everything_, the negativity and hating may be permanent.

**Comment by TurboGit** [comment]
Oh sure I'd do some testings :)

**Comment by ralfbrown** [comment]
Closing in favor of 8078 for the remapping and #9314 for the bugfix part.

**Comment by MStraeten** [comment]
i did some test and it seems fine.
little UI improvement: in the h help overview the cmd key is represented as "Mod2"

**Comment by ralfbrown** [comment]
> little UI improvement: in the h help overview the cmd key is represented as "Mod2"

That was a known TODO.

**Pull request closed without merging**
