### PR TITLE
save and use an independent format for every storage, fixes #11690

### LINKED ISSUE #11690: [export] file format should better be independent in the various storages
Now if you change the file format, the change reflects in all (or almost all) the storage types.

This is not the optimal behaviour, because I easily want to use a format for saving on disk, a different one for sending by email, a different one for hugin panorama, etc.

So the file format shouldn't be the same for all the formats, each target storage should keep memory of its preferred format.

### PR DESCRIPTION
**Pull request by paolobenve**
This PR implements what explained in #11690: for every storage, the format is saved independently, so that it's remembered throughout the darktable session, and when darktable is closed, too.

Surely the code quality can be better, I apologize if something is rough... Anyway it works! Help me to correct what isn't perfect!

### CODE REVIEW

**Comment by wpferguson** [comment]
I defined a preset for gimp to export with OpenEXR.  I defined another preset for hugin to export with TIFF 16 bit.  When I start the preset both gimp and hugin show JPG output format.  So, it appears that this PR breaks the presets.

**Comment by TurboGit** [comment]
@paolobenve : Is that still on your scope? If so it needs some fixes otherwise please close. TIA.

**Comment by paolobenve** [comment]
> Is that still on your scope?

yes

**Comment by wpferguson** [comment]
Tested this with lua storage scripts.  Used contrib/RL_out_sharp.lua.  

1. Opened exporter and selected RL_out_sharp
2. File format came up as TIFF.  I selected JPG.
3. I exited out of darktable.
4. Restarted darktable and most of the fields are blank in the exporter and after a few seconds it crashes

[darktable_bt_A1UGS1.txt](https://github.com/darktable-org/darktable/files/9618320/darktable_bt_A1UGS1.txt)
[darktable_bt_LC7VS1.txt](https://github.com/darktable-org/darktable/files/9618322/darktable_bt_LC7VS1.txt)

**Comment by dterrahe** [comment]
From the discussion so far, I'm not convinced this adds anything beyond using presets, but offers a different, somewhat confusing and incomplete, way to achieve the same thing that actually causes clashes. Could you please explain how you intend to resolve the conflicts without this still behaving unpredictably, even/especially for new users for whom presets are too difficult to figure out? Or otherwise close this so we have fewer PRs that people might spend time on testing? Normally I'd say you could leave this open as part of a "library" that people could cherry-pick features out of for their personal compilation. But your target audience probably doesn't self-compile...

Even research&development that doesn't lead to new products is valuable because it shows what _doesn't_ fully work and why, so your efforts are definitely appreciated!

**Comment by dterrahe** [comment]
Closing this for now. Please reopen if merge conflicts and the issues mentioned have been resolved or open an issue to discuss direction first. Many thanks!

**Pull request closed without merging**
