### PR TITLE
WB Presets for Pentax K-1 firmware ver. 1.52

### PR DESCRIPTION
**Pull request by johnny-bit**
Sample set contributed by Thomas_Gulmark via pixls.us

### CODE REVIEW

**Comment by TurboGit** [comment]
Thanks !

**Comment by gribouilleuse** [comment]
Hello,

In the file src/external/wb_presets.c there are already few presets for Pentax K-1 :

>   /* Pentax K-1 Firmware Version 1.10 */
>   { "Pentax", "K-1", Daylight, 0,  { 2.14062, 1.0, 1.66406, 0.0 } },
>   { "Pentax", "K-1", Shade, 0,     { 2.65625, 1.0, 1.25000, 0.0 } },
>   { "Pentax", "K-1", Cloudy, 0,    { 2.37109, 1.0, 1.43750, 0.0 } },
>   { "Pentax", "K-1", DaylightFluorescent, 0,      { 2.61328, 1.0, 1.60938, 0.0 } },
>   { "Pentax", "K-1", CoolWhiteFluorescent, 0,     { 2.23047, 1.0, 1.82031, 0.0 } },
>   { "Pentax", "K-1", WhiteFluorescent, 0,         { 2.01953, 1.0, 2.19531, 0.0 } },
>   { "Pentax", "K-1", WarmWhiteFluorescent, 0,    { 1.70312, 1.0, 2.77734, 0.0 } },
>   { "Pentax", "K-1", Tungsten, 0,  { 1.32422, 1.0, 2.92969, 0.0 } },
>   { "Pentax", "K-1", "2500K", 0,    { 1.14062, 1.0, 2.75391, 0.0 } },
>   { "Pentax", "K-1", "3000K", 0,    { 1.40234, 1.0, 2.33984, 0.0 } },
>   { "Pentax", "K-1", "5000K", 0,    { 2.07812, 1.0, 1.54688, 0.0 } },
>   { "Pentax", "K-1", "5500K", 0,    { 2.19141, 1.0, 1.45703, 0.0 } },

Should they be deleted?

**Comment by johnny-bit** [comment]
Damn, that's what I get for rushing things, I was dead sure I removed them in PR. must've missed removal commit :/ if you want you can create our own PR removing those or I'll do that soon (ish) ;)

**Comment by TurboGit** [comment]
I'm also to blame, I always do a "git grep" to ensure we don't already have entries for a new PR. I certainly mess my test on this one :)

**Pull request merged**
