### PR TITLE
collect: add set preference to presets menu

### PR DESCRIPTION
**Pull request by phweyland**
related to #7050 

move collect preferences from main preferences to preferences in presets menu.
These preferences are not saved with presets.

image

### CODE REVIEW

**Comment by phweyland** [comment]
@TurboGit , Pascal this PR is ready for review.

**Comment by TurboGit** [comment]
We are unfolding the complexity of the preference. And this will be needed more and more as we move some prefs from the general dialog to the module.

What I'd like is:
- add a new attribute in darktableconfig.xml.in say dialog with the name of the dialog (dialog="collect")
- generate a pref_collect_gui_dialog.c file from there
- use it in this PR

This will avoid having to list all prefs or handling the fact that they are int, float, boolean... I suppose this will simplify lot the code.

How does that sound ?

**Comment by TurboGit** [comment]
BTW, I'm still wondering about this. The issue was too many prefs in early discussion now we have as many prefs but split out in many places. I'm sure this will raise lot of discussion as (and this is my case) some would prefer having all prefs in a single location. This is BTW what is done in many applications I know.

**Comment by parafin** [comment]
IMHO spreading preferences to be located more locally to what they affect makes sense and helps understanding and finding them by adding context. But I do understand that sometimes it's desired to go over all settings. Luckily they are still stored centrally in darktablerc, which is quite readable in text editor. So maybe it can be considered a workaround...

**Comment by ptilopteri** [comment]
perhaps a notice could be provided that preferences have changed.  I know that I frequently have to compare my darktablerc with the default on update to make adjustments or frequently my short-cuts and/or other setting do not work as expected.  many of the earlier configs are no longer available and there are quite a few new ones.
tks

**Comment by Nilvus** [comment]
I really like too to have preferences near what they are related to. And thanks for working on that but we indeed need to be all agree to what to move and what to not move now. Some things should remains on main preferences. Actual move for import, information module and metadata ones are good things and already merged. For that one, we need to be sure if all settings should move. And for some other. I have to apologize as I don't take time by now to summarize what we already discussed in #7050 issue. I will have more time this week so I will change that and we need to finish the discussion and choices in #7050.

**Comment by Nilvus** [comment]
Just to avoid misunderstanding, I like that PR.

**Comment by phweyland** [comment]
> What I'd like is:
> 
>     * add a new attribute in darktableconfig.xml.in say dialog with the name of the dialog (dialog="collect")
> 
>     * generate a pref_collect_gui_dialog.c file from there
> 
>     * use it in this PR
> 
> 
> This will avoid having to list all prefs or handling the fact that they are int, float, boolean... I suppose this will simplify lot the code.
> 
> How does that sound ?

For the sake of the discussion, here are some personal findings during this work.
So far I see 3 cases:
- metadata view. Only display settings (a lot of). Nothing in darktableconfig.xml.in.
- import. Process settings. Some are in darktableconfig.xml.in. For some others (metadata) this is more difficult because the list of metadata can increase and it requires attention to synchronize them in darktableconfig.xml.in.
- collect. Only display settings. All are coming from darktableconfig.xml.in. The only example of standard prefs dialog.

I see some advantages to define everything is a single place.
- same framework to define the presets
- no need to reinvent the wheel at each new preset
- consistent behavior

But I don't see the generated file (preferences_gen.h) as an advantage. This is a great duplication of code. And this is not flexible. 
I would prefer an extended set of routines (as conf.c ones) specific for display, like I started to propose at the end of preferences.c (nothing else than one copy of preferences_gen.h ones per type) which still can be optimized. The code is not duplicated. And it is more flexible:
- one can mix centralized defined preferences and other stuff. 
- one can link specific actions on certain ui events (one example in import pref).

>     * add a new attribute in darktableconfig.xml.in say dialog with the name of the dialog (dialog="collect")

I like the idea.

>     * generate a pref_collect_gui_dialog.c file from there

I 'm not comfortable with this one. I would prefer to generate a simple table (for "collect") with the information needed to call the standard display routines. If everything is standard, the code is quite simple.
But that lets the door opened to add some other actions, information or behavior to the pref dialog if necessary.
And we can use dialog = import for the standard part of it.

**Comment by TurboGit** [comment]
> I 'm not comfortable with this one.

Let me give it a shot, if I can build the template for this I'll let you put the correct node needed for the full dialog. I'll report back.

**Comment by TurboGit** [comment]
For having the preferences moved close to the module it seems we have many people for, so we'll go this way.

**Comment by TurboGit** [comment]
@phweyland : see #7557 

Let me know if something missing. If this works for collect I'll add the necessary piece of code for the export dialog.

**Comment by phweyland** [comment]
A small issue somewhere.
Both button cancel and save do not save the changes.
Escape key saves the changes.

**Comment by phweyland** [comment]
@TurboGit 
the logic:
`  if(response_id != GTK_RESPONSE_DELETE_EVENT) return;`
is the one for global preferences dialog. Here we have to consider also:
`GTK_RESPONSE_NONE and  GTK_RESPONSE_YES `
and do the opposite on 
`GTK_RESPONSE_DELETE_EVENT`

**Comment by TurboGit** [comment]
@phweyland : I have fixed the dialog responses. I'm merging this to master now. Thanks.

**Comment by TurboGit** [comment]
Merged manually, closing.

**Pull request closed without merging**
