### PR TITLE
masks continuous add

### PR DESCRIPTION
**Pull request by edgardoh**
This PR allows to select the position of the source when adding a mask and also to keep adding masks without pressing the add button again.

When adding a clone mask a cross will be displayed on the position where the source will be created. To change the source position CNTRL+click sets an absolute position, that means next mask will have the source created at that position. SHIFT+click set a relative position, the first time the source will be created at the selected position but next mask will have the source at the same relative position of the previous one.

With CNTRL+click on the shapes toolbar on the retouch module the continuous add is activated. When a shape is added the module is still on add mode.
For the circle and ellipse is still available the possibility of dragging the source after the add and then keep adding.
New shortcuts are also added for this add type.

For now this only works with the retouch module.

### CODE REVIEW

**Comment by TurboGit** [comment]
If I agree that this can be useful for the retouch module it is also the case for the spot removal module. But there I'm using a key to add circle and I find that having a handle on the keyboard and one to place the spot with the mouse is just good. So all in all I'm not sure the extra complexity here is really needed. Better to add a key binding for the different tools? Have you tried?

**Comment by edgardoh** [comment]
I have shortcuts for each shape and I use them to add the masks, but I like
this feature more. I like being able to see where the source will be
created and being able to change the position if needed, and having my left
hand free and not need to press a key for each add makes a difference to me.

This feature has been requested several times, so I'm sure I'm not the only
one that find it useful.

2018-09-25 4:16 GMT-03:00 Pascal Obry <notifications@github.com>:

**Comment by TurboGit** [comment]
I tied it, and found the view of the source not easy to use. I do prefer the click on the dest and drag to the source the mouse.

I would certainly split this in two PR. The first for the keep adding and one for the view of the cross (source created).

Note that the cross in the relative position does not seems to be correctly placed when using the relative mode. The absolute mode looks ok. Trying again to see if we can found a pattern... but now I cannot reproduce.

If we go with that we probably want the very same behavior in the spot removal module (keep adding).

BTW, I'd love to have feedback from more people, so if you are reading this... :)

**Comment by edgardoh** [comment]
I made only one PR for both because the keep adding without the possibility
of selecting the source position don't make much sense with the path and
brush, those cannot be drag, and adding multiple shapes and then change the
source for each one is not practical.

For me the cross works fine indicating the position where the source will
be created, but I forget to comment on the following issue:

To define the position one has to place the mouse pointer on the desired
position, not the cross. It feels more natural and also with the circle and
brush it gives an idea of the area covered by the future mask. But the
cross remains in the same position, and I would like it to be under the
mouse, but I couldn't do it. I can't read the keyboard state when only the
shift or control are pressed. It seems that gtk sends a different code than
the shift or control, and dt filter that codes, so a zero is propagated on
the events. I couldn't find a way around this.


2018-09-25 11:34 GMT-03:00 Pascal Obry <notifications@github.com>:

**Comment by theres** [comment]
Hi, I'd like to put my two cents.
1. Gimp shows outline of source shape with cross in the middle, I like this a bit more, because cross is not always good visible. 
2. When using brush tool in absolute mode cross stays in the same place while drawing. In Gimp it follows a mouse and return to the initial position after button release - this also is a bit user friendly imho.
3. It sometimes escape `continuous add` mode, not sure when, seems like a bug.

Anyway, I personally like it. Quite useful for skin retouch and spot removal when background is uniform (like sky). Similar to what Gimp and Photoshop do for clone and heal tools. 

For simple spot removal/heal, I'd love to see something more like in Lightroom - it just tries to automatically find best matching source spot (could be probably realized by something similar to searching in PatchMatch, at least for small spots)  

PS. module shortcuts do not work well with multiple module instances now, so usage may be limited.

**Comment by edgardoh** [comment]
Hi,

1. I didn't draw the source because I thought it will be distracting, and I
didn't want to change the interface that much, but I don't use GIMP, so if
in your experience is better and everybody agrees I can add it.
2. I can do that.
3. I cannot duplicate this. The continuous mode is exited with right-click,
click on the shapes toolbar or with the shortcuts, maybe you hit some of
that by accident?

No idea how LR works but before deciding on this healing I have tested some
others that do not require a source and I liked this one better. Maybe some
other algorithm can be added, but finding one with good performance/results
ratio won't be easy.

But before doing any work let's first be sure that this will be accepted.

I'm not sure I understand, you are saying that shortcuts don't work well
with multiple instances in general or just on the retouch module?


2018-09-25 17:31 GMT-03:00 Dominik Markiewicz <notifications@github.com>:

**Comment by theres** [comment]
> 3. I cannot duplicate this. The continuous mode is exited with right-click,
click on the shapes toolbar or with the shortcuts, maybe you hit some of
that by accident?

Maybe, not sure yet. I've got something like this maybe 3-4 times while testing without clear reason.

> I'm not sure I understand, you are saying that shortcuts don't work well
with multiple instances in general or just on the retouch module?

In general. As example, add shortcut for increase exposure in exposure module, then shortcut will always add exposure to the first instance of this module, not to the active one. In retouch on the other hand, if you add shortcut for circle tool, it will add it to the last added instance.

**Comment by TurboGit** [comment]
I did a second pass and I'm starting to understand and appreciate the usage.

To me here is what is missing:
- indeed the point 2 above, trace for the brush would be nice

- if I'm not mistaken the only other place where we have a clone is on the "spot removal" module and I would like to have the same behavior here. It would be a shame to have two cloning tools working differently and not supporting the same level of usage. As you already have the cross and relative/absolute position of the source in "spot removal" it just remains the multiple clone support.

I did a first pass on the code and don't have comment, sounds just correct to me.

**Comment by edgardoh** [comment]
Great, I'll start working on point 2, and leave point 1 until I have more
feedback.

About the spot removal, we seem to have different views on that. For me is
not a good idea to duplicate code/functionality, and thre's no real
advantage here, if the user wants a feature that is not present on the spot
removal he/she can always use the retouch.

The easiest to do the port it is to copy the retouch.c into the spots.c and
remove the wavelet decompose (and maybe the blur and fill), but again, it
doesn't seems right to have that duplicated.

That being said, I don't mind doing that work, but in that case let's wait
until the retouch is better tested and we are confident that there's no
more functionality added (I may have a couple on my todo list) . I don't
want to copy it over and over.


2018-09-27 10:45 GMT-03:00 Pascal Obry <notifications@github.com>:

**Comment by TurboGit** [comment]
I see your point. I always thought that retouch is for retouching skin and you do imply that the retouch module is for everything (spot removal + skin retouch...). And I start thinking alike. So let's forget about the spot removal for now. Thanks again for your hard work.

**Comment by edgardoh** [comment]
Now the cross follow the mouse while adding in absolute mode

**Comment by edgardoh** [comment]
When in continuous add if the shape type is changed the cross will go to what seems a random position until the mouse is moved, then it returns to the correct position.
This is because the mouse position in the masks module is reset each time a mask is created. This last commit fixes it.
Also, when a mask is created, the preview is always displayed on the center of the image until the mouse is moved. Now it will be displayed under mouse, if the mouse is outside the darkroom area it will be in the center as it is now.

**Comment by TurboGit** [comment]
The brush continuous mode seems to be always activated, to reproduce:
- open a picture
- open retouch iop
- do not change any default
- click on brush
- click on blur
- apply a brush

when releasing the mouse the brush is still selected

**Comment by TurboGit** [comment]
BTW, I have the same behavior with the circle  tool, probably with others (not tested).

**Comment by edgardoh** [comment]
Fixed. It happens when selecting/changing the algorithm.

**Comment by TurboGit** [comment]
No more comments. All good now. Thanks.

**Comment by aurelienpierre** [comment]
Hi,

I don't know if this is this commit or another, but it seems that the retouch module is crashing sometimes in OpenCL mode.

What seems to be the source is having several masks overlapping, mixing correcting and blurring masks makes it worse. It doesn't happen everytime, but when it does, the terminal says `could net enqueue kernel [retouch] : -4`. Also this error makes the whole desktop UI freeze hard (hard reboot needed).

No problem in CPU mode.

**Comment by TurboGit** [comment]
That's strange I have never crashed the module. I'll try with more masks overlapping. Please do not hesitate to give more information to reproduce if possible.

**Comment by aurelienpierre** [comment]
I'm still figuring it out, it's not systematic. The kernel fails only after several minutes of adustments in the darkroom, and the big freeze happens only during picture export.

**Comment by TurboGit** [comment]
BTW, Is that only since the continuous add implementation in this PR?

**Comment by edgardoh** [comment]
-4 means out of resources, that can happen, but for a given image it should
happen every time it is exported, and dt should fallback to CPU and things
go normal from there. If it is only after a while of using dt it could mean
a memory leak somewhere.
One way to try it is to copy that same edits on a large number of images
and export them several times.

Also that message don't necessarily means that the retouch is crashing dt,
can be any other module. I take that a backtrace is not being generated, so
try to generate one. You can find how to do it in:
How to produce a backtrace
https://www.darktable.org/development/

If you share the xmp that get you the error I can do some tests myself.

**Comment by aurelienpierre** [comment]
> BTW, Is that only since the continuous add implementation in this PR?

It's only since I have merged this PR with my dt's master fork that I have had this error, but I haven't used the Retouch module enough before to be 100 % sure it wasn't there already.

> -4 means out of resources, that can happen, but for a given image it should happen every time it is exported,

The -4 error happens only during the darkroom edits and after some time, so the memory thing is the first thing I thought of. But this is a non-blocking error (the pixelpipe fallbacks on CPU, everything is slower but works). I have a 4 GB vRAM GPU and 32 GB of RAM, so I reset the OpenCL settings in darktable.rc first, and saw it didn't change things. 

> Also that message don't necessarily means that the retouch is crashing dt,

Yes, removing one of the 2 retouch instances I used fixed the crash during export. 

> I take that a backtrace is not being generated, so try to generate one.

I will try, but as it makes the whole OS crash (even the consoles), I'm not sure what I will be able to do. I will try to reproduce a faulty editing first.

**Comment by edgardoh** [comment]
>
> It's only since I have merged this PR with my dt's master fork that I have
> had this error,
>
Try to duplicate the issue with the official version, not your fork.

**Comment by aurelienpierre** [comment]
I haven't been able to reproduce so far and, and I didn't kept the faulty XMP file as I needed to edit the picture asap. It happened only on 36 Mpx Nikon RAW files with a heavy stack of edits, so this might have been bad luck while pushing the hadware too far. But it still seems odd since I have a beast of a computer.

**Pull request merged**
