### PR TITLE
When we compress the history we need to keep the current selected module

### PR DESCRIPTION
**Pull request by TurboGit**
Fix history_end after a compress action.

### CODE REVIEW

**Comment by TurboGit** [comment]
Tested these last days, and fixing a bug. Will merge.

**Comment by houz** [comment]
I see several problems with that patch.
* You are just looking for operation, that will most likely fail when multi instances are used.
* You are using the result from sqlite in g_strclpy without checking if sqlite3_step worked.

Instead I would do the delete query, then count how many entries are left with num < history_end and use that as the new history_end after removing the holes in num.

**Comment by TurboGit** [comment]
@houz, ok I look at this.

For the first point I'm not sure we have a problem since we are looking for the top operation with the higher num. Won't that work with multi-instance?

**Comment by houz** [comment]
Why do you need the operation at all? You are deleting everything above history_end, so the biggest num + 1 is what you need. Do I miss anything?

**Comment by TurboGit** [comment]
@houz, exactly my thinking, not sure why I did that :) Maybe because with the old bug some random history item were selected and I was highly confused! Anyway I have prepared a new branch this morning. I create a pull request in a moment. Please review. Thanks.

**Pull request merged**
