### PR TITLE
thumb : refine cross/stars positions

### PR DESCRIPTION
**Pull request by AlicVB**
after some discussion with @Nilvus, this PR change : 
- cleanup comments, size and pos and the stars, cross and colorlabels (very slight change in fact)
- ensure that the reject cross and the colorlabels stay align on image borders instead of "moving" to center in big thumbnails

### CODE REVIEW

**Review by Nilvus — APPROVED** [review]
Just much better. Thanks!

**Comment by AlicVB** [comment]
ok, I've also fixed a bug spotted by @Nilvus about the refresh of margins in some cases...
To reproduce the bug (quoting @Nilvus ): 
1. show 4 thumbs per lines
2. set overlay to "permanent"
3. change zoom level to show 1 thumb per line
4. go to next image => OK
5. go to next image again => the margin has changed (see the stars positions for example)

**Review by TurboGit — APPROVED** [review]
Works for me, thanks! I'll add some consts.

**Comment by TurboGit** [comment]
Merged in master and darktable-3.8.x branch.

**Pull request merged**
