### PR TITLE
Suppress hidden files in import dialog

### LINKED ISSUE #11225: macOS filesystem metadata files included on import
**Update 25-02-2022 15:22:**

**Describe the bug/issue**
MacOS filesystem metadata files are included on import. These files start with `._`. Because the files end with the original file's extension, Darktable sees them as images and imports them. However, in Darktable they can't be opened and give an error.

---
**Original report:**

**Describe the bug/issue**
TIF files created by Epson Stylus SX420W/SX425 cannot be displayed in Darktable. Photos do work in macOS file explorer. 

```
Magick: Not a TIFF or MDI file, bad magic number 1280 (0x500). (/Volumes/Elements_02/Foto/2000 Divers/._00 Divers 062.tif).
[GraphicsMagick_open] image `._00 Divers 062.tif' not found
[dt_imageio_export_with_flags] mipmap allocation for `unused' failed
[dt_imageio_export_with_flags] mipmap allocation for `unused' failed
[dt_imageio_export_with_flags] mipmap allocation for `unused' failed
[rawspeed] (._00 Divers 062.tif) virtual std::unique_ptr<RawDecoder> rawspeed::RawParser::getDecoder(const rawspeed::CameraMetaData *), line 91: No decoder found. Sorry.
```

**To Reproduce**
Import the attached image.

**Expected behavior**
Show the image.

**Screenshots**
Schermafbeelding 2022-02-25 om 12 23 43

**Platform**
* darktable version : 3.8.1
* MacBook Pro (15, retina, 2015) 
* OS                : MacOS Monetery 12.1 
* Memory            : 16GB
* Graphics card     : Intel Iris Pro 1536 MB

**Additional context**
Example image that can't be shown: [00 Divers 062.tif.zip](https://github.com/darktable-org/darktable/files/8140745/00.Divers.062.tif.zip)

### PR DESCRIPTION
**Pull request by zisoft**
Trying to fix some old macOS issues...

fixes #11225

I think it doesn't make sense to display hidden files in the import dialog.

Found a strange bug: `g_file_info_get_is_hidden()` always returns 0, at least on macOS so I made an additional check if the filename starts with a `.`

### CODE REVIEW

**Comment by kmilos** [comment]
A Step in the right direction 👍

I presume there is still an issue with recursive import though?

**Comment by zisoft** [comment]
I don't think so.
This function is called recursively, so the suppression should work as well.

**Comment by kmilos** [comment]
Ok, sounded like it was UI only...

**Comment by victoryforce** [comment]
> Found a strange bug: `g_file_info_get_is_hidden()` always returns 0, at least on macOS

I don't think it's a bug. Try the following: In Terminal, run the command
```
chflags hidden /path/to/the/file
```
You can check the success of the utility with a command
```
stat -f %f /path/to/the/file
```
This command should output 32768 (it outputs 0 for non-hidden files).

After that, check what `g_file_info_get_is_hidden()` returns on that file.

Apparently, .DS_Store files in macOS do not have a hidden attribute, and the Finder does not show them because of their special function and their name being reserved.

**Comment by zisoft** [comment]
I tried on my Mac:

    chflags hidden /path/to/the/file

Finder does not show the file but `g_file_info_get_is_hidden()` still returns 0.

> Apparently, .DS_Store files in macOS do not have a hidden attribute, and the Finder does not show them because of their special function and their name being reserved.

Yes, macOS handles Unix style hidden files (filename starts with a `.` as well and does not show them. That's why I added the the check for filenames starting with a `.`

**Review by TurboGit — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
