### PR TITLE
add new blending fields to history diff

### PR DESCRIPTION
**Pull request by dterrahe**
also correct translation marking

### CODE REVIEW

**Comment by TurboGit** [comment]
Maybe not directly related but I see that for the flip module we have an entry saying "colorspace  : RGB (scene) -> RGB (display)" I have changed the default in preference. But anyway it seems that we do not want to look at the blend introspection information for module having no blending mode. Worth fixing.

**Comment by dterrahe** [comment]
For modules that _do_ have blending mode, do you want each individual module to show a colorspace change if you change the default in preferences? Otherwise, the changed default should probably be reflected in default_blendop_params. The history diff will then show any changes with regards to _your_ defaults.

**Comment by TurboGit** [comment]
> For modules that _do_ have blending mode, do you want each individual module to show a colorspace change if you change the default in preferences?

Yes, I would say so.

**Comment by dterrahe** [comment]
Now hiding blending diff if the module doesn't support blending.

I know it helps code simplification, but really, should we be allocating (and storing in database and xmp) a blend_params structure if the module doesn't support blending? A bunch of the standard modules store and load (and update from legacy) the default blending params over and over again without using them at all.

**Comment by TurboGit** [comment]
Works for me, thanks !

**Pull request merged**
