### PR TITLE
Improve checks for automatic opencl_scheduling_profile

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Whenever a new opencl device configuration is found via 'opencl_checksum'

- this might be because a card has been plugged in/out or (de)-activated in bios or
 - has been en/disabled via the device specific conf key

dt tries to find the best profiling schedule.
We should select the "very fast" or "multiple gpu" modes **only** if for
- multiple gpu we find all equally fast cards. As we keep track of device performance
  we can do that but allow a difference of 10%
- for "very fast" we select that only if very fast is found and also a single device, otherwise
  the default is likely better.

@AxelG-DE could you check?

### CODE REVIEW

**Comment by AxelG-DE** [comment]
>     * has been en/disabled via the device specific conf key

I am a bit lost on this one... How?
 
> @AxelG-DE could you check?

In between my major home-move-finishing tasks, I might find time :)

**Comment by jenshannoschwalm** [comment]
@TurboGit i think we should try it this way for 4.0

**Comment by jenshannoschwalm** [comment]
> I am a bit lost on this one... How?

```
Quick DT 4.0 OpenCL tuning reference

In Preferences - all settings are valid without a restart

darktable resouces:
 - choose large if mainly using dt in your desktop session or for export
tune OpenCL performance:
 - memory size: calculate available OpenCL memory for every device once per dt session
 - memory transfer: use pinned transfer while tiling, might improve performance depending on device
   but uses more memory
 
In darktablerc there is a conf key automatically generated for every found OpenCL device holding all
per-device settings, most of them were global thus prohibiting a per-device tuning.

You may edit this conf key, it looks like
cldevice_v4_quadrortx4000=0 250 0 16 16 1024 0 0 0.017853 or in general

cldevive_version_canonicalname=a b c d e f g h x.xxxx

 a) avoid_atomics:  (1) avoiding or (0) use atomics (Only very old devices require an avoid.
 b) micro_nap:      default 250. If using multiple devices the non-desktop device could be set to 0
 c) pinned memory:  (0) select mode by gui. (1) enforce pinned transfer. (2) disable pinned transfer
 d) clroundup wd:   both roundups have 16 as default.
 e) clroundup ht:
 f) event_handles:  safe up to 1024, (0) to disable CL events (might not report errors but faster)
 g) async mode:     if (1) device uses asnchronous dt mode, this uses more events and might be
                    unstable on old&small devices with heavy tiling and pinned transfer.
 h) disabled:       (0) enable or (1) disable device. Bad devices are marked as disabled by dt
 i) benchmark:      DO NOT edit except maybe set to 0 to enfore a CL re-benchmarking

Please note, bad device keys force a rewrite to defaults.

Note for nerds, there is another per-device key defining CL compiler options
cldevive_version_canonicalname_building=compiler options as you define
```

See h) so change it from 0 to 1 (or reverse)

**Comment by gi-man** [comment]
@jenshannoschwalm correct me if I'm wrong, but i think everytime there is a update driver for the video card, a new checksum and kernel are generated. If so, will the conf key will be performed again ? I'm not sure if I want this when Nvidia updates their driver every month. They updated the drivers yesterday, so when I get home (I'm in the cell phone), i will check.

**Comment by jenshannoschwalm** [comment]
Sorry, closing this for now, will have to think on how to do it a better way. Indeed the crc checksum is not handled in a correct way.

**Comment by AxelG-DE** [comment]
I still volunteer to be your test-engineer :)

**Pull request closed without merging**
