### PR TITLE
Disable GTK client side decoration for Windows builds

### LINKED ISSUE #3307: Darktable window cannot be resized (DT 3.0, Windows 10)
**Describe the bug**

After installing the RC of Darktable 3.0 on Windows 10, i cannot resize the main application window. Fullscreen Toggle works, and on the top border of the winow at some locations the height can be changed. On the left, right and lower border resize does not work, i.e. the mouse cursor does not change to indicate a resizable window.

**To Reproduce**
1. Install the Darktable 3.0 RC on Windows 10
2. Start
3. Try to resize Window

**Expected behavior**
The Main window should be resizable

**Platform (please complete the following information):**
 - OS: Windows 10 Pro 
 - Version 1909 (Build 18363.418)

**Additional context**
I have two monitors, one 4K at 125% Scaling and one WQHD at 100%. I changed to only one Display at 100% but nothing changed.
Already have done a fresh install with all config files of old versions deleted.

### PR DESCRIPTION
**Pull request by mbaumgae**
Disable GTK client side decoration for Windows builds to prevent main window resizing issues on Windows OS.

Fixes #3307

### CODE REVIEW

**Comment by parafin** [comment]
As a suggestion - maybe use glib wrapper g_setenv instead.

**Comment by mbaumgae** [comment]
Thanks @parafin for the code suggestion

**Comment by peterbud** [comment]
Should it be only for the Windows platform? Or the other platforms are OK with disabling CDS?

**Comment by mbaumgae** [comment]
I think the other platforms should be ok with the current GTK default CSD behavior, which is enabled by default as far as I understand. So this PR only affects the Windows build. This should provide more independence from the decision of the MSYS-team, whether to incorporate the CSD patch or not.

**Comment by parafin** [comment]
It's inside #ifdef _WIN32, so this PR is OK.

**Comment by peterbud** [comment]
OK, it's inside a `#ifdef _WIN32`, but _within_ a conditional block which is executed **only** when redirect is needed. I think this environment variable should be set irrespective of whether output redirection is needed or not.

**Comment by mbaumgae** [comment]
Thanks @peterbud for this catch!

**Pull request merged**
