### PR TITLE
[presets] allow mass preset export

### LINKED ISSUE #2383: Usability: export all dtpresets
if switching between different test data.db an export function for all presets in one step would be helpful, to simplify reconstruction of a brand new test environment from scratch.

### PR DESCRIPTION
**Pull request by johnny-bit**
Allow export of all user-defined presets

Additionally allows import of multiple presets at once

Fixes #2383

### CODE REVIEW

**Comment by TurboGit** [comment]
Works for me, we need a bit of CSS to add a little margin between the export/import buttons at the bottom of the window though.

@johnny-bit : can you do that ? @Nilvus : may help if you are not fluent in CSS.

**Review by TurboGit — CHANGES_REQUESTED** [review]
Some CSS work needed.

**Comment by johnny-bit** [comment]
CSS done :D

**Comment by TurboGit** [comment]
Works for me. I have planned this for 3.6 but maybe we could have this in 3.4.1 or later, that's your call.

**Comment by johnny-bit** [comment]
3.6 is fine for me for this small thingie. 3.4.1 is cool too - it's relatively small change. Either way I have to make PR for dtdocs...

**Comment by johnny-bit** [comment]
dtdocs pr here: https://github.com/darktable-org/dtdocs/pull/185

**Pull request merged**
