### PR TITLE
Fujifilm X-S10 WB presets.

### PR DESCRIPTION
**Pull request by floemker**
Data was extracted with wb_extract.pl.

### CODE REVIEW

**Comment by johnny-bit** [comment]
`wb_extract.pl`? We don't have that one... We do have [`extract_wb.py`](https://github.com/darktable-org/darktable/blob/master/tools/extract_wb.py)

Usually the camera manufacturer is CamelCase as seen with other Fujifilm cameras. Can you confirm all those presets work and are available in wb module for raws taken with X-S10?

**Comment by floemker** [comment]
wb_extract.pl was used at

    https://www.darktable.org/2012/10/whats-involved-with-adding-support-for-new-cameras/

I originally  used the newest version

    # $Id: wb_extract.pl,v 1.9 2014/09/16 02:15:18 nkbj Exp $

But I now repeated the process with extract_wb.py. That gave besides rounding the same
values, but used different formatting and CamlCase.

**Comment by johnny-bit** [comment]
YEah, that article is OLD, newest instructions are on wiki: https://github.com/darktable-org/darktable/wiki/Camera-support :)

Overall looks good now :)

**Review by TurboGit — APPROVED** [review]
Thanks !

**Pull request merged**
