### PR TITLE
iop module gui focus shortcuts

### PR DESCRIPTION
**Pull request by elstoc**
adds a new "focus module" shortcut to all iop modules to toggle gui
focus and allows control-click on the module enable button to also
toggle gui focus for the module (since this icon is now used to show
focus- as well as enabled-state for modules)

this is probably also a reasonable alternative solution for #4608 and
gives the user the choice of showing crop & rotate gridlines (by
assigning focus) or not prior to executing another module shortcut

for crop & rotate the focus toggle also works as an alternative 'commit'
button/shortcut

### CODE REVIEW

**Comment by elstoc** [comment]
Possibly resolves #3481, though this would require two shortcuts rather than one

**Comment by TurboGit** [comment]
Ok, let's go with that. We can then move guides without deploying the module on all modules having them like vignette, crop&rotate, graduiatednd...

**Comment by elstoc** [comment]
Thanks @TurboGit. I'm happy to close #4608 based on that, but I didn't raise the issue which inspired it so I'm not sure. What do you think?

**Comment by TurboGit** [comment]
Yes I'll close #4608 for now.

**Pull request merged**
