### PR TITLE
Changes to Crop/Rotate Apsect Ratio Menu

### PR DESCRIPTION
**Pull request by markfeit**
(Near-verbatim from item posted to darktable-devel.  Code differs slightly from posted patch:  fixes a bug and improves the sort order change.)

This patch makes some changes to the Crop and Rotate plugin's aspect menu:

* Adds a handful of new built-in ratios.

* Adds alternate names to some existing ratios (e.g., "5:4" now shows "5:4, 4x5, 8x10").

* Formats all aspect ratios except those that can't be quantified (freehand, original image) to add the aspect ratio relative to 1 formatted to two decimal places (e.g., "CinemaScope 2.35"). Putting the ratio at the end makes the menu more visually-appealing since entries are right-justified. I'm a former Bibble/AfterShot user and found that having the x:1 ratios in a column makes it easier to spot things in the menu if you already have the ratio in your head.

* Changes the sort order from least-square-first to most-square-first. This puts some of the more-obscure ratios like CinemaScope and Golden Cut further down on the list and more common ones like 8x10 and 5x7 further up. (This one's probably a matter of personal preference.)

### CODE REVIEW

**Comment by sebix** [comment]
To bring the discussion of the naming `ISO 216, DIN 476, A4` up again: I would omit the `4`. The ratio is the same for all A0 up to A10, it's not specific to A4.
Also, what about adding the ratio itself? `ISO 216, DIN 476, A, √2:1`
For the golden mean, giving the ratio itself is not so easy.

* `cinemascope` → `cinemascope, 2.35:1`
* `ISO 216, DIN 476, A4` → `ISO 216, DIN 476, A, √2:1`
* `widescreen` → `widescreen, 1.85:1`
* `anamorphic` → `anamorphic, 2.39:1`

I can't give a statement on the code changes.

**Comment by markfeit** [comment]
There are 11 each of DIN/ISO  A, B and C sizes, all based on different dimensions for the "0" size but having the same ratio.  I stuck A4 in there because it's familiar to the rest of the world as "Letter" is to Americans.  (Being American, I don't have a horse in this race other than getting this patch in.)  Anything that makes the entry easily recognizable to most people without cluttering it up is fine by me.

The change I made to the code calculates the aspect ratio as x:1 and appends the result formatted to two decimal places to every entry (see screenshot below).  This makes all of the entries uniform and prevents anyone adding to ratios in the code (which, honestly, should really be in a file distributed with DT instead of hardwired) or in their own personal list from having to calculate and format it.

screenshot-6

The code works; I've been using it since before I submitted the patch.

**Comment by pmjdebruijn** [comment]
I like the new ratio sorting... 

But I don't think these cinema aspect ratios belong in darktable at all. Our presets should be whatever most people would use for photography purposes. Cluttering the menu up with irrelevant aspect ratios isn't an improvement. Keep in mind that people who want these aspect ratio can still enter them manually.

**Comment by markfeit** [comment]
Relevance is in the eye of beholder, and even that's getting blurry.  I have no clue why the "10:8 in print" ratio is there (much less why it's 1.2:1), but I also do a lot of crops at the CinemaScope and HDTV ratios.  The latter is starting to show up as a standard print and frame size, which makes it jump out of cinema and into photography.

Ideally, which of the built-in ratios included in the menu would be a configuration item and the user could add custom items directly from the UI and have them stored in the per-user config.  Maybe I'll take that on as my next project.

In the mean time, what's a reasonable target number?  The menu stands at 19 including the two we can't get rid of (original and freehand).  I'd have called 20 too many but could be convinced to cut it back to a smaller number.  For my money, 10:8 in print and Golden Cut are easy to throw out the window, and I could be talked into cutting out a couple of the cinematic sizes if HDTV, Widescreen and Anamorphic stay.

**Comment by LebedevRI** [comment]
@markfeit 
> Ideally, which of the built-in ratios included in the menu would be a configuration item and the user could add custom items directly from the UI and have them stored in the per-user config. Maybe I'll take that on as my next project.

You can already do that: ae36f035e1496b8b8befeb74ce81edf3be588801

**Comment by markfeit** [comment]
Meant something a little more user-friendly than that.  At any rate, let's get this one done with.

**Comment by boucman** [comment]
I personally think that A4 is better than A on its own. it's the most common paper size and will be  recognized by the people that are used to DIN standards. I never heard of our paper formats be called A or A family or anything like that, so A on its own won't be easily understood, whereas A4 will be recognized instantly.

The other formats (B and C) are much less used and the few people that would know about them would probably know enough about the DIN standard to recognize them as DIN and know that they have the same ratio than the A family.

In other word : people that know the DIN standard won't be helped by having A, B, C listed next to it, and people that don't wouldn't recognize A on its own as "the common paper format ratio"  so A4 sounds a good idea to me...

**Comment by houz** [comment]
Just to chime in, adding aspect ratios to the config is mostly there as a backend, a nice GUI to manage those can still be added.

**Comment by TurboGit** [comment]
I like this new sorting.

**Pull request merged**
