### PR TITLE
Denoise profiled: change default to wavelets

### LINKED ISSUE #7018: [denoise (profiled)]  change default to wavelet-auto
**Is your feature request related to a problem? Please describe.**

As discussed previously on IRC with @rawfiner:
Today the default of denoise (profiled) is non-local-means (NLM).

**Describe the solution you'd like**

The module denoise (profiled) has such brilliant results when using in wavelet-auto mode, that I would appreciate, this could be the new default.

**Alternatives**

quicky is an auto applied preset in "switch-off" state. Still there are scenarios, where the default remains the default (accels, midi-board, reset)

**Additional context**

### PR DESCRIPTION
**Pull request by rawfiner**
Fixes #7018

### CODE REVIEW

**Review by TurboGit — COMMENTED** [review]
I don't understand the change in legacy and having a new version ? The default to wavelet-auto should only happen for new edits... Or am I missing something ?

**Comment by rawfiner** [comment]
Yes indeed, there was some discussion about it in the issue, but I should have explained that here as well sorry. As wavelets in Y0U0V0 require higher strength, I made a change so that with a strength of 1 it produces an already quite denoised result, like the module does in the other modes

**Comment by rawfiner** [comment]
Strength is basically multiplied by 2.5 internally, and only for wavelets in Y0U0V0 mode

**Comment by TurboGit** [comment]
@rawfiner : That's my fault too, I looked at the whole change but it is clear when looking at the 2 commits separately :)

**Review by TurboGit — APPROVED** [review]
Works for me, thanks !

**Comment by rawfiner** [comment]
Thank you :-)

**Comment by elstoc** [comment]
The documentation currently discusses the possibility that the default strength might be insufficient. Should we just remove that text or should there be some discussions about differences between versions?

**Comment by rawfiner** [comment]
I think if there will be one documentation for each version, then we can remove that text completely, but either option is fine for me

**Comment by EC1000** [comment]
> Strength is basically multiplied by 2.5 internally, and only for wavelets in Y0U0V0 mode

If I have already-existing presets with wavelets in Y0U0V0 mode, does it change something / should I update some parameters (when updating to 3.8/master with this commit)?

**Comment by rawfiner** [comment]
@EC1000 the module updates the strength automatically so that old edits keep the same effect

**Comment by todd-prior** [comment]
@rawfiner @dtorop @TurboGit   If denoise profiled is enabled with wavelets or auto wavelets the colorpicker selects black...Toggle to nlm or nlm auto it comes back...must be some interaction going on....

note the point picker marker with black square..  
image
NLM 
its fine
image

**Comment by todd-prior** [comment]
I’m on a newer build and it seems fine now…I wonder if there was a glitch, certain combination of modules or just that version of the picker code which has been getting a lot of updating recently. I will loop back but I think its okay currently…..

**Pull request merged**
