### PR TITLE
import: open in darkroom when [add to library] a unique image

### LINKED ISSUE #8915: Double-click in import-in-place doesn't work
Ubuntu 18.04   dt 3.5.0+1966~g12d7a9967-dirty

If I select a raw in the right-hand panel of "import in-place", double-click has no effect, whereas pressing Enter brings it into lighttable as expected.

### LINKED ISSUE #9363: Import to library with a single image should open it
**Is your feature request related to a problem? Please describe.**

When importing a single image to library, in a collection or folder that already contains images (let's say my `~/Downloads` folder), it gets lost in the collection. I have to find it manually.

**Describe the solution you'd like**

If only a single image is imported, open it straight in darkroom.

**Alternatives**

At least, center the lighttable view on the recently imported image.

### PR DESCRIPTION
**Pull request by phweyland**
fixes #9363
fixes #8915

### CODE REVIEW

**Comment by TurboGit** [comment]
I tried many time and never got into the darkroom after importing a single image. Maybe a recent regression due to merging ?

**Comment by phweyland** [comment]
I'll retest that.

**Comment by phweyland** [comment]
Cannot reproduce any more. What is your action ? select and enter or double-click ?

**Comment by johnny-bit** [comment]
Ok... So it worked for me the first time but didn't the second... weird...

**Comment by phweyland** [comment]
As the dt_control_job_wait() is not effective (my fault), success or failure to open in darkroom was depending on the speed of the image import.
The new code may not be very elegant but I don't make it fail any more.

**Comment by johnny-bit** [comment]
> EDIT: But Travis doesn't like the code ...

```
/home/runner/work/darktable/darktable/src/src/control/jobs/control_jobs.c:2290:5: fatal error: releasing mutex 'data->wait_mutex' that was not held [-Wthread-safety-analysis]
    dt_pthread_mutex_unlock(data->wait_mutex);
    ^
1 error generated.
```

Yeah - LLVM thread safety... compile time analysis if the threading makes sense to it.

**Comment by phweyland** [comment]
> LLVM thread safety... compile time analysis if the threading makes sense to it

makes sense for thread exclusion but not for signaling...
g_signal is also a bit complex (9 parameters to create a new one...).

Anyway at the end the code is quite simple.

**Review by TurboGit — APPROVED** [review]
All good now, thanks !

**Pull request merged**
