### PR TITLE
nlmeans_core: replace SIMD_FOR with for to improve performance

### PR DESCRIPTION
**Pull request by n0s0r0g**
CPU: Intel(R) Core(TM) i7-6700
Threads: 4
Build: Release, SSE2-optimized codepaths disabled
Compiler: `gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`

Test: `0020-denoise-nlmeans`

**pixel pipeline** processing took:
`SIMD_FOR`: 7.9s (7.927; 7.889; 7.897)
`for`: 5.3s (5.285; 5.337; 5.272)

**CPU time** for [Loop at line 473 in nlmeans_denoise._omp_fn.0]
_Measured by Intel VTune Profiler_
`SIMD_FOR`: 19.010s
`for`: 7.424s

Test: `0035-multiple-modules`

**pixel pipeline** processing took:
`SIMD_FOR`: 11.514s (11.494; 11.536; 11.512)
`for`: 10.118s (10.135; 10.118; 10.101)

**CPU time** for [Loop at line 489 in nlmeans_denoise._omp_fn.0]:
`SIMD_FOR`: 24.540s
`for`: 18.068s

### CODE REVIEW

**Comment by ralfbrown** [comment]
Weird.  SIMD_FOR is just the equivalent of writing
```
    #ifdef _OPENMP
    #pragma omp simd
   #endif
   for
```
So what your change does is merely remove the hint to the compiler that the loop is vectorizable....   I'd love to see the generated assembly for the two cases to figure out what's going on there.

**Comment by n0s0r0g** [comment]
`for` loop:
```
Address Source Line Assembly
0x144184	481	vmulss xmm4, xmm0, dword ptr [r8]
0x144189	481	vmulss xmm3, xmm0, xmm3
0x14418d	481	vmulss xmm1, xmm0, xmm1
0x144191	481	vaddss xmm0, xmm0, dword ptr [rcx+0xc]
0x144196	481	add rcx, 0x10
0x14419a	481	vaddss xmm4, xmm4, dword ptr [rcx-0x10]
0x14419f	481	vaddss xmm3, xmm3, dword ptr [rcx-0xc]
0x1441a4	481	vaddss xmm1, xmm1, dword ptr [rcx-0x8]
0x1441a9	481	vmovss dword ptr [rcx-0x10], xmm4
0x1441ae	481	vmovss dword ptr [rcx-0xc], xmm3
0x1441b3	481	vmovss dword ptr [rcx-0x8], xmm1
0x1441b8	481	vmovss dword ptr [rcx-0x4], xmm0
```

`SIMD_FOR` loop:
```
Address	Source Line	Assembly
0x14418b	478	mov rax, r8				
0x14418e	478	sub rax, r9				
0x144191	478	vmovss xmm1, dword ptr [rax+r14*1]				
0x144197	478	mov dword ptr [rbp-0x44], 0x3f800000				
0x14419e	478	vmovss dword ptr [rbp-0x50], xmm1				
0x1441a3	478	vmovss xmm1, dword ptr [r8]				
0x1441a8	481	vshufps xmm0, xmm0, xmm0, 0x0				
0x1441ad	478	vmovss dword ptr [rbp-0x4c], xmm1				
0x1441b2	478	vmovss xmm1, dword ptr [rax+rcx*1]				
0x1441b7	478	add rsi, 0x4				
0x1441bb	478	vmovss dword ptr [rbp-0x48], xmm1				
0x1441c0	481	vmulps xmm0, xmm0, xmmword ptr [rbp-0x50]				
0x1441c5	481	add r8, 0x10				
0x1441c9	481	add rdi, 0x10				
0x1441cd	481	vaddps xmm0, xmm0, xmmword ptr [rdi-0x10]				
0x1441d2	481	vmovups xmmword ptr [rdi-0x10], xmm0				
```

**Comment by ralfbrown** [comment]
So the compiler *is* generating vectorized code only in the case with the hint, but clearly the extra shuffling to get things where they need to be to use vector instructions outweighs the benefit.  Looks like the optimizer's cost model is incorrect for your CPU.

**Comment by n0s0r0g** [comment]
I guess the hint misleads the compiler that is it beneficial to vectorize. I can't blame the compiler for 2.5x faster loop code if we compare CPU time. Do you expect performance degradation on other CPU's?

By the way, `0020-denoise-nlmeans` test has the highest performance degratation with SSE2-optimized codepath disabled:
native: `2.71` sec (2.708; 2.729; 2.703)
native-no-sse2: `7.9` sec (7.927; 7.889; 7.897)

**Comment by aurelienpierre** [comment]
@ralfbrown The `SIMD_FOR` macro is not a good idea, in my opinion, since you need to additionnaly declare `aligned(buffer:16)` or `aligned(buffer:64)` for the compiler to actually make a clever use of the vectorization. I have also, in the past, witnessed degraded performance with `simd for` when the alignment is not declared (and it's referenced in many OpenMP tutos all around).

**Comment by n0s0r0g** [comment]
It looks like vectorized versions are slower due to "Loads Blocked by Store Forwarding" issue.

**Comment by ralfbrown** [comment]
OK, I see what's happening in those two cases -- the writes to the pixel[] array aren't being optimized away into a load of an xmm register, so we have four 32-bit memory writes in flight at the time of the 128-bit memory read that the loop got vectorized into.  What is the performance like if we simply move the setting of pixel[] _before_ the computation of `wt`?
```
              const float *const inpx = in+4*col;
              const float DT_ALIGNED_ARRAY pixel[4] = { inpx[offset],  inpx[offset+1], inpx[offset+2], 1.0f };
              distortion += (col_sums[col+radius] - col_sums[col-radius-1]);
              const float wt = gh(distortion * sharpness);
              SIMD_FOR (size_t c = 0; c < 4; c++)
              {
                out[4*col+c] += pixel[c] * wt;
              }
```
I just checked, and GCC8 leaves the stores to `pixel` before the `wt` computation.

**Comment by n0s0r0g** [comment]
Test: `0020-denoise-nlmeans`

`SIMD_FOR_new`: 7.476s (7.527; 7.443; 7.458)
`for_new`: 5.343s (5.331; 5.366; 5.332)

Previous measurements:
`SIMD_FOR`: 7.9s (7.927; 7.889; 7.897)
`for`: 5.3s (5.285; 5.337; 5.272)

**Comment by ralfbrown** [comment]
OK, it helps, but there obviously still isn't enough time between the last write to `pixel` until it gets read as a unit.
Will have to think about this.

**Comment by ralfbrown** [comment]
I've tried a number of variations, and found one that makes GCC8 use a vector register for pixels[4], but in all the variations I tried, my 3rd-gen Threadripper showed exactly the same time within measurement error (so it's not being affected by the Loads Blocked by Store Forwarding).  That's SIMD_FOR, plain `for`, rearranging the setup of `pixels` before the computation of `wt`, etc.

Here's what worked:
```
   const float DT_ALIGNED_PIXEL pixel[4] = { inpx[offset],  inpx[offset+1], inpx[offset+2], 1.0f };
#pragma omp simd aligned(pixel, out:16)
    for (size_t c = 0; c < 4; c++)
```
GCC's optimizer did miss out on an optimization, however: it loads pixel[] into a vector register, inserts the four floats, then stores it back.  But it then uses that vector register as one of the args to the multiplication, so it doesn't need a memory read.

**Comment by n0s0r0g** [comment]
Test: `0020-denoise-nlmeans`
`omp_simd_ver2`: 4.745 (4.747; 4.749; 4.740)

This version is faster.

**Pull request closed without merging**
