### PR TITLE
Rawspeed: Rs-identify: CMakeLists.txt: properly link against JPEG and Pugixml. Fixes #11133

### PR DESCRIPTION
**Pull request by mazhe**
I have issues on OSX due to the fact there is a target_link_libraries call that result in "-lpugixml -ljpeg" compiler arguments when it could/should use what was returned by the find_package() calls (like what is used to link libdarktable & other binaries).

Here is a small patch to fix this.

Thanks

### CODE REVIEW

**Comment by mazhe** [comment]
(This should fix <https://redmine.darktable.org/issues/11133>)

**Comment by LebedevRI** [comment]
Are you sure this does not also need
```
  include_directories(SYSTEM ${JPEG_INCLUDE_DIRS})
  include_directories(SYSTEM ${Pugixml_INCLUDE_DIRS})
  add_definitions(${JPEG_DEFINITIONS})
```
?

**Comment by mazhe** [comment]
It seems this is not necessary because it's done in the CMakeList.txt file in src... but that could not hurt maybe?

**Comment by LebedevRI** [comment]
Ah right.

**Comment by LebedevRI** [comment]
@mazhe i hope you are not on osx 10.6, because i'm about to break it by hard-requiring C++11.

**Comment by mazhe** [comment]
Not a problem at all, when I'm on my macbook, I also tend to use the best available llvm package from macports (if only to get openmp support). There however an issue with another osx specific function (the one that retrieve the version), but I need to test my fix a bit more.

**Pull request merged**
