### PR TITLE
Fix picker leave

### LINKED ISSUE #7153: Segmentation fault with color picker and switching to lighttable
When testing #7152, it seems that there is a possibility to have a segmentation fault when performing a color pick and switching to lighttable at the same time. This is not 100% reproducible as it could take several tries to make it happen.

**To Reproduce**
1. Select an image and go to darkroom
2. Use the white balance "spot"
3. Change the region one or more times
4. After changing a region, but before the picker color has been applied, press `L` to switch to lighttable
5. darktable can crash (sometimes)

**Expected behavior**
darktable shouldn't crash :wink: 

**Platform:**
 - darktable version: could reproduce with darktable master 3eb2253b956aadfaad885919138174c28b4af3d0 (with and without #7152)
 - OS: Ubuntu 18.04
 - Could reproduce it both with OpenCL code path and CPU code path

**Additional context**
- Crash log with a tiff file [crash-1.log](https://github.com/darktable-org/darktable/files/5625772/color-picker-crash-1.log)
- Crash log with a raw file [crash-2.log](https://github.com/darktable-org/darktable/files/5625773/color-picker-crash-2.log)
- Crash log with CPU code path [crash-3-cpu.log](https://github.com/darktable-org/darktable/files/5625776/color-picker-crash-3-cpu.log)

**First analysis**
It looks like there is a race condition between the clean up performed when exiting darkroom and the color picker callback. The error happens either in `_iop_color_picker_signal_callback` (`src/gui/color_picker_proxy.c:245`) when dereferencing `dev` or later `_iop_color_picker_signal_callback` → `_iop_color_picker_apply` (`src/gui/color_picker_proxy.c:97`) → `_iop_record_point_area` (`src/gui/color_picker_proxy.c:46`) when dereferencing the module picker (which has probably been cleaned up).

`dt_iop_color_picker_init` seems to be currently called in `dt_gui_gtk_init` so when darktable is initialized, and `dt_iop_color_picker_cleanup` seems not to be called. Perhaps those methods should be called when entering and leaving darkroom?

### PR DESCRIPTION
**Pull request by dterrahe**
fixes #7153

@ralfbrown as you have done a lot of work on pipes/locks/threads, maybe you've got a better solution to avoiding the case where gtk_widget_queue_draw gets called on a widget that has just been deleted? The solution implemented here involves connecting and disconnected a signal every time dt_control_queue_redraw_widget gets called and it is used in 42 locations. Probably many of those could directly use gtk_widget_queue_draw because it is clear that they are in the same gui thread. But using dt_control_queue_redraw_widget everywhere has the appeal that one doesn't need to worry about that. Until something like this introduces a penalty for the extra robustness.

### CODE REVIEW

**Comment by ralfbrown** [comment]
While I have no knowledge of Gtk, this sounds like a race condition on a pointer variable.  The proper way to handle that is to atomically exchange the pointer for NULL before doing the deletion, assuming that the Gtk code itself will then properly deal with a NULL pointer.  A quick search indicates the following should work (but not tested):
```
    GtkWidget* foo;
    #pragma omp atomic capture
   {
    foo = picker->widget;
    picker->widget = NULL;
    }
    if (foo) GtkDestroy(foo);
```
(the braces are required to make the pragma apply to both assignments)

**Comment by dterrahe** [comment]
Ah, but what happens here is not a race during such a very short period. What does happen is that the pipe has calculated some results for a module that need to be shown in a widget in that module. But the widget/gui loop runs in another thread. So `dt_control_queue_redraw_widget `queues an event in that thread to request a widget redraw. But there already could be other events ahead of it in that queue; for example a keypress L that switches to lighttable after destroying all the darkroom widgets. So by the time the redraw is requested, the widget doesn't exist anymore.

For this particular case, one could make a dedicated `dt_control_queue_redraw_widget` that only applies to darkroom widgets and that first checks if we are still in the darkroom. But that would again mean that users carefully have to consider which call to use. In which case it would be just as easy to check the 42 calls to `dt_control_queue_redraw_widget `and see which don't really need it...

**Comment by ralfbrown** [comment]
I see.  So we'd want to cancel the pending events before destroying the widget, but even that still leaves races if one had been dispatched but not yet processed by its handler....
Sorry, I'm out of ideas for now.

**Comment by dterrahe** [comment]
The solution I pushed works, I think. I mean, it works in the sense that it hasn't crashed for me yet, but also, I think this is how it is supposed to work. It is just that it is a bit expensive, (dis-)connecting signals all the time, if we use it all over the place where not needed (i.e. if we could have done gtk_widget_queue_draw directly becasuse the widget is definitely still alive in the same thread).

I found an alternative, cheaper, approach using  `g_idle_add((GSourceFunc)gtk_widget_queue_draw,(void*)widget);` matched with a `g_idle_remove_by_data(module->widget)` in `dt_iop_gui_cleanup_module`. This seems to work much better than nothing, but I still manage to get occasional crashes.

**Comment by dterrahe** [comment]
@TurboGit who would you suggest could opine on this? Would be nice to have this crashing bug fixed before 3.4 (without too many side effects to worry about).

**Comment by dterrahe** [comment]
> This seems to work much better than nothing, but I still manage to get occasional crashes.

Turns out that multiple delayed queue redraws could get lined up, so they all needed to be removed. After adding a while loop it now seems to work.

**Comment by TurboGit** [comment]
> @TurboGit who would you suggest could opine on this? Would be nice to have this crashing bug fixed before 3.4 (without too many side effects to worry about).

I fear that you are our best expert on Gtk stuff at this time. Maybe @parafin or @AlicVB ? I'm certainly out for this :)

**Comment by TurboGit** [comment]
Just looked at the code and it seems simple enough to be merged. I'll see next week (maybe tomorrow) for testing.

**Comment by TurboGit** [comment]
Looks good, I was not able to make dt crash and the pickers seems to work as expected (tested in many modules).

**Pull request merged**
