### PR TITLE
Spanish translation update

### PR DESCRIPTION
**Pull request by EdgarLux**
No untranslated strings, only left some fuzzy strings.

### CODE REVIEW

**Comment by TurboGit** [comment]
Right, better:
`4716 translated messages, 62 fuzzy translations.`

The 62 fuzzy should be easier to translate. Should I merge this PR or wait for the update?

**Comment by EdgarLux** [comment]
> Right, better: `4716 translated messages, 62 fuzzy translations.`
> 
> The 62 fuzzy should be easier to translate. Should I merge this PR or wait for the update?

Yes, in fact I am about to finish the last 22 chains. It won't take long. Thank you.

**Comment by EdgarLux** [comment]
Finally, all strings are translated. This PR is ready for merge. Thank you.

**Review by TurboGit — APPROVED** [review]
Thanks! And I confirm that the translation is 100% done.

**Pull request merged**
