### PR TITLE
wb_presets: add Nikon Z 6_2

### LINKED ISSUE #14182: White balance support of Nikon Z6 ii
Attached are finetuned (with step 1.0) white balance presets for Nikon Z 6_2 camera. 

[darktable-whitebalance-20230411.tar.gz](https://github.com/darktable-org/darktable/files/11204878/darktable-whitebalance-20230411.tar.gz)
For noise profiles, please also attach the entire archive with `.pdf` plots.

### PR DESCRIPTION
**Pull request by kmilos**
Resolves #14182

### CODE REVIEW

**Comment by TurboGit** [comment]
Likewise, I restarted it and it still fails. On MacOS it seemed to me that the disk was full in previous run.

**Comment by kmilos** [comment]
Same failure mode on all 3 platforms - seems to compile fine to the end, and then something goes wrong...

Anyway, could be on GH side, lets wait a couple of more hours/days and try again...

**Comment by kmilos** [comment]
Ah, it actually is this change:
```
FAILED: share/darktable/CMakeFiles/validate_wbpresets_json D:/a/darktable/darktable/build/share/darktable/CMakeFiles/validate_wbpresets_json 
```

I'll have to try to figure out why, not obvious right now...

**Comment by kmilos** [comment]
Ok, should be good to go now @TurboGit 

Still a few kinks in that script...

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
