### PR TITLE
imageio: use only valid data window for EXRs

### PR DESCRIPTION
**Pull request by kmilos**
Resolves https://github.com/darktable-org/darktable/issues/14136

@eoyilmaz @pitbuster Please test if possible.

### CODE REVIEW

**Comment by eoyilmaz** [comment]
nice 👏

**Comment by TurboGit** [comment]
> I was going to wait for confirmation if this is now the desired behaviour, but here goes: wink

You mean that the reply from @eoyilmaz is not definitive? I thought he had validated this patch, sorry.

**Comment by kmilos** [comment]
Nope, he just got excited I guess and replied before the CI told me I had a mistake in there... 😉

**Comment by eoyilmaz** [comment]
> Nope, he just got excited I guess and replied before the CI told me I had a mistake in there... 😉

sorry guys for creating the confusion, yeah it was me just getting excited, I don't have the means of compiling it in my Macbook Pro for now, but I can check it under my fedora workstation later today 👍

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
