### PR TITLE
imageio_libraw: skip dcraw_process()

### PR DESCRIPTION
**Pull request by kmilos**
@cytrinox @matt-maguire please review and test

Continuing from https://github.com/darktable-org/darktable/pull/10442#issuecomment-975253550

### CODE REVIEW

**Comment by kmilos** [comment]
There is one downside w/ this approach: the white level is inexact (bit depth max by default), as is the usual case w/ all Canons, hence the need for a database of Canon white level per ISO we don't have here (dt relies on rawspeed for this). As a result, highlights might come out magenta on load.

OTOH, in the original approach, dcraw_process() updates it w/ actual data measurement, but the black level is also substracted from all the levels after the processing, so we were actually clipping more than necessary.

**Comment by cytrinox** [comment]
@kmilos The actual white level is stored in CTMD track in CR3 which I use for the DNG converter. I expected that libraw does the same to get it. Maybe it's somewhere in the Canon-specific metadata fields in libraw structure?

**Comment by kmilos** [comment]
I'm not familiar with the CR3 boxes/tracks, nor Canon's makernotes. Not sure what libraw actually puts in its `rawdata.color.maximum`, maybe you can have a closer look at [LibRaw::parseCR3()](https://github.com/LibRaw/LibRaw/blob/5bc2c67456fa759c11b41af635a37112d03d8eaf/src/metadata/cr3_parser.cpp#L112) if you're more familiar w/ Canon and CR3, that's the function being called eventually by libraw_open_file() early on...

**Comment by kmilos** [comment]
Ok, I think we want to use either [NormalWhiteLevel or SpecularWhiteLvel from the makernotes](https://github.com/LibRaw/LibRaw/blob/2a9a4de21ea7f5d15314da8ee5f27feebf239655/src/metadata/canon.cpp#L1238); no idea what those mean for Canons though, any preference? Maybe go for specular, as that one is also used to set `linear_maximum`?

**Comment by kmilos** [comment]
And IMHO we definitely don't need to manually change the order of WB coeffs, as libraw handles this (and black/white levels) through the `RGGB_2_RGBG` reordering macro...

**Comment by piratenpanda** [comment]
So whitepoint is now 14888 instead of 16384 for ISO 200 for the R5. I wonder why the values are so different

**Comment by kmilos** [comment]
> So whitepoint is now 14888 instead of 16384

1638**3** is the default simply derived from bit depth (2^14-1), and AFIAK never the correct value for Canons, they always seem to have a lower white point value depending on ISO, see e.g. [5DM4](https://github.com/darktable-org/rawspeed/blob/e5a947ce230a9c487f9d2499f8a76b23958c840c/data/cameras.xml#L701-L720).

**Comment by piratenpanda** [comment]
Makes sense. I only compared to the values from rawspeed here https://github.com/darktable-org/rawspeed/pull/271/files

**Comment by kmilos** [comment]
Maybe nobody got around to actually measure/confirm/update them for that rawspeed patch?

In any case, these are now coming straight from the camera metadata...

How about the NormalWhiteLevel value (see e.g. exiftool) for that camera? Though I'd be surprised it would be higher than SpecularWhiteLevel...

**Comment by piratenpanda** [comment]
For the picture I get 14888 in SpecularWhiteLevel from your patch and NormalWhiteLevel from exiftool says 13535

**Comment by kmilos** [comment]
Thanks for checking, it all seems good to me...

**Comment by piratenpanda** [comment]
On a first glance the new way looks more natural to me, but I also don't know what to look for to check

**Comment by kmilos** [comment]
> On a first glance the new way looks more natural to me

Could also be the fix for white balance coeffs ordering, you can also check the color temp before and after this patch.

**Comment by TurboGit** [comment]
> On a first glance the new way looks more natural to me, but I also don't know what to look for to check

Same on my side. The white-balance was off in some pictures and some were too cold others too warm. Now all of them seems well balanced. To me this is a real improvement.

**Comment by cytrinox** [comment]
Whitelevel and WB coeffs are the same as for Adobe DNG converted DNGs. So looks good to me.

**Review by TurboGit — APPROVED** [review]
Good then. Thanks for reviewing @cytrinox.

**Pull request merged**
