### PR TITLE
Rewrite help section to comply with GNU CLI standards

### PR DESCRIPTION
**Pull request by fabiosirna**
Hi All,
I spent some time rewriting the darktable CLI help and version following the GNU Standards for Command Line Interfaces and other best practices.

Ref. https://www.gnu.org/prep/standards/standards.html#Command_002dLine-Interfaces
Ref. https://clig.dev/#introduction

This is my first PR, so be kind with criticism and feedback :)
I opened the PR in draft, because I would like to complete other parts.

**Details (work in progress)**

My intervention changes the inline help from:
image

to something more in line with GNU standards; this it output of `darktable --help|less` :
image
image
image

This is the output of `darktable --version` :
image

### CODE REVIEW

**Comment by TurboGit** [comment]
Clearly a nice improvement to me!

**Comment by fabiosirna** [comment]
Thanks @TurboGit !

I'm trying to add some colors, but the output will broken. Didn't have time to investigate too much. If you have any suggestion, please let me know (see screen below).

SCR-20230923-morq

I worked mainly on the output for darktable.
I'd like to review also the other CLI like darktable-cli.
Can I continue on this PR or better to close this and open a dedicated one?

**Comment by TurboGit** [comment]
I'm really not sure the colored output is ok, this may breaks on some consoles (Windows?). If we are going with color it must be an option disabled by default as I'm not sure there is a way to check for supported colored output.

**Comment by fabiosirna** [comment]
In the latest commit I'm using only Gray for disabled option (screenshot in the original post is updated):

```
\033[38;5;244mDISABLED\033[0m
```

ANSI colors should be standard, but ... if it's an issue I can remove them.

**Comment by victoryforce** [comment]
> ANSI colors should be standard, but ... if it's an issue I can remove them.

And the output can be redirected to some file. Text colorization is only safe when we check that the output goes to a terminal.

**Comment by fabiosirna** [comment]
@TurboGit @victoryforce you are  right, I removed the colored output, because the redirection to a file retains ANSI colors and is not readable, invalidating the effort to make all output... readable and intuitive :)

**Comment by fabiosirna** [comment]
@TurboGit Since this is my first PR, I prefer to close what I have done so far because it is complete. I tested it on my configuration (macOS) and was careful not to touch other parts of the code.

I revisited the output of ``darktable -h`` and ``darktable -v`` as per the screenshots above.

I will open another PR for the output of darktable-cli if this is approved.
Thank you and I hope I have done a good job. 
Please let me know.

**Comment by fabiosirna** [comment]
@TurboGit rebased on latest master and conflicts solved.

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Comment by fabiosirna** [comment]
Thanks, much appreciated!

**Pull request merged**
