### PR TITLE
Replace picasa by piwigo in translations

### PR DESCRIPTION
**Pull request by Mik-**

### CODE REVIEW

**Review by TurboGit — COMMENTED** [review]
I'm not sure this is right. Better let the translators really check their languages and fix that.

**Comment by johnny-bit** [comment]
@TurboGit - this isn't imo controversial ;) msgid has "piwigo" translation has "picasa", it's a bit obvious that this needs change ;)

**Comment by Mik-** [comment]
As a native german speaker, I can at least approve the german translation. I also can remove the changes of the other translations, if desired.

**Comment by TurboGit** [comment]
@johnny-bit : but maybe the whole strings may need to be changed. some language have male/feminine noun and some grammar rules may need change.

**Comment by TurboGit** [comment]
Yes please, german only is ok.

**Comment by Mik-** [comment]
Reverted the changes on the other languages.
(Sorry for too much commits, it's late)

**Review by TurboGit — APPROVED** [review]
Thanks !

**Pull request merged**
