### PR TITLE
noise profile: Add Canon EOS 5D Mark IV, fixes #11539

### LINKED ISSUE #11539: Some collections filters don't combine with "date taken" filter
The work of collections filters have changed for the worse.

On Windows 7.
Before change. Commit https://github.com/darktable-org/darktable/commit/50349bd7edca9a0a6d4b65677a49dad7c270ab29

https://user-images.githubusercontent.com/15331117/163682393-5a47b96d-e95e-4bd7-b7e6-619268935f39.mp4

When it changed. Commit https://github.com/darktable-org/darktable/commit/2ee3589a67cfb10af0732d6940135b5cb5c61c6d

https://user-images.githubusercontent.com/15331117/163682431-8bfbf7ce-ac47-43ab-b5a8-5c9e69bf1da9.mp4

That is, I select a filter (eg "film roll") and get a list of all collections. I add (AND) the "date taken" filter, choose a period and the collections list is empty.

The problem still persists.

On Debian 11 is better. Only there is no highlighting of the periods to which the found collections belong. Like there:

50349bd7edca9a0a6d4b65677a49dad7c270ab29 avi_timeline

### PR DESCRIPTION
**Pull request by dhoulder**
Profile generated by Dejan Perkovic. See
https://redmine.darktable.org/issues/11539#note-4

### CODE REVIEW

**Comment by LebedevRI** [comment]
It's not that we don't see the profiles in redmine/maillists.
It's that someone knowledgeable needs to review the plots and PDF and veto whether this profile is good to go or not.
At this moment in time i think only two persons both know how to do that and actually do that (@hanatos & @schenlap), and everyone has only so much free time...

**Comment by ArchangeGabriel** [comment]
@LebedevRI Then why have all profiles submitted to GitHub over the past year been merged while some are waiting for input on Redmine for more than one year (e.g. https://redmine.darktable.org/issues/10868)? I don’t blame you, I now what lacking of free time is very well, but PR here definitively get more attention than submission on Redmine. Why not move issues to GitHub?

**Comment by LebedevRI** [comment]
> Why not move issues to GitHub?

How does it help anything? If there is one mouth, it does not matter whether you drink your tea/coffe/water/etc from red cup or from white cup.

> Then why have all profiles submitted to GitHub over the past year been merged
> PR here definitively get more attention than submission on Redmine.

I guess the logical answer is right on the surface. As you can see, majority of these noiseprofile PR's from the last year have come from a @schenlap who has demonstrated an ability to validate noiseprofiles, thus once such a pr is up, i pretty much merge it right away.
I'm not sure what other answer you wanted to hear.

**Comment by ArchangeGabriel** [comment]
> How does it help anything? If there is one mouth, it does not matter whether you drink your tea/coffe/water/etc from red cup or from white cup.

Well to keep the analogy it appears to me you’re drinking coffee from both cups, which might not be as efficient as sticking to one. But that’s your organization after all, and as you pointed out (see below) is not the real source of the issues at hand. So…

> I guess the logical answer is right on the surface. As you can see, majority of these noiseprofile PR's from the last year have come from a @schenlap who has demonstrated an ability to validate noiseprofiles, thus once such a pr is up, i pretty much merge it right away.
I'm not sure what other answer you wanted to hear.

OK, _mea culpa_, I admit I’ve never look at who was submitting the noise PRs (I mostly just look at email notifications), neither did I ever thought it could be the same person for most of them (I was assuming that those PRs where submitted by independent people using those DSLR). So as a matter of fact you gave a perfect explanation of why someone like me being subscribed to this repo but not to the whole Redmine was having the impression of near instantaneous acceptation of profile submitted here vs Redmine. I was plainly wrong, because I did not look closely enough.

So in the end my concern is mostly to see noise profiles being submitted to Redmine and then merged here in only some days (because after looking a bit further that’s how @schenlap PR come from) while some tickets are open for months, without any explanation on them (even just a “Sorry, this profile is complicated to validate, and we lack time/people to do this right now, we’ll come back to you later” or “Those files looks strange, could you try a new attempt so that we get files easier to validate” if they actually are such kind of issues).

That being said, keep up you’re good work on this amazing software! :)

**Pull request closed without merging**
