### PR TITLE
fix #5627 (for "Auto applied WB preset is not used for thumbnail #5391")

### LINKED ISSUE #5627: Possible solution for "Auto applied WB preset is not used for thumbnail #5391"
Yes, it valid but not obvious.

At least mention in the tooltip for 'auto-apply per camera basecurve presets' that the setting is valid only when selected 'display-referred' for 'auto-apply pixel workflow defaults'.

_Originally posted by @esq4 in https://github.com/darktable-org/darktable/issues/5391#issuecomment-642761969_

### PR DESCRIPTION
**Pull request by esq4**

### CODE REVIEW

**Comment by esq4** [comment]
Yes of course. Exactly "display-referred".
_I'm sorry, I got lost in my thoughts. :(_

**Comment by esq4** [comment]
Do I need to make new pull request?

**Comment by esq4** [comment]
I'm sorry twice, I built my thoughts and (possibly) updated this request.

**Comment by TurboGit** [comment]
Looks ok now, thanks!

**Pull request merged**
