### PR TITLE
use GtkPopover for toolbar floating windows

### PR DESCRIPTION
**Pull request by dtorop**
This simplifies code and makes the toolbar floating windows Wayland compatible (see bug 11535). It also fixes a subtle bug in mouse grab behavior for bauhaus comboboxes.

In order to make things work with Wayland without jumping through too many hoops, this PR uses more GTK interfaces in lieu of low-level GDK work. But this results in UI changes:

- The floating windows are now drawn centered over the button they correspond to, and with a tail pointing to that button.
- Pressing `ESCAPE` now closes the floating window.
- On GTK+ < 3.16, there will be a close transition for the floating window
- Clicks outside of a bauhaus combobox will close the combobox. Previously they were ignored, and if the combobox was in a floating window, that floating window would not close until its toolbar button was pressed again then the user clicked outside of the re-presented floating window.
- Moving the mouse slightly outside of a bauhaus combobox previously generated "prelight" events on widgets, and those widgets would respond to mouse clicks even though a combobox and floating window was also open. Now other widgets are not sensitive to mouse clicks until after the combobox and floating window are closed. Tooltips will still appear, though.

Questions:

- GtkPopovers make the code cleaner, and push the hairy floating window implementation onto GTK. But the floating windows now look GTK-ish, rather than bauhaus-ish. Is this a good thing? (There should be ways to draw floating windows without tails, at the expense of more code complexity and being more subject to future changes in GTK/GDK).
- Should the popover implementation (now quite minimal, but it'd grow more elaborate if it goes back to using GDK) end up in src/dtgtk, rather than having the same boilerplate code repeated in multiple places?

### CODE REVIEW

**Comment by LebedevRI** [comment]
> * Pressing ESCAPE now closes the floating window.
> * Clicks outside of a bauhaus combobox will close the combobox.

👍

**Comment by dtorop** [comment]
>> - Pressing ESCAPE now closes the floating window.
>> - Clicks outside of a bauhaus combobox will close the combobox.

> 👍

Thanks! Other behaviors remain the same:

- Clicking outside of the floating window still closes it.
- Moving the mouse cursor more than 50 pixels out of a bauhaus combox or pressing `ESCAPE` still closes the combobox.

Also, I should mention that floating windows are now styled via CSS (within the constraints of what GtkPopover allows).

**Comment by LebedevRI** [comment]
So i have finally just tested it, i think this is good.
I think it's best if @houz / @hanatos could try this first.

**Comment by dtorop** [comment]
Exciting! It's definitely a risky/invasive change, but I hope worth it for the simplified code and simpler relationship to GTK. Will keep an ear out if problems arise. This does bring a Wayland-workable darktable much closer, for what that is worth.

**Pull request merged**
