### PR TITLE
remove unused flag CPF_DO_NOT_USE_BORDER in calls

### PR DESCRIPTION
**Pull request by Mark-64**
`dtgtk_button_new()` and `dtgtk_togglebutton_new()` widgets no longer use the flag `CPF_DO_NOT_USE_BORDER`, as this functionality has been moved to css.
This PR just cleanes up all the calls to those function from the unused flag, that could be misleading for who reads the code.
there should be no visible effect whatsoever.

### CODE REVIEW

**Comment by TurboGit** [comment]
Does this require #5223 to be merged before ?

Need a rebase due to changes in liquify. Thanks.

**Comment by Mark-64** [comment]
No it is totally independent from #5223. 
Rebased

**Comment by TurboGit** [comment]
Please avoid merging master into your topic branch. It is better to rebase on master and fix conflicts if any. Thanks.

**Comment by Mark-64** [comment]
yep, still fighting with eclipse/git integration, sorry about that

**Pull request merged**
