### PR TITLE
database: backup db for each new release.

### PR DESCRIPTION
**Pull request by TurboGit**
We backup library.db and data.db with to library.db-pre-<version> and
data.db-pre-<version>. The version string here is the version of the
current darktable release (using MAJOR.MINOR.PATCH, e.g. 3.0.0).

For #3455.

### CODE REVIEW

**Comment by TurboGit** [comment]
Discussed in #3455, but I'm really not convinced that this will help. The XMP modifed by the new release won't be read by the old one... And may even crash dt I suppose.

**Comment by parafin** [comment]
There are limitations to usefulness of this, yes, but it won't hurt. I think if re-scan option isn't enabled in preferences, then DB take precedence and XMPs will be just overwritten on edit. Also one can just delete XMPs of the images present in DB.

**Comment by aurelienpierre** [comment]
Great !

**Comment by TurboGit** [comment]
Ok, let's this in then.

**Pull request merged**
