### PR TITLE
Spelling of grayscale as one word is much more common

### PR DESCRIPTION
**Pull request by victoryforce**
See https://books.google.com/ngrams/graph?content=grayscale+image%2Cgray+scale+image

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
I would expect some code to check this :-) are you sure it doesn't test for 'gray scale'

**Comment by elstoc** [comment]
I don't necessarily disagree here, but bear in mind it will break people's configuration if you change it

**Comment by victoryforce** [comment]
> I would expect some code to check this :-) are you sure it doesn't test for 'gray scale'

This is the value of the preference option. So yes, it will be checked against saved value and this change unfortunately will reset user choice (as grayscale is not the default value). OTOH, between versions, as a rule, there are always changes in the configuration, so the user expects some need to open the settings and check them after the upgrade.

So the question is what do we think is more important, consistency and correct spelling in the interface or minimizing the loss of user settings.

**Comment by victoryforce** [comment]
> 1. I meant, have you checked that existing code does not check old string?

Got it. I misunderstood your question at first... You mean code in a module that compares the value of configuration variable (from darktablerc) against the literal string. Yes, I checked it out. dt_conf_is_equal compares this value with the string "false color". So renaming "gray scale" to grayscale will not affect this.

> 2. Normally, if we change such a pref setting we would want user data to be preserved.

The state of things can be formulated as follows: this PR **preserves** user data in the sense that the user-configured darktable behavior does not change. If the user has chosen "false color" before this change darktable will behave accordingly. The same goes for grayscale, darktable will respect this preference.

@elstoc:
> I don't necessarily disagree here, but bear in mind it will break people's configuration if you change it

It will not break configuration. The only thing this change will break is *displaying* specific option value in the settings GUI, i.e. if "gray scale" was saved in darktablerc then you'll see blank entry instead because xslt-generated code in the settings GUI will decide that this is not the same as "grayscale".

Similar changes have already taken place. For example, with the change of available options in 'demosaicing for zoomed out darkroom mode' (when PPG was replaced by RCD).

**Comment by elstoc** [comment]
> It will not break configuration. The only thing this change will break is displaying specific option value in the settings GUI, i.e. if "gray scale" was saved in darktablerc then you'll see blank entry instead because xslt-generated code in the settings GUI will decide that this is not the same as "grayscale".

Right. The code checks for "false color" and assumes it's gray scale (grayscale) if it's _not_ false color. Still far from ideal for the settings GUI to show blank when a valid option was previously chosen by the user (I would consider this "breaking" the settings GUI) but you're right that this won't be the first time we've broken settings by such a change. As I said, I just wanted to draw attention to the possible impact and I don't object to changing it.

**Review by TurboGit — APPROVED** [review]
Given all the discussion I understand that the breakage won't be too annoying, let's move on this one, sooner is better than later anyway. And I agree with @jenshannoschwalm let's not bloat the code for this.

**Pull request merged**
