### PR TITLE
gpx: parse only elements within trk

### PR DESCRIPTION
**Pull request by edgomez**
I came to use a few KML<->GPX online converters, and also a popular
open source gps GPX logger on Android. These were generating GPX files
that darktable would throw a warning at, and the message is not very
clear. Try to avoid that.

The basic document structure was:
<gpx>
<wpt lat="xxx" lon="yyy">
 <ele>average of the waypoints</ele>
 <name>Description</name>
</wpt>
<trk>
 <trkpt></trkpt>...
</trk>
</gpx>

This structure is perfectly legit when looking at the XML schema file.

The problem is that we parse all "wptType" sub elements wether or not we're
in a trk>trkpt or not, and DT chokes if no trkpt is actually being parsed.

So we must better track what we're actually parsing and currently limit the
wptType subelements parsing within trk>trkpt

### CODE REVIEW

**Comment by edgomez** [comment]
The patch in itself ensures we only parse tk data. This is better than current approach, but in the end this PR just kills one warning visible to users looking at stderr. I propose this as PR because i'm not sure it's a valuable patch or not

**Comment by LebedevRI** [comment]
How does this relate to Redmine issue #10682 ?
Does it fix it?

**Comment by edgomez** [comment]
Tested the GPX file from the bugreports and added a few printf to make sure that those valid elements are correctly skipped with this PR.

Yes, this PR also fixes #10682. Which sorts of qualifies this PR as bugfix. Great :dancer: 

Will you merge this and close the bug ? do we want this in 1.6.x as well ?

**Comment by houz** [comment]
16x is basically dead and will most likely not see any more releases. So feel free to fix bugs there, but it's basically a waste of time I suppose.

**Comment by edgomez** [comment]
thanks @houz, if no 11.6.x release is planned then I'll just push the PR this evening on master.

**Comment by houz** [comment]
1. `parsing_tk` should be called `parsing_trk`.
2. doesn't your code leak memory when there are `trkpt` outside of a `trk`?
3. formatting is off, please remove spaces between `if` and `(`.

**Comment by edgomez** [comment]
> 1. parsing_tk should be called parsing_trk.

Done

> 2. doesn't your code leak memory when there are trkpt outside of a trk?

Not that i can think of as the new code doesn't try parse anything outside trk>, we don't even issue malloc for wptType data as was done in the old code.

I checked importing a few GPX files and a ASAN build, no leaks reported on exit.

> 3. formatting is off, please remove spaces between if and (.

Done

> 4. you should also init parsing_trk to FALSE.

Is already done, the gpx struct is allocated using g_malloc0 and hopefully FALSE == 0 in glib.

Are we good for merge ?

**Comment by LebedevRI** [comment]
@edgomez 
Hint: adding e.g. "Fixes [#10682](http://redmine.darktable.org/issues/10682)" into PR name or commit message would automatically fix the issue when that commit hits git master.
Please close that bug as fixed if this indeed fixed it.

**Comment by edgomez** [comment]
> Please close that bug as fixed if this indeed fixed it.

Thanks for the commit log tip.

I've marked the bug as Fixed in redmine.

-- 
Edouard Gomez

**Pull request merged**
