### PR TITLE
#9287 piwigo export

### PR DESCRIPTION
**Pull request by Codekloeppler**
Start coding on Piwigo Export

### CODE REVIEW

**Comment by strixaluco** [comment]
Thank you for taking efforts to implement Piwigo export, @Codekloeppler. Were there any objectives to get this merged?

**Comment by TurboGit** [comment]
See https://github.com/TurboGit/darktable/tree/piwigo

It's done :)

**Comment by strixaluco** [comment]
Oh, I searched only in the darktable-org repo. That's amazing! Can we assume it will be merged into the master?

**Comment by TurboGit** [comment]
Yes, but not 2.6 as we are in feature freeze. So, it will be merged in 2019 and available on the dev version soon.

**Comment by strixaluco** [comment]
> Yes, but not 2.6 as we are in feature freeze.

Right. Will be checking the dev version then. Thank you!

**Comment by Codekloeppler** [comment]
Am 2018-11-20 10:07, schrieb strixaluco: 

>> Yes, but not 2.6 as we are in feature freeze.
> 
> Right. Will be checking the dev version then. Thank you!

Hello, 

sorry for my late reply, I just saw these mails a minute ago. 

Yesterday, I solved a problem on my implementation, that was bugging me
for a while.
So, now it's somewhat frustrating to hear, that this work was all done.
;-) 

But I'm really glad, that the piwigo plugin will be merged to master
soon. 

Thank you all!

**Comment by TurboGit** [comment]
> So, now it's somewhat frustrating to hear, that this work was all done. ;-)

No, you're now ready to implement some others like SmugMug or any other services around :)

**Pull request closed without merging**
