### PR TITLE
refactor: dedup ellipse-drawing code for retouch shapes

### PR DESCRIPTION
**Pull request by ralfbrown**
Note: this PR will cause a compile error if it and #8281 are merged prior to #8290  (due to duplicated function -- both need `_bounding_box`, but because masks.c prior to #8290 includes both of the .c files in itself, they end up in the same compilation unit).

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Looks good !

**Comment by TurboGit** [comment]
@ralfbrown : need conflict resolving.TIA.

**Comment by ralfbrown** [comment]
Conflicts resolved.

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Pull request merged**
