### PR TITLE
Redesign of export & thumbs

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
For some dt versions there have been a number of issues and fixes related to exact exported size
or crashes/errors related to out of memory access while processing exports.

After some work on the pixelpipe and roi handling i think the underlying culprit is current handling
of roi_in size in finalscale since dt 2.0
```
  // out = in * scale + .5f to more precisely round to user input in export module:
  roi_in->width  = (roi_out->width  - .5f)/roi_out->scale;
  roi_in->height = (roi_out->height - .5f)/roi_out->scale;
```

The code leads to a reduction of the roi_in size which is possibly/likely too small to provide complete data
for the processed roi_out. Let's look at the simple example of an 1.0 scaled output of a 1000x1000 image,
the export pixelpipe will be processed with an input of 999x999 -> 1000x1000 with a scale of 1.0.

In `dt_imageio_export_with_flags()` we had to handle this conflict and introduced some fixes/workarounds
that basically either reduced output size by 1 or did a cpu bound costly & slightly blurring upscaling to
the requested size. Both are bad.

The new code
1. in finalscale rounds **up** the roi_in size thus providing requested input data in all cases for roi_out
2. avoids needs to either size reduction or upscaling thus improving quality and performance
3. removed workarounds so less code complexity

Also the upscaling while using "set size by scale" did not work, for `dt_control_export()` a parameter flag
`dimensions_scale` had to be added to support this.

Any downsides?
All exports and thumbnails will be slightly different as they are either of correct/different size or with
same size but not upscaled/blurred.

Incomplete list of related issues and pr's

#12386 #12194 #12165 #11716 #10837 #9738 #8952 #7465 #5232 #5228

Certainly requires profound testing and updates in darktable-tests

### CODE REVIEW

**Comment by TurboGit** [comment]
@jenshannoschwalm : Nice work, so far I have always the proper export size. That's really a nice rework of this part which has accumulated pile of workaround. Of course the whole integration testsuite expected output has to be regenerated. I'll continue testing.

**Comment by jenshannoschwalm** [comment]
yes, i also couldn't get a failure yet and no upscaling for thumbs so noticably faster lightroom & exports :-)

**Comment by Nilvus** [comment]
I love seeing such PR, faster and better exports (I didn't test but just read comments) AND with less code lines! Best combo ;-)

**Review by TurboGit — COMMENTED** [review]
@jenshannoschwalm : I did some test and found one regression on test 0030 (this is a test using the border iop).

Before this PR:

```
$ exiftool 0030-framing/output.png | grep "^Image Size"
Image Size                      : 2048x1377
```

After this PR:

```
$ exiftool 0030-framing/output.png | grep "^Image Size"
Image Size                      : 2047x1377
```
Note the 2047 vs 2048. All images are exported with max 2048 x 2048 on the integration testsuite so the current master seems better.

This may due to some rounding in `src/iop/borders.c`. Let me know if you prefer looking at this after this is merged or if you prefer fixing this as part of this PR. TIA.

EDIT: This can be reproduced by exporting the image with the framing.xmp from the testsuite from GUI.

**Comment by TurboGit** [comment]
> If you don't mind i would clearly prefer to get the border module issue to be done in **another** pr. There is another issue pending on that with non-symmetrical border width and i would like to get that fixed too.

Works for me. I'll merge this as it is a very big improvement anyway. For the borders issue I had a quick look and this patch makes things better:

```
--- a/src/iop/borders.c
+++ b/src/iop/borders.c
@@ -311,27 +311,31 @@ void modify_roi_out(struct dt_iop_module_t *self, struct dt_dev_pixelpipe_iop_t
     if(roi_in->width > roi_in->height || !d->max_border_size)
     {
       // this means: relative to width and constant for height as well:
-      roi_out->width = (float)roi_in->width / (1.0f - size);
+      roi_out->width = roundf((float)roi_in->width / (1.0f - size));
       roi_out->height = roi_in->height + roi_out->width - roi_in->width;
     }
     else
     {
       // this means: relative to height and constant for width as well:
-      roi_out->height = (float)roi_in->height / (1.0f - size);
+      roi_out->height = roundf((float)roi_in->height / (1.0f - size));
       roi_out->width = roi_in->width + roi_out->height - roi_in->height;
     }
   }
   else

```

I'll open an issue and will add this patch there to be discussed.

**Comment by TurboGit** [comment]
@jenshannoschwalm : Issue created : #13350

**Pull request merged**
