### PR TITLE
imageop: prevent module being re-enabled

### LINKED ISSUE #6924: modules on/off not respected when module is on and expanded. Clicking on/off collapses module instead of switching it off.
3.3.0+1613~gc8f2d6cd9

Pasted history from image1 to kosher image2.

Realized the crop needed to be fixed in image2.

Clicked the enabled crop module to expand it.

Then without changing the crop clicked the module on/off to turn it off (the mouse was specifically on the in/off and it was highlighted), but it treats the click as module collapse.

### PR DESCRIPTION
**Pull request by elstoc**
Resolves #6924

### CODE REVIEW

**Comment by elstoc** [comment]
This definitely fixes the bug and doesn't _appear_ to cause any other effects, but I don't know what this functionality is doing so needs review.

**Comment by TurboGit** [comment]
@elstoc : the operation_tags_filter() was introduced back in 2011 in commit cd24715ef91d0223130cb0342ac6cc9141117b2b.

I'm not sure to see all the consequence of using this mode and as there is no reference to an issue hard to tell.

I have tested this and indeed it fixes the issue. We may want to check all modules using distortion and how they works when using together (lens, perspective correction, crop & rotate, maybe liquify).

**Comment by elstoc** [comment]
@TurboGit I think I've pushed an alternative that's less likely to break things.

**Comment by TurboGit** [comment]
@elstoc : works for me too and indeed looks lot safer. thanks.

**Pull request merged**
