### PR TITLE
expose/culling : limit call to database

### PR DESCRIPTION
**Pull request by AlicVB**
avoid going through all entries to speedup the slots creation. In particular `dt_collection_get_all` with -1 parameter, can take time with large collection. I have switch to using the "in-memory" sqlite table with the help of `LIMIT` and so on.
This *should* enhance loading times for expose/culling slots. In my benchmarks there's a gain of about 1 sec with 27K images (but I have a quite good config)
@edgardoh : as usual, can you have a look/test. This as become a quite big rewrite, so I hope I've not break anything (or forgot some feature)

### CODE REVIEW

**Comment by AxelG-DE** [comment]
Tested. 
Works for me.
THank you very much!

**Comment by edgardoh** [comment]
@AlicVB , sorry but I don't have the time right now to do a test. I don't think I get what you are doing here and maybe you already considered this, but what if we store the collected images list in memory when the collection changes? The only downside will be that on large collection it can be resources consuming.

**Comment by AlicVB** [comment]
@edgardoh : no problem, we aren't in a hurry !
What you propose is already in place in a different form : on each collection change, a new sqlite table (memory.collected_images) is stored. So we have just to reuse it. Then, we can play with `JOIN` and `LIMIT` to only get what we want. That's basically what I've done...

**Comment by edgardoh** [comment]
Well, now I'm sure I don't understand what you did!

My idea is to modify only dt_collection_get_all(), if the in-memory list is empty it will perform the select as it does now, if not empty it returns a new list but using the in-memory list as a source. This way we don't need to modify the existing code. Can this be done with the memory.collected_images? Or maybe you are introducing other optimizations?

**Comment by AlicVB** [comment]
The main idea is that if we use in-memory database, we can do everything in one pass. for example, here is the steps for culling : 
1- get the first image (as before, we only reuse slots values, instead of last_first_selected)
2- `SELECT m.imgid, b.aspect_ratio FROM memory.collected_images AS m, images AS b WHERE m.imgid = b.id AND m.rowid >= (SELECT rowid FROM memory.collected_images WHERE imgid = %d) ORDER BY m.rowid LIMIT %d`
3- we get all what we want (and not more) directly !
Apart from that, I've done some other optimizations, mainly resulting as the above changes.

**Comment by edgardoh** [comment]
OK, I just took a quick look at your code, so there's a good chance that what I say makes no sense. If you think this is faster than a list I'm OK with it.

**Comment by AlicVB** [comment]
I think so, because, we don't have to construct/verify/... the list, and as said because getting the ids can be done in 1 pass (and sqlite is quite performant for query stuff, especially with in-memory tables)
...and it simplify the code at the same time !

**Comment by AxelG-DE** [comment]
@AlicVB

I don't know, if it is related, but would you mind looking into my comment of PR #2471

Thanks

**Comment by AlicVB** [comment]
@AxelG-DE : done. thanks for the report (for the record, the problem comes from one of my previous PR, not this one)

**Comment by TurboGit** [comment]
Better speed is ok, the changes looks a bit complex to me. Anyway, this works fine on my side so I'll merge now for more field testing as it is difficult to assess if this is 100% correct just be review. Thanks.

**Comment by TurboGit** [comment]
Can you just fix the French word "avec" in the first commit log message?

**Comment by AlicVB** [comment]
@TurboGit : done :)

**Comment by TurboGit** [comment]
Thanks.

**Comment by AxelG-DE** [comment]
@AlicVB
Thank you!

**Comment by Nilvus** [comment]
Great works @AlicVB. I've never see images display so fast. Really faster. Thanks a lot ! I've passed about 900 images without any problem  By now, all is 100% perfect.

**Comment by AxelG-DE** [comment]
Need to correct my self, my collection is 12,000 pics in one folder, filtered to 850 :-)

**Pull request merged**
