### PR TITLE
Update info line when cropped size changes

### LINKED ISSUE #10705: information line is not updated: it needs update when the crop size variables are used
3.8.x

(from #10695)

I'm using CROP_HEIGHT and CROP_WIDTH in the "pattern for information line".

When a new image is loaded, 0 and 0 is shown.

Cropping or rotating doesn't update the values in the info line according to current values of those two variables.

The information line must be updated when loading the image the first time (0 and 0 are shown) and when some module changes the crop data:
- crop
- rotate and perspective
- lens correction
- ....
- maybe some deprecated module

### PR DESCRIPTION
**Pull request by paolobenve**
trying to fix #10705, works:mostly but not perfectly

The info line is updated:
- after some module changes the crop size; the change happens when another module is activated
- when an element in history stack is clicked

### CODE REVIEW

**Comment by paolobenve** [comment]
I'm using this string:

`$(EXIF_EXPOSURE) • f/$(EXIF_APERTURE) • $(EXIF_FOCAL_LENGTH) mm • $(EXIF_ISO) ISO → $(CROP_WIDTH) x $(CROP_HEIGHT)`

in the preferences - darkroom - pattern for image information line

**Review by TurboGit — CHANGES_REQUESTED** [review]
Nice, but while testing this I found  some refresh issues:

- Open a picture
- Discard history
- Enable crop / do a small crop of the image (remember the crop size)
- Enable another module (say `rgb curve`)

Now, move one step back in history on `rgb curve`, crop size ok. Move another step back, the crop size is not changed, but the display is. Move one step up in the history on crop again, see that the crop size corresponds to the original size and not the cropped one.

**Comment by paolobenve** [comment]
any hint?

**Comment by paolobenve** [comment]
after rebasing onto current master something is better, while there are still problems.

**Comment by paolobenve** [comment]
> Nice, but while testing this I found some refresh issues:
> 
> * Open a picture
> * Discard history
> * Enable crop / do a small crop of the image (remember the crop size)
> * Enable another module (say `rgb curve`)
> 
> Now, move one step back in history on `rgb curve`, crop size ok. Move another step back, the crop size is not changed, but the display is. Move one step up in the history on crop again, see that the crop size corresponds to the original size and not the cropped one.

It looks like now the size is updated correctly

**Review by TurboGit — APPROVED** [review]
Thanks, tested and seems that it is working in all scenario now.

**Pull request merged**
