### PR TITLE
Bump required CMake version

### PR DESCRIPTION
**Pull request by victoryforce**
We currently declare CMake version 3.10 to be sufficient for building darktable. But the minimum required version of CMake for the rawspeed build is now 3.18:

https://github.com/darktable-org/rawspeed/blob/5ceb9e64a64fa28c134b255861ba06f8594d5ee8/CMakeLists.txt#L1

Since rawspeed is always compiled when building darktable, 3.18 is actually the minimum required version for the entire program.

### CODE REVIEW

**Comment by TurboGit** [comment]
Nice, I was about doing a PR for that. Thanks!

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by TurboGit** [comment]
Merged in master, cherry-picked in 4.2 branch.

**Comment by victoryforce** [comment]
@TurboGit Do you plan to mention this requirement change in the release notes? Just noticed that the PR was not labeled accordingly.

**Comment by TurboGit** [comment]
> @TurboGit Do you plan to mention this requirement change in the release notes? Just noticed that the PR was not labeled accordingly.

Good catch, thanks now the tag is properly set.

**Pull request merged**
