### PR TITLE
Support for reading 16-bit (half) float TIFFs

### PR DESCRIPTION
**Pull request by kmilos**
Partly addresses https://redmine.darktable.org/issues/8380 (which seems didn't make it over to github...)

### CODE REVIEW

**Comment by kmilos** [comment]
A test image can be generated froma  32-bit float TIFF using Imagemagick:

`magick convert test_float.tif -depth 16 -define quantum:format=floating-point [-compress zip -define [tiff:predictor=3]] test_half.tif`

**Comment by TurboGit** [comment]
Looks good to me. Just to be sure, the current master does read those TIF but using lib ImageMagick if dt is compiled with it.

```
[tiff_open] error: Not a supported tiff image format.[rawspeed] (test_half.tif) virtual std::unique_ptr<rawspeed::RawDecoder> rawspeed::RawParser::getDecoder(const rawspeed::CameraMetaData*), line 91: No decoder found. Sorry.
[GraphicsMagick_open] image `test_half.tif' loading
```

This patch makes the loading native and does not require ImageMagic. Correct?

**Comment by kmilos** [comment]
3.2.1 wouldn't read those for me on Windows (skullhead icon in lighttable, error message when double clinking), and I don't know if the Win build comes w/ ImageMagick or not... Sorry I haven't tried master first...

So yes, this makes it "native" (for the read only), just like 32-bit float, relying only on libtiff (+zlib for compressed variants).

The are alternatives like relying on similar code in OpenEXR or rawspeed, but they seem to be exposed through a C++ interface only, and I didn't feel it was necessary to rewrite the entire TIFF reader...

**Comment by TurboGit** [comment]
Ok, thanks for the details. That match my understanding and since this works let's merge. Thanks.

**Pull request merged**
