### PR TITLE
Fix locallaplacian padding

### LINKED ISSUE #3753: dt3.0: lut 3D: Gtk-WARNING drawing failure for widget 'GtkWindow' & 'GtkDrawingArea'
**Describe the bug**
The combobox at first line of lut 3D module is producing two Gtk warnings when the "lut file" selection icon is not used before.
100% reproducible in this context

**To Reproduce**
1. Select an image and Go to 'darkroom'
2. Open the 'lut 3D' module
3. At the first parameter line, do not use the "lut file" icon on the left, but directly Click on the combobox on the right.
4. No choice proposed (no file listed), but See the following 2 Gtk warnings in the console:
```
(darktable:26403): Gtk-WARNING **: 17:03:45.033: drawing failure for widget 'GtkDrawingArea': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(darktable:26403): Gtk-WARNING **: 17:03:45.033: drawing failure for widget 'GtkWindow': invalid value (typically too big) for the size of the input (surface, pattern, etc.)
```
**Expected behavior**
No Gtk warning

**Platform (please complete the following information):**
 - OS: Ubuntu 19.10 / Gtk 3.24.12-1ubuntu1
 - darktable 3.0.0rc2+97~gb26d5128f

**Additional context**
When the "lut file" icon on the left is used before, and a lut file selected, then the list of choices on the combobox is not empty, and no Gtk warning reported

dt compiled by myself from latest git master using standard build instruction. No specific option added

**Side comment**
I do not fully understand the logic to have two different widgets (the "lut file" icon, and then the combobox) on the same line to select the lut file

### PR DESCRIPTION
**Pull request by aurelienpierre**
Attempt to reduce possible errors sources from #3756 for OpenCL and fix https://redmine.darktable.org/issues/12349 for SSE2 and for good.

### CODE REVIEW

**Comment by aurelienpierre** [comment]
For the record, the last commit deletes the special handling of the full pipeline preview in SSE2 path. What it did was waiting for the thumbnail preview to setup the laplacian transformation, then fetch the buffers and reuse them for speed-up. It lead to inconsistencies when the preview pipe finished after the full pipe (the infamous "local laplacian: inconsistent output") and possible racing conditions with the mutex.

So I have put the SSE2 path on the same page than the OpenCL and plain C pathes, and the full preview pipeline recomputes independently from the thumbnail. It doesn't seem to penalize performance.

**Comment by aurelienpierre** [comment]
@TurboGit could you consider merging that for 3.0 or do you think it's too risky ?

1ceae79 is not the bugfix it should have been but stores sizes in struct instead of recomputing them everytime. It doesn't change the actual processing.

055f8c7 disables the clever handling of full preview with the info already computed and cached for the thumbnail, because there is no guaranty that the thumbnail will be computed first (when it's not, you get the "inconsistent output" message). Note that it only affects SSE2 path, and essentially makes SSE2 behaves as the plain C and OpenCL ones, for better consistency (even if some perf penalty should be expected, but my tests don't show a noticeable difference, mainly because the former code made the full pipeline wait for thumbnail mutex locks to be released).

**Comment by TurboGit** [comment]
@aurelienpierre : yes too risky so close to the tag now. this is not a regression, let's wait a bit more we will have time to do proper field testing for 3.0.1.
Thanks for tracking this down!

**Comment by TurboGit** [comment]
Works for me! Thanks.

**Pull request merged**
