### PR TITLE
Canon PowerShot SX160 IS

### PR DESCRIPTION
**Pull request by hknaack**
Finally, getting to contribute my calibration settings of the Canon PowerShot SX160 IS. Model name exif tag contains "Canon" in JPG-images from cameras built in firmware as well as DNG files created with CHDK. Darktable did not present those presets on a model string like "PowerShot SX160 IS".
I did some color calibration with argyll as well and provided a camera support ticket [1], but was told that darktable would not add more color profiles. The logs however show, that new color profiles still got added. My profiles are still available on my github [2].
Unfortunately, I don't possess this camera any longer, so I can't take any new shots.
[dt-noiseprofile-20161030.tar.gz](https://github.com/darktable-org/darktable/files/1844902/dt-noiseprofile-20161030.tar.gz)
[basecurve.pdf](https://github.com/darktable-org/darktable/files/1844903/basecurve.pdf)
[tonecurve.pdf](https://github.com/darktable-org/darktable/files/1844904/tonecurve.pdf)

[1] https://www.darktable.org/redmine/issues/11205
[2] https://github.com/hknaack/colorcalibration

### CODE REVIEW

**Comment by LebedevRI** [comment]
The base/tone curves aren't being merged (globally, not in just this pr)
You probably want to move white balance presets to a different pr
So this pr should only be left with noiseprofile

**Comment by hknaack** [comment]
Well, I have a hard time figuring what should be included into darktable, if on the camera support page [1] base curves and color matrices are mentioned. Also, dt-curve-tool.c still recommends to add the preset to iop/basecurve.c and iop/tonecurve.c [2]. This should all be comunicated more clearly.

Is it a requirement, to separate the white balance PR from the "new camera support" or just "noise profile" PR or what is the intention? Please shed some light about the workflow, because I am a bit confused.

[1] https://www.darktable.org/2012/10/whats-involved-with-adding-support-for-new-cameras/
https://github.com/darktable-org/darktable/blob/master/tools/basecurve/dt-curve-tool.c#L1066

**Comment by LebedevRI** [comment]
> Is it a requirement, to separate the white balance PR from the "new camera support" or just "noise profile" PR or what is the intention? Please shed some light about the workflow, because I am a bit confused.

wb presets can be just merged, while noiseprofiles needs review.

**Comment by hknaack** [comment]
OK, moved Whitebalance presets to a separate PR and did noise profiles with recent scripts (dropped images for ISO400-ISO1600, because shots were not enough out of focus).

**Comment by TurboGit** [comment]
Closing, those do not apply anymore. Seems like the code is somehow broken.

**Comment by hknaack** [comment]
> Closing, those do not apply anymore. Seems like the code is somehow broken.

Could you elaborate a bit more on this? Which code is broken, how can I help? Do I need to profile again?

**Comment by TurboGit** [comment]
It does not compile when rebased on master. If you want this, please rebase, fix and force push on this PR. Thanks.

**Comment by hknaack** [comment]
OK, I did a local rebase and compile failed due to some of my profiles ISO were below 31 and for whatever reason, such ISO values are not supported any more? Well, fine, I can drop those.
Other than that, it complained about my model string being too long. Yet, with any shorter string, the denoise module will not be able to match my noise profile with my photos.
So, I would propose to only adjust my PR to drop the noise profile's ISO values below 31. Is that OK with you?

**Comment by TurboGit** [comment]
Any news on this?

**Comment by hknaack** [comment]
It seems the model string was checked to be no more than 23 characters, which was the model string length of somebody else's camera. The code actually dealing with those strings doesn't need a length restriction. I just increased it to 32 characters, but that is also just a random value, which might be enough for a long time, or not.

**Comment by hknaack** [comment]
Now that the lower ISO values are no problem any more, I updated this PR to contain the noise profiles for down to ISO 10. I hope there are no more other issues.

**Comment by TurboGit** [comment]
Please as discussed before only add the noise profile in this PR. Also, looking at the curves it seems that the values are not really good in the high luma value. I'll ask confirmation. Also this is missing the noise_result.pdf. Maybe because it was not generated back in 2016.

**Comment by TurboGit** [comment]
Confirmed, the curves are not very clean. As a first solution redoing the computation (with the same pictures) but with the recent tool would be nice? If the curves are still not clean I fear that you'll need to redo the shot, and restart the whole process.

**Comment by TurboGit** [comment]
Ok, at this stage I'll close. Feel free to open a new PR with corrected curves and with only the noise profile. Thanks.

**Pull request closed without merging**
