### PR TITLE
[db_snap] try to improve snap behaviour on windows

### LINKED ISSUE #6579: Database snapshot rotation does not work correctly under windows
**Describe the bug**

Database snapshots are written on each closedown of darktable, but max number of snapshots is not honoured (none are deleted) and hence snapshots just accummulate.

**Expected behavior**

Older snapshots should be delected to honour max number - see below

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0+1130~g96726f7cc
 - OS: Windows 10
 - N/A
 - N/A

**Additional context**
With database snapshots set in config file as:

```
database/create_snapshot=once a week
database/keep_snapshots=2
database/maintenance_check=on startup
```
I get the following

```
-r--r--r-- 1 jim None   688128 Oct 19 16:51 /c/Users/jim/AppData/Local/darktable/data.db-snp-20201019155124
-r--r--r-- 1 jim None   688128 Oct 19 16:51 /c/Users/jim/AppData/Local/darktable/data.db-snp-20201019155155
-r--r--r-- 1 jim None   688128 Oct 19 16:52 /c/Users/jim/AppData/Local/darktable/data.db-snp-20201019155227
-r--r--r-- 1 jim None   688128 Oct 19 16:53 /c/Users/jim/AppData/Local/darktable/data.db-snp-20201019155258
-r--r--r-- 1 jim None   688128 Oct 19 16:53 /c/Users/jim/AppData/Local/darktable/data.db-snp-20201019155324
-r--r--r-- 1 jim None   688128 Oct 19 16:53 /c/Users/jim/AppData/Local/darktable/data.db-snp-20201019155353
-r--r--r-- 1 jim None 55967744 Oct 19 16:51 /c/Users/jim/AppData/Local/darktable/library.db-snp-20201019155124
-r--r--r-- 1 jim None 55967744 Oct 19 16:51 /c/Users/jim/AppData/Local/darktable/library.db-snp-20201019155155
-r--r--r-- 1 jim None 55967744 Oct 19 16:52 /c/Users/jim/AppData/Local/darktable/library.db-snp-20201019155227
-r--r--r-- 1 jim None 55967744 Oct 19 16:53 /c/Users/jim/AppData/Local/darktable/library.db-snp-20201019155258
-r--r--r-- 1 jim None 55967744 Oct 19 16:53 /c/Users/jim/AppData/Local/darktable/library.db-snp-20201019155324
-r--r--r-- 1 jim None 55967744 Oct 19 16:53 /c/Users/jim/AppData/Local/darktable/library.db-snp-20201019155353
```
i.e. a snapshot is written everytime I close darktable and it looks like they are never deleted.

Following up on this it appears to be the read attribute that is part of the problem. If I do a chmod +w on these files then they are deleted, but if I don't they are not, although from the logfile from a debug run the program thinks it is deleting them.

from one run of darktable we have the following (without doing any chmod):

```
13.286220 [db backup] found file: data.db-snp-20201019173700.
13.286220 [db backup] found file: data.db-snp-20201019174010.
13.287221 [db backup] found file: data.db-snp-20201019174351.
13.288220 [db backup] found file: library.db-snp-20201019173700.
13.289220 [db backup] found file: library.db-snp-20201019174010.
13.289220 [db backup] found file: library.db-snp-20201019174351.
.
.
17.860269 [db backup] data to C:\Users\jim\AppData\Local\darktable/data.db-tmp-20201019174509
17.865269 [db backup] 5 out of 21 done
17.892411 [db backup] 10 out of 21 done
17.923128 [db backup] 15 out of 21 done
17.953239 [db backup] 20 out of 21 done
17.995840 [db backup] 21 out of 21 done
17.998840 [db backup] removing old snap: C:\Users\jim\AppData\Local\darktable\library.db-snp-20201019173700.
18.002839 [db backup] removing old snap: C:\Users\jim\AppData\Local\darktable\data.db-snp-20201019173700.

end:   2020:10:19 18:45:13
```
and from the next

```

12.498668 [db backup] checking snapshots existence.
12.499667 [db backup] found file: data.db-snp-20201019173700.
12.500667 [db backup] found file: data.db-snp-20201019174010.
12.500667 [db backup] found file: data.db-snp-20201019174351.
12.501668 [db backup] found file: data.db-snp-20201019174509.
12.503672 [db backup] found file: library.db-snp-20201019173700.
12.504673 [db backup] found file: library.db-snp-20201019174010.
12.504673 [db backup] found file: library.db-snp-20201019174351.
12.505698 [db backup] found file: library.db-snp-20201019174509.
.
.
16.041010 [db backup] removing old snap: C:\Users\jim\AppData\Local\darktable\library.db-snp-20201019173700.
16.044010 [db backup] removing old snap: C:\Users\jim\AppData\Local\darktable\library.db-snp-20201019174010.
16.047005 [db backup] removing old snap: C:\Users\jim\AppData\Local\darktable\data.db-snp-20201019173700.
16.050005 [db backup] removing old snap: C:\Users\jim\AppData\Local\darktable\data.db-snp-20201019174010.

end:   2020:10:19 18:47:28
```
data.db, library.db etc. are all correctly 'rw'

### PR DESCRIPTION
**Pull request by johnny-bit**
Try to fix #6579 

Let's see if this works

@phrrk - can you check it? we'll try make it this time.

please run test runs with `-d sql`, not `-d all`.

### CODE REVIEW

**Comment by phrrk** [comment]
Looks good.  With 'once per day' produces one snapshot.  With 'on each close' produces up to required number of snapshots and then starts deleting oldest one.  Thanks.

**Comment by johnny-bit** [comment]
are there any `GLib-CRITICAL **: 18:47:24.647: g_str_has_prefix: assertion 'str != NULL' failed` messages?

That's the requirement for me :) After that @TurboGit can review and merge :)

**Comment by phrrk** [comment]
no `GLib-CRITICAL **: 18:47:24.647: g_str_has_prefix: assertion 'str != NULL' failed` messages with -d sql

**Comment by johnny-bit** [comment]
Then it's ready for review :)

**Review by TurboGit — APPROVED** [review]
Looks good, thanks for looking at this Windows idiosyncrasy !

**Pull request merged**
