### PR TITLE
Minimal CSS for Gtk 3.20

### PR DESCRIPTION
**Pull request by TurboGit**
I've reworked from scratch the darktable.css file. We all agree that it is a mess to maintain, the new version is 25% in size of the original one. That is around 460 lines have been removed. This version can also be adjusted in term of darkness just by changing base_color.

The look is not 100% identical to the current one, but it is close and usable.

All in all I think it could be a base to start over the CSS styling on darktable.

This is NOT meant to be MERGED, just discuss and see if is makes sense to continue this branch.

### CODE REVIEW

**Comment by TurboGit** [comment]
Any news on this? Have someone tried it?

**Comment by LebedevRI** [comment]
The bigger problem with gtk and theming is that in any case, our css only overrides some subset of the gtk theme

**Comment by TurboGit** [comment]
I understand, yet my proposal above is that this subset should be larger as using far less rules, the rules are more generic. Not sure if it is the best solution but at least the CSS looks easier to maintain this way (size of the CSS divided by 4, not that bad :)

**Comment by TurboGit** [comment]
Closing this as no use for now.

**Comment by LebedevRI** [comment]
I have in my todo to look at doing all this theming more properly, using native gtk theme base, with auto-generation and whatnot. Will see if i get to work on that...
https://github.com/GNOME/gtk/blob/gtk-3-22/gtk/theme/Adwaita/README

**Comment by TurboGit** [comment]
Sounds good!

**Pull request closed without merging**
