### PR TITLE
modulegroups : fix contextmenu with own defined groups

### LINKED ISSUE #8173: Strange behaviour trying to add modules to my group
3.5.0+1011~gcf8280351-dirty   Ubuntu 18.04

I'm unable to add modules to my new "favourites" group.   Ok in dt 3.4 release.

To reproduce: Click "manage presets" to get screen below.
Click the plus sign below "new".
It displays a short horizontal black bar about 4mm long instead of showing the module list.  I can't even get a screen grab of this - it seems to be inhibiting it. Once I click elsewhere and the black bar is gone, I can do a screen grab ("Print Screen").
Screenshot from 2021-02-10 11-38-35

### PR DESCRIPTION
**Pull request by AlicVB**
fix #8173

### CODE REVIEW

**Comment by elstoc** [comment]
Yes, this appears to resolve the issue for new module groups. 

Should the quick access panel only be able to access widgets for modules that have been added to a module group? I only ask because you create a new empty module group preset, the first thing you're presented with is an empty quick access panel. Until you add a new group and then add a module to it, the add widget menu is empty - which people might think is a fault.

IMO it's reasonable to allow users to access widgets on modules that aren't currently present in a group - they can already access the full module via search. I can see a use case where I might put all of the simple (one- or two-slider) modules on the QA panel and then just keep the more complex modules in a separate group.

**Comment by AlicVB** [comment]
hmm... the main problem I see is with the "link" button. Should we disable it in that case ? not sure it's a good idea... This is especially problematic if the module "not present in groups" is not enabled, and so is not present in the "active" group.

That said, I see the problem you mentioned for new "empty" layouts. Maybe we shouldn't start we completely empty layouts but with a sort of *very* minimal layout with just filmic/basecurve, exposure, colorbalance or something like that ? that would also avoid the strange "empty" window at start...

**Comment by elstoc** [comment]
> hmm... the main problem I see is with the "link" button

This is similar to an issue with shortcuts that someone raised the other day - in that they don't work if a module is enabled but not in a group. Given that you can enable non-grouped modules, I'd say that it should work in the same way as if you used search to access the module - i.e. it appears but with no group selected.

> Maybe we shouldn't start we completely empty layouts but with a sort of very minimal layout

Alternatively just remove the bare '+' button and insist that users always start by duplicating an existing group

**Comment by AlicVB** [comment]
> Given that you can enable non-grouped modules, I'd say that it should work in the same way as if you used search to access the module - i.e. it appears but with no group selected.

yes, that would be consistent



> Alternatively just remove the bare '+' button and insist that users always start by duplicating an existing group

The only problem is that it may make the discoverability of how to create new layouts harder... so for my part I would prefer the other solution...

Anyway, the current PR is needed in any case, and I'll try to implement the above discussion after ;)

**Review by TurboGit — APPROVED** [review]
Thanks !

**Pull request merged**
