### PR TITLE
filmicv4 : add a slight amount of gaussian noise in highlights

### PR DESCRIPTION
**Pull request by aurelienpierre**
helps reducing the "synthetic effect" of bloomed highlights

without: (master, 10 iterations of high quality reconstruction)
DSC_0552_14

with: (this PR)
DSC_0552_19

with: (this PR, 1 iteration of high quality reconstruction)
DSC_0552_20

### CODE REVIEW

**Comment by aurelienpierre** [comment]
hold on, we may need Poisson noise too.

**Comment by elstoc** [comment]
I notice that the gaussian looks much more 'harsh' (greater range) than the others using the same value in the noise slider. Is this intentional? It might be better if the noise parameter was more consistent in its visual effect.

**Comment by TurboGit** [comment]
I have lot of noise when using this last version even with default setting, here is a screenshot when changing the reconstruct option to show better the noise:

image

**Comment by TurboGit** [comment]
Depending on the settings there is also lot of noise appearing in the shadows.

**Comment by aurelienpierre** [comment]
> Depending on the settings there is also lot of noise appearing in the shadows.

Can you check the highlight mask ? It means the highlight threshold is too low, so most of the image gets reconstructed.

> I have lot of noise when using this last version even with default setting, here is a screenshot when changing the reconstruct option to show better the noise:

What noise level makes it acceptable ?

> I notice that the gaussian looks much more 'harsh' (greater range) than the others using the same value in the noise slider. Is this intentional? It might be better if the noise parameter was more consistent in its visual effect.

That's an effect of the stats distribution of noise, but I seem to have a problem with the poissonian noise anyway.

**Comment by TurboGit** [comment]
All this with the default using "scene referred" mode. 

The highlight mask looks ok:

image

The image:

image

The settings (all default, not touched):

image

image

The level that makes this acceptable is around -.040 IL:

image

**Comment by aurelienpierre** [comment]
Latest commit should fix most of your issues @elstoc and @TurboGit (if not all).

**Comment by elstoc** [comment]
Thanks will test soon.

**Comment by TurboGit** [comment]
Better but still now 100% clean:

image

As soon as you move a bit the threshold to -1.5 IL the noise is back & strong:

image

**Comment by aurelienpierre** [comment]
In that case, @TurboGit you need to allow more iterations of high-quality reconstruction. The chroma noise will then be turned into luma noise that the reconstruction will be able to use to fake texture.

**Comment by TurboGit** [comment]
> In that case, @TurboGit you need to allow more iterations of high-quality reconstruction. The chroma noise will then be turned into luma noise that the reconstruction will be able to use to fake texture.

Ok, indeed it smooth-out the noise in this case. I bet we''ll get lot of questions on this.

**Comment by TurboGit** [comment]
The "add noise in highlights" slider does not behave very well, a mouse scroll does increment of 1 but it is generally for too much and indeed you've set 2 decimals to this slider. We probably want an increment of 0.1 ? Even 0.5 is too much I think.

**Comment by aurelienpierre** [comment]
I have updated the defaults params so the noise level 0.5 instead of 1, I hope it will make it more reliable.

**Comment by TurboGit** [comment]
> I have updated the defaults params so the noise level is set to 0.5 instead of 1, I hope it will make it more reliable.

My very limited experience with this module tell me that 0.2 should be even better as a default (closer to previous behavior).

**Comment by TurboGit** [comment]
Looks good now! Let me play with it tomorrow a bit and we will probably be able to merge.

**Comment by TurboGit** [comment]
Looks better to me now. The default values are more conservative and won't raise too many questions now. Let's have this merged to gain more field testing. Thanks!

**Pull request merged**
