### PR TITLE
image: import lightroom metadata only if no other xmp

### LINKED ISSUE #7957: Import creates two image instances when xmp filename ends "_01.cr2.xmp"
Import a folder that contains a previously edited image and an xmp file. If the xmp file has a filename "<img_filename>_01.cr2.xmp" darktable creates two duplicate instances of the image and generates a second xmp file (named "<img_filename>.cr2.xmp"). Same thing happens if I rename it to "<img_filename>_02.cr2.xmp".

If the xmp is named "<img_filename>.cr2.xmp" only a single instance of the image is imported.

This seems to be a regression of an issue I originally raised and resolved: #4385

3.5.0+800~g3366c75b9
ArchLinux

### PR DESCRIPTION
**Pull request by phweyland**
hopefully fixes #7957

still some redundancy however, 
_image_read_duplicates() calls again dt_exif_xmp_read() for the main xmp ...

### CODE REVIEW

**Comment by phweyland** [comment]
@elstoc, it would be great if you could check if that solves actually your issue. TIA

**Comment by elstoc** [comment]
Thanks that looks good to me. 

@TurboGit I would like this to be considered for 3.4.1 - it's a real pain if I have to reimport a folder as I very often delete version 0.

**Review by TurboGit — APPROVED** [review]
I cannot tell if it fixes the issue, but this seems clearly correct as we don't want to parse any Lr XMP if there is some duplicates as in this case those pictures have then already been processed by dt.

**Comment by TurboGit** [comment]
Merged in master & 3.4.1.

**Pull request merged**
