### PR TITLE
export: disable insert-text handler when programatically inserting

### LINKED ISSUE #6127: [lighttable] Heap-overflow on darktable startup
```
=================================================================
==18761==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000e88f34 at pc 0x7f4ad2762f41 bp 0x7ffc0d3f2920 sp 0x7ffc0d3f20d0
READ of size 5 at 0x602000e88f34 thread T0
    #0 0x7f4ad2762f40  (/usr/lib64/libasan.so.6+0x3ff40)
    #1 0x7f4ad17100b3 in g_strdup (/usr/lib64/libglib-2.0.so.0+0x740b3)
    #2 0x7f4ad0a397fc  (/usr/lib64/libgobject-2.0.so.0+0x3a7fc)
    #3 0x7f4ad0a2b54b in g_signal_emit_valist (/usr/lib64/libgobject-2.0.so.0+0x2c54b)
    #4 0x7f4ad0a2c0be in g_signal_emit_by_name (/usr/lib64/libgobject-2.0.so.0+0x2d0be)
    #5 0x7f4ad10b1f34  (/usr/lib64/libgtk-3.so.0+0x1baf34)
    #6 0x7f4a7520e16d in insert_text_handler /home/abuild/rpmbuild/BUILD/darktable-3.3.0~git389.d04857316/src/libs/export.c:511
    #7 0x7f4ad0a12fc1 in g_closure_invoke (/usr/lib64/libgobject-2.0.so.0+0x13fc1)
    #8 0x7f4ad0a25692  (/usr/lib64/libgobject-2.0.so.0+0x26692)
    #9 0x7f4ad0a2bd38 in g_signal_emit_valist (/usr/lib64/libgobject-2.0.so.0+0x2cd38)
    #10 0x7f4ad0a2c0be in g_signal_emit_by_name (/usr/lib64/libgobject-2.0.so.0+0x2d0be)
    #11 0x7f4ad10b1f34  (/usr/lib64/libgtk-3.so.0+0x1baf34)
    #12 0x7f4ad10b9fcf in gtk_entry_set_text (/usr/lib64/libgtk-3.so.0+0x1c2fcf)
    #13 0x7f4a7520ef25 in _set_dimensions /home/abuild/rpmbuild/BUILD/darktable-3.3.0~git389.d04857316/src/libs/export.c:204
    #14 0x7f4a7521074f in gui_reset /home/abuild/rpmbuild/BUILD/darktable-3.3.0~git389.d04857316/src/libs/export.c:215
    #15 0x7f4a75212baf in gui_init /home/abuild/rpmbuild/BUILD/darktable-3.3.0~git389.d04857316/src/libs/export.c:856
    #16 0x7f4ad22cb7aa in dt_lib_init_module /home/abuild/rpmbuild/BUILD/darktable-3.3.0~git389.d04857316/src/libs/lib.c:776
    #17 0x7f4ad2013186 in dt_module_load_modules /home/abuild/rpmbuild/BUILD/darktable-3.3.0~git389.d04857316/src/common/module.c:59
    #18 0x7f4ad22cd29a in dt_lib_init /home/abuild/rpmbuild/BUILD/darktable-3.3.0~git389.d04857316/src/libs/lib.c:1104
    #19 0x7f4ad1efe7fb in dt_init /home/abuild/rpmbuild/BUILD/darktable-3.3.0~git389.d04857316/src/common/darktable.c:1013
    #20 0x55e9066780c5 in main /home/abuild/rpmbuild/BUILD/darktable-3.3.0~git389.d04857316/src/main.c:92
    #21 0x7f4ad1ba0cc9 in __libc_start_main (/lib64/libc.so.6+0x26cc9)
    #22 0x55e906678149 in _start (/usr/bin/darktable+0x1149)

0x602000e88f34 is located 0 bytes to the right of 4-byte region [0x602000e88f30,0x602000e88f34)
allocated by thread T0 here:
    #0 0x7f4ad27d127f in __interceptor_malloc (/usr/lib64/libasan.so.6+0xae27f)
    #1 0x7f4ad16f6338 in g_malloc (/usr/lib64/libglib-2.0.so.0+0x5a338)
    #2 0x7f4ad0a12fc1 in g_closure_invoke (/usr/lib64/libgobject-2.0.so.0+0x13fc1)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/usr/lib64/libasan.so.6+0x3ff40) 
Shadow bytes around the buggy address:
  0x0c04801c9190: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c04801c91a0: fa fa 07 fa fa fa 07 fa fa fa 00 00 fa fa 00 00
  0x0c04801c91b0: fa fa fd fd fa fa 00 06 fa fa 00 01 fa fa 00 00
  0x0c04801c91c0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c04801c91d0: fa fa fd fa fa fa fd fa fa fa 05 fa fa fa 02 fa
=>0x0c04801c91e0: fa fa 05 fa fa fa[04]fa fa fa fa fa fa fa fa fa
  0x0c04801c91f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c04801c9200: fa fa fd fd fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c04801c9210: fa fa fd fa fa fa fd fa fa fa 02 fa fa fa fd fa
  0x0c04801c9220: fa fa fd fa fa fa 05 fa fa fa 00 fa fa fa fd fa
  0x0c04801c9230: fa fa fd fd fa fa 00 02 fa fa fd fd fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==18761==ABORTING
```

**To Reproduce**
1. Build darktable with AddressSanitizer
2. Start darktable

### PR DESCRIPTION
**Pull request by elstoc**
Resolves #6127

### CODE REVIEW

**Comment by johnny-bit** [comment]
This indeed solves #6127 :+1:

**Comment by TurboGit** [comment]
Ok, looks good to me. Thanks!

**Comment by dterrahe** [comment]
Interesting that all this extra work is needed just to set the text in an entry widget when a signal is linked to it. Another case of gtk setting up hoops to jump through.
I wonder if the signal gets fired when manipulating the buffer instead of the entry
(so gtk_entry_buffer_set_text (gtk_entry_get_buffer(entry),text,-1))
Haven't tried because replicating the fault in the first place seems non-trivial ;-)

**Comment by elstoc** [comment]
> Interesting that all this extra work is needed...

All I wanted was the functionality of a spin button without the pointless +/- buttons but it all took way more effort than was really justified for the original change. I think it's perhaps easier in GTK4 (because the buttons are actual GtkButtons).

**Comment by dterrahe** [comment]
Looks like the simple solution is this:
```
static void insert_text_handler(GtkEditable *entry, char *text, int length, gpointer position, gpointer user_data)
{
  for (int i=0; i < length; i++)
  {
    if (!isdigit(text[i]))
    {
      g_signal_stop_emission_by_name (entry, "insert-text");
      return;
    }
  }
}
```
The only time this is different is when a text is pasted that is a mix of numbers and other characters. The above throws everything away whereas your code extract all the numbers in the text. In hindsight I know you wish you hadn't gone to the extra trouble. It is helpful when somebody accidentally copies an extra space at beginning or end. In all other cases, I'm not even sure it is better...

**Pull request merged**
