### PR TITLE
tiff: fix Lab conversion on import

### LINKED ISSUE #12521: Broken support for 8/16bit tiff with CIELAB/ICCLAB photometric
**Describe the bug/issue**
Back in 2019, support for TIFF files in CIELAB/ICCLAB color space was added via PR1996 for DT2.6. This support allowed the use of LAB TIFF files created by high-end film scanners from the company Heidelberg and their software Newcolor.

This support seems to be broken, DT just renders the images black. I cannot determine the exact version when the feature stopped working because I did not add a new PPA when changing to Linux Mint 20 and have been working with the installed version up until recently when upgrading to Linux Mint 21 and installing the corresponding PPA with a jump to DT4.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Import provided sample image (16-bit CIELAB TIFF)
2. Check appearance in Lighttable and Darkroom module

**Expected behavior**
Correct rendering of provided TIFF file

[LAB_16bit_TIFF_Sample.tif.zip](https://github.com/darktable-org/darktable/files/9594225/LAB_16bit_TIFF_Sample.tif.zip)

**Screenshots**

DT4_
black-preview
DT4_black-darkroom-image

**Which commit introduced the error**

I am pretty sure it worked at least up to DTv3.4. The feature was introduced via PR#1996 and got into DTv2.6.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.0.1
* OS                : Linux kernel 5.15.0-47-generic
* Linux - Distro    : Linux Mint 21 Cinnamon
* Memory            : 16GB
* Graphics card     :  AMD RX560
* Graphics driver   :  tried OS supplied, oibaf PPA and running now on AMDGPU-PRO
* OpenCL installed  : yes (AMDGPU-PRO supplied)
* OpenCL activated  : tried on and off
* Xorg              : 
* Desktop           :  Cinnamon
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
 - Can you reproduce with another darktable version(s)?
I could access DT3.8 via APT cache and installed it, but behavior was the same: black images

 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)?
yes

 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")?
 yes

 - Do you use lua scripts?
no

### PR DESCRIPTION
**Pull request by kmilos**
Fixes #12521

We convert to RGB internally already, no need to label the image buffer differently.

### CODE REVIEW

**Comment by kmilos** [comment]
@calabi-yaui Please test

**Comment by kmilos** [comment]
This came in at #2264 @edgardoh

**Comment by calabi-yaui** [comment]
@kmilos I am not very used to compile PRs on github so I followed the instructions I was given in 2019 and it seems I compiled the version based on your PR12528 successfully. DT version now shows 270fde8d3, but behavior did not change. Still black previews and full image renders.

**Comment by kmilos** [comment]
> DT version now shows [270fde8](https://github.com/darktable-org/darktable/commit/270fde8d3346c284d849604067e91f1fc23f282c)

That is just the "clean" master branch, and does not include this PR.

**Comment by calabi-yaui** [comment]
I see, an error message went unnoticed when I tried to pull fix_tiff_lab.

Executing "git pull --rebase https://github.com/kmilos/darktable.git fix_tiff_lab" gives me merging problems due to existing 

src/common/imageio_tiff.c 
src/common/wb_presets.c

files. I am not familiar with the GitHub enviroment and a bit helpless here. I got to know different programming and scripting languages from my studies, but I am not working in the field of programming and I am lacking the experience to deal with GitHub errors. Can you point me in the right direction? using "git rm" to remove them first did not help because I am asked to commit them first and I am not sure if that causes any damage here.

**Comment by TurboGit** [comment]
@calabi-yaui : the PR has been rebased, can you resume testing? TIA.

**Comment by calabi-yaui** [comment]
@TurboGit : It took me some time to understand the GitHub basics, but I think I compiled this PR successfully because it works! Great work, thank you so much for fixing this in such a short time @kmilos 

screenshot_working

**Review by TurboGit — APPROVED** [review]
Thanks to both of you!

**Pull request merged**
