### PR TITLE
fix crashes darktable on macOS on #5901

### PR DESCRIPTION
**Pull request by esq4**
Could this be the solution for #5892?

### CODE REVIEW

**Comment by parafin** [comment]
There are 2 questions here:

1. Does #5892 original issue exist on macOS - I will check.
2. Can crash from #5901 happen on platforms other than macOS - I don't know, but checking for errors is a good idea even if errors seem to never happen.

So let's have someone else's opinion here too.

**Comment by johnny-bit** [comment]
I looked at the issue here at length today and I wanted to call dibs, alas I'm 24 minutes late :/

If you don't mind I'd like to propose an alternate solution that should be universal, not depend on ifdefs (root of all evil) and not leaking memory like crazy ;)

Plz give me ~1h

**Comment by parafin** [comment]
I've checked and timestamps on macOS look strange - I see some hieroglyphs in there, but it's not empty like on Windows (originally). So better fix is indeed welcome here.

**Comment by johnny-bit** [comment]
@parafin - please check #6263 With it we've got a fighting chance to understand why there are hieroglyphs on macos and it should cover windows usecase (windows strftime returns non-utf8 compatible string that can be converted)

**Comment by TurboGit** [comment]
Closing as better fix put in place.

**Pull request closed without merging**
