### PR TITLE
updates to pt_BR

### PR DESCRIPTION
**Pull request by jpellegrini**
These are updates by both me and Marcus Gama, that's why there are different commits.

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by jenshannoschwalm** [comment]
Seems to break build right now ...

**Comment by Nilvus** [comment]
Yes, I put a comment on commit. It's on line 10: `\n"` as been removed and need to be kept at the end.

**Comment by jpellegrini** [comment]
Sorry! PR #12207 fixes this

**Pull request merged**
