### PR TITLE
database version 33: delete images with invalid film id

### LINKED ISSUE #7891: database 33 upgrade freezes
ae6065691b49c0090b2d05074514632ae0f41af0 is ok
bfa4cb27c98f5365e66a11d036c22bf0e51933b5 freezes on the database upgrade - no message

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS:  debian 10

### PR DESCRIPTION
**Pull request by HansBull**
Attempts to fix #7891

### CODE REVIEW

**Comment by lhietal** [comment]
I'm not sure what can cause invalid film id but silently deleting images from the database doesn't seem like a good idea. Darktable db can be used to manage a photo archive and making sure problems are handled properly is an important part of not losing data.

There could be some sort of indication in the UI that images had to be deleted. Therefor user could try to correct the problem. Probably by reimporting specific photos.

**Comment by TurboGit** [comment]
> There could be some sort of indication in the UI that images had to be deleted. Therefor user could try to correct the problem. Probably by reimporting specific photos.

Problem is that we can't say where the images were. We only know the name which is possible DSC0002.NEF or whatever. And note that such image won't be usable nor visible from the ui. So they are already "lost", that's why I have proposed to just remove the db entries in this case.

**Comment by lhietal** [comment]
You are right that filename is propably the only possible way to recognize the images. Filename can also be very informative for some people. 

Would it be possible to add a popup to notify about the deleted images after db upgrade. That way users could make sure that importnt images are not left out of the db. I think it is acceptable to just have the user do necessary actions manually.

**Comment by TurboGit** [comment]
No I'm not for adding complexity here for almost no gain.
- we are talking about a very rare case, only one such report at this stage
- the images were not referenced and dangling before
- the images are removed now, better
- the images have probably no history or module order
- the dangling references are most probably due to a crash, we finalize the job properly in this PR
- remember, nothing is lost, users just have to reimport the folder (and maybe this is already has already been done)

**Comment by HansBull** [comment]
Was just writing some ten lines with a modal message dialog displaying the affected filenames...

**Comment by lhietal** [comment]
I was just trying to make sure that people know that they might have missing images which might not be easy to discover on a large collection.

**Pull request merged**
