### PR TITLE
macOS: Fix several shift-scrollwheel issues

### LINKED ISSUE #15391: Shift-modifier + mouse-wheel-scroll has no effect on macOS - color harmony
### Describe the bug

The vectorscope shift+scroll and shift+alt+scroll have no effect, both involve the shift modifier.
- shift+scroll to change width
- shift+alt+scroll to change height

See additional info below. This appears to be a known macOS issue in gtk.h. It looks like this requires special macOS SHIFT+wheel handling at each location, likely why it recurring with new features.

### Steps to reproduce

1. Based on my reading of related issues this requires running on macOS.
2. Go to vectorscope (RYB) color harmony.
3. Press SHIFT and scroll wheel to widen or narrow the color harmony wedges.
4. There is no effect.

### Expected behavior

The pop up states (shift+scroll to change width)

### Logfile | Screenshot | Screencast

_No response_

### Commit

4.4.2 

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Mac

### What is the version of your OS?

macOS 14.0

### Describe your system?

MacBook M1

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

M1

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

These other color harmony adjustments (modifier+scroll) work fine:
- scroll to coarse-rotate 
- ctrl+scroll to fine rotate 
- alt+scroll to cycle 

The vectorscope buttons for modes and color harmony models work as expected.
In other usages such as increasing/decreasing a drawn mask opacity taper the shift+scroll works fine. 
Weirdly, I found the MacBook built-in trackpad equivalent of mouse-shift+scroll works, that is shift-key plus sliding two-fingers up or down the trackpad does work while the mouse-shift+scroll does not.

From the previous related dt issues ([https://github.com/darktable-org/darktable/issues/2786](url)), it seems the problem is somewhat understood as commented in gtk.h. 

> /* Note that on macOS Shift+vertical scroll can be reported as Shift+horizontal scroll.
>  * So if Shift changes scrolling effect, both scrolls should be handled the same.
>  * For this case (or if it's otherwise useful) use the following 2 functions. */
> 

Not confident I want to attempt a fix, but I tried to systematically look through the code (4.4.2) for places where there could related issues due to the irregular macOS-SHIFT behavior and believe I found 2 or 3. I looked/greped for occurrences of the dt_gui_get_scroll_unit_deltas() without the corresponding variant that captures macOS-SHIFT+scroll dt_gui_get_scroll_unit_delta() (yellow in column).

Missing macOS-SHIFT special handling occurrences 
1. This issue occurs in libs/histogram.c  > _eventbox_scroll_callback()
2. A similar issue is in libs/geotagging.c > _datetime_scroll_over()
3. potentially in iop/atrous.c > checks GDK_SHIFT_MASK for fallbacks I don't know how those work.

Thanks!

Screenshot 2023-10-08 at 14 48 57

### PR DESCRIPTION
**Pull request by zisoft**
- change color harmonies width
  - change height on modules/textinputs
  - change geotagging date/time

fixes #15391

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Thanks! Works for me.

**Comment by TurboGit** [comment]
@zisoft : Probably worth a release notes entry.

**Comment by zisoft** [comment]
Release notes:
Fixed several mouse scroll wheel issues on macOS in combination with the shift modifier key, i.e.: Color harmonies width, module height, geotagging date/time.

**Comment by TurboGit** [comment]
Thanks!

**Pull request merged**
