### PR TITLE
toneequal : optimize some more the guided filter 

### LINKED ISSUE #3285: OSX: toneequal performance: dramatical slowdown in 100% view
**Describe the bug**
enabling toneequalizer slows down the processing in 100% view:

without toneequalizer:
`461,207339 [dev_process_image] pixel pipeline processing took 0,617 secs (0,825 CPU)`
with toneequalizer (default setting)
`543,471325 [dev_process_image] pixel pipeline processing took 24,894 secs (169,061 CPU)`

fit to screen view:
without:
`990,819389 [dev_process_image] pixel pipeline processing took 0,890 secs (3,468 CPU)`
with:
`1085,089492 [dev_process_image] pixel pipeline processing took 1,275 secs (6,214 CPU)`

on export:
without:
`1357,441986 [dev_process_export] pixel pipeline processing took 11,130 secs (23,644 CPU)`
with toneequal:
`1298,763360 [dev_process_export] pixel pipeline processing took 20,778 secs (96,342 CPU)`

the -d perf output tells me it's not using GPU and beein processed on cpu
`543,024582 [dev_pixelpipe] took 21,650 secs (158,445 CPU) processed `tone equalizer' on CPU, blended on CPU [full]`

processing time scales with the scale factor:
30%: [dev_process_image] pixel pipeline processing took 2,607 secs (15,862 CPU)
50%: [dev_process_image] pixel pipeline processing took 5,171 secs (33,202 CPU)
67%: [dev_process_image] pixel pipeline processing took 9,122 secs (61,960 CPU)
85%: [dev_process_image] pixel pipeline processing took 16,828 secs (115,837 CPU)
100%: [dev_process_image] pixel pipeline processing took 25,011 secs (173,619 CPU)

**Platform (please complete the following information):**
 - OS: OSX
 - Version 3.0.0 rc0

### PR DESCRIPTION
**Pull request by aurelienpierre**
up to 20% perf improvement, not sure it reproduces on other systems.

Partially fixes #3285 and #3081 but expect no miracle.

### CODE REVIEW

**Comment by MStraeten** [comment]
doesnt compile on osx:
```
/Users/martinstraeten/src/darktable_debug/src/common/fast_guided_filter.h:211:13: error: 
      expected an OpenMP directive
#pragma omp reduction(+:tmp) aligned(tmp:16) aligned(guide, mask, guide_...
            ^
/Users/martinstraeten/src/darktable_debug/src/common/fast_guided_filter.h:225:13: error: 
      expected an OpenMP directive
#pragma omp aligned(tmp:16) aligned(temp:64)
            ^
/Users/martinstraeten/src/darktable_debug/src/common/fast_guided_filter.h:322:13: error: 
      expected an OpenMP directive
#pragma omp aligned(in:64) aligned(w:16) reduction(+:w)
            ^
/Users/martinstraeten/src/darktable_debug/src/common/fast_guided_filter.h:330:13: error: 
      expected an OpenMP directive
#pragma omp aligned(temp:64) aligned(w:16)
            ^
/Users/martinstraeten/src/darktable_debug/src/common/fast_guided_filter.h:361:13: error: 
      expected an OpenMP directive
#pragma omp aligned(temp:64) aligned(w:16) reduction(+:w)
            ^
/Users/martinstraeten/src/darktable_debug/src/common/fast_guided_filter.h:369:13: error: 
      expected an OpenMP directive
#pragma omp aligned(w:16) aligned(in:64)
            ^
6 errors generated.
```

**Comment by parafin** [comment]
CI fails with the same errors, clear indication that this PR can't be merged currently.

**Comment by MStraeten** [comment]
compiles now - slight better performance

**Comment by aurelienpierre** [comment]
I messed branches, will revert.

**Comment by TurboGit** [comment]
Thanks !

**Pull request merged**
