### PR TITLE
avoid mixed precision floating point number arithmetic

### PR DESCRIPTION
**Pull request by rabauke**
... and avoid unnecessary explicit casts

### CODE REVIEW

**Comment by TurboGit** [comment]
There is lot more than just mixed precision fix. Please separate this in multiple PR. The fix can be integrated but not the other parts as we are in feature freeze. And it makes the review harder for me. A commit with "reformatting" can be reviewed quickly, here I have a bunch of modifications and need to be careful to what is really code changes or just reformatting. Thanks.

**Comment by rabauke** [comment]
I opened a new pull request, which is includes the reformatting part only. As soon as this new PR has been merged I will modify this PR to fix mixed precision issues only.

**Comment by TurboGit** [comment]
Sorry I prefer merging non bug-fixes only for 3.0.1. The reformatting will have to wait for 3.0.1. If you feel that the fix is important for 3.0 please create the patch on top of current master. Thanks.

**Comment by aurelienpierre** [comment]
@rabauke could you fix the conflicts ?

**Comment by rabauke** [comment]
> @rabauke could you fix the conflicts ?

@aurelienpierre Conflicts have been resolved.

**Comment by aurelienpierre** [comment]
Code reviewed, program tested on CPU, Intel Neo OpenCL and Nvidia OpenCL. It's all good to me.

@TurboGit if you are ok, I will merge.

**Comment by TurboGit** [comment]
Let me merge this now.

**Pull request merged**
