### PR TITLE
integration tests for X-Trans demosaic

### PR DESCRIPTION
**Pull request by ralfbrown**
Ref #7086

### CODE REVIEW

**Comment by TurboGit** [comment]
On my side I have rawdenoise test failing:

```
Test 0068-rawdenoise-xtrans
      Image mire1-xtrans.raf
      CPU & GPU version differ by 18913 pixels
      Max  dE         6.0342
      Mean dE         0.0083
      Count above max 235
  FAILS: image visually changed
         see diff.png for visual difference
         (58014 pixels changed)
```

**Comment by TurboGit** [comment]
And the diff is showing a really bad pattern:

diff

**Comment by ralfbrown** [comment]
That's exactly the pattern that comes out when comparing a 16-threaded run against a single-threaded run.  But I used run.sh to create the expected.png, so we should both be running with four threads.  Hmm....

The code is doing a nearest-neighbor interpolation to generate a full-size image in each of the R/G/B channels, which involves copying each R and B pixel to all eight of its neighbors.  When parallelizing, the first row of each horizontal slice gets a different value, because instead of the lower row overwriting the higher one, the other thread later comes along and overwrites the lower row from the higher one in the adjacent slice.  The DWT then spreads those changes 32 pixels in all four directions.  Bayer doesn't have this issue, because it processes quarter-size single-channel images for R/G1/G2/B.

**Comment by TurboGit** [comment]
You put me on the right track... I have 16 threads indeed and found out that none of our // for are following the max threads setting.

See #7097 for a patch that fixes the issue on my side.

We should probably do that in every // for, do you agree ?

**Comment by TurboGit** [comment]
Could this also explain the issue with lens test ?

**Comment by ralfbrown** [comment]
That's a rather nasty fix.  OpenMP is properly honoring the desired threads setting on my system, so a better solution  than changing **every** // for would be figuring out why yours isn't, and what setting will make it use the desired number of threads.  Do you have any of the OMP_* environment variables set?  (Though on my system, OMP_NUM_THREADS has no effect, because the thread-setting code in dt's init overrides it -- when I start darktable or darktable-cli with "-t 2", I get the message "[dt_init] using 2 threads for openmp parallel sections" and every single parallel for then uses two threads.)

And yes, thread-counts affecting lens correction had occurred to me, since it's doing subpixel stuff.

**Comment by TurboGit** [comment]
Are you sure yours is honoring the max thread? The parameter is only set into OpenMP in the job controls (exporting for example) but it does not seems set in other places.

**Comment by TurboGit** [comment]
No, I'm wrong it is set in darktable.c  :(

**Comment by TurboGit** [comment]
@ralfbrown : Found a single // for where this is needed, I don't see why really :( See my updated PR, any idea ?

**Comment by ralfbrown** [comment]
That's the loop doing the nearest-neighbor interpolation I described above.  On my system, it properly honors the requested number of threads, so I get different outputs depending on which -t N is specified.

I've been looking at the environment variables for OpenMP.  Try setting OMP_THREAD_LIMIT=4 before running the test.  If that gets you a match to my reference image, then my suspicion is that OMP_DYNAMIC is either set or defaults to TRUE, and that dynamic thread allocation in your OpenMP goes all the way up to the thread limit regardless of OMP_NUM_THREADS -- contrary to the wording in the 4.5 spec, where OMP_DYNAMIC is allowed to choose anything between 1 and min(available,limit).  The fix for that would be adding a call omp_set_dynamic(0) in the init.

**Comment by TurboGit** [comment]
> OMP_THREAD_LIMIT=4

This fixes the problem indeed.

But adding omp_set_dynamic() does not solves the issue:

```
diff --git a/src/common/darktable.c b/src/common/darktable.c
index 9c6c75162..165e68309 100644
--- a/src/common/darktable.c
+++ b/src/common/darktable.c
@@ -866,6 +866,7 @@ int dt_init(int argc, char *argv[], const gboolean init_gui, const gboolean load
 
 #ifdef _OPENMP
   omp_set_num_threads(darktable.num_openmp_threads);
+  omp_set_dynamic(0);
 #endif
```

**Comment by ralfbrown** [comment]
Doing more web searches hasn't located any further useful hints (unlike NUM_THREADS, there's no function call equivalent to the environment variable for OMP_THREAD_LIMIT).

Since the integration tests are the only place where it's critical to have the exact number of threads, let me suggest just adding OMP_THREAD_LIMIT=4 to run.sh.

**Comment by TurboGit** [comment]
Yep, will do that.

I have even checked that omp_get_max_threafs() properly return 4 but yet it seems that the loop is using far more threads.

**Comment by TurboGit** [comment]
All good now, merging !

**Pull request merged**
