### PR TITLE
Fix "find location" function

### LINKED ISSUE #2006: Broken "Find location" on Windows
**Describe the bug**
I just want to draw attention on a Windows bug described on Redmine: [the "find location" feature is broken on Windows](https://redmine.darktable.org/issues/12523). It seems serious enough to have a totally broken feature on a new version build.

It is a Windows port issue, as the feature is working fine on Linux.

**To Reproduce**
1. Go to 'map'
2. Enter location
3. Press 'Enter'

**Expected behavior**
A list of possible locations should appear.

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows 10 64 bits.
 - Version 2.6.0

### PR DESCRIPTION
**Pull request by peterbud**
Fixes #2006 

Similar changes are needed for using curl at facebook, piwigo and picasa upload, but I could not test those cases unfortunately. Facebook is not working for me in it's original state, and I don't have piwigo and picasa account, so I decided not to change them blindly.

In case somebody is maintaining those, it would be trivial to apply this solution before each `curl_easy_perform() `call

### CODE REVIEW

**Comment by TurboGit** [comment]
@peterbud : I understand for not changing blindly, but we are disable SSL check for the export module for now, so it works.

Now I'd like to fix this for better security. So I'll do the change, I'll check that all is well with picasa and piwigo (I have account). I'll change blindly for Facebook. And then I'll try to check that on Windows when 2.6.1 is released.

**Comment by parafin** [comment]
> Why cant we use the system CA store?
> 
> Even more Why ... WHY is this on for all platforms? If windows needs it ... guard it accordingly.

It's also useful on macOS and shouldn't hurt on Linux either.

**Comment by TurboGit** [comment]
@daris: the CA is only installed on Windows for now. So no problem. And if needed Linux and MacOS user could put a CA file at the right place. So all in all, currently it is a no-op expect on Windows.

**Comment by techexo** [comment]
@TurboGit or @peterbud Shouldn't this PR be in the 2.6.1 milestone, as #2028 was, as it replaces it?

**Comment by TurboGit** [comment]
Yes, it should be in 2.6.1. I'm waiting for more tests on Linux to ensure nothing is broken.

**Pull request merged**
