### PR TITLE
attempt to fix #6774

### LINKED ISSUE #6774: unsupported output profile reported
**Describe the bug**

unsupported output profile reported

**To Reproduce**

Just start current dt, and see on console:

```
[dt_ioppr_set_pipe_output_profile_info] unsupported output profile 2 , it will be replaced with sRGB
[dt_ioppr_set_pipe_output_profile_info] unsupported output profile 2 , it will be replaced with sRGB
[dt_ioppr_set_pipe_output_profile_info] unsupported output profile 2 , it will be replaced with sRGB
[dt_ioppr_set_pipe_output_profile_info] unsupported output profile 2 , it will be replaced with sRGB
[dt_ioppr_set_pipe_output_profile_info] unsupported output profile 8 , it will be replaced with sRGB
[dt_ioppr_set_pipe_output_profile_info] unsupported output profile 8 , it will be replaced with sRGB
[dt_ioppr_set_pipe_output_profile_info] unsupported output profile 8 , it will be replaced with sRGB
[dt_ioppr_set_pipe_output_profile_info] unsupported output profile 8 , it will be replaced with sRGB
[dt_ioppr_set_pipe_output_profile_info] unsupported output profile 8 , it will be replaced with sRGB
[dt_ioppr_set_pipe_output_profile_info] unsupported output profile 8 , it will be replaced with sRGB
[dt_ioppr_set_pipe_output_profile_info] unsupported output profile 8 , it will be replaced with sRGB
[dt_ioppr_set_pipe_output_profile_info] unsupported output profile 8 , it will be replaced with sRGB
```

**Expected behavior**

no error on console

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: GNU/Linux Debian

**Additional context**

Very recent regression.

### LINKED ISSUE #6781: histogram is bunched up to the right
Screenshot_2020-11-07_21-00-01

This is from an image that definitely has black in it so should be well spread out. Histogram of the same image from an earlier (dirty) build:

Screenshot_2020-11-07_21-01-30

git bisect says...

48b533fc14ab81c43bcca9202548287bd3f27e29 is the first bad commit
commit 48b533fc14ab81c43bcca9202548287bd3f27e29
Author: Aurélien PIERRE <aurelien@aurelienpierre.com>
Date:   Sat Nov 7 14:47:58 2020 +0100

    write output profile in pipeline
    forgotten file from commit 88adadf

 src/iop/colorout.c | 3 +++
 1 file changed, 3 insertions(+)

### PR DESCRIPTION
**Pull request by aurelienpierre**
@TurboGit could you try that ?

fix #6781 fix #6774

### CODE REVIEW

**Comment by TurboGit** [comment]
No still does not work. As soon as I enter darkroom I get a bunch of:

```
WORK : matrix_in : 0,673480, matrix_out : 1,647233 
INPUT INIT : matrix_in : nan, matrix_out : nan 
INPUT CORRECT : matrix_in : 0,876097, matrix_out : 1,135193 
WORK : matrix_in : 0,673480, matrix_out : 1,647233 
INPUT INIT : matrix_in : 0,876097, matrix_out : 1,135193 
INPUT CORRECT : matrix_in : 0,876097, matrix_out : 1,135193 
OUTPUT : matrix_in : nan, matrix_out : nan 
[dt_ioppr_set_pipe_output_profile_info] unsupported output profile 8 , it will be replaced with sRGB
OUTPUT : matrix_in : nan, matrix_out : nan 
[dt_ioppr_set_pipe_output_profile_info] unsupported output profile 8 , it will be replaced with sRGB
WORK : matrix_in : 0,673480, matrix_out : 1,647233 
INPUT INIT : matrix_in : 0,876097, matrix_out : 1,135193 
INPUT CORRECT : matrix_in : 0,876097, matrix_out : 1,135193 
OUTPUT : matrix_in : nan, matrix_out : nan 
[dt_ioppr_set_pipe_output_profile_info] unsupported output profile 8 , it will be replaced with sRGB
```
At least there is no `nan` now.

**Comment by aurelienpierre** [comment]
So there is no problem here.

The type 8 means `DT_COLORSPACE_DISPLAY = 8` profile. darktable tries to fetch the matrix and LUT from that profile if it can, to process it internally and faster. If it can't, it puts NAN in `matrix_in[0]` and `matrix_out[0]` which disables the darktable color path and forces LittleCMS2 handling in colorout.

What we need the output color profile for is to convert the RGB properly to XYZ, in order to use the parametric masking properly with JzAzBz. If your display profile is one darktable can't handle internally, switching to sRGB is the safest bet. 

Anyway, this will color space is only used for modules using blending **after** colorout, which consist only in the watermark module. By the way, the SVG files used in watermark also assume sRGB and have no proper color management if that condition is not met.

So the output line is not a regression, merely a log. Should I remove it ?

**Comment by elstoc** [comment]
Appears to resolve #6781 as well

**Comment by TurboGit** [comment]
Yes, if it is indeed OK and so fixed we need to remove all debug output. Such output should only happen when there is errors. TIA.

**Comment by aurelienpierre** [comment]
Sure, debug was not meant to stay.

**Pull request merged**
