### PR TITLE
tag fix - repair darktable tags not detachable

### PR DESCRIPTION
**Pull request by phweyland**
Hopefully solves #4677 and should be compatible with 3.0.2

removed a piece of unused code plus added some const.

Looking at the issue I've found other problems in copy metadata which are related to new lighttable changes. I'll make another PR for that => 3.2.

Thanks

### CODE REVIEW

**Comment by TurboGit** [comment]
@phweyland : should this be merged in master and darktable-3.0.x or only darktable-3.0.x?

**Comment by TurboGit** [comment]
BTW, this does not apply on darktable-3.0.x.

**Comment by phweyland** [comment]
> BTW, this does not apply on darktable-3.0.x.

I can go back to last commit for 3.0.1, apply these changes and push --force again.
But probably it won't apply on 3.2 anymore...
Is that the way to do ?

**Comment by TurboGit** [comment]
Yes. Push in a new branch and create a new PR if you think this PR is ok for master.

**Comment by phweyland** [comment]
Seems to be wrong.
I've tried to open another PR comparing against tag 3.0.1 but I have no option to rise it.

I need help ... :-)
Can you apply the 3 files changes on your side ?

**Comment by TurboGit** [comment]
> I need help ... :-)
> Can you apply the 3 files changes on your side ?

I need help too :) You have now 201 files changed !

Hard to says what you did wrong :( You may have rebased on 3.0.1 instead of darktable-3.0.x branch.

**Comment by TurboGit** [comment]
Is that the single good commit to apply fbfce4a822d9f4e7e451b2c0d56c317f604ec6be ?

Is should go on master, right ?

**Comment by phweyland** [comment]
> Is should go on master, right ?

No, only on 3.0.1

Don't know if that helps, comparing with 3.0.1 I get this:

**Comment by phweyland** [comment]
> Is that the single good commit to apply [fbfce4a](https://github.com/darktable-org/darktable/commit/fbfce4a822d9f4e7e451b2c0d56c317f604ec6be) ?

yes

**Comment by phweyland** [comment]
> You may have rebased on 3.0.1 instead of darktable-3.0.x branch.

Yes it's what I did. Good to know !

**Comment by scorpi11** [comment]
I can confirm that my issue was solved with @phweyland 's tag-fix-3.0.1 branch.

**Comment by TurboGit** [comment]
Manually merged in 3.0.x branch.

**Comment by phweyland** [comment]
> Manually merged in 3.0.x branch.

Thanks, I'll do better next time.

**Pull request closed without merging**
