### PR TITLE
[imageio] Implementation of export to email in Windows

### LINKED ISSUE #15363: [Windows] [imageio] Export and send as email doesn't work in Windows
When I try to export images and send as an email in Windows it does not complete successfully. The files are exported to a temporary folder and the process ends silently without calling the mail client. The reason is that the code contains a call to "xdg-email", which obviously does not exist in Windows.

This is understandable, because the code for sending via email was written long before the Windows platform was supported. When Windows is supported, we should either not compile this target storage for Windows, or implement the corresponding Windows-specific code.

### PR DESCRIPTION
**Pull request by victoryforce**
Resolves #15363.

### CODE REVIEW

**Comment by wpferguson** [comment]
Tested on win10.  

Did an export and got `there is no email program associated...` error, even though the default application for mail is configured as the included windows mail client.  I hadn't set it up yet, so I did and tried again.  Still got the error.

If I got the error the first time, then tried exporting again, I didn't get an error but I did see a message pop up about exporting to AppData/Temp.

**Comment by victoryforce** [comment]
> Tested on win10.
> 
> Did an export and got `there is no email program associated...` error, even though the default application for mail is configured as the included windows mail client.

My understanding is that setting the default email program in Windows Settings has nothing to do with choosing a client to send via MAPI. This setting only specifies the program that is called to process the mailto URI. I had and now have Google Chrome as the default email program in Settings, while sending emails via MAPI works fine for me via Outlook.

> I hadn't set it up yet, so I did and tried again. Still got the error.

In Windows, the inability to send email if the local email client is not configured with an email account and an IMAP server is expected. In Linux, similarly, xdg-email will fail if known mail clients are not installed, and if the running client is not configured, it is impossible to send email until the account and server settings are completed.

> If I got the error the first time, then tried exporting again, I didn't get an error but I did see a message pop up about exporting to AppData/Temp.

The message about the export to the temporary files folder should appear, this is how "send as email" works, first the export takes place, then in `finalize_store()` the exported images are attached to the email. This message is displayed in the same way under Linux.

I'm afraid I may be misunderstanding the final result of your testing. Did you manage to finally get your mail client running with images attached?

**Comment by wpferguson** [comment]
> I'm afraid I may be misunderstanding the final result of your testing. Did you manage to finally get your mail client running with images attached?

I could not get it to work with the default windows e-mail client, which is supposedly MAPI compliant according to Microsoft.

After reading your response I tried setting the mailto client to Google Chrome, Microsoft Edge, the default windows mail client, and finally outlook, which I downloaded and installed.  No matter what client I used, darktable just responded with the `no email program associated...` error.  I rebooted in between client changes just to make sure that the system was cleanly initialized with the current email program.

**Comment by victoryforce** [comment]
As far as I can tell from [googling](https://www.google.com/search?q=no+email+program+associated), your error is not that uncommon, with many "how-to" articles devoted to it, but it's hard to say for sure what could be causing it. Even interaction with Cortana is called among the culprits.

I didn't get such an error, all I had to do was add an account with login and server settings in Outlook. After the client was configured, both the trivialized test code and the final code in darktable worked without issue...

It's unfortunate that this issue is preventing testing. I would like confirmation that the code is working somewhere other than my Windows. I would like to emphasize that the code framework for working with "Simple MAPI" is quite simple and is found in many programs, so I do not expect that there are any problems with it. But, still... I would like to see confirmation that everything is fine.

If I'm not mistaken, @zisoft, I recall that in addition to macOS, you have the option to test on Windows?

**Comment by zisoft** [comment]
> If I'm not mistaken, @zisoft, I recall that in addition to macOS, you have the option to test on Windows?

Yes, I can have a look on monday

**Comment by wpferguson** [comment]
I did a little more troubleshooting.  I tried using file manager and right clicking on a file and using send to.  I got the same `no email program associated...` error so it's definitely a windows configuration issue, not a darktable problem.  

I tried all the stuff for fixing it, but didn't have any luck.

There's a reason I use Linux as my daily driver :smile:

**Comment by victoryforce** [comment]
@zisoft Thank you, that's great news.

@TurboGit So, I am positive that this PR can be safely merged.

**Comment by zisoft** [comment]
@victoryforce: Never used that export target but while testing this I just tried on macOS... nothing happens.
The file gets exported and the log tells `22.6564 [email] launching 'xdg-email --subject ...`
There is no `xdg-email` on macOS. 

@wpferguson: Sure, will try tomorrow. But as long as you cannot send a file via right-click in explorer there must be something else missing.

**Comment by wpferguson** [comment]
@zisoft the -d flag is another issue, but since I'm already having a problem with sendto I thought I'd try and "independent second opinion".  I did try it on a Win11 box and I can't sendto on that either and the -d flag results in a quick exit.

**Comment by victoryforce** [comment]
> Mine currently exits silently, but I'm not sure if it's a darktable problem or a windows problem

From looking at the code I can say for sure that this is a darktable problem. I'll make a fix today as soon as I get to my computer.

**Comment by victoryforce** [comment]
> @victoryforce: Never used that export target but while testing this I just tried on macOS... nothing happens. The file gets exported and the log tells `22.6564 [email] launching 'xdg-email --subject ...` There is no `xdg-email` on macOS.

Exactly, the situation is the same as in Windows. We need to either add a macOS-specific implementation (similar to what is done for Windows), or disable the target storage "send as email" for the macOS platform, as this is better than keeping broken functionality in the interface.

**Comment by zisoft** [comment]
> There is no xdg-email on macOS

`open -a Mail file1.jpg file2.jpg ...`

works on macOS. Unfortunately no subject can be passed.
And this opens the macOS built in mail client even if the user is using a different app. But this is even better than no reaction without feedback.

This should be trivial to implement. I can prepare a PR when this one is merged.

**Comment by TurboGit** [comment]
Ok, just to be sure this is safe to merge as it fully fixes the issue on Windows and a separate PR will be proposed for macOS. Right?

**Comment by zisoft** [comment]
Yes, I have the macOS implementation ready. Because the changes are in the same file, I wanted to wait for this PR to be merged first.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by TurboGit** [comment]
Merged then, thanks!

**Pull request merged**
