### PR TITLE
Rewrite FindGettext to be simpler & better.

### PR DESCRIPTION
**Pull request by mazhe**
Hi,

I've been having issues with gettext detection, I've checked a bit the project and they don't seems to provide canonicaly a pkg-config file, and libintl is a simple library only linking with libc

I took advantage of that to rewrite a very simple FindGettext, would you consider including it?

### CODE REVIEW

**Comment by houz** [comment]
I tried to remove gettext from cmake alltogether, please see if that is allowing you to compile darktable. These tests should have been unused anyway.

**Comment by mazhe** [comment]
Actualy, it break build on my system (FreeBSD 10.1, clang 3.3, GNU ld 2.17.50):

>Linking C executable darktable-cli
>cd /home/mazhe/Devel/graphics/darktable2/build/src/cli && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/darktable-cli.dir/link.txt --verbose=1
>/usr/bin/cc   -std=c99 -Wall -fno-strict-aliasing -pthread -march=native -msse3 -g -Werror -Werror=type-limits -O2 -g -DNDEBUG -O2   CMakeFiles/darktable-cli.dir/main.c.o  -o darktable-cli  ../libdarktable.so ../external/rawspeed/librawspeed.a ../external/LuaAutoC/liblautoc.a /usr/local/lib/libgtk-3.so /usr/local/lib/libgdk-3.so /usr/local/lib/libpango-1.0.so /usr/local/lib/libcairo.so /usr/local/lib/libgdk_pixbuf-2.0.so /usr/local/lib/libatk-1.0.so /usr/local/lib/libxml2.so /usr/local/lib/libIlmImf.so /usr/local/lib/libImath.so /usr/local/lib/libIex.so /usr/local/lib/libIlmThread.so /usr/local/lib/liblensfun.so /usr/local/lib/libgio-2.0.so /usr/local/lib/libglib-2.0.so /usr/local/lib/libgthread-2.0.so /usr/local/lib/libgmodule-2.0.so /usr/local/lib/libpangocairo-1.0.so -lpthread /usr/local/lib/librsvg-2.so /usr/local/lib/libsqlite3.so /usr/local/lib/libexiv2.so /usr/local/lib/libcurl.so /usr/local/lib/libpng.so -lz /usr/local/lib/libjpeg.so /usr/local/lib/libtiff.so /usr/local/lib/liblcms2.so /usr/local/lib/libjson-glib-1.0.so /usr/local/lib/libopenjpeg.so -L/usr/local/lib -llua-5.2 -lm /usr/local/lib/libcups.so -Wl,-rpath,/home/mazhe/Devel/graphics/darktable2/build/src:/usr/local/lib: 
>/usr/bin/ld: /usr/local/lib/libintl.so.8: invalid DSO for symbol `libintl_bindtextdomain' definition
>/usr/local/lib/libintl.so.8: could not read symbols: Bad value
> cc: error: linker command failed with exit code 1 (use -v to see invocation)

I understand this is kinda a GNU ld "feature" that requires explicit linking against all dependencies, including those coming from other shared libraries (this was the bug that prompted me to rewrite the FindGettext module in the first place)...

I guess I could use something like -DCMAKE_C_STANDARD_LIBRARIES="/usr/local/lib/libintl.so" at cmake invocation, which is quite annoying with since I always have to then re-find it the next time I have to wipe and rebase my workdir against upstream...

**Comment by parafin** [comment]
The error message you posted and your explanation for it don't match. ld definitely doesn't require to list indirect dependencies (unless it's a static lib of course).

**Comment by mazhe** [comment]
Ok, this one is kinda weird, but not new : it seems there were already traces of a freebsd-specific libintl linking in src/cli/CMakeLists.txt... Except it was supposely confined to gcc < 4.3 (I have not been able to build darktable with gcc/g++ since freebsd switched to libc++).

If you have any idea, I could test them, but the dirty workaround would be to link regardless on the compiler on the *BSD platforms, would not it? (despite working without that two weeks ago).

**Comment by parafin** [comment]
IMHO, the actual problem is that we do actually directly use libintl (e.g. bindtextdomain function), so removing gettext detection was just plain wrong.

**Comment by houz** [comment]
I reverted 8d26343af849f3d2ab2e6e032fcf8161c496f76e even though I don't understand the problem, either Glib's i18n stuff pulls in what is needed, or it shouldn't compile.
Next time please say that a patch is for fixing BSD so people knowing about obscure platforms can have a look instead of me.

**Comment by parafin** [comment]
https://developer.gnome.org/glib/stable/glib-I18N.html doesn't include bindtextdomain as provided function, so we are using gettext directly even if we also use some glib wrappers around it. It just happens that on Linux gettext seems to be included into libc, so linking doesn't fail.

**Comment by mazhe** [comment]
Sorry for bringing my obscure platform problems, I never noticed gettext functions were inside the glibc before.

I've updated the pull request taking account that.

**Comment by LebedevRI** [comment]
What about this PR?

@mazhe Are the changes still needed?
If yes, could you please update the pr?

**Comment by mazhe** [comment]
Sorry for the delay, I had to review the issue and the changes over last year.

Seems OK on the platforms I manage daily (FreeBSD/OSX): pkgconfig for the former, cmake find_library for the latter. I am closing the issue, thanks for your hard work!

**Pull request closed without merging**
