### PR TITLE
Add WB presets for Canon 760D

### PR DESCRIPTION
**Pull request by jnegre**
This commit adds the WB presets for the Canon 760D

### CODE REVIEW

**Comment by pedrocr** [comment]
This looks fine but I'd like to have a look at the source files. Could you upload them somewhere and link them here?

By the way you can use the script in tools/extract_wb to generate the presets. It should format them a bit better.

**Comment by jnegre** [comment]
extract_wb was used, but it had a hard time on my files.

The files I used have been deleted since my patch, I will upload new ones ASAP.

**Comment by jnegre** [comment]
You'll find the raws + the ouput of extract_wb at http://jnegre.org/tmp-pullrequest-darktable/

**Comment by pedrocr** [comment]
Thanks. Note that's not the output of extract_wb it's wb_extract.pl from ufraw. Our extract_wb should produce better output in most cases although it doesn't support these images yet for some reason.

**Comment by pedrocr** [comment]
Seems like I just had a too old exiftool. The script works mostly fine as is. Just need to fix up a bug or two.

**Comment by pedrocr** [comment]
extract_wb in master now deals with these files properly. Do you want to push a commit with the output yourself or should I do it now that I have the file?

**Comment by jnegre** [comment]
Here it is.

Sorry for having several commits, running extract_wb wasn't straightforward on my system. If you feel like rejecting this pull request and want to make your own, clean commit, I won't be mad.

**Comment by pedrocr** [comment]
The diff looks fine. Could you just squash the 4 commits into a single one?

**Comment by pedrocr** [comment]
The easiest way to do it is probably to just reset the branch back to master, add a single new commit and then force push to the same remote branch.

**Comment by jnegre** [comment]
Will try.

**Comment by pedrocr** [comment]
We were trying to get a release out so I pushed a single commit with you as author with these changes:

https://github.com/darktable-org/darktable/commit/842546a3a569131aa63c8cd4dd52fb5245b60977
https://github.com/darktable-org/darktable/commit/c2f7fdb1fce2d1206cb6b86d19a2de03f71e2448

Hope that's ok with you.

**Comment by jnegre** [comment]
That's perfectly fine with me, I was making a mess of my local repository :-(
Thanks for your work.

**Pull request closed without merging**
