### PR TITLE
reformatting pixelpipe and cleanup

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Minor reformatting as proposed codestyle while checking all over and making use of `dt_print(DT_DEBUG_ALWAYS` instead of `fprintf(stderr`

### CODE REVIEW

**Comment by dterrahe** [comment]
> proposed codestyle

Where is that proposed/documented? The indentation looks somewhat random, but maybe that's my phone?

**Comment by TurboGit** [comment]
> EDIT2: having a stream of separate code formatting commits is going to make git blame useless. :sad:

I understand, yet this is only for function headers which are mostly unreadable (to me) today.

**Comment by TurboGit** [comment]
@dterrahe : BTW, I'm sure I have seen a question from you to me about Git, I cannot find where it was... Do you remember?

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
