### PR TITLE
Make dual action of one star rating a config option

### PR DESCRIPTION
**Pull request by itinerarium**
Bug tracker: https://redmine.darktable.org/issues/9959

Per https://www.darktable.org/usermanual/ch02s02s04.html.php, "Clicking ... the first star for a second time resets the image rating to unranked, or zero stars." 

While documented, the default behavior is problematic as attempting to re-rate an image one star (e.g., by reflex) will, instead, clear the star rating for that image. Similar note from mailing list: https://www.mail-archive.com/darktable-user@lists.darktable.org/msg01249.html.

A config option to enable/disable this behavior would be preferable.

(Separately, it appears that the code for processing ratings for the lighttable and darkroom views is different. Is any background available?)

### CODE REVIEW

**Comment by LebedevRI** [comment]
https://github.com/darktable-org/darktable/blob/master/CONTRIBUTING.md#code

**Comment by itinerarium** [comment]
Did the most recent commit address the coding style issue?

**Comment by LebedevRI** [comment]
I was specifically linking to:
> Code

> Before you spend a lot of time working on a new feature, it's always best to discuss your proposed changes with us first. The best place to do that is in our IRC channel on irc.freenode.net, channel #darktable or the development mailing list, see here for more information. This will dramatically improve your chances of having your code merged, especially if we think you'll hang around to maintain it.

**Comment by itinerarium** [comment]
Got it. Will try IRC for this item.

**Comment by LebedevRI** [comment]
@itinerarium thanks, merged manually. commit messages are rather useless tbn :)

**Pull request closed without merging**
