### PR TITLE
slideshow: fix minimum delay to 2s and 4s when using high quality.

### LINKED ISSUE #3253: Slideshow Extremely slow and freezes
**Describe the bug**
Have collection of 448 pics.
In lightable view.
Press S to start slideshow.
Machine starts spinning out of control with memory usage spiking, mouse disappears.
Slideshow preference has a 1 second delay between images.
Press the space bar to start slideshow.
Images dont change, clicking on the screen or using arrow keys or tab does nothing or it takes a long time to do anything
When it does start to change  the pic the CPU usage is 100% memory usage crosses 1Gb, after  slide change it comes back to 0.
I have seen the usage climb as high as 
image

What I have figured out with trial and error, left click takes it forward, right click takes it backwards, havent figured out how to get out of the slideshow yet. Is this documented somewhere ?

Have to kill darktable to get out of slideshow.
Opencl is permanently disabled on my 2.7 version.
Have 32 GB Ram.
Images are on external SSD.

**Platform (please complete the following information):**
 - OS: Win 10
 - Version 2.7.0+2113~gefde14b3d

### PR DESCRIPTION
**Pull request by TurboGit**
Fixes #3253.

### CODE REVIEW

**Comment by parafin** [comment]
Doesn't delay heavily depend on PC processing power and history stack applied to the particular image?

**Comment by TurboGit** [comment]
> Doesn't delay heavily depend on PC processing power and history stack applied to the particular image?

Yes it does. But there is almost no way to compute this properly (disk speed SSD or not, swap, current jobs...). So what I propose here is just a minimum that will help avoiding some/most problems.

**Comment by parafin** [comment]
Assumptions about computer performance tend not to hold for very long. "640 KB is enough for everybody."
I mean I'm not sure what problem this PR might solve. In a lot of cases the limits you are proposing won't be high enough anyway. And in others (maybe in the future) these limits instead will put unnecessary restrictions on the user. IMHO the only thing relevant here is how fast image change makes sense in a slideshow. 1 second is a good guess.

**Comment by TurboGit** [comment]
I have a better solution... Closing this PR.

**Pull request closed without merging**
