### PR TITLE
add missing thread-safety-analysis annotations to permit Debug build …

### PR DESCRIPTION
**Pull request by ralfbrown**
…with llvm/clang

Compiler annotations for thread safety analysis were only present on the non-debug code in common/dtpthread.h, which caused `./build.sh --build-type Debug` to fail for llvm/clang.

Fixes the issue mentioned by @MStraeten in a comment on #7349.

### CODE REVIEW

**Comment by MStraeten** [comment]
doesn't fix the issue.

**Comment by MStraeten** [comment]
build with  -DCMAKE_BUILD_TYPE=Debug is successful with OSX,
but darktable crashs immediately:
```
Assertion failed: (!ret), function dt_pthread_mutex_lock_with_caller, file /Users/martinstraeten/src/darktable_debug/src/common/dtpthread.h, line 115.
Process 74278 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = hit program assert
    frame #4: 0x000000010039fa91 libdarktable.dylib`dt_pthread_mutex_lock_with_caller(mutex=0x0000000110a3a0e8, file="/Users/martinstraeten/src/darktable_debug/src/gui/gtk.c", line=312, function="update_focus_peaking_button") at dtpthread.h:115:3
   112 	{
   113 	  const double t0 = dt_pthread_get_wtime();
   114 	  const int ret = pthread_mutex_lock(&(mutex->mutex));
-> 115 	  assert(!ret);
   116 	  mutex->time_locked = dt_pthread_get_wtime();
   117 	  double wait = mutex->time_locked - t0;
   118 	  mutex->time_sum_wait += wait;
Target 0: (darktable) stopped.
```

**Comment by ralfbrown** [comment]
Unfortunately I can't reproduce (at least in part because it runs single-threaded due to lack of OpenMP with clang-8).  Does anything bad happen if you remove the assertion?

**Comment by MStraeten** [comment]
removing the assertion there results in a later crash
```
Assertion failed: (!ret), function dt_pthread_mutex_unlock_with_caller, file /Users/martinstraeten/src/darktable_debug/src/common/dtpthread.h, line 195.
Process 6125 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = hit program assert
    frame #4: 0x000000010039ffb6 libdarktable.dylib`dt_pthread_mutex_unlock_with_caller(mutex=0x00000001112750e8, file="/Users/martinstraeten/src/darktable_debug/src/gui/gtk.c", line=314, function="update_focus_peaking_button") at dtpthread.h:195:3
   192
   193 	  // need to unlock last, to shield our internal data.
   194 	  const int ret = pthread_mutex_unlock(&(mutex->mutex));
-> 195 	  assert(!ret);
   196 	  return ret;
   197 	}
   198
Target 0: (darktable) stopped.
```

**Comment by ralfbrown** [comment]
Hmm, that's the matching unlock function for the lock which had previously triggered an assertion.  Since none of the calls to that function actually check the return value, removing this second assertion will let things go further, but again might cause bad things to happen later.

**Comment by parafin** [comment]
Where exactly is darktable->gui.mutex initialized? I couldn't find it. If it's not initialized, no wonder lock and unlock operations fail.

**Comment by MStraeten** [comment]
```
Assertion failed: (!ret), function dt_pthread_mutex_destroy, file /Users/martinstraeten/src/darktable_debug/src/common/dtpthread.h, line 68.
Process 91589 stopped
* thread #14, name = 'worker 7', stop reason = hit program assert
    frame #4: 0x00000001002cb007 libdarktable.dylib`dt_pthread_mutex_destroy(mutex=0x00007000019f5870) at dtpthread.h:68:3
   65  	static inline int dt_pthread_mutex_destroy(dt_pthread_mutex_t *mutex)
   66  	{
   67  	  const int ret = pthread_mutex_destroy(&(mutex->mutex));
-> 68  	  assert(!ret);
   69
   70  	#if 0
   71  	  printf("\n[mutex] stats for mutex `%s':\n", mutex->name);
Target 0: (darktable) stopped.
(lldb) up
frame #5: 0x00000001002cac04 libdarktable.dylib`dt_dev_cleanup(dev=0x00007000019f57f0) at develop.c:144:3
   141 	  if(!dev) return;
   142 	  // image_cache does not have to be unref'd, this is done outside develop module.
   143 	  dt_pthread_mutex_destroy(&dev->pipe_mutex);
-> 144 	  dt_pthread_mutex_destroy(&dev->pipe_mutex);
   145 	  dt_pthread_mutex_destroy(&dev->preview_pipe_mutex);
   146 	  dt_pthread_mutex_destroy(&dev->preview2_pipe_mutex);
   147 	  dev->proxy.chroma_adaptation = NULL;
(lldb) up
frame #6: 0x00000001001fcead libdarktable.dylib`dt_imageio_export_with_flags(imgid=1, filename="unused", format=0x00007000019f80c8, format_params=0x00007000019f8028, ignore_exif=1, display_byteorder=0, high_quality=0, upscale=0, thumbnail_export=1, filter=0x0000000000000000, copy_metadata=0, export_masks=0, icc_type=DT_COLORSPACE_NONE, icc_filename=0x0000000000000000, icc_intent=DT_INTENT_LAST, storage=0x0000000000000000, storage_params=0x0000000000000000, num=1, total=1, metadata=0x0000000000000000) at imageio.c:1044:3
   1041	    goto error;
   1042
   1043	  dt_dev_pixelpipe_cleanup(&pipe);
-> 1044	  dt_dev_cleanup(&dev);
   1045	  dt_mipmap_cache_release(darktable.mipmap_cache, &buf);
   1046
   1047	  /* now write xmp into that container, if possible */
(lldb)
```

**Comment by ralfbrown** [comment]
OK, so that was obviously not the only mutex problem.  This one is easy to diagnose from what you've posted -- it's a double destroy, so we can just delete that line.

**Comment by parafin** [comment]
I wonder how many issues on macOS were caused by this missing darktable.gui->mutex initialization. It may be worth to re-check cairo crashes with newer Xcode after this PR finally works, @MStraeten.

**Comment by MStraeten** [comment]
Build fails in Debug mode, fine for RelWithDebInfo
```
In file included from /Users/martinstraeten/src/darktable_debug/src/control/control.h:21:
/Users/martinstraeten/src/darktable_debug/src/common/darktable.h:346:49: fatal error: 'acquire_capability' attribute requires
      arguments whose type is annotated with 'capability' attribute; type here is 'dt_pthread_mutex_t'
      (aka 'struct dt_pthread_mutex_t') [-Wthread-safety-attributes]
static inline void dt_lock_image(int32_t imgid) ACQUIRE(darktable.db_image[imgid & (DT_IMAGE_DBLOCKS-1)])
                                                ^
/Users/martinstraeten/src/darktable_debug/src/external/ThreadSafetyAnalysis.h:37:33: note: expanded from macro 'ACQUIRE'
  THREAD_ANNOTATION_ATTRIBUTE__(acquire_capability(__VA_ARGS__))
                                ^
1 error generated.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/bauhaus/bauhaus.c.o] Error 1
make[1]: *** [bin/CMakeFiles/lib_darktable.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ralfbrown** [comment]
Wait - I added the annotation to `dt_pthread_mutex_t` in the first commit for this PR....

**Comment by parafin** [comment]
Those are different functions, they need those annotations too.

**Comment by ralfbrown** [comment]
Nope, same function at the same line number as in the original report which led to this PR.  And it's the type which needs the annotation being complained about. 
@MStraeten did you compile with the full PR or just the one-line deletion from the last commit?

**Comment by MStraeten** [comment]
did 
```
git reset --recurse-submodules --hard origin/master
git pull -f --no-edit --recurse-submodules https://github.com/darktable-org/darktable.git master
git pull -f --no-edit https://github.com/darktable-org/darktable.git pull/7363/head
```
It’s fine now - maybe there was something left or not properly merged earlier

**Comment by parafin** [comment]
Yeah, sorry, read the error message too fast:)

@MStraeten, so dt now builds and runs in Debug mode on macOS for you, correct?

**Comment by MStraeten** [comment]
yep

**Comment by johnny-bit** [comment]
Well, this should help with debug builds for linux (and maybe win/osx) to be added to CI :)

**Comment by parafin** [comment]
@TurboGit, this is something definitely for 3.4.1, since one of the mutexes didn't work in dt before this PR, at least on macOS. It probably caused some amount of bugs.

**Comment by TurboGit** [comment]
@parafin : noted, indeed worrisome the missing init of a mutex.

@all: is that PR ready to go or is there some more work planned on it ?

**Comment by ralfbrown** [comment]
I say it's ready.

**Comment by TurboGit** [comment]
So let's merge this now in master and 3.4.1. Thanks.

**Pull request merged**
