### PR TITLE
Update for Hebrew translation

### PR DESCRIPTION
**Pull request by sbraitbart**
I don't understand whats wrong.
I did:
git fetch --all -p
git submodule update -f
git checkout master
git push origin master
git checkout -b translation
cd po
intltool-update he
poedit and updated the translation
git add po/he.po
git commit -m 'Updated Hebrew translation'
git push origin translation

Why wouldn't it auto merge?

Thanks
Shlomi

### CODE REVIEW

**Comment by houz** [comment]
The he.po hasn't any (relevant) changes in it.

**Comment by sbraitbart** [comment]
I did make changes. I will try the git flow again to try and find what went wrong.

**Comment by sbraitbart** [comment]
I am sorry but I need some help here. I don't know what went wrong but I can't fix the git. I did the following:

shlomi@avia:~/darktable2/darktable$ git fetch --all -p
Fetching origin
Fetching upstream
shlomi@avia:~/darktable2/darktable$ git submodule update -f
shlomi@avia:~/darktable2/darktable$ git checkout master && git reset --hard upstream/master
Already on 'master'
Your branch and 'origin/master' have diverged,
and have 395 and 6 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
HEAD is now at 11e8cec Merge remote-tracking branch 'upstream/pr/1456'
shlomi@avia:~/darktable2/darktable$ git pull
CONFLICT (file/directory): There is a directory with name src/external/rawspeed in 7249eb1ff9f06e6395bbc56b6aa2bed4e920b519. Adding src/external/rawspeed as src/external/rawspeed~HEAD
Auto-merging po/he.po
CONFLICT (content): Merge conflict in po/he.po
Automatic merge failed; fix conflicts and then commit the result.

I resolved the he.po file and went on:

shlomi@avia:~/darktable2/darktable$ git add po/he.po
shlomi@avia:~/darktable2/darktable$ git commit -m 'git fix'
U	src/external/rawspeed
error: commit is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit, or use
hint: 'git commit -a'.
fatal: Exiting because of an unresolved conflict.

What should I do now?

Thanks
Shlomi

**Comment by sbraitbart** [comment]
I forced update my origin master and I will update the translation again and initiate a new pull request.

**Comment by LebedevRI** [comment]
@sbraitbart i would recommend reading some articles/tutorials about git, it indeed takes some time/thought to get used to/understand...
Relevant:
[Xkcd Git](https://xkcd.com/1597/)

**Pull request closed without merging**
