### PR TITLE
imageio_im: read image profile, add WebP read fallback

### PR DESCRIPTION
**Pull request by kmilos**
~~Also added JXL to GraphicsMagick~~ and a few other small improvements @victoryforce 

Continues from https://github.com/darktable-org/darktable/pull/12533

### CODE REVIEW

**Comment by kmilos** [comment]
Caveat for the release notes: [GraphicsMagick does not currently support color profiles in JXLs and will decode and internally transform them to sRGB using libjxl's builtin methods](https://sourceforge.net/p/graphicsmagick/code/ci/171c0dd24d8ad781775a32c081c062e3699476e8/tree/coders/jxl.c#l595). As dt's `colorin` will fall back to sRGB the colors will be correct, but gamut clipping might have occurred and there is no way to get that data back. OTOH, [ImageMagick attempts to extract the original profile and pixel values](https://github.com/ImageMagick/ImageMagick/blob/c50602cc46b62b8342b8802b980714793f1730e0/coders/jxl.c#L409-L417).

TODO: dt should implement a native JXL reader as well.

**Comment by victoryforce** [comment]
> TODO: dt should implement a native JXL reader as well.

I am working on it now.

**Comment by kmilos** [comment]
> I am working on it now.

Great. You know about the export PR? Should use the CMake stuff from there....

**Comment by kmilos** [comment]
I have now verified both WebP and JXL import via ImageMagick using the [fixed MSYS2 package](https://github.com/msys2/MINGW-packages/pull/13287).

**Comment by TurboGit** [comment]
Hum... Embarrassing... I must be blind tonight but I cannot find a single jxl sample !!!! Lot of web site talk about this format, there is papers, blog post.... but no sample to download !

Actually I found one but it does not open, so not sure the image is correct. Do you have a file to share? TIA.

**Comment by victoryforce** [comment]
> Actually I found one but it does not open, so not sure the image is correct. Do you have a file to share? TIA.

Are you talking about the image from [this page](https://www.ghacks.net/2021/05/11/find-out-if-your-browser-supports-the-new-image-format-jpeg-xl/)? If so, then it should open, this is the correct image. But the point is that ImageMagick needs to be built with JXL support for this to work, and of all the distros and plaftorms I've checked, only the package for mingw does (thanks to kmilos).

**Comment by TurboGit** [comment]
@victoryforce : Yes it is the image on this page. I'll try again then... but I got a skull thumbs yesterday!

**Comment by TurboGit** [comment]
Ok, I see that:

`Magick: No decode delegate for this image format (/home/obry/Images/Darktable/format/IMG_20200308_194050.jxl).`

So I probably don't have a proper version of ImageMagick.

**Comment by TurboGit** [comment]
I have this one on my system:

```
libgraphicsmagick1-dev:
  Installed: 1.4+really1.3.38+hg16739-1
  Candidate: 1.4+really1.3.38+hg16739-1
  Version table:
 *** 1.4+really1.3.38+hg16739-1 750
        750 http://ftp.debian.org/debian unstable/main amd64 Packages
```

**Comment by kmilos** [comment]
Yes, it obviously depends on how GraphicsMagick/ImageMagick were built for a particular distro - I think Arch has it for example? Also note that libjxl/jpeg-xl/jpegxl could be marked as an optional dependency of the GM/IM package on some distros (plugin loaded at runtime) and needs to be installed additionally.

Perhaps I should split this in separate PRs that can be verified independently: 1) WebP for IM, and 2) JXL for GM/IM once the first is merged?

**Comment by TurboGit** [comment]
> 1) WebP for IM, and 2) JXL for GM/IM once the first is merged?

Yes please!

**Comment by kmilos** [comment]
Ok, this one now is WebP (+PAM) only. Verify w/ `-DUSE_WEBP=OFF -DUSE_GRAPHICSMAGICK=OFF -DUSE_IMAGEMAGICK=ON`

**Comment by kmilos** [comment]
> I cannot find a single jxl sample !!!!

Btw, this is also a good opportunity for you to test the JXL export PR ;)

**Comment by TurboGit** [comment]
> Btw, this is also a good opportunity for you to test the JXL export PR ;)

I have tested and reviewed, a minor comment and I'll merge. That's great to see this in dt.

**Review by TurboGit — APPROVED** [review]
Looks good to me, thanks!

**Comment by kmilos** [comment]
> Just a question it looks like ImageMagick is active project but GraphicMagick is almost dear. Right?

Unfortunately [GM is short on contributors](http://www.graphicsmagick.org/NEWS.html#id1) indeed...

**Pull request merged**
