### PR TITLE
lens: Adapted to Lensfun API

### PR DESCRIPTION
**Pull request by bronger**
It is now in sync with Lensfun commit 8e44481b (2019-07-18).

### CODE REVIEW

**Comment by jakubfi** [comment]
I would be against adding compatibility with the current git lensfun version, as it is still versioned as 0.3.95 in the tree, while being API-incompatibile with the released 0.3.95 tgz. There is currently no clean way (if any) to distinguish between 0.3.95 and current. I know this is experimental anyway, but let's stick to a released version at least.
There is a nice solution though, while I have your attention: 0.3.96 pretty please? :-)

**Comment by bronger** [comment]
Fair enough. I agree that both options are sub-optimal.

I don’t make releases as they are made by Sebastian Kraft.

**Comment by TurboGit** [comment]
Any update on this ? What is the status on lensfun side ? Last stable version ? Should this be pursued or closed ? TIA.

**Comment by TurboGit** [comment]
Since 0.3.95 is buggy and now even reverted from MSYS repository let's just close this.

**Pull request closed without merging**
