### PR TITLE
import: add tags presets combobox

### PR DESCRIPTION
**Pull request by phweyland**
- import_metadata: align tags ui on metadata
- import_metadata: update combo boxes on any presets change
- import_metadata: code cleaning
- libs: add presets change signal (init, new, update, delete)
- metadata: remove init presets signal (as done above)
- tagging: fix bug on set_params (only new tags were added)
- tags: make _tag_get_tags() answer for imgid = -1 as well

@elstoc, as I cannot test this myself I would appreciate if you could check the metadata combobox still initializes properly for you. TIA.

### CODE REVIEW

**Comment by elstoc** [comment]
@phweyland the metadata combobox initialises fine, but if I create a new metadata preset it gets put at the bottom of the list and isn't moved to the correct location until I restart.

**Comment by phweyland** [comment]
Thanks for testing.
> it gets put at the bottom of the list and isn't moved to the correct location until I restart

I'll look at this.


> I would comment that it's not entirely obvious what the second preset drop-down is for (the first is preceded by the "apply metadata" tick box so is more obvious)

I agree. I can rename the preset labels to "metadata preset" and "tags preset" but that may take too much place. It doesn't hurt to make a try. I'll do.

**Comment by elstoc** [comment]
Yeah I'm not a big fan of taking up extra width either

**Comment by phweyland** [comment]
@elstoc
Here I've changed the label for presets. Ellipsizing protects against enlargement. Still not perfect
Set them italic to make the difference with other lines.
And sorted out the comboboxes as in presets list.

image

@nilvus, some questions.
Do you have any recommendation about the usage of name or context (# or . in CSS) ?


` gtk_widget_set_name(label, "import_presets")`

or
` gtk_style_context_add_class(context, "import_presets");`


It could be visually more comfortable to have a separator line between the flags on the top and the metadata grid on the bottom. Thoughts ? Advice ?

**Comment by elstoc** [comment]
Ok that's fine, but could you rename it "tag presets" as it's more grammatically correct in English.

**Comment by phweyland** [comment]
> could you rename it "tag presets" as it's more grammatically correct in English.

thanks ! :) Done.

**Review by elstoc — APPROVED** [review]

**Comment by TurboGit** [comment]
I'll merge this as working for me but I found a little glitch for the two presets entries.

If you select an import preset that has `apply metadata` ticked then the _metadata presets_ & _tag presets_ combo are filed with the first item from the combo even though those are not the one corresponding to the metadata or tags entries.

**Comment by TurboGit** [comment]
@phweyland : let me know if you want me to create an issue for this.

**Comment by phweyland** [comment]
>  let me know if you want me to create an issue for this.

No need to create an issue. I'll look at this. Thanks

**Pull request merged**
