### PR TITLE
fix hold key regressions and modifier only fallbacks

### LINKED ISSUE #9752: cannot use 'w' key on french keyboard
**Describe the bug/issue**

The w key seems dead.

**To Reproduce**
1. Go to 'shortcut' in preference
2. Double-click on any action
3. Clic on '`w`' to define this key as shortcut for the action 
4. See error, nothing happens
5. Clic on `atl+w` to define this key as shortcut for the action
6. See error, the key shortcut is defined as `alt+`

**Expected behavior**

The `w` key should be active and properly used to define a shortcut. 

**Platform**
* darktable version : current master
* OS                : Linux / GNOME 3.38
* Linux - Distro    : Debian/sid

### PR DESCRIPTION
**Pull request by dterrahe**
fixes #9752

Switch off special treatment of hold shortcuts (like W or Ctrl-W for preview) while defining new shortcut (either in dialog or visually). This does logically result in emulated modifiers (on MIDI for example) not being treated as such while defining new shortcuts. So if midi key A is defined as ctrl modifier, the keyboard will need to be used to define ctrl+midi key B, even though afterwards A+B together will trigger the shortcut.

Also fixes hold shortcuts in combination with modifiers; only in the case where the hold shortcut actually is an emulated _modifier_ are other modifiers ignored (so you can do shift+ctrl+alt).

Third fix is for defining fallbacks; when defining a fallback shortcut, you can use _just_ modifiers (shift+, or shift+ctrl+alt+). You don't _have_ to (but _can_) combine them with moves or clicks. You _cannot_ combine them with normal key presses (because that would be the base shortcut that you are defining a fallback for).

### CODE REVIEW

**Comment by TurboGit** [comment]
Something still not working. Assignment is working, what I have done:

- Assigned `w` to preview
- Assigned `alt+w` to sticky preview

But now when I click on `w` I get a sticky preview instead of a standard preview where the preview should end as soon as the key is released.

**Review by TurboGit — CHANGES_REQUESTED** [review]
Assignment ok, usage seems broken.

**Comment by TurboGit** [comment]
> Is the effect of the w shortcut set to "hold" (the default)?

Yes.

> If it is, could you please send me your shortcutsrc?

Here it is.

[shortcutsrc.txt](https://github.com/darktable-org/darktable/files/6957390/shortcutsrc.txt)

**Comment by dterrahe** [comment]
I'm sorry, I'm not yet succeeding to reproduce. Does the `h`  key work as it should? Or `w` in darkroom (full preview)?

My suspicion is that you get somehow stuck in mapping mode but I don't know how. Do you have the problem even immediately after starting dt?

**Comment by TurboGit** [comment]
> My suspicion is that you get somehow stuck in mapping mode but I don't know how. Do you have the problem even immediately after starting dt?

Yes. And I have conducted another test which may help. I have removed shortcutsrc and started dt. I can use `w` and `alt-w` to display the preview. This seems wrong as `alt-w` is not assigned to any action.

**Comment by dterrahe** [comment]
This is strange. On my debian machine I've repeated your exact steps (switch to FR keyboard, delete shortcutsrc, start dt) and w (my z key) gives me a preview as long as I hold it and alt+w gives me "no fallback for alt+ lighttable/preview".

That's with gtk 3.24.29-1 and under kde/plasma. At the moment I have no ideas why you would see such different behavior. We may need to dig into what difference between our systems can explain it.

Would you please confirm that you have the same problems with h and darkroom full preview via w. And ctrl-w (preview with focus detection)?

**Comment by TurboGit** [comment]
> Would you please confirm that you have the same problems with h and darkroom full preview via w. And ctrl-w (preview with focus detection)?

Yes, `ctrl+w` give me the standard preview until I release the key.

**Comment by TurboGit** [comment]
I'm on GNOME Shell 3.38.5 with libgtk-3-0 3.24.24-4.

I have tested again (with same issue) after removing shortcutssrc and keyboardrc.

**Comment by dterrahe** [comment]
I'm afraid I still cannot reproduce. @johnny-bit @ralfbrown is this something you are seeing?

**Comment by johnny-bit** [comment]
Just tested it and it's interesting...

I deleted shortcutsrc to have `w` as "preview" and `f` as sticky, however `w` acts as if it was sticky! The effect for `w` is `hold`

same thing happens with `h` key which should only show help window as long as one holds h key, right?

**Comment by dterrahe** [comment]
I figured out with @johnny-bit 's help that this is caused by NumLock. It needs to be ignored like everywhere else. I will submit a fix hopefully today.

**Comment by johnny-bit** [comment]
After most recent commit the issue is gone for me and all shortcuts work :)

**Review by TurboGit — APPROVED** [review]
Working just fine on my side too now, thanks a lot for finding and fixing the issue!

**Pull request merged**
