### PR TITLE
gradient: make it easier to click rotate handle

### PR DESCRIPTION
**Pull request by elstoc**
rotate handle is far to small at the moment and difficult to click - increase size to make it easier

### CODE REVIEW

**Review by TurboGit — COMMENTED** [review]
Can you describe the issue? I have already fixed that by allowing a larger area around the handle and in fact the handle is only an indicator and not active at all.

**Comment by elstoc** [comment]
I have to very very accurately get my mouse close to the rotate handle to rotate. I miss it a lot.

**Comment by TurboGit** [comment]
Are you using a down sampling ? I find it strange that I cannot reproduce... Or maybe you have an HiDPI screen ?

**Comment by TurboGit** [comment]
And sorry I was wrong on one point, you're modifying as variable which corresponds to the area defining the active zone.

**Comment by elstoc** [comment]
I'm not using down sampling no

**Comment by TurboGit** [comment]
I have tested your patch and this works too on my side. I aslo have a 1080p screen. Ok, I'll merge anyway this change cannot hurt and it will keep a bit of mystery for me :)

**Pull request merged**
