### PR TITLE
presets: Make sur we check for IOP preset when called from preferences.

### LINKED ISSUE #15761: "only show" preset option not available in preferences dialog
If I create a new preset and choose "only show this preset for matching images", but I accidentally set the preset such that it never appears (e.g. I get a lens name wrong) it is impossible to remove this flag without first correcting the preset so that it is shown, or removing it entirely. This is because for some reason the dialog that appears when selecting it from preferences does not include this option:

From darkroom:
Screenshot_2023-11-28_08-02-11

From preferences:
Screenshot_2023-11-28_08-02-40

Similarly, the "reset" option is missing as well

darktable 4.5.0+1294~g749a577100 on ArchLinux

### PR DESCRIPTION
**Pull request by TurboGit**
When a preset is edited from preferences we don't know if it is an IOP or a lib module. So we now check if the given module name is an IOP and in this case we do call the routine dt_gui_presets_show_iop_edit_dialog which is defined to edit IOP presets.

Fixes #15761.

### CODE REVIEW

**Comment by TurboGit** [comment]
@elstoc : Should fix your issue, can you test? TIA.

**Comment by elstoc** [comment]
LGTM thanks

**Comment by TurboGit** [comment]
Sadly, looks like this is not a proper fix. It will make things breaks in many case as the actual module from which the preset has been created cannot be retrieved from the preferences in fact. The only way to edit properly an IOP preset is actually when called from the menu in an IOP as here we know which module & instance is to be used.

My fix bypass this and always present the default module with default param & blending... Which is not what the user want.

**Comment by elstoc** [comment]
Honestly I'm not sure why we bother having that tab in the preferences dialog at all

**Comment by TurboGit** [comment]
To rename, add a description or change the filtering based on ISO, aperture... That's still quite some possibilities. The only part you cannot change are the params and blending.

**Comment by TurboGit** [comment]
Anyway I'm closing this PR as it is wrong.

**Pull request closed without merging**
