### PR TITLE
collect: add the entry "not tagged" to tag collection

### PR DESCRIPTION
**Pull request by phweyland**
image

### CODE REVIEW

**Comment by johnny-bit** [comment]
Wow, this is cool idea!

**Comment by TurboGit** [comment]
Yep good idea to find more work to do on our collection of pictures :)

**Comment by phweyland** [comment]
@hansbull, I find the collection query not as fast as I would like (the collect seems faster I have no idea why).
If you any advice to optimize (the "not tagged" part), that would be great ! TIA

**Comment by phweyland** [comment]
> @HansBull, I find the collection query not as fast as I would like (the collect seems faster I have no idea why).
If you any advice to optimize (the "not tagged" part), that would be great ! TIA

Please do not worry about this.
I've checked the response time under sqlitestudio of :

```
SELECT imgid FROM main.tagged_images AS a
JOIN data.tags AS b ON a.tagid = b.id
AND SUBSTR(name, 1, 10) <> 'darktable|'
```

... 0.001 sec.

**Comment by muenznej** [comment]
great! thanks for the fix!

**Pull request merged**
