### PR TITLE
fix duplicate preview in darkroom

### LINKED ISSUE #4638: duplicate manager - inconsistent processing
Within the darkroom the duplicate manager allows you to click on any of the duplicate images to compare with the current edit. However, the image you get when you click on a duplicate is often not consistent with the image you'd get if you double-clicked to change image and view directly in the darkroom.

For example, I import an image and perform some edits on it. I then duplicate that image in the lighttable and do not perform any further edits (so both duplicate images - in this case v0 and v2 - are identical).

I expect that if I view version 0 in the darkroom and click on version 1 in the duplicate manager then, after some processing, the image should remain unchanged (they are identical edits).

The actual result, when the entire image is viewed, is that version 2 seems to be more 'fuzzy' than version 0:

v0 (the image being processed currently)
full_v0

v2 (viewed by single-clicking in the duplicate manager)
full_v2

If I zoom to 100% the results are better, but the image position seems to be off (the image moves up and to the left by a few pixels when I click on version 2) and sometimes the brightness can be different (though I didn't reproduce that here).

v0 (the current image)
zoom_v0

v2 (from duplicate manager)
zoom_v2

I would like to be able to perform different edits on the same picture and use this module to perform an accurate comparison but this does not currently seem to be possible as I can't rely on the processing to be the same on both. The only reliable and consistent way to do this at the moment is to load v2 in the darkroom, take a snapshot, and then go back and enable the snapshot against v0

These issues seem fairly consistent (I've reproduced on a number of versions including current master and on a number of images) so I haven't uploaded the raw or xmp but I can if needed.

I'm running on ArchLinux and the issue occurs both with and without OpenCL.

Presumably because it's getting the images from the cache, if I switch to version 2 in the darkroom and view v0 from the duplicate manager, both images look the same as they did in my original example above (i.e. v2 is fuzzy).

If I clear the cache before re-entering darktable and start off with v2 in the darkroom the above results are reproduced (i.e. v0 is fuzzy)

### PR DESCRIPTION
**Pull request by aurelienpierre**
synchronize Cairo drawing on the main darkroom window to:

1. get the same image resolution (so far, duplicate preview were too blurry for 1:1 comparison)
2. support color assessement mode
3. ensure main and duplicate preview are the same size

~NOT WORKING SO FAR (I need help):~
~When zoomed-in, the duplicate preview surface is not shifted correctly. Can't figure out where the mistake is. Faulty lines are:~
```
const float dx = -zoom_x * img_wd - (img_wd - 2. * tb) * nz / 2. + (img_wd - 2. * tb) / 2.; 
const float dy = -zoom_y * img_ht - (img_ht - 2. * tb) * nz / 2. + (img_ht - 2. * tb) / 2.;
```
~some scaling is not right.~

Fixed thanks to @AlicVB

Fixes #4638

### CODE REVIEW

**Comment by elstoc** [comment]
N.B. this will resolve #4638 if merged.

**Comment by AlicVB** [comment]
> @AlicVB do you have an idea ?

yes, buying an hidpi screen ;)

I'll have a look (at the code, not the screens) :)

**Comment by aurelienpierre** [comment]
Ready for review and merging

**Comment by elstoc** [comment]
Doesn't quite do it for me I'm afraid - the two images still look different and theres some subtle pixel-shifting going on and brightness/contrast changes. Here's an example where both images are identical duplicates of each other:

Zoomed in (current image)
1zoomed_before

Zoomed in (duplicate selected)
2zoomed_after

Zoomed out (current image)
3_fullscreen_before

Zoomed out (duplicate selected)
4_fullscreen_after

**Comment by aurelienpierre** [comment]
brightness/contrast changes come with Cairo interpolation, I'm afraid I won't be able to do anything here. What happens is the original preview as computed 1:1 by dt, while the duplicate is choosen from the closest mipmap cache size and interpolated to final size by Cairo.

Pixel shifting is hard to solve, I thought I got rid of it since I don't see it on my screen. Basically it's a matter of ensuring all sizes computations are made the same and rounded exactly the same too which, given the number of intermediate steps involved, is a PITA.

**Comment by aurelienpierre** [comment]
Also you can test various interpolation methods for Cairo by setting in darktablerc : `ui/cairo_filter=best/good/fast`

**Comment by elstoc** [comment]
Thanks @aurelienpierre. ``fast`` is certainly by far the worst. Not only does the whole image shift but bits of it seems to warp and it just seems really odd. Changing it to ``good`` or ``best`` does fix that to a large extent, though there's still the issue that the entire image shifts by a few pixels and it's still not as sharp as the normal darkroom view.

That combined with contrast and brightness differences means it won't be good for testing subtle changes between edits (I would mostly want to use this to assess differences between filmic versions). So I guess I might be back to good old snapshots for that.

**Comment by AlicVB** [comment]
about pixelshift etc : imo that will be difficult to avoid as we don't use different path in pipe with different options for the "regular" image in darkroom and for the duplicate preview.
Maybe we can change that to get exactly same outputs, but that will be quite a challenge and quite heavy for cpu !

**Comment by jenshannoschwalm** [comment]
Some thoughts, although i have never used the duplicate manager personally before, so i might be "out-of-fucus"

If we use the written mipmaps, there might be problems resulting from the situation we wrote them. 1. compresses jpeg, dynamic range, added noise, compression artefacts, all would lead to subtle differences, rescaling will make that much worse.
2. If we write mipmaps, are we sure to use a decent jpeg quality? This is taken from exports default...
3. If we write mipmaps the export does **not** use high quality mode if the image is smaller than the pipeline size.
4. pixelshift might be the result of subtle upscaling while writing the mipmap. I can't see this on the screenshots, but is this worse on a regular pattern?

ideas?
1. When preparing for duplicate comparing, would it be better to have a 16bit image to compare?
2. enforce high resolution mode for larger mipmaps >= 4 maybe?

**Comment by aurelienpierre** [comment]
@jenshannoschwalm since we are comparing output to output, both mipmap and original image are 8 bits with reduced dynamic range, so it's no issue on that regard. However, scaling and interpolation discrepancies are an issue, but the only way to fix it would be to bypass all Cairo filters with our own.

**Comment by jenshannoschwalm** [comment]
Aah, thanks for explaining output vs output.

**Comment by TurboGit** [comment]
I still have a little bit of shift (no HiDPI screen on my side) but less important. So this goes into the right directly for me. Thanks.

**Pull request merged**
