### PR TITLE
[wb_presets] take over Canon M5 wb values for Canon M6

### PR DESCRIPTION
**Pull request by MStraeten**
Since canon M5 and M6 are siblings and share the same sensor the whitebalance values can be taken over from M5 to M6

### CODE REVIEW

**Comment by johnny-bit** [comment]
They indeed share the same sensor! :+1:

**Comment by TurboGit** [comment]
Is that 100% sure that the wb presets are the same? I kind of remember the opposite in another case, no?

**Comment by johnny-bit** [comment]
Well, they have same coeffs in adobe coeffs, that means same rgb coeffs in wb modules will produce same results for them... I'd say it's safe, but I'll leave the decission up to you :)

**Comment by TurboGit** [comment]
Ok, if they have the same adobe coeffs it seems safe. Let's go for 3.4!

**Comment by MStraeten** [comment]
I checked these with my canon m6 and it seemed to be ok

**Comment by johnny-bit** [comment]
You could have pretended that you created them ;) or actually create them ;) but hey-  less work, same effect, world better!

**Comment by MStraeten** [comment]
Indeed, but i use colorcalibration now ;)

**Pull request merged**
