### PR TITLE
Better wording for the name of the fall-off slider in the vignetting module

### LINKED ISSUE #11882: Not very accurate name of vignetting module parameter
The vignetting module has a parameter called "fall-off **strength**".

The issue is as follows.

The slider is marked as a percentage. This is the percentage of the distance on the radial scale where the light drop curve will end (lowest value - 0%, highest - 200%). Therefore, at the lowest value of 0% it will be a sharp drop in light immediately to the lowest level of the vignette, without any transition. Increasing the value on the slider, on the contrary, increases the distance to the lowest level, making the transition more gradual.

Regarding the parameter name. When we use some quality or property in a parameter name, it means that as the value of this parameter increases, that quality or property will increase, and vice versa. Therefore, for "fall-off strength" the higher the value of the parameter, the greater the "strength of fall-off" should be. In other words, higher values should cause a steeper transition. In reality, the opposite is true.

Actually we have to operate not with the notion of strength / weakness (these are not the best words in this case) but with notion of how fast fall-off curve will drop from the highest to the lowest value. In other words, we are talking about steepness of that curve, or sharpness (abruptness) of the transition. And we should use a word that reflects the quality that will increase with increasing parameter values. Therefore, the best name for the parameter, in my opinion, will be "**_fall-off_ _gradualness_**" as gradualness seems to be the most appropriate antonym for steepness or abruptness. At the max value of this parameter the transition will be the most gradual. When the parameter is at 0, there is no graduallness at all, the fall-off will be sharp.

This issue is an invitation to discussion and possible suggestions for a better name from those who know English better than me.

### PR DESCRIPTION
**Pull request by victoryforce**
closes #11882

### CODE REVIEW

**Comment by TurboGit** [comment]
@elstoc : Can you comment about **gradualness**? The word exists, but seems rarely used so I'm not sure it applies here. TIA.

**Comment by victoryforce** [comment]
> I don't like the word "gradualness", or "progressiveness", which was also mentioned in the issue. Both of these words seem strange to me (even though they might be valid words) and I can't think of any other situation I've ever seen them used.

To be honest, I found the word "gradualness" in the dictionaries of synonyms and antonyms, and the word "progressiveness" in the description of this slider in dtdocs. :)
I also find these words quite rare and rather academic in style.

> Since this parameter is related to the size of a drawn element (and the first size control is called "scale"), other options might be "fall-off scale" (or "fall-off size" perhaps) or (the term used in drawn masks) "feather size".

Well, after some thought, my suggestions on the names...

The tooltip for "scale" slider is "the radii scale of vignette for start of fall-off".
The tooltip for "fall-off strength" slider is "the radii scale of vignette for end of fall-off".

These tooltips accurately describe the action of the sliders. The best names for sliders would be those that just as accurately and clearly name the sliders, but are shorter than tooltips. So it seems logical to rename "fall-off strength" to "fall-off end". This will immediately show the user that this slider controls the end of the fall-off area. Also more immediately clear will be the name "fall-off start" instead of abstract (and unclear without a tooltip) "scale". Additionally, these names will become uniform and it will be easier for the user to perceive them as controlling the same feature.

So, my suggestion:
- rename "scale" to "fall-off start"
- rename "fall-off strength" to "fall-off end"

@elstoc, @TurboGit Do you agree?

**Comment by elstoc** [comment]
> rename "scale" to "fall-off start"

> rename "fall-off strength" to "fall-off end"

Hmm I'm still not sure we're quite there yet.

> the radii scale...

I hadn't even looked at the tooltips. I thought radii was plural. There is only one radius defined by each setting isn't there? On that basis perhaps "central radius" and "fall-off radius" might work?

**Review by TurboGit — COMMENTED** [review]
Would **progressiveness** be better?

**Comment by TurboGit** [comment]
Ok, reading again all this it seems that no action is probably the best at this stage.

**Comment by TurboGit** [comment]
Let's close this at this stage, status-quo seems the best for now.

**Comment by victoryforce** [comment]
> Let's close this at this stage, status-quo seems the best for now.

@TurboGit Have you not overlooked the fact that the status quo contains an obvious bug, and therefore cannot be the best option? It's not just about a widget label that could be improved a bit. "Not very accurate" in the title of the issue (#11882) is a euphemism. To be precise, current label of the slider is _completely opposite to its action_.

Leaving such a clear and obvious bug in the program just because we couldn't agree on a better words is the worst possible solution.

I'd like to ask you to discuss what you don't like about my proposal:

> - rename "scale" to "fall-off start"
> - rename "fall-off strength" to "fall-off end"

The only thing that was said about this version was "Hmm I'm still not sure we're quite there yet" and to be honest, I didn't understand what exactly was wrong.

**Comment by TurboGit** [comment]
@victoryforce : I don't understand or I'm very tired, but the PR as it is only contains a single word change from strength to gradualness. If there is another issue then it should be part of another PR otherwise, yes I will not be able to follow everything. I'm trying my best to review and understand all PR but please keep things simple (1 PR = 1 fix or enhancement). Thanks.

**Comment by victoryforce** [comment]
> @victoryforce : I don't understand or I'm very tired, but the PR as it is only contains a single word change from strength to gradualness.

@TurboGit Absolutely true. The original PR was exactly that, but in the discussion I myself agreed that the original change was not the best and offered a better, more considered option. But I didn't see any support, so I didn't change the initial PR version. What would you advise me to do? Make a new PR with a new proposal? But if no one supports it, then this PR will also not be accepted, do I understand correctly?

**Comment by elstoc** [comment]
If the solution is still not agreed (I'm still not convinced there's a problem worth solving) this should be discussed in an issue before a solution is proposed.

**Pull request closed without merging**
