### PR TITLE
Simplify _refine_with_detail_mask for cpu

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
- some code cleanup
- debug log writes `CL` instead of `on GPU` for readability

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
Would also be safe for 4.4

**Review by TurboGit — APPROVED** [review]
Looks good!

**Comment by TurboGit** [comment]
I'd still wait for 4.6 to merge this.

**Comment by jenshannoschwalm** [comment]
Closing this for now as there is a major details mask update following

**Pull request closed without merging**
