### PR TITLE
preferences: make the changed preferences with a little tick character.

### PR DESCRIPTION
**Pull request by TurboGit**

### CODE REVIEW

**Comment by TurboGit** [comment]
@Nilvus : this is my proposal to highlight the non default prefs.

**Comment by TurboGit** [comment]
It is not dynamic... maybe we can do better with some CSS rules ?

**Comment by TurboGit** [comment]
I found previous PR and discussion #6433.

**Comment by TurboGit** [comment]
@johnny-bit : are you still looking at this ? Maybe this PR is just a good compromise for now until we have a better solution ?

**Comment by Nilvus** [comment]
I will test that ASAP.

**Comment by johnny-bit** [comment]
I hoped to have guidance from @Nilvus on what to do and do it with css... I'm no fan of changing labels if we can avoid it. It should be possible to do checkmarks in css too but IMO checkmarks look worse than bold/italic label but I have no idea for something both nice looking and easy to code.

**Comment by elstoc** [comment]
I'm also not a big fan of the bold/italic. I do like the idea of visually indicating changed prefs but I'm not sure a tick does it for me either (since some people might read other meaning into it - like "this is a good setting - well done"!). Would an asterisk be too inconspicuous?

**Comment by TurboGit** [comment]
Yes asterisk is fine to me.

**Comment by elstoc** [comment]
Could also change the 'double-click to reset' tooltip to say 'this configuration is at its default value' or something

**Comment by Nilvus** [comment]
Asterisk is not fine for me. Asterisk means (at least in french but If I'm not wrong also in english) required setting/field... So, not a good idea.

**Comment by Nilvus** [comment]
> Could also change the 'double-click to reset' tooltip to say 'this configuration is at its default value' or something

Like that but I would suggest: "double-click to reset this as it's default value".

**Comment by elstoc** [comment]
> Like that but I would suggest: "double-click to reset this as it's default value".

I'm not sure what you mean by this. I'm suggesting a tooltip for when it's already at the default value, so double-click won't do anything.

**Comment by Nilvus** [comment]
> > Like that but I would suggest: "double-click to reset this as it's default value".
> 
> I'm not sure what you mean by this. I'm suggesting a tooltip for when it's already at the default value, so double-click won't do anything.

I just understand the opposite for what you mean. So, just forget that.

**Comment by elstoc** [comment]
> Asterisk is not fine for me. Asterisk means (at least in french but If I'm not wrong also in english) required setting/field

Yes I suppose it could be interpreted that way. That's the problem with using 'standard' characters - they're almost all loaded with some other implied meaning. Other possibilities: dagger †, double-dagger ‡

**Comment by TurboGit** [comment]
I have a new version, I have used an asterisk for now, but we can decide the best character. The most important change in this version is that the character gets updated as soon as the value is changed. So we dynamically have an indication of a setting being default or not.

**Comment by elstoc** [comment]
Works for me.

**Comment by johnny-bit** [comment]
Due to family problems I can't work on my version...  but I still dislike that it's string shenenigans instead of css looking at a code. The problem mentioned by @elstoc is because the font isn't monospaced so the space padding for character doesn't work.

I thought about using additional element on the row and display on the element icon/character and show/hide that element via css class.

I like how the indicator is dynamic tho.

**Comment by elstoc** [comment]
If we have a different css class for those that are at their default value, then something along the following lines would probably work (probably needs some tweaking though):
```
#preferences_notebook label.preference_default
{  border-left: 10px solid @plugin_bg_color;  }

#preferences_notebook label.preference_non_default
{  border-left: 10px solid @bg_color; }
```
gives...
Screenshot_2020-10-24_14-21-48

**Comment by johnny-bit** [comment]
I like elstoc suggestion.

sob., 24 paź 2020, 15:23 użytkownik Chris Elston <notifications@github.com>
napisał:

**Comment by TurboGit** [comment]
Sorry didn't see the message I was working on a new UI:

The star is now on it's own column and well visible. I find this good and probably good enough for now.

image

**Comment by TurboGit** [comment]
@elstoc : Agreed I didn't like messing with the label, see new version, lot cleaner and makes the non-default well visible and can be tweaked by CSS.

**Comment by TurboGit** [comment]
The character used is still an asterisk but we can use any UTF-8 character instead.

**Comment by TurboGit** [comment]
Now seeing @elstoc proposal I still prefer my last proposal.

**Comment by elstoc** [comment]
> Now seeing @elstoc proposal I still prefer my last proposal

I agree. Perhaps a bullet character or icon would be best.

**Comment by elstoc** [comment]
Also, give the asterisk/bullet label a tooltip "this setting has been modified" so people don't raise "what does this bullet mean" queries

**Comment by TurboGit** [comment]
@elstoc  :tooltip added.

**Comment by TurboGit** [comment]
I have set a bullet instead of the asterisk, more visible.

**Comment by elstoc** [comment]
Works fine for me. Thanks @TurboGit - definitely an improvement over the bold/italic text

**Comment by TurboGit** [comment]
Let's merge at this point then!

**Pull request merged**
