### PR TITLE
show active shape combine mode in menu

### PR DESCRIPTION
**Pull request by dterrahe**
Fixes half of #14689

image

When multiple shapes are selected and they have different combine modes, instead of a tick mark to indicate the active modes, it might be more "correct" to use the _inconsistent_ indicator. But since that resembles a minus, imho it could be more confusing.

Setting a tooltip to show only when hovered over the mode icons column in the treeview is a bit of a hassle. @elstoc would you be able to suggest a tooltip that could be shown anywhere on a row without causing confusion? Then `gtk_tree_view_set_tooltip_column` could be used.

### CODE REVIEW

**Comment by elstoc** [comment]
> it might be more "correct" to use the inconsistent indicator

or perhaps grey out both the selected options and/or make it impossible to change when more than one shape is selected?

> a tooltip that could be shown anywhere on a row without causing confusion

I guess it would have to be a summary of the shape properties, which might get a bit verbose. I think the check boxes are probably enough for me.

**Comment by dterrahe** [comment]
> make it impossible to change when more than one shape is selected

Being able to change more than one shape at a time was a new feature introduced in 4.4 that I think is useful even when not same. Otherwise you'd have to carefully deselect anything that has a different mode and change them separately later.

Having multiple ticks showing should be enough warning to be careful (at least better than nothing, like now).

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

A release notes entry maybe?

**Comment by dterrahe** [comment]
Release Note:
- when multiple mask shapes are combined, in the popup menu for a shape a tick mark is shown in front of the active combine mode, which can be easier to read than the icon in front of the shape.

**Comment by TurboGit** [comment]
Thanks!

**Pull request merged**
