### PR TITLE
basics: rework links to full iops

### LINKED ISSUE #7745: basic adjustments GUI: put only one gear wheel per module
In the new basic adjustments, when putting more than one slider for a module, there are multiple "go to the full version" gear wheels.

immagine

I believe they are unnecessary and clutter the GUI for no reason. I would like to see just one, maybe next to the module name.

### PR DESCRIPTION
**Pull request by Mark-64**
Continues from #7753.

New proposal for the basics tab, with layout change and new icon for link to the full iops, trying to incorporate all suggestions received.

Managing both options for `plugins/darkroom/modulegroups_basics_sections_labels` required some work.
In the end the solution is pretty simple but it took me some time to figure out.

Here is how it looks with labels...

immagine

...and without

immagine

Alignments and spacings can be perhaps further polished in css, but I happily leave this to @Nilvus ;-)

Please make a thorough review of the code.
Closes #7745

### CODE REVIEW

**Comment by johnny-bit** [comment]
Add "fixes #7745" and It'll be cool :)

Honestly - this looks great!

**Comment by Mark-64** [comment]
Yes, and please don't merge yet, I have in mind  a small optimization in the code

**Comment by TurboGit** [comment]
@Mark-64 : after your comment about not merging, I see a commit... Does that mean that the PR is ready for review ? BTW, do not hesitate to add a message in a PR when it is the case. Thanks.

**Comment by Mark-64** [comment]
Yes it is ready

**Comment by Nilvus** [comment]
Just tested. Great work @Mark-64. This is part is much better and really great with that PR. I don't see any parts to be improved with CSS. But will check more when this will be in master.

**Comment by AlicVB** [comment]
good work. it's indeed better like that !
Thanks for the work !

**Comment by TurboGit** [comment]
Really nice ! Thanks.

**Pull request merged**
