### PR TITLE
http -> https

### PR DESCRIPTION
**Pull request by supertobi**
Changes http://www.darktable.org to https://www.darktable.org

### CODE REVIEW

**Comment by houz** [comment]
Thanks for going through these. There are some merge conflicts, could you resolve those please? I will merge then.

**Comment by supertobi** [comment]
First time I've resolved merge conflicts in github. I hope it's OK.

**Comment by go66u6ra6b8** [comment]
Carding

**Comment by go66u6ra6b8** [comment]
Ca

**Pull request merged**
