### PR TITLE
modulegroups : allow to remove from right-click too

### PR DESCRIPTION
**Pull request by AlicVB**
this enhance right-click on modulegroups tabs by allowing to add or *remove* modules.

### CODE REVIEW

**Comment by aurelienpierre** [comment]
For me, this could go in 3.4 to finish the migration from modulelist.c to modulegroups.c with no loss of usability.

**Comment by johnny-bit** [comment]
Well, It can go into 3.4.1 :) it's imo necessary.

**Comment by TurboGit** [comment]
@AlicVB : This PR needs some work to fix the conflicts. TIA.

**Comment by AlicVB** [comment]
ah ah... I was just fighting with rebase and co when you write the msg... Should be done now ;)

**Comment by TurboGit** [comment]
I don't see that the tick in front of the module name is useful. In fact you already have two sections, as soon as you click on a module in a section it is either added or removed. So anyway we don't see the tick state changing and since we already have two sections I just find this superfluous. Thoughts ?

**Comment by AlicVB** [comment]
Agree, it's not mandatory. A tooltip like "click to remove" or click to add" should be sufficient for the discoverability...

**Comment by AlicVB** [comment]
@TurboGit : done :)

**Comment by TurboGit** [comment]
Perfect now! Merged into master and queued for 3.4.1.

**Pull request closed without merging**
