### PR TITLE
filmicrgb: revert part of previous optimization (fix crash).

### PR DESCRIPTION
**Pull request by TurboGit**
Tentative fix for #7258.

### CODE REVIEW

**Comment by Mark-64** [comment]
Works for me, thank you.

**Comment by TurboGit** [comment]
@ralfbrown : you may want to have a look. TIA.

**Comment by TurboGit** [comment]
@ralfbrown : I'm not sure it is always 4. See parameters LF_Even, LF_odd, HF_RGB & HF_grey are all allocated as a multiple of ch floats. (filmicrgb.c 1169 call wavelets_detail_level).

**Comment by TurboGit** [comment]
>  The latter would be easy to check by leaving the code in wavelet_detail_level unchanged and increasing the size of the allocation for HF_grey at line 1104 in reconstruct_highlights by 4.

This is difficult for me as I cannot reproduce. But I'll prepare another patch for the OP to test. We'll see....

**Pull request closed without merging**
