### PR TITLE
dt_mm_enable_flush_zero needs to produce value in non-SSE builds

### PR DESCRIPTION
**Pull request by ralfbrown**
Fixes #13877

### CODE REVIEW

**Comment by MStraeten** [comment]
now:
```
[ 44%] Building C object bin/CMakeFiles/lib_darktable.dir/develop/format.c.o
/Users/martinstraeten/src/darktable/src/develop/blends/blendif_lab.c:273:17: fatal error: unused variable 'oldMode' [-Wunused-variable]
      const int oldMode = dt_mm_enable_flush_zero();
                ^
1 error generated.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/develop/blends/blendif_lab.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/Users/martinstraeten/src/darktable/src/develop/blends/blendif_rgb_hsl.c:319:17: fatal error: unused variable 'oldMode' [-Wunused-variable]
      const int oldMode = dt_mm_enable_flush_zero();
                ^
1 error generated.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/develop/blends/blendif_rgb_hsl.c.o] Error 1
/Users/martinstraeten/src/darktable/src/develop/blends/blendif_rgb_jzczhz.c:296:17: fatal error: unused variable 'oldMode' [-Wunused-variable]
      const int oldMode = dt_mm_enable_flush_zero();
                ^
1 error generated.
```

**Comment by ralfbrown** [comment]
Adding a void cast of the variable should tell the compiler not to complain that the variable is unused....

**Comment by MStraeten** [comment]
builds successful on M1, thanks for the effort

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by leuc** [comment]
build fails at this patch on RISC-V (rv64imafdc) at git tag release-4.4.1

```
[ 21%] Building C object bin/CMakeFiles/lib_darktable.dir/common/darktable.c.o
In file included from /home/user/darktable/src/common/darktable.c:22:
/home/user/darktable/src/is_supported_platform.h:65:9: note: ‘#pragma message: Building without SSE2.  Some functionality will be noticeably slower.’
   65 | #pragma message "Building without SSE2.  Some functionality will be noticeably slower."
      |         ^~~~~~~
In file included from /home/user/darktable/src/develop/develop.h:30,
                 from /home/user/darktable/src/develop/pixelpipe_hb.h:25,
                 from /home/user/darktable/src/develop/pixelpipe.h:115,
                 from /home/user/darktable/src/common/exif.h:23,
                 from /home/user/darktable/src/common/darktable.c:35:
/home/user/darktable/src/common/darktable.c: In function ‘dt_init’:
/home/user/darktable/src/develop/imageop.h:665:35: error: statement with no effect [-Werror=unused-value]
  665 | #define dt_mm_enable_flush_zero() 0
      |                                   ^
/home/user/darktable/src/common/darktable.c:527:3: note: in expansion of macro ‘dt_mm_enable_flush_zero’
  527 |   dt_mm_enable_flush_zero();
      |   ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors
```

**Comment by ralfbrown** [comment]
Change line 527 to read
```
(void)dt_mm_enable_flush_zero();
```

**Pull request merged**
