### PR TITLE
thumb overlays : add mixed mode

### PR DESCRIPTION
**Pull request by AlicVB**
This is an idea from @elstoc  that I forgot to implement in previous PR

it allow to have basic infos (rating, ...) always shown and extended lines on mouse hover

### CODE REVIEW

**Comment by elstoc** [comment]
Thanks @AlicVB. What i was asking for though was a mode where the stars/color labels are allowed to overlay on top of the image, so that the image itself always extends as close to the edge of the (top/bottom) borders as defined in the CSS and no area of the box is pre-allocated to the overlays.

**Comment by AlicVB** [comment]
@elstoc : not sure to understand exactly. (but in any case, I think the new mixed mode can be useful)

So, You want the "basic overlays always shown, without any reserved space, right ?
This is doable in css, by modifying the "basic on mouse hover" mode. You have to ensure that `.dt_overlays_hover` is treated as `.dt_overlays_always` for all thumbnails buttons. If don't manage to get it work, I can guide you !
You can also play with negative margins, but beware that reserved space is only proportional to thumb size for small thumbs.

**Comment by elstoc** [comment]
I want every image to look like when hovering in 'overlays on mouse hover' mode, but permanently. Perhaps another 'recipe' for when I've done my usertweaks.css PR.

**Comment by johnny-bit** [comment]
ye! that's perfect usecase for #4670 isn't it?

**Comment by elstoc** [comment]
Sounds like it, yes.

**Comment by TurboGit** [comment]
Works for me! Thanks.

**Comment by AxelG-DE** [comment]
@AlicVB 
am I the only one, who has trouble in current master, if I am in culling mode, cannot change the overlay modus?

Unfortunately I cannot make a screenshot, because, what happens:
- in culling mode (zoom=4) I try to open overlay menu clicking the star. 
- It opens and has the _overlay on mouse hover_ activated 
(in filemanager I changed already to ext. over.)
- now I try to reach ext. overlay and when I pass by the _overlay on mouse hover_, that line get 100% transparent and the menu closes

**Comment by AlicVB** [comment]
be patient, culling is under rewrite..., but I keep that point in my mind

**Comment by AxelG-DE** [comment]
o.k. I will :-)

another thing...
do I remember correct, time ago Aurélien added a grey bar to overlay, so that the stars can be seen better? Seems now this grey bar is still there, but "empty"
grafik

Also filmstrip seems buggy (see the empty frame)
grafik

**Comment by Nilvus** [comment]
> o.k. I will :-)
> 
> another thing...
> do I remember correct, time ago Aurélien added a grey bar to overlay, so that the stars can be seen better? Seems now this grey bar is still there, but "empty"

I'm working on improving CSS actually so spending some time on this PR and moving my mouse hover and testing all these new modes as I update/test new CSS changes. I don't see that. As before, I didn't use the option to have this gradient, and this option seems to not be now visible (can't remember which one and how it was named), I suggest you to check your darktablerc file. And/or test before if you still have that with a whole new fresh darktablerc file (by saving of course yours). Probably the related line adding this gradient still there or something like that. If really needed after that, creating a new issue and pinging AlicVB would probably be better than here.

> Also filmstrip seems buggy (see the empty frame)

This is not related to this PR so as my last sentence: a new separated issue would be better.

**Comment by Nilvus** [comment]
It seems there's indeed an issue about extended text on thumbnails. @AxelG-DE: could you just precise if your gradient on your last image is related to the extended text activated on preferences? Could you check that at the end of the preferences? If activated, could you uncheck that preference and restart darktable then see if this gradient is here or not? If gradient is not there, that could confirm an issue on this option. I have something like now I've just add this option on some images (not all but some with txt file and other without). @AlicVB?

**Comment by AlicVB** [comment]
@AxelG-DE : As said by @Nilvus , can you please open new issue (one for each bug) It's really easier to follow and to not forget things. Thanks

**Comment by AxelG-DE** [comment]
sorry, I didn't want to abuse the communication thread here. I was driven by the idea, keeping it lean.

Let me try with all the "additional context" from new BugReport and if keeps on reproducible, indeed I will open a new issue

**Pull request merged**
