### PR TITLE
fix crash on loading sidecar files

### LINKED ISSUE #9948: OSX: native filechooser for sidecar files causes segfaults on importing sidecars
Importing an xmp sidecar history stack --> load sidecar file results in an segfault after selecting the xmp file with osx native
 file slection dialog and opening it.
debugger output:
```
[image_cache_allocate] failed to open image 14412240 from database: no more rows available
[exif] error adding history entry for image -1
[exif]   FOREIGN KEY constraint failed
[exif] error reading history from '/Users/martinstraeten/SynologyDrive/20180624-IMG_0623_01.CR2.xmp'
libdarktable.dylib was compiled with optimization - stepping may behave oddly; variables may not be available.
Process 81336 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x200000001)
    frame #0: 0x00000001001dc090 libdarktable.dylib`dt_history_load_and_apply_on_list(filename="/Users/martinstraeten/SynologyDrive/20180624-IMG_0623_01.CR2.xmp", list=<unavailable>) at history.c:197:23 [opt]
   194 	  dt_undo_start_group(darktable.undo, DT_UNDO_LT_HISTORY);
   195 	  for(GList *l = (GList *)list; l; l = g_list_next(l))
   196 	  {
-> 197 	    const int imgid = GPOINTER_TO_INT(l->data);
   198 	    if(dt_history_load_and_apply(imgid, filename, 1)) res = 1;
   199 	  }
   200 	  dt_undo_end_group(darktable.undo);
Target 0: (darktable) stopped.
```
The error isn't reproducible with builds containing the old file chooser

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. select image in lighttable, discard history (just to be safe there's nothing that migth interfere with content from loaded xmp)
2. Click on 'load sidecar file' 
3. --> osx native filechosser opens and is used to select the xmp file
4. click open and get segfault

**Which commit introduced the error**
b35ee51ce479c7dbb1cb9ce70bda44be6cabfefb is the first bad commit
commit b35ee51ce479c7dbb1cb9ce70bda44be6cabfefb
Author: Marco Carrarini <marco.carrarini@gmail.com>
Date:   Sat Sep 4 23:13:14 2021 +0200

    native filechooser for sidecar files

 src/libs/copy_history.c | 15 +++++++--------

**Platform**
* darktable version : darktable 3.7.0+965~gb35ee51ce-dirty
* OS                : OSx

### PR DESCRIPTION
**Pull request by Mark-64**
This fixes #9948 by copying the list returned by `dt_view_get_images_to_act_on()`, like it is done in other parts of DT

### CODE REVIEW

**Review by TurboGit — COMMENTED** [review]
I don't think this is the correct change as the list is already copied where needed when passing it to signals & collection update (else part line 165).

The only explanation about this is that the imgs gets invalidated while running the dialog. Is that the case here? Hard to believe... but well we never know.

I just spotted this and act_on_any is always TRUE as we return early if imgs == NULL. We could clarify this.

**Comment by parafin** [comment]
Please read original bug report for analysis.

**Comment by Mark-64** [comment]
> I just spotted this and act_on_any is always TRUE as we return early if imgs == NULL. We could clarify this.

Correct. Let me try to fix this

**Comment by Mark-64** [comment]
with the last commit act_on_any is fixed.
For the main problem, if we eliminate the list copy in any of the two
```
      dt_collection_update_query(darktable.collection, DT_COLLECTION_CHANGE_RELOAD, DT_COLLECTION_PROP_UNDEF,
                                 g_list_copy((GList *)imgs));
      DT_DEBUG_CONTROL_SIGNAL_RAISE(darktable.signals, DT_SIGNAL_GEOTAG_CHANGED,
                                    g_list_copy((GList *)imgs), 0);
```
there is a crash.

**Comment by TurboGit** [comment]
> Please read original bug report for analysis.

Indeed, I should have started there! Thanks.

**Review by TurboGit — APPROVED** [review]
Thanks !

**Comment by MStraeten** [comment]
successfully tested on osx - thanks for the fix

**Pull request merged**
