### PR TITLE
guides: refactor overlay color settings and add contrast

### PR DESCRIPTION
**Pull request by elstoc**
Set the r,g,b colors for darkroom overlays once and store to darktable.gui for use in drawing code. This avoids constant retrieval of configuration value on draw

Also adds a new "contrast" slider, to increase the contrast between light and dark parts of dashed lines in overlays.

This probably now supersedes #11058.

### CODE REVIEW

**Comment by elstoc** [comment]
Actually, this won't work for black/white, since black/white don't use the "amt" value to scale the colors. I'll have a think about alternatives for this

**Comment by elstoc** [comment]
I had assumed that it would be possible to set the colour/alpha of both the "on" and the "off" portions of the dashed line (created with `cairo_set_dash`) using a contrast setting but it seems that we just tell cairo to draw a dashed line and it takes care of the colours. Anyone got any idea how we can override this?

**Comment by Nilvus** [comment]
> This will conflict with #11058 so I'm happy to either rebase after that is merged or incorporate those change here.

Do it as you want. If it's easier for your to incorporate my changes here, feel free to do it (just authored me).

Do you plan to add your contrast setting proposal?

**Comment by elstoc** [comment]
> Do you plan to add your contrast setting proposal?

I'm looking at it now. It's possible that the contrast setting will negate your PR, since maximum contrast + grey lines will create overlays that alternate black/white.

**Comment by elstoc** [comment]
I've added a contrast setting but it's not 100% finished. Would be nice to get some feedback before I complete it. Most of the "amt" values passed into the function (in master) are either 0.2, 0.3 (dark) or 0.7, 0.8 (light) so my plan is to make all of these 0.25 / 0.75 at the default contrast of 0.5. I've hacked this into the dt_draw_set_color_overlay function for now but if people are happy I'll tidy up later.

As I say above, I suspect this supersedes #11058.

There's a separate (existing) issue whereby the guide lines shortcuts don't work until you've activated the popup at least once, so I might try to fix that here as well.

**Comment by Nilvus** [comment]
Contrast is a great addition and much better than adding colors I agree. But, actually there's something strange: when I set grey color and move contrast, color goes to write but with a dotted line and sort of better continuous grey line when contrast is to 0 (no black!).

Grey, contrast to 0:

image

Grey, contrast to 0.5:

image

Grey, contrast to 1.0:

image

Last thing, I'm wondering if the contrast line should have a clearer name. I'm not sure which choice would be the best (and short) but contrast only could be not clear enough for some users on what it does. Maybe "contrast overlay"?

**Comment by Nilvus** [comment]
And if that PR could allow white and black as my PR propose, I'm of course totally on to cancel/close my PR. I'm happy to see overlay colors be improved, and with a better than just adding black and white colors. So thanks for your work here @elstoc.

**Comment by elstoc** [comment]
> when I set grey color and move contrast, color goes to write but with a dotted line and sort of better continuous grey line when contrast is to 0 (no black!)

The "contrast" here is the contrast between the light and dark parts of the dashed lines. Zero contrast means a continuous line. So this is as expected.

**Comment by Nilvus** [comment]
> The "contrast" here is the contrast between the light and dark parts of the dashed lines. Zero contrast means a continuous line and max contrast means the light parts are at 100% brightness and the dark parts at 0, so black/white. So this is as expected.

Ok, that's ok for me. I will test again a little more those following days by working on images.

**Comment by elstoc** [comment]
This should be ready to review now. Given that the brightness parameter basically only takes two values now, I would suggest that it is best modified by changing the alpha parameter, and I have done this for a couple of calls. It may need further tweaking for some overlays.

**Review by Nilvus — APPROVED** [review]
Last changes are better and your PR make guides overlays much better. It's also more powerful than just adding more overlays. Thanks.

**Review by TurboGit — APPROVED** [review]
Works for me, and nice clean-up BTW. Thanks.

**Pull request merged**
