### PR TITLE
po/collect header sort

### LINKED ISSUE #16018: Folder Sorting Issue in DT 4.6
### Describe the bug

Darktable 4.6 has reversed the sort order of the folders view in the collections module. Here's a screen shot of the view in 4.4:

dt44

And this is what the same thing looks like in 4.6:

dt46

### Steps to reproduce

Import folders named by year
Select "folder" view in collections module
the oldest folder will be at the top

### Expected behavior

in darktable 4.4 the newest folder was at the top

### Where did you obtain darktable from?

distro packaging

### darktable version

darktable 4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

Arch Linux x86_64, Kernel: 6.6.8-arch1-1

### Are you using OpenCL GPU in darktable?

No

### PR DESCRIPTION
**Pull request by TurboGit**
collect: Move sorting from preference to new module header tool box.
    
Fixes #16018.

### CODE REVIEW

**Comment by TurboGit** [comment]
image

**Comment by bengtfalke** [comment]
Looks good with the sorting icon.... intuitive.

**Comment by elstoc** [comment]
Looks like a nice addition to me. Thanks!

**Comment by da-phil** [comment]
Awesome, thank you!  I also thought about this feature only yesterday and started to work on something :sweat_smile:

**Comment by luxagraf** [comment]
This looks perfect, thank you so much TurboGit

**Pull request merged**
