### PR TITLE
thumbs : add tooltip for groups

### PR DESCRIPTION
**Pull request by AlicVB**
"group" icon on thumbnails show tooltip like : 

------------------------------------------
3 grouped images

**current (leader)**
IMG_005896.NEF
IMG_005478.NEF

### CODE REVIEW

**Comment by TurboGit** [comment]
Nice !

**Comment by TurboGit** [comment]
Just a minor change needed, when grouping files that are clone you get the same name into the tooltip. So to distinguish them I suppose we want to add the version of the clone. Thoughts ?

**Comment by AlicVB** [comment]
oh yes, I'll have a look

**Comment by AlicVB** [comment]
@TurboGit : done + small optimizations

Note that to avoid to complex computations and loops, I've done a very rough versionning test : if version is not null, it is shown.
Although there might be cases where there's only 1 image version but its version number is not null...

Let's think indicating version numbers in this rare cases is not too harmful :)

**Comment by TurboGit** [comment]
Works for me. Thanks.

**Pull request merged**
