### PR TITLE
Use a libheif function that will give us the true bit depth of the original pixels

### LINKED ISSUE #13161: Wrong input colour profile for HEIC images
**Describe the bug/issue**

Darktable is importing HEIC images from my phone (Samsung SM-G781B) with the wrong input profile. Images are incorretly set to linear Rec709 RGB on import, rather than sRGB. The module order is also set to v3.0 RAW.

Here's an example file (can't be uploaded to github):
https://drive.google.com/file/d/1hbCyKOiiZUb7MQMyZIIsDfuVyW9b6FAT/view?usp=sharing

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Import HEIC image
2. Select input color profile in darkroom

**Expected behavior**
Input profile should be set to sRGB

**Screenshots**

Incorrect: default linear Rec709 RGB input color profile
image

Correct: sRGB input color profile
image

**Platform**

* darktable version : 4.0.1 (flatpak)
* OS                : Linux 5.10.0-18-amd64
* Linux - Distro    : Debian 11 (bullseye)

### PR DESCRIPTION
**Pull request by victoryforce**
This PR fixes #13161.

The essence of the problem: 8-bit HEIF images without color space information are displayed incorrectly in darktable (have a faded look). This is because a linear input profile is selected for such an image, even though they, as is common for all 8-bit images without an explicit profile specification, should default to the non-linear sRGB color space.

Why does this happen? The reason is a combination of one bug and one overly generalizing assumption in the code:

- We mistakenly identify 8-bit HEIF images as HDR. This is because the libheif function `heif_image_get_bits_per_pixel_range` does not actually tell us the true bit depth of the original image data. When decoding an 8-bit image in the context of our code, this function returns a value of 10 (after reading the libheif source code I could explain why, but it would take a lot more text and ultimately isn't that important). Believing that 10 is the bit depth of the original data, we mistakenly decide it's HDR.

- In the input color profile module, we assume that all HDR images without an explicitly specified profile should be encoded in the linear space and choose the linear Rec709 color space for them. Because we mistakenly identified an 8-bit image as HDR, this leads to the wrong profile selection.

To get the actual bit depth of the original pixel values we need to use the `heif_image_handle_get_luma_bits_per_pixel` function.

I have not been able to find samples of HDR (high-bit depth) HEIF images without an explicitly specified color profile.
Therefore, it remains an open question whether such images (if anyone creates them at all) will be linear or not. But it is worth remembering that the assumption about the linearity of all high-bit depth images may be too strong an assumption, which may be better reconsidered. Perhaps it should be used only for specific image formats (EXR, RGBE), which by their nature are intended for HDR images and are therefore inherently linear.

### CODE REVIEW

**Comment by parafin** [comment]
In video nowadays 10bit non-linear output is quite common. But I suspect it usually comes with metadata about used colorspace.

BTW sRGB gamma is not the same as Rec709 gamma, though quite close. Even worse, there are a couple of versions of sRGB gamma…

**Comment by kmilos** [comment]
Good catch!

I believe this code path predates AVIF/HEIFs and was indeed meant for "true" HDR containers: EXRs, RGBEs, float TIFFs...

W.r.t. 10/12b AVIF/HEIFs, it is indeed not likely (nor sensible) they won't use a transfer curve, but IMHO they are intended for HDR content, and we should still flag it as such and create the appropriate workflow for HDR. Not sure what the fallback input profile should be though...

Btw, even w/ this correct 8b detection, there is a risk that the Exif `ColorSpace` will not be sRGB, but parsing Exif at this point is a bit of a pain I guess...

In general, is there maybe a way we can feedback to the user in all such cases: "Color profile missing in file X, assuming Y. Please check the `input color profile` module settings and adjust if needed.", where Y can be either sRGB or linear Rec709? I think currently we potentially just report it in the log...

**Comment by victoryforce** [comment]
> Good catch! Must say I'm baffled by the original/decoded difference by libheif 😖

Thinking about it, I even see some logic in their implementation. And after all, the name of the function (...get_bits_per_pixel_`range`) is not misleading. The only (unpleasant) surprise is that under certain circumstances it returns a value that is different from the original bit depth (ie, the range is extended during decoding).

So what's really annoying about libheif is the absolute lack of __quality__ documentation. Short comments before the function prototype in heif.h? Sorry, that's not documentation, that's a fail.

> I believe this code path predates AVIF/HEIF/JXLs and was indeed meant for "true" HDR containers: EXRs, RGBEs, float TIFFs...

It sure does.
(https://github.com/darktable-org/darktable/blob/master/src/iop/colorin.c#L1898, That's what you're talking about, right?)

> W.r.t. 10/12b AVIF/HEIF/JXLs, it is indeed not likely (nor sensible) they won't use a transfer curve, but IMHO they are intended for HDR content,

Well, not necessarily intended for HDR. 10+ bit depth says nothing about the dynamic range. Color bit depth itself is just about color accuracy.

> and we should still flag it as such and create the appropriate workflow for HDR.

They are correctly flagged, nothing has changed here.

> Not sure what the fallback input profile should be though...

To be honest, we are discussing a hypothetical case and it is unlikely that there will be any sane device that will produce such images.

> Btw, even w/ this correct 8b detection, there is a risk that the Exif `ColorSpace` will not be sRGB, but parsing Exif at this point is a bit of a pain I guess, and this is still a step in the right direction and should cover the vast majority of cases.

We don't need to parse it in the HEIF image loading function. This will be taken into account in the input color profile module:
https://github.com/darktable-org/darktable/blob/master/src/iop/colorin.c#L1890

> In general, is there maybe a way we can feedback to the user in all such cases: "Color profile missing in file X, assuming Y. Please check the `input color profile` module settings and adjust if needed.", where Y can be either sRGB or linear Rec709? I think currently we potentially just report it in the log...

Let's solve problems as they arise. We cannot guess all the ways in which broken or ambiguously interpreted images can be created.

**Comment by victoryforce** [comment]
Changed the comments a bit to trigger the unbroken CI to run and show the green light.

@TurboGit The fix is obvious and safe, it is clearly suitable for 4.2.1.

**Comment by victoryforce** [comment]
@TurboGit May I ping you on this? This PR is already three weeks old, but it hasn't even been marked by a milestone. Maybe it somehow got lost?

**Comment by TurboGit** [comment]
@victoryforce : Yes, good to ping me on this I indeed completely missed this PR, sorry.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
