### PR TITLE
XMP files are alway overwritten from the DB (bug #12247 fix)

### PR DESCRIPTION
**Pull request by esq4**
XMP files are alway overwritten from the DB regardless of the state of the “search for updated XMP files at startup” checkbox

### CODE REVIEW

**Comment by TurboGit** [comment]
Yes XMP are overwritten.... The fix seems to change filename to UTF-8, no clear to me given the change log what you are actually trying to solve. Can you clarify? Thanks.

**Comment by esq4** [comment]
https://redmine.darktable.org/issues/12247  :

```
**Description**
If you set the "search for updated XMP files at startup" option, Darktable 
automatically updates the XMP files from the DB. This is in the Windows.
But in Linux Darktable allows me to select an action in the dialog box.

**History**
#1 Updated by Mike Romanov over 1 year ago
It looks like darktable ignores (does not detect) the changes in xmp files, 
gets history stacks from DB and then in darkroom just overwrites xmp files.

#2 Updated by m laverdiere about 1 year ago
Here's what I see in 2.6 version for Windows: when the option to look for 
modifications to xmp files on startup is selected, it does nothing on startup, 
i.e. it reloads the data from the database and eventually overwrite the xmp, 
without any dialog box to choose what to do. On my Linux box, I see that 
dialog box where the user can choose between loading the modified xmp 
or overwrite them.
```

In other words. I am editing the same shots on  Windows or Linux computers. On Linux, the programm allows me to accept the changes at startup, while on Windows it overwrites them with outdated data  from the database without asking.

The problem turned out to be that Windows 7 uses a regional code page for the file 
system (cp1251 in my case), while Darktable uses utf-8 to write file paths in db.

**Comment by TurboGit** [comment]
Please DO NOT merge master branch into topic branches. If really needed you need to rebase.

**Comment by TurboGit** [comment]
Merged in master. Thanks.

**Pull request merged**
