### PR TITLE
Send to trash: add an option to delete all files

### PR DESCRIPTION
**Pull request by bennygui**
For this bug: http://thread.gmane.org/gmane.comp.graphics.darktable.devel/6889

### CODE REVIEW

**Comment by LebedevRI** [comment]
Adds new string, probably a feature(?) => will have to wait until after 2.1

**Comment by bennygui** [comment]
@LebedevRI I'm letting you decide what is best... but from the thread, the person who reported this said: "As a person, who had to click the button 50+ times I would prefer having 
an untranslated string :)"

Anyway... It will probably not affect many users.

**Comment by houz** [comment]
What about a checkbox "remember the choice" or "don't ask again" (or something like that) which just remembers whatever you click for that job. It would allow deleting them all, but also to just remove all of them from the collection. Or whatever someone wants.

**Comment by bennygui** [comment]
I'm not sure it's worth putting a lot of effort into: this dialog will almost never pop except if you have weird  file permissions or if trashing is disabled on the system or the filesystem.

**Comment by TurboGit** [comment]
Is that still needed? If so, can this be rebased and retested on current master? Thanks.

Otherwise let me know and I'll close this PR. Thanks.

**Comment by TurboGit** [comment]
Merged manually fixing the conflicts. Tested and working as expected. Thanks.

**Pull request merged**
