### PR TITLE
gradient: fix rotation angle

### LINKED ISSUE #7494: 3.4.0: Masking tool turns a few degrees counter clockwise when the mouse button is released
**Describe the bug**

The gradient handle in the masking tool turns a few degrees counter clockwise when the mouse button is released. So it is not possible to turn the handle precisely to its final position.

**To Reproduce**

1. Go to the exposure tool (for example, other modules work as well).
2. Select "drawn mask" button
3. Press "add gradient" button
4. Place gradient somewhere on your image
5. Select handle/dot at the end of the arrow to turn the orientation of the gradient.
6. Turn gradient and release mouse button.
7. Turn handle does not stay at the selected position but moves some degrees counter clock wise.

**Expected behavior**

The handle should not turn automatically some degrees to displace the gradient orientation

**Screenshots**

See attachment:
darktable-3 4 0-bug

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: 
 - 
 - 
Darktable Version: 3.4.0
Os: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic 
Open CL: No

**Additional context**

This error was not present in 3.2.1 and other older versions

### PR DESCRIPTION
**Pull request by elstoc**
Resolves #7494

### CODE REVIEW

**Comment by elstoc** [comment]
Looks like this was caused by a partial reversion of #4598.

**Comment by paolodepetrillo** [comment]
I had made this change to fix #7035, where the rotation goes backwards if the image is flipped either horizontally or vertically because the handedness of the coordinate system is changed. This PR does reintroduce this issue.

I'm not really sure what the general solution would be to handle all of these different cases including flips and distortions.

**Comment by elstoc** [comment]
Yeah I don't know either. I'm hoping that my PR can at least inspire someone who knows better because this behaviour (#7494) happens on every image with lens correction. #7035 is a more serious problem but #7494 is probably a more common one. I don't know what the best thing to do is.

**Comment by elstoc** [comment]
@paolodepetrillo: I borrowed some code from the gui creation code - as with all changes on this module I'm not 100% sure why it works but it appears to (unless I'm missing something). Please can you test it.

**Comment by elstoc** [comment]
I've done my best to break this with various combinations of rotate, flip, orientation and lens correction. It seems pretty stable to me.

**Comment by paolodepetrillo** [comment]
I've also tested it with combinations of flip, rotate, orientation, and lens correction, and I didn't see any problems. I think it probably makes sense to go ahead and merge this even though a more general solution might be possible in the future.

There is still some weirdness related to perspective correction and / or liquify but I'm not sure if there is any reasonable way to fix it.

The purpose of this fix is to just determine whether or not the handedness of the coordinate system has been flipped, ignoring any other distortions or rotations, and change the direction of rotation if it has.

I think this is how it works now, with this fix applied: when the user drags the handle to rotate the gradient, the angle between the starting position and ending position of the gradient line (not the perpendicular arrow) **in the preview window** is measured. If the coordinate system is flipped the angle is negated. The gradient is then rotated by that angle. The image, and the gradient UI elements, then go through the entire pipeline with whatever transformations are applied, and are drawn in the preview window. When we are only doing rotations and small symmetrical distortions like lens correction, a rotation of X degrees in the preview window corresponds to a rotation of X degrees in the transformed image, and the gradient line doesn't appear to move after being rotated. But when there is a distortion like perspective correction, the angles no longer match. This explanation is probably not very clear, I will add some screenshots with perspective correction later to show what I think is happening.

**Comment by elstoc** [comment]
Thanks @paolodepetrillo that was pretty much the explanation I had worked out. Regarding the weirdness with perspective correction and liquify I don't think we're ever going to be able to handle more extreme distortions. Some of those sorts of things are discussed in https://github.com/darktable-org/darktable/issues/3904.

**Comment by TurboGit** [comment]
This introduces a regression:

Take the integration test image.

1. Add a liquify circle on white circle (proportional scale) on the right.

image

2. Add a gradient at the center of this circle (real center not the deformed one). See result:

image

The gradient vector is completely off (not passing by the center). The arrow at the end of the vector too. Rotating the gradient move the vector also.

**Comment by elstoc** [comment]
@TurboGit Is this a regression? I see the same on master.

**Comment by TurboGit** [comment]
Indeed, not a regression. So this PR is indeed an improvement. It would be nice to fix all those issues but I agree this is quite difficult, I have already spent hours on those for different cases. So, I'll merge this as anyway it is another step in the right direction.

**Pull request merged**
