### PR TITLE
Added label "modulename" for translators

### PR DESCRIPTION
**Pull request by mpaglia0**

### CODE REVIEW

**Review by TurboGit — COMMENTED** [review]
I suppose this is needed for the Italian language to do proper translation depending on context. Right?

**Comment by mpaglia0** [comment]
Yes Pascal, it is correct.
And I will try to find time and knowledge in order to add these kind of
labels to other strings.
It is difficult to translate single words outside the general sense of a
concept.
darktable is becoming complicated and specialized: I think translators
needs all the possible help in order to deliver a first quality job.

Thanks,
Maurizio

Il giorno dom 17 lug 2022 alle ore 18:15 Pascal Obry <
***@***.***> ha scritto:

**Comment by TurboGit** [comment]
@mpaglia0 : Ok, but keep in mind that this will break the translations, so we want to do that only if we have issues on a specific language where the same word can have two different translations in two different contexts.

**Comment by mpaglia0** [comment]
OK, thank you indeed for your kind explanation.
My intention was to help but - in this case - please cancel the PR
Thanks,
Maurizio

Il giorno lun 18 lug 2022 alle ore 09:17 Pascal Obry <
***@***.***> ha scritto:

**Comment by TurboGit** [comment]
@mpaglia0 : I'm closing then. Thanks.

**Comment by mpaglia0** [comment]
Thanks.

Il giorno lun 18 lug 2022 alle ore 10:07 Pascal Obry <
***@***.***> ha scritto:

**Pull request closed without merging**
