### PR TITLE
lut3t - 3D lut module

### PR DESCRIPTION
**Pull request by phweyland**
rebased on master + cleaning

### CODE REVIEW

**Comment by phweyland** [comment]
Sorry. I'm a bit lost. I've rebased my master. Made the cleaning on top of it. It still shows up conflicts.

**Comment by TurboGit** [comment]
I suppose you need to restart this clean-up on top of master and please make sure the file lut3d.c is using UNIX line ending.

**Comment by TurboGit** [comment]
I have done the clean-up. I'm closing this. Please double check that my clean-up is correct and corresponds to this PR. I've also reformatted some code.

**Comment by phweyland** [comment]
On the "files changed" page everything looks ok.

> I have done the clean-up.

Thank you. Where do you execute that ? (On the "files changed" web page I don't see the end of line type).

> I've also reformatted some code.

I haven't detected any difference with what I've pushed ...

NB for the code you have merged (#2128) the trailing space strip was disabled but I've enabled it back before this push.

**Pull request closed without merging**
