### PR TITLE
Add Pentax K-3 II and fix lens model detection for K-3(II)

### PR DESCRIPTION
**Pull request by tomtor**
See also http://redmine.darktable.org/issues/9897

### CODE REVIEW

**Comment by pmjdebruijn** [comment]
Thanks. However it's not yet complete. We would still be missing the rather critical adobe_coeffs. They can be extract from a PEF converted to DNG, using Adobe DNG Converter. (see tools/dngmeta.sh).

**Comment by tomtor** [comment]
OK, thanks for the pointers, did that. The coeffs are identical to the S-3.
In cameras.xml I choose black and white for an ISO 800 PEF. The differences for other ISOs are minimal.

I changed make from Ricoh to Pentax, as was also done for the K-3? I think this is needed
for selecting the default "Pentax-like" for base curve.

**Comment by tomtor** [comment]
Fixed borders and naming in cameras.xml (similar to existing K-3)

**Comment by LebedevRI** [comment]
Something is wrong about this PR WRT rebasing - there shouldn't be e.g. my commits.

**Comment by pmjdebruijn** [comment]
Final nitpick, due to historical reasons, more specific names in adobe_coeff should be listed first.

So "Pentax K-3 II" should be above "Pentax K-3", other lossy matching will match Pentax K-3 first, since the matrices are identical it's not a problem in this case. And in master we don't do lossy matching anymore. However we still do to some extent in 1.6.x.

**Comment by tomtor** [comment]
Ok, fixed in:

https://github.com/darktable-org/darktable/pull/930

**Pull request closed without merging**
