### PR TITLE
CI: remove ubuntu-18.04 GNU7 jobs

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by TurboGit** [comment]
Does that mean a change for this section too :
 https://github.com/darktable-org/darktable/blob/3e4680da9fbf40d2fc1077b8cb8cca14f3244cb2/README.md?plain=1#L152

**Comment by kmilos** [comment]
Well, the [cmake config](https://github.com/darktable-org/darktable/blob/master/cmake/compiler-versions.cmake) (out of sync w/ the README apparently) requires at least GCC 7, and it seems that's the min version where C++17 features are implemented, but it still doesn't work...

**Comment by kmilos** [comment]
Ah, it might not be using the matching [libstdc++-7](https://packages.ubuntu.com/bionic/libstdc++-7-dev), but no idea how to tell it to...

**Comment by kmilos** [comment]
This (-std=c++17 presumably) now fails w/ AppleClang 12, but Clang 12 on Linux doesn't complain about the same thing... Any ideas for a workaround? @parafin @MStraeten 

```
In file included from /Users/runner/work/darktable/darktable/src/src/common/exif.cc:46:
In file included from /usr/local/include/exiv2/exiv2.hpp:26:
In file included from /usr/local/include/exiv2/datasets.hpp:33:
In file included from /usr/local/include/exiv2/metadatum.hpp:27:
/usr/local/include/exiv2/value.hpp:54:17: fatal error: no template named 'auto_ptr' in namespace 'std'; did you mean simply 'auto_ptr'?
        typedef std::auto_ptr<Value> AutoPtr;
                ^~~~~
/usr/local/include/exiv2/config.h:105:3: note: 'auto_ptr' declared here
  using auto_ptr = std::unique_ptr<T>;
  ^
1 error generated.
```

FYI, exiv2 is updated for C++17 only on the main branch, and there is no release in sight AFAIK...

**Comment by parafin** [comment]
Well, there is no auto_ptr anymore in C++, so the failure is expected. exiv2 obviously doesn’t support C++17 as released, so you can enable it in the code which uses exiv2. Why this PR at all? There is no description…

**Comment by kmilos** [comment]
GCC and Clang and Linux and Windows seem to have some fallback?

This is because latest rawspeed drop now requires C++17, so we now have a bit of a problem... @LebedevRI

**Comment by parafin** [comment]
I’m not sure what happens if parts of the code are compiled with different standard settings… Have you encountered some problems?

**Comment by kmilos** [comment]
GCC and Clang and Linux and Windows seem to have some fallback?

This PR is because the latest rawspeed drop now requires C++17 (and broke CI as we discussed [here and below](https://github.com/darktable-org/darktable/pull/12722#issuecomment-1307225300)), so we now have a bit of a problem... @LebedevRI

**Comment by parafin** [comment]
I mean what happens if you don’t touch darktable cmake code and just remove old compilers from CI?
Alternatively try to compile rawspeed integration parts with C++17 and exiv2 parts with C++14. Or are they present together in some parts?

**Comment by parafin** [comment]
I think I’ve built darktable after rawspeed update with no problems. Are sure the error didn’t just come from old compliers without C++17 support?

**Comment by kmilos** [comment]
Hm, possibly it was related to just gcc7, let's try that...

**Comment by kmilos** [comment]
Go figure! Thanks @parafin 

@TurboGit Can we get this merged soon so we have working CI again?

**Comment by TurboGit** [comment]
> @TurboGit Can we get this merged soon so we have working CI again?

Sure, just waiting for the CI to end its job, if all green it will be my next merge. Thanks for handling this!

**Pull request merged**
