### PR TITLE
po/lt composite - add support for creating composite image from lighttable

### PR DESCRIPTION
**Pull request by TurboGit**
Not an easy one, but seems be working.

@elstoc : Feel free to test.

NOTE: This PR changes the database structure, please backup before testing.

### CODE REVIEW

**Comment by elstoc** [comment]
It's not clear how this is supposed to work. If I select a single unprocessed CR2 image and click on "create composite" then "working" appears on the image, darktable becomes unresponsive and I get a bunch of messages on my terminal...

```
    55.4824 cannot get iop-order for overlay instance 1
    55.6188 cannot get iop-order for overlay instance 1
    67.0191 cannot get iop-order for overlay instance 1
    78.4674 cannot get iop-order for overlay instance 1
```

**Comment by elstoc** [comment]
Yeah it's less breaky now for that simple use case. I'm still really unsure of the expected UX though. For example I selected three images and chose the composite option. Again my PC screamed at me (fan noise), a bunch of images went white in the lighttable and displayed "working" on them without every really seeming to resolve into an image. I get the feeling it did some sort of duplication? But again, the only thing I could do to unbreak was to discard history on everything and start again.

I managed to briefly get into one of the images and saw five (I think) instances of the composite module, some of which had an image, and some of which did not.

I was envisaging this more as a two image operation, like a copy and paste. So, select one image as a source and then choose another as the target -- the source image is added to the composite module in the target image. This functionality as written seems to create additional duplicates instead (?) but I don't know how to tell which image is/should be the "master" and which images only appear within the composite module.

As I say, I'm less and less convinced that this was a good idea in the first place.

**Comment by elstoc** [comment]
> No duplicate but multiple instance of composite module

It seems to create duplicates for me and, from what I can tell it creates twice as many instances of the composite module as I'm expecting (half of which don't seem to include an image). I wonder if it's duplicating my images and then attempting to composite all of the duplicates as well.

It's also unusably slow (possibly because of the above behaviour) and makes me feel my computer is about to take off. I've ended up killing darktable a number of times because of how long it takes without seeming to do anything so what I have seen is from a very few brief forays into the darkroom view before I had to terminate the application.

**Comment by SoupyGit** [comment]
> This functionality as written seems to create additional duplicates instead (?)

I just pulled master today for first time in about a week or two, and I confirm duplicates issue. Weird thing is, I never even touched composite module, just made duplicates of existing edits in light table and lots of things went wrong, including dt becoming unresponsive and high cpu/fan. That high cpu/fan also occurs when backing up with rsync to external drive. It doesn't do that if I leave darktable out of backup. I figure it's related to this modules since mu symptoms are similar to elstoc, but if you wish I will open a new issue for it.

**Comment by SoupyGit** [comment]
Seems like latest commits have solved the problems, so shouldn't need to open an issue now. Well done.

**Pull request closed without merging**
