### PR TITLE
Better rejected thumb css

### PR DESCRIPTION
**Pull request by Nilvus**
A feedback from @aurelienpierre agreed on the fact that background around image should be darker for rejected images, as @TurboGit wanted. Maybe I was wrong, so I post something that should be a better compromise. Would be good to have some feedback from different people on this PR.

As @aurelienpierre also says, we need to thought of the fact that we can cancel a rejected image because we change our mind. To do that, it's good to be able to see image normally. That's why I remove hover effect and so allow to display image normally, only when hovering the image.

@AlicVB: your feedback is wanted too as you started the work on this.

I let this as a WIP to wait for more feedback.

### CODE REVIEW

**Comment by difrkaguilar** [comment]
As I see, in my case I changed the values to:

/* Set rejected images */
.dt_thumbnail_rating_6 #thumb_image
{
  color: rgba(0,0,0,0.25); /* only the transparency is used to fade the image drawing */
}

.dt_thumbnail_rating_6 #thumb_back
{
  background-color: shade(@thumbnail_bg_color,0.84); /* also fade the thumb background */
}

I selected those values because as rejected images I don't like to see the star ratings, then I changed those gray values to match the gray of the stars with the background of the box, the stars are not visible now. As rejected images, the stars do not have to be present in the box.

**sample image**
Screenshot-20211003115515-2132x1311

**Comment by Nilvus** [comment]
> I selected those values because as rejected images I don't like to see the star ratings, then I changed those gray values to match the gray of the stars with the background of the box, the stars are not visible now. As rejected images, the stars do not have to be present in the box.
> **This could be a FR. Hide the star rating in rejected images.**

Hmm, I don't understand that. On my side, star rating are hidden in rejected images. I also think they should be hidden. See in grey themes and same overlay what I have on my side:

image

**Comment by AlicVB** [comment]
@Nilvus : great ! I especially like the "no transparency" on mouse hover.
@difrkaguilar : tbh, at first, I've thought that the stars where removed at first sight. Here they are almost invisible ! @Nilvus : if you look well we can see them on your screenshot...

**Comment by Nilvus** [comment]
Oh shit, this let me think I forgot to check that on dark theme and they are visible.

@AlicVB: they are really hard to see but as they remains visible on dark theme, that so need a CSS update to just completely remove them visually. Will add that.

**Comment by difrkaguilar** [comment]
Hide them is the most ideal for all themes.

**Comment by Nilvus** [comment]
> Hide them is the most ideal for all themes.

And done! Last commit hide completely stars when images are rejected.

**Comment by TurboGit** [comment]
@Nilvus : Better but I would still go lot darker for the background, 0.6 is ok to me. 0.85 not visible enough to me. I would at least go to a value between 0.7 & 0.8. But I'm maybe alone. As explained on a channel, to me a rejected image has nothing important except that it is rejected and when I do not filter out them from Lt filter I just want to be sure I spot them very easily.

**Comment by Nilvus** [comment]
> @Nilvus : Better but I would still go lot darker for the background, 0.6 is ok to me. 0.85 not visible enough to me. I would at least go to a value between 0.7 & 0.8. But I'm maybe alone. As explained on a channel, to me a rejected image has nothing important except that it is rejected and when I do not filter out them from Lt filter I just want to be sure I spot them very easily.

I really don't understand why 0.6 now (you even propose 0.8 before)? With that PR, it's quite visible and could be easily distinguish with not rejected images.

**Comment by TurboGit** [comment]
> I really don't understand why 0.6 now

I'm just saying that even down to 0.6 it is fine with me. And yes, 0.8 is ok too. Maybe a compromise?

**Comment by difrkaguilar** [comment]
Finally in my personal dark theme I left the value at 0.65 to distinguish better between rejected and not.

**sample screenshot**

Screenshot-20211003175930-2282x1328

**Comment by TurboGit** [comment]
> Finally in my personal dark theme I left the value at 0.65 to distinguish better between rejected and not.

Looks clear and visually easy to distinguish! That's why I'm pushing for a better default than 0.85.

**Comment by Nilvus** [comment]
Ok, I applied 0.75 since it seems I'm alone here on background choice. Make background darker let stars became visible in grey theme because of specific setting that override transparent setting. After testing, I think default setting in darktable.css is good too in grey theme. That's why I remove lines you could see in last commit in darktable grey css file.

Adding border is to make borders more similar visually as darker theme make the illusion that border are clearer on rejected images than other ones without that border setting line I added in last commit.

Hope it would good now. I think we have had good feedback so I remove WIP label.

**Comment by Nilvus** [comment]
Some update since I forgot to update 2 comments (fix now). All good to review and merge if ok.

**Review by AlicVB — APPROVED** [review]
all good for me :)
thanks !

**Comment by TurboGit** [comment]
All good to me also now. Thanks @Nilvus !

**Review by TurboGit — APPROVED** [review]
I'm ok for merging that. I'll let Aurélien review.

**Comment by aurelienpierre** [comment]
Works here ! Thanks !

**Pull request merged**
