### PR TITLE
Updates to pt_BR

### PR DESCRIPTION
**Pull request by jpellegrini**

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by wpferguson** [comment]
This breaks compiling...
```
/home/bill/src/darktable/darktable/po/pt_BR.po:1913: number of format specifications in 'msgid' and 'msgstr' does not match
/usr/bin/msgfmt: found 1 fatal error
/home/bill/src/darktable/darktable/src/external/rawspeed/data/cameras.xml validates
4418 translated messages, 4 fuzzy translations.
make[2]: *** [po/CMakeFiles/locale_pt_BR.dir/build.make:61: share/locale/pt_BR/LC_MESSAGES/darktable.mo] Error 1
make[2]: *** Deleting file 'share/locale/pt_BR/LC_MESSAGES/darktable.mo'
make[1]: *** [CMakeFiles/Makefile2:2138: po/CMakeFiles/locale_pt_BR.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by TurboGit** [comment]
@wpferguson : Yes, saw that just after merging :( Now fixed.

**Comment by wpferguson** [comment]
Thanks :)

**Comment by jpellegrini** [comment]
Oops, sorry!

**Comment by TurboGit** [comment]
@jpellegrini : Not your fault, the main .mo file had a percent character % and it should had have a double one %%.

**Pull request merged**
