### PR TITLE
Fixing gamut checking

### LINKED ISSUE #14180: git master : gamut check : artifacts in gamut check highlights, in cyan
### Describe the bug

The darktable -> toggle gamut check button produce produce artifacts in the cyan highlight. It appears as if some out of gamut areas are repeated. This happens to me for Canon 5D mk IV CR2 raw files, but also R5 CR3 and ARW and other formats.

Screenshot from dt-bug 1

### Steps to reproduce

1. build darktable master
2. Start darktable
3. In lighttable do `add to library` of this file [_Y8A0003.CR2](https://drive.google.com/drive/folders/10r1y68OzVLrlwNA88GviGQM6EMvE9I-b?usp=share_link). (The picture is tilted 90 degrees. It has no particular meaning here). 
4. Go to darktable and execute `history reset`, `orientation rotate 90 CCW`, `color balance rgb - standard`
5. Stay in darktable and execute `toggle gamut checking`
6. A gamut warning overlay is shown in pink with gamut warning from the sun and the highlights of the cloud repeated in several places in the picture. Please refer to screenshot above. Sometimes I have to move `color balance rgb - global saturation` slider up and down, or `zoom in an out`.

Darktable release-4.2.0 works. If I do:
```
git checkout release-4.2.0
git submodule update --recursive
```
and rebuild, then the 4.2.0 version does not have any artifacts.

### Expected behavior

It is expected to get out of gamut warning for highlights, but they should not be repeated semi randomly depending on satration and zoom level.

### Logfile | Screenshot | Screencast

A screenshot is displayed under the describe the bug headline. Another example. zoomed in, where suddenly the could highlight is repeated instead.
Screenshot from dt-bug 2

### Commit

Not known at this stage. It has been like this for some time (months? weeks?). Darktable 4.2.0 works without issues

### Where did you install darktable from?

self compiled

### darktable version

darktable 4.3.0+1701~g45bd8e8997

### What OS are you using?

Linux

### What is the version of your OS?

Debian 11.6

### Describe your system?

- OS : Linux debian 5.10.0-21-amd64 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

- Linux - Distro : Debian 11.6

- Memory : 16 GB

- Graphics card : NVIDIA Corporation TU104GL [Quadro RTX 4000]

- Graphics driver : Nvidia Driver Version: 470.161.03

- OpenCL installed : Yes, OpenCL 3.0 CUDA 11.4.309

- OpenCL activated : Yes

- Xorg : X11

- Desktop : Gnome 3.38.5

- GTK+ : 3.24.24

- gcc : gcc (GCC) 12.2.0

- cflags :

- CMAKE_BUILD_TYPE : release.

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA Corporation TU104GL [Quadro RTX 4000],  Nvidia Driver Version: 470.161.03

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

- Can you reproduce with another darktable version(s)? **yes, also with older commits. this is not entirely recent, moth? weeks?**
- Can you reproduce with a RAW or Jpeg or both? **RAW-file-any-format (CR2, CR3, ARW, DNG)  and jpg***
- Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
- If the issue is with the output image, attach an XMP file if (you'll have to change the extension to .txt)
- Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
- Do you use lua scripts? **no**
        What lua scripts start automatically?
        What lua scripts were running when the bug occurred?

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Maybe not the fastest code but at least working correctly.

The problematic code was introduced in
https://github.com/darktable-org/darktable/commit/22239a23377618822e7c466d44386cd293451a2a by @ralfbrown

Fixes #14180

Comments
1. Issue could be reproduced quite easily in many images, no dependency on ppipe caching
2. might want some love for performance although no so bad for me

### CODE REVIEW

**Comment by ralfbrown** [comment]
I believe it would be much simpler to just correct my typo:
`   if(outp[4*j+0] < 0.0f || outp[4*j+1] < 0.0f || out[4*j+2] < 0.0f)`
That "out" should be "outp" and is the reason why the cyan patterns get repeated (`out` points at the start of the buffer, while `outp` points at the start of the chunk the current thread is processing).

**Comment by jenshannoschwalm** [comment]
So i close this and you do a "proper" pr? (I didn't spot the typo and just couldn't understand why your code wouldn't work correctly)  :-)

**Comment by TurboGit** [comment]
> So i close this and you do a "proper" pr? (I didn't spot the typo and just couldn't understand why your code wouldn't work correctly) :-)

Tested @ralfbrown fix proposal and working for me. I'll commit.

**Comment by ralfbrown** [comment]
> (I didn't spot the typo 
I didn't either until after you had determined which code path was misbehaving...

**Pull request closed without merging**
