### PR TITLE
build: add -ftree-vectorize in RELWITHDEBINFO mode.

### PR DESCRIPTION
**Pull request by TurboGit**
Following discussion on pixls.

### CODE REVIEW

**Comment by TurboGit** [comment]
@ralfbrown : What's your take on this?

**Comment by TurboGit** [comment]
And the `-ftree-vectorize` option is not part of `-O3` so we may want to add it there too.

**Comment by ralfbrown** [comment]
Some quick tests using darktable-bench indicate that `-ftree-vectorize` cuts the performance difference between RelWithDebInfo and Release by about 45% on my machine, but adding it to Release results in the same performance within measurement error.

**Comment by TurboGit** [comment]
@ralfbrown : Great, so let's put this in. Thanks.

**Comment by flannelhead** [comment]
Nice improvement indeed. I wonder if `-ffast-math -fno-finite-math-only` would make up for the rest of the difference.

**Pull request merged**
