### PR TITLE
help: add version string to release help url.

### PR DESCRIPTION
**Pull request by TurboGit**
For #7792.

### CODE REVIEW

**Comment by elstoc** [comment]
How would you recommend testing this?

**Comment by TurboGit** [comment]
Difficult indeed as this need a release version. On my side I have tweak the `gboolean dt_is_dev_version()` to always return FALSE.

`    return val % 2 == 0 ? FALSE : TRUE;`

to
`    return val % 2 == 0 ? FALSE : FALSE;`

**Comment by elstoc** [comment]
I tried creating a new tag (3.6.0) in my local repo. The first time I did it I got an empty URL with just `/3.6` in it and I had to delete `context_help/url` from my darktablerc file. Given that, once a setting is made to `darktablerc`, it cannot be subsequently changed in `darktableconfig.xml.in`, do we really want to use config items to store the URLs?

Once I cleared the context_help entries from darktablerc it seems to work fine.

**Comment by TurboGit** [comment]
> do we really want to use config items to store the URLs?

Yes, because in case during a release we have a big issue and want to switch to another server we can at least give a chance to users to change the base url. And in general having hard coded strings into the code is bad.

But it was possible to update darktablerc from the conf data, I may have broken something. Let me check.

**Comment by TurboGit** [comment]
> The first time I did it I got an empty URL with just `/3.6` in it and I had to delete `context_help/url` from my darktablerc file.

Does that mean that your entry in darktablerc was empty ? If so that's a bug somewhere else, no? This value should have been initialized with the default from darktableconfig.xml.in.

**Comment by elstoc** [comment]
> Does that mean that your entry in darktablerc was empty ? If so that's a bug somewhere else, no? This value should have been initialized with the default from darktableconfig.xml.in.

Yes it was present but empty (I was not using a clean darktablerc). But either way, my point remains: once the url has been set in darktablerc, how can we change it (in a future release, for example) without a user action?

**Comment by TurboGit** [comment]
> But either way, my point remains: once the url has been set in darktablerc, how can we change it (in a future release, for example) without a user action?

New version support this. Always use default version and can be overridden if user also set `false` for `context_help/use_default_url`.

**Comment by elstoc** [comment]
Yeah that makes sense. I'll test in a bit.

**Review by elstoc — APPROVED** [review]
Looks good to me

**Comment by TurboGit** [comment]
Thanks for the review @elstoc !

**Pull request merged**
