### PR TITLE
Updates to pt_BR

### PR DESCRIPTION
**Pull request by jpellegrini**

### CODE REVIEW

**Comment by Nilvus** [comment]
I suggest you to update your translation. A file was missing to translate it and has been added just an hour ago. I also see that you still have old channel mixer rgb name (now color calibration).

**Comment by Nilvus** [comment]
See that issue (fixed an hour ago): https://github.com/darktable-org/darktable/issues/6807

**Comment by jpellegrini** [comment]
> I suggest you to update your translation. A file was missing to translate it and has been added just an hour ago. I also see that you still have old channel mixer rgb name (now color calibration).

Yes, I've seen that -- just pushed an update.

**Review by TurboGit — APPROVED** [review]
Thanks !

**Pull request merged**
