### PR TITLE
show image count in filter toolbox instead of hinter

### LINKED ISSUE #10518: FR: make the selected images counter available when only showing the filter bar
Darktable's Lighttable enables you to customize the top bar display :
DIsplay all
image
Hide the "filterbar"
image
Hide all
image
Only show the "filterbar"
image

To have as much useful screen estate as possible, I use the last on : only the filter bar is displayed.
But when doing so, in lighttable, the user has no way to know how many images have been selected.
That is because the selection counter is hidden !
image
This counter is available is other setups (see top screenshots)

Could it be possible to put it in the "filterbar" so that the count of selected images is available whatever your topbar (except in "hide all" mode, of course) ?

Thanks a lot
GLLM

### PR DESCRIPTION
**Pull request by dterrahe**
fixes #10518

image
image

This allows the "hinter" to be hidden once one is comfortable enough with the mask/module controls to not need the reminder (which can also quickly be pulled up with "h").

Aside: the label widget in the filter toolbox that is used to display the selection is exposed using the same kind of proxy getter functions as the filter and sort box for consistency. I am not convinced there is much value in jumping through various levels of indirection to in the end expose very specific widgets in very specific modules, thereby completely breaking encapsulation anyway. As far as I'm concerned, just exposing the widget pointers directly, or even the module->data struct pointer and definition if that only contains 3 pointers, does not reduce any maintainability and in fact makes things more transparent. If any of the proxy interfaces are, at a later stage, more generically applicable (i.e. more than one module could use them) it could be refactored at that point. The complexity of the interface would then provide some indication of how widely used it might be, which at the moment is does not at all.

### CODE REVIEW

**Comment by TurboGit** [comment]
I like this, indeed the ability to hide the hints without loosing this information is a nice move to me.

I would even propose to rework the wording of this text as part of this PR as for small screen it will probably be a problem and it has always sounded too verbose to me.

Currently we have:
`1 image of <nn> (#num) in current collection selected`
or
`2 images of <nn> in current collection selected`

Why not just:

`1 (#num) / nn selected`
or
`2 / nn selected`

Maybe even using bold fonts for the numbers.

We always select images, we always select in current collection. If this is important it should be in the doc but having that on the UI takes spaces and is not really useful after some minutes of using dt. 

Any other proposals?

**Comment by TurboGit** [comment]
@Nilvus : You may want to give your feedback on this. TIA.

**Comment by Nilvus** [comment]
> @Nilvus : You may want to give your feedback on this. TIA.

Just let me few days to test that and put feedback

**Review by TurboGit — APPROVED** [review]
In this last version we have the best of both world (top-bar & hint messages) :) Thanks! It is ok by me.

**Comment by Nilvus** [comment]
All good to me. Just a little thing:

1) select an image and see infos shown on filter on header bar depending on what's visible
2) switch top things to show with 'shift+ctrl+t'
3) see that where image count is shown update only when clicking again on the image (or another) but not when top panels shown are changed.

I think the update should be done when switching top panels shown

**Comment by dterrahe** [comment]
This is not unlike what happens if the hinter area temporarily shows some other information (for example mask shape scroll actions) and is then cleared; it will also not "go back" to showing selection information.

This could possibly addressed, but not necessarily as part of this PR. It should only be done if the hinter is empty, because if you actually toggled the top bar because you wanted to see if the hinter showed some information, you could inadvertently overwrite what you were looking for.

**Comment by Nilvus** [comment]
@TurboGit: just in case you miss that one but could be merged regarding last comment by @dterrahe on my little "issue" (and it's a really minor one. I rarely, as I suppose others users, change top panels on lighttable view).

**Review by Nilvus — APPROVED** [review]

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
