### PR TITLE
lua tags: avoids to delete the tag while renaming it.

### LINKED ISSUE #10368: [FR] Save custom sort order of images
**Problem**
I love the feature "images order aware tags" (#5134)

My problem is, that the manually defined order gets lost quite easily:
- rename the tag with lua-script "rename-tags" (because in fact it generates a new tagid)
- reinstall darktable (because the position is only saved in library.db)

**Solution**
- migrate the existing sort-order in the lua-script "rename-tags"
- save sort order in xmp-file

**Alternative**
export + import sort order (analog to export tags to .txt)

### PR DESCRIPTION
**Pull request by phweyland**
fixes #10368 partially

To come, a change of the script contrib/rename-tags.lua to use the new darktable.tags.rename API.

### CODE REVIEW

**Comment by phweyland** [comment]
@wpferguson 
This API darktable.tags.rename is a low level routine and doesn't make any contextual check.
Outside the script contrib/rename-tags, do you see any utility for it ?
If not, I'll cancel this PR. TIA.

**Comment by wpferguson** [comment]
Here's my thoughts...

`darktable.tags.rename(tag, "new_name")` should be `darktable.tags.rename("old_tag_name", "new_tag_name")`

we need 

```
local tag = darktable.tags.find("old_tag_name")
tag.rename("new_tag_name")
```

and what should we do about images?  We could do `image.rename_tag("old_tag_name", "new_tag_name")` but do we just rename the tag for that image, i.e. delete the tag from the image, create a new one and attach it, or rename the tag for all images, or just not offer the option (my pick, because I think you can probably do more damage than good).

I can code up my suggestions and attach them to a comment.  I don't know how to do a PR to a PR :)

**Comment by phweyland** [comment]
I don't really understand your suggestions (seem contradictory to me...) 

> and what should we do about images?

Nothing, as the renamed attached tag remains attached.

**Comment by wpferguson** [comment]
I didn't word that very well.

If I have an image, `img = darktable.image.find(1)` I can do `img.attach_tag(tag)`, `img.detach_tag(tag)`, and `img.get_tags()`.  The question I was trying to ask was "Should we also have `img.rename_tag()`.  I think it might be confusing because I could see someone renaming a tag on a image and expecting it to only apply to that image.  So therefore I think we should do nothing about renaming tags from an image.  I just raised it in case someone had a different idea about it.

**Comment by wpferguson** [comment]
@phweyland please disregard my previous comments.  What you have looks fine.  Sorry for the noise.

**Comment by phweyland** [comment]
> please disregard my previous comments. What you have looks fine.

Ok, no problem.

Rephrasing my questions:
- From my standpoint the script contrib/rename-tags is buggy and the function is already fully covered by the core darktable (tagging module: `edit` and `change path`). Therefore it should be deprecated. 
- If agreed, we may not need the darktable.tags.rename API any more.
- If still needed, I wanted to highlighted that this API is a low level one. For example it doesn't check potential conflicts, which should be done by the lua script itself.

What do you think ?

**Comment by wpferguson** [comment]
> From my standpoint the script contrib/rename-tags is buggy and the function is already fully covered by the core darktable (tagging module: edit and change path). Therefore it should be deprecated.

Agreed.  I think the only reason the script existed was because of missing functionality in core.  Now that it's there I think the script can go away.  I'll add an error message with the deprecation notice and we can make it go away when 4.0 is released.

> If agreed, we may not need the darktable.tags.rename API any more.

I agree.  My muddled thoughts above were from trying to figure out how to use it, then I backtracked on my thinking.  So, I believe you are right and we don't need this function.  And, I'm sure that if we do, someone will let us know :)

I think you can close this and I'll go deprecate the rename-tags script.

**Comment by phweyland** [comment]
Ok, thanks for the answers.

**Pull request closed without merging**
