### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by mmardegan**
Add the Italian translation to the next dt 4.4.2 and correct "interpolatore" (thank you HansBull)

### CODE REVIEW

**Comment by HansBull** [comment]
Had a look at the first 10k lines in current master and found three more:
Line 1476: worflow
Line 1719: bibilioteca
Line 8672

**Comment by TurboGit** [comment]
Sorry, it is too late for 4.4.2 which will be released very very soon :)

**Comment by mmardegan** [comment]
> Had a look at the first 10k lines in current master and found three more: Line 1476: worflow Line 1719: bibilioteca Line 8672

Thank you HansBull, typo error corrected and committed here
https://github.com/mmardegan/darktableITA/commit/0b302f7fc12765c033c8f4f5fa744d83c781c1df 
If it's too late, it will be integrate on the next release.
HansBull If you have other suggestion or find other errors you are welcome.

**Comment by mmardegan** [comment]
> Sorry, it is too late for 4.4.2 which will be released very very soon :)

But... why don't you merge this pull request in the release 4.4.2 @TurboGit ??? For only two typo error... incredible... I realy don't understand.

**Comment by mmardegan** [comment]
It's been merged in the master branch! Why?

**Comment by TurboGit** [comment]
> But... why don't you merge this pull request in the release 4.4.2 @TurboGit ??? For only two typo error... incredible... I realy don't understand.

Because we won't provide a new build for 4.4.x. So what's the point? Do you build from source?

**Pull request closed without merging**
