### PR TITLE
Undo memory leak

### PR DESCRIPTION
**Pull request by edgardoh**
This fixes the undo of a deleted base instance, that was not working, and a memory leak on every undo-delete, to confirm build with asan.

The redo of a deleted instance and undo of a new one still have funny effects, but that is even more tricky than this one, so better to handle it on a new PR.

There's still a memory leak on the undo, but it doesn't seem to be related to this. I'll check that later.

### CODE REVIEW

**Comment by edgardoh** [comment]
BTW, delete several instances, undo/redo fast, dt will crash.

**Comment by edgardoh** [comment]
Just fixed the last memory leak.

**Comment by TurboGit** [comment]
Thanks fantastic work! I'll test... To tell the truth I'm a bit nervous about this one which is touching some delicate part of the code. We need to test, I'll do that right away.

**Comment by TurboGit** [comment]
Ok, tested and working fine. I did not spot issues on the code, let's merge this for a wider field testing.

**Pull request merged**
