### PR TITLE
cmake: auto disable SSE2, support woa64

### PR DESCRIPTION
**Pull request by kmilos**
Should now cover other options, not just macOS & M1 @jonastr

### CODE REVIEW

**Comment by kmilos** [comment]
But really this should be auto-detected as part of the CMakeLists.txt itself...

**Comment by kmilos** [comment]
Now w/ upstreamed patch from working demo at https://github.com/msys2/MINGW-packages/pull/12526

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by jonastr** [comment]
nice improvement @kmilos!

**Pull request merged**
