### PR TITLE
reports status

### PR DESCRIPTION
**Pull request by codingdave**
I was trying to make a duplicate from a raw that was one a NAS. The NAS was accessed via nfs and I had **no write permissions**. Thus the xmp generation failed. However, there was no feedback from dt and dt behaved as if it was successful.

This PR adds writing to the console the reason for failure of *g_fopen*, if any.

### CODE REVIEW

**Comment by codingdave** [comment]
Example feedback:

    ~/unstable/darktable_master/bin/darktable
    cannot write xmp file '/nfs/david/images/2018/DSC_0563_15.NEF.xmp': 'Permission denied'
    cannot write xmp file '/nfs/david/images/2018/DSC_0563_15.NEF.xmp': 'Permission denied'
    cannot write xmp file '/nfs/david/images/2018/DSC_0563_15.NEF.xmp': 'Permission denied'
    cannot write xmp file '/nfs/david/images/2018/DSC_0563_15.NEF.xmp': 'Permission denied'
    cannot write xmp file '/nfs/david/images/2018/DSC_0563_15.NEF.xmp': 'Permission denied'
    cannot write xmp file '/nfs/david/images/2018/DSC_0563_15.NEF.xmp': 'Permission denied'

Why there are 6 operations trying to do the same is not related to my PR ;-)

**Comment by parafin** [comment]
I think most users start dt without terminal window, so output on the console is only useful for debugging the problem, not actually notifying about its existence.

**Comment by codingdave** [comment]
> I think most users start dt without terminal window, so output on the console is only useful for debugging the problem, not actually notifying about its existence.

We don't know how users start darktable. But I agree that this is not the final solution. However it is a valuable improvement.

**Comment by aurelienpierre** [comment]
You can double the fprintf with a `dt_control_log(_("%s not found"), variable);` to display error in UI

**Comment by codingdave** [comment]
> You can double the fprintf with a `dt_control_log(_("%s not found"), variable);` to display error in UI

Thanks, I'll do. I guess this gives the toast messages.

**Review by TurboGit — APPROVED** [review]
Thanks !

**Pull request merged**
