### PR TITLE
reorder blending buttons to save 2 lines

### LINKED ISSUE #8350: [idea] make blend GUI more compact
The mention of extraneous vertical space in #8346 reminded me that I haven't yet posted this....

The panel for drawn+parametric masks is tall enough that on a 1080p screen, you can't see all of it at once without collapsing the filmstrip.  It should be possible to save height equivalent to two lines of text by rearranging things a bit.

The first line can be saved by moving the "hide shapes" and "show mask" buttons from the very bottom to the header line of the "mask refinement" section, just like the reset button for parametric masks is on the right end of the header line for that section.

The second is from removing on of the two instances of the string "drawn mask".  Two possibilities here:
1. just remove the header line.  Easier, but won't look as nice.
2. eliminate the copy in the text box for the pull-down  menu, then move the shape icons onto the same line.

Implementing the latter case would require being able to set a minimum width for the expanded pulldown which is greater than the current width of the collapsed text box.   It will also constrain just how narrow the entire side panel can be made (more than the first alternative).  If the second alternative is used, I would suggest putting the pulldown between the shape-creation and show/invert buttons to have a clear visual separation between the two groups with different functionalities.

### PR DESCRIPTION
**Pull request by dterrahe**
fixes #8350

also reordered mask shape buttons to match retouch/spots.
image

### CODE REVIEW

**Comment by TurboGit** [comment]
The order of the tools was different from retouch/spots because it was decided this way long long ago. It was felt that for retouch/spots the most common was circle whereas for blending the brush. Now I'm not opposed to more consistency, just saying to be sure this is on the table and possible raise discussion here.

**Comment by dterrahe** [comment]
> it was decided this way long long ago

I'm sorry, I didn't realise or even consider that it might have been intentional. I'm more than happy to change that back if you want?

My own 2cnts; the circle is very clearly a shape, so seeing that, I think "this is a whole bunch of shapes". The brush... could be something else (line width, whatever; the tooltip will tell me) so now I'm thinking this _could_ be a mixture of different things.

That's probably just me though; if there is _any_ chance that changing this annoys some people or breaks there long habits, I'd rather not take that chance just to please the god of consistency!

**Comment by dterrahe** [comment]
Reverted the brush button move in order to make this a single issue paper cut PR rather than tagging on something controversial.

**Comment by TurboGit** [comment]
@dterrahe : I'll merge this and please open a separate PR for the reordering of the tools. Personally I prefer uniformity, we'll see if this is ok for most devs.

**Review by TurboGit — APPROVED** [review]
Thanks !

**Comment by TurboGit** [comment]
@elstoc : Not sure there is something to do for the doc but just in case there is a screenshot or a description saying that the icons are at the bottom of the window...

**Comment by elstoc** [comment]
@TurboGit - there may be. I'll take a look. Always best to tag if you're not sure.

**Comment by dterrahe** [comment]
Also, now that this has landed, a heads-up to @Nilvus who might be able to do something about the vertical spacing between the lines and headers.

**Comment by Nilvus** [comment]
> Also, now that this has landed, a heads-up to @Nilvus who might be able to do something about the vertical spacing between the lines and headers.

I will check that

**Pull request merged**
