### PR TITLE
po/fix mask tree refresh

### PR DESCRIPTION
**Pull request by TurboGit**
A bit larger that I would have like for a bug fix, but really not way around that as the code to fix the issue was really not there.

This does:
- When clicking the arrow in a module drawn mask it select the group in the mask manager
- If you select one of the shape on the image it gets selected on the mask manager 
- If you select a group in the mask manager all shapes for this group are displayed
- Selecting one of those shapes on the image will select it in the mask manager
- Selecting a shape in top-level of the mask manager will display it on the image
- Selecting this shape and moving it on the image will select the corresponding shape in the mask manager
- If the shape is in multiple module, the one having the focus will gets selected
- If a shape is in multiple module, the tooltip now properly display them on multiple line instead of catenated

That's all for this "simple" bugfix !

### CODE REVIEW

**Comment by TurboGit** [comment]
I've targeted this for 3.8, if there is many voices against I'll move this for 4.0.

**Comment by elstoc** [comment]
You've tagged as a bug fix - does that mean this is all pre-existing functionality - if not, how much is new? I'm not sure I was aware of all this stuff and now that I am, I feel like it probably needs documenting. On that basis maybe 4.0 would be best. I'm prepared to be persuaded otherwise though

**Comment by TurboGit** [comment]
I think it was expected to be there, but the current behavior (as reported in the corresponding issue #7723) was that the tree was collapse all the time after each mask selection or move on the image.

**Comment by elstoc** [comment]
I don't know then. Feels like it should be documented, which is the only thing I really care about. We could break the string freeze on dtdocs, since we're going to give translators an extra month anyway.

**Comment by AlicVB** [comment]
> I think it was expected to be there, but the current behavior (as reported in the corresponding issue #7723) was that the tree was collapse all the time after each mask selection or move on the image.

I still have the issue here with your PR... is it just me ?

If I understand well, the main goal here is to keep the synchronization between the mask manager and the module masks interface at all times. That would be great indeed, and it has been designed to do so...

For the target milestone, I don't really care... on one hand the code changes are not so massive, once you remove all the reformatting, but on the other hand it's not a really big issue imho...

**Comment by TurboGit** [comment]
> I still have the issue here with your PR... is it just me ?

Hopefully yes :) I have spent so much time on ensuring that this was fixed... Or is that on a specific procedure that I have not tested?

**Comment by TurboGit** [comment]
@AlicVB : Of course if you have a scenario where is still does not work as expected, please share!

**Comment by AlicVB** [comment]
I've just retested with a fully clean build, ensuring all your commits are here, with a fresh darktablerc, etc... and I confirm that I can reproduce with some basic steps : 
1. take a "new" image  (history removed)
2. open in darkroom
3. unfold the mask manager and the exposure module
4. click on the pencil icon icon in exposure module to expand the drawn mask interface
5. add a brush by clicking on the brush icon in the exposure module
6. => in mask manager "grp exposure" is created, selected and expanded (with the brush form inside)
7. add a circle by clicking on the icon in the exposure module
8. => in mask manager, "grp exposure" is not selected and collapsed

**Comment by TurboGit** [comment]
Ok, indeed a scenario I did not test :( I can reproduce and not that even starting point 6 the brush should be selected. I'll fix that.

**Comment by AlicVB** [comment]
great (that you can reproduce) :)

**Comment by TurboGit** [comment]
> great (that you can reproduce) :)

Should be fixed, it is a shame that having tested many scenario you've just found one not working :) Hopefully this is now ok.

**Review by AlicVB — APPROVED** [review]
Seems good now :)

note that there's still some inconsistency but that's inherent to how mask selection works (bad) atm : selection by hover vs selection by click : it's a mess ;)

I have a WIP for @aurelienpierre project of drawn mask toolbar that will fix all that, but there's still lot of work. Hope that we'll have time to implement that for 4.0

**Comment by TurboGit** [comment]
Merged! We still have some time for field testing.

**Pull request merged**
