### PR TITLE
Update folders for filmrolls

### PR DESCRIPTION
**Pull request by vithom**
Squashed of the following:

* Add the pop-up menu for filmroll as well
* Update the collection view just before the pop-up display

### CODE REVIEW

**Comment by TurboGit** [comment]
Please use a meaningful first line in your commit. It makes more work to look at #7019 to know what is this about. It should be:

```
Fix issue with this or that and now it works.

Some more description if needed to explain why it is needed
and how it has been done.

Fixes #???? or Closes #????
```

Note that the empty lines are part of the style to separate the three sections. Also the first line should be kept short as it is the "subject" of the commit and what is used for git format-patch and the PR title here for example. TIA.

**Comment by johnny-bit** [comment]
@TurboGit - This is cool little feature that has usability benefits and adds no new strings - can this be in 3.4 (or if not - 3.4.1?)

**Comment by TurboGit** [comment]
Can't be for 3.4 we are 4 days before full freeze so no new feature now. But 3.4.1 for sure.

**Comment by TurboGit** [comment]
When removing a filmroll with the new context menu I get:

```
(darktable:254055): GLib-GObject-WARNING **: 16:38:20.785: invalid cast from 'GtkListStore' to 'GtkTreeStore'

(darktable:254055): Gtk-CRITICAL **: 16:38:20.785: gtk_tree_store_remove: assertion 'GTK_IS_TREE_STORE (tree_store)' failed
```
This is reusing the contextual menu from folders and I suppose both are using different structures.

**Review by TurboGit — CHANGES_REQUESTED** [review]
Need fixing the remove on filmrolls.

**Comment by vithom** [comment]
> Need fixing the remove on filmrolls.

Warning and CRITICAL outputs are fixed.

**Review by TurboGit — APPROVED** [review]
Good ! Merging to master, queued for 3.4.1. Thanks.

**Comment by cjelgin** [comment]
@elstoc I can write up some documentation for this and submit a PR on dtdocs

**Comment by elstoc** [comment]
ok cool thanks @cjelgin

**Pull request merged**
