### PR TITLE
thumbtable: change how file manager row is calculated

### LINKED ISSUE #5871: Lighttable thumbs disappear when last thumb selected and reentered from darkroom
**Describe the bug**
All thumbs disappear in lighttable when reentering from darkroom. It only happens when the very last thumbnail is selected in a collection. If any other thumb is selected, expected behavior results. If I use the timeline selector in the bottom pane, I can make a selection that make thumbs appear again.

**To Reproduce**
1. Go to a collection and select the last thumb and enter darkroom
2. Hit "l" to return to lighttable.
3. All thumbnails have disappeared and the widget is no longer scrollable by the mousewheel. Grabbing the scrollbar with the mouse reveals an empty lighttable.

**Expected behavior**
I expect the thumbs to still be there when returning to lighttable.

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0+13~ga4325917f
 - OS: archlinux
 - OpenCL: Intel Skylake

### PR DESCRIPTION
**Pull request by elstoc**
Resolves #5871

### CODE REVIEW

**Comment by elstoc** [comment]
Sorry guys. Second try at this. I've tried as many variations of test as I could think of and I think this is more robust. Please test lots!!

**Comment by groutr** [comment]
@elstoc Did some moderate testing. The original issue that I reported appears to be fixed. However, I did notice an odd behavior with this test case:
1. In file manager, set number of thumbs per row to 1
2. scroll to very last thumb
3. scroll up (I'm using the arrow keys). The scroll bar doesn't begin to move until I've scrolled beyond the second to last thumb.

**Comment by groutr** [comment]
Another test case (though perhaps unrelated to the changes in this PR):
1. Switch to zoomable light table view.
2. Zoom out all the way.
3. Select a thumb, enter darkroom, and press "l"
4. Observe that all thumbs before the selected thumb disappear until I move the view.

**Comment by elstoc** [comment]
Thanks @groutr. I can also reproduce this latest issue in https://github.com/darktable-org/darktable/commit/10be7dc47211f570a74e33e4fdc51eb5ca90c4cf (i.e. prior to my PRs) so it sounds like a separate issue. Please can you raise a new bug report for this.

**Comment by TurboGit** [comment]
@AlicVB : we you have time, can you give me your OK on this one? Thanks.

**Review by AlicVB — APPROVED** [review]
good catch : offset number start at 1 and not 0 due to how it's store in db...

**Comment by TurboGit** [comment]
Thanks !

**Comment by ptilopteri** [comment]
position of the "zoomable lighttable" is the mouse pointer.  If one rolls the scroll wheel to determine number of images displayed, the image strip moves off the mouse pointer location and can disappear and not be found again.

**Pull request merged**
