### PR TITLE
pref : remove unused "show text sidecar"

### PR DESCRIPTION
**Pull request by AlicVB**
as pointed by @Nilvus in #7050

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Good !

**Comment by wpferguson** [comment]
This actually goes with the lua script official/generate_image_txt.lua.  If we are doing away with the option to display it, then I guess we can do away with the script that generates the text to display.  

I don't know if anyone uses this.  I think I'll hold onto the script for awhile and see if this raises enough of a ruckus that it needs to be reverted.  If not, then I'll remove the script in a few months.

**Comment by AlicVB** [comment]
this feature has not disappear in fact, but is replaced by the use of $(SIDECAR_TXT) in overlay content.

**Comment by wpferguson** [comment]
@AlicVB thanks.  I'll undeprecate the script. :)

**Pull request merged**
