### PR TITLE
export iptc: clean up the original ones when necessary

### LINKED ISSUE #10483: Existing IPTC (string-r) fields in original image duplicated on export
**Describe the bug/issue**
When imported image already contains IPTC(IIM) fields those are duplicated on export. This only happens with tags that have type `String-R`. 

**To Reproduce**
1. Import image containing IPTC(IIM) metadata eg. ([https://iptc.org/std/photometadata/examples/IPTC-PhotometadataRef-Std2021.1.jpg](https://iptc.org/std/photometadata/examples/IPTC-PhotometadataRef-Std2021.1.jpg))
2. In metadata export options add formula that adds the same values eg. (Tag: `Iptc.Application2.Keywords` Formula:`$(TAGS)`)
3. Export image
4. Inspect exported image metadata (exiftool, exiv2)

**Expected behavior**
Tags in original image are not present in exported image if changed in darktable.

**Platform**
* darktable version : 3.7.0+1548~g27ab43af5
* OS                : macOS 10.14.6
* exiv2            : 0.27.5

**Additional context**
After following change export seems to work as expected.

```
diff --git a/src/common/exif.cc b/src/common/exif.cc
index 66d4fe286..78fcd195f 100644
--- a/src/common/exif.cc
+++ b/src/common/exif.cc
@@ -4017,6 +4017,22 @@ int dt_exif_xmp_attach_export(const int imgid, const char *filename, void *metad
                   // FIXME if an element of the list contains a ", " it is not correctly expeorted
                   Exiv2::IptcKey key(tagname);
                   Exiv2::Iptcdatum id(key);
+                  Exiv2::IptcData::iterator iptcPos;
+
+                  // remove existing values so they are not added twice
+                  iptcData.sortByKey();
+                  if((iptcPos = iptcData.findKey(key)) != iptcData.end())
+                  {
+                    while(iptcPos != iptcData.end())
+                    {
+                      std::string keyName = iptcPos->key();
+                      const char *ckey = keyName.c_str();
+                      size_t len = keyName.size();
+                      if(!(g_str_has_prefix(ckey, key.key().c_str()) && (ckey[len] == '[' || ckey[len] == '\0'))) break;
+                      iptcPos = iptcData.erase(iptcPos);
+                    }
+                  }
+
                   gchar **values = g_strsplit(result, ", ", 0);
                   if(values)
                   {
```

After this change it is not possible to add values to existing keys unless the key is also available on import. I think that not having unexpected tags is nicer behaviour but some people might be relying on the ability to add values to otherwise unavailable tags.

Ideally it should be possible to map exiv2 tags to darktable metadata also on import. Similar functionality as with export. That would allow darktable to be used more flexibly as a part of metadata workflows.

### PR DESCRIPTION
**Pull request by phweyland**
fixes #10483

### CODE REVIEW

**Comment by lhietal** [comment]
There is something weird happening when defining formulas for IPTC fields. It seems some random other values are also removed from exported image. When no formuls are defined all original values are copied to exported image. I will test more tomorrow.

**Comment by phweyland** [comment]
You are correct. All iptc after keywords inclusive are deleted. I'll try to understand why.

**Comment by phweyland** [comment]
Better this way indeed ! Thanks for testing !

**Review by lhietal — APPROVED** [review]
Thank you for working on this. Now it is possible to control IPTC metadata.

Syncronisation of IPTC values with Exif and XMP by default could be done later. Similar to how some XMP and Exif keys are already getting same values in overlapping keys. There has been some efforts to standardise this. [Exiftool implementation](https://exiftool.org/TagNames/MWG.html)

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
