### PR TITLE
Highpass denoise

### PR DESCRIPTION
**Pull request by edgardoh**
Feature #10821
Added the equalizer as a denoise option to the highpass module.
This allows to denoise the highpass, so noise is not sharpened
on noisy images. Also can sharpen the highpass, since the denoise
soften it.
I copied the source code from atrous.c to highpass.c, resulting
on duplicated code, which is not good. A better way would be to
reuse the existing code, but I don't want to modify the existing
atrous.c without some pointers from someone with more experience
on DT than myself. And of course if there's a better way to reuse the code
i'm happy to hear about it.

### CODE REVIEW

**Comment by LebedevRI** [comment]
1. you should have talked to us in #darktable first :)
2. it looks strange. there should be no need to merge those 2 iops into 1.
I'm pretty sure that you can do just that in Equalizer already...

**Comment by edgardoh** [comment]
The equalizer works very well and does a very good job as a denoiser, but the results are a bit different  depending on the image.
Of course, as I say already, the code is no good, and maybe is not worth the effort to rework it for a small difference on a particular type of pictures.
I already have it locally, so I'm going to keep testing it, if I find a considerable difference then I'll come back.

**Comment by edgardoh** [comment]
You were right, there is no point in this, there are better ways to do it.

How do I get in touch the next time? IRC is not an option for me and I have subcribed to darktable-dev+subscribe@lists.darktable.org but haven't received any mails yet, seems that the list is inactive (I have readed that there should be +30 mails/day)

**Comment by rwh86** [comment]
@edgardoh For contacting the developers, the IRC channel is definitely the best, but the darktable-dev mailing list is still in use and most of the devs are subscribed to it.

The mailing list that you're thinking of that has 30+ mails per day is probably the user list, see: https://github.com/darktable-org/darktable/blob/master/README.md#mailing-lists

**Comment by edgardoh** [comment]
I was already subscribed to the users list, receiving mails on a daily basis. The dev list I'm talking about is described here: http://www.darktable.org/contact/#mailinglists as having a lot of movement (is the same list as in the link you provide)

Maybe is just this time of the year, I'll wait and see, and also try to reach the IRC.

**Comment by LebedevRI** [comment]
@edgardoh last mail in darktable-dev was on Jan 4 2016.
While IRC is the best option, darktable-dev will do too :)

But 30+ mails per day is definitely not darktable-dev, but darktable-users.

(IIRC What would be cool and is more or less meaningful is frequency-based blend mode, maybe some day. but it will be slow...)

I'll close it then...

**Pull request closed without merging**
