### PR TITLE
improve stale messages and stale exemptions

### PR DESCRIPTION
**Pull request by johnny-bit**
The change should allow prs/issues that got commented on to remove "no activity" label and generally be nicer overall.

### CODE REVIEW

**Comment by elstoc** [comment]
Could you also exempt the no activity labels so that it's only added once?

**Comment by johnny-bit** [comment]
Has it ever added no-activity label more than once if the label is there? I know it adds the label and comment when the label is not present.

**Comment by Nilvus** [comment]
I would also be to increase no-activity to 60 days and close more quickly if no more activity. 365 days is quite long. I would suggest something like 180 days.

**Comment by elstoc** [comment]
> Has it ever added no-activity label more than once if the label is there?

Yeah you're right, #3434 had it added once and didn't update it again subsequently. We get the repeated pings because you keep removing the label :).

> 365 days is quite long

It's long for bug fixes - after 365 days a bug at least needs to be reproduced on the latest version. But for enhancement requests, they can sit there until a developer decides to code them, and 365 days doesn't seem unreasonable for that.  I'm fairly sure I've coded enhancement requests older than 180 days.

**Comment by Nilvus** [comment]
> It's long for bug fixes - after 365 days a bug at least needs to be reproduced on the latest version. But for enhancement requests, they can sit there until a developer decides to code them, and 365 days doesn't seem unreasonable for that. I'm fairly sure I've coded enhancement requests older than 180 days.

Indeed, you're right.

**Comment by johnny-bit** [comment]
TBH -  #9817 was on request that was older than 365 days(#4234) :) but got motivated via post in pixls.us :P

OK, Increasing stale marker to 60 days...

**Review by TurboGit — APPROVED** [review]
Ok !

**Pull request merged**
