### PR TITLE
Blending tabs icons: enable hover effect

### PR DESCRIPTION
**Pull request by Mark-64**
This PR will enable mouse hover effect for three of the icons in blending tabs:

- parametric
- drawn and parametric
- raster

Example
Screenshot from 2020-06-21 08-07-25
Screenshot from 2020-06-21 08-07-26

### CODE REVIEW

**Comment by Mark-64** [comment]
converted to draft as I would like to handle the `CPF_ACTIVE` state too

**Comment by Nilvus** [comment]
Not sure to understand the purpose of your PR as hover effect is already enable and works great.

**Comment by johnny-bit** [comment]
@Nilvus - i think the difference is changing gradient colours on icon to invert gradient, so that icon "pops" more :)

eg: currently gradient for parametric goes from dark to white with white markers and on hover icon is still from dark to white with white markers. as seen on example this changes icon to on hover be from light to dark with dark markers.

**Comment by Nilvus** [comment]
> @Nilvus - i think the difference is changing gradient colours on icon to invert gradient, so that icon "pops" more :)

Maybe for parametric mask, that's could be better. Will test that so, as I'm not convinced actually.

**Comment by Nilvus** [comment]
Tested and finally all good. Parametric and drawn parametric is good (PR title is not suitable but content needed). Thanks.

**Comment by Mark-64** [comment]
Sorry if it wasn't clear, the purpose is for the cairo drawing to respond to change of state (prelight and now also active), like all the other icons (almost). Before the color was hardcoded for these three icons.

Screenshot from 2020-06-21 13-47-11

**Comment by TurboGit** [comment]
Thanks !

**Comment by johnny-bit** [comment]
Hey @Mark-64 - plz make drawn/drawn+parametric "pen" icon pretty, like in https://github.com/darktable-org/darktable/pull/5314#issuecomment-640103642 (not the same :)), I'll send beer :wink:

**Comment by Mark-64** [comment]
You mean a brush like this ?
image

**Comment by elstoc** [comment]
Should be the other way round though surely, the drawn/parametric masks icon should be a pen and the brush icon (in the shapes selection) should be a brush.

**Comment by johnny-bit** [comment]
Exactly what @elstoc said :) drawn mask -> pen/pencil, brush in shapes -> brush :)

**Comment by Mark-64** [comment]
I see.
I will try to make it tomorrow

**Pull request merged**
