### PR TITLE
A "final crop" module suggestion (stripped down clipping)

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
As many of us would like to have a image cropping at the end of the pipeline this is a WIP suggestion. (#8702 and more)

It's just the clipping modules having stripped off all sorts of stuff that might lead to interpolation,
**only** the cropping functions are left.

There are some parts left over from keystone correction and rotation that should be fixed but at least
this seems to be a "working suggestion" and i think this might be more appropriate than allowing multiple
instances of the clipping module.

Atm i am stuck here, if others agree this would be feasable i would like either
- suggestions or
- someone else stepping in

TODO:
- modify_roi_in & out must be improved / simpler
- i think we don't need distort_transform / backtransform here ???
- k_h and k_v are not necessary after proper ROI modify functions.

### CODE REVIEW

**Comment by AlicVB** [comment]
I quite like this approach ! indeed it's better than c&r duplication !

I've not tested yet, but some remarks/suggestions : 
- all this should be kept very simple and performant (this shouldn't be hard, considering we don't have any computation to do)
- only the gui stuff may be more complex with all the things we may draw on screen
- at some point we may want to add an option to hide everything about crop features in c&r (that would simplify the gui a lot)


>     * modify_roi_in & out must be improved / simpler

not sure why it's so "complex" currently.... maybe have a look at borders code as an example (this is basically the same operation )
At first sight, I would say : 
1. compute the right/left/top/bottom crop size in pixels (if not already done during gui stuff)
2. change in/out sizes accordingly



>     * i think we don't need distort_transform / backtransform here

yes we do, but it's just some translation based on the left & &top cropping (again, see borders as an example)



>     * k_h and k_v are not necessary after proper ROI modify functions.

I don't get why they are here at all in fact... Are we speaking of keystone datas ???

If you need help or prefer to do more technical things, don't hesitate to ask ;)

**Comment by AlicVB** [comment]
I even wonder if we shouldn't go further and add some proxy here to allow other modules to change cropping for ex. if autocrop set in c&r, do it in this module. Same for perspective...

tbh (but don't repeat it too loud) I'm still dreaming of complete rewrite/replacement of c&r... dropping crop from there would be a first step ;)

**Comment by elstoc** [comment]
First of all thanks very much for working on this.

> I quite like this approach ! indeed it's better than c&r duplication !

I completely agree. I raised C&R duplication because I don't have sufficient knowledge (yet) to create my own module and it didn't look like anyone was going to start working on it, so it's great that you've decided to look at it.

I think we need to think about the intended end-game here (see #6736), but this is definitely a good first step. Long-term we should get rid of crop&rotate and perhaps it might be worth renaming that module (crop/rotate/keystone or something) and simplifying the name of this one to "crop". 

Eventually, IMO, the remaining functionality of the old module should be moved into other modules (I think perspective correction is a reasonable place to hold both keystone and rotation, since they are all related) and I think flip is the only thing that's left.

Some sort of global shortcut to click&drag for rotation would be good as well, but flip needs to go somewhere.

Anyway I digress - stripping out the extraneous features from this module will definitely make it easier to maintain and improve later and I'm all for it.

We should think about pipe position as well here. Currently it's very late in the pipeline - is there reasoning to this position? Are there modules before it that would benefit from having the full image available. Obviously we need some balance of performance and utility here.

**Comment by jenshannoschwalm** [comment]
I confess i feel really unsafe on this area of code as you see. (i thought because of the late position in pipeline we wouldn't need the transforms and backtransforms ...)
 
> I don't get why they are here at all in fact... Are we speaking of keystone datas ???

Yes, have removed them ... 

> If you need help or prefer to do more technical things, don't hesitate to ask ;)

Hhm, is this an offer to step in and continue work on this? If yes, i would really appreciate that! This pr was more like "what can I do on this subject on two rainy days?" and at least much of the boring stripping-off stuff has been done :-)

(And indeed i am currently more into "technical stuff", working on porting either IGV or LMMSE as proper high ISO demosaicers)

**Comment by AlicVB** [comment]
@jenshannoschwalm : yes, I can step in if you want...
I'm currently trying to make a wider proposal, but this PR will definitively be part of it !

**Comment by jenshannoschwalm** [comment]
> yes, I can step in if you want...

GREAT! I leave this pr open for a while so other might add ideas?

**Comment by AlicVB** [comment]
@jenshannoschwalm : ok, I'll take care and continue the work on top of your first commits :) though I'm not sure what will happen to your commits if you close your local branch...

As said, I've tried to do a wider proposal in #8834 (that said, this one will be needed anyway, imho)

**Comment by AlicVB** [comment]
@jenshannoschwalm : I've done it in #8838 (I didn't manage to push it here, but I've manage to reuse your commits)

**Comment by elstoc** [comment]
Should we close this one then?

**Comment by AlicVB** [comment]
@elstoc : yes, except if that void @jenshannoschwalm commits (I don't think so, but...)

**Comment by elstoc** [comment]
The commits will still remain both on @jenshannoschwalm's branch and on yours, so they shouldn't be lost.

**Comment by jenshannoschwalm** [comment]
ok

**Pull request closed without merging**
