### PR TITLE
chromatic aberration correction

### LINKED ISSUE #6965: add chromatic aberrations correction before input color profile compatible with xtrans sensors
**Describe the bug**
the rendition of fujifilm RAF files is very problematic sometimes. Especially with foliage images or high contrast areas.
There are artifacts in hight contrast zones and a "smeared" rendition of foliage in trees.
I noticed that the demosaic method needs to be perfectioned but maybe the solution could be a dedicated input color profiles for fujifilm cameras (I have an X-T3). At the moment the best fuji RAF rendition by a third party editor is by Capture One.
I tried changing the input color profile from "enhanced color matrix" to "linear prophoto RGB", and the results are that the colour rendition is wrong but the artifacts are nearly totally gone, making the image very very similar to the capture one version (from an "artifact" point of view at least). The smeared colors I suppose that would benefit only from a better demosaic.
Anyway this way and with a lot of color tweak through some modules, the results are very similar to Capture One.
Looking at the darktable's supported camera list, the custom color matrix for fujifilm cameras aren't available.
so I think we need:
-custom matrix for fuji
-trying to improve demosaic method

I'm no developer at all but If I could help, I would be happy to. I own a Fuji X-T3 if you need some kind of sample RAF file.

**Expected behavior**
No artifacts or smeared colours in fujifilm RAF files processing.

**Screenshots**
On the left the enhanced color matrix, on the right the linear prophoto RGB. I added only lens correction and defringe to make the differences more clear.
immagine

**Platform (please complete the following information):**
3.2.1 on every OS

### PR DESCRIPTION
**Pull request by rawfiner**
Fixes #6965

## Why another chromatic aberration correction module
Chromatic aberration can currently be corrected using several ways in darktable:
- lens correction module (cannot correct all chromatic aberrations)
- chromatic aberration module (it is too early in pipeline, due to that lens correction may add new aberration instead of correcting the existing one. Also, it does not work for xtrans sensors)
- defringe (it is too late in pipeline: strong blue CA give black edges due to colorin, and gives color halos around edges)

## Main characteristics
This PR adds a new module (after lens correction and before colorin in pipeline) to correct chromatic aberration.
It works on any kind of chromatic aberration whatever the physical cause (unaligned channels, some channels out of focus, ...).
It gives way lower color halos than defringe.
It is also quite fast, execution time is independent from the radius (relies on gaussian blur, execution time is approximately 5x the execution time of a gaussian blur with 4 channels, as the algorithm uses 5 gaussian blurs).

## The algorithm
The algorithm is inspired by adaptive manifolds: https://www.inf.ufrgs.br/~eslgastal/AdaptiveManifolds/

The main idea is to locally find a function to approximate the channel to correct from the guide channel.
Let's say our guide channel is the green channel.
We could use a very simple function based on the ratio of local averages:
`R = local_average_R * G / local_average_G`
This works quite well but produces color halos.

We use adaptive manifolds to make the function more complex, while still keeping its formula very simple (we don't want overfitting, or we would not correct anything).
We construct 2 local averages per channels, one average of the pixels that are higher of the local average, and one average of the pixels that are lower than the local average.
See in this graph, the green line is the average of dots that are higher than average, and the red line is the average of dots that are lower than average:

manifolds

We compute the manifolds based only on the guide average, this way we split the pixels in a consistent way across channels.

Then, we compute the ratio of the higher manifolds and lower manifolds, and approximate the result based on the distance of the input pixel of the guide channel to the 2 manifolds.

It is basically a refinement of the ratio of local averages that can handle edges.

## Some results
original image (lens correction is powerless for the CA of this image):
Capture d’écran du 2021-01-02 17-51-15

defringe (CA are removed but halos are very visible with the saturated blue sky):
Capture d’écran du 2021-01-02 17-52-10

this PR (only some small artefacts in the sky close to the bird beak and the yellow area, due to the fact that our function is too sparse to accurately model this area that has 3 very different colors in a small area)
Capture d’écran du 2021-01-02 17-51-19

## TODO
rebase on master, code cleanup, git cleanup...

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
Shouldn't any CA correction be done on raw data to avoid demosaicer errors?

**Comment by rawfiner** [comment]
> Shouldn't any CA correction be done on raw data to avoid demosaicer errors?

In my opinion this would give marginally better image quality. Ideally, denoising should also happen before demosaic for the same reason. In darktable though, it is hard because modules before demosaic have to be fast enough to compute darkroom preview on full size image in less than 1s. Also, handling the color filter array makes the code more complex. For instance the current cacorrect that works before demosaic does itself a partial demosaic (on the green channel) to compute the correction. Finally, as lens correction corrects chromatic aberrations based on a profile, I wanted to have the module later in the pipeline to avoid troubles with that.

Furthermore, as far as I know, most demosaic algorithm interpolate green channel without taking into account the others. Then, if we use green channel as a guide for chromatic aberration correction with this module, we should not get almost none errors due to demosaic, as the algorithm will rewrite red and blue data as a function of the green data. If using other channels, it may be different but I never noticed particular artefact that I thought would be due to demosaic, and not to the principle of the algorithm itself.

I hope it makes things clearer :-)

**Comment by jenshannoschwalm** [comment]
> I hope it makes things clearer :-)

I does :-)

**Comment by rawfiner** [comment]
I added some performance optimisations, very similar to the ones made for EIGF:
I use a downscaled image to compute the gaussian blurs (here the manifolds), that I upscale before computing the correction for each pixel.

With this, I get a 5x speedup, now processing 20Mpx in 0.8s on an i7-6700 CPU @ 3.40GHz

**Comment by muenznej** [comment]
thats great news! how likely is this to be merged into master anytime soon? 
I d love to use and test it with my vintage lenses that go from excellent to crap CA handling :)

**Comment by rawfiner** [comment]
I still have to improve the behavior of the algorithm. It can give artefacts in some cases, and I would like to reduce that. I can't really say when it will be ready, I have some ideas but we'll have to see if they work in practice!

**Comment by jakubfi** [comment]
I was testing the module for the last few days and I'm here to report: I've noticed that it produces strong artifacts on contrasting edges on zoomed out images when color smoothing is enabled in demosaic module. With color smoothing disabled artifacts are much less noticable, but still present. Other than that, I'm really impressed with how it deals with all kinds of chromatic aberrations, even those nastiest ones.

**Comment by rawfiner** [comment]
Thanks for testing! Yes I am aware there are artifacts sometimes with current algorithms. They usually happen for edges where the guide channel has almost no edge while other channels have strong edge. Changing the guide channel helps, but sometimes result in artifacts elsewhere in the image...
I am working on fixing this :-)

**Comment by rawfiner** [comment]
I have pushed a major update.

One new slider has appeared, a strength slider.
It can be used to reduce overshooting, edge bleeding, etc.

Steps remaining: checking if some parts of code needs some more cleanup, and git cleanup :-D

Example:
In this picture which is very complicated due to the presence of colorful flowers:
Capture d’écran du 2021-04-29 22-54-56
Capture d’écran du 2021-04-29 22-55-46

with force to 4 (see flowers colors are washed out):
Capture d’écran du 2021-04-29 22-55-01
Capture d’écran du 2021-04-29 22-55-51

with force to 0.7, area that are likely to suffer from overshooting are less corrected:
Capture d’écran du 2021-04-29 22-54-58
Capture d’écran du 2021-04-29 22-55-55

**Comment by rawfiner** [comment]
Ready for review :-) (@TurboGit  or @aurelienpierre)

### short guide (before I write the documentation):

for all cases:
- (optional but good to get the best results) in lens correction, manually adjust the chromatic aberration settings to minimize the chromatic aberrations
- start with high strength to well see the effect (strength = 4)
- increase radius as much as needed
- change guide channel to find the one which gives best result
- lower strength to better preserve areas without chromatic aberration

additional possibilities for complicated cases:
- if needed, use a parametric or drawn mask
- if needed, use the "darken only" or "brighten only" modes, possibly with 2 instances (one in darken only and one in brighten only)
- if needed, use the R, G, or B blend modes, using several instances, in combination with the darken only and brighten only modes

**Comment by rawfiner** [comment]
By the way, would it be ok for you to rename "chromatic aberrations" module as "chromatic aberrations bayer", to have the module from this PR called "chromatic aberrations" (I don't think having rgb in the name of the module adds some value, it just makes the name longer).
What do you think?

**Comment by jenshannoschwalm** [comment]
Bayer is technically correct but why not "raw"?

**Comment by rawfiner** [comment]
> Bayer is technically correct but why not "raw"?

Yes good idea. It will be more consistent with other modules names in darktable like "raw denoise".

**Comment by TurboGit** [comment]
> By the way, would it be ok for you to rename "chromatic aberrations" module as "chromatic aberrations bayer"

Yes, that's an option.

@rawfiner : do you have a RAW to share for testing this ? I have hard time to find a good RAW with chromatic aberrations, with my camera & kind of photos I do I don't have this or very very light.

**Comment by rawfiner** [comment]
> @rawfiner : do you have a RAW to share for testing this ? I have hard time to find a good RAW with chromatic aberrations, with my camera & kind of photos I do I don't have this or very very light.

Here you are:
https://drive.google.com/drive/folders/1q2ZwinyNtPFkMMcrLHwm4gNwhzFUQUZ1?usp=sharing

Note that most of these are actually really nasty images with really strong chromatic aberrations, advanced techniques described above as "if needed" are actually needed for several of these images. Also, they are mostly from xtrans sensor, so comparison with raw chromatic aberration module is not easy. Though, the P2200055.RW2 picture is a good entry point: not too complicated, and bayer sensor so we can compare with raw chromatic aberration module.

**Comment by aurelienpierre** [comment]
testing…

**Comment by TurboGit** [comment]
BTW, we have now:
- chromatic aberration raw (old renamed raw)
- defringe
- chromatic aberration (this one)

I'm wondering what should be done for defringe module ? Maybe worth considering making it deprecated. Do you agree ?

**Comment by rawfiner** [comment]
Yes defringe could be deprecated I guess...

I pushed a commit that renames this module as "chromatic aberration", and renames "chromatic aberration" as "chromatic aberration raw"

I also pushed a second commit that improves the algorithm, sorry for this late change, I had the new idea this morning... it does not change a lot of things, just adds a refinement step in get_manifolds if asked by the user. This makes hard images such as XT200061.RAF from the drive much easier to correct. It is offered as an option as it may smooth colors too much on images with only small chromatic aberrations

**Review by TurboGit — CHANGES_REQUESTED** [review]
Comments after review.

Apart from that it works well and better than previous (ca & defringe) in all cases I have tested.

**Comment by elstoc** [comment]
The old module might be better named "raw chromatic aberration" rather than "chromatic aberration raw". Seems to fit our existing naming conventions better.

**Comment by rawfiner** [comment]
Thank you for the review @TurboGit ! I pushed the changes.
I also followed @elstoc suggestion and renamed the old chromatic aberration module to "raw chromatic aberrations".

**Review by TurboGit — APPROVED** [review]
All good to me, let's merge. Thanks for the hard work.

**Comment by elstoc** [comment]
I've done some basic changes for the documentation. For now I've created a dummy page for the new module and renamed the old one to "raw chromatic aberrations". See https://github.com/darktable-org/dtdocs/commit/4da608da3c0b7a56ce2d31e5781653a4233b561d.

@TurboGit this should give you the URLs for the help links too.

**Comment by elstoc** [comment]
I've also added the deprecation notice to defringe.

**Comment by rawfiner** [comment]
> I've done some basic changes for the documentation. For now I've created a dummy page for the new module and renamed the old one to "raw chromatic aberrations". See [darktable-org/dtdocs@4da608d](https://github.com/darktable-org/dtdocs/commit/4da608da3c0b7a56ce2d31e5781653a4233b561d).

Thank you @elstoc 
I will write documentation in the coming days :-)

**Comment by TurboGit** [comment]
> @TurboGit this should give you the URLs for the help links too.

Perfect, links changed/added.

**Comment by Mangus78** [comment]
Hi, I'm seeing a lot of artifacts when the image in the darkroom is zoomed out with CA RGB module active, is it an issue related to some setting about preview rendering quality or something else? It's difficult to edit the image without a correct preview, going zooming in and out continuously is time consuming.
Other than that, this module is FANTASTIC!!
immagine

**Comment by rawfiner** [comment]
Hi
Could you send me your raw file and settings to reproduce please?
Thanks!

**Comment by Mangus78** [comment]
I'm using the latest git version compiled today, just experimenting a bit with the new modules.
raw file, the xmp and darktablerc:
https://drive.google.com/drive/folders/1i-ZzuVFESQ185EAcYXvZbZKjg8dnZO2C?usp=sharing

**Comment by Mangus78** [comment]
Oh and btw, I noticed the same behaviour with any image, not just this one.

**Comment by rawfiner** [comment]
Thanks for the raw and xmp
I can reproduce. It seems to appear especially when color smoothing is enabled in demosaic. I don't know the source of the issue yet, I'll investigate.

**Pull request merged**
