### PR TITLE
collect : fix usage of exclude for first item

### LINKED ISSUE #13334: Exclude filter seems to no work anymore on collections module
**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to collections module
2. Start with all images shown (for example starting by filmroll with all filmrolls)
3. click on arrow beside to exclude images
4. for example, choose module then a module to show images that do not have that module
5. See that images shown remains images that have the module ("except" condition seems to work same as and or or)

**Expected behavior**

Having except condition working as before, as except condition!

I see that because I've noticed some images without lens correction module activated and I would quickly found them. I have had that possibility before and no more now.

**Screenshots**
image

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : actual master

### PR DESCRIPTION
**Pull request by AlicVB**
this fix #13334

### CODE REVIEW

**Comment by Nilvus** [comment]
Will test tomorrow as refresh was quite tricky on master.

**Review by TurboGit — APPROVED** [review]
Tested on working on my side. @Nilvus : Do you still plan to test? If not I'll merge.

**Comment by Nilvus** [comment]
Just let me time to test

**Review by Nilvus — APPROVED** [review]
All good, thanks!

**Pull request merged**
