### PR TITLE
c&r : rework the preview ready detection

### LINKED ISSUE #8791: crop & rotate : disappearing grid lines
**Describe the bug/issue**
switching between "darkroom" view to "lightroom"  view and back again ( without any changes ) the grid lines disappear :(

**To Reproduce**
1) remove data.db, library.db.  There is a .db that has the _Crop & Rotate defined with existing grid lines_ ( 3x3 ) ( i dont know who has it defined/retained). I can erase everything wiithout care, so dont do it on real productions.
2) run darktable
3) import a .JPG image ( no associated .xmp file ) crop & rotate Grid lines should be visible on the image.
4) "darktable" should be visable
5) switch to "lighttable"
6) switch back to "darktable"
at this point the **grid lines have disappeared**.
7) to continue on, if you rotate the image, the picture will loose some 5ev brightness. No cropping done, or shown. Thumbnail image in upper left corner seems unaffected,
8) switching back and forth between "lightroon" and "darkroom" does nothing - image retains the loss of light.  I think crop settings does nothing at this point either.

Fedora 32, dt 3.4.1

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : e.g. Linux - kernel 5.10.2 / Win10 (Patchlevel) / OSx
* Linux - Distro    : e.g. Ubuntu 18.4
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**

### PR DESCRIPTION
**Pull request by AlicVB**
this fix #8791 

as said in the issue : 
> That said, I'm quite reluctant to push the fix in master now, because c&r is so sensible, that I'm really not sure to not have broken something else...
So the question is : is this issue critical enough to take the risk or not (open question, really)

### CODE REVIEW

**Comment by johnny-bit** [comment]
SHIP IT :)

**Comment by TurboGit** [comment]
@AlicVB : The deal... I'll test this tomorrow and if all goes well I'll merge to get better field testing (remember the only test case you missed is the one broken) and if an issue is found we'll revert. We have one full month before the release for fixing issues.

**Comment by TurboGit** [comment]
@AlicVB : there is an annoying regression.

- open an image (c&r not activated)
- expand the module (do not activate)
- see that the grids are not displayed
- activate the module now, the grids are still not displayed
- the only way around is to fold & expand again the module

This is really a usability issue. I'm always expanding the module and then get the crop lines to directly work on the image.

**Comment by AlicVB** [comment]
ahah I was sure there will be something ;) I'll have a look !

**Comment by AlicVB** [comment]
@TurboGit : should be fixed. "just" a stupid missing case !
Thanks for the tests

**Review by TurboGit — APPROVED** [review]
Looks good and working on my side now. Let's go for a larger field testing ! Thanks for fixing this.

**Pull request merged**
