### PR TITLE
Update zh_CN.po

### PR DESCRIPTION
**Pull request by Nameless-J**
This time I corrected some mistakes and added two new translations

### CODE REVIEW

**Comment by TurboGit** [comment]
But there is conflicts with previous PO. What should I do ? Copy the new version on top of the other? Maybe you want to double check that nothing bad happened to this PR.

**Comment by Nameless-J** [comment]
Sorry, I'm not very proficient in how to use pull request. So I don't know what kind of conflict happened.
I carefully compared the old and new versions. It seems that my modification will not trigger bugs in the program, and I have used the new version without any errors. So I think we can use the new version to cover the old one.

**Comment by Nameless-J** [comment]
I see three versions here, so maybe I submitted them in the wrong way? Maybe I just need to pull request the latest revision?

**Comment by Nameless-J** [comment]
Anyway, 1c872a5 is the latest.

**Comment by TurboGit** [comment]
Understood, I'll merge manually then. Thanks.

**Pull request closed without merging**
