### PR TITLE
Improve thumbnails CSS and font-weight

### LINKED ISSUE #8985: Font face defined only by font-family attribute
**Describe the bug/issue**
The specific Roboto font face used in _darktable-elegant-*_ themes is currently defined only by `font-family` property. This assumes that _Roboto Light_ and _Roboto Condensed_ are recognized as separate font families. If this is not the case both fallback to _Roboto_ (implemented in https://github.com/darktable-org/darktable/commit/8ecbf59202bf39acc885db9c8054bf6208d73eb8) which is regular weight and stretch.

CSS spec suggests that `font-family` property is only used to specify the family and `font-weight`, `font-stretch` and `font-style` are used to specify an individual face. ([css](https://www.w3.org/TR/css-fonts-3/#font-family-prop))

**Expected behavior**
Adding properties for weight and stretch to https://github.com/darktable-org/darktable/blob/1f105ca20ecdbeb6c023401ee6ee412943bd3fed/data/themes/darktable-elegant-darker.css#L73-L80 and https://github.com/darktable-org/darktable/blob/1f105ca20ecdbeb6c023401ee6ee412943bd3fed/data/themes/darktable-elegant-darker.css#L96-L103 would keep proper font faces even if only _Roboto_ is recognized as a font family. I assume this wouldn't change the font face if _Roboto Light_ and _Roboto Condensed_  are recognized on other systems.

**Platform**
* darktable version : 3.5.0+2228~gabfd8d42e
* OS                : macOS 10.14.6

### LINKED ISSUE #9003: (minor) thumbnails misaligned by 1 pixel in filmstrip depending on aspect ratio
**Describe the bug/issue**

This is really nitpicking here, so I would understand if this issue was closed with a "won't do". 

Anyway, thumbnail pictures are not perfectly centered in their 'slot' in the filmstrip. The left border is 1 pixel too wide (or the right one is 1 pixel too thin, depending on your point of view). Since my pictures have a 3:2 aspect ratio and vertical/square pictures are not affected, I assume that this occurs because the pixel width of the 'box' is always the same and therefore thumbnails with an even or uneven pixel number can not be centered properly.

A fix would probably require to crop a single pixel row from the thumbnail to make the count always even/uneven or by making the width of the box one pixel wider/smaller depending on the shape of the thumbnail. 

To reproduce, use this CSS snippet to better visualize the area around a picture. My screen has a 1680/1080 resolution - other resolutions might require different values.
```
#thumb_main:active #thumb_back
{
  border: 4px solid shade(@thumbnail_selected_bg_color, 1.25);
}
```
image
As you can see, the thumbnail overlaps on the right side but not on the left side.

image
Without the white border it is really hard to spot, but the splitting line is not perfectly centered.

Like I said, it is nitpicking, but once you see it, you cannot unsee it ;)

Manjaro Linux - 3.5.0+1967~g4024d7d73

### PR DESCRIPTION
**Pull request by Nilvus**
Fix #8985. @lhietal: your feedback is welcomed too.

This also improve (a little) CSS code generally (like putting some default setting in the beginning (like radiobutton).

### CODE REVIEW

**Comment by Solarer** [comment]
Hi @Nilvus,
I am now at 3.5.0+2370~gd06912666 (which should be your branch) but nothing has changed as far as I can tell.

**Comment by Nilvus** [comment]
> Hi @Nilvus,
> I am now at 3.5.0+2370~gd06912666 (which should be your branch) but nothing has changed as far as I can tell.

Your answer didn't help. First your issue is hard to reproduce clearly and then, I now have same margin on each side. So without more infos, It will be hard to do more... Just to be sure: it's impossible to not have image hover border if you set big border like you do when thumbnails are small. That's just normal.

**Comment by Solarer** [comment]
What I meant was: I still have uneven margins on my darktable but I even used a brand new config-dir. So I wanted to check if I made a mistake while checking out your code (I don't think I did).
> it's impossible to not have image hover border if you set big border like you do when thumbnails are small.

Sure, what I mean is that the image hovers the right border by 1 additional pixel compared to the left.

This screenshot is from your PR, you might have to zoom in a bit.
image

What else can I do to help you reproduce the issue?

**Comment by Nilvus** [comment]
> What I meant was: I still have uneven margins on my darktable but I even used a brand new config-dir. So I wanted to check if I made a mistake while checking out your code (I don't think I did).

Did you clean completely before compile darktable (remove build dir inside local git folder and remove darktable destination folder) ?
 
> Sure, what I mean is that the image hovers the right border by 1 additional pixel compared to the left.
> 
> This screenshot is from your PR, you might have to zoom in a bit.
> image 
> What else can I do to help you reproduce the issue?

I can't reproduce anymore with my PR. I don't know what you could provide. Just be sure to have compiled with build dir removed and darktable install folder too. And/or test if you find a way to not reproduce (filmstrip in other parts for example) and a more precise way to reproduce. But not sure you will have. See what I have on my side with that PR:



Zoom in and see that margin is the same on left and right.

**Comment by Nilvus** [comment]
Same screenshot with 2 sizes and less margins to see that it's correctly aligned:




I use images with 4:3 format, so I also tested that with a 3:2 image (not sure which one you use) and I also can't reproduce your issue:

**Comment by Nilvus** [comment]
> Weird. Yes I remove the build dir before compiling but I do not use the "install" flag - so I run the binary directly from the build/bin/ dir and leave the destination folder as-is.
> I uploaded 2 pictures here. Can you check if it works with them? https://www.dropbox.com/sh/aptpbndxmbp40lp/AADw5lZWa1tD1XGTNrnmK_FYa?dl=0
> 
> Otherwise I am not doing anything special. It occurs in lighttable and darkroom.

So we are stuck here. The images couldn't be the issue, except ratios one, and as I said, I already tested with 3:2 images like you (your images confirm that you are on 3:2 ratio, what I had suspected) Using an image or another with same ratio will not change anything here. We are only about size, image ratio adjustment. And I'm afraid but I can't reproduce, even with more 3:2 images. So I can't do better here I'm afraid and I see nothing more that could help me reproduce what you have. Except maybe test on your side with a correctly/completely installed darktable version (so not by running it from build dir!

I also really don't see which CSS code remaining could explain what you have. All is set to be centered, same border.

I'm just not really sure if a CSS part could be related to filmstrip (I'm quite sure it's not related and not so will not change anything but in case):

```
.dt_thumbtable_reorder #thumb_main:hover #thumb_back      
{
      border-left : 4px solid rgb(255, 187, 0);
}
```
Could you test by adding that in preferences CSS dialog box and set border size to 2px instead of 4px? Could you reproduce your issue? 

Without able to reproduce or find a way to, it will be hard to help more here. And CSS tweak you add to find that issue is not darktable default setting and your issue is not really visible (or really hard to see) without your CSS tweak,

Anyway, @AlicVB: as you work on Gtk/C code for that part, if you have something to add or any idea, or check if you reproduce or not #9003 issue that this PR try to solve...

**Comment by Nilvus** [comment]
Some more thoughts here. @Solarer: on your issue, you suppose that's this is probably due to fixed thumbnail. The thumbnail is not really fixed, just adjusted to be same size than others ones, and margin is a percent of size that is adjusted dynamically. So not this. This PR improve at least CSS code and add better order. 

I also just tested with different font set in my system (I'm using Ubuntu 21.04 with Gnome 40) and also tested on 2 different screens (my default 16:9 laptop screen with classic 1920x1080 and my external screen with 16:10 and tested with 1920x1200 and 1680x1050) to be sure that doesn't change anything.

So, at this stage, I really don't see how this could be fixed with CSS. And I'm not sure it's necessary to spent more time on that issue (see my previous comment) and except if some new thing come out, I think we will consider it fixed or at least won't fix for you as you said yourself in the beginning of your issue.

@TurboGit: I suggest to wait 1 or 2 day to see if something new is out for this (for example, if @AlicVB find something) or if you found a way to reproduce on your side (maybe). Or you merged this as it is if ok for you. As you want.

**Comment by Solarer** [comment]
I can try some more on Sunday but if you have been able to confirm this bug before your PR and you cannot see it anymore now, then it is likely fixed and something is wrong on my end.
So consider it closed from my side. ;) 
 If necessary I can open a new ticket

**Comment by lhietal** [comment]
> Fix #8985. @lhietal: your feedback is welcomed too.

Font-weight is now working correctly for me and font-stretch is difficult to implement without possible regressions. So fixes #8985. Thanks.

I cannot reproduce thumbnails not correctly centered. With or without this PR.

**Comment by Nilvus** [comment]
> I can try some more on Sunday but if you have been able to confirm this bug before your PR and you cannot see it anymore now, then it is likely fixed and something is wrong on my end.
> So consider it closed from my side. ;)
> If necessary I can open a new ticket

Ok, thanks for your help. The tricky part here is I've successfully reproduce your issue 2 times with master, but only 2 times and I can't ind how. So I even not sur that my PR really solves the issue. I've tried again with master this day and can't reproduce. And @lhietal comment confirm that too. So, it remains possible that your issue only appears in really specific config/settings/sizes or something else you could add here... And will be hard to find if it's still there. By the way, we also need to not broke something else for such a minor thing and, apparently, a glitch that appear in some really specific cases.

**Comment by Nilvus** [comment]
> Font-weight is now working correctly for me and font-stretch is difficult to implement without possible regressions. So fixes #8985. Thanks.

Thanks for your feedback for both issues related here. And I totally agree with you about font here: it would be a bad idea to add more thing at this state in CSS code without taking the risk to have regressions. That's why I didn't add more. Font-weight set to medium for example doesn't work correctly, so I don't add it.

**Comment by xfh** [comment]
@Nilvus I think @Solarer 's issue is hard to reproduce due to how sensitive you need to setup the scale. It's more noticeable when the filmstrip is small and you need to adjust the height pixel by pixel.

I got here an example where the thumb width is 120px, borders set to 4px. This is with darktable 3.4.1 and still happens with your pull request.

rounding-offset

I don't think it's a CSS related problem. The GTK widgets only accept integer sizes. The mipmaps (image thumbnail in pre-computed sizes) have to be fitted/scaled into the thumb widget. This happens in two places:
https://github.com/darktable-org/darktable/blob/481978bcad0b44da636e2bd396dc3a774c13712b/src/dtgtk/thumbnail.c#L465-L466
and
https://github.com/darktable-org/darktable/blob/481978bcad0b44da636e2bd396dc3a774c13712b/src/views/view.c#L1022-L1025

As you see, the float values have to be rounded to integers for the GTK widgets and the cairo surface. The final width can differ by one pixel, probably due to different rounding.

In my case, the thumbnail wants to set the width to 114px, but cairo rounds it down to only 113px, resulting in the 1px offset.
In my test case, the cairo width was computed to 113.999992px, but due to the integer conversion only 113 px remain. Maybe it would be better to use a natural rounding in view.c, but That might affect quite a bit. Curious what you think @AlicVB.

**Comment by Nilvus** [comment]
@xfh: thanks for such precise and complete answer. This helps a lot. As you, I've tried a lot of height (really small, small, medium and big ones) to check and even use screen ruler tool like you to check carefully.
I don't know anything with Gtk and was suspecting something possible on this side and you confirm that. That's why I ping (and you too) @AlicVB. It's not an urgent thing but all details count.

With that answer, @TurboGit: you could review and merge this PR. I think we have no more thing to do with CSS now. I will unlink @Solarer issue and assign to @AlicVB.

**Review by TurboGit — APPROVED** [review]
Works for me, thanks !

**Pull request merged**
