### PR TITLE
RGB parade as histogram alternative

### PR DESCRIPTION
**Pull request by dtorop**
This adds RGB parade as a histogram alternative (see #4149).

To not require cycling through too many histogram types, the single button which cycled between linear/logarithmic/waveform is replaced by two buttons. One toggles between "regular" histogram and waveform-style. The other, when in histogram mode, toggles between linear and logarithmic histogram. When in waveform mode, it toggles between waveform and RGB parade.

Much of the code changes (including a new conf entry) are to allow this mode/submode switching. This will also clear the way for other modes (e.g. vectorscope) without bothering users who already don't want to see a waveform when simply want to switch between linear and logarithmic histograms. 

There are also some optimizations, particularly to histogram calculation. This PR should be equivalent speed to the code in master, for both calculating and drawing histograms. It requires 3/4 the memory to store the calculated waveform histogram, though it uses more temporary memory when drawing the waveform histogram.

### CODE REVIEW

**Comment by prokoudine** [comment]
Your more recent 'more-scopes' branch fails to build though

```
[ 96%] Test-compiling OpenCL program blendop.cl
/home/alex/soft/photography/darktable/darktable-more-scopes/data/kernels/blendop.cl:1004:35: error: use of undeclared identifier 'CL_FLT_EPSILON'
  const float mask_epsilon = 16 * CL_FLT_EPSILON;  // empirical mask threshold for fully transparent masks
                                  ^
1 error generated.
make[2]: *** [data/kernels/CMakeFiles/opencl-program-blendop.cl.dir/build.make:62: data/kernels/blendop.cl.touch] Error 1
make[1]: *** [CMakeFiles/Makefile2:8763: data/kernels/CMakeFiles/opencl-program-blendop.cl.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by dtorop** [comment]
@prokoudine:

> Your more recent 'more-scopes' branch fails to build though
...
> /home/alex/soft/photography/darktable/darktable-more-scopes/data/kernels/blendop.cl:1004:35: error: use of undeclared identifier 'CL_FLT_EPSILON'
>   const float mask_epsilon = 16 * CL_FLT_EPSILON;  // empirical mask threshold for fully transparent masks

Try the rgb-parade branch (as in this PR). The more-scopes branch is very much work-in-progress, and even though it may have commits dated newer, is actually older code (I rebased before making rgb-parade branch). The more-scopes branch is from just before the fix in 7781cb1c1f27c4c697ce93e135b74096b76d6140, and won't compile without that fix.

I'll rebase & update more-scopes eventually, but it's very much a working branch.

Thank you for trying this out.

**Comment by TurboGit** [comment]
This looks ok. I tested it and it works fine, I'm not quite clear about the way to use such histogram as it is new to me. I'm merging that. Thanks.

**Comment by dtorop** [comment]
@TurboGit That's fabulous. Thank you for looking it over and merging it! I've come to like the RGB parade after a few weeks of using it. You get to see the character of each color channel and how their overall levels compare with a bit more clarity than waveform. But I also think waveform is great and probably the more useful overall visualization...

**Comment by phweyland** [comment]
Nice !
Should not be the waveform / histogram icons inverted ?

image

**Comment by dtorop** [comment]
@phweyland  writes:

> Should not be the waveform / histogram icons inverted ?

Good questions! I tried not to change the existing behavior (though I sometimes wondered if it is a bit backward).

Here's the behavior before this PR (737735db94617468392fd76d109741a1a530e034):

image

The rule seems to be that the icon represents the current state, and the tooltip gives guidance as to what a click will do. The rationale may be that the converse would be a bit strange -- to see an icon which is the opposite of the current state.

These buttons are a bit of a hack -- custom rolled outside of dt's themed gtk & bauhaus. Maybe the real problem is that these should be proper widgets, e.g. dtgtk_togglebutton, with some more thought to behavior/icon.

**Comment by dtorop** [comment]
To follow up -- in fact, the histogram UI could use a general update. Currently how it positions/sizes the buttons and detects mouseover/click/drag is entirely hand-rolled (a monolithic widget). It redraws the entire histogram widget on motion-notify-event, which is more work than is needed.

**Pull request merged**
