### PR TITLE
Improve dialog options of deletion error second attempt

### PR DESCRIPTION
**Pull request by dterrahe**
Attempt to push #10821 over the line, since @Solarer doesn't seem to have time at the moment.

This first rebases the additions made by @Solarer off master.

Then it adds an "apply to all" to the delete/remove confirmation dialog(s) to use the answer for all remaining files. This works for all answers (delete/remove/skip and obviously abort). If attempting to move to trash first, then if in the first confirmation a physical deletion is requested _without "apply to all"_ but then in the second any of the options is requested _with "apply to all"_ then the physical deletion is implied for all remaining files that could not be moved to trash as well.

image

Not sure how to make "move to trash" fail but "physically delete" succeed, so this all needs some testing.

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
I think I have tested this properly and it works on my side. I'm not sure I have tested all scenario though. Anyway, let's merge this as it is a nice usability enhancement. Thanks!

**Comment by Solarer** [comment]
@dterrahe thanks from my side as well for picking this up

**Comment by dterrahe** [comment]
Release note:
- improve clarity and usability of dialog to confirm further action upon failure of physical file deletion or moving to trash.

@elstoc @paperdigits @victoryforce if you have suggestions to improve any of the strings changed or introduced in this PR, please get them in before the string freeze. Many thanks!

**Comment by TurboGit** [comment]
@dterrahe : Thanks a lot!

**Comment by victoryforce** [comment]
> if you have suggestions to improve any of the strings changed or introduced in this PR, please get them in before the string freeze.

My suggestions are as follows:

- It is better to get rid of redundant words that do not add clarity. The shorter the better. Without the word "physically" the text loses nothing in comprehensibility.
- It is better to get rid of the words "no" and "yes". This will help to narrow down too wide answer buttons, and for the user's mind, this is an extra word-answer that _ties his attention to the question_. Whereas it is easier for the user when the reply button is self-contained.
- Likewise, it is better to choose accelerators that emphasize action verbs, i.e. D for _Delete and R for _Remove. Using Y and N (for _Yes and _No) force the user to recall how the question is worded.
- It is better to put the action verb first in order to immediately catch the user's attention. That is, I would formulate the first two buttons as `_delete permanently` and `_remove from library`.

What are your thoughts on these suggestions?

**Comment by dterrahe** [comment]
All fine by me. I am a poor judge on whether any of these are an improvement for the layman. Please submit a PR!

**Pull request merged**
