### PR TITLE
Show the full-frame equivalent focal length in the image information module

### LINKED ISSUE #14155: Exif "Focal Length in 35mm Format"
**Is your feature request related to a problem? Please describe.**
 It seems that Darktable does not import the EXIF variable "Focal Length in 35mm Format". I would find it very useful for cameras with non-full frame sensor.

**Describe the solution you'd like**

**Alternatives**

**Additional context**

### PR DESCRIPTION
**Pull request by victoryforce**
Closes #14155.

Additional information is not shown when we know that the sensor is full-frame, this will obviously be redundant. Also, image metadata does not always directly contain data on the equivalent focal length. In some cases, such information can be calculated from other available data (this is the case, for example, with Canon cameras), but this is a separate issue.

Also added precision to the displayed focal length. Even for camera zoom lenses, the focal length will not always be a whole number. As for the actual focal length of optics in smartphones, it is several times shorter. Therefore, if the true focal length for the smartphone image was, say, 1.9 mm, and we discarded the decimal part and showed it as 1 mm, then in percentage terms this is a huge inaccuracy.

### CODE REVIEW

**Review by ralfbrown — APPROVED** [review]
Looks good.

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Comment by TurboGit** [comment]
Needs a release notes entry please.

**Comment by victoryforce** [comment]
For the Release Notes:
"Show the full-frame equivalent focal length and crop factor in the image information module"

**Comment by TurboGit** [comment]
Thanks!

**Pull request merged**
