### PR TITLE
add noise profiles for 2 cameras

### PR DESCRIPTION
**Pull request by hatsunearu**
Closes issues #5876 and #6138. Please double check if the graph fits are acceptable, but it looks good in my eyes.

### CODE REVIEW

**Comment by LebedevRI** [comment]
Sorry, i'm not sure who reviews new noise profile submissions, but i don't know how to read those plots.

**Comment by LebedevRI** [comment]
Those submodule changes should not be in the PR.

**Comment by hatsunearu** [comment]
Shit, let me see how to fix. I might have to "rewrite history" or make a new PR

**Comment by TurboGit** [comment]
@LebedevRI : @rawfiner or I can read and validate those noise profiles.

**Pull request closed without merging**
