### PR TITLE
Fix a copy and paste bug in messages in LUT 3D module

### PR DESCRIPTION
**Pull request by victoryforce**
We were referring to 3dl format files as cube format files.

### CODE REVIEW

**Comment by victoryforce** [comment]
@TurboGit This PR now also includes a fix for a broken macOS CI build caused by lensfun package explicitly depends on python 3.10 instead of system-wide version (which is now 3.11). As in the previous similar case, I simply added a commit to the existing PR to test what would work.

As with all CI fixes, it would be great if this fix were accepted ASAP. It does not change the actual dt code in any way, so the code freeze status should not limit us here.

But you might not want to accept all the PR that affects GUI strings right now. So the question is, should I separate this CI fix into a separate PR?

**Comment by victoryforce** [comment]
Since the lensfun formula in homebrew has been corrected, the corresponding fix that was added to this PR is no longer needed. Therefore, it is simply removed from this PR, which now contains only fixes to the UI texts, as indicated in its title.

**Comment by TurboGit** [comment]
@victoryforce : My plan about this is the following. I'll merge in 4.2 if we also break some more strings in some other important fixes for the next minor release otherwise I'll prefer having this for 4.4.

**Review by TurboGit — APPROVED** [review]
Thanks! We have some string changed in 4.2, so let's go with that.

**Pull request merged**
