### PR TITLE
qap : use module gui order

### LINKED ISSUE #9739: FR: Quick Access panel: order of widget according to iop instead of alphabetical order
if i add some sliders of colorbalance rgb to the quick access panel these are ordered alphabetically. 
In my opinion it makes more sense to keep the order of the original module since this order makes sense ;)

**Alternatives**
make the order of widgets customizable (more effort to allow users to get the same result)

### PR DESCRIPTION
**Pull request by AlicVB**
this fix #9739

after all the work around accels, the qap widget are sorted in the interface by alphabetic order, which doesn't make sense.
This PR change that by reusing the module "real" order, as shown in the gui.

this is done by recursively inspect the subwidgets inside the module main widget. afaict, this works without problem. The only problematic case I can see is if a module for some reason *remove* a widget (instead of hiding it) but I'm not sure if this happen at all (and anyway, in this case, this should better be changed by hiding it)

this also add some computations each time the QAP is shown, but I've not seen any latency in real usage...

### CODE REVIEW

**Comment by dterrahe** [comment]
Well done! I was thinking along those lines but thought it would be too complicated to implement.

One little problem I think this might have is that some actions are linked to containers. For example you can add some "notebooks"/tab groups to QAP (for example together with a graph; the tabs then select which of luminance/hue etc are manipulated in the group.) I think your code will only look _inside_ the tabs, but not consider adding the tabgroup itself. Although I haven't actually tested...

**Comment by AlicVB** [comment]
> For example you can add some "notebooks"/tab groups to QAP

oh right... I was not aware of this possibility. from my test, I've found `color calibration -> page` that works like that. right ?
I've just pushed a fix, so now qap inclusion is also tested for containers now...

**Comment by dterrahe** [comment]
That looks like it should work indeed.

One more thought; if a container is added  to QAP, maybe you don't want to look if separate widgets within the container should also be added because the outcome might be a little unexpected? Again, I haven't been able to test this...

**Comment by AlicVB** [comment]
@dterrahe : indeed, you're right ! Now we just exit the routine as soon as the widget is added, whatever if it's a container or not. This also avoid unnecessary loops....

**Review by TurboGit — APPROVED** [review]
Works for me, thanks !

**Pull request merged**
