### PR TITLE
restore proper display of modules in sidebars

### LINKED ISSUE #17441: commit 799f2296fa breaks display of modules in sidebars
### Describe the bug

When 799f2296fa was added, all utility and processing modules which normally showed in the sidebars in lighttable, darkroom, and map views disappeared.  Darkroom still shows the nav window, scopes, modulegroup tabs, and module order, but nothing else in the sidebars.

Bisect result on master bdd838ac36 was
```
799f2296fa1a1cae3e02172cdf9b4e8dd3e78df5 is the first bad commit
commit 799f2296fa1a1cae3e02172cdf9b4e8dd3e78df5
Author: Diederik ter Rahe <dterrahe@yahoo.com>
Date:   Fri May 24 09:16:48 2024 -0400

    simplify tips when lighttable is empty
    
    add more lines pointing to correct buttons
    right align 2nd column and ellipsize if not enough space

 src/dtgtk/thumbtable.c | 187 +++++++++++++++++++++++++------------------------
 src/dtgtk/thumbtable.h |   1 +
 src/gui/gtk.c          |   1 +
 3 files changed, 97 insertions(+), 92 deletions(-)
```

### Steps to reproduce

1. Start darktable with the above-mentioned commit included; this may be with either an existing config or a new, empty config directory
2. in lighttable, observe that both sidebars are empty (no import/collections/image information on left, no history/styles/tagging/export on right)
3. if using an existing config, change to darkroom and observe no utility or processing modules in the sidebars, only nav, scopes, modulegroups header, and module order
4. switch to map view and observe empty sidebars

### Expected behavior

appropriate modules should be shown in both sidebars

### Logfile | Screenshot | Screencast

_No response_

### Commit

799f2296fa

### Where did you obtain darktable from?

self compiled

### darktable version

4.9.0+439~g799f2296fa

### What OS are you using?

Linux

### What is the version of your OS?

Mageia 9

### Describe your system?

_No response_

### Are you using OpenCL GPU in darktable?

No

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by ralfbrown**
Fixes #17441

### CODE REVIEW

**Comment by pehar1** [comment]
Also not reproducible for me with 4.9.0+442~g014696f710

**Comment by ralfbrown** [comment]
I don't understand it either, but that was the only thing added in the breaking commit whose removal fixed things....  Somehow, hooking the signal for the center view must have prevented the sidebars from being redrawn properly.

Gtk 3.24.38
Glib 2.76.3

**Comment by ralfbrown** [comment]
Took another look at that code, and realized that the callback function used returns `void` rather than `gboolean`.  If I instead hook a function which does nothing but return TRUE, I get the broken behavior; if the function does nothing but return FALSE, everything works correctly.  So it looks like having a later hook (which I guess gets called first) by a function which happens to leave a nonzero value in RAX, Gtk thinks the signal has been handled and doesn't pass it along to the earlier function which used to get the signal and redraw the side panels as well as the center.

**Comment by dterrahe** [comment]
@ralfbrown's analysis is exactly right.

I'm adding a fix in #17425 (which would otherwise have to be rebased again if a fix was committed separately first).

**Comment by ralfbrown** [comment]
Fixed by #17425

**Pull request closed without merging**
