### PR TITLE
crop : remove double-click to apply feature

### LINKED ISSUE #10486: Same double click behaviour in Crop and Rotate
In the latest version (built locally) the Crop and Rotate are now two different modules. Now we have `crop`, and `rotate and perspective`.  The original behaviour was to double click the photo to finalise the changes. This is still the behaviour in `crop`.
In `rotate and perspective`I have to leave the module pane (i.e. click on another module) to activate the changes.

**Describe the solution you'd like**
I like the double click and it would be awesome if both modules adopted the same function.

**Alternatives**
in any case, it would be more logical if both modules have the same workflow. Being double click or not they are different now.

### PR DESCRIPTION
**Pull request by AlicVB**
this fix #10486 

Same as what has been done for c&r some times ago.
this may cause some problems with focus

### CODE REVIEW

**Comment by elstoc** [comment]
For 3.8? Aren't we in feature freeze?

**Comment by AlicVB** [comment]
Well... I see it more as a bug fix, as it was a fix for an issue in c&r that I forget to port to the crop module...
but in fine, I don't really care as the related issue is not so obvious to reproduce...

**Comment by elstoc** [comment]
I'm not bothered. Just thought I'd ask the question

**Comment by TurboGit** [comment]
> For 3.8? Aren't we in feature freeze?

That is a bug fix to me.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by elstoc** [comment]
I've no problem with merging this but just a note that when we get to string freeze we might want to be careful about things that need a user manual update, since we are intending to have a dtdocs string freeze at the same time.

**Comment by TurboGit** [comment]
Noted !

**Pull request merged**
