### PR TITLE
rework color harmony GUI - guides selection

### LINKED ISSUE #13458: add harmony guides buttons - remove corresponding key shortcut (alt-scroll)
I find (let's see if it is shared) that changing the color harmony guides using a key combination (alt+scroll) is not good.

My proposal would be to add a set of buttons to select one of the guide. Maybe vertically where the current harmony toggle is? Any other proposal? And then remove this `alt-scroll` support (we still have an action that can be used to map to any key) and the description in the tooltip.

Also after some use I also found the current color harmony icon hard to read on my big screen. I would certainly prefer:

image

BTW, you mentioned also that you liked it.

### PR DESCRIPTION
**Pull request by Mark-64**
Fixes #13458 (or at least it tries to).

Introduce a pop over menu to select the color harmony in place of the ALT+SCROLL.
New icon for the button too.

image

### CODE REVIEW

**Comment by TurboGit** [comment]
I'm not found of the pop-over.

**Comment by spaceChRiS** [comment]
I just tested this and there are a couple of topics that I found:
1. The color harmony guides are only visible in RYB. It might not be obvious to the user why this is the case. Therefore I wonder if the icon should be there always, but greyed out and with a mouseover tooltip that explains why it is not active?
2. It would be great to be able to cycle through the different harmony guides when using the mouse wheel with the mouse over the color harmonies icon.
3. The order of cycling through the widths of the guides seems odd to me, currently it is zero --> small --> wide --> medium, but to me, zero --> small --> medium --> wide seems more natural.
4. Shift-scroll reduces the step size of rotation here, while the typical behavior is that shift-scroll accelerates the action. I understand that ctrl-scroll, which otherwise reduces the steps, is already used to change histogram height. But maybe it makes sense to have the fine rotation as default and the coarse rotation with shift?

**Comment by Mark-64** [comment]
> I'm not found of the pop-over.

I am happy to change, what do you propose?
A sting or a grid of buttons doesn't seem better to me. They would have icons very similar to each other and user would have to rely on tooltips to see which is which, which would end up to be slower

**Comment by Mark-64** [comment]
> > I'm not found of the pop-over.
> 
> I am happy to change, what do you propose? A string or a grid of buttons doesn't seem better to me. They would have icons very similar to each other and user would have to rely on tooltips to see which is which, which would end up to be slower

**Comment by Mark-64** [comment]
>     1. The color harmony guides are only visible in RYB. It might not be obvious to the user why this is the case. Therefore I wonder if the icon should be there always (Edit: I mean, only on the vectorscope, but all its modes), but greyed out and with a mouseover tooltip that explains why it is not active?

I am not in favor of this, the whole logic of the histogram is to hide buttons when they are not relevant. Color harmonies are traditionally assessed in the RYB space, users have to understand this or read the documentation

 
>     2. It would be great to be able to cycle through the different harmony guides when using the mouse wheel with the mouse over the color harmonies icon.

This is nice, I might try to do it, although I don't recall of this kind of interaction in other parts of DT gui, let's see what others think about it.

>     3. The order of cycling through the widths of the guides seems odd to me, currently it is zero --> small --> wide --> medium, but to me, zero --> small --> medium --> wide seems more natural.
The idea was to start from medium (default) and then the variants -> wide -> small -> zero. But it is easy to change

>     4. Shift-scroll reduces the step size of rotation here, while the typical behavior is that shift-scroll accelerates the action. I understand that ctrl-scroll, which otherwise reduces the steps, is already used to change histogram height. But maybe it makes sense to have the fine rotation as default and the coarse rotation with shift?

Again, it's a question of usability, shorter keystrokes for the more frequently used functions. Coarse rotation should be ok for 99% of the cases, as in the color space 15° is a noticeable change, but I hardly imagine a use case requiring 1° accuracy.

**Comment by spaceChRiS** [comment]
> the whole logic of the histogram is to hide buttons when they are not relevant.

Sure, it was just something that I stumbled upon when trying your PR (I know it's actually related to another PR already merged, but I only tested it now with the new PR). And IMHO the inactive button with the tooltip is relevant as it serves a purpose, in the same way a save button is there but inactive and becomes active when one starts to enter a file name (just the first example that came to my mind). I read the discussion in the other threads, but may not remember all details. However, in this case it is not about adding 10 more icons, but only if there are 3 on the right side in all 3 vectorscope modes, or only in one. In RYB there are three anyway. And histogram and waveform even have 4 buttons on the right side, in none of these modes, buttons on the right side change (but to be fair, they also are always strictly necessary). (Don't get me wrong, I can live with both solutions, and your additions to the scope are already a great achievement, it's just that I find an inactive button more sound.)

> I don't recall of this kind of interaction in other parts of DT gui

It's e.g. the behavior of all drop-down selections.

> The idea was to start from medium (default)

Due to my try-and-error testing I missed the initial state, therefore it was not obvious to me.

> Again, it's a question of usability, shorter keystrokes for the more frequently used functions. Coarse rotation should be ok for 99% of the cases, as in the color space 15° is a noticeable change, but I hardly imagine a use case requiring 1° accuracy.

Sure, I think you are correct about the usability, but on the other hand, shift-scroll might be already in the muscle memory of many users. What about remapping the ctrl-scroll change size functionality in favor of a consistent UX, e.g. to shift-ctrl-scroll? I know that this is already there for a while, but now we have mouse resize as well …

I know that I am late to the party, and that this is most likely the wrong PR for these discussion, but OTOH I thought my feedback based on this initial test with fresh eyes may be useful.

**Comment by Mark-64** [comment]
So, all in all, for color harmonies, there is a pop over menu (still to be agreed if we prefer a menu with many buttons).
I moved all the scroll actions from the histogram drawable to the harmony button, following an idea by @spaceChRiS :
- scroll to coarse rotate
- shift+scroll to fine rotate
- alt+scroll to change harmony
- ctrl+scroll to change width

Those seem to be more confined to me now, avoiding to mess up with the histogram drawable

Also  introduced action to cycle color harmonies. I put it in the "color harmonies" section, @dterrahe should it be on the upper level instead?

**Comment by TurboGit** [comment]
> I am happy to change, what do you propose?

I understand that my comment was not very helpful, but I already said that I would prefer set of buttons.

My full proposal (to be discussed with others to be sure we won't ask you to change again & again the code):
- Move the vector-scope button on the left in the group of 4 top-left.
- When vector-scope is activated display the set of guide buttons bellow it
- When flying over the button display the actual guide + the name
- Of course, clicking on the button select the guide
- The new buttons on the left have to be different and possibly none selected (no guide)
- The left button of the top-right button set can be removed. 

I understand that this takes some space, but when the cursor is over the score we don't really care about the scope itself at this point. So the little parts hidden by the buttons are not that terrible or making things impossible for the users.

A quick mock-up:

image

**Comment by dterrahe** [comment]
> * scroll to coarse rotate
> * shift+scroll to fine rotate
> * ctrl+scroll to change width

Not wanting to start a whole side-discussion about this that isn't the most crucial at this point, but just mentioning that the "standard" is that adding "shift" to scroll normally triggers coarser adjustments and "ctrl" means fine. The problem here obviously is that ctrl is already taken by the resize and that fine as default might be tedious. But we could consider changing the resize trigger to something more complicated (like alt+shift+scroll or something) now that resize can also be achieved by left-button drag directly. #13129 would also benefit from this.

As said I'd be happy to ignore this completely for now; if it is changed at some later point in a comprehensive overhaul of scroll behavior I don't think it would take too much time to retrain muscle memory for this particular module.

**Comment by Mark-64** [comment]
> > * scroll to coarse rotate
> > * shift+scroll to fine rotate
> > * ctrl+scroll to change width
> 
> Not wanting to start a whole side-discussion about this that isn't the most crucial at this point, but just mentioning that the "standard" is that adding "shift" to scroll normally triggers coarser adjustments and "ctrl" means fine. The problem here obviously is that ctrl is already taken by the resize and that fine as default might be tedious. But we could consider changing the resize trigger to something more complicated (like alt+shift+scroll or something) now that resize can also be achieved by left-button drag directly. #13129 would also benefit from this.
> 
> As said I'd be happy to ignore this completely for now; if it is changed at some later point in a comprehensive overhaul of scroll behavior I don't think it would take too much time to retrain muscle memory for this particular module.

In this PR I moved the scoll actions from the drawable to the color harmony button. So also ctrl is available.
If we switch to a series of buttons we can do the same for every button.
Thta has the advantage to be more confined and not interfere with the resize by ctrl+scroll

**Comment by Mark-64** [comment]
> My full proposal (to be discussed with others to be sure we won't ask you to change again & again the code):

Ok, let's wait a bit to see if there is consensus on this. I will have little time to work on DT for the coming two weeks anyway.

**Comment by HSUfineprint** [comment]
> display the set of guide buttons bellow it
When flying over the button display the actual guide + the name

Surely, I agree with @TurboGit in these.
But I prefer harmony buttons on the right side. That keeps functions on the right, scope selectors on the left. 

As for shift + scroll, respect the behavior is important. Scroll to rotate 10~15° by default is enough in most usage. Use something more complicated to rotate 1°.

**Comment by TurboGit** [comment]
> But I prefer harmony buttons on the right side. That keeps functions on the right, scope selectors on the left.

But for them to not hide too much the display it must be on the right along the borders. But in this case it must be always displayed even for non vectorscope otherwise the group of buttons on the right will change position (jump) each time the vectorscope is selected or unselected. That's why in my proposal I have put the vectorscope first on the left.

**Comment by HSUfineprint** [comment]
> But for them to not hide too much the display it must be on the right along the borders.

It depends on the width/height ratio of histogram module. In my case, they didn't need to be on the right border and won't block the scope. Not sure about other users. But monitor ratio is wider and wider, I guess that might not be a problem. We got more and more space on width.

**Comment by HSUfineprint** [comment]
So, it's an organization or visibility choice. I would compromise on that. Since current layout is not 100% functions / scope selectors separate.

I'm wondering if we could open a topic to solicit opinions when consensus is not clear, in where users are, pixls maybe. Not talking this PR, but sometimes coding is in blind or someone's opinion.

**Comment by Mark-64** [comment]
For everybody to comment, this is @TurboGit proposal
image

Real code, but not fully functional yet. The vertical box with the color harmony buttons could be made a bit different in css to have a better separation.
My only concerns are:

- some the buttons are quite similar, to understand which is which you will have to see the tooltip or fly over the buttons to see the "preview" on the graph
- the buttons take a lot of vertical space, if the scope height is reduced, the last ones will be hidden

For the last point, maybe putting the buttons inside a popover, but then we need another button to trigger it.

**Comment by TurboGit** [comment]
> * the buttons take a lot of vertical space, if the scope height is reduced, the last ones will be hidden

You can remove the first one (no grid) as we can have the same if no button are toggled.

**Comment by dterrahe** [comment]
> the buttons take a lot of vertical space

((_I'm only going to whisper this, but have you tried GtkFlowBox? A whole new can of worms for you to savour...))

**Comment by Mark-64** [comment]
For you to test, with the last commit we switch to this

image

Automation seems to work, including fly over effects and actions (but need testing)
Also moved text to the right, to take less vertical space.

I want to try GtkFlowBox, but can't do it before one week.
Comment are welcome

**Comment by TurboGit** [comment]
For me this last version is perfect for vectorscope.

I would just reorder the scope now to put : vectorscope (first as today), waveform, rgb parade, histogram

That is the two most important scopes first vectorscope and waveform.

**Comment by Mark-64** [comment]
> I would just reorder

Done.
Please note that all scroll actions are moved from the graph to the buttons.
This way they are not interfering with scope resize, and moreover, while your are flying over the buttons to choose the best fit, you can also scroll to rotate, which is very handy.
I put this as ready for review. Other improvements can be done with other PRs

**Comment by TurboGit** [comment]
> Please note that all scroll actions are moved from the graph to the buttons.

Yes, I've seen that and for me it is perfect. As you said it does not interfere with global scope accels and also make it easy to switch & rotate guides.

**Comment by TurboGit** [comment]
Let's move forward, this is so much better than the current UI I'll merge this today. Again we can always refine the implementation but I've been using this and really much much better than the current UI.

**Comment by Yvan-56** [comment]
Hi everyone,
Firstly, many thanks for the color harmony in vectorscope, it is awesome, easy to use and very efficient !
Just one little suggestion: may it be possible to move dyad before tryad for coherency (when looking at the list of icons to select) ?

Regards,
Yvan

**Comment by TurboGit** [comment]
@Mark-64 : I have one minor UI improvement to propose. I'll move the tooltip on the main vectorscope icon. We don't need it on the guide buttons as it repeats the exact same accels and the name of the guide (first line) is anyway on then bottom-right of the scope. Those tooltip tend to be annoying and hiding the scope/buttons when flying over.

**Comment by TurboGit** [comment]
> Just one little suggestion: may it be possible to move dyad before tryad

That's already the case. Before dyad we have the divided-complementaty.

**Comment by TurboGit** [comment]
@Mark-64 : On alternative to my proposal is to ensure the tooltip is always drawn on the left of the current mouse position.

**Comment by TurboGit** [comment]
@dterrahe : As our Gtk expert can you comment about the way to display a tooltip at some specific location? IIRC we tried that but it was not easy... I don't remember all the details :) TIA.

**Comment by Mark-64** [comment]
I am ok with both solutions, but I am away from home, I can't help with coding for few days

**Comment by dterrahe** [comment]
> can you comment about the way to display a tooltip at some specific location? IIRC we tried that but it was not easy... I don't remember all the details

We (or at least I) haven't tried to force-position the tooltip window; the fight you are referring to was with popover positioning. Tooltips locations can in theory be manipulated, but without trying I don't know if that interferes with the standard tooltip routine (that adds the shortcuts etc). We'd also have to consider that the scope can be moved to the left panel, so then the tooltip would have to be drawn on the right, over the vectorscope itself.

My preferred solution would be to remove the tooltips from the individual guides (except if they have been assigned a shortcut). As you say:
> the name of the guide (first line) is anyway on then bottom-right of the scope.

Then if widget resize is changed to alt+shift+scroll (an RFC PR will be submitted soon) I would move the scroll handling to the scope itself (as it is with histogram etc) and move the (changing) tooltip there as well (consistent with the other modes, including correct title "vectorscope" etc)
Scrolling over the icons can be made to fall through to the scope itself so the benefit mentioned in https://github.com/darktable-org/darktable/pull/13469#issuecomment-1413579478 need not be lost.

If this gets merged I'm happy to make those changes in the alt+shift+scroll resize PR I mentioned (if @Mark-64 is ok with that).

**Comment by TurboGit** [comment]
@dterrahe : That's a deal then :) I'll move the tooltip myself and will merge this. Then I'll let you rework the actions.

**Comment by dterrahe** [comment]
Other small suggestion, now that I'm finally (sorry) playing around with this a bit more (and at the risk that this might have been discussed before; again sorry) could the harmony name in the bottom right corner be swapped with the rotation angle so that it sits lower and especially the long ones stick out a little bit less over the scope itself? And maybe remove the "rotation: " string?

And the upper limit to the aspect ratio that the histogram can be resized to could be increased > 100% (in darktableconfig.xml.in) so one can choose if one wants the icons on the left _or_ the text at the bottom right to intrude over the drawing?

**Comment by TurboGit** [comment]
Ok, on both points. I'll do that. Thanks.

**Review by TurboGit — APPROVED** [review]
Thanks! A very very nice addition to darktable.

**Comment by TurboGit** [comment]
@dterrahe : All done now. I'll be off for around 3h. Hopefully I did not messed something :)

**Comment by Mark-64** [comment]
The problem I see by swapping the two text lines at the bottom right is that while numbers characters have all the same pixel extents in pango, letters have different heights, so the placement of the text might slightly change with the different guide lines.
I can't test now and not a big deal anyway, but since I am a bit maniac with these imperfections, I will investigate and possibly fix when I am back.

**Comment by dterrahe** [comment]
Yes, I saw that it jumped a bit. Seems to be solved by getting logical instead of ink extends.

**Comment by s7habo** [comment]
Very nice addition!

I just saw it and am testing it. However, scrolling does not seem to work. I am not able to rotate it. 

I am testing it with darktable 4.3.0~git450.f5a79a84-1+9040.1 version in Kubuntu 22.04.

**Comment by ptilopteri** [comment]
nor for me on openSUSE Tumbleweed, dt f5a79a84

**Comment by dterrahe** [comment]
> I am not able to rotate it.

For now (in master) you need to hold the mouse over the harmony buttons for scrolling to work. #13523 solves this.

**Pull request merged**
