### PR TITLE
po/overlapping path sel

### PR DESCRIPTION
**Pull request by TurboGit**
Add support for handling overlapping forms.

The selection is done based on the distance of the cursor from the forms' barycenter. Testing with standard masks and on retouch module.

Current status of what is done:

- [x] circle
- [x] ellipse
- [x] path
- [x] gradient
- [x] brush

### CODE REVIEW

**Comment by elstoc** [comment]
Not sure what you mean by 'barycentre'. Wouldn't it be better to determine based on closeness to the edges (the visible mask outline)?

**Comment by TurboGit** [comment]
> Wouldn't it be better to determine based on closeness to the edges (the visible mask outline)?

No because there is more chance to get a wrong control points (ellipse / path)  selected as there is many of them. Now it is very improbable that the barycenter (gravity center of the form?) of multiple overlapping forms are at the very same position.

You can test this PR and you'll see that the selection works very well even tested with 3 circles fully inside of each others.

**Comment by Nilvus** [comment]
@TurboGit: if I'm not wrong, this PR should fix so this issue: #8697. If yes, it would be good to link it to your PR to close when this will be merged.

**Comment by elstoc** [comment]
@Nilvus: It's mentioned in the first commit

**Comment by elstoc** [comment]
Seems _mostly_ ok but as it stands I can't access the top control node of this ellipse:

Screenshot_2021-04-19_12-42-48

**Comment by TurboGit** [comment]
> Seems _mostly_ ok but as it stands I can't access the top control node of this ellipse:

Of course you're right ! I just missed your point. So we indeed need to get the minimal distance of the control points too. This will be a bit more CPU angry but should be ok for an interactive algorithm anyway.

**Comment by elstoc** [comment]
> So we indeed need to get the minimal distance of the control points too.

I'm still not sure I see why the centre is the best way to do this. It should be whichever on-screen line I'm closest to since it's the visual reference I have that's closest to my mouse. If my mouse is right over a node (or segment) then node (segment) selection should take precedence. Obviously there will be corner cases where lines are close to each other so perhaps there will need to be some priority order given. Perhaps (1) Node - very close (2) Segment - very close (3) Shape line - rough (3) Feather line - rough.

**Comment by Nilvus** [comment]
> @Nilvus: It's mentioned in the first commit so will auto-close when merged

Didn't check (and so see) that. I just comment as I had seen no linked issues. But if's in, all good!

**Comment by TurboGit** [comment]
Should be ready now!

**Comment by elstoc** [comment]
The scenario mentioned above works better now but it does still feel odd when you move your mouse towards the centre of the inner ellipse and suddenly it selects the circle again.

There also seems to be something a little asymmetrical about the way it works. If I start with my mouse pointer on the lower node of the ellipse and slowly move it upwards, the ellipse remains selected until I get to the very centre, at which point the circle is selected. As I continue to move upwards it's not until I get half way between the centre of the ellipse and the top node, that the selection changes again.

https://user-images.githubusercontent.com/9555491/115253180-0a61ac80-a124-11eb-98ff-5508ec40a885.mp4

**Comment by TurboGit** [comment]
That's because you are at a moment flying over (and closer to the center of the ellipse) the center of the outer circle. The center is important to be able to move this circle so we need to take it into account.

**Comment by TurboGit** [comment]
Of course in you scenario you could move the circle but selecting on the area outside the ellipsis but inside the circle. But again if the circle is fully inside another ellipsis/circle we need to handle the center as a control point.

**Comment by elstoc** [comment]
It's the asymmetry that's the main oddity here. Look at where the cursor changes during the motion.

**Comment by TurboGit** [comment]
I see, a bit strange indeed... No idea about the problem at the moment.

**Comment by elstoc** [comment]
Let's go with it as it is and you can always push a fix later if you work it out.

**Review by elstoc — APPROVED** [review]

**Comment by TurboGit** [comment]
In you case I suppose the center of the circle is a little bit above the one of the ellipsis. So when moving up the closet is the ellipsis. When little bit above the center the closest is the circle and it gets selected. Then moving up, you are closer to the circle center until the closest new match is the ellipsis top control. That should be the explanation for the asymmetry I suppose.

**Comment by elstoc** [comment]
Yes I think you're right. If I move the ellipse slightly I can reverse the behaviour.

**Comment by TurboGit** [comment]
Let's merge now, some more tests on my side. All seems good. Thanks for reviewing/testing @elstoc .

**Comment by s7habo** [comment]
Just tested it. Works great.  Thanks guys!

**Comment by AlicVB** [comment]
@TurboGit : sorry for the delay... just tested, and yes it works great ! There will always be corner cases as the one @elstoc mentioned, but we can't really avoid that. imo, the key point is that now we have a way to do it, even if we need to move the mouse a little bit :)

**Pull request merged**
