### PR TITLE
add shortcuts for rating and colors filters

### LINKED ISSUE #11562: [FR] add shortcuts to the new filtering module
The new filtering module has just land into master.
One point that remains to do is to allow some shortcuts to be set. I've not touch this part at all in order to propose something coherent from the start.
Shortcuts for the "add rule/sort/history" buttons will be straightforward... but what will be difficult here is for the filters themselves, as we can't know in advance which filters will be present or not...

@dterrahe : what is your view on this ?

### PR DESCRIPTION
**Pull request by dterrahe**
fixes #11562

You can visual assign shortcuts to a specific rating or color without using the shortcuts/prefs dialog. Color shortcuts normally toggle selecting the color. To switch to excluding it, change the effect in the shortcuts dialog (click on the widget) to ctrl-toggle.

A rating shortcut will select the lower bound of the range, unless it is already selected, in which case it will toggle the upper bound to max. To select all images, press shift+r (lower bound=rejected) and if _only_ rejecteds are shown, press it again to show rejected -> max. You can switch the _effect_ to _cap_ to change to maximum of the range.

If you have fallbacks enabled, pressing any of the rating shortcuts (for example shift+1) and scrolling up or down increases/decreases the minimum rating. If a midi button with a light is mapped to a rating, it will light up if the rating falls in the selected range. If a midi rotor is mapped, it's light will indicate the minimum of the range (on the x-touch).

### CODE REVIEW

**Comment by AlicVB** [comment]
Thanks for the work !
I've not looked at the code for instance (will do it later)
For a first and very quick test : 
- I would have expected the colorlabels to cycle between their 3 states... do you think it can be done without too much changes ?
- here, although I have all the colorlabels shortcut defined, for rating, I have only shit-r defined by default. That's not a real issue, but I want to be sure it's done on-purpose !

**Comment by AlicVB** [comment]
OK, I think the second point can be ignored, as it seems to be caused by my french keyboard which already need to press shift, in order to reach the numbers...

Some other though : 
- I like the press+scroll like it's implemented in the fall back. Ideally I would like to be able to define 2 shortcuts, 1 for the lower bound (say `j`), the second for the higher (say `k`), and to have `j+scroll` to change the lower bound and `k+scroll`to change the higher bound. And all that without the need to use fallback (like what we have for sliders)... Do you think it's doable ?
- One big advantage of the above proposal, is that this can be extend "for free" to all the other range widgets...

Again, I'm asking, asking... without doing anything ;) So feel free to ignore that if you find the ideas to hard to implement or out-of-scope !

**Comment by dterrahe** [comment]
> * I would have expected the colorlabels to cycle between their 3 states... do you think it can be done without too much changes ?

The shortcut is just replicating the behavior of the color label toggle buttons, so I'm not sure why you would expect them to behave differently. I would rarely use the exclude option, so would prefer the current behavior. If you do decide to change it, please keep in mind that currently I can press shift+F1+F2+F3+F4+F5 (if I had enough fingers) and scroll down and always be sure that the filters are switched off (if fallbacks are enabled). Similarly (but less useful) to enable all of them with scroll up. If you toggle (and possibly scroll, in a loop?) through all three options, I will have to make the filter visible to make sure what its status is.

> `k+scroll`to change the higher bound.

This is already possible but takes a few steps to set up, because you need to assign _scroll up_ and _scroll down_ separately
- switch to visual mapping mode
- hover above rating filter and _k+scroll up_
- click on widget to open shortcuts dialog
- change the _effect_ of the new shortcut to _higher_
- double-click on the shortcut to create a "duplicate"
- _k+scroll down_
- Answer "yes" to creating separate shortcuts for up and down moves
image
- change the effect of the new shortcut to _lower
image

> One big advantage of the above proposal, is that this can be extend "for free" to all the other range widgets...

Imho the better, standard, way to define shortcuts for the _other_ ranges is to have two separate elements, _min_ and _max_ that shortcuts can be visually assigned to by hovering over the left and right entry boxes and that would both have _dt_action_effect_value_. If you assigned _k_ to that, you'd automatically get the standard shortcuts _k+scroll_, _shift+k+scroll_ for larger moves, _ctrl+k+scroll_ for smaller moves (_or_ you can disable fallbacks if you wish) and you could assign shortcuts to jumping to max or min.

**Comment by dterrahe** [comment]
> OK, I think the second point can be ignored, as it seems to be caused by my french keyboard which already need to press shift, in order to reach the numbers...

Those default shortcuts also cause problems for me on Windows, where they get linked to the numeric keypad and are impossible to trigger for the same reason.

I'll remove them. The shift+0 and shift+r shortcuts may not be everyone's preference anyway.

**Comment by AlicVB** [comment]
> The shortcut is just replicating the behavior of the color label toggle buttons

right. Forget this one... shortcut should behave like the Ui, as you say !



> Imho the better, standard, way to define shortcuts for the _other_ ranges is to have two separate elements, _min_ and _max_ that shortcuts can be visually assigned to by hovering over the left and right entry boxes and that would both have _dt_action_effect_value_. If you assigned _k_ to that, you'd automatically get the standard shortcuts _k+scroll_, _shift+k+scroll_ for larger moves, _ctrl+k+scroll_ for smaller moves (_or_ you can disable fallbacks if you wish) and you could assign shortcuts to jumping to max or min.

Sounds great !



> This is already possible but takes a few steps to set up

If we implement the above proposal, don't you think we can also add the min/max elements to rating too ? They won't be reachable directly on the UI, as all the widget areas already correspond to something else, but they would be in the shortcut interface, and would be easier to use than your proposal, imho...

**Comment by dterrahe** [comment]
> If we implement the above proposal, don't you think we can also add the min/max elements to rating too ?

"min" for rating would be duplication, because any of the other elements by default refer to min. "max" would make sense; The higher/lower effects of the other elements could be removed. The "cap" effect would still be useful to directly assign a specific rating as the upper bound. Pressing just a key shortcut (rather than a scroll/move) would directly toggle "-> max" (for the other ratings, it only toggles "-> max" if the current min is the same as the pressed key). max/cap could set the upper bound equal to the lower bound. It normally is, except when the user explicitly has changed it to differ.

**Review by AlicVB — APPROVED** [review]
This last version is great. Code looks good too.
Next step would be to extend that to the other range widgets, as you have proposed, but that can be done in a second step.
At least with that we have no regression with 3.8.1 !

**Review by TurboGit — APPROVED** [review]
Thanks to both of you!

**Comment by dterrahe** [comment]
6. in https://www.merriam-webster.com/dictionary/cap
: an upper limit (as on expenditures) : [CEILING](https://www.merriam-webster.com/dictionary/ceiling)

**Comment by TurboGit** [comment]
> 6. in https://www.merriam-webster.com/dictionary/cap
>        : an upper limit (as on expenditures) : [CEILING](https://www.merriam-webster.com/dictionary/ceiling)

Thanks!

**Pull request merged**
