### PR TITLE
convert navigation zoom dropdown to bauhaus

### LINKED ISSUE #9833: Keyboard Shortcut for "Small" in darktoom [Feature Request]
In darkroom in the top left corner you have the overview where you can select different zoom levels (small, fit, 50%, 100%, 200%, 400%, 800% and 1600%).
Preferences allow you to define shortcuts for zoom close-up, zoom fill, zoom fit, zoom in and zoom out (preferences->views->darkroom).

Would you consider an option to implement a keyboard shortcut to zoom to "small"?

Best regards

### PR DESCRIPTION
**Pull request by dterrahe**
image

Shows a standard tooltip with its function and the shortcuts mapped to it (two have been converted; the others, close-up and in/out don't directly correspond to options in the dropdown.)

Now also allows directly typing a zoom percentage and the navigator itself responds to middle click and mouse scroll by adjusting zoom level as if the center area had been clicked/scrolled. This would benefit from a remapping of ctrl+scroll (as suggested in #13496).

Hopefully the fact that it now looks like a standard (for dt) dropdown addresses some of the issues mentioned in #13383.

Fixes #9833 (a shortcut can be set up for any of the choices in the dropdown by selecting the correct _effect_)

### CODE REVIEW

**Review by TurboGit — CHANGES_REQUESTED** [review]
One little glitch, you cannot scroll on the new combo to select the different zoom levels. It seems that the mouse wheel actions are taken by the navigation window itself.

**Comment by TurboGit** [comment]
Another point is that if the picture is light it is hard to read the text. Maybe we could add some kind of shadow box below the combo? @Nilvus : Your help is certainly needed here.

**Comment by dterrahe** [comment]
> you cannot scroll on the new combo to select the different zoom levels.

It _somewhat_ works for me. If the current zoom level corresponds to one of the fixed percentages in the list or "fit", it will select the correct item in the list (you can see that if you click on it to open it; it will be in the right location). and you can then also scroll up/down. But if you have a "broken" percentage (generated by scrolling or "fill" or "small" or by direct typing), it will show it as xx% (as it did before) and the selected item will be -1. Scrolling will then only get you to the first item, "small", which again will generate a broken percentage and reset the selection to -1. If you scroll fast you can "jump over" the first few items and get to the fixed list.

Let me know if your problem is different.

**Comment by TurboGit** [comment]
My issue is somewhat different I think. Some more data:

1. If I select the say 100 zoom level then I can scroll to change zoom level above without issue, and when at 1600 down to 100, no problem. (speaking for a standard image around 3500 x 5000).
2. When I move down to 50% ok
3. Next scroll and I stop at 52% looks like the "fit" on the image width. That is the navigation window takes the while width of the image.
4. From there I cannot change using scroll, it kinds of jump/stick

The point 2 above will be 30% for a landscape image. Another scroll goes to 15% and it is somehow stuck too.

**Comment by dterrahe** [comment]
> My issue is somewhat different I think

This is exactly what I tried to describe.

**Comment by TurboGit** [comment]
> This is exactly what I tried to describe.

Indeed, reading more carefully... sorry!

**Comment by dterrahe** [comment]
It may be there is a translation issue in French (when you select "fit" does it show "fit" or a percentage?) I can show fill as well, and _maybe_ small, and just hope that people won't somehow find any change objectionable...

**Comment by TurboGit** [comment]
> It may be there is a translation issue in French (when you select "fit" does it show "fit" or a percentage?)

I did my test with the English UI when I reported the issue.

When I select `fit` it shows `fit` also in French.

**Comment by dterrahe** [comment]
fixed I think.

@prokoudine would be great to get some feedback on whether this is an improvement at all. I've tried to at least improve (not resolve, I know) all the issues mentioned in https://github.com/darktable-org/darktable/issues/13383. I know you've had problems compiling PRs, but I hope you can sympathize with the challenge of working in the dark again.

**Comment by TurboGit** [comment]
> fixed I think.

Works on my side now, thanks!

**Comment by Nilvus** [comment]
> Another point is that if the picture is light it is hard to read the text. Maybe we could add some kind of shadow box below the combo? @Nilvus : Your help is certainly needed here.

That the remaining issue indeed. What's bad is that it's much better without shadow when picture is not light behind. But, we can't set text color regarding what's behind. I've began to test some shadow but I will not have time until sunday to work on more.

@dterrahe: could you add for just that combo a CSS name (not id), I suggest:

`#nav-zoom`

@TurboGit: after that add, I think it's better to wait my CSS proposal (as a diff on that PR). I'm quite sure that if we merge that before fixing that, we will quickly have an issue opened. No need to manage that. As soon as I can, I will provide a proposal with the diff here.

Is this ok for both of you?

**Comment by Nilvus** [comment]
Oh and a really great improvement on navigation module. Great work @dterrahe! Thanks!

**Comment by dterrahe** [comment]
> could you add for just that combo a CSS name (not id)

I'm not 100% sure I know exactly what you want here, so it might be better for you to add that yourself in your PR? The widget is created in gui_init in this PR so you can set anything on `d->zoom` after the call to `DT_BAUHAUS_COMBOBOX_NEW_FULL`.

**Review by TurboGit — APPROVED** [review]
Looks good, I'll merge now.

@Nilvus : I'll help you if needed for the widget name.

**Comment by Nilvus** [comment]
I know how to add widget name.

As I've said previously, I don't think that is a good idea to have merge this this soon. We deal with quite too many issues and as I will not be able to do CSS part, I'm quite sure we will have an issue for not visible text before I do CSS part... Waiting just 2 or 3 days would have been better to avoid more things to deal with as we have time... But now it's done...

**Comment by prokoudine** [comment]
> @prokoudine would be great to get some feedback on whether this is an improvement at all.

It definitely is!

**Comment by Nilvus** [comment]
@TurboGit, @dterrahe and @prokoudine: this new menu is not visible (as I've noticed previously) on image with bright background on bottom right. I've tried some CSS settings to find a suitable way and (as expected) it's quite tricky. If I made it clearly visible on bright background, then it become too bright on darker background.

By now, I've found those settings that are some sort of good compromise (even if I'm not completely satisfied by those ones):

```
.dt_bauhaus.right
{
  background-color: alpha(@grey_60, 0.25);
  color: @graph_fg_active;
  border-top-left-radius: 0.21em;
  margin: 0;
}

.dt_bauhaus.right:hover
{
  background-color: alpha(@button_hover_bg, 0.5);
}
```

I will made some tests but would be good if you can test them and put feedback (on bright background, of course, menu is not completely visible but better than actual master and allow not have too bright menu on darker background).

Another option: set a full background to have always same display but this would hide part of the image behind and remove actual fade in image effect.

Your view on that and/or any other idea is welcomed to help me find the best way here.

**Comment by dterrahe** [comment]
tbh it doesn't bother me too much. With your changes it is easier to see where to aim if you know you want to click on the dropdown somewhere in that corner, so for me that's good enough. If you don't _know_ there is a dropdown and your _first_ image is so overexposed that you can't see anything and discoverability is zero, your biggest problem is not the zoom level anyway. To know the _current_ zoom level, I can more or less deduce from the size of the shrunken area in the navigator, so... And somebody who _always_ wants to be able to read the zoom level, they can adjust the aspect ratio of the navigator so that most of the time the dropdown isn't on top of the image.

**Comment by Nilvus** [comment]
Thanks @dterrahe for your feedback. Of course, when talking about bright images, I do not talk about overexposed ones (you are right about those that discoverability would not be the issue there) but bright images like ones with snow for example. Anyway, I test my changes a little more on my side and will then propose a PR.

That new menu you made is far way better than old one. Minor one but really great UI improvement.

**Pull request merged**
