### PR TITLE
RFC: move filmic graph to within the notebook to save space

### PR DESCRIPTION
**Pull request by TurboGit**
Proposed by @dterrahe, to be discussed if something we want to merge or not.

The new UI is:

image

image

image

image

image

### CODE REVIEW

**Comment by elstoc** [comment]
Given the size of other modules, I'm not really that bothered about saving space. I'm already used to the size of _color balance rgb_ and _diffuse or sharpen_ and have always worked with just one module at a time (or even without modules expanded at all) because it's easier anyway. I don't particularly _mind_ the altered view (I don't know if it's better or worse), but I'm not sure I see the point.

**Comment by ralfbrown** [comment]
I don't feel strongly either way - without a mask (which I've never used on filmic), the vertical size simply isn't an issue.

**Comment by jenshannoschwalm** [comment]
I would like this new UI. Only show the graph where appropriate would be my argument.

**Comment by MStraeten** [comment]
I opt for the old layout for ui consistency: tone equalizer, color equalizer also has the graph in top of the sliders.
And btw: even in hardware a display of values is seldom below sliders…

**Comment by Donatzsky** [comment]
I vote to keep the current/old layout. This change seems a little pointless to me. Reconstruct and options are the only two tabs where this will save space, but they are also not that commonly used I suspect, so the actual space savings are minimal. And, like @MStraeten says, having the graph below would be both inconsistent and unconventional.

**Comment by TurboGit** [comment]
Ok, clearly this does toward keeping current GUI. I was also for this. Let's close. Thanks all for commenting.

**Pull request closed without merging**
