### PR TITLE
Drawn masks hints for feathering mode and opacity

### PR DESCRIPTION
**Pull request by moy**
The first patch is really important IMHO. The second fixes a minor inconsistency I found while testing the first one.

### CODE REVIEW

**Comment by upegelow** [comment]
Good point. However, I think we are in string freeze for 2.2.0 so we can only merge after the release.

**Comment by LebedevRI** [comment]
No we are not in a string freeze, yet :)

**Comment by LebedevRI** [comment]
No, we are **NOT** in a string freeze, _yet_. :)

**Comment by LebedevRI** [comment]
@moy thank you.
Please do send more fixes like this, before we go into string freeze.

**Comment by moy** [comment]
Thanks for merging. You should write more buggy software if you want me to send more patches ;-).

**Comment by LebedevRI** [comment]
If you want buggy, you have certainly added the tooltip to the correct area of dt code :(

**Pull request merged**
