### PR TITLE
import: on refresh exif don't update rating if ignore exif rating set

### LINKED ISSUE #8081: metadata 'refresh exif' overwrites manual rating
in the import dialog there's an option to ignore the rating contained in the exif data, since these are set to 0 by default for some cameras if no rating is set in camera.
When refreshing exif data (e.g. after an update for supported metatdata) the rating is also refreshed so the darktable rating is overwritten.

**Expected behavior**
alternative 1: the exif rating is ignored when refreshing exif data
alternative 2: the behaviour is customizable via a preference

**Platform (please complete the following information):**
 - Darktable Version: darktable-3.5.0+941~g17138775d
 - OS: osx

### PR DESCRIPTION
**Pull request by phweyland**
fixes #8081

### CODE REVIEW

**Comment by MStraeten** [comment]
hmm, this resets it to the default import rating. but since the rating might be changed imho its more valuable to keep the manual set rating by default.

**Comment by phweyland** [comment]
> this resets it to the default import rating

Only is if you don't have any xmp file, right ? Otherwise the rating in xmp should have priority. Could you confirm this ?

But you are right, "refresh exif" is not an import.

**Comment by phweyland** [comment]
Should work as commented now.

**Comment by MStraeten** [comment]
confirmed, it's fine now

**Review by TurboGit — APPROVED** [review]
Thanks !

**Pull request merged**
