### PR TITLE
iop_layouts : fix module order in presets manager

### LINKED ISSUE #6475: Module order in the new presets / manage presets / manage modules layout section.
I just noticed the new and improved *presets* -> *manage preset* -> *manage modules layout*, which is a very nice improvement indeed!

I do have a request though:

**Is your feature request related to a problem? Please describe.**

Saying it is a problem is going a bit far but I find it somewhat annoying that the module order shown in the groups are completely random.

**Describe the solution you'd like**

Being able to choose between the _pipeline order_ or _alphabetically_ would be nice.

If only one can be implemented: The _pipeline order_, as is the current order in 3.2.1, would be be my choice.

Anyway: thanks for the all the work and effort that's being put into darktable. Much appreciated!

### LINKED ISSUE #6514: Darktable crashes when going from darktable to lighttable after changing the modules list
**Describe the bug**

Darktable crashes after I add a module in one of the groups of "manage module layouts", when I return to lighttable. All development done is gone. I can reproduce this consistently.

**To Reproduce**

0. Make an editable layout; default_1 as a duplicate of default.
1. Double click on a photo
2. Go to "manage module layouts"
3. Click on default_1, add a module to the effects group
4. close the "manage module layouts" window, double click on the image to return to lighttable.
5. Hangup, sometimes a corrupted view in lighttable, segmentation fault

**Expected behavior**
Browsing images in lighttable, thumbnail updates, development is saved

**Screenshots**
Screenshot from 2020-10-12 18-47-46

**Platform (please complete the following information):**
 - Darktable Version: a1f80bf30bec45be7e7545898ee911f54a7509ed
 - OS: Arch Linux
 - OpenCL activated
 - GPUs: GeForce GTX 1070 w/ 455.28, Radeon RX Vega 56 (DRM 3.38.0; 5.8.14-arch1-1, LLVM 10.0.1)

**Additional context**

Installed from https://aur.archlinux.org/packages/darktable-git/

[dtdbg.log](https://github.com/darktable-org/darktable/files/5366398/dtdbg.log)

### PR DESCRIPTION
**Pull request by AlicVB**
this fix #6475

Edit :  added a new commit which should fix #6514 and also the second part of #6475 if the "add module" popup is shown
Edit2 : added fix to not show multiple instance or hidden modules in the list

### CODE REVIEW

**Comment by trougnouf** [comment]
That does seem to resolve #6514, thank you ! :)
I'm staying on this branch until it gets merged, will update if there are unusual crashes.

**Comment by trougnouf** [comment]
Some minor details I've noticed:
* If a module is duplicated in the current development, then it appears twice in the preset manager and removing one of them removes both. (This confused me a bit because I didn't realize I had the module activated twice so I had no clue why this happened)
* "default", "all modules", and their duplicates contain modules that cannot appear in the final list (and whose inclusion or occlusion doesn't seem to make a difference), like "raw overexposed" and "overexposed". That is not the case with the other presets.

**Comment by AlicVB** [comment]
@trougnouf : fixed an fixed :) thanks for the tests !

**Comment by TurboGit** [comment]
I'm merging that now, working on my side. Thanks.

**Pull request merged**
