### PR TITLE
fix ignore Exif rating on import

### LINKED ISSUE #13286: import: ignore Exif rating = TRUE is ignored for raw files containing XMP.xmp.Rating
during import 'ignore Exif rating = TRUE ' is ignored for raw files containing XMP.xmp.Rating so during import the custom set 'initial rating' value  is ignored:
image 

**To Reproduce**
1. set "add to library" preferences:  check 'ignore exif rating' & set initial rating to 2 (some cameras uses a default rating 1) 
2. add cr3 file to library (e.g. https://raw.pixls.us/getfile.php/4662/nice/Canon%20-%20Canon%20EOS%20R6%20-%203:2.CR3)
3. check initial rating: 0 stars

some further checks:
Canon 5DmIV rating **not ok** (contains XMP.xmp.Rating 0): https://raw.pixls.us/getfile.php/983/nice/Canon%20-%20EOS%205D%20Mark%20IV%20-%20RAW%20(3:2).CR2
Nikon Z6 rating **not ok** (contains XMP.xmp.Rating 0): https://raw.pixls.us/getfile.php/3581/nice/Nikon%20-%20Z%206%20-%2014bit%20compressed%20(3:2).NEF
Nikon D7200 rating **ok** (doesn't contain XMP.xmp.Rating): https://raw.pixls.us/getfile.php/832/nice/Nikon%20-%20D7200%20-%2014bit%20compressed%20(Lossless)%20(3:2).NEF)

**Which commit introduced the error**
need to bisect - checked my older builds: issue was introduced between 20.10. (darktable-4.1.0+719\~g9ec4d3dce) and 06.11. (darktable-4.1.0+860\~g64a61e52e)

**Platform**
* darktable version : > darktable-4.1.0+860~g64a61e52e
* OS                : OSx

### PR DESCRIPTION
**Pull request by zisoft**
This PR fixes #13286

Bildschirm­foto 2023-01-18 um 19 01 57

The _ignore EXIF rating_ checkbox is handled for `XMP.xmp.Rating` too and with this change it works as I would expect it to work:

If _ignore EXIF rating_ is checked, the rating gets overridden by the import settings (even if there is an xmp file with a rating besides the image file).

So maybe the checkbox should be renamed as well: "ignore Exif/XMP rating" ?

What do you think?

### CODE REVIEW

**Comment by TurboGit** [comment]
@zisoft : Thanks for contributing to dt, if I'm not mistaken you're new here.

> So maybe the checkbox should be renamed as well: "ignore Exif/XMP rating" ?

Or maybe `ignore embedded rating`. I find XMP confusing as of course we don't want to ignore the rating read from an existing XMP. BTW, have you double checked that if an XMP is present the rating is properly read and set?

**Comment by zisoft** [comment]
To not be misunderstood here, this is the way it works in the PR:

- If the checkbox is checked, the rating from the image file or from the xmp file is ignored.
- If the checkbox is not checked, the rating is read from the image/xmp file.

This is the way I would expect it. I want to ignore the ratings and make that clear by checking the box.

I have checked it with my Canon cr2 files with and without accompanying xmp files.

**Comment by TurboGit** [comment]
> * If the checkbox is checked, the rating from the image file or from the xmp file is ignored.

Hum... not sure it is a good idea. This is very dangerous as say you export a folder of hundreds of images and you forgot that this option is checked... You've then lost all rating as the image have been imported and XMP reset. This option has been designed to ignore only the rating embedded into the RAW/Jpeg images (from camera). It is sad to see some camera `XMP.xmp.Rating` instead of `Exif.image.Rating`.

What to do?

Maybe ignore `XMP.xmp.Rating` if the option is set only when importing from camera. That said, not sure how easy to do this is.

If you have another proposal do not hesitate. But we really want to say ultra-safe regarding this.

**Comment by zisoft** [comment]
> If you have another proposal do not hesitate. But we really want to say ultra-safe regarding this.

No problem at all :-)

I know its a difficult topic. Maybe others can give their opinion too.

**Comment by TurboGit** [comment]
Just a side note, do not merge master into a topic branch. You should rebase it on top of master and force push your topic branch here. TIA.

**Comment by zisoft** [comment]
yes, my fault. Sorry.

**Comment by zisoft** [comment]
I have now changed the logic as follows:

- XMP files have priority. If any XMP file(s) is present, the rating is taken from there. This also works with multiple XMP files (duplicates) with different ratings
- If no XMP file is present:
  - If the checkbox _ignore EXIF rating_ is checked, override any rating from the image file
  - if the checkbox _ignore EXIF rating_ is NOT checked, take the rating from the image file

I have tested this with my Canon CR2 files and any possible combination of xmp files (from darktable as well as from other software).

I cannot see any reason why this should not work with image files from other camera vendors, but please test.

**Comment by Nilvus** [comment]
Your last proposal @zisoft seems safe, and much better than your first proposal. Thanks.

**Comment by Nilvus** [comment]
Oh, and why not updating now "Ignore EXIF rating" to Ignore embedded rating"? Would be better to suit that PR (and will probably be more understandable for users who do not know what is EXIF or XMP).

**Comment by TurboGit** [comment]
> Oh, and why not updating now "Ignore EXIF rating" to Ignore embedded rating"?

That was my initial proposal, but the last one is really only for EXIF as it was before. So maybe using EXIF is ok, I suppose this is a well know term for photographs.

**Comment by Nilvus** [comment]
> > Oh, and why not updating now "Ignore EXIF rating" to Ignore embedded rating"?
> 
> That was my initial proposal, but the last one is really only for EXIF as it was before. So maybe using EXIF is ok, I suppose this is a well know term for photographs.

On what I understand, this is not only Exif but also XMP **embedded** in the image (if there's no XMP file). So your initial proposal remains adapted to me.

**Comment by gi-man** [comment]
> I have now changed the logic as follows:
> 
> * XMP files have priority. If any XMP file(s) is present, the rating is taken from there. This also works with multiple XMP files (duplicates) with different ratings
> * If no XMP file is present:
>   
>   * If the checkbox _ignore EXIF rating_ is checked, override any rating from the image file
>   * if the checkbox _ignore EXIF rating_ is NOT checked, take the rating from the image file
> 
> I have tested this with my Canon CR2 files and any possible combination of xmp files (from darktable as well as from other software).
> 
> I cannot see any reason why this should not work with image files from other camera vendors, but please test.

I cant build/test at the moment. What happens with dng and/or jpg import?

**Review by TurboGit — APPROVED** [review]
Works for me. One corner case but nothing to do. If one decide to only write XMP at edit, the following scenario does change the rating:
- Copy & Import with a rating of 2
- Remove pictures from db
- Change rating to 5
- Import them back, all rating are set to 5 if ignore exif rating is checked

But there is no magic, user has decided to not write XMP.

**Comment by TurboGit** [comment]
@zisoft : I have added an entry into the RELEASE_NOTES. Just in case you didn't saw my message in the dev mailing list I have asked the devs to provide a text entry for the RELEASE_NOTES for all integrated changes to help me keep the RELEASE_NOTES up to date and allow our users to better test the changes.

**Comment by zisoft** [comment]
@TurboGit I missed that indeed, thank you for the hint.
I have now subscribed to the dev mailing list.

**Pull request merged**
