### PR TITLE
Show modules with a transition

### PR DESCRIPTION
**Pull request by Sacules**
This PR improves the UX of the modules by showing a simple transition when toggling them. [Here's a demo](https://imgur.com/l13mxeK).

I think what's missing might be an option to let the user configure the duration of the transitions, what do you think?

### CODE REVIEW

**Comment by Nilvus** [comment]
Thanks for that, will test it soon.

About an option to let the user configure the duration, we discussed multiple times in the past about settings darktable had. It's good to have a software that can be customized but we were agree to also avoid having too much. And we already have quite a lot options. We are on a time now that we need to be careful to not overwhelm them. And that one it's not the more useful to add.

Said that, we found a compromise to have 2 sort of options:
- standard ones : those on the UI
- expert/advanced mode : those in darktablerc file

So, It's a NO for me for first option but a YES in darktablerc file.

**Comment by elstoc** [comment]
> I think what's missing might be an option to let the user configure the duration of the transitions

I agree - this will be a feature that people either love or hate, so the speed should be configurable somewhere (and setting it to zero should disable the animation). I don't hate the number of options like some do so I'd be ok with it in the preferences dialog.

**Comment by TurboGit** [comment]
Yep, I fully agree with @elstoc, an option is welcome here. TIA.

**Review by TurboGit — COMMENTED** [review]
Tested and it looks very good to me. Found that each time you go from Lighttable to Darkroom you get on the console:

```
(darktable:333574): GLib-GObject-WARNING **: 17:45:03.527: invalid cast from 'GtkEventBox' to 'GtkScrolledWindow'

(darktable:333574): Gtk-CRITICAL **: 17:45:03.527: gtk_scrolled_window_get_vadjustment: assertion 'GTK_IS_SCROLLED_WINDOW (scrolled_window)' failed

(darktable:333574): Gtk-CRITICAL **: 17:45:03.527: gtk_adjustment_set_value: assertion 'GTK_IS_ADJUSTMENT (adjustment)' failed
```
For the pref I would choose a int between 0 to 100 to represent a transition speed in 1/100 of seconds. That is 0 to deactivate the feature and 100 to have transition of 1s. Would that work for you?

**Comment by Sacules** [comment]
Fixed those console errors.

> For the pref I would choose a int between 0 to 100 to represent a transition speed in 1/100 of seconds. That is 0 to deactivate the feature and 100 to have transition of 1s. Would that work for you?

I was thinking of just letting the user set the speed in ms, from 0 to an arbitrary limit, like 1000ms as you mentioned. I feel this might be a bit more intuitive than having to mentally do the conversion from a number between 1 to 100 to the actual value, but that's just me, I'm no designer tbh. If we add the option on the UI, I had in mind an input with a `ms` label next to it, or maybe a slider instead?

**Comment by elstoc** [comment]
You don't have that sort of control if you want to put the option in the preferences dialog, unless you put it in the general tab. Most options are defined in `data/darktableconfig.xml.in` An integer value will automatically use a spinbutton control and having it jump by 1ms each time you click might be a bit painful (I'm not sure we can define step size).

**Comment by TurboGit** [comment]
> I was thinking of just letting the user set the speed in ms, from 0 to an arbitrary limit, like 1000ms as you mentioned.

Works for me.

**Comment by Sacules** [comment]
Alright, fixed a small bug, and also added the option to the miscellaneous/interface section, let me know if that's fine.

**Comment by TurboGit** [comment]
> So, It's a NO for me for first option but a YES in darktablerc file.

Fact is that expert mode is for expert but this is quite general settings that I feel many user's will like to set or experiment with.

What we may do at some point is to have an expert mode to show some options only when activated. There is probably many options like this one that we could have only displayed in expert mode. It will also make dt in a better position, having to say "edit darktablerc manually" is not really user friendly. It was ok and a good workaround, but I fell that dt at this point has reached a status where we want to do better.

If you agree I can implement this expert mode. What do you think?

**Comment by elstoc** [comment]
> If you agree I can implement this expert mode

I think there might be some strong opinions against this (based on previous discussions in IRC) so it might be worth raising an issue for discussion first.

**Comment by TurboGit** [comment]
One issue:
- unselect all module's group in darktable (or select a group where there is many modules and so a scrollbar is displayed)
- select a module, it is opened and then scrolled up (looks like the amount of scroll depends on the size of the module when expanded)

(just found out that this is also the case in current master, but looks less weird because it is instantaneous).

**Comment by TurboGit** [comment]
> I think there might be some strong opinions against this (based on previous discussions in IRC)

You mean some people prefer:

`emacs ~/.config/darktable/darktablerc`

To anything else we could propose? This is quite common those days, like the about:config for example.

Preferring emacs to a UI proposed way of hiding preferences seems like there is only computer scientist using dt :)

**Comment by elstoc** [comment]
Some people prefer `vim ~/.config/darktable/darktablerc` too :)

I'm just saying it might be controversial but I suppose it all depends on the actual implementation. For something like this, though, I think it's worth raising an issue because there are probably a number of ways to do it. If nothing else, you might at least get some alternative ideas for the implementation.

**Comment by TurboGit** [comment]
> Some people prefer `vim ~/.config/darktable/darktablerc` too :)

How is that possible :)

Ok, I'll raise an issue for discussion. And note that to my point of view the discussion on IRC are somehow irrelevant to the project as I'm not on IRC as probably some others devs.

**Comment by elstoc** [comment]
> And note that to my point of view the discussion on IRC are somehow irrelevant to the project as I'm not on IRC as probably some others devs.

Sure, I just mention it as an indication that you might get some comments. Better this happens before you do all the dev.

**Comment by Sacules** [comment]
> One issue:
> 
>     * unselect all module's group in darktable (or select a group where there is many modules and so a scrollbar is displayed)
> 
>     * select a module, it is opened and then scrolled up (looks like the amount of scroll depends on the size of the module when expanded)
> 
> 
> (just found out that this is also the case in current master, but looks less weird because it is instantaneous).

Yeah, this only happens when `scroll to processing modules when expanded/collapsed` is enabled. Since the scroll depends on the expanded module size, it can only happen once it has been fully revealed. I tried to look for a way to make the scroll smooth instead of instantaneous, but couldn't find anything within GTK.

**Comment by Nilvus** [comment]
> @Nilvus :
> 
> > So, It's a NO for me for first option but a YES in darktablerc file.
> 
> Fact is that expert mode is for expert but this is quite general settings that I feel many user's will like to set or experiment with.
> 
> What we may do at some point is to have an expert mode to show some options only when activated. There is probably many options like this one that we could have only displayed in expert mode. It will also make dt in a better position, having to say "edit darktablerc manually" is not really user friendly. It was ok and a good workaround, but I fell that dt at this point has reached a status where we want to do better.
> 
> If you agree I can implement this expert mode. What do you think?

I had answered with what we discussed already and that we have a lot of options now. But yes, I agree with you here. The only thing is I'm not sure it's the more useful option to add for standard user even if I understand that this will be good. Personally, I don't care if we have such option or not. it's indeed probably better to have it visible and @Sacules option to add it in misc tab is the best place to put it in in darktable settings.

About having an expert mode, I agree that this will be better and a lot more user friendly than darktablerc file. Of course. I completely agree to have one but it depends how we implement it AND we need to take care also about what @elstoc answer to that here. I see other difficulties but will continue in #11420 issue you opened.

**Comment by elstoc** [comment]
> unselect all module's group in darktable (or select a group where there is many modules and so a scrollbar is displayed)
> select a module, it is opened and then scrolled up (looks like the amount of scroll depends on the size of the module when expanded)

I agree this looks odd - enough so that I might choose to disable the transition animation. At least a partial solution would be to only scroll a module if it's not completely visible after being expanded, and then only scroll it such that it is all visible (which might only scroll it up a small amount). Currently it always tries to push the module to the top of the UI, which is often unnecessary.

**Comment by elstoc** [comment]
> That's odd, I'm not getting that error, does it happen every single time you launch?

Yes. I tried rebasing and still got it.

**Comment by TurboGit** [comment]
> When you expand negadoctor the module scrolls off the screen.

Exactly what I was about to say and also the move is fast and seems unexpected. Again it was "mostly" ok before because all was instantaneous, now you see a transition for the module to open and then this fast move to the top which seems just a bug and find very annoying.

I would try to scroll only if the bottom of the module is out of the panel otherwise I'll do nothing. I kind of remember that we have a code to ensure that the module is visible and we trigger the move. This routine has to be changed to take into account the height of the panel and the module. Maybe not easy, but I don't feel the behavior in this PR is ok for integration.

**Comment by Sacules** [comment]
> I would try to scroll only if the bottom of the module is out of the panel otherwise I'll do nothing.

Yeah, after trying it a bit more it does feel off, so I'll try to do that instead. I'm a bit busy this week, so it's gonna take me a little while.

**Comment by Nilvus** [comment]
Much better. Just 2 things:
- 150ms seems better for me than 250ms. 250ms make the behavior a little weird for me.
- more important: when we open multiples modules, and so scrollbar appear, the behavior is rough. And it's really something to improve. I think something smoother, maybe by adding what this PR add, also in panels scrollbars (only that and only when modules are opened and scrollbar appear). Hope I'm clear here.

**Comment by Sacules** [comment]
>     * more important: when we open multiples modules, and so scrollbar appear, the behavior is rough. And it's really something to improve. I think something smoother, maybe by adding what this PR add, also in panels scrollbars (only that and only when modules are opened and scrollbar appear). Hope I'm clear here.

You mean that the scrollbar should appear with a transition instead of just popping in? In that case it should be easy to add, I'll give it a try

**Comment by Nilvus** [comment]
> You mean that the scrollbar should appear with a transition instead of just popping in? In that case it should be easy to add, I'll give it a try

Probably something like that

**Comment by Sacules** [comment]
Ok I've given it a try it and doesn't seem as easy as I thought it would haha. Seems there are 2 ways to solve it. Either via CSS, which i'm looking into, or replace the ScrolledWindow with a custom widget, which might or might not be worth the effort just for a small transition.

**Comment by elstoc** [comment]
On the plus side, you have another six months to get it right now :)

**Comment by dterrahe** [comment]
I have submitted #12637 which started out with a different goal; to make sure that expanding modules are fully visible (by moving them up if needed) even when they are further expanded by adding blending masks or opening a collapsible section. After making the move smooth (using gtk_widget_add_tick_callback), adding revealers, like are used here, to make the expansion itself smooth as well was a logical next step. And then adding those to the blending sections too.

`scroll_to_module` is supported in a different, smooth, way (fixing a bug in master when switching between instances of the same module or other equally tall ones) so that needs careful testing by those who actually use it. 

It could probably use a wider audience at this point.

**Comment by dterrahe** [comment]
Now that #12637 has been merged, I hope nobody minds if I close this PR, since this functionality is also included there.

Thanks again @Sacules for the idea!

**Pull request closed without merging**
