### PR TITLE
map - images grouping to speed up display

### PR DESCRIPTION
**Pull request by phweyland**
Today map view displays each image even if hidden by others. To keep the display time acceptable the user can limit the number of images, 100 is good, 1000 is already a burden.

So this PR to group the images by proximity and display only one image per group. Additionally displays the number of images by group.

image

Still work in progress because:
- when ones moves to map, the map is displayed 5 times. There may be a bit of mess on current signaling to be cleaned up.
- relationship between geo-coordinates and pixels is not stable (in particular when a border of the map appears on the screen)

### CODE REVIEW

**Comment by TurboGit** [comment]
Yeah! Thanks @phweyland for polishing the map view. Looks promising.

**Comment by phweyland** [comment]
@TurboGit 
I'm quite happy with the speed (with 30.000 geotagged images / 50.000) despite the fact it remains a lot a useless triggering (maybe due to osm-gps-map internals).
There are still some old issues I haven't been able to fix so far (missing tiles, undo, ...) 

But I think it deserves your review and certainly some more tests.
Thanks

**Comment by TurboGit** [comment]
Looks nice and way better than current implementation.

I've always found the vignette on the map too small to be very useful. I would try to double the size and eventually group them when they are a bit farther to avoid all thumbs to overlap. Not sure how this will render... You may find something better.

**Comment by TurboGit** [comment]
BTW, it looks like your thumbs are bigger than mine on your screenshot above, see mine:

image

**Comment by phweyland** [comment]
> BTW, it looks like your thumbs are bigger than mine on your screenshot above, see mine:

I've made a screenshot with a small window (not full screen).


> I've always found the vignette on the map too small to be very useful.

I agree the size is a bit too small. Currently the thumb size is fixed. It could be possible to make it proportional to screen size ? Or to make it configurable ?

**Comment by phweyland** [comment]
> and eventually group them when they are a bit farther to avoid all thumbs to overlap.

As done the group size is half the thumb size. This allows a maximum overlap of half a thumbnail. We could avoid completely the overlap making the group size equal to thumb size. Or make the ratio configurable ?

**Comment by TurboGit** [comment]
Proportional to screen size (taking into account DPI) seems like the best option to avoid another preference.

**Comment by phweyland** [comment]
> Proportional to screen size (taking into account DPI)

I locate the DPI things. Is the screen size (or factor) already known in dt ? Just to be sure before using something like gdk_window_get_scale_factor().

**Comment by TurboGit** [comment]
I think DT_PIXEL_APPLY_DPI should work in that case.

**Comment by phweyland** [comment]
> I think DT_PIXEL_APPLY_DPI should work in that case.

Probably not enough, because already applied (line 873)...

**Comment by phweyland** [comment]
Maybe a bit too large now ?

**Comment by phweyland** [comment]
BTW white count corresponds to images exactly at the same location, yellow otherwise.

**Comment by TurboGit** [comment]
@phweyland : Large ok but maybe not too much but the numbers are really too small!

It seems that the thumbs have a black border, right? Maybe add a white one to ensure proper visibility on all backgrounds?

**Comment by TurboGit** [comment]
What would be nice is to be able to right+click (or ctrl+click) on a thumbs and be able to go to the corresponding filmstrip in the "collection filter" module. More interactivity with the map would be nice I think.

**Comment by phweyland** [comment]
> Large ok but maybe not too much but the numbers are really too small!

So between 64 and 128 for the thumbs ? What would be the right value ?
About the font size, I've taken the same as in the timeline. Font size = 10. Should 12 the right size ?

> Maybe add a white one to ensure proper visibility on all backgrounds?

I don't really see the benefit here.


> at would be nice is to be able to right+click (or ctrl+click) on a thumbs and be able to go to the corresponding filmstrip in the "collection filter" module. More interactivity with the map would be nice I think.

100% agreed. It was my intention to have another PR to create "location" collections based on the geotag. And one of the way to create a new one can be as you say.

**Comment by phweyland** [comment]
> > Maybe add a white one to ensure proper visibility on all backgrounds?
> 
> I don't really see the benefit here.

We could add a white border between image and black border to highlight a group. And remove the number when the image is alone.

For the next 10 days I may not have access to my keyboard....
There is no hurry, but I think there are a lot of small adjustments still to do, which could be done with other PRs.

**Comment by TurboGit** [comment]
> About the font size, I've taken the same as in the timeline. Font size = 10. Should 12 the right size ?

Yes, maybe 12 will be better, 10 is really too small to be read easily.

> There is no hurry, but I think there are a lot of small adjustments still to do, which could be done with other PRs.

Agreed, let's change the font and I'll review again and merge if all ok. This is already a nice improvement no need to hold it longer.

**Comment by phweyland** [comment]
Font-size on thumbnails set to 12.

**Comment by TurboGit** [comment]
Thanks Philippe ! Looks good now to me.

**Pull request merged**
