### PR TITLE
Travis CI: build usermanual

### PR DESCRIPTION
**Pull request by LebedevRI**
As a pr to not break build.

### CODE REVIEW

**Comment by LebedevRI** [comment]
Huuh, why does it try to fetch `http://docbook.sourceforge.net/release/xsl/*`

**Comment by LebedevRI** [comment]
@upegelow 
am i missing some packages? 
why does it try to get xsl from the internet?

https://travis-ci.org/darktable-org/darktable/jobs/168018281

**Comment by upegelow** [comment]
I think that's a typical way of handling docbook stylesheets (though I 
didn't set this up myself).

 From the docbook stylesheet manual:

You do not actually have to download the stylesheet files to use them. 
Most XSL processors, if given a URL instead of a filename, will fetch 
the stylesheet over the Internet. However, because the DocBook 
stylesheets are big and use many file modules, this process uses a lot 
of network bandwidth and greatly slows down the processing of your 
documents. But it can be used in a pinch when you are on a machine that 
does not have the stylesheets installed. For example:

xsltproc  \
    http://docbook.sourceforge.net/release/xsl/current/html/docbook.xsl \
    myfile.xml

Am 16.10.2016 um 11:42 schrieb Roman Lebedev:
> @upegelow <https://github.com/upegelow>
> am i missing some packages?
> why does it try to get xsl from the internet?
>

**Comment by LebedevRI** [comment]
Hmm, well there is [docbook-xsl](https://tracker.debian.org/pkg/docbook-xsl) let's see what happens if i add them into dockerimage..

**Comment by LebedevRI** [comment]
@upegelow yep, adding `docbook-xsl` fixed it, apparently.

**Comment by LebedevRI** [comment]
It works, but what i don't like is that the build process just stalls for a few minutes on
```
Built target target_media_images
```

**Comment by LebedevRI** [comment]
Update: it seems the command that takes this long is
```
[292/294] cd /build/darktable/doc/usermanual && xsltproc --xinclude --output /build/darktable-build/doc/usermanual/darktable_profile.xml xsl/darktable_profile.xsl darktable.xml
```
Not exactly surprising though :(

**Comment by LebedevRI** [comment]
@upegelow before i even try to dig it any further, there isn't newer, more modern `xsltproc` that is fast?

**Comment by peterbud** [comment]
@LebedevRI  when I built the usermanual it was also extremely slow. The whole darktable build takes 3-4 minutes on my machine, and the usermanual took alone 30 mins+(!) to build. the xsltproc was using only 1% of the CPU, so I have no clue what it was doing. And yes, it was constantly downloading the stylesheets from the internet.

**Comment by LebedevRI** [comment]
@peterbud for stylesheets, install `docbook-xsl`.

PS: unless we manage to bring `time make darktable-usermanual` to under 5 minutes (3-4 min is ok), there won't be CI for usermanual.

**Comment by upegelow** [comment]
@LebedevRI
Unfortunately no idea how to make xsltproc faster. As an alternative to 
actually building the manual we could test the sources for consistency 
with xmllint:

xmllint --xinclude --noout --postvalid darktable.xml

That's even more picky than xsltproc.

**Comment by LebedevRI** [comment]
Hm, yes, that could work for now.
But the final point of this pr is to build the usermanual, so that the current version (git master) can be automatically uploaded somewhere on dt.org

**Comment by LebedevRI** [comment]
Ok, validity check for usermanual is good-enough for now i'd say :)

**Comment by LebedevRI** [comment]
Does not warn about missing files referenced by `<graphic fileref="name.jpg" />` :(

**Pull request merged**
