### PR TITLE
change color contrast labels so that there's less confusion

### LINKED ISSUE #6376: Color contrast module grading colors (cosmetic).
**Feature request**
The sliders of green vs magenta and blue vs yellow are without their respective colors.
It is just a cosmetic thing. I don't know how the scales are projected, because now the marker is more at the left and the scale goes from 0 to 5.

**Solution**
Would be great a solution cretae a grading colors between them.

**Alternatives**
See the attached image.

**Additional context**
Cosmetic01

### PR DESCRIPTION
**Pull request by johnny-bit**
Issue #6376 stems from misunderstandig of label and thus process. This PR fixes #6376 not by graphically filling request, but by better explaining what'll happen. Teaching through GUI.

labels taken from @elstoc's suggestion, tooltips my idea.

### CODE REVIEW

**Comment by TurboGit** [comment]
Ok for the tooltip... But adding "contrast" into labels in a module names "color contrast" seems highly superfluous to me !

**Comment by junkyardsparkle** [comment]
Maybe "steepness" would be less superfluous? :-)

**Comment by elstoc** [comment]
or "slope"... but in the end we're just trying to find synonyms for "contrast". I think in this case the repetition is justified since just "green vs. magenta" has caused confusion - it's just too easy to read it and think "oh it must be green at this end and magenta at the other". Contrast provides clarity even if it is a repetition of the module name.

**Comment by junkyardsparkle** [comment]
...or even "blue/yellow saturation", which would be descriptive of actual effect... honestly, though,  repeating "contrast" doesn't seem horrible, at least in English (but adding red/cyan contrast might just push it over the edge! :roll_eyes:).

**Comment by johnny-bit** [comment]
I'm with elstoc on this one but I can accept another wording that
accurately describes what the sliders do :)

czw., 15 paź 2020, 00:14 użytkownik junkyardsparkle <
notifications@github.com> napisał:

**Comment by TurboGit** [comment]
Ok, so I withdraw my comment.

**Comment by johnny-bit** [comment]
One thing - dont merge yet please. I messed shortcuts for sliders. Will fix
it later today. Fun of using '/' as path separator.

czw., 15 paź 2020, 10:02 użytkownik Pascal Obry <notifications@github.com>
napisał:

**Comment by elstoc** [comment]
"green-magenta contrast" might work?

**Comment by TurboGit** [comment]
Looks ok! Thanks.

**Pull request merged**
