### PR TITLE
merge sticky and hold preview in lighttable

### LINKED ISSUE #13597: RFC: minor inconsistency for focus detection
There is a mode to view a preview with & without the "focus" area.

For preview we have a single shortcut with 2 "elements" to select with or without focus detection

For sticky we have two shortcuts:

- toggle preview mode
- toggle preview mode with focus detection

Maybe worth make this as the standard (non sticky) preview?

### PR DESCRIPTION
**Pull request by dterrahe**
fixes #13597

release note:
- In lighttable, link "hold" and "sticky" preview shortcuts to the same action (previously there were two "toggle sticky preview mode" actions, one with and one without focus detection). Focus detection is selected via an _element_, hold or toggle via an _effect_. All mapped shortcuts are shown in the tooltip of the preview layout button.

In lighttable, the "preview" (which you get when holding w, but which can also be made into a toggle by changing the _effect_ of the shortcut) and "sticky preview" (aka full preview layout) are implemented completely separately (one in the lighttable view and the other in the lighttable toolbox, for example). But they offer similar functionality and also both have a focus detection mode, which in one case is an _element_ of the shortcut and in the other is a separate action. This is confusing.

This PR makes a start of merging the two. As a consequence _all_ the shortcuts show up in the tooltip to the full preview button.
image
(note that shift-F is manually added to demonstrate but won't be a default shortcut)

However, getting into full preview by pressing the button gets you in a slightly different state than using the "f" shortcut. The latter doesn't change the layout mode. This can be "fixed", but I'm wondering if that is the correct remedy and whether the "sticky" preview should be a separate mode at all or be removed. I just don't understand enough about the design decisions around the different "layouts" and what the intended difference, if any, between the preview modes is.

Hopefully @AlicVB will be able to shed some light on this. Many thanks!

### CODE REVIEW

**Comment by AlicVB** [comment]
Sorry for the delayed answer...
For the first point : the separation in 2 files is due to the fact, that when the full preview has been added to the bottom toolbar, I have not been able to move the "non sticky" preview there, because of the "key press/release" stuff. iirc inputng was not in place...
For the second point (I hope to have understood it well) : in fact it does the same thing in 2 different places because the "key release" event and the shortcut one don't share same signatures (that plus the fact that the key event is shared for all the buttons).
For fullpreview the idea is to let `d->layout` value untouched and just call the `preview_enter` routine. That way, when we exit preview, we can go back to previous layout. That's needed because preview can be called from all the "standard" layouts.

I'll test your code asap and report if any problem. Thanks for your work !

**Comment by dterrahe** [comment]
No problem and thanks for your response!

I didn't really mean the separation into two files, but the fact that full preview is implemented as a separate _layout_. As you say, it is really a temporary _mode_ that applies to all the other layouts and when exiting it, you return to the previous layout. But _because_ it is a separate layout, you can, in "full" preview reenable the side panels and that state will then be saved, so there is no "real" full preview anymore (until the user understands how to undo those changes.

So I was just wondering if having "full preview" _really_ as a mode (i.e. d->layout doesn't get set to DT_LIGHTTABLE_LAYOUT_PREVIEW) would be achievable without too many changes. Or if I'm missing drawbacks to such a change.

During your testing please keep in mind that I haven't yet fixed some issues resulting from that and the "sticky" situation.

**Comment by dterrahe** [comment]
@AlicVB not hurrying you, but have you had any further thoughts about this or managed to look at this pr (not "testing" because it is still wip/needs cleaning up).

**Comment by AlicVB** [comment]
> But _because_ it is a separate layout, you can, in "full" preview reenable the side panels and that state will then be saved, so there is no "real" full preview anymore (until the user understands how to undo those changes.

That's on purpose, as some users rely on filmstrip inside the full preview (sticky). Yes, we can argue that then it's not fullpreview anymore...



> So I was just wondering if having "full preview" _really_ as a mode (i.e. d->layout doesn't get set to DT_LIGHTTABLE_LAYOUT_PREVIEW)

iirc, d->layout is not touch when entering fullpreview...

in fact, I have certain misunderstood something, because I don't see what you want to achieve here... For me we don't really have multiple ways to enter full preview (apart that it's spread and duplicated in many places (and centralizing all this in one place would be great)

**Comment by dterrahe** [comment]
> That's on purpose, as some users rely on filmstrip inside the full preview (sticky). Yes, we can argue that then it's not fullpreview anymore...

That would exactly be my argument. How is this different from culling with zoom to 1 image? If there _is_ a difference, it is not clear what it _is_. If there _isn't_, it isn't clear that there is _no_ difference. To me. And I understand how to (un)hide panels and everything, so if it isn't clear to me... Maybe I'm using them all wrong all the time.

Say I'm one of those users that uses sticky preview _with_ filmstrip. How do I now get to a _real_ full preview (non-sticky)? I'd have to switch off the filmstrip first. Or use tab. But if those are "good" options for a full preview, why do we have a separate full preview _at all_?

I'm just saying there is beauty in simplicity. 

> iirc, d->layout is not touch when entering fullpreview...

You are right! I think... The button gets toggled. But not when entering via "non-sticky" preview. Which made a difference for #13518. It is confusing. I haven't figured out where the separate panel states for preview are saved 😕

Look, is this all important _to me_? No. But if I'm trying to do a clean-up and achieve consistency, as @TurboGit requested in #13597, I'd like to end up with something clean and consistent, otherwise there is simply no point.

**Comment by AlicVB** [comment]
> I'm just saying there is beauty in simplicity.

I completely agree. I wouldn't object for removing this feature ! and it would be great to cleanup all this (thanks again for the work !)

now for the implementation (I'm sure you already know most of this) : 
preview currently works exactly as culling internally (it's even a "special case" of a culling layout). That means that when you enter preview, you don't use another window or whatever, but just change the content of the main one, as well as the panel, borders, etc... exactly the same than when you switch from classic layout to culling.
The only difference is that we don't set `d->layout`, but `d->preview_state` and in most place, to determine the "real" layout we so need to check both values. Maybe that can be simplify by using only`d->layout` and storing somewhere the previous layout...

> The button gets toggled. But not when entering via "non-sticky" preview

for me, it's just a missing state update. Don't you think that your PR will solve this (by centralizing sticky and non-sticky shortcuts to the same point) ?



> I haven't figured out where the separate panel states for preview are saved confused

here :  `gui/gtk.c:240`



> I'd like to end up with something clean and consistent, otherwise there is simply no point.

I hope you don't get me wrong here : I'm totally with you :)
it's just that sometimes I have difficulties to understand English correctly (and in this case to remember what I have done years ago)

**Comment by dterrahe** [comment]
> > I haven't figured out where the separate panel states for preview are saved confused
> 
> here : `gui/gtk.c:240`

Yes, I now remember seeing that before. Fond memories! ;-)

All understood. I hope I didn't sound toooo argumentative; there's just a lot of stuff accumulated for historical reasons and because we don't want to break anybody's workflow (even if it doesn't make sense or depends on "bugs", either in design or implementation). People may be _using_ the fact that they basically have two separate "single image culling modes" and can configure panels separately for each. They'll be upset if I decided to "clean this up".

I do remember getting very confused when I first started using dt with the different layouts and how panel visibility settings were connected. This was before your major rework. Pressing TAB and then something like `ctrl+shift+r` _still_ confuses me (but we learn not to do these things.) So yeah, TAB should be included in the whole review as well and that is just too much for my current appetite. I'll have a look at how I can wrap this PR up minimally (maybe with just some state updates, as you say) without opening a hornets nest.

Thanks for your responses and for being patient with me.

**Comment by dterrahe** [comment]
Fullscreen state was maintained both in the lighttable view and the lighttable tools module, so I removed that duplication to make things slightly easier to follow. As usual a good chance that I broke something, but the buttons seem to be updating correctly for me...

**Comment by dterrahe** [comment]
Fixed a bugs and crash that cropped up after rebasing off #13579.

Also added a release note in the OP.

Improved refreshing of the button states (returning `TRUE` from `_lib_lighttable_layout_btn_release` prevented the standard handling of button toggling, including calling `gtk_widget_queue_draw`) but I occasionally see a "stuck" preview button still (which fixes itself on mouse over).

BTW this PR also improves the tooltip for color label shortcuts:
image

**Comment by dterrahe** [comment]
It's in the OP.

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Pull request merged**
