### PR TITLE
prefs: remove import settings from pref dialog

### PR DESCRIPTION
**Pull request by phweyland**
related to #7050

details:
- import: add initial rating pref to have the import settings on the import dialog
- preferences: add int & bool routines to use prefs locally using the the global preferences darktableconfig.xml.in

image

image

### CODE REVIEW

**Comment by johnny-bit** [comment]
When thinking about migration to GTK4 this is kind of stuff to think about... Apparently in GTK4 they removed possibility of adding widgets to dialogs in favour of using native open/save/choose dialogs :cry:

**Comment by phweyland** [comment]
> Apparently in GTK4 they removed possibility of adding widgets to dialogs in favour of using native open/save/choose dialogs

Strange. Would not be a good news. Do you have more information about this (GTK4 dialog doc doesn't describe this) ?

**Comment by johnny-bit** [comment]
> Strange. Would not be a good news. Do you have more information about this (GTK4 dialog doc doesn't describe this) ?

In issue #7220 

in linked issue https://gitlab.gnome.org/GNOME/gtk/-/issues/3453 i mentioned that we can't use recommened GtkFileChooserNative as we use custom widgets to do stuff. Further elaborating on that in https://gitlab.gnome.org/GNOME/glib/-/issues/2263 I received this response from @ebassi:

> GTK4 actually removed the entire API to set custom widgets and previews, to ensure that file selection dialogs work in the same way everywhere, regardless of platform and sandboxing.

That's what I'm basing my reply on...

**Comment by phweyland** [comment]
> we can't use recommened GtkFileChooserNative as we use custom widgets to do stuff.

Got it! Thanks for the links. 
So it is not for all dialogs, but only for file chooser dialogs... :relieved: 
Only this particular `import` dialog is impacted. Once the preferences accessible on preset menu, it will be very easy to move this stuff into and free the usage of `GtkFileChooserNative`

**Comment by TurboGit** [comment]
Works for me. Thanks.

**Pull request merged**
