### PR TITLE
imageio: round to nearest on export

### PR DESCRIPTION
**Pull request by kmilos**
It is more traditional/correct to round than to simply truncate.

### CODE REVIEW

**Comment by kmilos** [comment]
Actually, turns out it was almost never rounded for any export, so also adding in general and J2K.

Curiously, when doing low quality 8-bit exports, equivalent roundf() is done by the gamma iop.

**Comment by TurboGit** [comment]
Have you run the testsuite with this change ? This is a very delicate area and we have made lot of effort to ensure the final image size is "stable" even when rotating image 90°. So I'll be very reluctant to change code on this area...

**Comment by parafin** [comment]
It's not about size, it's about data itself when converted from float to int.

**Comment by TurboGit** [comment]
Oh I see, I should have look at the code... The title was a bit misleading and reminded me of a recent discussion.

**Comment by kmilos** [comment]
That's right, sorry for not being more explicit.

The 16-bit export is the most suspect for the 65536 instead of 65535 scaling factor...

**Comment by aurelienpierre** [comment]
Why not simply use a `roundf()` ?

**Comment by kmilos** [comment]
It's [equivalent](https://en.cppreference.com/w/c/numeric/math/round), no?

```
The double version of round behaves as if implemented as follows:

#include <math.h>
double round(double x)
{
    return signbit(x) ? ceil(x - 0.5) : floor(x + 0.5);;
}
```

No particular reason really, just a few (maybe very minor) pros: no extra header to think about, and also makes the J2K macro "shorter"; finally, a couple of cycles faster since there is no test for sign, we know we're dealing w/ positive and bounded values at this point.

**Comment by aurelienpierre** [comment]
It's equivalent arithmetically, but having a function that says what we are doing is always more maintenance-friendly. Plus, indeed, compilers might vectorize basic math function in clever ways, so better tell them what the goal is, rather than how to do it.

**Comment by TurboGit** [comment]
Well I was expecting this, 78  integration tests out of 82 are failing with 1000 to 10000 pixels moving above dE 2.0.

```
Test 0000-nop
      Image mire1.cr2
      CPU & GPU version differ by 24297 pixels
      Max  dE         2.8999
      Mean dE         0.3942
      Count above max 4946
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42715e+06 pixels changed)

Test 0001-exposure
      Image mire1.cr2
      CPU & GPU version differ by 25723 pixels
      Max  dE         2.6680
      Mean dE         0.3284
      Count above max 3293
  FAILS: image visually changed
         see diff.png for visual difference
         (2.41321e+06 pixels changed)

Test 0002-local-contrast
      Image mire1.cr2
      CPU & GPU version differ by 1.7502e+06 pixels
      Max  dE         2.6604
      Mean dE         0.3315
      Count above max 3654
  FAILS: image visually changed
         see diff.png for visual difference
         (2.40487e+06 pixels changed)

Test 0003-denoise-bilateral
      Image mire1.cr2
      CPU & GPU version differ by 29334 pixels
      Max  dE         2.5805
      Mean dE         0.3303
      Count above max 3413
  FAILS: image visually changed
         see diff.png for visual difference
         (2.41253e+06 pixels changed)

Test 0004-masks
      Image mire1.cr2
      CPU & GPU version differ by 23313 pixels
      Max  dE         2.8999
      Mean dE         0.4210
      Count above max 6123
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42683e+06 pixels changed)

Test 0005-orientation-minus-90
      Image mire1.cr2
      CPU & GPU version differ by 24280 pixels
      Max  dE         2.6604
      Mean dE         0.3941
      Count above max 4994
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42697e+06 pixels changed)

Test 0006-orientation-plus-90
      Image mire1.cr2
      CPU & GPU version differ by 24184 pixels
      Max  dE         2.6604
      Mean dE         0.3941
      Count above max 5113
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42632e+06 pixels changed)

Test 0007-orientation-180
      Image mire1.cr2
      CPU & GPU version differ by 24328 pixels
      Max  dE         2.6680
      Mean dE         0.3941
      Count above max 4951
  FAILS: image visually changed
         see diff.png for visual difference
         (2.4274e+06 pixels changed)

Test 0008-flip-h
      Image mire1.cr2
      CPU & GPU version differ by 23212 pixels
      Max  dE         2.5806
      Mean dE         0.3969
      Count above max 5183
  FAILS: image visually changed
         see diff.png for visual difference
         (2.43921e+06 pixels changed)

Test 0009-flip-v
      Image mire1.cr2
      CPU & GPU version differ by 23202 pixels
      Max  dE         2.5848
      Mean dE         0.3970
      Count above max 5409
  FAILS: image visually changed
         see diff.png for visual difference
         (2.43885e+06 pixels changed)

Test 0010-flip-hv
      Image mire1.cr2
      CPU & GPU version differ by 23288 pixels
      Max  dE         2.8999
      Mean dE         0.3967
      Count above max 5326
  FAILS: image visually changed
         see diff.png for visual difference
         (2.43869e+06 pixels changed)

Test 0011-gdnd-90
      Image mire1.cr2
      CPU & GPU version differ by 22472 pixels
      Max  dE         2.8999
      Mean dE         0.4360
      Count above max 5906
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42634e+06 pixels changed)

Test 0012-gdnd-45
      Image mire1.cr2
      CPU & GPU version differ by 22990 pixels
      Max  dE         2.6199
      Mean dE         0.4320
      Count above max 6651
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42645e+06 pixels changed)

Test 0013-denoiseprofile-wavelets
      Image mire1.cr2
      CPU & GPU version differ by 60421 pixels
      Max  dE         2.6364
      Mean dE         0.3454
      Count above max 3406
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42482e+06 pixels changed)

Test 0014-filmic-rgb
      Image mire1.cr2
      CPU & GPU version differ by 29349 pixels
      Max  dE         2.5848
      Mean dE         0.3315
      Count above max 2692
  FAILS: image visually changed
         see diff.png for visual difference
         (2.44006e+06 pixels changed)

Test 0015-shadhi-bilateral
      Image mire1.cr2
      CPU & GPU version differ by 31838 pixels
      Max  dE         2.6604
      Mean dE         0.3477
      Count above max 4116
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42752e+06 pixels changed)

Test 0016-lowpass-bilateral
      Image mire1.cr2
      CPU & GPU version differ by 34102 pixels
      Max  dE         2.8999
      Mean dE         0.3441
      Count above max 3477
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42702e+06 pixels changed)

Test 0017-monochrome
      Image mire1.cr2
      CPU & GPU version differ by 7723 pixels
      Max  dE         1.9935
  OK

Test 0018-perspective-corr
      Image mire1.cr2
      CPU & GPU version differ by 35579 pixels
      Max  dE         2.5806
      Mean dE         0.3085
      Count above max 3187
  FAILS: image visually changed
         see diff.png for visual difference
         (2.20643e+06 pixels changed)

Test 0019-color-mapping
      Image mire1.cr2
      CPU & GPU version differ by 40487 pixels
      Max  dE         2.5806
      Mean dE         0.3209
      Count above max 2692
  FAILS: image visually changed
         see diff.png for visual difference
         (2.41473e+06 pixels changed)

Test 0020-denoise-nlmeans
      Image mire1.cr2
      CPU & GPU version differ by 986498 pixels
      Max  dE         2.5806
      Mean dE         0.3463
      Count above max 2727
  FAILS: image visually changed
         see diff.png for visual difference
         (2.41868e+06 pixels changed)

Test 0021-retouch-wavelets
      Image mire1.cr2
      CPU & GPU version differ by 32794 pixels
      Max  dE         2.5806
      Mean dE         0.3446
      Count above max 3726
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42639e+06 pixels changed)

Test 0022-color-zones
      Image mire1.cr2
      CPU & GPU version differ by 34295 pixels
      Max  dE         2.6680
      Mean dE         0.3594
      Count above max 4583
  FAILS: image visually changed
         see diff.png for visual difference
         (2.40981e+06 pixels changed)

Test 0023-channelmixer
      Image mire1.cr2
      CPU & GPU version differ by 34615 pixels
      Max  dE         2.6604
      Mean dE         0.3512
      Count above max 3838
  FAILS: image visually changed
         see diff.png for visual difference
         (2.3869e+06 pixels changed)

Test 0024-contrast-equalizer
      Image mire1.cr2
      CPU & GPU version differ by 786701 pixels
      Max  dE         2.6604
      Mean dE         0.3197
      Count above max 3475
  FAILS: image visually changed
         see diff.png for visual difference
         (2.35168e+06 pixels changed)

Test 0025-exposure-guided-filter
      Image mire1.cr2
      CPU & GPU version differ by 25577 pixels
      Max  dE         2.8999
      Mean dE         0.3720
      Count above max 4538
  FAILS: image visually changed
         see diff.png for visual difference
         (2.38177e+06 pixels changed)

Test 0026-haze-removal
      Image mire1.cr2
      CPU & GPU version differ by 550161 pixels
      Max  dE         2.6680
      Mean dE         0.3504
      Count above max 4362
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42242e+06 pixels changed)

Test 0027-denoiseprofile-nlmeans
      Image mire1.cr2
      CPU & GPU version differ by 614535 pixels
      Max  dE         2.5806
      Mean dE         0.3945
      Count above max 4667
  FAILS: image visually changed
         see diff.png for visual difference
         (2.4236e+06 pixels changed)

Test 0028-highpass-overlay
      Image mire1.cr2
      CPU & GPU version differ by 596688 pixels
      Max  dE         1.9935
  OK

Test 0029-color-correction
      Image mire1.cr2
      CPU & GPU version differ by 41144 pixels
      Max  dE         2.6680
      Mean dE         0.3409
      Count above max 4425
  FAILS: image visually changed
         see diff.png for visual difference
         (2.26279e+06 pixels changed)

Test 0030-framing
      Image mire1.cr2
      CPU & GPU version differ by 30157 pixels
      Max  dE         2.5806
      Mean dE         0.3752
      Count above max 4746
  FAILS: image visually changed
         see diff.png for visual difference
         (2.33291e+06 pixels changed)

Test 0031-globaltonemap-drago
      Image mire1.cr2
      CPU & GPU version differ by 43699 pixels
      Max  dE         2.8999
      Mean dE         0.3286
      Count above max 2524
  FAILS: image visually changed
         see diff.png for visual difference
         (2.43892e+06 pixels changed)

Test 0032-watermark
      Image mire1.cr2
      CPU & GPU version differ by 24036 pixels
      Max  dE         2.8999
      Mean dE         0.3958
      Count above max 4896
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42748e+06 pixels changed)

Test 0033-blending-modes-uniform
      Image mire1.cr2
      CPU & GPU version differ by 41799 pixels
      Max  dE         2.6680
      Mean dE         0.3186
      Count above max 3355
  FAILS: image visually changed
         see diff.png for visual difference
         (2.34054e+06 pixels changed)

Test 0034-blending-modes-parametric
      Image mire1.cr2
      CPU & GPU version differ by 30322 pixels
      Max  dE         2.6604
      Mean dE         0.3155
      Count above max 3766
  FAILS: image visually changed
         see diff.png for visual difference
         (2.32622e+06 pixels changed)

Test 0035-multiple-modules
      Image mire1.cr2
      CPU & GPU version differ by 1.47282e+06 pixels
      Max  dE         2.4974
      Mean dE         0.2563
      Count above max 3309
  FAILS: image visually changed
         see diff.png for visual difference
         (1.9253e+06 pixels changed)

Test 0036-liquify
      Image mire1.cr2
      CPU & GPU version differ by 34005 pixels
      Max  dE         2.8999
      Mean dE         0.3918
      Count above max 4900
  FAILS: image visually changed
         see diff.png for visual difference
         (2.4266e+06 pixels changed)

Test 0037-filmic-reconstruction
      Image mire1.cr2
      CPU & GPU version differ by 35756 pixels
      Max  dE         2.8999
      Mean dE         0.3437
      Count above max 3748
  FAILS: image visually changed
         see diff.png for visual difference
         (2.41253e+06 pixels changed)

Test 0038-colorcontrast
      Image mire1.cr2
      CPU & GPU version differ by 34530 pixels
      Max  dE         2.6638
      Mean dE         0.3592
      Count above max 3768
  FAILS: image visually changed
         see diff.png for visual difference
         (2.3347e+06 pixels changed)

Test 0039-invert
      Image mire1.cr2
      CPU & GPU version differ by 9842 pixels
      Max  dE         2.6604
      Mean dE         0.2370
      Count above max 1888
  FAILS: image visually changed
         see diff.png for visual difference
         (1.41479e+06 pixels changed)

Test 0040-fill-light
      Image mire1.cr2
      CPU & GPU version differ by 25317 pixels
      Max  dE         2.8999
      Mean dE         0.3757
      Count above max 1901
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42901e+06 pixels changed)

Test 0041-localtonemap
      Image mire1.cr2
      CPU & GPU version differ by 28875 pixels
      Max  dE         2.2144
      Mean dE         0.3403
      Count above max 238
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42724e+06 pixels changed)

Test 0042-zonesystem
      Image mire1.cr2
      CPU & GPU version differ by 26045 pixels
      Max  dE         2.5805
      Mean dE         0.3737
      Count above max 6571
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42649e+06 pixels changed)

Test 0043-dithering-fs
      Image mire1.cr2
      CPU & GPU version differ by 1.1726e+06 pixels
      Max  dE         0.0000
  OK

Test 0044-dithering-random
      Image mire1.cr2
      CPU & GPU version differ by 22480 pixels
      Max  dE         2.6604
      Mean dE         0.3355
      Count above max 3871
  FAILS: image visually changed
         see diff.png for visual difference
         (2.1745e+06 pixels changed)

Test 0045-vignetting
      Image mire1.cr2
      CPU & GPU version differ by 730483 pixels
      Max  dE         2.8999
      Mean dE         0.4826
      Count above max 5521
  FAILS: image visually changed
         see diff.png for visual difference
         (2.40248e+06 pixels changed)

Test 0046-demosaic-greens
      Image mire1.cr2
      CPU & GPU version differ by 26203 pixels
      Max  dE         2.8999
      Mean dE         0.3938
      Count above max 4958
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42701e+06 pixels changed)

Test 0047-demosaic-amaze
      Image mire1.cr2
      CPU & GPU version differ by 7907 pixels
      Max  dE         2.5806
      Mean dE         0.3947
      Count above max 4955
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42784e+06 pixels changed)

Test 0048-demosaic-vng
      Image mire1.cr2
      CPU & GPU version differ by 20491 pixels
      Max  dE         2.6638
      Mean dE         0.3936
      Count above max 4979
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42526e+06 pixels changed)

Test 0049-rawdenoise
      Image mire1.cr2
      CPU & GPU version differ by 11978 pixels
      Max  dE         2.5806
      Mean dE         0.3986
      Count above max 4921
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42543e+06 pixels changed)

Test 0050-bloom
      Image mire1.cr2
      CPU & GPU version differ by 852291 pixels
      Max  dE         2.4078
      Mean dE         0.3181
      Count above max 2187
  FAILS: image visually changed
         see diff.png for visual difference
         (2.39634e+06 pixels changed)

Test 0051-soften
      Image mire1.cr2
      CPU & GPU version differ by 762913 pixels
      Max  dE         2.5805
      Mean dE         0.3579
      Count above max 2708
  FAILS: image visually changed
         see diff.png for visual difference
         (2.43228e+06 pixels changed)

Test 0052-color-reconstruction
      Image mire1.cr2
      CPU & GPU version differ by 839274 pixels
      Max  dE         2.8999
      Mean dE         0.3973
      Count above max 4957
  FAILS: image visually changed
         see diff.png for visual difference
         (2.4263e+06 pixels changed)

Test 0053-levels
      Image mire1.cr2
      CPU & GPU version differ by 30482 pixels
      Max  dE         2.6604
      Mean dE         0.2844
      Count above max 1053
  FAILS: image visually changed
         see diff.png for visual difference
         (2.38727e+06 pixels changed)

Test 0054-rgblevels-linked
      Image mire1.cr2
      CPU & GPU version differ by 32263 pixels
      Max  dE         2.5806
      Mean dE         0.3614
      Count above max 3813
  FAILS: image visually changed
         see diff.png for visual difference
         (2.33416e+06 pixels changed)

Test 0055-rgblevels-indep
      Image mire1.cr2
      CPU & GPU version differ by 36079 pixels
      Max  dE         2.5667
      Mean dE         0.3296
      Count above max 1100
  FAILS: image visually changed
         see diff.png for visual difference
         (2.22472e+06 pixels changed)

Test 0056-vibrance
      Image mire1.cr2
      CPU & GPU version differ by 25094 pixels
      Max  dE         2.6638
      Mean dE         0.3929
      Count above max 4995
  FAILS: image visually changed
         see diff.png for visual difference
         (2.41572e+06 pixels changed)

Test 0057-colorize
      Image mire1.cr2
      CPU & GPU version differ by 8494 pixels
      Max  dE         1.0556
  OK

Test 0058-defringe
      Image mire1.cr2
      CPU & GPU version differ by 18527 pixels
      Max  dE         2.5799
      Mean dE         0.3986
      Count above max 4815
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42969e+06 pixels changed)

Test 0059-grain
      Image mire1.cr2
      CPU & GPU version differ by 24019 pixels
      Max  dE         2.8999
      Mean dE         0.3938
      Count above max 5035
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42562e+06 pixels changed)

Test 0060-rgbcurve-indep
      Image mire1.cr2
      CPU & GPU version differ by 43208 pixels
      Max  dE         2.6199
      Mean dE         0.3438
      Count above max 2031
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42508e+06 pixels changed)

Test 0061-lowlight
      Image mire1.cr2
      CPU & GPU version differ by 23545 pixels
      Max  dE         2.5477
      Mean dE         0.3929
      Count above max 6620
  FAILS: image visually changed
         see diff.png for visual difference
         (2.44226e+06 pixels changed)

Test 0062-splittoning
      Image mire1.cr2
      CPU & GPU version differ by 33518 pixels
      Max  dE         2.6680
      Mean dE         0.3787
      Count above max 4756
  FAILS: image visually changed
         see diff.png for visual difference
         (2.40055e+06 pixels changed)

Test 0063-velvia
      Image mire1.cr2
      CPU & GPU version differ by 41317 pixels
      Max  dE         2.6680
      Mean dE         0.3652
      Count above max 3829
  FAILS: image visually changed
         see diff.png for visual difference
         (2.3386e+06 pixels changed)

Test 0064-demosaic-xtrans-vng
      Image mire1-xtrans.raf
      CPU & GPU version differ by 9545 pixels
      Max  dE         2.5806
      Mean dE         0.5285
      Count above max 9497
  FAILS: image visually changed
         see diff.png for visual difference
         (2.45008e+06 pixels changed)

Test 0065-demosaic-mark1
      Image mire1-xtrans.raf
      CPU & GPU version differ by 23802 pixels
      Max  dE         2.5806
      Mean dE         0.5284
      Count above max 9449
  FAILS: image visually changed
         see diff.png for visual difference
         (2.44975e+06 pixels changed)

Test 0066-demosaic-mark3
      Image mire1-xtrans.raf
      CPU & GPU version differ by 10225 pixels
      Max  dE         2.5806
      Mean dE         0.5284
      Count above max 9438
  FAILS: image visually changed
         see diff.png for visual difference
         (2.44952e+06 pixels changed)

Test 0067-demosaic-fdc
      Image mire1-xtrans.raf
      CPU & GPU version differ by 5650 pixels
      Max  dE         2.5806
      Mean dE         0.5293
      Count above max 9492
  FAILS: image visually changed
         see diff.png for visual difference
         (2.44998e+06 pixels changed)

Test 0068-rawdenoise-xtrans
      Image mire1-xtrans.raf
      CPU & GPU version differ by 14229 pixels
      Max  dE         2.5806
      Mean dE         0.5355
      Count above max 9788
  FAILS: image visually changed
         see diff.png for visual difference
         (2.45039e+06 pixels changed)

Test 0069-tonecurve-rgb-linked
      Image mire1.cr2
      CPU & GPU version differ by 30647 pixels
      Max  dE         2.8999
      Mean dE         0.3536
      Count above max 1666
  FAILS: image visually changed
         see diff.png for visual difference
         (2.43902e+06 pixels changed)

Test 0070-tonecurve-xyz-linked
      Image mire1.cr2
      CPU & GPU version differ by 23245 pixels
      Max  dE         2.6604
      Mean dE         0.3775
      Count above max 1075
  FAILS: image visually changed
         see diff.png for visual difference
         (2.44324e+06 pixels changed)

Test 0071-tonecurve-lab-linked
      Image mire1.cr2
      CPU & GPU version differ by 29348 pixels
      Max  dE         2.8999
      Mean dE         0.3744
      Count above max 5078
  FAILS: image visually changed
         see diff.png for visual difference
         (2.43926e+06 pixels changed)

Test 0072-tonecurve-lab-indep
      Image mire1.cr2
      CPU & GPU version differ by 25352 pixels
      Max  dE         2.5415
      Mean dE         0.3496
      Count above max 1881
  FAILS: image visually changed
         see diff.png for visual difference
         (2.31392e+06 pixels changed)

Test 0073-spot-removal
      Image mire1.cr2
      CPU & GPU version differ by 22436 pixels
      Max  dE         2.5806
      Mean dE         0.4101
      Count above max 6076
  FAILS: image visually changed
         see diff.png for visual difference
         (2.44014e+06 pixels changed)

Test 0074-retouch-clone
      Image mire1.cr2
      CPU & GPU version differ by 22824 pixels
      Max  dE         2.5806
      Mean dE         0.3935
      Count above max 4446
  FAILS: image visually changed
         see diff.png for visual difference
         (2.44124e+06 pixels changed)

Test 0075-retouch-heal
      Image mire1.cr2
      CPU & GPU version differ by 51728 pixels
      Max  dE         2.5806
      Mean dE         0.3841
      Count above max 4014
  FAILS: image visually changed
         see diff.png for visual difference
         (2.40188e+06 pixels changed)

Test 0076-retouch-blur-fill
      Image mire1.cr2
      CPU & GPU version differ by 116935 pixels
      Max  dE         2.5806
      Mean dE         0.3900
      Count above max 3896
  FAILS: image visually changed
         see diff.png for visual difference
         (2.41043e+06 pixels changed)

Test 0077-croprotate-keystone
      Image mire1.cr2
      CPU & GPU version differ by 16414 pixels
      Max  dE         2.5806
      Mean dE         0.3928
      Count above max 5198
  FAILS: image visually changed
         see diff.png for visual difference
         (2.30773e+06 pixels changed)

Test 0078-basecurve-fusion
      Image mire1.cr2
      CPU & GPU version differ by 31177 pixels
      Max  dE         2.6604
      Mean dE         0.3089
      Count above max 2721
  FAILS: image visually changed
         see diff.png for visual difference
         (2.41202e+06 pixels changed)

Test 0079-toneequal-gf
      Image mire1.cr2
      CPU & GPU version differ by 28110 pixels
      Max  dE         2.6680
      Mean dE         0.3818
      Count above max 3268
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42798e+06 pixels changed)

Test 0080-toneequal-eigf
      Image mire1.cr2
      CPU & GPU version differ by 30103 pixels
      Max  dE         2.8999
      Mean dE         0.4084
      Count above max 2268
  FAILS: image visually changed
         see diff.png for visual difference
         (2.42713e+06 pixels changed)

Test 0081-mask-groups
      Image mire1.cr2
      CPU & GPU version differ by 19926 pixels
      Max  dE         2.8999
      Mean dE         0.3736
      Count above max 4413
  FAILS: image visually changed
         see diff.png for visual difference
         (2.1285e+06 pixels changed)

Total test 82
Errors     78
```

**Comment by kmilos** [comment]
I guess that was to be expected since the values change overall.

The tricky part is now deciding/agreeing on what is the "correct" reference for the tests.

**Comment by aurelienpierre** [comment]
@TurboGit when coding the color checker calibration, I found that delta E 1976 is really pessimistic as a metric, and anyway not really uniform. Switching to delta E 2000 should make things look less concerning.

On the matter at hand… The rounding done here will improve accuracy of the output, so the delta E is actually a good sign.

**Comment by TurboGit** [comment]
@aurelienpierre : sure I agree with everything but updating 78 expected files of 5Mb is 390Mb, I fear some won't like that :)

**Comment by saknopper** [comment]
I realize that I'm breaking in here without being asked to, but: it might be worth looking into git lfs (https://git-lfs.github.com/) to store the expected images for the unit tests.

**Comment by parafin** [comment]
Please don't use Git LFS.

**Comment by TurboGit** [comment]
@saknopper : GitLFS won't change the fact that we will require everyone to download 380Mb in next update, or I'm mistaken?

The standard Git can deal with 5Mb files without problem, this issue is no there.

**Comment by saknopper** [comment]
@TurboGit : the feature list on the website explicitly says "Download less data. This means faster cloning and fetching from repositories that deal with large files." That being said, I don't have experience with it myself. So if someone who has (@parafin  ?) says it isn't worth looking into, then feel free to ignore my suggestion :)

**Comment by parafin** [comment]
Faster cloning and fetching in git LFS refers to the fact, that fresh clones won't require downloading the whole history of LFS-tracked files (which is possible with shallow clone BTW, without LFS). But if we take a use-case of a user tracking the master, he still will automatically download all updates anyway. It won't happen if he doesn't have git LFS installed, but I don't think it's a good workaround for the problem. For better alternatives see #7198, e.g. feel free to use a separate repository for these files and enable LFS there. Maybe it's a good time to consider solving this.

As for why I'm against git LFS - once you begin using it, there's basically no turning back - you can expect troubles moving/copying repository to another hosting (even if you remove LFS in one of the following commits) and so on. Also it's not as easily installable as git itself, at least on some systems. So I'm strongly against using it for main dt repository.

**Comment by TurboGit** [comment]
@parafin:
> For better alternatives see #7198, e.g. feel free to use a separate repository for these files and enable LFS there. Maybe it's a good time to consider solving this.

I think indeed it is time to use a separate repository and make it a sub-module. I don't think we'll manage without this or we will impose lot too much download for everyone. This will require more work for devs updating & using the tests though and we need to keep the sub-module properly committed to follow closely the changes in dt.

Anyway, let's start moving about this. I'll ask for a new repository named `darktable-tests`. Fine with you or do you have a better proposal ?

**Comment by parafin** [comment]
Separate repository is definitely a go if you ask me.

My question about submodule though - how easy it is to exclude it from usual updates people staying on master do? Because we have other submodules and they must be updated. I just haven't investigated this. Can't we just do `git clone` and `git pull` in run.sh or something like that?

**Comment by TurboGit** [comment]
> Separate repository is definitely a go if you ask me.

Ok, I'll ask to have one created.

**Comment by TurboGit** [comment]
> Can't we just do `git clone` and `git pull` in run.sh or something like that?

No because we want to track the test repository with the main darktable one (branching, and when a commit require a test update).

**Comment by TurboGit** [comment]
> My question about submodule though - how easy it is to exclude it from usual updates people staying on master do?

I suppose this is possible, but I don't know right now. Will have to look at this.

**Comment by TurboGit** [comment]
According to the documentation the solution should be:

`$ git config submodule.src/test/integration.update none`

**Comment by TurboGit** [comment]
I tested that on the current OpenCL header:

```
$ git submodule update 
Skipping submodule 'src/external/OpenCL'
```

Seems like it is working as expected.

**Comment by kmilos** [comment]
Just noticed a new darktable-tests repo has been created, think this is the right way to go as well.

Btw, I think there might be some other problems with the `deltae` script, shall I open an issue in the new repo, rather than keep discussing here?

**Comment by TurboGit** [comment]
> Just noticed a new darktable-tests repo has been created, think this is the right way to go as well.

And now integrated as sub-module.


> Btw, I think there might be some other problems with the `deltae` script, shall I open an issue in the new repo, rather than keep discussing here?

Sure ! Also this script has recently been update by Aurélien, so be sure to check with the latest version.

**Comment by TurboGit** [comment]
I have merged this manually, squashing all commits together and updating the integration tests expected output.

**Pull request closed without merging**
