### PR TITLE
imageio_libraw: also keep the base black level

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by kmilos** [comment]
A recent commit broke master @TurboGit @wpferguson @jenshannoschwalm @aurelienpierre 

https://github.com/darktable-org/darktable/actions/workflows/ci.yml

**Comment by TurboGit** [comment]
@kmilos : Thanks for the heads-up... I don't have the issue but I see this in the log:

```
/home/runner/work/darktable/darktable/src/src/develop/develop.c: In function ‘dt_dev_process_image_job’:
/home/runner/work/darktable/darktable/src/src/develop/develop.c:635:3: error: implicit declaration of function ‘dt_lua_async_call_alien’ [-Werror=implicit-function-declaration]
   dt_lua_async_call_alien(dt_lua_event_trigger_wrapper,
   ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors
```

@wpferguson : Any idea ?

**Comment by kmilos** [comment]
> I don't have the issue

The CI had issues: https://github.com/darktable-org/darktable/actions/runs/3247644469

Should not have been merged.

**Comment by victoryforce** [comment]
```
#ifdef USE_LUA
#include "lua/call.h"
#endif
```
should be added to src/develop/develop.c

**Comment by TurboGit** [comment]
> > I don't have the issue
> 
> The CI had issues: https://github.com/darktable-org/darktable/actions/runs/3247644469
> 
> Should not have been merged.

I know, my bad again !

**Comment by kmilos** [comment]
> I know, my bad again !

No pressure, no need to apologise ;) Let's just leverage the CI when we have it!

**Comment by TurboGit** [comment]
The lua issue is fixed, we still have errors on MacOS that was there before and that I just don't understand.

**Comment by kmilos** [comment]
The macOS one came w/ https://github.com/darktable-org/darktable/commit/bff7b3bfeddae134128a29e57b3028a6476052f0 @jenshannoschwalm

**Comment by jenshannoschwalm** [comment]
I am at work so can't check right now :-(

**Comment by kmilos** [comment]
No worries, just trying to pinpoint... Actually, looks like coincidence, and not related to your change directly:

```
CMake Error at /usr/local/Cellar/cmake/3.24.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
  (Required is at least version "4.5")
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.24.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:[59](https://github.com/darktable-org/darktable/actions/runs/3247514070/jobs/5327647401#step:4:60)4 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.24.2/share/cmake/Modules/FindOpenMP.cmake:545 (find_package_handle_standard_args)
  CMakeLists.txt:89 (find_package)
```

Homebrew problems again? Beyond my expertise/interest unfortunately...

**Comment by jenshannoschwalm** [comment]
Just had look at the build log for the mentioned pr, no idea right now.

**Comment by wpferguson** [comment]
Sorry about the compile issue.  I saw it on my phone but couldn't access the logs to see what happened.  Thanks for taking care of it.

**Comment by kmilos** [comment]
Thanks @victoryforce for sorting out the macOS CI issue!

**Comment by TurboGit** [comment]
@kmilos : After all the side discussions with compilation issues... Finally is that ready for merging?

**Comment by kmilos** [comment]
Yes, ready, merci!

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
