### PR TITLE
Usermanual fact checking & updates Part 1

### PR DESCRIPTION
**Pull request by LebedevRI**
This covers the first half of the usermanual, up to `3.4.4. Correction group`
Added strings may need further polishing :)

### CODE REVIEW

**Comment by upegelow** [comment]
@LebedevRI: please tell me when I should take over with this PR.

**Comment by LebedevRI** [comment]
@upegelow feel free to do so at any moment.
Any further fixes will just go into Part 2

**Comment by upegelow** [comment]
@LebedevRI: thanks. I only made a few linguistical changes .

**Comment by LebedevRI** [comment]
@upegelow thank you!

**Pull request merged**
