### PR TITLE
masks: implement feathering resize by shift-scroll

### PR DESCRIPTION
**Pull request by upegelow**
this takes away the previously implemented lower limit for the
feathering area.

### CODE REVIEW

**Comment by TurboGit** [comment]
working fine for all forms except pencil. It seems that for the pencil the shift-scroll still change the size of the object and not the feather. Do you confirm that?

**Comment by upegelow** [comment]
>  It seems that for the pencil the shift-scroll still change the size of the object and not the feather. Do you confirm that?

This is true. The brush shape works differently from the other ones. It is defined by size+hardness rather than size+feather.

**Comment by LebedevRI** [comment]
Last-minute new feature addition into masks(!) is the worst.
Just saying.

**Comment by upegelow** [comment]
> Last-minute new feature addition into masks(!) is the worst.
Just saying.

Well, and now?

**Comment by LebedevRI** [comment]
> Well, and now?

Don't know.
"Just saying." was supposed to convey that i'm not completely against merging this now, but rather just not happy about it.

**Comment by upegelow** [comment]
Not being happy is not a call for action. So we either merge or not.

**Comment by upegelow** [comment]
@TurboGit: knowing that French text tends to be longer than the English one, could you please have a look if we get into issues with the changed hinter messages? The one for the ellipse shape is probably the longest one.

**Comment by LebedevRI** [comment]
> Not being happy is not a call for action.

Now you got it :) That was the point.

**Comment by TurboGit** [comment]
Will look at this but not before Monday.

Pascal Obry / Magny les Hameaux

Le 19 nov. 2016 9:51 AM, "Ulrich Pegelow" <notifications@github.com> a
écrit :

**Comment by LebedevRI** [comment]
BTW, we want **rc1** soon (preferably by the end of *this* week), and i think we will also **hard-string-freeze** at the same time.
So if you are certain about merging, better sooner than later.

**Comment by TurboGit** [comment]
@upegelow : the french text looks fine to me. I've just updated it and tried to minimize it.

**Pull request merged**
