### PR TITLE
Introduce debug log macros

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
All debugging output should only be done if there is ANY flag set in darktable.unmuted

Instead of adding an 'if(darktable.unmuted)` before every dt_print() variant we redefine the functions names and introduce macros that do that for us.

### CODE REVIEW

**Comment by TurboGit** [comment]
I'm not sure to understand, the current implementation of `dt_print()` already check for `darktable.unmuted` and possible verbose mode. Also this now forces a `{ }` when inside `if` condition to avoid the compiler to complain. All in all I'm not too happy with this proposal.

**Comment by jenshannoschwalm** [comment]
I understand your reluctance. Yet - aren't the parameters for `dt_print()` variants calculated when calling it? This would avoid that - and i didn't have a better idea than a macro. With this pr there would be almost no runtime cost, right?

**Comment by parafin** [comment]
You could try this to avoid the addition of braces everywhere:

`#define dt_print(...) do{if(darktable.unmuted)dt_print_ext(__VA_ARGS__);}while(0)`

**Comment by TurboGit** [comment]
> With this pr there would be almost no runtime cost, right?

Probably the case yes, but the comment log was not describing this goal. So yes, maybe try the proposal from @parafin.

**Comment by parafin** [comment]
I mean you really use my proposal, because without it someone will write code without braces, which will introduce very strange results when else clause is written right after.

**Comment by TurboGit** [comment]
I'm really not sure this change is worth the effort.

**Comment by dterrahe** [comment]
@parafin I've come across your approach before, of course, but wondering what the drawbacks would be of this alternative:
```
#define dt_print_pipe(...) darktable.unmuted && (dt_print_pipe_ext(__VA_ARGS__), TRUE)
#define dt_print(...) darktable.unmuted && (dt_print_ext(__VA_ARGS__), TRUE)
#define dt_print_nts(...) darktable.unmuted && (dt_print_nts_ext(__VA_ARGS__), TRUE)
```
They are not equivalent, of course, so would not "catch" some strange uses that wouldn't work with a normal statement, like for example adding extra conditions like
`extra_flag == TRUE && dt_print(DT_DEBUG_ALWAYS, "extra flag tested\n");

> I'm really not sure this change is worth the effort.

Not with the need for extra braces, but I have often looked at debug statements that call many functions in their argument lists and wondered if we could not prevent all that wasted effort for the cases where all debug printing is disabled anyway. I think I would be in favor of moving the whole check for
```
  if(thread != DT_DEBUG_ALWAYS)
  {
    if(((darktable.unmuted & thread) & ~DT_DEBUG_VERBOSE) == 0) return;
    if((thread & DT_DEBUG_VERBOSE) && !(darktable.unmuted & DT_DEBUG_VERBOSE)) return;
  }
```
into a separate (inline?) function call in the macro, so
```
#define dt_print_pipe(thread,...) dt_print_requested(thread) && (dt_print_pipe_ext(__VA_ARGS__), TRUE)
#define dt_print(thread,...) dt_print_requested(thread) && (dt_print_ext(__VA_ARGS__), TRUE)
#define dt_print_nts(thread,...) dt_print_requested(thread) && (dt_print_nts_ext(__VA_ARGS__), TRUE)
```
(or @parafin's version of same).

**Comment by parafin** [comment]
Your version should be fine too, I think.

**Comment by jenshannoschwalm** [comment]
Anyone want to take over the macro game?

**Comment by dterrahe** [comment]
> Anyone want to take over the macro game?

Sure. I'll submit a PR based on my suggestion above. I'll see if I can figure out whether "@parafin's approach" produces more efficient machine code.

**Pull request closed without merging**
