### PR TITLE
[WIP] small lighttable UI fix

### PR DESCRIPTION
**Pull request by AlicVB**
see commits title for details

### CODE REVIEW

**Comment by aurelienpierre** [comment]
I have added my work on top of that to fix the border glitches in lighttable in https://github.com/aurelienpierre/darktable/tree/lighttable.

Namely : 2d91b39d1b0a069c7fe841f0c873409c905cfb9b

basically, I discovered that thumbnails height and width were computed and used internally as float in expose_filemanager() but passed to dt_image_expose() as int32. This caused rounding issues and misplacement of group borders, when redrawing of background over group lines.

This changes width and height to float, use fixed-sized borders and accurately move the thumbnails and borders where they should.

TODO: port the changes to zoomable table view and filmstrips.

**Comment by AlicVB** [comment]
last commit is the follow up of @aurelienpierre work, but for full preview and culling image informations display. It looks like that (full preview with everything on) : 
Capture d’écran_2019-09-27_20-29-22
For the details, everything is now scaled based on the fontsize, which is defined by `fminf(DT_PIXEL_APPLY_DPI(20.0f), 0.91 * width / 10.0f);` (to mimic the zoom != 1 part)
@aurelienpierre can you have a look ? btw, I fear it will put some mess in your previous mentioned work. Sorry (I'm seeing it just now, after the push...)

**Comment by aurelienpierre** [comment]
It seems the sound icon is showing even when there is no sound associated with the picture:

Screenshot_20190927_210306

**Comment by AlicVB** [comment]
oh... sheet, forgot to put back some checks, I've commented to be sure all possible icons are drawn. let me correct that !

**Comment by aurelienpierre** [comment]
hmmm did that fix it ? or maybe I got a merging issue ?

**Comment by aurelienpierre** [comment]
@AlicVB maybe you can merge my branch in yours if you want. I have rebased.

**Comment by TurboGit** [comment]
This is still WIP, right?

**Comment by aurelienpierre** [comment]
It works pretty well on my side. Just the sound icons that get drawn anyway.

**Comment by aurelienpierre** [comment]
well, no. Found issues on my side. I don't know if we want to merge @AlicVB 's branch and mine as one, since they are interleaved.

**Comment by TurboGit** [comment]
Ok, will wait for @AlicVB feedback.

**Comment by AlicVB** [comment]
to be close once PR #3039 is merged

**Pull request closed without merging**
