### PR TITLE
topbar: avoid scrolling issue in the add new filter menu

### LINKED ISSUE #12956: scrolling over filter hamburger popup "new filter" menu adds filters
Presumably since #12849 

1. click on the "hamburger" menu left of "filter" in the top toolbar.
2. move the mouse down to hover over "new filter" line
3. click to open the menu of available filters (this step is not necessary, but that's how I found out; this looks like a combo popup, so the next step seemed logical to me)
4. use the scroll wheel to scroll through the available filters. The popup gets messed up; it looks like it scrolls up, but what actually happens is that one by one the filters get added to the top bar (and removed from the menu)

Expected; scrolling could move the menu up or down as with other popups. Alternatively, scrolling could do nothing. Scrolling should not add items to the top bar.

### PR DESCRIPTION
**Pull request by AlicVB**
this fixes #12956

This is a way more simple fix than previous PR #13010 . In fact bauhaus combobox already has everything required to "mute" scrolling feature :)

### CODE REVIEW

**Comment by TurboGit** [comment]
> this fixes #12956

Does not fix the issue on my side.

**Comment by TurboGit** [comment]
After scrolling I have:
image

**Review by Nilvus — APPROVED** [review]

**Comment by Nilvus** [comment]
I made a lot of scrolling effect and this fixes on my side. I can't reproduce what you have @TurboGit.
As you compile and test a lot, maybe you forgot to clean your build and installation folders before compiling?

**Comment by AlicVB** [comment]
@TurboGit : I don't reproduce either : here, scrolling only change the "highlighted" line in the combobox popup, without creating a new filter...

**Comment by TurboGit** [comment]
@Nilvus : I cleaned up my build directory. I have rebuilt from scratch. Started dt with a clean install (no db, no darktablerc)... Still the issue:

image

**Comment by AlicVB** [comment]
oh... wait : I sort of reproduce another related issue : if you *don't* open the combobox : just hover the mouse on it, and then scroll *very quickly*, I have managed to insert more than one filter at a time...
That's a bauhaus combox issue (and I'll try to fix it too)

But I fear that it's not you case, as in your screenshots the popup is shown, meaning you have "opened" the combobox... right ?

Question : in the collect module, can you reproduce : open the filters combobox and scroll : does it change the content of the treeview/listview on the fly ?

**Comment by TurboGit** [comment]
> But I fear that it's not you case, as in your screenshots the popup is shown, meaning you have "opened" the combobox... right ?

That's right.

**Comment by TurboGit** [comment]
> Question : in the collect module, can you reproduce : open the filters combobox and scroll : does it change the content of the treeview/listview on the fly ?

image

When I scroll where the mouse is displayed it changes the value and also the current filter (so applying the value indeed).

**Comment by AlicVB** [comment]
well... I was speaking of the "old" collect module ;)
because there, the filter type combobox already use the "mute scrolling" feature, so I wanted to know if that work there for you or not...

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Pull request merged**
