### PR TITLE
color_conversion: fix error on macos.

### LINKED ISSUE #3212: OSX: opencl support broken by color_conversion: constant float matrix[9]
**Describe the bug**
compiling opencl kernels at system start terminates for color_conversion.cl 

```
/Applications/darktable.app/Contents/Resources/share/darktable/kernels/color_conversion.cl:114:63: error: parameter may not be qualified with an address space
inline float4 matrix_product(const float4 xyz, constant float matrix[9])
                                                              ^
/Applications/darktable.app/Contents/Resources/share/darktable/kernels/color_conversion.cl:124:132: error: parameter may not be qualified with an address space
inline float get_rgb_matrix_luminance(const float4 rgb, constant dt_colorspaces_iccprofile_info_cl_t *profile_info, constant float matrix[9], read_only image2d_t lut)
```
 
**To Reproduce**
1. call /Applications/darktable.app/Contents/MacOS/darktable-cltest

**Platform (please complete the following information):**
 - OS: OSX 10.14
 - Version darktable 2.7.0+2091~gbe6a92465-dirty

### PR DESCRIPTION
**Pull request by TurboGit**
Fixes #3212.

### CODE REVIEW

**Comment by MStraeten** [comment]
fix doesnt help:
```
/usr/local/share/darktable/kernels/rgb_norms.h:36:106: error: passing '__constant float *' to parameter of type 'const float *' changes address space of pointer
    return (work_profile == 0) ? dt_camera_rgb_luminance(in): get_rgb_matrix_luminance(in, profile_info, profile_info->matrix_in, lut);
                                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~
/usr/local/share/darktable/kernels/color_conversion.cl:124:129: note: passing argument to parameter 'matrix' here
inline float get_rgb_matrix_luminance(const float4 rgb, constant dt_colorspaces_iccprofile_info_cl_t *profile_info, const float matrix[9], read_only image2d_t lut)
                                                                                                                                ^

0.076845 [opencl_init] failed to compile program `basic.cl'!
```

**Comment by TurboGit** [comment]
> fix doesnt help:
> 
> ```
> /usr/local/share/darktable/kernels/rgb_norms.h:36:106: error: passing '__constant float *' to parameter of type 'const float *' changes address space of pointer
>     return (work_profile == 0) ? dt_camera_rgb_luminance(in): get_rgb_matrix_luminance(in, profile_info, profile_info->matrix_in, lut);
>                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~
> /usr/local/share/darktable/kernels/color_conversion.cl:124:129: note: passing argument to parameter 'matrix' here
> inline float get_rgb_matrix_luminance(const float4 rgb, constant dt_colorspaces_iccprofile_info_cl_t *profile_info, const float matrix[9], read_only image2d_t lut)
>                                                                                                                                 ^
> 
> 0.076845 [opencl_init] failed to compile program `basic.cl'!
> ```

Just pushed a new version. Can you test?

**Comment by MStraeten** [comment]
also not accepted:
```
/usr/local/share/darktable/kernels/rgb_norms.h:36:106: error: passing '__constant float *' to parameter of type 'float *' changes address space of pointer
    return (work_profile == 0) ? dt_camera_rgb_luminance(in): get_rgb_matrix_luminance(in, profile_info, profile_info->matrix_in, lut);
                                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~
/usr/local/share/darktable/kernels/color_conversion.cl:124:123: note: passing argument to parameter 'matrix' here
inline float get_rgb_matrix_luminance(const float4 rgb, constant dt_colorspaces_iccprofile_info_cl_t *profile_info, float matrix[9], read_only image2d_t lut)
                                                                                                                          ^

0.516100 [opencl_init] failed to compile program `basic.cl'!

```

**Comment by TurboGit** [comment]
Ok, new version proposed. If not working I'll let someone else try :)

**Comment by MStraeten** [comment]
bingo, OpenCl kernels are built

**Pull request merged**
