### PR TITLE
Just testing CI with some revert

### PR DESCRIPTION
**Pull request by TurboGit**

### CODE REVIEW

**Comment by TurboGit** [comment]
@dterrahe : The failure has started when merging #13579. I'm trying to revert part of push that to check on CI has it seems this affect only CI (nobody seems to be able to reproduce). If you have any idea to find the culprit more easily let me know.

**Comment by TurboGit** [comment]
Ok, the CI is clean and I have reverted:

```
commit fd589b86086897e66ed75b2bc1913bff07f9c156
Author: Pascal Obry <pascal@obry.net>
Date:   Thu Feb 23 18:33:25 2023 +0100

    Revert "silence warning about lua in gui thread"
    
    This reverts commit 1a197311beef0cfbfcb68b887bfee91477970b15.

commit ae05b5590c58409826e82c1629fecb217e023bed
Author: Pascal Obry <pascal@obry.net>
Date:   Thu Feb 23 18:33:18 2023 +0100

    Revert "better support combos from introspection (blending/borders/sort)"
    
    This reverts commit ee3a34aeacefb2f7c07fc0495396eeb60256184e.

commit e88fae615ea88df4bcc2dd2fe08939f9b5c61bdf
Author: Pascal Obry <pascal@obry.net>
Date:   Thu Feb 23 18:33:13 2023 +0100

    Revert "support shortcuts to sliders/combos created in lua"
    
    This reverts commit 27b023facf754e9a060beeb64e6e35405b3a861a.

commit 1a19d248323f1a98917d8a4c07046069eb8a1356
Author: Pascal Obry <pascal@obry.net>
Date:   Thu Feb 23 18:33:01 2023 +0100

    Revert "style fixes as requested"
    
    This reverts commit 3ec9ce1fc11f59f27d828cd74ee4e8e4e7dd0b8c.

commit 05be0a1d0127c13437ca2792a76e82cd385fa5f4
Author: Pascal Obry <pascal@obry.net>
Date:   Thu Feb 23 18:32:51 2023 +0100

    Revert "reorder blending modes"
    
    This reverts commit c3037f45631e7ad9efd4b22fcc464d4708f78838.
```

I'll try to find which commit.

**Comment by dterrahe** [comment]
Just keep in mind that when the CI was failing for this PR itself, eventually I got it to cleanly run by triggering a rerun a few times. So just the fact that it now cleanly ran _once_ after the revert doesn't necessarily _proof_ too much; it seems to be somewhat random...

The PR is mostly/entirely UI/lua, so it is strange that it would impact a cli command. Is there anyway we can get more detail from the CI about the crash since nobody, me included, has managed to reproduce it elsewhere? It seem so be in Magick (but could be random memory corruption elsewhere, of course).

**Comment by jenshannoschwalm** [comment]
Just my two cents writing / thinking

Taking the 000-noop test is already surprising here

cpu path
diff

gpu path
diff-cl


I guess you have generated the reference with opencl ?

Simple modules (rawprepare, highlights-clip) without changes i can remember, leaves out finalscale - although that seemed to work right. That uses `dt_iop_clip_and_zoom_roi()` and the cl variant calling `dt_interpolation_resample_roi()` or the cl variant again.

1. They use `DT_INTERPOLATION_USERPREF` are we sure the CI defines that?
2. we did some changes on interpolation recently. (didn't check yet and in need for sleep ...)

**Comment by TurboGit** [comment]
I may I found the issue with the CI, see #13723.

**Comment by dterrahe** [comment]
Oops! Sorry about that! I thought that was equivalent. And those variables are only meant to be used in the gui, so why it trips up the cli?

And also strange that it _only_ triggered a crash in CI. Any ideas why that might be? I tried to run the exact same command locally, compiled with the same compiler, with same (release) settings and it was fine.

**Comment by TurboGit** [comment]
> Oops! Sorry about that! I thought that was equivalent. And those variables are only meant to be used in the gui, so why it trips up the cli?

Don't be sorry that's not the issue after all :( A false alarm as this is as you say most probably a memory corruption.

**Pull request closed without merging**
