### PR TITLE
collection(tags): avoid a case insensitive possibility.

### PR DESCRIPTION
**Pull request by phweyland**
Small but still a bug. Sorry. Complete #7201

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Thanks !

**Comment by TurboGit** [comment]
Now the tag handling is consistent which is good. But thinking more about this, why a tag should be case sensitive ?

If I have "house", "House" or "HOUSE" why actually not selecting all occurrences of them when selecting "house" ? At the end those are words and do means (or reference) the exact same thing ?

What do you think ?

**Comment by phweyland** [comment]
> If I have "house", "House" or "HOUSE" why actually not selecting all occurrences of them when selecting "house" ? At the end those are words and do means (or reference) the exact same thing ?

I completely agree. But I haven't found the right track for the time being.

I started from the idea (which may be wrong) that house and House are a unique tag (should not coexist in the tags table, like on windows you cannot have both files house.txt and House.txt). 
I've made some test to turn the tags table case insensitive (collate nocase on name). This works for english (26) letters, but not for é and É (Activité and activité are seen as duplicate, but activité and activitÈ are seen as different by SQLite), while g_utf8 routines work well (return == in both cases).
To make sqlite work, we should add ICU features to it. I can have a look to this but that will be another dependency.
Another issue I had was linked to dt language. In English the conversion of tags table sensitive  <-> insensitive works properly, but when dt is in French `DROP table data.tags` (which is one of the steps) doesn't work anymore...

Do you see another track ?
What do you think ?
Do I issue a PR with the current state, just to expose it and get feedback ?

**Comment by phweyland** [comment]
Thinking about a possible other way.
Statement: To group house, House, HOUSE makes sense mainly in collect module. I may want to see all of them in a same collection.

1. Keep the different cases in tags table.
2. The display in collect is in lowered case and group all cases (house, House, ...) under house (case insensitive)
3. In light table, collection.c uses LIKE to get the occurrences 
4. The display in tagging stays case sensitive because house tag is different than House. So we don't change here (export metadata, etc... neither).

In that case we can keep the tags table as is. However, in 3., to get activité, Activité and ActivitÉ in the same query, LIKE must work with non English letters, i.e. we still need to add ICU feature to Sqlite.

**Pull request merged**
