### PR TITLE
maintenance: isnan -> dt_isnan in misc files (NAN removal, part 6)

### PR DESCRIPTION
**Pull request by ralfbrown**
Convert calls to isnan() to optimization-safe dt_isnan().  Not all calls have been replaced to avoid conflicting with other pending PRs (once everything is merged, there should be no more direct isnan() calls in these files).

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by TurboGit** [comment]
A missing include I suppose:

```
 /home/runner/work/darktable/darktable/src/src/imageio/imageio_libraw.c:298:47: fatal error: implicit declaration of function 'dt_isnan' is invalid in C99 [-Wimplicit-function-declaration]
  if(raw->rawdata.color.cam_mul[0] == 0.0f || dt_isnan(raw->rawdata.color.cam_mul[0]) || !raw->rawdata.raw_image)
```

**Comment by ralfbrown** [comment]
Hmm, wonder why common/math.h doesn't get included in that build....

**Review by TurboGit — APPROVED** [review]
All green now, thanks!

**Pull request merged**
