### PR TITLE
dterrahe - cherry picked

### PR DESCRIPTION
**Pull request by TurboGit**

### CODE REVIEW

**Comment by MStraeten** [comment]
breaks macos compilation:
```
In file included from /Users/martinstraeten/src/darktable/src/develop/imageop.h:44:
/Users/martinstraeten/src/darktable/src/dtgtk/togglebutton.h:37:3: fatal error: redefinition of typedef 'GtkDarktableToggleButton' is a C11 feature [-Wtypedef-redefinition]
} GtkDarktableToggleButton;
  ^
```

**Comment by MStraeten** [comment]
maybe specific for macports based builds

**Comment by zisoft** [comment]
Same here, Homebrew package manager:

```
In file included from /Users/mario/src/darktable/src/common/collection.c:27:
In file included from /Users/mario/src/darktable/src/control/control.h:32:
In file included from /Users/mario/src/darktable/src/control/jobs.h:98:
In file included from /Users/mario/src/darktable/src/control/jobs/develop_jobs.h:22:
In file included from /Users/mario/src/darktable/src/develop/develop.h:30:
In file included from /Users/mario/src/darktable/src/develop/imageop.h:44:
/Users/mario/src/darktable/src/dtgtk/togglebutton.h:37:3: fatal error: redefinition of typedef 'GtkDarktableToggleButton' is a C11 feature [-Wtypedef-redefinition]
} GtkDarktableToggleButton;
  ^
/Users/mario/src/darktable/src/dtgtk/togglebutton.h:27:22: note: previous definition is here
G_DECLARE_FINAL_TYPE(GtkDarktableToggleButton, dtgtk_togglebutton, DTGTK, TOGGLEBUTTON, GtkToggleButton)
                     ^
```

**Comment by MStraeten** [comment]
fix is fine, thanks

**Pull request merged**
