### PR TITLE
Update darktable-bench script, sidecar, and documentation

### PR DESCRIPTION
**Pull request by ralfbrown**
New sidecar for v4.2 that includes Sigmoid.
Correctly find the line reporting image load time (strings changed)
Drop slowest run as outlier when at least five runs performed.
Update documentation.

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by todd-prior** [comment]
I found this in my build directory in msys2 and it did run from there.... should it?? It just says command not found... unless its a path issue??

**Comment by ralfbrown** [comment]
Do you have python3 installed?  It's a Python script.
Not familiar with windows, but on Linux you can just invoke the script as path/to/the/script/darktable-bench in the dt source directory and it will find everything it needs.  You can try running the script with the --verbose flag, which will make it print where it is searching for things.

**Comment by ptilopteri** [comment]
read the README.txt file in the same directory.

**Comment by todd-prior** [comment]
> read the README.txt file in the same directory.

Yep I read it and tried from a number of folders... I will see if perhaps it is the python thing... could just be something else as its msys2 on windows ...

**Pull request merged**
