### PR TITLE
collect : limit refresh

### PR DESCRIPTION
**Pull request by AlicVB**
as discussed in #9042 this allow to specify which property has been changed when requesting collection update. This property is then used in collect module to only refresh the treeview if the property is really used inside the query.
That should limit drastically the number of rebuild.

### CODE REVIEW

**Comment by TurboGit** [comment]
Looks good to me ! I'll test tomorrow.

**Comment by ralfbrown** [comment]
Successfully avoids updates for stars and color labels, whether applied by clicking on the image, the bottom-row icon list, or keyboard shortcut.  But star ratings filter and sorting still cause an unconditional rebuild, as do adding/removing tags.

Here's what I successfully tried for the ratings filter (don't know how to make a PR on top of someone else's PR), basically pushing the decision on what property to pass up to `_lib_filter_update_query`s caller:
```
diff --git a/src/libs/tools/filter.c b/src/libs/tools/filter.c
index 7fad678ac..b67c626cf 100644
--- a/src/libs/tools/filter.c
+++ b/src/libs/tools/filter.c
@@ -55,7 +55,7 @@ static void _lib_filter_reverse_button_changed(GtkDarktableToggleButton *widget,
 /* callback for rating comparator combobox change */
 static void _lib_filter_comparator_changed(GtkComboBox *widget, gpointer user_data);
 /* updates the query and redraws the view */
-static void _lib_filter_update_query(dt_lib_module_t *self);
+static void _lib_filter_update_query(dt_lib_module_t *self, dt_collection_properties_t changed_property);
 /* make sure that the comparator button matches what is shown in the filter dropdown */
 static gboolean _lib_filter_sync_combobox_and_comparator(dt_lib_module_t *self);
 /* save the images order if the first collect filter is on tag*/
@@ -300,7 +300,7 @@ static void _lib_filter_combobox_changed(GtkComboBox *widget, gpointer user_data
   _lib_filter_sync_combobox_and_comparator(user_data);
 
   /* update the query and view */
-  _lib_filter_update_query(user_data);
+  _lib_filter_update_query(user_data, DT_COLLECTION_PROP_RATING);
 }
 
 /* save the images order if the first collect filter is on tag*/
@@ -339,14 +339,14 @@ static void _lib_filter_reverse_button_changed(GtkDarktableToggleButton *widget,
   _lib_filter_set_tag_order(user_data);
 
   /* update query and view */
-  _lib_filter_update_query(user_data);
+  _lib_filter_update_query(user_data, DT_COLLECTION_PROP_UNDEF);
 }
 
 static void _lib_filter_comparator_changed(GtkComboBox *widget, gpointer user_data)
 {
   dt_collection_set_rating_comparator(darktable.collection, gtk_combo_box_get_active(widget));
 
-  _lib_filter_update_query(user_data);
+  _lib_filter_update_query(user_data, DT_COLLECTION_PROP_RATING);
 }
 
 static void _lib_filter_sort_combobox_changed(GtkComboBox *widget, gpointer user_data)
@@ -358,16 +358,16 @@ static void _lib_filter_sort_combobox_changed(GtkComboBox *widget, gpointer user
   _lib_filter_set_tag_order(user_data);
 
   /* update the query and view */
-  _lib_filter_update_query(user_data);
+  _lib_filter_update_query(user_data, DT_COLLECTION_PROP_UNDEF);
 }
 
-static void _lib_filter_update_query(dt_lib_module_t *self)
+static void _lib_filter_update_query(dt_lib_module_t *self, dt_collection_properties_t changed_property)
 {
   /* sometimes changes */
   dt_collection_set_query_flags(darktable.collection, COLLECTION_QUERY_FULL);
 
   /* updates query */
-  dt_collection_update_query(darktable.collection, DT_COLLECTION_CHANGE_RELOAD, DT_COLLECTION_PROP_UNDEF, NULL);
+  dt_collection_update_query(darktable.collection, DT_COLLECTION_CHANGE_RELOAD, changed_property, NULL);
 }
 
 static void _lib_filter_reset(dt_lib_module_t *self, gboolean smart_filter)
@@ -416,7 +416,7 @@ static int sort_cb(lua_State *L)
     dt_collection_set_sort(darktable.collection, (uint32_t)value, 0);
     const dt_collection_sort_t sort = dt_collection_get_sort_field(darktable.collection);
     gtk_combo_box_set_active(GTK_COMBO_BOX(d->sort), _filter_get_items(sort));
-    _lib_filter_update_query(self);
+    _lib_filter_update_query(self, DT_COLLECTION_PROP_UNDEF);
   }
   luaA_push(L, dt_collection_sort_t, &tmp);
   return 1;
@@ -437,7 +437,7 @@ static int sort_order_cb(lua_State *L)
     gtk_combo_box_set_active(GTK_COMBO_BOX(d->sort), _filter_get_items(sort));
     gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(d->reverse),
                                dt_collection_get_sort_descending(darktable.collection));
-    _lib_filter_update_query(self);
+    _lib_filter_update_query(self, DT_COLLECTION_PROP_UNDEF);
   }
   luaA_push(L, dt_collection_sort_order_t, &tmp);
   return 1;
@@ -454,7 +454,7 @@ static int rating_cb(lua_State *L)
     luaA_to(L,dt_collection_filter_t,&value,1);
     dt_collection_set_rating(darktable.collection, (uint32_t)value);
     gtk_combo_box_set_active(GTK_COMBO_BOX(d->filter), dt_collection_get_rating(darktable.collection));
-    _lib_filter_update_query(self);
+    _lib_filter_update_query(self, DT_COLLECTION_PROP_RATING);
   }
   luaA_push(L, dt_collection_filter_t, &tmp);
   return 1;
@@ -471,7 +471,7 @@ static int rating_comparator_cb(lua_State *L)
     luaA_to(L,dt_collection_rating_comperator_t,&value,1);
     dt_collection_set_rating_comparator(darktable.collection, (uint32_t)value);
     gtk_combo_box_set_active(GTK_COMBO_BOX(d->comparator), dt_collection_get_rating_comparator(darktable.collection));
-    _lib_filter_update_query(self);
+    _lib_filter_update_query(self, DT_COLLECTION_PROP_RATING);
   }
   luaA_push(L, dt_collection_rating_comperator_t, &tmp);
   return 1;
```

I would suggest adding DT_COLLECTION_PROP_SORT for at least the ascending/descending sort order, which collect.c can then just ignore unconditionally (that's a pure display matter).  Handling the sort-order combobox will be trickier, since a special case is needed at least for the aspect-ratio sort,  but the default case can probably use PROP_SORT as well.

**Comment by AlicVB** [comment]
@ralfbrown : you're right, I'll integrate what you propose if you don't mind...

That said, there's lot of other things we can optimize. In fact, when I've done this PR, in the doubt, I've always put DT_COLLECTION_PROP_UNDEF to be sure to not break anything...

One of the main enhancement we can do would be to handle multiple properties. That would be needed for all history change, which may change "modules" "history" and "aspect_ratio" for example... But that's quite a big change, and I would prefer to keep this PR as simple as possible to avoid regressions at this point in the release cycle !

**Comment by johnny-bit** [comment]
@AlicVB - your proposition about multiple properties sounds great and I'd agree it'd be a big challenge. When I done signal debugging stuff it was also for observations like this to analyze what's going on ;)

so - maybe keep that in mind for 3.8 and have this as good as it gets for 3.6 :)

**Comment by AlicVB** [comment]
> so - maybe keep that in mind for 3.8 and have this as good as it gets for 3.6 :)

that's the plan :)

**Comment by ralfbrown** [comment]
> in the doubt, I've always put DT_COLLECTION_PROP_UNDEF to be sure to not break anything...

Definitely the right approach, especially while in safe mode.

I don't mind that you integrate  what I posted,  that's why I posted the diff.

**Comment by AlicVB** [comment]
@ralfbrown : done :) with the DT_COLLECTION_PROP_SORT ... Thanks for the code ;)

**Comment by phweyland** [comment]
I agree with the fact that DT_COLLECTION_CHANGE_RELOAD (or DT_COLLECTION_CHANGE_NEW_QUERY as well) needs to know what is (are) the change(s).

But that means also that the feature (like import, tags, metadata, ...) has to know that collections should be done on collect/collection side when some change happens.
This is not coherent with other signals which trigger also collect/collection like DT_SIGNAL_TAG_CHANGED, DT_SIGNAL_GEOTAG_CHANGED, ... for which that's collect/collection which decide what to do.

I don't know is the best, but I think there is a  kind of redundancy there.
Or, at least, I'm very often in doubt when it comes to signaling a change from the feature side. 
What do you think ?

**Comment by AlicVB** [comment]
hmmm if I understand well, what you propose would be to have a routine like `dt_collection_property_change(property, list)` that would be call in place of `dt_collection_update_query`. And then inside that new function decide if we need to rerun/rebuild the query or not, depending on the collect params ?

That would great, and would certainly avoid *lot* of unneeded query update !
But at this point in the release cycle, I would prefer to keep things as simple as possible... maybe we need to create a FR so we keep track of the idea and don't forget it ?

**Review by phweyland — APPROVED** [review]
Nothing to add. Looks ok for me.
I've made a quick test. I haven't found any issue.

**Review by TurboGit — APPROVED** [review]
Works for me and looks good. Merging now to ensure more field testing as this touches many places in the code. Thanks !

**Pull request merged**
