### PR TITLE
background colors from CSS instead of hardcoded

### PR DESCRIPTION
**Pull request by moy**
Most of dt's UI is themeable using CSS, and it is tempting to use this
to create a neutral grey or a white theme (see e.g.
https://redmine.darktable.org/issues/11173). Unfortunately, a few color
values are still hardcoded in the source code, hence a full light theme
is only possible by patching the C files and recompiling.

This patch replaces the hardcoded values with code that fetches them
from @define-color definitions in darktable.css. For example, a neutral
grey theme can use:

```CSS
@define-color darkroom_bg_color #777777;
@define-color darkroom_preview_bg_color shade(@darkroom_bg_color, .8);
@define-color lighttable_bg_color @darkroom_bg_color;
@define-color lighttable_preview_bg_color shade(@lighttable_bg_color, .8);
```

The colors are unchanged by default.

@aurelienpierre: I wrote the patch after seeing your message on the mailing list (I can't find the link anymore). Your feedback is welcome.

### CODE REVIEW

**Comment by houz** [comment]
Thanks for starting to work on this! It has been bugging me forever, just not enough to start doing anything about it. 😄
Since there are hardcoded colors used in the expose functions (i.e., drawing the gui) that are called quite often I would prepare the infrastructure to load the known colors at startup into a GHashTable in `dt_gui_gtk.h` and just look them up at runtime.

**Comment by moy** [comment]
Do we need a GHashTable? We know statically which color will be loaded so a simple `struct` would be enough, no?

(It's a real question, you obviously know dt's design much better than me!)

**Comment by houz** [comment]
Sure, an array of colors, together with an enum that maps human readable names to array indices would work, too.

**Comment by moy** [comment]
OK, I pushed a new version which should be better. Actually, there was already a similar mechanism for `bgcolor` in `gtk.c`, my code now hooks at the same place.

I didn't add a CSS key for `DT_GUI_COLOR_BG` because I don't understand where the color is supposed to appear, so I'm not sure it would be useful and what name would be appropriate. If needed, a CSS key can be added straightforwardly later.

**Comment by houz** [comment]
This looks good. Just one thing: there is that repetition of code like

    GdkRGBA bc = darktable.gui->colors[DT_GUI_COLOR_DARKROOM_BG];
    cairo_set_source_rgb(cr, bc.red, bc.green, bc.blue);

which should probably be put into an inlineable function like `dt_gui_gtk_set_source_rgb(cairo_t *cr, dt_gui_color_t color)` (and please come up with a shorter name for it 😃).

**Comment by moy** [comment]
Done, and indeed the patch looks much nicer now. I just removed the `_rgb` suffix from your `dt_gui_gtk_set_source_rgb` name suggestion.

**Comment by houz** [comment]
The `_rgb` is important. Maybe drop the `_gtk` and make it `dt_gui_set_source_rgb()`. Otoh, I like that the function names make it (in general) clear in which file the code is. Which brings us back to `dt_gui_gtk_set_source_rgb()`. It seems we need some input from others. @LebedevRI, @hanatos?

**Comment by LebedevRI** [comment]
What about using native styling abilities, like with `#iop-plugin-ui`?

**Comment by moy** [comment]
About the name: the `rgb` part in `cairo_set_source_rgb` refers to the fact that the color is given as r, g and b, as opposed to `cairo_set_source_rgba`. Here we don't provide the values as r, g and b, but as an instance of an enum. The fact that rgb is used internally is an implementation detail, there's no need to expose it to the user.

**Comment by moy** [comment]
> What about using native styling abilities, like with #iop-plugin-ui?

`iop-plugin-ui` is drawn in Gtk so the code lets Gtk do the styling. For background colors, the existing code draws them using Cairo. I don't think there's a way to let Cairo do the styling from CSS.

I don't know if there's a good reason to use Cairo over Gtk here, but switching to Gtk would imply a rather intrusive change in the code, so my patch just went the simpler way: get the colors from Gtk and feed them to Cairo.

**Comment by houz** [comment]
No, the `rgb` part isn't to differentiate from `rgba` but to make it clear that we are not wrapping `cairo_set_source` (https://www.cairographics.org/manual/cairo-cairo-t.html#cairo-set-source).

**Comment by moy** [comment]
I still consider the fact that we use `cairo_set_source_rgb` internally as an implementation detail, we could very well use another `cairo_set_source*` function internally. The caller doesn't need to know which function is used internally to use `dt_gui_gtk_set_source`. I don't think the function name should reflect this implementation detail.

**Comment by LebedevRI** [comment]
For me the rgb part is there to tell what the function expects as a parameter, the color? pattern? kitten?
So rgb should stay.

**Comment by moy** [comment]
Since the argument is precisely not RGB, I don't really get the argument (I would consider that as a counter-argument actually, I find it really misleading to have a `_rgb` suffix for a function that doesn't take RGB colors). But I seem to be the only one to think like that, so let's re-add this `_rgb` suffix.

**Comment by moy** [comment]
It was probably not clear from my previous message, but I pushed a version that should address all your comments. I think it's ready for merging. If not, let me know if I can do something.

Thanks,

**Comment by houz** [comment]
Thanks a lot. About the naming of the function, if we want to hide the fact that it's loading an RGB value via cairo we should probably also hide the `_source_` part. But for now it works and we can think about naming it differently another day. There are more places where names are suboptimal. 😃

**Pull request merged**
