### PR TITLE
snapshots : make them dynamic and resizable

### LINKED ISSUE #2694: Snapshots: naming, identify and zooming
**Is your feature request related to a problem? Please describe.**
I have some difficulties identifying snapshots. Actually, I forgot often which is the snapshot and which is the picture (especially when I rotate upside-down the middle line).
I'd like the possibility to rename the snapshot as I can rename the iop modules on the right.

**Solution you'd like**

I'd like to have:

- The possibility to assign a name to the snapshot
- The snapshot's name superimposed to the image and something like "original" on the other part.
- The possibility to zoom in and out both part of the image (depending on where the mouse pointer is)

**Alternatives I've considered**
It seems there is not a real alternative so far. The only way seems to switch on/off the snapshot button.

### LINKED ISSUE #11471: FR: Side by side snapshot view
I am thinking something like the culling mode in the lighttable, but for snapshots inside the darkroom. Basically two full images next to each other. One being static (snapshot), and the other editable. 

This is useful when working with reference images. You could have a snapshot of any image right next to the one one you are editing, and make changes accordingly. This can be useful to unify a set of images, or to try to replicate a particular look. 

The current implementation of snapshots is useful for before/after comparison of the same image. 

Would this be possible?

### PR DESCRIPTION
**Pull request by TurboGit**
This introduce a dynamically created snapshot, to note:
1. resize & zooming supported
2. this does not use a file anymore (should fix some windows issues)
3. each snapshot are cached
4. the image buffers and surface are created on the fly
5. the vertical mode & horizontal mode are working
6. the snapshot tooltipe now contains the image filename
7. fixes the currently selected snapshot when adding a new one and a snapshot is already selected
8. works on all zoom (FIT to 100%) and even in closeup 1600%

Fixes #2694.
Fixes #11471.

### CODE REVIEW

**Comment by TurboGit** [comment]
At this stage this is ready for merging. The only "minor" issue is that we have on some pictures a very little offset (~1 pixel) between the snapshot and the actual image. This is a rounding issue as the computation of the snapshot and the actual dr display is not using the fully same code.

To me this is not a big deal and the overall experience if far better. I'd like some external review before merging. TIA.

**Comment by elstoc** [comment]
> This is a rounding issue as the computation of the snapshot and _the actual dr display is not using the fully same code_.

This is my concern here. If this is using similar code to the "duplicate manager" then I am worried that the snapshot will no longer be guaranteed to be comparable with the current edit, especially where testing things like sharpening/denoising strategies. Indeed I see subtle differences between images when I compare them (comparing a snapshot of the current edit to the current edit in the darkroom view). See my comments on related feature request (https://github.com/darktable-org/darktable/issues/2784) and my issues (https://github.com/darktable-org/darktable/issues/4638 and https://github.com/darktable-org/darktable/pull/5453). I would still much prefer to rely on the "screenshot" method of the current functionality; as it is I really can't be certain I'm comparing like with like. Perhaps the previous method could be enabled as a secondary option?

> a very little offset (~1 pixel) between the snapshot and the actual image

I've seen this on all the images I've tested and it's quite off-putting.

**Comment by TurboGit** [comment]
@elstoc : What I meant is that the computation of the position on the canvas is slightly different. But the rendering is the same (using a pixelpipe initialized the same way). On my side I definitly have the very same and comparable image. On image where I don't have the one pixel shift, moving the separator I see no difference at all.

Do you have a picture to share?

**Comment by elstoc** [comment]
Here's an example, extreme I'll admit, where I think the issue is that diffuse/sharpen does not appear to be enabled in the snapshot at all. I pushed the parameters of diffuse/sharpen to make it more obvious.:

Screenshot_2022-10-29_00-48-02

Could it be the snapshot is using fast pipe mode? Apart from that, you say it uses "a pixelpipe initialized in the same way" but you also say "the computation of the snapshot and the actual dr display is not using the fully same code". Could you be more specific on the differences? I'm just concerned that before the snapshot was always definitely pixel-perfect (because it was a screenshot) and now it might be different, and I don't know how much to trust it.

Either way though, I see the pixel shift to some extent or another on almost every image and it's very distracting. IMO this needs to be fixed or the old method retained as an option until it can be perfected.

Another thing is that the display shows "imageid/history number" in the module. I only got what the first number was when I looked at your comment above and it confused me. The image ID is an internal thing used to maintain database consistency and I'm guessing this won't mean anything to anyone - IMO stuff like that shouldn't really be exposed in the UI except in the image information module. Perhaps you could include a tooltip that contains the image filename instead?

**Comment by wpferguson** [comment]
The lua snapshot code doesn't appear to work with the new snapshot module.

**Comment by TurboGit** [comment]
> The lua snapshot code doesn't appear to work with the new snapshot module.

Yes, for now I have deactivated the Lua code. I'll rework it when the final solution is stable.

**Comment by TurboGit** [comment]
@elstoc : Indeed, huge difference let me try to reproduce.

To clarify the current implementation:
- The snapshot _rendering_ use a standard pipe as the darkroom. BTW, this is using the same code used for exporting images, but instead of going through a format container (jpeg, tiff...) the raw data is used for display. If we have different output here it means that we have a fully broken export in darktable, and we know this is not the case.
- The snapshot _display_ use the same cairo surface with the same filter level as used in darkroom.
- The snapshot positioning is not using the very same code and we could indeed have a slight offset ~1 pix due to rounding.

**Comment by TurboGit** [comment]
@elstoc : Hum something really wrong with my last changes as the snapshot does not work anymore...

I have found the stupid issue, please try again the snapshot should be now identical.

**Comment by TurboGit** [comment]
@elstoc : I have now implemented your idea about the tooltip. Indeed the image-id is internal.

**Comment by elstoc** [comment]
Ok, so now the image is the same as the current edit. But the offset remains (for me this is a big issue). Also, at full zoom level it takes _ages_ to make the preview if I have heavy modules in use (presumably it's basically doing a full export). This is with a fairly decent GPU as well (8Gb Nvidia 1080).

For my example image (with diffuse/sharpen) there seems to be an issue whereby the snapshot only works when I select the top of the stack _without changing anything_. For example, if I enter a new image, reset the stack, add diffuse/sharpen (deblur hard), zoom, and snapshot the last module in the pipe, the diffuse/sharpen module is still not enabled in the snapshot. If I exit the darkroom and re-enter I can correctly select and snapshot the last module in the pipe (though it takes some 7 or 8 seconds for the snapshot to appear). Again, this is much slower than the normal darkroom screen update and with OpenCL disabled it takes more like 20 seconds. For many users this will make the use of snapshot functionality impractical.

**Comment by TurboGit** [comment]
> For example, if I enter a new image, reset the stack, add diffuse/sharpen (deblur hard), zoom, and snapshot the last module in the pipe, the diffuse/sharpen module is still not enabled in the snapshot.

I can reproduce, I'll have a look.

For the pixel-shift we may want to use the old snapshot method. This could be cached and used for the same zoom level. But for the other zoom-level we have to resort on computing it dynamically. At least this will be identical with what is currently supported.

**Comment by elstoc** [comment]
> But for the other zoom-level we have to resort on computing it dynamically. At least this will be identical with what is currently supported.

I'd still like to include the ability to disable panning/zooming entirely, perhaps as a tweak in the performance section. At the moment as soon as anyone enables the snapshot on a different pan/zoom to where it was taken, it will trigger a long-running calculation and will not be possible to return to the original snapshot/screenshot - which will be annoying. Maybe it could always default to the original zoom/pan location (when enabling) and use the screenshot. Then only recalc if you decide to pan/zoom _from within the snapshot view functionality_.

This is all still far from ideal though, and I don't think we're ever going to make this sort of thing performant. The current functionality does everything I need and, for me, the new functionality is not worth the performance penalty and pixel-shift.

**Comment by TurboGit** [comment]
@jenshannoschwalm @dtorop : Maybe you have an idea about this. The speed issue discussed here is because when zooming we do the actual computation for a larger image (scaled). At some point the modules that are CPU intensive (diffuse&sharpen for example) have so many pixels to handle that it becomes slow to process the snapshot.

One idea would be to introduce ROI in imageio export (I'm using `dt_imageio_export_with_flags()`). Do you think this is possible? I'm really lost on this part.

**Comment by TurboGit** [comment]
> For example, if I enter a new image, reset the stack, add diffuse/sharpen (deblur hard), zoom, and snapshot the last module in the pipe, the diffuse/sharpen module is still not enabled in the snapshot.

This is now fixed.

**Comment by jenshannoschwalm** [comment]
I can't really understand the code changes while on mobile for some more days. Wouldn't it be easier to introduce and make use of a duplicate of the full pipe?

**Comment by TurboGit** [comment]
@jenshannoschwalm : The imageio code does use a dev pipe, not fully duplicate of the darkroom full pipe though. Are you suggesting to introduce a new full-pipe (like the one for second window) just for the snapshot lib?

Anyway to me this looks like it won't do for 4.2. Let's re-discuss this when you're back in some days.

**Comment by elstoc** [comment]
> first okish version for 4.2

I haven't tested it (will try to test in the next couple of days" but if your description suggests it might still be better waiting for 4.4. We shouldn't be putting anything that's just "okish" in releases :)

**Comment by TurboGit** [comment]
> > first okish version for 4.2
> 
> I haven't tested it (will try to test in the next couple of days) but your description suggests it might still be better waiting for 4.4. We shouldn't be putting anything that's just "okish" in releases :)

Sure, but the _okish_ is to me far better than the current situation :)

**Comment by TurboGit** [comment]
@elstoc : Don't spend time testing, I think the actual ROI is not properly set after all.

**Comment by TurboGit** [comment]
@elstoc : You can test again when you have some time. I have fully reworked this and now using a standard pixelpipe. There is no more pixelshift and it is using a proper ROI as the darkroom view. The code is quite simpler now. My first dive into the pixelpipe world :)

**Comment by elstoc** [comment]
Just a quick test today and it looks much better. A couple of comments from my drive-by testing...

If you're going to support zooming, you should also support panning. If I move the zoom box in the navigation module the current edit pans but the snapshot does not; similarly if I use the arrow keys to pan. There's also a shortcut that allows you to pan with the mouse while overlays are enabled (e.g. to use when color pickers or shapes are on the screen) and this should also allow the image to be panned while snapshots are enabled.

Also (corner case I admit) we have lost one feature with this change. If I take a snapshot and then clear history, the snapshot now refers to a non-existent history item and should probably be deleted (enabling the snapshot displays something that's definitely not the history step I took the snapshot with). With current functionality, because it's a screenshot, it doesn't matter.

Finally, when viewing on a different image than the one on which the snapshot was taken, I would recommend some sort of visual indication (perhaps a different colour or asterisk against the snapshot description?) that it's from a different image (in addition to the tooltip), just for when people are working with sets of nearly identical exposures.

**Comment by elstoc** [comment]
Not for right now, but I guess most of these code changes could be ported to the duplicate manager, which at the moment is slow and uses a different pipe (meaning that results are not comparable to the current darkroom view).

**Comment by TurboGit** [comment]
@wpferguson : I have enabled back the Lua code. As there is no more filename for a snapshot I have removed the corresponding Lua binding. Can you double check that I didn't messed the Lua support? TIA.

**Comment by TurboGit** [comment]
@elstoc : 
- panning is supported.
- snapshots removed when history clear/compressed

The last point is difficult (visual indication). That was my idea when I had introduced the image-id as part of the snapshot name. I'll see if I can do something...

**Comment by elstoc** [comment]
Better again (this is getting close to ready now). Still doesn't support click+drag to pan and the "snapshot" side flashes (to grey background) when panning/zooming. Given that the "current edit" doesn't flash at all perhaps there's some additional caching that can be done to speed it up (failing that it could display the current edit full-screen - instead of grey - until the snapshot has updated)?

**Comment by TurboGit** [comment]
@elstoc : I have put a visual indication for snapshots of others images. not really nice ui wise... let's see what we can do there! Any proposal?

**Comment by elstoc** [comment]
> not really nice ui wise

Agreed. I'd say a two-stage approach

1. prefix the description with a pair of asterisks, for example `**monochrome (14)`
2. amend the tooltip so that it only appears when the snapshot is not taken from the current image and change the tooltip to say `** this snapshot was taken from <image-name>`.

**Comment by elstoc** [comment]
Yeah that's much better. Just the two (perhaps three) points to be addressed:

- panning with click+drag
- grey-screen while updating
- perhaps some caching might improve the update speed?

**Comment by TurboGit** [comment]
I have fixed the display when the iso12646 mode is activated.

**Comment by TurboGit** [comment]
> * panning with click+drag

This has never been supported, why not if I have time.

> * grey-screen while updating

Yes, not easy as this update is not asynchronous.

> * perhaps some caching might improve the update speed?

I thought about this, but an image surface for each zoom level and this for all snapshot will take quite a bit of memory.

**Comment by elstoc** [comment]
> This has never been supported

Yes, but then panning never worked either because the snapshot no longer lined up

**Comment by TurboGit** [comment]
@elstoc : I have fixed the grey-screen, should be better now.

**Comment by TurboGit** [comment]
@elstoc : And now panning is supported. Hope you'll let me sleep a bit :) Well, thanks for the review, really just help getting dt better.

**Comment by elstoc** [comment]
Better and better...

> And now panning is supported

I'm reluctant to provide more feedback now, but then sleep is overrated :) so here goes...

I see from the code that you've used Ctrl+click+drag for panning with the mouse. I think this might be better to use the same shortcut as for pan/zoom with masks - the shortcut action is "views/darkroom/allow to pan and zoom while editing masks".

Also, when you pan by dragging the highlighted rectangle on the navigation module, the whole image moves (including the snapshot half) but when click+drag-panning only the current edit moves, with the snapshot half only updating after a delay.

Honestly though, we're into nit-picky stuff now. This is a massive improvement over the current functionality, and one I was convinced would be virtually impossible to do without much more rework than this. Great work.

**Comment by TurboGit** [comment]
The action is named : `"allow to pan & zoom while editing masks"`

So we'll have to rename it.

@dterrahe : How can I check a specific shortcut here the action above which is mapped with GDK_KEY_a. This is done on darkroom:

```
  ac = dt_action_define(sa, NULL, N_("allow to pan & zoom while editing masks"), NULL, &dt_action_def_skip_mouse);
  dt_shortcut_register(ac, 0, DT_ACTION_EFFECT_HOLD, GDK_KEY_a, 0);

```
I need to check in lib module snapshots.c that the specific key GDK_KEY_a (or whatever key has been mapped to this action) is pressed.

**Comment by elstoc** [comment]
> So we'll have to rename it.

I thought it was already used in other contexts, but now I'm not so sure. Perhaps Ctrl+click+drag is fine.

**Comment by dterrahe** [comment]
@TurboGit as long as the shortcut is pressed, the variable `darktable.develop->darkroom_skip_mouse_events` will be TRUE, so you just have to check that. A search will give examples.

I haven't looked at this at all yet, because I hardly ever use snapshots since it was hardly useful without flexible zooming. Now catching up on the discussion I'm getting curious! Sounds like really good work.

**Comment by TurboGit** [comment]
Thanks! Now the panning is done using the standard "escape" key.

**Comment by TurboGit** [comment]
@elstoc : should be ready to merging now :)

Thanks @dterrahe!

**Comment by elstoc** [comment]
The delayed update on dragging is still not ideal (it should show the current edit - panned - and then update, rather than just leaving the current edit static) but I'm fine to raise a separate issue for that if you like.

This is already way better than I thought possible.

**Comment by TurboGit** [comment]
@elstoc : Yes I think this is enough for this PR. Let's raise two issues and we'll see if we have time for 4.2. TIA.

**Comment by TurboGit** [comment]
@elstoc : Note that I have also fixed the duplicate preview by using the new support routine added here. This is a lot of simplification. I'll create a PR soon.

**Comment by TurboGit** [comment]
@elstoc : I had an idea... and then we now show the current edit - panned - and then update :)

**Comment by elstoc** [comment]
Perfect!

**Comment by TurboGit** [comment]
Merged, this will give us some time for field testing.

**Comment by wpferguson** [comment]
The lua part works as well as it worked in master, before the merge.  There are a couple of issues with the lua code, but they were pre-existing.

**Comment by jenshannoschwalm** [comment]
Have been away for some days, first thing now was to try this - whow - it's a  huge progress!

**Comment by TurboGit** [comment]
@jenshannoschwalm : Thanks! This has been itching me since a long time... I had always been reluctant to tackle this feature as it seems almost impossible to do properly. After reading a bit more the develop/pixelpipe code I thought of a way to achieve this goal. Fact is that my first try was not correct as based on the imageio support which is trying hard to create an external picture with the proper size (read messing with the image width & height). After that I have decided to extract from imageio the code running the pixelpipe... and at this stage it becomes far easier to get proper aligned snapshots.

I have used this same code for the duplicates (see today merge).

And I have now as new PR which is code simplification for darkroom by using the same (now shared) code to display an image surface. If you have some free time please review/test this:

https://github.com/darktable-org/darktable/pull/12761

I hope I didn't mess the darkroom :)

**Comment by jenshannoschwalm** [comment]
Will do after pushing a better pr for highlights...

**Comment by todd-prior** [comment]
Sorry I see that the image is panning when I move the navigation box...tried a few mouse actions and could not seem to drag the image.... I have likely missed something simple...

**Comment by ptilopteri** [comment]
> Sorry I see that the image is panning when I move the navigation box...tried a few mouse actions and could not seem to drag the image.... I have likely missed something simple...

the arrow keys will move the displayed portion of the image, and I believe holding the "a" depressed and dragging with the mouse works.

**Comment by todd-prior** [comment]
> > Sorry I see that the image is panning when I move the navigation box...tried a few mouse actions and could not seem to drag the image.... I have likely missed something simple...
> 
> the arrow keys will move the displayed portion of the image, and I believe holding the "a" depressed and dragging with the mouse works.

Thanks....I think a is also the tone eq right ....I had forgotten about that ...thx

**Comment by TurboGit** [comment]
@todd-prior : And 'a' is also the way to pan when creating mask.

**Comment by dterrahe** [comment]
This is really wonderful stuff @TurboGit

**Pull request merged**
