### PR TITLE
po/fix paste parts

### PR DESCRIPTION
**Pull request by TurboGit**

### CODE REVIEW

**Comment by TurboGit** [comment]
@AlicVB : I did not found a better fix, was quite tricky to investigate. At least if there is no better fix this could go in 3.2 as the corresponding issue is a show stopper for the release.

**Comment by TurboGit** [comment]
> what about the closing button of the selection widget?

It returns the cancel values as far as I know. Note that this check was there before and has always been working.

**Comment by jenshannoschwalm** [comment]
When I tried to find the problem for this issue  it also happened when pressing that.

**Comment by TurboGit** [comment]
You mean when quitting using the top-right cross in the dialog's title bar ?

**Comment by TurboGit** [comment]
Ok now we check for != OK which ensure that the paste is done only when OK is received. Should be safer anyway.

**Comment by TurboGit** [comment]
Thanks for the review @AlicVB .

**Pull request merged**
