### PR TITLE
po/fix liquify

### PR DESCRIPTION
**Pull request by TurboGit**
I'm don't know if we can do better here, but at least this works by drawing interpolated path a user would expect.

### CODE REVIEW

**Comment by TurboGit** [comment]
Tested with line, curve and doing an inner or outer interpolated strength, all seems good:

image

**Comment by toschi23** [comment]
I am sorry if this is the wrong place to comment. I am very new to open source github workflow. 
I also do not know how I can check this version out to test for some edge cases.
From what I can tell with my limited C and C++ knowledge, you check, if the two vectors are in the top left and lower left quadrant. And go from there, while this certainly catches allmost all off the cases a cleaner way in my opinion would be to check if the difference in angles is above 180° or π respectively. The difference appears if one of the angles if the vectors point to diagonal quadrants and are either slightly bigger or slightly smaller than 180° / π. 
I am completely aware, that this is a super uncommon edge case, but the math would be cleaner. Also the code might benefit from less if statements. 
I still struggle with the last line of your code, e.g. how phi gets computed in line 714.
From my experience coding python code I myself would have come up with a shortest angle calculation along the lines of:
`shortest_angle = ((arg2-arg1) + M_PI_F) % (2*M_PI_F) - M_PI_F`

**Comment by toschi23** [comment]
I am sorry for spamming, but I just understood what the last line does and everything makes more sense now. I still believe instead of doing the two if statements this way, checking first if the angles are more than 180° apart makes more sense, to get all the egde cases.
After that check another if clause whether arg1 or arg2 is bigger should solve the rest.

**Comment by TurboGit** [comment]
@toschi23 : Fact is that all works well even for angles more that 180° except when crossing PI (on the west).

```
             -PI/2
                ^
                |
                |            -
                |
PI <----------- x -------------> 0
                |
                |            +
                |
                v
              PI/2
```

**Comment by TurboGit** [comment]
As a comparison here how it looks like without the patch on current master:

image

**Comment by TurboGit** [comment]
Don't know if it is the best solution, but it fixes a bad issue, merging.

**Comment by aurelienpierre** [comment]
FWIW, the `complex` type needs to be replaced by `float[2]` because no compiler can vectorize complex points handling as of Clang 11 and GCC11.

**Pull request merged**
