### PR TITLE
[GUI] A couple of spelling corrections (HDR, LDR)

### PR DESCRIPTION
**Pull request by victoryforce**

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by victoryforce** [comment]
@HSUfineprint I was considering this too. But unfortunately, I cannot say with certainty which term is at least used more often in relation to image formats. Yes, of course there is Google Books Ngram Viewer, but the problem is that these acronyms have other meanings that are not related to dynamic range. In addition, I got the impression that the HDR / SDR pair is more common in texts related to video and TV technologies. When we search for an HDR / LDR pair, we see texts related to photography more often.

In any case, I think we should not make a decision on this issue in a hurry before the string freeze.

Maybe @TurboGit  and @elstoc  would like to comment?

**Comment by elstoc** [comment]
Yeah, I'm not sure.

> I got the impression that the HDR / SDR pair is more common in texts related to video and TV technologies

That's my impression too

**Comment by HSUfineprint** [comment]
Adobe uses SDR in Camera Raw's HDR technology preview article.
https://helpx.adobe.com/camera-raw/using/hdr-output.html

If we decide to use LDR, should we change the tooltip of filmic module for consistancy?
`#: ../src/iop/filmicrgb.c:356msgid ""
`"apply a view transform to prepare the scene-referred pipeline\n"`
`"for display on SDR screens and paper prints\n"`
`"while preventing clipping in non-destructive ways"`

Yes, the SDR terms mainly mean display's dynamic (in aforementioned situations). But I worry about users feel confused.

**Comment by victoryforce** [comment]
> Adobe used SDR in Camera Raw's HDR technology preview article. https://helpx.adobe.com/camera-raw/using/hdr-output.html

Yes, and in this article, the term SDR is used in relation to displays: "High Dynamic Range (HDR) displays offer greater brightness and contrast than Standard Dynamic Range (SDR) displays."

Therefore, it is logical to use the term SDR here, since LDR is practically not used when describing TV and display technologies. In these areas, we talk about normal, _standard_ brightness and contrast and high.

A different situation has developed in the field of image processing. Here, historically, no one considered 8 bits per channel as some kind of "standardized bit depth". Therefore, a rather logical terminology has developed here: low (bit depth) as opposed to high.

> If we decide to use LDR, should we change the tooltip of filmic module for consistancy?
> 
> filmicrgb.c:
> 
> ```
> return dt_iop_set_description(self, _("apply a view transform to prepare the scene-referred pipeline\n"
>                                       "for display on SDR screens and paper prints\n"
>                                       "while preventing clipping in non-destructive ways"),
> ```
> 
> Yes, the SDR terms mainly mean display's dynamic (in aforementioned situations). But I worry about users feel confused.

It doesn't take much for users to be confused. There will be users who have never heard of SDR or LDR, but only know about HDR from smart TV ads (and then only in the context of HDR10, HDR10+). Not sure it's worth sacrificing terminology accuracy for the comfort of uneducated users.

**Comment by HSUfineprint** [comment]
It's questionable LDR is more accurate then SDR. We processed tone mapping for printing and/or display in traditional limited media dynamic range. Until HDR came out. People needs a term for those not HDR image formats and devices. As to describe traditional or original DR, using Normal or Standard is very reasonable. Low is just a antonym to High. And bit depth is not absolutely about DR. A 16 bit integer TIFF is LDR image, 10 bit float AVIF could be HDR image.

But we are not dictionary editors. I'll leave it as it. Let's move on.

**Pull request merged**
