### PR TITLE
Manual lens vignette correction

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Rationale: As we all know the vignetting correction based on lensfun data is often not
included or good enough.
For camera/lens combinations with available and dt-supported embedded metadata
the situation is somewhat better.

As discussed with @s7habo the missing correction is a showstopper for an all-in-darktable
workflow for quite a number of images.

As the maths models for lensfun vs embedded differ significantly and both are not easy to be
controlled via additional gui parameters a different way has been chosen here.

An "additional manual-vignette pre-processing step" has been implemented, the modified data are
further processed by the chosen lens correction model.
BTW this is the same way as done in RT, also the tanh() based model for optical vignetting
was found there.

We have 3 GUI controls in a collapsible section
1. intensity - amount of vignetting correction
2. radius - percentage of image size to be corrected
3. strength - the "steepness" of correction "outside" of the radius

Some details of implementation:
1. As the maths model is quite computing intensive we do a linear spline on precalculated
   data for radius.
2. The spline data are checked and updated at runtime only if radius or strength had been changed,
   this is checked via a hash.
3. We have a vignette-mask visualizer at the intensity slider
4. lens module version had to be bumped again (a note to testers, lens presets are updated)
5. I chose to __not-implement__ any centre-displacement as that requirement seems to be **very** rare
   and would blow-up the UI even more.

As i am definitely not the Gtk wizard, i would appreciate any UI improvements to be done after
this pr.

### CODE REVIEW

**Comment by HSUfineprint** [comment]
not testing this yet, just a reminder of strings

We changed vignetting module strings in https://github.com/darktable-org/darktable/pull/13034, maybe you want to take a look to keep the consistency.

**Comment by jenshannoschwalm** [comment]
> We changed vignetting module strings in #13034, maybe you want to take a look to keep the consistency.

I looked into that and for me the "wording" in this pr would be ok but wouldn't have a problem with better suggestions.

**Comment by TurboGit** [comment]
When 

> * intensity - amount of vignetting correction
> 
> * radius - percentage of image size to be corrected
> 
> * strength - the "steepness" of correction "outside" of the radius

Hard for me to see a diff in intensity & strength, so maybe:

- strength
- radius
- fall-off strength (or steepness?)

To match what is done for vignetting module?

**Comment by jenshannoschwalm** [comment]
You mean the wording?

**Comment by jenshannoschwalm** [comment]
Latest commit includes the suggested better wording of UI parameters, for the sake of code readability also the according parameters have been renamed

**Review by TurboGit — APPROVED** [review]
Works for me. Thanks!

**Comment by s7habo** [comment]
It works great! 

grafik

grafik

Darktable is now complete for me. Thanks a lot @jenshannoschwalm , @TurboGit !!

**Comment by jenshannoschwalm** [comment]
@elstoc i will post a short description for release notes and some longer text for the manual.

**Comment by jenshannoschwalm** [comment]
@TurboGit Release note: A manually controlled vignette correction has been added tot the lens module.

@elstoc for the docs maybe 
_____________________________________________________________
As we don't have full vignetting correction available via the provided lensfun or embedded data we provide an additional correction controlled manually via sliders. The effect of correction can be visualized via a mask button.

The algorithm is using a simple sinh model and for simplicity always assumes a centered vignette. 
**strength** overall strength of effect
**radius** defines the unchanged portion of the image with a fall-off **steepness** for the out-of-radius part.
_____________________________________________________________

???

**Pull request merged**
