### PR TITLE
Check for valid pointer while dynlib loading

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
As specified in the refs for g_module_symbol() it is valid to return a NULL pointer as success.

So we also do a check for that condition and only return TRUE if we have a valid function pointer.

Related to #14061 but can't test here as drivers work. At least that could be a scenario related to "buggy" CL drivers crashing.

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
In release note: Fixing OpenCL library loading in case of not fully implemented required symbols

**Comment by parafin** [comment]
AFAIK NULL is returned if the symbol is present and it points to 0 address. It’s quite hard to produce a dynamic library with such symbol, so IMHO it’s an  unlikely situation. Note that non-NULL pointers may as well be invalid (and NULL pointer can be a valid address in rare cases;) ).

**Review by TurboGit — APPROVED** [review]
Thans! Doesn't hurt to have more debug information if something goes wrong.

**Comment by jenshannoschwalm** [comment]
> AFAIK NULL is returned if the symbol is present and it points to 0 address. It’s quite hard to produce a dynamic library with such symbol, so IMHO it’s an unlikely situation.

Right. At least i tried via manually malconfiguring the OCL loader and could generate a situation where the symbol was loaded but the pointer was NULL in that case. That might be happening if the systems opencl setting is wrong. For osx we checked that already btw.

> Note that non-NULL pointers may as well be invalid
How to test that?

**Comment by parafin** [comment]
If it crashes on access, then it's invalid;)

**Pull request merged**
