### PR TITLE
new icon for configure shortcuts in top panel

### PR DESCRIPTION
**Pull request by Mark-64**
This is a proposal for a new "configure shortcuts" icon in top panel
See discussion in #9483 
image

### CODE REVIEW

**Comment by TurboGit** [comment]
The arrow is what is used on desktop icons when it is a shortcut on old windows (I have stopped using Windows long time ago). Is that still the case? The icon here is ok to me, but previous was also ok to me, finding good icon is hard. So let's see what others think about this.

**Comment by Mark-64** [comment]
The pencil is kind of controversial here, I have in mind a couple of alternatives, just give me time

**Comment by Mark-64** [comment]
Ok, here are possible alternatives:
1) keep the arrow, but replace the pencil with a small sign indicating a new thing:
a) a plus sign
b) a "shine" sign like 
immagine
or 
immagine
whole meaning being "new shortcut"

2) replace also the arrow with a lightning sign
immagine
to convey the "accelerator" concept

Opinions?

**Comment by Nilvus** [comment]
We need to use something just more logical and simple: a keyboard icon, like in most software or configuration ones in OS. So icons like those ones would be better and clear for users:

https://icons.iconarchive.com/icons/vcferreira/firefox-os/128/keyboard-icon.png
https://maxcdn.icons8.com/Share/icon/p1em/Computer_Hardware/keyboard1600.png

**Comment by johnny-bit** [comment]
@Nilvus - I proposed keyboard + arrow in #9689 . I'll try to finish it up today and see how it works out.

**Comment by Nilvus** [comment]
> @Nilvus - I proposed keyboard + arrow in #9689 . I'll try to finish it up today and see how it works out.

I see that but I agree with @TurboGit: the icon is not well balanced and I don't see why the arrow. Another proposal could be some midi keyboard icon that is near a keyboard one. Like that icon:

https://thumbs.dreamstime.com/z/midi-keyboard-line-icon-midi-keyboard-line-icon-digital-piano-keys-linear-style-sign-mobile-concept-web-design-synthesizer-174010974.jpg

**Comment by dterrahe** [comment]
I think midi is irrelevant for most people and would be too confusing in an icon. Simple keyboard would work for me.

**Comment by Nilvus** [comment]
> I think midi is irrelevant for most people and would be too confusing in an icon. Simple keyboard would work for me.

I'm ok for simple keyboard

**Comment by johnny-bit** [comment]
Then I'll do simple keyboard then :D

**Comment by Mark-64** [comment]
ok, closing here then

**Pull request closed without merging**
