### PR TITLE
legacy_presets: remove foreign_keys tweaking.

### PR DESCRIPTION
**Pull request by TurboGit**

### CODE REVIEW

**Comment by HansBull** [comment]
Well since I don't see any foreign keys affected by this mass insert, switching foreign keys off and on can be removed. 

But as the comment on line 1125 says: `a bit stupid, deletes and re-inserts every time :(` during startup.

**Comment by TurboGit** [comment]
That's also my thinking. I'm even wondering if legacy_presets is still needed, I've completely lost track of why it exists, it was there when I joined the project. Maybe some Git archeology will tell us. Anyway, I'll merge this PR as we won't have anymore a foreign_keys tweak here.

**Comment by parafin** [comment]
legacy_presets come from version 1.1: https://www.darktable.org/about/faq/#faq-old-presets

It's a dump of all built-in presets that existed at that point so that they could be added to the history stack when opening old xmp files. Not-auto-applied presets are of no use there, but I guess it was easier to just dump the whole table...

**Comment by TurboGit** [comment]
@parafin : Thanks for the reference ! Didn't know about this.

So first I will remove the non auto-applied preset from the list here. This will save some cycles when starting dt by removing some insert into this table.

Second, I'm wondering in fact if we still want to support that. Actually, pictures edited before 1.1 are probably very very rare now and maybe it would be better to revisit the edits of those pictures if not ok. Also I don't think the base curve presets have changed since then (to be confirmed) and those are counting for the vast majority of entries in legacy_presets.

How does that sound to you ?

**Comment by parafin** [comment]
Removing non-auto-applied presets is IMHO safe.

Removing base curve presets isn't future-proof (in case they will be changed) - so IMHO not safe.

Getting rid of this code altogether (breaking update path 1.0->3.6) - not sure. While it can be OK for software to require multiple step upgrades (e.g. 1.0 to 3.4, then 3.4 to 3.6), but it's more about its configuration. In this case it's XMP files that can be lying around in archive, and I think breaking them intentionally require a good reason. What do you have in mind? Speed up start time? Probably another solution can be found - e.g. creating this table only on demand when old XMP is encountered for the first time.

**Comment by TurboGit** [comment]
I had in mind code clarification and clean-up. It is not safe indeed. So let's get rid of non auto-apply presets and I'll add some comments on this file plus some comment on the auto-apply circuitry using those legacy presets to ease understanding of the code. Thanks for your feedback, you've been around in the project since longer that I :)

**Pull request merged**
