### PR TITLE
Add Serbian translation

### LINKED ISSUE #8064: Serbian translation of Darktable
Hello,

I have just finished Serbian translation of Darktable, and you can find
it attached along this email. Note that we have both cyrilic and latin
translations. Just rename ".txt" to ".po" (github does not like po files).

PS. I am the coordinator of Gnome translations and have already
translated GIMP in my language.

Best,
Miloš

[sr.txt](https://github.com/darktable-org/darktable/files/5907078/sr.txt)
[sr@latin.txt](https://github.com/darktable-org/darktable/files/5907079/sr%40latin.txt)

### PR DESCRIPTION
**Pull request by kmilos**
Resolves #8064

### CODE REVIEW

**Review by TurboGit — CHANGES_REQUESTED** [review]
Naming @latin break build:

```
CMake Error at po/CMakeLists.txt:14 (add_custom_target):
  The target name "locale_sr@latin" is reserved or not valid for certain
  CMake features, such as generator expressions, and may result in undefined
  behavior.
```
Can you rename the file to sr_latin.po ?

**Comment by kmilos** [comment]
I don't think so, this is how glibc expects the locale identifier and how it is for all other (POSIX) software...

@gpopac Have you come across this cmake issue before?

**Comment by kmilos** [comment]
Can we maybe replace the `@` with `-` on the fly for the custom target name generation?

https://cmake.org/cmake/help/latest/command/string.html#replace

**Comment by TurboGit** [comment]
Not sure, but on dt we have variant with '_', for example 

-                        pt_BR "Brazilian Portuguese"
-                        pt_PT "European Portuguese"

**Comment by parafin** [comment]
> Not sure, but on dt we have variant with '_', for example
> 
> * **pt_BR**    "Brazilian Portuguese"
> * **pt_PT**    "European Portuguese"

that's different case.

**Comment by kmilos** [comment]
> Not sure, but on dt we have variant

Not the same thing. Those are actually two distinctly different dialects of the language that depend on geography. Luckily that corresponds to how POSIX constructs the locale tag with language_TERRITORY.

https://en.wikipedia.org/wiki/Locale_(computer_software)

In this case we have the same language and dialect, same territory, but different script, so the @modifier must be used.

This is indeed an unfortunate scheme, but there was not enough foresight for localisation issues in the 80s when this POSIX standard. As a result, we now (cca 2006) have more modern BCP 47 and CLDR standards that address localisation in a better way, but unfortunately dt and most FLOSS is still tied to POSIX.

**Comment by gpopac** [comment]
@TurboGit the file must be named sr@latin and compiled .mo file should go into /usr/share/locale/sr@latin/LC_MESSAGES/ in order for system to discover the translation.

@kmilos What should we do? One option is to file a glibc bug and the other is to find a way of overrun default behaviour and allow „@“ in cmake. I had no similar issues before with cmake, but we have already discussed that glibc way of handling latin translation is not perfect nor standard and should be changed.

If not possible to easily fix cmake compilation complain, maybe a temporary solution is to include only sr.po for a start? For latin we could use sr-Latin, hopefully to become a standard one day?

**Comment by kmilos** [comment]
> What should we do? One option is to file a glibc bug

Oh, I have tried some 15 years ago ;)

No dice.

> sr-Latin

Please don't mention this again. If anything, stick to BCP 47 sr-Latn or CLDR sr_Latn.

**Comment by gpopac** [comment]
@kmilos  Oh, I see you have replied in details in the mean time :) And yes, no sr-Latin, but sr-Latn! Usp!

**Comment by gpopac** [comment]
PS. We also have sr_RS, sr_BA, sr_ME which refers to the territory (Serbia, Bosnia and Herzegovina and Montenegro). And all these have their own latin and cyrilic versions.

**Comment by kmilos** [comment]
@TurboGit The proposed cmake workaround seems to work in my local tests.

**Comment by TurboGit** [comment]
Thanks, all this is really new to me. Will test the proposed patch and will come back.

**Comment by kmilos** [comment]
Yep, L10N, like people, can be complicated ;)

**Review by TurboGit — APPROVED** [review]
Looks good and working now. Thanks.

**Pull request merged**
