### PR TITLE
Properly support PortMidi in the build system

### PR DESCRIPTION
**Pull request by Sturmflut**
PortMidi is a dependency required for MIDI device support in Darktable. it seemingly never got added to the build system properly. It's just silently detected in the background and then used if you have it installed. But if you don't, you silently get a darktable binary without MIDI support and never see the missing library under "The following OPTIONAL packages have not been found:".

This patch wires PortMidi into CMake like all the other dependencies. It also introduces the new CMake option USE_PORTMIDI.

### CODE REVIEW

**Comment by TurboGit** [comment]
@kmilos : I'd like to view on this, it seems ok to me... but what about Windows?

**Review by dterrahe — APPROVED** [review]
I'm very happy someone finally stepped up to help with the CMAKE part of this, but I have very little knowledge of the make system and the correct way to implement this, so I can't really do a proper review. Especially with regards to cross platform issues. If this help with getting the Debian version to support midi out of the box, that would be great!

**Comment by Sturmflut** [comment]
@dterrahe It doesn't help with that. The debian package has to add a Build-Dependency on libportmidi-dev and a Dependency on libportmidi. That would have already enabled MIDI supported in previous versions.

I've contacted the Debian PhotoTools maintainers and asked for this to be done.

**Comment by MStraeten** [comment]
breaks osx build:
```
Undefined symbols for architecture x86_64:
  "_Pm_Close", referenced from:
      _midi_write in midi.c.o
      _update_with_move in midi.c.o
      _midi_device_free in midi.c.o
      __timeout_midi_update in midi.c.o
  "_Pm_CountDevices", referenced from:
      _midi_open_devices in midi.c.o
  "_Pm_GetDeviceInfo", referenced from:
      _midi_open_devices in midi.c.o
  "_Pm_GetErrorText", referenced from:
      _midi_write in midi.c.o
      _update_with_move in midi.c.o
      __timeout_midi_update in midi.c.o
  "_Pm_Initialize", referenced from:
      _midi_open_devices in midi.c.o
  "_Pm_OpenInput", referenced from:
      _midi_open_devices in midi.c.o
  "_Pm_OpenOutput", referenced from:
      _midi_open_devices in midi.c.o
  "_Pm_Read", referenced from:
      _poll_midi_devices in midi.c.o
  "_Pm_Terminate", referenced from:
      _midi_close_devices in midi.c.o
      _gui_cleanup in midi.c.o
  "_Pm_WriteShort", referenced from:
      _midi_write in midi.c.o
      _update_with_move in midi.c.o
      __timeout_midi_update in midi.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/darktable/plugins/lighttable/libmidi.so] Error 1
make[1]: *** [lib/darktable/plugins/lighttable/CMakeFiles/midi.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by Sturmflut** [comment]
@MStraeten Thanks for checking. I think I found the error and pushed a second commit that should fix it. Could you please pull and try again?

**Comment by Sturmflut** [comment]
I've also sent a [pull request](https://github.com/flathub/org.darktable.Darktable/pull/95) to Flathub, so MIDI will hopefully work by default in the Flatpak.

**Comment by MStraeten** [comment]
now the osx build is successful

**Review by TurboGit — APPROVED** [review]
And CI is saying that the Windows build is OK too. Nice enhancement. Thanks.

**Comment by kmilos** [comment]
> And CI is saying that the Windows build is OK too.

Confirmed - sorry I wasn't able to look at it straight away...

**Pull request merged**
