### PR TITLE
preset and style shortcut fixes

### LINKED ISSUE #11502: recent change losing custom shortcuts ?
**Describe the bug/issue**
With a recent upgrade, say in the last few days, I've lost some of my custom shortcuts.

I restored the 4 shortcut files in the ~/.config folder from yesterday.

Before running darktable doing  _grep 'apply BW' short*_ shows as below, which is correct.  They are 5 styles to apply a B&W filter via the colour calibration module.

shortcutsrc:b;shift=global/styles/apply BW|blue
shortcutsrc:g;shift=global/styles/apply BW|green
shortcutsrc:r;shift=global/styles/apply BW|red
shortcutsrc:t;shift=global/styles/apply BW|orange
shortcutsrc:y;shift=global/styles/apply BW|yellow
shortcutsrc.backup:b;shift=global/styles/apply BW|blue
shortcutsrc.backup:g;shift=global/styles/apply BW|green
shortcutsrc.backup:r;shift=global/styles/apply BW|red
shortcutsrc.backup:t;shift=global/styles/apply BW|orange
shortcutsrc.backup:y;shift=global/styles/apply BW|yellow
shortcutsrc.edit:b;shift=global/styles/apply BW|blue
shortcutsrc.edit:g;shift=global/styles/apply BW|green
shortcutsrc.edit:r;shift=global/styles/apply BW|red
shortcutsrc.edit:t;shift=global/styles/apply BW|orange
shortcutsrc.edit:y;shift=global/styles/apply BW|yellow

When I run darktable none of these shortcuts work e.g. shift + r to apply my black and white red filter.

Whilst darktable is running the grep shows as below, so no longer showing these in the shortcutsrc file :
shortcutsrc.backup:b;shift=global/styles/apply BW|blue
shortcutsrc.backup:g;shift=global/styles/apply BW|green
shortcutsrc.backup:r;shift=global/styles/apply BW|red
shortcutsrc.backup:t;shift=global/styles/apply BW|orange
shortcutsrc.backup:y;shift=global/styles/apply BW|yellow
shortcutsrc.edit:b;shift=global/styles/apply BW|blue
shortcutsrc.edit:g;shift=global/styles/apply BW|green
shortcutsrc.edit:r;shift=global/styles/apply BW|red
shortcutsrc.edit:t;shift=global/styles/apply BW|orange
shortcutsrc.edit:y;shift=global/styles/apply BW|yellow

The issue looks to be shortcuts linked to a style as my shortcuts to presets (e.g. tone equalizer / contrast tone curve soft) are still working.

Within darktable I then recreated the shortcut to shift + r.  I could create the shortcut however on applying it via shift + r it says the style has been applied but nothing happens.  It should add a module to the top of the history stack.

If I manually apply the style, either via the lighttable or the quick access icon bottom left of the darkroom, it works as expected.

**Expected behavior**
I expect the custom shortcuts to remain.

**Platform**
3.9.0~git1030.d5a8dd5d26-1 on Ubuntu 20.04

### LINKED ISSUE #11926: [dt_action_locate] error message
reproduce this way:
- run darktable from the terminal
- generate a new preset in the export module (I think that every lighttable module should produce the same effect, while darkroom modules doesn't)
- open the preferences and got to the presets, open the export module line and select the new preset
- hit the keyboard cancel button and confirm deleting -> the error message `[dt_action_locate] action '<preset name>' doesn't exist` appears in the terminal

The error message appears if deletion is made from the preset edit dialog, too.

The function `dt_action_locate` prints it, invoked by `dt_action_rename_preset`, invoked by `dt_gui_presets_confirm_and_delete`.

### LINKED ISSUE #12139: Trouble with shortcut et styles
Hello,

I have updated dt in v4. I have shortcuts with my styles that I use in v3.8. With the update, there is a trouble. When I click, the window writes Sepia is applied but no changes in history. 

I have 2 types of styles, two ( no pipe) that I can apply with the shortcuts and the others with a pipe I can't. 

I can change the name of the "directory" (before pipe) and it works. But after reboot, it doesn't work.

dt v4 + 19
debian stable
OpenCL active

Thanks

### PR DESCRIPTION
**Pull request by dterrahe**
fixes #12139
fixes #11502
fixes #11926
corrects #12208

Solves thee issues:
Issue 1:
Defining or renaming presets for lib modules would previously not correctly manage the associated actions (they'd still be called "new preset") so shortcuts could only be defined after a restart. This should now work correctly.

Issue 2:
preset and style names containing a pipe ("|"). There was "some" initial support in inputng for the new gnome "contexted translations" style, which broke these presets/styles. Since preset/style names are internally already stored in translated form, they are now not translated again when setting up the corresponding actions.

Issue 3:
The recently introduced `N_("selected images action", "group")` breaks shortcuts to that button when switching languages.

Previously the translation context was separately supplied to `g_dpgettext2` (which requires either storing a context for each string or specific contexts per use case, like "blendmode" for `dt_develop_blend_mode_names`, which then forces a separate translation for _all_ strings in that context even if they don't deviate from the normal meaning).
 
The "new" gnome way is to _only_ specify a context, in the string itself, for strings that _require_ a separate context , using "context|string". These are then translated using `Q_()` instead of `_()`.

To fully switch to this new way, we should switch from _intltool_ to _gettext_ (https://wiki.gnome.org/MigratingFromIntltoolToGettext). We could then instruct it to parse the new format when used in `N_()`. Instead, I have here redefined `NC_()`, which is used in only a few locations (for example to correct #12208),  to pass the combined string and process it at the other end using `Q_()`. Doing the full _gettext_ migration would allow supporting this functionality in introspection as well.

I have not yet implemented _full_ contextual translation support _everywhere_ that `N_` is used. Obviously button labels work (for the _group_ button). `dt_bauhaus_widget_set_label` should fully work, as well as combobox items, but since none of these have existing cases with contexted translations, actually using `NC_` here might uncover issues (that should be easy to fix). Testing is hard if there are no use cases...

`dt_develop_blend_mode_names` could be cleaned up (meaning the "blendmode" context removed) except for those modes where the translation should actually deviate from the non-contexted version (if there are any; this is not a quick check).

Edit: this allows more comboboxes to be set up using `dt_bauhaus_combobox_new_full` which exposes their possible values as _effects_ in shortcuts and lua calls to _dt.gui.action_, so that they can be directly activated.
Specifically this applies to display intents, where `NC_("rendering intent", "saturation")` previous prevented this.

### CODE REVIEW

**Comment by TurboGit** [comment]
@dterrahe : Even if a bug fix I'm wondering if this is safe for 4.0.1? Looks like a bit invasive. How do you feel?

**Comment by dterrahe** [comment]
Agreed; it would be better to have this in master first, so it will get thoroughly tested before release ;-)

In the OP I'm kind of making the case to switch to `gettext` in the build process, but I'm not that knowledgeable in that regard (especially the cross-platform consequences) so might be a better job for someone else.

**Comment by dterrahe** [comment]
@TurboGit my preferred order would be to merge this after #12338. There are some conflicts between the two. Resolving those here would make this PR smaller, but also easier to revert out if problems do occur.

**Comment by TurboGit** [comment]
@dterrahe : Noted, waiting for wpferguson feedback on #12338.

**Review by TurboGit — APPROVED** [review]
Ready for me, should I merge now?

**Comment by dterrahe** [comment]
Yes please.

**Pull request merged**
