### PR TITLE
x100f: basecurve and tonecurve

### PR DESCRIPTION
**Pull request by dtorop**
Calculated for 16 images taken 1/3 stop apart of a windowsill surrounded by tiles with a dark area below. Camera set out of focus at longest possible focal length (focused very close). White balance set to auto, film mode standard, highlight/shadow/etc. at 0, JPEGs output as sRGB.

This gives a smooth curve, and pleasing results on processed images. In graphs, the count of pixels across the range of the raw brightness is fairly smooth, and the resulting curve is a good fit for the measured green curve.

This uses the camera's recent version 2.00 firmware.

Below should be links to the basecurve and tonecurve plots generated by gnuplot.

[tonecurve.pdf](https://github.com/darktable-org/darktable/files/1717544/tonecurve.pdf)
[basecurve.pdf](https://github.com/darktable-org/darktable/files/1717545/basecurve.pdf)

### CODE REVIEW

**Comment by LebedevRI** [comment]
[unless something has changed] we don't merge those curves and custom color profiles
No methodology to verify them, no volunteer[s] to check the new submissions

**Comment by dtorop** [comment]
I was wondering, I couldn't remember if that went for basecurves or noise profiles (or both?). I'll close the PR, but leave the branch up, as I like the results with this curve.

**Comment by crepererum** [comment]
What could be done to verify these curves? I also own a x100f, so if there's anything I can do, please let me know.

**Comment by dtorop** [comment]
I made a few obviously bad basecurves before making this one. This one appeared satisfactory because:

- In basecurve.pdf and tonecurve.pdf the sample count histogram is fairly uniform across the brightness range and doesn't have any anomalous thick sections.
- The JPEG RGB channel brightness curves are consistent with each other and don't have odd kinks, which make the curve hard to fit plus just plain look weird.
- Both of which suggest that the sample images were sensibly made, unlike some bad choices I made in other source images, e.g. photographing a glossy black box in front of a window.
- The resulting curve looks like a sensible basecurve: a slow rise in the toe, and leveling out in the shoulder.
- Comparing a JPEG/raw pair, with the raw processed with the basecurve, the tonality between the two isn't too far off.
- The basecurve looks similar to the curve generated by `darktable-chart` and an IT8.7 target.
- I like what the basecurve does when I use it day-to-day.

But I can't speak to how one would formally verify the curves.

The curve I made for the X100S a few years ago looks somewhat different, but that may be due not only to a different generation of sensor but that back then the I believe `dt-curve-tool` worked slightly less well, and I may have been even more naive about using it.

I am curious if one is better of using the results of `darktable-chart`, as even if the curve is drawn from less tonal data, there is the benefit of a color LUT.

**Pull request closed without merging**
