### PR TITLE
Correctly display infinity focus in image information

### PR DESCRIPTION
**Pull request by victoryforce**
... this time with enhanced reliability of the check for infinity.

### CODE REVIEW

**Comment by TurboGit** [comment]
Do you have a picture with FFFFFFFF as focus distance to test.

I'm asking because after checking our current code I see that the exif value is read using:

`      float value = pos->toFloat();`

Meaning that if the tag is set to FFFFFFFF it will certainly already be broken by the `toFloat()` so at the end the test `>= 0XFFFFFF00` won't help.

**Comment by victoryforce** [comment]
> Do you have a picture with FFFFFFFF as focus distance to test.

Yes. This:
https://raw.pixls.us/getfile.php/3874/nice/Hasselblad%20-%20X1DM2-50c%20-%2016bit%20(4:3).fff

**Comment by TurboGit** [comment]
> > Do you have a picture with FFFFFFFF as focus distance to test.
> 
> Yes. This: https://raw.pixls.us/getfile.php/3874/nice/Hasselblad%20-%20X1DM2-50c%20-%2016bit%20(4:3).fff

Thanks, tested and working. The focus distance stored into the db is `4294967296,00`.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by kmilos** [comment]
That's right, 0x100000000 is the outcome of rounding to nearest (in this case, up), which is the default for most implementations. The 0xFFFFFF00 threshold is chosen to cover any possible rounding down case.

**Pull request merged**
