### PR TITLE
Add all default modules that can't be disabled but are hidden into hi…

### PR DESCRIPTION
**Pull request by TurboGit**
…story.

This ensures that the corresponding module have an entry into the database
and into the XMP. This is needed to have proper handling of the reorder
of the modules.

Also, the corresponding entries are hidden from the history GUI.

Part of #2905.

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
I checked it with current master (2019.09.12) and  #2939 included. Works fine.

**Comment by MStraeten** [comment]
in the history stack in darkroom the changes on the input color profile arent longer displayed. if using styles containing input color profile settings these aren't shown in the history stack, so it's hard to realize where changes were applied.

**Comment by parafin** [comment]
That's why I originally suggested not to hide anything - hiding logic will be prone to bugs like that.

**Comment by TurboGit** [comment]
> That's why I originally suggested not to hide anything - hiding logic will be prone to bugs like that.

I missed that then... Here you wrote the opposite :+1: 

https://github.com/darktable-org/darktable/pull/2905#issuecomment-528485286

But certainly I agree with you and I'm also more for displaying everything.

**Comment by parafin** [comment]
Your question was "Do we want them to appear also into the history GUI?", my answer was "I guess yes" ;) By "transparently mapped from DB/XMP to GUI" I meant not to hide anything.

**Comment by TurboGit** [comment]
My bad :) I didn't get it right!

**Comment by TurboGit** [comment]
So, nothing hidden in this new version.

@MStraeten : can you double check that your issue is fixed now?

**Comment by MStraeten** [comment]
confirmed, now it's fine

**Comment by TurboGit** [comment]
@MStraeten : thanks for testing.

Let me merge this now. This is potentially delicate and better to have early field testing.

**Pull request merged**
