### PR TITLE
thumbtable: fix inconsistent hover state for icons

### PR DESCRIPTION
**Pull request by aurelienpierre**
conflicting CSS rules prevented icons to show in "overlays on hover" mode, they were hard-set to transparent.

### CODE REVIEW

**Review by Nilvus — CHANGES_REQUESTED** [review]
Good catch. I've missed that. Thanks.

Just remains now to add the hover effect on those icons. You could see on overlay extended one that there is a little hover effect when hovering icons (see group icon for example). This is set starting line 2073 in your CSS file of this PR. Needed so for both hover and hover extended overlays.

**Comment by aurelienpierre** [comment]
> Just remains now to add the hover effect on those icons. 

Since when do we have hover effects ? Do you understand that Gtk is single-threaded lib running on CPU and that effects need to render at at least 30 FPS ? This is just a performance penalty.

**Comment by Nilvus** [comment]
> > Just remains now to add the hover effect on those icons.
> 
> Since when do we have hover effects ? Do you understand that Gtk is single-threaded lib running on CPU and that effects need to render at at least 30 FPS ? This is just a performance penalty.

Since just few years, at least. And your PR here is also about hover effects. That never bothered you before... But seems that now nearly all things bothered you. Maybe we should removed all hover effects in darktable? I'm quite sure a lot of people will love that.

Just to remember that, even if performance penalty is indeed bad, there's other things to take care. And on top thumbnails images, and since probably near the beginning of darktable, there's different icons: those that are actionable (group and audio ones) and some that are not (altered or extension name for example). Having an hover effect is just a good way in an UI to let the user understand that an icon is actionable (with hover effect) and for non actionable one without hover effect of course. This is used (hover effect for actionable effects) in nearly all actionable items in darktable (buttons, icons, etc). And it's also the same on nearly all apps I know. But maybe all that is stupid...

**Comment by TurboGit** [comment]
Supersede by #11872.

**Pull request closed without merging**
