### PR TITLE
rawprepare: more significant text in tooltips

### PR DESCRIPTION
**Pull request by rabauke**
Currently, the tooltips in the Raw black/white point module just repeat the text in the corresponding sliders' labels. Thus, the tooltips do not provide additional information to the user. This PR is to enhance the text which is displayed in the tooltips.

### CODE REVIEW

**Comment by rabauke** [comment]
@LebedevRI : I do not think that the suggested text 

`set the camera specific black level %i of the RGGB Bayer pattern `

implies that there would be a _specific_ mapping between the sliders 1 to 4 to particular pixels of the RGGB pattern. It just implies that there _is_ a mapping of the sliders 1 to 4 to particular pixels of the RGGB pattern, which is not specified. In order to avoid the false impression of a particular mapping, one might change the tooltip text to 

`set one camera specific black level of the RGGB Bayer pattern `

What do you suggest?

**Comment by LebedevRI** [comment]
What about X-Trans?

**Comment by LebedevRI** [comment]
The mapping is: 

------------------| Column & 1 == 0 | Column & 1 == 1
----------------- | --------------------- | ---------------------
Row & 1 == 0 | black level 0        | black level 1        
Row & 1 == 1 | black level 2        | black level 3        

I'm not quite sure it is possible to express that in short nice words.

**Comment by rabauke** [comment]
@LebedevRI : I do not think that it is necessary (or even possible) to describe the pattern shown in your table in a tooltip text. This might be, however, an issue for the user manual. Regarding the tooltips, I still think we should be more specific here. Considering that Bayer patterns are not used exclusively, a suitable text might be

`set one camera specific black level of the camera sensor pattern`

Btw: The user manual gives the impression that the module would work with Bayer patterns only.

**Comment by LebedevRI** [comment]
I hear you, but i still believe that being any more specific here will either result in overly long lines,
or it will convey the wrong idea. It's not *really* related to the pattern, but to this 2x2 pattern grid.

**Comment by rabauke** [comment]
Although I find the current tooltip text unsatisfactory, I agree. It's difficult to to come up with a better text for the tooltips. I am going to remove the PR until I have an idea for a more useful description.

**Comment by TurboGit** [comment]
Given your last message, I'm closing.

**Pull request closed without merging**
