### PR TITLE
Revert to XWayland

### LINKED ISSUE #13150: Can't select lens in "lens correction" module
for the latest version of darktable (git master) I was unable to select a lens in the lens correction module manually. The list of lenses disappears before I can make any selection. This is required for any manual lens or in my case any lens used with the Nikon FTZ adapter.

**To Reproduce**
1. Go to 'lens correction module'
2. Try to select lens manually
3. List disappears

**Expected behavior**
- Selecting lens is possible

Version: darktable git master / commit 4b3d410bc0a963b4357ad4c8fe4e1abd0a32d439
Platform: archlinux x86-64, gnome on wayland, opencl installed/active

### LINKED ISSUE #13180: dt 4.2: Ctrl+t not working for tagging
I'm on darktable 4.2.0, freshly upgraded, on Fedora 37 (GNOME 43.2, with default Wayland) using OpenCl on a laptop (Asus B9450FA /Intel, i5-10310U UHD graphic).

When trying to tag photos using keyboard shortcut ctrl+tag, the usual input small box oddly appears in the upper left corner, right on the window title bar (instead of bottom centre), and it is just not working. Trying to put some text as tag does nothing. See screenshot attached.

My tests were made with a fresh darktable setup, with all the default settings (except for dark theme, to make it more clear for the screenshot).

Dessin sans titre

### LINKED ISSUE #13311: Can't scroll drop-down entries
**Describe the bug/issue**
Since 4.2 when opening a drop-down (e.g. in collections-module), I can't scroll to the top entries of the drop-down anymore.

**To Reproduce**
1. Open 'collections'
2. open dropdown (click on 'film-roll')
3. choose 'history' (at the end of the list)
4. open dropdown again (click on 'history')
5. try to choose film-roll again (at the top of the list)
6. neither moving the mouse to the top, nor using the mouse-wheel moves the drop-down list to show the top entries

**Expected behavior**
The drop-down list should move down if I scroll up
(as it was until 4.0.1)

**Screencast**
[dropdown-4.0.1_OK.webm](https://user-images.githubusercontent.com/5677563/211422604-b29ebc12-747c-45a5-b28b-cf3e3ff17f27.webm)
[dropdown-4.2.0_NOK.webm](https://user-images.githubusercontent.com/5677563/211422606-794bae09-2ab0-4017-a33e-f456fccffc49.webm)

**Platform**

* darktable version : 4.2.0
* OS : Manjaro Linux
* Desktop : Gnome 43.1
* Memory : 32 GB
* OpenCL installed : no
* OpenCL activated : no
* Graphics card : Mesa Intel® HD Graphics 630 (KBL GT2)
* Graphics driver : video-linux
* HiDPI (scale 200%)

### LINKED ISSUE #13312: Tooltips at the bottom not visible
**Describe the bug/issue**
When hovering buttons near the bottom of the screen (e.g. culling), the tooltip is not visible

**To Reproduce**
1. Go to lighttable
2. hide filmstrip but show bottom panel
3. hover culling icon
5. tooltip is shown underneath -> outside of the window -> not visible

**Expected behavior**
Show the tooltip above, if there is not enough space underneath
(as it was until 4.0.1)

**Screencast**
[tooltip-4.2_NOK.webm](https://user-images.githubusercontent.com/5677563/211423923-9d8e2922-46e0-4b04-b098-a9ed436ebba1.webm)
[tooltip-4.01_OK.webm](https://user-images.githubusercontent.com/5677563/211423920-913b08be-98c2-4c34-867b-cd501e811873.webm)

**Platform**
* darktable version : 4.2.0
* OS : Manjaro Linux
* Desktop : Gnome 43.1
* Memory : 32 GB
* OpenCL installed : no
* OpenCL activated : no
* Graphics card : Mesa Intel® HD Graphics 630 (KBL GT2)
* Graphics driver : video-linux
* HiDPI (scale 200%)

### PR DESCRIPTION
**Pull request by victoryforce**
Too many problems in native Wayland.

This should fix #13180.

EDIT: Also should fix #13150, fix #13311, fix #13312.

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by victoryforce** [comment]
I'd propose following phrase for release notes:
When using Wayland give priority to XWayland, because native Wayland is the cause of many issues in darktable.

**Comment by TurboGit** [comment]
Thanks!

**Comment by TurboGit** [comment]
> unless the statement is "we will not support wayland, ever"

No the statement is we will support wayland when someone will step up to fix the above mentioned issues.

**Comment by kubrickfr** [comment]
> No the statement is we will support wayland when someone will step up to fix the above mentioned issues.

Hence my comment, why closing the issues? They still exist and should be worked on if that's the goal.

**Comment by TurboGit** [comment]
> Hence my comment, why closing the issues? They still exist and should be worked on if that's the goal.

Probably automatically closed by GitHub as part of the commit. Can you list the issue to reopen? TIA.

**Comment by victoryforce** [comment]
> "Too many issues"? It seems like #13150 #13311 #13312 are most likely the same issue.

These are not the same issue by definition, they are not duplicate bug reports, they describe different problems in the process of working with darktable. You may have meant that they have the same root cause. That's right, the problem is in native Wayland.

> Anyways, I don't understand how this closes the issues mentioned here,

Issue is a report about a certain problem when using darktable. In these issues, there was information that switching to the X11 backend (that is, exactly what this PR does) eliminates the problems. That is why this PR claims to resolve these issues.

If you claim that this PR does not solve the problems described in the mentioned issues, you can add comments with this information to them and the issues will be reopened.

> unless the statement is "we will not support wayland, ever"

As I wrote above, the issues are closed, because this PR eliminates the problems described in them. I don't understand how the statement you formulated (strange in itself) has anything to do with this.

**Pull request merged**
