### PR TITLE
Sort aspect ratio

### PR DESCRIPTION
**Pull request by TurboGit**
Add a way to sort on the actual aspect ration (final one, after cropping).

I need that from time to time to select a set of picture in a specific aspect (portrait or landscape) for an exhibition.

### CODE REVIEW

**Comment by TurboGit** [comment]
There is a dead-lock if you use the aspect-ratio filter while importing new pictures. To be fixed.

**Comment by TurboGit** [comment]
I'd like some testing, if you read this and build darktable. Please test and report here. Thanks.

**Comment by TurboGit** [comment]
Should be fixed! Thanks for reporting this case.

**Comment by edgardoh** [comment]
All good now.

**Comment by TurboGit** [comment]
Ok, let's merge for a wider audience then. Thanks for the feedback.

**Pull request merged**
