### PR TITLE
mask indicator tooltip to show the source module for raster mask

### PR DESCRIPTION
**Pull request by Mark-64**
With this PR the tooltip for the mask indicator, in case of raster mask, will show which is the soruce module.
This can be useful when checking masks with collapsed modules. Previously we had to expand the module to find out the mask source

immagine

### CODE REVIEW

**Comment by TurboGit** [comment]
`as in module` -> `taken from module` or `created from module` ?

It would read:

```
this module has a raster mask
taken from module exposure 2
```

What do you think ?

**Comment by Mark-64** [comment]
yup, "taken from module" is fine

**Review by TurboGit — APPROVED** [review]
All good to me now, thanks!

**Comment by todd-prior** [comment]
In addtion to this can we not enable a preview of this mask. While it is an improvement to clearly identify where it comes from if you want to do a quick check to confirm what you have masked based on the raster mask selection. Perhaps you want to evaluate between two mask options for the raster mask. Clearly we have the date in the module to clearly apply the modules edit. Would it be difficult to have a preview that could be enabled??

**Pull request merged**
