### PR TITLE
Fix #4005 icons size for HiDPI displays

### LINKED ISSUE #4005: UI: super tiny on/off history icons on Windows 10
DT 3.1 git master on Windows 10, 4k monitor.
The on/off icons in the history stack are super small
Cattura14

while the same icons in modules are normal
Cattura15

### PR DESCRIPTION
**Pull request by Mark-64**
fix for #4005 and top right icons.
In 4k display, Windows 10:

before 
Cattura22

after
Cattura23

before
Cattura24

after
Cattura27

### CODE REVIEW

**Comment by TurboGit** [comment]
Looks ok to me!

@Nilvus : What do you think?

**Comment by Nilvus** [comment]
> Looks ok to me!
> 
> @Nilvus : What do you think?

I will not have time this week to test but on what I see in screen captures, that's great. And it's ok if it doesn't change anything on lowdpi displays and on other OS like Linux or MacOs.

**Comment by Mark-64** [comment]
The correction only depends on darktable.gui->dpi_factor and it's pretty mild. 
For lowdpi screens the factor is normally 1.0 and there is no change. 
The correction becomes visible only when dpi_factor is significantly higher than 1.0, like in my 4k display under Windows10 where it is 1.75. The same display in Ubuntu has a factor of 1.0, don't know why.
More tests are welcome of course.

**Comment by TurboGit** [comment]
It changes nothing on lowdpi, so I'll merge on master and 3.0.1. Thanks!

**Pull request merged**
