### PR TITLE
Fix collection filter modes not working

### LINKED ISSUE #14944: Collection filter modes not working (or very unintuitive)
### Describe the bug

The "and not" mode on a collection filter gives me the exact same results as the "and" mode.
Tested with filename, rating, and search filters.
The "or" mode is also not doing what it says, e.g.
```
rating 
    all
or filename
    PC230370
```
will match only the single file. It should match all files since they all have any rating, thus matching the first half of the "or" operation.
Testing something simple like
```
rating
    all
or rating
    all
```
returns no matching images, which does not make sense at all.

### Steps to reproduce

1. Open a collection with at least two images
2. Add a new collection filter of the "filename" type
3. Set the filename filter to the filename of one of the files
4. Toggle the filter to ensure it's working
5. Set the "combination operator" to "and not"
6. Toggle the filter - it keeps the same image as in "and" mode

### Expected behavior

Remove the matched images, not show only those.

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2, also tested with 4.2.1

### What OS are you using?

Mac

### What is the version of your OS?

12.6.7

### Describe your system?

_No response_

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by zisoft**
fixes #14944

### CODE REVIEW

**Comment by victoryforce** [comment]
So, I test this PR with the two filters that are specified in the raised issue: rating and filename.

The first filter has the value "all" (that is, show files regardless of rating).

Enter the string in the file name field in the second filter. Only files containing this string in the name are displayed, everything is correct.

Now we change the logic to "or", all images are displayed, everything is correct.

Now we change it to "and not", everything except the specified names is displayed, everything is correct. So the bug is indeed fixed.

So what's the problem? Let's try to click on the filename filter disable button and the program will crash with the following backtrace:
```
(gdb) bt
#0  0x00007fff7e775f10 in ucrtbase!strlen () from C:\WINDOWS\System32\ucrtbase.dll
#1  0x00007fff4e5986e8 in ?? () from C:\msys64\ucrt64\bin\libglib-2.0-0.dll
#2  0x00007fff12f0eae6 in dt_collection_set_extended_where (extended_where=0x615e32e0, collection=0x66f4d70) at C:/msys64/home/victor/darktable/src/common/collection.c:626
#3  dt_collection_update_query (collection=<optimized out>, query_change=query_change@entry=DT_COLLECTION_CHANGE_RELOAD, changed_property=DT_COLLECTION_PROP_FILENAME, list=list@entry=0x0) at C:/msys64/home/victor/darktable/src/common/collection.c:2485
#4  0x00007ffefc5b973c in _event_rule_changed (rule=rule@entry=0x5ed5bcd0, entry=<optimized out>) at C:/msys64/home/victor/darktable/src/libs/filtering.c:658
#5  0x00007ffefc5bc6b8 in _event_rule_changed (rule=0x5ed5bcd0, entry=<optimized out>) at C:/msys64/home/victor/darktable/src/libs/filtering.c:650
#6  _event_rule_disable (widget=<optimized out>, rule=0x5ed5bcd0) at C:/msys64/home/victor/darktable/src/libs/filtering.c:1104
#7  _event_rule_disable (widget=<optimized out>, rule=0x5ed5bcd0) at C:/msys64/home/victor/darktable/src/libs/filtering.c:1101
```

**Comment by zisoft** [comment]
Cannot reproduce the crash you mentioned.
Did you make a clean build?

**Comment by victoryforce** [comment]
Yes, a clean build. I'm checking on Windows, although I don't think there's the kind of code involved that might be platform-specific. I even tested by running on an empty configuration to exclude the possibility that the crash is due to some configuration specifics.

It is enough to simply add (after removing the default ones), it seems that any filter, one filter is enough, and click on its disable button. The program crashes. The crash is 100% reproducible.

**Comment by zisoft** [comment]
Cannot reproduce that either and I see no relation to this PR.
Can you check this behaviour on master without this PR applied?

**Comment by victoryforce** [comment]
> Can you check this behaviour on master without this PR applied?

On the current master without this PR, there is no crash when pressing the disable rule button, but filters do not work correctly.

> Maybe the selected collection type? I have mine set to 'directory'

I had a 'film roll', but I changed the collection type to a 'folder' and it didn't change anything, it crashes the same way.

**Comment by victoryforce** [comment]
After thinking about it, I've changed my mind that the behavior here shouldn't be platform specific. Yes, there is hardly any OS-specific code in the filter-related code itself. But a situation is possible when certain not very correct code works differently on different platforms. I once fixed such a bug in the filter code. In that case, the problem was the absence of a "return" in one of the function's execution flows. It didn't crash on Linux, but always crashed on Windows. So it's possible that differences in code generation by compilers and/or differences in system libraries can lead to different program behavior...

I'll test how it works on Linux today.

**Comment by zisoft** [comment]
By reading the code I found indeed an issue: For disabled filters no query part were set.
Can you please try with my lates commit?

**Comment by victoryforce** [comment]
Great! Everything is fine now, both on Windows and on Linux.

**Comment by zisoft** [comment]
Release notes:
Fixed a bug in the collection filter module where the conjunction of multiple filters were not handled properly.

**Comment by TurboGit** [comment]
Thanks!

**Pull request merged**
