### PR TITLE
Fix deflicker. Breaks (unreleased) history stacks. Deflicker can now be released.

### PR DESCRIPTION
**Pull request by LebedevRI**

### CODE REVIEW

**Comment by pedrocr** [comment]
The deflicker calculations look good to me. Trying it out I think we could simplify the GUI and the implementation of the other exposure modes:

  * Remove the old auto mode (it produces the same results as setting deflicker to 0EV and adjusting the percentile slider to 100%-"clipping threshold)
  * Add the option for deflicker to only sample a given area of the image
  * Remove the mode selection at the top of exposure and instead have the following options:
    * black slider: same as now
    * exposure slider: same as now
    * area selection toggle: enables/disables using only the given area of the image
    * deflicker enable toggle: enables the deflicker mode
    * white percentile: same as deflicker percentile
    * target level: same as deflicker
  * To get the deflicker behavior just press the button or fiddle with either white percentile or target level. When you do that the exposure slider changes to indicate the computed EC
  * To go back to manual behavior just press the button or fiddle with the exposure slider

**Comment by LebedevRI** [comment]
>Remove the old auto mode
That was kind of planned, and is possible once i finally implement area selection.
Though, (a while back) i *think* @boucman wanted to still have the old auto mode.

>Add the option for deflicker to only sample a given area of the image
Definitely on my todo.

>Remove the mode selection at the top of exposure and instead have the following options:
That is how it was initially implemented, and it was horrible. Really do not want to go back to that "UI".
Try some commit before fd134a7a8a67ff476c7665bdddd56664b33487d8

**Comment by pedrocr** [comment]
> Try some commit before fd134a7

Yeah, I like that quite a bit more than the current mode. It makes it obvious what is happening. Compared to this I'd:
  * remove the old auto mode (the same can be obtained with deflicker) and just rename deflicker auto
  * add another toggle to enable/disable area selection

**Comment by LebedevRI** [comment]
>Remove the old auto mode
>(it produces the same results as setting deflicker to 0EV and adjusting the percentile slider to 100%-"clipping threshold)

Without checking, i think only for images with zero clipping.

**Comment by pedrocr** [comment]
Actually the math looks exactly like setting percentile to 100% and then adjusting the EV to negative value. I think there is an f(clipping_threshold) = EV function that makes the old auto mode exactly like deflicker. Either way functionally it's the same thing, adjusting the exposure by comparing the highlights in reference to the clipping level so there's no need to have two ways of doing it.

**Comment by pedrocr** [comment]
> Yeah, I like that quite a bit more than the current UI. It makes it obvious what is happening.

A simple way to bridge these two UI concepts would be to move the mode dropdown to below black and exposure sliders. That way the GUI would work almost like it does now but it would be obvious that the parameters are just black/exposure and everything else are just ways to adjust it (or not) automatically.

**Comment by LebedevRI** [comment]
@upegelow please do note that i have removed "histogram of" selection.
I'm sorry to change ui this late, but it was needed. Now i'm reasonably confident that we can release this feature.

**Pull request merged**
