### PR TITLE
Finish Input NG; simplify and clean up command shortcuts

### PR DESCRIPTION
**Pull request by dterrahe**
Paying off remaining code debt from Input NG. This removes the temporary plumbing that was put in place to connect the old gtk closure based callbacks to the new infrastructure. 

### easier callback definitions and setup
Something like
```
static gboolean _lib_snapshots_toggle_last(GtkAccelGroup *accel_group, GObject *acceleratable, guint keyval,
                                          GdkModifierType modifier, gpointer data)
{
  dt_lib_snapshots_t *d = (dt_lib_snapshots_t *)data;

  if(d->num_snapshots)
    gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(d->snapshot[0].button), !gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(d->snapshot[0].button)));

  return TRUE;

}
void init_key_accels(dt_lib_module_t *self)
{
  dt_accel_register_lib(self, NC_("accel", "toggle last snapshot"), GDK_KEY_x, GDK_CONTROL_MASK);
}

void connect_key_accels(dt_lib_module_t *self)
{
  GClosure *closure = g_cclosure_new(G_CALLBACK(_lib_snapshots_toggle_last), (gpointer)self->data, NULL);
  dt_accel_connect_lib(self, "toggle last snapshot", closure);
}
```
now looks like this
```
static void _lib_snapshots_toggle_last(dt_action_t *action)
{
  dt_lib_snapshots_t *d = dt_action_lib(action)->data;

  if(d->num_snapshots)
    gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(d->snapshot[0].button), !gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(d->snapshot[0].button)));
}
```
with a single line gui_init to set up the action and optionally assign a default shortcut

`  dt_action_register(DT_ACTION(self), N_("toggle last snapshot"), _lib_snapshots_toggle_last, GDK_KEY_x, GDK_CONTROL_MASK);
`
### translations
This does away with most of the remaining "accel" translation domain. For most shortcuts, the strings in the shortcut are the same as the strings used for the corresponding widget, so the separate domain just required two identical translations. For command shortcuts this may not be the case, but there is much less confusion now; everything simply needs to be marked with N_("") and most of the time the name doesn't need to be identically repeated (once in `init_key_accels` and once in `connect_key_accels`), translated once and just plain the other.

EDIT: some "combined" translations, like for example `NC_("accel", "panels/left")`, are now marked separately, `N_("panels"`) and `N_("left")`, avoiding besides duplication problems with slashes in translations.

### easier button shortcuts setup

Many buttons now only need one call in `gui_init`, for example
```
  d->copy_parts_button = dt_action_button_new(self, N_("selective copy..."), copy_parts_button_clicked, self,
                                              _("choose which modules to copy from the source image"),
                                              GDK_KEY_c, GDK_CONTROL_MASK | GDK_SHIFT_MASK);
```
rather than two more lines in init/connect_key_accels. As a side effect, some additional buttons can now be used via shortcuts.

### cleanup of unnecessary / incorrect help links for modules

Somewhat separately (but touching the same code areas) this removes explicit linking to module help pages that were already generically set up in `dt_view_manager_switch_by_view`. Some links were also (hopefully) corrected, so that more widgets are clickable with the help-pointer (which can now be toggled via a shortcut). For example the shortcut button itself (and the rest of the top-right toolbox).

### CODE REVIEW

**Comment by dterrahe** [comment]
@TurboGit this will create some merge conflicts with #11482 since both touch a lot of similar code, but I'm happy to rebase this after you merge the other PR; nothing complicated.

**Review by TurboGit — COMMENTED** [review]
A nice clean-up !

I have done many checks and all seems ok. One thing I have noticed when I first started dt I had lot of Gtk+ CRITICALS message on the console. I tried to reproduce after by looking at the console to see which elements was creating it... But I was not able to reproduce, restarted many time, no luck...

Have you seen that? Could this be an issue only at the first start with the new system.

**Comment by dterrahe** [comment]
> I had lot of Gtk+ CRITICALS message on the console

Haven't seen that and can't think of a reason this PR would cause that. Were you running in a clean directory or could this be a leftover from testing another PR?

**Comment by TurboGit** [comment]
> Were you running in a clean directory or could this be a leftover from testing another PR?

Could be from another testing, no sure. I've done many things/checks tonight. We'll see when I test it again. BTW, the PR you referenced has been merged, so conflicts are to be resolved here now. TIA.

**Comment by dterrahe** [comment]
Rebased.

Also fixed a few bauhaus label translations that would break shortcuts when switching languages.

**Review by TurboGit — APPROVED** [review]
Thanks! Better merging this sooner than later to ensure a good field testing.

**Pull request merged**
