### PR TITLE
Guided laplacian/Chroma diffusion : avoid diffusing the norm

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Just cherry-picked from authors fork

### CODE REVIEW

**Comment by TurboGit** [comment]
If a full cherry-pick we need to keep authorship. I'll do this if you agree before merging.

BTW, OP does not respect the authorship on its side and this is very problematic, many of our works is just taken as-is and committed with OP as author. I have warned OP that this is not correct at all, we must strive to avoid doing the same.

**Comment by jenshannoschwalm** [comment]
> If a full cherry-pick we need to keep authorship. I'll do this if you agree before merging.

Absolutely. Just don't know how to do that correctly.

**Comment by TurboGit** [comment]
> > If a full cherry-pick we need to keep authorship. I'll do this if you agree before merging.
> 
> Absolutely. Just don't know how to do that correctly.

Ok, you have two solutions:

1. Add remote for OP Git repo say `ansel`

Then just do:
```
$ git fetch ansel
look for commit and cherry-pick:
$ git cherry-pick <SHA-1>
```

2. As you've done for this PR but at the time of the commit:

`$ git commit --author="Firstname Name <firstname.name@here.com>"`

The commit will be yours, but the authorship will be given to the author specified.

**Comment by TurboGit** [comment]
Manually merged with authorship preserved. Thanks.

**Comment by jenshannoschwalm** [comment]
Thanks a lot for the info. Will do correctly next time ...

**Pull request closed without merging**
