### PR TITLE
Fix missing map module on macOS homebrew builds

### PR DESCRIPTION
**Pull request by zisoft**
A required library `libsoup@2` needs to be correctly linked for homebrew, otherwise cmake cannot find `osmgpsmap-1.0` and the Map module is missing.

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Thanks for the PR. And thanks for the work on MacOS. Just a word as you're the official new maintainer for MacOS I'll now trust your word for everything MacOS related as I don't have a way to check all this. So if you are unsure please let me know and we can ask @MStraeten to have a look or give its feedback.

All in all, I'm very pleased to see the MacOS port moving forward, a very big and sincere thanks to you and I'm sure all MacOS users will join me here.

**Comment by zisoft** [comment]
@TurboGit thank you very much 🙏

**Comment by victoryforce** [comment]
@zisoft I join in the thanks. Now we have the opportunity to give masOS darktable some much needed care and love.

@TurboGit How do you feel about creating a GitHub Team for those working on masOS darktable? At least for the sake of @mentioning, although they can use [other features provided by GitHub](https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams).

**Comment by zisoft** [comment]
@victoryforce thank you 🙏

**Comment by TurboGit** [comment]
> @TurboGit How do you feel about creating a GitHub Team for those working on masOS darktable? At least for the sake of @mentioning, although they can use [other features provided by GitHub](https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams).

I'll try to do that if I find a way around the complexity of the GitHub domain management :) The group could be names `macos`. Ok?

**Comment by zisoft** [comment]
Would it be possible to get a few more permissions on github? I would like to clean up the macOS related issues. For example issue 13376 can be closed (no link by intent, I don't want to leave a mention to this discussion in that issue).

Or to mark issues with scope _macos support_

(sorry for being offtopic here...)

**Comment by TurboGit** [comment]
> Would it be possible to get a few more permissions on github?

Sure, you should have received an invitation to join the team.

**Comment by zisoft** [comment]
Thank you! 👍

**Pull request merged**
