### PR TITLE
export metadata: replace preferences menu by button next export one

### LINKED ISSUE #11466: Saving edited metadata in the JPEG exif on export
Feature request: I spend so much time editing metadata in my photographs, but I can't see anything (other then CAMERA metadata) in the exported JPEG's EXIF.

If I edit "title", "author" (...) fields in metadata, I'd like to see them in the exif in the exported JPEG

### PR DESCRIPTION
**Pull request by phweyland**
- reverts partially #7294
- fixes #11466

### CODE REVIEW

**Comment by elstoc** [comment]
I'm fine with consistency but I've never been overly fond of putting the preferences in the presets menu -- IMO it's just a bit too hidden away there. We could also do consistency by putting buttons in the module UI. BTW we already have such preferences as a collapsible menu in import (though here we call them "parameters").

**Comment by AlicVB** [comment]
well, if I read correctly @phweyland coment in #11466 
> BTW don't forget metadata preferences are embedded in presets (each preset can have its own metadata preferences).

that's not real preferences, but much more module settings... On the other hand, I don't like the "button to open a dialog to get/set params" way. Not really consistent with other parts of dt imho.
I would vote for a collapsible section, like we have in import.
And btw, I'm sure we can put other parameters inside another collapsible too (the ones in the bottom esp.)

**Comment by phweyland** [comment]
@alicvb, Correct.
In metadata settings there are 2 parts. The first is a list of check boxes which can set easily in the module body (collapsible or not). The second one is a list of specific metadata plus the corresponding formula. This one won't set properly inside the module body. So any way we'll have a pop up window, right ?

**Comment by phweyland** [comment]
> I never really understood the desire to move stuff out of global preferences

The closer they are to the module the easier they are to find.

**Comment by TurboGit** [comment]
> I would vote for a collapsible section, like we have in import.

I fear this won't fit in the module which are not wide enough to display what the export dialog contains.

**Comment by AlicVB** [comment]
> I fear this won't fit in the module which are not wide enough to display what the export dialog contains.

you're right (I didn't remember of the right part of the dialog)... so we may have to keep the dialog somehow then... (or put that in a popover)
Considering the type of data it contains, I think it would be better to have this inside the module UI...

What about a line that would say "3 metadatas exported" followed by a gear or whatever that would open the dialog ?? (I even think that a popover would be better to emphasis on the fact that this are parameters (thus saved inside presets)

**Comment by elstoc** [comment]
Personally, I would prefer a gear icon in the module header as a way of consistently and clearly flagging the existence of additional preferences.

**Comment by TurboGit** [comment]
> Personally, I would prefer a gear icon in the module header as a way of consistently and clearly flagging the existence of additional preferences.

Not sure about this. Many apps have now an hamburger like icon (in Android especially) to access preferences. That's the case also of Firefox that I'm using to type this text and this icon is always placed top-right. So to me we are not so different here.

**Comment by gi-man** [comment]
I think a simpler approach is to keep the export metadata exportation as it is but add one extra field in the module global options: Include metadata (from preferences) Yes/No

This way we can enable most of the metadata check boxes in the preferences settings, but keep the Options include the metadata default to No.

**Comment by Nilvus** [comment]
About all your proposals, I think using collapsible sections is the best way. Of course, as @TurboGit says, all metadata options won't fit into it but left column, yes. And most users will probably only use left column only. We could then propose and advanced option to open dialog window with right column (a gear button for example). Indeed, they are more export options like settings of the module. So more like collapsible section of import module than, for example, settings in preferences menu of collections one.

**Comment by TurboGit** [comment]
Closing, we will revisit this if needed.

**Pull request closed without merging**
