### PR TITLE
[GUI] Use ngettext to ensure correct translation of text in the plural form

### PR DESCRIPTION
**Pull request by victoryforce**
The singular form in the ngettext call will never be used for translation in the current code, but ngettext is needed to ensure the correct plural form in translations.

### CODE REVIEW

**Comment by dterrahe** [comment]
Maybe the `if(i > 1)` could be removed then? It looks to me like it was just there to avoid a grammatically incorrect message...

**Comment by victoryforce** [comment]
I doubt it was done for that purpose, rather I'm pretty sure the code author decided that this message shouldn't be shown when the action only applied to one image. That is, the message is made to draw attention to the fact that the action is applied to the entire selection of images.

**Comment by TurboGit** [comment]
> I doubt it was done for that purpose, rather I'm pretty sure the code author decided that this message shouldn't be shown when the action only applied to one image. That is, the message is made to draw attention to the fact that the action is applied to the entire selection of images.

But then we only need the plural form, no?

**Comment by victoryforce** [comment]
> But then we only need the plural form, no?

Yes, as I wrote in comment, the singular form in the ngettext call will never be actually used for translation in context of this code (but this parameter must be present in the ngettext call).

**Comment by TurboGit** [comment]
I understand this yes, but this does nothing in the code except introducing a new string. So, my question is why? Is that to make it clear to translator using poedit that there is a plural form? If not, then please explain why this? And I fully understand that this path is correct and will not break anything, I'm just trying to understand the rational.

**Comment by victoryforce** [comment]
> I understand this yes, but this does nothing in the code except introducing a new string.

We not __just__ introduce a new string, we introduce ngettext call.

> So, my question is why?

Short answer is to ensure the correct plural form in translations. More details below.

> Is that to make it clear to translator using poedit that there is a plural form? If not, then please explain why this? And I fully understand that this path is correct and will not break anything, I'm just trying to understand the rational.

What is the problem we are trying to solve?

There are languages with several plural forms. In such languages, the translation of a specific phrase will depend on which number is part of the phrase. For example, in the Ukrainian language we have three forms, special cases for numbers ending in 1 and 2, 3, 4, except those ending in 11, 12, 13, 14. Therefore, the gettext framework needs to have a number at the input in order to produce the correct translation. This is exactly what ngettext() does.

Without calling ngettext, as it was before this patch, the localization system will not be able to make correct translations for different plural forms.

**Comment by victoryforce** [comment]
Perhaps the best way to understand this area will not be my short explanations, but [this page](https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html), where everything is explained clearly, comprehensibly and at the same time not very verbose.

**Review by TurboGit — APPROVED** [review]
Thanks for your patience and explanation :) I understand now.

**Pull request merged**
