### PR TITLE
use gtk_widget_activate to click non-toggle button

### LINKED ISSUE #9428: NG input: copy/paste shortcuts doesn't work in culling/preview mode
**Describe the bug/issue**
Since new shortcut manager, ctrl+c/ctrl+v and shift+ctrl+c/shift+ctrl+v doesn't work in culling/preview modes.

@dterrahe: probably for you.

**To Reproduce**

Just try them in culling or preview mode. For culling mode, I tested with 2 images but should be the same with more images.

Shortcuts works well in lighttable file manager default view and in darkroom and were working well with older system.

**Expected behavior**
Having those shortcuts working great in culling/preview modes.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.7.0+200~g76d1a261e
* OS                : Linux Ubuntu 21.04

### LINKED ISSUE #9464: Ctrl+A not working...no way to select all files in FileManager view...could not find entry in new presets either
My apologies if i am missing something but it seems at least in Windows...ctrl A is no longer defined and so you can't use it to select all files....

I tried to look through the new presets and only found a reference for select file not all files....

image

EDIT: Seems to be defined in config file after some deeper digging

### LINKED ISSUE #9469: [DT 3.7]  The keyboard shortcuts work only if corresponding menu items are visible/active/opened
I just found out from issue #9464 that keyboard shortcuts behavior has basically changed in darktable 3.6/3.7. Keyboard shortcuts work only if corresponding entries or menus are visible or active. 

In some cases this leads to unnecessary limitation of usability. 

An example is described in issue #9464. Ctrl+a selects only if the "select" menu in lighttable is expanded. Here is the short screen capture:

https://user-images.githubusercontent.com/38165484/125025512-143fdf80-e083-11eb-8618-0f12f95bc942.mp4

Another example is my use of the keyboard shortcut "s" for creating a snapshot in darkroom. I used this keyboard shortcut to create a snapshot in full screen with closed side panels. This was very useful to compare before and after photos without disturbing side panels. This in turn I use as thumbnail for Youtube videos. Here is an example: 

Darktable_38

This is not possible anymore:

https://user-images.githubusercontent.com/38165484/125026294-88c74e00-e084-11eb-8234-013e48387527.mp4

**Expected behavior**

Keyboard shortcuts should work regardless of the visibility/activation of the corresponding menu. 

**Platform**

* darktable version :3.7.0~git277.0f575bc2bd-1
* Linux - Distro    : Kubuntu 20.04
* OpenCL activated  : yes

### PR DESCRIPTION
**Pull request by dterrahe**
fixes #9428
fixes #9469
fixes #9464

@Nilvus would you please test if this works with hidden and visible buttons?

### CODE REVIEW

**Review by Nilvus — APPROVED** [review]
@dterrahe: thanks for that quick fix. I suppose that when you talk about testing with hidden and visible button is so to have right panel and development menu visible and expanded or not. I so tested both and I can confirm it works really great and fast with that PR. It's so fixes my issue. Great work!

**Review by TurboGit — APPROVED** [review]
Thanks !

**Review by TurboGit — APPROVED** [review]
Thanks !

**Comment by s7habo** [comment]
Now everything works as it should. Thanks a lot @dterrahe !

**Pull request merged**
