### PR TITLE
cmake: Fail if we don't have llvm for testbuild opencl programs

### PR DESCRIPTION
**Pull request by cryptomilk**
This is just a small cleanup to directly fail we want to testbuild but don't have the right tools available.

### CODE REVIEW

**Comment by MStraeten** [comment]
This patch makes it impossible to build darktable on osx using the instructions on https://github.com/darktable-org/darktable/blob/master/packaging/macosx/BUILD.txt

**Comment by cryptomilk** [comment]
Well, you should provide the error message you're getting. I don't have OSX

**Comment by parafin** [comment]
I think default for TESTBUILD_OPENCL_PROGRAMS has to be changed to OFF if this change to be accepted. Otherwise I think it’s a good idea for configure system not to switch options on and off automatically, it just adds pain for packagers.

**Comment by cryptomilk** [comment]
I'm fine switching it off, but I still want to see what actually fails and why :-)

**Comment by parafin** [comment]
Probably it fails because that option is ON and llvm is not found.

**Comment by MStraeten** [comment]
cmake .. \
 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.7 \
 -DCMAKE_C_FLAGS=-I/opt/local/include/libomp \
 -DCMAKE_CXX_FLAGS="-stdlib=libc++ -I/opt/local/include/libomp" \
 -DCMAKE_LIBRARY_PATH=/opt/local/lib/libomp \
 -DBINARY_PACKAGE_BUILD=ON \
 -DRAWSPEED_ENABLE_LTO=ON

returns:
....
-- Could NOT find LLVM (missing: LLVM_DIR)
CMake Warning at CMakeLists.txt:377 (message):
  Could not find LLVM 3.9+
...

**Comment by MStraeten** [comment]
but it seems to exist: 
clang --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by parafin** [comment]
Yeah, I've never investigated what exactly is needed for OpenCL kernel compilation, but I doubt Xcode LLVM is enough. Probably custom-build vanilla clang is needed.

**Comment by cryptomilk** [comment]
I'm sorry, but clang is a C compiler and LLVM is a compiler infrastructure. It is looking for the development tools of LLVM (the compiler infastructure) not the C compiler!

In Linux terms this means the `llvm-devel` package is missing!

**Comment by homer3018** [comment]
Hello everyone.
Noob here. I'm having issues with the compilation of what's needed for OpenCL (issue #2568 ) and I was wondering if what you're discussing and the issue I face could be related.
Apologies if this is not related.

**Comment by cryptomilk** [comment]
@homer3018 totally unrelated! :-)

@MStraeten Does it work if you install llvm devel files?

**Comment by MStraeten** [comment]
I installed llvm-8 and clang-8 from macports but llvm-config isnt in the path. Apples compilers are detected further. Unfortunately i dont know, what‘s needed to replace the default osx build chain. The Build instructions seems to be tailored for the apple toolchain. Setting LLVM_DIR or replacing CC environment variables as i was told via irc resulted in a completely messup of the build environment.

**Comment by parafin** [comment]
I wouldn't advice trying to replace Xcode compiler - it will end in tears.
I suggest to remove this functionality for Mac platform from cmake (`if(NOT APPLE)`), since I don't think anybody is interested in it.

**Comment by cryptomilk** [comment]
I've change the default to OFF on Apple and Win32.

**Comment by cryptomilk** [comment]
Rebased to master ...

**Comment by cryptomilk** [comment]
I've rebased the patch and adopted it for master.

**Comment by cryptomilk** [comment]
@TurboGit What are we doing with this?

**Comment by cryptomilk** [comment]
There doesn't seem to be interest in this ...

**Pull request closed without merging**
