### PR TITLE
imageio: support writing metadata to XCF

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by TurboGit** [comment]
@kmilos : I need you input for testing this PR. I have exported a picture in .xcf and opened it in GIMP. Looking at the metadata in GIMP I see nothing in `Image -> Metadata -> View Metadata` or in `Image -> Image Properties`.

**Comment by kmilos** [comment]
Need to have all the metadata boxes checked in the export preferences (same applies like we had fixed for AVIF/EXR/JEPG XL for 4.2.0) in order to handle the opt-in privacy issue...

**Comment by TurboGit** [comment]
> Need to have all the metadata boxes checked in the export preferences

I missed the tags box checked... All good now on my side. Thanks.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by kmilos** [comment]
Up to you of course, but this one might actually be safe/simple to include in 4.2.1 and update the release notes so AVIF/EXR/JPEG XL/XCF are all nicely bunched together... If so, I can prepare a new PR (because imageio.c moved)?

**Comment by TurboGit** [comment]
Not urgent and/or critical and it is an enhancement so let's keep that for 4.4 only.

**Comment by kmilos** [comment]
Sure, no probs.

**Pull request merged**
