### PR TITLE
Windows: install ImageMagick libraries

### PR DESCRIPTION
**Pull request by kmilos**
@victoryforce This is WIP, still needs fixing up of bundling dependencies (I think for both GM and IM coders) ~~in packaging/CMakeLists.txt~~

Edit: decided to manually add the handful of dependencies only for the formats we rely on from GM or IM (really only jp2, jxl, miff, and webp from our list have external dependencies, others are handled by GM/IM internally).

### CODE REVIEW

**Comment by kmilos** [comment]
Tested w/  `-DUSE_GRAPHICSMAGICK=OFF -DUSE_IMAGEMAGICK=ON -DUSE_JXL=OFF -DUSE_WEBP=OFF` and I could import both JXL and WebP.

**Comment by victoryforce** [comment]
@kmilos Thanks, that's great. I will try to find time tomorrow and test.

**Comment by victoryforce** [comment]
> Tested w/ `-DUSE_GRAPHICSMAGICK=OFF -DUSE_IMAGEMAGICK=ON -DUSE_JXL=OFF -DUSE_WEBP=OFF` and I could import both JXL and WebP.

Promising start, I was also able to import JXL images! So at least you managed to bring IM in the Windows environment to a working state. I will test further on a larger set of images.

**Comment by victoryforce** [comment]
@kmilos Unfortunately, when working through the IM library, dt segfaults on my JXL image collection (on which the native loader works fine). I'm currently looking for a minimal reproducer (if the problem is in the specific image(s) and not some contextual stuff).

😢

**Comment by kmilos** [comment]
> dt segfaults on my JXL image collection

I guess you could try just IM's `magick` CLI to see if it really is just down to IM implementation...

**Comment by victoryforce** [comment]
> > dt segfaults on my JXL image collection
> 
> I guess you could try just IM's `magick` CLI to see if it really is just down to IM implementation...

Yes, this is a bug in the IM implementation. imdisplay.exe also crashes on this image.

You can download this image from the URL in the comments to this issue: https://github.com/libjxl/libjxl/issues/716
(namely from https://www.earth.org.uk/img/data-4.png.jxl)

**Comment by kmilos** [comment]
That's both good and bad news I guess. Unfortunately msys2 ships v52 of IM 7.1.0, while latest seems to be 55... Not sure I'll have time to build, but I will also try the OOTB MSVC binaries tomorrow...

**Comment by victoryforce** [comment]
The latest as of today is 7.1.0-56. And the good news is that imdisplay from this version (native Windows build, I mean) no longer crashes on my reproducer. We can expect msys2 to be no different in this regard. Although, of course, it would be correct to wait for the new IM version in msys2 and test with it.

**Comment by kmilos** [comment]
No longer "wip" as far as I'm concerned...

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
