### PR TITLE
Let's require gcc8 for darktable

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
1. required version in compiler-versions
2. relaxed tests for version in code base

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Looks good to me, thanks!

**Comment by LebedevRI** [comment]
This is not really correct.
The proper solution is to either just drop darktable's `compiler-versions.cmake`,
or keep it in sync with the one in rawspeed.

**Comment by jenshannoschwalm** [comment]
Sorry, i simply forgot that rawspeed had it's own `compiler-version` setup. Don't know yet what the "really correct" way would be. Probably keep in sync.

**Comment by LebedevRI** [comment]
> Sorry, i simply forgot that rawspeed had it's own `compiler-version` setup. Don't know yet what the "really correct" way would be.

> Probably keep in sync.

Yeah, i forgot to do that when updating the submodule.

**Pull request merged**
