### PR TITLE
drawn masks: fix for curved gradient

### PR DESCRIPTION
**Pull request by upegelow**
hopefully fixing #3907 and #3918

### CODE REVIEW

**Comment by TurboGit** [comment]
Will have a look ASAP.

Also I have spotted a discrepancies. In creation mode the mouse scroll change the gradient, in edit mode it changes the curvature.

**Comment by upegelow** [comment]
Am 29.12.19 um 16:49 schrieb Pascal Obry:
> Also I have spotted a discrepancies. In creation mode the mouse scroll 
> change the gradient, in edit mode it changes the curvature.

Certainly this has to be consistent.

**Comment by TurboGit** [comment]
And I think mouse scroll should change the form as for all other shapes. Changing the gradient should be mouse scroll. Ok for you?

**Comment by upegelow** [comment]
Am 29.12.19 um 17:14 schrieb Pascal Obry:
> And I think mouse scroll should change the form as for all other shapes. 
> Changing the gradient should be mouse scroll. Ok for you?

I was considering to allow change of curvature only after the gradient 
is created.

The way how all these scroll actions work is by storing the last value 
in darktablerc. So next time the same form is created we start with the 
previous value (e.g. diameter of a circle/ellipse).

For the gradient I assume that 99% of the cases the user wants a 
straigth line. A curved gradient is a very special case and users might 
be irritated to suddenly find that all new gradients are curved.

**Comment by TurboGit** [comment]
Makes sense. Let's go with that.

**Comment by upegelow** [comment]
Am 29.12.19 um 17:29 schrieb Pascal Obry:
> Makes sense. Let's go with that.
> 
I will add a commit to the existing PR.

**Comment by jenshannoschwalm** [comment]
I just tested this pr; the lagging feels much better (you can pick the anchor and rotate but drawing that takes up to 2 secs)
but there are still wrong lines visible like before.

**Comment by upegelow** [comment]
Am 29.12.19 um 17:57 schrieb Hanno Schwalm:
> I just tested this pr; the lagging feels much better (you can pick the 
> anchor and rotate but drawing that takes up to 2 secs)
> but there are still wrong lines visible like before.
> 

Here everything is very responsive, even when selecting lens correction 
with a strong distorting lens (e.g. Leica lens of a Panasonic FZ1000).

Probably there are some issues if we feed coordinates which are too far 
outside of the image frame into transform/backtransform of lens 
correction. For calculating the gradient guides we do so in order to 
have some meaningful indicators when the user shifts the gradient. 
Admittedly the guides extend quite a lot. I'll try to make this behave 
more reasonable.

BTW: please suggest a camera/lens combination for further testing.

**Comment by jenshannoschwalm** [comment]
Leica Q, has a fixed lens with pretty strong correction. Test image available in pixls - i am using that for testing too - the lensfun file is
here.
[leica-q.xml.txt](https://github.com/darktable-org/darktable/files/4008373/leica-q.xml.txt)

**Comment by upegelow** [comment]
Am 29.12.19 um 18:46 schrieb Hanno Schwalm:
> Leica Q, has a fixed lens with pretty strong correction. Test image 
> available in pixls - i am using that for testing too - the lensfun file is
> here.
> leica-q.xml.txt 
> <https://github.com/darktable-org/darktable/files/4008373/leica-q.xml.txt>
> 

Interesting :) That profile seems to behave very badly if confronted 
with coordinates too far out of the image frame. I will need to dig a 
bit deeper into that issue.

**Comment by upegelow** [comment]
It's not specific for the gradient shape. If you make a circle shape 
large enough and shift it far outside the frame (zoom out to 8%) the 
lens correction module goes all berserk.

**Comment by TurboGit** [comment]
This last version looks good to me. If there is still an issue with the lens correction I suppose we should fix that in another PR. Will merge this in master and 3.0.1. Thanks.

**Comment by TurboGit** [comment]
Actually the curve gradient is for 3.2, so only merged in master.

**Comment by jenshannoschwalm** [comment]
@upegelow latest commit fixes here too :-)

**Comment by jenshannoschwalm** [comment]
> Actually the curve gradient is for 3.2, so only merged in master.

Is that decision debatable? At least for some Leicas it would mean a severe restriction for any 3.0.x version. And there are more issues around that could be related.

**Comment by TurboGit** [comment]
@jenshannoschwalm : Yes, that's an open project, everything is debatable as long as the solution is workable.

**Comment by upegelow** [comment]
Am 29.12.19 um 21:08 schrieb Hanno Schwalm:
> @upegelow <https://github.com/upegelow> latest commit fixes here too :-)
> 
I think we have a general topic with the transform/backtransform logic 
here. What input value are permissible? How can we tell between valid 
and invalid output values? I think this is not defined but should be.

**Pull request merged**
