### PR TITLE
po/liquify missed updates

### PR DESCRIPTION
**Pull request by TurboGit**
Fix part one of #12573.

Still no idea about the 2nd and 3rd issues.

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
Are you sure that changing any of the nodes or segments is reflected by a change in the parameter struct? That would mean the hash doesn't change resulting in a wrong cache line?

**Comment by TurboGit** [comment]
> Are you sure that changing any of the nodes or segments is reflected by a change in the parameter struct? That would mean the hash doesn't change resulting in a wrong cache line?

That was my thinking too, but at the moment it seems that the change is reflected. That's driving me crazy :(

**Comment by jenshannoschwalm** [comment]
And the pipeline is retaken?

**Comment by jenshannoschwalm** [comment]
I mean, the cache debug info should never have a hit here while the module is expanded.

**Comment by TurboGit** [comment]
I see this under dev debug:

```
2,994050 [pixelpipe_process] [preview] using device 0. Cache: used=126MB
43,050597 [pixelpipe_process] [preview] done. used=126MB, limit=0MB, hitrate=0,20
43,055502 [pixelpipe_process] [full] using device 0. Cache: freed=115MB (0/2), used=416MB, limit=498MB
43,189370 [pixelpipe_process] [full] done. used=520MB, limit=498MB, hitrate=0,10
```

When the redraw should be done. So a full pixelpipe process was done.

**Comment by jenshannoschwalm** [comment]
There is the extra - d verbose flag

**Comment by TurboGit** [comment]
Yes, and the cache handling seems good, at the time the refresh should have been done I see:

```
88,898087 [pixelpipe_process] [preview] using device 0. Cache: used=126MB
88,898315 [pixelpipe_cache_get]      preview important HIT           ashift, line  5, age   -5, at 0x7f599b597040, hash  15480231183350561536, basic  18392705661906364951
88,898323 [pixelpipe_cache_get]      preview                        liquify, line  8, age    7, at 0x7f59966c4040, hash   6430940927775136803, basic  13990198157982547124
88,918394 [pixelpipe_cache_get]      preview                       exposure, line 11, age    5, at 0x7f59916db040, hash  16159607489326048845, basic  16425193736361654170
88,919199 [pixelpipe_cache_get]      preview                        colorin, line  8, age 1001, at 0x7f59966c4040, hash  18446744073709551615, basic  18446744073709551615
88,920472 [dev_pixelpipe] [preview] module `colorin' passing important hint to next module
88,920478 [pixelpipe_cache_get]      preview important      channelmixerrgb, line 11, age 1001, at 0x7f59916db040, hash  18446744073709551615, basic  18446744073709551615
88,925269 [pixelpipe_cache_get]      preview                      filmicrgb, line  6, age    5, at 0x7f5998232040, hash   2443334036397982023, basic  14149483204942332944
88,929448 [pixelpipe_cache_get]      preview important             colorout, line 11, age 1001, at 0x7f59916db040, hash  18446744073709551615, basic  18446744073709551615
88,948968 [pixelpipe_cache_get]      preview important HIT            gamma, line  4, age   -4, at 0x7f5998fe9040, hash                     0, basic                     0
88,962637 [pixelpipe_process] [preview] done. used=126MB, limit=0MB, hitrate=0,20
88,964926   [free cacheline] [full]            gamma, line  2, age  -24, size=81MB at 0x7f59c0324040
88,965060   [free cacheline] [full]          colorin, line  4, age  -29, size=34MB at 0x7f59bbdc4040
88,965183 [pixelpipe_process] [full] using device 0. Cache: freed=115MB (0/2), used=416MB, limit=498MB
88,965365 [pixelpipe_cache_get]         full important HIT           ashift, line  5, age  -57, at 0x7f59b66ac040, hash  17538362633728683217, basic  18392705661906364951
88,965380 [pixelpipe_cache_get]         full           NEW          liquify, line  2, age 1002, at 0x7f59c373c040, hash  18446744073709551615, basic  18446744073709551615
88,992818 [pixelpipe_cache_get]         full           NEW         exposure, line  4, age 1003, at 0x7f59c148c040, hash  18446744073709551615, basic  18446744073709551615
88,994755 [pixelpipe_cache_get]         full           NEW          colorin, line 14, age   58, at 0x7f59bbdc4040, hash  18446744073709551615, basic  18446744073709551615
88,996997 [dev_pixelpipe] [full] module `colorin' passing important hint to next module
88,997004 [pixelpipe_cache_get]         full important      channelmixerrgb, line  2, age 1002, at 0x7f59c373c040, hash  18446744073709551615, basic  18446744073709551615
89,009340 [pixelpipe_cache_get]         full                      filmicrgb, line  4, age 1002, at 0x7f59c148c040, hash  18446744073709551615, basic  18446744073709551615
89,013716 [pixelpipe_cache_get]         full                       colorout, line  2, age 1001, at 0x7f59c373c040, hash  18446744073709551615, basic  18446744073709551615
89,088973 [pixelpipe_cache_get]         full important                gamma, line 10, age   10, at 0x7f59afd58040, hash  18044426173865791900, basic  16425193736361654170
89,098062 [pixelpipe_process] [full] done. used=520MB, limit=498MB, hitrate=0,10
```

So we have a FULL & NEW run for liquify.

**Comment by jenshannoschwalm** [comment]
I see your work on making sure everything is  in params. All issues fixed now?

**Comment by TurboGit** [comment]
No, all my clean-up has not fixed the issue ! At least the code is less confusing. That's already a nice step.

**Comment by TurboGit** [comment]
> Sure. Will just finish preparing the opposed inpaint pr before that.

Great! Maybe it is just a stupid mistake and I do not spot it...

> Why not merge this as is first?

Sure, I'll keep it on my branch for some more time and will merge soon.

**Comment by jenshannoschwalm** [comment]
Before going into it
a) i guess you have checked cairo redrawing taking place already?
b) i don't know the code at all (yet :-) any masks needing to be transformed having no calls?

**Comment by TurboGit** [comment]
> Before going into it 
> a) i guess you have checked cairo redrawing taking place already? 

Yes.

> b) i don't know the code at all (yet :-) any masks needing to be transformed having no calls?

I don't think so.

This really looks like some race condition between the distortion and the actual params being set.

To reproduce:
- Create a curve with 3 nodes
- On the middle point, ctrl+clic
- When the node is displaying the 2 controls of the bezier curve, just move them a lot to ge a well visible distortion
- No ctrl+clic on the same middle point, the the controls are no more visible (autosmooth mode) see that the cairo curve is properly drawn but the distortion is not changed.
- Now just slightly drag&drop any control on canvas (center point, strength-point, node handle to change size)... And you'll see that the distortion is applied.

**Comment by TurboGit** [comment]
From there:
image

To there (distortion not applied):

image

And if I move slightly first node on top:

image

**Comment by TurboGit** [comment]
This is now merged, mostly code refactoring & clean-up. The bug is still there.

**Comment by TurboGit** [comment]
@jenshannoschwalm : I found the issue... I'll issue a PR in a moment ! A relief... This was really driving me crazy !!!!

**Pull request merged**
