### PR TITLE
Fix OpenCL

### PR DESCRIPTION
**Pull request by cryptomilk**
This fixes OpenCL with ROCm for me.

### CODE REVIEW

**Comment by cryptomilk** [comment]
@aurelienpierre

**Comment by TurboGit** [comment]
Sound good! We had discussed that with Aurélien some time ago and were surprised that the const was accepted here.

**Comment by aurelienpierre** [comment]
Thanks @cryptomilk

**Comment by aurelienpierre** [comment]
Just out of curiosity, what was broken ? @cryptomilk

**Comment by TurboGit** [comment]
It was a compilation issue.

**Pull request merged**
