### PR TITLE
adobe_coeff.c: provisional Fujifilm X100F support

### PR DESCRIPTION
**Pull request by dtorop**
Data copied from X-T2. This is the same data which LibRaw is using. Appears fine judging from test images, but does not come from a DNG.

### CODE REVIEW

**Comment by LebedevRI** [comment]
Why do you think it would use `X-T2`/`X-Pro2` color matrix, while both `Fujifilm X100S` an `Fujifilm X100T` use the same matrix, which is not the same as for `X-T2`/`X-Pro2`?

**Comment by dtorop** [comment]
> Why do you think it would use X-T2/X-Pro2 color matrix, while both Fujifilm X100S an Fujifilm X100T use the same matrix, which is not the same as for X-T2/X-Pro2?

The X100F uses the 3rd gen. sensor (https://en.wikipedia.org/wiki/Fujifilm_X-Trans_sensor#List_of_X-Trans_sensors) which it shares with the X-T2/X-Pro2, so more likely its characteristics align with those than X100S/X100T.

But within generations there are divergences, e.g. for gen 2 16MP, X100S and X100T matrices match, but the matrices for X-T1, X-T10, X-E2 are different (and match each other), while the X70 is totally different.

`// 2nd gen. 16mp`
`    { "Fujifilm X100S", { 10592,-4262,-1008,-3514,11355,2465,-870,2025,6386 } },`
`    { "Fujifilm X100T", { 10592,-4262,-1008,-3514,11355,2465,-870,2025,6386 } },`
`    { "Fujifilm X-T10", { 8458,-2451,-855,-4597,12447,2407,-1475,2482,6526 } },`
`    { "Fujifilm X-T1", { 8458,-2451,-855,-4597,12447,2407,-1475,2482,6526 } },`
`    { "Fujifilm X-E2", { 8458,-2451,-855,-4597,12447,2407,-1475,2482,6526 } },`
`    { "Fujifilm X70", { 10450,-4329,-878,-3217,11105,2421,-752,1758,6519 } },`
`// 3rd gen.`
`    { "Fujifilm X-Pro2", { 11434,-4948,-1210,-3746,12042,1903,-666,1479,5235 } },`
`    { "Fujifilm X-T2", { 11434,-4948,-1210,-3746,12042,1903,-666,1479,5235 } },`

The relevant commit to LibRaw https://github.com/LibRaw/LibRaw/commit/7834056ad4ead68a8ad4ad6d1f8ffb89872ff54c is described as "(temp)". It looks like Adobe DNG Converter doesn't currently support the X100F (see https://helpx.adobe.com/camera-raw/kb/camera-raw-plug-supported-cameras.html#Fujifilm), and dcraw doesn't have an entry. Is there any other way to figure out a matrix?

So not sure what to do. This color matrix is workable, but judging from history, probably isn't right. Is it better to withdraw PR, merge a profile that may be wrong and fix it later, or leave this open/incomplete until a proper matrix is published, so in the meantime anyone who needs a quick fix of X100F support can pull it in by hand? Presumably any images edited with a wrong matrix will need to be re-edited?

**Comment by LebedevRI** [comment]
> The X100F uses the 3rd gen. sensor (https://en.wikipedia.org/wiki/Fujifilm_X-Trans_sensor#List_of_X-Trans_sensors) which it shares with the X-T2/X-Pro2, so more likely its characteristics align with those than X100S/X100T.

Aha, okay

> It looks like Adobe DNG Converter doesn't currently support the X100F (see https://helpx.adobe.com/camera-raw/kb/camera-raw-plug-supported-cameras.html#Fujifilm), and dcraw doesn't have an entry.

Yeah, all that i have already checked before commenting :/

> Is there any other way to figure out a matrix?

The adobe matrix - not that i know of.
But one can of course shoot color target and compute color matrix for himself.

> leave this open/incomplete until a proper matrix is published, so in the meantime anyone who needs a quick fix of X100F support can pull it in by hand?

This, i think.
Once the matrix is known, this is to be updated and merged.

> Presumably any images edited with a wrong matrix will need to be re-edited?

Yeah, currently the color matrix is not stored in history stack, so any changes (i.e. if we replace matrix) essentially destroys the history stack

Thanks for verbose reply.

**Comment by LebedevRI** [comment]
@dtorop i think the matrix has arrived.

**Comment by LebedevRI** [comment]
@dtorop, @schenlap: thank you both!

**Pull request closed without merging**
