### PR TITLE
po/iop instance name - remove hard coded style and use CSS 

### PR DESCRIPTION
**Pull request by TurboGit**
Rework module label / instance name.
    
Both label and instance name was a single label and some style
was directly generated in code by darktable to render the instance
name smaller and the trouble message red. This has been removed and
properly placed in CSS to be able to style those elements.

This mostly gives the same output that current master:

image

### CODE REVIEW

**Comment by TurboGit** [comment]
One more point, the trouble logo now replaces the instance-name. It was put in front because there was no other choice before (at then end and so being possibly ellipsized). Now that we have full control and that the module's instance-name is a first class citizen in the UI we have:

image

And no more jump of the IOP label when it is displayed.

**Comment by dterrahe** [comment]
Interesting. Haven't checked out or compiled yet, but just looking at the changes I'm surprised this works. You seem to be adding two labels to a GtkEventBox, which is supposed to be a GtkBin, so should only have one child.

Responding to https://github.com/darktable-org/darktable/issues/13660#issuecomment-1435022419:
> Do you know if we can have precedence between two consecutive labels for the ellipsis?

I don't think you can without taking over the allocation process which is normally based on the natural width of the labels. Having said that, in the module labels I already _did_ quite a lot of messing with the allocation process to implement #6224 (which could interact with/get broken by this PR). So that probably would need to be extended to allocate between the two labels _and_ the buttons.

**Comment by TurboGit** [comment]
> You seem to be adding two labels to a GtkEventBox, which is supposed to be a GtkBin, so should only have one child.

I don't think I do that.

> So that probably would need to be extended to allocate between the two labels _and_ the buttons.

So probably out of this PR.

**Comment by dterrahe** [comment]
> > You seem to be adding two labels to a GtkEventBox, which is supposed to be a GtkBin, so should only have one child.
> 
> I don't think I do that.

You are right; just me struggling to read diffs :-)

> > So that probably would need to be extended to allocate between the two labels _and_ the buttons.
> 
> So probably out of this PR.

Have you tried if there are any regressions in the button hiding? In the past the added "mask" button also broke it, but maybe I managed to make it more robust since then. But I _think_ it would still only be trying to resize the one label, at best, and not the now two.

**Comment by TurboGit** [comment]
> Have you tried if there are any regressions in the button hiding?

Yes no issue. It behaves as in current master.

> But I _think_ it would still only be trying to resize the one label, at best, and not the now two.

If we do this then it won't be possible to have a panel width as small as today as it will be blocked to at least contains the larger module name. I see no clean solution to this.

**Comment by TurboGit** [comment]
@jenshannoschwalm : This new version only do ellipsis the end of the module name and the middle of the instance name. Would that work better for you?

**Comment by MStraeten** [comment]
seems this needs some tweaking regarding fonts:
image
(win10 darktable-elegant-grey)

**Comment by TurboGit** [comment]
Can you test with:

```
#iop-module-name
{
  font-weight: normal;
  font-family: sans-serif;
  font-size: 0.8em;
}
```

and

```
#iop-module-name
{
  font-weight: lighter;
  font-family: sans-serif;
  font-size: 0.8em;
}
```

And tell me if one looks ok on Windows? TIA.

**Comment by TurboGit** [comment]
Ok, both are looking alike, I'll just add the sans-serif font. Thanks!

**Pull request merged**
