### PR TITLE
test picker event to prevent crash

### LINKED ISSUE #9468: Crashes using pipette to perform auto selection or optimizations
Using dev build 3.7+277 on Windows 10.

I seem to be getting quite a few crashes when using any of the auto pipettes in filmic or the second tab of color balance rgb. Example to have filmic set white relative with the picker....
[darktable_bt_DKEH60.txt](https://github.com/darktable-org/darktable/files/6788871/darktable_bt_DKEH60.txt)
[darktable_bt_D0E050.txt](https://github.com/darktable-org/darktable/files/6788872/darktable_bt_D0E050.txt)

See files attached

### LINKED ISSUE #9470: Darktable crashes when using white/contrast gray fulcum color picker in color balance rgb module
**Describe the bug/issue**

Darktable crashes when using white/contrast gray fulcum color picker in color balance rgb module

**To Reproduce**

1. Open corlor balance rgb module
2. Go to "masks" tab and click on one of color picker in section "treshold" (white or contrast gray fulcrum)

Darktable crashes.

[darktable_bt_TMZG60.txt](https://github.com/darktable-org/darktable/files/6789325/darktable_bt_TMZG60.txt)

* darktable version : 3.7.0~git277.0f575bc2bd-1
* OS                : Linux
* Linux - Distro    : Kubuntu 20.04
* Memory            : 
* Graphics card     : GeForce GTX 1070
* Graphics driver   : nvidia 460.80
* OpenCL installed  : yes
* OpenCL activated  : yes

### LINKED ISSUE #9480: Seg Fault with Filmic
**Describe the bug/issue**
Any attempt to use the 'auto-tune' button on filmic causes dt to freeze and then close.

**To Reproduce**
1. Open any image
2. Click on 'Filmic'
3. Check that sliders are working correctly ... OK
4. Click on 'auto-tune' button
5. darktable freezes and then closes.

[darktable_bt_CZS250.txt](https://github.com/darktable-org/darktable/files/6793367/darktable_bt_CZS250.txt)
[Terminal-bt.txt](https://github.com/darktable-org/darktable/files/6793371/Terminal-bt.txt)

2 log files attached

Which commit introduced the error** Git version:3.7.0+277~g0f575bc2bd 
I have tried a later version and the problem remains

**Platform** Linux

* darktable version : version:3.7.0+277~g0f575bc2bd 
* OS                : Linux - kernel 5.12.9-1
* Linux - Distro    :Manjaro/Arch
* Memory        16Gb.    : 
* Graphics card     Nvidia 
* Graphics driver   :Quadro K1000M 
* OpenCL installed  no
* OpenCL activated  no
* Xorg              : 
* Desktop           XFCE: 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? Version from prior day did NOT behave in this manner.
 - Can you reproduce with a RAW or Jpeg or both? RAW and DNG ... I do not have JPG for processing
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)?Yes
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes
   - What lua scripts start automatically? None
   - What lua scripts were running when the bug occurred? None

### PR DESCRIPTION
**Pull request by dterrahe**
fixes #9468
fixes #9470
fixes #9480

This fixes a sloppy bug introduced with #9441. Sorry.

Many thanks to @davidvj, @todd-prior and @s7habo for reporting and to @wpferguson for copying me in.

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Thanks !

**Comment by todd-prior** [comment]
Im to blame for this one....the right click virus was a favour to me.  :)

**Comment by dterrahe** [comment]
Absolutely not your fault that I messed up!

And you were right that something needed fixing there. Don't stop asking for improvements that we all benefit from.

**Comment by todd-prior** [comment]
Very grateful for that little fix. For me it works great and no visual interruption to get the ctrl key anymore. Its a very small thing but really nice to have thanks for caring and working to include this....



Get Outlook for Android

**Pull request merged**
