### PR TITLE
Details mask 4.6 reworked

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Why rework the code?
A short summary: The 'details-mask' is used for refining other masks and for dual demosaicers.
It's data are derived from Y0 gradients via a scharr operator.

To support both raws and sraws the first step was handled both in rawprepare and in demosaic, we prepared a preliminary mask there which is later scaled&cropped according the the 'mask using' module. The code was difficult to read, understand and maintain.

Also there were some implementation flaws:
1. When getting the resized &cropped mask we had to check for the preliminary mask writing module
2. Some tricks to make pixelpipe cache safe
3. The Y0 data were not 'pure' as all modules before demosaic (like raw cfa, hlr ...) could change data in a non predictable way. Also the demosaicer itself might add smoothing and itself does some approximations both leading to changed data. So the basic idea of using unprocessed Y0 data for details was not reached
4. Choosing a different region in darkroom mostly required a recalculation of the mask

So, basically a rewrite of the whole stuff. A short summary

1. The scharr mask is always written in rawprepare. a) for sraws we calculate from available rgb raw data b) for raws calculate Y0 by averaging a 5x5 region Both algos do some gaussian blur here for stability of scharr calcalculation
2. The validity of the mask is checked via a local hash taking roi_out and rawprepare parameters into account.
3. As we mostly have full data available in rawprepare we will have to recalculate the mask only after changing whitepoint or alike.
4. All modules later in the pipe requiring the details mask do so by calling dt_masks_calc_detail_mask(struct dt_dev_pixelpipe_iop_t *piece, const float threshold, const gboolean detail, const gboolean output) please note 'output', if true the mask is scaled to roi_out of piece, otherwise to roi_in.
5. We have subtle differences in the mask due to changed algorithm.
6. No opencl code yet
7. Proper mask visualizing in dual demosaicer
8. Adding a mask distortion function to demosaic

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
Forgot to mention, this PR does not work correctly until #14697 has been merged

**Comment by jenshannoschwalm** [comment]
Hold on -- some rebase problems ...

**Comment by jenshannoschwalm** [comment]
@TurboGit this PR is sort of a tricky beast. It reduces code complexity a lot, also details data are far more reliable and not affected by any module's processing until (and including) demosaic so a clear improvement. (btw the processing in rawprepare can be further improved by internal tiling doubling performance - i would do this after possibly merged)

There is one problem though, we will have subtle differences for the mask result, as i see it with better quality but a slight difference. We might want another regression test for masks using detail threshold here - or did i miss that?

**Comment by TurboGit** [comment]
> We might want another regression test for masks using detail threshold here - or did i miss that?

Do we already have a regression for detail masks? I don't remember...

**Comment by jenshannoschwalm** [comment]
I couldn't find one. Would be in masking tests I guess

**Comment by TurboGit** [comment]
I'll add a specific test for detail mask and will check against this PR.

**Comment by TurboGit** [comment]
The good news is that the diff between the CPU and OpenCL implementation is now smaller. The Max dE was 1.90169 and more than 126000 pixels differing.

The bad news is that the diff between the old and new algorithm is quite big:

```
Test 0150-detail-mask
      Image mire1.cr2
      CPU & GPU version differ by 24198 pixels
      CPU vs. GPU report :
      ----------------------------------
      Max dE                   : 1.44979
      Avg dE                   : 0.00407
      Std dE                   : 0.04741
      ----------------------------------
      Pixels below avg + 0 std : 99.13 %
      Pixels below avg + 1 std : 99.15 %
      Pixels below avg + 3 std : 99.18 %
      Pixels below avg + 6 std : 99.29 %
      Pixels below avg + 9 std : 99.47 %
      ----------------------------------
      Pixels above tolerance   : 0.00 %
 
      Expected CPU vs. current CPU report :
      ----------------------------------
      Max dE                   : 43.79417
      Avg dE                   : 0.95464
      Std dE                   : 2.62974
      ----------------------------------
      Pixels below avg + 0 std : 82.39 %
      Pixels below avg + 1 std : 89.80 %
      Pixels below avg + 3 std : 97.42 %
      Pixels below avg + 6 std : 99.61 %
      Pixels below avg + 9 std : 99.94 %
      ----------------------------------
      Pixels above tolerance   : 13.11 %
 
  FAILS: image visually changed
         see diff.png for visual difference
         (627021 pixels changed)
```

diff

**Comment by jenshannoschwalm** [comment]
I will see what I can do to improve it and come back later.

**Comment by TurboGit** [comment]
The test I have added is not yet merge and can be found there: 
https://github.com/darktable-org/darktable-tests/tree/po/detail-mask

**Comment by jenshannoschwalm** [comment]
> The test I have added is not yet merge and can be found there

Thanks, i will use it :-) I'll postpone this work until the raster-mask, lens-vignette and retouch stuff has been discussed, reviewed and hopefully merged :-)

**Comment by TurboGit** [comment]
> > The test I have added is not yet merge and can be found there
> 
> Thanks, i will use it :-) I'll postpone this work until the raster-mask, lens-vignette and retouch stuff has been discussed, reviewed and hopefully merged :-)

I'm slowly reviewing all the PR for 4.6...

**Comment by jenshannoschwalm** [comment]
@TurboGit @s7habo i have not been able to reduce difference in the test significantly. This is clearly due to the different maths preceding the calculation of the scharr mask. As this is inherent to the pixelpipe code (not only the demosaicer) the approach presented here works excellent in many cases but breaks edits on a per-use basis.

What could i do here - the proposed code works definitely better and more stable - 
1. Add some versioning in blend details. That would blow up code even more plus maintaining old code, so not so good to me.
2. Currently i am investigating a mask derived from local Y0-variance (a 9x9 pixel area), that would allow much better selection of "structures" like hair, fur or feathers. Maybe using the same slider but an additional button switching between methods...


Do you have other ideas ... ?

**Comment by s7habo** [comment]
I have no idea about any algorithms.  Maybe such an article can inspire you.

https://www.frontiersin.org/articles/10.3389/frsip.2022.826967/full

> Currently i am investigating a mask derived from local Y0-variance (a 9x9 pixel area), that would allow much better selection of "structures" like hair, fur or feathers. Maybe using the same slider but an additional button switching between methods...

I find this interesting idea and will gladly test it :grin:

**Pull request closed without merging**
