### PR TITLE
bugfix: dehaze turning image black

### LINKED ISSUE #7391: Haze module and other modules that rely on dt_box_* cause image deterioration or crash when enabled
WSL Ubuntu 20.04.1 LTS
Master : darktable 3.5.0+111~g3cca160f9

Compressed history to original.
Activate Haze module.
Image goes black.

Haze

Any image that was previously edited and has an active haze module in it, it goes black. Disabling it returns it to normalcy.

Problem is most visible with haze, but can cause problems/crashes with tone equalizer, bloom, soften, highpass and anything relying on dt_box_.

### LINKED ISSUE #7404: Inverted or incorrect colours in filmstrip and main image
**Describe the bug**

I am experiencing image display issues with builds of release-3.5.0-111-g3cca160f9 and release-3.5.0-127-g54fc5b4dd on Fedora 33.
With these builds, when I start darktable some of the images in the filmstrip appear to have inverted colours, e.g. all light areas such as sky are shown black. Selecting one of these images the full image is also displayed this way.
If I revert to a build of release-3.5.0-80-g94892dc6d, when started the filmstrip still shows the affected images in inverted colours, but when those images are selected the full display has correct colours and the filmstrip image is corrected.

**To Reproduce**
With builds of either release-3.5.0-111-g3cca160f9 or release-3.5.0-127-g54fc5b4dd

1. start darktable, some images in the filmstrip show inverted colours
2. select an affected image
3. the full image display is also shown inverted
4. revert to build release-3.5.0-80-g94892dc6d
5. start darktable
6. images in filmstrip shown with inverted colours in dt versions noted above are still shown inverted
7. select an affected image
8. the full display image is shown in correct colours and that image in the filmstrip has its colurs corrected.
-->

**Expected behavior**
Image colours to displayed correctly in filmstrip and main display

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: noted above
 - OS: Linux, Fedora 33
 -  No OpenCL
 - Nvidia GTX 750Ti, nouvou driver

**Additional context**

### PR DESCRIPTION
**Pull request by ralfbrown**
Attempt to fix #7391, fix #7404.

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
So the bug was the missing reduction?

**Comment by ralfbrown** [comment]
No, the reduction clause just tells the compiler that it's OK to break the dependency chain into multiple chains to enable SIMD, something I noticed could be added while taking an in-depth look at the code.

My guess is that what broke things is changing fmaxf/fminf to MAX/MIN macros.  But that shouldn't have made a difference even in the presence of NaNs, because the way glib defines those macros and my code uses them, the NaNs wouldn't propagate (MAX(NaN,b) returns b, and the loop is m=MAX(pixel,m) with m initialized to -INFINITY).  Unless the compiler went and swapped args, reversing the test to compensate....

**Comment by ralfbrown** [comment]
Well, I have good news and bad:
The good is that I'm suddenly able to reproduce the issue.
The bad is that this PR doesn't fix it....

I have run valgrind, and it's not an unitialized value or buffer overrun.  I likely won't be able to investigate further for a coupla days.

**Comment by jenshannoschwalm** [comment]
Maybe we misunderstand. But i really think you are not right here. There is the shared `float m` and we want to find the min/max over all threads. The reduction - imho - makes sure the data in `float m` are collected over **all** threads so the writing is done via atomic instructions, mutex protection or whatever the openmp implementation selects. For me this is a typical race condition. Or did i oversee something?

**Comment by TurboGit** [comment]
@ralfbrown : I confirm that this does not fix the issue on my side.

**Comment by TurboGit** [comment]
Just for the record I have disabled all the OpenMP code in the box_filters.c code and still see the issue. So looks like it is not a race condition, nor an OpenMP issue or reduction.

**Comment by johnny-bit** [comment]
Another issue affected by box_mean problem: #7410 - this affects tone equalizer.

**Comment by TurboGit** [comment]
See #7411 which seems obviously correct.

**Comment by TurboGit** [comment]
Closing as fixed in #7411 .

**Comment by ralfbrown** [comment]
> Maybe we misunderstand. But i really think you are not right here. There is the shared `float m` and we want to find the min/max over all threads. The reduction - imho - makes sure the data in `float m` are collected over **all** threads so the writing is done via atomic instructions, mutex protection or whatever the openmp implementation selects. For me this is a typical race condition. Or did i oversee something?

That particular loop is not parallelized.  (The function as a whole gets run in parallel, but each instance on a different part of the image.)
The reduction clause tells the compiler that it's OK to do a transformation like
```
for (int i = 0; i < width ; i += 4) {
   m1 = max(pixel[i],m1);
   m2 = max(pixel[i+1],m2);
   m3 = max(pixel[i+2],m3);
   m4 = max(pixel[i+3],m4);
}
  m = max(max(max(m1,m2),m3),m4);
```
after which it can obviously run m1...m4 as the four lanes of a SIMD instruction.  Without the reduction, it has to assume that the `m` in iteration i+1 depends on the `m` in iteration i, so it can't vectorize.

**Comment by jenshannoschwalm** [comment]
Aaah! Something new for me, thanks a lot for detailed explanation...

**Pull request closed without merging**
