### PR TITLE
modulegroup + presets fix focus

### LINKED ISSUE #8557: modulegroups: selected preset not always in bold
Start darktable with an empty config and load an image. Choose any module group preset from the list. The module group preset is changed but not highlighted in bold as it should be.

Enter the "manage presets" dialog and exit without changing anything and the preset is now correctly highlighted.

I suspect that there is some difference between how the "manage" screen saves presets and how they are initialised by the `init_presets` function in `modulegroups.c`, leading to a mismatch when the current module parameters are compared with the saved preset.

darktable 3.5.0+1545~g75e9b248e on ArchLinux.

ping @AlicVB

### LINKED ISSUE #8558: modulegroups: auto-preset checkbox has grey background
In modulegroups, manage presets screen, create a new preset and click on the gear button next to the autoapply text.

The first check box on the dialog that pops up has a light-grey background, possibly because that checkbox has keyboard focus?

Screenshot_2021-03-26_17-08-52

It would probably be best to start this dialog with focus on the 'cancel' button?

ping @AlicVB

### PR DESCRIPTION
**Pull request by AlicVB**
this fix #8557 
this fix #8558 

fix modulegroups built-in preset highlight in the preset menu.
put focus on cancel btn in presets dialog if the name and desc entries are disabled

### CODE REVIEW

**Comment by elstoc** [comment]
Thanks @AlicVB. If I select "search only" or "modules: deprecated" those items are still not in bold.

**Comment by AlicVB** [comment]
@elstoc : oops sorry, I've forgot that ones... should be fix now !

**Comment by elstoc** [comment]
All good now. Thanks @AlicVB.

**Review by TurboGit — APPROVED** [review]
Thanks !

**Pull request merged**
