### PR TITLE
remove some shapes from group

### LINKED ISSUE #13119: Mask manager is broken in master
Just a reminder that we have some pending issues in mask manager, affecting all OSs:
1) "delete this shape" doesn't work at all
2) "remove from group" remove all the shapes from group
See #12655 and #12656, also [here](https://discuss.pixls.us/t/cant-delete-brush-mask-bug-or-user-error/34048)

I rebuilt 4.01 and mask manager is working fine, so this is a serious regression and maybe we should try to fix this before 4.2.
On my side I will try to perform a bisect.
Thank you

### PR DESCRIPTION
**Pull request by dterrahe**
fixes https://github.com/darktable-org/darktable/issues/12655
fixes #13119

### CODE REVIEW

**Comment by wpferguson** [comment]
I made an extra instance of exposure, then added a circle and ellipse and bumped up exposure. Added another instance of exposure and added a path then bumped down exposure.  Opened mask manager and deleted the shapes one by one with no problem.

**Comment by wpferguson** [comment]
Did some further testing deleting groups and cleaning up unused shapes.  I removed the module that had the masks, then did a `cleanup unused shapes` in mask manager.  One shape still showed up, so I tried to delete it and got a crash.

I'll try recreating the crash and taking better notes this time :)

[darktable_bt_1RSBX1.txt](https://github.com/darktable-org/darktable/files/10203104/darktable_bt_1RSBX1.txt)

**Comment by jenshannoschwalm** [comment]
Also remember what happens while compressing history.

**Comment by wpferguson** [comment]
Steps to recreate

1. Create second instance of exposure
2. Turn on drawn masks
3. Add a circle, ellipse, brush stroke, path
4. Adjust exposure
5. Delete second instance of exposure
6. Go to mask manager and delete group, which leaves the 4 masks
7. Right click and select clean up unused masks, but notice the unused masks still show up in mask manager.
8. Start deleting from the bottom of the list, path then brush stroke then ellipse.
9. Delete circle and it crashes.

**Comment by dterrahe** [comment]
@wpferguson thanks for testing. Would you please see if the second commit solves that problem?

**Comment by MStraeten** [comment]
removing all from group if one shape is selected to remove is fixed.
cleanup unused shapes doesn't work further

**Comment by dterrahe** [comment]
Yep, that's what I said in #13129. Since that leaves #12656 as the only open bug in the "aggregation" bug #13129, I believe it is correct to close it as a duplicate (if it wasn't before). It is not a crash bug and (as far as I understand) not a regression, so I'm assuming nobody deems it RC. But yeah, like most of the other 700+ open issues, it is still open.

**Comment by wpferguson** [comment]
@dterrahe works without crashing

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
