### PR TITLE
Fresh new icons for better UI and minor fixes

### LINKED ISSUE #11680: selected color pickers invisible in dark mode
Using the dark mode, the color pickers in exposure, filmic (white / black relative exposure), color look up table, color balance rgb (and possibly others) are not visible anymore.

@Nilvus : this one is for you :)

### PR DESCRIPTION
**Pull request by Nilvus**
And a new set of icons updated. Hope you will like them.
I also fix some minor issues (like in darker CSS file, some forgotten update) and fix #11680 too.
Minor improvement on collapsible sections and more, the icons.

See before/after below.

New remove icon:
Capture d’écran du 2022-04-29 18-15-45
Capture d’écran du 2022-04-29 18-21-20

Icon used in modulegroups but see also new + and arrows icons:
Capture d’écran du 2022-04-29 18-16-35
Capture d’écran du 2022-04-29 18-20-12

Result of new remove icon in blending tabs:
Capture d’écran du 2022-04-29 18-16-54
Capture d’écran du 2022-04-29 18-19-54

A more readable folder icon:
Capture d’écran du 2022-04-29 18-15-24
Capture d’écran du 2022-04-29 18-20-34

And better lens correction module:
Capture d’écran du 2022-04-29 18-17-46
Capture d’écran du 2022-04-29 18-19-31

I should probably update other parts in following days, so I let this one as WIP by now.

### CODE REVIEW

**Comment by TurboGit** [comment]
> * For the cross... I'm mitigated : I find the new one less "light" and less "obvious", but that also différentiate it from the "X" letter...

I agree with @AlicVB  on this one.

**Comment by TurboGit** [comment]
> * for the lens module, I wonder why we don't use bauhaus combobox here, that would add some consistency with the rest of the UI (and I prefer the look they have)

Because the arrow does not actually list only the combo entries. I don't remember the full details and cannot verify right now, but I remember having looked at this some time ago.

**Comment by Nilvus** [comment]
> > * For the cross... I'm mitigated : I find the new one less "light" and less "obvious", but that also différentiate it from the "X" letter...
> 
> I agree with @AlicVB on this one.

So, what do you suggest for that one? I think X letter is not good. I've tried square icon (same as + and I think it's worst than my proposal). Tried too square and cross, not filled. Not good too.
Any ideas?

**Comment by Nilvus** [comment]
Or maybe use same icon, but not filled (so same as the one to "remove" image on lighttable):

image

image

image

**Comment by Nilvus** [comment]
Or octagon one:

image

image

image

I like this one, and more than icon proposed actually on that PR. What do you think of all those proposal?

**Comment by elstoc** [comment]
> Or octagon one

Not sure, makes me think of a road sign.

**Comment by Nilvus** [comment]
@elstoc: I like that one but I understand the link with road sign. It's not a problem to me but I understand it could for some. But I don't like square with rounded corners for this one. It's especially bad in modulegroups manager. See below

Octagon with bigger cross:
image
image

Rounded square (in modulegroups):
image

**Comment by elstoc** [comment]
I think the main problem was that the X was too big. If you got rid of the border and made that small x a bit more bold it would be fine.

**Comment by Nilvus** [comment]
> I think the main problem was that the X was too big before. If you got rid of the border and made that small x a bit more bold it would be fine.

Yes, but I don't really like that X alone, even smaller

**Comment by TurboGit** [comment]
The X alone on the fusion tool bar is perfect to me.

**Comment by Nilvus** [comment]
To resume all those proposals:
- octagon is KO for @elstoc and ok for @AlicVB and me
- first proposal (filled rounded one) is not liked by @TurboGit and @AlicVB. So we forget this one.
- square with rounded corners is OK for @elstoc but a no go for me
- same for X letter only (and OK for @TurboGit so on blending tabs!)
- remains so arc one (like to reject thumbnails) where I've had few feedback. Seems that was OK for you @AlicVB and it's ok for me.

There's mainly 4 parts with finally not completely same use case:

1. **blending tabs:** the icon is more to close and cancel any prepared mask
2. **progress bar when importing or exporting images:** to cancel launched action
3. **module manager:** the icon is to remove module or group
4. **filter widgets:** same here, remove filter

On reading more your feedback and after some thinking and use cases here, maybe we should have 2 icons here:
- to remove items (so filter widgets and module manager) which is near reject action. So I would propose same icon as actual reject one on thumbnails, for 3 and 4
- to cancel launched actions: use X letter, just a little smaller than in master. So for 1 and 2

Is this proposal ok for all of you?

**Comment by elstoc** [comment]
The joys of UI development -- you'll never please everyone.

**Comment by TurboGit** [comment]
@Nilvus : Sounds like a plan, yes!

**Comment by Nilvus** [comment]
Ok, so I update those icons regarding my last "plan" proposal! I don't post screenshots this time. I let you test if it's good for you. I also reduce a little deprecated size.

**Comment by elstoc** [comment]
Since none of the icons are filled now on the manage module layouts screen, perhaps the plus sign icon should be amended in line with the others.

**Comment by Nilvus** [comment]
> Since none of the icons are filled now on the manage module layouts screen, perhaps the plus sign icon should be amended in line with the others.

I tested not filled one for this icon and it's not good. I would so prefer to put back filled icon removed. And it's not same part. I think it's not a problem to have add icon more visible and it's in line with arrows. So, or we let that, or I put back filled rounded cross icon.

**Comment by Nilvus** [comment]
I finally test square with rounded corners (as suggested by you, @elstoc), but with a version never tested until now: filled one.

And I finally think it's the better choice (I keep X letter for progress bar andr blending tabs).

Capture d’écran du 2022-04-30 19-00-05

Capture d’écran du 2022-04-30 19-18-54

**Comment by elstoc** [comment]
I agree. The filled x icon is nicely consistent with the filled + icon.

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Comment by Nilvus** [comment]
> Works for me, thanks!

Heu, I didn't updated this PR with last proposal. Was too quick to merge it

**Comment by difrkaguilar** [comment]
It looks great. Almost like the old proposal I made last year.

Screenshot-20220501213105-1463x209

Of course I made a lot of others crazy icons too jejeje.


> The joys of UI development -- you'll never please everyone.

Pizzas are round, cut into triangles and delivered in square boxes. jejeje

**Comment by Nilvus** [comment]
> It looks great. Almost like the old remove icon proposal I made last year.
> 
> Screenshot-20220501213105-1463x209
> 
> Of course I made a lot of others crazy icons too jejeje.

And your mockups had helped me finding ideas for the work I've done for darktable 4.0. Thanks!
Not filled square icons do not render good on the UI (seems better in screenshots than in the UI) for me. I'm now stopped for darktable 4.0 to continue UI work as my PC is now in the way to repair center and should not come back repaired until about 10 days, so near complete feature freeze.

**Pull request merged**
