### PR TITLE
Allow more than 500 images for timelapse

### PR DESCRIPTION
**Pull request by OrthoCube**
The current 500 limit is quite restrictive especially for lengthy timelapse sessions. It would be very helpful if the limit is greatly increased (or removed altogether)

### CODE REVIEW

**Comment by TurboGit** [comment]
Why not set it to 9999 for now. I don't see a drawback. We need some limit for the spin button, but we may even push it to more if needed.

**Comment by OrthoCube** [comment]
@TurboGit 

> Why not set it to 9999 for now. I don't see a drawback.

I thought about setting it to 9999 :D But thought about being conservative and chose 5000 because maybe the devs had a reason for the original 500 limit.

However, currently, there is no mechanism for cancelling a currently ongoing time lapse so if a user chose 9999 images, and it ended up being too much, the user has no choice but to kill the program to cancel. I was wondering if that might be a problem if the limit is set to too large.

**Comment by TurboGit** [comment]
> However, currently, there is no mechanism for cancelling a currently ongoing time lapse so if a user chose 9999 images, and it ended up being too much, the user has no choice but to kill the program to cancel. I was wondering if that might be a problem if the limit is set to too large.

Well 500 with one image per second is already too long. So let's raise this limit, the proper fix is to propose a cancel of the task.

**Comment by OrthoCube** [comment]
I decided to up the limit up to 9,999 for special cases. Please let me know if that was a bad thing. (This is my second pull request in my whole life)

**Comment by TurboGit** [comment]
Looks good, thanks !

**Comment by AxelG-DE** [comment]
> 
> Well 500 with one image per second is already too long. So let's raise this limit, the proper fix is to propose a cancel of the task.

Aaaeeeehmmmm :-))
Timelapses need at least 25 pics per second, than this sequence is just 20sec, so for TL that is just the basic! One night of astro-TLs you come home with 3.000 pics easily
SCNR :-)

@OrthoCube
if you are on to TLs, may I link you to my [pixls-thread](https://discuss.pixls.us/t/timelapse-photography-and-darktable/14579/59) ? :)

**Pull request merged**
