### PR TITLE
make mask edit mode part of history undo.

### LINKED ISSUE #2667: Ctrl + Z gets me out of mask editing mode
Darkroom: every module with masks: apply a path mask (or any type of drawn mask), turn on "view mask", then draw a couple of points, then press Ctrl + Z to undo the last step. The last step will be correctly undone, but "view mask" is also disabled, and so is "show and edit mask elements".
Instead, I would expect that Ctrl + Z undoes the last step (like today) and preserves "view mask" and "show and edit mask elements", if they are switched on.

This happens in the windows and the ubuntu version, 2.6.2 and 2.7.

### PR DESCRIPTION
**Pull request by TurboGit**
Fixes #2667.

### CODE REVIEW

**Comment by johnny-bit** [comment]
I hoped that this would work in full, but it seems like it's missing "something"

Here's a clear step for testing:

1. add say "exposure" module with visible adjustment
2. enable mask view (yellow mask)
3. add drawn mask - say circle
4. add 2 more circles
5. ctrl-z last circle.

What happens:
mask view (yellow thingie) gets disabled, there are 2 mask circles.

What should happen:
mask view stays enables, there are 2 mask circles.

I wonder what's missing...

**Comment by TurboGit** [comment]
Well the issue was with mask edit mode not with mask display  so I have fixed the mask edit. For lack display I'm not sure if it makes sense.

**Comment by johnny-bit** [comment]
In similar way record if mask view is enabled and restore mask view too?

**Comment by TurboGit** [comment]
> In similar way record if mask view is enabled and restore mask view too?

That's probably possible, my point is that this is part of history and doing undo will activate or deactivate the mask view. This is the same for the mask edit mode. BTW, I'm wondering if we do not want to only enable and never disable when doing undo. I have no strong opinion, but I feel that this is really a usability issue if we do not get it right.

**Comment by TurboGit** [comment]
I have added the mask display into the history undo support. To be tested to see how it feels.

**Comment by johnny-bit** [comment]
IMO this now fixes ALL the problems in #2667 and works nicely!

**Comment by TurboGit** [comment]
Merged in master and queued for 3.4.1.

**Pull request merged**
