### PR TITLE
[CI] fix CI runs so there are no false-fails

### PR DESCRIPTION
**Pull request by johnny-bit**
Denoised CI runs.

Should shut up now and be working foreva!

### CODE REVIEW

**Comment by johnny-bit** [comment]
@TurboGit - this fixes building on windows with MSYS Makefiles as well as Ninja, fixes Mac builds and makes things universal.

Plz review & merge asap, also on 3.4 branch to get better and honester CI runs reports.

**Comment by TurboGit** [comment]
Really good job, all tests are passing. Thanks.

**Comment by TurboGit** [comment]
Merged in master, manually merged in darktable-3.4.x branch with some other commits and conflicts resolution. Please double check if I didn't mess the files.

**Comment by johnny-bit** [comment]
in 3.4 branch you also have to migrate over .ci/ci-script.sh script to one from master - the build expects nosse targets and will probably fail without that...

Otherwise Should be fine :)

**Comment by TurboGit** [comment]
Done !

**Pull request merged**
