### PR TITLE
set light patterns for Behringer b-control midi rotors (BCR2000/BCF2000)

### PR DESCRIPTION
**Pull request by dterrahe**
Implement light patterns for the old behringer BCF2000 and BCR2000 midi controllers. Only tested on the latter. Similar to x-touch mini, these controllers have 13 lights circling the rotors that indicate the current position. For the top row, these can be configured to spread from the middle (when a slider range goes from -x to +x), fill up to 100% (if range is 0-100) or just a single dot in all other cases. Since these machines use a (flexible!) configuration language send via sysex messages, the implementation is a little more cumbersome than it was for the x-touch. The setting for each rotor is only sent when the pattern _changes_ in order not to cause delays during each update.

### CODE REVIEW

**Comment by dterrahe** [comment]
Several other Behringer X-Touch models could probably easily supported; according to their documentation, the codes to send are very similar to the x-touch mini. But I don't have any of these so can't test. If there's somebody who's interested in providing feedback/testing, please respond here.

**Comment by TurboGit** [comment]
@dterrahe : I think we can merge this now and enhance this for other devices if needed later. Is that ok?

**Comment by dterrahe** [comment]
Of course, yes please. Without feedback there's not much I can do. Maybe a little blurb in the release notes still trigger some response.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
