### PR TITLE
colorcontrast: vectorization

### PR DESCRIPTION
**Pull request by ralfbrown**
Rewrote the plain-C codepath to make it vectorize well.  Unfortunately, with GCC8 it still takes 1.5x as long as the SSE codepath due to memory bottlenecks and lack of nontemporal stores (changing the _mm_stream_ps in the SSE codepath to _mm_store_ps slows it down to the same timing as the new plain codepath).  Without nontemporal stores, x86 processors read in a cache line that's being modified even if the entire contents will be written without being read.  So each pixel this iop processes causes two main-memory reads and a write without nontemporal stores compared to one read and one write with.

I've done what I can to add support for requesting nontemporal stores as compilers implement them (Clang 8 and 9 are supposed to have a `__builtin` function, Clang 10 and up claim to support the new OpenMP 5.0 `nontemporal` directive; GCC 9 recognizes that directive but does nothing with it, and I haven't been able to find any info about whether GCC10+ actually implement it).

### CODE REVIEW

**Comment by johnny-bit** [comment]
This brings me to a convo with @aurelienpierre - we should define which compilers/tricks we support.

One voice is for "drop GCC 7/8 compatibility since it hinders our optimization efforts"
Another voice is for "just drop openmp support for gcc7 (or even8)" if we can with that allow fixes to be present even for those compiling with older compilers.

**Comment by ralfbrown** [comment]
My position is that we should continue supporting the somewhat older versions (remember, GCC 8 is less than three years old) as long as major distros still have them as their default compiler, but we don't need to feel compelled to avoid optimizations only supported by newer compilers.  For the most part, that can be handled via macros or utility functions which become no-ops if the particular feature is not supported (e.g. the `dt_omp_nontemporal` macro in this PR).  Dropping OpenMP entirely would be an over-reaction to having a feature or two from e.g. OpenMP 5.0 unavailable in some supported compilers.

Limiting oneself to only the newest version of the compiler is fine for personal projects, but would make dt unavailable to a lot of users.

**Comment by TurboGit** [comment]
I agree, we should still support GCC 8 but make no effort to optimize code for it and concentrate with GCC 9 and above.

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Pull request merged**
