### PR TITLE
remember show mask and suppress status while module is in focus

### LINKED ISSUE #8426: Show mask button state inconsistent when switching between mask modes
**Describe the bug/issue**
I am currently working to a PR to "activate" the mask indicators introduced with #8352 and I found a bug that needs to be resolved first.

**To Reproduce**
Enter darkroom with a new edit, choose a module that support blending, for example exposure
Set any mask (drawn and/or parametric), for example a drawn mark with some shapes
Push the button "show mask", the mask is shown
Now switch the mask mode to one that does not have the "show mask button" (None, Uniform or Raster) and back
See the mask is shown again, but the "show mask" button is off: this is inconsistent

**Expected behavior**
Either the button is off and the mask is not shown or the button is on and the mask is shown

**Screenshots**
See the mask is shown, but button is off
image

**Platform**
DT git master, both Windows 10 and Linux

### PR DESCRIPTION
**Pull request by Mark-64**
With this PR I try to fix #8426 but avoiding to reset the "show mask" and "temporarily switch off mask" buttons while switching between mask modes in blending tabs.
So for example if the show mask is on in drawn mask and the mask mode is changed to uniform and then back, the mask is again visualized and the button stays on, avoiding inconsistency. When the module loses focus button are reset anyway.

Please let me know if this is an acceptable behavior to you.
Another possibility would be forcing a center image refresh so that switching back and forth the mask is not visualized anymore and the button is off, keeping consistency, but adding one maybe unnecessary refresh.

### CODE REVIEW

**Comment by Mark-64** [comment]
does not work as excpected, closing

**Comment by Mark-64** [comment]
Need more work as it doesn't fix all inconsistencies

**Comment by Mark-64** [comment]
Guys, I need you help. I can understand decently the GUI, but the pixelpipe is greek for me.
Switching between mask modes is ok now with the above commit, but going back and forth between lighttable and darkroom is not fixed.
I have checked with the debugger and initialization happens in `enter()` in darkroom.c
```
    module->request_mask_display = DT_DEV_PIXELPIPE_DISPLAY_NONE;
    gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(bd->showmask), FALSE);
    module->suppress_mask = 0;
    gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(bd->suppress), FALSE);
```
Why then the mask is visualized if it was active when switching to lighttable? 
Forcing a refresh will remove the mask visualization, but where to put the refresh and how to perform it only if necessary?

**Comment by Mark-64** [comment]
Added a refresh in the leave darkroom routine, if a module has a mask visualized. I guess this is executed next time darkroom is entered and it fixes the second issue in #8426.
I am not sure this is the correct method, though, please review

**Review by TurboGit — APPROVED** [review]
Works for me. Thanks!

**Pull request merged**
