### PR TITLE
Fix yellow color label contrast with thumbnail background

### LINKED ISSUE #7529: Darkroom Filmstrip - elegant-dark theme: yellow color labels are invisible on the currently selected photo
**Description & how to reproduce**

Using the latest DT3.4, theme: darktable-elegant-dark. 

Open any photo in the darkroom and set it with a Yellow color label (press F2). The Yellow color label (small yellow circle) is added to the photo however it's invisible in the GUI. Moving forward in the filmstrip to the next photo will allow you to see that the yellow label was added.

The same problem happens also in the Lighttable, but in this case it happens only when hovering with the mouse on any picture that has a yellow label - the background color to show the "hovering selection" is such that the yellow color can't be seen.

Here is a graphical expample of the problem as seen in the Darkroom Filmstrip:

image

All three photos in the snippet have a Yellow label, but this can't be seen in the currently selected photo.

To prevent or mitigate this problem, I suggest using a darker grey background just behind the Overlay line in the filmstrip even for the currently selected photo. This background could perhaps be a little lighter than the grey color used for non-selected photos in the filmstrip.
This same concept could apply to the Lighttable "mouse hovering selection" that suffers from the same problem.

**Platform (please complete the following information):**
 - Darktable Version: 3.4
 - OS: Ubuntu 20.04
 - OpenCL: active
 - Which graphics card and driver version: nvidia, GTX1650; X11; 450.80.02

### PR DESCRIPTION
**Pull request by Nilvus**
Fix  #7529

Posting this as a draft just waiting for feedback on this change.

### CODE REVIEW

**Comment by TurboGit** [comment]
For me it looks better on dark, grey and darker theme. Thanks.

**Comment by dterrahe** [comment]
There are some hardcoded #eeee00 markup foreground colors in variables.c and thumbtable.c that presumably "should" be kept in sync with this. I don't know if there is an easy way to link that to CSS though. So maybe just leave as is...

**Comment by TurboGit** [comment]
> There are some hardcoded #eeee00 markup foreground colors in variables.c and thumbtable.c that presumably "should" be kept in sync with this. I don't know if there is an easy way to link that to CSS though. So maybe just leave as is...

Good catch, I have fixed this in master.

**Comment by Nilvus** [comment]
Improve color for better contrast, especially in selected thumbnail state. Should be good to be merged now.

**Comment by TurboGit** [comment]
Thanks !

**Pull request merged**
