### PR TITLE
Use preset's multi_name as module label.

### PR DESCRIPTION
**Pull request by TurboGit**
In an attempt to give better control to the actual module label used (avoiding also long preset names possibly hard to read and ellipsize) the module label is now using the preset multi_name if set. If not set, the preset name is used as before.

For #13982.

This PR is a follow up to change in the way the module label is updated.

Until 4.2 the module label was updated only with numbers for multiple instance.

Starting with 4.4 the module's label is updated with the following action:

- Applying a preset, the multi-name of the preset recorded at creation time is used as label or if empty the preset name is used.
- Applying auto-presets when starting an edit or resetting the history stack does the same as above.
- Changing params in the module will check for a corresponding preset, if found the preset name is displayed otherwise the module label is cleared.
- If a module label is hand edited it will be record and won't change due action above. That is, the module label will always be the one hand edited.

A new preference has been added to disable the auto renaming of module label and so if disabled the behavior will be the one found in  4.2.

### CODE REVIEW

**Comment by elstoc** [comment]
How is the preset multi-name set? How can it be modified? Is this just hidden from the user? IMO this is not a good idea - if there's a new parameter it should be exposed for alteration.

This also doesn't fit the use case where a user does not want to show preset names as labels at all (which is what I would like). I still think this would be better as a separate visible parameter in the preset window -- set the label to this parameter if it is set, else leave the label untouched.

**Comment by TurboGit** [comment]
> How is the preset multi-name set? How can it be modified? Is this just hidden from the user? IMO this is not a good idea

Why do you expect a bad implementation by default.

Please read : https://github.com/darktable-org/darktable/issues/13982#issuecomment-1478987720

**Comment by TurboGit** [comment]
Just a side note, you asked for a way to enter the module label using a new GUI entry in the preset creation dialog. This is equivalent without any new GUI widget as we use the actual module's label as preset.

**Comment by elstoc** [comment]
> Why do you expect a bad implementation by default.

I don't. I tested it and I couldn't work out how to set it

**Comment by TurboGit** [comment]
> can't be subsequently updated (so the stored parameter is hidden), unless I've missed something.

Yes it can by editing the preset.

**Comment by elstoc** [comment]
At the very least the creation/update method is obscure and not obviously connected to the preset itself.

**Comment by TurboGit** [comment]
> At the very least the creation/update method is obscure and not obviously connected to the preset itself.

That could be said for all module's parameter then. We you create a preset it kind of snapshot the current module status and this includes the module's label.

**Comment by TurboGit** [comment]
The multi_name has always been the instance name in darktable since its inception.

**Comment by elstoc** [comment]
Honestly, though, I just want to be able to turn this off and only set the instance name when it's useful to me

**Comment by TurboGit** [comment]
> Honestly, though, I just want to be able to turn this off and only set the instance name when it's useful to me

I believe you can with this implementation. I just have to double check that an empty string is taken and we don't fall back to the preset name.

**Comment by elstoc** [comment]
I don't want to have to manually delete the name on every image, and if I delete it atm, it auto-repopulates

**Comment by elstoc** [comment]
I have never considered instance name to be a module parameter, and it feels odd doing so (given that you can have multiple instances with the same parameters)

**Comment by elstoc** [comment]
I'll try and test this at some point today but please could you make sure that there's at least one post (preferably the first one) on each Pull Request that fully describes the final (or current, if it's WIP) functionality. The related issue has a lot of comments and dtdocs is more likely to get updated if the description of the functionality is easy to find/read/understand.

**Comment by TurboGit** [comment]
@elstoc : I have added a description, hopefully it is clear enough for the documentation. Let me know.

**Comment by elstoc** [comment]
There seems to be some odd issue when I use multiple instances all with the same preset. This is a valid use case (sometimes you want to enhance an effect and the best way is to use multiple identical instances). I've used the exposure module as an example but I don't necessarily consider this the only valid use case, just a test scenario.

Here I have added three instances, without editing the instance name, but all using the same +1EV preset. The modules are different _instances_ but are no longer distinguishable because they all have the same name:

Screenshot_2023-03-24_09-17-29

The same does not occur if I choose a +2EV preset for one of the instances:

Screenshot_2023-03-24_09-23-33

In this case, the functionality leaves the instance name as the auto-generated integer ("2" for this example). This leads to my second concern: that the functionality will only ever work on the first instance of a module. Indeed one of the key use cases is to be able to have multiple instances show information about each instance, and it does not do this.

Another odd thing... After I've cleared history a few times, the auto-incremented instance numbers go up (so after a few clears, it's creating instances 4, 5, 6 etc.). This is fine and expected. However, if I create a new instance (say it's auto-generated number 4) and then choose a preset, it _updates_ the instance number to, for example, 2.

I'm far from finished testing all scenarios yet but I think this is enough to be going on with...

**Comment by elstoc** [comment]
Another... If I update my +1EV preset from a module that has the instance name "onemore", and then generate a new instance using the same preset, it updates that second instance to have the same instance name. Should this be possible? I thought the instance names should be unique.

Of course this goes back to a concern I've mentioned before... the module label is now _sometimes the instance name and sometimes the preset name_. How do I know which? I don't.

**Comment by EC1000** [comment]
I just tested with "automatically update module name" set to false. 
It seems to work well except one point: an empty label is applied when I use a preset saved without a label (or a hard-preset module). When no label (i.e. empty label) was saved, applying the preset should not replace the label of the module. So as in 4.2, it should: let untouched the current label if the preset is applied to an existing instance; set a "numbered label" if it is a new instance. 

I will continue to test, and also try with option set to true (even if it is not the one I intent to use).

**Comment by elstoc** [comment]
Seems to work as in 4.2 if the preference is unset. I'm not sure the tooltip of the preference is quite right though. It talks about automatically updating a "module name" to match a "preset name". It's not clear exactly what we mean by "module name" (see below) and it doesn't mention the fact that it can also update based on "the instance name of the module at the time the preset was created". I can't think of a nice simple way to put this in the tooltip as it's quite complicated functionality with a few "ifs". I guess for clarity the description in the presets dialog should probably say something like "automatically update module _label from preset_".

We should be clear about terminology here as well (both for clarity in the UI and so that I can reference it in the manual). AIUI we have three pieces of terminology that we need to reference and we should not mix up these terms or it will cause confusion:
- the "instance name" is the description stored against each module instance for an image (not the same as the "module name" which is, e.g., exposure, filmic rgb etc)
- the "preset name" is the name of the preset stored and displayed in the preset maintenance dialog
- the "module label" is the description shown in the module header and it could either show the instance name or the preset name, depending on the preference, whether or not the preset has a stored name and whether the instance is already named (which will also have to be clearly described in the manual)

**Comment by TurboGit** [comment]
@elstoc : At this stage and for clarity to our users we may well just talk about `module label` and `preset name`. The instance name is historical and probably more an internal (or dev) terminology but nothing that a user should deal with.

The `module label` is a text to identify the module. Whether it is hand edited by the user, generated from a preset or auto generated when creating a new instance for identification purpose is maybe not necessary important. What do you think?

**Comment by TurboGit** [comment]
Oh, and I'm happy to see that the option gives you the 4.2 behavior. At least we will have more freedom for our users and most people should be happy.

**Comment by elstoc** [comment]
> The module label is a text to identify the module. Whether it is hand edited by the user, generated from a preset or auto generated when creating a new instance for identification purpose is maybe not necessary important. What do you think?

I'd like the user to understand how it's set and updated, and how to change that behaviour. I'm still not entirely sure I understand it.

BTW if we're treating it as if it's a module parameter (so that the preset needs to be amended in order to save changes to it), the preset menu should read "Update preset \<name\>" rather than "edit this preset"

**Comment by EC1000** [comment]
@Turbogit: About the empty label with option set to false, I just tried the last commit. It seems to have changed but to the "opposite direction".

Before (when I wrote my previous comment): 
1. it correctly applied a saved label
2. but it also applied an empty label (i.e. it erase the existing one) if no label was saved. 

Now, it always erase the label (point 1 has change instead of point 2): 
1. a (not empty) saved label is not applied; instead it remove the existing one. 
2. it still applied an empty label (i.e. it erase the existing one) if no label was saved.

**Comment by EC1000** [comment]
From https://github.com/darktable-org/darktable/issues/13982#issuecomment-1480763820: 

> >[with option = true] I though a hand-edited label would be stored and applied as hand-edited with the preset.
> 
> Yes it should and from my testing it was working, maybe I broke something in the last iteration of my PR.

Just to let you know, it is still not the case with your lastest commit.

**Comment by EC1000** [comment]
> BTW if we're treating the label as if it's a module parameter (so that the preset needs to be amended in order to save changes to it), the preset menu should read "Update preset <name>" when the user has amended the label rather than "edit this preset"

I agree :+1:, it would be easier to understand and more consistent.

**Comment by TurboGit** [comment]
> Just to let you know, it is still not the case with your lastest commit.

A reproducer please, on my side a hand-edited preset name is store properly and seems to be applied properly too. So I bet we are using different scenario.

**Comment by EC1000** [comment]
By correctly applied, do you mean "applied as hand-edited" and therefore not reset when a parameter is changed?

What I did: 
1. set some parameters 
2. manually change the label: "X"
3. save a preset: "Y"
4. apply the preset on a new instance
5. label is correctly set as "X" (not "Y")
6. change a parameter
7. see that label is reset (empty or "1")

With step 2, I expected that in step 7 the label would stayed "X" (since the saved label is supposed to be applied as hand-edited).

**Comment by TurboGit** [comment]
That's definitely wrong... I'll have a look, pretty sure it was working on my side, I may have messed up something in the last iteration. Thanks!

**Comment by TurboGit** [comment]
Fixed in last version. And this has never worked before for sure. Thanks.

**Comment by EC1000** [comment]
It seems to work when the preset is manually applied (7 steps above), but not when the preset is auto-applied: 
1. set some parameters
2. manually change the label: "X"
3. save a preset: "Y" **with "auto applied this preset"**
4. **reset history**
5. label is correctly set as "X" (not "Y")
6. change a parameter
7. see that label is reset (empty or "1")

**Comment by elstoc** [comment]
With the preference switched on...

1. rename the exposure module to "exposure+1"
2. set the exposure to +1EV
3. store a new preset called "+1EV"
4. switch to a new image
5. manually set the exposure to +1EV
6. module is automatically renamed to "exposure+1"

This shouldn't happen if we're treating the label as a normal module parameter for the purposes of the preset. The label "exposure+1" is part of the preset and if I've not set my current label to that value, then my module parameters do not match the preset. The label should only be set to "exposure+1" if I manually choose the preset.

**Comment by TurboGit** [comment]
> It seems to work when the preset is manually applied (7 steps above), but not when the preset is auto-applied:

Fixed!

**Comment by TurboGit** [comment]
> * manually set the exposure to +1EV (by moving the slider, not choosing the preset)
> 
> * module is automatically renamed to "exposure+1"

That's expected and a feature. The current parameters are always search against the preset and if one match it is used a module label (expect if this module as already been renamed).

**Comment by elstoc** [comment]
> That's expected and a feature

In my opinion the features of this PR defy logic and will be virtually impossible to explain to a user without reams of confusing text. From my playing around with the feature last night it looks something like...

> If you manually set the module label by typing text into the module header then that label will be retained unless you subsequently manually select a preset which was created from a module having a different label. If the module label is empty at the time you select a preset it will either be temporarily set to the preset description (and reset to the previous label if you subsequently alter the parameters) or permanently set to the stored module label (if the preset was created from a module having a different label -- you will not be able to see what this label was unless you select the preset). If you happen to update the module parameters to something that matches a preset (but did not select the preset manually) the module label will be temporarily updated to either the label that was in place at the time you created the preset (if there was one -- again you cannot view this) or the name of the preset. In this case (parameters matching the preset but not manually selected) the label will revert to its previous value if you alter any of the parameters. 

I defy anyone to understand that and I am very much relieved that there is an off switch.

**Comment by TurboGit** [comment]
**For a module label**

The module label is either:

* The hand-edited label, this label will never change
* The preset label if the set of parameters correspond to one of the preset for the module. In this case the preset will also be highlighted in the pop-up preset menu.
* The empty string for the first instance or the instance number for multiple instances

**For creating a preset**

The preset label is:

* The current module label if any at the time of the creation of the preset or when editing a preset.
* If the module's label is hand-edited, the preset label is also recorded as hand-edited


> I am very much relieved that there is an off switch.

Perfect then, everyone is happy.

**Comment by elstoc** [comment]
I think that's a heavily simplified description of how it works in practice, but honestly I weary of this now. You're clearly fine with this change as it is and I won't convince you otherwise.

**Comment by TurboGit** [comment]
> I think that's a heavily simplified description of how it works in practice

But I still think it is the way it will be perceived by the users. That's what I wanted as a **behavior**. Isn't that more important than the internal details?

**Comment by EC1000** [comment]
@TurboGit: https://github.com/darktable-org/darktable/pull/13998#issuecomment-1483829312 (for option set to false) was still not working as expected last time I checked. Was your last commit supposed to fix it, or not yet?

**Comment by TurboGit** [comment]
> @TurboGit: [#13998 (comment)](https://github.com/darktable-org/darktable/pull/13998#issuecomment-1483829312) (for option set to false) was still not working as expected last time I checked. Was your last commit supposed to fix it, or not yet?

Maybe I'm confused, but I thought that @elstoc wanted no label to be set when applying a preset when the option is OFF. That is, the same behavior as in 4.2.

**Comment by elstoc** [comment]
yes I want to retain full control of the module labels as in 4.2

**Comment by TurboGit** [comment]
> yes I want to retain full control of the module labels as in 4.2

My recollection was correct. @EC1000 I'll then merge this PR which is now a large move forward. We'll get hopefully more feedback about this new feature. If you still have some idea for enhancement we'll continue in another issue/PR. Thanks to you and @elstoc for discussing this and even if we are in disagreement in some parts I do hope that the new preferences will make every parties happy.

**Comment by EC1000** [comment]
Since 4.2, there is the possibility in master to have auto-applied multi instances. 

With the current implementation (global option = false), no label is applied to any of the instances ! 

@elstoc I understand that you want to keep control of the label, and I do too! 
My proposition was the same behavior as 4.2 only with the addition of saving and applying the hand-edited label with the preset (both for global option true or false). Otherwise, there is no way to distinguish between the multiple instances.
This would not work for you? 
Did you test to auto-apply multiple instances with global option set to false?

**Comment by TurboGit** [comment]
> With the current implementation (global option = false), no label is applied to any of the instances !

Clearly a bug, and I'll fix.

**Comment by EC1000** [comment]
[self quoting about option = false:]
> Now, it always erase the label (point 1 has change instead of point 2):
> 
> 1. a (not empty) saved label is not applied; ~instead it remove the existing one~ [edit]
> 2. it still applied an empty label (i.e. it erase the existing one) if no label was saved.

The current behavior is not the 4.2 behavior.

**Comment by elstoc** [comment]
I just don't want applying a preset to update the module label. Or at the very least the ability to manually remove any label that I've accidentally (it will always be accidental) set against a preset without doing a dance that involves clearing the module label updating the preset and then reinstating the module label -- i.e. I would like it exposed in the preset maintenance window.

I don't think I'll ever use automatically-applied-multi-instances (I wasn't even aware this was a thing) which is _really_ making my head spin.

Ideally though I'd love to just stop talking about this.

**Comment by EC1000** [comment]
@TurboGit : sorry did not see your answer before my last comment. 

> EDIT: No actually I have the number 1, 2... applied to newly created multi-instances. So I may misunderstand the issue.

I will retry with master tomorrow if possible.

> EDIT: I see you mean when multiple instance of a module is auto-applied to new edits or after resetting the history, right?

Yes

**Comment by EC1000** [comment]
> I just don't want applying a preset to update the module label. Or at the very least the ability to manually remove any label that I've accidentally (it will always be accidental) set against a preset without doing a dance that involves clearing the module label updating the preset and then reinstating the module label -- i.e. I would like it exposed in the preset maintenance window.

Personally I was fine with exposing the label in the preset, but adding a new field was not considered a good idea.

> I don't think I'll ever use automatically-applied-multi-instances (I wasn't even aware this was a thing)

It is possible since the same PR that introduced the auto-update of label. In particular, it allows to do what was only possible with a style before (but you had to manually applied the style). 

I feel disappointed, because with the current implementation, it means I cannot replace a style (that I manually apply to all my images) with the new features:
- either I use the option=true, which make it possible to auto-apply labeled instances, but with the drawback of adding a label to any auto module (I do not want this as @elstoc).
- or I use option=false but then the labels do not differentiate the instances. 

I suppose having 3 possibilities for the global option is out of the question? If not, it could be: 
Update module label: 
1. manually (current "false")
2. 1 + with the label saved with a preset
3. 1 + 2 + with preset name if the set of parameters correspond to one of the preset for the module (current "true").

**Comment by EC1000** [comment]
Self quoting again:
> replace a style (...) with the new features

This would be the equivalent of an "auto-applied style".

**Comment by TurboGit** [comment]
@EC1000 : As I said a bug after all the different implementations I've done, when a preset is auto-applied it should: 

- Use the multi-priority (1, 2, 3) for being able to differentiates the different instances
- Use the hand-edited name is recorded in the preset

So you can control the instance name of the presets when multiple are applied.

**Comment by TurboGit** [comment]
@EC1000 : See #14037.

Please if there is still issues create new issue as the discussion here is becoming long and closed anyway. TIA.

**Comment by EC1000** [comment]
> @EC1000 : As I said a bug after all the different implementations I've done, when a preset is auto-applied it should:
>
> * Use the multi-priority (1, 2, 3) for being able to differentiates the different instances
> * Use the hand-edited name is recorded in the preset

Sorry, I misunderstood what you considered a bug vs normal. This seems great, thanks!

**Pull request merged**
