### PR TITLE
re-enable fast-math for Release build and libmvec for GCC

### PR DESCRIPTION
**Pull request by aurelienpierre**
This enables https://sourceware.org/glibc/wiki/libmvec.

`-fast-math` was removed in d5afea7 hoping to fix weird bugs. But it turns out that it completely disables auto-vectorization too, as it shows here : https://godbolt.org/z/fjxYqK vs. https://godbolt.org/z/xc7zs3.

Notice that this will make some modules slower than before. I will fix them in the next weeks.

### CODE REVIEW

**Comment by johnny-bit** [comment]
Interesting that this breaks filmic unittests ;)

**Comment by aurelienpierre** [comment]
The test broken is a division of a sum of powers, and I suspect this has to do with denormals flushing close to zero.

**Comment by johnny-bit** [comment]
Is this PR made obsolete by #8923?

**Comment by TurboGit** [comment]
Yes, OBE to me. Closing.

**Pull request closed without merging**
