### PR TITLE
RFC: topbar : new filtering menu icon

### PR DESCRIPTION
**Pull request by AlicVB**
This is part of #13065 

This implement @difrkaguilar proposal for a new filtering menu icon : 
image

### CODE REVIEW

**Comment by TurboGit** [comment]
I like it, better than the huge hamburger!

**Comment by TurboGit** [comment]
I've put that for 4.2 because:
- It is very safe
- It is only GUI
- It is a new feature in 4.2 so no possible "regression"
- It feels really better

**Review by Nilvus — CHANGES_REQUESTED** [review]
First, some thanks:
@AlicVB for making such icon so quickly. 
@difrkaguilar for his really good proposal. I like that icon too, much better for that menu.
@TurboGit for proposing, on purpose, that for 4.2.

But before merging, this need a little update: less margin on the left and more on the right.

With that PR:

image

What I propose to have:

filter

**Comment by Nilvus** [comment]
Just a note, this so need to move margin on the left to the right for that icon. Probably by adding a specific id on that icon.

Margin-left should so be set to 0. For margin-right, set same setting as other parts of toolbar. See line around line 1350 where you have that:

```
.dt_quick_filter,
#filter-sort-box label,
#header-rule-box label,
#header-sort-box label
{
  margin-right: 0.56em;
}
```

If needed, I can work on update that but not before wednesday. But I'm sure you can do that @AlicVB. I will be able to check code if needed with my phone but not test the update before wednesday too.

**Comment by difrkaguilar** [comment]
> First, some thanks:
> @AlicVB for making such icon so quickly.
> @difrkaguilar for his really good proposal. I like that icon too, much better for that menu.

Many thanks to all of you for giving me the opportunity to help from my modest position, at least with some ideas and proposals to the development of this fantastic application that every day makes it even better for the benefit of all those who wish to use it.
Other mockups will come in the near future ;-) 👍

**Pull request merged**
