### PR TITLE
change paste history order

### PR DESCRIPTION
**Pull request by edgardoh**
Changes the order of copied/pasted history items.

### CODE REVIEW

**Comment by edgardoh** [comment]
Also, for some reason, when pasting history the file manager jumps to the top, no idea what's going on there.

**Comment by TurboGit** [comment]
Looks good to me! I'll have a look at the file manager jumps I

**Comment by TurboGit** [comment]
But I'll need to reproduce... I don't see a jump... What is the steps to reproduce? Thanks.

**Comment by edgardoh** [comment]
Right now it happens when I paste the history on some image or when I
return to lighttable from the darkroom. It happens all the time, no special
scenario.

**Pull request merged**
