### PR TITLE
gradient mask : lower curvature step + allow to set up at creation

### PR DESCRIPTION
**Pull request by AlicVB**
usually when you change curvature of the gradient, you have to be quite precise... and you can still get a "big" curvature with little efforts imho.
If some fell the needs for that, we can even image to set the curvature step in some hidden config entry (but then, we may have to do that for all other params :))

This also add the possibility to change the curvature before adding the gradient. Of course, for the next gradient, the curvature will be back to 0.0 !

This work follow the (true) comment of @elstoc recently. thanks !

### CODE REVIEW

**Comment by elstoc** [comment]
Have we run out of modifier keys to set rotation?

**Comment by AlicVB** [comment]
scroll = curvature ctrl-scroll = opacity shift+scroll = compression... so I would say yes ;)
Anyway, rotation is related to it's center position...

That said, on creation, you can click+drag to define it, and on edition, you can use direct control points...

**Comment by elstoc** [comment]
> on creation, you can click+drag to define it

I didn't know that... but yes - segfault. Must add that to the documentation

**Comment by AlicVB** [comment]
> I didn't know that... but yes - segfault. Must add that to the documentation (but not the segfault)

Maybe it was just in my dream... but anyway I need to fix the segfault, and I'll try to implement that at the same time :) not in this PR, thought !

**Comment by elstoc** [comment]
tbh I'm not sure how useful it would be. Better to place and then adjust I think

**Comment by AlicVB** [comment]
I'm quite sure I've already used that in an image with a diagonal horizon (slope of a mountain) : you click on an horizon extremity and drag till the other extremity, like we can do for rotation... but my memory....

**Comment by elstoc** [comment]
Ah yes - it does work in v3.4 and I'd misunderstood how it works - it is indeed useful.

**Comment by AlicVB** [comment]
@elstoc : finally the fix was just few lines, so I've added the fix here in a new commit. the click+drag has magically reappear :) and I'm reassured about my brain ;)

**Comment by elstoc** [comment]
Hmm. Works but it's slightly confusing at first because click-drag during creation sets the direction parallel to the gradient line, but normal edit sets the direction perpendicular to it. Should it be consistent - i.e. drag into the direction that the mask will be opaque?

**Review by TurboGit — APPROVED** [review]
The new curvature step is indeed more useful. And good to see the fix also. Thanks.

**Comment by TurboGit** [comment]
> Hmm. Works but it's slightly confusing at first because click-drag during creation sets the direction parallel to the gradient line, but normal edit sets the direction perpendicular to it. Should it be consistent - i.e. drag into the direction that the mask will be opaque?

When creating the goal is to have the gradient following the horizon for example. A bit like when using the horizon setup in crop&rotate. When editing you're just rotating over the pivot. So I don't see an inconsistency and this works as expected to me.

**Comment by elstoc** [comment]
Yes but if you choose the wrong direction to move your mouse then the gradient is upside-down and of course you can keep dragging until the line is right. Feels odd that I have to remember left->right to select the top and right->left to select the bottom, when I could just drag the mouse in that direction.

**Comment by elstoc** [comment]
Meh I'm sure I'll get used to it - I didn't even know about this feature before anyway

**Pull request merged**
