### PR TITLE
[image load] Identify JPEG files by magic bytes, not file extension

### PR DESCRIPTION
**Pull request by victoryforce**
Sometimes there are cases when images are in JPEG format, but their file extensions do not correspond to this format. For example, there are reports of such a situation with iPhone photos: https://discuss.pixls.us/t/darktable-not-presenting-heic-files-for-selection/33699.

This fix allows such images to be loaded.

### CODE REVIEW

**Comment by kmilos** [comment]
We already check file magic in [`dt_imageio_is_ldr`](https://github.com/darktable-org/darktable/blob/9cc36e437a6b2b2ddcc3d811f490f83b4e80e0f8/src/common/imageio.c#L538). However, I don't see a trivial way to leverage this right now to avoid another file access, so this'll have to do in the meantime..

 Some thoughtful refactoring is probably needed in the future to handle loader decision in a better way...

**Comment by kmilos** [comment]
> That's for sure! But this work is more for obtaining a more logically written, aesthetic, understandable code than for achieving any practical results. Obviously, this will not speed up the image import process. So this is a job that would be nice to do, but definitely a low priority.

Yep, and also easier to maintain and extend... So many things to do, so little time... 😉

**Comment by kmilos** [comment]
Note that the DT_IMAGEIO_FILE_CORRUPTED -> DT_IMAGEIO_FILE_LOAD_FAILED renaming did not happen on the 4.2.x branch, so there will need to be some some manual back-porting or separate PR for it...

**Comment by victoryforce** [comment]
> Note that the DT_IMAGEIO_FILE_CORRUPTED -> DT_IMAGEIO_FILE_LOAD_FAILED renaming did not happen on the 4.2.x branch, so there will need to be some some manual back-porting or separate PR for it...

Thanks for noticing. That's why, IMHO, such safe source code changes (like enum renaming I mean) are better accepted before branching, so as not to create incompatible states of the source code.

Situations in which this fix will help are not only theoretical, they happen and are not so rare. There are repeated reports of similar problems with the iPhones, and users somehow manage to get JPEGs with incorrect raw file extensions, often with the Exif.Image.Software tag containing the value "Picasa" (I have no idea how this can be achieved).

For example, in addition to the link in the first PR comment:

- iPhones can take screenshots that have a .png extension but are actually JPEGs. There was also an issue where this is the cause of the problem:
https://github.com/darktable-org/darktable/issues/12483
(maybe there are other similar issues, I didn't do a full search)

- Examples of situations in which images of JPEG format ended up in files with the file extension of raw formats:
https://github.com/darktable-org/darktable/issues/12951
https://github.com/darktable-org/darktable/issues/12999
(maybe there are other similar issues, I didn't do a full search)

**Comment by victoryforce** [comment]
@TurboGit May I ping you on this as well? I don't want to be annoying, but this PR is already one week old and it hasn't been marked by a milestone yet.

This PR solves a real problem for some users and thus improves their user experience. I do understand that this fix will require additional work to be added to 4.2.1 (see kmilos' comment), but it would be nice if it could be done.

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Comment by TurboGit** [comment]
Merged in master.

**Comment by TurboGit** [comment]
I let you do a PR for 4.2. TIA.

**Comment by victoryforce** [comment]
> I let you do a PR for 4.2. TIA.

I made a PR against the darktable-4.2.x branch. Is everything done correctly?

**Pull request merged**
