### PR TITLE
Add protection against NULL pointer dereference when loading CMYK profile

### LINKED ISSUE #15061: Darktable crashes when applying a soft-roof
### Describe the bug

Darktable crashes when applying a soft-roof. It is possible to choose the correct soft-roof profile, but when you enable the soft-roof the program crashes instantly.

### Steps to reproduce

1. Doubleclick on a photo in the lighttable in order for the photo to open in the darkroom
2. Choose a soft-roof profile
3. Enable soft-roof

### Expected behavior

Marketable should show the photo with the soft-roof applied and should not crash

### Logfile | Screenshot | Screencast

`-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               darktable [2534]
Path:                  /Applications/darktable.app/Contents/MacOS/darktable
Identifier:            org.darktable
Version:               4.4.2 (4.4.2.0)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-08-13 13:13:20.3256 +0200
OS Version:            macOS 13.5 (22G74)
Report Version:        12
Anonymous UUID:        896C87A2-8A5F-1159-7787-A4262268B908

Time Awake Since Boot: 890 seconds

System Integrity Protection: enabled

Crashed Thread:        11  worker res 1

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [2534]

VM Region Info: 0 is not in any region.  Bytes before following region: 4307140608
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      100b9c000-100bac000    [   64K] r-x/r-x SM=COW  ...cOS/darktable

11  libgtk-3.0.dylib              	       0x102adf278 _gtk_marshal_BOOLEAN__BOXEDv + 124

Thread 11 Crashed:: worker res 1
0   libdarktable.dylib            	       0x1012b59cc dt_ioppr_transform_image_colorspace_rgb + 68 (iop_profile.c:1301)
1   libhistogram.so               	       0x10f0a36ac dt_lib_histogram_process + 348 (histogram.c:958)
2   libdarktable.dylib            	       0x101367aec _dev_pixelpipe_process_rec + 5936 (pixelpipe_hb.c:2487)
3   libdarktable.dylib            	       0x10136502c _dev_pixelpipe_process_rec_and_backcopy + 72 (pixelpipe_hb.c:2572) [inlined]
4   libdarktable.dylib            	       0x10136502c dt_dev_pixelpipe_process + 596 (pixelpipe_hb.c:2670)
5   libdarktable.dylib            	       0x10131f4dc dt_dev_process_preview_job + 452 (develop.c:350)
6   libdarktable.dylib            	       0x1012fef3c dt_dev_process_preview_job_run + 16 (develop_jobs.c:25)
7   libdarktable.dylib            	       0x1012f8bd8 dt_control_run_job_res + 264 (jobs.c:215) [inlined]
8   libdarktable.dylib            	       0x1012f8bd8 dt_control_work_res + 752 (jobs.c:519)
9   libsystem_pthread.dylib       	       0x18744bfa8 _pthread_start + 148
10  libsystem_pthread.dylib       	       0x187446da0 thread_start + 8

Thread 11 crashed with ARM Thread State (64-bit):
    x0: 0x000000035b9ec000   x1: 0x00000002da778000   x2: 0x0000000000000537   x3: 0x000000000000037e
    x4: 0x000000014ac6ca00   x5: 0x0000000000000000   x6: 0x000000010f0ab905   x7: 0x0000000000000ea0
    x8: 0x0000000000000001   x9: 0x000000017036e400  x10: 0x0000000000000018  x11: 0x0000000000000018
   x12: 0x000000011af95860  x13: 0x0000000000000000  x14: 0x0000000000003046  x15: 0x00000000ffff7dff
   x16: 0x00000001012b5988  x17: 0x00000001e6ff3d90  x18: 0x0000000000000000  x19: 0x00000002da778000
   x20: 0x000000014ac6ca00  x21: 0x000000035b9ec000  x22: 0x0000000000000000  x23: 0x000000000000037e
   x24: 0x0000000000000537  x25: 0x000000014b228000  x26: 0x0000000000000000  x27: 0x00000001016e2cf8
   x28: 0x0000000000000000   fp: 0x000000017036e5b0   lr: 0x000000010f0a36ac
    sp: 0x000000017036e400   pc: 0x00000001012b59cc cpsr: 0x00001000
   far: 0x0000000000000000  esr: 0x92000006 (Data Abort) byte read Translation fault

Model: MacBookAir10,1, BootROM 8422.141.2, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Display: MateView, 6016 x 4010, MirrorOff, Online
Memory Module: LPDDR4, Micron
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4378), wl0: May 13 2023 07:20:48 version 18.20.383.15.7.8.150 FWID 01-b37727a5
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB2.0 Hub
USB Device: MateView
USB Device: Datacolor SpyderX
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.
`

### Commit

Pushing the soft-roof button forces the crash

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

MacOS Ventura 13.5

### Describe your system?

Apple M1 Silicon 
MacBook Air
8 GB RAM
2nd ext. Monitor Mateview Huawei
256 GB Disc

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

The crash happens with a RAW (tested with two pics, no difference, same crash) and with a jpeg.
No LUA scripts used.

### PR DESCRIPTION
**Pull request by victoryforce**
Fixes #15061.

### CODE REVIEW

**Comment by MStraeten** [comment]
doesn’t fix 15061 since cmyk profiles could be used earlier. Just the null pointer protection makes sense

**Comment by victoryforce** [comment]
> doesn’t fix 15061 since cmyk profiles could be used earlier. Just the null pointer protection makes sense

Yes, I already learned from the discussion in the issue.

At first, when checking, it seemed to me that the soft-proof on the cmyk profile did not really change anything (except for the disappearance of the histogram). So I decided that cmyk profiles don't work at all. In fact, on my screen the changes from WhiteWall Canvas glossy were so subtle that I didn't notice them at first... :-/

So yes, only null pointer protection makes sense.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by victoryforce** [comment]
@TurboGit For Release notes:

`Fixed crash when applying CMYK soft-proof ICC profile.`

**Comment by TurboGit** [comment]
Thanks!

**Comment by todd-prior** [comment]
I might have just tried some flawed icc but in looking into the the recent query about softproofing all the icc I tried to use to check it were causing DT to crash... I will get the log and details of the profile tonight when I am home.....just commenting now to say that maybe this is not 100% fixed....

**Pull request merged**
