### PR TITLE
colorequal.c: Use 10 as default radius size for the guided filter.

### LINKED ISSUE #16117: color eq effect radius defaults
A place to discuss the default value of color eq 'effect radius' in 'options' tab. I personally feel the current default of 50px is much too high - allow me to demonstrate.

For all the below, curve smoothing and other options remained at defaults. Guided filter was on.

Here is a completely desaturated image using color eq only:

desat-all

And here is the image if we increase just one slider with effect radius 50px default:

desat-default-50px

As you can see, although I have only lifted 'lime', colours on the other side of the spectrum, such as 'blue', become visible. In fact, looking at the scopes, all colours seem to have been increased by a similar amount!

Here is the image if the effect radius is changed to the minimum value of 3px:

desat-min-3px

In my opinion, it looks much closer to expectations.

For brightness tab, here is a completely darkened image using color eq only:

dark-default-50px

If you want even the lightest colours to become black, you have to turn effect radius up to 100px:

dark-black-100px

Here is the image if we increase just one slider with effect radius 50px default:

dark-default-50px-2

Compared to if we increase the same slider with effect radius at minimum 3px:

dark-min-3px

Again, in my opinion it looks much closer to expectations.

In my tests, the impact of this slider on hue is negligible. 

Based on the above, I propose to change the default from 50px to something much lower, perhaps even the minimum of 3px (or 10px if we wish to be a little more conservative).

### PR DESCRIPTION
**Pull request by TurboGit**
Fixes #16117.

### CODE REVIEW

**Comment by TurboGit** [comment]
The integration test picture with:

image

(nothing else changed)

With effect radius 10px:

image

With effect radius 20px:

image

With effect radius 30px:

image

And finally with 3px:

image

**Comment by SoupyGit** [comment]
Hm yes low px is definitely unusable there, however I would argue even the effect at 30px is undesirable. 

Using saturation not brightness, here is the effect of 30px

sat-30px

Vs 3px

sat-3px

Which is basically the same as using no guided filter.
To me, 30px is unacceptable for saturation, given the effect it has on colours on the opposite side of the spectrum. Again, scopes show clearly.

If this is not a maths issue with the guided filter, I might actually argue the module would be better split in two - one without the guided filter for saturation (and possibly hue), and one with the guided filter for brightness. As it stands, you really can't use both saturation and brightness together with the same settings without some sort of undesirable compromise. The alternate might be two different presets - one for sat/hue, the other for brightness - however it would still hold that if someone wanted to adjust both they would need two instances - in which case you might as well just have two modules.

**Comment by TurboGit** [comment]
@SoupyGit : I agree that 30px for saturation is too much, but this actually can be seen by the user as bleeding on other colors and actually can understand than the effect radius is too big. But for luminance it looks better as using 3px looks very bad and can be seen as a bug. So I'm tempted to move to 30px now as a "workaround" as it seems a bit more generic than 3px or 50px. The guiding filter may be improved later and then we'll review this setting. Do you agree?

**Comment by SoupyGit** [comment]
30px is better than 50 for sure, and like you say low values like 3-10px really don't work for brightness as is. If guiding filter still needs work than any settings we come up with now may only be temporary, so yes go ahead with your proposal, and can maybe revisit later.

**Comment by Christian-Bouhon** [comment]
Hello,
If I may intervene in your discussion between developers. My first impression was that I was getting poorer results with the "Color Zones" module. Then I noticed that I was getting much better results without the guided filter and the white point at 1.5 EV. I wonder if the Option tab adds any value.
If you like, I can share a few examples.
Best regards,
Christian

**Comment by SoupyGit** [comment]
Hi Christian,
The most suitable white point will vary from image to image, pending how much you increase luminance in prior modules. As far as I see, the goal of the guided filter is to eliminate the noisy appearance which occurs when guided filter is not used (brightness tab is affected more than saturation tab here). 

My observations are that better results are achieved without guided filter for saturation tab when adjustments are not extreme. If adjustments are extreme, a little guided filter can help.

**Comment by jenshannoschwalm** [comment]
We certainly need a far better brightness correction via the guiding algorithm. But - please note that we definitely add a lot of chroma noise without the guiding in use.

**Comment by TurboGit** [comment]
I'll finally close this as we may have better solution. No need for a workaround for the time being.

**Pull request closed without merging**
