### PR TITLE
[WIP] scroll images is slower

### PR DESCRIPTION
**Pull request by edgardoh**
When scrolling through images in culling there's some delay, it seems to be introduced by _preview_get_zoom100()

I have partially removed that change and also added a prefetch on culling to avoid the refresh of the images.

### CODE REVIEW

**Comment by edgardoh** [comment]
@AlicVB , I don't know what _preview_get_zoom100() does so take this just as a try. Also if you could review the prefetch to be sure it doesn't mess with other things.

I also made some changes to pixelpipe to continue with #2484.

**Comment by AlicVB** [comment]
_preview_get_zoom100() is used to know the value of full resolution zoom value in advance. Inside this function, it's dt_image_get_final_size which can take time (although not really significant here). What I propose is :
1- to only call this on the first zoom change. That will delay a little bit the first zoom step, but shouldn't block scrolling anymore.
2- to track down what is taking time in dt_image_get_final_size.

For 2 : what images are you using ? are the images unaltered ? does -d perf show something useful ?
Thanks

**Comment by edgardoh** [comment]
> _preview_get_zoom100() is used to know the value of full resolution zoom
> value in advance. Inside this function, it's dt_image_get_final_size which
> can take time (although not really significant here). What I propose is :
> 1- to only call this on the first zoom change. That will delay a little
> bit the first zoom step, but shouldn't block scrolling anymore.
>
Right now (on master)  _preview_get_zoom100() is called every time, even on
full preview, and in culling for each displayed image, even if not zoomed.
If I understand correctly it should be called only when zoomed in (and in
the first zoom?), but I have no idea how to do that.
This should be done in a separate PR anyway, I added it here just to
confirm what is causing the delay.

> 2- to track down what is taking time in dt_image_get_final_size.
>
> For 2 : what images are you using ? are the images unaltered ? does -d
> perf show something useful ?
>
Both edited and unaltered. I'll try to explain better what I'm doing here:
When scrolling, the images that are not in memory seem to be reprocessed,
first a kind of blurred image is displayed and shortly a sharper one is
displayed. This both on edited and un-edited images. What happens is that
the expose can't find a cache with the right size, so a smaller one is
used, then on a second pass, the right cache is retrieved.
What I'm doing is to prefetch the next and previous images, so when the
cache is requested the right size can be retrieved. This is how the file
manager works (it prefetch an entire row)

Thanks

**Comment by AxelG-DE** [comment]
It seems to work fine for my case :+1:

**Comment by AlicVB** [comment]
> Right now (on master) _preview_get_zoom100() is called every time

Yes, but compute only occurs at the first call, after that, final_width/height are store in the image structure and just returned without computing anything.


> but I have no idea how to do that.

I'll take care of that soon in a separate PR

> When scrolling, the images that are not in memory seem to be reprocessed,

Just noticed that too. It shouldn't.  (and hopefully, it's the root cause of our problem here)... I'll investigate here too

**Comment by edgardoh** [comment]
I'll keep this on hold then, there's another active PR anyway so better
wait.

**Comment by AlicVB** [comment]
@edgardoh : I've move the final size computation to only zoom cases in #2471 : can you test it ? (I've added it to this already pending PR, as I needed the changes done there)

I delay the first zoom step, but after some thought, I'm not really for reverting it completely, as it solves a lot of other bug (in mipmap sizes, with some special raws with small embedded preview, etc...)

I'll investigate of the mipmap recompute problem now (in a completely new PR I hope)

**Comment by AlicVB** [comment]
ok, it was not a full recompe, just a reloading in the cache.
I've fixed it in #2471 too
Now I think, I'll stop here, before #2471 becomes a nightmare to review, and @TurboGit want to kill me ;)

If you agree with my changes there, I think this PR should be closed (maybe just open a new PR for the other changes you made)

**Comment by TurboGit** [comment]
Ok, I'll close this PR and will review #2471 then. Thanks, and I'll try to refrain from killing someone, promised :)

**Comment by edgardoh** [comment]
Why? We still don't know if this is needed, that's for @AlicVB  to say.

**Comment by TurboGit** [comment]
@edgardoh : AlicVB says just above that we could close this PR if #2471 is merged :)

**Comment by edgardoh** [comment]
@TurboGit  : @AlicVB says if I agree, and I do not. But even if he didn't say it, this is my PR and you didn't even ask me.

And in my last comment in #2471 I'm reporting an issue that still needs to be discussed.

**Comment by TurboGit** [comment]
Ok, ok I reopen then. I did not understood.

**Comment by AlicVB** [comment]
@edgardoh : I've focused on "my" part of the changes you've done (=fix the regressions due to my work), and completely forgot the prefetch part... my bad. That should enhance image scrolling indeed.

So, to resume, we should keep the prefetch part, and drop the other changes, right ? (correct me, if needed)
I'll take care of that in another PR, and let you close this one once you review it if you agree

**Comment by edgardoh** [comment]
@AlicVB , OK, I'll create another another PR with the prefetch stuff, but let's keep this one open, @AxelG-DE  is running some test and we may need it if he find something.

@AxelG-DE , please leave a note here when you're done with this so we can close it.

**Comment by AlicVB** [comment]
@edgardoh : in fact, I've already done it here https://github.com/AlicVB/darktable/commit/898d567980a1490c70d5230cf8545558b5709f32
(I've adapt it a little bit to the recent changes)
I don't know how to push something with adding another author name (but I know it's possible) so if the code is fine for you, just copy/paste it in your PR. if it can save some of your time...

**Comment by edgardoh** [comment]
I didn't understand that you'll do it, but great, just push this one, never
mind the authors.

Thanks!

**Comment by AlicVB** [comment]
@edgardoh : done in #2508 
and to be sure you keep working, I've this one for you : #2509 ;)

**Comment by edgardoh** [comment]
> @edgardoh <https://github.com/edgardoh> : done in #2508
> <https://github.com/darktable-org/darktable/pull/2508>
>
Thanks!

>
> and to be sure you keep working, I've this one for you : #2509
> <https://github.com/darktable-org/darktable/issues/2509> ;)
>
Thanks? ;)

**Comment by edgardoh** [comment]
Testing is done, so I'm closing this.

**Comment by AxelG-DE** [comment]
@edgardoh @AlicVB 
Sorry, I didn't get the notification (as often) from above, where you asked me to report... 

Actually I did report on #2484. I guess you saw it. 

In general I think 
- that big lag in darkroom is solved
- culling is even today 4th May still slower than I wish, at least on bigger film rolls
- something suspicious on [opencl_synch_cashe](https://github.com/darktable-org/darktable/issues/2514)

**Pull request closed without merging**
