### PR TITLE
fix memleaks in various places

### PR DESCRIPTION
**Pull request by johnny-bit**
I was trying to learn a bit about asan builds (those are noisy as heck!) but I managed to find (and fix) a memleak in modulegroups (and iop order, views) :)

### CODE REVIEW

**Review by AlicVB — APPROVED** [review]
For modulegroups : that's perfectly fine
For views : seems ok too
For ioporder : I prefer to let that to specialist, @TurboGit ?

**Review by TurboGit — APPROVED** [review]
Thanks !

**Comment by johnny-bit** [comment]
catching memleaks is hard :/ this PR is ready IMO ;) tested that there's no double free and that nothing yells at me ;)

**Comment by TurboGit** [comment]
Yes, the iop-order fix is correct.

**Comment by johnny-bit** [comment]
Is this something to cherry-pick for 3.4.1 or not necessary?

**Comment by TurboGit** [comment]
Yes, all merged into 3.4.1 except the one for modulegroups.

**Pull request merged**
