### PR TITLE
Created a build-doc helper script as discussed in darktable issue #4177

### PR DESCRIPTION
**Pull request by matt-maguire**
As requested in darktable github issue #4177 :
https://github.com/darktable-org/darktable/issues/4177

this is a simple helper script to help build the darktable documentation. Ideally
the makefiles for the project should be fixed up to make building the documentation
easier, but this script may be useful as a stopgap measure until the darktable
documentation strategy is finally decided.

### CODE REVIEW

**Comment by TurboGit** [comment]
First of all thanks for making this happens!

I tried it and add an issue build the HTML, the messages are:

```
No adjustColumnWidths function available.
Processing terminated by xsl:message at line 405
make[3]: *** [doc/usermanual/CMakeFiles/darktable-usermanual-dtorg-en.dir/build.make:62: doc/usermanual/dtorg/en/index.html] Error 1
make[2]: *** [CMakeFiles/Makefile2:8549: doc/usermanual/CMakeFiles/darktable-usermanual-dtorg-en.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
No adjustColumnWidths function available.
Processing terminated by xsl:message at line 405
make[3]: *** [doc/usermanual/CMakeFiles/darktable-usermanual-dtorg-it.dir/build.make:62: doc/usermanual/dtorg/it/index.html] Error 1
make[2]: *** [CMakeFiles/Makefile2:8659: doc/usermanual/CMakeFiles/darktable-usermanual-dtorg-it.dir/all] Error 2
No adjustColumnWidths function available.
Processing terminated by xsl:message at line 405
No adjustColumnWidths function available.
Processing terminated by xsl:message at line 405
make[3]: *** [doc/usermanual/CMakeFiles/darktable-usermanual-dtorg-fr.dir/build.make:62: doc/usermanual/dtorg/fr/index.html] Error 1
make[2]: *** [CMakeFiles/Makefile2:7895: doc/usermanual/CMakeFiles/darktable-usermanual-dtorg-fr.dir/all] Error 2
make[3]: *** [doc/usermanual/CMakeFiles/darktable-usermanual-dtorg-es.dir/build.make:62: doc/usermanual/dtorg/es/index.html] Error 1
make[2]: *** [CMakeFiles/Makefile2:8576: doc/usermanual/CMakeFiles/darktable-usermanual-dtorg-es.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:8154: doc/usermanual/CMakeFiles/darktable-usermanual-dtorg.dir/rule] Error 2
make: *** [Makefile:3397: darktable-usermanual-dtorg] Error 2
```
Any idea?

**Comment by matt-maguire** [comment]
Looks like you are missing the docbook xsl java bindings. In my system I have a /usr/share/java/docbook-xsl-saxon/docbook-xsl-saxon.jar file that contains the adjustColumnWidths function. In Manjaro linux it is installed using the commands (described in the comments in the script):
# cd ~/aur
# git clone https://aur.archlinux.org/docbook-xsl-saxon.git
# cd docbook-xsl-saxon
# makepkg -sri

**Comment by TurboGit** [comment]
Thanks! I'm on Debian, I have just added it:
`$ sudo apt install docbook-xsl-saxon`

**Comment by TurboGit** [comment]
But I still have the same issue:

```
No adjustColumnWidths function available.
Processing terminated by xsl:message at line 405
```

**Comment by matt-maguire** [comment]
Did you regenerate your all Makefiles with cmake so it can pick up the new jar file?

**Comment by TurboGit** [comment]
> Did you regenerate your all Makefiles with cmake so it can pick up the new jar file?

I just deleted the main build directory. Restarted build.sh and the build-doc.sh. Looks like it is ok now.

**Comment by TurboGit** [comment]
Ok, looks like it is working ok. I was able to build all documentation. Thanks.

**Pull request merged**
