### PR TITLE
import: speed up files list and folders views

### LINKED ISSUE #8782: New import dialog is slow in Windows
The new dialogs "import in place" / "copy and import" are quite slow, especially in Windows.
I have a collection not that big, 6.5K images, nevertheless when I start DT the dialog takes around 10 seconds to appear after pressing the button. Subsequent calls after the first take around 3 seconds.
In Linux times are about half of the above, still quite slow.
An there is no visual feedback, the buttons seem unresponsive, quite confusing.
At least the dialog should appear immediately and being progressively filled in, to provide feedback to the user.

### PR DESCRIPTION
**Pull request by phweyland**
- disable sorting when fulfilling the files list (f3-4 seconds for nealy 60.000 images on HDD)
 
should help to solve the issue commented by @ralfbrown in #8782.
~~but probably doesn't affect the main issue reported by @Mark-64.~~
Now fixes #8782 as well.

### CODE REVIEW

**Comment by ralfbrown** [comment]
Sorting after every insertion would definitely slow things down :-).  Just tried with this patch, and the 43k-file directory now takes about two seconds, the 20k-file recursive tree about one second, and the 5800-file directory shows no discernible delay
.

**Comment by phweyland** [comment]
@ralfbrown thanks for testing. Yes I'd forgotten this.


>  so you could move them outside and have just one copy instead of two

Yes, for one half (disabling) but the enabling acts on different columns. I'll make the change.

**Comment by phweyland** [comment]
attempt for fake expanders.
I had to also to come back to control the selection and avoid parasitic ones <= the automatic selection of first level was forcing the expansion of that level,  just we wanted to avoid).

**Comment by elstoc** [comment]
Seems to work fine (though I never had any performance issues) - seems instantaneous to me. I would still prefer for the last selected folder to be cleared when a new root is chosen. If I choose a new root, I think it's safe to assume I want to choose a new import folder. Right now if I change my root from `/home/chris/photos/by-date` and then change back to `/home/chris` it auto-expands to my last selected directory, which I then have to collapse.

This behaviour is fine when entering the window for a new import though.

**Comment by elstoc** [comment]
Yes I'm asking for expanded (because the recommended use case is that you'll always select a sub-folder) but not selected.

**Comment by phweyland** [comment]
@elstoc, I think I made it.

**Comment by elstoc** [comment]
I'm not sure if we're misunderstanding each other here. See [this commit](https://github.com/elstoc/darktable/commit/677d9e0ce3e656b3a750bd690b71e6623dae5fd5) for what I was going for.

**Comment by Mark-64** [comment]
This works fine for me too, almost instantaneous.
Though I agree is less beautiful :-/

**Comment by phweyland** [comment]
> I'm not sure if we're misunderstanding each other here. See [this commit](https://github.com/elstoc/darktable/commit/677d9e0ce3e656b3a750bd690b71e6623dae5fd5) for what I was going for.

OK, I've missed the case of changing the folder with the button. Can you tell me if we are ok when you change the folder by the combobox ?

**Comment by elstoc** [comment]
> OK, I've missed the case of changing the folder with the button.

Ah that was the one that _I_ didn't test :)

Yes that looks fine

**Comment by elstoc** [comment]
> Though I agree is less beautiful :-/

Find another Gtk app that doesn't cheat this way and we'll steal some code ;)

**Comment by phweyland** [comment]
OK. Thank you both for testing. I make the last fix and we should be good.

**Comment by elstoc** [comment]
Still doesn't work on choosing a new folder with the button (or am I being impatient and you have another commit to come?)

**Comment by phweyland** [comment]
> Still doesn't work on choosing a new folder with the button

For me it works most of the time, but sometimes not. I'm chasing this... :(

**Comment by elstoc** [comment]
You haven't included all of my fixes in your commit

**Comment by phweyland** [comment]
> You haven't included all of my fixes in your commit

I don't agree with the first one (or I don't understand it)

**Comment by elstoc** [comment]
If the last chosen folder is empty, expand the root, else expand the last folder.

**Comment by phweyland** [comment]
> If the last chosen folder is empty, expand the root, else expand the last folder.

_expand_folder() is already called after each update_folders_list(), and normally with the good parameters. The I don't see the need of of clearing the selection. But I may miss some case...

**Comment by phweyland** [comment]
I've just fixed my issue. Do you still see any other issue  ?

**Comment by elstoc** [comment]
> _expand_folder() is already called after each update_folders_list(), and normally with the good parameters. The I don't see the need of of clearing the selection. 

Yes I see what you mean. What I did seemed to work but I didn't look properly at the code. 

I can't see what you've done to fix it but it seems to be working now.

I think this is good to go

**Comment by phweyland** [comment]
> I can't see what you've done to fix it but it seems to be working now.

click on [force-pushed](https://github.com/darktable-org/darktable/compare/19796120272e1af41d09d1b63700a278f31f8c99..d087547066ac5afc9cd6039628db01ef0573b69c) of the last commit and you get the changes ... (root was not always set properly (so many changes that it seems to be a ball of knots now ...))

> I think this is good to go

So let's call Pascal @TurboGit for review.

**Comment by elstoc** [comment]
> click on force-pushed of the last commit and you get the changes

Ah I've been clicking on the wrong thing all this time :)

**Review by TurboGit — APPROVED** [review]
Looks good to me. Big thanks to you and @elstoc for the implementation and testing.

**Pull request merged**
