### PR TITLE
tonecurve - fixed error init of scale in gui

### PR DESCRIPTION
**Pull request by phweyland**
tonecurve histogram did not appear at init time because scale was not set.

### CODE REVIEW

**Comment by Nilvus** [comment]
So it resolve this issue #2506 

@phweyland : what do you think of this issue (not possible to change scale background with css) : #2402 ? Is it possible to also improve that with that PR (or another) ?

**Comment by TurboGit** [comment]
Looks good, thanks.

**Comment by phweyland** [comment]
> what do you think of this issue (not possible to change scale background with css) : #2402 ? Is it possible to also improve that with that PR (or another) ?

It is easy to improve the readibility. That's also a change in PR #2638.
But to make it compatible css that's another story... Is rgb curve compatible css ?

**Comment by Nilvus** [comment]
no, rgb curve is not css compatible. But here just a better readability would be ok. About css, if something made, that would be the idea to have same thing like the histogram, so here especially the background.

**Pull request merged**
