### PR TITLE
Color OPENCL_ACTIVATED variable red if "no"

### LINKED ISSUE #2301: have an visible indicator in lighttable and more importent in darkroom, whether opencl is working or not
**Is your feature request related to a problem? Please describe.**
Especially on GENTOO-Linux there are several ways to mess up opencl or a new development-masked driver does not support opencl, or any other flaw...

**Describe the solution you'd like**
maybe near the dt-logo in the top left corner of darktable's window (lighttable and darkroom), have an indicator, whether or not opencl is activated successfully (additional opencl-logo, or have a "tick" attached to the logo or any other clear visual indicator....

**Describe alternatives you've considered**
I know, one can start "darktable -d opencl" or go to preferences and check. However, such indicator would be WAY more convenient to have an eye on from time to time

**Additional context**

### PR DESCRIPTION
**Pull request by dterrahe**
Trying to (partially) close out a really old FR; fixes #2301

image

### CODE REVIEW

**Comment by Nilvus** [comment]
Maybe too much visible I think. We make the UI to avoid distractions. I'm considering that some color is of course needed but is it worth the case here? Thus, your proposal lack a space after ":"

**Comment by dterrahe** [comment]
It is an _ERROR_ message. The specific request was to make it stand out much more so that it doesn't go unnoticed. You _can't_ stand out and _not_ distract; distraction is the intention.

So the question is, are we worried that there might be people who intentionally manually add the OPENCL_ACTIVATED variable to their status information, but then don't really care if it is _yes_ or _no_. Or more specifically, who would still continue even if opencl has failed without trying to remedy the configuration problem first and _then_ would find the red message annoying and distracting.

Personally, I'm not worried.

But obviously I would welcome suggestions on how to make an unobtrusive message stand out in a different way.

> our proposal lack a space after ":"

This is my personal "pattern for the information line", manually added in the Preferences/General tab so I could show the effect in a screenshot. It is not part of the PR as can be easily verified by looking at the file changes.

Thanks for reviewing.

**Comment by TurboGit** [comment]
> So the question is, are we worried that there might be people who intentionally manually add the OPENCL_ACTIVATED variable to their status information, but then don't really care if it is _yes_ or _no_.

I think it is the case, one can see this as just a status or as an error.

I suppose an alternative solution could simply be (already supported today):

`$(OPENCL_ACTIVATED/#no/ERROR ACTIVATION FAILED)`

People won't miss this message I suppose.

**Comment by dterrahe** [comment]
> already supported today

Nice! I did not realize/-member that substitutions are supported in variables. So we could simply close #2301 by suggesting

`OpenCL: $(OPENCL_ACTIVATED/no/<span foreground='red'><b>ACTIVATION FAILED</b></span>)`

It would be even nicer if somehow multiple substitutions were possible, i.e. if the "yes" could be replaced by nothing, so that either an error or nothing would be shown. That would make it much more suitable for inclusion in the thumbnail overlays as well. One could use a trick to hide the "yes" by setting alpha to (almost) 0.
`<span alpha='1%'>$(OPENCL_ACTIVATED/no/<span foreground='red' alpha='100%'><b>OPENCL ACTIVATION FAILED</b></span>$(NL))</span>`
image

The hidden "yes" still takes up space, obviously. stretch=‘ultracondensed’ _might_ help if that's an issue.

@AxelG-DE what do you think? You'll need to translate the "no" in the above string if you use German settings.

@elstoc this could be a "fun" example in https://darktable-org.github.io/dtdocs/en/special-topics/variables/

**Comment by Nilvus** [comment]
Oups, just see comment and closed PR after posting my comment... Probably a best idea to include that in the doc if it's possible to let user implement it himself. Few users will probably want that.

**Comment by dterrahe** [comment]
> Few users will probably want that.

Maybe _all_ users that have a normally working OpenCL setup that occasionally has driver problems will want this...

**Comment by elstoc** [comment]
> @elstoc this could be a "fun" example in https://darktable-org.github.io/dtdocs/en/special-topics/variables/

Could do, yes. Could you raise a FR or PR please.

**Comment by dterrahe** [comment]
https://github.com/darktable-org/dtdocs/pull/525

**Comment by AxelG-DE** [comment]
Pitty this thing is closed faster than I could reach home :-/

For me #2301 is still open and I wouldn't be happy if it gets closed.
Yes @TurboGit gave me that variable at times as it was similar controversial than it almost rose here as well. That variable is better than nothing but you do not see it in lighttable and as you can see from this conversation here, ppl even do not know this variable exists.

I think I maintain my Gentoo quite ok-ish and still it happens every now and then, the opencl fails (due to updates ran or half completed or reboot is due)

So I would be very happy, if "openCL failed" will be shown somewhere when opencl is inteded but failed without having a varialbe set.

**Comment by elstoc** [comment]
> That variable is better than nothing but you do not see it in lighttable

I have it show in the thumbnail tooltip pattern, which works for me. Problem is, afaik there's no way to currently tell the difference between "opencl failed" and "you don't have a GPU", since both of these result in opencl not being available.

**Comment by dterrahe** [comment]
> there's no way to currently tell the difference between "opencl failed" and "you don't have a GPU"

Which is why we can't add this by default, but if you know your GPU setup should work you can add it yourself, as you say both in darkroom but also in lighttable thumbnail tooltips.

> That variable is better than nothing

Have you tried it with the markup I proposed above (or in the dtdocs PR)? Is that really still not enough (especially in darkroom)?

> when opencl is inteded but failed

How do we know this? Are you suggesting we give _every_ user a warning that he has no OpenCL (either because he has no driver, or a driver is  installed incorrectly or it is installed correctly, but there is no card, or there is a gpu, but it isn't the correct, discrete, one or you have correctly configured your gpu but disabled it because it is too noisy) until they manually switch it off somewhere?

**Comment by AxelG-DE** [comment]
> > when opencl is inteded but failed
> 
> How do we know this? Are you suggesting we give _every_ user a warning that he has no OpenCL (either because he has no driver, or a driver is installed incorrectly or it is installed correctly, but there is no card, or there is a gpu, but it isn't the correct, discrete, one or you have correctly configured your gpu but disabled it because it is too noisy) until they manually switch it off somewhere?

By the time of my FR one had to edit darktablerc to make opencl switched on. That it is not available is detected e.g. when _-d opencl_ hence i thought it can be known

**Comment by dterrahe** [comment]
> That it is not available is detected

Correct. But whether it _should_ be available can not. If you have a GPU, but no driver dt can use, it just has to assume you _don't_ have one.

**Pull request closed without merging**
