### PR TITLE
po/fix style mi

### LINKED ISSUE #10553: unable to update a style
after changing some settings in an image it's not possible to update a style based on this settings.

**To Reproduce**
1. define style
2. edit image, change settings of a module in the style
3. back to lighttable select edited image (click by mouse on it so it's highlighted)
4. select style, click on edit, select module to be updated, save
5. apply style to a different image
6. check settings of the module in darkroom
7 see error: unchanged settings are applied

**Expected behavior**
changes are taken over to the style

**Platform**

* darktable version : darktable 3.7.0+1614~g234334b5d-dirty
* OS                : OSx

### PR DESCRIPTION
**Pull request by TurboGit**
This fixes #10553 and introduce a better fix for #8610.

### CODE REVIEW

**Comment by elstoc** [comment]
Doesn't work for me with multiple instances. I create, for example, three instances of the exposure module with exposures of +1, +2 and +3EV respectively and save them as a style. I apply the style to an image and adjust all modules to a random different exposure, then update the style from the edited image (by clicking update beside each exposure instance). If I then apply that style, it creates three exposure instances as expected but they are all at default settings (The first is set to +0.5EV (the normal default), the second and third are both set to 0EV (the default for new instances))

**Comment by MStraeten** [comment]
fix is taking over changed settings but not properly working with multiple instances.
creating a style with 1 instance of a module is possible - then update based on changed settings of this instance is ok
creating a style with 2 instances of a module is possible - then update based on changed settings of both instances is ok
creating a style with 1 instance of a module is possible - then adding a further instance via update is not supported (the further instance is not even displayed)
adding further modules (not yet in the style) is possible

**Comment by TurboGit** [comment]
Hum, your two reports are not in sync! It works for one and fails for the other. I have changed slightly the last commit and it could help.

> creating a style with 1 instance of a module is possible - then adding a further instance via update is not supported (the further instance is not even displayed)

Yes, that's part of the non supported feature describe in the commit log. There is no easy way for that.

**Comment by TurboGit** [comment]
@elstoc : I have tested your scenario with 3 instances and it works for me (with previous version and with the minor update just done)... Or there is one step that I'm missing or not doing exactly the same way.

**Comment by elstoc** [comment]
Seems to work fine now

**Comment by TurboGit** [comment]
@elstoc : I don't have those messages, I'll see if I can reproduce. Maybe because you are applying the style in "overwrite" mode instead of "append" ?

**Comment by elstoc** [comment]
> Maybe because you are applying the style in "overwrite" mode instead of "append" ?

Nope. My style consists of just 3 exposure modules and nothing else, applied to a clean stack in append mode.

**Comment by TurboGit** [comment]
Ok, I can reproduce when applied from the darkroom. Looks like a too zealous check during the history modifications while applying the style. No big deal for now and probably not related to this PR. I'll merge as this is definitely a good step forward. Thanks all for testing.

**Pull request merged**
