### PR TITLE
fix slider dragging update speed again

### LINKED ISSUE #11911: e3da6ed partially or completely reverted 2a9b4f1
A [very old issue came](https://github.com/darktable-org/darktable/issues/2724) back for me.

After very long time, this got solved by 2a9b4f1

I do have that same lag again, when first time drag a slider, as can be seen [here](https://github.com/darktable-org/darktable/issues/2724#issuecomment-1139378687):

dt_bauhaus_slider_postponed_value_change is totally changed (thru e3da6ed) in master compared to the time the issue got fixed so the changes got removed.

copied from IRC discussions:
_there is (was?) darktable.develop->average_delay which shows current pipeline latency (how much time it takes to run)
the problem was that while dragging the changes in this number wasn't taken into account_

@dterrahe is there any chance, that you could (re)implement, what has happened in 2a9b4f1

### PR DESCRIPTION
**Pull request by dterrahe**
fixes #11911

@AxelG-DE please test carefully for any side effects when updating using and not just on exposure but also slower modules and when dragging, scrolling or adjusting sliders using midi.

### CODE REVIEW

**Comment by AxelG-DE** [comment]
I will start testing it tomorrow.

for comprehensive testing I still think a testing plan needs to be populated, to avoid something like my last time intensive testing happens :-)

**Comment by AxelG-DE** [comment]
### Tests done
- **it works as expected** and solves my issue #11911
- **no drawbacks** found!

### Details:
I have tested this with the following modules:
- exposure
- filmic whilte relative exposure and black relative exposure
- color calibration, temperature
- tone equalizer mask exposure compensation and mask contrast compensation

For all above I have assigned rotators on my x-touch mini

- I have checked function and observed increments **all o.k.**
- between each test I have restarted dt, as only then you can notice (it was more harsh in #2724 by that time it was enough to reset the module IIRC, so we improved anyhow
- I checked draging, mousewheel and rotators **all o.k.**
- I observed (but not only for this commit, also master), that shift+wheel changes the increment, but shift+rotator does not. Maybe intentionally, just reporting...
- only sporadically (not the full list above) I have tested to exceed the slider max or min value and checked, whether the module still behaves normal **o.k.**

From my perspective, I am a) happy and b) good to go

If there is further testing required, please let me know!

**Comment by dterrahe** [comment]
Thanks for the extensive tests and report!

> shift+wheel changes the increment, but shift+rotator does not.

Do you have fallbacks enabled (in the shortcuts dialog/tab)?

**Comment by AxelG-DE** [comment]
> Do you have fallbacks enabled (in the shortcuts dialog/tab)?

Now yes, helped, thanks :) (but this is OT here, so I will be silent now :) )

**Review by TurboGit — APPROVED** [review]
Thanks to both of you!

**Pull request merged**
