### PR TITLE
collect: when filtering the tree displays the matching records

### LINKED ISSUE #12031: Tags don't show in the tree with matching tag
When I want to search for a tag, like "wa%" and hit enter nothing shows in the tree below. (But the images in lighttable are the correct one)
See below screenshot + video

image
[The video](https://nx22856.your-storageshare.de/s/YkarAZ6WsHt3PMY)

Darktable version: darktable master at version 6e25214
OS: Linux opensuse Tumbleweed

### PR DESCRIPTION
**Pull request by phweyland**
attempt to fix #12031

### CODE REVIEW

**Comment by atomikdg** [comment]
@TurboGit  this fix my bug since I patched

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Comment by TurboGit** [comment]
@phweyland : Just found out that when you restart dt the entry is filled with the last search "%pic%", the lighttable has the right pictures displayed but the collection filter displays all the entries (not filtered). Not a big issue, but could be nice to fix before the release.

**Comment by phweyland** [comment]
This said, I would agree that both cases (manual or automatic) should behave the same behavior. Consistency, simpler code, ...
But in that case the behavior should be applied for all lists and, as with all behavior changes, that may bother some.

**Pull request merged**
