### PR TITLE
fix scrollbar

### PR DESCRIPTION
**Pull request by TurboGit**
the scrollbar in the collection or style modules where not visible.

### CODE REVIEW

**Comment by TurboGit** [comment]
would be strange that identical definitions are there for real... But at least this would deserve a comment. Let me separate this from the slider update.

**Comment by LebedevRI** [comment]
I have cherry-picked relevant changes that seem fit to me in 2cb86dfd8f942ebf9d120a725abd6b6ab82be07d.

**Comment by TurboGit** [comment]
ok. fine then.

**Comment by TurboGit** [comment]
I have adjusted the commit as it depended on the commit not merged from this PR.

**Pull request closed without merging**
