### PR TITLE
Fix HLR mask issues

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
As reported in #12913 there are issues with wrong mask visuals.

These are related to data in modules parameters (thus the hash) are not changed id one of the mask buttons is changed.

So - if we do some of the mask visuals we invalidate the pixelpipe cache.

Also there was on bug in the segments visual possibly showing wrong data, an off-by-one test.

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
@TurboGit while investigating this i noticed that the "sliders with a button" don't do a `gui_changed()` call. Is this something we might want to change?

**Comment by TurboGit** [comment]
> "sliders with a button"

You mean the slides in highlight module having a mask button? Is that the case for all other modules?

**Comment by jenshannoschwalm** [comment]
from useless
```
/** optional gui callbacks. */
void gui_changed(dt_iop_module_t *self, GtkWidget *w, void *previous)
{
  // If defined, this gets called when any of the introspection based widgets
  // (created with dt_bauhaus_..._from_params) are changed.
  // The updated value from the widget is already set in params.
  // any additional side-effects can be achieved here.

```

The sliders might be introspection based, the buttons beside them are not.

**Comment by TurboGit** [comment]
But this is only useful when the controls has some effects on the params. The mask button is only GUI based and won't change the parameters so I don't think it is needed. Any specific bug spotted?

**Comment by jenshannoschwalm** [comment]
> Any specific bug spotted?

No :-) But at least here the button changes runtime `process()`  output data and we have to take care of that.

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Comment by TurboGit** [comment]
> No :-) But at least here the button changes runtime `process()` output data and we have to take care of that.

Maybe worth opening an issue to discuss that then.

**Pull request merged**
