### PR TITLE
Tools: Enable watch_folder.sh recursion

### PR DESCRIPTION
**Pull request by lrkwz**
Enable recursion on `watch_file.sh`. 

See https://linux.die.net/man/1/inotifywait for limitations.

### CODE REVIEW

**Review by TurboGit — CHANGES_REQUESTED** [review]
All the change in shebang are not ok. We already discussed that and actually the /usr/bin/env created lot of issues in CI and build on some other OS.

**Comment by TurboGit** [comment]
Also it is a good idea to keep changes very different like those in different PR.

**Review by lrkwz — COMMENTED** [review]
Changed the shebang back to the "standard" `#!/bin/bash`

**Comment by TurboGit** [comment]
Ok , the commits are a bit of a mess! There is two options:
1. you propose a PR with 2 commits : one for the clean-up one for the recurse support in watch_folder
2. I squash everything in a single commit

Let me know!

**Pull request closed without merging**
