### PR TITLE
Stabilize lighttable scrollbar

### LINKED ISSUE #15886: Shaky images in lighttable on specific settings
### Describe the bug

Shaky images on lighttable with filmrolls between 16 and 20 images only and 5 images per row on main view.

See video below:
[Capture vidéo du 2023-12-16 11-26-00.webm](https://github.com/darktable-org/darktable/assets/45535283/92b13f92-362a-4912-b5e2-2059eee79dab)

### Steps to reproduce

1. set a filmroll with 16 to 20 images (I don't have that issue above or below that)
2. set 5 images per row (I don't have that issue above or below)
3. see the images shake

Issue reporduced with and without OpenCL and on all my filmroll with 16 to 20 images.

### Expected behavior

No shaking

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

Actual master

### What OS are you using?

Linux

### What is the version of your OS?

Debian Sid

### Describe your system?

_No response_

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
We subtract some (arbitrary) value to avoid toggligling between scrolbbar on/off states.

Fixes #15886

@Nilvus would you check if that works on your side too. Here no shakyness any more.

In case someone want's to know why this works, i really can't tell :-) Just looked through the code how the bars are activated / deactivated. If you have a close look the switch from bar -> no bar and reverse do happen if there is some small amount below lowest visible row.

### CODE REVIEW

**Comment by TurboGit** [comment]
> In case someone want's to know why this works, i really can't tell :-)

Maybe @dterrahe knows :) Or another way to fix that.

**Comment by jenshannoschwalm** [comment]
Well, for me it's the correct piece of code. And the correction is okayish. We could calculate precisely:

How much does height of a thumb in ease if we decrease overall width by scrollbar width.

Would you prefer the correct calculation instead of a safe guess?  😎

**Comment by TurboGit** [comment]
@jenshannoschwalm : Don't know what is better, I'm no expert on this. I know that @dterrahe has made lot of fixes to support what is called natural-size (or something like that) and I don't want to break this :)

But sure _to me_ the fix looks good!

**Comment by jenshannoschwalm** [comment]
force-pushed a squashed fix using a calculated threshold to avoid flicker / unstable states.

**Comment by Nilvus** [comment]
Some lack of time. I could test that in following days. Best wishes to all

**Comment by Nilvus** [comment]
Tested and I confirm this fix the issue. Thanks @jenshannoschwalm. Have a great Christmas.

**Comment by jenshannoschwalm** [comment]
Release note: Fix possible flicker in lighttable filemanager mode

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by TurboGit** [comment]
Merged in master and 4.6.x branch.

**Pull request merged**
