### PR TITLE
Add some Color Equalizer presets.

### PR DESCRIPTION
**Pull request by TurboGit**
- Bleach bypass
- Kodachrome 64 like
- Kodachrome porta 400 like
- Teal & Orange

### CODE REVIEW

**Comment by s7habo** [comment]
Nice. Thank you! 

Just a small correction:

"Kodachrome porta like " is "Kodak Portra 400 like".  Kodak Portra  400 is actually the name of this analog film series.

I plan to make a few additional previews. Is that okay?

**Comment by todd-prior** [comment]
I plan to make a few additional presets. Is that okay?

I'm sure people will be very happy for you to make as many presets as you can.. :)

**Comment by elstoc** [comment]
I'm assuming we think the module is in a complete enough state that these won't need revisiting later? Would it be worth waiting until closer to the release before including these?

**Comment by jenshannoschwalm** [comment]
I personally think the maths is stable now. But let's see if we find issues.

CE has been developed lately in great teamwork and I think merging it in an alpha state has been a success so if we decide later how to do better we can certainly modify such presets before release.

**Comment by s7habo** [comment]
I will be happy to adjust the presets if there are further changes in the module.

**Pull request merged**
