### PR TITLE
another take on GCC12+ compiler bug workaround

### PR DESCRIPTION
**Pull request by parafin**

### CODE REVIEW

**Comment by parafin** [comment]
Seems to work.
My only concern is that `*(matrix) = NAN` will be probably considered by compiler as outside of `#pragma GCC optimize ("-fno-finite-math-only")`, but it seems to work as expected anyway (I guess just plain assignment isn't broken by `-ffinite-math-only`). Also correct me if I'm wrong, but the target is to switch to -FLT_MAX anyway, right?

**Comment by LebedevRI** [comment]
Just disable the warning globally?
It's mind-swimmingly bogus and implemented in an incorrect way.

**Comment by parafin** [comment]
> Just disable the warning globally?
> It's mind-numbingly bogus and implemented in an incorrect way.

Yes, that’s another way to go, which I thought about. I’m fine with it too. I just don’t like currently implemented approach with spraying pragmas all over the code - it’s not sustainable. My thinking was to implement a workaround this time, considering the potential benefit of catching some real problem by this warning type, but to disable it altogether for GCC if we encounter a false-positive once again. But indeed maybe just go straight to it.

**Comment by TurboGit** [comment]
So is there a general agreement that this should be in 4.4? I would say so, just checking that this is ultra-safe and we all agree.

**Comment by parafin** [comment]
I suggest to merge this, yes.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
