### PR TITLE
collect: avoid folder status checking at display time

### LINKED ISSUE #9042: very slow star rating or using filer in lighttable
**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Use a database with lot of collections
2. Go to 'lighttable'
3. Over and image and click on the star on the thumb
4. See error, it takes long time before the star is actually applied

**Expected behavior**

Should be just instantaneous (as before).

**Platform**

* darktable version master
* OS                : Linux

**Additional context**

See line 16,638286 where the SQL query tales 1 full second.

```
16,636658 [sql] /home/obry/dev/builds/darktable/build/src/src/common/collection.c:1058, function dt_collection_get(): prepare "SELECT id FROM main.selected_images AS s JOIN (SELECT DISTINCT mi.id FROM (SELECT  id, group_id, film_id, filename, datetime_taken,   flags, version,  position, aspect_ratio,  maker, model, lens, aperture, exposure, focal_length,  iso, import_timestamp, change_timestamp,  export_timestamp, print_timestamp  FROM main.images AS mi  ) AS mi WHERE   (flags & 256) != 256  AND  (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/mnt/photos/Photos/2021/avril/pâques liam'))) ORDER BY filename, CASE WHEN flags & 8 = 8 THEN -1 ELSE flags & 7 END DESC, version) AS mi WHERE mi.id = s.imgid LIMIT -1, ?3"
16,637492 [sql] /home/obry/dev/builds/darktable/build/src/src/common/collection.c:2193, function dt_collection_image_offset_with_collection(): prepare "SELECT DISTINCT mi.id FROM (SELECT  id, group_id, film_id, filename, datetime_taken,   flags, version,  position, aspect_ratio,  maker, model, lens, aperture, exposure, focal_length,  iso, import_timestamp, change_timestamp,  export_timestamp, print_timestamp  FROM main.images AS mi  ) AS mi WHERE   (flags & 256) != 256  AND  (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/mnt/photos/Photos/2021/avril/pâques liam'))) ORDER BY filename, CASE WHEN flags & 8 = 8 THEN -1 ELSE flags & 7 END DESC, version"
16,638227 [sql] /home/obry/dev/builds/darktable/build/src/src/dtgtk/thumbtable.c:238, function _thumb_get_rowid(): prepare "SELECT rowid FROM memory.collected_images WHERE imgid=95735"
16,638261 [sql] /home/obry/dev/builds/darktable/build/src/src/dtgtk/thumbtable.c:238, function _thumb_get_rowid(): prepare "SELECT rowid FROM memory.collected_images WHERE imgid=95735"
16,638286 [sql] /home/obry/dev/builds/darktable/build/src/src/dtgtk/thumbtable.c:1923, function dt_thumbtable_full_redraw(): prepare "SELECT rowid, imgid FROM memory.collected_images WHERE rowid>=1 LIMIT 12"
16,640496 [sql] /home/obry/dev/builds/darktable/build/src/src/libs/collect.c:1885, function list_view(): prepare "SELECT folder, film_rolls_id, COUNT(*) AS count FROM main.images AS mi JOIN (SELECT id AS film_rolls_id, folder       FROM main.film_rolls)   ON film_id = film_rolls_id  WHERE (1=1) GROUP BY folder ORDER BY film_rolls_id DESC"
17,577917 [sql] /home/obry/dev/builds/darktable/build/src/src/libs/duplicate.c:403, function _lib_duplicate_init_callback(): prepare "SELECT i.version, i.id, m.value FROM images AS i LEFT JOIN meta_data AS m ON m.id = i.id AND m.key = ?3 WHERE film_id = ?1 AND filename = ?2 ORDER BY i.version"
17,578277 [sql] /home/obry/dev/builds/darktable/build/src/src/common/collection.c:1037, function dt_collection_get_selected_count(): prepare "SELECT COUNT(*) FROM main.selected_images"
17,578377 [sql] /home/obry/dev/builds/darktable/build/src/src/libs/image.c:250, function _update(): prepare "SELECT COUNT(id) FROM main.images WHERE group_id = ?1 AND id != ?2"
17,588142 [sql] /home/obry/dev/builds/darktable/build/src/src/common/collection.c:1037, function dt_collection_get_selected_count(): prepare "SELECT COUNT(*) FROM main.selected_images"
17,588261 [sql] /home/obry/dev/builds/darktable/build/src/src/libs/tools/timeline.c:621, function _time_read_bounds_from_collection(): prepare "SELECT db.datetime_taken FROM main.images AS db, memory.collected_images AS col WHERE db.id=col.imgid AND LENGTH(db.datetime_taken) = 19 AND db.datetime_taken > '0001:01:01 00:00:00' COLLATE NOCASE ORDER BY db.datetime_taken ASC LIMIT 1"
17,588502 [sql] /home/obry/dev/builds/darktable/build/src/src/libs/tools/timeline.c:642, function _time_read_bounds_from_collection(): prepare "SELECT db.datetime_taken FROM main.images AS db, memory.collected_images AS col WHERE db.id=col.imgid AND LENGTH(db.datetime_taken) = 19 AND db.datetime_taken > '0001:01:01 00:00:00' COLLATE NOCASE ORDER BY db.datetime_taken DESC LIMIT 1"
17,588788 [sql] /home/obry/dev/builds/darktable/build/src/src/common/history.c:1582, function dt_history_hash_get_status(): prepare "SELECT CASE  WHEN basic_hash == current_hash THEN 1  WHEN auto_hash == current_hash THEN 2  WHEN (basic_hash IS NULL OR current_hash != basic_hash) AND       (auto_hash IS NULL OR current_hash != auto_hash) THEN 4  ELSE 1 END AS status FROM main.history_hash WHERE imgid = 95735"
17,589015 [sql] /home/obry/dev/builds/darktable/build/src/src/common/image.c:320, function dt_image_full_path(): prepare "SELECT folder || '/' || filename FROM main.images i, main.film_rolls f WHERE i.film_id = f.id and i.id = ?1"
```

### PR DESCRIPTION
**Pull request by phweyland**
fixes #9042

- add the memory table film_folder
- connect collect queries on it
- to be done: refresh the table on folders status change

### CODE REVIEW

**Comment by phweyland** [comment]
If I'm not wrong remain the not covered following cases, in parallel of dt running:
- the user deletes a film folder
- the user creates a missing film folder

The first one should be possible adding a "changed" event to each dt film folder...
The second one has probably a solution as well (that could be tricky to get all the possible cases), but both seems a bit heavy for a small benefit.
I would vote not to treat those cases.

Two other remarks:
- each time there is change (mount or import) all the status are evaluated and the collect view is recalculated. There is room for optimization if necessary, with more code.
- In library and data there some FOREIGN KEY(key) REFERENCES table(key) ... I've failed to build that in memory referring a library table (film_rolls). 

Thoughts ?

**Comment by johnny-bit** [comment]
"in parallel to dt running"... so... user deletes or moves folder outside of darktable?

I don't think it's necessary to setup say GFileMonitor for them if that's what you're asking. But "simply" reacting to folder change and seeing if it's avail would be good to have but not a priority at all.

**Comment by phweyland** [comment]
> "in parallel to dt running"... so... user deletes or moves folder outside of darktable?

Yes, exactly.

**Comment by TurboGit** [comment]
This does not seems to work on my side. I have a network drive. I start dt with the network drive unmounted. All my collections and folders are stroked-out. Fine and expected. I do mount my external network drive and all the folders and collections are still stroked-out as if not readable/reachable. Maybe the monitoring does not take into account network drives?

**Comment by phweyland** [comment]
If you start dt with your drive already mounted, what is displayed ?

> Maybe the monitoring does not take into account network drives?

I've made my tests on usb drives. As we monitor "mount" events this should work also for network drives... Is there an easy way to simulate this kind of drive ?

**Comment by phweyland** [comment]
Side question. How does appear your drive in import module ?

**Comment by TurboGit** [comment]
> If you start dt with your drive already mounted, what is displayed ?

All is good, no folder/collection stroked-out.

> Side question. How does appear your drive in import module ?

It is a mount point defined into fstab. It is mounted to a directory /mnt/photos so appears as a directory when mounted.

To simulate that you can try something like this:

```
mkdir -p ~/tmp/iso
cd ~/tmp/iso

# create a dir and put some files on it (whatever)
mkdir dir
cp somefile dir/

# create an iso out of those data
$ mkisofs -o data.iso ~/tmp/iso/dir

# create a mount point
mkdir mnt
sudo mount data.iso ~/tmp/iso/mnt -o loop

# when done/tested unmount
sudo umount ~/tmp/iso/mnt
```

**Comment by phweyland** [comment]
Thanks, I can reproduce the issue. Checking...

**Comment by phweyland** [comment]
In this scenario the mount/umount detection works, but mnt is still present even if there is no image in there.
To be stroked-out, mnt should be deleted as well.
In the network scenario, are we in the same case ?

**Comment by phweyland** [comment]
But the following sequence works:

```
$ mkisofs -o data.iso ~/tmp/iso
$ mkdir mnt
$ sudo mount data.iso mnt -o loop
$ sudo umount mnt
```

The difference is that instead of "mnt" we have "dir" in collect. "mnt" is always present while "dir" is correctly detected (present/absent).

How to correlate this with the network case ?

**Comment by TurboGit** [comment]
> In the network scenario, are we in the same case ?

Yes, the directory (mount point) is always there. But the content is pointing to the actual network drive when mounted.

**Comment by phweyland** [comment]
Ok, then network drive and iso drive may behave [differently.](url)
To be sure there is no mount/unmount detection in the network case, could you please add a trace in the _mount_changed() routine ?
Is your network drive accessed through samba ?

**Comment by TurboGit** [comment]
> Is your network drive accessed through samba ?

Yes. Using `cifs` protocol.

**Comment by TurboGit** [comment]
> could you please add a trace in the _mount_changed() routine in collect.c ?

Sure, will try to do that in the coming days and will report back.

**Comment by phweyland** [comment]
I'm starting having a samba server running.
When you say "I do mount my external network drive" what do you do exactly ?
Having the drive defined in /etc/fstab, `sudo mount -a` does trig the mount monitoring in dt. `sudo unmount samba` as well. So I guess I don't reproduce your case yet...

**Comment by TurboGit** [comment]
I'm doing : `sudo mount /mnt/mount-point` if `samba` in your example is the mount point (empty directory) then we are doing the same.

**Comment by phweyland** [comment]
My config is:
fstab:
`//192.168.0.27/samba-share      /home/philippe/samba    cifs    username=philippe,password=xxxx     0       0`

in [samba-share] I've a folder and some images.

in [import in place] I've:
image

in collect:
image

Then:
$ sudo umount samba => stroked
$ sudo mount samba => unstroked

Notes
- I was afraid that you did something on server side instead of dt machine> it's possible that `cifs` cannot trig remote events.
- My first test was on a remote machine but as my local network is crap, everything was very very slow. I've ended up setting the server on the dt machine with the same results but a bit faster.

**Comment by TurboGit** [comment]
I have added some printf(à in _mount_changed() in collect.c and there is nothing displayed. So clearly on my side this is not called, don't know why !

**Comment by TurboGit** [comment]
@phweyland : I have added in collect.c to list all drives:

```
  d->vmonitor = g_volume_monitor_get();
  {
    printf("=>        g_vmonitor !!!!\n");
    GList *drvs = g_volume_monitor_get_connected_drives (d->vmonitor);

    while(drvs)
    {
      GDrive *dr = (GDrive *)drvs->data;
      printf("   drive : %s\n", g_drive_get_name(dr));
      drvs = g_list_next(drvs);
    }
  }

```

I just get my local SSD:

```
=>        g_vmonitor !!!!
   drive : SSDPEMKF010T8 NVMe INTEL 1024GB
```

So now we know why the other mount points are not seen when mounting or un-mounting them as they are not detected so not monitored. But why.... My external mount point is a NAS, but this should not make a difference when unmounted, the system only knows the fstab entry anyway.

**Comment by TurboGit** [comment]
I have also added the list of mounts missing above:

```
  d->vmonitor = g_volume_monitor_get();
  {
    printf("=>        g_vmonitor !!!!\n");
    GList *drvs = g_volume_monitor_get_connected_drives (d->vmonitor);

    while(drvs)
    {
      GDrive *dr = (GDrive *)drvs->data;
      printf("   drive : %s\n", g_drive_get_name(dr));
      drvs = g_list_next(drvs);
    }

    drvs = g_volume_monitor_get_mounts (d->vmonitor);

    while(drvs)
    {
      GMount *dr = (GMount *)drvs->data;
      printf("   mount : %s\n", g_mount_get_name(dr));
      drvs = g_list_next(drvs);
    }
  }
```

I get:

```
=>        g_vmonitor !!!!
   drive : SSDPEMKF010T8 NVMe INTEL 1024GB
   mount : Private
```

I get a mount, Private which is a specific encrypted mount directory on my home partition.

Now that I think about it, the /mnt/photos is not on the home partition. I have / and /home separated, maybe that's the difference here?

**Comment by TurboGit** [comment]
Ok, confirmed, if I set my mount point to `/home/obry/photos` instead of `/mnt/photos` I get the mount notifications.

**Comment by TurboGit** [comment]
But I don't see an option to get gio to monitor mount points on any partition on current drive/computer.

**Comment by TurboGit** [comment]
But I get notification when I insert an USB drive which gets mounted in /media/obry/xxx !

**Comment by parafin** [comment]
Do you know how these notifications work, at least on Linux? I mean who creates an event about new mount? I strongly suspect it only works in DE environment, and will fail for some users in any case.

**Comment by TurboGit** [comment]
> Do you know how these notifications work, at least on Linux?

No, not exactly, just that there is some events sent on the event-loop for that.

**Comment by parafin** [comment]
I think you need to use this too: https://developer.gnome.org/gio/stable/gio-Unix-Mounts.html

**Comment by phweyland** [comment]
Pascal, thanks for all your tests. I did not imagine that /mnt, /media or /home would behave differently. I'll continue to dig in that direction.

**Comment by phweyland** [comment]
> I think you need to use this too: https://developer.gnome.org/gio/stable/gio-Unix-Mounts.html

Thanks. Sure. I'll try it.

**Comment by phweyland** [comment]
When I mount the network drive as /home/philippe/samba it's visible in the file browser as a new mount:
image

When I mount it as /mnt/samba it is not visible. To access the remote files I've to go to /mnt/samba.

**Comment by phweyland** [comment]
> I think you need to use this too: https://developer.gnome.org/gio/stable/gio-Unix-Mounts.html

This does work for /mnt mounts.
Now this is unix specific. I probably have to manage WIN32 apart ...

**Comment by johnny-bit** [comment]
Judging from CI, you should use unixmount on unix systems and prev version on windows.

**Comment by phweyland** [comment]
First test on windows 10 is not successful. USB drive mount/unmount are not detected.

**Comment by TurboGit** [comment]
I'll test on Linux tomorrow. Is that ok for you if merging if all goes well on Linux and then work in a separate PR for the Windows issue?

**Comment by phweyland** [comment]
>  Is that ok for you if merging if all goes well on Linux and then work in a separate PR for the Windows issue?

Sure. Please go ahead.

**Review by TurboGit — APPROVED** [review]
Really good, working on my side. Nice job ! Thanks a lot Philippe.

**Comment by elstoc** [comment]
@TurboGit you've tagged this as documentation-pending, but does it need any user manual changes?

**Pull request merged**
