### PR TITLE
rework lighttable toolbar

### LINKED ISSUE #5926: Make image fill the whole (or the most of the) screen in file manager
**Is your feature request related to a problem? Please describe.**
When I Shift-scroll in the FileManager to only see one image, the image does not fill the whole screen. @aurelienpierre told me its because the requirement was to always have square items in the file manager. However, here it is really annoying because the image has the same size as each of the 2 images that I can see when I Shift-Scroll in the other direction by one go. 

**Describe the solution you'd like**
Be able to make the image much larger, whatever still works fine.

### PR DESCRIPTION
**Pull request by AlicVB**
This fix #5926 
This follow the work on icons by @quovadit in #7762 

The changes : 
- drop the layouts combobox and culling zoom mode combobox in favor of icons
- move sticky preview accels to lighttable lib
- change default accel for sticky preview to 'F' (+ctrl if one want focus detection)
- add shortcuts for filemanager and zoomable (empty by default) so all layouts have their shortcuts

### CODE REVIEW

**Comment by wpferguson** [comment]
@AlicVB if you need a lua script to test with, let me know.

**Comment by TurboGit** [comment]
@wpferguson : If you have one you can share or maybe you can test the Lua part in this PR ? I have myself reviewed the code and tested this, for me it is OK to be merged.

**Comment by wpferguson** [comment]
@TurboGit I tested last night and it worked fine for me

**Comment by TurboGit** [comment]
@wpferguson : So all good then ! Thanks a lot.

**Comment by AxelG-DE** [comment]
I bumped into this just yesterday, when I had to spend the available free time to bisect, why alt+w isn't providing the sticky preview anymore.

- "w" for preview still works (even though I need to press several times initially sometimes to make it work)
- I don't see, what is wrong with alt+w for sticky preview
- ctrl+shift+f is focus/DOF highlight
-- from that perspective "f" or ctrl+f isn't logic to me for sticky preview

TBH  not that happy about that change, even I could redefine, but don't prefer that, as it usually draws back during debugging with fresh configdir

**Comment by AxelG-DE** [comment]
I just found, in #7831 you guys discussed about reverting ctrl+f, but this commit here at least took away alt+w and is kinda related to #7831 if I'm not mistaken

**Comment by quovadit** [comment]
@AxelG-DE : there was also a discussion in [5926](https://github.com/darktable-org/darktable/issues/5926#issuecomment-754209779)
The main goal was to make the fullscreen preview easier to access, so a new icon was introduced, and the shortcut was simplified from a not-obvious two-button combination alt+w to a single key 'f' - meaning fullscreen - as in lightroom

**Pull request merged**
