### PR TITLE
WIP - Move retouch & liquify before perspective correction.

### LINKED ISSUE #10764: 3.8 retouch before Rotate&Perspective
Hi all.
Not sure if this is bug, or just something that users need to be aware of....
I was revisiting an old image, and decided to do some retouch work very early in my workflow.
I then activate the new Rotate and Perspective module to straighten the horizon.
And doing THAT threw all of the retouch brush strokes out of alignment!
All the debris in the water (that I had cloned out using retouch) were now visible again.
My solution was simply to move Retouch to immediately prior to the R&P module.
The other solution is to do R&P before activating Retouch.

darktable version : 3.8.0+8~gfb39ffd86
OS                       : 5.4.0-91-generic
Distro                   : Linux mint 20, Cinnamon 4.6.7

### PR DESCRIPTION
**Pull request by TurboGit**
This is to ensure that the source area (clone from in retouch and displaced
pixels for liquify) are always available even if a perspective correction
has been done.

Fixes #10764

Note that this is changing the v3.0 IOP order and it may be better to introduce a v3.1 to not change older edits. Beware then, this is only for testing purpose at this stage.

### CODE REVIEW

**Comment by AlicVB** [comment]
@TurboGit : I need to do more tests, but I fear that we'll have issues with textures deformations, then... See this comment for example https://github.com/darktable-org/darktable/issues/8675#issuecomment-819807932 (and also the second comment of the same thread...)

Not sure we can have everything...

**Comment by TurboGit** [comment]
> @TurboGit : I need to do more tests, but I fear that we'll have issues with textures deformations, then...

Yes, that's what I also feared (see my comment in the linked issue). But I have not been able to reproduce visible issue at the moment.

**Comment by TurboGit** [comment]
@AlicVB : If you can find a bad example it would be good, but I have tested this on textures and a visible building edge and adding rotating and/or perspective give excellent result (that is no visible issue, the correction is perfect). So maybe we are good at this stage.

**Comment by AlicVB** [comment]
@TurboGit : I have just done a very quick and theoretical example : 
original image (a grid transformed via r&p and exported :
original
 I've just done a perspective correction in r&p to get back the correct grid and a basic cloning circle in retouch. source is bottom-left, destination : center
with the actual situation (retouch after r&p) :
now
 with retouch before r&p :
bad

as you can see, with retouch before r&p, you miss the r&p correction on the cloned structures.
In this theoretic case, it's particularly obvious, but in the real life, we can imagine a electric line with poles. you correct it to have all the poles vertical, and then you can do your retouch which will respect the poles verticality

**Comment by AlicVB** [comment]
Now I don't say "don't do it", just that this will have drawbacks... the question is what is worth... or better what do we want to focus on ;)

**Comment by TurboGit** [comment]
@AlicVB : I may be missing something very specific but I cannot see how this can be a problem in real usage with my PR. What I have done:

1. use a grid

image

2. add a retouch area

image

(I have added a black line to be sure we localize the retouched area)

3. all good, nothing is seen

image


4. I have add a perspective correction
5. the area with the retouch is perfect

image


Of course if I move the retouch module now after the rotation & perspective one I get the wrong result you are showing. But this is also true today if you move the retouch before.

And what I'm suggesting is adding a new order version to keep the current order for old edits. So, expect if I'm wrong all this pretty safe, no?

Note that indeed with the current iop-order I can report the problem you have explained above with your schema. Again I may be missing something obvious...

**Comment by TurboGit** [comment]
@AlicVB : I have been testing more and to me this PR actually is a fix for the issue you described.

**Comment by AlicVB** [comment]
@TurboGit : sorry, seems that I have failed (as usual) to explained the most important step of my example : 
the starting image should already have the distortion without any module applied (for the example, I have taken the grid, distort with r&p, exported the result, and used the exported jpg as the base image)
imho this is more representative of a concrete work, where you have a distorted image as input and you need to correct it to get the right textures.

**Comment by elstoc** [comment]
Yes I recall this fix in a previous version and it fixed a few of my images that had lens correction applied (mostly things where I was taking corners of windows as source/target patches). I certainly wouldn't want this to be reverted.

**Comment by TurboGit** [comment]
@AlicVB : And have you tried to reproduce the issue with my PR? I tried again as you said and cannot reproduce the issue. But I can definitely on current master... Or I'm just too tired tonight :)

**Comment by TurboGit** [comment]
No sorry, I can reproduce :(

**Comment by TurboGit** [comment]
I see this now and understand the issue, indeed this is not good at all so closing.

**Comment by TurboGit** [comment]
@AlicVB : Thanks for your patience on this one :)

**Pull request closed without merging**
