### PR TITLE
lighttable : fix drag-n-drop and zoom center

### LINKED ISSUE #2305: Drag zoomed image display thumb icon
When dragging a zoomed image in file manager it drags it a bit and then it displays the drag icon for the thumb.
It works fine on expose mode.

In both file manage & expose the zoom don't follow the mouse when in full preview or when comparing images.

### PR DESCRIPTION
**Pull request by AlicVB**
This PR should fix #2305 : 
- The bug that doesn't deactivate drag_n_drop in full preview mode
- The feature to center the zoom at pointer position in full preview (deactivated in expose mode as it's way more complex)

### CODE REVIEW

**Comment by TurboGit** [comment]
Thanks.

**Comment by edgardoh** [comment]
It seems that I'm not able to zoom as much as before, is that intended?

**Comment by AlicVB** [comment]
Normally, the max zoom is at 100% (the real image size), maybe check with another viewer to compare (I've just checked, and it's ok here). Note that there's a small jump the first time you reach the max zoom. It's due to the fact that we don't know what is the max output size of the image before computing the last mipmap...

**Comment by edgardoh** [comment]
I did some debug and here I get a 2.5:

https://github.com/darktable-org/darktable/blob/master/src/views/lighttable.c#L2568

seems that the lib->fp_surf[i].zoom_100 is modified by the view manager

**Comment by AlicVB** [comment]
Oh ok : indeed I've added this to ensure that zoom levels stay the same across all pictures in expose mode. If you have image with different sizes, that means that the max zoom is reach when the smallest image reach 100%... Is that your case ?

**Comment by TurboGit** [comment]
I have seen that indeed. I don't think we want to go above 100% so the only solution would be to MAX the zoom at 100% for each individual pictures. That is, if one is lot smaller it will stays at 100% while the others are zoomed. Would that work?

**Comment by edgardoh** [comment]
Not on my tests, all images are from the same camera, same size,
orientation, etc.

**Comment by edgardoh** [comment]
That will be OK with me, but its not what is happening, I can barely zoom
when displaying same size images.

**Comment by AlicVB** [comment]
@TurboGit : not straightforward to code, but I'll have a look
@edgardoh : so there's a bug somewhere. I'll do some more tests on my side to try to reproduce... Just to be sure : does it happen in full preview too ?

**Comment by edgardoh** [comment]
Full preview is working fine on all view modes, the issue is in regular
preview on expose and culling.

**Pull request merged**
