### PR TITLE
Relicense promo svg

### LINKED ISSUE #9674: SPDX statement in appdata file does not match LICENSE
Gnome software reports Darktable license as `Proprietary`, since the appdata file
defines:

https://github.com/darktable-org/darktable/blob/1dd4b369cc1fc3aa1d829c6e649206e3b91ada85/data/darktable.appdata.xml.in#L10

and `CC-BY-NC-3.0` is not an approved OSI or FSF free software license.

According to https://www.darktable.org/about/ and https://github.com/darktable-org/darktable/blob/master/LICENSE
the license is GPLv3.

The issue is described in
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-project_license

> The license given in the project_license tag should be the ‘main’ license of the project. For a software project, this is typically the license for the code. It is not recommended to include the license for accompanying documentation (for example) in project_license, as that could confuse users. In particular, the CC-BY-SA-3.0 license which is commonly used for documentation is not an (FSF or OSI) approved license for free software, so including it in project_license results in the project as a whole being considered non-free.

Looking in https://spdx.github.io/spdx-spec/appendix-IV-SPDX-license-expressions/#1-disjunctive-or-operator
it seems that using `OR` will fix this issue.

See also gnome-software bug:
https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1338

### LINKED ISSUE #10002: The promo watermark isn't FLOSS
I noticed Darktable uses the non-free `CC-BY-NC-3.0` license ([here](https://github.com/darktable-org/darktable/blob/master/data/darktable.appdata.xml.in#L10
)), making de facto the project as a whole non-free. After searching, it seems to be caused by the `data/watermarks/promo.svg` file, which contains mentions of using that license ([here](https://github.com/darktable-org/darktable/blob/e8cb2cb1d9a2b34a4bbe27278247dae0ff09c3c8/data/watermarks/promo.svg?short_path=d8e98d2#L292) and [here](https://github.com/darktable-org/darktable/blob/e8cb2cb1d9a2b34a4bbe27278247dae0ff09c3c8/data/watermarks/promo.svg?short_path=d8e98d2#L301)).

Maybe it's worth changing the license of that file to a free one so the application as a whole can still be considered FLOSS? Or replacing the file if that's impossible.

### PR DESCRIPTION
**Pull request by darix**
Change the license of promo.svg to CC-BY-SA-3.0

In [#10002][0] the author and creator (@MRIG) offered to drop the file or
relicense the file if necessary. As [parafin][1] pointed out, dropping
the file might break edits. So apply the 2nd option.

Fixes #10002

Update the appdata file with the new license combination

With the change in b5f4026cd we have no more files in CC-BY-NC-3.0.

This should fix #9674.

[0]: https://github.com/darktable-org/darktable/issues/10002#issuecomment-919335546
[1]: https://github.com/darktable-org/darktable/issues/9674#issuecomment-993679181

### CODE REVIEW

**Comment by darix** [comment]
@TurboGit @aurelienpierre can we get this into 3.8.0 and then also backported to 3.6-stable please?

**Comment by TurboGit** [comment]
Sure I'll merge later today in 3.8. Why in 3.6? We won't release any new version on this branch.

**Comment by darix** [comment]
Just in case we do another 3.6.x release at some point. but 3.8.0 is making me happy too.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
