### PR TITLE
modulegroups manager : rework dialog ui

### LINKED ISSUE #8562: manage module layouts: convert side menu to combobox
The manage module layouts screen often has module groups that disappear off the right-hand-side of the dialog.

I would like to suggest that the left-hand menu pane be converted to a combobox at the top of the dialog so that more horizontal space can be given over to the module group manipulation pane.

This could even be combined into the existing "preset name" entry field.

### PR DESCRIPTION
**Pull request by AlicVB**
fix #8562 
close #8578 

This implements a new disposition for the modulegroups manager window for the following goal : 
- avoid horizontal scrollbar for groups and let more space to show them

So the preset list is put on top in a combobox...
All previously features are available (except duplication or deletion of the non-current preset)
This also solve a little missing feature to detect and avoid preset names collisions...

@elstoc : ping, as it's your idea in fact :)
@Nilvus : if you have some time to review css (can be after the merge)... imho it's ok like that, but I'm sure you will propose some enhancements ;)

### CODE REVIEW

**Comment by elstoc** [comment]
Looks good. A couple of comments

- You have a checkbox for auto-apply preset but none for auto-show and if you choose auto-show in the dialog there's no way to see that you've done it. I envisaged greyed-out (insensitive) checkboxes - if you're going to allow the user to tick them, they should change the tick boxes in the resulting dialog as well
- The arrows to move the groups around don't behave predictably - move some groups around and occasionally one of the buttons won't work or it will skip over two groups instead of one or move the wrong group. It's even sometimes possible to move a group before the quick access panel.
- I'm not sure you need the presets label on the combobox but it might be worth styling it with slightly larger font?
- An issue I've seen on a few things - if you click on a plus button, that button gets focus and is styled differently until you click on another. It's even possible to have multiple plus buttons styled this way. Similar thing in the auto-apply popup: if you select then deselect a tick box it remains highlighted. Same thing on the other checkboxes tbh. May be easier to change the CSS so that these effects are never applied.
- When you open the maintain screen doesn't always default to the preset that's currently selected in the darkroom. I can't find an entirely reliable reproducer though
- It seems to be possible to duplicate the search only preset and then de-select the search-only checkbox. If you exit and go back in, the search box is re-ticked. Might be worth making the tick box insensitive and auto-selected if there aren't any groups. Similarly it might be worth preventing the last group from being deleted if the box isn't checked.

**Comment by AlicVB** [comment]
First, thanks for this detailed review !

>     * You have a checkbox for auto-apply preset but none for auto-show

yep, that's because auto-show isn't implemented for libs afaik . We'll need to either remove it from the preset dialog or implement that for libs too



>     * I envisaged greyed-out (insensitive) checkboxes - if you're going to allow the user to tick them, they should change the tick boxes in the resulting dialog as well

insensitive checkbox is a solution, yes... I've preferred the way where each toggle open the preset dialog, whatever the checkbox state and then the checkbox is updated with the result of the dialog. But I can make them insensitive as well if you prefer, and just use the button to get the dialog...



>     * The arrows to move the groups around don't behave predictably

I've not really changed how they work, so I think this is an "old" issue... but I'll have a look !

For the focus issues, I think that this is out of the scope of this PR (easy way to avoid fixing it, as I've no idea how to solve it :-P)
For the "search only" part, I'll have a look too : we clearly miss some safeguards here !

**Comment by elstoc** [comment]
> whatever the checkbox state and then the checkbox is updated with the result of the dialog

I'm fine with implementing it like this but the update should go both ways - i.e. tick the box to open the dialog with the appropriate box ticked.

**Comment by TurboGit** [comment]
Also, it would be nice to keep the dialog size and restore it each time the module group is opened.

**Comment by TurboGit** [comment]
>     * The arrows to move the groups around don't behave predictably

I also see that, but I don't have a way to describe in which circumstances it happens. Strange...

**Comment by AlicVB** [comment]
> I also see that, but I don't have a way to describe in which circumstances it happens. Strange...

fixed ! stupid leftover from the quick acces panel addition...

**Comment by elstoc** [comment]
> Also, it would be nice to keep the dialog size and restore it each time the module group is opened

That would be great, yes. If you can work out how to do it, we could also do the same with preferences.

**Comment by TurboGit** [comment]
> That would be great, yes. If you can work out how to do it, we could also do the same with preferences.

We already do that for the import dialog.

**Comment by elstoc** [comment]
Ok I'll look at doing the same for preferences. PR coming soon.

**Comment by TurboGit** [comment]
> Ok I'll look at doing the same for preferences. PR coming soon.

Thanks, look for:

**Comment by AlicVB** [comment]
last changes : 
- fix the erratic group move
- remember the previous window size (default is same as before)
- safeguards to avoid completely empty preset
- bigger font in the top part of the dialog
- hide the filtering checkbox in the preset dialog in case of libs (as this feature is not implemented for libs yet) 

I hope to not have forgot anything :)

**Comment by elstoc** [comment]
I'll give it a proper test in the morning but looks like you've resolved most of the stuff I've raised. There needs to be some CSS love - mostly spacing between the combobox and the buttons, and between the auto-apply label and the settings button. 

The only thing I can't see from my comments is removal of the "preset: " label on the combobox which I don't think is necessary. In terms of the bigger font, I was just talking about the preset combobox really, so your eye is drawn to it: "first step - choose from this list".

Remembering the previous size is a very very useful addition for this screen.

**Comment by elstoc** [comment]
I suppose my only other comments are about the visual balance of the groups. It feels to me like the quick access panel should be allocated more space (at least the same amount of space as the rest of the groups). Also the visual balance of the group headers is thrown off a bit by the arrows. I wonder if they might look better on the same row as the + icons?

**Review by TurboGit — APPROVED** [review]
Merging now to get more field testing and feedbacks.

**Comment by TurboGit** [comment]
Manually merger with conflict resolution.

**Comment by Nilvus** [comment]
I discover all that and seems interesting. Good to see some CSS optimizations and less code. Good work @AlicVB. Will check CSS more ASAP but I have really few times actually. But I will try to work again on that part until the end of this month.

**Pull request closed without merging**
