### PR TITLE
Extend rotation angle slider tooltip about soft limit escape hatch

### PR DESCRIPTION
**Pull request by yaitskov**
https://github.com/darktable-org/darktable/issues/12156

### CODE REVIEW

**Comment by victoryforce** [comment]
You should not touch translation files, updating them is the work of translators. Changes in translatable strings will be reflected in the gettext template file, which translators use to get updates to work with.

**Comment by dterrahe** [comment]
In 4.0 you can also "force" adjustments larger than the soft limits in bauhaus sliders by scrolling while hovering over the left or right 10% of the slider bar or by holding `ctrl+shift` while dragging or scrolling. If fallbacks are enabled, this also automatically works for "dynamic" shortcuts.

It would be useful if bauhaus visuals were improved to indicate whether the currently shown range is soft-limited. A task for someone with artistic skills...

**Comment by yaitskov** [comment]
Thanks for quick feedback!
I reverted PO files.

My points are: I am total newbie in photo post-production. 
Newbies usually is biggest shared user in an app.
Newbies is the source for regular users, isn't it.
I was blocked on the issue for a few hours and I had to ask for help.

Documentation is good to have, but why following meme exists "if nothing helps read the manual". ;)
younger generations tend to read less books and keen to watch stuff.
Do iphone/android have manual? probably, but who read them?

The UI solution seems unique to DarkTable (DT). Maybe there is some CAD system / flight simulators leverage on it, but these are rare systems.

I am for innovations, but DT is not market leader and having different UX from its rivals and not presented in UI of regular apps (such as mail, player, word processor...)  has cost - poorer "conversion rate" to regular app users.

There are lot of sliders in the app and this is my first PR. Not all sliders control values in the same domain, but slider soft limit is constant, so overlap ration between soft limit and full domain is different same as relevance of tooltip extension. For rotation angle overlap looks tiny 1/10 if let's say limit is 100 degrees. Maybe pro photographers don't leave 10 degrees range  for horizon correction 99% of the time but newbies do. I have an idea for general solution: _a stack of drop down sliders for every decimal digit. Once a slider hits soft limit (10.0) another slider below appears for another digit (preset with 1), and original slider gets 0._ This way resolution density is preserved and UI is "self-explanatory".

Thanks for shortcuts. 

P.S.
My rare case when required shortcuts are suboptimal - I have a Debian laptop - scrolling wheel died on my external mouse, but I prefer type with external keyboard, because I don't have an external monitor I put my laptop on a box to don't put strain on my neck. So scrolling is out.
Ctrl Shift is magic combination which is often used to switch keyboard layout and on Linux UI user might have hard time catching it.

**Comment by TurboGit** [comment]
> Documentation is good to have, but why following meme exists "if nothing helps read the manual". ;)
> younger generations tend to read less books and keen to watch stuff.

And then why should we care... if one does not read the manual it will certainly use dt at 10% of its power. No tooltip will help about that. It would be really sad to use dt like a simple phone app.

**Pull request closed without merging**
