### PR TITLE
collect: fix range selection and click

### PR DESCRIPTION
**Pull request by AlicVB**
This allow to select range of value with shift-click even without the "single-click" setting

### CODE REVIEW

**Comment by TurboGit** [comment]
> This allow to select range of value with shift-click even without the "single-click" setting

Maybe I did not understand what this was about but I was thinking it would allow to:
1. select 1 star
2. fly over the 3 stars and shift-click to have a range selected from 1 to 3 stars.

The scenario above is not working on my side. Can you clarify? TIA.

**Comment by TurboGit** [comment]
Ah ok, this is on the collect module, I was trying to do a range selection with shift-click on the collection filters (the new module you've added recently).

**Review by TurboGit — APPROVED** [review]
Working on my side, thanks!

**Comment by AlicVB** [comment]
@TurboGit : ok, now I understand :) That would be a good addition for the filters thought !

**Pull request merged**
