### PR TITLE
Updated sk translation #2

### PR DESCRIPTION
**Pull request by miroslavfikar**
Updated sk translation #2

### CODE REVIEW

**Comment by TurboGit** [comment]
Please do not merge master branch into your topic branch. Can you clean-up the PR, a single commit without any merge? Thanks.

**Comment by miroslavfikar** [comment]
> Please do not merge master branch into your topic branch. Can you clean-up the PR, a single commit without any merge? Thanks.

I am sorry, this is my first attempt to help with translations using git and I probably messed it up. I was following this page: https://redmine.darktable.org/projects/darktable/wiki/Translating_darktable

How can I start from scratch? (I will copy my modified po file somewhere else).

**Comment by miroslavfikar** [comment]
> Please do not merge master branch into your topic branch. Can you clean-up the PR, a single commit without any merge? Thanks.
Dear Pascal, attached is the updated sk.po file, please add it to the repository. And meanwhile I will try to find out the correct way of interacting with git.
Best, Miroslav

[sk.po.gz](https://github.com/darktable-org/darktable/files/3885055/sk.po.gz)

**Comment by TurboGit** [comment]
Merged, thanks!

**Pull request closed without merging**
