### PR TITLE
thumb : allow to set tooltip visibility per size/mode

### PR DESCRIPTION
**Pull request by AlicVB**
this can be set in the overlays popup menu.
By default, tooltips are on except for "big" thumbnails and culling/preview

### CODE REVIEW

**Comment by TurboGit** [comment]
Something buggy here, I had permanent overlay for size 1 and 2, now
- set lt to size 1
- open menu for overlay and set "show tooltip"

The lt now is set with overlay on mouse over and not permanent. This can be reproduced all the time.

**Comment by AlicVB** [comment]
damn it... I think I've fixed that already... I'll have a look

**Comment by AlicVB** [comment]
ok, so I've mess up with git again... There was 2 commits of this PR but the second one has been dropped I don't know where... I've finally recreated it from scratch.
Indeed without this one the PR broke everything... sorry !

**Comment by TurboGit** [comment]
Works for me now. Thanks!

**Pull request merged**
