### PR TITLE
Fix highlights colorspace conversion, enable for non-monochromes

### LINKED ISSUE #15156: Highlight reconstruction fails with EXR Image
### Describe the bug

I have recently opened an EXR image which i had imported into darktable some time ago (nov 2022) with an
older darktable version.

When now opening the image in DT 4.4.2, only the upper third of the image is visible, in the preview and also in the
darkroom view.
The file itself is ok, since when opening with gimp or with an image viewer, it shows full content. See screenshot.

It re-appears fully in DT as soon as i click the module "filmic rgb" one below "highlight reconstruct". See screenshot.

As soon as i click in "highlight reconstruct" or any above that in the history, the image is broken again.

### Steps to reproduce

Since i dont want to upload my full image here, i have attached my xmp file.
1. Plug in an EXR file matching my XMP file, so it gets hopefully reproducible.
2. Import image into DT.
3. Go to Darkroom. Image should be broken
4. click into history step 6, Image should be ok.

XMP file:

[2022-11-05 22-28-13 (C,S2).exr.xmp.txt](https://github.com/darktable-org/darktable/files/12500237/2022-11-05.22-28-13.C.S2.exr.xmp.txt)

Screenshot showing the bug (click anything later than step 6):

dt-bug-2

Screenshot if clicking in step 6:
Dt-Bug-1

### Expected behavior

_No response_

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you install darktable from?

flatpak

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Describe your system?

NVidia RTX 3060 present, which is used for OpenCL rendering.

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia RTX 3060

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
1. Make sure the colorspace is taken correctly even for non-raws/sraws
2. Re-enable the module for non-raws with clip and opposed as selectable modes, same as for sraws.

Fixes #15156

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
While checking this; the latest 2 commits are code maintenance for OpenCL code, in the laplacian code there was also a memory leak in case of errors

**Comment by jenshannoschwalm** [comment]
@TurboGit to make this an easier review i just did what is required as a fix ...

**Review by TurboGit — CHANGES_REQUESTED** [review]
This beaks old JPEG/TIFF (all non non-raw) edits as it now enable the module by default. We have two options:
1. Enable the module for non-raw only for new edits
2. Disable the module for non-raw and let users enable it if needed

I have no strong opinion on this. Maybe 2 is better as highlights on non-raw will most of the time not do a big change anyway.

**Comment by jenshannoschwalm** [comment]
I would also opt for 2. Will do

**Comment by jenshannoschwalm** [comment]
I tested and the latest push commit should be fine

**Comment by jenshannoschwalm** [comment]
Release note would be:
Highlights module is available for all non-raw files

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
