### PR TITLE
import: fix unworking gtk_tree_view_scroll_to_cell()

### LINKED ISSUE #8804: [collect images] image filtering got severe regression after new import dialog got introduced by ee9ac742f
**Describe the bug/issue**
I have organised my pictures as following:

~/pictures/YYYY/YYYYMMDD_(event or job-code)/(subfolder per day of shoting)

That means the parent folder for event or job-code does not include any RAW files but the subfolder, they do.

I do move and rename my pictures with RapidPhotoDownloader (which actually offers the function to separate the pics per shooting day)

_In the past_ 
I imported the parent directory with dt and all was fine, I got that parent directory listed in the film roll of "collect images" module and saw all pictures at once and still did have the chance to further filter the collection per day if I wanted (and leave/remove that filter if I do not want anymore).

_Now wIth the new import dialog_ 
introduced by 3.5.0-1415-gee9ac742f (if I am not mistaken), you have to import a complete collection, e.g. for my case ~/pictures/YYYY. So far so good, but now in the "collect images" module you merely see the day by day folders but no more the parent folder with event or jobcode.

In below screenshot (sorry is German due to --configdir /tmp) you see several folders from August 2020. Those are all from a trip to Rostock in Germany. 
- There is no way _anymore_, to have all those pics in one collection in lighttable (e.g. to export them all at once)

grafik

PLEASE no recommendations such like "...oh you better organize your photos differently..." 
- That org is not so uncommon, 
- it worked for many years, 
- more than 85k pics 
- and a five years differential backup behind. 
So there is no way for me to re-arrange. 

From my point of view we recently introduced a **severe regression**.

SIDE NOTE: me and my family we are in the progress of moving home. That situation has some issues in the background making it more severe and prioritised than usual. Any expected reply or involvement from my side might have huge delays (even my PC will be packed soon). I am expecting my self coming back to a little bit normal around August time frame but didn't want to let this rest by the time 3.6 would be out.

**Expected behavior**
Actually I just want to have it as it was before (e.g. like in the current official branch of 3.4.1)

**Which commit introduced the error**
AFAIK 3.5.0-1415-gee9ac742f 
@phweyland may I kindly ping you here

**Platform**
* darktable version : 3.5.0+1415~gee9ac742f-dirty and 3.5.0-1908-g26428873c
* OS                : Linux - kernel 5.11.11-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : NVIDIA GeForce GTX 1060 6GB
* Graphics card1    : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-465.19.01
* OpenCL installed  : Yes (opencl-headers-2020.06.16)
* OpenCL activated  : Yes
* Xorg              : xorg-server-1.20.11
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.26
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "RelWithDebInfo" 

**Additional context**
 - Can you reproduce with another darktable version(s)? **yes all since ee9ac742f*
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

### LINKED ISSUE #8809: import: scroll to selection doesn't work
The new import-in-place functionality is supposed to expand the folder structure to the last selected folder and then scroll to it, but the call to `gtk_tree_view_scroll_to_cell` doesn't seem to work and I can't figure out why. If the last selected folder is off the bottom of the scrollable area, it remains invisible on launch of the dialog and you have to manually scroll to it.

@phweyland any ideas?

### PR DESCRIPTION
**Pull request by phweyland**
fix #8809

@elstoc thanks for giving me the opportunity to clean up this. And BTW not too far from one of your suggestions.

fix #8804 as well

### CODE REVIEW

**Comment by elstoc** [comment]
hehe cool

**Comment by elstoc** [comment]
I hate to scope-creep your PRs (that never stopped me before), but while you're here, I much prefer for the last-selected folder to have its sub-folders collapsed when re-entering the import dialog, since this usually best matches the state the window was in when it was last closed.

So add a call to `gtk_tree_view_collapse_row()` after the call to `gtk_tree_view_expand_to_path()`.

I'm happy to submit as a separate PR but thought it would save some effort to include it here, if you agree.

**Comment by phweyland** [comment]
>  I much prefer for the last-selected folder to have its sub-folders collapsed when re-entering the import dialog, since this usually best matches the state the window was in when it was last closed.

I don't understand. Could you give any example ?

**Comment by elstoc** [comment]
> I don't understand. Could you give any example ?

Sure. If I select the following folder for import, it does not expand on selection. Immediately before I press the import button (or cancel out), the screen looks like this:

Screenshot_2021-04-29_00-00-40

When I choose import-in-place the next time, the folder is now expanded

Screenshot_2021-04-29_00-00-58

I want it to look like the first screenshot - since we don't auto-expand sub-folders when selecting them manually, we shouldn't auto-expand them when selecting them automatically either.

**Comment by phweyland** [comment]
Got it. Makes sense. Thanks. I'll do it.

**Comment by phweyland** [comment]
done

**Comment by elstoc** [comment]
Thanks @phweyland. Works for me.

**Review by TurboGit — APPROVED** [review]
Thanks !

**Pull request merged**
