### PR TITLE
imageio: avif: Add support for libavif >= 0.7.0

### PR DESCRIPTION
**Pull request by cryptomilk**
Add support for libavif >= 0.7.0

### CODE REVIEW

**Comment by parafin** [comment]
What happes with libavif 0.7.0 without this patch?

Did libavif change ABI version of the library at this release (it's a number after libavif.so.)?

I'm concerned about what happens when dt is built against older libavif and then libavif is updated.

**Comment by cryptomilk** [comment]
libavif changed the API and bumped the SO version number from libavif.so.2 to libavif.so.3 for 0.7.0.

```
magrathea:~ # rpm -qa | grep libavif[0-9]
libavif3-0.7.1-1.1.x86_64
libavif2-0.6.2-1.1.x86_64
```

**Comment by parafin** [comment]
OK then

**Comment by TurboGit** [comment]
Looks good to me, thanks !

**Pull request merged**
