### PR TITLE
Fix crash on startup when debug output enabled

### PR DESCRIPTION
**Pull request by victoryforce**

### CODE REVIEW

**Comment by wpferguson** [comment]
Tested on windows and still crashes.  On Linux no crashes with or without the change.

**Review by TurboGit — APPROVED** [review]
Indeed, strange to see a `dt_free_align()` here! Thanks!

**Comment by wpferguson** [comment]
Further testing revealed that this does indeed fix the crash on windows.  I also had a corrupt configuration directory, so once I got rid of that I could do some accurate testing.

**Comment by wpferguson** [comment]
Thanks @victoryforce

**Pull request merged**
