### PR TITLE
ellipsize created shapes label in mask manager

### PR DESCRIPTION
**Pull request by elstoc**

### CODE REVIEW

**Comment by elstoc** [comment]
I didn't try it on an image with shapes so I didn't spot that. Sounds reasonable.

**Comment by elstoc** [comment]
Actually I can't see the number of shapes. Are we looking at the same place?

**Comment by TurboGit** [comment]
@elstoc : mask manager is fully broken anyway :( See #5359.

**Comment by elstoc** [comment]
Ah. Well I've made the change to ellipsize in the middle instead if you want me to push it. I don't spend much time in mask manager so it's not a big deal for me. I was just going through the modules to find which ones cause the header buttons to disappear off the side of the screen when you shrink the panel.

**Comment by TurboGit** [comment]
I see, this is only for the label, not the shapes name inside the mask manager. All good then.

**Pull request merged**
