### PR TITLE
Fix history_end setting.

### PR DESCRIPTION
**Pull request by TurboGit**
It is possible to have non continuous value for history.num. So MAX(num)
can be wrong, it is better to use COUNT(num) in this case.

### CODE REVIEW

**Comment by TurboGit** [comment]
You can see that the history is not continuous by running:

sqlite> select imgid,count(num),max(num) from history group by imgid;

**Comment by TurboGit** [comment]
Even better a new version with code refactoring to avoid duplicated code.

**Comment by houz** [comment]
That is wrong, it has to be max+1.

**Comment by TurboGit** [comment]
Ok, I understand. But don't we have something to do if the history stack has hole? I mean this will happen for every users with hole in the history.

I've looked at a way to have an SQL command to remove hole, but it seems that this is impossible with SQLite which is missing some commands like row_number() and dense_rank() and more over it does not support ""OVER(partition by ...)".

Do you see a solution to fix that?

**Pull request closed without merging**
