### PR TITLE
po/atrous mix

### PR DESCRIPTION
**Pull request by TurboGit**
The mix value in atrous is now part of the parameters. It can then be adjusted later without loosing precision. The edit on the curve is down with mix = 1.0 as it is not possible (easy & understandable) to edit the curve with mix < 0. The way it is working in this PR is good to me.

### CODE REVIEW

**Comment by elstoc** [comment]
Looks good to me. Perhaps needs a tooltip or something to signpost that negative mix being edited in positive mode is intended behaviour. Also, rather than editing negative mix with +1.00 why not just always edit with ABS(mix)?

**Comment by TurboGit** [comment]
> why not just always edit with ABS(mix)?

That's not so easy to edit. I tried that but with a mix of say 0.1 you have little vertical space for the edit. Remember that the values are all bounds [-1 .. 1 ]. So at the end you have 1/10 of the vertical space and 1/10 of the precision.

**Comment by TurboGit** [comment]
> Perhaps needs a tooltip or something to signpost that negative mix being edited in positive mode is intended

Yes, good idea !

**Comment by elstoc** [comment]
> with a mix of say 0.1 you have little vertical space for the edit

Well yes, but then the same is true of editing positive mixes

**Pull request merged**
