### PR TITLE
Enable UCRT build on Win (GCC and Clang)

### LINKED ISSUE #10280: Windows build fails for UCRT instead of MSVCRT
Same error in both the [UCRT64 and CLANG64 environments](https://www.msys2.org/docs/environments/), so not depending on compiler but C runtime library only:

```
../src/win/strptime.c: In function 'strptime':
../src/win/strptime.c:392:11: error: 'tzname' is deprecated: Only provided for source compatibility; this variable might not always be accurate when linking to UCRT. [-Werror=deprecated-declarations]
  392 |           ep = find_string(bp, &i, (const char *const *)tzname, NULL, 2);
      |           ^~
compilation terminated due to -Wfatal-errors.
```

_Originally posted by @kmilos in https://github.com/darktable-org/darktable/issues/9010#issuecomment-847858362_

### PR DESCRIPTION
**Pull request by kmilos**
Fixes #10280

### CODE REVIEW

**Comment by kmilos** [comment]
As there is no gphoto2 in the clang64 repo yet, this also requires https://github.com/darktable-org/darktable/pull/10660

**Comment by kmilos** [comment]
@wpferguson @johnny-bit @TurboGit Please review - it is important to enable UCRT builds for a) potentially better/native UTF-8 support [1-3] in the future and b) as the only option for building for Windows on Arm ([MSYS2 CLAGARM64 environment](https://www.msys2.org/docs/environments/)), so we might as well start testing on UCRT64/CLANG64

[1] https://developer.r-project.org/Blog/public/2020/05/02/utf-8-support-on-windows/index.html
[2] https://developer.r-project.org/Blog/public/2020/07/30/windows/utf-8-build-of-r-and-cran-packages/index.html
[3] https://developer.r-project.org/Blog/public/2021/03/12/windows/utf-8-toolchain-and-cran-package-checks/

**Comment by johnny-bit** [comment]
Personally - I'm all for it.

**Review by TurboGit — COMMENTED** [review]
What about the LibRaw changes, have they been proposed as PR to the main repository?

**Comment by kmilos** [comment]
Yep, just syncing the dt external repo to that commit.

**Review by TurboGit — APPROVED** [review]
All good then, thanks!

**Comment by kmilos** [comment]
Ta

**Pull request merged**
