### PR TITLE
Fix shifting numbers

### LINKED ISSUE #12941: issue when editing values in the preferences
Set a key shortcut with effect=set and try to edit the value, see:

image

The editing "entry" seems shifted somehow.

### PR DESCRIPTION
**Pull request by Nilvus**
Fix #12941

### CODE REVIEW

**Comment by TurboGit** [comment]
Still not working on my side:

image

It depends on the actual preference window width, if I make it smaller now the edit zone is way farther on the left:

image

**Review by TurboGit — CHANGES_REQUESTED** [review]
Still something not working.

**Comment by Nilvus** [comment]
So I can't do more on my side. I just revert commit @dterrahe point a different way to allow keeping fix made by the commit. On my side, I can't reproduce your issue. That so means there's something else not only on CSS code probably.

**Comment by Nilvus** [comment]
To be sure we talk about same thing, your issue was numbers shifting in spinbutton entry when changing them. I fix that. On your screenshot here, I dont see any shifting number. With that PR, I do not have anymore shifting number on my side, I have them with actual number.

**Comment by dterrahe** [comment]
Away from computer so can't check this PR, but the bigger issue was not the shift, but the fact that the _entry_ became transparent so that both the number in the list and the number in the entry are visible at the same time. This PR does not attempt to fix that.

**Comment by Nilvus** [comment]
> Away from computer so can't check this PR, but the bigger issue was not the shift, but the fact that the _entry_ became transparent so that both the number in the list and the number in the entry are visible at the same time. This PR does not attempt to fix that.

If my PR doesn't fix that, that means so that my commit you pointed was not the cause. This PR set back background-color as it was. Now, I don't understand anymore the issue and so what can I do...

**Comment by dterrahe** [comment]
Looks to me you only fixed the `spinbutton button`, not the `entry`?

**Comment by Nilvus** [comment]
> Looks to me you only fixed the `spinbutton button`, not the `entry`?

The entry is put back like before commit, as well as spinbutton. Commit was there to fix another part. I need to take care of both. On my side, it works and I see a difference. If it's not fixed, I so don't understand the issue.

**Comment by Nilvus** [comment]
Note that for the entry, nothing had changed. Before, after commit you pointed, and that PR, background is the same. So if it's the issue, the issue was old and before my commit.

**Comment by dterrahe** [comment]
You are right. Still a CSS issue though...

**Comment by Nilvus** [comment]
As I have no more infos and I can't reproduce issue, maybe I should close this.
@TurboGit: your screenshots are not helpful. More, they do not show same thing than those on your issue and make the issue completely unclear for me. I can't reproduce shifting numbers shown on your issue with that PR but I can with actual master. So is this PR useful or not?

I will not (and can't) do more as I can't reproduce on my side and have no more infos here (nor on Matrix).

**Comment by Nilvus** [comment]
I removed my last comment as I finally found a way to reproduce. I don't know how to fix that and I can't understand why this could be a CSS issue. The issue is that when spinbuttons are shown (by clicking on entries) and size is too small, the treeview column is not updated to show correctly spinbutton. So spinbutton with entry is displayed above other parts around.

What is needed is that treeview column should be updated regarding its content. And that is done in Gtk/C code, not CSS.

I so update that PR as its content remains necessary but I don't have skills to fix issue. I remove the link to it.

**Comment by dterrahe** [comment]
With transparent _entry_, as currently in css:
image


With
```
spinbutton button,
entry
{
  background-color: alpha(@fg_color, 1);
}
```
image

There's still something going wrong with the +/- in the spinbutton buttons; I do not know if that has always been the case (and I don't particularly care), but at least when I implemented the shortcuts dialog the entry itself was readable, like here, and the buttons didn't "blend" into the text behind, because the text in the background was covered and not seen-through.

I'm sure the `background-color: alpha(@fg_color, 0.09);` was put in for some very good reason though, so the fix may need to be more specific then what I gave here as a demonstration.

**Comment by Nilvus** [comment]
You say it: "and the buttons didn't "blend" into the text behind, because the text in the background was covered and not seen-through."
That so means that the issue was there before and just that some previous background hide that. So CSS is not a fix, it's a workaround.

**Comment by dterrahe** [comment]
The edit box previously did _not_ have an alpha of 0.09, so it was _not_ transparent, which is what gtk depends on when it overlays it over the table when the entry is being edited. At some point, after I implemented the list in the way it is intended by gtk, the `background-color: alpha(@fg_color, 0.09);` was added, which made the entry see-through, which broke the behavior gtk expected. I am not going to look up for you when that happened, because, frankly, I am not interested.

@TurboGit I hope you understand I am not going to waste further time on this. It is tiresome.

**Comment by Nilvus** [comment]
Alpha was added to better show related items on all background (since collapsible sections adding). Anyway, thanks for your feedback and comments. This was tiresome for me too but your feedback make me understand better the issue. I will so update that PR and revert back some settings here and just add specific background for spinbutton on treeview. Will be easier and made the trick.

**Comment by Nilvus** [comment]
@TurboGit: PR updated. Should be good now.

**Review by TurboGit — APPROVED** [review]
Perfect @Nilvus, works for me. Thanks!

**Comment by TurboGit** [comment]
> @TurboGit I hope you understand I am not going to waste further time on this. It is tiresome.

No problem, energy goes where we fill comfortable anyway.

**Pull request merged**
