### PR TITLE
manual: basic documentation for mask feathering

### PR DESCRIPTION
**Pull request by rabauke**
This pull request provides some basic documentation for the new mask feathering feature. I plan to add an example to illustrate its usage in a future pull request.

### CODE REVIEW

**Comment by rabauke** [comment]
@upegelow Comments, corrections or any other suggestions are always welcome but I can't see any.

**Comment by upegelow** [comment]
Looks like I forgot to press "submit".

**Comment by rabauke** [comment]
@upegelow Thanks for your suggestions, which I have tried to incorporate into my revised version.

**Comment by upegelow** [comment]
Perfect. Thanks!

**Pull request merged**
