### PR TITLE
po/fr upcase

### PR DESCRIPTION
**Pull request by TurboGit**
@Nilvus : This is a rewrite of the French translation to:
- Use capitalized words
- Fix the list to be uniform, some with starting with - and other with a big-dot and the option was sometime around quote on some others not...
- Fix some full upper-case acronym like PDF...

### CODE REVIEW

**Comment by Nilvus** [comment]
I will test that but for this, will be better to let that PR opened few weeks (I just mean 2 or 3 for example). 4.4 release is in 4 months and will be good to test on use that, see which parts are ok, which are affected by CSS and if we need to deal (or not) with other languages that have uppercase (or not).

**Comment by TurboGit** [comment]
CSS can't be affected as this is only changing the translation.

I also don't want this to be let opened too long as part I have also added context for the section on the UI to help all translators to be able to use capitalized words as discussed in the previous PR. So ok, to be open a week but not much as I don't want to maintain this specific branch for too long.

What is important here is that we at least agree about the translation and BTW everybody else can fix the remaining strings.

**Comment by TurboGit** [comment]
And just a last note... This **can't be 100% correct** as I have changed almost all strings, so better having more eyes to look at the rendering directly in darktable.

**Comment by Nilvus** [comment]
When I talk about CSS, it's related to that comment (https://github.com/darktable-org/darktable/pull/13609#issuecomment-1426805427) on your previous RFC PR. 
And of course, I will not check all strings, just check what will rendering be.

**Comment by TurboGit** [comment]
> When I talk about CSS, it's related to that comment ([#13609 (comment)](https://github.com/darktable-org/darktable/pull/13609#issuecomment-1426805427)) on your previous RFC PR.

I don't see the relation with this PR, can you give more details as I may be missing something.

**Comment by Nilvus** [comment]
> > When I talk about CSS, it's related to that comment ([#13609 (comment)](https://github.com/darktable-org/darktable/pull/13609#issuecomment-1426805427)) on your previous RFC PR.
> 
> I don't see the relation with this PR, can you give more details as I may be missing something.

It's explained on comment linked. I don't see anything more to precise. Anyway, it's not important by now. I will test/check and put feedback if it's ok.

**Comment by Nilvus** [comment]
It's good except one important thing: uppercase only first letter of first name on module. In our language, we do not put uppercase on all names. So, for example:

instead of "Balance Couleur RVB", we need "Balance couleur RDV". Instead of "Diffusion ou Netteté", we want "Diffusion ou netteté, etc.

It's ok for example on "Informations de l'image" and on titles on settings.

**Comment by Nilvus** [comment]
Oh, just see filter menu on collections module, same issue, some filters have uppercase on all words, just put it on first word). See screenshot below (3 lines on the middle that are not good):

image

**Comment by TurboGit** [comment]
> In our language, we do not put uppercase on all names. So, for example:

@Nilvus : Thanks for the review. Note that the `Title Case` style does not exist in any language. I have done that to make short title (like module name) more readable as it was discussed for English. In fact those are not correct sentence anyway. That was the rational, isn't this really something you dislike?

**Comment by Nilvus** [comment]
This is clearly something I disklike, in french. It's just not natural and worst than no uppercase at all on our language. Having uppercase on all words for title is ok in english as it's natural on that language.

**Comment by Jiyone** [comment]
I prefer `Title case` too :)

**Comment by TurboGit** [comment]
@Nilvus : New version pushed. I have then removed all Title Case except for 2 module names where there is two different actions : 

- Rotation et Perspective
- Diffusion ou Netteté

**Comment by TurboGit** [comment]
And I have renamed `Docteur néga` en `Docteur négatif`.

**Comment by Jiyone** [comment]
> And I have renamed `Docteur néga` en `Docteur négatif`.

I don't agree on this one. This was not necessary and digress from the original name negadoctor.

**Comment by Nilvus** [comment]
> @Nilvus : New version pushed. I have then removed all Title Case except for 2 module names where there is two different actions :
> 
>     * Rotation et Perspective
> 
>     * Diffusion ou Netteté

I don't like that but I could deal with that. I let other comment. @AlicVB?

For "Docteur néga", I agree with @Jiyone.

**Comment by TurboGit** [comment]
> For "Docteur néga", I agree with @Jiyone.

Well... Title Case is too English, fine but then you prefer néga which is not even in a French dictionary ! What can I say, I'm quite confused by the arguments.

**Comment by Nilvus** [comment]
Short name is used in French as well as in English, even if it's not on dictionary. Thus, Docteur néga just respect original name. Using Title Case or Title case and choosing a name are just two different things, so arguments are just different. Even on real life, we often use words that are in dictionary (added some times years later, sometimes never).

But, I will not battle for Docteur néga(tif) choice, I just put my view but don't and will never use it. So I don't care which choice will be final one.

**Pull request merged**
