### PR TITLE
fix altgr and virtual modifiers

### LINKED ISSUE #9374: OSX: Input System NG: cmd+something is recognized as cmd+meta+something
osx cmd+something is recognized as cmd+meta+something
--> so it's quite cumbersome to use darktable since ctrl+something no longer is used on osx

pressing h indicates cmd+c or shift+cmd+c is defined

**To Reproduce**
1. try to copy paste in lighttabe or darkroom via cmd+c or shift+cmd+c
2. get a message "cmd+meta+c not assigned" or "shift+cmd+meta+c not assigned" 

**Platform**
* darktable version : darktable-3.7.0+178~gfb034c530
* OS                : OSx

### LINKED ISSUE #9384: OSX: Input System NG: arbitrary recognition of shift+ctrl if midi devices (keyboards) are attached
**Describe the bug/issue**
Just pressing shift and ctrl and c is usuallly recognized as a plain "c" 
best way to get this accel is to hold ctrl and shift key and press c several times. 
unfortunately it's behaves very arbitrary ... sometimes even the first attempt is successful

**To Reproduce**
1. edit shortcutsrc and replace cmd by ctrl to avoid the issue with cmd recognition.
2. try to copy paste in lighttable or darkroom via shift+ctrl+c
3. get a message "c not assigned" 
4. keep holding shift and ctrl and press c several times until the dialog appears
repeat this several times since the first attempt might be successful ;)

**Platform**
* darktable version : darktable-3.7.0+178~gfb034c530
* OS                : OSx

### LINKED ISSUE #9397: Input NG regression : cannot add | in tag module
**Describe the bug/issue**

Cannot enter a hierarchical tag in tag module. The pipe character cannot be entered in the tagging entry.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to 'lighttable'
2. Select tagging module
3. Click on 'entry'
4. Try entering 'parent|child'
4. See error, cannot enter |

### PR DESCRIPTION
**Pull request by dterrahe**
Hopefully fixes #9374 and fixes #9397 and fixes #9384.

@MStraeten would you please test if this resolves your issue with cmd+meta?

### CODE REVIEW

**Comment by MStraeten** [comment]
doesn't help cmd+ is detected as cmd+meta

**Comment by dterrahe** [comment]
@MStraeten and @TurboGit would you please test for me if this fixes your issues with modifier keys?

Using French keyboard please test any shortcuts that use AltGr (both default ones, like [ and ] for timeline and rotation) but also newly created ones. AltGr should now be supported as a full fledged modifier so it can be used with any key.

Unfortunately modifier keys under X are notoriously hard to support (gtk doesn't do a complete job of it) so people that have tweaked their keyboard setups (to change which keys map to the "standard" modifiers or to make them "sticky") may run into problems. But probably not worse ones than before.

**Comment by MStraeten** [comment]
it's fine now cmd is recognized as cmd.
but it's like in #9384: it needs several attempts to get cmd+something recognized as cmd+something and not just something

**Comment by dterrahe** [comment]
The last commit fixes the missing modifiers problem when a midi device is connected (#9384) for me under Windows (and also works under Linux).

Would you please let me know if this is portable to OSX too?

**Comment by MStraeten** [comment]
fixed - i can do a cmd+a and also shift+cmd+c and it's recognized on first attempt

**Review by TurboGit — APPROVED** [review]
Works for me, thanks !

**Pull request merged**
