### PR TITLE
Raster mask glitches

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
1. The raster mask polarity button should only be visible if a raster mask has been selected.

2. If there is no raster mask selected the mask should be zero.

### CODE REVIEW

**Comment by TurboGit** [comment]
@jenshannoschwalm : 
1. I think the mask polarity button should be visible but not active to ensure it takes the place and so the corresponding GUI line with have all the widgets at the same place in all conditions.
2. The same problem exists for drawn mask GUI, so I think it should be changed too for consistency.

**Comment by jenshannoschwalm** [comment]
> 1. I think the mask polarity button should be visible but not active to ensure it takes the place and so the corresponding GUI line with have all the widgets at the same place in all conditions.

I don't understand what you are exactly proposing. Currently we toggle between two states which is at least misleading if there is no mask selected. Do you propose this button to be sort of "tri-state" (other symbold for not available?)

**Comment by jenshannoschwalm** [comment]
Ok, done for rastermasks. Other masks are a bit more complicated it seems, also there are two polarity buttons so i would prefer to get this done in another pr.

Use sensitive in latest commit, also squashed.

**Comment by jenshannoschwalm** [comment]
Still working on raster masks & color picker issues reported in #14271. Hard to trigger for me but ...
Would prefer to get this merged without the talked-about other polarity toggle buttons. ok?

**Comment by TurboGit** [comment]
> Would prefer to get this merged without the talked-about other polarity toggle buttons. ok?

As this is a new feature (not really a bug since we have lived with this for years) and dt is now in feature freeze I'm proposing to postpone this for 4.6. There is no urgency. Ok?

**Comment by jenshannoschwalm** [comment]
> There is no urgency. Ok?

Ok, understood. Yet inside this pr there are some bugfixes. (As the opencl stuff) I will prepare a PR just with bugfixes ok?

**Comment by TurboGit** [comment]
> Ok, understood. Yet inside this pr there are some bugfixes. (As the opencl stuff) I will prepare a PR just with bugfixes ok?

Yes, would be good. Thanks.

**Comment by jenshannoschwalm** [comment]
Closing this stuff for now. Will
1. Do a PR's with bugfixes for 4.4 and
2. re-open later for 4.6

**Pull request closed without merging**
