### PR TITLE
Only show element in tooltip when mapping, with shortcuts or on its own

### LINKED ISSUE #11224: Last line in tooltips is "button" or "force"
Reproduce:
Hover mouse over a slider like for example the exposure slider.
Now the last line in the tooltip displays "button" or "force".

Bild1

This happens in my selfbuild (MSYS) master (3.9.0+542).

Does not happen in the regular 3.8.1.
EDIT: does also happen in 3.8.1, but the word "button" is displayed only when the mouse is at the right end of the slider.

OS: Win 10

### PR DESCRIPTION
**Pull request by dterrahe**
fixes #11224

### CODE REVIEW

**Comment by TurboGit** [comment]
Fixes many instances, but I still see some tooltip with just **force**. For example in the blurs module:

Capture d’écran de 2022-03-10 08-53-02

(I was hovering on rotation)

**Comment by dterrahe** [comment]
This is kind of intentional; in all cases where a widget doesn't have an explicit tooltip, but there are elements, the element is used as the tooltip. This is for example used for notebook tabs and for some buttons (the "presets" in this PR is one). One of the reasons for this choice is that otherwise you'd get the same word twice, once as the tooltip and once as the element. With this PR that would only happen in mapping mode, but still.

So there are two (or three) approaches:
1 add a tooltip everywhere. "rotation" maybe doesn't need one, but that hasn't stopped us before.
2 add back tooltips for widgets that currently depend on the inputng one. notebook as I mentioned, but there are others so there is a chance I'll miss one. In mapping mode, compare existing tooltip with element and if identical, don't show twice.
EDIT: actually, I'm now starting to remember this might be more complicated because the notebook tooltip would be at the tab level whereas currently the tooltip is at the widget (tab bar) level. So using gtk tooltips would probably prevent shortcuts from showing completely.
(3 leave as is and live with an occasional "force"; I'll need to add an indication to bauhaus anyway that scrolling over the "force" area ignores soft limits)

I suspect your preference would be 2, but it will take a bit more time (especially the checking for missed cases)
EDIT: given my EDIT at 2, my preference would be to stick with 1 (or 3).

**Comment by TurboGit** [comment]
@dterrahe : Given your description I'll go with 3 now. And if we fill those occasional `force` are a pain in future we will add some tooltips (so doing 1).

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
