### PR TITLE
filemanager : fix scrollbar manual move

### LINKED ISSUE #11390: lighttable: manually dragging scrollbar causes misalignment
If you scroll up and down the lighttable (file manager) view using the mouse scroll button or by pressing the arrow keys, the view scrolls by a single image at a time, such that the top row always contains a row of complete images. However, if you click-and-drag the scrollbar this does not happen, leading to a gap at the top when you scroll back up again. See the following example...

https://user-images.githubusercontent.com/9555491/159715593-8c7d2a01-1414-4032-98ea-1af8e7810fc1.mp4
 
darktable 3.9.0+812~g55c24a5b1

### PR DESCRIPTION
**Pull request by AlicVB**
this fix #11390 
this also tidy up the code, as there's no scrollbars for zoomable

### CODE REVIEW

**Comment by elstoc** [comment]
Certainly better than it was but one minor issue. In the following video I do the following:

1. From the top of the view, scroll down and then back up again by clicking and dragging the scrollbar. Works fine.
2. Repeat with the mouse scroll wheel
3. Manually drag the scrollbar down a tiny bit and then attempt to scroll down with my mouse wheel again. The result is different to when I started from the top (the scrollbar stays in the middle and I don't see an empty row at the bottom).

https://user-images.githubusercontent.com/9555491/165817446-8adfbdca-1bc8-4393-b994-98e5012066a5.mp4

**Comment by AlicVB** [comment]
@elstoc : thanks for the tests. This is indeed another bug caused by the same commit... It should now be fixed by ensuring that scrolling fallback to entire row (and fix the offset accordingly)

**Comment by elstoc** [comment]
Another one I'm afraid. Similar to before but this time if you drag the scrollbar down slightly and then scroll _up_ with the mouse wheel you get an extra empty row at the top.

**Comment by AlicVB** [comment]
@elstoc : next one ? :D

**Comment by elstoc** [comment]
> next one ?

Well now that you mention it... The major issues are gone but in both of the scenarios above the scrollbar position is kind of inconsistent with the position of the images. For example if I click+drag down a little and then mouse-scroll back up again the thumbnails align correctly but the scrollbar doesn't change position.

**Comment by AlicVB** [comment]
Should be fixed !
@elstoc : have you noticed that I don't call for a next one, this time ? :D

**Comment by elstoc** [comment]
> have you noticed that I don't call for a next one, this time ? 

Nice try but I can always break stuff (disclaimer: I did try to fix this issue myself but I got frustrated by all these problems and gave up!).

Scroll all the way to the bottom (there's an empty row). Now click+drag the scrollbar up a little way and then mouse-scroll down again. The view won't scroll down until you've manually pulled the scrollbar up far enough to hide the empty row. Then when you scroll down the empty row comes back.

**Comment by AlicVB** [comment]
I should have fixed that too now...
(and I switch off my computer quickly to not see the next one ;))

**Comment by elstoc** [comment]
> (and I switch off my computer quickly to not see the next one ;))

lol

No more next ones... All good for me now. Thanks @AlicVB.

**Pull request merged**
