### PR TITLE
Add HEIF media type association

### PR DESCRIPTION
**Pull request by AndrewKvalheim**
This registers `image/heif` as a [supported](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-0.9.5.html#mime-types) media type in Linux installations.

I’ve guessed at how you might like to implement this, but I don’t know CMake very well.

### CODE REVIEW

**Comment by kmilos** [comment]
At the same time, we have x-exr and jp2 in there without checking if those are really supported. So we could simply just add heif and avif without checking as well, or fix up the others...

**Comment by TurboGit** [comment]
I'll think we should fix the others. TIA.

**Comment by AndrewKvalheim** [comment]
Thanks, makes sense. Updated to cover the other conditional extensions as well, so this also adds AVIF and CR3.

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Comment by kmilos** [comment]
We actually don't set any other raw type (there is no mime type for those), so there is no need for CR3.

**Comment by TurboGit** [comment]
Let's do that for 4.0.1.

**Comment by kmilos** [comment]
And ppm we support always.

**Comment by TurboGit** [comment]
> We actually don't set any other raw type (there is no mime type for those), so there is no need for CR3.

But how the system knows that dt can open CR3 and propose it in the list of possible application to open such file?

**Comment by AndrewKvalheim** [comment]
> other raw type (there is no mime type for those)

I can offer this:

```console
$ xdg-mime query filetype '2013-09-25T10:04:47#0028.orf'
image/x-olympus-orf
```

> And ppm we support always.

Should `ppm` be added to the [base list](https://github.com/darktable-org/darktable/blob/aad8edc3fa761f406f63231c6a955e773e9a9598/data/supported_extensions.cmake)?

**Comment by TurboGit** [comment]
> Should ppm be added to the [base list](https://github.com/darktable-org/darktable/blob/aad8edc3fa761f406f63231c6a955e773e9a9598/data/supported_extensions.cmake)?

Not sure. We need a specific library to load ppm (GraphicMagick maybe, I did not check) and so if not available it cannot be read. Anyway this needs more digging to be sure.

**Comment by kmilos** [comment]
We support ppm/pgm through src/common/imageio_pnm.c, no GM/IM needed.

**Comment by AxelG-DE** [comment]
When HEIF-support is on, should I then see heif or heic in the export module under the file format?
I compiled master with HEIF but do not see anything like that.

My build log says:
```
$ cat dt.build.1000.2022.10.26.1947.log | grep -i heif
-- Could NOT find libheif (missing: libheif_DIR)
-- Found libheif: /usr/lib64/libheif.so (found version "1.13.0") 
 * libheif
[ 53%] Building C object bin/CMakeFiles/lib_darktable.dir/common/imageio_heif.c.o
```
The full log:
[dt.build.1000.2022.10.26.1947.log.zip](https://github.com/darktable-org/darktable/files/9873007/dt.build.1000.2022.10.26.1947.log.zip)

**Comment by kmilos** [comment]
As the README says, HEIF is supported only for import.

**Comment by AxelG-DE** [comment]
Ooops
tnx

**Pull request merged**
