### PR TITLE
po/dynamic workflow

### PR DESCRIPTION
**Pull request by TurboGit**
This PR makes changing workflow NOT require a restart.

### CODE REVIEW

**Comment by TurboGit** [comment]
Hope someone will review/test this one. TIA.

**Comment by johnny-bit** [comment]
Tested, needs work ;)

1st scenario:
1. start with scene-refered workflow
2. switch to display-refered
3. discard history & open up test image - the exposure module has +0.5 EV
4. restart darktable
5. discard history & open up test image - no exposure module enabled.

2nd scenario:
1. start with display refered
2. switch to scene-refered
3. discard history & open up test image - there's no exposure module enabled!
4. restart darktable
5. discard history and open up test image - exposure module is present and has +0.5 EV

there's something missing about exposure module, otherwise it's fine - the module order is properly set in all cases.

**Comment by TurboGit** [comment]
Issue with exposure module and the new implementation is cleaner.

**Comment by johnny-bit** [comment]
Tested - couldn't break it :+1: 

started with scene ref -> display ref - all is good
display ref -> scene ref - all is good
have on display ref, clear image history, switch to scene ref and enter darkroom - scene ref is applied
have on scene ref, clear image history, switch to display ref and enter darkroom - display ref is applied
switch to "none" from scene ref - no filmic, no basecurve, no exposure
switch to "none" from display ref - no basecurve, no filmic, no exposure...

This works great!

**Comment by TurboGit** [comment]
Thanks, merging then!

**Comment by aurelienpierre** [comment]
Code looks good (I just saw the reviewing request).

**Comment by TurboGit** [comment]
@aurelienpierre : no problem, this has been tested to dead by  @johnny-bit !

**Comment by Nilvus** [comment]
@TurboGit: if this bring not restart needed to change workflow, tooltip in preferences need to be updated as the "need restart" info is still there. Just see on last master, by working on usermanual. Could you update tooltip?

**Comment by TurboGit** [comment]
Good catch! Now fixed, thanks @Nilvus !

**Pull request merged**
