### PR TITLE
Convert colorbalance iop to SSE

### PR DESCRIPTION
**Pull request by bruceg**
Consider this a request for comments -- it works, but I'm sure I've missed some some style and documentation bits (most notably the copyrights on new files are blank).

### CODE REVIEW

**Comment by mgehre** [comment]
darktable uses neither -fwhole-program nor -flto, thus the compiler won't be able to inline the function defined in a cpp file. Due to the fact that the colorspace functions are called in tight loops in colorbalance, I think that all your files should become header files to allow inlining.

I saw quite some speed ups, see e.g. #968

**Comment by TurboGit** [comment]
Do you have figures to share about the speed-up?

**Comment by houz** [comment]
I am currently in the process of merging this manually. I played around a bit with making the color conversions static inline in the .h file but couldn't measure any significant speedup. Do you have some benchmark that's showing something different?

**Comment by houz** [comment]
This was merged manually.

**Pull request closed without merging**
