### PR TITLE
fix compatibility with Xcode 11.3.1

### PR DESCRIPTION
**Pull request by parafin**
Compilation results in segfault on my macOS 10.14 and XCode 11.3.1.
Pinging @ralfbrown since it is his changes: maybe you can figure out a workaround to keep those OpenMP pragmas on macOS.
Also added this type of build to CI to catch these things earlier.

### CODE REVIEW

**Comment by parafin** [comment]
Temporary reverted the changes in this PR to test CI. See first commit for actual changes.

**Comment by parafin** [comment]
It looks like compiler chokes on reduction openmp stuff. Same issue as in 62e4498ed7e60b80767782de4beef7796ab18c7b

**Comment by parafin** [comment]
Specifically using #pragma omp declare reduction is no go (it crashes on use, not definition).

**Comment by johnny-bit** [comment]
Is it possible to do the `__APPLE__` check along with check for xcode version? I was under the impression that older xcode has problems but not newer ones.

**Comment by parafin** [comment]
It is possible, but let’s hear from @ralfbrown first, maybe we can remove it altogether by somehow rewriting openmp pragmas…

**Comment by ralfbrown** [comment]
I don't have any Apple hardware to try this with, and won't really have time to look into it until next weekend.  The trouble with trying to eliminate the problematic reduction clause is that the source code would then need to implement per-thread variables and a second loop to add up the per-thread sums.

**Comment by parafin** [comment]
OK, nevermind then. I've update ifdef's to be more specific, let's see if I guessed the required minimal Xcode version correctly.

**Pull request merged**
