### PR TITLE
po/speed up sql

### PR DESCRIPTION
**Pull request by TurboGit**

### CODE REVIEW

**Comment by TurboGit** [comment]
@phweyland : Can you review ? This do a nice speed up and one table tagq was not used.

**Comment by TurboGit** [comment]
Merged on master and 3.0.1.

**Comment by phweyland** [comment]
Oooohhh! Good catch!
All is good. Just see my comment.

By curiosity, you have moved some space from end to start of line. Any reason for that ?

Thanks

**Comment by TurboGit** [comment]
> By curiosity, you have moved some space from end to start of line. Any reason for that ?

That's just for reading purpose as I'm indenting the SQL from start so there is no need to space at the end. The indenting is helpful (at least to me) to better see the actual SQL syntax.

**Comment by TurboGit** [comment]
> All is good. Just see my comment.

Sorry I don't see your comment.

**Comment by phweyland** [comment]
Sorry, I haven't submitted ... (I don't know yet how to use this part).

**Comment by TurboGit** [comment]
@phweyland : In fact the whole SQL statement can be removed, see #4227.

**Pull request merged**
