### PR TITLE
CI: add jsonschema for validation on macOS

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by zisoft** [comment]
Is this really needed? `jsonschema` is deprecated for homebrew:

 > This formula has been deprecated since 2023-01-20 because it cli is deprecated, and will be removed

**Comment by kmilos** [comment]
> Is this really needed?

Yes, we'd like to see macOS failures e.g. here as well: https://github.com/darktable-org/darktable/actions/runs/4389742431

> jsonschema is deprecated for homebrew

It is deprecated everywhere. Someone would indeed need to update the entire dt build recipe for `check-jsonschema` instead for all platforms, this is just bringing macOS in line...

**Comment by victoryforce** [comment]
I do not see any practical benefit from this. Frankly speaking, it does not add any value to our CI process. jsonschema does not affect the functionality of the compiled application, it is only a verification of our json files. It is not necessary to run this verification for every build, it is optimal to run it for just one if possible. Verification failure in one runner is enough to cause CI to fail, why repeat the same thing multiple times?

In fact, it's even better to remove this verification from the build environments altogether and move it to server-side pre-commit hooks. Why run the check many thousands of unnecessary times, when we can ensure that incorrect files simply do not enter the repository.

**Comment by kmilos** [comment]
> Verification failure in one runner is enough to cause CI to fail, why repeat the same thing multiple times?

For the benefit of saving watts/time by cancelling unnecessary jobs. E.g. before we had "minimal" Linux tests in CI, and didn't run further if those failed.

> In fact, it's even better to remove this verification from the build environments altogether and move it to server-side pre-commit hooks. Why run the check many thousands of unnecessary times, when we can ensure that incorrect files simply do not enter the repository.

Totally agree, just no time/interest to implement this unfortunately.

**Comment by victoryforce** [comment]
But, on the other hand, such cases when someone creates PR with an incorrect json file are extremely rare. To save watts by stopping three jobs earlier in that one CI run, we spend time and watts checking files in thousands of other CI runs.

In short, it is difficult to find the optimal balance here. Since the server pre-hook will run verification only for the right type of files, it will optimize the verification costs.

**Review by TurboGit — APPROVED** [review]
Let's move forward, thanks!

**Pull request merged**
