### PR TITLE
make darkroom loading screen optional

### LINKED ISSUE #4085: darkroom 'loading image' message blanks screen
In darktable 2.6, I often made a couple of different edits in duplicate files and then was able to easily compare them by navigating between images (using space or backspace). In the current master build, a new 'loading page' has been added which essentially blanks the screen while the next image is being loaded and presents a 'loading image' message on-screen.

Unfortunately the blanking of the screen also blanks my memory of what was there before, meaning I now have to take a snapshot or exit into the lighttable to do any comparisons.

Please can it be changed back to the previous behaviour, i.e. so that the previous image remains on-screen until the next is loaded. The 'loading image' message is still helpful (so we know darktable is doing something) so should probably be retained.

### PR DESCRIPTION
**Pull request by elstoc**
Resolves #4085

Disable the preference to just use a toast log over the top of the image

### CODE REVIEW

**Comment by johnny-bit** [comment]
Yes, very much please. This solves pain point my wife and I have as described in https://github.com/darktable-org/darktable/issues/4085#issuecomment-745531514

**Comment by AlicVB** [comment]
For the record, this has been done on purpose to solve the following situation : you switch to a very big image (or any image that take time to load) which take, for example ,10 s. to load. With your setting to false, nothing happens in dt during this 10 s. which make the feeling that dt is "freezed"... and the same apply for smaller loading time too...

Now I perfectly see your use case, and making this optional can be a solution... maybe we can also add a message on screen like "next image currently loading..." in case one has put the option off ?

**Comment by elstoc** [comment]
> maybe we can also add a message on screen like "next image currently loading..." in case one has put the option off ?

In place of or as well as the "working" message that already appears?

**Comment by AlicVB** [comment]
I would say in place of... working message is already used for every pipe recompute. imho we need a specific message...

**Comment by elstoc** [comment]
we could use the same toast message that appears at the top of the screen when you use a dynamic shortcut.

**Comment by elstoc** [comment]
If I do this, do we need the grey screen any more or could this be the out-of-the-box solution without any preference?

**Comment by Nilvus** [comment]
> If I do this, do we need the grey screen any more or could this be the out-of-the-box solution without any preference?

Grey screen preference (in darktablerc file only) need to be kept I think, even with toast message. It's no big deal having it in darktablerc file.

**Comment by elstoc** [comment]
I'm fine with keeping the preference and will make it darktablerc only if there's a consensus but I much prefer visible preferences (in the prefs window)

**Comment by Nilvus** [comment]
> I'm fine with keeping the preference and will make it darktablerc only if there's a consensus but I much prefer visible preferences (in the prefs window)

I agree, but we need to be careful to not have too many settings in preferences as discussed already in #7050 and other places before.

**Comment by ralfbrown** [comment]
If the preference is made darktablerc-only, I vote to make the default "no gray screen".  Basically every other program keeps the current image on-screen until the next one is ready to display.

**Comment by AlicVB** [comment]
ok, I've redone some tests with big images, and anyway, in the current implementation, the "waiting" screen sometime takes 2 s. to be shown, so this don't fully answer the initial problem. (I've tried to force gui refresh without success)

I've tried you're last proposal here, and it's not so bad. I would have preferred a most obvious message position, like the one we use in lighttable, thought... do you think it's possible ?

**Comment by elstoc** [comment]
Well the other _easy_ one is `dt_control_log` which appears as a toast in the center of the screen. That message sticks around for longer though (has a longer timeout) because it's usually for displaying errors. I'm not familiar with other alternatives though so I'm not sure I'm qualified to comment.

The general use case for this mode is because people want to perform visual before/after comparisons without having to use the (imperfect) duplicates module or snapshots. In this case, the toast log being at the top of the screen generally keeps it out of the way of the image which is good imo.

**Comment by johnny-bit** [comment]
please don't use `dt_control_log`, since it's on the center. toast log is perfect imo :)

**Comment by AlicVB** [comment]
sorry, I've miss a part in my explanations. The idea for the message in the middle is in case we want to get ride completely of the current grey screen (or to make it not by default)... the proposal was just to find a compromise :)

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Pull request merged**
