### PR TITLE
Modified basecurve and tonecurve to increase similarity of interface

### PR DESCRIPTION
**Pull request by GrahamByrnes**
See #5491 

This PR modifies the code for basecurve.c and tonecurve.c so they now have

- the same option to vary the compression of the histogram;
- the scale of this is enlarged to include the linear option by going fully left;
- and so there is no use having the linear/log toggle, and I removed it.

Aside from that, there is a struct in tonemap.c that seems to store camera presets. I can't see what it's doing there, it seems to be more the role of basecurve... for the moment I haven't touched it.

Now to try to resolve some conflicts without screwing up...

### CODE REVIEW

**Comment by GrahamByrnes** [comment]
Arrgh... something going wrong in code that seems fine to me: `preserve_colors_callback` which I don't think I changed.

Might have to clear out my github and start again from a new repo.

**Comment by TurboGit** [comment]
@GrahamByrnes : Any news on this? Will you pursue the work on this or should it be closed?

**Comment by TurboGit** [comment]
@GrahamByrnes : No problem, I'm just slowly reviewing all stale PR marked for 3.4... No urgency, just ping me when this is ready. Thanks.

**Comment by GrahamByrnes** [comment]
There have been a lot of structural changes, ie the workflow variable, on top of the preservecolors etc... I think it might be easiest to close this, and then to start again.
I've been happily working with my fork from early July, so I'll need to get motivated again.

**Comment by TurboGit** [comment]
Understood, closing.

**Pull request closed without merging**
