### PR TITLE
Fix pugixml timestamp problem

### PR DESCRIPTION
**Pull request by LebedevRI**

### CODE REVIEW

**Comment by peterbud** [comment]
Works well as well in Windows with 1.8

**Comment by LebedevRI** [comment]
Yeah, something is strange, i'm thinking pugixml-1.8 homebrew formula is borked, but i have no way to prove it, or to check, really. Not sure why else it worked with 1.7 and fails with 1.8 (for homebrew only)
https://github.com/Homebrew/homebrew-core/commit/556a412cad8d1e2b9ac3b5b449551da2a40d0d18

**Comment by peterbud** [comment]
As I see they have turned on the new build flag BUILD_PKGCONFIG (which is good!)
https://github.com/Homebrew/homebrew-core/commit/556a412cad8d1e2b9ac3b5b449551da2a40d0d18#diff-a466161cd94499914fec86537d914681R22

That new flag is creating for the header files and for the static library a separate subdir, and also generates a PKGCONFIG file. The old FindPugi.cmake was not using pkg-conf at all, and tried to find the header files in the include dir with brute force.

**Comment by LebedevRI** [comment]
> PKGCONFIG

Yes, and this pr changes `FindPugixml.cmake` to actually use that pkg-config.
So i'm not sure why we end up with `Pugixml_LIBRARY` that contains invalid(?) lib, according to cmake:
```
+cmake --build /Users/travis/build/darktable-org/darktable/build -- -j2 -v
ninja: error: '/usr/local/Cellar/pugixml/1.8/lib/pugixml-1.8/libpugixml.a', needed by 'src/libdarktable.dylib', missing and no known rule to make it
+cmake --build /Users/travis/build/darktable-org/darktable/build -- -j1 -v -k0
ninja: error: '/usr/local/Cellar/pugixml/1.8/lib/pugixml-1.8/libpugixml.a', needed by 'src/libdarktable.dylib', missing and no known rule to make it
```

**Comment by peterbud** [comment]
Hmm `pugixml/1.8/lib/pugixml-1.8/libpugixml.a` ?
Normally the static library is installed `${PREFIX}/lib/pugixml-1.8/libpugixml.a`
seems `pugixml/1.8/` at the beginning like an error. 
But I have 0 experience on homwbrew/osx

**Comment by LebedevRI** [comment]
The file timestamp is the culprit, apparently.

**Comment by peterbud** [comment]
Nice catch. So homebrew takes the timestamp in the tarball to mark the compiled binaries? Learning every day.

**Comment by LebedevRI** [comment]
I guess it does make sense from deterministic/reproducible builds, as @houz suggested in IRC.

**Comment by LebedevRI** [comment]
@peterbud though the more important lesson here is what such null timestamps to to `ninja` and `ld`.

**Pull request merged**
