### PR TITLE
[noiseprofiles] Simplify noise profile json schema and clean-up of noise profiles

### PR DESCRIPTION
**Pull request by da-phil**
This is motivated by a previous fix in https://github.com/darktable-org/darktable/pull/7315 to make the CI checks on the noise profile JSON schema green again.

#### Proposed changes to noise profile JSON schema:
* Remove camera maker string min/max size attribute as we already enforce the usage of only specific enum values 
* Give a little bit more space (+5 characters) to camera model and camera model + ISO string to avoid this problem once a new camera model with a longer name appears
* Set `"minItems": 1` for camera maker / model and noise profile arrays

This PR also cleans up the following:
* Duplicated camera profiles
* Replace tab indentation by spaces

CC: @johnny-bit / @rawfiner / @chhil

### CODE REVIEW

**Comment by johnny-bit** [comment]
well, min/max items in array spec can imo be removed... or rather set min items to 1 (needs to have at least one noiseprofile to be valid) and since we require unique items AND enforce enum usage of makers there's no point in having max as anything outside enum will be killed and will be above max if all makers are present.

**Comment by da-phil** [comment]
> well, min/max items in array spec can imo be removed... or rather set min items to 1 (needs to have at least one noiseprofile to be valid) and since we require unique items AND enforce enum usage of makers there's no point in having max as anything outside enum will be killed and will be above max if all makers are present.

`minLength` / `maxLength` don't specify the array size, but the (camera maker) string size, see https://json-schema.org/understanding-json-schema/reference/string.html#id5, and this is already enforced by the possible enum values.

If we wanted to specify the min/max array size we would need to use `minItems` / `maxItems`, see https://json-schema.org/understanding-json-schema/reference/array.html#length 

I'd be fine to specify a `minItems: 1` for all the arrays: camera maker, camera model and profiles.

**Comment by johnny-bit** [comment]
Look at lines 125&126:
```json
      "minItems": 14,
      "maxItems": 14
```

change that too :)

**Comment by da-phil** [comment]
> Look at lines 125&126:
> 
> ```json
>       "minItems": 14,
>       "maxItems": 14
> ```
> 
> change that too :)

Ups, you're right, they were overlooked ;)
Would you agree with the changes to have only `"minItems": 1` as a constraint?

**Comment by johnny-bit** [comment]
Me? Yes. that's what I'd recommend.

**Comment by da-phil** [comment]
> Me? Yes. that's what I'd recommend.

Great, I think I figured out the json schema checking step which is run in the CI pipeline:
```
jsonschema -i data/noiseprofiles.json data/noiseprofiles.schema
```
This check should be green now.

**Comment by Nilvus** [comment]
Just be careful, this PR seems to remove DC-G95 noise profiles added this day by commit: 0c237c9e26143381b581291832d3731d8ba115a9

And as you can see, there's no conflict noticed here.

**Comment by da-phil** [comment]
> Just be careful, this PR seems to remove DC-G95 noise profiles added this day by commit: [0c237c9](https://github.com/darktable-org/darktable/commit/0c237c9e26143381b581291832d3731d8ba115a9)

Yes, it was a duplicate entry, that's why I removed it :smile:

**Comment by TurboGit** [comment]
> Yes, it was a duplicate entry, that's why I removed it smile

How was this possible is a mystery to me, I always check for previous entry but did miss this one today ! I probably made a typo in my grep :( Anyway I'll revert that right away. Thanks for catching !

**Comment by da-phil** [comment]
> > Yes, it was a duplicate entry, that's why I removed it smile
> 
> How was this possible is a mystery to me, I always check for previous entry but did miss this one today ! I probably made a typo in my grep :( Anyway I'll revert that right away. Thanks for catching !

It was my fault, I committed this duplicate noise profile because I also didn't watch out for it :sweat:  But at least I made up for it by removing it again, after I started to understand the darktable codebase better.
The `uniqueItems` JSON schema checker didn't find it because I modified the `comment` attribute to contain the whole github username of the noise profile contributer.

**Comment by TurboGit** [comment]
Manually merged in master, queued for 3.4.1.

**Pull request closed without merging**
