### PR TITLE
Early fallback to cpu path if cl tiling problems are evident

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
In current master we expect cl tiling code still to be faster than cpu code, this is **not** correct if cl device memory is pretty small and
- we have a large tiling.factor_cl
- there is a large tiling.overlap

This became evident with diffuse&sharpen but in fact is a general problem.
Existing code is at least often slower than cpu code.

But as reported in #11201 (comments by @da-phil) there are also artefacts or crashes i understood
as intel-driver related but i could reproduce such issues too on a 64GB-cpu 8GB-gpu system using the
recently introduced 'notebook' resourcelevel mode. So there might be more issues around.

This pr tests in cl pipeline very early if cl tiling will not work and if so uses cpu code instead.

### CODE REVIEW

**Comment by da-phil** [comment]
Thanks for further investigating this issue!
I applied your patch, but couldn't see the new debug message in my [log messages](https://github.com/darktable-org/darktable/files/8192380/with_opencl.txt), although OpenCL was activated. Or maybe I didn't use enough iterations in "diffuse or sharpen"?
In my case I used the "dehaze" preset with 12 iterations.

**Comment by jenshannoschwalm** [comment]
I my case i use a 50mix image and diffuse&sharpen with
Bildschirmfoto von 2022-03-06 15-11-28
giving this log
```
18.143010 [dt_dev_pixelpipe_process_rec] module `diffuse' uses cpu because of extremely small tiles 1, overlap 1024
51.307390 [pixelpipe_process] [full] using device 0
51.318959 [default_process_tiling_cl_roi] use tiling on module 'demosaic' for image with full input size 2872 x 2344
51.318969 [default_process_tiling_cl_roi] (2 x 1) tiles with max input dimensions 1760 x 2344
51.318971 [default_process_tiling_cl_roi] tile (0, 0) with 1451 x 2344 at origin [1876, 670]
51.337092 [default_process_tiling_cl_roi] tile (1, 0) with 1450 x 2344 at origin [3298, 670]
51.368637 [dt_dev_pixelpipe_process_rec] module `diffuse' uses cpu because of extremely small tiles 1, overlap 1024
```


BTW here is one example of bogus output without this pr as a proof there is something wrong with current tiling code - i will dig into this later anyway.
Bildschirmfoto von 2022-03-06 15-19-05

got this relevant -- clearly bad -- part in log
```
6.789120 [default_process_tiling_cl_ptp] use tiling on module 'diffuse' for image with full size 1447 x 1181
6.789133 [default_process_tiling_cl_ptp] (1447 x 1) tiles with max dimensions 1268 x 1269 and overlap 1024
6.789135 [default_process_tiling_cl_ptp] tile (0, 0) with 1268 x 1181 at origin [0, 0]
8.761124 [pixelpipe_process] [full] using device 0
8.816956 [default_process_tiling_cl_ptp] use tiling on module 'diffuse' for image with full size 1447 x 1181
8.817956 [default_process_tiling_cl_ptp] (1447 x 1) tiles with max dimensions 1268 x 1269 and overlap 1024
8.817978 [default_process_tiling_cl_ptp] tile (0, 0) with 1268 x 1181 at origin [0, 0]
9.889900 [pixelpipe_process] [full] using device 0
9.923907 [default_process_tiling_cl_ptp] use tiling on module 'diffuse' for image with full size 1447 x 1181
9.923921 [default_process_tiling_cl_ptp] (1447 x 1) tiles with max dimensions 1268 x 1269 and overlap 1024
9.923923 [default_process_tiling_cl_ptp] tile (0, 0) with 1268 x 1181 at origin [0, 0]
```

**Comment by TurboGit** [comment]
> i will dig into this later anyway.

In this PR or a separate one? Just asking to know if this PR is ready for review. TIA.

**Comment by jenshannoschwalm** [comment]
> In this PR or a separate one?

@TurboGit That will be another pr as i currently don't know exactly what sometimes goes wrong and why with tiling. There is certainly a problem with tiles being correctly aligned - at least this is evident for xtrans sensors (see #6517). Rounding error?

For this pr, i would like a review now :-) It's not only a bugfix but also about performance as in the tested cornercases cpu path would be faster.

**Review by TurboGit — APPROVED** [review]
Looks good, thanks!

**Comment by wpferguson** [comment]
My 24 second exports just went back to a minute. Even small tiles on a GPU are faster than the CPU

**Comment by jenshannoschwalm** [comment]
> Even small tiles on a GPU are faster than the CPU

Yes - unless
1. we have a large overlap and heavy memory load resulting from tiling_cl
2. available gpu mem is much smaller than cpu memory

See performance as in comment described at the top of this thread.

So - the check in the pr seems to be wrong, could you feedback your system please? Your result is also with d&s? Any special aspect of the image?

**Comment by wpferguson** [comment]
Mine is 400% slower with this

**Comment by wpferguson** [comment]
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| N/A   56C    P0    23W /  N/A |    550MiB /  3014MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1651      G   /usr/lib/xorg/Xorg                 29MiB |
|    0   N/A  N/A      7116      G   /usr/lib/xorg/Xorg                224MiB |
|    0   N/A  N/A      7463      G   /usr/bin/gnome-shell               45MiB |
|    0   N/A  N/A      7753      G   cairo-dock                          4MiB |
|    0   N/A  N/A      8985      G   /usr/lib/firefox/firefox           90MiB |
|    0   N/A  N/A     10837      G   ...RendererForSitePerProcess       16MiB |
|    0   N/A  N/A     12761      G   /usr/lib/firefox/firefox           67MiB |
|    0   N/A  N/A     13889      G   /usr/lib/firefox/firefox            1MiB |
|    0   N/A  N/A     14079      G   /usr/lib/firefox/firefox            1MiB |
|    0   N/A  N/A    145208      C   .../dttestperf/bin/darktable       46MiB |
+-----------------------------------------------------------------------------+
```

```
opencl=TRUE
opencl_async_pixelpipe=false
opencl_avoid_atomics=false
opencl_building_gpu0=-cl-mad-enable -cl-no-signed-zeros -cl-unsafe-math-optimiza
tions -cl-finite-math-only -cl-fast-relaxed-math
opencl_checksum=876204412
opencl_device_priority=*/!0,*/*/*/!0,*
opencl_library=
opencl_mandatory_timeout=400
opencl_memory_headroom=
opencl_memory_requirement=768
opencl_micro_nap=1000
opencl_number_event_handles=25
opencl_scheduling_profile=very fast GPU
opencl_size_roundup=16
opencl_synch_cache=active module
opencl_use_cpu_devices=false
opencl_use_pinned_memory=false
```

```
resource_default=512 32 128 700
resource_large=700 64 128 900
resource_small=128 16 64 400
resource_unrestricted=16384 1024 128 875
resourcelevel=unrestricted
```

A couple of the images were cropped, so the export times were less.  All of the images were from a Canon 7DmkII (18.8MB).

O/S Ubuntu 20.04.4 up to date with today's updates.

[hardware.txt](https://github.com/darktable-org/darktable/files/8200063/hardware.txt)

[test_results.zip](https://github.com/darktable-org/darktable/files/8200033/test_results.zip)
[117EOS7D2_D2_6182.cr2.xmp.txt](https://github.com/darktable-org/darktable/files/8200035/117EOS7D2_D2_6182.cr2.xmp.txt)

**Comment by wpferguson** [comment]
Quick summary of results 

```
grep pipeline\ process with_patch.txt 
69.633057 [dev_process_export] pixel pipeline processing took 62.841 secs (463.626 CPU)
83.967273 [dev_process_export] pixel pipeline processing took 13.666 secs (86.934 CPU)
205.087180 [dev_process_export] pixel pipeline processing took 120.256 secs (822.939 CPU)
292.373504 [dev_process_export] pixel pipeline processing took 86.246 secs (652.775 CPU)
304.616597 [dev_process_export] pixel pipeline processing took 11.339 secs (70.212 CPU)
453.916571 [dev_process_export] pixel pipeline processing took 148.456 secs (792.334 CPU)
655.692126 [dev_process_export] pixel pipeline processing took 200.233 secs (784.810 CPU)
673.431846 [dev_process_export] pixel pipeline processing took 16.835 secs (100.672 CPU)
780.562952 [dev_process_export] pixel pipeline processing took 106.217 secs (797.673 CPU)
887.110225 [dev_process_export] pixel pipeline processing took 105.671 secs (797.447 CPU)

grep pipeline\ process without_patch.txt 
21.510246 [dev_process_export] pixel pipeline processing took 13.272 secs (22.424 CPU)
29.427058 [dev_process_export] pixel pipeline processing took 7.261 secs (12.600 CPU)
76.271765 [dev_process_export] pixel pipeline processing took 45.963 secs (62.910 CPU)
105.126432 [dev_process_export] pixel pipeline processing took 27.776 secs (32.460 CPU)
111.959957 [dev_process_export] pixel pipeline processing took 5.891 secs (10.529 CPU)
143.940092 [dev_process_export] pixel pipeline processing took 31.153 secs (36.698 CPU)
175.981564 [dev_process_export] pixel pipeline processing took 31.173 secs (36.799 CPU)
187.146353 [dev_process_export] pixel pipeline processing took 10.291 secs (26.830 CPU)
219.489021 [dev_process_export] pixel pipeline processing took 31.432 secs (37.503 CPU)
251.608940 [dev_process_export] pixel pipeline processing took 31.220 secs (37.021 CPU)
```

**Comment by jenshannoschwalm** [comment]
Thanks @wpferguson for hinting me. Indeed you are absolutely right, the estimation introduced in this pr is wrong - too pessimistic. I worked on this last night - and will do more testing tonight again doing just a "safety belt" that is not guessing performance but just makes sure cl tiling is possible at all. So far tests are ok without rendering bugs.

**Pull request merged**
