### PR TITLE
Make natural tag sorting configurable

### LINKED ISSUE #16081: Incorrect tag sorting
### Describe the bug

If the interface language "English" was selected, then the list of tags in the tagging module is sorted as in the "english" screenshot.
If a different language was selected, special characters are not taken into account when sorting this list. I tried Deutsch and Russian ("deutsch" and "russian" screenshots).

english
english

deutsch
deutsch

russian
russian

### Steps to reproduce

1. Create some tags with/without leading special characters.
2. Select English (and then some other) interface language.
3. Restart darktable and open tagging module.

### Expected behavior

_No response_

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you obtain darktable from?

self compiled

### darktable version

4.7.0+227~g420bc453d7

### What OS are you using?

Linux

### What is the version of your OS?

Linux debian12 6.1.0-15-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.66-1 (2023-12-09) x86_64 GNU/Linux

### Describe your system?

_No response_

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by zisoft**
fixes #16081 

It seems that not everyone is comfortable with the natural tag sorting (#15983) so I now made it configurable in the preferences:

Bildschirmfoto 2024-01-13 um 11 21 02

### CODE REVIEW

**Comment by TurboGit** [comment]
If I understand correctly this is because an issue in a Glib routine. We already have quite a lot of preferences, so maybe not a good idea to have a new one. If a workaround a bug for the locale maybe we can add an hidden pref for the time being waiting for the upstream bug to be fixed.

**Comment by zisoft** [comment]
It is a toggle to disable the case-insensitive and natural sort. Couldn't imagine that anyone don't want it, so I'm absolutely fine with closing this PR.

**Comment by victoryforce** [comment]
@zisoft [Your advice](https://github.com/darktable-org/darktable/issues/16081#issuecomment-1889814531) to the feature requester was absolutely logical and correct. He justifies his desire by the fact that he wants to group together certain special tags in the list (names of people, names of cities). But this is what categories (hierarchical tags) exist for, the user should not abuse sorting and uppercase for this purpose.

**Comment by zisoft** [comment]
So we agree and I close this.

**Pull request closed without merging**
