### PR TITLE
topbar: rework menu to avoid issue with combobox

### LINKED ISSUE #12956: scrolling over filter hamburger popup "new filter" menu adds filters
Presumably since #12849 

1. click on the "hamburger" menu left of "filter" in the top toolbar.
2. move the mouse down to hover over "new filter" line
3. click to open the menu of available filters (this step is not necessary, but that's how I found out; this looks like a combo popup, so the next step seemed logical to me)
4. use the scroll wheel to scroll through the available filters. The popup gets messed up; it looks like it scrolls up, but what actually happens is that one by one the filters get added to the top bar (and removed from the menu)

Expected; scrolling could move the menu up or down as with other popups. Alternatively, scrolling could do nothing. Scrolling should not add items to the top bar.

### PR DESCRIPTION
**Pull request by AlicVB**
this fixes #12956 

this implement @dterrahe proposal by using combobox for individual filters and simple button to add new filter.

### CODE REVIEW

**Comment by Nilvus** [comment]
That fixes indeed #12956 but I don't like that new way. It's not obvious to click append, see a filter appears without knowing which one, then understand that this need to click on combobox menu of the new filter to set wanted one...

What I don't understand is why we can't have a combo to select directly filter wanted, like we already have (and of course without #12956 issue) for example on darkroom for adding new modules (or settings on QAP) by right-clicking on a tab. I do not suggest to use right-clicking here (even if it could also be an idea) but use same menu popup on filter menu. But maybe there's some Gtk limits I don't know.

**Comment by Nilvus** [comment]
Just a thing: it's good though to have a combo menu to change existing filter (that's a great improvement). The only bad way is adding a new filter.

**Comment by AlicVB** [comment]
> What I don't understand is why we can't have a combo to select directly filter wanted

because of the "scroll" issue :( That plus the fact that we can't (or at least *I* am not able to) use context-menu inside popup... I fear that it's a gtk limitation...



> Just a thing: it's good though to have a combo menu to change existing filter (that's a great improvement). The only bad way is adding a new filter.

Yes... and no :)
This has also some limitations : 
- this will prevent future "simple" reordering of filters with drag and drop
- you can't either reorder filters directly by changing their "type", as to avoid duplicate filters, the combobox only allow to select an "unused" type of filter. So if you want to change the order of filters 1 and 2, you have to set the type of filter 1 to a random value, then set type of filter 2 to the "old" filter 1 type, ... Not really great...

**Comment by AlicVB** [comment]
well in fact, bauhaus already has the needed feature to avoid the scrolling issue... So let's close this complex PR in favor to #13017 which is way more simple ;)

**Comment by Nilvus** [comment]
> > Just a thing: it's good though to have a combo menu to change existing filter (that's a great improvement). The only bad way is adding a new filter.
> 
> Yes... and no :) This has also some limitations :
> 
>     * this will prevent future "simple" reordering of filters with drag and drop
> 
>     * you can't either reorder filters directly by changing their "type", as to avoid duplicate filters, the combobox only allow to select an "unused" type of filter. So if you want to change the order of filters 1 and 2, you have to set the type of filter 1 to a random value, then set type of filter 2 to the "old" filter 1 type, ... Not really great...

I forgot the future reordering. Indeed, this will be better.

**Pull request closed without merging**
