### PR TITLE
iop_profile: take intent in account in profile info lookup

### PR DESCRIPTION
**Pull request by flannelhead**
Fixes https://github.com/darktable-org/darktable/issues/8160.

### CODE REVIEW

**Comment by flannelhead** [comment]
CI had some hiccups when setting up the tests...

**Comment by aurelienpierre** [comment]
Please hold on any color profile change, I'm currently rewriting the color conversions to use the same color framework everywhere (`colorin.c`, `colorout.c` and `iop_profile.c`). Basically I'm merging `iop_profile.c` into `colorspaces.c` and then we will be able to handle all conversions from C and from OpenCL from an high-level method that will switch to LittleCMS or internal handling when appropriate.

**Comment by flannelhead** [comment]
Ok, the rewrite sounds really good. Thanks for the notice.

> Also, once again, intent don't matter as long as we stay in unclipped floating point RGB pipeline. They only matter when going to (bounded…) uint formats.

Yep I know this now and have read through the relevant code, so I think I understand it. :) Anyway this PR addressed what seemed like a flaw that could've bitten if the `dt_ioppr_add_profile_info_to_list()` would be used in a certain use case involving bounded formats and several intents for the same profile. But let's get back to this after the rewrite if it's still relevant (though hopefully it isn't!)

**Comment by TurboGit** [comment]
Just a question, I do not see why is this needed ? A profile is anyway fully independent of the intent. The intent is a final choice to tell the process how to project the colors into a specific profile. Right?

**Comment by flannelhead** [comment]
@TurboGit consider the following: let's say we have a profile that actually has a LUT for the perceptual intent, thus it would be applied using LCMS2 in darktable. However let's say there are two different IOPs, IOP1 and IOP2. IOP1 wants to use this profile with the perceptual intent, IOP2 with the relative colorimetric intent (which doesn't require a CLUT as far as I can tell and might be equally well applied here). Now we would have something like

```
void iop1_process()
{
  // profile name would be really given as a parameter to the IOP
  dt_iop_order_iccprofile_info_t *my_profile_info = dt_ioppr_add_profile_info_to_list(DT_COLORSPACE_FILE, "myprofile.icc", DT_INTENT_PERCEPTUAL);
}

```

**Comment by TurboGit** [comment]
> a profile that actually has a CLUT for the perceptual intent

That was something I didn't know. So a CLUT may be targeted/prepared for a specific intent? That's new to me. I had always thought that a profile was fully independent of the intent.

**Comment by flannelhead** [comment]
@TurboGit yes, the XYZLUTs in profiles are intent-specific. The matter is discussed here: http://www.colorwiki.com/wiki/Color_Management_Myths_21-25#Myth_.2321:_There_are_perceptual_rendering_intents_available_when_converting_from_scanner.2Fcamera-.3Eworkspace_or_workspace-.3Eworkspace.
The absolute and relative colorimetric intents are implemented using just the matrix and possible tone response curves. Perceptual and saturation intents require a more elaborate color LUTs to define how out-of-gamut colors are mapped. E.g. in DisplayCAL one may opt in to generate perceptual and saturation LUTs which map from a selected source color space to the display color space.

Most of the time when one selects the perceptual rendering intent in a transform, relative colorimetric is actually used unless the target profile has a perceptual intent table. Elle's page has a quite nice discussion of this: https://ninedegreesbelow.com/photography/icc-profile-conversion-intents.html#srgb-perceptual-matrix-lut

**Comment by TurboGit** [comment]
@flannelhead : thanks for the clarifications, all clear now... learning everyday !

**Comment by TurboGit** [comment]
@flannelhead : Do we still need this? If so can you fix the conflict TIA.

**Pull request closed without merging**
