### PR TITLE
exif: improve unknown DNG illuminant handling

### LINKED ISSUE #10873: darktable 3.8.0 no longer recognizes embedded color matrix for DNGs produced by Kalpanika X3F -> DNG converter
**Describe the bug/issue**

darktable 3.8.0 reports a missing color matrix in DNGs produced from Sigma X3F raw files by the X3F Tools (Kalpanika).
With 3.6.1, such DNGs could still be opened and processed with reasonable colors.

**To Reproduce**

Convert a Sigma X3F to DNG with x3f_extract (Kalpanika, https://github.com/Kalpanika/x3f/releases).
Import and open resulting DNG in darktable. Error message notifies about missing color matrix, colors are way off.

**Expected behavior**

No error message, reasonable colors.

**Platform**

* darktable version : 3.8.0
* OS                : OSX 11.6.2 Big Sur 
* OpenCL installed  :  y
* OpenCL activated  : y

**Additional context**
The color matrices are actually present in the DNG (Color Matrix 1, Forward Matrix 1, Camera Calibration 1) but the Calibration Illuminant 1 is set to 0 (Unknown). If the Calibration Illuminant is set to e.g. D55 using exiftool, the file can be opened without error message and with usuable colors.
See screenshot of darktable thumbnails below (left: DNG with CalibrationIlluminant1 = unknown, right: set to D55 using exiftool)

grafik

### PR DESCRIPTION
**Pull request by kmilos**
Fixes #10873

Also covers all other known DNG illuminants w/ color correction matrices.

### CODE REVIEW

**Comment by kmilos** [comment]
@jenshannoschwalm Please review

@geni1105 Please test (or provide a link to a sample)

@TurboGit Although not a trivial change, can we consider for 3.8.1?

**Comment by jenshannoschwalm** [comment]
Looks good, unfortunately i have only a small number of images with "rare" illuminants so can't test thoroughly.

**Comment by kmilos** [comment]
Thanks. O also don't have an extensive test set. The regular case (A/D65) continues working as before, as does the "Daylight" one we fixed recently.

**Comment by aurelienpierre** [comment]
What is "daylight" ? Daylight is supposed to be a continuum from 3500 K to 8000 K.

**Comment by kmilos** [comment]
"Daylight" is defined in the Adobe DNG SDK as 5500K (as we recently established in https://github.com/darktable-org/darktable/pull/10851). It was not a fortunate choice for an enum description indeed.

**Comment by aurelienpierre** [comment]
Things like that make me wonder if Adobe's guys have the slightest idea of what they are doing.

**Comment by kmilos** [comment]
I think this is some legacy stuff from the early days of the DNG spec (I guess coming from most camera WB menu settings being nicely descriptive but meaningless in terms of precision), that unfortunately has to now be supported. More recent DNG spec recommendations are to sanely use explicit A/D65 etc.

**Comment by parafin** [comment]
I don't totally follow all the logic here, but I guess it looks fine.

**Comment by kmilos** [comment]
> I don't totally follow all the logic here

And I thought I made a good effort with the comments ;)

**Review by TurboGit — APPROVED** [review]
Let's go with that for 3.8.1 then. Thanks!

**Comment by TurboGit** [comment]
Merged in master and darktable-3.8.x branch.

**Comment by geni1105** [comment]
Tested and seems to work, no more error message and reasonable colors - thanks!

Example DNGs here https://www.dropbox.com/sh/vtuty3pdfirjtbj/AACBX4TQS3mQAXBkv3k1w5wZa?dl=0 
(not sure if this is right way to post examples, please advise)

One thing I noticed: 
- the xxx.X3F.DNG is directly as output from X3F Wrapper (Kalpanika), with DNG OpcodeList3 tag to correct for Merrill cameras' color vignetting - unfortunately not yet supported by darktable, but otherwise it opens fine.
- the xxx.X3F-1.DNG is from passing the Kalpanika DNG through Adobe DNG Converter, which applies the OpcodeList 3 tag directly to the "raw" pixels (through compatibility setting "ACR 4.6 and newer"). This image opens without error message as well, but shows weird colors?

**Comment by kmilos** [comment]
As this was about restoring functionality lost wrt the previous version, can you please confirm the behaviour with the two DNGs is the same in st 3.6.1?

**Comment by geni1105** [comment]
3.6.1 is the same, so the functionality is restored :-)

On both 3.8.0 and 3.6.1, the issue occurs when using the color calibration module (with WB set to "camera reference" in the white balance module). Switching off the color calibration module and setting WB "as shot" in the white balance module gives better colors, although that displays a crazy temperature value of 25000 K and some color cast (that can be mostly corrected with color balance RGB).

**Comment by kmilos** [comment]
Sounds like an issue that needs to be investigated separately then.

**Pull request merged**
