### PR TITLE
fix history export diff

### PR DESCRIPTION
**Pull request by phweyland**
makes consistent dt_exif_xmp_read_data_export() with dt_exif_xmp_read_data() in relation with history.

Related to #4355, but I cannot say that would solve it.

### CODE REVIEW

**Comment by johnny-bit** [comment]
"use of undeclared identifier 'iop_order_version'"

It seems you've forgot to initialize it in `dt_exif_xmp_read_data_export`?

**Comment by phweyland** [comment]
> "use of undeclared identifier 'iop_order_version'"
> 
> It seems you've forgot to initialize it in `dt_exif_xmp_read_data_export`?

Just forgotten to test ... :(

**Comment by phweyland** [comment]
> Related to #4355, but I cannot say that would solve it.

It works for me with that fix (using exiv2).

**Comment by johnny-bit** [comment]
For me it fixes #4355 (exiftool)

**Comment by TurboGit** [comment]
Thanks! Merged.

**Pull request merged**
