### PR TITLE
add style preview in lighttable & darkroom

### PR DESCRIPTION
**Pull request by TurboGit**
This is a rework of the tooltip on the styles lib in the lighttable and menu items in darkroom to display a preview of the style applied to the first selected picture.

### CODE REVIEW

**Comment by TurboGit** [comment]
This is now ready for integration. Here are how it looks...

In the lighttable over the style lib:

image

In darkroom, over the style menu:

image

**Comment by jenshannoschwalm** [comment]
Very nice!

**Comment by wpferguson** [comment]
I arrange my styles in groups, i.e. Watermark|Landscape Watermark|Portrait Watermark|None.  I imported some styles and the Watermark group was selected.  I imported some images, then clicked on one and darktable crashed.  

[darktable_bt_9DSEV1.txt](https://github.com/darktable-org/darktable/files/9911979/darktable_bt_9DSEV1.txt)


Let me know if you need anything else

**Comment by TurboGit** [comment]
@wpferguson : Should be fixed, thanks for testing.

**Comment by wpferguson** [comment]
@TurboGit tested against the style list I sent you.  Works for me :).

**Pull request merged**
