### PR TITLE
Windows package do not use appdata.xml

### PR DESCRIPTION
**Pull request by victoryforce**
Installing this file is simply not necessary for the Windows build.

### CODE REVIEW

**Comment by kmilos** [comment]
Not 100% sure, but perhaps we actually want to keep it if installing as a MSYS2 package (`-DBUILD_MSYS2_INSTALL=ON`) that is then a part of a Unix-like filesystem layout? (E.g. I have already `C:\msys64\ucrt64\share\metainfo\org.gnome.cantarell.metainfo.xml`...)

I agree that for standalone Windows installer it might not make sense, like the man pages neither for example...

**Comment by victoryforce** [comment]
> Not 100% sure, but perhaps we actually want to keep it if installing as a MSYS2 package (`-DBUILD_MSYS2_INSTALL=ON`) that is then a part of a Unix-like filesystem layout?

This is a metadata file that contains information for the software centers of the free software ecosystem. This file does not make any sense neither for the Windows platform nor for MSYS2 software distribution platform.

> (E.g. I have already `C:\msys64\ucrt64\share\metainfo\org.gnome.cantarell.metainfo.xml`...)

This is a packaging error, this file should not be here.

> I agree that for standalone Windows installer it might not make sense, like the man pages neither for example...

And even less sense. it will not be possible to view the man pages normally in Windows due to the missing viewing program. But these are at least text files from which you can get some information when viewing them as plain text (it's ugly to look at, but still). There is simply no use of metadata for Linux software centers in Windows.

**Comment by kmilos** [comment]
> This is a metadata file that contains information for the software centers of the free software ecosystem. This file does not make any sense neither for the Windows platform nor for MSYS2 software distribution platform.

IMHO MSYS2 is a free software ecosystem, and not unlike a Linux distribution (not talking about building standalone native Windows apps/installers here). Whether it needs all freedesktop.org aspects of it, I don't know...

**Comment by victoryforce** [comment]
> > This is a metadata file that contains information for the software centers of the free software ecosystem. This file does not make any sense neither for the Windows platform nor for MSYS2 software distribution platform.
> 
> IMHO MSYS2 is a free software ecosystem, and not unlike a Linux distribution

I did not claim that MSYS2 is not a free software ecosystem.

> Whether it needs all freedesktop.org aspects of it, I don't know...

Does MSYS2 have some sort of "App Store" where you can search for apps, read their descriptions, view screenshots, add or read reviews? If there is no, then the appstream metadata file is definitely of no use here.

**Comment by victoryforce** [comment]
So what can we do with this extremely simple PR that has been stuck for a month and a half? Since the change itself is very simple, the delay is obviously due to doubts about its correctness.

The only option to unfreeze this PR that I see: I can ask you, @kmilos, as the person who expressed his doubts about this change, to make a proper review. By review, I mean verifying the correctness of my claim that appdata.xml, which conforms to the Freedesktop AppStream specification, is not used by Windows software centers.

Although I understand that you may not be interested in this and you will not want to waste time on such research. Then, if there is no confirmation of my conclusion, then it seems to me that the most reasonable decision is to close this PR, since the efforts to prove its correctness are simply disproportionate to the benefit from it.

@TurboGit What is your opinion on this?

**Comment by kmilos** [comment]
Sorry Viktor, no time to look into this. I guess it's fine to remove it - no probs I see whatsoever for the installer, and we can always bring it back for the MSYS2 package if the need arises.

**Review by TurboGit — APPROVED** [review]
Looks good to me, thanks!

**Comment by TurboGit** [comment]
@victoryforce : We just need a conflict resolution on this. TIA.

**Comment by victoryforce** [comment]
> @victoryforce : We just need a conflict resolution on this. TIA.

Rebased.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
