### PR TITLE
Fixes to provide AppStream conformance

### PR DESCRIPTION
**Pull request by victoryforce**
All of these changes are required to ensure AppStream compliance and avoid validation warnings.

### CODE REVIEW

**Comment by victoryforce** [comment]
@TurboGit I would like to start work on AppImage packaging of darktable, and these fixes are requisite. Would it be possible to accept them in the near future?

**Comment by TurboGit** [comment]
@victoryforce : Can this wait a bit as it is for 4.4 I'd like to avoid merging stuff not for 4.2.1 at the moment. My plan is generally to wait 2 or 3 weeks after the release to start merging things for next major release. Hope this is ok by you.

**Comment by victoryforce** [comment]
@TurboGit I don't see what's wrong with having a darktable 4.2.1 release in distro-agnostic AppImage format. This fix is completely non-invasive, it just allows you to pass validation.

**Comment by TurboGit** [comment]
There is also changes in the global progress status reported to the user's DE. I'm not sure how safe this is, of course I can test but this is only on GNOME Shell, we may have issues on other DE.

**Comment by victoryforce** [comment]
> There is also changes in the global progress status reported to the user's DE. I'm not sure how safe this is, of course I can test but this is only on GNOME Shell, we may have issues on other DE.

It is precisely these changes in the code of src/control/progress.c are here to ensure that we will not have problems. If we look at the source code and [read the descriptions of the functions](https://wiki.ubuntu.com/Unity/LauncherAPI), we will see that the parameter to which we make changes is the _basename of the application's .desktop-file including the extension_. That is, the change in progress.c simply _reflects the change in the name of the desktop file_. __There are no other changes in the code__. I certainly expect that there will be a review and that this code will be tested, but I am absolutely sure that it is safe and that there will be no problems with DEs.

Now about the importance of this PR.

The quality of dt releases depends on how widely users have tested the program before the release. So to improve the quality of darktable releases, our main task is to increase the number of users who are willing to play with the new code. If we don't make it easy for them to install and run the program, we won't increase their numbers. We have periodic builds for the Windows platform advertised on pixls.us. It's good. However, most of our users use Linux, and Linux users are known to be the most active and enthusiastic about trying new things. The problem is only in the huge number of different distros and their releases and the impossibility of compiling dt for each of them with good quality. As a result, we currently have only those testers who are not deterred by the need to build the program themselves.

We can offer users fresh universal AppImage builds, but that would at least require us to fix an incompatible desktop filename that doesn't allow validation when creating an appimage.

I don't think there's any point in delaying this process for half a year.

**Review by TurboGit — CHANGES_REQUESTED** [review]
Ok, but then let's do full changes.

- `data/darktable.desktop.in` should be renamed `data/org.darktable.darktable.desktop.in`
- tools/darktable-gnome-nightlight-disabled.sh (one occurence in comment to fix)
- CMakeLists.txt - some occurences in comments and one in a message to be fixed
- po/POTFILES.in : should be changed to use `data/org.darktable.darktable.desktop.in`

**Comment by victoryforce** [comment]
I deliberately did not rename the template files to keep the changes to a minimum. OK, will make those changes hopefully later today when power will be restored.

BTW, if we'll change the name of the source template file to match the target .desktop file, then it is logical to rename the .appdata.xml template as well, not only .desktop template.

**Comment by TurboGit** [comment]
Merged in master & 4.2 branch. Thanks.

**Pull request merged**
