### PR TITLE
lens: fix roi_in computation

### PR DESCRIPTION
**Pull request by rawfiner**
With TCA correction, the coordinates of transformation from R, G, and B channels can be different.
Thus, we have to take all of them into account.
Partial fix for #8865. Makes the issue much less problematic: we can crop to eliminate the remaining fringes, while before this the fringes remained even after cropping (regardless of how much we cropped). And zoomed in, the fringes are no more visible.

### CODE REVIEW

**Comment by rawfiner** [comment]
I just thought on a way to fix the issue completely... So adding wip meanwhile. I will try that tomorrow

**Comment by rawfiner** [comment]
Second part of the fix: the index are restricted to [0, width[ and [0, height[.
Putting settings as strong as made possible by the module (probably not realistic), we can unfortunately (but logically) still see some artifacts on borders as several pixels will take the same pixel as source, but the artifacts are less disturbing than the previous one, and won't affect results of local average other modules may do later (contrary to setting the pixels to 0 value):
Capture d’écran du 2021-05-06 13-45-19
Note that I increased contrast and saturation to make the phenomenon more visible.

I don't know if there is a better way to fix this, at least it makes the issue much less problematic

**Comment by TurboGit** [comment]
@rawfiner : is that still wip ?

**Comment by rawfiner** [comment]
@TurboGit no, if this solution is ok for you we can consider this as no more wip

**Review by TurboGit — APPROVED** [review]
Ok, looks ok for 3.6, I didn't find issues/regressions. Thanks.

**Comment by rawfiner** [comment]
Thanks! :-)

**Pull request merged**
