### PR TITLE
Fix partial copy of large files on "import from camera".

### PR DESCRIPTION
**Pull request by orium**
This happened because `write()` makes no guarantees of writing everything that
was requested.  Apparently, in Linux, it doesn't write more than 2GB at a time,
but writing a file of any size is only correct if we keep calling `write()`
until everything is written.

Closes bug #11689.

### CODE REVIEW

**Comment by LebedevRI** [comment]
Is this on a 32-bit or 64-bit systems?

**Comment by orium** [comment]
> Is this on a 32-bit or 64-bit systems?

On 32-bit systems this will work for <4GB files.  This is because the gphoto library uses `unsigned long int` to represent file sizes, which will be 32 bits in 32-bit systems.

On 64-bit system this fixes the file truncation problem, because a `unsigned long int` will have 64 bits (well, the C standard only says "at least 32 bits", but in practice compilers use 64 bits).

A way to fully solve this, as well as avoiding high memory consumption (since files are completely loaded into memory), is to not depend on gphoto to read files.  It does load the entire file in memory just to get the exiv2 "datetime taken", which could be done by reading it directly from the file (the exiv2 library supports that).  We can then copy the file ourselfs and avoid the limitations of gphoto.

I will take a shot at this approach and if everything goes well I will update the PR.

**Comment by LebedevRI** [comment]
> On 32-bit systems this will work for <4GB files. This is because the gphoto library uses unsigned long int to represent file sizes, which will be 32 bits in 32-bit systems.

> On 64-bit system this fixes the file truncation problem, because a unsigned long int will have 64 bits (well, the C standard only says "at least 32 bits", but in practice compilers use 64 bits).

Fact: gphoto provides correct file size info, else nothing will work.

What i was really asking is, what about `-D_FILE_OFFSET_BITS=64` and it's friends?

> A way to fully solve this, as well as avoiding high memory consumption (since files are completely loaded into memory), is to not depend on gphoto to read files.

Do you propose to implement all the camera operations ourselves?
Because currently libgphoto does all the talking and we can simply use it to get the data.

> It does load the entire file in memory just to get the exiv2 "datetime taken",

The file is already in the memory, because we are going to write it onto disk.
Or does the libgphoto provide a functionality to not read the file into memory, but directly save it into provided filename? But still, i bet internally it will still fullly read it into the memory.

> which could be done by reading it directly from the file (the exiv2 library supports that).

Sure.

> We can then copy the file ourselfs and avoid the limitations of gphoto.

Copy from where? How?

> I will take a shot at this approach and if everything goes well I will update the PR.

You are talking about two (three?) different issues here:
1. darktable truncates large files when copying them from gphoto
2. gphoto fully reads the file into memory, we then parse that buffer for the timestamps, and save onto disc
   * **If** gphoto can save the file directly, **and** avoid huge memory usage, **then** and only then we could use exiv2 to get the timestamps from the file from disc.

Do note `*If** gphoto can save the file directly`. If it can not, then the second part of your comment is a moot point.

**Comment by orium** [comment]
> A way to fully solve this, as well as avoiding high memory consumption (since files are completely loaded into memory), is to not depend on gphoto to read files. It does load the entire file in memory just to get the exiv2 "datetime taken", which could be done by reading it directly from the file (the exiv2 library supports that). We can then copy the file ourselfs and avoid the limitations of gphoto.
>
>I will take a shot at this approach and if everything goes well I will update the PR.

Nevermind.  We need gphoto to read the file from the camera, since the camera fs doesn't need to be mounted.

**Comment by LebedevRI** [comment]
> Nevermind. We need gphoto to read the file from the camera, since the camera fs doesn't need to be mounted.

That is the whole point of `import from camera` :)

**Comment by orium** [comment]
If we accept that "gphoto provides correct file size info" then we accept that 32-bit system truncate file sizes to 4GB and this is the candidate PR.

The memory consumption problem however could be solved in a couple ways:

1. Gphoto has a way to read chucks of a camera file, so this could be used to solve the memory problem and the 4GB file size problem on 32bit (the `gp_camera_file_read()` that can read parts of a file uses `uint64_t`).
However, the final filename depends of the exiv "datetime taken", so we would need to copy it somewhere first, then read the exiv "datetime taken", then move the file to right place.
2. Alternatively I can (maybe?) implement a `Exiv2::BasicIo` that actually knows how to read from a camfile, again by using `gp_camera_file_read()`, and with this we can read the exiv data directly from the camfile.  (atfer a quick looking at the `Exiv2::BasicIo` interface some stuff doesn't map very nicely...)

Either way, we can ignore the memory problem for now...

**Comment by LebedevRI** [comment]
1. 32-bit systems are practically not supported anyway.
2. Let's not mix apples and parrots here. If this is about file truncation, then don't turn it into something else
3. Using that functionality to import something that is completely unrelated to darktable (videos) is a total abuse.
   We should either implement black/white -lists of file extensions / MIME types.
   Or kill that whole functionality completely.
   Seriously.

**Comment by orium** [comment]
> Using that functionality to import something that is completely unrelated to darktable (videos) is a total abuse.
> We should either implement black/white -lists of file extensions / MIME types.

I'm happy with that.  Anyway, this how a data should be written with `write()`.  We always have to check and loop if there is still stuff that wasn't written.

**Comment by LebedevRI** [comment]
> Anyway, this how data should be written with write(). We always have to check and loop if there is still stuff that wasn't written.

Yes.

**Comment by orium** [comment]
Anything needed to be done to merge this?

**Comment by LebedevRI** [comment]
Right, sorry.
I'm not really familiar with multi-gb file writing.
So what about `_LARGEFILE_SOURCE` / `_LARGEFILE64_SOURCE` / `_FILE_OFFSET_BITS` macros?
Are they unrelated? Or is the current diff the right fix?

**Comment by orium** [comment]
> So what about _LARGEFILE_SOURCE / _LARGEFILE64_SOURCE / _FILE_OFFSET_BITS macros?

These macros allow you to use a 64-bit interface for writing/reading/etc in 32-bit systems.  In 64-bit system they will do nothing.  However, in 32-bit system we already have the gphoto limitation of using a 32-bit var to hold the size, so it doesn't help there.

(However even if these macros helped we would still need to `write()` to the file in the way that this PR does.  See below.)

> Are they unrelated? Or is the current diff the right fix?

You can see this PR as a "fix for `write()ing to files correctly`".  It also fixing the 2GB limit on 64-bit systems is a side-effect.  In practice the `write()` worked fine before because the linux kernel is nice enough to make `write()` not return prematurely (e.i. without writing everything) for chunks of data less than 2GB, but it could do so and still be POSIX complient.

Maybe it is even possible for `write()` to only write, say, a few bytes, if it gets a interrupt in the wrong time or something like that.  If that is possible than darktable might truncate small files if you are really unlucky.

**Comment by LebedevRI** [comment]
Some additional considerations to be had, from irc:
```
[20:49:12] <LebedevRI> (what about the pr though)
[20:53:26] <houz> reading man 2 write i see some more cases that we might want to deal with, for example ret == -1 and errno == EINTR -- should we try again?
[20:54:47] <houz> and if i understand the man page correctly, on a full disk write may reutrn 0 which will send dt into an infinite loop
[20:55:04] <houz> not sure if we can handle that though
[20:55:49] <houz> and if we got an error, should we unlink the file we wrote to?
```

**Comment by orium** [comment]
> <houz> reading man 2 write i see some more cases that we might want to deal with, for example ret == -1 and errno == EINTR -- should we try again?

Yes, we  should.  Will update PR.

> <houz> and if i understand the man page correctly, on a full disk write may reutrn 0 which will send dt into an infinite loop

It will not return zero in this case.  It will return <0 and set `errno` to `ENOSPC`:

> If  a  write()  requests  that more bytes be written than there is room for (for
example, the file size limit of the process or the physical end  of  a  medium),   
only  as  many bytes as there is room for shall be written. For example, suppose   
there is space for 20 bytes more in a file before reaching a limit. A  write  of   
512  bytes  will  return  20. The next write of a non-zero number of bytes would   
give a failure return (except as noted below).
>
> ERRORS
>
>        ENOSPC There was no free space remaining on the device containing the file.

In fact, [`write()` should not return zero for non-zero sized `write()s`](https://stackoverflow.com/questions/41904221/can-write2-return-0-bytes-written-and-what-to-do-if-it-does#41970485).

**Comment by houz** [comment]
> On  success, the number of bytes written is returned (zero indicates nothing was written).  It is not an error
       if this number is smaller than the number of bytes requested; this may happen for  example  because  the  disk
       device was filled.

This sounds as if 0 could be returned.

**Comment by orium** [comment]
> On success, the number of bytes written is returned (zero indicates nothing was written).

I think this only happens if we ask `write()` to write 0 bytes.

> It is not an error if this number is smaller than the number of bytes requested; this may happen for example because the disk device was filled.

I think this is talking about >0 number of bytes.  As I said in the quote in my previous comment if there is only 100 free bytes in the FS and you ask `write()` to write 200 bytes it will return `100` and subsequent calls to `write()` will return <0 and `errno` will be set to `ENOSPC`.

See the SO link in my previous comment.

**Comment by LebedevRI** [comment]
(BTW, we *can* detect infinite loops, by checking some bool flag, and if not set, setting it, and only then writing.)

**Comment by orium** [comment]
From what I can see `write()` returning zero is not a thing in POSIX-compliant system (see [this](https://stackoverflow.com/questions/5656628/what-should-i-do-when-writefd-buf-count-returns-0/5656787#5656787) and [this](https://stackoverflow.com/questions/41904221/can-write2-return-0-bytes-written-and-what-to-do-if-it-does#41970485)).

Also, if we look at the gnulib `full_rw()`, which is the code used by the GNU coreutils `cp`, we can see that [they handle the case where `write()` returns zero](https://github.com/coreutils/gnulib/blob/master/lib/full-write.c#L45) but only because:

```
/* Some buggy drivers return 0 when one tries to write beyond
   a device's end.  (Example: Linux 1.2.13 on /dev/fd0.)
   Set errno to ENOSPC so they get a sensible diagnostic.  */
```

**Comment by houz** [comment]
Fair enough, no 0 then. 😄

**Comment by orium** [comment]
Alright!

Anything else before landing this puppy?

**Comment by houz** [comment]
This looks sane. We just have to decide if it would make sense to delete files that were only partially copied.

**Comment by orium** [comment]
> We just have to decide if it would make sense to delete files that were only partially copied.

Maybe we should.  Updating PR...

**Comment by orium** [comment]
Ping.

(Note that travis didn't build on macOS for some reason...)

**Comment by orium** [comment]
Just a reminder to close https://redmine.darktable.org/issues/11689

**Pull request merged**
