### PR TITLE
Enable accelerators for sliders in iop modules

### LINKED ISSUE #3482: [Feature] Basic adjustment module : enable dynamic (key+mouse) accels
HI all !

I love the new Basic Adjustment module (#2168), and use it to adjust :
* Black level
* Exposure
* Contrast
* Brightness
* Saturation
* Vibrance to come in #3121

image

I would really love to be able to set Dynamic shortcut for each of those entries so that I can adjust them using accels, i.e. a simple keypress + mouse scroll U/D without having to go on the sliders in the module.

image

(This FR could probably apply to maaaany modules ;) )

Thanks
GLLM

### PR DESCRIPTION
**Pull request by dterrahe**
Closes #3482 (which is specifically for the basic adjustments module.

I've defined accelerators for all other modules that didn't have them, but often they don't seem to work (haze removal, global tonemap, denoiseprofile, defringe, colorzones, colorchecker, bilat). 

There were also modules where the definitions were already there, but deactived with a "#if 0 // BAUHAUS doesn't support keyaccels yet..." line. And indeed, after removing the line, the accelerators didn't work (channel mixer, highpass, velvia, vibrance). 

Except in the case of "grain" which had deactivated accelerators that worked fine after they were reenabled.

I have tried to find out what the difference between working and non-working modules is, but have not yet been able to spot it. Any help on what "BAUHAUS doesn't support keyaccels yet..." refers to (since sometimes it clearly does work) would be welcome. Otherwise a deep debug will be needed.

### CODE REVIEW

**Comment by dterrahe** [comment]
For the modules where the accelerators don't work, connect_key_accels does not get called on the switch to darkroom. If the module is added to favorites, it then suddenly works. Even if it then gets removed (and then it still works after switching out and back into darkroom).

This code in darkroom.c suggests something interesting in the initialisation of module->so->state. 
```
   if(module->so->state != dt_iop_state_HIDDEN)
    {
      if(module->connect_key_accels) module->connect_key_accels(module);
      dt_iop_connect_common_accels(module);
    }
```
but just removing the conditional doesn't fully resolve the problem and I'm not sure what a HIDDEN state is supposed to achieve, so don't want to mess with this...

**Comment by kbarni** [comment]
Here's a patch to add accelerator for the upcoming *vibrance slider* in the *Basic adjustments* iop (pull request https://github.com/darktable-org/darktable/pull/3599).
I prefer to submit a patch to make it easier to merge both requests. 
(This won't work at the moment as the `sl_vibrance` variable is not declared in this branch yet).

[vibrance-accel.patch.txt](https://github.com/darktable-org/darktable/files/3904839/vibrance-accel.patch.txt)

**Comment by dterrahe** [comment]
Thanks!
I saw your addition and was going to keep an eye out to see which one got merged first; then the other can apply this patch. I'm not enough of a git guru to know if there is a way to officially support this kind of 2-way dependency :-)
    On Friday, 29 November 2019, 10:52:11 GMT, kbarni <notifications@github.com> wrote:  
 
 
Here's a patch to add accelerator for the upcoming vibrance slider in the Basic adjustments iop (pull request #3599).
I prefer to submit a patch to make it easier to merge both requests.
(This won't work at the moment as the sl_vibrance variable is not declared in this branch yet).

vibrance-accel.patch.txt

**Comment by TurboGit** [comment]
Can you fix the conflict ? Thanks!

**Comment by dterrahe** [comment]
In Github Desktop (under windows) errors in the pre-commit script prevent me from committing a very simple merge conflict resolution. I've tried to fix it manually in vscode and git command line under linux, but it seems I've made a mess of it that I have no idea how to resolve. Can you work with this or should I start from scratch?

**Comment by TurboGit** [comment]
Have you added explicitly the files that were on conflict?

**Comment by dterrahe** [comment]
Not sure what you mean. There was a formatting change in the first line _after_ my change in colorzones.c I've committed a merge resolution that includes that change. But I seem to have done several merges to get up to date that now show up in this merge request above (I did not really make changes to 29 files). And it looks like the formatting change has been reverted when I intended to accept it in my merge...

**Comment by TurboGit** [comment]
You have merged master into your branch and this is the wrong decision. You should have rebased your branch on top of master.

**Comment by dterrahe** [comment]
Yep, I figured that out. I'm still a git/github novice and rebase gave an error because of the merge conflict that I didn't know how to resolve.

Anything i can do now to fix this or should i start with a fresh branch and cherry pick my commits? And then submit a new pull request?

**Comment by TurboGit** [comment]
> Yep, I figured that out. I'm still a git/github novice and rebase gave an error because of the merge conflict that I didn't know how to resolve.

- edit file reported with merge conflicts and fix it
- do a : git add <fixed-file>
- do a : git rebase --continue

And repeat until there is no more conflicts and you are back to the top of your branch.

**Comment by dterrahe** [comment]
I think it looks ok now, after a force-push

Now that #3599 has been merged, I have also included the patch provided above.

**Comment by TurboGit** [comment]
Thanks! I'll have a look at this tomorrow.

**Comment by TurboGit** [comment]
Thanks merged!

**Comment by TurboGit** [comment]
Merged in master and 3.0.1.

**Pull request merged**
