### PR TITLE
slideshow : better handling of shortcuts

### PR DESCRIPTION
**Pull request by AlicVB**
This should solve most part of recent shortcuts issues with slideshow.
What it does : 
1. use `key_pressed` instead of `key_released` inside the view, because key_pressed event are not triggered if a "global" shortcut is associated with the key.
So this avoid to make exception for all global shortcuts (borders, fullscreen, help window, ...)
Currently, if you press a global shortcut not handled by an exception in slideshow, this exit the slideshow AND apply the shortcut. Example, if you type `H`, you see the help window and exit slideshow, same with `ESC` : exit fullscreen AND the slideshow...
2. in order to make exit more discoverable, I've also implemented an exit by retyping the view shortcut (`S` here). I've done that for all view, as imho, it would be handy. But that can be discussed...

### CODE REVIEW

**Comment by TurboGit** [comment]
This does not work as now you can't use shift to type the + sign (above the = on a French keyboard) as the shift is interpreted as soon as pressed. That's the problem with key_pressed and why I have moved the handling the the key_release some time ago.

**Review by TurboGit — CHANGES_REQUESTED** [review]
this broke the use of modifiers shift or ctrl.

**Comment by AlicVB** [comment]
OK, now I understand better your first fix, I somehow miss its goal...
What I've done in last commit is to explicitly ignore modifiers key in key press, so we can only take care of "real" key press.
The only drawback is that you can't use anymore shift keys to navigate through images like before, you have to use arrows. But anyway using shift keys here wasn't a good idea, as it prevent the use of some key value on some keyboard layouts : example for french keyboard, to type + without the numpad, you have to press Shift+= ...

**Comment by TurboGit** [comment]
Thanks !

**Comment by quovadit** [comment]
@AlicVB : I'm not convinced of this change, because now it's not possible anymore to quit slideshow by pressing ESC.
I know that ESC already quits fullscreen-mode, but for me it's the most intuitive key possible to get out of a (nearly) fullscreen mode like the slideshow.

**Comment by AlicVB** [comment]
@quovadit : yes, I know it's the ideal, but the previous state was really buggy too and I'm even surprised that we don't get issues with it... having shortcuts that change thing in the middle of view change...
The best I can propose for you is to remove the shortcut for exiting fullscreen (you can still use F11) then, as ESC will be unused, you should exit exit slideshow with this key...

**Comment by quovadit** [comment]
@AlicVB : sounds good for me - thanks

**Pull request merged**
