### PR TITLE
[metadata_view]: correctly handlne invalid utf in strftime

### LINKED ISSUE #5892: No timestamps are displayed on Windows
No timestamps are displayed on Windows (but they are present in the db)

timestaps in windows 7

Darktable Version: master
OS: Windows 7 Pro

### PR DESCRIPTION
**Pull request by johnny-bit**
This is imo the correct way to fix #5892 

This is an alternative to #6262 

Selling points: no memory leaks, error handling :) if string is utf-8 compatible there's no burned cpu cycles :)

### CODE REVIEW

**Comment by parafin** [comment]
You didn't get all of them, so it still crashes for me. Check line 547.

**Comment by parafin** [comment]
As for why I get hieroglyphs - it seems to be one of those wonderful locale problems on macOS - if I set LC_ALL=C, then everything looks good (in English). So let's ignore that for now, maybe I'll get around investigating it sometime (or better yet someone else).

**Comment by johnny-bit** [comment]
I'll fix it in a bit (line 547) - as for hieroglyphs it still should in case of utf8 conv problems complain or if there are no complaints, those hieroglyphs are valid utf-8 and strftime may have invalid locale indeed...

**Comment by johnny-bit** [comment]
Fixed. Can you please check if it doesn't crash now? should cover all timestamps now :)

**Comment by parafin** [comment]
Doesn't build now:
```
/Users/parafin/src/darktable/src/libs/metadata_view.c:545:65: error: incompatible pointer types passing 'struct tm *' to parameter of type 'const time_t *' (aka 'const long *') [-Werror,-Wincompatible-pointer-types]
      _metadata_update_timestamp(d->metadata[md_exif_datetime], &tt_exif);
                                                                ^~~~~~~~
/Users/parafin/src/darktable/src/libs/metadata_view.c:225:71: note: passing argument to parameter 'value' here
static void _metadata_update_timestamp(GtkLabel *label, const time_t *value)
                                                                      ^
/Users/parafin/src/darktable/src/libs/metadata_view.c:540:12: error: unused variable 'datetime' [-Werror,-Wunused-variable]
      char datetime[200];
           ^
2 errors generated.

```

**Comment by johnny-bit** [comment]
Arght. Wrong branch built + rush :D Now should be good + properly tested :)

**Comment by parafin** [comment]
Works now. I've also found a workaround for hieroglyphs. It seems setlocale on macOS is kind of (or totally) broken.

**Comment by parafin** [comment]
BTW that workaround fixes the crash also, so this PR isn't required:)) But probably a good idea nonetheless.

**Comment by johnny-bit** [comment]
At least it fixes memleaks (really, the mem would leak like crazy) + technically it only does utf8 conversion when absolutely needed so that's another plus and it even shows when conversion has problems :D

Anyway - Ready for review and merging :)

**Comment by TurboGit** [comment]
It probably also fixes #4088.

**Review by TurboGit — APPROVED** [review]
All good to me! Thanks.

**Pull request merged**
