### PR TITLE
Implement webkitgtk for oAuth like logins

### PR DESCRIPTION
**Pull request by jcsogo**
This PR will implement a very simple common webauth framework based on webkitgtk that can be used by the export modules to get oAuth authentication. Right now only facebook module is using it. This module wasn't working now because of the changes introduced by facebook that made impossible for the user to paste back the URL with the required token in our dialog.

### CODE REVIEW

**Comment by parafin** [comment]
Seriously? DT will link against full-blown browser engine?

**Comment by hanatos** [comment]
well i'm sure i won't link against it in my build :)

what's with all the files with funny endings? (.c.old, .c.orig, .c.roi)

**Comment by jcsogo** [comment]
@parafin this is the only way to support facebook right now. This or we drop support for it. You can of course decide not linking it to webkit and you won't have it.

@hanatos sorry about those files, I used an old copy of the repo and forgot about those when doing the initial commit. Already fixed in the code (rebased)

**Comment by LebedevRI** [comment]
For the record, i *highly* do not like this at all.
I vote for just dropping fb export.

**Comment by hanatos** [comment]
+1

**Comment by parafin** [comment]
If this PR is the only solution, then +1 from me.

**Comment by pedrocr** [comment]
I agree with dropping if we have to do this. As discussed on IRC asking the user to input his facebook user/password into a window we control is completely broken when it comes to security.

What was discussed on IRC was that we could do something nicer by doing the redirect to http://localhost:$SOMEPORT and use that page to capture the data we need and tell the user "This is all done please close this tab and go back to dt". This would require us to add a HTTP endpoint to dt which is just a few lines of libsoup (which apparently we already depend on).

**Comment by LebedevRI** [comment]
So is there another way?

**Comment by pedrocr** [comment]
@houz was interested in looking into the localhost redirect method, don't know if he actually tried it though...

**Comment by houz** [comment]
I wouldn't know how to do that without a Facebook account and access to the app settings.

**Comment by jcsogo** [comment]
I am asking right now for the app to be transferred to us/darktable
facebook page. Let's see when this is done.

On Tue, Jan 27, 2015 at 11:41 AM, houz <notifications@github.com> wrote:

> I wouldn't know how to do that without a Facebook account and access to
> the app settings.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/darktable-org/darktable/pull/825#issuecomment-71624771>
> .
>



-- 
José Carlos García Sogo
   jcsogo@gmail.com

**Comment by boucman** [comment]
mentionning @chubinou so he is aware of this...

**Comment by houz** [comment]
No longer needed, we have an HTTP server now.

**Pull request closed without merging**
