### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S *.po,*.pot,./src/external,./src/common,./data/pswp -L ba,bloc,dinamic,hist,ist,inout,uint,ue,webp
`

### CODE REVIEW

**Comment by elstoc** [comment]
You might want to consider breaking this into two pull requests, since one of these changes (to `geotagging.c`) is not suitable for 3.8 (as it changes a translated string).

IMO the changes to the comments  and README could either be for 3.8 or 4.0 but obviously the changes to the release notes only make sense for 3.8.

**Comment by luzpaz** [comment]
guess we wait till the next release then

**Comment by TurboGit** [comment]
> guess we wait till the next release then

Ok, so I'll set back to release 4.0

**Comment by elstoc** [comment]
:) looks like you went through exactly the same thought processes as me

**Comment by TurboGit** [comment]
But I have found just after merging that the change in `packaging/macosx/gtk-mac-bundler-0.7.4.patch` was wrong as we cannot change a line in a patch otherwise it won't apply. So I have now reverted this part.

**Comment by luzpaz** [comment]
sorry about the `.patch` file :face_exhaling:

**Pull request merged**
