### PR TITLE
Add missing mutex init for darktable-cli

### PR DESCRIPTION
**Pull request by victoryforce**
The added mutex initialization should fix the issue with `assert()` being triggered by EINVAL error code returned by `pthread_mutex_lock()`.

Also removed the forced successful completion from the CI step, as there should be no job failure issues after this fix.

### CODE REVIEW

**Comment by zisoft** [comment]
The forced successful completion can be removed from nightly.yml as well.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by TurboGit** [comment]
Do you think we need a release notes entry for this? If so, can you provide one? TIA.

**Comment by victoryforce** [comment]
This issue was not visible to users. A normal user can run darktable-cli, of course, but it's hard to imagine a user doing that in a Debug build. And in non-Debug builds this problem does not affect the result in any way and is therefore invisible to users.

Therefore, in my opinion, an entry in the release notes for this is unnecessary.

**Pull request merged**
