### PR TITLE
export metadata - replace fixed tag list by exiv2 list 

### PR DESCRIPTION
**Pull request by phweyland**
Replaced the hard coded metadata list by an exiv2 standard one.

### CODE REVIEW

**Comment by phweyland** [comment]
Retrieving more metadata from exiv2 brings some data type which are not covered today like Rational or SRational types. Some more work must be done at least to prevent to fulfill a tag with not coherent values.

**Comment by phweyland** [comment]
adding metadata exiv2 type information

**Comment by phweyland** [comment]
Some variables like $(EXIF_APERTURE) are not suitable to set up the metadata tag Exif.Photo.ApertureValue which a RATIONAL (two longs) as commented in that thread https://discuss.pixls.us/t/darktable-3-0-exif-on-export/15486.

I've worked on the exiv2 metadata types (which are now visible in the metadata tag dictionary) but it seems difficult to convert properly the variables to such metadata. Except other argument I don't plan any work on this.

However in the same thread it appears useful to be able to remove all exif tags except some. Here comes the last commit which adds the possibility to enter '=' in the formula. This says that, despite exif tags are disabled, such a tag has to be exported.

image

The metadata tag dictionary looks now like that:
image

**Comment by phweyland** [comment]
3.2... end of the year. :(

**Comment by TurboGit** [comment]
@phweyland : Don't be sad, it's an open project we can discuss everything. I put 3.2 because I feel this could wait but we can reconsider. Maybe for 3.0.1 or 3.0.2 ?

**Comment by phweyland** [comment]
There are 2 points in that PR.
I had left the first one on the to do list. That's the title of the PR.
The second one comes from an issue faced by a user for a use case I hadn't considered (do not export exif except some of them), issue #3944.
There is not urgency, but there is no more reason to wait. 
If not an issue for you, 3.0.1 would be fine.

**Comment by TurboGit** [comment]
Manually merged on master and 3.0.1 branch.

**Pull request closed without merging**
