### PR TITLE
documentation for haze removal module

### PR DESCRIPTION
**Pull request by rabauke**
I wrote some documentation for the haze removal module. There is a minor issue with the included figure. Fonts are rendered slightly differently on my computer compared to the screenshots in the existing documentation. At the moment I have no idea how to fix this.

### CODE REVIEW

**Comment by upegelow** [comment]
> Fonts are rendered slightly differently

Most screenshots in the manual come from my system and I'm using `font: DejaVu Sans Regular 8;` in darktable.css. I can take care that the screenshot fits to the others after merging.

A suggestion: although the module does a great job (I used it on several images recently with nice results) users should be warned that taking out all atmospheric perspective from an image might render their images flat.

**Comment by rabauke** [comment]
@upegelow I would highly appreciate if you care for the screenshot. Not only the font also the icons look slightly smaller on my system compared to the screenshots in the rest of the documentation.

I slightly updated the documentation. I contains the following statement: _Setting both controls to unity maximizes the amount of haze removal but this is also likely to produce some artifacts. Removing the atmospheric light entirely may render the image flat and may result in an unnatural looking style. Optimal values are typically slightly below unity and are rather image dependent but are also a matter of personal aesthetic preferences._ I think this should be warning enough. The former version did contain a similar but weaker wording.

Heiko

**Comment by upegelow** [comment]
Cool.

> Optimal values are typically slightly below unity 

So my mileage varies here :) Don't know if this depends on the camera or my overall history stack but on my images (mostly Fuji, some Canon) I typically stay with strength values about 0.3 and distance about 0.04. In my eyes higher values lead to an unnatural look.

**Comment by rabauke** [comment]
@upegelow As I already wrote, it is _also a matter of personal aesthetic preferences_. Nevertheless, I think the word _slightly_ may be inappropriate here. It has been removed.

Heiko

**Pull request merged**
