### PR TITLE
[iop] add option to prompt rename on new instance 

### LINKED ISSUE #9644: FR: A new Preference under darkroom/modules
I've been playing around a lot with second instances of some modules, and when I do, I always rename the module to indicate what that instance is doing.
And every time, I have to manually click on the multiple instances icon, and select Rename.
I would love to see a checkbox preference under darkroom/modules that says something like "Prompt for name on addition of new instance".
So, the moment you invoke a new instance of any module, darktable gives you the rename box straight away.
Just a thought.
Cheers.

### PR DESCRIPTION
**Pull request by johnny-bit**
fixes #9644 

Implements immediate rename on new instance option

### CODE REVIEW

**Comment by dterrahe** [comment]
Not behind development machine so haven't tested this out, but a couple of thoughts (some may be based on wrong assumptions or interpretations).

1. People don't like double click delays. It was a big initial criticism of input ng. They make things feel "slow" to respond.
2. If you quickly want to expand two different modules by clicking on their headers successively, if you are fast enough (don't know if this is possible!) the first click will be forgotten and the module never opens.
3. g_timeout_add gets executed when idle. So the delay could easily get longer than the double click delay. People might click again, which would restart the count.
4. You have to be careful about cleaning up or you'll get a crash. Here, if the module gets deleted immediately after a click on its header (by switching to lt or a different image) things might end bad.
3 and 4 were some of the reasons why I removed gtimeouts in #9732
5. People are used to ctrl-click; you may never be able to reclaim it.

Making name immediately editable on new instance might be preferable (I'm sure I'm not seeing some obvious drawbacks now), also making rename more discoverable. And clicking anywhere else would end the edit.

Not that I have too much against using double click, mind. Although it is used for "reset" in some other places (bauhaus and module shortcut fallbacks for two)...

**Comment by johnny-bit** [comment]
> People don't like double click delays. It was a big initial criticism of input ng. They make things feel "slow" to respond.

On my system my configured double click delay is very fast but indeed the delay could be "felt".

> If you quickly want to expand two different modules by clicking on their headers successively, if you are fast enough (don't know if this is possible!) the first click will be forgotten and the module never opens.

The current implementation is "global", i could make it "local" to module which would start timeouts on super fast clicks to module. I decided to go with "global" for now just for the simplicity and to allow testing.

> You have to be careful about cleaning up or you'll get a crash. Here, if the module gets deleted immediately after a click on its header (by switching to lt or a different image) things might end bad.

Indeed, I'm not checking for null `user_data`.

> People are used to ctrl-click; you may never be able to reclaim it.

for now :P One thing that prompted that was that even a person doing yt tutorials forgot about obvious shortcut ;)

> Making name immediately editable on new instance might be preferable (I'm sure I'm not seeing some obvious drawbacks now)

This could piss off people who (like me) do multi-instance without renames and do speedrun for edits ;) such "enforced rename" would grind some gears and would have to be hidden behind option like the original issue requested.


Overall I 100% agree with your review. I just need a bit more testers and opinions :)

**Comment by elstoc** [comment]
I want modules to expand immediately. For me it's not worth the slow expand to get double-click renaming.

**Comment by johnny-bit** [comment]
OK, re-done to be in-line with #9644 request.

Please test :)

**Comment by elstoc** [comment]
I think you might have introduced a regression here. If you right-click on the multi-instance menu it both creates a new instance and opens the preset menu. In master it just creates a new instance.

**Comment by dterrahe** [comment]
> Indeed, I'm not checking for null `user_data`.

If only it were so simple. The user_data won't be set to NULL when the module gets destroyed; it will just continue to point to a now-deleted module.

> On my system my configured double click delay is very fast but indeed the delay could be "felt".

When developing UIs, it might make sense to use the same configuration as your average user so you feel their "pain". A fast double-click speed is not achievable for everybody, so you would make the function inaccessible to them or normal cllicks very slow.

For same reason we all should use really slow development machines.

> would grind some gears

Just for me to understand; what do you do immediately after creating an instance? If you click on anything, it should automatically end the edit without you needing to do anything extra. So unless I'm mistaken (I haven't tried/tested now) the _only_ thing that would require an additional action to close the edit would be if you immediately wanted to use a shortcut.

**Comment by elstoc** [comment]
Not every click elsewhere closes the edit. If you attempt to change a contrast equalizer curve, for example, the rename entry doesn't close. I would still prefer it to be optional.

**Comment by johnny-bit** [comment]
> I think you might have introduced a regression here. If you right-click on the multi-instance menu it both creates a new instance and opens the preset menu. In master it just creates a new instance.

Cannot reproduce... it works as expected regardless whether prompt for rename is on or off.

>  I would still prefer it to be optional.

It is optional and disabled by default :)

> Not every click elsewhere closes the edit. If you attempt to change a contrast equalizer curve, for example, the rename entry doesn't close.

Indeed - the "curves" seem to not change edit stare of renamer, that include things like contrast equalizer, denoise in wavelets mode, tone equalizer. However things like color zones or tone curve work nicely, so it's some interesting gui interaction.

**Comment by elstoc** [comment]
I don't know what to say. I've tried with master and then with your PR rebased on master so it's definitely this PR that's introduced it, but I don't know how.

**Comment by elstoc** [comment]
Thanks. All good for me now.

**Comment by johnny-bit** [comment]
> I don't know what to say. I've tried with master and then with your PR rebased on master so it's definitely this PR that's introduced it, but I don't know how.

Fixed. Seems like for some reason that caused the event to propagate. Newest commit uses returns as defined in specs to stop event propagation in case we know to handle.

> I thought @dterrahe was kinda suggesting the possibility of having it work this way always and was just saying I'd prefer to keep it optional.

If we can iron out the kinks (like the couple input elements that do not end the rename) then maaaaybe dterrahe's suggestion is actually good one? That however would indeed interfere with shortcuts.

Anyway - this is ready for review :)

**Comment by elstoc** [comment]
> That however would indeed interfere with shortcuts

That's a big however for me.

**Review by TurboGit — APPROVED** [review]
Nice, I very much like this. Thanks.

**Pull request merged**
