### PR TITLE
Noise profiles

### LINKED ISSUE #4525: Add Panasonic DC-GF9 noise profile
For noise profiles, please also attach the entire archive with `.pdf` plots.

I was guided by the instructions here: https://pixls.us/articles/how-to-create-camera-noise-profiles-for-darktable/. 

I recognized that the darktable scenes the camera model name different than the noise profile generator. Darktable recognizes the camera as DC-GF9 while noise profile generator sees it as DC-GX800.
I renamed it in the preset.json tested it and replaced it in the attached tar.gz.

[darktable-noiseprofile-20200320.tar.gz](https://github.com/darktable-org/darktable/files/4364997/darktable-noiseprofile-20200320.tar.gz)

If it is more easy for you if i merge it directly to noiseprofiles.json let me know.

Thy
Christian

### PR DESCRIPTION
**Pull request by rawfiner**
Fixes  #4525 , #4481 , #4481 and #5121

### CODE REVIEW

**Comment by TurboGit** [comment]
Thanks !

**Comment by johnny-bit** [comment]
When doing "fixes #issue" github seems to match only the 1st issue so one needs to list issues one by one or close rest by hand :)

**Comment by rawfiner** [comment]
Indeed, thanks @johnny-bit 
I tried to modify the text of the PR, but github does not seem to take it into account unfortunately. @TurboGit could you close the issues please?

**Comment by TurboGit** [comment]
All closed.

**Comment by rawfiner** [comment]
Thank you :-)

**Pull request merged**
