### PR TITLE
clipping: quick workaround for bug #11329

### PR DESCRIPTION
**Pull request by upegelow**
this is just a quick hack to overcome bug #11329 before the 2.2.0 release.
all in all the clipping module is totally screwed and needs a major/full
rewrite.

### CODE REVIEW

**Comment by LebedevRI** [comment]
> all in all the clipping module is totally screwed and needs a major/full rewrite.

Yep. lensfun-0.4.0 will have perspective correction stuff we need, so i think at this point it is best to simply wait until it is releases, and do not even attemp reworking c&r.

**Comment by upegelow** [comment]
To me the biggest problem of the clipping module is that it has evolved over several years without a consistent mathematical approach. So every element has been put on top of the other (clipping margin, rotation matrix, perspective shear) plus the strange way of generating the final correction data over several steps (commit_params, modify_roi_out, process).

**Comment by LebedevRI** [comment]
For that exact reason, splitting `clipping.c` into just the crop tool, and doing a clean re-implementation of perspective correction/keystone/rotation features from the scratch using lensfun PC stuff *may* result in not-so-disastrous code.

**Comment by houz** [comment]
We still need to maintain the old mess for legacy history stacks. Or deprecate c&r and write a new crop tool. However, from a user's point of view I wouldn't like to need to switch modules for cropping and rotating. So this isn't straight forward at all.

**Comment by LebedevRI** [comment]
> We still need to maintain the old mess for legacy history stacks. Or deprecate c&r and write a new crop tool.

Exactly. Current `clipping.c` would be deprecated, and new `cropping.c` would be added.

> However, from a user's point of view I wouldn't like to need to switch modules for cropping and rotating. So this isn't straight forward at all.

True, will not argue there.
This is not set in stone, but there are really good reasons to do this way.

**Comment by upegelow** [comment]
Let's also first see if lensfun brings enough to the table. After all rotation and perspective correction are not directly lens bound and can be implemented in a straightforward way with homographic conversions (like in ashift). I am a bit concerned to rely on a fresh implementation in an external library as any incompatible changes in that library will put the burden on us to guarantee legacy behavior.

**Comment by LebedevRI** [comment]
> Let's also first see if lensfun brings enough to the table.

I want to revamp current `lens.c` anyway, and change it's place in pipe.
So it wouldn't even be a modification of `lens.c`, that iop would get deprecated too.

> After all rotation and perspective correction are not directly lens bound

Generally true, but depends whether you want to get better results or not.
I *think*, e.g. if you want to straighten horizon, it *needs* to be bound to lens, @bronger can correct.

> and can be implemented in a straightforward way with homographic conversions

Not arguing there. However so far the lensfun-based `lens.c` managed to not get overly bloated/complicated/broken. Therefore i do not think that moving interpolation stuff from `clipping.c` into it would make it worse.

> (like in ashift). 

I'm hoping to re-use it's ui/sampling as an input for perspective correction.

> I am a bit concerned to rely on a fresh implementation in an external library as any incompatible changes in that library will put the burden on us to guarantee legacy behavior.

It for sure has much more tests than we do have :)
https://github.com/lensfun/lensfun/tree/master/tests

BTW, http://wilson.bronger.org/lensfun/perspective-correction.html

**Comment by upegelow** [comment]
Travis reports errors on MacOS but I don't think they are related to this PR.

If no objections I'll merge tomorrow.

**Comment by LebedevRI** [comment]
> Travis reports errors on MacOS but I don't think they are related to this PR.

Indeed they are not, #1365

**Comment by LebedevRI** [comment]
I'm gonna close and immediately reopen this just to re-trigger ci...

**Pull request merged**
