### PR TITLE
nicer list in map find-location

### LINKED ISSUE #5304: Map view: polish localisation results list for 3.2
**Describe the bug**
As we are on polish the UI for the 3.2, it remains a thing I just see and will probably need some Gtk things to then tweak CSS, on map view.

Just search a place on top right module and see:

The list is just awful. Results needs to be aerate between them, the left arrows are strange to be there and that way. So we need to have a polished list and space between results like on most dropdown (for example filter collections).

### PR DESCRIPTION
**Pull request by AlicVB**
icon removed. items are now named dt-map-location and can be tweaked by css (not done here)
this fix #5304

### CODE REVIEW

**Comment by TurboGit** [comment]
@AlicVB : I suppose @Nilvus will do the CSS ? So I can merge this now, right?

**Comment by AlicVB** [comment]
let's wait a minute that he don't have any other requirement ;)

**Comment by Nilvus** [comment]
I will test that. Thanks for doing that quickly. @TurboGit: the Lucky Luke of the merge ;-) ;-)

**Comment by Nilvus** [comment]
Ok, so tested and all good. Like the way it can be now. Thanks again @AlicVB. See first tests I just made with CSS (not the final one but a first idea):



@TurboGit: You can shoot and hit the master!

**Comment by TurboGit** [comment]
All good then. Merging.

**Pull request merged**
