### PR TITLE
Move all image I/O related files from common/ to imageio/

### PR DESCRIPTION
**Pull request by victoryforce**

### CODE REVIEW

**Comment by victoryforce** [comment]
The build fails only in the macOS runner with diagnostics, which, it seems to me, is not related to the content of PR:

```
In file included from /Users/runner/work/darktable/darktable/src/src/osx/osx.mm:24:
In file included from /Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:54:
In file included from /Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSCIImageRep.h:11:
/Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/CoreImage.framework/Headers/CIImage.h:152:38: fatal error: expected a type
+ (CIImage *)imageWithCGImageSource:(CGImageSourceRef)source
                                     ^
1 error generated.
```

Anyway, I don't really understand how moving the source files can trigger such an error...

**Comment by TurboGit** [comment]
Yes I saw that, cannot be this PR.

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Comment by TurboGit** [comment]
@zisoft : Ok, and do you know why? The reported failure is hard to understand....

**Comment by zisoft** [comment]
I'm lost here too, this commit has 97 changed files...

**Comment by parafin** [comment]
I don't see anything in this PR that could affect compilation of osx.mm. Are you totally sure the commit prior to it builds fine right now on your system? Haven't tried building myself though.

**Comment by parafin** [comment]
But indeed CI broke with this exact PR, why it was merged then?

**Comment by parafin** [comment]
I would suggest to revert and see if it fixes macOS CI. If it does, then keep this reverted until someone can explain why it breaks.

**Comment by zisoft** [comment]
> Are you totally sure the commit prior to it builds fine right now on your system?

I see this commit history:

    git log --pretty=oneline
    2fdb89d7329df710a6f83ec49def63224e8faddf collect : fix usage of exclude for first item
    2669d89b12330d18ea48de74fdfb3891e228fe59 Merge pull request #13352 from TurboGit/po/borders-rounding
    f62c9b258a7403a8723808f209bd833a4202b97d rgbcurve: bugfix, setup picker with compensate middle grey param
    393e52be379a2911f3a07ca3a78151861d87b840 Updates to pt_BR
    808b3ed32deac2cd68a1b021a2a9f0fa3b6e415e Move all image I/O related files from common/ to imageio/
    
    30a419a3f4150e12260267312929822b7abcb1fc borders: Minimize accumulated errors.
    c627e92cfaf77ff32e9ae96e0ba1e1b97c9ba776 Minor reformatting
    ad9435da635d358bbd14c1d1a0c9538f7300ce86 borders: Some more rounding to better fit the framing.
    e099c53610f382460329613acc526bb253bd7780 borders: Fix rounding issues when computing width/height.

Checking out from bottom to top I can successfully build up to `808b3ed32deac2cd` which gives the above error.

**Comment by TurboGit** [comment]
@zisoft : Have you tried removing the build directory completely. Maybe soe ccache issue?

```
$ rm -fr build
$ ./build.sh
```

Or whatever the incantation is on MacOS.

**Comment by TurboGit** [comment]
> then keep this reverted until someone can explain why it breaks.

Meaning forever :) 

Let's try first to have some MacOS dev help here. Moving some files around should not have such terrible result, maybe this has uncovered a more severe issue.

**Comment by TurboGit** [comment]
> But indeed CI broke with this exact PR, why it was merged then?

It was merged because the MacOS CI is not 100% reliable and when I looked at the result it was clear to me that it was not due to this PR (and I was wrong, yes). That's not the first time the MacOS CI fails and Linux & Windows CI are ok.

**Comment by zisoft** [comment]
> @zisoft : Have you tried removing the build directory completely. Maybe soe ccache issue?

Yes, removing the build dir is part of the build process in the MacOS scripts.

I would appreciate to help here but the change history of this commit is fairly huge. Will try to break down the changes into smaller steps and see at what point the error arises.

**Comment by kmilos** [comment]
Could this be down to some header file include order change perhaps?

**Comment by victoryforce** [comment]
> Will try to break down the changes into smaller steps and see at what point the error arises.

The only thing in these changes that could theoretically have any effect is changing the order of some of the includes. In most cases, the include lines were sorted alphabetically, and since the new directory of included files changed this order, they were moved to preserve the alphabetical order.

**Comment by victoryforce** [comment]
> Could this be down to some header file include order change perhaps?

Yes, this is the only thing that, I don't understand in what way, but it could have an effect. Ideally, all header files should be self-contained, and inclusion order should not matter. In practice, people sometimes write header files that are not self-contained, and sometimes inclusion order does matter.

It is clear that moving the files to another directory with appropriate corrections of all links cannot break anything by itself. So, if the cause of the problem in macOS CI is precisely this PR, then it can only be the order of includes.

The strangest thing is that there are no problems when building on Linux, so it's very unlikely to be simple errors due to cross-dependencies between header files.

**Comment by parafin** [comment]
osx.mm is self-contained meaning it doesn't use any darktable headers, so include order has nothing to do with it. It seems we have some conflict with actual header filename between some macOS and system framework, moving it to a path that's in -I exposed the problem.

**Comment by parafin** [comment]
Given previous comment, I guess it's imageio.h. I would suggest to try to rename it.

**Comment by parafin** [comment]
My guess some macOS framework has smth like #include <imageio/imageio.h> and now darktable has this include, overriding the system one. The simplest solution is to rename imageio.h to smth like imageio_common.h, should do the trick. But that's my untested theory.

**Comment by zisoft** [comment]
just did that, renamed it to `imageio_xyz.h` and changed all `#include` references.
Build runs fine now.

I will now checkout master and repeat that step.

**Comment by parafin** [comment]
If you could submit a PR it would be great. Just use smth better than xyz;) I suggest common.

**Comment by zisoft** [comment]
So, finally confirmed. Simple renamed `imageio.h` to `imageio_common.h` and changed the references.
Build runs fine, darktable executable runs fine.

I will prepare a PR now.

That was pure luck the the first file I tried here leads to the error.

**Pull request merged**
