### PR TITLE
collection query cleanup and fix

### PR DESCRIPTION
**Pull request by AlicVB**
This remove unused code, do some cleanup, reformat to avoid code duplication and fix an issue with "ambiguous" id in the collection query.

### CODE REVIEW

**Comment by AlicVB** [comment]
finally another refactoring to simplify and make the code more robust, esp. with more than one defined sort order

**Comment by TurboGit** [comment]
Some issues:
1. select collection based on tags / description / title
2. filter on aspect ratio

`sqlite3 error: /home/obry/dev/builds/c-darktable/x86_64-linux-gnu-default/src/src/common/collection.c:566, function _collection_update_aspect_ratio(), query "SELECT id FROM main.images WHERE (( (mi.id NOT IN (SELECT id FROM main.meta_data WHERE key = 2))) AND ( 1=1 AND (1=1))) AND (aspect_ratio=0.0 OR aspect_ratio IS NULL)": no such column: mi.id`

Fix is trivial, I'll fix.

**Review by TurboGit — APPROVED** [review]
Thanks for the very nice clean-up, and the fixes!

**Comment by AxelG-DE** [comment]
is it possible, this PR caused a regression? My Lighttable suddenly getting super sluggish when scrolling (up to 3s stall).
I will likely create an issue soon, just bisect is not easy over new db versions
[dt-bug_2023-09-24.txt](https://github.com/darktable-org/darktable/files/12708132/dt-bug_2023-09-24.txt)

**Comment by AlicVB** [comment]
yes, this may be a drawback of recent db changes.
I would say : wait for #15312 to be merge (this optimize and fix some issues)
Then, if you still reproduce, open a new issue, and specify your settings in the collect module, the filtering one and the sort order you use...
Thanks !

**Comment by AxelG-DE** [comment]
Understood

**Comment by AxelG-DE** [comment]
@AlicVB so I went back on commit before yours, so `4.5.0-706-g5534adfb0f` and the lighttable is crisp as before

@TurboGit could you kindly have an eye on it...

My collect module looks like this:
grafik

**Comment by TurboGit** [comment]
> @TurboGit could you kindly have an eye on it...

Sure just tested with current master (so without the last PR from @AlicVB) and I cannot  reproduce the slowdown.

**Comment by TurboGit** [comment]
@AxelG-DE : Found and fixed, during my clean-up of the images tables all the SQL indices (& trigger) where removed hence the slowdown for large DB. I was not able to experience this while testing on my dev test DB.

**Comment by AxelG-DE** [comment]
TNX!
I will check tomorrow.

yes, my lib is a bit bigger :) 1.398.505.472 bytes.... (confess, there are double imports inside, per folder and whole pic-dir, will re-import one day...)

**Comment by AxelG-DE** [comment]
@TurboGit and @AlicVB  I "tested" (briefly) the version 4.5.0-756-g76cf661582 and it is crisp as before. TNX!

**Comment by TurboGit** [comment]
> yes, my lib is a bit bigger :) 1.398.505.472 bytes.

Would be interesting to know the drop in size after my DB clean-up (0b875bf1687f1a068b48a6828c7ee0b6ef3173f6) removing some columns. Do you have the information?

**Comment by AxelG-DE** [comment]
@TurboGit 

I had to restore a backup from two days ago, as I have moved on already to re-import my pics. However, indeed I am happy to do so. So here is the result:

library.db from before all this changes:
`-rw-r--r-- 1 gerber users 1397850112 22. Sep 21:42 library.db`
and after the changes:
`-rw-r--r-- 1 gerber users 1396244480 25. Sep 11:52 library.db`
So the delta is:
1.605.632 bytes :)

**Comment by TurboGit** [comment]
> 1.605.632 bytes :)

Thanks, not a huge gain (0.12%) but not bad either :)

**Comment by AxelG-DE** [comment]
on my laptop the db even increased from 
6.324.224
to 
6.356.992

**Comment by TurboGit** [comment]
You need to call `vacuum` (from sqlite3) to ensure old data are removed and the free space actually recovered.

**Comment by AxelG-DE** [comment]
hmmm why the db-maintenance thingy disappeared in dt or is it just hidden somewhere?
on my main machine I anyway built a new db to get rid of dupes. And now the generate-cache is running :)

**Comment by AxelG-DE** [comment]
BTW: I didn't do that vacuum-tingie  with above test about my old db on the main machine. Do you need me to repeat that test?

**Comment by TurboGit** [comment]
> hmmm why the db-maintenance thingy disappeared in dt or is it just hidden somewhere?

We have removed all those options and now dt check the DB fragmentation and does the vacuum if necessary.

**Comment by AxelG-DE** [comment]
> We have removed all those options and now dt check the DB fragmentation and does the vacuum if necessary.

Sounds cool and there might be a threshold not be met, as VACCUUM actually did something to me...

initial:
-rw-r--r-- 1 gerber users `1397850112` 25. Sep 16:55 library.db
start dt and let it upgrade the db
-rw-r--r-- 1 gerber users `1396408320` 25. Sep 16:56 library.db
and after VACUUM and PRAGMA
-rw-r--r-- 1 gerber users `1396211712` 25. Sep 16:57 library.db

Don't ask me, why the numbers are different than first test...

draft overview :-)
[sqlite3-size.ods](https://github.com/darktable-org/darktable/files/12716794/sqlite3-size.ods)

Now I will go back to my new lib and let the cache-generator keep going

**Comment by AxelG-DE** [comment]
MAYBE first time dt actually did VACUUM and this time not, just an idea...

**Comment by TurboGit** [comment]
> MAYBE first time dt actually did VACUUM and this time not, just an idea...

Yes a plausible explanation! And thanks for the data.

**Pull request merged**
