### PR TITLE
2nd window: allow fullscreen

### PR DESCRIPTION
**Pull request by edgardoh**
Allows fullscreen on 2nd window.

Addresses #2405

### CODE REVIEW

**Comment by edgardoh** [comment]
@Nilvus , this now goes to fullscreen with F11/Escape hard-coded, no idea yet how to make it configurable. To be discussed.

2nd window has a name now, second_window.

As for the background color, I use DT_GUI_COLOR_DARKROOM_BG.

Could you please test and let me know what's missing?

**Comment by Nilvus** [comment]
Great works ! I will follow when this will be merged as it seems I will have to update css to remove border. It seems that you set second_window name tag if I read correctly your code.

**Comment by Nilvus** [comment]
I write my comment same time as yours. Not sure it will be possible to change border with your code. It seems that you set 'second_window' tag name on widget and not on window. It's window background which is top parent who display border. Widget a subparent of window theme and display middle grey part and image inside.

**Comment by edgardoh** [comment]
Not sure I follow, I set the name just like in the main window, and yes, is
using the widget. Does this works on the main window?

**Comment by Nilvus** [comment]
> Not sure I follow, I set the name just like in the main window, and yes, is using the widget. Does this works on the main window? El dom., 19 may. 2019 a las 14:54, Nilvus (<notifications@github.com>)

Yes, main_window tag is on top parent window widget. But I can't detail here, I'm only able to code on css and use Gtk inspector to see that. I don't know how to code except CSS/HTML.

**Comment by Nilvus** [comment]
Forget what I said, 'second_window' is correctly tagged on window top parent. And I didn't understand that you also removed the border so I don't see anything to be customized or added, but that could be for those who wants to with this tag, so separately from main window.
Works really great and it really resolve the issue totally.

The only thing is that I find the time to display image a little longer than before (1 or 2 seconds more) and I've this on starting and when I go fullscreen and revert back to classic window.

**Comment by edgardoh** [comment]
> Forget what I said, 'second_window' is correctly tagged on window top
> parent. And I didn't understand that you also removed the border so I don't
> see anything to be customized or added, but that could be for those who
> wants to with this tag, so separately from main window.
> Works really great and it really resolve the issue totally.
>
> The only thing is that I find the time to display image a little longer
> than before (1 or 2 seconds more) and I've this on starting and when I go
> fullscreen and revert back to classic window.
>
Depending on the change in size the image is reprocessed, so maybe that's
what you see. Try it with -d perf, if you see that is processing the pipe
more than it should we have a problem. For me is working the same as
before.

**Comment by edgardoh** [comment]
I reuse now the global accel "toggle fullscreen" and "leave fullscreen", it works only if the 2nd window has the focus.

The image is draw on the center of a grid, so it should be possible to define some border around it with CSS, not sure if some work is needed for that.

**Comment by TurboGit** [comment]
I don't think we want to make the F11/escape configurable as those keys are common to almost (if not all) desktop environment.

**Comment by edgardoh** [comment]
> I don't think we want to make the F11/escape configurable as those keys
> are common to almost (if not all) desktop environment.
>
They already are for the main window, seems reasonable to use it for the
2nd one.

**Comment by edgardoh** [comment]
@Nilvus , I think I found it, it was not using the preview pipe if the preview2 was not available, so it seems to take longer, could you confirm?

**Comment by Nilvus** [comment]
> I don't think we want to make the F11/escape configurable as those keys are common to almost (if not all) desktop environment.

What about other OS (Mac and Windows) ? I'm not sure if they use this shortcut for full screen (even on MacOS I use for about 10 years, I don't remember that ;-) !). So maybe more secure to have configurable shortcut, and it's more consistent to have same than main window. So great for me.

@edgardoh : I have test with preview pipe adding and it's now really quick (instantaneous most of the time on my computer) so perf preview is ok now.
About line around image, I think it's not needed on this window so I will not check if it could be made or not. A pure and simple preview window as it is is great like that for me.

**Comment by edgardoh** [comment]
Great!

@TurboGit , if you agree with the shortcut then this is ready for review.

**Comment by TurboGit** [comment]
I kind of remember that F11 works on Windows too but my memory is very bad. And configuration is not bad anyway.

**Comment by TurboGit** [comment]
Working fine on my side! Thanks.

**Pull request merged**
