### PR TITLE
Channel mixer RGB/ color calibration : add OpenCL kernel

### PR DESCRIPTION
**Pull request by aurelienpierre**
Tested on Intel and Nvidia OpenCL. Consistency between CPU and GPU path has not been tested yet.

### CODE REVIEW

**Comment by johnny-bit** [comment]
silly GCC 7 errors out with `error: unknown type name ‘cl_mem’` in `src/iop/channelmixerrgb.c:1899`

**Comment by TurboGit** [comment]
GPU vs CPU all good:

```
Test 0084-cacorrect
      Image mire1.cr2
      CPU & GPU version differ by 22652 pixels
      ----------------------------------
      Max dE                   : 0.00000
      Avg dE                   : 0.00000
      Std dE                   : 0.00000
      ----------------------------------
      Pixels below avg + 0 std : 100.00 %
      Pixels below avg + 1 std : 100.00 %
      Pixels below avg + 3 std : 100.00 %
      Pixels below avg + 6 std : 100.00 %
      Pixels below avg + 9 std : 100.00 %
      ----------------------------------
      Pixels above tolerance   : 0.00 %
  OK
```

**Comment by aurelienpierre** [comment]
>       CPU & GPU version differ by 22652 pixels

You sure ?

**Comment by TurboGit** [comment]
> > ```
> >   CPU & GPU version differ by 22652 pixels
> > ```
> 
> You sure ?

Well no, that was a quick test on modules using channelmixerrgb. Let's double check...

**Comment by TurboGit** [comment]
Confirmed, I have added a new test.

Before applying this PR:

```
Test 0085-channelmixerrgb
      Image mire1.cr2
      CPU & GPU version differ by 27897 pixels
      ----------------------------------
      Max dE                   : 0.00000
      Avg dE                   : 0.00000
      Std dE                   : 0.00000
      ----------------------------------
      Pixels below avg + 0 std : 100.00 %
      Pixels below avg + 1 std : 100.00 %
      Pixels below avg + 3 std : 100.00 %
      Pixels below avg + 6 std : 100.00 %
      Pixels below avg + 9 std : 100.00 %
      ----------------------------------
      Pixels above tolerance   : 0.00 %
  OK

Total test 1
Errors     0
```
And after applying this PR, a bit more diff between OpenCL and CPU but very close:

```
Test 0085-channelmixerrgb
      Image mire1.cr2
      CPU & GPU version differ by 27900 pixels
      ----------------------------------
      Max dE                   : 0.00000
      Avg dE                   : 0.00000
      Std dE                   : 0.00000
      ----------------------------------
      Pixels below avg + 0 std : 100.00 %
      Pixels below avg + 1 std : 100.00 %
      Pixels below avg + 3 std : 100.00 %
      Pixels below avg + 6 std : 100.00 %
      Pixels below avg + 9 std : 100.00 %
      ----------------------------------
      Pixels above tolerance   : 0.00 %
  OK

Total test 1
Errors     0
```

**Review by TurboGit — APPROVED** [review]
All good !

**Pull request merged**
