### PR TITLE
Fix crop in LR import

### PR DESCRIPTION
**Pull request by leclercj**
Fix crop data migration from Lightroom to darktable
crop migration moved after orientation migration, and done with respect of user orientation
merge_two_orientations() moved from iop/flip.c to common/image.c for code factoring

### CODE REVIEW

**Comment by leclercj** [comment]
This morning I'm not sure anymore this is the shortest & simpliest way to fix the problem. Let me think about it one day before merging.

**Comment by TurboGit** [comment]
Sure! Thanks for working on this @leclercj !

**Comment by leclercj** [comment]
Less changes for the same result.
Tested with Lightroom 6 with combinations of exif (raw format) rotation + user rotations in LR
Should be ok to merge now.

**Comment by TurboGit** [comment]
Perfect! Thanks.

**Pull request merged**
