### PR TITLE
Refactor images to act on

### PR DESCRIPTION
**Pull request by Solarer**
This PR is a draft for a different implementation of "images_to_act_on" based on issue #6025.
This code decides upon which images an action should be performed (e.g. user clicks on apply color label "red" while having some pictures selected and others active. Should the action be applied to the active or selected pictures?)

The old algorithm had some special quirks and behaved differently if the mouse hovered a selected picture or a non-selected picture - the new approach is more straight forward and should result in less confusion for new and old users.

- Priority is as follows:
`Selection > Mouseover > Active Images`

- Exception Culling Dynamic mode
`Mouseover > Active Images`

- Exception Fullscreen Views:
`Always act on full-screen image`

The exception in Culling Dynamic is necessary because some pictures are always selected in this mode and we are working on this "sub-collection". Otherwise mouseover and active images would always be overwritten by selection.
The same can happen in culling fixed mode if the mode is entered with an active selection (this limits navigation to selection). I therefore moved this feature from culling fixed mode to culling dynamic only by unlocking the zoom slider in culling dynamic.
Culling fixed mode behaves now more like the filemanager layout (navigation never limited to selection) and in culling dynamic the user CAN choose to view only a subset of all pictures using the zoom slider which limits his navigation to the selection. 

- The feature "Copy history on mouseover" has been disabled but can be enabled by setting `copy_on_hover=TRUE` in `darktablerc` for users that want this behavior.

Known bugs:
- If darktable is started in culling dynamic mode, the zoom slider is disabled until the user enters another mode and restarts darktable.
- When hovering a picture in culling and applying e.g. a color label with F1, mouseover disappears and focus shifts to the first active image instead of remaining on the hovered image.
- `copy_on_hover=FALSE` is not automatically stored in `darktablerc` even though I added it to `darktableconfig.xml.in`

Open Question:
When displaying multiple images in culling and scrolling through the collection, the first active image is in status "mouseover". This can be irritating because a user might expect to act on all active images but this limits him to the first image only.

### CODE REVIEW

**Comment by AlicVB** [comment]
Great that you've finally done it !

I'll test that later, but I have a first question after a brief look at the code : I thought that you wanted to propose an alternative algorithm, but you seem to have dropped the previous one, right ?

Not sure it's the right solution as the previous behavior was working fine for lot of us (not all of us, hence the need of your work) and changing habits for such a central feature might be problematic/unwanted...

Do you think it's possible to keep both algorithm available, with a pref to choose the one to use ? next step will be to decide which one to put as default, but that's another story ;)

**Comment by Solarer** [comment]
@AlicVB I did exactly that in the beginning but I cleaned it up a few commits earlier because most of the stuff behaves very similar to before.
If you think it is necessary I can put the if-else block back in but I think it works quite well ;)

**Comment by AlicVB** [comment]
@Solarer : I've just done a very quick test, and I'm really not convinced it's better (but you already know that) The main blocking points for me (again, after a very small test period) : 
1. culling fixed and full screen not limited to the selection. I very often use that to preview/cull images that are not necessary contiguous (1 "foreign" image in the middle for example). I also use that to quickly show a "manual" diaporama for a selection of images...
2. things can be applied to an "invisible" image : you click on one image for whatever reason (the selection can even be here from an older session). you scroll the collection... you hover another image , press D, F1 or del and ... this is the "invisible" image that gets changed/removed...

point 1. is really a "no-go" for me. For point 2, we touch to the "spirit" of this change so it's more a "personal taste".

I still really think that all of this -if we decide to do it- should be determined by a pref !

**Comment by Solarer** [comment]
@AlicVB thanks for checking it out!

Regarding 1) this is now in culling dynamic mode. Just change the zoom to 1 or 2 images at a time and scroll - it will skip any unselected "foreign" pictures. Previously, this mode showed you all selected pictures at once. You get this old behavior if you choose a zoom level greater than the number of pictures you selected. Please try it out :+1: 

Full preview is limited to selection if you enter this mode from culling-dynamic. I agree that this is not very consistent. Full preview should probably be always limited to selection. 

Regarding 2) I don't really see how it could be implemented in a consistent way. 
If I select all pictures in a collection I always have some pictures that are selected but "invisible". Similarly, I could select one picture in the beginning and one picture at the end of a collection. How should the code decide when to ignore and when to respect my selection? The old behavior of letting mouseover overwrite the selection was one of the points that were criticized. Can this not be solved by making it more visible to a user that he has an active selection? For example, if no pictures are selected we hide the text in the top instead of saying "0 images of XX in current collection are selected" that way the text will only show if pictures are selected making it much more transparent to the user on what basis he is working on.
Allowing users to reenable the old behavior that mouse-over has highest priority is also acceptable to me but we should not handle images differently once they scroll out of sight.

**Comment by Solarer** [comment]
Full preview navigation is now limited to selection if a selection is present and there is no mouseover.

**Comment by Solarer** [comment]
You can now pick the old images_to_act_on algorithm by setting `images_to_act_on_legacy=FALSE` in darktablerc.
This does not change back the behavior of culling. If you want to limit navigation to selection pick culling-dynamic.

**Comment by EC1000** [comment]
I agree with @AlicVB, it should stay a option to switch to "Selection > Mouseover > Active", personnally I use mouseover to enter full screen, add color label, etc

**Comment by quovadit** [comment]
@Solarer : thanks for working on this important topic, but my usecases don't work yet:
- culling fixed-mode:
  - the first image (# 1) in lighttable is selected
  - I start culling fix-mode by pressing x
  - 2 images are shown (# 1 and # 2)
  - image # 1 is selected but does not have a white border (NOK)
  - I press the key '4' to give four stars to the first image (OK)
  - I press arrow-right to navigate to the next image-pair
  - images # 2 and # 3 are shown now, # 2 has a white border (OK)
  - I press the key '1' to give one star to the second image
  - the 1-star rating got applied to the image # 1 - which is not even visible (NOK !)
- culling dynamic-mode
  - 5 images are selected (# 1, # 2, # 3, # 4, # 5)
  - I start culling fix-mode by pressing ctrl-x
  - 2 images are shown (# 1 and # 2)
  - I press the key '4' to give four stars to the first image
  - the 4-star rating got applied to all visible images # 1 and # 2 (NOK !)
- filemanager layout
  - I start darktable
  - the header says '1 image ... is selected'
  - I don't see a selected image, so I press arrow-right, arrow-left
  - now the first image (# 1) is highlighted, the header still says '1 image ... is selected'
  - I press the key '4' to give four stars to the first image (# 1)
  - the 4-star-rating got applied to image # 42 - which is not  even visible (NOK !)

So here are my suggestions how to fix these issues:
- culling
  - In culling (fix+dynamic) there is always one (1) image highlighted (= it has a white border + all actions are applied on this image)
  - when starting culling mode, the first visible image gets highlighted
  - details see [#7254](https://github.com/darktable-org/darktable/issues/7254)
- filemanager layout
  - navigation with the arrow-keys in filemanager layout changes the selection immediately
  - to navigate without changing the selection use ctrl-arrow-key (default behaviour of nautilus e.g.)
  - improve visibility of selected image
  - no action will be applied, if none of the selected images are visible - show toast-message instead

**Comment by wpferguson** [comment]
Lua also uses images to act on (exposed as darktable.gui.action_images), so if you change the behavior you may break multiple scripts

**Comment by wpferguson** [comment]
A thought about this.  Instead of having "it works one way or it works the other" would it make more sense to make _images to act on_ configurable.  Everyone agrees to a certain core functionality (i.e. images that are selected should always be part of the ones to act on) and then other parts can be enabled or disabled (such as hover).  The default behavior could be the current, then have some preferences to turn behaviors on or off, or select from a set of alternatives.

**Comment by AlicVB** [comment]
@Solarer : I've given it a try to your new culling approach... and I'm sorry to say that it still doesn't cover my workflow. I have 2 main usage of culling : 
- dynamic for a "rapid" selection of the better images from a set (usually ~10 images). I don't look at the details then, just the framing, etc...
- static (with 2 images) if I need to compare individual images from a set in details (usually with few images, 3-4) This images are not always contiguous, due to "foreign" images in the middle for example

Now with your proposal, I always need to play with the zoom slider... not cool !

I will repeat what I've already said : 
I really think that the current approach should remained **unchanged** and that you propose your new algorithm in parallel. 

The current algo has been designed carefully to fulfill what some of us think as the better approach and it works quite well for us...
That doesn't mean your work is useless or bad designed. I perfectly understand that it doesn't satisfy everyone, (esp. but not only due to the fact that it's not what people are used too) But if you don't touch the current situation and propose something else in parallel, it will be way simpler to handle for *you* as a dev and for *us* as reviewer/tester, you even may decide to drop some workflow completely, if some usecases becomes harder to reach is not a problem anymore as soon as *you* decide that it's not your goal, etc... Then it will be up to the user to decide !

**Comment by Solarer** [comment]
@quovadit thank you for your input and a happy new year!
All of your complaints are more or less related to how selection has been implemented so that needs to be improved.

1) The problem is that the image remains selected when switching to culling and selection has higher priority than anything else. I missed this case and will think about a solution. 

2) The first image does not become active once you enter culling with Ctrl-X - you need to move with the arrow keys / mouse wheel. I can fix this as well but I think it always was like this. I have not really touched that part of the code.

3) I think the right way to tackle this is to make it better visible to a user when he has an active selection and that he has to clear it if that is not what he desires. Additionally, I could also clear selection upon starting darktable and when moving the arrow keys we could jump to the last selected image instead at the top of the collection. How does that sound to you?
Ignoring images that are out of screen I deem problematic because it could just be by accident. If you select something in Nautilus and scroll further down, the selection would still be valid.
You can also select images by pressing space bar in file manager as you move around with the arrow keys so actively moving the selection could break this use case instead.

**Comment by Solarer** [comment]
@EC1000 I agree. Currently there is no GUI setting for this but it can be done with the `images_to_act_on_legacy=TRUE` in `darktablerc`. Note that you still can enter fullscreen with mouseover right now (with and without selection). Setting color label with mouseover also works but your selection has to be empty now.

@wpferguson good point mentioning Lua! I don't know if having it fully customizable will be necessary but it would not be straight forward to code. Certain combinations would break things for sure.

**Comment by quovadit** [comment]
> 1. will think about a solution

thanks!


> 2. The first image does not become active once you enter culling with Ctrl-X [...] I think it always was like this.

yes, it has always been like this, that's what I described in #7254, so it would be great if this could also be fixed in this PR


> 3. If you select something in Nautilus and scroll further down, the selection would still be valid.

That's true, but starting nautilus you never have selected (unvisible) items. 
And I do not see any usecase, where you want to act on selected images you don't see (even in nautilus).


> I could also clear selection upon starting darktable 

For me it would be ok to clear selection on start, but I can imagine there are users who like it, that the selection is remembered.


> when moving the arrow keys we could jump to the last selected image instead at the top of the collection. How does that sound to you?

This would be great. Perhaps we could even jump to the first selected image when starting dt

**Comment by Solarer** [comment]
@AlicVB Happy New Year,
I fully agree that we can and should do things in parallel to give people time to adept and make a choice. The reason why I completely changed the code in the beginning was that I thought the change would be smaller. Apparently it is not - so lets work in parallel because of the advantages. I already made the changes in the code base :+1: for `darktablerc` if a gui settings option is desired it can be added. 

The culling-thing is a different topic that I see independent of whatever happens to `images_to_act_on`. You are right, it is annoying to use the slider all the time but that is just a small detail that can be fixed. I propose to solve it as follows: Culling fixed remains hotkey `X` and culling dynamic gets a new hotkey (for example `C`) and it remembers the number of images to show (in your case 2). If you hit `Ctrl-C` you enter culling dynamic with the slider set to its max value. Hitting `C` again returns you back to 2. What do you think about that?

Currently the culling mode behaves differently depending on whether you enter it with an active selection or not and that is hard to understand especially since there is no graphical feedback. I think a change here would be for the better for all users independent of what they pick for `images_to_act_on` and could be as small as remembering a new key binding. It would have probably deserved its own ticket but it is a prerequisite to prioritizing selection so I had to do it first. I explained my reasoning for this in the top.

**Comment by AlicVB** [comment]
@Solarer : Happy new year to you too...

Thanks for your explanation. I now understand a little more your changes in culling. Effectively this should have deserve it's own ticket, but I understand that it's a prerequisite for all the rest of your work...
So let's speak about that for instance...

Your proposal about another shortcut is not really different than creating a third culling mode. That's not necessarily a problem, but better say it ;)
Now about the "new" culling fixed mode. You'll have a problem with the selection anyway I fear. Some usecases : 
1. select 2 images, enter culling fixed mode, go forward multiple times, click on "delete" => the 2 deleted images are the one of the beginning, not the ones shown in big in the screen ! (note that in this case, it's even worth, as the confirmation dialog says 'do you want to remove 2 files..." so you have no way to know that's not the right images)
2. select 'many' images, enter culling fixed mode, click on delete => the full selection is removed and you have no way to know which images are concerned if you don't show filmstrip (which is the case for lot of us, as culling need to avoid visual distraction as much as possible) Of course here the confirmation window can help you, but...
3. select many images, enter culling fixed mode, try to define a colorlabel to the better image (this is the goal of culling after all). You simply can't as the shortcuts will be applied to the whole selection... rating is still possible, but not with shortcuts anymore...
4. The same also apply to darkroom : select 2 images, go to darkroom, go forward multiple time, click on "export" in the export lib => this is not the current image that is exported...

for me, points 1 and 3 make the "new" culling mode completely useless (but if you still can use other modes...), and point 4 is completely a blocking point.

Anyway, and whatever the act_on algo, imho in mode where we show only specific images (fullscreen, culling, darkroom,...) user *always* expect that the action will be applied to the images shown on screen...

Generally speaking, I hope that all my remarks will not discourage you too much. I am aware that I am only pointing out problems without putting forward any real solutions... I apologize for this and thank you for your work!

**Comment by Solarer** [comment]
@AlicVB 
> Your proposal about another shortcut is not really different than creating a third culling mode.

Essentially, yes :stuck_out_tongue: but I thought we might be able to save some space like this. I don't have a preference here, we could go either way as long as a user does not have to use the slider all the time.

Again, thank you for your input! It does give me very good hints how to further improve the design but I don't see the same major problems as you do. Please let me explain:

Your use case 3) is covered by the new culling dynamic mode because here selection is ignored (see my first post). Otherwise it would be impossible to limit navigation to a selection and still work with the files. You are right, culling fixed does not work for 3) but that is by design. Culling dynamic should be used instead.

Case 2) I am not really sure what to think about this because I never disable the filmstrip. I see 2 potential answers here: 
- Culling fixed is the wrong mode because you really want to limit your work and navigation to the selected pictures (in that case culling dynamic would be the right choice - selection is completely ignored here and it would behave the way you want). If a user doesn't want to limit himself to the selection he should clear the selection once he does not need it anymore.
- The user should be aware that hiding an element of the UI does not change how the program behaves. You are right to point out that selecting 2 pictures and viewing 2 different pictures is a very nasty situation. But I think it can be solved by improving visualization. I probably should use the white box that shows up on mouseover for whatever `images_to_act_on` has in focus (here: the 2 selected images).

All 4 of your examples are based on a situation where a user does a selection of images but does not really want to do anything with it as a whole. My answer to that would be: `don't select images if you don't want to act on them` and I don't mean that in any arrogant or mean way but that is a direct consequence of the new `images_to_act_on` order. If `selection has priority about anything else` it is impossible to ignore selection in certain cases. The only way around that is to stick with the original `images_to_act_on`. If it is not possible to align the new code with the expectations of a part of the darktable community then the original `images_to_act_on` will have to remain in code as an alternative to satisfy their requirements and I don't see a problem with that. But maybe we should stop about thinking how to make a new `images_to_act_on` for those who are perfectly happy with the way it works right now. We cannot change and not-change something at the same time :stuck_out_tongue_closed_eyes:. Maybe a second ticket is required to fine-tune the existing algorithm but that would need to be done by someone else because my vision for it is what I coded so far so I am clearly the wrong person to do this fine-tuning.
> in mode where we show only specific images (fullscreen, culling, darkroom,...) user always expect that the action will be applied to the images shown on screen...

Fullscreen yes, I made an exception for that. Darkroom, you can probably ask 5 people and get 5 different opinions on it :laughing: so I will try to stick with the same behavior as all other modes (for now) for the sake of consistency. Culling, see above.

> I hope that all my remarks will not discourage you too much. I am aware that I am only pointing out problems without putting forward any real solutions...

No worries, I think your critique is very constructive and you don't have to come up with solutions for problems that I design. 
That being said, maybe there is no way to reach a unified solution for everyone. I hope that we can at least find a common basis regarding culling because I don't think we should put more if/else blocks in other places outside of `images_to_act_on`. We can implement an alternative `images_to_act_on` but we should not do that for culling.

**Comment by Solarer** [comment]
Update:
- No longer highlight mouseover ALWAYS but instead highlight the current `images_to_act`. This should make it clearer if a user acts on selected pictures, mouseover or active images. This is also an improvement for people using the legacy `images_to_act_on` in filemanager layout since it makes it more visible that using mouseover on a selected picture picks the whole selection and not just a single image.
- When entering culling with a single selected picture we drop the selection because the user probably only clicked the image to mark it as a starting point for culling instead of actively wanting to "select" the image.

**Comment by Solarer** [comment]
@quovadit I hope this fixes 1) and 3) for you. 
I did not make the cursor start at the last selected picture since it felt unnatural. Maybe we can add something like `Alt+Arrow Key` skips through selected images. But I would do that outside of this PR.

**Comment by quovadit** [comment]
My issue in culling fixed-mode is fixed now, so after pressing the right arrow only one image has a white border, and this image gets the rating (OK).

But now the initial status when starting culling fixed-mode is as wrong as in culling-dynamic:
Both images have a white border (NOK) and both get the rating (NOK).

The filemanager issue is unchanged, so you can still act on images you don't see, which is never expected in my opinion, especially if you highlighted a different image with the cursor.

**Comment by Solarer** [comment]
@quovadit I believe I fixed your issues with culling now.

In culling dynamic it was always the case that all images were active and I did not change that. Are you implying that you want a different behavior?

> The filemanager issue is unchanged, so you can still act on images you don't see, which is never expected in my opinion, especially if you highlighted a different image with the cursor.

Yes, it still acts on images you cannot see because I see no way how to get a consistent behavior if I do not do it that way. If you scroll up in #6025 you can find a post where I collected issues related to this and most of them complain about inconsistencies. To tackle that I tried to make it a lot clearer on what images a user does act:

- Old behavior (old images_to_act_on):
If you hover an image within a selection, you will act on all selected images. But the interface does not make this clear, since only one image is highlighted. So a user could think he acts on only one image instead of selection.


In this image the user will only act on 1 image. There is little visual difference to the image above.
image

- New behavior (old images_to_act_on):
I now highlight `images_to_act_on` so the full selection will now be highlighted when mouse over is in selection


- New behavior (new images_to_act_on)
This should also make clearer that the mouseover has no effect if a selection is active (notice that there are no rating stars on the mouseover image). It will work the same way for selected images that you cannot see.


It would then be the user's responsibility to remove the selection once he is done with it.

-----
Similarly, in culling there is now a white border around all `images_to_act_on` if there are multiple. Of course if we use arrow keys to navigate, only the first one will be highlighted (same way as before).


This should make it clear if you selected other images than the ones we see on screen:


Again, the user can now clear his selection if he is done with it.

**Comment by Solarer** [comment]
I also played a little bit with the CSS styles so that I can see the difference between selection and active images. (not yet in git repo)
image

We can probably find something that looks better than this works quite well already.

**Comment by quovadit** [comment]
> In culling dynamic it was always the case that all images were active and I did not change that. Are you implying that you want a different behavior?

yes, I am. I don't see a usecase where multiple images should be active in culling.
To cull is to pick something, so while I am seeing multiple images at once to compare them, I pick (=rate) only one of them. 

So it would be great if (in both culling-modes) only the first visible image would be active initially and when the mouse leaves an image after mouseover. 

This would also be consistent to full preview and darktable, where only one image is active.


But I love the fact, that now it's always clear which image(s) will get the rating, because of the white border.

So maybe we should use this white border even in filemanager:
- all images to act on have a white border
- if there are selected images: 
  - those images have a white border
  - mouse-over does not highlight the image at all (no white background)
  - but if '[extended] overlays on mouse hover' is chosen, mouseover should show rating and color-labels.
- if no image is selected:
  - the mouse-over image gets a white border

And I think there should be a button to clear selection in order to 'enable mouse-over-acting'.
(maybe in the header where the number of selected images is shown).

By the way: I liked the old version with '0 images of 42 in current collection are selected', because it's explicit that no image is selected. 

Maybe it could be extended to "0 images of 42 selected, 1 image (#21) active (mouseover)"

And I would differentiate, which actions will be applied on selections, and which on active images:
- only rating and colorlabels (which get visible on mouseover), should be applied on mouseover
- actions like 'remove' (shown in the module 'selected image[s]' should only be applied on selected images
  - so if no image is selected, I mouseover one image and press 'del', nothing should happen
  - currently it's weird that the buttons get active on mouseover, but as soon as I move the mouse to the buttons, they get inactive

**Comment by Solarer** [comment]
> I don't see a usecase where multiple images should be active in culling.

It does make sense for culling dynamic. You might start out with 10 images and once you narrow down your selection to your favorite 3, you want to give all of them a 5 stars rating.
I will not change this for now because I do see a use case there. But I am thinking about a different improvement here. 

Not sure what you mean by '[extended] overlays' but from other discussions my impression was that a lot of thought was put into the visualization and brightness of different UI elements in darktable and changing things there without discussing it will cause trouble. I would like to keep visual changes small for now.

> there should be a button to clear selection 

There is. It is right in the first module on the right. You can select all, none, invert selection...

> I liked the old version with '0 images of 42 in current collection are selected', [...] extend to [...] 1 image (# 21) active (mouseover)"

The idea was to make it easier to see when a user selects a picture because the text gets a lot longer. The difference between a 0, 1, 8 or what ever number is more subtle and might be missed. Maybe displaying the images to act on is enough -  I would like a few more opinions on that and change it back if displaying a 0 is preferred. But I would not add the active image information because you can already get it from the image details module on the left.

Actions should always be applied the same or it will not be consistent and people will continue to raise tickets. But I understand your remark because of the buttons lighting up. Maybe they should stay dark on mouse over. But that should be a separate ticket because it is a separate issue. Can you open one?

**Comment by Solarer** [comment]
Or you allow a mouse click to stick to an image so that you can move the mouse to a button. Again, this deserves a separate ticket

**Comment by Solarer** [comment]
@AlicVB, can you point me into the right direction on how to:
-  create a new menu entry in the preference menu so that I can implement an option to pick the `images_to_act_on` algorithm?
- change the current behavior of the `Ctrl-X` key binding in order to adjust to my changes in culling?
I searched for a while but was unsuccessful

**Comment by AlicVB** [comment]
> * create a new menu entry in the preference menu so that I can implement an option to pick the `images_to_act_on` algorithm?

looks into `darktableconfig.xml.in`, you have to add an entry like `<dtconfig prefs="lighttable" section="general">` and everything will be done automagically at compile time.



> * change the current behavior of the `Ctrl-X` key binding in order to adjust to my changes in culling?

this is defined in `libs/tools/lighttable.c` note the "tools" part : it's the bottom toolbar which shows the icons to switch lighttable modes... then you have `init_key_accels`

**Comment by Solarer** [comment]
These last commits should address most issues that have been raised until today and the experience should be quite smooth now. Please let me know what you think

### Changes

* added an option in preferences `miscellaneous/act on algorithm/images to act on order` to choose between the old and new `images_to_act_on` order/algorithm.
* added an option in preferences `miscellaneous/act on algorithm/force mouseover priority` to allow users to choose if they want the mouse over option to have highest priority or not. You can choose between `never` (default), `always` and `only copy and paste` which will only impact the copying of edit history in darkroom.

image

* renamed culling layouts to better reflect how they behave and added shortcuts (I am open to different names and a better button design for the `"dyn"` button

|Layout |Description  | Shortcut|
|--- | --- | ---|
|**culling**| same as old culling when entering without a selection. movement unrestricted even if a selection is present.|`C` (new)|
|**culling restricted** | same as old culling when entering with a selection. movement limited to selected images. shared zoom slider position with regular culling |`X` (same as before)|
|**culling dynamic mode**| same as old culling dynamic. can now be enabled by a small `dyn` modifier button that is only visible when in culling restricted layout. can also be reached directly via same shortcut as before. remembers its last position.|`Ctrl-X` (same as before)|

image

### Known bugs that I was not able to fix (help required):
* for some reason when starting darktable the `dyn` button is always visible even though I hide it in all modes except culling restricted via code. I think something forces it to become visible again. Switching layout once after starting dt fixes this issue. I do not know what forces the button to be visible on startup
* a few commits back I made the change to highlight `images_to_act_on` in `_event_main_motion`. That means when entering the thumbtable with the mouse cursor, `images_to_act_on` gets called BEFORE `_event_motion_notify` can set `table->mouse_inside = TRUE;` . Thus the `if-else` block in `act_on.c` 
```
// column 1,2,3
  if(dt_ui_thumbtable(darktable.gui->ui)->mouse_inside)
  {
    // column 1,2
    sqlite3_stmt *stmt;
```
returns false when entering the thumbtable for the first time. Moving the mouse to a subsequent image solves the problem

**Comment by Solarer** [comment]
I tried to keep my last message short in an attempt not to overload it, sorry if that led to more confusion. I will try to explain:

### Act on

The central change in this PR regards a new `images_to_act_on` algorithm. During the development it became clear that some part of the community is happy with the way how it works right now and they don't want and don't need a change. So we need the option to choose between the old and new algorithm. That is the first new preference field. I could have called the options old/new, legacy/refactored but that does not really explain what the difference between them is so I included the priority chain in the name:

old algorithm: `mouseover selection > mouseover > active > selected`
new algorithm: `selection > mouseover > active`

Now, I personally think mouseover should never have priority over selection to avoid accidents but that is personal taste and some people want to use this as a feature to speed up their workflow, so I added a second preference for that. Maybe the naming is bad but it is the same as your 'point-and-shoot' button in screen 2, but as a preference instead of a button: If you leave `force mouseover priority` == `never`, 'point-and-shoot' is disabled but if you select `always` it gets enabled and the order changes to:

old algorithm: **(mouseover)** > mouseover selection > ~~mouseover~~ > active > selected
new algorithm: **(mouseover)** > selection > ~~mouseover~~ > active 

I am not opposed making it a button, but I am not sure if it is necessary. You could just leave it on all the time and be careful about your mouse position if you don't want to use it. (Yes, in case someone sticks with the current images_to_act on, there is almost no difference what they pick for `force mouseover priority` since mouseover already has very high priority.)

There is also a third option `only on copy and paste` which is somewhat an attempt to find something in the middle between on and off. In #6025 people said that they want mouseover to take priority over selection so that they can easily copy and paste edits in darkroom (Ctrl-C/Ctrl-V). This option enables this behavior but does not change the mouseover priority for other things such as color labels, ratings, etc. 

### Culling
I am not sure if I made this clear, but I only made a visual update here! There were always three culling modes, there was just no way to tell them apart visually.

Darktable 3.8 behaves differently whether you enter culling and then select 4 images or first select 4 images and then enter culling. In the first case your movement is not restricted, in the second case it is. So I made a split here into culling modes `C` and `X`. In `C` you are unrestricted, no matter in which order you entered the layout and selected images and in `X` you are always restricted to a selection and therefore cannot enter without selection (also, selection is ignored for images_to_act_on because you always have something selected). That is the only difference.

Culling dynamic could have stayed its own mode but navigation is also restricted and you cannot enter without selection so the only difference between `X` and culling dynamic is the amount of images displayed. Therefore I merged them and left its original key binding `Ctrl-X` intact. 

#### your questions
> none of them seems to do what I would like to do:
go through a collection of images, and rate one image after the other, so during the whole process of culling only and exactly 1 image should be hightlighted, regardless whether I just started culling, moved the mouse after hovering over one image (to see the exif data), or pressed an arrow-key.

The normal culling mode `C` still does exactly all that with one exception: moving the mouse over an image removes the `mouse over` status and all active images are highlighted until you move an arrow key or move the mouse to an image again. You seem to be unhappy about it but it always worked this way - I only made it visible and I am not sure if this is a bug or a feature. Can you please open a separate ticket for it and ask if it is a bug or a feature? If people agree that it should be changed I will gladly change it for you within a day. But I do not want to remove stuff that people might use without clarification. Sorry.

> you can act on images you don't see

I do not fully get this point. I just checked and you can also act on images you don't see in darktable 3.8 **today**! Go to file manager, select some images, use the scroll wheel or slider to move them out of sight, press `4` and scroll back up -> images have 4 star rating. 
There are only 2 scenarios in which you do not act on selected images that are not visible:
1) in filemanager when you have a mouseover via mouse cursor or arrow-keys active - but that is not because we ignore images out of screen - it is because mouseover has **higher priority** than selection and we ignore **all** selected images (even the ones on screen).
2) in culling because active images have higher priority than selection and we therefore **always** ignore **all** selected images (even the ones on screen).

Changing both is the whole point of this PR. I could see the following adjustments:

1) Try setting `force mouse priority` to `always` and see if it behaves as you want. It will also change the behavior of 2). If you need to enable/disable it, it could be solved by a shortcut to your 'point-and-shoot' button which does nothing else than toggling `force mouse priority` between `always / never`  (can you try this by hand and see if such a shortcut would you the right result). Third alternative is a shortcut to release your arrow-keys-mouseover (you could test this by moving your mouse which removes mouseover)
Remember to set  `selection > mouseover > active` first.
Note, that this is only an **indirect** change to how to handle "invisible" images by changing the priority. I don't want to handle images off-screen different than on-screen.

For 2) you should release your selection via `Ctrl-Shift-A` or go to culling restricted mode `X` where selection is ignored for images_to_act_on and you only act on the first visible image (we have to ignore selection here because we never have zero images selected). Your 'point-and-shoot' button would bring the same result. If this is not an option to you, please explain why.

**Comment by wpferguson** [comment]
Just a thought.  Should all of the culling changes be moved into a separate PR and this one just focus on images to act on?  Just testing images to act on is going to be enough fun without adding other stuff too.

**Comment by AlicVB** [comment]
@Solarer : I've really hard time to follow your work here... I'm not sure we are going in the right direction.

In my mind, your work was a matter of implementing another algorithm for the image_to_act_on function... so it should have only modified this part of code. Eventually, you may have need to punctually adapt some small things but that's all...

Now you end up proposing a very complex PR which change a lot of things in a lot of places in the code, including key features, including things that would change whatever the chosen algo...

imho, for devs, that's simply won't be possible to review or discuss : example : example : how can I review the algo *without* the changes done in culling, ...

And, don't misinterpret my words : I agree to the fact that we should propose that new image_to_act_on algo

What I would propose is the following : 
1. pose clearly what should do the algo (I think you've done that)
2. evaluate clearly what other changes are *mandatory* for your new algo
3. for each change, open a PR/FR in which we can discuss the consequence of this change for the current implementation : as a matter of fact, we know quite well this part, and we can help you pointing issues...
4. we decide collectively if your change should be done in all cases or if you need to encapsulate so it's only available with your new algo.

You already have done 3 & 4 for some points (#10788, #10771), and that's a lot easier for us to review and discuss !

**Comment by Solarer** [comment]
I would like to split it up in 2 separate PRs but there will be one problem:
The change to culling is a prerequisite for the new `images_to_act_on`. If I want to make selection have a higher preference than active images (and mouseover), culling will not work properly anymore for all the people that want to work on a subset of images (by selecting images before entering culling or what I call restricted culling `X` in this PR). That mode is meant for making changes to **individual** images in a selection - not all of the selection. If selection has higher priority than mouseover/active images this mode will not work anymore as designed. 

Therefore the new `images_to_act_on` ignores selection in that mode. The reorginization of culling makes this visually transparent. If I split this PR I could check if `navigate_inside_selection` is true and ignore selection in that case but then `images_to_act_on` will behave differently depending on how you entered culling. This might be even harder to evaluate/test. 

If we want to discuss both things separately, we should start with the culling changes and put this PR on ice until then.
Or is there another good way in git to do this if branch B depends on branch A?

**Comment by AlicVB** [comment]
Thanks for your reply (and sorry for all the hassles I put on your work)...

> If we want to discuss both things separately, we should start with the culling changes

yes, that's exactly that... if that's possible for you that would be great !



> Or is there another good way in git to do this if branch B depends on branch A?

I'm far from a git expert, but that may work by rebasing your "new_act_on" branch on your "new_culling" one...

**Comment by Solarer** [comment]
ok, I can try and do that. Might take some time, though

**Pull request closed without merging**
