### PR TITLE
Switch CI to Ninja, fetch tag for nightly

### PR DESCRIPTION
**Pull request by kmilos**
Re https://github.com/darktable-org/darktable/issues/9745

Ninja builds have been working on my local machine for quite some time now (since 3.5), maybe I just skipped the problematic CMake version...

### CODE REVIEW

**Comment by wpferguson** [comment]
What does switching to Ninja gain for us?

**Comment by kmilos** [comment]
The build takes somewhat less time w/ Ninja as it is (supposed to be) better at utilizing multiple cores, which is beneficial for CI which runs several times a day and, therefore, the environment.

Unrelated to CI, it also figures out incremental builds better than make, so developers can have a shorter cycle as well.

For infrequent release/test builds from scratch I agree it does not make a huge difference.

**Comment by wpferguson** [comment]
I tried Ninja and it appears to work without problems.  I believe that the way we're building releases is what we should be testing with, so if we want to move to Ninja then we should do it early in the cycle so that it gets plenty of testing via the darktable insider program.

**Comment by TurboGit** [comment]
> I tried Ninja and it appears to work without problems. I believe that the way we're building releases is what we should be testing with, so if we want to move to Ninja then we should do it early in the cycle so that it gets plenty of testing via the darktable insider program.

Fully agree, we really need to be consistent on the build procedure.

**Comment by kmilos** [comment]
Sure. Mind you, we built w/ Ninja as default on the CI in the past.

**Comment by kmilos** [comment]
@wpferguson It also turns out one needs to `lensfun-update-data` _before_ CMake configuration, it is too late to be picked up in the packaging step (`/var/lib/lensfun-updates/version_1` doesn't exist at configure time on a clean system, or is out of date)...

**Comment by johnny-bit** [comment]
Ninja looks stable after recent changes... We could switch to it on other builds too to gain a bit of speed for all 40+ actions...

**Comment by kmilos** [comment]
The Windows CI is failing again, presumably because MSYS2 no longer install Autotools implicitly in their base-devel.

@TurboGit @wpferguson @johnny-bit Can we please merge this already?

**Comment by johnny-bit** [comment]
I'm all for it! My only "addition" would be to switch to ninja on other platforms (or create matrix with makefiles if somebody wants it)

**Comment by wpferguson** [comment]
I've tested on windows and it appears to work fine.  If we are going to do it, now would be a good time so that it can get plenty of testing prior to 4.0.

My only question is who is the Ninja expert in case there are problems?

**Comment by kmilos** [comment]
One can always reach out to MSYS2 devs.

**Comment by kmilos** [comment]
I have now added the generator to the matrix and switched it to Ninja only for all platforms. All tasks pass, so let's go already 🚀

The Windows build instructions are updated accordingly as well.

**One last thing:** I think we should remove the Windows packaging and uploading from the CI (we don't do it for other platforms, and I feel it is a bit wasteful to do for every single PR), should be sufficient to only have them in the nightly build. If OK, I will then make one more commit?

**Comment by johnny-bit** [comment]
> I think we should remove the Windows packaging and uploading from the CI (we don't do it for other platforms, and I feel it is a bit wasteful to do for every single PR), should be sufficient to only have them in the nightly build. If OK, I will then make one more commit?

I'm ok with that!

**Comment by TurboGit** [comment]
> **One last thing:** I think we should remove the Windows packaging and uploading from the CI (we don't do it for other platforms, and I feel it is a bit wasteful to do for every single PR), should be sufficient to only have them in the nightly build. If OK, I will then make one more commit?

Fully agreed !

**Comment by kmilos** [comment]
Argh, the latest macOS failure is due to some Homebrew download error unrelated to this change. The previous commit was all green, so I still think this is good to go...

**Review by TurboGit — APPROVED** [review]
Thanks! The darktable version 3.8.1 is almost ready now and anyway this does not touch the de source code. So let's bit the bullet :)

**Comment by kmilos** [comment]
Merci!

**Pull request merged**
