### PR TITLE
histogram: fix button tooltips

### PR DESCRIPTION
**Pull request by elstoc**

### CODE REVIEW

**Comment by elstoc** [comment]
Ultimately I think this is probably a workaround to a Gtk bug but it's less bad than no tooltips until someone can come up with a better fix.

**Review by TurboGit — APPROVED** [review]
Working, nothing better to propose. Thanks.

**Comment by elstoc** [comment]
The only downside I found is that if you move your cursor while over the icons, the tooltip moves about / redraws with the mouse because its content is being continually updated. But I tried a load of alternative fixes and nothing else worked.

**Comment by dtorop** [comment]
@elstoc I appreciate your working on this one, and glad that you found an angle on it... I'm curious as well if it's a GTK bug, or if this is a sort of overlaying of widgets which GTK was never designed to handle...

**Comment by elstoc** [comment]
I'm not sure either but on balance I'm inclined to believe it's a bug, since my fix really should have no effect - the tooltips at this point are already correctly set (I checked). I saw some reports suggesting that if you don't put the buttons in a container it works but I couldn't work out how to do without the ButtonBox. I only stumbled on this solution because the "clicked" action temporarily restored the tooltips, so I just tried replicating what it was doing.

**Pull request merged**
