### PR TITLE
Colorbalancergb colorwheel

### PR DESCRIPTION
**Pull request by lemirep**
**colorbalancergb: add ColorWheel control**
    
Although the sliders are a convenient way of setting the various parameters they
have the caveat of not being very intuitive for uses to visualize common color
theory patterns.

For these reason, the above patches add a simple color wheel control which
allows to visualize which hue/chroma the shadows/midtones/highlights are
being set to.

It can serve purely for visualization purposes or can be interacted with as an
alternate way of changing hues / chromas.

As the chroma is rarely set to a very high value and more often to low values,
the color wheel uses a non linear scaling so as to make it easier to set values
in the usual target range.

- Maintaining Shift while dragging make changing hue in steps of 10 degrees and
  hues in step of 0.1 on the non linear scale.

- Maintaining Control while dragging locks the chroma so that only hues can be
  changed

- Mouse Scroll will increase/decrease hue by 10 of closest cursor on the color
  wheel

image

### CODE REVIEW

**Comment by TurboGit** [comment]
So going from center to outer border you are changing the luminance and chroma?

**Comment by elstoc** [comment]
It looks pretty but this module was already one of the largest (in terms of vertical space taken) and I fear this addition makes it _too_ big.

**Comment by TurboGit** [comment]
> It looks pretty but this module was already one of the largest (in terms of vertical space taken) and I fear this addition makes it _too_ big.

Agreed, we have the following options:
- reject this PR
- add the colorwheel into a collapsible section
- add the colorwheel in its own tab

**Comment by lemirep** [comment]
> 

No only chroma gets modified. Luminance can only be changed with the sliders.

**Comment by TurboGit** [comment]
> > 
> 
> No only chroma gets modified. Luminance can only be changed with the sliders.

Ok, so we need sliders + colorwheel which is too much a a single display.

Maybe we can have a module layout option to select between the current UI or the colorwheel plus the luminance sliders only?

**Comment by TurboGit** [comment]
Just a note: Don't jump on any implementation until we have discussed the way to go. Or do it if you are ready to rework it again :) TIA.

**Comment by lemirep** [comment]
I can look into making it collapsible. Having it into its own tab might not be practical if you have to switch back to the sliders tab to change the luminance values.

I could investigate adding circular sliders around the wheel to control luminance though. This would allow having into its own tab.

**Comment by elstoc** [comment]
On the whole, while I like the thought behind this, I'm not sure it really adds anything, or not enough to justify the extra UI "clutter" (for want of a better word). I think the sliders are better and we don't need more options - let's choose one way of doing things and stick to it. IMO the current implementation is fine.

**Comment by jenshannoschwalm** [comment]
> Maybe we can have a module layout option to select between the current UI or the colorwheel plus the luminance sliders only?

If we would had a collapsible section for the colorwheel, we could hide the chroma and hue sliders depending on the collapsed state?

**Comment by TurboGit** [comment]
> If we would had a collapsible section for the colorwheel, we could hide the chroma and hue sliders depending on the collapsed state?

That's a possibility to explore, but then how to display the three areas in the colorwheel with different luminance? A single colorwheel controlled with three luminance sliders seems impossible to me. @lemirep : What would be your proposal around that?

**Comment by lemirep** [comment]
I was thinking about adding a circular slider around the color wheel to control the luminance, similar to what color wheels in DaVinci Resolve or Capture One are doing:
image

Obviously we wouldn't be able to view the luminance for highlights/midtones/shadows at the same time, one would have to either hover or click on one of the cursor/handles on the color wheel first and the slider would show the luminance for the selected cursor.

At that point, the Color Wheel could be in its own tab though

**Comment by elstoc** [comment]
Sounds complex (from a ui point of view)

**Comment by jenshannoschwalm** [comment]
Or even worse more confusing than helpful?

**Comment by lemirep** [comment]
Does it? If you can scroll to change the value of the luminance slider when the mouse is hovering it that should be quite straight forward. Such a color wheel tab would take up half the space the current 4 ways tab does. 
Also it would give users the choice of either using sliders in the current existing tab or switch to the color wheel for people that needs to visualize better how grading of the different shades related to one another. Doing things like split complimentary with purely the sliders is, I find, more tedious that what a color wheel would allow.

**Comment by elstoc** [comment]
> Also it would give users the choice

I'm all for choice but sometimes it just looks like we can't make up our minds.

**Comment by MStraeten** [comment]
how to set 3 different values via right click and manual typing? quite simple for separate sliders ...

**Comment by lemirep** [comment]
Well I perceive a lack of enthusiasm for changing the way this module is currently controlled :)

I can understand concerns with the wheel taking too much space when used in conjunction with the sliders. 
Having it in its own tab would solve that and leave users the choice of which interface he finds is more intuitive.
But that would be confusing, offer too many choices... 
Ok but couldn't the same thing be said of the bauhaus slider? I'd rather see it as offering different ways of interacting with it, choice being left to the users to find what suit them best.

I can't help but wonder why all other color grading software either enforce the color wheel or provide the option of switching between wheel and sliders...

I understand this is an iterative process and my current approach might not be the best. I'm happy to discuss in good faith and rework the wheel so that UI occupation, intuitiveness and ease of use are the best I can make them to be. Yet if that's not going to be sufficient or not provide any value for darktable users, you might as well close the PR now.

I'm happy to live with that feature only in my own fork after all.

**Comment by wilecoyote2015** [comment]
In my opinion, the colorwheel improves the UX significantly and is worth the additional interface complexity.
In particular, the circular slider seems quite intuitive for me. I could imagine having the corresponding slider shown when as soon as hovering over one of the three handles in the colorwheel and changing the slider by ctrl+mouse drag starting from the corresponding handle.

Is the backdrop color managed?

**Comment by TurboGit** [comment]
I would like to propose another more global and generic way of handling this.

My proposal would be to create a new widget (see dtgtk as examples) for controlling colors. That is, having a single widget with different views. One would be the current 3 sliders, then we could have another view of the same widget with a colorwheel and a luminance slider. Later we could also add more way to control it (RGB, CMJN or whatever). In all cases the widget will be able to deliver the three needed values : Luminance, Hue and Chroma.

This widget would be used anywhere we have currently a way to select a color. Using some kind of prefs user's could change individually the kind of UI for some modules.

**Comment by lemirep** [comment]
> Is the backdrop color managed?
Yes it should be. I used the same code that was used to paint the color sliders which uses the output color profile

**Comment by lemirep** [comment]
> My proposal would be to create a new widget (see dtgtk as examples) for controlling colors. That is, having a single widget with different views. One would be the current 3 sliders, then we could have another view of the same widget with a colorwheel and a luminance slider. Later we could also add more way to control it (RGB, CMJN or whatever). In all cases the widget will be able to deliver the three needed values : Luminance, Hue and Chroma.

How would we go about having the 3 shades (shadows, midtones, highlights) on the same widget at the same time? The Color Wheel would allow that quite easily but for the sliders, we would need to expand that to 3 slider per shades.

**Comment by TurboGit** [comment]
> How would we go about having the 3 shades (shadows, midtones, highlights) on the same widget at the same time?

No, we would have 3 colorwheels. On colorwheel for each area where a color is being selected. And we should be able to change the UI of each widget individually. This would be used in colorbalance but also in other modules where we have similar selectors.

My idea is to really create a generic widget to select a color from 3 sliders or a colorwheel and 1 slider and use it consistently in all the modules to avoid reinventing the wheel (no pun intended) all the time.

**Comment by lemirep** [comment]
Ok I see, I'll get started on that over the next few days then.

**Comment by paperdigits** [comment]
It isn't clear to me how this is an improvement over what we have now. The sliders and the vectorscope proved a ton of information about what is happening.

I'm still on 1080p monitors, and Color Balance RGB takes up almost all of my vertical space. If I want to add a parametric mask, I'm scrolling the module. Vertical space in darktable is gold. 

If this is really better, lets get rid of the sliders and replace all color sliders with this, but I don't feel that way.

We need to pick a UI concept and go with it. This free-for-all is confusing.

**Comment by lemirep** [comment]
@paperdigits 
> It isn't clear to me how this is an improvement over what we have now. The sliders and the vectorscope proved a ton of information about what is happening.
Not sure how a vectorscope is related to a color wheel in this very context. There's as related as the exposure slider is to the histogram.

> 
> I'm still on 1080p monitors, and Color Balance RGB takes up almost all of my vertical space. If I want to add a parametric mask, I'm scrolling the module. Vertical space in darktable is gold.

Even some of the smallest modules with a parametric mask take almost the full height. Having a color wheel with all the shades cursors on it would have taken up 50% less space than the current sliders.
> 
> If this is really better, lets get rid of the sliders and replace all color sliders with this, but I don't feel that way.
> 
Have you given the patch a try? If so what makes you feel it's inadequate. It's hard to improve upon something if no one clearly defines what makes them feel a certain way.

**Comment by MStraeten** [comment]
it’s not about a patch, it’s about an UI concept, how to deal with color in general: separate slider makes it easy to use the mouse as well as keyboard or rotation controls on further devices. 
A consistent UI concept has to be defined first, then do patches for the master. Maybe better to branch for that UI stuff and integrate the stuff once it’s mature enough.

**Comment by lemirep** [comment]
@MStraeten you're right, I'll just do stuff in my own fork while you guys figure out if you ever want to have anything better than a slider.

Apart from @TurboGit, no one has proposed anything  beside _feelings_ and stating how a color wheel would just add confusion. 

My intent was to provide a visual cue for people who want to apply color harmony principles (complimentary colors, split complementary, triads...) where sliders falls short. Or do they....

Right now, there are simply too many constraints to please everyone:
- takes too much UI space
- would be too confusing if the color wheel was in its own tab
- would overwhelm users if we offer the option of choosing between sliders or color wheel to represents YCH colors
- needs a unified UI concept everywhere

Now if you add the fact that there's very little constructive criticism, just feelings that it's no good, no explicit reason, proposition or solution discussed, I don't see the point in me trying to contribute anything at this stage.

People who are interested can always cherry-pick my patches and see if it works out for them or there's something they can reuse.

I would have appreciated any feedback on the current implementation that no one has bothered to try.

@TurboGit thanks for trying to come up with a solution that would please everyone and your continued investment in the project over the years.

**Comment by TurboGit** [comment]
@lemirep : I find it sad that you don't still plan to implement the new generic widget as discussed. This is generic (and will be good code sharing saving lot of code everywhere), it will be a 100% the same UI by default and will let people use a colorwheel if they like. I don't see why this would hurt someone... But I can understand that you lost motivation!

**Comment by paperdigits** [comment]
I feel like we should have some process for larger UI changes. There needs to be a process to refine and agree on things before people write any code. This is the same thing that happened with the sigmoid PR.

When large changes show up, its hard to change them. There is sunken fallacy cost, and also since the code is already written, a stronger need to be a hard yes/no to include it.

We should also decide on a UI paradigm, as has been shown with the changes to the filtering module as well as this.

On August 13, 2022 7:50:44 AM PDT, Paul Lemire ***@***.***> wrote:
***@***.*** you're right, I'll just do stuff in my own fork while you guys figure out if you ever want to have anything better than a slider.
>
>Apart from @TurboGit, no one has proposed anything  beside _feelings_ and stating how a color wheel would just add confusion. 
>
>My intent was to provide a visual cue for people who want to apply color harmony principles (complimentary colors, split complementary, triads...) where sliders falls short. Or do they....
>
>Right now, there are simply too many constraints to please everyone:
>- takes too much UI space
>- would be too confusing if the color wheel was in its own tab
>- would overwhelm users if we offer the option of choosing between sliders or color wheel to represents YCH colors
>- needs a unified UI concept everywhere
>
>Now if you add the fact that there's very little constructive criticism, just feelings that it's no good, no explicit reason, proposition or solution discussed, I don't see the point in me trying to contribute anything at this stage.
>
>People who are interested can always cherry-pick my patches and see if it works out for them or there's something they can reuse.
>
>I would have appreciated any feedback on the current implementation that no one has bothered to try.
>
***@***.*** thanks for trying to come up with a solution that would please everyone and your continued investment in the project over the years.

**Comment by MStraeten** [comment]
> My intent was to provide a visual cue for people who want to apply color harmony principles (complimentary colors, split complementary, triads...) where sliders falls short. Or do they....

if that’s your intent, then have a look at the colorcorrection module. Maybe that’s a better starting point for this purpose.

**Comment by emko** [comment]
> > My intent was to provide a visual cue for people who want to apply color harmony principles (complimentary colors, split complementary, triads...) where sliders falls short. Or do they....
> 
> if that’s your intent, then have a look at the colorcorrection module. Maybe that’s a better starting point for this purpose.

how does that help with colorbalance rgb?

**Comment by paperdigits** [comment]
> how does that help with colorbalance rgb?

There is a color wheel implementation there of some sorts.

**Comment by MStraeten** [comment]
> how does that help with colorbalance rgb?

to achieve a proper UX you need to differentiate between the use use case and tools.
If there’s a better module to fit your use case, then tweak that.
If you need bread you won’t try to change your butchers business ;)

If you just want to replace some sliders by a set of color wheels that’s a different job. And as turbogit stated: that should be done with a generic widget that can be reused to achieve a consistent UX. Also important as paperdigit writes: that’s a large change on the UX so it’s worth to discuss that before patching some stuff at just one place.

**Comment by spaceChRiS** [comment]
Why cannot both be achieved at the same time: A generic widget that can hold 1, 2, 3 or 4 points. For a generic widget this would be needed anyway, as it is often not only 1 color but a color range with ramp that has to be selected. When the widget can handle 1, 2 or 4 settings, why not add the 3 required here as well?

For the luminance input, there already is a widget for this purpose, why not reuse the design to stay consistent with the available UX?
grafik
I know it is a bit different to the use case here, it's not an overlay of the image but of the color circle, the middle ring would not be required, and it could be more compact for the purpose discussed here, but at least it would not look different and do the job.

About the learning curve for users, I think this would be pretty straight forward and self explaining. The hovered point shows the overlay and can be tuned with the mouse wheel, and when the mouse leaves the point, it's still highlighted (bold circle instead of thin circle), such that it is clear that the one slider below (or circular slider around the circle) is linked to this point (for those that do not have a mouse wheel).

For the case of selecting 2 colors (with or without ramp), this would even simplify selections that are not easily possible yet, e.g. selecting all colors from violet to orange in the case below:
grafik

**Pull request closed without merging**
