### PR TITLE
Show an error message window when we can't run due to too new database version

### LINKED ISSUE #15673: The user may not know the reason if dt terminates due to a too new version of the database
A situation is possible when a user created (or updated) a database with a version of darktable that created a schema of a newer version, and then runs a darktable build that does not support such a new version.

For example, a user installed multiple releases of darktable (with different schema versions) and hoped to run them alternately. Or installed a development snapshot (and updated the base), and then wants to return to work with a stable release.

A user running the program from the OS desktop by clicking on the icon will not be able to see the error message printed on stdout. And on the Windows platform, even launching from the command line will not help, since all printing goes to the log file.

Therefore, in this case, we need to report the reason for the termination of the program in the GUI window.

### PR DESCRIPTION
**Pull request by victoryforce**
Resolves #15673.

### CODE REVIEW

**Comment by TurboGit** [comment]
Not working on my side, I still have on the console:

```
     0,0575 [init] database version of `library.db' is too new for this build of darktable. aborting
     0,0577 ERROR : cannot open database
```

But there was no GUI dialog displayed!

**Review by TurboGit — CHANGES_REQUESTED** [review]
Looks like `has_gui` is `false` at this stage maybe?

**Comment by victoryforce** [comment]
> Looks like `has_gui` is `false` at this stage maybe?

No, this can't be. I'll take a look soon.

**Comment by victoryforce** [comment]
OK, I checked. Sorry, I was working on this on two computers and mistakenly pushed from the one where the unfinished version was, so the error window was only triggered when the data.db was too new. I have now added to PR the display of a window when the library.db is too new.

**Review by TurboGit — APPROVED** [review]
Working for me now, thanks!

**Pull request merged**
