### PR TITLE
thumb : add configurable tooltip

### LINKED ISSUE #4441: [FR] helpful UX additions in lighttable view
**Is your feature request related to a problem? Please describe.**
Currently lighttable has 2 problems as identified by user:

1. After clicking `?` the whole lighttable area is one big 'X' with contextual help
2. when hovering over image in file manager mode, there's no tooltip

**Describe the solution you'd like**

For problem 1:
In lighttable view depending on mode selected the `?` mode should link to https://darktable.gitlab.io/doc/en/lighttable_chapter.html#lighttable_overview or specific section

For problem 2:
Hovering over thumbnail in lighttable in filemanager view should bring tooltip with helpful info (after usual tooltip delay).
I think the layout of tooltip should be:
```
if(! extended_thumbnail_overlay){
[image name]
[exposure time] [aperture] [focal length] [ISO]
}
[dbl click] open image in darkroom
[W] preview image
[H] more shortcuts
```

**Alternatives**
I'm wondering what shortcuts to show in tooltip for images.

Plus I do agree that in lightroom view the rightclick is underutilized (however falling into popup menu trap is not advisable)

**Additional context**

This came from thread on reddit: https://www.reddit.com/r/DarkTable/comments/feev60/darktable_user_base_survey/

### PR DESCRIPTION
**Pull request by AlicVB**
this fix #4441 
tooltip content can be set in preference dialog. It use same tags as the info line tool.
If set to empty string, no tooltip is shown

### CODE REVIEW

**Comment by johnny-bit** [comment]
Tooltip is great addition, but only partial for #4441 (problem 2)

I'd still prefer if clicking on :grey_question: and hovering over lighttable didn't turn cursor into big :x:

If it's possible, please add that link to manual for lighttable :)

**Comment by AlicVB** [comment]
@johnny-bit : completely forgot the first part of the issue, sorry.
It should be fixed with the last commit in this PR

**Comment by johnny-bit** [comment]
perfect! I'll need to test it but code-wise it looks good!

**Comment by TurboGit** [comment]
Love it ! I can now remove the extended thumbs info. Thanks for all those enhancements @AlicVB .

**Pull request merged**
