### PR TITLE
Colorequalizer weighing function fix

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
As detected by @ralfbrown the weighing function returned wrongly restricted values so control via contrast and saturation threshold was not fully as intended.

Modified two sections for readability, also some comments modified here.

Slightly improved visibility of weighing function.

@TurboGit  Might possibly affect output in a subtle way.

### CODE REVIEW

**Review by ralfbrown — COMMENTED** [review]
The first changed line is the actual fix for the incorrect clamping.  The changes near line 540 were originally to try to work around a crash, and I'm guessing those near line 760 are for consistency.  They shouldn't be causing any change in output unless some of the saturation values are no longer being clamped.  But what worries me is the report of a difference between CPU and GPU results - since we have no OpenCL code path yet, those two runs should have been identical.  A difference indicates a data race somewhere causing some pixels to change from run to run. Do multiple runs of that test case without the PR show differences on some runs?  (OTOH, I just ran test 0159 five times without and five times with the PR, and got identical results on all ten runs, with no reported CPU/GPU differences.)

The final group of changes at line 1004+ looks like it just makes the curve in the displayed weighting graph marginally thicker, since it is running through twice as many values to `_get_satweight` covering the same range (0-1, offset by the appropriate shift variable).

**Comment by jenshannoschwalm** [comment]
> ... and I'm guessing those near line 760 are for consistency

Right, also it seems to me the parts might be more understandable this way

> unless some of the saturation values are no longer being clamped

Right again. The correction done here - depending on contrast - leads to slightly a) less bleeding into achromatic areas and b) better use of the guided filter results in highly saturated areas. Both are intended.


> The final group of changes

It's doing fewer "holes" inthe shown curve with high contrast used.

> But what worries me is the report of a difference between CPU and GPU results - since we have no OpenCL code path yet, those two runs should have been identical

I think we have that for some/many results. Also depends on implementation/precision of some native cl functions ...

**Comment by ralfbrown** [comment]
When there's no OpenCL code path, the "GPU" run is using the CPU codepath, so the results *should* be identical since the same code is being run both times.  The old haze removal module occasionally differs on a handfull of pixels when I forget to give the `--disable-opencl` flag (since I don't have OpenCL, it runs CPU twice), but I don't recall any other test cases with that issue.

**Comment by jenshannoschwalm** [comment]
That's not my experience, i've always had some differences cpu vs gpu, even for the very simple tests there was some difference in this range of pixels.

**Comment by ralfbrown** [comment]
I'm talking about when the "GPU" run is really running the CPU codepath.  Color Equalizer doesn't have an OpenCL code path yet....

**Comment by jenshannoschwalm** [comment]
> Color Equalizer doesn't have an OpenCL code path yet....

Yes but we compare "overall result" :-) When checking for differences opencl vs cpu per module we would have to use the results from  `--dump-pfm module-in-question`. I did that while reducing differences for demosaicers or opposed ...

**Comment by ralfbrown** [comment]
> Yes but we compare "overall result" :-) 

Ah, right.  If the output color profile module yields different results between CPU and OpenCL, that would affect most every test.
Darn confounding factors :)

Didn't think about that because I don't have OpenCL (graphics card too ancient, but it has the advantage of passive cooling so it doesn't add to the noise of my PC).

**Comment by jenshannoschwalm** [comment]
@TurboGit how to proceed.

1. Wait for a pending "overall fix" after sorting out the observed crashes, this might get integrated into that. @ralfbrown is working on refactoring the internal code ...
2. You would like me to make this PR **only** fixing the wrong restriction still for 4.8?
3. We could also keep it as is for 4.8 and do a version bump keeping existing edits for 5.0?

Let me know, would be fine with all ways.

**Comment by ralfbrown** [comment]
I realized while going over the code for the Nth time that the new limits have a corner case where a value of exactly 1.0 or clamped to 1.0 can read past the end of the interpolation table....  I fixed that with
```
  const float isat = (float)SATSIZE * (1.0f + CLAMP(sat, -1.0f, 1.0f-(1.0f/SATSIZE)));
```
but we could also increase the table size by one entry.

I recommend that at least the clamping fix be incorporated in 4.8.

**Comment by jenshannoschwalm** [comment]
force-pushed the correct clip

**Comment by ralfbrown** [comment]
16826 doesn't include the increased number of points in the curve for the weighting graph.  You might want to make that a separate PR.

**Pull request closed without merging**
