### PR TITLE
Color calibration as shot in camera adaptation setting fix

### LINKED ISSUE #8011: Color calibration adaptation setting visible when it has no effect
Problem occurs in latest from master 3.5.0+838~g82a13a17b.

In color calibration, when the illuminant is set to "as shot in camera", the adaptation is automatically set to either linear Bradford or CAT16 within check_if_close_to_daylight().

The problem is that the adaptation combobox remains visible and can be changed, but changing it has no effect. If it has no effect it should be hidden like the other controls that aren't relevant to the selected illuminant. Also, when switching from "as shot in camera" to custom, the adaptation combobox does not change to the adaptation that had been used automatically for "as shot in camera".

To reproduce:
Enable color calibration and set illuminant to "as shot in camera".
Change adaptation to any setting and observe no change in image.
Change adaptation to none or XYZ and then change illuminant to custom. Observe that the adaptation combobox does not change.

Expected behavior:
When illuminant is set to "as shot in camera" the adaptation combobox is hidden.
When illuminant is then set to custom, the adaptation combobox reappears and is set to either linear Bradford or CAT16, depending on what had been automatically set based on the camera WB.

### PR DESCRIPTION
**Pull request by paolodepetrillo**
Fixes #8011

Without this fix, any time the illuminant is set to 'as shot in camera', the setting of the adaptation combobox is ignored and CAT16 adaptation is applied. So it's possible to set illuminant to 'as shot in camera', set adaptation to None, and the module looks like adaptation is disabled when it is really still applying CAT16.

With this fix, the adaptation combobox setting is always used. Also, when the illuminant is changed from a different setting to 'as shot in camera', the adaptation combobox is automatically set to CAT16. This should be consistent with 'detect from image surfaces' and 'detect from image edges' which also set it automatically.

### CODE REVIEW

**Comment by paolodepetrillo** [comment]
Might have made a mistake creating this PR? It's got a couple commits from bringing my fork up to date in addition to the actual commit 59ff07e.

**Comment by TurboGit** [comment]
Indeed you seemed to have merged master into your topic branch. It is recommended to actually rebase your topic branch instead. In this simple case we can squash everything or merge manually anyway.

**Comment by TurboGit** [comment]
@aurelienpierre : can you review this one ? TIA. I'll merge as we need to take a single commit from here.

**Comment by aurelienpierre** [comment]
This change is not ok. "As shot in camera" is a dynamic setting, user is forbidden to change the adaptation, which is selected depending on the illuminant found. If anything, you just need to hide the combobox. Also, it will break compatibility in a minor way.

**Comment by paolodepetrillo** [comment]
Understood, it makes more sense to hide the combobox. I wasn't sure because the combobox was originally hidden when as shot in camera was selected for illuminant, but it was reenabled in 3798a3d.

**Comment by TurboGit** [comment]
So closing.

**Pull request closed without merging**
