### PR TITLE
Fix add to library crash

### LINKED ISSUE #9547: dt 3.7 crash at import "path lookup ... no such file or directory
Latest Manjaro, Nvidia proprietary, Ryzen 3900x, 32 gig RAM.

a) I just built darktable 3.7.0+384~g45dbc4dbb9 (from AUR)
b) I removed the old darktable directories in my .cache and .config
c) I started darktable, wanted to import some .RAFs. Immediate crash.

When invoked from a terminal, doing the same import still crashes,
giving the error msg
`path lookup '/home/claesl/0' fails with: 'No such file or directory'`

### PR DESCRIPTION
**Pull request by wpferguson**
in `apply_lua_filter` create the table indexes manually so that the indexes are guaranteed to be sequential and the size of the table is known.   Fixes #9547

### CODE REVIEW

**Comment by elstoc** [comment]
Fixes the issue for me. Thanks @wpferguson.

**Comment by phweyland** [comment]
Tested. Still works for me (but I could not reproduce the issue before the fix) :).

However the same code ("pre-import") is in film_jobs.c, with probably the same issue...

**Comment by wpferguson** [comment]
@phweyland thanks for testing.  I don't know the importer code, so you told me what else needed fixing.  

I had read the table stuff, but sometimes it's hard to understand without an example.  Now that it blew up in our face I understand what they meant :).

I couldn't reproduce on my system either.  Had to build a Fedora VM in order to see the crash.

**Review by TurboGit — APPROVED** [review]
Thanks for the team work !

**Pull request merged**
