### PR TITLE
Silence the webp loader's complaint about failed metadata reading

### LINKED ISSUE #12590: darktable-generate-cache throws error messages
**Did you buy darktable from an application store ?**
no, self build from master

**Describe the bug/issue**
`darktable-generate-cache` throws an error message `[webp_open] WebPGetInfo failed` for each image for which thumbnails are generated

**Expected behavior**
No error messages

**Which commit introduced the error**
Probably https://github.com/darktable-org/darktable/pull/12560
Not observed with 4.1.0-426-g3bb5fd2d5, observed with 4.1.0-450-ge83f7f7fb

**Platform**
* darktable version : 4.1.0-450-ge83f7f7fb
* OS : Linux 5.15.0-46-generic / Ubuntu 22.04.1 LTS
* Memory : MemTotal:       65773056 kB
* Graphics Card :     Product Name                          : NVIDIA GeForce RTX 2060
* Graphics Card : Driver Version                            : 470.141.03
* OpenCL installed :   Device OpenCL C Version                         OpenCL C 1.2
* OpenCL activated : yes
* Xorg : Version: 1:7.7+23ubuntu2
* Desktop : LXQt
* GTK+ : 3.24.33
* gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
* CMAKE_BUILD_TYPE : release

 - Can you reproduce with another darktable version(s)? **no**
 - Do you use lua scripts? **no**

### PR DESCRIPTION
**Pull request by victoryforce**
Resolves #12590

### CODE REVIEW

**Comment by kmilos** [comment]
Alternatively, you can just return immediately if the extension is not .webp like most other loaders do. Or even better, check for magic bytes early.

**Comment by victoryforce** [comment]
> Alternatively, you can just return immediately if the extension is not .webp like most other loaders do.

Yes, I could. And for what? What will this improve? Just because other loaders do it doesn't mean it's the best way. See #12483.

> Or even better, check for magic bytes early.

WebPGetInfo is essentially a magic byte checker as well (which additionally returns two useful values). The webp API documentation clearly states that the WebPGetInfo function is used "to ___detect a WebP file___ and gather the picture's dimensions". What you're suggesting is essentially adding duplicate code because it actually repeats what the existing code already does: it determines whether the current file can be loaded.

> I guess the error output can still be useful if dealing w/ genuine (but corrupted?) WebP files?

And how do you distinguish a genuine but corrupted WebP file from a file that is not corrupted, but just mistakenly an image of another format in a file with the extension .webp?  The answer is that _in the general case_ you can't tell.

**Comment by victoryforce** [comment]
All of these `fprintf()'s` are fatal error messages and are not debug messages in any way, so `DT_DEBUG_IMAGEIO` is not appropriate here.

**Comment by kmilos** [comment]
> All of these `fprintf()'s` are fatal error messages and are not debug messages in any way, so `DT_DEBUG_IMAGEIO` is not appropriate here.

I really don't see why you couldn't turn it into a useful debug message here, but it's your prerogative.

**Comment by victoryforce** [comment]
> > All of these `fprintf()'s` are fatal error messages and are not debug messages in any way, so `DT_DEBUG_IMAGEIO` is not appropriate here.
> 
> I really don't see why you couldn't turn it into a useful debug message here, but it's your prerogative.

Not sure I understand your point. Well, to be completely honest: I don't get your point at all.  The essence of the ___debug___ message is that it helps to find the cause of the problem, but in the absence of problems it is an _unnecessary, "noise"_ message. That is why debug messages are enabled explicitly (in our case, we have to run with "-d imageio"). Fatal error messages, on the contrary, should not be hidden behind debug enablers.


By the way, I didn't expect this apparently correct one-line fixer commit to be met with such a stream of additions and improvements. 🙂

**Review by TurboGit — APPROVED** [review]
Reading comments here, to me it is ok as we are indeed detecting an error which is reported to the callee with the DT_IMAGEIO_FILE_CORRUPED. Anyway, let's move on. Thanks.

**Pull request merged**
