### PR TITLE
darkroom : keep selection in sync if unique

### LINKED ISSUE #4916: selection of current image is lost between lighttable and darkroom
Selection has lost consistency between lighttable and darkroom.
To reproduce: 
Select an image in lighttable. 
Enter darkroom mode ("D").
Select other image with single click (I haven't checked for double click, maybe too).
Return to lighttable with "L".

The selection returns to the image, selected in lighttable, not in darkroom.  

That is a dataloss issue - the actions are applied to the wrong image (user is sure the selected one is the last one selected).

Darktable from git master of 2020.05.05.
Linux Mint 19.3 Mate x64.
OpenCL is active,  Radeon RX580.

### PR DESCRIPTION
**Pull request by AlicVB**
this fix #4916

### CODE REVIEW

**Comment by TurboGit** [comment]
Don't we need the same code for the print module ?

**Comment by AlicVB** [comment]
@TurboGit : I don't really know the print module as my printer in b&w only with very low resolution... but I think it makes sens. I'll take care

**Comment by AlicVB** [comment]
@TurboGit : done. I've also fixed an inconsistency between print and other view in the last commit can you double check ?

**Comment by TurboGit** [comment]
Works for me, thanks !

**Pull request merged**
