### PR TITLE
blend_gui: makes channels button work better with small panel size.

### LINKED ISSUE #8503: parametric mask mode gui space
**Describe the bug/issue**

The parametric mask mode g R V B... are on the same line and seems to be allowed to only take half of the line length. This means that when the panel is small the mode are not all displayed but need to be scrolled with `<` and `>` buttons on the left and on the right. 

**To Reproduce**

1. Go to darkroom
2. Select a module
2. Activate parametric mask
3. Reduce panel size
4. See error, not all mode are visible

**Expected behavior**

The mode buttons should be allowed 2/3 of the line probably.

**Screenshots**

image

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : master
* OS                :  Linux
* Linux - Distro    :  Debian

### PR DESCRIPTION
**Pull request by TurboGit**
Fixes #8503.

### CODE REVIEW

**Comment by TurboGit** [comment]
@dterrahe : another narrow panel fix, is that ok to you?

**Comment by elstoc** [comment]
I was just about to submit the same change :)

Only comment (not _really_ related to this PR) is that the color pickers and the channel list seem mis-aligned, probably because there's quite a lot of top/bottom padding within the icons, which is only visible when you hover them..

**Comment by dterrahe** [comment]
This is fine by me!

I'll confess that when I introduced the change that made the notebook tabs shrinkable, instead of fixed size with hardcoded spaces, so that it wouldn't force a minimum width for the panel, I considered making it exactly like this. But I was worried that it was too much of a change from the previous situation for people who use the panel at full width and that I would end up having tedious discussions with people who didn't see any value in making narrow panels behave nicely. So I self-censured.

**Review by dterrahe — COMMENTED** [review]
👍

**Comment by TurboGit** [comment]
Thanks for the review & comments. Merging.

**Pull request merged**
