### PR TITLE
exif: DNG detection improvements

### PR DESCRIPTION
**Pull request by kmilos**
For HDR, only PhotoMetric interpretation w/ float format matters.

For mono, only single channel LinearRaw matters, regardless of bit depth.

Also check root IFD tags just in case there is nor preview image.

### CODE REVIEW

**Comment by sgotti** [comment]
@kmilos Perhaps this is too meticulous, but the dng spec says that the full size image should have NewSubFileType == 0, perhaps it could be better to test the root ifd and available subifds and use the one using NewSubFileType == 0 instead of getting the first values availables from the root and the first subifd? (not clear if this is mandatory and how to fallback if some dngs don't provide NewSubFileType).

**Comment by kmilos** [comment]
@sgotti Yes, that should indeed be the case, and AFAIK NewSubFileType should be mandatory. However, I'd leave such a refactoring (probably best to identify the raw IFD first, then use it everywhere rather than check on every access) for another time...

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by TurboGit** [comment]
That's a more a fix than an improvement, right? So for 4.4? If so, please can you give me a text for the release notes? TIA.

**Comment by kmilos** [comment]
Yeah, it's just covering some corner cases, good for 4.4.

Don't think it's worth mentioning particularly in the relnotes TBH...

**Pull request merged**
