### PR TITLE
basecurve: remove per-camera base curves

### PR DESCRIPTION
**Pull request by pedrocr**
This came up while discussing this issue:

http://redmine.darktable.org/issues/10760

stemming from this discussion:

http://comments.gmane.org/gmane.comp.graphics.darktable.devel/6844

I'd say we have two options:
- Accept curves as submitted by the users with minimal quality checking (does it look right? does it have too many points?). Since we no longer autoapply per-camera base curves by default this would just add new presets that users can just ignore if they want. It would still result in a variable quality of base curves shipped directly by us.
- Just remove all the per-camera base curves. We don't have a way to validate the curves and have misgivings even about some already merged. So let's at least be consistent and not have curves for any camera.

This PR does the second option. I'm partial to the first but not by much. I do strongly think we should make a decision instead of dragging this along wasting our time every time it comes up.

### CODE REVIEW

**Comment by edgomez** [comment]
> I'd say we have two options:
> 
>     * Accept curves as submitted by the users with minimal quality
>     checking (does it look right? does it have too many points?).
>     Since we no longer autoapply per-camera base curves by default
>     this would just add new presets that users can just ignore if
>     they want. It would still result in a variable quality of base
>     curves shipped directly by us.
>     * Just remove all the per-camera base curves. We don't have a way
>     to validate the curves and have misgivings even about some
>     already merged. So let's at least be consistent and not have
>     curves for any camera.

I'd like to share my opinion and past experience about the basecurve/tonecurve.

In my case, i tried to create the D7000 and the D750 basecurves/tonecurves because the ones that are shipped just don't work well: over saturation of the red/orange tones (bad for skin), kill detail in the shadows.

By chance the curve tool was already there, but had some limitations.

I tried to overcome some of them, but I'm still not happy with the tool:
- the averaging on multiple photos helps output consistent curves
- the fact the tool has to go though multiple pictures has increased the difficulty for the user, the doc tries to workaround that but it's not enough
- i failed at getting a*/b* curves done right. They have some specificity that current code doesn't respect (0 is probably is point of symmetry)

IMHO, we should spend more time on the curve tool:
- make sure that the tool output meets some quality criteria (even the curves i did aren't good in the end, i see weird artifacts on higlight areas). We should probably check that the first derivative and second derivatives are smooth and bound to safe values.
- improve the procedure so that we can help the user create good material to compute the curves, the denoise profile procedure is great in that regard.
- maybe the accumulated data should be sent to the developers, the same way a tarball is created for denoise profiles ?
- for the nikon case, why not use the curves embedded in the EXIF data ? what about the other brands ?
- get the curves out of the code, adding curves should be easy, not a developer task, or a sqlite command. The denoise JSON approach is nice. The LUA repo approach is nice too.

Curves are a critical part of a photography rendering. Getting rid of the current curves is nothing but hiding the fact we don't spend enough energy/time on providing good ones, or the means to create them.

I can dedicate some time on this, but what i lacked a few months ago, was ideas and objectives.

-- 
Edouard Gomez

**Comment by LebedevRI** [comment]
We should also remember that there has been some thought about changes needed to deprecate "always-on" basecurve, and apply *curve by default later in pipe.

**Comment by pedrocr** [comment]
@edgomez @LebedevRI you guys are both absolutely correct in saying that there's a big chance we'll rework the way we do base curves in the future. That issue though is orthogonal to the one I'm bringing up. To restate our options in that context, we can tell users:

  * Our per-camera basecurves are broken and unfit by our quality standards so we've removed them until we can find a new way of doing it.
  * Our per-camera basecurves are broken but are the best we have right now. We'll keep accepting new ones with minimal quality testing and will very likely rework them in the future.

I've already done the work for the first option (this PR) and am willing to do the work for the second (merge the few curves that show up because some user has decided to do one). 

At least some users are finding the curves useful and since PR #998 these curves aren't even used by default so the quality issue should be minimal. I'd just not publicize the curves but accept them if they show up.

**Comment by TurboGit** [comment]
I'd vote for:

> Our per-camera basecurves are broken but are the best we have right now. We'll keep accepting new ones with minimal quality testing and will very likely rework them in the future.

**Comment by McBofh** [comment]
I also vote for the second option.

**Comment by pedrocr** [comment]
I haven't seen anyone actually want to remove these curves. Should I just close this and start taking the curves users have submitted?

**Comment by LebedevRI** [comment]
This is basically the same shadow zone as enhanced curves, modulo [#10345](http://redmine.darktable.org/issues/10345)
But *if* one comes up with a proper way to verify their quality, then i bet no one will vote them to be removed.

**Comment by pedrocr** [comment]
>This is basically the same shadow zone as enhanced curves, modulo #10345

It doesn't have that problem because unlike colorin this doesn't break history stacks as we save the actual curve.

>But if one comes up with a proper way to verify their quality, then i bet no one will vote them to be removed.

The situation we have now is that we don't really know how to validate the new ones just like we didn't know how to validate the old ones. We don't enable them by default either, which is why my opinion is option 2 above:

  * Our per-camera basecurves are broken but are the best we have right now. We'll keep accepting new ones with minimal quality testing and will very likely rework them in the future.

Otherwise we keep having users asking "but my FOO camera has them why can't I add them to my BAR camera".

**Comment by aurelienpierre** [comment]
Anyway, basecurves are useless if you are using proper camera color profiles, right ?

I never used them : if you make photographs in RAW format, I guess it's not to replicate camera/manufacturer presets in your editor.

**Comment by ArchangeGabriel** [comment]
Just discovered this because of @aurelienpierre message. From my user perspective, I was going to look at adding Canon 760D curve some time next month, because currently it’s really not good (in the sense that the default output is far from the JPEG one — which, to be honest, is quite good in fact), while it wasn’t that bad with my former 650D.

And even if that’s strange, what I expect as a beginner user is in fact that opening the RAW in DT make it looks like the JPEG issued from camera/manufacturer presets by default and then move things around. Especially, I avoid mangling with base curve at all, I’m rather using DT for noise reduction or restoring over- and under-exposed shots. Not to be creative with the basecurve.

So, FWIW, I would prefer ability to have per camera basecurves rather than nothing, especially if their use is optional. Of course, the best would be a reworked basecurve process à la denoising system.

**Comment by hanatos** [comment]
closing as discussed in irc. let's keep as is and for the future move more towards a curve that comes late in the pipe (as possible using a measured tone curve potentially in RGB today already)

**Pull request closed without merging**
