### PR TITLE
po/fix exposure

### PR DESCRIPTION
**Pull request by TurboGit**

### CODE REVIEW

**Comment by elstoc** [comment]
Yep that resolves #5655 for me. Thanks @TurboGit.

**Comment by elstoc** [comment]
I've worked out what the other issue is now (with the module layout changing when toggling a picker). It's because the display on the input/output sliders needs to change to accommodate an additional number (in brackets) after the input/output labels - is that the average of the area or value of the point selected? So ultimately, I suppose that's not an issue then, and this PR should close both #5654 and #5655.

**Comment by TurboGit** [comment]
@elstoc : thanks for feedback, now merged.

**Comment by TurboGit** [comment]
BTW, can you double check that #5654 is fixed ?

**Comment by elstoc** [comment]
I can no longer reproduce the main issue in #5654 so it can be closed (I'll close it now)

**Comment by dterrahe** [comment]
While looking at the code that was fixed here, I was wondering if this code ever does anything useful.
https://github.com/TurboGit/darktable/blob/e265124f1cd4060857bb3ba20f2c73236bad8486/src/iop/exposure.c#L839-L850
It looks at the color picker while drawing, but the picker only sends updated numbers when the region selection is completed and by that time it also sends a signal that picks up the results. So basically, I'm wondering if there is a need for both the callback color_picker_apply _and_ the code in draw.

The code in draw _also_ calls exposure_set_black, but this could move to the callback.

**Pull request merged**
