### PR TITLE
import: add a pref to give priority to initial import rating on exif rating

### LINKED ISSUE #7692: star at import not honored
**Describe the bug**
The number of star at import is not honored, all images get 0 star.

**To Reproduce**
1. Go to 'lighttable'
2. Click on 'preference' on import module
3. Ensure 1 star is set for new import
4. Import some picture
5. See that 0 star is set on imported images

**Expected behavior**
The number of star for new imported images should be set properly

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: GNU/Linux 

**Additional context**
I suspect an issue due to recent rewrite of the settings from general pref to import dialog.
I properly have `ui_last/import_initial_rating=1`

### PR DESCRIPTION
**Pull request by phweyland**
fixes #7692

### CODE REVIEW

**Comment by phweyland** [comment]
Not tested, as I haven't raw file with exif rating.

**Comment by TurboGit** [comment]
Not working, see #7714 for a proposal.

**Comment by TurboGit** [comment]
Just a note, this is not working as the value on the XMP takes precedence in `exif..cc` at line 1472 after calling `_exif_decode_exif_data`().

**Comment by phweyland** [comment]
> Not working,

What does not work ?

> XMP takes precedenc

Always.

**Comment by TurboGit** [comment]
@phweyland : the non working part is still the same, here is what happen with your PR:

- you import from a card
- the xmp is created
- then you read the exif data
- this called _exif_decode_exif_data : OK
- the rating is set to -2, so the import rating is used : OK
- then the XMP file is read
- the Rating is found to be 0
- it override the previous setting to 0 : NOK

In your PR the rating setting is made too early. In my proposal it is made after the import and only if there is no XMP file at the time we start reading the exif/xmp.

**Comment by phweyland** [comment]
>     * the xmp is created

Sounds strange as e first step. Is not a part of the problem there ?
And even so, rating should be not defined at this stage.

>     * the Rating is found to be 0

This doesn't sound not ok

>     * then the XMP file is read

And only if xmp has a rating, the rating has to be overridden.
If xmp has no rating it should let the initial import rating or exif rating if appropriate.

Could you share a nef file with a rating please. I would like to play a bit with this.

**Comment by TurboGit** [comment]
@phweyland : here is such NEF: https://drive.google.com/file/d/1lmVXoR6Pe8uw2KNI4vT7F3gWqPoDy8vu/view?usp=sharing

**Comment by phweyland** [comment]
> here is such NEF:

Thanks ! that's all the sun you can send to me ? :smiley:

**Comment by TurboGit** [comment]
> Thanks ! that's all the sun you can send to me ?

A beautiful picture, isn't it :) Taken by my window, there is nothing better at the moment here :)

**Comment by phweyland** [comment]
$ exiv2 -PEXI 20210106_0001.NEF | grep Rating
Exif.Photo.ISOSpeedRatings                   Short       1  800
Xmp.xmp.Rating                               XmpText     1  0

This is not and exif.rating but an xmp.rating.

**Comment by phweyland** [comment]
Easier with a file indeed, thanks !
It seems this not related to the written (or not written) xmp.
The exif hypothesis was also wrong, as this raw file comes xmp data.
So, I think that the correct fix is to reset the rating to `initial import rating` after dt_exif_read() (which reads also the xmp data) if "ignore exif rating" is set.

Note:  "ignore exif rating" wording is not totally accurate, but "ignore raw rating" can be misleading in case of non raw files.

**Comment by TurboGit** [comment]
Ok, working on my side. Thanks for the fix!

**Pull request merged**
