### PR TITLE
Bug 12387

### PR DESCRIPTION
**Pull request by edgardoh**
I re-opened this just to get more info on the issue, this is not a fix, at least yet.

Stefan, let's start by adding a circle on the exposure module and dragging it, let me know what is displayed on the command line.

### CODE REVIEW

**Comment by edgardoh** [comment]
gui->posx=-1.000000 shouldn't happen here, this is set on the dt_masks_events_mouse_leave but it records the position of the mouse while in the image, and when the mask is dragged the mouse must be on the image.

Just pushed a new commit, let's try again, same scenario.

**Comment by s5k6** [comment]
$ git up
    ...
    $ git pull
    Updating fa7517bb8..2d42b46e9
    Fast-forward
     src/develop/masks/masks.c | 6 ++++++
     1 file changed, 6 insertions(+)

compiling, retry

    $ "${prefix}/bin/darktable" --library "${prefix}/dummy-library" ~/tmp/DSC_3932.NEF 1>|stdout.log 2>|stderr.log

the bug is still there

    $ cat stderr.log 
    $ cat stdout.log 
    [dt_masks_init_form_gui]
    [dt_masks_events_mouse_moved] before set pos gui->posx=-1.000000, gui->posy=-1.000000
    [dt_masks_events_mouse_leave]
    [dt_masks_events_mouse_moved] before set pos gui->posx=-1.000000, gui->posy=-1.000000
    [dt_masks_events_mouse_leave]
    [dt_circle_events_button_pressed] form_selected before start the form dragging gui->posx=-1.000000, gui->posy=-1.000000, gui->dx=0.000000, gui->dy=0.000000
    [dt_circle_events_button_pressed] form_selected start the form dragging gui->posx=-1.000000, gui->posy=-1.000000, gpt->points[0]=168.007751, gpt->points[1]=271.939087, gui->dx=169.007751, gui->dy=272.939087
    [dt_masks_events_mouse_moved] before set pos gui->posx=-1.000000, gui->posy=-1.000000

**Comment by edgardoh** [comment]
Yes, I'm not fixing anything, just trying to see what's going on.

For some reason, dt thinks that the mouse is leaving the image right before the mouse button is pressed, that's what this sequence means:
[dt_masks_events_mouse_leave]
[dt_circle_events_button_pressed]  form_selected before start the form dr...

worst, it thinks that the mouse is not returning to the image before the mouse button is pressed.

Just pushed another commit, let's try again, same scenario.

Also, when creating a mask a preview is displayed, that is working fine? The preview is always under the mouse?
On the spot removal shortcuts can be defined, when creating a mask with a shortcut, the preview is displayed ok?

**Comment by s5k6** [comment]
$ git up
    Fetching origin
    remote: Enumerating objects: 8, done.
    remote: Counting objects: 100% (8/8), done.
    remote: Total 8 (delta 7), reused 8 (delta 7), pack-reused 0
    Unpacking objects: 100% (8/8), done.
    From github.com:edgardoh/darktable
       2d42b46e9..53c1eb1ea  bug_12387  -> origin/bug_12387
    $ git pull
    Updating 2d42b46e9..53c1eb1ea
    Fast-forward
     src/develop/masks/masks.c | 2 ++
     src/gui/gtk.c             | 3 +++
     2 files changed, 5 insertions(+)

The preview is shown, and it is always under the *shape*, i.e., not the mouse.  I've made a screencast here:

    https://depot.s5k6.net/B53pnjQAHxnTgvTw/53c1eb1ea.mp4

The shape jumps away at 21" into the video, that was when I started *dragging* the mouse, not when clicking on the shape. (mous down: shape still there.  move mouse: jumps).  Also, thwe preview is updated only when I release the buttom (mouse up).

At 28", you'll see that while dragging the shape to the left, the shape stops a bit from the left border of the image, although I do not release the mouse button.  When moving right again, the shape starts to move again.

    $ cat stderr.log 
    $ cat stdout.log 
    [dt_masks_init_form_gui]
    [center_enter]
    [dt_masks_events_mouse_moved] before set pos gui->posx=-1.000000, gui->posy=-1.000000
    [center_leave]
    [center_enter]
    [button_pressed]
    [center_leave]
    [dt_masks_events_mouse_leave]
    [center_enter]
    [button_pressed]
    [dt_circle_events_button_pressed] form_selected before start the form dragging gui->posx=-1.000000, gui->posy=-1.000000, gui->dx=0.000000, gui->dy=0.000000
    [dt_circle_events_button_pressed] form_selected start the form dragging gui->posx=-1.000000, gui->posy=-1.000000, gpt->points[0]=140.197723, gpt->points[1]=131.449463, gui->dx=141.197723, gui->dy=132.449463
    [dt_masks_events_mouse_moved] before set pos gui->posx=-1.000000, gui->posy=-1.000000
    [center_leave]
    [dt_masks_events_mouse_leave]
    [center_enter]
    [button_pressed]
    [dt_circle_events_button_pressed] form_selected before start the form dragging gui->posx=-1.000000, gui->posy=-1.000000, gui->dx=141.197723, gui->dy=132.449463
    [dt_circle_events_button_pressed] form_selected start the form dragging gui->posx=-1.000000, gui->posy=-1.000000, gpt->points[0]=285.557678, gpt->points[1]=331.865051, gui->dx=286.557678, gui->dy=332.865051
    [dt_masks_events_mouse_moved] before set pos gui->posx=-1.000000, gui->posy=-1.000000
    [center_leave]
    [center_enter]
    [center_leave]
    [center_enter]
    [center_leave]
    [center_leave]
    [dt_masks_events_mouse_leave]
    [center_enter]
    [dt_masks_events_mouse_moved] before set pos gui->posx=-1.000000, gui->posy=-1.000000
    [center_leave]
    [dt_masks_events_mouse_leave]

I'll try the shortcuts in a minute.

**Comment by s5k6** [comment]
Sorry, I maybe fail to do the “shortcuts” thing.  I do not know how to define shortcuts (I'm thinking of keyboard shortcuts?) in the spot removal module.  I also could not find it in the manual.

In case you mean the presets available in every module: Same effect.  If I store a spot removal as preset, then remove it from the history stack, compress that, go to lighttable, and back to darktable (same image), I can apply the prest.  Preview looks good.  I cannot modify that shape, unless I create an additional spot-removal-shape (another bug?).  Then I can move the original shape, but see the jumping effect again. — but you ment keyboard shortcuts, right?

**Comment by edgardoh** [comment]
This is what I get when I go to darkroom, display the masks for the exposure module, then drag it:

[center_enter]
[button_pressed]
[button_pressed]
[button_pressed]
[dt_masks_init_form_gui]
[dt_masks_events_mouse_moved] before set pos gui->posx=-1,000000, gui->posy=-1,000000
[center_leave]
[dt_masks_events_mouse_leave]
[center_enter]
[dt_masks_events_mouse_moved] before set pos gui->posx=-1,000000, gui->posy=-1,000000
[button_pressed]
[dt_circle_events_button_pressed] form_selected before start the form dragging gui->posx=434,120270, gui->posy=796,871399, gui->dx=0,000000, gui->dy=0,000000
[dt_circle_events_button_pressed] form_selected start the form dragging gui->posx=434,120270, gui->posy=796,871399, gpt->points[0]=405,685364, gpt->points[1]=807,304260, gui->dx=-28,434906, gui->dy=10,432861
[center_leave]
[dt_masks_events_mouse_leave]

Notice that gui->posx is not -1.0, that's because there's a [dt_masks_events_mouse_moved] event before [button_pressed] that sets the position.

In your case, for some reason, there's a:

[center_leave]
[center_enter]
[button_pressed]
[center_leave]
[dt_masks_events_mouse_leave]
[center_enter]

before the [dt_circle_events_button_pressed], and no [dt_masks_events_mouse_moved], so the mouse position is not updated.

So, in your environment, for some reason, darktable thinks that you are doing the following:

-enter the image
[center_enter]

-move the mouse
[dt_masks_events_mouse_moved] before set pos gui->posx=-1.000000, gui->posy=-1.000000

-leave the image
[center_leave]

-enter the image
[center_enter]

-press the mouse button
[button_pressed]

-leave the image
[center_leave]
[dt_masks_events_mouse_leave]

-enter the image again
[center_enter]

-press the mouse button (whithout moving the mouse!!!)
[button_pressed]
[dt_circle_events_button_pressed] form_selected before start the form dragging gui->posx=-1.000000, gui->posy=-1.000000, gui->dx=0.000000, gui->dy=0.000000

gtk is not my thing, so I can't say if this is a gtk or a darktable implementation problem, what doesn't seem correct is to have a [center_leave] before the mouse is pressed, even if we get a [mouse_move] event after that.

I'm afraid that this is as far as I can go, sorry we were not able to fix the problem, but at least we got more info, so if someone with more knowledge of gtk and your environment take an interest in this he/she will have more data to work with.

**Comment by s5k6** [comment]
Oh, too bad.  But *thank you very much* for the effort and time you've invested.  I'll point this out to the FVWM guys, maybe they have an idea...

**Comment by edgardoh** [comment]
keyboard shortcuts can be defined in preferences->shortcuts->image operations

There's shortcuts for almost any module, I don't really use them, but I do find them useful for the retouch and spot removal modules.

**Comment by edgardoh** [comment]
Nothing else I can do here, I'm closing it.

**Pull request closed without merging**
