### PR TITLE
Add D780 noise profile

### LINKED ISSUE #12151: Noise profile for Nikon D780
Hi,

I measured the noise profile of my Nikon D780 at room temperature (25C). The generated tarball is attached.

Issues & suggestions:

1. `darktable-gen-noiseprofile` failed to run `darktable-cli`. Reason seems to be that `darktable-cli 4.0.0` does not recognize the option `--apply-custom-presets false`. I removed this option, which should do no harm according to the doc.
2. ISO detection for high Nikon ISOs is wrong. Specifically, ISO102400 is detected as ISO180, and ISO204800 as ISO192. I changed the function `get_image_iso()` to use `exiftool -ISO -s -s -s "$file"`, which works well for all my images.
3. The tool could plot a/b values v.s. ISO. I discovered the above issue when I used a python script to plot the values that shows an abrupt peak near ISO 150.

Attachment: [darktable-noiseprofile-20220708.tar.gz](https://github.com/darktable-org/darktable/files/9072975/darktable-noiseprofile-20220708.tar.gz)

My script for plotting the a/b vs ISO graph:
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import matplotlib.pyplot as plt
import numpy as np

import argparse
import json

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('input')
    parser.add_argument('--min', type=int, help='min ISO to plot')
    parser.add_argument('--max', type=int, help='max ISO to plot')
    args = parser.parse_args()

    with open(args.input) as fin:
        preset = json.load(fin)

    profile, = preset['noiseprofiles']
    model, = profile['models']

    iso = []
    rgb_a = []
    rgb_b = []
    for i in model['profiles']:
        iso.append(i['iso'])
        rgb_a.append(i['a'])
        rgb_b.append(i['b'])

    iso = np.array(iso)
    rgb_a = np.array(rgb_a)
    rgb_b = np.array(rgb_b)

    mask = np.ones_like(iso, dtype=np.bool_)
    if args.min:
        mask &= iso >= args.min
    if args.max:
        mask &= iso <= args.max

    fig, ax = plt.subplots(2, 1)
    def plot_one(ax, coeff):
        for i, j in enumerate('rgb'):
            ax.plot(iso[mask], coeff[mask, i], 'x-', color=j)

    plot_one(ax[0], rgb_a)
    plot_one(ax[1], rgb_b)
    plt.show()

if __name__ == '__main__':
    main()
```

### PR DESCRIPTION
**Pull request by jia-kai**
Fixes #12151.  Since no one responded to that issue, I decided to open a PR. See the original issue for related attachments.

### CODE REVIEW

**Comment by rawfiner** [comment]
Hi! Sorry for the wait and thank you for the PR.
Could you confirm that you did profiling on all available ISO values (I see no ISO 1600, which seems unusual)?
Apart from that the profile looks good!

**Comment by jia-kai** [comment]
> Hi! Sorry for the wait and thank you for the PR. Could you confirm that you did profiling on all available ISO values (I see no ISO 1600, which seems unusual)? Apart from that the profile looks good!

You are right! Thanks for replying and spotting this issue! I was unfamiliar with the tool and took a few experiment photos. Somehow I forgot to fill in the ISO gaps... I will upload new files later.

**Comment by jia-kai** [comment]
@rawfiner I've updated the json in this PR. The new files are attached. Please let me know if you find other issues, thanks!

[darktable-noiseprofile-20220718.tar.gz](https://github.com/darktable-org/darktable/files/9136942/darktable-noiseprofile-20220718.tar.gz)

Below is a plot of the fitted a/b params vs ISO:

ab_iso

**Review by rawfiner — APPROVED** [review]
Looks good to me! The curves are good and the profile has a very nice behaviour. Thanks!
By the way, the plot of a and b w.r.t iso value in log log is very nice to check the overall behaviour. If you have time, could you add it (in another PR) to the script that creates the noiseprofiles so that the resulting figure is included as well in the archive? It would be a nice contribution!

**Review by TurboGit — APPROVED** [review]
Thanks to both of you!

**Pull request merged**
