### PR TITLE
Slight tuning of compiler flag & enable cmake macros

### PR DESCRIPTION
**Pull request by levitte**
Before this change, the checks for different C / C++ compiler flags
resulted in macros like these:

    C_COMPILER_UNDERSTANDS_-Wall
    C_COMPILER_UNDERSTANDS_-Wstack-usage=32768

Of course, these aren't workable macros, so from this change on, all
dashes and equal signs are replaced with `__0x2d__` and `__0x3d__`

### CODE REVIEW

**Comment by LebedevRI** [comment]
Nah, the exact names do not matter
Just sync the changes back from rawspeed (e.g. [[1]](https://github.com/darktable-org/rawspeed/blob/develop/cmake/Modules/CheckCXXCompilerFlagAndEnableIt.cmake)) if you really want to

**Comment by levitte** [comment]
Oh, so that's where those files are coming from...

**Comment by levitte** [comment]
Okie, done.

**Comment by LebedevRI** [comment]
And reverted, something broke.

**Comment by LebedevRI** [comment]
And it's back.

**Pull request merged**
