### PR TITLE
pixelpipe cache: allow for reallocating data even in two line caches

### LINKED ISSUE #13421: segfault when upscaling images
**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**
Darktable will segfault when upscaling an image, or even simply when upscaling is allowed. This can occur during export, as well as during printing (which uses the export pipeline).

**To Reproduce**
1. Import an image
2. In export
a. reset the export lib (if not already a fresh config)
b. set size  to "by scale (for file)" (for convenience of reproduction for arbitrary images sizes)
c. in the next text box, set scale factor to any number > 1
d. set "allow upscaling" to "yes"
4. Select the image and hit "export"
5. darktable will work for a bit then segfault

_alternative cli invocation_

```
darktable-cli PATH_TO_IMAGE /tmp/exported.jpg  --width NUM_LARGER_THAN_IMAGE_WIDTH --upscale true
```

_minimal cli invocation_

```
darktable-cli PATH_TO_IMAGE /tmp/exported.jpg --upscale true
```

Note that in this case it appears that it isn't even necessary to force upscaling via a `--width` argument.

**Expected behavior**
The image will be exported upscaled.

**Which commit introduced the error**
fe309e6c8b695eae204fa5637b33e051a8b4d5b4

But is this commit is actually bad? Or could fixing the cache behavior have exposed another bug? 

**Platform**

* darktable version : 4.3.0+301~gecd8a47312
* OS : Linux 6.0
* Linux - Distro : Debian testing
* Memory : 32GB
* Graphics card : GeForce RTX 3080 Mobile
* Graphics driver : Nvidia 510.108.03
* OpenCL installed : yes
* OpenCL activated : yes
* Xorg : 7.7
* Desktop : Gnome
* GTK+ : 3.24.36
* gcc : 12.2.0
* cflags :
* CMAKE_BUILD_TYPE : Release

**Additional context**

 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? **yes**
   - What lua scripts start automatically? **none**
   - What lua scripts were running when the bug occurred? **none**
 - This occurs if conf `codepaths/openmp_simd=true` as well as with the default `codepaths/openmp_simd=false`, though in different functions

**Backtraces**

I don't get a backtrace from the segfault when running darktable, but instead just a core dump. I can see a backtrace via gdb, though. Here is gdb output when running `darktable-cli`

```
Thread 35 "darktable-cli" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff1dff7240 (LWP 1562909)]
.omp_outlined._debug__.17 (roi_out=0x7fffffff5a60, in_stride=<optimized out>, out=<optimized out>, out_stride=<optimized out>, .global_tid.=<optimized out>, .bound_tid.=<optimized out>, vmeta=<optimized out>, vlength=<optimized out>, hlength=<optimized out>, in=<optimized out>, vindex=<optimized out>, hindex=<optimized out>, hkernel=<optimized out>, vkernel=<optimized out>) at /home/dtorop/src/darktable/src/common/interpolation.c:1682
1682	      _mm_stream_ps(o, vs);
(gdb) bt
#0  .omp_outlined._debug__.17
    (roi_out=0x7fffffff5a60, in_stride=<optimized out>, out=<optimized out>, out_stride=<optimized out>, .global_tid.=<optimized out>, .bound_tid.=<optimized out>, vmeta=<optimized out>, vlength=<optimized out>, hlength=<optimized out>, in=<optimized out>, vindex=<optimized out>, hindex=<optimized out>, hkernel=<optimized out>, vkernel=<optimized out>)
    at /home/dtorop/src/darktable/src/common/interpolation.c:1682
#1  .omp_outlined..18
    (.global_tid.=<optimized out>, .bound_tid.=<optimized out>, roi_out=0x7fffffff5a60, vmeta=@0x7fffffff59c8: 0x5555581c03a8, vlength=@0x7fffffff59b8: 0x5555581adf00, hlength=@0x7fffffff59c0: 0x7fff48019040, in=<optimized out>, in_stride=<optimized out>, vindex=<optimized out>, hindex=<optimized out>, hkernel=<optimized out>, vkernel=<optimized out>, out=<optimized out>, out_stride=<optimized out>) at /home/dtorop/src/darktable/src/common/interpolation.c:1620
#2  0x00007ffff784d5a3 in __kmp_invoke_microtask ()
    at /usr/lib/llvm-14/lib/libomp.so.5
#3  0x00007ffff77c1329 in  () at /usr/lib/llvm-14/lib/libomp.so.5
#4  0x00007ffff77bfbc2 in  () at /usr/lib/llvm-14/lib/libomp.so.5
#5  0x00007ffff78277cb in  () at /usr/lib/llvm-14/lib/libomp.so.5
#6  0x00007ffff164cfd4 in start_thread (arg=<optimized out>)
    at ./nptl/pthread_create.c:442
#7  0x00007ffff16cd66c in clone3 ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

And here is gdb output with a similar invocation using the OpenMP code (via `--conf codepaths/openmp_simd=true`)

```
Thread 33 "darktable-cli" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff22ffb140 (LWP 1563881)]
0x00007ffff7b0a5a0 in .omp_outlined._debug__.13 (roi_out=<optimized out>, in_stride_floats=<optimized out>, in=0x7fff4a3de040, out_stride_floats=<optimized out>, out=<optimized out>, .global_tid.=<optimized out>, .bound_tid.=<optimized out>, vmeta=<optimized out>, vlength=<optimized out>, hlength=<optimized out>, vindex=<optimized out>, hindex=<optimized out>, hkernel=<optimized out>, vkernel=<optimized out>) at /home/dtorop/src/darktable/src/common/interpolation.c:1519
1519	      for_each_channel(c, aligned(vs:16)) out[baseidx + c] = fmaxf(vs[c], 0.f);
(gdb) bt
#0  0x00007ffff7b0a5a0 in .omp_outlined._debug__.13
    (roi_out=<optimized out>, in_stride_floats=<optimized out>, in=0x7fff4a3de040, out_stride_floats=<optimized out>, out=<optimized out>, .global_tid.=<optimized out>, .bound_tid.=<optimized out>, vmeta=<optimized out>, vlength=<optimized out>, hlength=<optimized out>, vindex=<optimized out>, hindex=<optimized out>, hkernel=<optimized out>, vkernel=<optimized out>)
    at /home/dtorop/src/darktable/src/common/interpolation.c:1519
#1  .omp_outlined..14
    (.global_tid.=<optimized out>, .bound_tid.=<optimized out>, roi_out=<optimized out>, vmeta=<optimized out>, vlength=<optimized out>, hlength=<optimized out>, vindex=<optimized out>, in_stride_floats=<optimized out>, hindex=<optimized out>, hkernel=<optimized out>, in=<optimized out>, vkernel=<optimized out>, out_stride_floats=<optimized out>, out=<optimized out>)
    at /home/dtorop/src/darktable/src/common/interpolation.c:1458
#2  0x00007ffff784d5a3 in __kmp_invoke_microtask ()
    at /usr/lib/llvm-14/lib/libomp.so.5
#3  0x00007ffff77c1329 in  () at /usr/lib/llvm-14/lib/libomp.so.5
#4  0x00007ffff77bfbc2 in  () at /usr/lib/llvm-14/lib/libomp.so.5
#5  0x00007ffff78277cb in  () at /usr/lib/llvm-14/lib/libomp.so.5
#6  0x00007ffff164cfd4 in start_thread (arg=<optimized out>)
    at ./nptl/pthread_create.c:442
#7  0x00007ffff16cd66c in clone3 ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

### PR DESCRIPTION
**Pull request by dtorop**
Export pixelpipe assumes that the image will not increase in size. This will not be true if it is being upscaled.

Fixes #13421.

~~This appears as a bigger diff than it is, as it simply removes the check for two line caches when determining whether to reallocate the memory for a cache line.~~ It also now moves the special handling of two line caches out of `dt_dev_pixelpipe_cache_get()` into its helper `_get_cacheline()`.

(One could argue that there still should be a bit of special handling for two line caches: That we should always bypass looking for a cache hit for these. There should never be one, as the cache is merely used as a way to keep two buffers live, one for input and one for output of the current iop.)

@jenshannoschwalm: What do you think of this? My worry is that this a stopgap, and the correct fix to initialize the export pixelpipe with the correct output image size. I haven't looked at the code enough to know, though.

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
You are right, #13405 broke upscaling.


> @jenshannoschwalm: What do you think of this? My worry is that this a stopgap, and the correct fix to initialize the export pixelpipe with the correct output image size. I haven't looked at the code enough to know, though.

This pr will certainly do a lot of free and allocs.

I suggest: in twolines mode don't reallocate if sizes are not equal but only if requested size is smaller than what we have.

**Comment by jenshannoschwalm** [comment]
Will have a look, if we can find out about maximum required buffer size before initializing the cache that would be better :-)

**Comment by dtorop** [comment]
> This pr will certainly do a lot of free and allocs.

Possibly! Though if the image size remains the same through most of the pixelpipe, in most cases (excepting crop or finalscale?), only at those steps.

I wish I understood the cost of alloc/free more. It sounds like for > 128K data (pretty much all images) we're asking the kernel to map/unmap some 4K  pages (at least on Linux). I have no idea how to measure this, though, as I think a lot of this work happens when the kernel thinks it is necessary, not when we call libc.

We could use mmap/munmap/mremap directly. This would guarantee that the pointers are aligned (as they'd be aligned to page boundaries, which is far more than the 16 or 64 we normally request) and maybe mremap is more efficient than munmap + mmap. But there'd have to be a fallback path, at least for Windows?

> I suggest: in twolines mode don't reallocate if sizes are not equal but only if requested size is smaller than what we have.

This makes a lot of sense, even though it's back to an extra codepath for two line caches. But as these are so short-lived, it makes sense that they grow but don't shrink until they're deallocated completely. I'll push an extra commit to do that.

> Will have a look, if we can find out about maximum required buffer size before initializing the cache that would be better :-)

Yes! It looks like, as pre #13405 the code was tolerant of growing the buffer, that this was never a problem before.

**Comment by dtorop** [comment]
One more commit, back to a special case for two line caches. This _could_ also go back to causing subtle bugs, as the buffer size attribute may exceed the image data size. But also this is only a problem when reweighting a cache or verifying a cache hit (neither of which should occur in thumbnail/export pipelines), it's more a potential problem for a future coder...

**Comment by jenshannoschwalm** [comment]
https://github.com/darktable-org/darktable/blob/4a7058da3f3f57466fd5496d615ad52d1c1eafd8/src/develop/pixelpipe_cache.c#L340-L341

**Comment by dtorop** [comment]
> https://github.com/darktable-org/darktable/blob/4a7058da3f3f57466fd5496d615ad52d1c1eafd8/src/develop/pixelpipe_cache.c#L340-L341

Ah! Yes... Will fix.

**Comment by jenshannoschwalm** [comment]
See my above comment - was still re-editing . Anyway: VERY nice to see you on this code too!

**Comment by dtorop** [comment]
> See my above comment - was still re-editing

Ah I see now... Your version is clearer. I put up yet one more commit with your clearer conditional and skipping hash check for two line cahces. Which led to fiddling with the code.

>  VERY nice to see you on this code too!

Thank you! I seem to have a knack suddenly for hitting edge cases in it...

**Comment by jenshannoschwalm** [comment]
Well, you got me into a way to almost double my hit rate!

**Comment by jenshannoschwalm** [comment]
Maybe squash in one commit?

Other from reading diff looks good now for me.

**Comment by dtorop** [comment]
> Well, you got me into a way to almost double my hit rate!

Interesting! Due to this code, or another idea?

> Maybe squash in one commit?

Will do.

> Other from reading diff looks good now for me.

Great!

**Comment by jenshannoschwalm** [comment]
Due to the last PR on this...

**Review by TurboGit — APPROVED** [review]
Thanks to both of you for this quite delicate issue!

**Comment by dtorop** [comment]
> Due to the last PR on this...

That makes sense. As it was ignoring data from cache lines once they were resized!

**Pull request merged**
