### PR TITLE
Noise Profile: Canon EOS M5, fixes #11610

### PR DESCRIPTION
**Pull request by rrenomeron**
Plots and stuff available at https://drive.google.com/file/d/0B_HpnO6hbpJxTDdXWFRfb0Raemc/view?usp=sharing

### CODE REVIEW

**Comment by rrenomeron** [comment]
The additional entries were due to extra shots I'd taken, I've reviewed and removed the excess.

**Comment by drhaynes** [comment]
Thanks @rrenomeron for doing this.

@LebedevRI can this be merged now? Keen to get M5 support in. Thanks!

**Comment by LebedevRI** [comment]
As soon as someone who can read those plots verifies them (hint: that is not me)

**Comment by drhaynes** [comment]
Ah, what is involved? Is it something I could help with?

**Comment by schenlap** [comment]
#11610 is already fixed (28 days ago). Do you have any problems with merged noise profile?

**Comment by LebedevRI** [comment]
Sounds like it's fixed :)

**Pull request closed without merging**
