### PR TITLE
colors filter: restore last state equivalent

### PR DESCRIPTION
**Pull request by phweyland**
This catches up @AlicVB work to the last state of the colors filter PR.
- mask stored in hexa format instead of decimal integer
- a bit more room for possible future colors
- better logic on the widget itself

remains some work on _action_process_colors(). @dterrahe, sorry to bother you but I need some indication to finish this. Could you have a look please ?

### CODE REVIEW

**Comment by dterrahe** [comment]
From reading the code, I'm not completely clear what your changes do and I'm away from developing so can't just try it out.

`_action_process_colors` just needs the current state (used to be stored in "sel_value" of the widget), either off or not (include/exclude), to decide whether to toggle the button if a shortcut requests an explicit "on" or "off" (if requesting on and the button is already on, then no action needed).

It also needs to return whether the new state is "on" or "exclude" so that if the shortcut is linked to a midi button that has a light, it correctly indicates the state.

**Review by AlicVB — CHANGES_REQUESTED** [review]
First, I want to thank you to take this in place of me :)

I've tested and review the code. everything works well (except the shortcuts). Previous selected values are lost, but doesn't cause any troubles (considering this has not been published in any stable version and that it's not a critical setting, imho we are fine)

There's just a little glitch that I had fixed on my version : 
The "grey" (all) button is not updated after a click on another color. That's not a "big" issue as it doesn't change the filter value, but that cause strange gui states : 
- click on the grey button => all color all selected (ok)
- click another time on any color => the color is unselected (ok) but the grey button remain selected (not ok)

Same happen (but is less problematic) if you manually select all the colors : the grey button stay unselected, and you then need to click 2 times on it to unselect all the colors

**Comment by phweyland** [comment]
Thanks both for your comments. I'll try to fix all this.

**Comment by phweyland** [comment]
I think I've solved the above issues now.
The shortcuts (Shift+F1, ...) work but Ctrl+Shift+F1,... don't. Like they were captured by selected images...

**Comment by TurboGit** [comment]
This is working on my side and is ready to be merged. Just a question:

> The shortcuts (Shift+F1, ...) work but Ctrl+Shift+F1,... don't. Like they were captured by selected images...

You mean here that Ctrl+Shift+F1 doesn't work, but that's expected right (because the action is captured by the lighttable), right? So ready to be merged? (just asking to avoid a too early merged - like I do sometime - while the PR is still being fixed :).

**Comment by phweyland** [comment]
> You mean here that Ctrl+Shift+F1 doesn't work, but that's expected right

Yes, the only doubt is that the code associated to shortcut (line 225) in colors.c treats the ctrl case but, even setting a non used shortcut, like Shift+Ctrl+F11, _action_process_colors() is triggered but without the DT_ACTION_EFFECT_TOGGLE_CTRL flag. So it acts as a normal toggle.

**Comment by AlicVB** [comment]
> Yes, the only doubt is that the code associated to shortcut (line 225) in colors.c treats the ctrl case but, even setting a non used shortcut, like Shift+Ctrl+F11, _action_process_colors() is triggered but without the DT_ACTION_EFFECT_TOGGLE_CTRL flag. So it acts as a normal toggle.

I think it's expected : `DT_ACTION_EFFECT_TOGGLE_CTRL` seems to correspond to the case where you set the shortcut effect to "ctrl-toggle" so if you don't set this effect, the shortcut, whatever it is, will act as a "normal" click on the color label.

**Review by AlicVB — APPROVED** [review]
All good for me now. Thanks again !

**Review by TurboGit — APPROVED** [review]
Perfect then, thanks!

**Pull request merged**
