### PR TITLE
imageio: Fix possible compile error in avif.c

### PR DESCRIPTION
**Pull request by cryptomilk**
Missing include for `bool`.

### CODE REVIEW

**Comment by TurboGit** [comment]
In darktable we use gboolean and not C++ bool so the proper fix may be to change bool to gbooelan in avif.c.

**Comment by cryptomilk** [comment]
This is a C99 bool not C++. I guess we do C99 right?

**Comment by parafin** [comment]
That's not the point. The fact that you technically can use bool, doesn't mean that it matches dt's code convention. E.g. if you need to pass boolean value between different darktable parts, you must choose some specific type, which is @TurboGit said is gboolean.

**Comment by cryptomilk** [comment]
Moved to gboolean ...

**Pull request merged**
