### PR TITLE
dt_image_cache_write_release should be locked per image.

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Might be related to #3463

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
Could be triggered by darktable-generate-cache

**Comment by TurboGit** [comment]
Looks ok and cannot harm. Thanks!

**Comment by jenshannoschwalm** [comment]
@Turbogit Unfortunately this does harm in a way i don't understand. When i import a folder it locks, i thought maybe img->id is changed magically while writing the sidecar file or cache_release but this isn't the case. I can unlock_image right after sqlite3_finalize(stmt); and it keeps locking.

Absolutely no idea right now by looking at the code. What does this mean?

**Comment by TurboGit** [comment]
@jenshannoschwalm : Not sure to see what the lock occurs, but the seems that dt_cache* are already ensuring that the calls are thread safe (dt_cache_get / dt_cache_[read/write]_release).

I'll revert that for now anyway as it prevent importing folders :(

**Pull request merged**
