### PR TITLE
allow wb preset shortcuts to work while module is collapsed

### PR DESCRIPTION
**Pull request by elstoc**

### CODE REVIEW

**Comment by johnny-bit** [comment]
Ping me if you're gonna work on some stuff in White Balance or Channel Mixer modules :)

**Comment by elstoc** [comment]
@johnny-bit I'd like to add something to the white balance module ;)

**Comment by elstoc** [comment]
Seriously though it's tiny and I'm happy to close it if it's superseded by one of your changes or you'd like to incorporate it into your PR.

**Comment by johnny-bit** [comment]
No prob with this - go ahead :) I meant different things :) I'm totally fine with this PR :)

**Comment by elstoc** [comment]
Thanks that's what I thought. I did know you were working on white balance, just didn't think this was worth bothering you with.

**Comment by TurboGit** [comment]
Ok ! Thanks.

**Pull request merged**
