### PR TITLE
overexposed: warn if histogram profile is unsuitable for current mode

### PR DESCRIPTION
**Pull request by flannelhead**
Fixes https://github.com/darktable-org/darktable/issues/7660.

On master (2c8b69f01a8da31ab56a2998bb1bb723f6d4e361), with a LUT profile selected as the histogram profile. Shows the whole image as clipped to black.
overexposed_bad_indication

With this PR applied:
overexposed_bad_profile_control_log

### CODE REVIEW

**Comment by johnny-bit** [comment]
Good idea! Worth also mentioning in docs!

**Comment by flannelhead** [comment]
> Good idea! Worth also mentioning in docs!

Agreed. I can make the addition if this one is merged.

I'm not 100% sure about the current control log text. It might be too technical - the user doesn't necessarily know about matrix and LUT profiles, and it's not apparent from the GUI which profile is of which kind. "Please choose another profile" is less technical but also not very informational.

Perhaps we could say "LUT profiles are not supported for current clipping preview mode. Please choose another histogram profile".  This is a bit more concise. If a LUT profile is set as the histogram profile, it means the user has changed something (the default histogram profile is sRGB) and might be aware of that, and might be also aware that it is indeed a LUT profile.

**Comment by TurboGit** [comment]
Why not filter the profile and let user select only suitable profile ? We should do the same for softproof for example where sRGB or any other display profile are not suitable.

**Comment by flannelhead** [comment]
> Why not filter the profile and let user select only suitable profile ? We should do the same for softproof for example where sRGB or any other display profile are not suitable.

I think that would be good, a simple solution for the problem. However as far as I can tell, histogram for example works well with a LUT profile as there's nothing matrix-profile specific (unlike certain modes of the clipping indicator). It's debatable whether LUT profiles are any good for histograms, though.

I guess it's a matter of defining the criteria; which kind of profiles are acceptable for each profile selection?

**Comment by TurboGit** [comment]
I'm far from expert on this domain, but to me there is two kinds for profile:
1. matrix based (for display & histogram)
2. lut based (for printing & softproofing)

As far as I understand a lut based profile can also be used for display purpose.

So finally I suppose we should propose:
1. for display (matrix & lut profiles)
2. for histogram (matrix profiles)
3. for printing & softproof (lut base profiles)

Let' me raise @aurelienpierre attention here as he has more expertise as I on this.

**Comment by flannelhead** [comment]
Superseded by https://github.com/darktable-org/darktable/pull/8037, closing.

**Pull request closed without merging**
