### PR TITLE
fix bauhaus popup left jump and margins

### PR DESCRIPTION
**Pull request by dterrahe**
After #8425 fixed some of the jumping issues with bauhaus pop-ups, of course the remaining ones are even more obvious. This now tries to fix all of them.

@TurboGit if you notice anything that is not perfect now, let me know and I'll try to fix before merging.

Small fixes:
- combobox pop-up label name used to indent slightly more than when not popped up, causing a little jump even when first line selected.
- slider label touched border when popped up (and after above change, combobox too) so added a small margin to the left. This of course meant that everything _within_ the pop-up window had to be shifted by the same relative amount to the right, which is the majority of this PR (and the work of figuring everything out and testing).
- combobox pop-up didn't have enough margin at the bottom.
- slider pop-up didn't ellipsize the label when it wouldn't fit next to the number, so they would overlap. Now (almost) the same as when not popped up.
- when typing into a very small slider pop-up, the cursor size was too large. Now consistent with text size.

The last two are best tested in color balance when in column mode:
image

edit: also set tnum for bauhaus and toast so that numbers don't jump around for fonts that have unequal number widths.

### CODE REVIEW

**Comment by dterrahe** [comment]
Just now spotted another oddity (in the screenshot :-) )

If you pop-up a slider and then move the cursor down a little (to the "curves" area) and then close the pop-up, the slider label and value will now be reprinted in a different color.

Let me try to fix that first.

**Comment by dterrahe** [comment]
OK, I suspect this has something to do with `gtk_widget_get_state_flags`, `gtk_widget_set_state_flags(widget, GTK_STATE_FLAG_ACTIVE, TRUE);` and the comment @aurelienpierre left in `show_pango_text` a year ago:
`// FIXME: get that working so we can put :active text in bold, for example.`
Sounds big enough for a separate project (the bauhaus widgets don't get redrawn when their state changes apparently so they are just left the way they were supposed to look the last time they were drawn.)

So @TurboGit please ignore my previous comment and review this as is (when you have time, obviously, not high priority and as said I'd rather now get the layouting right once and for all instead of continuing to submit partial fixes).

**Comment by TurboGit** [comment]
>     * combobox pop-up didn't have enough margin at the bottom.

Better indeed now, but I find that there is more margin at the bottom than at the top now. I would add more top margin to align with what is done on the bottom.

**Comment by TurboGit** [comment]
>     * combobox pop-up label name used to indent slightly more than when not popped up, causing a little jump even when first line selected.

I was not able to reproduce this and so impossible to me to say there is something fixed.

Anyway I love (really I mean it) those small details it makes the GUI looks far better. Of course I have used to live with them, but it is far better without all those small glitches. Big thanks!

**Comment by dterrahe** [comment]
> > ```
> > * combobox pop-up didn't have enough margin at the bottom.
> > ```
> 
> Better indeed now, but I find that there is more margin at the bottom than at the top now. I would add more top margin to align with what is done on the bottom.

Even with letters that extend below the baseline (gqp etc)? That's where I noticed it initially; they were touching the border.

> I was not able to reproduce this and so impossible to me to say there is something fixed.

For example, in white balance, the settings drop down, select "as shot". Now click on it again; when the pop-up shows the full list, "as shot" stays in exactly the same place. But "settings" (the label of the dropdown) move _right_ a tiny bit. This PR should fix this ***massive*** problem.

**Comment by TurboGit** [comment]
> But "settings" (the label of the dropdown) moves _right_ a tiny bit.

I see, nice fix indeed!

> Even with letters that extend below the baseline (gqp etc)?

Yes, a little bit. Take for example the **color balance** module. Click on the mode (first combo), the last line contains **gamma** & **gain** and both **g** seems still to have a bit more space below than on top of first combo entry.

**Comment by dterrahe** [comment]
> But that a very minor point compare to the fix here, so if too hard to fix (if needed) we can go with current PR.

I'm looking at it. It is a little hard to figure out which magic numbers to use to make it all fit exactly. In theory there's _widget_space_, _INNER_PADDING_, and 2. _widget_space_ is also used for line width It would be great if I could fix it all so that if later somebody changes one of the constants, it will all still work. But I'm afraid it will fall apart in all kinds of places (and I don't actually want to change to constants to test, which I guess is the only correct way but may unearth many more places to fix.

**Comment by dterrahe** [comment]
I changed the padding at the bottom. It is a "magic number/looks good" change rather than a theoretically correct one (don't know where to find/how to calculate the correct adjustment; it seems like fonts are supposed to touch the bottom of their "box"?) Plus it doesn't scale with font size (none of the other paddings do so to fix that would be a bigger job), so this is anyway a compromise but it seems to work reasonably well for some sizes I tried. Hope you agree?

I don't really want to change the spacing at the top, because then the border will often overlap with the item above even if it is a slider or a combobox with the top item selected (if lower item selected there will always be overlap).

**Comment by dterrahe** [comment]
Added the tnum font attribute to bauhaus labels. This forces all numerals to have the same width, so the value shown at the right of the slider does not jump around as much when it changes.

This depends on the font family, which might be system dependent. On my system, the standard _darktable_ theme doesn't need this (the numbers are already equal-width) but all the others, dark/darker/grey use different fonts with jumpy numbers. It is possible that this could be achieved with CSS, but there's a lot of confusion on gtk lists about how and whether it would work and of course bauhaus support for CSS is somewhat limited, so it's probably not a bad thing to just force it in _show_pango_text_...

**Comment by dterrahe** [comment]
Also set tnum of toast messages so the toast is rock solid when using dynamic shortcuts (unless of course the sign or number of digits change).

**Review by TurboGit — APPROVED** [review]
Really good now. Thanks!

**Pull request merged**
