### PR TITLE
Add icon for rawprepare.

### PR DESCRIPTION
**Pull request by TurboGit**

### CODE REVIEW

**Comment by houz** [comment]
Is there any idea behind the icon? I know that it's hard to come up with something for these generic iops.
Should we merge this (I am not totally opposed, I'd just like to know if there is any meaning to it) we also need the PNG version.

**Comment by TurboGit** [comment]
This idea behind the icon is that rawprepare is about setting a black/white dot. The icon has a black dot inside a white dot.

I have added the png.

**Comment by houz** [comment]
What do you mean, it's setting a black/white dot?

**Comment by TurboGit** [comment]
I mean that the rawprepare iop is about setting the black/white point. So the icon has a white and black dot. This is the meaning. I found it better than no icon at all. What do you think?

**Comment by houz** [comment]
I guess there is some language thing involved, the "point" part of white/black point has nothing to do with a dot. So if it's a pun I'm all for it, but as a literal meaning it's not working i guess. Anyway, feel free to merge, it won't hurt and if we think that the icon should be changed later we can still do that. We might even hide the iop from the general gui some day.

**Comment by TurboGit** [comment]
Ok, will merge. Thanks.

**Pull request merged**
