### PR TITLE
[user manual] update images for chapter lighttable

### PR DESCRIPTION
**Pull request by mepi0011**
This pull request will replace my pull request  #3997

PS. I would like to replace more images but first the discussion in [Issue #2964](https://github.com/darktable-org/darktable/issues/2964) has to be  solved!

### CODE REVIEW

**Comment by Nilvus** [comment]
Good work but please convert images in jpg to have lighter sizes. Some are way too big and use too much space so also too much bandwidth. See how much size you add on "Files changed" tab. JPG format is more suitable for such images (or reduce image size).

**Comment by TurboGit** [comment]
@Nilvus : I think our documentation tool only supports png. At least there is no jpeg at the moment. But a PNG can be compressed and/or use a smaller resolution.

**Comment by mepi0011** [comment]
> I think our documentation tool only supports png.

I agree to @TurboGit. At the moment all pictures in the user manual are png files.

To reduce the the size of the images I can reduce the pixel count. My committed images have more pixels, so I can reduce it.

**Comment by mepi0011** [comment]
It is time to merge the Pull Request! With this change, all overview screens will be updated to the latest version of darktable 3.0. Some of the replaced images are still from the darktable 2.3.

**Comment by mepi0011** [comment]
Please consider this change before implementing the [issue 4177 ](https://github.com/darktable-org/darktable/issues/4177)

**Comment by Nilvus** [comment]
It's not the goal of this PR but as I don't have any camera compatible of tethering view, I have never seen how this view is render on darktable 3.0. There's a too big right margin on camera settings module. Unfortunately, I can't improve that as I can't access to this view...

**Comment by mepi0011** [comment]
I use the original darktable 3.0 installation of Manjaro Linux. In tethering mode I activate live view. darktable didn't show a histogram. Do I have to switch it on separately?

Does anybody else use Manjaro Linux and can confirm the missing histogram maybe it's a bug?

**Comment by TurboGit** [comment]
It means there is a bug ini the capture view. I'll try to have a look.

**Comment by mepi0011** [comment]
> It means there is a bug ini the capture view. I'll try to have a look.

Hi @TurboGit,

Did you have the opportunity to have a closer look at the missing histogram?

**Comment by TurboGit** [comment]
@mepi0011 : see #4298.

**Comment by mepi0011** [comment]
Isn't it better to merge the pull request because the pictures around the manual are from very old darktable versions!
A missing histogram in a screenshot of the thetering mode will not be noticed by most people. The old pictures that are no longer up to date are quite noticeable.

**Comment by TurboGit** [comment]
@mepi0011 : Fact is most of the screenshots there are already OBE. Icons, thumbs, preference dialog all these have been revamped. So this PR needs to be created again. But wait a bit there is some more icon eye candy to come from Aurélien.

**Comment by Nilvus** [comment]
> @mepi0011 : Fact is most of the screenshots there are already OBE. Icons, thumbs, preference dialog all these have been revamped. So this PR needs to be created again. But wait a bit there is some more icon eye candy to come from Aurélien.

And my CSS PR to merge with some improving overlays mode, better focus title, and some hover effect fixes

**Comment by TurboGit** [comment]
Closing as this has been done in another PR. Today most if not all images for the user's manual are up to date.

**Pull request closed without merging**
