### PR TITLE
crop : fix focus when entering from c&r

### LINKED ISSUE #8956: crop / crop & rotate focus issue
As mentioned in #8945, and now in darktable 3.5.0+2208~gbea8e81fd on ArchLinux.

1. Add a crop in the crop module and double-click to commit
2. Expand crop & rotate but don't make any changes
3. Expand crop again
4. Preview image is no longer cropped (you have to collapse the crop module to get it back again)

### PR DESCRIPTION
**Pull request by AlicVB**
this fix #8956

### CODE REVIEW

**Comment by elstoc** [comment]
Doesn't quite work for me. Start with a fresh edit. Expand crop. On-screen crop guides do not appear, even if I then enable the module. Works fine if I enable crop, expand another module, and then re-expand crop.

**Comment by AlicVB** [comment]
@elstoc : you're right, we need to take care of the case where crop is not activated on expand... I've force pushed a new version that should be better !

**Comment by elstoc** [comment]
Yep works for me now. Thanks.

**Review by TurboGit — APPROVED** [review]
Works for me, thanks !

**Pull request merged**
