### PR TITLE
navigation panel: use double buffering to avoid blackouts

### PR DESCRIPTION
**Pull request by upegelow**
In current master we observe short-term blackouts in the navigation/preview window whenever there are continuous changes to module parameters. To reproduce open an image in darkroom, activate the tonecurve module and shift some nodes. Any other module with sliders or any module when changing the sliders of a parametric mask should do the same.

This PR adds double buffering to the navigation panel.

### CODE REVIEW

**Comment by hanatos** [comment]
shouldn't gtk widgets be double-buffered already? i suspect that it might be enough to make the parent widgets transparent via css, to avoid the need for constant redrawing, but can't proof it at this time.. (that's one difference between gtk2 and gtk3, that all in-between widgets such as event boxes, hboxes, etc now are drawn solid)

**Comment by LebedevRI** [comment]
Looks good to me, but i agree with hanatos.
There must be another way, to just completely skip redrawing when we are not ready to draw.

**Comment by upegelow** [comment]
Fine if there is a better way.

**Comment by hanatos** [comment]
all i tried in 3 minutes with css actually made it worse.. i would say if we can't quickly find the better gtk way let's just merge, this flicker is really annoying.

**Comment by hanatos** [comment]
(i think something similar happens when leaving darkroom mode. instead of just leaving the old image there until light table exposes, the background first draws itself over everything in solid gray)

**Comment by upegelow** [comment]
I suggest we merge. We can always drop double buffering if we find a better fix later.

**Comment by LebedevRI** [comment]
I have looked at other approaches to fixing this issue, and i do not think i can do anything workable right now, although i do believe i know how to fix it.
So yes, @upegelow rebase and we'll merge it as it is for now.

**Pull request merged**
