### PR TITLE
export_metadata: make $(variables) completion work.

### PR DESCRIPTION
**Pull request by phweyland**
- remove also the list of variables from the tooltip (not visible and flickering/blinking)

The same flickering/blinking (at least on my low definition screen) happens also on filename field of export module. This may be due to the fact the list is now too large.

### CODE REVIEW

**Comment by elstoc** [comment]
I don't get the flickering but I can rarely see the whole tooltip

**Review by TurboGit — COMMENTED** [review]
As we are at it I would do the same for the export entry where indeed the tooltip cannot be seen completely and is mostly noise and annoying now.

**Comment by phweyland** [comment]
Done.

**Review by TurboGit — APPROVED** [review]
Thanks, nice clean-up!

**Pull request merged**
