### PR TITLE
channelmixerrgb: double CAT false positive warnings, take 3

### PR DESCRIPTION
**Pull request by aurelienpierre**
Ugh #7271 -_-

### CODE REVIEW

**Comment by TurboGit** [comment]
With this patch I always get dt crash and when fixing code I still have double CAT.

**Comment by kofa73** [comment]
This version, after removing .config/darktable, produces a segfault during darktable startup. Logs: https://tech.kovacs-telekes.org/files/dt-7324/

**Comment by TurboGit** [comment]
@aurelienpierre : I fear the issue is in the fact that the iop_entry recorded as CAT reference isn't stable and after some debug info I found that the first one registered (too early while pipe is inited?) has an iop_order = 0 and this one will be used, the next run a proper iop_order is found and so the module is considered as another one and => double CAT !

**Comment by aurelienpierre** [comment]
I'm almost tempted to remove the warnings at all at that point.

**Comment by aurelienpierre** [comment]
Or just a check if iop_order == 0 ?

**Comment by TurboGit** [comment]
@aurelienpierre : no `iop_order_f > 0.0f` but I have also a doubt about another check.

**Comment by TurboGit** [comment]
@aurelienpierre : I think I have a fix, I'll send a PR this afternoon and if needed we can talk about this live to definitely fix this issue before the release.

**Comment by aurelienpierre** [comment]
@TurboGit ok, call me whenever you need.

**Pull request closed without merging**
