### PR TITLE
fix reject toggle issue

### LINKED ISSUE #4760: A quite annoying bug: cancel a rejected image is no more possible
**Describe the bug**
On last master, cancel a rejected image is no more possible.

**To Reproduce**
Provide detailed steps that can reproduce the behavior, such as:
1. On lighttable, just select an image (with shortcut or clicking on the cross)
2. Select the same rejected image and try to cancel last action by clicking again on the red cross or with 'r' shortcut.
=> image still rejected...

**Expected behavior**
Have possibility to cancel a rejected image.

### PR DESCRIPTION
**Pull request by phweyland**
As pinpointed by @AlicVB 
Fixes #4760

### CODE REVIEW

**Comment by Nilvus** [comment]
Thanks @phweyland. Just see that. So maybe PR #4779 from @TurboGit should be closed?

**Comment by Nilvus** [comment]
Just tested and confirm that it fix the issue.

**Comment by TurboGit** [comment]
Thanks ! Better than my fix.

**Comment by phweyland** [comment]
> the possibility to cancel a rejected image with the 'r' shortcut

The shortcut applies on list of images, therefore toggle feature is not included.

**Pull request merged**
