### PR TITLE
[masks/shapes] make hinter messages match what's possible

### LINKED ISSUE #7593: Shift+scroll hint not available when brush stroke highlighted
Current master.

Select cursor to view all the shapes in retouch.
image

Don't recall if `shift+scroll` was ever mentioned in the text for setting feathering/hardness when the brush stroke is highlighted.

image

### PR DESCRIPTION
**Pull request by johnny-bit**
fixes #7593

Hinter messages were lacking couple hints. Added missing hints.

### CODE REVIEW

**Comment by johnny-bit** [comment]
Pinging @elstoc bacause maybe this might have some connections with docs :)

**Review by TurboGit — COMMENTED** [review]
On some screen the length of the hint was reported too wide. I would propose to rework all the mask hints as follow (removing "to set") to gain space:

**size**: scroll, **hardness**: shift-scroll, **opacity**: ctrl-scroll.

And with all actions in bold to ensure better reading. How does that sound ?

**Comment by elstoc** [comment]
Sounds good to me. I don't think this will impact dtdocs.

**Comment by johnny-bit** [comment]
I'll rework it tomorrow then...

as for docs - I *think* all are accurate, maybe with exception of brush which has reversed scroll/shift-scroll for size/feathering changes. Just wanted to check if docs need checkup.

**Comment by johnny-bit** [comment]
Done... + i made it a bit prettier and toastier ;)

**Comment by TurboGit** [comment]
Merged in master, queued for 3.4.1.

**Pull request merged**
