### PR TITLE
Nikon D5: reenable camera support after check, fixes #11236

### LINKED ISSUE #11236: Canon M6 weird Color Matrix in white balance module
while in white balance camera reference color temperature is shown is 6502K for 3.8.1 it's 25000 in current master.
also there's no valid tint value displayed
 
image

**Platform**
* darktable version : darktable-3.9.0+556~g70f65c0ff
* OS                : OSx

### PR DESCRIPTION
**Pull request by schenlap**
Samples in ticket are all black, for D5_Uncompressed_12bit.NEF i get a
warning: {{{[rawspeed] (D5_Uncompressed_12bit.NEF) Skipped out of buffer
}}}

Samples from
http://www.photographyblog.com/reviews/nikon_d5_review/sample_images/
are ok.

### CODE REVIEW

**Comment by schenlap** [comment]
I don't know if we should merge this, as the samples in the ticket produce a warning.

**Comment by LebedevRI** [comment]
I will merge this.
That is a separate issue, feel free to open new bugreport to track it.

**Comment by LebedevRI** [comment]
~~The _actual_ problem here, i think, is the seemingly different black levels though.~~
I rechecked, and based on the *current samples* you are right, only the 12bit raws from D5 have blacklevel of 100, all 14bit have blacklevel of 400.

**Comment by LebedevRI** [comment]
@schenlap thank you!

**Pull request merged**
