### PR TITLE
Add darktable.gui->ppd_thb and preview_downsampling correction to focus display.

### LINKED ISSUE #6737: CTRL+W  (preview with focus detection) seems to be offset top left for windows build
When I do a ctrl+w in lighttable the red focus boxes appear top left. Which clearly is not the focus area. I wonder if the placement of these boxes has got affected with some of the dpi changes or image display resolution changes.

image

On todays master build for windows.

Same image ctrl+w
On windows 
image

On linux
image

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Fixes #6737

### CODE REVIEW

**Comment by TurboGit** [comment]
That's not fixing the issue to me when the preview down-sampling is set to something different that original. Just set it to 1/4 and you'll see that the focus point are all grouped into the top-left corner.

**Review by TurboGit — CHANGES_REQUESTED** [review]
Looks like there is still a missing scaling somewhere.

**Comment by jenshannoschwalm** [comment]
Ah, i didn't check the preview downsampling at all, i never use it.

**Comment by jenshannoschwalm** [comment]
Yeah, but that was related to preview_downscaling ...

**Comment by jenshannoschwalm** [comment]
Should be fixed

**Comment by chhil** [comment]
Tested changes on windows and linux, the boxes appear same size and location. I consider this fixed.

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Pull request merged**
