### PR TITLE
fix zoom in and out for small images

### PR DESCRIPTION
**Pull request by Mark-64**
This PR will fix issue #8014 erratic behavior in darkroom for zoom-in and zoom-out, with both mouse scroll and keyboard shortcut, when working on small images and/or large screens.
In those cases the fit-to-screen scale could be above 1:1 and this will cause issues without the PR: reverse zoom action ar no zoom at all.
The case is less infrequent as one may think, due to diffusion of HiDPI displays.

### CODE REVIEW

**Comment by Mark-64** [comment]
I have no clue why CI failed with this simple PR:

```
  remote: Not Found
  Error: fatal: repository 'https://github.com/darktable-org/rawspeed.git/' not found
  Unable to fetch in submodule path 'src/external/rawspeed'; trying to directly fetch f383f62eda0d22f53ea1b09c42348d63b5c915ac:
  remote: Not Found
  Error: fatal: repository 'https://github.com/darktable-org/rawspeed.git/' not found
  Fetched in submodule path 'src/external/rawspeed', but it did not contain f383f62eda0d22f53ea1b09c42348d63b5c915ac. Direct fetching of that commit failed.
  Error: The process '/usr/bin/git' failed with exit code 1
```

What should I do ? Plase help

**Comment by TurboGit** [comment]
I restarted the checks, rawspeed is ok now but whereami is failing in a similar way !

**Comment by TurboGit** [comment]
Restarted again, we'll see!

**Comment by johnny-bit** [comment]
Unfortunately CI sometimes needs to be kicked for interminent errors, but it is still very reliable checking tool and should be heard...

**Comment by TurboGit** [comment]
Thanks !

**Pull request merged**
