### PR TITLE
Allow for 400% and 800% zoom.

### PR DESCRIPTION
**Pull request by TurboGit**
Avoid a large gap between 200% and 1600%.

### CODE REVIEW

**Comment by LebedevRI** [comment]
Would be great to have.

**Comment by aurelienpierre** [comment]
That's it ?

**Comment by TurboGit** [comment]
What do you mean Aurélien? Yes, that's it, the support was there for all power of 2, only the entries to select those zoom levels were not wired.

**Comment by aurelienpierre** [comment]
Ok, I thought this would lead to some interpolation updates as well.

**Comment by TurboGit** [comment]
Tested to death :) working as expected on my side.

**Comment by PaoloAst** [comment]
Thank you @aurelienpierre, it works fine! In your opinion, could be possible to add the possibility to change the zoom level using the mouse wheel too,, like when the zoom is under 200%?

**Comment by aurelienpierre** [comment]
I did nothing here @PaoloAst. I don't know for the mouse, I'm really not a GUI guy. I'm only playing with equations, that's all I understand.

**Pull request merged**
