### PR TITLE
Add distinguishable text for always-on entries in history.

### PR DESCRIPTION
**Pull request by TurboGit**
This was hitching me since some tine now. @Nilvus, what do you think?

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
This really looks great! Will lead to less confusions.

**Comment by TurboGit** [comment]
@jenshannoschwalm : this with #3392 should avoid most issues about the history regarding default modules.

I just want to have feedback from @Nilvus on the CSS/GUI part before merging.

**Comment by Nilvus** [comment]
@TurboGit :  I’m at work so I will see that tonight

**Comment by aurelienpierre** [comment]
I like it.

**Comment by Nilvus** [comment]
@TurboGit : a really good thing to distinguish these modules on all part of darkroom. A more consistent and efficient UI with your adds on these. Great job. I really like it.

Only thing is I find the color text lacks a little bit contrast on all themes and especially on grey themes. Just change shade color on css you use from 0.8 to 0.9 make a better contrast on all themes. So I would change line 346 to that :

`  color: shade(@plugin_label_color, 0.9);`

**Comment by TurboGit** [comment]
Fine with me. Will do.

**Comment by TurboGit** [comment]
I have also tagged the first "original" node as always one. Thanks for the review.

**Pull request merged**
