### PR TITLE
themes: make icons styles work with user css tweaks

### LINKED ISSUE #5176: Themes icons issue: no icons visible if activate new usercss setting
**Describe the bug**
Icons from any theme icons are no more visible when activating the new usercss file. @elstoc: this one probably for you!

**To Reproduce**

1. Go to preferences (be in darkroom before to see issue directly)
2. Activate on of the icons themes
3. Check modify theme with CSS tweaks below
4. Just save it and see icons no more visible (no need to add any tweak to see the issue.

--> uncheck modify theme with CSS tweaks and see icons visible again.

**Expected behavior**
Apply icons and see them visible if CSS personal tweaks is activate.

### PR DESCRIPTION
**Pull request by elstoc**
modify how user css tweaks are loaded so that it can handle the relative
paths in the icon urls in the -icons themes

Resolves #5176

### CODE REVIEW

**Comment by Nilvus** [comment]
Tested and confirm it's fixed. Thanks.

**Comment by elstoc** [comment]
Thanks for testing @Nilvus. I've just pushed a much neater solution. Would you mind doing a quick retest.

**Comment by Nilvus** [comment]
Works too.

**Comment by TurboGit** [comment]
Looks good, thanks!

**Pull request merged**
