### PR TITLE
fix sqlite 3.15 (ubuntu 18) issue on duplicate image

### LINKED ISSUE #5696: Duplicating an image/.XMP results in an SQL error
I was trying the duplicate facility.  I think I clicked on "create duplicate with same stack" in darktable.  It created the filename_01.CR2.xmp and there was no obvious problem in dt gui, but the Terminal window had this -

paulssd2@shovel2:~$ $HOME/DT-Mast-9Jun20/bin/darktable --cachedir $HOME/.cache/darktable-9jun --configdir $HOME/.config/darktable-9jun

[export_job] exported to `/mnt/b3fa3123-84fd-4cfc-97a8-567e75014d9a/Data/CR2 Store/2020_05_20-Queens-Road-walk-TIDIED/_5D_02396-soldier1-V1-S-sRGB.jpg'

sqlite3 error: /home/paulssd2/DT-Mast-9Jun20/darktable-code/src/common/image.c:868, function dt_image_duplicate_with_version(), query "INSERT INTO main.tagged_images (imgid, tagid, position)  SELECT ?1, tagid,         (SELECT (IFNULL(MAX(position),0) & 0xFFFFFFFF00000000)         FROM main.tagged_images)         + (ROW_NUMBER() OVER (ORDER BY imgid) << 32) FROM main.tagged_images AS ti WHERE imgid = ?2": near "OVER": syntax error

sqlite3 error: /home/paulssd2/DT-Mast-9Jun20/darktable-code/src/common/image.c:869, function dt_image_duplicate_with_version(): near "OVER": syntax error

sqlite3 error: /home/paulssd2/DT-Mast-9Jun20/darktable-code/src/common/image.c:870, function dt_image_duplicate_with_version(): near "OVER": syntax error

[export_job] exported to `/mnt/b3fa3123-84fd-4cfc-97a8-567e75014d9a/Data/CR2 Store/2020_05_20-Queens-Road-walk-TIDIED/_5D_02396-soldier2dark-V1-S-sRGB.jpg'

Blank lines added for clarity.

dt 3.1.0+2017~ga6c18e1b7-dirty       Ubuntu 18.04      i7  32Gb    no vid card

### PR DESCRIPTION
**Pull request by phweyland**
fixes #5696

@RawConvert I have tested the code but I would appreciate if you could test on your side how it works, including  integration with sqlite 3.15. Thanks in advance.

### CODE REVIEW

**Comment by TurboGit** [comment]
Looks good, thanks.

**Comment by RawConvert** [comment]
Looks OK.  Just built Master - dt 3.1.0+2440~g673f25287-dirty - and created duplicate XMPs, both in light- & dark- table.  No messages in the Terminal window.

Why was this new Issue created instead of using #5696?

**Comment by phweyland** [comment]
> Why was this new Issue created instead of using #5696?

Not an issue, a pull request ... :)

**Comment by RawConvert** [comment]
Aha.

I thought I'd check on the version etc.  Here's a section from today's build, not 3.15!...
...
-- Found LensFun: /usr/lib/x86_64-linux-gnu/liblensfun.so  
-- Found Sqlite3 3.22.0
-- Sqlite3 version older than 3.24, some features may be downgraded
-- Found GIO
...

Just thought you should know.

**Comment by phweyland** [comment]
Yes you are right, the title of the PR is not exact. 
If < 3.15 you cannot build dt, but if <3.24 sqlite has not the required functions.
Interesting to know that ubuntu 18 includes now sqlite 3.22.

**Pull request merged**
