### PR TITLE
gtk: Ensure proper default panel size when starting dt for the first …

### LINKED ISSUE #12855: default layout not very attractive
Now that the panels don't have a minimal size the default layout when dt starts from the first time is not really attractive. For the first contact with dt I don't think this is good... See what I get:

image

None of the module labels on the right are readable. I think we should ensure a minimal default when starting the first time.

@dterrahe : One for you :)

### PR DESCRIPTION
**Pull request by TurboGit**
…time.

Fixes #12855.

### CODE REVIEW

**Comment by dterrahe** [comment]
Maybe these two variables should be added to darktableconfig.xml.in with a default?

**Comment by TurboGit** [comment]
> Maybe these two variables should be added to darktableconfig.xml.in with a default?

I thought about this...But was too lazy :)

```
#define DT_UI_PANEL_SIDE_DEFAULT_SIZE 350
#define DT_UI_PANEL_BOTTOM_DEFAULT_SIZE 120
```

I'll moved them into `darktableconfig.xml.in`.

**Comment by TurboGit** [comment]
@dterrahe : New version pushed using config keys.

**Comment by dterrahe** [comment]
Sorry, I should have been clearer. What I meant was that if the panel _size_ variables (not _default_ size) are defined explicitly in the XML, then they can be given a default there and the extra code to do that becomes redundant.

**Comment by TurboGit** [comment]
> Sorry, I should have been clearer. What I meant was that if the panel _size_ variables (not _default_ size) are defined explicitly in the XML, then they can be given a default there and the extra code to do that becomes redundant.

That's not possible as those keys are depending on the view, so all panels in all the views are using different keys. I don't want to add all the combination. And moreover if we add a new view in dt this will break and we will need more keys to be added.

**Comment by dterrahe** [comment]
You are right of course, sorry. Not behind computer so didnt really look too closely.

**Comment by dterrahe** [comment]
I'm wondering if the _natural_ width of the panel could be used as the default if not initialised yet. If that works it might be better supporting different resolutions. Let me have a look when I get up.

**Comment by TurboGit** [comment]
> Let me have a look when I get up.

Sure!

**Comment by TurboGit** [comment]
Closing as worked on #12866.

**Pull request closed without merging**
