### PR TITLE
rework homebrew build scripts to use build folder

### PR DESCRIPTION
**Pull request by zisoft**
The MacOS build scripts for homebrew creates builds and installs within `packaging/macosx`.

This PR is a rework of the scripts to use the build folder, keeping the source tree clean.

### CODE REVIEW

**Review by TurboGit — COMMENTED** [review]
Is it expected to commit this empty script : `Y_cleanup_hb_darktable.sh`

**Comment by zisoft** [comment]
The script should be deleted, not an empty file.
Will check.

**Comment by zisoft** [comment]
Fixed.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
