### PR TITLE
Fix warning about missing cl target opencl version

### PR DESCRIPTION
**Pull request by darix**
Fix warning about missing CL_TARGET_OPENCL_VERSION.

As the default fallback seems to be 220 I use that as a default version

```
In file included from /usr/include/CL/cl.h:32,
                 from /home/abuild/rpmbuild/BUILD/darktable-3.0.0rc0~git23.cb0aaf0c1/src/common/dlopencl.h:27,
                 from /home/abuild/rpmbuild/BUILD/darktable-3.0.0rc0~git23.cb0aaf0c1/src/common/opencl.h:38,
                 from /home/abuild/rpmbuild/BUILD/darktable-3.0.0rc0~git23.cb0aaf0c1/src/develop/imageop.h:37,
                 from /home/abuild/rpmbuild/BUILD/darktable-3.0.0rc0~git23.cb0aaf0c1/src/develop/develop.h:30,
                 from /home/abuild/rpmbuild/BUILD/darktable-3.0.0rc0~git23.cb0aaf0c1/src/control/jobs/develop_jobs.h:22,
                 from /home/abuild/rpmbuild/BUILD/darktable-3.0.0rc0~git23.cb0aaf0c1/src/control/jobs.h:99,
                 from /home/abuild/rpmbuild/BUILD/darktable-3.0.0rc0~git23.cb0aaf0c1/src/control/control.h:32,
                 from /home/abuild/rpmbuild/BUILD/darktable-3.0.0rc0~git23.cb0aaf0c1/src/bauhaus/bauhaus.h:23,
                 from /home/abuild/rpmbuild/BUILD/darktable-3.0.0rc0~git23.cb0aaf0c1/src/bauhaus/bauhaus.c:20:
/usr/include/CL/cl_version.h:34:9: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
   34 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
      |         ^~~~~~~
In file included from /usr/include/CL/cl.h:32,
                 from /home/abuild/rpmbuild/BUILD/darktable-3.0.0rc0~git23.cb0aaf0c1/src/common/dlopencl.h:27,
                 from /home/abuild/rpmbuild/BUILD/darktable-3.0.0rc0~git23.cb0aaf0c1/src/common/opencl.h:38,
                 from /home/abuild/rpmbuild/BUILD/darktable-3.0.0rc0~git23.cb0aaf0c1/src/develop/imageop.h:37,
                 from /home/abuild/rpmbuild/BUILD/darktable-3.0.0rc0~git23.cb0aaf0c1/src/common/color_picker.c:23:
/usr/include/CL/cl_version.h:34:9: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
   34 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
      |         ^~~~~~~
```

### CODE REVIEW

**Comment by darix** [comment]
This should be backported to 3.0

**Comment by darix** [comment]
it seems https://github.com/darktable-org/darktable/pull/3302 also sneaked in here. so in doubt accept 3302 first

**Comment by parafin** [comment]
@aurelienpierre, why the hell did you write the commit message b4c5fc58c1274585a6afe0bae5733e7bed514042 saying that you've updated headers to version 1.2, while actually it's OpenCL 2.2 and then you even went ahead and patched upstream headers in-place? src/external should contain unmodified files from upstream, not just random code. Maybe we should find actual OpenCL 1.2 headers and re-upload them to the repo. Or at least we should check that @darix's change in this PR make them identical to OpenCL 2.2 headers from khronos.

**Comment by darix** [comment]
I moved the patched code to config.h

**Comment by parafin** [comment]
Can you confirm that now all files match to unmodified version?

**Comment by parafin** [comment]
OK, they definitely not, at least cl.hpp and copyright are outdated. Someone has to fix that mess and write normal commit message, saying that it's actually OpenCL 2.2, not 1.2.

**Comment by darix** [comment]
uhm here it matches now. except for cl.hpp which seems to be something DT specific (and then should probably be in src/common and not src/external/CL

**Comment by parafin** [comment]
cl.hpp doesn't look DT-specific. It's OpenCL C++ bindings. I'm not sure if this file is needed at all, DT will probably build fine without it.

**Comment by parafin** [comment]
Fixed remaining files and merged manually.

**Comment by TurboGit** [comment]
Instead of copying the files we may want to introduce a sub-module as done for rawspeed. This will avoid being tempted to change the code in dt repo.

What is the main repository for these files?

**Comment by parafin** [comment]
https://github.com/KhronosGroup/OpenCL-Headers

**Comment by TurboGit** [comment]
@parafin : thanks, see #3309 (I have checked that the sources are exactly the same as the current ones).

**Comment by aurelienpierre** [comment]
> @aurelienpierre, why the hell did you write the commit message [b4c5fc5](https://github.com/darktable-org/darktable/commit/b4c5fc58c1274585a6afe0bae5733e7bed514042) saying that you've updated headers to version 1.2, while actually it's OpenCL 2.2 and then you even went ahead and patched upstream headers in-place? src/external should contain unmodified files from upstream, not just random code. Maybe we should find actual OpenCL 1.2 headers and re-upload them to the repo. Or at least we should check that @darix's change in this PR make them identical to OpenCL 2.2 headers from khronos.

My bad. I updated the files to OpenCL 2.2 for all the vendor built-in stuff, but forced the 1.2 idiom using pre-processor constants.

> As the default fallback seems to be 220 I use that as a default version

I actually forced the 120 version to make every vendor × plateform use the same version and hopefully avoid different results we will never have time to debug.

**Comment by darix** [comment]
well the force is in config.cmake.h now. and I patched all users of CL.h to include it before CL.h

**Comment by aurelienpierre** [comment]
Fair enough, I will have a look tomorrow.

**Pull request closed without merging**
