### PR TITLE
RFC: Improve rating range filter (and more)

### LINKED ISSUE #11757: Improve star rating filter
A couple of issues with the new star rating filter in the top bar of the lighttable view.

The first is that, in its default (all selected) state, it draws the eye a bit too much and can be distracting - it's quite bright and high-contrast.

The second is that it is somewhat hard to read at-a-glance. If I select a range of ratings, especially in the middle of the range, I have to look hard to see which stars I've selected. For example:

Screenshot_2022-05-07_22-49-21

The main thing I see when I just glance at this control is that two stars are highlighted. But I have to engage extra brain functions to work out which two stars are selected (is it two to three, or four to five?). In the previous interface, I usually used "greater than or equal to" by default so when I saw two stars highlighted in the top bar I instantly knew what that meant without having to think further (two == two or more stars). It's "intuitive" in the way that looking at an analogue clock is. In the new way it's the opposite, in that if I select "two or more stars", I will actually see three stars highlighted. This is hard on my tiny brain.

### PR DESCRIPTION
**Pull request by Nilvus**
This PR improve (I hope it will improve a lot) rating range filter.

I spent some time to test a lot of possibilities with @AlicVB help to complete that work. Thanks to him again!
We think it's:
- better than before in terms of contrast and visibility
- more sober
- allows a separation between the rejected icon and the stars (one of the criticisms)
- close to what we had before (but better)

**Darker theme**
Before:
image
After:
image

Before:
image
After:
image

**Dark theme**
Before:
image
After:
image

Before:
image
After:
image

**Grey theme**
Before:
image
After:
image

Before:
image
After:
image

@wpferguson: as it's thanks to you that I have finally understood why some users like you were having difficulties with that filter, your feedback is especially welcomed. I do not change the reject icon but I hope with all other changes, visibility and readability would now be good.

Just some notes:
- no there will not be any numbers, I think it's would reduce understanding that this is related to stars. Adding number on stars for such tiny icons would be worse too.
- take in consideration that I have my eyes on your answers (as well as @AlicVB of course) and so it's hard to be sure of what you will see. That's why feedback is needed, more than usual!

This PR also change blue color label to increase visibility, especially in darker themes.
This also reduce spacing between filters in left panel, following @difrkaguilar there: #13065

@TurboGit: if feedback are great, I hope this could go in 4.2 as it's as well as bugfix as little and safer improvement.

This PR so should (I hope) fix #11757

### CODE REVIEW

**Review by AlicVB — APPROVED** [review]
All good for me ! Thanks again @Nilvus for your work

**Comment by Nilvus** [comment]
Based on that PR, @TurboGit propose to make the line horizontal for no star icon. The result would so be (grey theme here as an example):

image
image

For those who want to test that, just apply that diff to that PR:

```
diff --git a/src/dtgtk/paint.c b/src/dtgtk/paint.c
index fe4c8af5b..31d9acce2 100644
--- a/src/dtgtk/paint.c
+++ b/src/dtgtk/paint.c
@@ -1735,8 +1735,8 @@ void dtgtk_cairo_paint_unratestar(cairo_t *cr, gint x, gint y, gint w, gint h, g
     else
       cairo_set_source_rgba(cr, r, g, b, a*.7);
 
-    cairo_move_to(cr, .9, .1);
-    cairo_line_to(cr, .1, .9);
+    cairo_move_to(cr, .1, .5);
+    cairo_line_to(cr, .9, .5);
     cairo_stroke(cr);
   }
```

Of course, think about testing that PR (and that diff) with all 3 themes for better feedback. Thanks.

**Comment by gi-man** [comment]
My silly comment is the hamburger menu. The spacing between the 3 lines seems too apart, more so when the import module hamburger menu is right next to it.

**Comment by Nilvus** [comment]
@gi-man: this PR is related to improve rating, not hamburger menu.

**Comment by TurboGit** [comment]
@Nilvus : Found an issue, do a range selection from 2 to 4 stars:

image

Do the very same selection again:

image

(this happens only if when selecting the first start the cursor is with the left-bar:

image

Maybe that was there before this PR, didn't check but never had this issue.

**Comment by Nilvus** [comment]
Not an issue from my PR. This is already there on master. And I don't have skills to fix that.

**Comment by AlicVB** [comment]
first, let's report @difrkaguilar comment here : https://github.com/darktable-org/darktable/issues/13065#issuecomment-1336521632
> the stars looks great as @TurboGit proposed with the horizontal line.

yes, that solution is great too...

**Pull request merged**
