### PR TITLE
avoid rerunning collection queries on star-rating change

### LINKED ISSUE #9042: very slow star rating or using filer in lighttable
**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Use a database with lot of collections
2. Go to 'lighttable'
3. Over and image and click on the star on the thumb
4. See error, it takes long time before the star is actually applied

**Expected behavior**

Should be just instantaneous (as before).

**Platform**

* darktable version master
* OS                : Linux

**Additional context**

See line 16,638286 where the SQL query tales 1 full second.

```
16,636658 [sql] /home/obry/dev/builds/darktable/build/src/src/common/collection.c:1058, function dt_collection_get(): prepare "SELECT id FROM main.selected_images AS s JOIN (SELECT DISTINCT mi.id FROM (SELECT  id, group_id, film_id, filename, datetime_taken,   flags, version,  position, aspect_ratio,  maker, model, lens, aperture, exposure, focal_length,  iso, import_timestamp, change_timestamp,  export_timestamp, print_timestamp  FROM main.images AS mi  ) AS mi WHERE   (flags & 256) != 256  AND  (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/mnt/photos/Photos/2021/avril/pâques liam'))) ORDER BY filename, CASE WHEN flags & 8 = 8 THEN -1 ELSE flags & 7 END DESC, version) AS mi WHERE mi.id = s.imgid LIMIT -1, ?3"
16,637492 [sql] /home/obry/dev/builds/darktable/build/src/src/common/collection.c:2193, function dt_collection_image_offset_with_collection(): prepare "SELECT DISTINCT mi.id FROM (SELECT  id, group_id, film_id, filename, datetime_taken,   flags, version,  position, aspect_ratio,  maker, model, lens, aperture, exposure, focal_length,  iso, import_timestamp, change_timestamp,  export_timestamp, print_timestamp  FROM main.images AS mi  ) AS mi WHERE   (flags & 256) != 256  AND  (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/mnt/photos/Photos/2021/avril/pâques liam'))) ORDER BY filename, CASE WHEN flags & 8 = 8 THEN -1 ELSE flags & 7 END DESC, version"
16,638227 [sql] /home/obry/dev/builds/darktable/build/src/src/dtgtk/thumbtable.c:238, function _thumb_get_rowid(): prepare "SELECT rowid FROM memory.collected_images WHERE imgid=95735"
16,638261 [sql] /home/obry/dev/builds/darktable/build/src/src/dtgtk/thumbtable.c:238, function _thumb_get_rowid(): prepare "SELECT rowid FROM memory.collected_images WHERE imgid=95735"
16,638286 [sql] /home/obry/dev/builds/darktable/build/src/src/dtgtk/thumbtable.c:1923, function dt_thumbtable_full_redraw(): prepare "SELECT rowid, imgid FROM memory.collected_images WHERE rowid>=1 LIMIT 12"
16,640496 [sql] /home/obry/dev/builds/darktable/build/src/src/libs/collect.c:1885, function list_view(): prepare "SELECT folder, film_rolls_id, COUNT(*) AS count FROM main.images AS mi JOIN (SELECT id AS film_rolls_id, folder       FROM main.film_rolls)   ON film_id = film_rolls_id  WHERE (1=1) GROUP BY folder ORDER BY film_rolls_id DESC"
17,577917 [sql] /home/obry/dev/builds/darktable/build/src/src/libs/duplicate.c:403, function _lib_duplicate_init_callback(): prepare "SELECT i.version, i.id, m.value FROM images AS i LEFT JOIN meta_data AS m ON m.id = i.id AND m.key = ?3 WHERE film_id = ?1 AND filename = ?2 ORDER BY i.version"
17,578277 [sql] /home/obry/dev/builds/darktable/build/src/src/common/collection.c:1037, function dt_collection_get_selected_count(): prepare "SELECT COUNT(*) FROM main.selected_images"
17,578377 [sql] /home/obry/dev/builds/darktable/build/src/src/libs/image.c:250, function _update(): prepare "SELECT COUNT(id) FROM main.images WHERE group_id = ?1 AND id != ?2"
17,588142 [sql] /home/obry/dev/builds/darktable/build/src/src/common/collection.c:1037, function dt_collection_get_selected_count(): prepare "SELECT COUNT(*) FROM main.selected_images"
17,588261 [sql] /home/obry/dev/builds/darktable/build/src/src/libs/tools/timeline.c:621, function _time_read_bounds_from_collection(): prepare "SELECT db.datetime_taken FROM main.images AS db, memory.collected_images AS col WHERE db.id=col.imgid AND LENGTH(db.datetime_taken) = 19 AND db.datetime_taken > '0001:01:01 00:00:00' COLLATE NOCASE ORDER BY db.datetime_taken ASC LIMIT 1"
17,588502 [sql] /home/obry/dev/builds/darktable/build/src/src/libs/tools/timeline.c:642, function _time_read_bounds_from_collection(): prepare "SELECT db.datetime_taken FROM main.images AS db, memory.collected_images AS col WHERE db.id=col.imgid AND LENGTH(db.datetime_taken) = 19 AND db.datetime_taken > '0001:01:01 00:00:00' COLLATE NOCASE ORDER BY db.datetime_taken DESC LIMIT 1"
17,588788 [sql] /home/obry/dev/builds/darktable/build/src/src/common/history.c:1582, function dt_history_hash_get_status(): prepare "SELECT CASE  WHEN basic_hash == current_hash THEN 1  WHEN auto_hash == current_hash THEN 2  WHEN (basic_hash IS NULL OR current_hash != basic_hash) AND       (auto_hash IS NULL OR current_hash != auto_hash) THEN 4  ELSE 1 END AS status FROM main.history_hash WHERE imgid = 95735"
17,589015 [sql] /home/obry/dev/builds/darktable/build/src/src/common/image.c:320, function dt_image_full_path(): prepare "SELECT folder || '/' || filename FROM main.images i, main.film_rolls f WHERE i.film_id = f.id and i.id = ?1"
```

### PR DESCRIPTION
**Pull request by ralfbrown**
Since changing the rating of an image can't possibly change the results of a collection filter, skip the (possibly very slow) update of the collection module when the user changes a star rating.

Fixes #9042, at least with respect to star ratings.  Possibly other invocations of `dt_collection_update_query` could be changed from DT_COLLECTION_CHANGE_RELOAD to DT_COLLECTION_CHANGE_NONE.

### CODE REVIEW

**Comment by TurboGit** [comment]
This indeed works but there is many more cases not handled when collection "folder" is selected.

- Using filter to changer order or select the number of star or to display only rejected for example.
- Sorting by filename, start or whatever
- Changing the rating from the bottom toolbar
- Changing a color label from the bottom toolbar

Maybe other cases, not sure.

**Comment by ralfbrown** [comment]
Color labels need to be processed, since they can be a criterion for selecting the contents of the collection.  But the code in libs/collect.c could probably be smarter about handling the update request.

I've found and changed the `dt_collection_update_query` call all of the handlers for the `view` and `sort by` comboboxes at the top eventually invoke, so your first two bullet points have now been covered (and the fourth is moot).

**Comment by AlicVB** [comment]
I'll have a look, but we need to be extremely careful here : there's a lot of corner cases if we use the top toolbar filtering and/or ordering by rating, esp. if the rating change concern lot of images including potentially the first one...

**Review by AlicVB — CHANGES_REQUESTED** [review]
That works, but I see this as a workaround that may cause other issues sooner or later : 
in fact here you use `DT_COLLECTION_CHANGE_NONE` as a special case of `DT_COLLECTION_CHANGE_RELOAD` but that's not the meaning of this tag, fact is that currently `DT_COLLECTION_CHANGE_NONE` is not used, but I would prefer that you add another entry in the enum for this case...

That said, `DT_COLLECTION_CHANGE_RELOAD` signal is used when we have to rerun the collection query without changing it, because we suspect that the resulting set of images may have changed (rating with rate filetring/ordering is an example, but there is others)
I *think* it's used in collect lib for : 
- updating the image count
- some collect items (aspect ratio, tags, ...) which may have to update the list of items

So why not just skipping `DT_COLLECTION_CHANGE_RELOAD` event in collect lib in the case of `DT_COLLECTION_PROP_FOLDERS` and `DT_COLLECTION_PROP_FILMROLL` ?
We will lost the recounting for this 2 items (but that's the case with this PR anyway)...

**Comment by ralfbrown** [comment]
The problem is that omitting the `dt_collection_update_query` call entirely then leaves the thumbtable display unchanged if you change star rating or sorting, etc.  And by the time the signal reaches the collect lib, there isn't any way to tell whether the thing that changed might affect the display (e.g. we do need to update a folders or filmroll display if a prior rule filtered on color label and the user changed a color label on an image).

**Comment by AlicVB** [comment]
sorry, I may have unclear... What I would propose is to "just" do in libs/collect.c something like
```
if (query_change != DT_COLLECTION_CHANGE_RELOAD || property == DT_COLLECTION_PROP_FOLDERS)
  _lib_collect_gui_update(self);
```
So you don't touch anything in thumbtable

**Comment by ralfbrown** [comment]
Which, as I said, won't properly update if a prior filter rule changes the set of images.  Suppose you have as first rule 'color != purple' and then set the purple label on every image in Folder1.  Folder1 now needs to be removed from the folder view, but your proposed check skips that update.

**Comment by AlicVB** [comment]
oops... right, after some rereading, I think it's me who don't read your answer correctly... sorry...

but still, I'm not convinced of the solution you propose... As I see it, you make an "exception" for ratings because it doesn't appears in the collect module, right ?

So your fix is "rating" only and cant' fix the same issue that happens when you change a colorlabel... imho, we better should work on fixing the root cause than making a temporary fix that add complexity in the code... Not to speak than one day rating may very well be added to the collect module (I've seen FR about this and that's not so stupid)

**Comment by ralfbrown** [comment]
Closing in favor of #9058.

**Pull request closed without merging**
