### PR TITLE
scroll through presets using shortcut

### LINKED ISSUE #6651: dynamic preset shortcuts
Provide the ability to cycle through a module's presets with a keyboard shortcut (similar to how dynamic comboboxes work). This would be particularly useful for modules like the channel mixer, where multiple film emulation presets are available and it would be great to be able to trial them one at a time without having to reopen the presets menu each time.

Raising as a FR rather than a PR because I'm aware that @dterrahe is already doing a lot of work around shortcuts and I didn't want to conflict with any of that work.

### PR DESCRIPTION
**Pull request by dterrahe**
fixes #6651

In mapping mode, hover above the presets button of an iop header and press a key (or press a key and scroll if you have disabled fallbacks). Now pressing the key and scrolling moves through all the available presets for the module.

You can also explicitly, via the preferences/shortcuts dialog, assign buttons to the _previous_/_next_ effects of the _presets_ element of a module.

### CODE REVIEW

**Comment by TurboGit** [comment]
@dterrahe : I need help for testing this.

I have followed the instruction but cannot assign a preset. In mapping mode when I press a key over the preset button of the "color correction" module for example the key is said assigned. Good. Now pressing this key I get a popup menu with all the presets listed:

image

I have also tried via the preferences/shortcut tab but in this case I cannot see the previous/next action under preset.

Any idea? TIA.

**Comment by dterrahe** [comment]
Do you have fallbacks enabled? If not, try enabling them. Or if you don't want to do that, use the scroll wheel while assigning the key.

**Comment by TurboGit** [comment]
> Do you have fallbacks enabled?

Yes I do.

**Comment by TurboGit** [comment]
Maintaining the key and scrolling at the same time works.

**Comment by dterrahe** [comment]
This is implemented as "next"/"previous" _effects_ on the "presets" _element_ of the module action itself, not on the "preset" section (which doesn't accept shortcuts) or any of the individual presets underneath (which can only be "activated"). In visual mapping mode, if you assign the shortcut key while hovering over the preset button, it will be automatically assigned to the correct _element_.

If you have fallbacks enabled, then assigning a key to the (default) "show" _effect_, will trigger a fall back to "next"/"previous" when you scroll (or move the mouse. or a gamepad joystick. or whatever).

image

However, as a fun fact, if you assign the key to the default _element_ of the module ("show" instead of "presets"), then, while holding that key, a right-click will give you the presets menu. But if you _also_ hold the right-click and _then_ scroll (or move the mouse) you'll scroll through all the presets. So in the example above, press-and-hold "n" & press-and-hold right mouse button & turn scroll wheel.

**Comment by TurboGit** [comment]
@dterrahe : Thanks for all the precision, working for me now.

**Pull request merged**
