### PR TITLE
[imageio] .ORI is the raw file extension

### PR DESCRIPTION
**Pull request by victoryforce**

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Thanks ! Indeed an Olympus RAW file.

**Comment by TurboGit** [comment]
Just need a release notes entry for this. TIA.

**Comment by victoryforce** [comment]
AFAIK, the only thing this fix affects is the collection filter by filename. More precisely, when using this filter with RAW, NON-RAW, LDR, HDR pseudo-extensions to filter by the corresponding image types. When we open the image in the darkroom, the loader can "refine" the file type, but until the image was opened, the type determined by the file extension is assigned to it.

To be honest, it's hard for me to squeeze this long explanation into a sufficiently short description.

Perhaps this fix is not worth mentioning in the README?

**Comment by TurboGit** [comment]
> Perhaps this fix is not worth mentioning in the README?

You're right, it was my first thought. No entry needed after all.

**Pull request merged**
