### PR TITLE
fix module order - synch with history at import time

### PR DESCRIPTION
**Pull request by phweyland**
Related to #4313

### CODE REVIEW

**Comment by phweyland** [comment]
Should be better after lightroom import.

This fix should help getting more synchronized info from collection history / module order. However not sure that is enough.

**Comment by TurboGit** [comment]
One question though. Adding this here now means that all imported pictures have an iop-order list so we cannot distinguish the non yet edited pictures. Right? Won't that be a nuisance for your altered work? Or maybe I'm confused... (little time at the moment to review seriously).

**Comment by phweyland** [comment]
> Adding this here now means that all imported pictures have an iop-order list so we cannot distinguish the non yet edited pictures. Right?

In fact that doesn't change anything on history side, just on module_order side.
The collection / history - altered / not altered relies only on history.

But this PR makes collection / module order match with collection / history one (so far :)). Wants to answer your concern merging collection / history & module order.

**Comment by phweyland** [comment]
> Won't that be a nuisance for your altered work?

I don't think so. I'm still trying to find a firm ground to strengthen the altered / not altered status. This is part of it.

**Comment by TurboGit** [comment]
Ok, let's go with that then. Thanks.

**Pull request merged**
