### PR TITLE
Add support for incremental updates of legacy params for strorage & f…

### PR DESCRIPTION
**Pull request by TurboGit**
…ormat.

We already have incremental legacy_params for libs. This patch implement the incremental update of format & storage. This will make the implementation easier and less error prone as previous code won't have been to be touched at all.

Some comments have been added into the current legacy_params code to ensure that incremental update is known by devs.

### CODE REVIEW

**Comment by TurboGit** [comment]
I'll first test this on #14973.

**Review by ralfbrown — COMMENTED** [review]
Looks good.

**Comment by TurboGit** [comment]
@ralfbrown : Thanks for the review. I have update the code to properly work when a new version of storage/format will be introduced. In the old code path we want to convert to a given struct that must be captured and not to the latest param struct. I think this is now good to go.

**Comment by TurboGit** [comment]
Tested on a new update of disk, reviewed again....

Let's bit the bullet.

**Comment by Sturmflut** [comment]
Hi,

conversion of the "on conflict" settings of the disk export module didn't work as expected for me on the first try. What I did:

1. Delete `~/.config/darktable/`
2. Build and install `release-4.4.2` tagged branch
3. Run darktable
4. Set the "on conflict" setting to "skip"
5. Close darktable
6. Build and install `po/incr-legacy-params` branch
7. Run darktable

What happened: The "in conflict" setting is set to "overwrite if changed" (now index 2)

What should have happened: The "on conflict" setting is set to "skip" (now index 3 instead of 2)

**Comment by TurboGit** [comment]
@Sturmflut : I did just that as a test and did not run into trouble. Can you share a preset created with 4.4.2?

**Comment by TurboGit** [comment]
@Sturmflut : It occurs to me that you are just speaking of the GUI (no preset involved?), right? If it is the case then this is OK as we don't update the latest GUI setting. The `legacy_params()` is only for stored presets, styles and current edits (DB & XMP).

**Comment by Sturmflut** [comment]
@TurboGit Ah, that's right, I was already suspecting I got some terminology wrong! I didn't even realise presets can also store configuration for modules like disk.

Any reason why we don't convert the latest GUI settings? As mentioned that can be quite confusing.

**Comment by TurboGit** [comment]
No good reason not to, but some more work that has never been done. Also, it would seems awkward maybe to handle this in legacy_params as here we are talking about updating the preferences. At the end that's not big deal as removing the preferences to restart from clean install is something that is done by some users and here we lost the last setting too. So at the end, maybe not worth the effort.

**Comment by GLLM** [comment]
Just late-to-the-party posting on this already merged PR !
I just discovered this new option in Export dialog and I love it !!
Thanks to all involved on this, it's a great improvement ! 

@elstoc @Sturmflut @TurboGit

**Pull request merged**
