### PR TITLE
po/fix legacy spots

### PR DESCRIPTION
**Pull request by TurboGit**
- fix dt crash for any spot migrated from v1 to v2
- fix creation of group when migrating spot from v1 to v2 

Work for #8373.

### CODE REVIEW

**Comment by TurboGit** [comment]
@AlicVB : this issue is from 2013 when migrating spot to the new mask handling. Any idea to fix fix that? See the issue I have created with some more information. I'm in a dead-end at the moment....

**Comment by TurboGit** [comment]
I have attached the XMP in the issue, see #8373

**Comment by TurboGit** [comment]
Not a draft anymore, @AlicVB I finally found a solution, I won't say very clean but it is working and probably not much we can do. Can you have a look? TIA.

**Review by AlicVB — APPROVED** [review]
Great !
First : it works for the xmp you've provided earlier :)
About the code, I don't see anything wrong. Yes it's a little bit hacky, but only inside the spot iop itself, and we don't have really to care about providing a clean code for subsequent devs, as the module is deprecated... We just have to ensure the upgrade, and that's the case now !

Thanks !

**Comment by TurboGit** [comment]
@AlicVB : Thanks for the review. Merging!

**Pull request merged**
