### PR TITLE
Complete CSS rework: optimize code and fix some remaining glitches

### LINKED ISSUE #5017: rating for non selected picture not visible
On the lighttable, the stars are not visible when thumbs are not hovered on dark and darker theme. It is ok on grey theme.

### PR DESCRIPTION
**Pull request by Nilvus**
### Why CSS complete rework?

Since last great features and rework made on darktable (preferences window, lighttable, culling/preview modes), CSS has now quite a lot more things to be tweaked but it has now been quite messy.

So, all this need to see if CSS can be reorganized and reduced without breaking the UI (of course).

### First commit and what it brings

As I recently work on lighttable, culling and preview modes, I start on these modes. By inverting @AlicVB order and thanks for his work, I have been able to reduce same part by near to 30 lines (and I also add some comments line) and simplify this part. The logic was to hide and then make visible what's need to be visible. In first commit of this draft PR, I begin by main part then details, by making them visible, then hide then and finish by selected and hover effect.
That's also now to tweak easier this part. For main things, only one item need to be changed.

Fix #5017 

**Ui improvements**
Now all main parts visible on thumbnails have same line to tweak, so changing audio/group color (for example), on default state, will also change to same color text infos, stars (not active), reject (not check), etc...
Thumbnails should now be better rendering and hover effect more consistent for stars and group/audio hover effect.

I've passed on all modes a lot of times and on all 3 main themes to be sure all is ok. It's normally ok but any test will be appreciated to check I don't forgot anything on this part.

### CSS comments (update)

I also improve (hope so) how comments are applied to be more practical. I've set 2 steps: main part, look like that:
```
/*----------------------
  - General properties -
  ----------------------*/
```

And inside this part, on second step, which part is set in this main part, look like that:
`/* Background */`

For other specific comments (under-comment of a part or some detailed comments):
`/*** Example comment ***/`

### What's remain to do?

All other lines on CSS to check which part could be reduced/optimized.
Stay tuned and all your ideas, things to tweak/improve are welcome.

### CODE REVIEW

**Comment by Nilvus** [comment]
Second part of CSS rework from first line to line 517 and cleaning.

It's also easier to change font setting for all text without changing anything else, including dialog windows. Related to #3207 issue and last discussion on it (@elstoc and @aurelienpierre).

**Comment by TurboGit** [comment]
I did a quick test and found nothing obviously wrong.

**Comment by elstoc** [comment]
> It's also easier to change font setting for all text without changing anything else, including dialog windows. Related to #3207 issue

Changing the font size with ``* {font-size: 0.9em;}`` for example, does also seem to change the size of some icons. Is that the recommended way (in the tweaks panel) to change the font size? Or is this just because you're not finished yet?

BTW while you're making CSS changes it would be good to have CSS tweaks box in a fixed-width font.

**Comment by Nilvus** [comment]
> Changing the font size with `* {font-size: 0.9em;}` for example, does also seem to change the size of some icons. Is that the recommended way (in the tweaks panel) to change the font size? Or is this 
just because you're not finished yet?

This part is normally finished and for most icons, I think it's better that they changed with text to not have to big icons regardless of text. But if you see icons that would not, feel free to share.

> BTW while you're making CSS changes it would be good to have CSS tweaks box in a fixed-width font.

Not sure to understand here but if you talk about your CSS edit view in preferences, on my side font is fixed (but I update some things recently).

**Comment by Nilvus** [comment]
Main rework should be done. Some comments probably to add to improve all and some reviews/tests remaining (maybe some things to tweaks).

Feel free to test and see if all is ok. And more important: is this new CSS is clearer than before or not? I'm sure it is for Thumbnail part (so first commit) but no so for other parts. I've tried to reorder by main content then main part and then specific ones (and of course by respecting CSS needed order to avoid some glitches and not applied settings).

**Comment by elstoc** [comment]
The icons on the top-right of the screen seem to change quite a bit in size between 1em and 0.97em (Github's not accepting my uploads at the moment so I can't show you screenshots)

In terms of the usercss box I'm suggesting you add the following:

```
#usercss_box textview
{ font-family: monospace; }
```

**Comment by Nilvus** [comment]
> #usercss_box textview
> { font-family: monospace; }

Thanks, will add that (good idea). About icons, could you test last commit. I think you talk about group, star, help and prefs icons. I don't see any problem there but will see again.

**Comment by elstoc** [comment]
Same thing with the latest commit. Just seems to be quite sensitive to small changes (presumably when it gets to a whole number of pixels?). I think overall I still prefer using the standard sizes and just scaling the whole UI by changing the DPI. 

Generally though I don't see any issues with the CSS.

**Comment by Nilvus** [comment]
> Same thing with the latest commit. Just seems to be quite sensitive to small changes (presumably when it gets to a whole number of pixels?). I think overall I still prefer using the standard sizes and just scaling the whole UI by changing the DPI.

Changing with DPI could also have other issues (for some users). If it's only these icons, I've just found why. They are not only set by font-size and all things set with em would inherit for 

> Same thing with the latest commit. Just seems to be quite sensitive to small changes (presumably when it gets to a whole number of pixels?). I think overall I still prefer using the standard sizes and just scaling the whole UI by changing the DPI.

Changing DPI could other have issues (for some users and it's also OS related), so not a better thing for a standard way. If it's only those icons the issue for setting font with CSS, I just check and it's because these icons needs to be set emphasize and not only on font-size, and size is set by font-size and min-width and padding...
See on line 390 for that. I've changed min-width to 0.8em and size icons is better related but a little smaller on default font size. It's ok for me though. Will probably see if it could be better. What do you think of that way?

> Generally though I don't see any issues with the CSS. The comments are definitely useful, but I'm not sure about the indenting. It doesn't really look right to me. Perhaps you can make the main sections stand out a bit more by underlining the section headers or putting them in a 'box'? Something like...
> 
> ```
> /*----------------------
>   - General properties -
>   ----------------------*/
> ```

Of course, much better. My head was sometimes say that I already see better than my actual way without remembering what... Thanks for that proposal. Really much better and more readable. Work to do tomorrow.

Good to see I could forgot indent...

**Comment by elstoc** [comment]
> What do you think of that way?

I'm not entirely sure what you're proposing. How about you push a new commit when you're ready and I'll test it for you.

**Comment by Nilvus** [comment]
> > What do you think of that way?
> 
> I'm not entirely sure what you're proposing. How about you push a new commit when you're ready and I'll test it for you.

By now, I test that only in User CSS textview. So just copy on it that to test and tweak:
```

*,
dialog label
{
font-size: 1em;
}

#header-toolbar #dt-toggle-button,
#header-toolbar #dt-button,
#footer-toolbar #dt-toggle-button,
#footer-toolbar #dt-button
{
  padding: 0.9em;
  min-width: 0.8em;
  border: 0;
  font-size: .7em;
}
```

By default, on CSS, min-width is on 0.9em; and there's a min-height line but on what I test, this line is no more useful so I will remove it.

**Comment by elstoc** [comment]
> Said that, thanks again for the new preferences window and this CSS box. It's quite faster to test new teaks before integrate them on css files.

I'll admit I was skeptical about including the CSS edit box in the preferences but I agree it's really useful. Also means I can do this to show you both the screenshots and CSS all in one go...

So, with your suggestion, and removing any DPI tweaks, here is the difference between font size 1em:

Screenshot_2020-05-09_21-03-41

and 0.8em:

Screenshot_2020-05-09_21-03-58

I'd expect 0.8em to be 80% the size of 1em but seems to be much smaller. Similarly the top bar seems quite a bit smaller.  Looking at the GTK documentation (https://developer.gnome.org/gtk3/stable/chap-css-properties.html) it's not entirely clear how it all works:

>  Length values with the em or ex units are resolved using the font size value, unless they occur in setting the font-size itself, in which case they are resolved using the inherited font size value.
> The rem unit is resolved using the initial font size value, which is not quite the same as the CSS definition of rem. 

Based on this I wonder whether we should be using rems rather than ems because those are entirely defined in terms of the base font size, rather than in terms of an inherited size. If you've got an inherited size based on an inherited size, couldn't you be getting 0.8em of 0.8em (0.64em) where you're expecting 0.8em? As I say it's not clear how it should work here.

**Comment by elstoc** [comment]
If we wish (and this might be the better way to do it) it appears that the font size can be set globally (in points) before loading a theme. For example the following (added to the start of ``dt_gui_load_theme`` in ``gtk.c``) would set the font size to 13 points:

```
  g_object_set(gtk_settings_get_default(), "gtk-font-name", "13", NULL);
```
This would be the 'initial' font referenced above and would ensure that all of the other fonts / sizes in the CSS scaled in accordance with it. I suspect it might be harder to do consistently in CSS alone.

**Comment by johnny-bit** [comment]
Having font selector and/or font-size selector would be great! Just need to have list of recommended fonts so that there won't be bugs like "i changed my fonts to webdings size 30 and now can't use darktable" ;)

**Comment by elstoc** [comment]
I think I might have got a bit over-enthusiastic with the idea of changing the font face. TBH I think size is plenty.

**Comment by Nilvus** [comment]
> Having font selector and/or font-size selector would be great! Just need to have list of recommended fonts so that there won't be bugs like "i changed my fonts to webdings size 30 and now can't use darktable" ;)

Of course, it will be better. But waiting for that, having the most easier and powerful way to do that with CSS is all we have. And that's easier to do even if it's not so good and precise as a font and size selector.

**Comment by elstoc** [comment]
> And that's easier to do even if it's not so good and precise as a font and size selector.

I've gone ahead and started work on a font size selector (it's not hard) and will have a PR ready soon.

**Comment by Nilvus** [comment]
> I think I might have got a bit over-enthusiastic with the idea of changing the font name. TBH I think size is plenty.

@elstoc: Thanks for all your tests and ideas.
We can't set a default size/font in Gtk code. When @aurelienpierre made the new UI, he has two main goals (except making a beautiful one and most of the place to the image):
- don't have any part hardcoded and all parts possible to tweak on CSS
- be sure that all users have same UI, so with a fixed fond and set size regardless of this font

That 2nd one is partially done. At first, the darktable default theme was removed and so let only elegant one. Or, to be more precise, the darktable.css was on start the actual darker elegant. But quickly after the UI was merged, an original developer change that (without discussion) and put back the darktable actual CSS without elegant font, claiming that the default theme should remain related to OS font and OS font size.

So hardcode a size, even if it's to make it relative after, is not the best thing to do I think (even if I would ideally also see the actual default theme gone away...

Anyway, I will try to see what I can do by using some rems instead of ems. About your screenshots and your 80% tests, be careful, sometimes we think that's smaller but our eyes are not the best and efficient way. Optic illusions exists. The only way is to check sizes and if the difference is really what's set.

**Comment by elstoc** [comment]
> We can't set a default size/font in Gtk code.

Do you mean it's not possible or you don't want to?

> So hardcode a size, even if it's to make it relative after, is not the best thing to do

I'm not suggesting hard-coding a size. The current size is already "hard-coded" to the user's gtk settings. I'm just suggesting the user should have the ability to set that font size independently of other gtk apps. "ems" are not hard coded size.

**Comment by Nilvus** [comment]
> > And that's easier to do even if it's not so good and precise as a font and size selector.
> 
> I've gone ahead and started work on a font size selector (it's not hard) and will have a PR ready soon.

Oh, this comment was not updated when writing my last comment. So if you work on it, no need for me to lost time to test rems in CSS. Good to know.
If you could test and precise to me which is better to change (or comment to remove) on my actual CSS rework about that to avoid (in the future) conflict between CSS and your PR.

**Comment by elstoc** [comment]
Given that I've tested it against your old CSS I think you can leave everything in "ems" because what I'm doing is basically equivalent to globally changing the gtk font size. I'll push the PR and you can take a look but I don't think there will be any conflicts.

**Comment by Nilvus** [comment]
> > We can't set a default size/font in Gtk code.
> 
> Do you mean it's not possible or you don't want to?
> 
> > So hardcode a size, even if it's to make it relative after, is not the best thing to do
> 
> I'm not suggesting hard-coding a size. The current size is already "hard-coded" to the user's gtk settings. I'm just suggesting the user should have the ability to set that font size independently of other gtk apps. "ems" are not hard coded size.

Seems that on my side, there's some of you comments posted later (hard to avoid confusion that way).

I'm not against hard coded if a font selector/size is added on darktable. The only thing was to avoid add hardcoded without font/size selector because some old users and developers want to keep having a theme related to OS font. But a real font/size selector it's another thing and so don't care about that.

**Comment by elstoc** [comment]
#4974

**Comment by Nilvus** [comment]
Last commit finish the whole rework:

- Improve comments and so make CSS more readable and so simplify for future updates
- Merge some duplicate things: this allow to be sure UI remains consistent when changing a setting. For example header treeview were same on accels window and shortcuts/presets in preferences window but same header treeview on import/export and all filechooser ones were different. That's no more the case.
- Fix some minor glitches: reject icon in red state not visible in some hover states, improve buttons in about dialog window, checked folder in filechooser dialogs...
- Remove and put back to previous state special changes made for setting font from CSS due to new #4974 PR by @elstoc.

I let this PR in draft mode for few days to be sure I didn't break or forgot something. All tests/checks are welcomed as near all CSS has changed.

**Comment by Nilvus** [comment]
New file chooser dialog window is coming. Hope you will like it:



Commit following soon.

**Comment by elstoc** [comment]
@Nilvus FYI I've made a minor CSS change in #5003 because I've introduced a new widget.

**Comment by Nilvus** [comment]
> @Nilvus FYI I've made a minor CSS change in #5003 because I've introduced a new widget.

Thanks for pointing that.

**Comment by Nilvus** [comment]
I will need help with Gtk on a minor thing but disturbing one: the arrow used to changer order on filter in header toolbar become quite bigger (too much) after clicking on it. On darktable restart, it come back to default size. Default and checked states are set by same settings, same lines on CSS and Gtk Inspector Tool confirm that theses lines are correctly applied but those lines don't affect the checked state of this arrow. I find that this arrow is set on src/libs/tools/filter.c and I'm quite sure there's something hardcoded and override CSS settings on checked state.

So if someone could say me how what to change on Gtk code to allow the GUI apply CSS set on checked state for this arrow. This arrow use #control-button CSS tag.

See below the arrow in checked state:

**Comment by elstoc** [comment]
> the arrow used to changer order on filter in header toolbar become quite bigger (too much) after clicking on it

I think this might need a code change - I don't think CSS will do it - darktable is redrawing the icon when it's clicked on.

**Comment by elstoc** [comment]
Give the above PR ago - should fix the issue

**Comment by Nilvus** [comment]
Last commit should be the last one of this work.

I spent some time to test/review probably all darktable parts (except tethering view because of a lack of compatible camera) and fix minor old glitches on some differents parts.

This commit also brings a whole new refactored file chooser dialog window.

Last thing, I remove a very unuseful text on 2nd tab on camera import dialog windows. Hope I do it the good way.

@TurboGit: this is ready for review but as you can see nearly all the CSS has been rework. Even if I made a lot of reviews, I of course could have missed something. So better to take time to test.

**Comment by elstoc** [comment]
@Nilvus I will say that the look/feel of the file chooser dialog window doesn't much bother me either way but I just wanted to mention, as we've discussed before, that the file chooser dialog is built differently depending on a user's window manager / desktop environment (I'm not sure which) - darktable just requests a file chooser and then adds some widgets to the bottom of it. 

That means that this change, more than any other will likely look different for everybody. Given this, I wonder whether it might be better to restrict changes to the file chooser to just setting the color scheme and perhaps the font face. Any tweaks you do to layout (padding, margins etc.) might look different on other people's systems.

Just a suggestion - I'm ok if you want to commit unchanged because I don't spend all that long in the file chooser dialog and it looks ok if a little more gnome-ish.

**Comment by elstoc** [comment]
Apart from that it looks good.

**Comment by Nilvus** [comment]
@elstoc: there were already margins/padding and darktable hover effects before, so all you cite about other desktop was already available and even on my system, the old one was different than what I have by default outside darktable so if changes, they shouldn't be so different.

Yes, it's a little Gnome-ish, but only for the icons on the left. I like this idea and that start from preferences rework. At first, I have test with the left border like on preferences and as the left border was just on the left of the icon...

About older filechooser dialog window, there's not so much change since. The main content where files and folders are shown is the same, except header button (name, type, size...) that now have exact same view than on shortcuts/presets and accels ones. That's mainly the left column that has change with different selected and hover effect and some margins/padding reduced. No more.

Last but not least, we are on a free software and on the middle of the development of the future major release. So we have time to have feedback and issues. We will see.

**Comment by Nilvus** [comment]
@TurboGit: as they're CSS new lines in #5003, this PR need to be merged after #5003 PR and I will need to add a last one commit to move lines on their new place in my PR.

**Comment by elstoc** [comment]
Agreed it was only a very minor thing and as I say it does look ok on my system. I think, except for the changes in #5003 this is probably good to go. Better to get it tested by as many people as possible.

**Comment by Nilvus** [comment]
> Agreed it was only a very minor thing and as I say it does look ok on my system. I think, except for the changes in #5003 this is probably good to go. Better to get it tested by as many people as possible.

@elstoc: As we are on specific possible desktop related issues, you know that buttons to cancel/open on dialog window are on headerbar on my side. On export module (storage options section), when I click to the folder to open the file chooser dialog window, cancel button is on exact same size as the right button (as I see is on the file chooser dialog window where I see that) and it's quite awful. It's same as arrow, don't know how to change that (not CSS related).

**Comment by elstoc** [comment]
I don't get that issue here (xfce):

Screenshot_2020-05-13_08-50-27

**Comment by Nilvus** [comment]
> I don't get that issue here (xfce):
> 
> Screenshot_2020-05-13_08-50-27

I finally installed this morning XFCE (before reading your post ;-)!) and see that. So I suggest to simply forget that.

**Comment by Nilvus** [comment]
Last update improve new things:

- to respect totally CSS recommendations, all pt have been removed and replaced by px.
- I also fix minor remaining glitches
- squash/rename commits for clarity (thanks to @rawfiner help for git ops)
- improve last new toast message by @elstoc. See below my proposal:

dark theme:


darkest one:


grey:


Hope you will like it.

@TurboGit: as discussed on overlays PR from @Mark-64, no need to wait to merge my PR. So it's all done for me and if testing is ok, you could merge this.

**Comment by TurboGit** [comment]
Tested, all looks very good !

Let me say that dt looks very pro with this new CSS and all the rework of lt and culling mode. I like the new overlay block which is properly placed on the image. The previous version was having the overlay a bit random and part of it out of the image.

Again, all this looks clean and yes very pro ! Congrats to all involved into this rewrite, special thanks for @AlicVB and @Nilvus !

**Comment by elstoc** [comment]
> improve last new toast message

Agreed much better now. Not sure whether you really need different colours for each theme, since it mostly overlays the image but they all look good so I can't complain.

One thing I did notice while testing this was that the icons on the bottom-left of the darkroom are larger than those on the bottom-right. However this isn't a CSS issue so I'll raise another PR to address that.

**Comment by Nilvus** [comment]
> Tested, all looks very good !
> 
> Let me say that dt looks very pro with this new CSS and all the rework of lt and culling mode. I like the new overlay block which is properly placed on the image. The previous version was having the overlay a bit random and part of it out of the image.
> 
> Again, all this looks clean and yes very pro ! Congrats to all involved into this rewrite, special thanks for @AlicVB and @Nilvus !

So objectives accomplished! Containment we lived had good sides!

**Comment by Nilvus** [comment]
> Agreed much better now. Not sure whether you really need different colours for each theme, since it mostly overlays the image but they all look good so I can't complain.

That's only to adjust colors to header toolbar as it's just below.

> One thing I did notice while testing this was that the icons on the bottom-left of the darkroom are larger than those on the bottom-right. However this isn't a CSS issue so I'll raise another PR to address that.

Good catch. Thanks for your PR.

**Pull request merged**
