### PR TITLE
Undo group

### PR DESCRIPTION
**Pull request by TurboGit**

### CODE REVIEW

**Comment by TurboGit** [comment]
This one does not apply cleanly but anyway it should be worked after #1418 and #1419 are merged. So for the moment do not spend time reviewing this one.

**Comment by advancingu** [comment]
@TurboGit Both mentioned commits have been merged some time ago. Would you be able to look at this issue again? Changing curve values still causes non-atomic undos in 2.4.2 for me.

**Comment by TurboGit** [comment]
I'm not really sure what to do with that at this stage.

**Comment by advancingu** [comment]
@TurboGit What do you mean? The merge conflicts could be resolved and the patch merged (assuming it fixes the undo issue).

**Comment by TurboGit** [comment]
Closing, this has been rebased in #2114 .

**Pull request closed without merging**
