### PR TITLE
pref submenu: activate Enter key to save preferences

### PR DESCRIPTION
**Pull request by phweyland**
Applying import pref solution for modules: collect, recent used collections, image information, metadata editor and export.
Same routine used, set in lib.c.

### CODE REVIEW

**Comment by dterrahe** [comment]
Have you considered replacing this approach with `gtk_dialog_set_default_response`?

**Comment by phweyland** [comment]
> Have you considered replacing this approach with `gtk_dialog_set_default_response`?

No, but I'll do ! If cancel still works, that should do it. Thanks.

**Comment by phweyland** [comment]
Made a test. That works as long as one does not touch the settings. Otherwise this doesn't work, probably because the focus is on one of the settings and not any more on the dialog window...

**Comment by dterrahe** [comment]
Oh well. Every step gtk helps a little, you have to fight it the rest of the way...

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
