### PR TITLE
print: fix image orientation handling

### LINKED ISSUE #11780: Provide deb packages on OBS for Ubuntu 22.04
**Describe the solution you'd like**
Provide Packages for Ubuntu 22.04 as it's a LTS release and is already in Production
https://download.opensuse.org/repositories/graphics:/darktable/
https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable

**Alternatives**
For now, I'm using packages for 21.10, but this is not a good recommendation.

**Additional context**

https://discuss.pixls.us/t/darktable-obs-build-on-ubuntu-22-04/30528

### PR DESCRIPTION
**Pull request by dtorop**
This catches the case when print view is entered from darkroom mode with an image of unknown width/height. Prior to this commit, the layout would default to portrait mode.

Fixes #11780.

A better fix may be to also have _set_orientation() fall back to the width/height in image metadata if there is no mipmap available.

Note that this does not fix the print settings orientation combobox, which can also be inaccurate.

### CODE REVIEW

**Comment by dtorop** [comment]
I added a bunch more commits after the first to try to work out a fix to #11781 and generally make things more smooth.

The goal here is to have the print settings panel be the only one which figures out orientation of the current image. If the user navigates to a new image, the orientation combobox will be set to landscape or portrait based on that image's orientation. That information will be passed on to the print view, which will update the layout preview accordingly. The print view only cares about the orientation as set in the print settings.

If the image has a lot of iops enabled, and it takes a while to process these to determine its orientation, the print settings panel will repopulate its orientation combobox once that work is complete.

A down side is that print settings now must catch a couple more signals, and it processes these even when not in print view. The latter should be fixable.

Still a bunch of FIXMEs, and the numerous commits could be coalesced.

**Comment by houz** [comment]
> A down side is that print settings now must catch a couple more signals, and it processes these even when not in print view. The latter should be fixable.

You can probably connect in `enter()` and disconnect in `leave()`.

**Comment by dtorop** [comment]
@houz: Thank you, using `view_enter()` and `view_leave()` now, which makes things better.

**Comment by dtorop** [comment]
I rebased in order to squash some of the multitude of commits together. This version appears to work well, and simplifies the prior code.

The major change is that the print settings panel now does all the work of determining image orientation, and passes that information on to the print view. Previously the panel and center view both tried to do this, sometimes with differing results.

**Comment by TurboGit** [comment]
All good to me! Working as advertised :) Thanks for fixing that.

**Comment by dtorop** [comment]
@TurboGit: Thank you for checking it! It's been a long-standing thing I've wanted to work out within an extremely useful part of the program. Speaking as someone who makes a lot of landscape format prints...

**Pull request merged**
