### PR TITLE
exif: no need to extra sanitize IPTC date and time

### PR DESCRIPTION
**Pull request by kmilos**
But the time portion of the datetime string should not be empty.

Fixes https://github.com/darktable-org/darktable/issues/15494

### CODE REVIEW

**Comment by victoryforce** [comment]
@TurboGit Today I was deep in a boring, long but necessary piece of research. I plan to review this PR tomorrow (that is, Tuesday).

**Comment by gi-man** [comment]
This works better than what I was working on. :-)

**Comment by victoryforce** [comment]
@TurboGit LGTM

**Review by victoryforce — APPROVED** [review]

**Comment by TurboGit** [comment]
Thanks!

**Pull request merged**
