### PR TITLE
Travis : add Clang 8 and GCC 9 recipies

### PR DESCRIPTION
**Pull request by aurelienpierre**
Update compilers versions

### CODE REVIEW

**Comment by aurelienpierre** [comment]
It seems something more needs to be done on the virtual host doing the building. Maybe @LebedevRI could check ?

**Comment by LebedevRI** [comment]
As you may be able to notice from the file you are editing, those ci entries are based on docker image.
That docker image is based on debian testing, which is presently frozen in preparation for next stable
release. And the debian testing, presently, does not have gcc-9/clang-8, otherwise i would have updated them already a while ago.

**Comment by LebedevRI** [comment]
gcc 9 migrated to testing, ci updated; no clang 8 yet..

**Comment by TurboGit** [comment]
Thanks Roman! Will help detecting issues.

**Pull request closed without merging**
