### PR TITLE
[GUI] sRGB profile name improvements

### PR DESCRIPTION
**Pull request by victoryforce**
1. Adding "e.g. JPG" to the sRGB profile name makes no sense. What is so special about sRGB that we don't just name it, but include some kind of explanation? What is special about the JPEG format that it is mentioned here? JPEG can only be in sRGB? No. Then why do we specify that the profile is "sRGB as in JPEG"? It looks strange and there is absolutely no logic in it.

2. We can leave "web-safe" as part of the profile name in the export module (just to remind the user that this is the best choice for images that will be posted on the web), but in print mode the mention of web-safe is out of place.

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Comment by kmilos** [comment]
Well, the web-safe one is ICC v2, the other one isn't... How do we know which one the user wanted in print now? Or they only have the one option?

**Comment by victoryforce** [comment]
> Well, the web-safe one is ICC v2, the other one isn't (v4)... How do we know which one the user wanted in print now? Or they only have the one option?

I'm not sure I understood you. This PR removes "web-safe" from the name used in print mode. And only there. The same name used in the export module is left unchanged since it might make sense there.

**Comment by kmilos** [comment]
Sure, but it might create confusion as there is already a "sRGB" that is v4 elsewhere (now in colorin)?

**Comment by victoryforce** [comment]
Perhaps you can describe what this confusion might be, using some example? I still don't understand what you are talking about.

**Comment by kmilos** [comment]
There are 2 sRGB ICC profiles in dt - a v2 one and a v4 one (some SW still does not understand v4 for example). By removing the extra designations in brackets (I'm not saying they were good necessarly), you created ambiguity.

**Comment by victoryforce** [comment]
> Well, the web-safe one is ICC v2, the other one isn't (v4)... How do we know which one the user wanted in print now? Or they only have the one option?

Yes, in print the user only have the one option. The right one.

> There are 2 sRGB ICC profiles in dt - a v2 one and a v4 one

Ambiguity can be created only if different versions of the same profile (sRGB in this case) are present in the same combobox. Of course, there is no such thing in the darktable interface. Therefore, there is no ambiguity.

**Comment by parafin** [comment]
> > There are 2 sRGB ICC profiles in dt - a v2 one and a v4 one
> 
> Ambiguity can be created only if different versions of the same profile (sRGB in this case) are present in the same combobox. Of course, there is no such thing in the darktable interface. Therefore, there is no ambiguity.

That’s untrue. Ambiguity can be in form of “what this option exactly means?”. E.g. to be sure that correct one is used.

**Comment by parafin** [comment]
But “(e.g. JPG)” definitely doesn’t help with that.

**Pull request merged**
