### PR TITLE
improve consistency for mouse action mods in H screen

### PR DESCRIPTION
**Pull request by dterrahe**
The help screen (H) shows mouse actions (non-input NG ones) that have modifier keys using a standard gtk function which uses capitals for Shift/Ctrl/Alt. Everywhere else (also for input NG shortcuts in the same screen) those are shown lower case. This PR restores consistency.

### CODE REVIEW

**Comment by dterrahe** [comment]
Also change the few exceptions from "double-click" to "double click".

This change breaks translations.

**Comment by TurboGit** [comment]
Yes, indeed the doc (and the code) has always been using a dash for double-click, same for ctrl-click, shift-click... So I would stick with that. Any incentive to change that on your side?

**Comment by dterrahe** [comment]
The majority of the code actually has space instead of hyphen. Which is why i went with that for iNG as well (also for triple and press).

**Comment by elstoc** [comment]
The general convention in dtdocs is upper case first letter for Ctrl, Shift, Alt, Enter (i.e. named keyboard keys) lower case for "click", hyphen for "double-click", "triple-click" and plus for combinations, e.g. Ctrl+click. When the user is asked to press a letter key, this is given in upper case, e.g. Alt+A.

**Comment by dterrahe** [comment]
When it is decided that this convention is also going to be applied in the program itself, I assume will coincide with a full move away from the lower-case rule? I'd rather not own all those string changes, but would gladly take care of the required changes in inputng, so please make sure to involve me. Until then, I'd prefer not touch anything in order not to end up in no-man's land.

But since the help screen already is split, is there interest to at least create consistency there (shift/ctrl/alt and "double click") for now? Basically the first commit plus two strings in view.c?

I'm also happy to close this PR if preferred.

**Comment by TurboGit** [comment]
> I assume will coincide with a full move away from the lower-case rule?

Yes, probably but I fear that this rule will still hold for a long time.

**Comment by dterrahe** [comment]
So until then, still worth at least being consistent in lowercasing shift and ctrl in UI.

Also changing "double click" -> "double-click".

**Review by TurboGit — APPROVED** [review]
Merging with resolved conflicts, easy as the commit in crop.c has been removed.

**Pull request merged**
