### PR TITLE
lut3d- add 3dl file support

### PR DESCRIPTION
**Pull request by phweyland**
- fix the call to gmic routine to get runtime version at each image init.
- support now 3dl files along with cube ones.

### CODE REVIEW

**Comment by phweyland** [comment]
@TurboGit the discussion about 3dl lut to be applied on raw image remembers me that lut3d can be moved outside colorin-colorout.
But in that case the combobox to chose the colorspace should be masked or at least disabled.
Is there a simple way for a module at init time to know if it is or not outside colorin-colorout ? (I had a look at iop_order.c but I' haven't found...).
Thanks

**Comment by TurboGit** [comment]
@phweyland : As I'm working actively on the full re-implementation of the iop-order support we can work on that when it is merged. With the new implementation it will be possible and quite simple to check this specific case.

So let's this PR wait for #3908.

**Comment by chrik5** [comment]
Can you please add a version check for the build process also? 
I doesn't make sense to build dt with a GMIC version which is not supported?

**Comment by TurboGit** [comment]
> Can you please add a version check for the build process also?
> I doesn't make sense to build dt with a GMIC version which is not supported?

There seem to be no way to do that. Any advice ?

**Comment by parafin** [comment]
If you can check it at runtime, then it's possible at configure time also - just compile a test program doing a runtime check.

**Comment by phweyland** [comment]
> If you can check it at runtime, then it's possible at configure time also - just compile a test program doing a runtime check.

Trying to understand the idea. 
Before building dt, build a small program with libgmic linked making in some way its version available. Then, at dt build time, use the the result of this program. Correct ?

**Comment by chrik5** [comment]
> then it's possible at configure time also
Yes, that seems to be what I had in mind. A GMIC version check on configure time. Is this somewhere here to add: 
https://github.com/darktable-org/darktable/blob/master/src/CMakeLists.txt#L432

**Comment by phweyland** [comment]
> > then it's possible at configure time also
> 
> Yes, that seems to be what I had in mind. A GMIC version check on configure time. Is this somewhere here to add:
> https://github.com/darktable-org/darktable/blob/master/src/CMakeLists.txt#L432

Yes, should be. But libgmic doesn't return its version (at least I haven't succeeded in making it work).

**Comment by parafin** [comment]
The following cmake code works:
```
set(CMAKE_REQUIRED_INCLUDES ${GMIC_INCLUDE_DIRS})
check_cxx_source_compiles("
#include <gmic.h>
#if gmic_version < 281
#error OLD_VERSION
#endif
int main() { return 0; }
" GMIC_VERSION_OK)
if(NOT GMIC_VERSION_OK)
  message(FATAL_ERROR "Too old GMIC version")
endif()
```
I don't suggest to use it as-is, just it's just to demonstrate the idea.

**Comment by phweyland** [comment]
> I don't suggest to use it as-is, just it's just to demonstrate the idea.

Great, thank you. I'll make a try asap.

**Comment by phweyland** [comment]
Yes, that works ! I'll remove the code corresponding to runtime version detection and issue a PR for that. Thanks a lot @parafin.

-- Performing Test GMIC_VERSION_OK
-- Performing Test GMIC_VERSION_OK - Failed
-- Found GMIC but version < 270

If libgmic is turned able to return the version to cmake, we'll revert this workaround.
see https://discuss.pixls.us/t/gmic-lookup-symbol-err-on-opensuse-darktable-master-build/15827/24

**Comment by TurboGit** [comment]
@phweyland : Now that iop-order PR is merged you can use dt_ioppr_is_iop_before() in iop_order.c to check for specific iop ordering. Let me know if this fill your need.

**Comment by phweyland** [comment]
> ow that iop-order PR is merged you can use dt_ioppr_is_iop_before() in iop_order.c to check for specific iop ordering. Let me know if this fill your need.

I was off. I'll do it asap. Thanks

**Comment by phweyland** [comment]
@TurboGit 

I've given some try. To make it work properly one must be informed when a module is moved in the pixelpipe. I've not found such an event. Any suggestion ?

Also I cannot use dt_ioppr_is_iop_before() to check if the module is after colorin.
If can use the same routine when I have only one instance it doesn't work for multiple instance.
I get this message which is clear enough (after_colorout code is not correct):
`cannot get iop-order for colorout instance 1`

With the same code I get a segmentation fault when I restart dt but that may be normal.
[darktable_bt_USC1F0.txt](https://github.com/darktable-org/darktable/files/4177665/darktable_bt_USC1F0.txt)

The piece of code I've added is this one:
```
  const int imgid = darktable.develop->image_storage.id;
  GList *iop_order_list = dt_ioppr_get_iop_order_list(imgid, FALSE);
  const gboolean before_colorin = dt_ioppr_is_iop_before(iop_order_list, "colorin", self->op, self->multi_priority);
  const gboolean after_colorout = dt_ioppr_is_iop_before(iop_order_list, self->op, "colorout", self->multi_priority);
  if(before_colorin || after_colorout)
  {
    gtk_widget_hide(g->colorspace);
  }
  else
  {
    gtk_widget_show(g->colorspace);
  }
```

**Comment by phweyland** [comment]
Using dt_ioppr_get_iop_order() (instead of dt_ioppr_is_iop_before()) and comparing it between modules gives the right result. It seems to work too with multi instances of the module.

So remain to find a way to be triggered when the module is moved.

**Comment by TurboGit** [comment]
I think the signal DT_SIGNAL_DEVELOP_HISTORY_CHANGE is raised when module moves.

**Comment by phweyland** [comment]
> I think the signal DT_SIGNAL_DEVELOP_HISTORY_CHANGE is raised when module moves.

That works but this may trig more often than required. Should I add a signal, like DT_SIGNAL_MODULE_MOVED ?

Sometimes I get a huge iop_order value (2147483647 here below).
Here are my traces (when I create the new instance, first occurrence of instance 1):

```
imgid 56915 module lut3d mprio 0 mod 21 in 29 out 69
moved
moved
cannot get iop-order for lut3d instance 1
imgid 56915 module lut3d mprio 1 mod 2147483647 in 29 out 69
moved
cannot get iop-order for lut3d instance 1
imgid 56915 module lut3d mprio 1 mod 2147483647 in 29 out 69
imgid 56915 module lut3d mprio 0 mod 21 in 29 out 69
```

When I compress the history stack the iop_value is back ok.

Maybe linked to that, the stack compression doesn't work properly:

image

I should have only 2 lut 3D lines.

My current code is this one:

```
  const int imgid = darktable.develop->image_storage.id;
  GList *iop_order_list = dt_ioppr_get_iop_order_list(imgid, FALSE);
  const int order_lut3d = dt_ioppr_get_iop_order(iop_order_list, self->op, self->multi_priority);
  const int order_colorin = dt_ioppr_get_iop_order(iop_order_list, "colorin", -1);
  const int order_colorout = dt_ioppr_get_iop_order(iop_order_list, "colorout", -1);
  printf("imgid %d module %s mprio %d mod %d in %d out %d\n", imgid, self->op, self->multi_priority, order_lut3d, order_colorin, order_colorout);
  if(order_lut3d < order_colorin || order_lut3d > order_colorout)
  {
    gtk_widget_hide(g->colorspace);
  }
  else
  {
    gtk_widget_show(g->colorspace);
  }
```

and for the trigger:

```
void module_moved_callback(gpointer instance, dt_iop_module_t *self)
{
  printf("moved\n");
  dt_control_signal_block_by_func(darktable.signals, G_CALLBACK(module_moved_callback), self);
  gui_update(self);
  dt_control_signal_unblock_by_func(darktable.signals, G_CALLBACK(module_moved_callback), self);
}
```

Let me know if you need more information.

**Comment by TurboGit** [comment]
> Should I add a signal, like DT_SIGNAL_MODULE_MOVED ?

I suppose so. Will be handy and could be reused in ioporder lib.

**Comment by TurboGit** [comment]
> Also I cannot use dt_ioppr_is_iop_before() to check if the module is after colorin.

Maybe a fix to be put in then. It should be ok with multiple instances I suppose.

**Comment by phweyland** [comment]
Set proper sequence to use dt_ioppr_get_iop_order(). My error above was to use dt_ioppr_get_iop_order_list() which returns a static list (not updated by the moves).

Maybe dt_ioppr_is_iop_before() can be removed now.

Added a specific "module moved" signal.

Fixed the delete module instance sequence (widget was deleted before calling gui_cleanup()) in imageop.

Should be OK for review. Thanks.

**Comment by TurboGit** [comment]
@phweyland : can you point me to a 3dl file to test? I just cannot find one :(

**Comment by phweyland** [comment]
[C-8120-STD.3dl.txt](https://github.com/darktable-org/darktable/files/4189095/C-8120-STD.3dl.txt)
[C-9730-STD.3dl.txt](https://github.com/darktable-org/darktable/files/4189096/C-9730-STD.3dl.txt)
[Choweed - Standard.3dl.txt](https://github.com/darktable-org/darktable/files/4189097/Choweed.-.Standard.3dl.txt)
[Adoras - Standard.3dl.txt](https://github.com/darktable-org/darktable/files/4189098/Adoras.-.Standard.3dl.txt)

**Comment by phweyland** [comment]
here https://blog.sowerby.me/fuji-film-simulation-profiles/

**Comment by TurboGit** [comment]
Looks ok ! Merged. Thanks.

**Pull request merged**
