### PR TITLE
Fujifilm X-T2: Basic support added, fixes (#11132)

### PR DESCRIPTION
**Pull request by schenlap**
Raw samples used:
http://img.photographyblog.com/reviews/fujifilm_x_t2/photos/fujifilm_x_t2_13.raf
http://img.photographyblog.com/reviews/fujifilm_x_t2/photos/fujifilm_x_t2_06.raf

wb_presets could not be extracted from samples

### CODE REVIEW

**Comment by LebedevRI** [comment]
Are those from adobe dng converter?

Our general idea is:  ideally, once a change in cameras.xml and adobe_coeff are made, it is best to not change that camera.
Because that would result in dt producing slightly different output for the same history stack, and we generally try to avoid that.

The fact that the camera definition (matrix, black/white levels, crop) are not saved in history stack is a bug though, will be fixed one day.

**Comment by schenlap** [comment]
Yes, coeffs are from adobe dng converter.

**Comment by LebedevRI** [comment]
Can not download the samples, "403 Forbidden"

**Comment by schenlap** [comment]
Ok, it seems that you have to go to
http://www.photographyblog.com/previews/fujifilm_x_t2_photos/
to download the images. I also get 403 from the direct link.

**Comment by LebedevRI** [comment]
@schenlap thank you!
All seems good based on those samples, so i merged.

**Pull request merged**
