### PR TITLE
Finishing ES translations

### PR DESCRIPTION
**Pull request by criadoperez**
Finished all pending ES translations with only a few still marked for review, which can be changed/improved but other translators if they consider it necessary.

### CODE REVIEW

**Comment by EdgarLux** [comment]
Hello @criadoperez . I've been working on the translation and integrating the updates. In fact, this pull request would cause regressions and add some issues to the current translation.

**Comment by criadoperez** [comment]
@EdgarLux ok. This pull request contains all pending translations. But as long as it gets done in time I don't care who does it.

**Comment by TurboGit** [comment]
Thanks !

**Comment by TurboGit** [comment]
@EdgarLux : there is still 14 fuzzy translations:

```
$ intltool-update es
..................................................................................................................................................................................................................................................................................................................................................................................................... done.
3703 translated messages, 14 fuzzy translations.
```

**Comment by EdgarLux** [comment]
> @EdgarLux : there is still 14 fuzzy translations:
> 
That's right. Thank you @TurboGit.

**Pull request merged**
