### PR TITLE
InputNG: add keyboard shortcut icon

### PR DESCRIPTION
**Pull request by johnny-bit**
ref #9483

this proposes an icon that looks like in the screenshot below

obraz

I think the cairo code (and the icon) needs some tweaks but IMO it's rather good for conveying what it does :)

// EDIT:

new, arrowless look:

obraz

### CODE REVIEW

**Comment by TurboGit** [comment]
Another icon !!! Yes ! Are we going to have an icon contest :)

I find this one a bit less balanced, too much on the right.

**Comment by johnny-bit** [comment]
I'll try to do it as a simple keyboard per @Nilvus' comment in another pr :)

**Comment by johnny-bit** [comment]
Pushed new look, this is how it looks on my low-res display:

obraz

**Review by Nilvus — APPROVED** [review]

**Comment by Nilvus** [comment]
Much better thanks. I'm just wondering if this would be better by changing this icon position too, like that (just an idea):

**Comment by johnny-bit** [comment]
I'm not changing button order in this PR ;)

**Comment by dterrahe** [comment]
Changing the button positions, especially the outside ones, is really going to mess with people's muscle memory; you'll have a lot of unhappy customers. You could possibly swap the question mark and shortcuts, and it might look more balanced, but having both configuration buttons together makes sense and also could trigger people to try out that new button while changing preferences.

**Comment by johnny-bit** [comment]
Thanks @Mark-64 ! That also makes it stand-out more in low-dpi screen :)

**Comment by TurboGit** [comment]
Last version looks good to me.

**Comment by johnny-bit** [comment]
The CI seems to have some timeout problem.

Otherwise I think this is ready to land. @dterrahe - is this OK?

**Comment by dterrahe** [comment]
> Otherwise I think this is ready to land. @dterrahe - is this OK?

I'm happy with this; looks good to me, in the sense that it gives an indication of meaning. But I shouldn't be the arbitrator on esthetics...

**Review by dterrahe — APPROVED** [review]

**Review by TurboGit — APPROVED** [review]
Thanks !

**Pull request merged**
