### PR TITLE
Bump GTK required version to 3.22

### PR DESCRIPTION
**Pull request by aurelienpierre**
The 3.22 version is the first one allowing a full control of margins and spacing from a CSS stylesheet, and is mandatory to benefit from the last UI changes.

Will solve #2388.

### CODE REVIEW

**Comment by TurboGit** [comment]
Some errors on the automatic checks:

```
/build/darktable/src/imageio/storage/facebook.c:602:7: error: 'gtk_show_uri' is deprecated [-Werror,-Wdeprecated-declarations]
  if(!gtk_show_uri(gdk_screen_get_default(), url, gtk_get_current_event_time(), &error))
      ^
/usr/include/gtk-3.0/gtk/gtkshow.h:32:1: note: 'gtk_show_uri' has been explicitly marked deprecated here
GDK_DEPRECATED_IN_3_22_FOR(gtk_show_uri_on_window)
^
/usr/include/gtk-3.0/gdk/gdkversionmacros.h:413:47: note: expanded from macro 'GDK_DEPRECATED_IN_3_22_FOR'
# define GDK_DEPRECATED_IN_3_22_FOR(f)        GDK_DEPRECATED_FOR(f)
                                              ^
/usr/include/gtk-3.0/gdk/gdkversionmacros.h:49:31: note: expanded from macro 'GDK_DEPRECATED_FOR'
#define GDK_DEPRECATED_FOR(f) G_DEPRECATED_FOR(f) _GDK_EXTERN
                              ^
/usr/include/glib-2.0/glib/gmacros.h:444:29: note: expanded from macro 'G_DEPRECATED_FOR'
#define G_DEPRECATED_FOR(f) G_DEPRECATED
                            ^
/usr/include/glib-2.0/glib/gmacros.h:432:37: note: expanded from macro 'G_DEPRECATED'
#define G_DEPRECATED __attribute__((__deprecated__))
                                    ^
1 error generated.
```

**Comment by aurelienpierre** [comment]
Facebook exporter doesn't work anymore, does it ?

**Comment by TurboGit** [comment]
Sure, but we have this also this issue reported in googlephoto, flickr and global_toolbox. It seems that the issue is gtk_show_uri() being deprecated. I'll fix.

**Comment by TurboGit** [comment]
Can you rebase on master and force-push here to see if my fixes on master works with that? Thanks.

**Comment by aurelienpierre** [comment]
Done @TurboGit

**Comment by TurboGit** [comment]
Thanks!

**Comment by TurboGit** [comment]
Ok, all green now. Merging. Thanks.

**Comment by rawfiner** [comment]
Thanks :)

**Pull request merged**
