### PR TITLE
po/fix masks manager menu

### PR DESCRIPTION
**Pull request by TurboGit**
As discussed in #10548, two bug fixes for the 3.8.

### CODE REVIEW

**Comment by elstoc** [comment]
So just to clarify (based on my testing), the changes here are as follows:

- It is no longer possible to duplicate or delete an entire group. Previously this was possible, but the menu option incorrectly stated "duplicate this shape" and "delete this shape". This has been done instead of just changing the names to "duplicate this group" and "delete this group", due to string freeze? Or is this a bug with this PR?
- The option to "add existing shape" to a group now only appears if there are shapes that don't form part of the group
- The names of any "non-group-member" shapes are now no longer displayed directly in the "group" menu but are now moved to the "add existing shape" sub-menu

If those changes were your intention, then this seems to work as expected.

**Comment by TurboGit** [comment]
> * It is no longer possible to duplicate or delete an entire group. Previously this was possible, but the menu option incorrectly stated "duplicate this shape" and "delete this shape". This has been done instead of just changing the names to "duplicate this group" and "delete this group", due to string freeze? Or is this a bug with this PR?

Hard to see a use case for duplicating a group (first it is not possible, we can only duplicate all the shape in the group). Deleting a group could be useful. I can restore that.

> The option to "add existing shape" to a group now only appears if there are shapes that don't form part of the group

Exactly. That seems correct as inverse semantic would be... a mess!

> The names of any "non-group-member" shapes are now no longer displayed directly in the "group" menu but are now moved to the "add existing shape" sub-menu

Yes.

So, the only point is adding back the delete group, because of string freeze we can just name it "**delete**" for now as this string is already present in other places.

**Comment by TurboGit** [comment]
I have added the delete on a group (a big comment in the code to fix the label after 3.8 is out).

**Comment by TurboGit** [comment]
Something else to fix, one assigning a mask to a group from the manager the count of mask in the module is not updated.

**Comment by TurboGit** [comment]
Two last issues should be fixed now.

**Review by elstoc — APPROVED** [review]
All good now

**Comment by TurboGit** [comment]
Thanks! That's merged now.

**Pull request merged**
