### PR TITLE
Move buttons border to css

### PR DESCRIPTION
**Pull request by Mark-64**
In the logic of removing hardcoded gui choices and delegate those to css, with this PR we move to css the control of icon buttons border.
The modification in the code is easy, however there is the problem that in lib and iop modules there are currently both flat (i.e. with no border) and normal (i.e. with border) buttons and they can't be distinguished in css, unless setting extra widget names. So I defined the name "non-flat" for those buttons.
I adjusted css to keep the current aspect and doing so I also fixed remaining glitches from my previous PR.

@Nilvus plase have a look. I leave the choice to you whether to merge this first or rather wait for your modifications (in that case I will rebase, no pb)

### CODE REVIEW

**Comment by Nilvus** [comment]
I will have a look soon. @TurboGit: why setting this PR to 3.4? It's about the UI and all things we are polish by now? I think about proposed a CSS PR on top of master, this PR and #5179 ones. So, that would mean some things for 3.2 and other for 3.4. I think this could be merged for mid-june, so my CSS works on june as it will only fix remaining glitches on top of that.

**Comment by TurboGit** [comment]
@Nilvus : because it is still marked as draft, we can always revisit this if it comes out of draft soon enough.

**Comment by Mark-64** [comment]
Well, I put it as draft because I didn't want to conflict with @Nilvus work on css, but if he wants to build on top of this PR instead, it can be merged immediately

**Comment by TurboGit** [comment]
After merging your other PR this one has conflicts now.

**Comment by Mark-64** [comment]
I messed up a bit to resolve conflicts, really sorry, I can't make "interactive rebase" work in my Eclipse IDE.
It should be OK now.

**Comment by Nilvus** [comment]
@Mark-64: it's all good for me. I prefer seeing that merged as they are other PR to work on for me. @TurboGit: if it's ok for you, it's ok for me to be merged.

**Comment by Mark-64** [comment]
Very good. I am working on other fixes, but they do not involve CSS this time :-)

**Comment by TurboGit** [comment]
Works for me, thanks !

**Pull request merged**
