### PR TITLE
export: set tab order

### LINKED ISSUE #8661: TAB key no longer works properly in Export module
Ubuntu 18.04  recent dt master 3.5.0+1616~ge9302dbf7-dirty

Suppose you are about to export and are altering the two pixel size values.  It used to be that you could type the first then press Tab to go into the second, as is universally normal.  But now Tab takes you nowhere as far as I can see.

Has there been some recent-ish "general" change to "special" keys?  I only ask because in addition to the above, I've had a couple of weird seemingly not reproducible events where holding down the Backspace key to delete the text in the Watermark module has caused darktable to jump back to lighttable.

### PR DESCRIPTION
**Pull request by elstoc**
allow user to tab through size fields in export module

Resolves #8661

### CODE REVIEW

**Review by TurboGit — CHANGES_REQUESTED** [review]
A second TAB after the height field is selected does switch the panels visibility. Would be nice to avoid that.

**Comment by elstoc** [comment]
This looks like an existing issue in master and I'm not sure it's possible except to swallow the tab key and keep the user in the field. TBH this will be a problem in lots of places. For example, the last field in the metadata editor, the "second" component of the date/time field in geotagging, the search field in the collect module, the search field in the darkroom... you get my point.

**Comment by TurboGit** [comment]
You're right ! If something is to be done it should be in another PR anyway. Thanks.

**Review by TurboGit — APPROVED** [review]

**Comment by dterrahe** [comment]
I am a little bit worried that special case approaches for individual widgets in many places make it more complicated to come up with generic solutions in #8078 that will work everywhere without first having to refactor/clean up our non-standard approaches. A large portion of the effort is spent investigating breakage and trying to understand what each workaround is trying to achieve. And that is if my, by definition limited, testing shows up issues that are specific to only a few locations.

**Pull request merged**
