### PR TITLE
let shortcut directly select a specific value in a combobox

### LINKED ISSUE #9121: No way to create shortcuts for menuentries in view menu in lighttable
**Is your feature request related to a problem? Please describe.**
in a default workflow using darktable I take a first look at new photos and mark really bad ones as “rejected” (r keyboard shortcut). Next in lighttable I select view->rejected and delete the shown ones. Then again I select view->all to view the remaining photos.
What I am looking for is a way in lighttable to select “view rejected” photos by a keyboard shortcut as well as "view all" photos. 

**Describe the solution you'd like**
Add a way to create  keyboard shortcuts for the view menu in lighttable. 
In darktable there are already many shortcuts to speed up work, but currently its not possible to add shortcuts for the view menu which as described would be helpful for a standard workflow.

Thanks
Rainer

### LINKED ISSUE #9471: FR: Consolidate guide lines and add shortcuts
As part of the recent guide generalisation in #8891 we no longer have the ability to change the type of guide lines that are overlaid on the image with a keyboard shortcut (you used to be able to allocate them to a dynamic shortcut in the C&R module).

In order to make the shortcut easier to use, it might also be worth consolidating the golden mean "extras" combobox into the guide lines combobox, perhaps with the following entries:

golden sections
golden spiral sections
golden spiral
golden mean (all guides)

Obviously we'll still need the extra grid comboboxes and the flip guides combobox but one less would be nice.

The ability to toggle guides in the separate distort modules via a shortcut would also be useful.

### LINKED ISSUE #9915: guides lines desynchronized
**Describe the bug/issue**

The guides buttons is enabled but the lines are not drawn, clicking on the button will display the line but deactivate the button!

**To Reproduce**
1. Go to 'darkroom'
2. Click on he 'guide' toggle button bottom-right
3. Quite darktable
4. Restart it and go to 'darkroom'
5. See guide button is activated, no guide lines displayed
6. Click the guide button, it is now deactivated but the lines are displayed

**Expected behavior**

Button status should properly reflect the guide status.

**Platform**

* darktable version : master
* OS                : Linux - GNOME
* Linux - Distro    : Debian/sid

### PR DESCRIPTION
**Pull request by dterrahe**
Works only for constant lists (i.e. doesn't work for filenames, variable color profiles or lua guides).

Needs some CSS work as separators in gtk dropdowns look strange.

image

Also converts the filter dropdowns to bauhaus with these types of shortcuts.
This _really_ closes #9121; @rainer042 would you please check if this works for you?

And adds shortcuts for guides widgets (which fixes #9471)

Also includes corrections that hopefully fixes #9915

### CODE REVIEW

**Comment by dterrahe** [comment]
> Needs some CSS work as separators in gtk dropdowns look strange.

 @Nilvus would you mind having a look? I'll also need to add names to the filter/sort widgets so they can be scaled correctly (i.e. font size dependent) in CSS.

**Comment by dterrahe** [comment]
Made filter combos scale with fonts via CSS

**Comment by Nilvus** [comment]
> > Needs some CSS work as separators in gtk dropdowns look strange.
> 
> @Nilvus would you mind having a look? I'll also need to add names to the filter/sort widgets so they can be scaled correctly (i.e. font size dependent) in CSS.

With pleasure. I could probably check that on Wednesday or, if not, only next week.

**Comment by dterrahe** [comment]
> > > Needs some CSS work as separators in gtk dropdowns look strange.

> > @Nilvus would you mind having a look? I'll also need to add names to the filter/sort widgets so they can be scaled correctly (i.e. font size dependent) in CSS.

> With pleasure. I could probably check that on Wednesday or, if not, only next week.

Thanks!

Only the first point still remains, as I already implemented the second one. The first issue is strictly speaking probably not specific to this PR; I suspect that _all_ standard gtk comboboxes with separator lines look a bit funky. It's just that I'm not aware of anywhere else where we use them ;-)

**Comment by dterrahe** [comment]
Rebased again

**Comment by dterrahe** [comment]
Rebased again

**Comment by dterrahe** [comment]
@Nilvus The thick separator line is caused by the wide `combobox *` selection in https://github.com/darktable-org/darktable/blob/cf99bbb0eec464b885acd6b0cb1d1a6ce6a2f7ec/data/themes/darktable.css#L307-L312

Possibly this could be tightened, but since I don't know which situations it is _meant_ to address I have not touched it for now. Instead I've added a specific 1px min-height override for combobox separators.

**Comment by Nilvus** [comment]
> @Nilvus The thick separator line is caused by the wide `combobox *` selection in
> Possibly this could be tightened, but since I don't know which situations it is _meant_ to address I have not touched it for now. Instead I've added a specific 1px min-height override for combobox separators.

I see that last week and this could be improved. I should have time this week to work on that and improve it. We should avoid px to emphasize all things (to adjust depending on size font and lodpi or hidpi screens) but let it that way for you PR. I will soon post some CSS tweaks proposal to follow this PR and another PR from AlicVB and having that 1px min-height for your PR is a good start to work on for me and not have quick issue when this will be merged if I'm not ready.

**Review by Nilvus — APPROVED** [review]

**Comment by Nilvus** [comment]
@TurboGit: all is good for me to be merged here.

**Review by TurboGit — APPROVED** [review]
Thanks !

**Comment by elstoc** [comment]
@dterrahe it's not clear whether this allows for _cycling_ the guide lines with key+scroll as mentioned in #9471. Does it?

**Comment by dterrahe** [comment]
yes

**Comment by elstoc** [comment]
Thanks

**Pull request merged**
