### PR TITLE
Lighttable

### LINKED ISSUE #3020: New PR #3007 info text color in thumbnail same than darktable-icon's frames = illegible
**Describe the bug**
If I am not mistaken, with PR #3007 the text color of the thumbnail changed and hence in the theme darktable-icons is not legible anymore, except the one hover.

@aurelienpierre I try to be anoying :smile: 

Screenshot_20190926_184531

### PR DESCRIPTION
**Pull request by aurelienpierre**
These are UI glitches and fixes based on @AlicVB #3023.

It also adds a light theme and fixes #3020.

### CODE REVIEW

**Comment by TurboGit** [comment]
We are missing darktable-icons-dark.css ?

Probably a rename but you forgiot to add the new version.

**Comment by aurelienpierre** [comment]
@TurboGit oups, forgot to add it to git index

**Comment by aurelienpierre** [comment]
Done. I have also fixed a debugging test forgotten by @AlicVB on sound icon

**Comment by TurboGit** [comment]
Great! Thanks, I'll try to have a look tomorrow now.

**Comment by Nilvus** [comment]
@aurelienpierre : I understand that lighttable needs some improvements (thumbnails part) but I really don't understand why you break the grey theme. Theme who was approved by community (and you). The new grey theme is not a grey theme anymore but a sort of light black theme. Could please revert back the grey theme with just the thumbnails improvements needed. In state, I'm against changing this theme.

**Comment by AlicVB** [comment]
@aurelienpierre : great ! so if I understand well, everything I've done is now here. I'm not sure if I can close my other PR without messing things here, so let's keep it open until this one is merged.
btw, I don't understand why there was still the sound icon debug problem after my last forced push from yesterday... it was ok locally...
Now let's try this !

**Comment by aurelienpierre** [comment]
>  I understand that lighttable needs some improvements (thumbnails part) but I really don't understand why you break the grey theme. Theme who was approved by community (and you). The new grey theme is not a grey theme anymore but a sort of light black theme. Could please revert back the grey theme with just the thumbnails improvements needed. In state, I'm against changing this theme. The new version doesn't reflect anymore my work and it's not anymore a middle grey theme.

I haven't changed the background colour of the grey theme (`@grey_30`), I was actually surprised that it was so dark when trying it. All the other changes are to make all the colours of the grey theme +15% brighter, and then the light theme is again +15% darker than the grey one, and ensure a 40% distance in shades between foreground and background.

> so if I understand well, everything I've done is now here. I'm not sure if I can close my other PR without messing things here, so let's keep it open until this one is merged.
btw, I don't understand why there was still the sound icon debug problem after my last forced push from yesterday... it was ok locally...

yeah, I have merged you commits at the beginning of the branch, then added my patches.

**Comment by Nilvus** [comment]
> I haven't changed the background colour of the grey theme (`@grey_30`), I was actually surprised that it was so dark when trying it. All the other changes are to make all the colours of the grey theme +15% brighter, and then the light theme is again +15% darker than the grey one, and ensure a 40% distance in shades between foreground and background.
> 
> > so if I understand well, everything I've done is now here. I'm not sure if I can close my other PR without messing things here, so let's keep it open until this one is merged.
> > btw, I don't understand why there was still the sound icon debug problem after my last forced push from yesterday... it was ok locally...
> 
> yeah, I have merged you commits at the beginning of the branch, then added my patches.

That's not what I see on your branch. I've compiled this branch and the grey theme is totally different that my version (not just a little brighter). And the light theme doesn't work (error message, css doesn't exist). About my grey theme, the problem is that you remove all @define-color on the beginning of the darktable-elegant-grey.css. That's why the CSS is totally broken.

**Comment by AlicVB** [comment]
yes, defined colors are missing from grey theme. Seems that css `@import` doesn't import defined colors :(
and you seem to have forgotten to add light theme css file to git index...

**Comment by AlicVB** [comment]
Some small pb for a first try : 
- in grey theme with re-added color definitions, in 'more module', active modules have the same background as other => you can't distinguish them in the list
- in culling and full preview, there's a black frame around first image (also present in filmstrip). Note that I can take care of this if you want

**Comment by aurelienpierre** [comment]
The define colour rules are supposed to get imported with `@import url("darktable.css");`, is it not the case on your side ?

**Comment by aurelienpierre** [comment]
Sorry, I forgot the file indeed. 

Here is what I get with commited settings:
Screenshot_20190928_183225
Screenshot_20190928_183207
Screenshot_20190928_183144

**Comment by aurelienpierre** [comment]
> in grey theme with re-added color definitions, in 'more module', active modules have the same background as other => you can't distinguish them in the list

I don't understand why base theme behaves as expected, and other treeviews in tagging module or collections behave as well…

> in culling and full preview, there's a black frame around first image (also present in filmstrip). Note that I can take care of this if you want

Yes. I'm not sure what behaviour is expected here. I think it's a good idea to highlight the active picture because tagging and metadata modules will be attached to it, and it would be weird to not know which pic is selected.

**Comment by Nilvus** [comment]
> > in grey theme with re-added color definitions, in 'more module', active modules have the same background as other => you can't distinguish them in the list
> 
> I don't understand why base theme behaves as expected, and other treeviews in tagging module or collections behave as well…
It's a lot better with last commits but it still remains two issues for me :+1: 
- light theme is nearer to my grey theme than your new one, so if we merge that, please put my name in light name instead of grey theme (to reflect my original work). I really don't like the new grey theme (it's a personal view).
- second and important issue : I don't have the gradient when hovering thumbnails as yours and the text image hovering the thumbnails remains totally unreadable with your work.

See what I see on my side :

Your grey theme :

apgreytheme

My grey theme :

mygreytheme

Your light theme :

aplighttheme

**Comment by aurelienpierre** [comment]
> light theme is nearer to my grey theme than your new one, so if we merge that, please put my name in light name instead of grey theme (to reflect my original work). I really don't like the new grey theme (it's a personal view).

I don't get what happens here. I have kept exactly the same background colour (grey_30) in the grey theme. Why is your screenshot so bright ? It looks like grey_50…

> second and important issue : I don't have the gradient when hovering thumbnails as yours and the text image hovering the thumbnails remains totally unreadable with your work.

You are using the extended thumbnail view, right ?

**Comment by Nilvus** [comment]
> > light theme is nearer to my grey theme than your new one, so if we merge that, please put my name in light name instead of grey theme (to reflect my original work). I really don't like the new grey theme (it's a personal view).
> 
> I don't get what happens here. I have kept exactly the same background colour (grey_30) in the grey theme. Why is your screenshot so bright ? It looks like grey_50…

I don't know. That's what I have. I just don't have a 4k display but it's calibrated (and same calibration (updated of course) than previous screenshots we have shared in the past about the grey theme.

> > second and important issue : I don't have the gradient when hovering thumbnails as yours and the text image hovering the thumbnails remains totally unreadable with your work.
> 
> You are using the extended thumbnail view, right ?

I'm not sure what you mean by extended thumbnail view but if you talk about image overlays activated (star icon), yes, that's what is unreadable in your themes.

**Comment by aurelienpierre** [comment]
> I don't know. That's what I have. I just don't have a 4k display but it's calibrated (and same calibration (updated of course) than previous screenshots we have shared in the past about the grey theme.

Could you try to drop your custom colour profile and test again ? It looks like a gamma issue. The look and the coded shade don't match, there is something odd here. I didn't got the same results as you using your grey theme before the changes I have made here. "My" grey theme and yours have exactly the same background colour in the code.

**Comment by Nilvus** [comment]
> Could you try to drop your custom colour profile and test again ? It looks like a gamma issue. The look and the coded shade don't match, there is something odd here. I didn't got the same results as you using your grey theme before the changes I have made here. "My" grey theme and yours have exactly the same background colour in the code.

I will test that. These last days, I was thinking about maybe buy a new screen (I have a good one but quite old). This test will maybe help me to decide buy a new or not. I come back in few hours after a new complete calibration.

**Comment by aurelienpierre** [comment]
> I will test that. These last days, I was thinking about maybe buy a new screen (I have a good one but quite old). This test will maybe help me to decide buy a new or not. I come back in few hours after a new complete calibration.

Don't profile, just use the generic sRGB profile to debug. If your calibration soft is ill-set, it will show by comparing a generic profile. Also, are you sure you are using the grey theme from master and not the local one ? I had saved a local grey theme you maybe sent me (don't remember where I got it), and the background value was grey_50, not grey_30.

**Comment by Nilvus** [comment]
> > I will test that. These last days, I was thinking about maybe buy a new screen (I have a good one but quite old). This test will maybe help me to decide buy a new or not. I come back in few hours after a new complete calibration.
> 
> Don't profile, just use the generic sRGB profile to debug. If your calibration soft is ill-set, it will show by comparing a generic profile. Also, are you sure you are using the grey theme from master and not the local one ? I had saved a local grey theme you maybe sent me (don't remember where I got it), and the background value was grey_50, not grey_30.

I'm totally sure to use themes from your lighttable branch. But it seems that I have a problem on ICC profile from the Gnome Control Center. For the first, when I change profile, nothing change on colors, in my laptop screen and my main external display. First time I have that and I recently update to Gnome 3.34... Not good. I will search another way to change that...

**Comment by aurelienpierre** [comment]
> I'm totally sure to use themes from your lighttable branch.

No, I meant your original grey theme you are comparing with above (prior to my changes), is it from current darktable master (not this branch) or from your `.config` directory ? Because we have 2 options here : either the grey theme of yours in use on your computer does not define grey_30 as background colour but grey_50 or similar, and this has been changed somehow on master, or you have a serious ICC profile gamma issue possibly mixed with GTK inconsistencies.

**Comment by Nilvus** [comment]
> > I'm totally sure to use themes from your lighttable branch.
> 
> No, I meant your original grey theme you are comparing with above (prior to my changes), is it from current darktable master (not this branch) or from your `.config` directory ? Because we have 2 options here : either the grey theme of yours in use on your computer does not define grey_30 as background colour but grey_50 or similar, and this has been changed somehow on master, or you have a serious ICC profile gamma issue possibly mixed with GTK inconsistencies.

I made some more tests. On my laptop screen (retina display ; macbook pro), the themes are a little darker. I've seen that my new workstation dock (I used it since tuesday, beginning of work at home one day a week) make the problem of profile doesn't changed. Anyway, the cnanges between different profiles are small and my external display is a little lighter (he have 10 years old !).

I've checked with Gtk debug which color is applied on main window background :

- Your grey theme : rgb(71,71,71)
- Your light theme : rgb(106,106,106)
- My grey theme (from actual master, not your branch nor .config directory) : rgb(106,106,106)

That's totally independant from gamma issues or screen ones and confirm that the light theme is my grey theme with some tweaks you made. I'm ok with that if you just put my name on light theme and remove it from the grey theme on state.

**Comment by aurelienpierre** [comment]
>  Your grey theme : rgb(71,71,71)
    Your light theme : rgb(106,106,106)
    My grey theme (from actual master, not your branch nor .config directory) : rgb(106,106,106)

Ok mystery solved… I understand now… In your theme, you redefined the values of the grey shades, so grey_30 doesn't have the same values in the dark and grey themes (and therefore doesn't mean grey 30 % in the grey theme). You should have just changed the colours names but leave the shades definitions as-is, since they are a continuous grey gradient in Lab translated into RGB. The `grey_30` tag in your original grey themes is actually 50 % grey.

**Comment by Nilvus** [comment]
> > Your grey theme : rgb(71,71,71)
> > Your light theme : rgb(106,106,106)
> > My grey theme (from actual master, not your branch nor .config directory) : rgb(106,106,106)
> 
> Ok mystery solved… I understand now… In your theme, you redefined the values of the grey shades, so grey_30 doesn't have the same values in the dark and grey themes (and therefore doesn't mean grey 30 % in the grey theme). You should have just changed the colours names but leave the shades definitions as-is, since they are a continuous grey gradient in Lab translated into RGB. The `grey_30` tag in your original grey themes is actually 50 % grey.
> 
> So, indeed, there is no need for a light theme, the grey one was enough. Maybe a less dark one half-way between grey and dark.


> > Your grey theme : rgb(71,71,71)
> > Your light theme : rgb(106,106,106)
> > My grey theme (from actual master, not your branch nor .config directory) : rgb(106,106,106)
> 
> Ok mystery solved… I understand now… In your theme, you redefined the values of the grey shades, so grey_30 doesn't have the same values in the dark and grey themes (and therefore doesn't mean grey 30 % in the grey theme). You should have just changed the colours names but leave the shades definitions as-is, since they are a continuous grey gradient in Lab translated into RGB. The `grey_30` tag in your original grey themes is actually 50 % grey.
> 
> So, indeed, there is no need for a light theme, the grey one was enough. Maybe a less dark one half-way between grey and dark.

 I'm not totally agree here. Of course, I didn't respect the grey number about %. I've just worked to have a nearer 50% grey theme and the light theme remains near my grey theme (who was approved by the community and you). I didn't change since that, I just don't respect what you mean on start about the number in grey_xx lines. I just respect the order. Your grey theme is too dark in my point of view. I care more of what I see that how it is written but if you want to adapt my work with same rendering and better writing, it is ok of course. So I'm not on that grey theme with my name and as my grey theme was approved, I would like to see it keeping.

**Comment by aurelienpierre** [comment]
> So I'm not on that grey theme with my name and as my grey theme was approved, I would like to see it keeping.

Yeah, of course, credit will be given where it's due, no worries.

**Comment by AlicVB** [comment]
ok, got it too... So colors are well imported via the @import function, but were redefined in the 'old' grey theme.
@aurelienpierre @Nilvus : if I can help you , just ask (but I prefer to let you fine tune all the colors) For my part, I'll try to think about the culling black border and come with a solution after this PR.

**Comment by TurboGit** [comment]
With this PR, the extended thumb overlay is not visible anymore.

**Comment by aurelienpierre** [comment]
>  I didn't change since that, I just don't respect what you mean on start about the number in grey_xx lines. I just respect the order. Your grey theme is too dark in my point of view. I care more of what I see that how it is written but if you want to adapt my work with same rendering and better writing, it is ok of course. 

All this is a big misunderstanding. Sorry about that. I didn't see the point of redefining the @grey_xx colours in the grey theme, since I assumed you used the same colours as defined in the dark theme (but I didn't checked). Once removed, the grey theme looked too dark to me, but I thought that's what you wanted (I barely reviewed it at the time), so I started another "real grey" theme to keep your work, and improved on top. As you know, I'm rushing 8 to 10 h/day on darktable since the beginning of summer to finish before feature-freeze, so I tend to be quite exhausted at this time and miss some obvious stuff.

Anyway, how it's written is how easy it will be to maintain in the future, so I think it's better to redefine a minimal amount of things in style sheets.

Plan for today is to fix the extended thumbnail view, restore the grey theme, add an in-between theme half-way between dark and grey, and let @AlicVB do whatever the hell he wants for selected thumbnail frame because I still have some filmic OpenCL code to piss for this evening.

**Comment by TurboGit** [comment]
@aurelienpierre  : great! looking forward to the last piece for 3.0!

**Comment by aurelienpierre** [comment]
Everything should be fixed by now: grey theme restored with proper credits, extended thumbnail exif, spacings, and new dark theme added.

**Comment by TurboGit** [comment]
Thanks! That's a very nice progress. I find the text on the culling view a bit too on the left. Placement would have to be adjusted but this can come later. I'll merge.

**Comment by TurboGit** [comment]
BTW, I like the new in-between theme color.

**Comment by Nilvus** [comment]
> All this is a big misunderstanding. Sorry about that. I didn't see the point of redefining the @grey_xx colours in the grey theme, since I assumed you used the same colours as defined in the dark theme (but I didn't checked). Once removed, the grey theme looked too dark to me, but I thought that's what you wanted (I barely reviewed it at the time), so I started another "real grey" theme to keep your work, and improved on top. As you know, I'm rushing 8 to 10 h/day on darktable since the beginning of summer to finish before feature-freeze, so I tend to be quite exhausted at this time and miss some obvious stuff.
> 
> Anyway, how it's written is how easy it will be to maintain in the future, so I think it's better to redefine a minimal amount of things in style sheets.
> 
> Plan for today is to fix the extended thumbnail view, restore the grey theme, add an in-between theme half-way between dark and grey, and let @AlicVB do whatever the hell he wants for selected thumbnail frame because I still have some filmic OpenCL code to piss for this evening. grinning

Indeed, and good to see it was just that. I have my part as I was quite lazy to take time to respect totally grey gradient in css code.

**Pull request merged**
