### PR TITLE
imageio_rawspeed: remove explicit color matrix denominator

### PR DESCRIPTION
**Pull request by kmilos**
@TurboGit This matches [rawspeed changes on develop](https://github.com/darktable-org/rawspeed/commit/70b01450c355f425fa04e6f1cd602b11c4248798), to be merged only when the module is bumped.

### CODE REVIEW

**Comment by TurboGit** [comment]
Noted. Please @LebedevRI let me know when the stable rawspeed branch is bumped I'll handle update the dt sub-module and will merge this PR. Also, it is nice to see you active again, without rawspeed dt will miss a lot!

**Comment by LebedevRI** [comment]
For my future reference, when is the next freeze for next major release planned?
It would be //really// good to have a shared ICAL with these dates.

**Comment by TurboGit** [comment]
@LebedevRI : The plan is described here : https://github.com/darktable-org/darktable/wiki/Handling-a-release

So week-6 from Dec 25 give us a feature freeze on Nov 14. Sorry I don't have a shared ICAL for this.

**Comment by LebedevRI** [comment]
And live!
@kmilos i've tried to clean up open issues that should now be fixed, but i may have missed some.

**Comment by TurboGit** [comment]
@LebedevRI, I see:

> Wo-hoo! But is it good to be back?

I can answer yes, it is good to see you back on this. Thanks a lot for all the work you are doing.

**Comment by kmilos** [comment]
@TurboGit @johnny-bit Looks like CI needs to be sorted for some new minimal requirements now...

**Comment by johnny-bit** [comment]
I'd love to have time to work on this and several other things in/on darktable... That being said - my camera has now measurable layer of dust on it and my "free time" is in negative values :/

**Comment by kmilos** [comment]
Tried fixing in https://github.com/darktable-org/darktable/pull/12822/commits/1e4cd4a1aeada8f3ff12171e38b8c6b60f151bd4 but doesn't seem to work....

**Comment by LebedevRI** [comment]
> Tried fixing in [1e4cd4a](https://github.com/darktable-org/darktable/commit/1e4cd4a1aeada8f3ff12171e38b8c6b60f151bd4) but doesn't seem to work....

You need to just completely remove the GCC7 job, please refer to https://github.com/darktable-org/rawspeed/blob/421f343cdb2bace834670b9a0c76b59bc57d3223/cmake/compiler-versions.cmake.

@parafin, speaking of compiler versions, do tell once the OSX XCode 12.4 baseline can be bumped
https://github.com/darktable-org/rawspeed/blob/421f343cdb2bace834670b9a0c76b59bc57d3223/.github/workflows/CI.yml#L393

**Comment by parafin** [comment]
Bumping it would mean I’m no longer able to build Intel macOS darktable package, since my MacBook is limited to macOS 10.15. So I guess someone with newer hardware has to take over this job.

**Comment by LebedevRI** [comment]
Hence i said //once it can be bumped//.

**Comment by kmilos** [comment]
> You need to just completely remove the GCC7 job

I'll leave that policy to @TurboGit (also note that the Ubuntu 18.04 runners are being deprecated and EOL'd on 2023-04-01)

**Comment by parafin** [comment]
I’m just warning that it doesn’t look to happen soon;)

**Comment by parafin** [comment]
Not sure how apps are usually built, because in any case you require actual Apple hardware to do it. GitHub just provides it for free;) Using GitHub infrastructure has its limitations and signing will have to be dealt outside of it, but indeed that would the way forward. But I’m not going to implement it, because I’m trying to pass macOS packager role to someone else, who will have to maintain it further on. I will be able to sign releases still, if needed. There are a couple of issues in darktable repo (might be closed already) where I explain that. Still, people mostly come and go.

**Comment by johnny-bit** [comment]
> can it not be automated via the very same github actions?

It Should be possible to do so and before my "timeout" i wanted to pursue making nightly + official builds done via CI

> I'm ignoring the signing part of the problem, but is is solvable.

And I even had an appetite to do signing for windows builds so that it's 'trusted source' alas somebody more skilled, determined and with more time on their hands can do it and I'll be happy it was done :)

**Comment by LebedevRI** [comment]
@johnny-bit

> > can it not be automated via the very same github actions?
> 
> It Should be possible to do so and before my "timeout" i wanted to pursue making nightly + official builds done via CI

(speaking about OSX only)
Do you have ETA as to when you might get around to looking into it?
Do you have the hardware to actually test the results?
Since doing so for OSX is the blocker for thinning supported compiler matrix,
i'd like to have that done rather sooner than later.

**Pull request closed without merging**
