### PR TITLE
exif: guard empty string writing by exiv2 version

### LINKED ISSUE #9594: Exported exif data changed/broken since 3.6
**Describe the bug/issue**

It seems that with 3.6 something with the exported exif data has changed. I notice it with using the hugo static site generator (https://gohugo.io). Hugo has the ability to read exif data from images (https://gohugo.io/content-management/image-processing/#exif) such as the date.

Everything worked fine with all the images I have exported with Darktable in the past. But since version 3.6 the images I export can't be used with hugo. It simply stops reading the image exif data with this error:

    exif: decode failed (zero length tag value)

I know that exif data is acually somehow present in the images exported with 3.6 as I can read them without any problems using `ExifTool` for example. But something has changed with DT 3.6 and I'm not sure if it's a problem with darktable or with the used go exif library. But I know it wasn't a problem before 3.6.

**To Reproduce**

You can reproduce the behaviour by running the goexif library used by hugo with the minimal example from the README: https://github.com/rwcarlsen/goexif/
You just have to add a main function and replace the image filename.
Run it once with an image exported by Darktable 3.4 and then with an image exported by Darktable 3.6.

**Platform**

* darktable version : 3.6.0
* Linux - Distro    : Fedora 34

### PR DESCRIPTION
**Pull request by kmilos**
Fixes #9594

Probably good to backport to 3.6.x branch as well...

### CODE REVIEW

**Comment by phweyland** [comment]
Doubt: should be EXIV2_VERSION >= EXIV2_MAKE_VERSION(0,27,4) instead of EXIV2_TEST_VERSION ?
Would that still work with version 0.27.5 ?

**Comment by kmilos** [comment]
EXIV2_TEST_VERSION(0,27,4) *is* the shorthand macro for EXIV2_VERSION >= EXIV2_MAKE_VERSION(0,27,4) ;)

**Comment by phweyland** [comment]
Perfect! Thanks.

**Review by TurboGit — APPROVED** [review]
Looks good, thanks.

**Comment by TurboGit** [comment]
Merged in master & 3.6.x branch.

**Comment by kmilos** [comment]
Thanks

**Pull request merged**
