### PR TITLE
[CI] Add Clang to Windows matrix

### PR DESCRIPTION
**Pull request by victoryforce**
Clang in MSYS2 is and always will be newer than in Ubuntu runners.

At the moment, this means going from Clang 15 to Clang 16.

### CODE REVIEW

**Comment by kmilos** [comment]
Please just uncomment CLANG64 msystem instead of installing and setting compiler directly.

Also, I personally don't feel this is the way to go - the Windows builds are very slow and thus burn many more watts...

**Comment by kmilos** [comment]
> such a change would result in an extra run of CI on the changed PR, which would run many jobs

How does [UCRT64,CLANG64] vs [GNU,LLVM] create more jobs?

I shall refrain from commenting on the rest.

What exact Clang >15 feature are you looking to take advantage of btw?

**Comment by victoryforce** [comment]
> > such a change would result in an extra run of CI on the changed PR, which would run many jobs
> 
> How does [UCRT64,CLANG64] vs [GNU,LLVM] create more jobs?

Miloš, I _never_ wrote that [UCRT64,CLANG64] vs [GNU,LLVM] create more jobs.

I just wrote (in the spirit of your worry about watts, so it was more tongue-in-cheek than serious) that changing the PR would cause another CI run. Of course, another CI run with many jobs will burn a lot of watts.

What was written seriously is that there is no problem to use your suggestion of installing packages via msystem. But for now we're talking about different things and I'm not sure if you're not going to further criticize the Clang version upgrade in CI. If we find an understanding on this, I can change the PR. But while PR is blocked by this criticism, such a change may turn out to be work done in vain.

> I shall refrain from commenting on the rest.

Thank you. As for the criticism of the uneconomical use of energy, you can recall that I reduced the number of executed jobs in CI by 8 times and optimized the ones that remained.

> What exact Clang >15 feature are you looking to take advantage of btw?

I'm not going to _take advantage_ of some specific Clang > 15 feature. This is CI (Continuous integration). And I'm going to add as fresh Clang as possible to it, because if we don't support newer versions of the compilers, then we might as well pack up shop.

**Comment by victoryforce** [comment]
@TurboGit What will be your decision on this PR? Should I close it?

**Comment by victoryforce** [comment]
I still don't understand what was the problem with this PR, but if it's stuck, I close it. I occasionally run a build with Clang in MSYS2, so problems with fresh Clang, if any, will be caught, albeit belatedly.

**Pull request closed without merging**
