### PR TITLE
homebrew: Explicitly install pkg-config

### PR DESCRIPTION
**Pull request by zisoft**
In addition to PR #13655 pkg-config needs to be added here as well.

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by TurboGit** [comment]
@zisoft : Are you volunteering to be the next MacOS maintainer? If so let me know, I have prepared the 4.2.1 tarball so if you want to try a release cycle it could be nice. Note that 4.2.1 is still handled by parafin, but this could be a good preparation for 4.4? Anyway, do not hesitate to send me a message.

**Comment by zisoft** [comment]
@TurboGit: Yes, you can count on me. But I would really like to see this as a teamwork, so someone else also needs to jump in.

**Comment by TurboGit** [comment]
Ok, I'll forward you the message I sent to the maintainers if you want to try a build from a release tarball. I hope you'll get help for MacOS soon. Thanks.

**Pull request merged**
