### PR TITLE
Added PL usermanual translation

### PR DESCRIPTION
**Pull request by lkarcz**
Another, due to email address mess - and I hope the last one - try to make a pull request of a complete Polish usermanual translation. Compared to disussion list attachment, this pull request contains newer PO file so please consider my email on the list as void.

### CODE REVIEW

**Comment by TurboGit** [comment]
Thanks!

Merged and PDF online:

https://github.com/darktable-org/darktable/releases/download/release-2.6.2/darktable-usermanual-pl.pdf

**Comment by lkarcz** [comment]
Nice to see that.

A link at https://www.darktable.org/resources/ maybe? ;) I think could
spread some words to some Polish IT / photo blogs when done.

Cheers,


pt., 12 kwi 2019 o 17:13 Pascal Obry <notifications@github.com> napisał(a):

**Comment by TurboGit** [comment]
> A link at https://www.darktable.org/resources/ maybe? ;) 

I have sent a PR for this, waiting for @patdavid to merge it.

**Comment by TurboGit** [comment]
Et voilà: https://www.darktable.org/resources/

**Comment by lkarcz** [comment]
I see PDF link only, still not available in upper 'online' section.

ŁK



pt., 12 kwi 2019 o 19:19 Pascal Obry <notifications@github.com> napisał(a):

**Pull request merged**
