### PR TITLE
Continue work on RCD demosaicer

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
There has been a nasty bug in the rcd demosaicer code introduced by me when tuning for performance.

Basically red@green and blue@green colorsites had been calculated wrong resulting in a sometimes
checkerboard like pattern especially visible at vertical borders, that was a definite bug.

Also the input data were wrong for the last column - this got un-noticed because we always used
even tile sizes.

A third point - this time an improvement - was cherry picked from the devel branch here, the border
region calculated by the less precise algo could be reduced so there are less visible artefacts at
the borders while zooming in.

The issue reported by @kofa73 at #7756 is probably fixed by this, at least i can't reproduce any
longer.

This should be merged as a bug-fix anyway.

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
@TurboGit the issue reported correctly in #7756 is something different i am currently fixing. (Parameters passed to the demosaicer are sometimes wrong) So as this is a bug fixer i would suggest to merge.

The other stuff should be in another pr, i am not sure if there is something to fix in 3.4 branch too ...

**Comment by TurboGit** [comment]
> The other stuff should be in another pr, i am not sure if there is something to fix in 3.4 branch too ...

No, RCD will be in 3.6 only.

**Review by TurboGit — APPROVED** [review]
Thanks !

**Comment by jenshannoschwalm** [comment]
Sure it's for 3.6, i will track down the problems mentioned in that issue and from my current understanding there might be something wrong with passed parameters for demosaicers in general.

**Pull request merged**
