### PR TITLE
Add geometry of Spyder Checkr Photo.

### PR DESCRIPTION
**Pull request by SolidTux**
This adds the color cards of the Spyder Checkr Photo (a smaller, more portable version of their color checkers). I assumed that it has the same colors as the new Checkr 48, just with a different geometry.

They have a shared [manual](https://spyderx.datacolor.com/wp-content/uploads/2022/08/Spyder-Checkrs-User-Guide-FINAL-EN-1.pdf), but I couldn't find something to really prove that it indeed is the same.

### CODE REVIEW

**Comment by elstoc** [comment]
If we're not sure they're the same, we shouldn't merge this, as it could do more harm than good.

**Comment by SolidTux** [comment]
Totally agree! I mainly opened this to start the discussion in the hope that someone might have more information.

**Comment by TurboGit** [comment]
In the manual it is said:

> Spyder Checkr Photo
> • 4 Interchangeable Target Color Cards
> • Spyder Checkr Photo Case
> • Lanyard
> • Download link and Software Serial Number

First point is worrisome... _Interchangeable_.

**Comment by SolidTux** [comment]
Interchangeable means that you can reorder the cards (e.g. have only only page of 24 color values and a grayscale card on one image). That is also a thing for the big Checkr (see page 5 in the manual).

Theoretically this means that one would need more than one definition, but I think having one with the stock configuration would be fine.

**Comment by TurboGit** [comment]
> but I think having one with the stock configuration would be fine.

I think we want a full support or no support. So we would need the definitions of the 4 cards.

**Comment by MStraeten** [comment]
No, just the 48 patches on on opposite sides are relevant - the others aren’t useable for color calibration. Even you can reorder the parts it doesn’t make sense to do it since most software evaluating the patches assumes the standard 48 patch layout or a 24 patch layout.
So for practical use the 48 patch layout and maybe the spyder checkt 24 comparable card makes sense ( but that should be already covered by the existing layout - to be verified)
Since there’re no new values for the patches reported, I’d assume these are the same values as the already known v2 values. It doesn’t make sense for datacolor to provide different sets of values for their product portfolio at the same time - since these are intended to be interchangeable.

**Comment by SolidTux** [comment]
I wrote a message to the datacolor support and got the following response:

> This information is not yet available for the Spyder Checkr Photo but it is being assembled.  Please check back in early January.

So it sounds like they are actually different. They also write something about an improved printing process, so maybe that lead to some color changes as well.

**Comment by TurboGit** [comment]
Good, let's wait then.

**Comment by kadykov** [comment]
> I wrote a message to the datacolor support and got the following response:
> 
> > This information is not yet available for the Spyder Checkr Photo but it is being assembled.  Please check back in early January.
> 
> So it sounds like they are actually different. They also write something about an improved printing process, so maybe that lead to some color changes as well.

Do you have any news from Datacolor?

**Comment by MStraeten** [comment]
obviously not, because otherwise the pr would already be updated ;)

**Comment by SolidTux** [comment]
I didn't get an update yet, but I'll write them a mail. But I'll definitely update the PR as fast as I find time then as I'm actually waiting to edit some photos and need it for that ^^

**Comment by SolidTux** [comment]
The answer I got one month ago was they "they will come back to me", but so far that hasn't happened. I sent another reminder, maybe this will be the month.

**Comment by kadykov** [comment]
Thank you for the update, I hope they will give us the confirmation soon.

**Comment by kadykov** [comment]
Any updates?

**Comment by MStraeten** [comment]
no, if there were updates the pr would have been updated and merged ;)

**Review by kadykov — CHANGES_REQUESTED** [review]
I have received an official answer from Datacolor with the [correct color values](https://spyderx.datacolor.com/downloads/SpyderCheckr_Color_Data_V2.pdf). So far, I found only two differences, and I marked them in the comments.
If there are no other suggestions, I think the commit should be merged.

**Comment by MStraeten** [comment]
the pdf was created 2018 - so they didn’t change the patches for spyder checkr photo. So the values for spyder_48_v2 also needs to be updated

**Comment by TurboGit** [comment]
Indeed, not changed since 2018, see the metadata in PDF:

Capture d’écran de 2023-04-18 13-31-57

**Comment by TurboGit** [comment]
@SolidTux : Any news about this?

**Comment by SolidTux** [comment]
I didn't get a response from the support, so I forgot about this for a while. I'll try to find time in the coming days (hopefully) or weeks to update the PR and test it a bit.

**Comment by TurboGit** [comment]
> I didn't get a response from the support, so I forgot about this for a while. I'll try to find time in the coming days (hopefully) or weeks to update the PR and test it a bit.

Note that feature freeze is on next Monday. So the dead line is short, if you cannot meet this dead line let me know and I'll reschedule for 4.6. TIA.

**Comment by SolidTux** [comment]
The branch should now be up to date with the master and updated with the new values.

**Comment by MStraeten** [comment]
Maybe also update the COLOR_CHECKER_SPYDER_48_V2 patches F1 and F5 to have consistent values according to the datacolor pdf.
It doesn’t make sense to correct them just for the new geometry

**Comment by SolidTux** [comment]
Should be done now.

**Pull request merged**
