### PR TITLE
recent history and rating filters "soft" revert

### PR DESCRIPTION
**Pull request by AlicVB**
this fix #11752 #11754 #11757

Hi all, 

Considering the amount of negative reaction to my recent changes, here is a solution that should please everybody and hopefully allow us to go forward in a more peaceful atmosphere :)

This PR allow those who want it to switch between the "history button" inside the collect module and the "recent collect" module. To do that, just use the specific preference located along the other "collect" or "recentcollect" prefs (under the hamburger button like for the other ones)
This PR also allow to use 2 different rating rules : "range rating" which will expose the "new" stars widget, and "rating" which will use the "legacy" widget.

**So finally it is possible to get the previous UI for collection and collection history as it was in 3.8.1 without seeing or using the new collection filters.**

Thanks to the modularity of dt modules and filters, the change done for that is completely self-contained. With very minor change done on the core code.

So, with that in place, everybody should be able (with 3-4 click one time) to get it's preferred way of working.

Once again, the goal here is NOT to avoid all the discussion / criticism, but to put us in a state where enhancements on one or the other solutions can be done. See the issues / PR mentioned above, and you will see that we always fall in a "stucked" situation where the only solution is to upset one group !

For those who will prefer the "legacy" UI, everything should work exactly as before. If that's not the case, it is a bug, so don't hesitate to report it in new issues : I'll take care as usual !

### CODE REVIEW

**Comment by aurelienpierre** [comment]
GUI-wise, it's an improvement. Although it still comes with one more option.

Dev-wise, it still increases the technical debt and adds one more option to maintain.

Long-term speaking, if you are still set on #10733, it's a loss of everybody's time because it will get nuked at some point.

**Comment by TurboGit** [comment]
@AlicVB : Thanks a lot for this. A good compromise for the 4.0 and just in time for the code freeze. I'll merge right away to ensure it gets tested ASAP. On my side it is all good. Again thanks for your patience and your hard work on this.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by ralfbrown** [comment]
Minor initiialization issue - the first time I started dt after incorporating this update, it showed *both* the history button and the recent collections module.   Toggling the preference in collections fixed that, and subsequently I've only seen on or the other, not both.

In addition, the recent collections module started out showing a bunch of filtering rules rather than recent collections.  Again, that was fixing itself, as only collections got added to the list, not changed filtering rules.

**Comment by AlicVB** [comment]
@ralfbrown : thanks for the test. I've proposed a fix here : #11802 
I've not reproduced the filtering rules in the recent collect module... I wonder if what you was seeing was not the recentcollect entries like they were before the removing of the module. That would explain it... can you confirm ? (or not ;))

**Comment by ralfbrown** [comment]
What showed in recentcollect was literally
 "range rating 0:1:% and color label 0:1:% and search 0:1:%"
and
 "range rating 0:1:>=3 and color label 0:1:-2147479552 and search:0:1:%"
(a couple haven't yet scrolled off the end of the history)

**Comment by AlicVB** [comment]
oh... I haven't reproduce that, but I'll test again ! Thanks !

**Comment by AlicVB** [comment]
@ralfbrown : I really can't reproduce... I have done many tests, each starting with a clean darktablerc + some random history : 
- 3.8.1 -> master
- 3.8.1 -> before the filters PR -> master
- before the filters PR -> master

And I may have overlooked something, but I don't get how that's possible in the code : the lines in the module are stored in darktablerc under `plugins/lighttable/recentcollect/line%d` and it's done nowhere else in the code... so the only solution would be an issue in how we retrieve the line, but I don't get how filters information can get there too...

My best guess atm would be that you have tested dt with a "ghost" recentcollect module (a leftover in the build dir) or that you have tested a revert of this module removing without ensuring that the right boolean is passed to the serialize/deserialized routines... Is that the case ?

If that's not the case, and you still have the values mentionned above (not sure), I would be interested if you can copy-paste the content of the `plugins/lighttable/recentcollect/line%d` with the higher numbers instead of `%d` ...

**Comment by ralfbrown** [comment]
It's possible I forgot to remove the build directory somewhere along the line.

Relevant darktablerc lines are
```
plugins/lighttable/recentcollect/line12=3:0:32:0:1:%$0:18:0:1:%$0:33:0:1:%$
plugins/lighttable/recentcollect/line13=3:0:32:0:1:>=3$0:18:0:1:%$0:33:0:1:%$
plugins/lighttable/recentcollect/line14=3:0:32:0:1:%$0:18:0:1:-2147479552$0:33:0:1:%$
```
while all the lower-numbered ones look like
```
plugins/lighttable/recentcollect/line2=1:0:0:/p/Pgh/2022/202205CMU$
```

**Comment by AlicVB** [comment]
hmmm... so effectively for some reason serialized filters have ended in your recentcollect lines in darktablerc... (that's not a mix of both)

I've read the code again, and I really don't get how that's possible at all...
For the record, the only point where we write `plugins/lighttable/recentcollect/line%d` is in recentcollect.c in the routine `_lib_recentcollection_updated` and the value written is issued from `dt_collection_serialize(buf, sizeof(buf), FALSE)` which can only write values like you have if the last parameter is `TRUE`...
I've also search among previous commit without success...

The only thing I can think of would be that you have tested the filter PR branch during the dev process, and there was an issue at that moment that has been fixed after by force-push...

If that's not the case, I propose to add some safeguard in recentcollect against degenerated entries...

**Comment by ralfbrown** [comment]
No, I don't think I've tested the PR before merge.  This is on my "production" copy, which gets rebuilt from master usually every few weeks (prior to Saturday, I had updated it the previous weekend).

**Pull request merged**
