### PR TITLE
conf: check also for symlink as a possible path.

### PR DESCRIPTION
**Pull request by TurboGit**

### CODE REVIEW

**Comment by AxelG-DE** [comment]
I checked and it did not help, sorry. Documented in the issue #15861 
I wish I could do more to have a more tangible test result

**Comment by AxelG-DE** [comment]
I have a new phaenomenon: dt hangs while I type, but getting a new PID every few seconds

**Comment by AxelG-DE** [comment]
I had delted my former comment as I found an error during my this morning tests, **sorry!!!**

**Comment by AxelG-DE** [comment]
tested the latest commit b4cce7b795 which seems a big improvement, while I can still stall it for ~300s when clicking on my home-dir with recursive and exclude-non-raws ticked.

That stall makes me still wondering, what is going on, when the CPU is busy for so long, but no IO happens

**Comment by TurboGit** [comment]
@victoryforce : Can you double check the 2nd commit: [imageio: Ensure we match a full file extension.](https://github.com/darktable-org/darktable/pull/15870/commits/e949a9fda9306ba147f61344bd3a049907781706)

**Comment by victoryforce** [comment]
> @victoryforce : Can you double check the 2nd commit: [imageio: Ensure we match a full file extension.](https://github.com/darktable-org/darktable/pull/15870/commits/e949a9fda9306ba147f61344bd3a049907781706)

If I remember glib functions correctly (I'm writing from memory right now), can we just use `g_ascii_strcasecmp` instead of `g_ascii_strncasecmp` with the extra check?

**Comment by TurboGit** [comment]
> If I remember glib functions correctly (I'm writing from memory right now), can we just use `g_ascii_strcasecmp` instead of `g_ascii_strncasecmp` with the extra check?

Fully correct, now fixed (plus some other occurrences). Thanks.

**Comment by AxelG-DE** [comment]
Sorry for my boon question:
The first commit says Check symlink as possible path and the last one says "never follow symlinks". Where my picture folder is particularly a symling :-D 
/me is confused :) :)

**Pull request merged**
