### PR TITLE
Bugfix #13668

### LINKED ISSUE #13668: dt-master crashes on export
**Describe the bug/issue**
While exporting dt master crahes with empty bactrace.

**To Reproduce**
export NEF to PNG with the following settings:
grafik
(actually also with this setting, where I started with:
grafik

** backtraces **
[darktable_bt_76WW01.txt](https://github.com/darktable-org/darktable/files/10774289/darktable_bt_76WW01.txt)
[dt-crash_20230218a.txt](https://github.com/darktable-org/darktable/files/10774290/dt-crash_20230218a.txt)

I could not CMAKE_BUILD_TYPE="RelWithDebInfo" due to #13667 

**Expected behavior**
No Crash

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.3.0+674~gec0e357b6
* OS                : Linux - kernel 6.1.12-gentoo
* Distro            : Gentoo Base System release 2.9
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : NVIDIA GeForce GTX 1060 6GB
* Graphics card1    : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-525.89.02
* OpenCL installed  : Yes (opencl-headers-2022.09.30)
* OpenCL activated  : Yes
* Xorg              : xorg-server-21.1.7
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.35
* gcc               : x86_64-pc-linux-gnu-11
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
A try to fix #13668 from reading source, no image to test on available for me.

So in need for
1. in depth review
2. testing by @AxelG-DE

### CODE REVIEW

**Comment by AxelG-DE** [comment]
@jenshannoschwalm 
testing has been started
I will issue a bunch of exports and report back tomorrow or latest on Saturday morning

**Comment by AxelG-DE** [comment]
grafik
this is unavoidable?

**Comment by jenshannoschwalm** [comment]
Yes. Once!

**Review by TurboGit — COMMENTED** [review]
This looks correct to me. The 0.5 is certainly a fix and hopefully it will fix the crash. I cannot say as I don't reproduce the issue. Let's wait for feedback from @AxelG-DE.

**Review by ralfbrown — APPROVED** [review]
Looks OK.
The code might be marginally faster if you made dx, dy, and lwidth `firstprivate` instead of `sharedconst` in the loop at line 200 -- there's no advantage in declaring constant integer variables shared, since the reference will take up as much space as the copy of the variable that gets made by firstprivate, and there's a good chance the compiler can keep them in registers instead of re-reading from memory.

**Comment by AxelG-DE** [comment]
up to now (23:06 CET) 1218 files exported successfully but I have injected this PR prior to 4f7a190...

will go to bed now. keep on reporting tomorrow...

**Comment by AxelG-DE** [comment]
I have exported 2474 pictures w/o crash. 
next I will compare the opencl settings and set them back to what I had and try again

**Comment by AxelG-DE** [comment]
I found the "cached kernels" are named differently...
darktable $ ls -la
insgesamt 32
drwx------  8 gerber users 4096 22. Feb 20:27 .
drwxr-xr-x 70 gerber users 8192 22. Feb 20:05 ..
drwx------  2 gerber users 4096 20. Feb 20:12 cached_kernels_for_NVIDIAGeForceGTX10606GB_5258505
drwx------  2 gerber users 4096 20. Feb 20:12 cached_kernels_for_NVIDIAGeForceRTX2070SUPER_5258505
drwx------  2 gerber users 4096 22. Feb 20:27 cached_v1_kernels_for_NVIDIAGeForceGTX10606GB_5258505
drwx------  2 gerber users 4096 22. Feb 20:27 cached_v1_kernels_for_NVIDIAGeForceRTX2070SUPER_5258505
drwxr-x--- 11 gerber users   87 29. Apr 2022  mipmaps-89f93a31a5f228beb2c9cd0ac2ac4fecf7eaa7d2.d
drwxr-x---  4 gerber users   24 23. Apr 2022  mipmaps-9d21b425574bb004e9bf37c1209e3854980bdba2.d

I will delete them anyways to make shure they are new

**Comment by AxelG-DE** [comment]
My settings getting reverted again (even w/o backup) :-/ , so I cannot do that test I announced with my own OpenCL settings ....

I strongly opt not to force-reset OpenCL-settings

**Comment by jenshannoschwalm** [comment]
You accepted the Infobox? Otherwise there is no update of the version ...

**Comment by AxelG-DE** [comment]
> @AxelG-DE : Your reports shows that this PR is a good fix anyway. Right?

no crash = good fix :-)



> You accepted the Infobox? Otherwise there is no update of the version ...

that might be, that I clicked "show again" (forgot tbh  :-) ). I can test this evening. Now I gotta go to the office...

**Comment by jenshannoschwalm** [comment]
Somewhat off-topic but @AxelG-DE : Did you measure **ever any** performance gain on a module by adding the compiler flags on nvidia devices? 

You know about the `--bench-module` switch ?

**Comment by AxelG-DE** [comment]
> Somewhat off-topic but @AxelG-DE : Did you measure **ever any** performance gain on a module by adding the compiler flags on nvidia devices?
> 
> You know about the `--bench-module` switch ?

I'm not really familiar with --bench-module, no. I remember once I fiddled with something but gave up when it went over my head. I did use my benchmark script which I posted to you during your opencl hot period. There wasn't too much gain.... Currently that script is broken, even I didn't touch it and live is in the way to fix it.

FWIW: I said recently, that I exported a lot the two weeks prior the crash issue. Now I remember one difference: 
at that time I was exporting directly to an old NAS via NFS, which is mega slow (2.5MB/s). Ever since I export to my quite fast barracuda, which has a Lvm_cache on an ssd.

**Comment by jenshannoschwalm** [comment]
That bench option is new stuff and allows to bench a specific module with a better timing so that will help to check such compiler options. So if you are experimenting with Nvidia options and find a faster & stable setting, let me know.

Such a hint could also be given by the info box you mentioned.

**Comment by AxelG-DE** [comment]
I think, from my side, we are ready to go...

1388 pictures exported and still running fine with the following OpenCL-settings:
(I know, some are obsolete, those are leftovers from past)

```
cldevice_intelruhdgraphics6300x3e98=0 1000 0 16 0.053222
cldevice_nvidiageforcegtx10606gb=0 1000 0 16 0.020314
cldevice_nvidiageforcertx2070super=0 1000 0 16 0.016996
cldevice_v0_intelruhdgraphics6300x3e98=0 1000 0 16 16 0.068525
cldevice_v0_nvidiageforcegtx10606gb=0 1000 0 16 16 0.021151
cldevice_v0_nvidiageforcertx2070super=0 1000 0 16 16 0.021101
cldevice_v1_intelruhdgraphics6300x3e98=0 250 0 16 16 128 0.064072
cldevice_v1_nvidiageforcegtx10606gb=0 250 0 16 16 128 0.020434
cldevice_v1_nvidiageforcertx2070super=0 250 0 16 16 128 0.046554
cldevice_v2_intelruhdgraphics6300x3e98=0 250 0 16 16 128 0 0.052595
cldevice_v2_nvidiageforcegtx10606gb=0 250 0 16 16 128 0 0.020326
cldevice_v2_nvidiageforcertx2070super=0 250 0 16 16 128 0 0.016950
cldevice_v3_intelruhdgraphics6300x3e98=0 250 0 16 16 128 0 0 0.053645
cldevice_v3_intelruhdgraphics6300x3e98_building=
cldevice_v3_nvidiageforcegtx10606gb=0 250 0 16 16 128 0 0 0.020676
cldevice_v3_nvidiageforcegtx10606gb_building=
cldevice_v3_nvidiageforcertx2070super=0 250 0 16 16 128 0 0 0.017082
cldevice_v3_nvidiageforcertx2070super_building=
cldevice_v4_intelruhdgraphics6300x3e98=0 250 0 16 16 128 0 0 0.055792
cldevice_v4_intelruhdgraphics6300x3e98_building=-cl-mad-enable -cl-no-signed-zeros -cl-unsafe-math-optimizations -cl-finite-math-only -cl-fast-relaxed-math
cldevice_v4_nvidiageforcegtx10606gb=0 70 0 16 16 1024 0 0 0.021183 0.000
cldevice_v4_nvidiageforcegtx10606gb_building=-cl-mad-enable -cl-no-signed-zeros -cl-unsafe-math-optimizations -cl-finite-math-only -cl-fast-relaxed-math
cldevice_v4_nvidiageforcegtx10606gb_id1=400
cldevice_v4_nvidiageforcertx2070super=0 10 0 16 16 1024 0 0 0.017178 0.000
cldevice_v4_nvidiageforcertx2070super_building=-cl-mad-enable -cl-no-signed-zeros -cl-unsafe-math-optimizations -cl-finite-math-only -cl-fast-relaxed-math
cldevice_v4_nvidiageforcertx2070super_id0=400

opencl=TRUE
opencl_async_pixelpipe=true
opencl_avoid_atomics=false
opencl_building_gpu0=-cl-mad-enable -cl-no-signed-zeros -cl-unsafe-math-optimizations -cl-finite-math-only -cl-fast-relaxed-math
opencl_building_gpu1=-cl-mad-enable -cl-no-signed-zeros -cl-unsafe-math-optimizations -cl-finite-math-only -cl-fast-relaxed-math
opencl_building_gpu2=-cl-mad-enable -cl-no-signed-zeros -cl-unsafe-math-optimizations -cl-finite-math-only -cl-fast-relaxed-math
opencl_checksum=623104504
opencl_device_priority=0,1,/1,*/0,1,*/0,1,*/*
opencl_disable_drivers_blacklist=true
opencl_library=
opencl_mandatory_timeout=100
opencl_memory_headroom=600
opencl_memory_requirement=1024
opencl_micro_nap=70
opencl_number_event_handles=1028
opencl_scheduling_profile=default
opencl_size_roundup=16
opencl_synch_cache=active module
opencl_tuning_mode=memory size and transfer
opencl_use_cpu_devices=false
opencl_use_pinned_memory=true
```

**Review by TurboGit — APPROVED** [review]
So, go... Thanks.

**Comment by gi-man** [comment]
> opencl_mandatory_timeout=100

This value seems low. I think dt is still using this (Hanno correct me if I'm wrong). Per this Issue https://github.com/darktable-org/darktable/pull/10836, 100=0.5sec. Default is 400 = 2s.

**Comment by AxelG-DE** [comment]
I ran this value as 100 since many years with 2 gtx 1060 at times, but admittedly by that time there was no defuse&sharpen. 

I may consider to raise it, but somehow unrelated to this solved issue, I guess as a CPU mudule crashed

(still wondering why I ran into this now and not earlier. The exported pics are favs, hence not exported for the first time) 

@jenshannoschwalm thanks for fixing. ❤️

**Comment by jenshannoschwalm** [comment]
> current default for timeout is 400. I don't know anything better with current architecture of opencl.

I think that a short timeout like 100 is much better if you have multiple gpus. The default of 400 is just sort of a hack.

**Pull request merged**
