### PR TITLE
color zones: fix periodic boundary conditions when color is selected by hue

### PR DESCRIPTION
**Pull request by rabauke**
Periodic boundary conditions must be applied when color is selected by hue in the color zones module. These periodic boundary conditions **cannot** be realized by tweaking the interpolation nodes, the interpolation routines themselves must obey periodic boundary conditions. Not doing so leads to various bugs, see issue https://github.com/darktable-org/darktable/issues/2533 and issue https://github.com/darktable-org/darktable/issues/2641.

Interpolation routines have been reimplemented from scratch and the color zones module has been revised. This bugfix will break some edits, i.e., old edits might give slightly different results with the revised code.

Code may affect _every_ module that utilizes spline interpolation. Testing needed. Currently, strong artifacts occur in the basecurve module in extreme highlights.

### CODE REVIEW

**Comment by TurboGit** [comment]
Can you please rebase on top of current master and solve the conflict? Thanks.

**Comment by TurboGit** [comment]
Looks good to me! Will merge hoping the diff with old edits won't be too big. Anyway, merging sooner will make a better field testing possible.

@rabauke : A side note, do not hesitate to add a comment when you push a fix as otherwise I do not notice the new version. There is no notification for a push, but I do get notification for comments.

**Comment by edgardoh** [comment]
@TurboGit , do you really want to risk breaking compatibility on all the curves, that is all our edits, just because of the periodic boundary on the hue curve on the color zones?

And why the default nodes are now added at the center of the curves? How that makes our work easier? Not to mention the inconsistencies that this introduces.

Can you please consider reverting this?

**Comment by TurboGit** [comment]
> And why the default nodes are now added at the center of the curves? How that makes our work easier? Not to mention the inconsistencies that this introduces.

Can you tell me more about this? I didn't see that on my side.

**Comment by TurboGit** [comment]
>  do you really want to risk breaking compatibility on all the curves, that is all our edits, just because of the periodic boundary on the hue curve on the color zones?

The changes should not be that big, at least what I have tested on my edits. Do you have found issues with that? If it breaks badly some old edits, yes I'll revert.

**Comment by edgardoh** [comment]
The default for the initial two nodes is not 0, 1 anymore, they are in the
middle. This does not makes much sense for most of the edits.

**Comment by edgardoh** [comment]
Is not about the intensity (is that the word?) of the changes, Heiko admits
that there's differences, and we guaranty backward compatibility, so for me
that alone is a don't.

If this makes the periodic boundary more accurate for the hue curve, then
great, let's go for it, but let's modify *only* the hue curve, not all
curves. The way to do this without breaking compatibility is to add new
interpolation methods, initially only on the color zones, and eventually
deprecate the old ones, like has been done for some blend modes. This may
give us more code, but is the price to pay to ensure backward compatibility.

And if the way nodes behaves on the color zones will change, at least give
some notice so we have the chance to discuss it.

**Comment by TurboGit** [comment]
Ok, reverted for now.

**Comment by aurelienpierre** [comment]
> The default for the initial two nodes is not 0, 1 anymore, they are in the middle. This does not makes much sense for most of the edits.

yeah but that's only the settings starting point, is it ? How does that break compatibility for existing nodes ?

What makes me wonder here is mostly the C++ lib in a project where nobody likes that, and no sign of vectorization/parallelization of the loops (as far as I understand C++).

**Comment by TurboGit** [comment]
@rabauke : is it possible to make the initial nodes on 0 1 instead of creating them in the middle of the curve? If not, why was this changed? I'd really like having this merged even if old edits are slightly changed. We are speaking about correctness of the routine. If there is real issues with that, do you think we can keep the old routine and have the new one activated only for new edits?

Last, if possible moving to plain C instead of C++ would be nice. But this is not blocking to me.

Thanks.

**Comment by TurboGit** [comment]
BTW, it would be nice to create a new PR for discussion as I cannot reopen a PR a "marked" as merged.

**Comment by aurelienpierre** [comment]
@Turbogit I guess if the periodic condition is respected, the 0 node == 1 node (that's the whole point of the periodicity) so having both makes no sense anymore.

**Pull request merged**
