### PR TITLE
geotagging: fix direct entry issue on month and day.

### LINKED ISSUE #9174: Changing date in geotagging module gives weird results
**Introduction**
see title

**Describe the bug/issue**
Changing date/time in geotagging module behaves somewhat weird.
Changing time is ok, I can enter any valid value and this is shown in the input field.
Changing date is different:
- changing year seems to be ok, but 
- when changing month or day the input value is not accepted and 
- when changing month the year jumps to another value

**Expected behavior**
Entering a figure in one of the fields should not affect other values of the date/time-string

**Screencast**
https://www.bilddateien.de/github/darktable-issue-9174.mp4

**Platform**
```
darktable version : 3.5.0+2458~g33deb6bb1
System:
  Kernel: 4.19.0-16-amd64 x86_64 bits: 64 compiler: gcc 
  v: 8.3.0 Desktop: Cinnamon 3.8.8 Distro: Debian GNU/Linux 10 (buster) 
Machine:
  Type: Desktop Mobo: ASUSTeK model: P8Z77-M v: Rev 1.xx serial: <filter> 
  UEFI: American Megatrends v: 2203 date: 12/18/2015 
CPU:
  Topology: Quad Core model: Intel Core i5-3570 bits: 64 type: MCP 
  arch: Ivy Bridge rev: 9 L2 cache: 6144 KiB 
  flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 27280 
  Speed: 3714 MHz min/max: 1600/3800 MHz Core speeds (MHz): 1: 3661 2: 3640 
  3: 3663 4: 3636 
Graphics:
  Device-1: Intel Xeon E3-1200 v2/3rd Gen Core processor Graphics 
  vendor: ASUSTeK P8H77-I driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.20.4 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1920x1080~60Hz 
  OpenGL: renderer: Mesa DRI Intel Ivybridge Desktop v: 4.2 Mesa 18.3.6 
  direct render: Yes 
```

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts?
   - What lua scripts start automatically? none
   - What lua scripts were running when the bug occurred? none
- also checked with `3.5.0+2330~g4fb67a1a1` and 
  - clean profile
  - some images in a clean folder with no xmp
  
  same behavior

### PR DESCRIPTION
**Pull request by phweyland**
Enter is now necessary to take in account entered digits.

Fixes #9174

@bilddateien Would be nice if you could check that solves properly your issue. TIA.

### CODE REVIEW

**Comment by bilddateien** [comment]
> @bilddateien Would be nice if you could check that solves properly your issue. TIA.

Will try to find out how to integrate this into my build ...

**Comment by phweyland** [comment]
to create a new local branch geotag-fix:

`git fetch https://github.com/darktable-org/darktable pull/9180/head:geotag-fix`

**Comment by bilddateien** [comment]
Thanks for your help,
in the meantime I tried
`$ git am 9180.patch
Wende an: geotagging: fix direct entry issue on month and day.`

and then I got:
`$ git log
commit 37b22c6eff1710dfa0da5241b67cc95eacc63d86 (HEAD -> master)
Author: phweyland <philippe.weyland@laposte.net>
Date:   Sun Jun 6 21:18:24 2021 +0200

    geotagging: fix direct entry issue on month and day.
    
    Enter is now necessary to take in account entered digits.
    
    Fixes #9174
`
and then I compiled.
Just started what identifies as `3.5.0+2473~g37b22c6ef` some minutes ago and tested.
Seems to work as expected - can enter month and day without changing the other values as long as I am in the valid range.

When entering month `13` it will be `01` and year is incremented by one off course. Also tested several combinations like this with different day, month and hour overflows - seems to work correct.

Looks good so far.

**Comment by phweyland** [comment]
Thanks a lot for testing @bilddateien.
@TurboGit I think this could be merged.
I'm not perfectly happy with the "enter" behavior ("tab" is a bit better) as the cursor stays at the end of the field,  but I don't have better idea for the time being. Any suggestion is welcome.

**Review by TurboGit — APPROVED** [review]
Looks ok to me and I have no better proposal. So merging now as it is a real fix and we can improve if a better fix is possible. Thanks!

**Pull request merged**
