### PR TITLE
imageio_tiff: support for 8/16bit tiff with CIELAB/ICCLAB photometric

### PR DESCRIPTION
**Pull request by upegelow**
TIFF files with CIELAB or ICCLAB format get converted to sRGB on input.

### CODE REVIEW

**Comment by TurboGit** [comment]
Sounds good! Do you think this can/should go in 2.6.1?

**Comment by parafin** [comment]
Shouldn't it be kept in LAB and just set LAB colorspace in colorin iop? Is conversion LAB->sRGB->LAB lossless?

**Comment by aurelienpierre** [comment]
> > Sounds good! Do you think this can/should go in 2.6.1?
> 
> Let's wait a bit. I am interested to see if this really works well. Also the decision to convert to sRGB might be debatable with e.g. AdobeRGB being an alternative.

As a working space, linear RGB spaces like REC2020 are most secure due to the proximity with pure spectral primaries. If it's an achival space, ACES P0 is the best, Prophoto RGB works too.

**Comment by TurboGit** [comment]
Ulrich, so what about 2.6?

**Comment by upegelow** [comment]
> Ulrich, so what about 2.6?

It's fine to cherry-pick into 2.6 (see discussion in darktable-users).

**Comment by calabi-yaui** [comment]
Hello Ulrich. This feature seems to be broken in v4, the images remain black. Any chance to get it back working? It is sorely missed.

**Comment by kmilos** [comment]
> This feature seems to be broken in v4, the images remain black.

Please open an issue for this, and provide as many details as possible, including ideally a sample image.

**Pull request merged**
