### PR TITLE
Avoid div by zero in dt_iop_clip_and_zoom_mosaic_half_size

### LINKED ISSUE #8951: darktable crashes with "Floating point exception (core dumped)" but darktable-cli works just fine
**Describe the bug/issue**
The following DNG makes darktable crash with an "Floating point exception (core dumped)" error: [dng.zip](https://github.com/darktable-org/darktable/files/6470557/data-631798-g50ilw7ggxkrze7lbkdc.dng.zip)

All other tools I tried are able to read this example DNG just fine though (including RawTherapee and Lightroom). Most interesting though, even darktable-cli is able to read this DNG and save it as a TIF so I am under the impression that it is a bug in darktable.

**To Reproduce**
Open the DNG referenced above in darktable, preferably having launched darktable from a terminal to also see the error message.

**Expected behavior**
That the DNG is opened without crashing, just like in RawTherapee and Lightroom.

**Platform**
* darktable version : 3.0.1
* OS : Linux 5.4.0-71-generic
* Linux - Distro : Ubuntu 20.04 LTS
* Memory : 32 GB
* Graphics card : NVIDIA GTX 1650
* Graphics driver : NVIDIA 460.56
* OpenCL installed : unknown
* OpenCL activated : unknown
* Xorg : 1.20.9
* Desktop : Xfce 4.14.0
* GTK+ : 3.24.20
* gcc : 9.3.0
* cflags : unknown
* CMAKE_BUILD_TYPE : unknown

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Fixes #8951

Although the file given in the issue is crippled we can avoid the crash.
In `dt_iop_clip_and_zoom_mosaic_half_size` and the sse friend there is possibly a div/0
problem that should be checked.

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
BTW for `dt_iop_clip_and_zoom_mosaic_half_size` and `dt_iop_clip_and_zoom_mosaic_half_size_f` -- should we keep the SSE2 code paths at all?

**Comment by TurboGit** [comment]
> BTW for `dt_iop_clip_and_zoom_mosaic_half_size` and `dt_iop_clip_and_zoom_mosaic_half_size_f` -- should we keep the SSE2 code paths at all?

I would say now as we have had many code having a perf very close to hand written sse code, and this makes maintenance by removing one code path. So you can remove and check if the loss for perf is acceptable.

**Comment by TurboGit** [comment]
> with consitant results. For all functions the sse specific code was somewhat slower (~20%)
> than the vectorized compiler code. Number of omp cores didn't matter, just made the results
> more measurable because of low execution times.

That's what I somehow expected. Today compilers are far smarter than us poor programmers and hand coded sse is often slower, harder to code, difficult to maintain and not ready for the next level of compiler optimizations. Good to see all this code removed. Thanks!

**Review by TurboGit — COMMENTED** [review]
Can we also remove the SSE specific #include in top of this file ?

**Comment by jenshannoschwalm** [comment]
> Can we also remove the SSE specific #include in top of this file ?

Yes i will fix it later today

**Comment by jenshannoschwalm** [comment]
Ready to merge.

**Comment by jenshannoschwalm** [comment]
Don't understand what is wrong with CI

**Review by TurboGit — APPROVED** [review]
Thanks !

**Pull request merged**
