### PR TITLE
Fix LDR image detection in HEIF loader (and add it to AVIF loader)

### PR DESCRIPTION
**Pull request by victoryforce**

### CODE REVIEW

**Comment by TurboGit** [comment]
@kmilos : A review for you, TIA.

**Review by kmilos — APPROVED** [review]
LGTM

**Comment by kmilos** [comment]
Actually, might be missing `loader = LOADER_AVIF;` now? (and same for HEIF)

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
