### PR TITLE
overlay colors: multi-colored icon

### PR DESCRIPTION
**Pull request by elstoc**
change the bottom-panel icon for overlay line colors so it's more colorful.

### CODE REVIEW

**Comment by elstoc** [comment]
@TurboGit as requested. I've tried a few color combinations and I'm not 100% happy with the aesthetics of any of them. This is the least worst!

**Comment by TurboGit** [comment]
Agreed a bit flashy, maybe with less opacity to have less aggressive colors like the RAW overexposed icon?

**Comment by elstoc** [comment]
It's also difficult finding four different colors that work well together without seeming lop-sided. Perhaps just two colors: one for the vertical lines and one for the horizontal. Red and green maybe?

**Comment by elstoc** [comment]
Another try. Why is this so hard?!

**Comment by TurboGit** [comment]
Seems like you failed pushing something :) Anyway, I tried it and put a 0.5 opacity, the colors are visible but less aggressive on the UI. Let's see what others think about this.

**Comment by elstoc** [comment]
I did. I forgot to add before I amended! I had just red and green:
Screenshot_2020-04-06_17-32-27

**Comment by TurboGit** [comment]
> I did. I forgot to add before I amended!

That's what I thought :) What do you think about the current version ?

**Comment by elstoc** [comment]
I edited my comment: it looks lop-sided because of the relative brightness of the colors. At first glance I only see the yellow and green lines.

**Comment by TurboGit** [comment]
Ok, can you do a PR with 2 colors ? If it does not look right we can just revert and go back to grey grid. Probably the best option...

**Pull request merged**
