### PR TITLE
Fix OpenMP for rgbe imageio loader

### LINKED ISSUE #15935: DT 4.6.0 - corrupted image with .hdr files
### Describe the bug

DT 4.6.0, self built on Windows 11, fully updated MSYS2.

Opening .hdr files produces corrupted central image in darkroom.
Resetting history doesn't help, as well as turning OpenCL on/off.
I have tried with several samples, it happens consistently for me.

immagine

For example, files taken from [here](https://filesamples.com/formats/hdr)

It used to be working in previous releases.

### Steps to reproduce

1. import the .hdr
2. open in darkroom

### Expected behavior

_No response_

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you obtain darktable from?

self compiled

### darktable version

4.6.0

### What OS are you using?

Windows

### What is the version of your OS?

Win11

### Describe your system?

_No response_

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

nVidia 1060

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Fixed OpenMP code
- use an aligned buffer for the rgbe loading
- use copy_pixel_nontemporal for performance
- performance measurably improved as we don't interfere with cachelines
- we ensure zero for alpha channel

Fixes #15935

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
Release note: Fixed RGBE image loader

**Comment by victoryforce** [comment]
Haven't taken the time to run tests to compare the speed of your code with mine yet, but I've verified it works. It also looks more "modern" anyway, and looks like it should be somewhat faster. So I'm closing my PR in favor of this.

**Comment by jenshannoschwalm** [comment]
> Haven't taken the time to run tests to compare the speed of your code with mine yet, but I've verified it works. It also looks more "modern" anyway, and looks like it should be somewhat faster. So I'm closing my PR in favor of this.

I tested perf while coding, here it is about 20% faster by using the copypixel stuff (though we are in the ms range :-)

More relevant could be the making sure we don't push NaNs into the pipe data. There were a number of AMD OpenCL specific issues fixed. I could never verify myself - not owning such a card, not intending to buy one and not interested in amd/kernel/driver hassles at all - but it seems that reading float4 data and processing them is sometimes a problem if one of the channels is a NaN, at least for some cards & drivers.

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Pull request merged**
