### PR TITLE
collect + tagging + metadata: use dt_ui_scroll_wrap() for widget resizing

### LINKED ISSUE #7120: Scroll issue in duplicate manager in darkroom
**Describe the bug**

We have a little issue in duplicate manager in darkroom on scrollbar.

**To Reproduce**

- create some clones to let appear a scrollbar in that module
- then scroll with mouse wheel by having the cursor over scrollbar. See that scrollbar doesn't stay where you want and come back to the top

To precise, scroll by having the cursor over the module and not scrollbar and scrollbar behavior is ok. I test in some other parts of darktable and seems that only duplicate manager have that issue. I tested with that PR and that issue is reproducible too, as in master.

**Platform (please complete the following information):**
 - Darktable Version: last master
 - OS:  Ubuntu 20.10 with Gnome 3.38.1

### PR DESCRIPTION
**Pull request by phweyland**
Collect + Tagging + Metadata: code factorisation as commented in #7138.

Fixes  #7120 (thanks to @dterrahe)

Fixes metadata collect regression

Diverse fixes about ellipsizing (@dterrahe) 

~~Plus some fixes  dt_ui_scroll_wrap():~~
~~- don't memorize out of range height~~
~~- don't resize below the minimum~~
~~- don't resize the plugins when mouse hovers thumbnails (for images with different set of information, tags, metadata, ...). I've moved the control with actual content height from redraw() to resize() to keep the author spirit, but my preference would be to remove this control letting the user choose the height he wants even bigger than the content.~~

### CODE REVIEW

**Comment by phweyland** [comment]
Apart metadata_view, the plugins which have implemented  dt_ui_scroll_wrap() are not sensitive to mouse thumbs hovering, which turns the automatic down resize more natural.

A solution may be to give the possibility to set a max size when calling dt_ui_scroll_wrap(), as it is coded in most places. If a max size is given it is used as the limit, otherwise the actual content height is used as currently.
Would that make sense ?
Would it be worth to do it now ?

**Comment by dterrahe** [comment]
As you mentioned in https://github.com/darktable-org/darktable/pull/7138#issuecomment-735940466 (and documented in #6408) the behavioral differences between for example how history and duplicates behave is different from how metadata and tagging behave. For this reason I did not blindly refactor everything to use dt_ui_scroll_wrap. The main purpose of #6408 was to allow the user the cap the maximum size of the history list so that it wouldn't eventually take up all space in the panel. It would be _bad_ if that meant that now it would _always_ take up the maximum allocated space.

If you extend dt_ui_scroll_wrap to support both use cases (and leave the darkroom modules as they are now or provide a good rationale why they are currently broken) then refactoring more definitely makes sense.

The only other thing to watch out for; the resizing is done dynamically based on content. I originally planned for this to be triggered by the "size-allocate" signal, i.e. once for each time the content changes, but this did not work. I'm not sure if this was caused by a bug in either gtk or dt or if it is the consequence of intended and necessary behaviour. Anyway, I had to use the "draw" signal instead, which gets called _much_ more frequently. So I'm a little worried that using the same approach for the 7 fields in the metadata editor might lead to slowdowns or flickering during mouse overs. But it might be OK if the size actually doesn't change depending on the content. Maybe you can even avoid connecting to the signal.

**Comment by phweyland** [comment]
@dterrahe thank you very much for your explanations and this piece of code where there is far more gtk knowledge than I have.
I had not seen the full context at the beginning and that's much clearer now. 

> It would be _bad_ if that meant that now it would _always_ take up the maximum allocated space.

Totally agreed. That's not the intention.

> if the size actually doesn't change depending on the content. Maybe you can even avoid connecting to the signal.

I've also thought about that. Thanks for confirming.

**Comment by phweyland** [comment]
@dterrahe I'm now able to have the previous behaviour for constant max and let the variable content size for darkroom plugins, except at init time, not getting the right value (-1) from dt_conf_get_int()... investigating.
A small question. There is the *cr parameter for _scroll_wrap_resize(), which is not used.  
Is it to be cleaned up ?

**Comment by dterrahe** [comment]
> @dterrahe I'm now able to have the previous behaviour for constant max and let the variable content size for darkroom plugins, except at init time, not getting the right value (-1) from dt_conf_get_int()... investigating.

Where are you expecting a -1? 

> A small question. There is the *cr parameter for _scroll_wrap_resize(), which is not used.
> Is it to be cleaned up ?

This is part of the signature of the "draw" signal callback so you'll get a crash (but no compile error) when you remove it.

**Comment by phweyland** [comment]
> Where are you expecting a -1?

No, I haven't understood that. I haven't reproduced the issue neither.
In fact it's too early to draw the widget properly at gui_init() time in metadata. The only solution I've found in the past is to use gui_post_expose().

So keeping the "draw" event even for constant max height solves the above issue.

> > Is it to be cleaned up ?
> 
> This is part of the signature of the "draw" signal callback so you'll get a crash (but no compile error) when you remove it.

Perfect.

**Comment by phweyland** [comment]
@dterrahe I'm good now for metadata and tagging. Normally I haven't changed the behaviour for the other cases, except the 2 first fixes mentioned at the beginning.

Would you be kind enough to review my changes (at least in gtk.c) ? Thanks in advance.

**Comment by dterrahe** [comment]
> In fact it's too early to draw the widget properly at gui_init() time in metadata. The only solution I've found in the past is to use gui_post_expose().

Ah, I now see what you are trying to do there with a temporary textview widget in gui_init. At that point the widgets haven't been realised yet (and therefore also haven't picked up any css settings) so that might be hard to get to work. Without "draw", you'd also not pick up any font changes a user could make in preferences. So options would be; have all respond to draw _or_ don't round metadata etc views to whole lines when increasing / decreasing size. If the "draw" solution works, without flickering, then that would be fine.

**Comment by phweyland** [comment]
> If the "draw" solution works, without flickering, then that would be fine.

On my side I have no flickering.



> don't round metadata etc views to whole lines when increasing / decreasing size

That's an idea, I can remove that in case of fixed max height.



> I'm good now for metadata

In fact, not exactly yet. the textview works but I've lost the labels ...

**Comment by dterrahe** [comment]
>  Normally I haven't changed the behaviour for the other cases, except the 2 first fixes mentioned at the beginning.

Ah, we may have had a miscommunication; those first two "fixes" were also intended behavior. With your changes, if I have a short history list (say 10 items) and I want to temporarily reduce the size, say to 5, and then I want to increase it to the maximum (so "never" show a scroll bar) I can't do it without adding history items, because I can't make the max bigger than the current list. So every time 1 item is added to the list, I have to/can increase the size by only 1.

Similarly, I can no longer reduce the size of image information and tags to very small. The "minimum" there was just intended to avoid an empty list to show as 1 row (with a lot of potential jumping between different sizes when mouse-overing). It _wasn't_ meant to prevent users from chosing a very small size if they explicitly want to. Because _why_? (see https://github.com/darktable-org/darktable/pull/6408#discussion_r499269048)

**Comment by phweyland** [comment]
> With your changes, if I have a short history list (say 10 items) and I want to temporarily reduce the size, say to 5, and then I want to increase it to the maximum (so "never" show a scroll bar) I can't do it without adding history items, because I can't make the max bigger than the current list. So every time 1 item is added to the list, I have to/can increase the size by only 1.

If I understand properly that's allow you to "jump" to full content size faster (one action, but you still need an action because the widget doesn't resize up automatically).
But, if you continue to scroll beyond the limit (low and high), you get the same effect the other way. To get back the scroll active you have to scroll all the way back. This is particularly painful when you scroll the wrong way (you don't know as you don't see any effect). I don't find this correct.
I think to cover properly the need (get back to full content height in one action) we would need a proper command: click on the mouse wheel ?


> It _wasn't_ meant to prevent users from chosing a very small size if they explicitly want to. Because _why_? (see [#6408 (comment)](https://github.com/darktable-org/darktable/pull/6408#discussion_r499269048))

Sorry, I haven't found the explanation for using min height as initial height. Maybe we should rename it "initial height" to make it clear ?

**Comment by dterrahe** [comment]
> If I understand properly that's allow you to "jump" to full content size faster (one action, but you still need an action because the widget doesn't resize up automatically).
> But, if you continue to scroll beyond the limit (low and high), you get the same effect the other way. To get back the scroll active you have to scroll all the way back. This is particularly painful when you scroll the wrong way (you don't know as you don't see any effect). I don't find this correct.

I don't disagree with you. It is, however, "logical". I experimented with this and found it more annoying that 1 single "smaller" scroll got me back all the way to where I started (if it immediately reduced to the currently used length) if I had just been scrolling "bigger" for a bit to make sure I hit the max.

So I completely understand you don't like/hate the result I eventually settled on. But don't assume that I didn't try you solution and found it even worse (for _my_ taste). I spent quite a bit too much time on this at the time. :-/

Maybe we could use a dt_toast_log to show that something is happening in the background? That could help discoverability. But it would probably need a new string, so too late for that for 3.4

Or otherwise I'll leave it to @TurboGit  to chose as an independent observer (because I'm definitely not one of those).

> I think to cover properly the need (get back to full content height in one action) we would need a proper command: click on the mouse wheel ?

That would work great, but how would you make it discoverable? Also, on my mouse, I can clearly feel each scroll "tick" so it is very easy to add room for, say, 3 more duplicates than the current number. Which option I would lose if I could only jump to "full content height".

> Sorry, I haven't found the explanation for using min height as initial height. Maybe we should rename it "initial height" to make it clear ?

It's not really "initial" height though. It is "minimum shown when maximum is greater than that". Or "don't shrink smaller if there are fewer items unless forced by a low max". I find it intuitive and useful in practice but somewhat inconvenient to describe. And I'd rather have it that way than the other way around ;-)

**Comment by phweyland** [comment]
OK, I see you have a long experience and this and I don't want to jeopardize the current darkroom behaviour.
The under/over scrolling is specifically linked to the dynamic usage of content_height.

However, content_height and under/over scrolling are not suitable for plugins which are sensitive to mouse hovering.

So I'll let the full current behaviour when max_height is not specified in  dt_ui_scroll_wrap().
When max_height is given, I'll mimic as far as I can the current behaviour plugins like metadata or tagging.

**Comment by phweyland** [comment]
@dterrahe thank you so much for your explanations and your patience.

@turbogit I think we are good now ;-)

**Comment by phweyland** [comment]
@dterrahe , sorry still thinking about....

For dt_ui_scroll_wrap() min_height represents the stable height below which the height stays stable whatever the content. Over this min_height the height follows content_height.
On the other hand the max_height I've introduced only provides a switch between two behaviours but is not useful in itself (as a maximum height, the hard coded 1000 pixels value should be enough).

So let's review if we could cover the needs with your code.

Stability.
Using the min_height property I can find a setup for metadata. It's enough to set min_height to 10 lines. The plugin starts with a single line per field (unfortunately with a scrollbar, maybe there is way to avoid this). But then if the user increases the height of some field to 5 lines for example, the metadata plugin remains stable whatever the actual metadata of the hovered images.
The plugin remains stable as long the user doesn't exceed 10 lines.

Initial height.
For tagging (or other plugins like collect) that would work the same way as metadata, except it has an initial height (even if no content) we cannot achieve, the actual minimum being one line. 
This would be a change but we could accept to start with one line. Only a new database will see the growing phase. An old database should already have a user defined height.
If we don't accept this, we need a way to define an initial height. 

What do you think ? Would you have an idea to setup an initial height ?

**Comment by dterrahe** [comment]
I'm not sure if this is what you mean, but you can set a default value by defining the settings in data/darktableconfig.xml.in (see #6408 for example)

**Comment by dterrahe** [comment]
I had forgotten that to properly support metadata etc _get_container_row_heigth needs to be able to determine the row height of a text view. I'm working on that now. Naturally, there is an obvious way to do this, but because gtk is too smart for it's own good, it doesn't always work correctly. So I'm trying to find a reliable approach.

**Comment by dterrahe** [comment]
I'm still seeing that problem with the labels disappearing in the metadata editor; does it work correctly for you? Need to figure out what is causing that. Maybe dt_ui_scroll_wrap needs to be rewritten a little more extensively to special-case textviews. Not what I planned on doing today, but hey!

**Comment by phweyland** [comment]
> I'm still seeing that problem with the labels disappearing in the metadata editor; does it work correctly for you? Need to figure out what is causing that. Maybe dt_ui_scroll_wrap needs to be rewritten a little more extensively to special-case textviews. Not what I planned on doing today, but hey!

It works for me:
image

When I had this issue, it was because I've changed _( ) to a local variable _(name) instead of _(dt_metadata_get_name_by_display_order(i)). I don't understand why it works in one case but not the other. 
However I don't think that  dt_ui_scroll_wrap() is guilty.

I've removed all my changes on your code and use  dt_ui_scroll_wrap() as is. I've solved the stability and initial size issues.
I don't get the exactly the same behaviour as before, I'm still a bit concerned about the blind scrolling, but I think it's better to use the same code and have the same behaviour everywhere.

Thanks again and sorry for the noise.

**Comment by phweyland** [comment]
> I had forgotten that to properly support metadata etc _get_container_row_heigth needs to be able to determine the row height of a text view.

I've removed the initial scrollbar of metadata textview setting a min of 15 in data/darktableconfig.xml.in.

**Comment by dterrahe** [comment]
I'm working on a better fix that supports different font sizes.

**Comment by dterrahe** [comment]
@phweyland I've sent you a pull request directly on the github branch underlying this PR. Fist time I've tried this, so let me know if it didn't work. The changes I made are:

This uses the line height of the text view to resize in steps of whole lines.

It also fixes the same functionality for treeviews that have multiple columns with non-identical heights. This was necessary for the tagging module.

I've added a (very!) simple toast (at top of screen) to show current max (in number of lines). So you can see it changing even if not directly affecting current size.

Also fixes darktable-org#7120

**Comment by phweyland** [comment]
Brilliant ! Thanks for the fixes in metadata.c. 
I didn't know the toast things. That's also excellent.

**Comment by phweyland** [comment]
But travis didn't like (i don't know if it linked to your changes..). Any idea ?

Err:25 https://dl.bintray.com/sbt/debian  Release
  504  Gateway Time-out [IP: 52.43.200.1 443]
Reading package lists...
E: The repository 'https://dl.bintray.com/sbt/debian  Release' no longer has a Release file.
Error: Process completed with exit code 100.

**Comment by phweyland** [comment]
I've got another issue> I should have checked more carefully.
I cannot hide the metadata I don't want to see anymore. I'll have to reverse the metadata fix I think.

**Comment by phweyland** [comment]
I've reverted the associated to gtk_widget_set_no_show_all() which still doesn't work (as commented :-)) keeping your other changes.

Travis still not happy for the same debian reason.

**Comment by dterrahe** [comment]
I hadn't realised/checked/remembered that the metadata selection could be changed on the fly; I thought it was only configured in darktablerc (once, at startup). You can change _update_layout as follows, and it works from gui_init (without needing gui_post_expose):
```
static void _update_layout(dt_lib_module_t *self)
{
  dt_lib_metadata_t *d = (dt_lib_metadata_t *)self->data;
  for(unsigned int i = 0; i < DT_METADATA_NUMBER; i++)
  {
    const gchar *name = dt_metadata_get_name_by_display_order(i);
    char *setting = dt_util_dstrcat(NULL, "plugins/lighttable/metadata/%s_flag", name);
    const gboolean hidden = dt_conf_get_int(setting) & DT_METADATA_FLAG_HIDDEN;
    const int type = dt_metadata_get_type_by_display_order(i);
    for(int j = 0; j < 2; j++)
    {
      GtkWidget *w = gtk_grid_get_child_at(d->metadata_grid,j,i);
      gtk_widget_show_all(w);
      gtk_widget_set_no_show_all(w, TRUE);
      gtk_widget_set_visible(w, (!hidden || type == DT_METADATA_TYPE_INTERNAL));
    }
    g_free(setting);
  }
}

```
However I'm getting a massive number of warnings and errors on the command line, coming from collect.c::metadata_changed
```
(darktable:244051): GLib-GObject-WARNING **: 18:24:27.237: invalid cast from 'DtBauhausWidget' to 'GtkComboBox'

(darktable:244051): Gtk-CRITICAL **: 18:24:34.910: gtk_combo_box_get_model: assertion 'GTK_IS_COMBO_BOX (combo_box)' failed

(darktable:244051): Gtk-CRITICAL **: 18:25:06.212: gtk_list_store_clear: assertion 'GTK_IS_LIST_STORE (list_store)' failed

etc etc etc
```

**Comment by phweyland** [comment]
> You can change _update_layout as follows, and it works from gui_init (without needing gui_post_expose):

I've made a quick try. At init time iut seems to work. but when I hide/show something it doesn't disappear/appear. I'll check again.



> However I'm getting a massive number of warnings and errors on the command line, coming from collect.c::metadata_changed

I've this even without your changes. I'll look at it. BTW, how do you see that's come form collect.c ?

**Comment by dterrahe** [comment]
> > You can change _update_layout as follows, and it works from gui_init (without needing gui_post_expose):
> 
> I've made a quick try. At init time iut seems to work. but when I hide/show something it doesn't disappear/appear. I'll check again.

works here (you put back the call to _update_layout in _config_button_clicked, right?)

> > However I'm getting a massive number of warnings and errors on the command line, coming from collect.c::metadata_changed
> 
> I've this even without your changes. I'll look at it. BTW, how do you see that's come form collect.c ?

Debugger :-) Yes, I know it wasn't introduced here, but it seems to be broken (did @TurboGit a while back maybe change the comboboxes in collect from ordinary gtk ones to bauhaus?)

**Comment by phweyland** [comment]
>  (you put back the call to _update_layout in _config_button_clicked, right?)

Thanks! better with that yes.

>  change the comboboxes in collect from ordinary gtk ones to bauhaus

Yes again. The messages have gone now, but I've still some issues. Working on it.

**Comment by dterrahe** [comment]
You might want to edit the init comment to this PR and put
`fixes #7120`
in there, so github will automatically close the issue when this gets merged (and let the reporter know his bug has been addressed)

**Comment by dterrahe** [comment]
One more PR to your personal repo with two separate additions; honoring "scroll panel" setting and converting the collect module.

It is funny to submit PR #4 and #5 :-)

**Comment by dterrahe** [comment]
Fixes for ellipsizing the content of lists in collect, styles and tagging so that a horizontal scrollbar is not required.

Also fixing broken ellipsizing for snapshots.

**Comment by phweyland** [comment]
Everything looks fine fro me now ! Ellipsizing on tagging is great.
Thanks @dterrahe

**Comment by phweyland** [comment]
@dterrahe Do you have any other comment or issue related to this ?
@TurboGit if dterrahe is ok, this PR is ready for review. Apart its title, it contains also some bug fixes.

**Comment by dterrahe** [comment]
> @dterrahe Do you have any other comment or issue related to this ?

Nope, I think its a solid improvement and I'm not experiencing any bugs myself.

The only thing I wish I could figure out is how to not have the scrolled_window capture scroll events when "mouse wheel scrolls modules side panel by default" is on. It works fine when there is no scroll bar, but when there is a scroll bar, the event gets captured and you can't scroll past the module (without moving the mouse outside the widget, I mean). Not a regression. Just something that irks me ;-)

**Comment by TurboGit** [comment]
@phweyland @dterrahe : given the amount of errors / tries I'm a bit uneasy to merge this for 3.4. The code is touching many files and the patch is not small... The question is can we live with current implementation until 3.4.1 ?

**Comment by dterrahe** [comment]
Sure, that's reasonable and fine by me. The fix for #7120 could be applied separately, but it is not a show stopper bug i think.

**Comment by phweyland** [comment]
From my side, I would find great to have this in 3.4 but this work as is. 
The regression on collect side for metadata is also not critical.
@dterrahe has made some improvements on the dt_ui_scroll_wrap(), but I let him comment them himself.

**Comment by TurboGit** [comment]
Ok, let's have this in 3.4.1 then, safer at this point.

**Comment by dterrahe** [comment]
Also fixes #7230

**Comment by dterrahe** [comment]
@phweyland did you mean to close this PR and delete the branch? This hasn't been merged yet.

**Comment by phweyland** [comment]
Sorry. My mistake.

**Comment by phweyland** [comment]
I've restored it, but seems to stay closed ... How do i reopen it ?

**Comment by TurboGit** [comment]
Some strange behaviors:
- the tags list can be resized a lot and the toast message is displayed ok 1, 2, ... 25. But at 5 it stops growing, that is we have a max of 5 lines.
-  the metadata entry are moving slightly between empty and with a word. It looks like a height of 1 is not high enough to display a word. This makes the entry dancing when flying over images with different information (with and without specific entry).

**Comment by phweyland** [comment]
Pascal, I'd deleted this branch from my local and remote repository (which has closed this PR) by mistake.
I've restored it on the remote repository and I can see it:
image
But my local git cannot find it (to checkout it again):
image

Is there a way to overcome this ? Thanks in advance!

**Comment by TurboGit** [comment]
As it is still on your remote you should get it back locally using:

`$ git fetch`

The branches you listed above are all from `origin/` is that you clone ? The main repo is `upstream` then ?

**Comment by phweyland** [comment]
???
`$ git fetch origin scroll-fix2` does work but
`$ git branch` doesn't show it,
`$ git checkout scroll-fix2` does work and
`$ git branch `shows it now

Looks strange to me but, great, I've got it again. Thanks Pascal !

**Comment by dterrahe** [comment]
> * the tags list can be resized a lot and the toast message is displayed ok 1, 2, ... 25. But at 5 it stops growing, that is we have a max of 5 lines.

Do you have 5 tags? Then this is intended behavior. ctrl-scroll sets the maximum size, but the list will not grow larger than necessary to show all content, unless there is a minimum specified in the dt_ui_scroll_wrap call (this can be useful to advertise that it is a multi-line field, if this is not otherwise obvious, and to avoid too much jumping when mouse-overing).

**Comment by phweyland** [comment]
>     * the tags list can be resized a lot and the toast message is displayed ok 1, 2, ... 25. But at 5 it stops growing, that is we have a max of 5 lines.

Not sure to understand correctly this.
Below the minimum (for tagging attached view this is 100 pixels) the windows remains stable whatever the number of items. Above it follows the number of items, limited by the number of lines you have reached in toast message. That's per @dterrahe design.
To avoid the dance flying over image I can increase the 100 pixels to 200 or 300 pixels.


>     * This makes the entry dancing when flying over images with different information (with and without specific entry).

I can also see this 1 pixel adjustment between an empty text and a one line text.
@dterrahe 
`  gtk_widget_get_preferred_height(w, NULL, &content_height);`
return 16 pixesl for an empty line, 17 for a line with something...

**Comment by phweyland** [comment]
@dterrahe , sorry, my mistake it is 
`  const gint increment = _get_container_row_heigth(w);`
which returns the above values.

**Comment by dterrahe** [comment]
> I can also see this 1 pixel adjustment between an empty text and a one line text.
> @dterrahe
> ` gtk_widget_get_preferred_height(w, NULL, &content_height);`
> returns 16 pixesl for an empty line, 17 for a line with something...

Yep. It used to be worse; previously I asked for the line height and assumed that a 1 line content would fit, but that always caused a vertical scrollbar. Now I'm getting the content height and dividing by the number of lines. No scrollbar, but still a difference between empty and 1 line. Thank Gtk for this behavior.

I'm experimenting now with better workarounds; give me a little time.

**Comment by dterrahe** [comment]
in gtk.c::_get_container_row_heigth, try this:
```
  else if(GTK_IS_TEXT_VIEW(w))
  {
    GtkTextIter iter = { 0 };
    gtk_text_view_get_iter_at_position(GTK_TEXT_VIEW(w), &iter, NULL, 0, 0);
    gtk_text_view_get_line_yrange (GTK_TEXT_VIEW(w), &iter, NULL, &height);
    if(!gtk_text_buffer_get_char_count(gtk_text_view_get_buffer(GTK_TEXT_VIEW(w)))) ++height;
  }
```
It seems to fix the problem for me in most cases, _but_ the 1 pixel adjustment is apparently font size dependent. On my system, it works fine <12 points _AND_ >15 points, but in between, there is still a 1 pixel jump up down. This makes no sense to me.

I'm going to experiment with temporarily putting 1 character into the buffer before measuring its height, but I don't know if it immediately resizes. Otherwise, always putting in a space in the box should work, but of course it would have to be stripped out when reading the box and it would confuse the user. Maybe setting a GtkTextTag with and “editable” property of FALSE for that one space would work, but now we are talking bandaid on top of bandaid...

**Comment by dterrahe** [comment]
Temporarily adding a space before measuring the height leads to multiple refreshes, which on my system leads to clearly visible up and down jumping, so that's a no go.

Maybe we could measure the adjustment needed between empty/non-empty textviews once and reuse it (and recalibrate it after a font change). For 1 pixel! Pfff...

**Comment by TurboGit** [comment]
> Do you have 5 tags?

No 3 tags only. But I think this should not be based on the number of tags as it is a global setting.

**Comment by dterrahe** [comment]
This works for all font sizes:
```
  else if(GTK_IS_TEXT_VIEW(w))
  {
    PangoLayout *layout = gtk_widget_create_pango_layout(w, "X");
    pango_layout_get_pixel_size(layout, NULL, &height);
    g_object_unref(layout);
  }
```

> > Do you have 5 tags?
> 
> No 3 tags only. But I think this should not be based on the number of tags as it is a global setting.

For tags, the minimum height is 100 pixels (5 lines in your font), _unless_ you set the maximum smaller than that. If you set the maximum higher (using ctrl-scroll) then the box can expand _if needed_ (i.e. if you have more than 5 tags) but it won't use that space permanently.

**Comment by phweyland** [comment]
> It seems to fix the problem for me in most cases, _but_ the 1 pixel adjustment is apparently font size dependent. On my system, it works fine <12 points _AND_ >15 points, but in between, there is still a 1 pixel jump up down. This makes no sense to me.

I can see the same effect.

**Comment by TurboGit** [comment]
> For tags, the minimum height is 100 pixels (5 lines in your font), _unless_ you set the maximum smaller than that. If you set the maximum higher (using ctrl-scroll) then the box can expand _if needed_ (i.e. if you have more than 5 tags) but it won't use that space permanently.

I see, a feature not a bug :) I'll keep that in mind when I'll do a second pass for testing. Thanks.

**Comment by phweyland** [comment]
> This works for all font sizes:
> 
> ```
>   else if(GTK_IS_TEXT_VIEW(w))
>   {
>     PangoLayout *layout = gtk_widget_create_pango_layout(w, "X");
>     pango_layout_get_pixel_size(layout, NULL, &height);
>     g_object_unref(layout);
>   }
> ```
Yes !

In my code I had:
`height /= PANGO_SCALE;`
Do think that is necessary ?

**Comment by dterrahe** [comment]
> Do think that is necessary ?

No; this is a result in pixels that will be used later to set a size in pixels.

**Comment by dterrahe** [comment]
> I see, a feature not a bug :) I'll keep that in mind when I'll do a second pass for testing. Thanks.

Indeed! ;-)

The behavior is a change from how how it worked previously (see here https://github.com/darktable-org/darktable/pull/7140#issuecomment-736307346). Imho it is _better_ but of course you are free to disagree...

**Comment by phweyland** [comment]
@dterrahe , I've inserted your piece of code.  It works for me (lines are bit less high but stable). 
I've also increase to 200 the min height of the tags attached view to keep it stable with more tags.

**Comment by dterrahe** [comment]
> lines are bit less high

I don't see that here; it should only affect empty fields. Otherwise you would see partial lines; the whole point is to round the size of the scrolled window to a whole number of lines. If that (no longer) works for you, please post a screenshot.

> I've also increase to 200 the min height of the tags attached view

That's fine by me. I normally don't have more than 2-3 tags attached, so I'll use ctrl-scroll to force a smaller size.

**Comment by phweyland** [comment]
> > lines are bit less high
> 
> I don't see that here; it should only affect empty fields.
With the change (pango layout) increment is 15 while it was 16 or 17 before (on my screen).

**Comment by dterrahe** [comment]
> > > lines are bit less high
> > 
> > 
> > I don't see that here; it should only affect empty fields.
> 
> With the change (pango layout) increment is 15 while it was 16 or 17 before (on my screen).

So if you enter a large number of lines and you reduce the size of the box to show only one line, does scrolling all the way down each time show one whole line or does it gradually show in-between lines?

**Comment by phweyland** [comment]
> So if you enter a large number of lines and you reduce the size of the box to show only one line, does scrolling all the way down each time show one whole line or does it gradually show in-between lines?

One whole line. And the number of visible lines fits with the toast number.

**Comment by phweyland** [comment]
@Turbogit, if @dterrahe is ok this PR is ready for your review.

**Comment by dterrahe** [comment]
> @TurboGit, if @dterrahe is ok this PR is ready for your review.

Last time I looked I didn't see any problems, so yes please go ahead.

**Comment by TurboGit** [comment]
Merged into master queued for 3.4.1.

**Pull request merged**
