### PR TITLE
fixes compiling with exiv v0.27.2.1

### PR DESCRIPTION
**Pull request by codingdave**
fixes compilation issues:
```/home/dave/workspace/darktable.git/src/common/exif.cc: In function ‘GHashTable* read_masks(Exiv2::XmpData&, const char*, int)’:
/home/dave/workspace/darktable.git/src/common/exif.cc:2039:12: error: comparison of integer expressions of different signedness: ‘const int’ and ‘size_t’ {aka ‘long unsigned int’} [-Werror=sign-compare]
     if(cnt == mask_src->count() && cnt == mask_name->count() && cnt == mask_type->count()
        ~~~~^~~~~~~~~~~~~~~~~~~~
/home/dave/workspace/darktable.git/src/common/exif.cc:2039:40: error: comparison of integer expressions of different signedness: ‘const int’ and ‘size_t’ {aka ‘long unsigned int’} [-Werror=sign-compare]
     if(cnt == mask_src->count() && cnt == mask_name->count() && cnt == mask_type->count()
                                    ~~~~^~~~~~~~~~~~~~~~~~~~~
/home/dave/workspace/darktable.git/src/common/exif.cc:2039:69: error: comparison of integer expressions of different signedness: ‘const int’ and ‘size_t’ {aka ‘long unsigned int’} [-Werror=sign-compare]
     if(cnt == mask_src->count() && cnt == mask_name->count() && cnt == mask_type->count()
                                                                 ~~~~^~~~~~~~~~~~~~~~~~~~~
/home/dave/workspace/darktable.git/src/common/exif.cc:2040:14: error: comparison of integer expressions of different signedness: ‘const int’ and ‘size_t’ {aka ‘long unsigned int’} [-Werror=sign-compare]
       && cnt == mask_version->count() && cnt == mask_id->count() && cnt == mask_nb->count())
          ~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/home/dave/workspace/darktable.git/src/common/exif.cc:2040:46: error: comparison of integer expressions of different signedness: ‘const int’ and ‘size_t’ {aka ‘long unsigned int’} [-Werror=sign-compare]
       && cnt == mask_version->count() && cnt == mask_id->count() && cnt == mask_nb->count())
                                          ~~~~^~~~~~~~~~~~~~~~~~~
/home/dave/workspace/darktable.git/src/common/exif.cc:2040:73: error: comparison of integer expressions of different signedness: ‘const int’ and ‘size_t’ {aka ‘long unsigned int’} [-Werror=sign-compare]
       && cnt == mask_version->count() && cnt == mask_id->count() && cnt == mask_nb->count())
                                                                     ~~~~^~~~~~~~~~~~~~~~~~~
```

### CODE REVIEW

**Comment by TurboGit** [comment]
But this breaks compilation with GCC 8, this is was is reported by Travis:

```
/build/darktable/src/common/exif.cc: In function ‘GHashTable* read_masks(Exiv2::XmpData&, const char*, int)’:
/build/darktable/src/common/exif.cc:2039:12: error: comparison of integer expressions of different signedness: ‘const size_t’ {aka ‘const long unsigned int’} and ‘long int’ [-Werror=sign-compare]
     if(cnt == mask_src->count() && cnt == mask_name->count() && cnt == mask_type->count()
        ~~~~^~~~~~~~~~~~~~~~~~~~
/build/darktable/src/common/exif.cc:2039:40: error: comparison of integer expressions of different signedness: ‘const size_t’ {aka ‘const long unsigned int’} and ‘long int’ [-Werror=sign-compare]
     if(cnt == mask_src->count() && cnt == mask_name->count() && cnt == mask_type->count()
                                    ~~~~^~~~~~~~~~~~~~~~~~~~~
/build/darktable/src/common/exif.cc:2039:69: error: comparison of integer expressions of different signedness: ‘const size_t’ {aka ‘const long unsigned int’} and ‘long int’ [-Werror=sign-compare]
     if(cnt == mask_src->count() && cnt == mask_name->count() && cnt == mask_type->count()
                                                                 ~~~~^~~~~~~~~~~~~~~~~~~~~
/build/darktable/src/common/exif.cc:2040:14: error: comparison of integer expressions of different signedness: ‘const size_t’ {aka ‘const long unsigned int’} and ‘long int’ [-Werror=sign-compare]
       && cnt == mask_version->count() && cnt == mask_id->count() && cnt == mask_nb->count())
          ~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/build/darktable/src/common/exif.cc:2040:46: error: comparison of integer expressions of different signedness: ‘const size_t’ {aka ‘const long unsigned int’} and ‘long int’ [-Werror=sign-compare]
       && cnt == mask_version->count() && cnt == mask_id->count() && cnt == mask_nb->count())
                                          ~~~~^~~~~~~~~~~~~~~~~~~
/build/darktable/src/common/exif.cc:2040:73: error: comparison of integer expressions of different signedness: ‘const size_t’ {aka ‘const long unsigned int’} and ‘long int’ [-Werror=sign-compare]
       && cnt == mask_version->count() && cnt == mask_id->count() && cnt == mask_nb->count())
                                                                     ~~~~^~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

**Comment by codingdave** [comment]
For me it doesn't seem to be the compiler but the exiv version. However, I looked into their code and couldn't find the change.

**Comment by TurboGit** [comment]
> For me it doesn't seem to be the compiler but the exiv version. However, I looked into their code and couldn't find the change.

I was referring to the travis builds, it is ok with CLang but not with GCC. See report by yourself.

**Comment by cryptomilk** [comment]
It's ugly but I think you have to cast `mask_src->count()` to `size_t` to fix the build with older versions of exiv2 ...

**Comment by codingdave** [comment]
I guess, yes. 
I have been following the interface change. 
exiv2 v0.26:
```
370af5c8a src/xmp.hpp           (Andreas Huggel 2009-11-27 05:59:23 +0000 149)         long typeSize() const;
ac314ddfb src/xmp.hpp           (Andreas Huggel 2007-09-16 09:30:30 +0000 150)         long count() const;
ac314ddfb src/xmp.hpp           (Andreas Huggel 2007-09-16 09:30:30 +0000 151)         long size() const;
```
v.27.2.1:
```
c72d16f4c include/exiv2/xmp_exiv2.hpp (Luis Díaz Más  2019-05-18 14:33:46 +0200 140)         size_t typeSize() const override;
c72d16f4c include/exiv2/xmp_exiv2.hpp (Luis Díaz Más  2019-05-18 14:33:46 +0200 141)         size_t count() const override;
c72d16f4c include/exiv2/xmp_exiv2.hpp (Luis Díaz Más  2019-05-18 14:33:46 +0200 142)         size_t size() const override;
```
The api has been changed recently as you see and is currently only on master. 
It looks like this change will get into the new release: https://github.com/Exiv2/exiv2/pull/819

**Comment by codingdave** [comment]
Hi @TurboGit, I have made forward and backward compatible changes. The code now casts the (old api) long to (next api) size_t, as suggested by @cryptomilk. Is there anything else I should do?

Kind regards
Dave

**Comment by TurboGit** [comment]
Looks ok now. It compiles with current GCC 8 and support exiv, so all good. I can't test if ok with exiv 0.27 but I trust you. Thanks.

**Pull request merged**
