### PR TITLE
po/fix path mask

### PR DESCRIPTION
**Pull request by TurboGit**
Multiple fixes:
- avoid jump of the source area when moving a node
- avoid jump of the source area when moving a segment
- fix source/target alignment issue

### CODE REVIEW

**Comment by TurboGit** [comment]
Can be tested, but I still have a little jump of the source when dragging it.

**Comment by elstoc** [comment]
> moving the "first" point of the target shape around throw the source shape away from the image...

I've noticed issues like this on master (moving a point on the target shape caused odd rotation or movement of the source shape) but couldn't find a consistent reproducer.

**Comment by TurboGit** [comment]
@AlicVB : The landscape issue was a stupid mistake not related for transform. Anyway should be fixed. I still have this shift of the source when moving which is proportional to the size of the feather and introduce by my fix for the alignment. So there is probably some mixing with corner/ctrl somewhere else...

**Comment by AlicVB** [comment]
@TurboGit : you was right, I've just found it : in path.c line 1322-1323 :)

**Comment by elstoc** [comment]
Sure I'll test later or perhaps tomorrow.

**Review by elstoc — APPROVED** [review]
Looks great to me. I tried to break it and I couldn't.

**Comment by TurboGit** [comment]
Good new that you didn't find a way to break it. Let's merge this, thanks!

**Pull request merged**
