### PR TITLE
Database version 32: add foreign keys

### PR DESCRIPTION
**Pull request by HansBull**
Opening a new, more clear PR instead of the old one. Adds foreign keys to tables that reference `images` for more data consistency- dtabase dependencies should be handled by database. Fixes cases like the recent #7781 .

### CODE REVIEW

**Comment by johnny-bit** [comment]
I think that also properly wrapping the deletions in transactions (and reverting them in case of fails) would have positive impact on database :)

**Comment by parafin** [comment]
What will happen if there are some inconsistencies in existing user database?

**Comment by HansBull** [comment]
Cases of invalid `group_id` like in #7781 are fixed with `UPDATE `images_old` SET group_id=id WHERE group_id NOT IN (SELECT id from `images_old`)` - with `images_old` being the temporary table we need for the recreation of `images` - so that the images remain and are given at least a group id referencing pointing to themselves. To avoid these cases in the future a `FOREIGN KEY(group_id) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE` is added.

Orphaned entries in the other tables like `history` referencing images that do not exist any more in the database are deleted. This can be done, as referenced non-existing images will not come back due to the primary key of `images` being autoincrement.

**Comment by chhil** [comment]
Any impact on generate cache command line?

**Comment by HansBull** [comment]
Should not affect generate cache command.

**Comment by johnny-bit** [comment]
You shouldn't have updated the rawspeed module ;) and the title requires version 33, doesn't it? :P

**Comment by HansBull** [comment]
Yes. All my fault. git learning curve is too steep: giving up.

**Pull request closed without merging**
