### PR TITLE
smooth scrolling for touchpads

### PR DESCRIPTION
**Pull request by emeikei**
I added an option for this as some systems can apparently have issues with this.

### CODE REVIEW

**Comment by TurboGit** [comment]
Looks good. One question you said it can causes issues but it is activated by default. What is the percentage of issues? If probable maybe it is better to have it deactivated by default. I even think it is safer to have it deactivated and let user test and report about this before activating it by default. What do you think?

**Comment by emeikei** [comment]
I don't know what the 'issues' are or if they're still relevant.  There's just a brief comment in the existing code. The issues question was raised in the forum but nobody responded.
My thinking is that by having it enabled by default, we stand more chance of finding out if these issues are still relevant.  And if nobody reports any issues then maybe we can eventually remove the option and just leave it enabled.

**Comment by homer3018** [comment]
If needed I could give it a try using my wacom tablet. If it works nicely it'b great !

**Comment by TurboGit** [comment]
@homer3018 : your wacom tablet has a touchpad or something similar? If so, yes please test and report. Thanks.

**Comment by homer3018** [comment]
@TurboGit yes, it is basically a giant touch pad which supports multi touch gestures also (zoom with 2 fingers, etc.) 
I'll see if I have the chance tonight, but yes I'll test anyway and report.

**Comment by TurboGit** [comment]
Any news on the test?

**Comment by homer3018** [comment]
Sorry, I have had forgot about this one.
Just tested it, and I do not see any difference in the lighttable with the option set to ON (default) or OFF. I'm unsure whether or not this is coming from my setup (say maybe the Wacom tablet is not recognised as a smooth scrolling capable device ?) or something else.

In the darktable however, both the side panels can be scrolled quite smoothly, and I'm seeing this regardless of the option state...

Is there a location where I am supposed to see a difference with the option ON and OFF ? If so could you please let me know where ?

**Comment by homer3018** [comment]
Interesting. I've switched back to 2.7.0+1247~g277c7aa7d which was the one I was using recently, and the scrolling (both side panels in the darkroom) do not scroll as smoothly as they did with yours. I do like the smooth scrolling :)

**Comment by m93a** [comment]
How exactly is this supposed work? I installed the latest commit (`2.7.0~git1468.f762741f8`) and smooth scrolling still doesn't work for me in Lightroom. And I don't see any new options under GUI. I'm on Acer A315 (with quad-touch touchpad) runnning Ubuntu 18.04.

**Comment by TurboGit** [comment]
Lost momentum. We'll reopen if needed.

**Pull request closed without merging**
