### PR TITLE
Update contextual help

### PR DESCRIPTION
**Pull request by rawfiner**
This pull request adds some links for the contextual help, adds anchors to some links, and makes the code more robust.
In particular, if the system language is not detected and the language is not set, there is no segmentation fault anymore, as well as if the code is compiled without l10n support.
I tested the code both on linux mint 18 and inside a docker based on fedora.

### CODE REVIEW

**Comment by rawfiner** [comment]
I thought it was ready, but it seems it is not ready yet. Closing the PR for the moment, and I will fix everything and reopen it later.

**Comment by rawfiner** [comment]
The problem with usermanual should be fixed by commit 76a8216.

**Comment by rawfiner** [comment]
By the way, issue https://redmine.darktable.org/issues/8660 should be closed

**Comment by TurboGit** [comment]
Thanks!

**Pull request merged**
