### PR TITLE
Fixes encoding issue on Windows when pathes contain non-ASCII symbols

### LINKED ISSUE #7489: dt 3.4 Windows 10 translation error with special characters
Hello

In darktable 3.4 for Windows I found that if I have a special character in the path leading to the configdirectory the character is not translated correctly. This causes darktable to terminate. The log file can look like this:

========================================
version: darktable 3.4.0
start: 2020:12:25 09:42:49

darktable.configdir: directory ‘C:\Users\B├Ârje\AppData\Local\darktable’ fails to open.’

=====================================================================

The directory after Users should read Börje. This is something that worked fine in dt 3.2 but with 3.3 this failed. 
The chachdirectory is also affected by this problem.

### PR DESCRIPTION
**Pull request by codingdave**
Fixes #7489

This PR shall fix the windows issue some users have. I can reproduce the reported issue #7489 on a windows (10) machine by calling

    "C:\Program Files\darktable\bin\darktable.exe" -d dev --configdir "c:\tmp\Söme Üsär" --cachedir "c:\tmp\Söme Üsär"

and I also can confirm that the issue is fixed with this change. 

Basically this PR instead of calling the ANSI version `GetFileAttributesA`  calls the wide-character version `GetFileAttributesW` and we receive the input in `wchar_t` by converting the UTF-8 encoded darktable strings (back) to the UTF-16 encoded Windows strings.

### CODE REVIEW

**Comment by codingdave** [comment]
Actually also helpful is to know where the logs are created:

    C:\Users\<put your username here>\AppData\Local\Microsoft\Windows\INetCache\darktable\darktable-log.txt

**Comment by TurboGit** [comment]
Please use a meaningful message in the PR. Only "Fix 7489" is hardly useful.

**Comment by johnny-bit** [comment]
If you'd also add "Fixes #7489" in content of opening comment It'd be great :) same for #7722 :)

Looking at changes it should indeed fix the problem.

**Comment by codingdave** [comment]
> If you'd also add "Fixes #7489" in content of opening comment It'd be great :) same for #7722 :)

Well, it is there but it could be more easy to understand. I give you that. Happy now? :-)

**Comment by TurboGit** [comment]
Thanks.

**Pull request merged**
