### PR TITLE
Make sure masks are saved even if the module is not enabled.

### LINKED ISSUE #8528: Switching module with applied mask off then on discards the mask
Cheking what module did not with snapshot but with switching the module off/on makes the mask ineffective. While it's still there it is not effectively applied. I can see it at least with the second module instance.

**To Reproduce**
1. Create second instance of Exposure module.
2. Create drawn mask (didn't check but suppose that the parametric mask is also appropriate)
3. Change the exposure (the image is changed according to the mask)
4. Switch this instance off (returning to previous look)
5. Switch the instance on again (exposure compensation is applied to whole image while the mask is technically in place but ineffective)

**Expected behavior**
On/off doesn't discard mask usage

* darktable version : 3.4.1
* OS                : linux 5.9.0-pf7
* Linux - Distro    : Gentoo

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support disabled
  ImageMagick support disabled
  OpenEXR support enabled

### PR DESCRIPTION
**Pull request by TurboGit**
Fixes #8528.

### CODE REVIEW

**Comment by TurboGit** [comment]
@Mark-64 : Can you test this ? TIA.

**Comment by TurboGit** [comment]
One of the more difficult issue I had to deal with !

**Comment by TurboGit** [comment]
I have just pushed a simpler version, easier to understand and still working.

**Comment by Mark-64** [comment]
Tested and working on my side!
Thank you, I would never be able to fix this one.

**Comment by TurboGit** [comment]
@Mark-64 : Thanks for testing, I'm merging that now, better sooner than later to ensure some filed testing before the release. I have not found a side effect, but we never know!

**Pull request merged**
