### PR TITLE
Avoid multiple guides drawing

### LINKED ISSUE #16056: 4.6.x: double gridlines after commit b3f0d57 while cropping
### Describe the bug

the bugfix for Fixes https://github.com/darktable-org/darktable/issues/15984 done with https://github.com/darktable-org/darktable/pull/15990 causes double gridlines (whole image + cropped area) during cropping
image

### Steps to reproduce

perform crop with 4.6.x

### Expected behavior

_No response_

### Logfile | Screenshot | Screencast

_No response_

### Commit

b3f0d57

### Where did you obtain darktable from?

self compiled

### darktable version

darktable 4.6.0+67~gbe30012e10-dirty

### What OS are you using?

Mac

### What is the version of your OS?

MacOS 14

### Describe your system?

_No response_

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Make sure in darkroom expose that guides are drawn only once.

Fixes #16056 

@MStraeten and @elstoc could you check in depth?

### CODE REVIEW

**Comment by elstoc** [comment]
Looks good to me

**Comment by AxelG-DE** [comment]
I did a quick test and the double grid is gone

not introduced by this (I think I saw it before), but my dotted grid lines now have a dark gray line underneath, which IIRC wasn't like this before (sorry for mixing things):
Screenshot_20240107_211038

**Comment by TurboGit** [comment]
Merged in master and 4.6.x branch.

**Comment by jenshannoschwalm** [comment]
Release note for 4.6 and 4.8

Fix double drawing of guide lines

**Comment by elstoc** [comment]
Release notes not needed as this is not an issue in 4.6

**Pull request merged**
