### PR TITLE
image infos : fix case where only one image from a selection is shown

### LINKED ISSUE #9084: image information does not show "<various values>" in culling fixed mode when selecting multiple pictures
**Describe the bug/issue**
When multiple pictures are selected that diverge in some image information (such as different exposure, focal length, ...) darktable will display "various values" in that field. This does not work for culling fixed mode. Here, only "image id" is replaced by "various values". Every other field displays information of the last picture that has been selected

**To Reproduce**
1. Enter culling (fixed) mode with a selection of images or select pictures after entering the mode.
2. Check out the image information.

**Screenshots**

Culling fixed
image

Culling dynamic and other modes
image

**Platform**

* darktable version : 3.5.0+2370~gd06912666
* OS                : Manjaro Linux

### PR DESCRIPTION
**Pull request by AlicVB**
this fix #9084 

@TurboGit : I have a big doubt about `gchar *const images = dt_view_get_images_to_act_on_query(FALSE);` does this strange syntax avoid the need to free `images` ???
if not, I need to declare it with a "normal" syntax and free it once used...

### CODE REVIEW

**Comment by ralfbrown** [comment]
`gchar *const` is an unchanging pointer to changeable data, while `const gchar *` would be a changeable pointer to unmodifiable data (which thus could not be freed).  I checked, and the return value from `dt_view_get_images_to_act_on_query` is newly allocated and needs to be freed.

**Comment by TurboGit** [comment]
@AlicVB : the answer was given by @ralfbrown, thanks !

**Comment by AlicVB** [comment]
done...
so this PR also fix a mem leak :)

**Review by TurboGit — APPROVED** [review]
Works for me, thanks !

**Comment by ralfbrown** [comment]
> so this PR also fix a mem leak :)

There are so many to choose from :(
I just posted a PR that fixes another 18 or so....
Fortunately the leaks in dt are all relatively small and infrequent; I once had one in an inner-most loop that burned through about a gigabyte per second :blush: even though each allocation was only a few KB.

**Pull request merged**
