### PR TITLE
po/copy part wb

### PR DESCRIPTION
**Pull request by TurboGit**
As reported by Aurélien, when in scene-referred mode it is not OK to skip the temperature in copy all as this module is working
together with the Color Calibration one.

So we copy temperature (or select it by default in the copy-parts dialog):
- if temperature is active
- and if color calibration if found in history
- and if in scene-referred mode

This makes the copy actually safer.

### CODE REVIEW

**Comment by Nilvus** [comment]
> * if temperature is active
> 
> * and if color calibration if found in history
> 
> * and if in scene-referred mode

I think first 2 here are sufficient. I don't set any mode in main preferences, I prefer to  use only presets. So with that PR, I will still have the actual problem. And as wb module needed to be set and active with D65 setting when color calibration white balance mode is set, this will be safe even if none of scene/display referred mode are set.

I would so replace "if in scene-referred mode" by "not in display-referred mode" or if none of those mode are selected AND color calibration module is set to modern setting in main preferences like are my settings below:

image

**Comment by parafin** [comment]
If one has modern chromatic adaptation enabled, why do you need copying the wb module, wouldn’t it be already enabled and set accordingly? What is the actual use-case this PR is trying to fix? Because all the arguments why wb shouldn’t be copied remain with modern chromatic adaptation - D65 presets differ between cameras.

**Comment by TurboGit** [comment]
> I would so replace "if in scene-referred mode" by "not in display-referred mode" or if none of those mode are selected AND color calibration module is set to modern setting in main preferences like are my settings below:

Thanks, indeed my current implementation is not good. But in fact all this has nothing to do with the scene vs display referred mode but only with the chromatic adaptation default (modern vs legacy). The scene-referred only deal with Filmic & Exposition by default instead of base curve.

I'll fix this.

**Comment by TurboGit** [comment]
@parafin : If you have color calibration and temperature you want to copy both because they are working together. There is chance that the temperature is set to "camera neutral" or if not then you probably know what you are doing. Not doing that means that you copy only CC and if the target picture has WB not set in "camera neutral" it completely mess the edit.

This has been reported by Aurélien on a French channel.

**Comment by TurboGit** [comment]
@Nilvus : The copy is now done based on chromatic-adaptation mode. So we have:

- if temperature is active
- and if color calibration if found in history
- and if in chromatic-adaptation mode is modern

**Comment by parafin** [comment]
> @parafin : If you have color calibration and temperature you want to copy both because they are working together. There is chance that the temperature is set to "camera neutral" or if not then you probably know what you are doing. Not doing that means that you copy only CC and if the target picture has WB not set in "camera neutral" it completely mess the edit.
> 
> This has been reported by Aurélien on a French channel.

IMHO instead of this complex logic of when to copy wb iop it would make more sense to just copy wb always. wb isn't included in copy-paste by default because you can't copy these params between cameras, and it's the same issue regardless of modern or legacy chromatic adaptation mode. So why it's OK to break copy-paste between cameras for modern chromatic adaptation and not for legacy?
Alternatively just drop this PR, because having WB not set to "camera neutral" when you have modern chromatic adaptation is a corner case IMHO.

**Comment by Nilvus** [comment]
> IMHO instead of this complex logic of when to copy wb iop it would make more sense to just copy wb always. wb isn't included in copy-paste by default because you can't copy these params between cameras, and it's the same issue regardless of modern or legacy chromatic adaptation mode. So why it's OK to break copy-paste between cameras for modern chromatic adaptation and not for legacy? Alternatively just drop this PR, because having WB not set to "camera neutral" when you have modern chromatic adaptation is a corner case IMHO.

So if the problem is between camera, then always so copy/paste wb for legacy workflow IF the camera is the same (it's possible to do as we have EXIF settings I think).

Conditions of this PR are needed even if the camera is not the same, as WB doesn't change for modern workflow. It's always D65 default setting and WB is really finally done with CAT module.

**Comment by parafin** [comment]
> Conditions of this PR are needed even if the camera is not the same, as WB doesn't change for modern workflow. It's always D65 default setting and WB is really finally done with CAT module.

If WB is always D65, why it’s needed to copy it? I really see only one case - if you’re copying to an old image with legacy chromatic adaptation. But in this case IMHO it’s better to reset history stack first anyway. As I said before I don’t really understand the use-case. Can someone describe a viable scenario how the problem this PR is trying to fix occurs?

**Comment by aurelienpierre** [comment]
Copy-pasting editing histories is relevant within the same series of pictures taken under the same lighting conditions. If the conditions have changed, one cannot expect that copy-pasting settings will yield the same results, and therefore it makes no sense to copy the whole stack. 

For sharing looks between different cameras, the best way is by using styles or doing a partial copy-pasting, meaning extra manual care.

Right now, the fact that WB is not copied by default makes the quick copy-pasting basically useless, since you always have to check manually WB in the pasting list.

Also, copying with "overwrite" mode has an undefined behaviour if WB is not selected. It can default to personal preset, workflow preset, or as read in camera, you don't know.


> If WB is always D65, why it’s needed to copy it?

Because WB D65 is not D65. You need to use a personal preset and auto-apply it if you want an actual D65. But personal presets are inited later, after the pipe is inited, so they don't get inited at all if the history is already initialised from a copy-pasting.

**Comment by aurelienpierre** [comment]
Actually, the color calibration settings depend on the WB and input profile settings, so whatever is done, these 3 need to be either copied or not but anyway, they need to be as a pack.

**Comment by parafin** [comment]
> Copy-pasting editing histories is relevant within the same series of pictures taken under the same lighting conditions. If the conditions have changed, one cannot expect that copy-pasting settings will yield the same results, and therefore it makes no sense to copy the whole stack.
> 
> For sharing looks between different cameras, the best way is by using styles or doing a partial copy-pasting, meaning extra manual care.
> 
> Right now, the fact that WB is not copied by default makes the quick copy-pasting basically useless, since you always have to check manually WB in the pasting list.

This an argument for always copying, regardless of chromatic adaptation mode.

> 
> Also, copying with "overwrite" mode has an undefined behaviour if WB is not selected. It can default to personal preset, workflow preset, or as read in camera, you don't know.

This sounds like a separate bug.

> 
> > If WB is always D65, why it’s needed to copy it?
> 
> Because WB D65 is not D65. You need to use a personal preset and auto-apply it if you want an actual D65. But personal presets are inited later, after the pipe is inited, so they don't get inited at all if the history is already initialised from a copy-pasting.
> 
> The consequence is color calibration settings rely on some initial WB settings that are not passed through the copy-pasting process, so the color calibration settings are basically always wrong when copy-pasting.

Maybe always for you, but not in general, especially for new users who would use default camera neutral wb. Let’s have show of hands who have custom D65 WB presets here?

**Comment by Nilvus** [comment]
> Maybe always for you, but not in general, especially for new users who would use default camera neutral wb. Let’s have show of hands who have custom D65 WB presets here?

I'm wondering if there's some misunderstanding here. When talking about D65, it was just a "shortcut" for me to talk about neutral one, which is (as tooltip said) D65 one. So to be sure we talk on same thing about WB module, I talk about that preset (and yes, sometimes it's to update an old workflow with copy/paste ; and it's better when there's just some modules only to use copy/paste and reset history):

image

**Comment by aurelienpierre** [comment]
> Maybe always for you, but not in general, especially for new users who would use default camera neutral wb. Let’s have show of hands who have custom D65 WB presets here?

Doesn't matter how the WB coeffs are set. The point is we need to pass these exact coeffs along with color calibration no matter what or there is no point in copying color calibration or even input profile.

**Comment by parafin** [comment]
I’ll ask once again - can you provide exact steps to reproduce the problem from the scratch (fresh dt installation)?

**Comment by aurelienpierre** [comment]
> I’ll ask once again - can you provide exact steps to reproduce the problem from the scratch (fresh dt installation)?

1. calibrate camera D65 WB on D65 image, as explained in https://docs.darktable.org/usermanual/3.8/en/module-reference/processing-modules/color-calibration/#caveats
2. make a preset out of this calibration and auto-apply it
3. open a new picture and edit it : WB is set do custom preset
4. copy-paste the edit to another picture:
   - in overwrite mode, WB will be set to darktable bullshit D65 (camera "neutral"),
   - in append mode, WB will be set to custom preset.

**Comment by parafin** [comment]
OK, what you described to me looks like a different bug - IMHO custom presets should be applied the same as built-in, so overwrite mode should also end up with your D65 custom preset.

**Comment by aurelienpierre** [comment]
> OK, what you described to me looks like a different bug - IMHO custom presets should be applied the same as built-in, so overwrite mode should also end up with your D65 custom preset.

In any case, WB settings should be copied with no further assumption or clever safety measure because that's what is expected.

**Comment by parafin** [comment]
OK. So I see 2 points here:

1. feature request to expand the list of copied iops with at least temperature and maybe colorin (regardless of preferences);
2. bug report about user presets not being applied in some cases.

I really don’t think this PR should be merged in current state.

**Comment by TurboGit** [comment]
Closing, no incentive to have this moved forward.

**Pull request closed without merging**
