### PR TITLE
integration tests, part 4

### PR DESCRIPTION
**Pull request by ralfbrown**
This PR adds integration tests for crop&rotate w/keystoning, basecurve w/fusion, and tone equalizer with both guided filter and eigf.

If I'm not mistaken, that leaves just color calibration, negadoctor, and (if we can make it replicable) lens correction.

### CODE REVIEW

**Comment by TurboGit** [comment]
toneequal tests are failing on my side:

```
Test 0079-toneequal-gf
      Image mire1.cr2
      CPU & GPU version differ by 28148 pixels
      Max  dE         2.0011
      Mean dE         0.0003
      Count above max 1
  FAILS: image visually changed
         see diff.png for visual difference
         (2717 pixels changed)

Test 0080-toneequal-eigf
      Image mire1.cr2
      CPU & GPU version differ by 29842 pixels
      Max  dE         2.1019
      Mean dE         0.0006
      Count above max 1
  FAILS: image visually changed
         see diff.png for visual difference
         (4883 pixels changed)

```

**Comment by TurboGit** [comment]
What I find strange is the 1 pixel above dE 2 !

**Comment by ralfbrown** [comment]
Reordered fpmath due to optimization strikes again!  Current master gets 0.0000 diff when compiled with --buildtype Release (which is how I had generated the reference images), but yields 2.0x diff when compiled as RelWithDebInfo.  I'm getting a somewhat larger number of changed pixels, but overall about the same mismatch as you saw.

That lone pixel must be a quite dark one -- "compare -metric pae" says the maximal difference is the minimum representable change, i.e. a pixel that rounded one way in one image rounded the other way in the other.

**Comment by TurboGit** [comment]
@ralfbrown : so should I just regenerate the expected output for 79 & 80 with a build in RelWithDebInfo mode ?

**Comment by ralfbrown** [comment]
Sure.  If it won't break anything, I can do a "git reset HEAD~2 ; git push --force" on the branch to eliminate the last two commits with those images so you don't have to manually merge.

**Comment by TurboGit** [comment]
No need to remove them. I'll manually merged needed to update the expected output and testing on my side anyway.

**Comment by TurboGit** [comment]
Manually merged now and 79 & 80 expected output updated.

**Pull request closed without merging**
