### PR TITLE
import&copy: keep the original access and modified timestamps

### LINKED ISSUE #12355: The "copy&import" operation results in a change in the date and time of the raw file.
I have posted this issue in Pixel.us, and I have been suggested to open an issue here. Maybe @phweyland could give some help.

When copying images (RAW format) from the memory card, using the “copy&import” option, DT changes the original date and time of the raw file (when the picture was taken), to the date and time of the moment the images are being imported into DT. Certainly in the file properties, in the left pane of DT, it does recognize the original date. So, it does not appear to have modified the exif data inside the raw. There is no problem. The problem is in the date of the file itself after copying it.

It is curious that when the pictures are taken with the RAW+JPG option, the copied RAW files have their time and date modified, but not the JPG files. This does not happen when I use another program to copy the photos from the memory card and then import them with DT.

This happens regardless of the version of DT (3.8, 4.0, 4.1 develop. build) or the version of Windows (10 or 11), but always Windows.

I attach some screenshots…

This is on the memory card. The date and time are those of the moment the photo was taken:
imagen

This is the setup used to copy&import:
imagen

… and this is the result on the destination folder:
imagen

You can appreciate that the date of the JPG file has been preserved, but the date of the RAW file has been changed to that of the moment it was transferred.

**Platform:**
* darktable version : 3.8, 4.0, 4.1 develop. build
* OS                : Win10 or 11

**Additional context:**
 - Do you use lua scripts? No, only the "copy&import" module

Thank you in advance!

### PR DESCRIPTION
**Pull request by phweyland**
fixes #12355

EDIT: The original issue is common to all OS, but the solution may be different. I've tested on Linux Debian.

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Looks good to me!

**Comment by gi-man** [comment]
I'm getting a failure trying to build this PR on windows:

```
C:/msys64/home/gman/test/darktable/src/control/jobs/control_jobs.c:2109:37: error: 'struct stat' has no member named 'st_atim'; did you mean 'st_atime'?
 2109 |     times[0].tv_sec = (long)statbuf.st_atim.tv_sec;
      |                                     ^~~~~~~
      |                                     st_atime

```

3 min too late.

**Comment by parafin** [comment]
This failure was caught by CI, so I wouldn't say anyone was too late, but the opposite...

**Comment by gi-man** [comment]
@TurboGit It is now failing on master. I built master 15min ago (before the merge), without a problem. I was testing the PR and noticed the problem.

**Comment by TurboGit** [comment]
> This failure was caught by CI, so I wouldn't say anyone was too late, but the opposite...

Sorry CI is failing on all PR so I did not bother looking on this one. My bad.

**Comment by TurboGit** [comment]
I have now reverted this change until the Windows issue is solved. I have tried looking for something equivalent to tv_sec but it seems not that simple and I know next to nothing about Windows. So please, can a Windows dev shine in there? TIA.

**Comment by TurboGit** [comment]
@phweyland : Reverted as breaking build on Windows.

**Comment by phweyland** [comment]
From https://www.man7.org/linux/man-pages/man2/stat.2.html:

           struct stat {
               dev_t     st_dev;         /* ID of device containing file */
               ino_t     st_ino;         /* Inode number */
               mode_t    st_mode;        /* File type and mode */
               nlink_t   st_nlink;       /* Number of hard links */
               uid_t     st_uid;         /* User ID of owner */
               gid_t     st_gid;         /* Group ID of owner */
               dev_t     st_rdev;        /* Device ID (if special file) */
               off_t     st_size;        /* Total size, in bytes */
               blksize_t st_blksize;     /* Block size for filesystem I/O */
               blkcnt_t  st_blocks;      /* Number of 512B blocks allocated */

               /* Since Linux 2.6, the kernel supports nanosecond
                  precision for the following timestamp fields.
                  For the details before Linux 2.6, see NOTES. */

               struct timespec st_atim;  /* Time of last access */
               struct timespec st_mtim;  /* Time of last modification */
               struct timespec st_ctim;  /* Time of last status change */

           #define st_atime st_atim.tv_sec      /* Backward compatibility */
           #define st_mtime st_mtim.tv_sec
           #define st_ctime st_ctim.tv_sec
           };

The "notes' say:

       Since kernel 2.5.48, the stat structure supports nanosecond
       resolution for the three file timestamp fields.  The nanosecond
       components of each timestamp are available via names of the form
       st_atim.tv_nsec, if suitable feature test macros are defined.
       Nanosecond timestamps were standardized in POSIX.1-2008, and,
       starting with version 2.12, glibc exposes the nanosecond
       component names if _POSIX_C_SOURCE is defined with the value
       200809L or greater, or _XOPEN_SOURCE is defined with the value
       700 or greater.  Up to and including glibc 2.19, the definitions
       of the nanoseconds components are also defined if _BSD_SOURCE or
       _SVID_SOURCE is defined.  If none of the aforementioned macros
       are defined, then the nanosecond values are exposed with names of
       the form st_atimensec.

I haven't found version requirement for darktable...
Any direction is welcome.

**Comment by TurboGit** [comment]
Yes for Linux no issue. Looking at MSDN it looks like we need `GetFileTime()` and `FileTimeToSystemTime()`.

The later will give us:

```
typedef struct _SYSTEMTIME {
  WORD wYear;
  WORD wMonth;
  WORD wDayOfWeek;
  WORD wDay;
  WORD wHour;
  WORD wMinute;
  WORD wSecond;
  WORD wMilliseconds;
} SYSTEMTIME, *PSYSTEMTIME, *LPSYSTEMTIME;
```

And hopefully wSecond/wMilliseconds are what we are looking for.

**Comment by phweyland** [comment]
> Looking at MSDN it looks like we need GetFileTime() and FileTimeToSystemTime()

Thanks! Making a try.
I continue with the same PR or I create a new one ?

**Comment by TurboGit** [comment]
A new PR please, I cannot reopen this one. TIA.

**Comment by WMAM** [comment]
Sorry if I duplicate this report. 
This is to confirm that this bug has not been fixed in the latest development builds... at least not in Windows 11. Thanks!

**Pull request merged**
