### PR TITLE
clipping: allow multiple instances

### PR DESCRIPTION
**Pull request by elstoc**
this will allow correction (rotation and keystone) to be done early in the pipe but allow a creative crop to be done later, allowing spot/retouch access to the uncropped image.

As suggested in https://github.com/darktable-org/darktable/issues/8634#issuecomment-819481837.

### CODE REVIEW

**Comment by elstoc** [comment]
Note: this doesn't work at the moment and I don't know why. When I try to create a new instance, it gets added to the history stack but is not visible in the right-hand panel. The following errors are shown on the console:

```
[dt_ioppr_check_iop_order] history module not used but enabled!! clipping 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] history module not used but enabled!! clipping 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] history module not used but enabled!! clipping 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] history module not used but enabled!! clipping 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] history module not used but enabled!! clipping 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] history module not used but enabled!! clipping 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] history module not used but enabled!! clipping 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] history module not used but enabled!! clipping 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] history module not used but enabled!! clipping 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! clipping 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] history module not used but enabled!! clipping 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] history module not used but enabled!! clipping 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] history module not used but enabled!! clipping 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] history module not used but enabled!! clipping 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! clipping 1(2147483647) image 0 (dt_dev_modules_update_multishow)
```

**Comment by jenshannoschwalm** [comment]
I think you have to take care about the roi sizes. Not sure though.

One more point, at least some dng images have a `cropping hint` detected in exiv, that shouldn't be done twice :-)

**Comment by AlicVB** [comment]
@elstoc : as a general note about multi-instance of "distort" iop : I'm not against, as it can solve some corner cases, but we need to keep in mind that having multiple instances of distortions will not be excellent in term of final image rendition (multiple interpolations, ...) and I'm not speaking about perfs...

**Comment by elstoc** [comment]
Yes I'm mainly wanting to use this for final crop. I'd prefer a separate "crop only" module but that's still a future project.

**Comment by elstoc** [comment]
Closing in favour of #8838

**Pull request closed without merging**
