### PR TITLE
Collect rework

### PR DESCRIPTION
**Pull request by AlicVB**
Here is an attempt to rework the collect module. Quick summary of changes : 
1- lot of code cleanup
2- the wildcards are now added directly in the entry and not on the query creation, to let more freedom to the user.
3- single-click selection *
4- range selection for numeric and date/time values (in the form [x;y])
5- autocompletion for the entry
6- show selected item more obviously *
7- don't restrict the list once selection done (to let user change it after)
8- gui to specify numeric and date values

point 3 and 6 are configurable for now, until we decide what is better.

Thanks for testing and reviewing !

### CODE REVIEW

**Comment by TurboGit** [comment]
Just tested and one comment. In the list I have many labels which are stroked. Is that because they are not accessible (external drive)? I find this difficult to read, maybe using a grey for the text color will be better?

**Comment by AlicVB** [comment]
seems I missed your comment :(
unreachable filmrolls/folders are now marked with an icon and not stroked anymore.

**Comment by TurboGit** [comment]
I've tested this new version, I'm not convinced by the cross at the start of each text. I find it heavy, maybe smaller and with one more space between the cross and the text. I think this will make it clearer? Another option is to use a different text color? But this is not what dt does today as all text has the same color. To be discussed.

**Comment by AlicVB** [comment]
New try using just a different text color. It's less readable here, but it's certainly due to gtk3 theming...
And some missing features re-added.

**Comment by TurboGit** [comment]
Thanks, to me it is better this way and we can always adjust the color of off-line collection with a CSS.

I have a question though, when I enter say "%studio%" and hit enter I do get only the photos from the matching collection in the lightable. But I would also have expected the list in the collection module to be restricted to the matching ones. No?

**Comment by TurboGit** [comment]
Ping?

**Comment by TurboGit** [comment]
Also would be nice to rebase to continue testing against git master.

**Comment by AlicVB** [comment]
I'm closing this PR, as there has been too much changes in master since last commit. It would be messy to rebase it.
Plan is to redo it in smaller pieces, easier to review and discuss.
step 1 : cleanup
step 2 : core change (no major gui change)
step 3 : changes in common/collections.c
step 4 : gui enhancement (to be discussed)

**Comment by pedrocr** [comment]
The current setup, both of collect and of preset application is very closely linked with the underlying database. A potential other way of doing it would be to have a search language like gmail does where you can more easily specify AND/OR and precedence (use parentheses). Then the GUI would either be similar to what we have now but allow an expert mode where editing the search string is possible or just do as gmail and have the search string be the main interface. To implement this properly we'd probably need a proper parser->AST->SQLgeneration path.

**Pull request closed without merging**
