### PR TITLE
focus (and reposition) lib with mouse

### LINKED ISSUE #14526: Unwanted scroll in sidepanel on mouse over in thumbnail list or film strip
### Describe the bug

Mouse over on a thumbnail in lighttables filemanager layout or the filmstrip in darktable causes the sidepanel to scroll to show the last expanded module if it's not fully visible at the bottom of the side panel. If the module is totally out of view the scoll will be queued and trigger when the panel is scrolled down to the point where the module becomes partly visible. The panel will then make a scroll jump to show the module completely.
This can be a bit annoying on a smaller screen in lighttable view when expanding the image information module at the bottom and then scroll up to double click a capture date in collections. When moving the mouse over to thumbnail view the left panel scrolls down to show image information fully. Collections are obscured and I have to scroll the side panel back to collections again to be able to select a new date.
Closing and expanding the collection module after expanding the image information module will stop this behaviour, but if this scrolling could be supressed with a resonable effort it would be great.

### Steps to reproduce

I have mouse wheel scrolls modules side panel by default activated
Resize the darktable window so that not both collection and image information modules can be completely visible at the same time when expanded.
Expand the collections module.
Expand the image information module.
Scroll back up to the collection module so that image information is mostly obscured.
Double click a capture date in collections to view the thumbnails.
Move mouse over a few thumbnails in central view and left panel will scroll down to show image information.

### Expected behavior

Darktable should not scroll the side panel on mouse over thumbnail

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you install darktable from?

self compiled

### darktable version

4.3.0+2229~g68237e9f0

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.04 in wsl / Windows 10 msys ucrt64 

### Describe your system?

Gtk version in the windows 10 build is mingw-w64-ucrt-x86_64-gtk3 3.24.37.r22.gf1b6556-2.
In Ubuntu 23.04 its libgtk-3-0/lunar  3.24.37-1ubuntu1

### Are you using OpenCL GPU in darktable?

No

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by dterrahe**
fixes #14526 by taking away focus from a lib when the mouse leaves it. This avoids the module continuing to be repositioned when its size changes (for example because the mouse hovers over a different image in the lighttable).

In implementing this, I noticed that #14445 and #14465 misinterpreted the meaning of the `mouse_leave` function (which deals with the mouse leaving the center widget, not the module widget) and fixed this by attaching a leave handler to the metadata module widget directly).

@ansluk would you be able to test if this solves your issue?

### CODE REVIEW

**Comment by zisoft** [comment]
There is still an unpleasant effect in the metadata editor: When editing a text field and then accidentally hovering the mouse over a different image, the text is lost. The text gets restored when hovering over a free area in the image grid but not when the intended image gets back focus.

But there is already a huge discussion in #6025 about the hovering behavior in general so I think we can leave it as is for now.

**Comment by TurboGit** [comment]
@dterrahe : Thanks for taking this over. We have a regression, the fix I did do not work anymore. To reproduce:

1. Select a picture in lighttable
2. Enter some text in says metadata **Title** entry (do not hit Enter)
3. Fly over the lighttable
4. Select another picture
5. Select back the previous picture
6. See that the Title is lost

So it looks like the leave event wasn't called !

**Comment by ansluk** [comment]
Thanks for looking into this!
I still have issues with the scrolling with this fix.  If I expand the image information module in left panel of lighttable, then scroll the panel up towards collections so image information is partly obscured, click an entry in collections and then move mouse over to the thumbnails, image information will still scroll into view again. Not sure why it doesn't work. I did try a crude variant (don't know gtk) of the fix you suggested in #14526 and that did seem to stop that scrolling.

**Comment by dterrahe** [comment]
As usual, I made some "simplifications" _after_ testing (while splitting the PR into separate commits) that broke things again. I blame jetlag this time :-)
(as an aside, since #14187 the repositioning problem reported in https://github.com/darktable-org/darktable/issues/14526 only occurs when at least _part_ of the "image information" module is visible. This is where my quick testing failed; I had moved it _completely_ out of view and it didn't reappear so I thought the fix worked).

Second: the metadata editor fix that depends on the leave event is somewhat limited in that if I click on the textview, then move the mouse away (to a different _module_, not the center widget, so that the ActOn selection isn't impacted), _then_ start typing and _then_, without saving, move the mouse over the center widget, the leave event for the metadata editor doesn't get called and the problem occurs as before.

So I've now implemented a different solution; whenever a textview has unsaved changes, I _grab_ the metadata editor module. So mouse moves are invisible outside it. You can only move focus to another textview in metadata editor or click the apply button until the change is either committed or canceled.

Please provide feedback on this. If it causes any issues, I can still simply fix the mouse-leave solution for now.

**Comment by TurboGit** [comment]
> Please provide feedback on this. If it causes any issues,

I'm not fan of this solution. I'm not sure I have used a software grabbing  an entry and requiring Enter to commit stuff.

Let's see what others think about this.

**Comment by dterrahe** [comment]
> I'm not sure I have used a software grabbing an entry and requiring Enter to commit stuff.

I'm not sure I have either. Maybe we should look at other software that uses the same (or similar) ActOn approach that dt has and see what solution they use to deal with the issues it causes. If there _is_ any such software.

For the record, committing a change on mouse move, when in most cases the selection immediately changes so it is not obvious that the change _was_ committed (and if this was unintentional, the window to do an undo might be lost) doesn't strike me as a drawbackless feature either. Still, as said if that is what you want, I'll be happy to reenable that here and carry the solution that works better _for me_ in my private patch set. No hard feelings.

**Comment by dterrahe** [comment]
The grab approach creates a problem when the mouse is hovered over a different image while the grab is active and then the tab key is used to move to the next field and thereby cause a commit; the hovered-over receives focus immediately and then immediately gets updated with the changed metadata.

So I have reverted this change and just "correctly" implemented the mouse leave approach. "correctly" in quotes, because since the `leave-notify-event` event also gets triggered when the mouse "leaves" the module widget to move over one of the widgets contained in it, almost any mouse move causes a commit. I believe master behaves the same way, so that this is not a regression, but haven't extensively tested.

**Review by TurboGit — APPROVED** [review]
Works for me, thanks! This implementation seems safer and more natural.

**Comment by dterrahe** [comment]
Now that any changes basically get applied as soon as one moves the mouse, maybe the "Apply" button should be removed:
- When the mouse gets to it, the change has usually already been committed, so there's no point pressing the button anymore.
- Having an "apply" button suggests it has to be pressed before any change is applied, hence that if it _isn't_ pressed, the change _won't_ be applied. But that's not what's happening. Rather, when one moves the mouse from the module to the lighttable, the change gets applied _and_ the metadata gets updated based on whatever is under the cursor, so it is not obvious at all the the change was applied to what was previously active.

**Pull request merged**
