### PR TITLE
Improve stars, colorlabels and some spacing

### LINKED ISSUE #7804: Star rating symbols not emphasized enough
When rating images the star rating symbols appear differently in different contexts. In most contexts, the selected star symbols have a dark interior and grey outline which makes them appear small when displayed on a grey or white background. They especially appear smaller than the unselected symbols. This is best seen in the attached screenshots.

**Expected behavior**
I would like the selected star symbols in all contexts to be all dark with no outline, similar to the screenshot where I say they appear OK.

**Screenshots**
This screenshot from lighttable view shows selected stars appear smaller than unselected stars next to them. 
stars looking smaller when set in lighttable

This screenshot from filmstrip shows ratings for the current image has similar look.
stars looking smaller when set in filmstrip

This screenshot from filmstrip while hovering over a not-current image also shows the problem.
stars looking smaller when set in filmstrip when hovering

This screenshot of the selected image in lighttable looks OK to me. This is what I think the selected stars should look like in all the above contexts. 
stars looking OK when set in lighttable if selected

darktable 3.4 running on Windows 10 with OpenCL on nVidia Quadro K1200 using nVidia driver

Thanks for considering this issue!

### PR DESCRIPTION
**Pull request by Nilvus**
Fix #7804. See new inactive stars (test for hover effect update too):

A french user suggested to increase colorlabels to better see them. He propose 1.2 size, that is too big. I've made some tests and think that updating from 1.0 to 1.1 is better. See below comparison between actual master on left (1.0), 1.05 size in middle and this PR, 1.1 on the right:

colorlabels

### CODE REVIEW

**Comment by Nilvus** [comment]
Last commit improve spacing in icons in footer toolbar and especially new ones from @quovadit and @AlicVB work, and so other older ones too. This also adjust spacing in new import module from @phweyland and so other section label with a little too more space on top. This will so reduce a little module height.

I'd like some reviews and feedback, especially from @greymont, @homer3018, @parafin for stars.

**Comment by parafin** [comment]
Looks good to me.

**Comment by Nilvus** [comment]
@TurboGit: maybe first commit could go in 3.4.1 and 2nd one for 3.6? How do you want to process for that?

**Comment by TurboGit** [comment]
Agreed, will merge first commit into 3.4.1.

**Pull request merged**
