### PR TITLE
exif read xmp: protect against base_order NULL

### LINKED ISSUE #7720: darktable crash while import of folder
_Don't know if this is related to https://github.com/darktable-org/darktable/issues/7641 since no more details are given there_

Preface: I have two folders in my archive with around 150 and 225 images, mainly in jpg format. Those were already imported in darktable in previous versions - no issues until now.

I decided to clean up some filenames (replacing a `space` by a `_`). For this I removed those files from the darktable database by the relevant lighttable option, fixed the filenames (both image and .xmp) and then tried to reimport the folder.

Darktable crashed while import.

After reading this https://github.com/darktable-org/darktable/issues/7691#issuecomment-754891186 I tried on a second machine (synchonized archive _and_ dt profile) - same result.

**Describe the bug**

darktable crashes when importing image folder with mainly jpg images with accompanying .xmp files produced by darktable 

**To Reproduce**

1. Go to 'lighttable'
2. Click on 'import folder'
3. move to target folder, disable all options (Metadata, recursive and ignore jpg)

**Expected behavior**

dt should simply import the (missing) images from the folder

**Screenshots**

no screenshots, backtraces from two machines attached
[darktable_bt_DQJNW0.txt](https://github.com/darktable-org/darktable/files/5778062/darktable_bt_DQJNW0.txt)
[darktable_bt_TDV1W0.txt](https://github.com/darktable-org/darktable/files/5778063/darktable_bt_TDV1W0.txt)

**Platform (please complete the following information):**
darktable from OBS
```
~$ darktable --version
this is darktable 3.4.0
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```

machine no. 1 - no openCL
```
System:
  Host: Rechner Kernel: 4.19.0-13-amd64 x86_64 bits: 64 compiler: gcc 
  v: 8.3.0 Desktop: Cinnamon 3.8.8 Distro: Debian GNU/Linux 10 (buster) 
Machine:
  Type: Desktop Mobo: ASUSTeK model: P8Z77-M v: Rev 1.xx serial: <filter> 
  UEFI: American Megatrends v: 2203 date: 12/18/2015 
CPU:
  Topology: Quad Core model: Intel Core i5-3570 bits: 64 type: MCP 
  arch: Ivy Bridge rev: 9 L2 cache: 6144 KiB 
  flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 27282 
  Speed: 1605 MHz min/max: 1600/3800 MHz Core speeds (MHz): 1: 1605 2: 1605 
  3: 1605 4: 1605 
Graphics:
  Device-1: Intel Xeon E3-1200 v2/3rd Gen Core processor Graphics 
  vendor: ASUSTeK P8H77-I driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.20.4 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1920x1200~60Hz 
  OpenGL: renderer: Mesa DRI Intel Ivybridge Desktop v: 4.2 Mesa 18.3.6 
  direct render: Yes 
```
machine no. 2 - also no openCL
```
System:    Host: carPC Kernel: 4.19.0-13-amd64 x86_64 bits: 64 compiler: gcc v: 8.3.0 Desktop: Cinnamon 3.8.8 
           Distro: Debian GNU/Linux 10 (buster) 
Machine:   Type: Desktop Mobo: ASRock model: J4205-ITX serial: <filter> UEFI: American Megatrends v: P1.30 date: 04/18/2017 
CPU:       Topology: Quad Core model: Intel Pentium J4205 bits: 64 type: MCP arch: Goldmont rev: 9 L2 cache: 1024 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 11980 
           Speed: 998 MHz min/max: 800/2600 MHz Core speeds (MHz): 1: 956 2: 929 3: 918 4: 996 
Graphics:  Device-1: Intel Atom/Celeron/Pentium Processor N4200/N3350/E3900 Series Integrated Graphics vendor: ASRock 
           driver: i915 v: kernel bus ID: 00:02.0 
           Display: x11 server: X.Org 1.20.4 driver: modesetting unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 505 (Broxton) v: 4.5 Mesa 18.3.6 direct render: Yes 
```

**Additional context**

Also tried to move the xmp away from the folder and import jpg only - same result
- Is the issue still present using an empty/new config-dir
YES

### PR DESCRIPTION
**Pull request by phweyland**
fixes #7720

@turbogit, this fixes the crash, but could you check the alternative action ?
EDIT: and that may not fix the root cause ...

### CODE REVIEW

**Comment by TurboGit** [comment]
The cause is that in the XMP we have:

```
     <rdf:li
      darktable:operation="metadata"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="gz02eJyNyrEOwiAURmEe5Y6alHZ3E5zZHaH8kRvg1lAqiU9vH8GzfkfRHynb4Dt/QHardZOdnK+QXSByyGsi4TV1yieifRmlTJTBAjLwLYD7edHFWm2e2lntHldl0CT5FuleAq8ZTaXe37dlGWPMgUuMvoMhc4T6AQcgMS4="
      darktable:multi_name=" "
      darktable:multi_priority="0"/>
```

And metadata is not a processing module, it should not be there. I kind of remember having fixed that, so looks like this file has been edited with a buggy dev version.

**Comment by phweyland** [comment]
ok. please close the PR if useless.

**Comment by parafin** [comment]
Invalid input ideally shouldn't lead to crashes though.

**Comment by TurboGit** [comment]
Agreed with you @parafin, I'll put in place a check an report an error message in stderrr in such a case.

**Comment by bilddateien** [comment]
I searched for
`darktable:operation="metadata"`
in my archive and found 905 out of my around 24.000 images with that line in the .xmp

I then removed filmrolls containing those files (this time with .NEF and .ORF files, not jpgs) and can confirm that reimporting them always caused a crash.

@TurboGit Is there a way to fix those 905 .xmps? 
Delete the line/the complete block? Or do I have to replace that by something meaningful?
Or simply leave as is and wait for the fix? (I do not feel well knowing I have that much buggy xmp files ... )

**Comment by TurboGit** [comment]
@bilddateien : This is worrisome... I did check the 89788 XMPs on my machine and no one with metadata ! I really don't understand how was this happening to you if you did not use a dev version.

The solution is to remove the block indeed. If you leave the block the XMP will be seen as broken and you will loose the history if you have edited this picture.

**Pull request closed without merging**
