### PR TITLE
imageio: workaround for disabling metadata export

### PR DESCRIPTION
**Pull request by TurboGit**
Proposed workaround for https://github.com/darktable-org/darktable/issues/13077.

Replace #13100.

Fixes a crash.

### CODE REVIEW

**Comment by TurboGit** [comment]
@gi-man : Can you double check that all is OK now? TIA.

**Comment by kmilos** [comment]
Good going 👍 
I though `format->mime()` was required to be implemented always looking at `imageio_api.h`...

**Comment by gi-man** [comment]
No segfaults.

I think it works as intended for 4.2. The 3 formats (avif, exr and jxl) will not display most of the metadata (eg. Creator, Rights) unless **all** checkboxes are selected. The others seems to be working like in the past.

With these settings: 
image

```
======== IMG_4733.avif
======== IMG_4733.exr
======== IMG_4733.jpg Creator                         : Playraw
======== IMG_4733.jxl
======== IMG_4733.png Creator                         : Playraw
======== IMG_4733.tif Creator                         : Playraw
======== IMG_4733.webp Creator                         : Playraw
    7 image files read
```

Disabling all of the checkboxes, disable it all.
```
======== IMG_4733_02.avif
======== IMG_4733_02.exr
======== IMG_4733_02.jpg
======== IMG_4733_02.jxl
======== IMG_4733_02.tif
======== IMG_4733_02.webp
    6 image files read
 ```

**Review by TurboGit — COMMENTED** [review]
Thanks for testing @gi-man and for handling this @kmilos, that's a good team work.

**Comment by gi-man** [comment]
@TurboGit or @elstoc  I was thinking we need to provide some documentation for this work around. Maybe in the Release Notes we should have a section for Known Issues or include it the the manual.

## Known Issues

- With the support of JXL, AVIF and EXR for export, selecting specific metadata (eg. geo tag, creator) is not currently possible. For formats JXL, AVIF and EXR, darktable will not include the metadata fields unless the user selects **all** of the checkboxes in the export preference options.

**Comment by TurboGit** [comment]
The section we used to fill for such information is Notes. I'll add this here. Thanks.

**Comment by elstoc** [comment]
Yeah I don't think the manual is the place for this. Release notes sounds like the best place

**Pull request merged**
