### PR TITLE
fix MacOS build error on imageio.h

### PR DESCRIPTION
**Pull request by zisoft**
This PR fixes build errors on MacOS due to naming conflicts on `src/imageio/imageio.h`.

See the discussion on #13357 for details.

### CODE REVIEW

**Comment by parafin** [comment]
I'm not sure if we want to rename imageio.c to imageio_common.c as well. For me it's fine as is. Let's wait for macOS CI to finish and then I suggest to merge.

**Comment by victoryforce** [comment]
> I'm not sure if we want to rename imageio.c to imageio_common.c as well. For me it's fine as is. 

For me, it's better as is too. Let's not rename.

**Comment by parafin** [comment]
Looks like CI is fine, one macOS job got stuck, probably GitHub issue, others finished fine. Windows CI fails, but it's due to other reasons.

Good to go.

**Comment by kmilos** [comment]
> Windows CI fails, but it's due to other reasons.

That's fixed as well in another PR waiting.

**Review by TurboGit — APPROVED** [review]
Thanks for the work and @parafin for the hint about the possible issue.

**Pull request merged**
