### PR TITLE
print view: graphical image coordinates overlay

### PR DESCRIPTION
**Pull request by dtorop**
In print view, the center view currently can overlay coordinates of an image area in the form of:

`(x_top, y_top) -> (x_bottom, y_bottom) | (w x h)`

For the sake of legibility, this PR shows these coordinates graphically. The width/height values are embedded in the rectangular outline of the image area. Instead of displaying the coordinates of the image area's corners, the image margins are displayed, in the hope that these will be more useful during page layout.

The resolution of these numbers now varies depending on the display units: mm's are displayed as whole numbers, while cm/inch display to the nearest 0.1 unit.

The print units chosen by the user are now stored in config as an enum rather than as an int, and have an entry in darktableconfig.xml.in.

Coordinates overlay as in current code:

image

With this PR:

image

### CODE REVIEW

**Comment by TurboGit** [comment]
Really nice when there is a single image area, becomes a bit less cool with multiple, here is an example with only 2 areas:

image

**Comment by dtorop** [comment]
> becomes a bit less cool with multiple, here is an example with only 2 areas

Maybe fading down the other images when dragging or mouseover on an image area? I will experiment...

**Comment by dtorop** [comment]
Also: The first pass on this was ruler-style x/y coords at the edge of the paper. This got visually confusing, hence this version. Another possibility would be to go back to giving margin measurements at the paper edge. The width/height measurements would either stay on the image frame, or also go down to the paper edges.

But I'll try fixing up this version first.

**Comment by dtorop** [comment]
Also, the math for positioning the text is pretty messy. There may be a way to tidy it, or maybe this is just the nature of highly specific one-off drawing code.

**Comment by TurboGit** [comment]
> Maybe fading down the other images when dragging or mouseover on an image area? I will experiment...

Maybe, waiting to see how this works.

**Comment by dtorop** [comment]
> > Maybe fading down the other images when dragging or mouseover on an image area? I will experiment...
> 
> Maybe, waiting to see how this works.

It's better -- but still not certain. I'm also trying to make the horizontal/vertical margin lines match on both sides -- it makes a stronger visual element & so is more legible...

**Comment by dtorop** [comment]
The last PR has some legibility fixes. The margin lines should be drawn more visibly now, and the non-selected images are given an alpha, which also helps a lot.

image

Also some more label positioning tweaks for when the image area is close to the page edge or is relatively small.

image

This looks better to me, but there is still a lot to take in when the grid is on.

**Comment by dtorop** [comment]
Also: Maybe the overlay with margins/dimensions makes sense for a single image box with no grid background. But once the grid is on, or there are multiple images, this isn't want is needed. And in that case the current code's output, or a variation (width/height on image box edges, corner coordinates in a box) makes sense.

**Comment by dtorop** [comment]
And one more thought: To keep things extra simple -- just a small variation on current code:

- width/height is in the edges of the image box, as in this PR
- x,y offset (same as top/left margin) is inside image box in top left corner (this and subsequent simply in form _x_,_y_)
- bottom right offset (not in this PR, but in current code) is inside image box in its bottom right corner
- bottom and right margin is just outside the image box, below & right (or simply to right if the image box is close to the page paper)

This takes care of my initial interest -- I find the monolithic `(x_top, y_top) -> (x_bottom, y_bottom) | (w x h)` to be confusing, and wanted a sense of all the margin measurements. But also doesn't confuse the center view with a lot of geometry lines. This would also mean fewer big blocks of geometry/Cairo work than is currently in this PR.

**Comment by dtorop** [comment]
But just to say -- I'm also open to keeping this PR as is, too. It is more stylish... I think this is all a design question, really.

**Comment by TurboGit** [comment]
Having the other parts of the composition greyed out as proposed in this second version of this PR is looking ok to me. Far better than the previous proposal. If you have no better idea I'll merge this version. The other proposal above seems less attractive to me.

**Review by TurboGit — APPROVED** [review]
Ok as-is to me.

**Comment by dtorop** [comment]
> Ok as-is to me.

Great! I won't overthink it then!

**Comment by TurboGit** [comment]
Thanks!

**Comment by elstoc** [comment]
I don't really know my way around the print view. Could someone advise on what documentation is required (if any) here.

**Comment by dtorop** [comment]
@elstoc: I made darktable-org/dtdocs#476 which should document this. Though this should be fairly visually self-explanatory...

**Pull request merged**
