### PR TITLE
update macos build instructions

### PR DESCRIPTION
**Pull request by curiousercreative**
Grateful for these build instructions, though I still struggled to get binaries built on macOS 10.14.6 and XCode 11.3. These updated build instructions are mostly a 1-1 translation of the previous txt file, just into markdown. I've marked this PR as a draft because I encountered the following problems but wasn't able to solve for them on my own:
1. MacPorts patches (I don't know how to generate these patch files :/)
    1.  `librsvg` patch needs updating for upstream changes
    2. `gmic` patch needs updating, `opencv` dep is now `opencv4`, but still needs to be blacklisted
    3. `libheif` (`gmic` dependency?) needs to blacklist `aom` dep
1. `curl -O https://download.gnome.org/sources/gtk-mac-bundler/0.7/gtk-mac-bundler-0.7.4.tar.xz` yields a 0 byte file. I was able to download directly via browser though...
1. `./make-app-bundle` (gtk-bundler) python2 not found errors are resolved with `ln -sf /usr/bin/python2.7 /usr/local/bin/python2`
1. `./make-app-bundle` still fails (permission errors?)

### CODE REVIEW

**Comment by curiousercreative** [comment]
@parafin what do you think of the translation to markdown? Any ideas on the outstanding issues above?

**Comment by parafin** [comment]
I'm fine with translation to markdown, but please use actual numbering in ordered list instead of using 1. everywhere. markdown is intended to be readable as a plain text file, without pretty rendering...
As for your questions/changes - I will have to review them, I hope to find time this month.

**Comment by MStraeten** [comment]
The hint on using xcode <12.2 is no longer necessary. Xcode 12.5 and sdk11.3 are fine - the former xcode version dependent looping of histogram is gone

**Comment by curiousercreative** [comment]
@MStraeten that's great! Are you able to make edits to this PR and update as you see fit?

**Comment by parafin** [comment]
> Grateful for these build instructions, though I still struggled to get binaries built on macOS 10.14.6 and XCode 11.3. These updated build instructions are mostly a 1-1 translation of the previous txt file, just into markdown. I've marked this PR as a draft because I encountered the following problems but wasn't able to solve for them on my own:

I've updated the build instructions in master, so please take a look and rebase your PR if you're still up to it.

> 1. MacPorts patches (I don't know how to generate these patch files :/)
>    
>    1. `librsvg` patch needs updating for upstream changes

I dropped it altogether, seems to work fine out of the box.

>    2. `gmic` patch needs updating, `opencv` dep is now `opencv4`, but still needs to be blacklisted

Patch updated. OpenCV dependency is now a variant, so only ffmpeg needs to be disabled now.

>    3. `libheif` (`gmic` dependency?) needs to blacklist `aom` dep

Why? aom built fine for me.

> 2. `curl -O https://download.gnome.org/sources/gtk-mac-bundler/0.7/gtk-mac-bundler-0.7.4.tar.xz` yields a 0 byte file. I was able to download directly via browser though...

Fixed that command.

> 3. `./make-app-bundle` (gtk-bundler) python2 not found errors are resolved with `ln -sf /usr/bin/python2.7 /usr/local/bin/python2`

Added a command creating that symlink.

> 4. `./make-app-bundle` still fails (permission errors?)

Works for me, so please elaborate how it fails, what is the error message?

**Comment by parafin** [comment]
Closing due to no activity. Please re-submit PR if still interested. Note that minimal requirements for building has been bumped since then.

**Pull request closed without merging**
