### PR TITLE
dither: cleanup and speedup Floyd-Steinberg dithering

### PR DESCRIPTION
**Pull request by ralfbrown**
F-S dithering is inherently fully sequential (every pixel depends an **all** pixels above and to the left of it), but there are still speedups possible.

- Merged some preprocessing that was being done in a separate loop into the main loop as incremental processing so that it becomes "free" in terms of memory traffic.
- Process two rows of the image in tandem, allowing even more memory transfers to be optimized away.

Together, this yields a speedup of 37% comparing the new plain-C code against the current master SSE code, and 43% speedup SSE vs. SSE.

Verified identical output on test 0043.

### CODE REVIEW

**Review by TurboGit — CHANGES_REQUESTED** [review]
This PR breaks the "floyd-steinberg auto" the preview get full black.

**Comment by ralfbrown** [comment]
Will take a look tonight.

**Comment by ralfbrown** [comment]
Fixed.

**Comment by TurboGit** [comment]
Looks good now to me. Thanks.

**Comment by TurboGit** [comment]
Merged into master and queued for 3.4.1.

**Pull request merged**
