### PR TITLE
lighttable dnd: keep all control on thumbtable

### LINKED ISSUE #10842: Dragging from the thumbnail view in darkroom mode to the main image crashes darktable
I didn't even know this was possible. This is latest dt git. Accidentally didn't let go of the image selection under the main image I was currently editing and dragged the thumbnail into the image. This lead to a crash. Backtrace as follows:

```
Thread 1 "darktable" received signal SIGSEGV, Segmentation fault.
dt_thumbtable_event_dnd_received (widget=<optimized out>, context=0x555558a83460, x=<optimized out>, y=<optimized out>, selection_data=0x7fffffffe2b0, target_type=<optimized out>, time=56450883, user_data=0x0) at /home/panda/Downloads/dtcompile/darktable/src/dtgtk/thumbtable.c:1730
1730	    if(table->drag_list)
(gdb) bt full
#0  dt_thumbtable_event_dnd_received
    (widget=<optimized out>, context=0x555558a83460, x=<optimized out>, y=<optimized out>, selection_data=0x7fffffffe2b0, target_type=<optimized out>, time=56450883, user_data=0x0)
    at /home/panda/Downloads/dtcompile/darktable/src/dtgtk/thumbtable.c:1730
        table = 0x0
        success = 0
#1  0x00007ffff6a6a9fc in  () at /usr/lib/libgtk-3.so.0
#2  0x00007ffff64141c0 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#3  0x00007ffff641455a in g_signal_emit_by_name () at /usr/lib/libgobject-2.0.so.0
#4  0x00007ffff6d482a1 in  () at /usr/lib/libgtk-3.so.0
#5  0x00007ffff6a68cf7 in  () at /usr/lib/libgtk-3.so.0
#6  0x00007ffff64141c0 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff641455a in g_signal_emit_by_name () at /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff6c4d4b6 in gtk_selection_convert () at /usr/lib/libgtk-3.so.0
#9  0x00007ffff6d4b1bc in  () at /usr/lib/libgtk-3.so.0
#10 0x00007ffff6bbde9f in gtk_main_do_event () at /usr/lib/libgtk-3.so.0
#11 0x00007ffff6926643 in  () at /usr/lib/libgdk-3.so.0
#12 0x00007ffff6972ca4 in  () at /usr/lib/libgdk-3.so.0
#13 0x00007ffff71e152c in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#14 0x00007ffff72357b9 in  () at /usr/lib/libglib-2.0.so.0
#15 0x00007ffff71e0ab3 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#16 0x00007ffff6bb393f in gtk_main () at /usr/lib/libgtk-3.so.0
#17 0x00007ffff7c55ad9 in dt_gui_gtk_run (gui=<optimized out>)
--Type <RET> for more, q to quit, c to continue without paging--
    at /home/panda/Downloads/dtcompile/darktable/src/gui/gtk.c:1385
        widget = <optimized out>
        allocation = {x = 0, y = 0, width = 566, height = 466}
#18 0x0000555555555090 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/panda/Downloads/dtcompile/darktable/src/main.c:93
```

### PR DESCRIPTION
**Pull request by phweyland**
attempt to fix #10842

@AlicVB I've tested and not found any flaw.
~~This said dt_thumbtable_event_dnd_received() is triggered even if darkroom is active and doesn't test if lighttable is active or not. Should I add something there ?~~

### CODE REVIEW

**Comment by TurboGit** [comment]
@phweyland : This basically revert ff2413d0e8fd8643ae0246618864c0f1f3502e0d which was done to fix #9981. Have you checked that it does not regress in this case?

**Comment by phweyland** [comment]
> Have you checked that it does not regress in this case?

No, and surely it regresses the case. 
On the other hand it's not clean to have two dnd receptions at the same time.
I'll look at that.

**Comment by phweyland** [comment]
Done.
For lighttable dnd receive, user_data is NULL, which makes dt crash for images dnd.
Limiting lighttable dnd receive to files, avoids this.

**Comment by piratenpanda** [comment]
I just tested, does not crash anymore but when you drag and drop, accidentally or by will, the thumbtable jumps to the first image most likely being reloaded or whatever. Is there a way to avoid this?

**Comment by phweyland** [comment]
> I just tested, does not crash anymore but when you drag and drop, accidentally or by will, the thumbtable jumps to the first image most likely being reloaded or whatever. Is there a way to avoid this?

Not sure to understand.
If I refer to the related issue, dnd from filmstrip to darktable, there is no dnd in fact. The selection is made on the first click. If it's not what you mean, could you explain a bit more the case.

**Comment by piratenpanda** [comment]
If I drag from there to the currently edited image
Bildschirmfoto von 2022-01-10 21-00-28

the thumbtable moves to the first image:
Bildschirmfoto von 2022-01-10 20-59-28

**Review by AlicVB — COMMENTED** [review]
I wonder... The crash happen because user_data is NULL when dnd is "recieved" by lighttable, right ?
Then why not just add a check that user_data is valid in `dt_thumbtable_event_dnd_received` in the second part of the `if`
I've just done a quick test, and this seems to work... and don't exhibit @piratenpanda last issue, neither regress for the fix #9981

**Comment by phweyland** [comment]
> Then why not just add a check that user_data is valid in `dt_thumbtable_event_dnd_received` in the second part of the `if`

Yes that works, as the test (view == lighttable), which was my first solution.
But it is not logical to receive in lighttable drag & drop event of images without the images list (which comes tihe user_data).
I would prefer to understand what does happen really.

**Comment by phweyland** [comment]
@AlicVB is there any reason to drag&drop a thumbtable image as a uri (file) ?
One could be to drag & drop the file of the image outside dt ... but dt loses the image. I don't see this as a valid case...

**Comment by phweyland** [comment]
This is my fix, only valid if we don't need thumbtable to send image files by drag & drop.
Note that now, in darkroom, dnd shows that the dnd is not accepted (instead of silently fail).

Explanation.
Without fix, both lighttable receiver and thumbtable emitter plays for images AND files.
In the case of the bug, lighttable requests images and thumbtable sends an image. Lighttable is unable to receives it because it doesn't get the list of id and fails by segfault.

With the first fix, lighttable receiver plays only with files and thumbtable emitter plays for images AND files.
In the case of the bug, lighttable requests files and thumbtable sends a file. Lighttable is able to receives it and reloads the image which is already in the database, then the glitch pinpointed by @piratenpanda.

With this last fix, lighttable receiver plays only with files and thumbtable emitter plays only for images.
In the case of the bug, lighttable requests files and thumbtable rejects this request.
Thumbtable is still able to receive both images and files.

Note 2. I've noted that thumbnails are also set to emit images AND files, which doesn't seem to be appropriate.

**Comment by phweyland** [comment]
@TurboGit I wanted to check what happened on Print view 9related to dnd), but even with master, I don't see any image in the center view. I cannot even select the pdf file printer (the only one I have). Do I miss anything ?

**Comment by TurboGit** [comment]
@phweyland : That's strange, I do have the PDF printer in there and I see pictures when I enter the view if PDF selected or any other printer. Maybe that related to the fact that you have only PDF, but I cannot test this right now.

**Comment by AlicVB** [comment]
@phweyland : tbh, I don't really use dnd and I find that quite complex to implement...

iirc, dragging files from thumbtable to somewhere outside dt was used by some people to drop images in some specific app to see detailed and specific infos (one use case was an app that allow to show all exifs/etc... infos, but there was some other) not sure about my memory, but some other people also use that to quickly create a list of image in a text editor for... I don't remember why...
At first I wanted to remove that too, but due to that usages, I've finally put it back.

Returning to this issue, let me explain how I see this (keep in mind, that I may perfectly be wrong) : 
- in lighttable view `gui_init`, we instantiate the dnd reception for *all* view  (`dt_ui_center_base(darktable.gui->ui)`) That's sort of a hack but should be fine because dt always start with lighttable.
- now that should be up to each view to decide what to do with the received datas. Maps already handle them, lighttable too (in the same way than thumbtable), darkroom should just ignore them, ...
- this may be done by extending the view api...

and I don't really see a problem in the fact that each dnd propose multiple sort of datas (URI or imageIDs) again, it's up to the receiver to handle them...
Now the question : where I'm wrong :) (because I know I miss something)

**Comment by TurboGit** [comment]
> iirc, dragging files from thumbtable to somewhere outside dt was used by some people to drop images in some specific app

Indeed, you can dnd from dt to GIMP or Rawtherapee for example. This is not possible anymore.

**Comment by parafin** [comment]
> * in lighttable view `gui_init`, we instantiate the dnd reception for _all_ view  (`dt_ui_center_base(darktable.gui->ui)`) That's sort of a hack but should be fine because dt always start with lighttable.

Not always I think - what about when dt is started with filename passed as an argument - as far as I remember it gets opened straight in darkroom.

**Comment by AlicVB** [comment]
> * in lighttable view `gui_init`, we instantiate the dnd reception for _all_ view  (`dt_ui_center_base(darktable.gui->ui)`) That's sort of a hack but should be fine because dt always start with lighttable.

in fact that's not exactly true : most views put widgets on top of `dt_ui_center_base(darktable.gui->ui)` so the dnd never arrive there. and it happen that *empty* lighttable and darkroom use this widget directly to draw their stuff, without something on top...

So imho, the bug is to use `dt_ui_center_base(darktable.gui->ui)` as receiver although we *only* want to have *empty* lighttable here... Now how to solve that... iirc disabling-re-enabling dnd receiver is buggy (read : I never manage to get it working ;))... adding a special widget only for that is not the best... Maybe we can add a dedicated function in view_manager which would dispatch the event to the right function (or drop them) depending on the current view ?

@parafin : you're right of course, but in fact it doesn't really matters, as `gui_init` from all view seems to be called at startup anyway...
That said it's not really clean to "hide" a global thing inside an "child" one...

**Comment by phweyland** [comment]
OK, thanks for comments and clarifications. 
The difficulty I see for the time being is the following.
When both receiver and emitter are images and files enabled, receiver requests an image. If the emitter is only file enabled it requests a file. In our case, the emitter (thumbtable) should deny both requests from lighttable. 
I'll read a bit more the dnd doc to see if there is some means to achieve that in another way.

**Comment by AlicVB** [comment]
> In our case, the emitter (thumbtable) should deny both requests from lighttable

well, in fact, this situation should **never** happen (dnd from thumbtable to lighttable) : dnd with lighttable as destination is only here to handle the case of an empty lighttable (someone who want to import images by dnd into a *empty* database for example). And in lighttable view, we can't have a situation where thumbtable is present and populated *and* lighttable empty at the same time. That's just impossible !

As said, the issue we face here is that the `drag-data-received` event is not limited to lighttable views but may also be triggered by other view (darkroom in our case), which is clearly a bug imo.

**Comment by TurboGit** [comment]
> well, in fact, this situation should **never** happen (dnd from thumbtable to lighttable) : dnd with lighttable as destination is only here to handle the case of an empty lighttable

What about the mode to reorder freely the thumbs?

**Comment by AlicVB** [comment]
> What about the mode to reorder freely the thumbs?

In this case, we dnd from thumbtable to thumbtable.

In fact, thumbtable widget is superposed on top of `dt_ui_center_base(darktable.gui->ui)` widget, which makes impossible to drop something there. The only cases where `dt_ui_center_base(darktable.gui->ui)` in not "hidden" by some superposed widgets is : 
- lighttable empty (the situation where you see some writing to explain that you either need to relax rules or import new images)
- darkroom
- ??? for other views

hopes it's a little more clear (sorry for my confuse explanations...)

**Comment by phweyland** [comment]
> And in lighttable view, we can't have a situation where thumbtable is present and populated _and_ lighttable empty at the same time. That's just impossible !

?. In lighttable, filter rejected images when there isn't any, you have an empty lighttable and a populated thumbtable. 

> So imho, the bug is to use dt_ui_center_base(darktable.gui->ui) as receiver although we only want to have empty lighttable here... 

Agreed.
The source of the issue is in the design.
Because the empty thumbtable has no surface to drag and drop into...
Using dt_ui_center_base(darktable.gui->ui), we create an ugly situation for drag and drop. Different cases have to be considered and the only thing we can do is, case by case, silently skip the drop.

Is there really no way to treat this inside thumbtable instead of spreading the issue over the views ?
Correctly implemented drag and drop shows to the user where he can drop, far before the drop itself, because each emitter/receiver are correctly set up. 

Again yes, the test in drag-data-receive, view == lighttable or user_data != NULL, avoids the bug, but the design is not correct. This is not a solution, only a workaround, until the next glitch.

**Comment by AlicVB** [comment]
> ?. In lighttable, filter rejected images when there isn't any, you have an empty lighttable and a populated thumbtable.

but you can't reach a point where you have filmstrip (thumbtable) and the *empty* view (the one with the writings) or I miss some cases...

I've done a quick test here to show you what I mean : https://github.com/AlicVB/darktable/tree/dnd_lt
That solution would allow darkroom to handle dnd in the future too. It's not finished, as we have to show the user that dnd is not possible at all in view other than lighttable,.. (by using the drag-motion event ??)

Another possibility is to add a special "lighttable only" widget where to draw the writings of the *empty* view and to apply the dnd to this widget. But is it worth the pain ?

> Is there really no way to treat this inside thumbtable instead of spreading the issue over the views ?

I may have misunderstand how that works, but iiuc, it's not up to the source to define which receiver to allow or not...

**Comment by phweyland** [comment]
> I may have misunderstand how that works, but iiuc, it's not up to the source to define which receiver to allow or not...

Agreed. That's the receiver which decides what it wants. And this specific case lighttable wants to receive files (from outside) and not image ids.

And for each view, we should have a specific widget which chooses what it wants to receive. As you said, switching from config to config when we switch of view is not very welcome.

Hopefully I've found that "flags" in targets definition may help, if external target are really external and internal ones really internal. I push this. Doesn't solve what I call the design issue, but at least could allow to configure properly the receivers.

**Comment by AlicVB** [comment]
> Doesn't solve what I call the design issue

I think that my attempt in https://github.com/AlicVB/darktable/tree/dnd_lt sort of solve this point. Hopefully with the 2 approach concatenated, we'll arrive to something ;)
(don't hesitate to just copy-paste the part you want in my branch if needed, no need to do complex git things)

**Comment by phweyland** [comment]
> > Doesn't solve what I call the design issue
> 
> I think that my attempt in https://github.com/AlicVB/darktable/tree/dnd_lt sort of solve this point.

if I understand properly, this is in the line of having one widget receiver which has to modify its behavior each time the view is changed. That really doesn't solve the design issue. Worse for me, that tends to generalize the wrong solution. Sorry :smile: 
Each receiver should have a proper "gtk_drag_dest_set", in fact its own set of handlers.
This said, as the views are designed there may be not other solution...

**Comment by AlicVB** [comment]
> if I understand properly, this is in the line of having one widget receiver which has to modify its behavior each time the view is changed. That really doesn't solve the design issue. Worse for me, that tends to generalize the wrong solution. Sorry smile

at least it mitigate the fact that the dnd reception is define for all view inside a specific one, and it also let us define how should each view handle (or not) dnd receptions...


> Each receiver should have a proper "gtk_drag_dest_set", in fact its own set of handlers.
> This said, as the views are designed there may be not other solution...

well, there's one and it's maybe the best solution in fact : we can : 
- add another gtk_drawing_area specifically for the lighttable view.
- This widget will be added/removed from the main widget (like what we do with lib->map in the map view
- it will have the dnd reception events, specifically for it and set it to whatever we need
- the writing of the "empty" lighttable should be drawn on it, instead of in the main view widget

That way, we have something specific for lighttable independently of the other view, which is cleaner that what we want to do atm...
How does that sound ?
(I can handle the "new widget" part if you want and let you set up the dnd for it...)

**Comment by AlicVB** [comment]
> Would it be that be such a penalty to give each view its own display widget ?

that's a generalization of what I propose in my previous post... even better designed (so dnd can be set for each view without efforts or errors), but little more work :)

**Comment by phweyland** [comment]
I think we have aligned our ideas now. :)

I think the PR fixes the referenced bug and could be merged as is.

> I can handle the "new widget" part if you want and let you set up the dnd for it

If you have time, sure. If not, I can make a try...

**Comment by AlicVB** [comment]
Great !
Then maybe I can let you have a try... don't hesitate to ask me here or in the french matrix for help if needed.
I think that copying what is done in map is a good start... and if you manage to generalize that for all view...
Thanks !

**Comment by phweyland** [comment]
This time, thumbtable is always in place for lighttable and we don't need any hack to recover the case "no image".

**Review by AlicVB — CHANGES_REQUESTED** [review]
That's way more clean indeed, and really not intrusive ! Great work !

To be picky, I would just change the drawing for filmstrip : 
- either don't draw anything at all
- either hide the lines which don't point to anything in this case...

If that can save you some time, note that you can use `table->mode` to know if you are in filmstrip mode or not

**Comment by phweyland** [comment]
Thanks for the kind words.
Cleaner indeed. I'll do it.

**Comment by phweyland** [comment]
Done. I've just let "there are no images in this collection" in filmstrip.

**Review by AlicVB — APPROVED** [review]
All good for me now. Thanks again for the work !

**Review by TurboGit — APPROVED** [review]
Works for me. Thanks!

**Comment by TurboGit** [comment]
Merged in master and darktable-3.8.x branch.

**Pull request merged**
