### PR TITLE
make export format and storage widgets actions

### PR DESCRIPTION
**Pull request by dterrahe**
Convert bauhaus widgets in the guis of imageio modules to shortcuttable actions (under the _lib/export/format_ and _lib/export/storage_ hierarchies). Mostly for completeness sake, but also because it makes them somewhat scriptable in lua via _darktable.gui.action_.

Introduce a new type of action for Entries and use it to allow shortcuts to set focus to text entry fields (most in the export module, but also in watermark). Replace the shortcut to the module search box to use this type instead of a command (which required convoluted layers of proxy functions).

Separately, fix a bug introduced by https://github.com/darktable-org/darktable/commit/81c38e1b7c03ef8b1f93b9d19cff4dd32f7cf621 and https://github.com/darktable-org/darktable/commit/59307e17deb8e3cee964bb7c7450127c9d7c2eed that broke the logic to determine if a parent box was hidden. This meant some shortcuts to invisible widgets were not correctly disabled.

@wpferguson the last change allows setting the text in an entry field using dt.gui.action. If the _effect_ is "set", the content of the _element_ (which normally for an entry is always "") is used to set or insert (depending on the speed) into the text box. If speed = "" (->NAN) then the content is overwritten. If speed is 0, the text is inserted at the start, -1 at the end anything else at the specified position. For example:
`dt.gui.action("views/darkroom/search modules", 0, "rgb", "set", "")`
This only works from lua; the _set_ effect for entries is not available for shortcuts, since it is not possible to store an arbitrary text in the _element_ field (which is an enum) there.
I don't know if lua already has dedicated functions to make export formats and storage locations scriptable, but otherwise this might help. Same for modules like watermark.

### CODE REVIEW

**Comment by dterrahe** [comment]
@wpferguson would like your opinion on the need to make non-static combo elements selectable from lua. At the moment, exporting using just dt.gui.action is not fully supported since both the format and storage combos are dynamically set up, so their values are not available via "item: xxx" effects. In theory, I could try to interpret, say "item:JPEG (8-bit)" anyway, by matching it against the _current_ list of options in the combo. This wouldn't work for shortcuts, since there is no mechanism to track changes in the list, so a shortcut might become invalid later. And it has the drawback that the combo only has _translated_ strings, so changing the ui language would cause scripts to stop working.

If there is another lua api that gives full access to all export options, then I think it would not be worth offering a suboptimal alternative.

**Comment by wpferguson** [comment]
I can create a storage in lua and control the image formats and whether it uses high quality or not (https://docs.darktable.org/lua/stable/lua.api.manual/darktable/darktable.register_storage/).  The things it would be nice to control are height, width, profile, style and mode (appears when a style is selected).

**Comment by wpferguson** [comment]
Now I understand.

I would it's better not to implement something that only works part of the time.  The user can define a preset with the export format, call that as the first thing, then manipulate the configurable items, then do the export.

On that note, can you select the style and mode (mode appears after you select a style.  mode is either orverwrite or append)?

**Comment by dterrahe** [comment]
> can you select the style and mode

You can easily check what is supported by trying to create a shortcut to the widget (I use mapping mode, hover over it and triple press t), then click on it and see what's under _effect_. Anything dynamic (changeable from the user interface or dependent on installed modules) won't be; if static, it should (or might be a fixable bug).

Short answer; style no, mode yes.
image

> The user can define a preset with the export format

That's an interesting suggestion I hadn't thought of (and users might not either...). Now I wonder what happens if a preset contains a format or storage option that's not available anymore (or if a new one is inserted in the list). I suspect it just stores the order enum? Might even crash?

So, if that's the case, a dirty (but at least _obviously_ dirty, so not giving the impression of official support) workaround could be to first call the combo with effect _first_ and then with effect _next_, with _speed_ giving the number of items to skip.

**Comment by dterrahe** [comment]
@TurboGit to be clear, I'm not planning on making further changes to this PR to address storage/format limitations as discussed above. Those could be looked at more closely later if needed, together with some version of #11711, if that is still somewhat considered.

As far as I'm concerned this is ready for testing/merging.

**Comment by TurboGit** [comment]
@dterrahe : Thanks for the heads-up, I'll have a look at this soon.

**Comment by TurboGit** [comment]
I found something strange. I have assigned triple-t to the format combo.

When I triple-press t I get the pop-up. Fine.

When I triple-press t and keep it pressed, if I move the mouse left/right I do change the format. Fine.

When I triple-press t and keep it pressed, if I scroll up/down I only change in one direction (next format) but cannot move the other direction. Maybe an issue with fallback?

**Comment by dterrahe** [comment]
> Maybe an issue with fallback?

I'm not seeing that issue here. Could you please send me your shortcutsrc?

If you execute the shortcut while in mapping mode (shortcuts button pressed), it will show you the shortcut received and the fallback resolution sequence in a toast. Make sure your mouse is over the central area (not over a widget, otherwise it will try to (re)map the shortcut).

**Comment by TurboGit** [comment]
Here is my shortcutrc. 

[shortcutsrc.txt](https://github.com/darktable-org/darktable/files/9566959/shortcutsrc.txt)

**Comment by dterrahe** [comment]
Is that when you triple press hold and scroll? I.e. the action that doesn't work? This looks like you should be getting the pop-up.

**Comment by TurboGit** [comment]
Now when I scroll I get:

image

On the first line I have **up** or **down**.
The last line is always fallback **dropdown**

**Comment by dterrahe** [comment]
That looks as it should and works fine here.

Is this a regression from this PR? Does it consistently not work for _all_ combos or only this specific one? How about a different (single key press) shortcut+scroll?

If this is not related to this PR, maybe it would be better to discuss in a separate bug report so we can find out if more people are having this problem (which would help identify the cause).

**Comment by TurboGit** [comment]
I just tried without this PR:
- Using `triple-t` with scroll or mouse move => OK
- Using simple `k` with scroll or mouse move => OK

With this PR merged into my current master:
- Using `triple-t` with scroll or mouse move => OK
- Using simple `k` with scroll or mouse move => OK

So, it is working now. Maybe because I have created a new shortcut `k` now. As I have done that in another computer I'll try to check later if on the first one I have been able to reproduce the issue I still have it... More later...

**Comment by TurboGit** [comment]
On on my other computer I still have the issue, I found that there is a fallback:

image

See `Scroll down : -1`

Removing it solves the issue.

Now the question is why this was set on my side and not on yours ?

**Comment by dterrahe** [comment]
That fallback is there to reverse the direction of scrolling under a shortcut so that it goes the same way as directly scrolling in the popup. So it should be applied to both the up and down moves, whereas in your setup it was only applied to the down. It should look like this
image
which I assume your other machine has. Now that you deleted it, presumably it gets recreated when restarting dt; could you check if it looks correct afterwards (i.e. no ", down" after both scroll and vertical)? Maybe you had an old shortcutsrc lying around that was created in an early test version of inputng? I don't understand why the debugging toast showed this fallback being matched for both the up and down moves...

**Comment by TurboGit** [comment]
Indeed fallback recreated properly, all ok now.

> Maybe you had an old shortcutsrc lying around that was created in an early test version of inputng?

That's probably the case, I'm testing so many things and almost never clean-up my testing env!

**Review by TurboGit — APPROVED** [review]
So ok now, thanks for helping testing this!

**Comment by dterrahe** [comment]
> almost never clean-up my testing env!

Maybe you should reconsider this practice? ;-)

Thanks as always for the careful testing!

**Pull request merged**
