### PR TITLE
Travis Revamp - various builds & OSX support in travis

### PR DESCRIPTION
**Pull request by johnny-bit**
This is me testing travis builds so that some day all PRs can be built and tested on all platforms and all that :)

### CODE REVIEW

**Comment by johnny-bit** [comment]
Can someone help me with osx and/or windows travis builds? @parafin ?

**Comment by parafin** [comment]
I have no experience with travis. I can only point you to packaging/macosx/BUILD.txt. E.g. fro OpenMP support you need to install libomp and pass `-DOpenMP_C_INCLUDE_DIR=/opt/local/include/libomp -DOpenMP_CXX_INCLUDE_DIR=/opt/local/include/libomp -DCMAKE_LIBRARY_PATH=/opt/local/lib/libomp` to cmake.

**Comment by johnny-bit** [comment]
Good news - osx now works. now I need halp with windows :)

**Comment by johnny-bit** [comment]
Hey @TurboGit - this is imo quite ready, since widows is "allowed to fail" config and I have deeper problem with travis on windows (and also windows builds on travis are "experimental"). I've opened a topic on travis forums to help me with windows build isues: https://travis-ci.community/t/clang-cmake-make-issues-when-trying-to-build-on-windows/10202

Another thing It might be worth doing is to have additional 2 targets: release and debug so that we know all 3 codepaths are compilling properly.

**Comment by johnny-bit** [comment]
This now can be used to correctly build master and all PRs in all configs except windows. once PR #6581 is done, windows stuff can re-happen.

**Comment by TurboGit** [comment]
Thanks !

**Pull request merged**
