### PR TITLE
fix starting in full screen on windows

### PR DESCRIPTION
**Pull request by TurboGit**
@wpferguson : Can you test this? TIA.

### CODE REVIEW

**Comment by wpferguson** [comment]
@TurboGit what was the problem this was fixing, or in other words how will I know if the fix worked or not?

I've started 4.6.0, switched to fullscreen (F11) and killed it with alt-F4.  Restarted it with no problems.  Changed window to maximized and stopped and started it with no problems.  This was on Win10.  Do I need to test on Win11?

**Comment by wpferguson** [comment]
Let me guess...

The problem is when you open a single image in darktable it immediately goes to darkroom and leaves a command window hanging on the screen.

**Comment by wpferguson** [comment]
The hanging window was due to a script_manager bug.  Fixed the bug, updated the scripts and it doesn't happen any more.

**Comment by TurboGit** [comment]
Here is a description of the issue:

1. start dt
2. press F11 to switch to full screen
3. press Alt-F4 to close
4. start dt again
expected: starts in full screen mode (this works on linux)
actually happening on windows: starts in a window that does not have title bar (and so no maximize etc buttons). Have to press F11 twice to get to full screen.

**Comment by wpferguson** [comment]
I tried that with 4.6.0 in win10 and 4.5.0+962 in Win11 and didn't see that problem.  I'm running in a VM without opencl.  I wonder if it could be related to that.

Testing the PR, everything worked fine.

Maybe @kmilos or @victoryforce are running windows on bare hardware and can test.

**Comment by zisoft** [comment]
Just tried that on my windows setup and cannot reproduce on current master.
F11 gives fullscreen mode. Quitting and restarting, dt comes up in fullscreen mode.
Pressing F11 (once) comes back to a normal window.
No difference with this PR.

The fullscreen mode is of course different from a maximized window. In fullscreen mode there is no title bar and thus no minimize/maximize buttons. So the only way to get out of fullscreen mode is to press F11 again (which the user needs to know).

**Comment by victoryforce** [comment]
> Maybe @kmilos or @victoryforce are running windows on bare hardware and can test.

Yes, I'm running Windows on bare hardware. I have Windows 10, latest updates. I have no opportunity to test on Windows 11 yet.

I could not reproduce the behavior before this PR as described by @TurboGit (launching in a window that does not have a title bar, that is). For me, there is no difference in the behavior of the program before this PR and with it.

**Comment by kmilos** [comment]
Can't reproduce here either, 4.7.0+364~ga8763b1498 on bare Windows 11 22H2: starts in full screen again (covered by taskbar though since started from terminal), and only one F11 press is needed to leave full screen.

**Comment by TurboGit** [comment]
So closing, thanks all for testing.

**Pull request closed without merging**
