### PR TITLE
noiseprofiles.json requires amendements for Nikon cameras to work properly

### PR DESCRIPTION
**Pull request by GLLM**
Hi

I hope I'm doing things the right way !

* Split Nikon maker section into "NIKON CORPORATION" for DSLRs and "Nikon" for other cameras.
image

I'm not sure if the binary capitalizes maker names before looking up for a profile. I let Nikon uncapitalized, as it was.

* Change DSLR model names from "Dxxx" to "NIKON Dxxx"
image

Note : not sure how Z mirrorless cameras are named, as well as what maker they are attached to ... Consequently, I did not impact the config for Z6 & Z7.

Tested with pics from my D600 ... worked ... at last :)

Thanks
GLLM

### CODE REVIEW

**Comment by TurboGit** [comment]
I have real doubts about this as the noise profiles have been working for many people since a long time. I had a Nickon D300, D800 & D850 now and I have no issue.

So first before fixing something can you create an issue and discuss what is broken ? TIA.

**Comment by GLLM** [comment]
Hi @TurboGit 
I was going to book an issue, and then thought that maybe providing, even if it's dismissed, a solution would be more proactive...

No problem with me to cancel this PR and insert an issue for the topic to be discussed.
I'll do so tonight.
Thanks 
GLLM

**Comment by TurboGit** [comment]
Thanks !

**Comment by GLLM** [comment]
Just logged #6644 ;-)

**Pull request closed without merging**
