### PR TITLE
Move wb presets into an external JSON file (data/wb_presets.json).

### PR DESCRIPTION
**Pull request by TurboGit**
The JSON file is checked against a schema for validity. The only
module using this is the module temperature which has been migrated
to this new API.

For #11831.

Note that a possibly controversial part is in there as I have used capitalized strings for the presets naming. If you don't want to see that we can lower case the preset name while loading them from the JSON.

Also, not yet done there is the sharing of the make/model schema with noise profiles JSON.

Last, I have used a list of name (enum) for the preset name to ensure that we have the name translated (see strings at top of common/wb_presets.c), but this somehow look strange as there is many kelvin number like 4500K.

### CODE REVIEW

**Comment by HansBull** [comment]
Maybe there could be a speed gain by either a cache mechanism or re-ordering the white balances on load, taking into account the cameras and models present in the database? Search would terminate much earlier if the camera the user usually uses was at the beginning of the list.

**Comment by TurboGit** [comment]
@HansBull : Not a good idea to me. First the load time is taking 20ms and if you try loading pictures from a new camera the WB won't be present. Having mechanism to check for the existence of WB in the table and doing late loading will add a lot of complexity with no gain.

**Comment by TurboGit** [comment]
> Also, not yet done there is no sharing of the make/model schema with noise profiles JSON.

I don't see a support for external (or multiple schema) in jsonschema the tools used by dt to validate the JSON data.

**Comment by TurboGit** [comment]
I have reverted the enum for the WB preset names and resorted on using a pattern. Not as readable but at least this code all the case of naming using Kelvin : 5500K

At this stage if no objection this is ready for merging.

**Comment by TurboGit** [comment]
I'll revert the capitalized preset names to keep UI consistent. I'll use a second commit which could easily be reverted when the UI is capitalized (see #12281).

**Comment by TurboGit** [comment]
BTW, I will merge this after 4.0.1 is released to have the possibility to add WB presets in 4.0.1 if necessary. I'll backport the new WB if needed into the JSON format.

**Pull request merged**
