### PR TITLE
database v34

### PR DESCRIPTION
**Pull request by HansBull**
datetime_taken: various queries in timeline and collection will now use a covering index shaving off already some 30ms per query on a 15k images collection. Larger collections will benefit. Should lead to more snappiness browsing by date or timeline. 

metadata: cuts down the subquery in collection.c:1058 to half for 15k images (25 ms => 12 ms). Adding `value` as a second column would not yield benefits, as it is queried with `LIKE %%string%%`

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Looks ok to me, thanks!

**Comment by phweyland** [comment]
Hi @HansBull 
I'm trying to update the images table.
The first issue I've met is the failure to drop the copied images_old table.
Using PRAGMA foreign_keys = OFF / ON I was able to drop it off.
The next issue is the following: all tables with constraints referencing images table are now referencing images_old table, like this:

image
How do I get rid of this ?

**Comment by HansBull** [comment]
It might be necessary to drop and recreate them (not that nice, I know). Don't know currently if there's another way.

**Comment by HansBull** [comment]
Hmmm... https://stackoverflow.com/questions/67006159/how-to-re-parent-a-table-foreign-key-in-sqlite-after-recreating-the-parent

**Comment by phweyland** [comment]
Got it !
Instead of renaming images to images_old, I create images_new, update it, drop images, and rename images_new to images.
Hoping there is no specific constraint about the sqlite version.
Thanks

**Pull request merged**
