### PR TITLE
midi keys mapped to module header reflect status

### PR DESCRIPTION
**Pull request by dterrahe**
If a midi button with a light is mapped to a module header button that enables, expands or focusses the module, then its light will reflect the current status. So it will light up if the module is in enabled, expanded or focused state.

I was reminded this needed to be implemented by #10475.

### CODE REVIEW

**Comment by TurboGit** [comment]
@dterrahe : What's your view on this? Is that bugfix? Looks like a feature to me... So maybe for 4.0?

**Comment by dterrahe** [comment]
Sure! No hurry/low priority.

**Comment by dterrahe** [comment]
Also set midi buttons lights correctly when they are mapped to a bauhaus button (for example color picker).

Support shortcut effects to always turn on or always turn off as well as toggling the button.

**Review by TurboGit — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
