### PR TITLE
lut3d update

### PR DESCRIPTION
**Pull request by phweyland**
- move the lut 3d folder definition from configuration to lut3d module
- static routines reformatting

related to discussion in #4747 about preferences

### CODE REVIEW

**Comment by phweyland** [comment]
image

**Comment by TurboGit** [comment]
Why not keep the global prefs as the default and still allow the redefine it in the Lut3D module as done here? At least it gives a default and don't require to redefine it all the time.

**Comment by parafin** [comment]
What is exactly the point of this setting? Is it a base path, while only relative path is saved in iop params? Then changing it might break existing history stacks. I think decision where to put this setting should come from description of how it works and should be used (use-case).

**Comment by phweyland** [comment]
>  Is it a base path, while only relative path is saved in iop params? Then changing it might break existing history stacks.

Yes, that's exactly that.  In that sense it should be in configuration and, once set, forgotten. If the user changes it that breaks all existing iop params except if the user has moved this folder and just updates the new location.

But I've seen some complaints of people saying the module did not work while they had not set the base path on configuration.

Last, the default setting of folder in configuration is not very strong. It is enough to open configuration (without touching the lut 3d root folder) to make the flag configuration set (on my machine I get plugins/darkroom/lut3d/def_path=/home/philippe in darktablerc just opening the configuration). This breaks the initialization control (as it hasn't been intentionally set). At least I haven't found the way to make it work better. On the other hand, inside the module (and removed from global configuration) I can control properly the initial setting.

I'm happy with this setting in the module, but without this last issue I would not have moved it out from configuration.

Thoughts ?

**Comment by elstoc** [comment]
On reflection I'm not entirely convinced it makes sense to have a global parameter set inside a module.  Without knowing the details I'd assume that setting was specific to the current image, and that the 'reset parameters' option would reset it back to its previous value.

**Comment by parafin** [comment]
If it shouldn't be modified once set except when user changes something in his system, it's obviously should be in preferences and not in iop GUI. Having it in IOP GUI invites user to change it every time.

**Comment by phweyland** [comment]
OK, I'll close this PR.

About the following issue any idea to solve it ?

> Last, the default setting of folder in configuration is not very strong. It is enough to open configuration (without touching the lut 3d root folder) to make the flag configuration set (on my machine I get plugins/darkroom/lut3d/def_path=/home/philippe in darktablerc just opening the configuration). This breaks the initialization control (as it hasn't been intentionally set). At least I haven't found the way to make it work better. On the other hand, inside the module (and removed from global configuration) I can control properly the initial setting.

**Comment by elstoc** [comment]
The default for this parameter is empty so I assume (without looking at the code) it must be something specific about how the config manages directory entries. Perhaps I could look at it with my parameter overhaul.

**Comment by phweyland** [comment]
> The default for this parameter is empty so I assume (without looking at the code) it must be something specific about how the config manages directory entries. Perhaps I could look at it with my parameter overhaul.

What I need to be able is to be confident on the dt_conf_key_exists().
So far, as said above, it's enough to open configuration / core options to make it existing.

**Comment by elstoc** [comment]
You couldn't do something based on the stored value rather than using dt_conf_key_exists()?

**Pull request closed without merging**
