### PR TITLE
RFC: getting rid of the 'auto-apply sharpen' option in preferences

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
As
1. for the vast majority of cameras around the sharpen module is not suggested to be used
2. we now have better ways to sharpen as in D&S for those sensors that would require it

i suggest to completely remove the option from preferences menu.

Open for discussion ...

### CODE REVIEW

**Comment by jwgarber** [comment]
I agree. The documentation for the [sharpen](https://docs.darktable.org/usermanual/3.8/en/module-reference/processing-modules/sharpen/) module says it is no longer recommended, so as a new user it surprised me that it is applied by default.

**Comment by elstoc** [comment]
Also we don't need preferences to apply stuff by default, we have other mechanisms for that.

**Comment by Jiyone** [comment]
True, I've already unchecked all auto stuff here.

**Comment by tpinfold** [comment]
What about instead of getting rid of the auto sharpen option ( which I have unticked) we have the option to apply the sharpening and denoising options that we like? I know I can do this as a style, but for most of my images I apply sharpen  demosiacing (AA filter) and noise (profiled) defaults with pleasing results. I would be happy to just have a couple of tick boxes in the preferences for this.

**Comment by elstoc** [comment]
> we have the option to apply the sharpening and denoising options that we like?

That's what presets are for

**Review by TurboGit — APPROVED** [review]
Fine by me, thanks!

**Comment by aurelienpierre** [comment]
That may break older edits. Prior to 3.0, the "always on" modules with default parameters (no user change) did not leave an entry in history and relied on the program to do the right thing. That deserves at least a mention somewhere where users will find it.

**Comment by elstoc** [comment]
> That deserves at least a mention somewhere

It was white balance (and the legacy/modern CAT setting) where this was first discovered wasn't it? So potentially an existing issue, though I'm not entirely convinced it will happen with this preference (I don't remember the exact reproducer now though).

You did start writing a "known issues" section for dtdocs but didn't respond to my review (or my IRC chases). Perhaps worth looking at that again.

**Comment by jenshannoschwalm** [comment]
> That may break older edits. Prior to 3.0, the "always on" modules with default parameters (no user change) did not leave an entry in history and relied on the program to do the right thing. That deserves at least a mention somewhere where users will find it.

I simply didn't have this in mind because it never was "always on"..
But where in the manual?

**Comment by TurboGit** [comment]
I didn't remember that, but indeed prior to 3.0 the module with default params where not stored. I've been facing that when rewriting the module order support. So we need to revert part of this PR to only remove the pref from the dialog.

**Comment by TurboGit** [comment]
But this needs some testing as I'm not sure we have an issue after all. When coming from the db the modules are added during the migration, so it should be ok. When importing an XMP I'm not sure what is happening and in which order so this case is probably to be checked carefully.

**Comment by jenshannoschwalm** [comment]
The problem for me is, if having an old edit without sharpening history included, the result while doing a fresh edit would be "don't apply sharpen" whatever the UI setting would be. Or is this wrong?

**Comment by aurelienpierre** [comment]
I think this is no issue since the defaults params of sharpen are so subtle, the effect is visible only zoomed 1:1, and I have always considered this module to be a loss of CPU cycles (you need to keep it super soft because it's so keen on edge artifacts). My opinion is break it but advertise it.

Actually, the right way I think would be to detect if the DB edit was done before 3.0 (dt version number is in the history, at least for XMP) and open a pop-up warning about white balance and sharpen.

**Comment by darkbasic** [comment]
Since previously we had sharpening enabled by default, wouldn't be better to have diffuse or sharpen enabled by default?

**Comment by jenshannoschwalm** [comment]
Certainly not :-) The reason for sharpen=on was historic (old cameras "required" that).

**Pull request merged**
