### PR TITLE
rawprepare: mono demosaiced image still have all the channels

### PR DESCRIPTION
**Pull request by kmilos**
Related to https://github.com/darktable-org/darktable/pull/14248

### CODE REVIEW

**Review by TurboGit — COMMENTED** [review]
The changes are ok, but what does it fixes exactly? What should I test? TIA.

**Comment by jenshannoschwalm** [comment]
Please remember the debayered cameras and how they are supported via demosaic passthru and tag setting. (Pretty weird stuff i know)

**Comment by kmilos** [comment]
For Bayer images currently, when you put demosaic to passthrough (mono), the rawprepare drops to a single channel black level correction.

I think this is a bug - before demosaic (of any kind), the image still has 4 channels so the controls in all the modules before demosaic should remain as is.

**Comment by kmilos** [comment]
And I think I found another bug now - once you set demosaic passthrough on a CFA input, it seems to flag the image as B&W permanently - resetting the demosaic module does nothing, and neither going back to original in the history stack...

**Comment by kmilos** [comment]
Aren't those already detected and `DT_IMAGE_MONOCHROME` flag set in `imageio_rawspeed`? If not, can you share what camera?

If yes, this change doesn't affect those... Note that I'm not changing anything about demosaic functionality.

**Comment by jenshannoschwalm** [comment]
They are not. Files are identical to normal raws. It's a modified camera hardware at the Sensor. Not many around but for those we have the passthru mono demosaicers.

**Comment by kmilos** [comment]
Ok, that explains it then, thanks. Dropping.

**Comment by jenshannoschwalm** [comment]
https://petapixel.com/2022/02/23/ricoh-grm-my-custom-monochrom-camera/

**Pull request closed without merging**
