### PR TITLE
Introduce dt_dump_pfm() as a developers helper

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
At various places in darktable we use some pfm file writing for intermediate results of processing modules.
These writes are switched on/off at compile time, it might be worth to investigate such intermediate data without recompile cycles.

Also deduplicates code.

This pr

1. introduces a darktable runtime switch `--dump-pfm <modname>`
2. implements 
``` 
void dt_dump_pfm(
      const char *filename,
      const float *data,
      const int width,
      const int height,
      const int channels,
      const char *modname);
```
   that can write masks or rgb data.
   The file written will always be at: `/tmp/darktable/<modname>/<filename>.pfm`

3. some minor code cleanup

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
Would be one of the helpers discussing/developing/evaluating the pending scaling issue ...

**Review by TurboGit — COMMENTED** [review]
Looks good clean-up to me. One question don't you think we could have this in pixelpipe code to dump input & output of the given module? I don't mean to replace what is there as you're dumping intermediate data, but as a general debug help too.

**Comment by jenshannoschwalm** [comment]
> One question don't you think we could have this in pixelpipe code to dump input & output of the given module?

Yes, that would be possible & possibly helpful. like

1. switch on with `-d dumpmod finalscale`
2. write images either in fullpipe or export mode

Although i would only want that for non-gpu code, otherwise very tricky (p-pipe bugprone)

**Comment by TurboGit** [comment]
Understood, I'll merge this now. Thanks.

**Pull request merged**
