### PR TITLE
Add a way to style with CSS thumbs bg when image is rejected.

### PR DESCRIPTION
**Pull request by TurboGit**
Part of #9518.

### CODE REVIEW

**Comment by Nilvus** [comment]
Actually, that breaks CSS for rejected image but we can consider that a WIP and wait for @AlicVB feedback probably about your comment in #9518

**Comment by elstoc** [comment]
Generally classes are better for styling than names, since you can have multiple classes

**Comment by TurboGit** [comment]
> Actually, that breaks CSS for rejected image

I'm not sure about this. If the CSS for rejected image `thumb_back_rejected` is equivalent to `thumb_back` all should be as it is on current master? And so one can adjust `thumb_back_rejected` to have a slightly different rendering. No?

But I agree that I would prefer a full thumb to be rendered dimmer.

**Comment by Nilvus** [comment]
> > Actually, that breaks CSS for rejected image
> 
> I'm not sure about this. If the CSS for rejected image `thumb_back_rejected` is equivalent to `thumb_back` all should be as it is on current master? And so one can adjust `thumb_back_rejected` to have a slightly different rendering. No?
> 
> But anyway better having a full thumb to be rendered dimmer.

No it isn't. Just compare visually, to begin, hover effect on master and with your PR for rejected images. But it's normal, if image is rejected, `thumb_back_rejected` replace `thumb_back` and there's no `thumb_back_rejected` added in CSS with your PR. That's why CSS is broken for rejected image (only in thumb_back part of course).

That's no big deal finally as we had not really decided how thumb back should be rendered visually for rejected images.

**Comment by Nilvus** [comment]
@TurboGit: just 2 things:

- I agree with @elstoc comment, so needs to be updated and add a class style instead of changing id name
- it would be better to add a class style for `thumb_main` than changing `thumb_back`. With thumb_main, that would allow more possibilities than just thumb_back. Actually we can so update CSS for background around the image but not fading the image or change other parts for rejected images

**Comment by Nilvus** [comment]
@TurboGit: do you have some update with requested changes possible in following days? I'm just asking as I have some minor CSS updates to provide and would be better with a single PR when this one will be merged.

**Comment by TurboGit** [comment]
@Nilvus : No I won't have something soon, I'd like @AlicVB feedback as adding a layer on top of a thumb to play with transparency is not something I'm good at :)

**Comment by AlicVB** [comment]
@TurboGit : I've done an attempt in #9890 
Finally, I've just drawn the image with transparency. It's way simpler and I think it's sufficient here...
I've also extended your class proposal a little bit by handling all the rating values, not only the rejected one...

**Pull request closed without merging**
