### PR TITLE
iop/lens: fallback to another method if not available when modified is 0

### PR DESCRIPTION
**Pull request by sgotti**
@TurboGit this should go after #12841 (it also contains its commit).

This change is debatable and also "confusing". I'll try to do my best to explain it. And I'd like to ear your thoughts or better ideas.

---

Fallback to another correction method if "modified" is 0 and the current
image cannot handle the method set in the parameters.

The rationale in this change is that if an user enables only the lens
module or changes only the "method" it probably just wants that lens
correction will be applied regardless of the selected method and
expectes that a preset should do the same.

The same is applicable to images xmp instead of presets when something
changes (darktable not compiled with lensfun, embedded metadata not
found due to changes in darktable code, image exif data manually
modified etc...)

**NOTE**: A case that isn't possible to handle instead is if an user wants to
apply ONLY the selected method and don't fallback. This will require an
option in the gui like "fallback to another method" but this will be
confusing since it isn't clear when this will happen (since it's not
related to the current image being developed but to preset applied on
another images or something that changed in darktable embedded metadata
code or compiled without lensfun).

Example issue fixed with this change:

* User enable the "lens" module in an image. The gui, depending on the
  image the user is working on, will choose "embedded metadata" (default
  if available on the image) or "lensfun" method.

* a. The user won't change anything in the module and saves a preset. It'll
  be saved with "modified" == 0 and choosed default method.

* b. The user only changes the method and saves a preset. It'll
  be saved with "modified" == 0 and choosed method.

Before this patch behavior:

If the method saved in the preset is "embedded metadata" and it's
applied to an image without "embedded metadata" nothing will be
corrected (plus ui glitches since it'll show the "embedded metadata"
widget).

If the method saved in the preset is "lensfun" and it's
applied using a darktable not compiled with lensfun and the image has
"embedded metadata" nothing will be corrected (plus ui glitches since
it'll show the "lensfun" widget).

After this patch:

If the method saved in the preset is "embedded metadata" and it's
applied to an image without "embedded metadata" it'll fallback to
"lensfun" method.

If the method saved in the preset is "lensfun" and it's
applied using a darktable not compiled with lensfun and the image has
"embedded metadata" it'll fallback to "embedded metadata".

### CODE REVIEW

**Comment by parafin** [comment]
Is there a good reason for lensfun dependency to be optional? It always struck me as strange for some iop to be optionally present - it means history stacks aren’t transferrable in general case…

**Comment by sgotti** [comment]
> Is there a good reason for lensfun dependency to be optional? It always struck me as strange for some iop to be optionally present - it means history stacks aren’t transferrable in general case…

I won't talk about the choice of making lensfun optional or not since I can see good reasons behind it (and it's there from the start of the lens module).

History stacks are transferrable but not "reproducible" since no lens collection is applied if darktable isn't compiled with lensfun.

But I'd like to add that also if lensfun will be mandatory there can be many other variables that can cause not reproducible outputs:
* lensfun db changed
* lensfun math changed (see 0.3.95 vs 0.3.3)
* Another really strange example: On my system the lensfun integration test is the unique that fails since the generated images is visibly identical but the compare and deltaE outputs are different (more than 100000 different pixels). Additionally I tried to use the same libraries used by the CI without success and also noticed that the output of lensfun changes if you enable/disable its SSE code paths.
* The same applies with metadata correction without #12844 if the image is already in the db and the image isn't refreshed

**Comment by parafin** [comment]
> History stacks are transferrable but not "reproducible" since no lens collection is applied if darktable isn't compiled with lensfun.

Well, it’s just terminology, you can call it “reproducible” if you want.

> But I'd like to add that also if lensfun will be mandatory there can be many other variables that can cause not reproducible outputs:
> 
> * lensfun db changed

It only matters for “unchanged” correction (though maybe it covers majority of cases) and shouldn’t happen often. In any case it shouldn’t be as dramatic as on vs off effect.

> * lensfun math changed (see 0.3.95 vs 0.3.3)

This is lensfun bug and one mustn’t use 0.3.95 or master lensfun, I think we are clear on that.

> * Another really strange example: On my system the lensfun integration test is the unique that fails since the generated images is visibly identical but the compare and deltaE outputs are different (more than 100000 different pixels). Additionally I tried to use the same libraries used by the CI without success and also noticed that the output of lensfun changes if you enable/disable its SSE code paths.

Some rounding or whatever mismatch doesn’t matter, the goal was never bit-equality of the output, because it would put too much constraints on performance optimisations (e.g. CPU vs OpenCL paths).

> * The same applies with metadata correction without [imageio/rawspeed: always read additional exif tags #12844](https://github.com/darktable-org/darktable/pull/12844) if the image is already in the db and the image isn't refreshed

This is basically a darktable bug.

My point is that there is an agreed (I think) goal of history stacks being forward-compatible, meaning user should only care about darktable version when transferring the edits, not any other parameters, like OS he is using or CPU architecture. Having an optionally-compiled iop IMHO defeats this purpose for no good reason (or is there such reason?). There are some other minor exceptions like history depending on external files (e.g. watermark), but they usually have a technical reason, which isn’t obvious how to overcome. Making lensfun mandatory dependency is easy, and this PR is a also a good additional reason to do it - to avoid adding code complexity (really, there is enough of that in darktable already).

**Comment by sgotti** [comment]
> Making lensfun mandatory dependency is easy, and this PR is a also a good additional reason to do it - to avoid adding code complexity (really, there is enough of that in darktable already).

Yeah. It'll simplify things a lot.

But since "embedded metadata" is not available for all image there's a remaining case to handle:
* user enables lens module, has "embedded metadata" method selected and saves a preset (modified == 0).

What should happen when the preset is applied to an image not supported by "embedded metadata" method?
a. Ignore it like now and don't do any correction BUT fix the ui glitches and add a warning.
b. fallback to lensfun like done in this PR?

**Comment by TurboGit** [comment]
> Is there a good reason for lensfun dependency to be optional?

It has always been the case, but we certainly want to review this decision. AFAIK, lensfun is available on all OS and has not caused issues since years. So as for @parafin it is probably better to make it mandatory and simplify the logic in lens correction module to cover all the cases.

> What should happen when the preset is applied to an image not supported by "embedded metadata" method?
> a. Ignore it like now and don't do any correction BUT fix the ui glitches and add a warning.
> b. fallback to lensfun like done in this PR?

I would go for **b** like in this PR.

**Comment by jenshannoschwalm** [comment]
**b** for me.

**Comment by TurboGit** [comment]
@sgotti : I'd like this to be part of 4.2, but time is running out for the feature freeze. Do you think you can do:
- Make lensfun mandatroy
- Do cleanup in lens module based on the fact that we know lensfun is always available (probably this should simplified some parts, even though I haven't looked at this).
- Add the fallback to lensfun when no metadata is available and modifier=0 (and do nothing when modifier=1).

Did I missed something?

Does that sounds possible to you?

**Comment by sgotti** [comment]
@TurboGit Looks good and I should be able to do this in the next days. 

I think that this could be merged as is since it's small and already contains the fallback to lensfun that's needed anyway and then do the lensfun mandatory stuff and cleanup in another PR.

**Comment by TurboGit** [comment]
Please never merge master or any other branches into a topic branch (this is to keep history of topic branch clean), you should rebase. TIA.

**Comment by TurboGit** [comment]
Ok, you've squashed everything together, so not a problem anymore :)

**Comment by sgotti** [comment]
> Please never merge master or any other branches into a topic branch (this is to keep history of topic branch clean), you should rebase. TIA.

Sorry, I know and also hate it but, stupid github, I clicked something accidentally...

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
