### PR TITLE
make inputng and introspection resilient to uppercasing

### PR DESCRIPTION
**Pull request by dterrahe**
in case something like #13609 happened

with some action definition/translation fixes in lighttable that would need to be submitted separately if this doesn't get merged.

### CODE REVIEW

**Comment by TurboGit** [comment]
Is this still needed as a generic improvement even though #13609 is closed?

**Comment by dterrahe** [comment]
Not _needed_ but it does make the code more robust and forgiving in case someone manually edits shortcutsrc or a lua script calling `dt.gui.action`. It would be of help if #12243 or #13618 confused people into thinking they could use upper case for action paths in those two situations, but also if #13609/#12281 is tried again in future when I'm no longer around.

A quick timing check suggests this doesn't significantly impact performance so seems "safe".

**Review by TurboGit — APPROVED** [review]
Will look at this.

**Review by TurboGit — APPROVED** [review]
Ok, works for me.

**Pull request merged**
