### PR TITLE
Bugfixing and don't prepare opposed for segmentation in sraw images

### LINKED ISSUE #12692: roi issue with inpaint opposed & crop
when using inpaint opposed (as well as segmentation based highlight reconstruction) in combination with crop the right side of the image turns black
[mire1.cr2.xmp.txt](https://github.com/darktable-org/darktable/files/9845109/mire1.cr2.xmp.txt)

the behaviour is dependent on the crop - playing around with more or less crop in hight or width results in proper crops but also in misbehaviour. Quite reproducible bis 16:9 ratio if the crop area has some space to the top ...

**To Reproduce**
1. open mire1.cr2 from tests/images
2. apply inpaint opposed highlight reconstruction
3. apply crop (e.g. 16:9) center aligned

**Screenshots**
image

**Which commit introduced the error**
```
1cb4f1afe3a7125955b13a9457b7335a97b5bf9f is the first bad commit
commit 1cb4f1afe3a7125955b13a9457b7335a97b5bf9f
Author: hanno@schwalm-bremen.de <hanno@schwalm-bremen.de>
Date:   Fri Oct 21 19:35:54 2022 +0200

    Proper fix for highlights reconstruction ROI problems

    As reported in #12667 there were crashes in opposed or segmentation based code.

    There has been a previous pr #12670, that one has become a mess but is a
    valuable resource to understand the problems.

    In short; the mentioned algorithms require all image data for a stable
    calculation of chromacity correction (opposed) and the segmentation
    analysis and recovery code.

    Thus we have to change the roi_in to "take it all".
    But - and that has been the problem of current code - the roi_out can be
    extended (for example by demosaic rounding for xtrans sensors).
    This results in a situation where the roi_out area is not fully inside roi_in.

    This can't be properly fixed in the modify code, we have to check for the
    proper output range in the algorithms.

    Fixes #12667

    Replaces #12670

 src/iop/highlights.c    |  19 ++++-----
 src/iop/hlrecovery_v2.c |  58 +++++++++++++++-----------
 src/iop/opposed.c       | 107 +++++++++++++++++++++++++++---------------------
 3 files changed, 101 insertions(+), 83 deletions(-)
```
**Platform**
* darktable version : darktable 4.1.0+614~g832272359
* OS                : OSx

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
I spent some time testing segmentation recovery also for sraws.
That works of course but there is a large performance penalty, also the segmentation algorithm does't work well.
It would require larger combining (definitely much slower) and different "magics".
So a no go from here because of too heavy code maintenance burden. The benefit of this is a slightly better performance of the inpaint opposed.

Also various minor fixes.

Fixes #12692

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
Will try to fix #12692 too in this pr

**Comment by jenshannoschwalm** [comment]
Latest commit fixes stupid cropping issue ...

Ready to go

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Comment by TurboGit** [comment]
@jenshannoschwalm : For the record, now that the algorithm are stable I have added two integration tests, one for the segmentation based algo and the other for the inpaint opposed one.

**Pull request merged**
