### PR TITLE
Add column fullthumb_hash into main.history_hash.

### PR DESCRIPTION
**Pull request by TurboGit**
For supporting the thumb crawler updater.

Part of #15294.

### CODE REVIEW

**Comment by TurboGit** [comment]
@jenshannoschwalm : I have add a column as INTEGER as discussed. The other hashes are BLOB, so maybe it would be better? Let me know.

**Comment by jenshannoschwalm** [comment]
Yes. For consistency

**Comment by TurboGit** [comment]
> Yes. For consistency

Done. Default value when not initialized is NULL.

**Comment by TurboGit** [comment]
@jenshannoschwalm : You can cherry-pick this in your PR or I can merge this if you feel it is ok. Let me know.

**Comment by jenshannoschwalm** [comment]
I'd prefer if you merge, pretty sure this is fully sufficient...

**Comment by TurboGit** [comment]
Merged!

**Pull request merged**
