### PR TITLE
masks behavior

### PR DESCRIPTION
**Pull request by edgardoh**
This changes are ported from PR Retouch GUI #1550:

-resize don't care where the mouse is inside a shape
Right now, to change the size of a shape, the mouse must be over the "body" of the shape, if it is over the feather, the feather is changed. The feather is also changed when pressing SHIFT, even if the mouse is over the body.
I have changed this so now the size is changed even if the mouse is over the feather, and the feather can only be changed pressing SHIFT.
When there's a lot of small shapes close to each other is difficult to select just the body of a shape, so sometimes I change the feather instead of the body, this change makes the work easer.

Changes in size & step

brush:
I have changed the step from:
float amount = 1.25f;
if(up) amount = 0.8f;
to:
float amount = 1.03f;
if(up) amount = 0.97f;

and the border from:
masks_border = MAX(0.005f, MIN(masks_border * amount, 0.5f));
to:
masks_border = MAX(0.0005f, MIN(masks_border * amount, 0.5f));

this allows to have a smaller brush and more control over the size. For small details I sometimes have to use the path because the brush is not small enough, when the brush will be the right tool for the job.

circle:
I have changed the minimum border size from:
if(up && circle->border > 0.001f)
to:
if(up && circle->border > 0.0005f)
this allows to have a harder border.

When the circle is created I have changed the minimum values from:
circle->radius = MAX(0.01f, circle_size);
circle->border = MAX(0.005f, circle_border);
to:
circle->radius = MAX(0.001f, circle_size);
circle->border = MAX(0.0005f, circle_border);
so the new created circle will have the same values as the last one, even if it is very small, otherwise I'm forced to change the size and feather of every new circle when working with small shapes.

path:
I have changed the minimum border size from:
masks_border = MAX(0.005f, MIN(masks_border * amount, 0.5f));
to:
masks_border = MAX(0.0005f, MIN(masks_border * amount, 0.5f));
this allows to have a harder border.

### CODE REVIEW

**Comment by TurboGit** [comment]
I really like this. Just need a bit more time for testing and more feedback would be nice.

**Comment by edgardoh** [comment]
> Everything looks good except for the harder edge of the circle mask : it
> creates aliasing on the edge, even with lanczos 3 interpolation
>
Where, the heal, clone, fill, blur?

**Comment by aurelienpierre** [comment]
I tested it in the exposure module. Does that change only affects the retouch module ?

**Comment by edgardoh** [comment]
> I tested it in the exposure module. Does that change only affects the
> retouch module ?
>
No, but that's how draw masks work, you can duplicate it on the current
version.

**Comment by TurboGit** [comment]
Been using this and looks good to me. Indeed this make it possible to more easily select a mask when lot of them are close to each others. Time for a wider field testing. Thanks.

**Pull request merged**
