### PR TITLE
metadata: don't lose edited values while hovering other images

### PR DESCRIPTION
**Pull request by phweyland**
- save edited value(s)
- show hovered images' values
- restore edited value(s) after hovering
- markup label of edited value to highlight it \<i\>\<u\>

### CODE REVIEW

**Review by TurboGit — CHANGES_REQUESTED** [review]
Found an issue:
- selected 3 images
- change the author to say **notme**
- fly over images, all good values are properly displayed
- go back to the author field, **notme** is displayed, all good
- type enter, seems to work
- fly over the changed images and you'll see that the author as not been changed

**Comment by phweyland** [comment]
Humm.. cannot reproduce it.
I've tried clicking on the field or not (on your step 4). That works for me.
If I click on another field and enter, the former field stays in editing mode.

**Comment by TurboGit** [comment]
I cannot reproduce now on my side. And I had tried multiple times before, really strange!

**Comment by TurboGit** [comment]
Do you agree that this is more a new feature and should be in 4.2 as we are in feature freeze?

**Comment by phweyland** [comment]
> Do you agree that this is more a new feature and should be in 4.2 as we are in feature freeze?

Yes, indeed.

**Comment by TurboGit** [comment]
@phweyland : This PR needs a conflict resolution otherwise ready to be merged. TIA.

**Comment by phweyland** [comment]
Rebased !

**Review by TurboGit — APPROVED** [review]
Thanks a lot @phweyland! Works for me.

**Pull request merged**
