### PR TITLE
Rastermask fixes 44 3

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Fixing remaining issues as reported in #14271 

1. 1st commit: We must invalidate cachelines with higher iop-order whenever we change the raster mask source. Also if we select "none"
2. Some improvements for "importance hints" debug logs. (openCL)

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Looks good, thanks!

Merging to ensure @s7habo will be able to test as soon as possible.

**Comment by s7habo** [comment]
Thanks for the effort, but unfortunately the issue is still there

**Comment by jenshannoschwalm** [comment]
Oh man. What do i do differently?

**Comment by s7habo** [comment]
> Oh man. What do i do differently?

 Please read the comment here:
 https://github.com/darktable-org/darktable/issues/14271#issuecomment-1556631184

**Pull request merged**
