### PR TITLE
In dual demosaicing VNG must always do the vng interpolation

### LINKED ISSUE #9101: Dual demosaic increases coarse noise
**Describe the bug/issue**
Turning on dual demosaic seems to increase noise. For example:
* Amaze: 
* VNG4: 
* Amaze+VNG4:
  * Threshold = 0.2: 
  * Threshold = 0 (should give pure Amaze, if I understand correctly): 
  * Threshold = 1(should give put VNG4): 

More examples at https://tech.kovacs-telekes.org/files/2021-05-29-darktable-dual-demosaic-noise/

Also, colour smoothing options are not available with dual demosaic.

**To Reproduce**

1. Download the raw from https://tech.kovacs-telekes.org/files/2021-05-29-darktable-dual-demosaic-noise/
2. Switch between demosaic settings

**Expected behavior**
Noise is not increased

**Platform**

* darktable version : 3.5.0+2368~g98ba99f78
* OS : Ubuntu Linux, kernel 5.11.0-17
* Linux - Distro : Ubuntu 21.04
* Memory : 64 GB
* Graphics card : NVidia 1060/6GB
* Graphics driver : 460.73.01
* OpenCL installed : yes
* OpenCL activated : yes & no, same result
* Xorg : xserver-xorg 1:7.7+22ubuntu1; xserver-xorg-core 2:1.20.11-1ubuntu1
* Desktop : KDE Plasma (kd5 5.80.0-0ubuntu1)
* GTK+ : 3.24.25-1ubuntu4.1
* gcc : 10.3.0-1ubuntu1
* cflags : unknown
* CMAKE_BUILD_TYPE : RelWithDebInfo

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
While dual demosaicing the vng_interpolate must not leave after the linear interpolation!

This problem is visible especialyl on high iso images or images with lots of color noise as has been pointed by @kofa73

Fixes #9101

### CODE REVIEW

**Comment by kofa73** [comment]
I'm sorry, I cannot detect any differences between the output from master (0aaee290b) and PR 9111 (e49e9eb). I've removed ~/.cache/darktable to make sure no previously cached content or OpenCL kernel interferes. I ran the test twice (exporting full-sized images with dithering), once with threshold = 0.2, once with threshold = 1.0. It's not only visual inspection: I loaded the corresponding pairs (same threshold) into the Gimp as layers, set the image to 32-bit linear, merging mode to difference; flattened the image, then tries stretching the histogram in Colors -> Levels, but it remained all black for both pairs. Which is quite strange, as I expected at least dithering to introduce differences. I'm puzzled now.

**Comment by kofa73** [comment]
Comparing the outputs to e.g. Amaze, I do detect a difference with the method described above, so that seems to be a valid way to validate image content. Exporting twice with Amaze + dither yields no difference, but there's a difference between Amaze with and without dither, as well as between Amaze + dither vs dual (RCD + VNG4) + dither.

**Comment by jenshannoschwalm** [comment]
I confess i don't understand your approach of testing. If we go with the image you gave with the issue reporting 2020-08-08_19-27-01_P1040511.RW2.

If you open it and set the threshold to close to zero -> if you now switch demosaicer from rcd to rcd&vng and vice versa (you can do the same with Amaze and amaze&vng) you won't see any visible difference. Now change the threshold to close to 1, now the output will stay the same for selecting vng, rcd+vng and amaze&vng. This is exactly as it should be.

I have no idea how the dither module works and what parameters is taks to render a pixel so i can't argument on this.

I also tried exporting (using 32bit tiffs), also comparing using gimp layers subtracting vng vs rcd&vng with a threshold of close to one and after very strong amplification (~1000) there was a difference to be seen.

Again testing export now comparing vng vs rcd&vng with a low threshold to allow rcd to step in and voila there is the visible difference (now **without** amplification) as the dual demosaicing mask has wanted.
This is the mask
Bildschirmfoto von 2021-05-30 20-36-07
and here is the diff in gimp (you have to click on it to see the difference)
Bildschirmfoto von 2021-05-30 20-34-27

For me it's exactly as it should be! Maybe we should add some comment in the manual, dual demosaicing is certainly nothing for images with lots of noise.

**Comment by kofa73** [comment]
I may have made a mistake, but cannot test more today, only tomorrow morning. Basically, I exported my daughter's photo twice (with threshold 0.2 and 1), one pair with master, one with your branch, and compared the pairs (so the master 0.2 with your 0.2, master 1 with your 1), and found no difference at all. But, as I said, I may have made a mistake, and I trust your tests; I can contribute more testing if you can wait until tomorrow morning.

**Comment by kofa73** [comment]
OK, I don't know what I did wrong, but I tested again and it seems to work fine. Thanks for the fix!

**Comment by jenshannoschwalm** [comment]
I have to thank you for making me unerstand a bug! Ready to be merged.

**Review by TurboGit — APPROVED** [review]
Thanks !

**Pull request merged**
