### PR TITLE
Clarify delete button (part 2)

### LINKED ISSUE #8656: Clarify delete button
**problem**

It's very difficult to see, which button really deletes the image file from disk:
- the remove_button has a tooltip including "(Delete)"
- the delete_button on the other hand does not include "delete" at all

The reason for this strange behavior with default-settings is:
  - the key 'del' is mapped to the remove_button
  - dt tries to move files to trash "on system that supports it"

**solution**
- extend the tooltip to "(key: 'Delete')
- always use the label 'delete' for the delete-action

Deleting image files including sidecars is a very severe action, dt can't undo the deletion, so it should not pretend to have a trash.

**Alternatives**
- remove delete_button
- create a trash in dt to undo the deletion of files

### PR DESCRIPTION
**Pull request by quovadit**
Part 2 to resolve #8656 

always use the label 'delete' for the delete-action

### CODE REVIEW

**Comment by elstoc** [comment]
If you want to better illustrate how it actually works then instead of the button text being "trash" it should be "trash/delete" and the tooltip should say "send file to trash, or delete if trash is not supported". If the user has disabled "send to trash" it should just say "delete" as currently.

**Comment by quovadit** [comment]
I don't think, that 3 terms on the screen (remove, trash, delete) make it easier to understand which button to use.

For me it is important to make the difference as clear as possible:
- one button does NOT delete the image
- the other button does delete the image

The (great) functionality of using the trash if possible is not helpful for this decision at all.

**Comment by parafin** [comment]
If the button is called delete, how user would know that files aren't actually being deleted, but moved to trash instead (so still taking up disk space)?

**Comment by quovadit** [comment]
> how user would know that files aren't actually being deleted

I did not know it either, although the button is called trash at the moment.

It is mentioned in the settings, and I will concretize it in dtdocs.

And by the way: if there is a duplicate, the delete-button does not delete either (which is also only explained in dtdocs).

**Comment by dterrahe** [comment]
> If the button is called delete, how user would know that files aren't actually being deleted, but moved to trash instead (so still taking up disk space)?

The user should know something about how their system is configured. It is not up to dt tooltips to explain to each user the basic functionality of _their_ operating system. That would imply writing complete OS manuals in tooltips (that then nobody would take the time to read because "too much text"). People that go about their lives deleting stuff trusting that dt will be able to restore it for them, without _once_ checking how to do it (without "undelete" button) or whether it works, or conversely people who get upset that "trash" still keeps a copy around for a while (until presumably the system warns them about running out of disk space and suggests permanently deleting) are probably not the target audience for dt. It will _never_ (with our current resources) be user friendly enough to prevent footshootery by those who blame others for their mistakes or lack of understanding. It detracts from fixing _actual_ bugs. And by broadening the focus to be a user-friendly powertool that will allow complex operations _without_ any possibility of unintended consequences, we'll end up pleasing nobody, losing developers and becoming irrelevant. That will happen long before Clippy is merged.

**Comment by parafin** [comment]
My point is about proposed renaming trash to delete. When action is called "trash" it's obvious files go to trash and not permanently removed, but if button is called "delete", then it's a fair assumption that trash isn't used (not all software makes use of trash, darktable didn't some time ago). Software behaviour shouldn't be surprising to user and delete button moving files to trash is IMHO surprising.

**Comment by quovadit** [comment]
> Software behaviour shouldn't be surprising to user

I absolutely agree!
But it is not guaranteed, that a trashed file can be recovered, so that would be even more surprising.

As any wording can be surprising for someone, but accidentally deleting is the worst case, it's the safest way to always call it delete.

**Comment by parafin** [comment]
No, delete should be called delete if it deletes. If we trash, button should be called trash. The only bug here is how we handle non-working trash.

**Comment by elstoc** [comment]
> The only bug here is how we handle non-working trash.

I'm not sure we've actually worked out how that functions yet. Has anyone actually tried it on a system with non-working trash?

**Comment by dterrahe** [comment]
There we go; taking responsibility for the correct functioning of each and every cross platform system we "support" and all possible configurations and settings on those systems. This should be the highest priority! Also I think when we're just thrashing the button should be green to indicate it is safe and when we're really deleting it should be red for danger.

**Comment by quovadit** [comment]
As mentioned before: I'm not talking about non-working trash but about auto-deletion of trashed files by OS. There is no chance that dt can handle this.

**Comment by parafin** [comment]
That’s up to user to configure. As you say dt can’t handle that. I really don’t see a problem and I don’t understand why would anyone assume that dt trash is different from system OS trash. At the contrary it makes sense to use one and only trash across applications. dt manual and/or tooltip should clarify that of course (probably already does).

Lastly trashing operation is not “safe”. Trash isn’t a place to store your files indefinitely. It just basically allows for a quick undo. I don’t think we should care about bad user habits. It doesn’t matter conceptually if it’s OS or dt who does cleaning of trash. Why aren’t you complaining to OS vendors about files disappearing from trash?

**Comment by quovadit** [comment]
I agree, that trashing is not safe, and that it does not matter who cleans the trash, it isn't a place to store files.

That's why I don't want to differentiate between trash and delete.

This way it would be very clear, what the difference between the two buttons is:
- remove: safe, nothing critical, just don't show in darktable anymore
- delete: not safe, be careful, the file will be gone (maybe with an undo-function - depending on your OS-settings)

Currently the two buttons are labeled remove / trash, so it's not that clear which option is the safe one.
I personally hesitate everytime I click on remove.

I know that there is one button which deletes, and another button which does not delete.
If there is no button labelled 'delete' I'm uncertain, which button to click.

The only goal of this PR is to be sure to click the right button which does not delete my files.

**Comment by parafin** [comment]
On that I can concur - remove does sound dangerous and I also hesitate sometimes. So maybe instead “remove” should be rephrased. This is related, I think, to the discussion of what “import” means in dt - whether it copies or just indexes the files.

**Comment by elstoc** [comment]
I'm not sure there's a better single word than remove. Perhaps "remove from database" would be clearer but probably too verbose for a button. Even the tooltip "remove from _collection_" isn't really correct.

**Comment by parafin** [comment]
“remove” here is an opposite action from “import”, but not “export”;) Basically it’s “unimport”. How about “forget”?

**Comment by elstoc** [comment]
> How about “forget”?

That might work

**Comment by quovadit** [comment]
I think  'remove' is very clear, if the counterpart is 'delete'.

So what about:
- trash --> delete (trash)
- delete --> delete permanently

image


The tooltip could be:
- remove
  - only remove from darktable, don't delete file on disk
- delete
  - physically delete from disk (using trash if possible)
  - physically delete from disk immediately

**Comment by TurboGit** [comment]
I think the `delete (trash)` label is a good solution.

**Comment by elstoc** [comment]
I agree. In fact it's almost exactly the same as the "trash/delete" suggestion I made in my first post. What were we arguing about?

**Comment by quovadit** [comment]
I still think that only calling it delete would be the best solution.
But since I'm the only one, your slightly adapted suggestion is the best compromise to the current solution.

**Comment by TurboGit** [comment]
@elstoc : I'd like your final review on this. To me it is ok, just wondering if the change of "collection" for "darktable" in strings are ok?

**Comment by elstoc** [comment]
"remove from collection" doesn't really mean anything - a collection depends on the criteria you use to define it. If I define a collection as "images with a given tag" then just removing the tag from an image removes it from the collection. It's still in the database.

I prefer "remove from database" as it should be clear that this doesn't imply deletion of the actual image, though "remove from database (without deleting files)" is fine if we want to be ultra-clear.

**Comment by quovadit** [comment]
for me "database" is very technical, that's why I called it "darktable"...

**Comment by elstoc** [comment]
I can live with that wording but I still prefer "database"

**Review by TurboGit — APPROVED** [review]
Ok, let's move forward. Thanks.

**Comment by lapineige** [comment]
I know this PR has been merged, but if you need information on what happens in that case:
>  I'm not sure we've actually worked out how that functions yet. Has anyone actually tried it on a system with non-working trash?

I can provide you a screenshot of the dialog that opens in that case, because I do have a "non working" trash since I replaced the local trash folder by a symbolic link (that darktable doesn't seem to be able to use).
Would that be helpful ?

**Comment by elstoc** [comment]
Couldn't hurt, thanks.

**Comment by lapineige** [comment]
Here it is:


a

This is the pop-up shown when you click on the *"trash"* button, then answer yes to the confirmation pop-up.
*NB: to be honest, thanks to this first 3 buttons (although I don't understand what the second button is doing… I'm removing only one file) I finally understood what was the difference between "trash" and "remove [from database]", and which button did what.*

If you close the pop-up without touching any button (using the escape key for instance) it removes the file from DT database… which is king of confusing, as I would have thought it would cancel everything… but at least the file is still on disk.
The very same happens if you click on "stop process". So I guess that the stopped "process" is in fact a "delete from disk" process". That's also a double with *"remove from collection"*. I don't know if it's intended or a bug, but this is confusing, surprising and scary the first time (before you realise the file wasn't deleted).


edit: I tried for the first time the *"physically delete"* button (I usually don't do that in DT, I prefer to use my file manager, then I'm 100% sure it goes to the trash). It does delete the file `example.raw` from disk instantly, yet 1~2s after that I have another pop-up about `example.raw.xmp` file.
Then I guess "physically delete all files" deletes all images+XMP in 1 operation.

**Comment by elstoc** [comment]
Thanks that looks fairly comprehensive. I guess it removes files from the database first and then tries to trash the files. It might be worth raising an issue if you think it could be improved, though it's not behaviour I can replicate as I have a working trash.

**Comment by lapineige** [comment]
That's a good idea, I will open an issue.

>  though it's not behaviour I can replicate as I have a working trash.

Maybe if you disable the trash ? I don't know what could be the side effects though…
If you're running Linux, you can just rename the trash folder, it should be enough to reproduce.

**Pull request merged**
