### PR TITLE
retouch: reorder tools to be consistent with other module.

### PR DESCRIPTION
**Pull request by TurboGit**
the brush is always first in mask, the select tool has been moved last.
also the fill mode is now last, probably less used than blur.

### CODE REVIEW

**Comment by TurboGit** [comment]
@edgardoh ok with this?

**Comment by upegelow** [comment]
From a logical point of view: shouldn't the retouch tools come below the wavelet decompose? In the normal way of working you first consider how to separate an image and then you start to work with tools on specific scales. This also would bring the shape modifiers closer to the shape producers.

**Comment by TurboGit** [comment]
Agreed. Makes senses and will certainly help usability. Will do that right away.

**Comment by TurboGit** [comment]
Done. It indeed makes things clearer to me.

**Comment by upegelow** [comment]
@edgardoh should give his POV on this.

**Comment by TurboGit** [comment]
@edgardoh : the most important point is having the tools and the tools options close to each other. So another option is to move the tools options above the wavelet decompose section. Would this be ok?

For the tools I'm using the brush more often :)

**Comment by edgardoh** [comment]
> @edgardoh <https://github.com/edgardoh> : the most important point is
> having the tools and the tools options close to each other. So another
> option is to move the tools options above the wavelet decompose section.
> Would this be ok?
>
By tool options you mean the shapes properties, so you want to bring those
two sections together? If that's the case, I place it last because the only
algorithms that have a property are the blur and fill with color, and they
are not used very often, so again the order of the sections reflect how
often they are used.

> For the tools I'm using the brush more often :)
>
Well, probably there's no way to make every one happy ;)

I've been using this tool for a long time time now, from very basic sensor
dust clean to heavy retouching and I'm comfortable with the GUI, but that
may very well be because I'm use to it, there's no way for me to tell other
than try something different.

From the use-case perspective, with the current functionality, there's no
much interaction with the GUI, I use the continuous add and focus on the
image, and when I use the wd I focus on the wd bar, so it doesn't really
matters where it is placed. Same goes for the order of the shapes and
algorithm buttons. So if you have a strong conviction that this changes
will make things better, go for it.

I still have the feeling that the order of the sections is OK the way it,
but again, what I say above.

**Comment by TurboGit** [comment]
> If that's the case, I place it last because the only algorithms that have a property are the blur and fill with color

No, there is also always the opacity. And for me I'm using the blur a lot as this is a good way to remove artefacts from the skin on different scales.

**Comment by edgardoh** [comment]
Just one more note, the properties section show/hide some fields based on the selected shape, so if a section is below it, it will be 'moved' each time a shape is selected. If you want the shapes and properties section together, the best option probably is what @upegelow suggested and make the wd section first.

**Comment by TurboGit** [comment]
Ok, so let's go for this. It is actually what I have done in this PR.

**Pull request merged**
