### PR TITLE
imageop: don't try to change group while duplicating modules

### LINKED ISSUE #5727: Do not clear "Search module" field when "new instance" is selected
**Is your feature request related to a problem? Please describe.**

I am always frustrated when the "Search module" field is cleared at a time when it still ought to be active.

I very often use the "Search module" field to quickly find a module.
Example: I enter  _equ_ and two modules are presented: 
_contrast equalizer_ and _tone equalizer_ (= correct; _equ_ is still shown in the search field = correct).

I do something in the _contrast equalizer_, and would like to invoke a second _contrast equalizer_. Now the _Search module_ field is cleared, and I have to enter _equ_ again to locate it.

**Describe the solution you'd like**

It is very good that the search field is cleared in other cases, but _not_ when a new instance is selected.

**Alternatives**

**Additional context**

### PR DESCRIPTION
**Pull request by elstoc**
Resolves #5727

### CODE REVIEW

**Comment by TurboGit** [comment]
Nice fix, thanks!

**Comment by ClaesGitHub** [comment]
@elstoc 
@TurboGit 

Latest git-version of darktable.
Steps to repeat problem:
- Start with new import.
- Open image in darkroom (_correction group_ is selected)
- Set _search module_ to `equ`
- In _contrast equalizer_, drag curve upwards
- middleclick to start a new instance of _contrast equalizer_ 

This will generate a faulty behaviour:
- In right column, only modules _contrast equalizer 1_, and tone equalizer are shown (this is wrong, since the starting _contrast equalizer_ also ought to be there.)
- To make module _contrast equalizer_ visible in the right column, I have to enter "equ" in the search module field again.
- [In history column, both _contrast equalizer 1_, and _contrast equalizer_ are shown (Correct)]

**However:** I wonder if this perhaps has something to do with the _contrast equalizer_ module, since I do not seem to be able to repeat this behaviour with other modules :-( For instance, the _tone equalizer_ behaves normally.

**Comment by elstoc** [comment]
Could you try it with #6005 please

**Comment by ClaesGitHub** [comment]
Good evening @elstoc,
Thank you! #6005 seems to have fixed that particular problem! :-)

**Pull request merged**
