### PR TITLE
align module and instance name to same baseline

### PR DESCRIPTION
**Pull request by dterrahe**
fish #14743

### CODE REVIEW

**Comment by TurboGit** [comment]
Seems ok to me, @elstoc can you test also?

**Comment by elstoc** [comment]
Looks good, thanks

**Comment by TurboGit** [comment]
@dterrahe @elstoc : Thanks!

Do you all agree to merge for for 4.4.1?

**Comment by elstoc** [comment]
Yep this is good to include in 4.4.1. Seems really low impact to me

**Comment by dterrahe** [comment]
I feel it diminishes the value of the release notes if trivial stuff like this (that for most people will be hard to see, even if pointing straight at it) takes up space and distracts from relevant stuff. The release notes should be a manageable condensation of all individual commits that allow deciding whether updating is worth it and not to miss out on new features. To see _exactly_ what went into 4.4.1 there is always https://github.com/darktable-org/darktable/commits/darktable-4.4.x

**Comment by TurboGit** [comment]
Sure, but at the same time it also shows that we care fixing little details. But I have no string opinion, so fine by me.

**Pull request merged**
