### PR TITLE
rewrite of slideshow for better responsiveness

### PR DESCRIPTION
**Pull request by TurboGit**
Also use code implemented recently for the dynamic snapshots and duplicate.
So better code sharing.

The most visible change is the display of a preview while waiting for the final display to be ready. This gives feedback to the user that something is going on and it makes the UI far better.

### CODE REVIEW

**Comment by TurboGit** [comment]
This PR contains fixes (speed, fix a possible lock) but based on a mostly whole rewrite. So maybe OK for 4.2, for this I need some testers to ensure nothing is _more broken_ than current master.  If you test this, please report. TIA.

**Comment by gi-man** [comment]
I build this PR a few moments ago on fedora 36 KDE X11. It is faster than current master. I noticed:

When I start the slideshow, before pressing the spacebar, it just show this indefinitely: 
image

After pressing spacebar, it starts, shows the image and works pretty fast.


I then tested with OpenCL off and with some images that have a heavy use of D&S and GL HLR. These take +30sec each to process. The default for the slideshow is 5 sec (I had mine at 1sec before), it makes the system slow to even quit back to lighttable. This might be understandable.

**Comment by TurboGit** [comment]
> When I start the slideshow, before pressing the spacebar, it just show this indefinitely:

I always have the currently selected image displayed. Do you have one or multiple selected image before entering the slideshow?

**Comment by gi-man** [comment]
I normally use select all. Now sometimes it shows the image at very low resolution and some times it shows the gray waiting screen. When the gray shows, pressing the space bar skips to the next selected image.

Playing more with it, it seems that it depends on the location of the mouse when I press S. If the mouse is on an image or on a module.

**Comment by Nilvus** [comment]
Just tested quickly and just much better than on actual master. On first launch, this works great and it's smoother. Previous one was too slow and most of the times freeze darktable. Not this one. Great work @TurboGit and I agree for 4.2 release. This is a great move to improve slideshow that I have forget to use before regarding how it was hard to correctly use it on my side. This should change with that PR.

I can't reproduce your issue @gi-man.

**Comment by gi-man** [comment]
Here is a screencast Fedora 36 Gnome Wayland

[Screencast from 11-18-2022 01:49:38 PM.webm](https://user-images.githubusercontent.com/97920861/202780985-64e7d79b-1feb-41bc-9417-aa2ed28d7ca1.webm)

**Comment by jenshannoschwalm** [comment]
I also did a check. Yes, indeed much faster if there were no correctly sized cached images available and stable or me too.

About the performance problems related to laplacian hlr or d&s as @gi-man reported, i don't see a good way to handle that.

**Comment by TurboGit** [comment]
> About the performance problems related to laplacian hlr or d&s as @gi-man reported, i don't see a good way to handle that.

Yes, no way around that directly in dt... Or wait some years to have a quantum computer :)

**Comment by TurboGit** [comment]
I'll review the code again and will merge in 4.2 finally. Thanks for testing.

@gi-man : I'll see if I can understand this issue... Do you have the disc cache activated in dt?

What about those values in _preferences / processing_:

image

**Comment by gi-man** [comment]
I dont have full preview cache on in the test environment. Turning it on had no effect.

**Comment by TurboGit** [comment]
> I dont have full preview cache on in the test environment. Turning it on had no effect.

I suppose you want to display the full preview of the file before going to the slideshow to ensure it is in the cache.

**Comment by TurboGit** [comment]
@gi-man : What is your screen resolution? Is that 4k?

**Comment by gi-man** [comment]
I made sure I open all the images in in full view to generate the cache, but it was still doing this. I noticed this message in terminal:
Magick: Sorry, can not handle image with PhotometricInterpretation=34892. ().
[dt_imageio_large_thumbnail GM] thumbnail not found?

So, I deleted the .cache folder and now it is working correctly.

**Comment by TurboGit** [comment]
@Nilvus @gi-man @jenshannoschwalm : Just pushed a new version with a large cache for an even better user's experience and also we now properly record an image even if the slideshow has moved forward (or backward).

Can you test this new fixed version? Hopefully it is even safer for 4.2. At this stage the fixes in this PR are really making this better I think.

**Comment by gi-man** [comment]
It works for me.

**Comment by jenshannoschwalm** [comment]
Now it might take a lot of ram. Are you sure  no other pipeline might interfere?

**Comment by TurboGit** [comment]
@jenshannoschwalm : I'm using a single pixelpipe and store only a cairo surface (screen size) per slots (5 slots). So this is safe I would say.

**Comment by Nilvus** [comment]
Much better and much smoother with last commits. Great work @TurboGit

**Comment by TurboGit** [comment]
Thanks, let's merge now.

**Pull request merged**
