### PR TITLE
theme: set right color for .dt_bauhaus_popup:disabled

### PR DESCRIPTION
**Pull request by sgotti**
The color was set to white instead of @bauhaus_fg_insensitive

### CODE REVIEW

**Comment by TurboGit** [comment]
One for you @Nilvus. TIA.

**Comment by dterrahe** [comment]
Ah, so the problem with this is that currently "combobox item=disabled" is used as a proxy for "this is a subgroup header". See in the collections module or blend mode drop downs. So we'll need to add a way to distinguish those from "normal" disabled items like this one, so that Nilvus can adjust his styling between the two.

**Comment by Nilvus** [comment]
@dterrahe is right. This fix is not good. Check subtitles on collection module property list. White setting was set to allow those subtitles to be displayed differently than properties.

On master with white setting:

image

With your PR:

image

I'm not sure though to understand what other parts are broken due to white color. I have really few times those days to search. So if you want to fix something else, could you please explain which parts and/or screenshots.

**Comment by sgotti** [comment]
@Nilvus 

image

In PR #12714 I created a combobox where an item should be disabled, In the screenshot the first item "embedded metadata" is disabled using `dt_bauhaus_combobox_entry_set_sensitive`, it's correctly not clickable but the color is white. This is fixed with this PR but as you as @dterrahe said it impacts other things.

If it can help, bauhaus combobox takes the entry color using  `gtk_style_context_get_color(context, GTK_STATE_FLAG_INSENSITIVE, &text_color_insensitive);` so it uses the modified css entry.

**Comment by Nilvus** [comment]
@sgotti: could you update your PR so to allow change you want (needed of course) AND kept actual white settings for subtitles like in collection list? Thanks.

**Comment by sgotti** [comment]
> @sgotti: could you update your PR so to allow change you want (needed of course) AND kept actual white settings for subtitles like in collection list? Thanks.

I looked at the code in `collect.c`. The left items (sections) are added with `dt_bauhaus_combobox_add_full` (via `dt_bauhaus_combobox_add_section`) and marked as not sensitive (that's the reason why this change affected this). So since I'm also using the same sensitive setting I'm not sure I can do something different when using the same code.

One solution will be to not use bauhaus but a gtk_menu like done by the styles menu but then I'll all the automatic management of parameters, signals and must do all custom.

I think that a clean solution will be the one proposed by @dterrahe to add an additional flag in bauhaus_combobox to define "section" entries and use a different css class for them. Sections are both insensitive but usually an insensitive text should look disabled while they want to be enabled also also very visible (it's the unique part that uses full white)

**Comment by dterrahe** [comment]
If this is the one exception where we use insensitive combo items as just insensitive, the widget could be given a `dt_gui_add_class` and CSS could distinguish it that way. It gets a little messy...

**Comment by SoupyGit** [comment]
Not a dev so forgive me if this is off the mark, but any chance this is related to #12666 ? There also two options were displayed in white, not one.

**Comment by dterrahe** [comment]
> Not a dev so forgive me if this is off the mark

Nothing to forgive, but no, that is a separate issue to do with position calculation being impacted by margins and stand-alone headers.

**Comment by sgotti** [comment]
> If this is the one exception where we use insensitive combo items as just insensitive, the widget could be given a `dt_gui_add_class` and CSS could distinguish it that way. It gets a little messy...

Let me know what you prefer and how you intend that "insensitive" items should be displayed by default. Then I can introduce the exception in the lens module (adding this exception will require to add a dedicated css class in the theme) or the idea proposed [above](https://github.com/darktable-org/darktable/pull/12723#issuecomment-1295031157) (the other way, marking "sections" entries and use a dedicated class).

**Comment by Nilvus** [comment]
CSS use classes for all same items then id for specific ones. Before, darktable CSS set specific id first. I completely rewritten CSS to respect standard CSS recently and it make sense to set all same items (and main ones) before specific ones.

So, I think here that all those items (subtitles and what you want @sgotti) are first insensitive ones. So I think this should be set first all insensitive and then add a specific id to set subtiles as white.

**Comment by Nilvus** [comment]
@sgotti: any news for that PR?

**Comment by sgotti** [comment]
@Nilvus  since the lens module changes were merged with a different approach this is not blocking. I'll happily work on it but perhaps it could be done after the 4.2 release.

**Comment by dterrahe** [comment]
I'm not sure if this is/would be used anywhere. We usually hide stuff that is not selectable. So maybe this (and the associated wip PR) can be closed as not really needed?

**Pull request closed without merging**
