### PR TITLE
fix shift+drag edge to shrink crop with constant aspect

### LINKED ISSUE #14642: Crop with hanker as the center of the image with holding ALT key.
It allow to crop and 4 sides crop toward or away from the center of the crop frame. The crop frame get bigger or smaller 4 sides at same time. It's useful and save clicking time. 

* Description *
In crop module, 
when you perform a crop, 
you can hold ALT and click and drag an edge or a corner 
and **4 sides moves at same time** **toward the center** or **away from the center** depending on wish direction you drag. And it change the crop area as hanker in the center.

**Alternatives**
I don't know.

**Additional context**

Crop toward center 1

### PR DESCRIPTION
**Pull request by dterrahe**
fixes #14642

In the crop module, this allows the cropped area to be made smaller by dragging an edge while holding shift (to maintain aspect ratio), fixing a bug probably existing since #9048.

This _also_, possibly more contentiously, changes the behavior when the crop is still 0 on all sides. At this point, it is not possible to _move_ the crop area, since there is no space anywhere to move it to, so the cursor shape and hinter message are a bit misleading and possibly confusing. With the second commit in this PR, instead of non-functional moving in the center of the image, the discoverability of edges and corners as crop zones is increased; even when far away from them, they light up and the cursor changes accordingly and dragging will have the same effect as if the actual zone was grabbed.

Besides helping discoverability, this makes it easier to grab one of the corners, since you don't have to go all the way there. But of course people may find the fact that behavior changes when once there _is_ a crop unappealing. Imho at that point it is easier to figure out that one should grab a corner, but feel free to add whatever emoji this triggers if you disagree.

@TurboGit the first commit could possibly still go in 4.4 as pure bugfix.

I think there should also be some changes to hinter text when (hoizontal and/or vertical) moving is not possible, but that is too late for the string freeze.

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Works for me, both commits ok. The second one is better as instead of doing nothing it still enable some cropping. The behavior seems easy understandable... So let's go for 4.4. Thanks!

**Comment by TurboGit** [comment]
Just need a little text for the release notes please.

**Comment by ActarusLeGrand** [comment]
If would be nice if at any time you can press the shift button to do the crop. Because right now you have to press it before clicking the mouse, a little weird.

I would like to be able to change the shift to ALT.

**Comment by dterrahe** [comment]
Release note:

bug fixes:
- In crop mode, shift+dragging an edge allows making a crop smaller, instead of just larger, while maintaining aspect ratio. Previously this feature only worked correctly when dragging a corner.

For the second change, extend the existing release note with a sentence:
- When the crop module receives focus and switches to an uncropped view of the image, the crop areas around the edges of the image briefly light up to indicate that they are now draggable. As long as the crop covers the full image, and moving it by dragging is impossible anyway, the sensitive zone for dragging corners and edges is enlarged.

> If would be nice if at any time you can press the shift button to do the crop.

Yes. That would introduce two possibilities; maintain the aspect ratio from before the drag started (like now) which would cause a jump as soon as you press the shift key after dragging for a bit. Or maintain the aspect ratio that existed when the shift key was pressed. So there would be bikeshedding and unhappiness.

> I would like to be able to change the shift to ALT.

Making all modifier keys (and double clicks and swapping mouse buttons) for central canvas actions configurable is a rather larger project. It should also reflect any changes in (h)elp text and hinter messages and make sure that settings don't conflict when multiple "modes" are active at the same time. So far nobody seems to have shown interest in taking this on, maybe because this would only add value for <10% of the user base and add complexity (and possibility for confusion and misconfiguration) for the rest and for developers who need to maintain code in future. Such "improvements" are often met with negativity, sapping developer morale and engagement. 

So while your suggestion is appreciated (we honestly do like users letting us know how they think things can be improved; otherwise we're very much tinkering in the dark/working off our own preferences) I wouldn't want you to get your hopes up that you'll get this option any time soon.

**Pull request merged**
