### PR TITLE
Update primaries.c with more explaining tooltips

### PR DESCRIPTION
**Pull request by MStraeten**
more explaining tool tips
describe the direction of hue changes

### CODE REVIEW

**Comment by kofa73** [comment]
Wouldn't 
- shift red towards yellow or magenta
- shift green towards cyan or yellow
- shift blue towards magenta or cyan
be more user-friendly?

Also, _purity_ is not one of the colour dimensions described at https://darktable-org.github.io/dtdocs/en/special-topics/color-management/color-dimensions/. Should the page be updated, or should a (perhaps technically less accurate) term like 'saturation' be used?
Is this the meaning the code uses? https://en.wikipedia.org/wiki/Colorfulness#Excitation_purity

**Comment by MStraeten** [comment]
> Also, _purity_ is not one of the colour dimensions described at https://darktable-org.github.io/dtdocs/en/special-topics/color-management/color-dimensions/. Should the page be updated, or should a (perhaps technically less accurate) term like 'saturation' be used?

If you have a look at the results, then the displayed saturation shades doesn’t match purity. So using one terminology for different behaviour isn’t helpful…

**Comment by kofa73** [comment]
(emphasis mine)
> If you have a look at the **results**, then the **displayed saturation shades** doesn’t match **purity**. So using one terminology for different behaviour isn’t helpful…

I'm not sure I understand. Are you saying that
- _saturation_ would be the wrong term, or that
- the indicators on the _purity_ sliders
image
 are not representative of _purity_ adjustments, or that
- the adjustments the module makes are not really _purity_ adjustments?

**Comment by MStraeten** [comment]
messed up the branch, so closing it - maybe the tooltip changes can be done better  when changing purity to saturation ...

**Pull request closed without merging**
