### PR TITLE
watermark: update watermark text to 512 characters max.

### LINKED ISSUE #3840: Watermark text length restricted to 60 character when composited on the image
Was trying to put a text longer than 60 as watermark.
Text field of the module allows the length but when composited on the image it only displays 60. 

This limit needs to be bigger or at least configurable.

Version : darktable-3.1.0+8~g7871a4f25-win64

### PR DESCRIPTION
**Pull request by TurboGit**
This is important as we can now have variables in the simple text entry
and so a limit of 64 was quickly reached.

Fixes #3840.

### CODE REVIEW

**Comment by chhil** [comment]
Any way to determine what can  fit on the fly using font/dpi/orientation of text and image size?

**Comment by TurboGit** [comment]
That won't work. This setting can be copied from image to image and moreover we are talking about IOP parameters which must have a static size.

**Comment by Nilvus** [comment]
512 is already a quite long text for watermark. And much appropriate now than previous 64.

**Comment by TurboGit** [comment]
Ok, I'll go with that. Thanks.

**Pull request merged**
