### PR TITLE
Keyboard shortcut for 100% (1:1) on HiDPI and standard displays

### PR DESCRIPTION
**Pull request by geni1105**
Adds a keyboard shortcut for 100% / 1:1 display, which also works on 4k/5k displays
(the "zoom closeup" shortcut goes to alternately 200%/400% on such displays).
Shortcut is initialized to alt+9.

Tested on iMac Retina 5k, and did my best to find out the settings for standard displays (but the zoom and ppd related code is not easily comprehensible, multiple parameters DT_ZOOM_xxx, scale, closeup, ppd, ... - appreciate if someone can test). 

As a newbie not sure if the .pot/.po files are really needed in the PR. Guess they are automatically generated usually, but I needed to patch them for local test and to include a German translation for personal use. Please advise about a better way ...

### CODE REVIEW

**Comment by TurboGit** [comment]
> Adds a keyboard shortcut for real 100% / 1:1 display on 4k/5k displays

This looks wrong to me. We need a single zoom for 100% (the current zoom closeup) to be a 100% zoom on all display HiDPI or not. Another way to say that is that having a 100% zoom specific to HiDPI is not the way to go.

**Comment by geni1105** [comment]
I agree, and I raised an issue orginally (https://github.com/darktable-org/darktable/issues/10839#issue-1097187621), however it was not accepted so I closed it. 
That's why I decided to do a separate, "real 100%" implementation (which I hope does work on all displays, not just HiDPI).

**Comment by parafin** [comment]
First I guess we need to agree if we’re calculating zoom percent from dots (scaled) or display pixels (unscaled). I think second option makes sense, but currently I guess first one is used? So if we’re to fix this, then we need to fix all existing steps, not add another one.

**Comment by jenshannoschwalm** [comment]
> So if we’re to fix this, then we need to fix all existing steps, not add another one

There have been a number of discussions and issues exactly about this point. Other people complaing about the issue the other way round. (scaling to pixels or dots is the point) After those discussions the current implementation had been chosen and fixed in that way. (Personally i had a different opinion btw)

@aurelienpierre had confirmed "correctness"

**Comment by geni1105** [comment]
> It is not that it was not accepted but that the current behavior is the one we want. Adding another zoom level here is just confusing to me. The PR quoted in #10839 seems to imply that in HiDPI the 100% zoom has been fixed, I don't have an HiDPI to test.

Depends what fixed means here, as the shortcut is not defined as "100% zoom" but as "zoom closeup". The apparently intended behavior is that it zooms alternately to 100%/200% on standard displays and to 200%/400% on HiDPI, and this works. 
Not sure what was the rationale of this decision for HiDPI, and I guess most would prefer to have the 100%/200% behavior irrespective of the type of display.

**Comment by parafin** [comment]
screen_ppd_overwrite option was removed some time ago, so now it's impossible to debug HighDPI issues without a HighDPI monitor. This is smth we need to fix.
If the point of this PR to leave 100% as 1 picture pixel:1 monitor dot (scaled), and just to be able to have such 100% as a keyboard shortcut, then I think Alt-1 should be modified to switch between 100% and 200% instead of adding a new shortcut. It was probably an oversight?..

**Comment by jenshannoschwalm** [comment]
> so now it's impossible to debug HighDPI issues without a HighDPI monitor

Linux / gnome offers display setting to 200% which leaves us as with a HighDPI monitor. No?

> Alt-1 should be modified to switch between 100% and 200%

Not sure i fully understand this. Do you suggest to have the Alt-1 key behaviour depending on another flag ?

See confirms and discussions in #8870

**Comment by geni1105** [comment]
@parafin Yes, that was the point of this PR. I understood that changing alt+1 would not be appreciated, therefore the PR to add an additional shortcut.

**Comment by parafin** [comment]
> > so now it's impossible to debug HighDPI issues without a HighDPI monitor
> 
> Linux / gnome offers display setting to 200% which leaves us as with a HighDPI monitor. No?

GNOME doesn't even cover Linux, and there's no such possibility out of the box on Windows or macOS.

> 
> > Alt-1 should be modified to switch between 100% and 200%
> 
> Not sure i fully understand this. Do you suggest to have the Alt-1 key behaviour depending on another flag ?

On the contrary - Alt-1 should behave regardless to High-DPI mode and cycle between 100% and 200% (whatever is defined as such, currently it's related to dots). Now, according to this issue, it behaves differently, which is unexpected IMHO.

> 
> See confirms and discussions in #8870

Which comment specifically is related to this dicussion?

**Comment by geni1105** [comment]
Any chance to get this merged?

**Comment by TurboGit** [comment]
@geni1105 : I suppose we should close this at this point?

**Comment by jenshannoschwalm** [comment]
Think so

**Comment by geni1105** [comment]
Well, there is no agreement on this PR, and also not on the clean and consistent behavior that @TurboGit proposed (see https://github.com/darktable-org/darktable/pull/11179#issuecomment-1046330622) ... 
I'm slightly disappointed that basic UI consistency topics do not get attention, but there are more important things in the world to worry about.
So I'll close it.

**Pull request closed without merging**
