### PR TITLE
collect : add optional single-click selection

### PR DESCRIPTION
**Pull request by AlicVB**
Default value stay double-click
As a side effect, this allow multiple (range) selection for numeric and date-time value

### CODE REVIEW

**Comment by houz** [comment]
What is the state of this PR?

**Comment by TurboGit** [comment]
@AlicVB: do you plan updating? Ot should we close this PR. Thanks.

**Comment by TurboGit** [comment]
Should we revisit and update this PR? I'm all for it do be integrated. Thanks.

Or let me know if you prefer closing this PR.

**Comment by TurboGit** [comment]
Too many things to change from this old PR. This will need a full rewrite.

**Pull request closed without merging**
