### PR TITLE
read tiff colorspace

### LINKED ISSUE #2252: New non-CIELAB pipe breaks the darktable-chart utility
Previously, the `darktable-chart` utility made use of [a "hidden" darktablerc option to enable a no-op output color profile which dumped the CIELAB data directly to a file](https://www.darktable.org/usermanual/en/darktable_chart_making_input_images.html). The recent changes to the pipeline in the master branch have broken this "feature". Prior to any 2.8 release, this should probably be addressed somehow.

### PR DESCRIPTION
**Pull request by edgardoh**
Lab tiff files are supported but were not handled.

Fixes #2252

### CODE REVIEW

**Comment by TurboGit** [comment]
Looks good! Thanks again, sorry I keep repetting that but you are really doing a great job!

**Comment by edgardoh** [comment]
Thanks!

This fix is correct as the tiff colorspace was not handled, but I'm not
sure that it will fix the reported issue as I don't really know how that
module works, maybe is something else going on.

**Comment by junkyardsparkle** [comment]
I haven't had a chance to check yet, but note that #2252 didn't actually involve a Lab TIFF file; the problematic TIFF was in the native linear scanner color space, the PFM file required by `darktable-chart` needs to be *exported* in Lab. In any case,, I'll try to have something actually useful to report shortly.

**Comment by junkyardsparkle** [comment]
TIFF file can now be successfully exported as Lab PFM file from a clean config, thanks for your effort! Now I'll try to figure out why it's not working from an updated 2.6 configuration...

**Pull request merged**
