### PR TITLE
Support lensfun library to 2.0.0

### PR DESCRIPTION
**Pull request by payano**
Issue #9037 was accidently closed, this is a continuation of that PR.

I want to start a discussion on how to implement support for new API in Lensfun, and fix the backward compability issues that lensfun has with the old API.

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
I don't know about lensfun internals but just looking at your diff; would we need to check the lib version at runtime?

**Comment by parafin** [comment]
I don't think so. lensfun ABI has changed, so it's not possible to switch libraries at runtime.

BTW, I suggest we drop all the code about 0.3.95 once (if) 2.0.0 is released, assuming #2813 is fixed.

**Comment by jenshannoschwalm** [comment]
> I don't think so. lensfun ABI has changed, so it's not possible to switch libraries at runtime.

Ok, as the distro shipped library stays constant?

**Comment by parafin** [comment]
It may be updated to newer version. The problem here is broken 0.3.95 version, I'm not sure if ABI is compatible, it's better if lensfun changed ABI version to make sure it's not used accidentally in place of 2.0.0 and we would refuse to compile with 0.3.95.

**Comment by elstoc** [comment]
Refusing to compile with 0.3.95 won't necessarily help with distros that already ship 0.3.95. There's probably as much (more?) chance that they patch darktable to allow 0.3.95 as that they downgrade the distro version of lensfun. Obviously those distros (ArchLinux and Manjaro _might_ be the only ones?) will already have users with a mix of old, new and broken edits anyway.

**Comment by parafin** [comment]
I don't think we can deal with broken edits, only try to limit amount of cases they are produced in the future.

**Comment by payano** [comment]
> I don't know about lensfun internals but just looking at your diff; would we need to check the lib version at runtime?

Are you sure about that? The #if statements are for the preprocessor and should be compile time checks, see: https://gcc.gnu.org/onlinedocs/gcc-3.0.1/cpp_4.html

**Comment by payano** [comment]
I'll start to work on the #2813 and try to discuss it further with the lensfun guys. I'll keep you posted.

**Comment by payano** [comment]
I got strange artifacts on one picture but when I copied it in dt it disappeared and can't reproduce it any longer, does this happens for all raw pictures for all lenses? I would be grateful if someone could please share one raw and xmp with this characteristics

**Comment by payano** [comment]
I'm using ubuntu and have installed darktable from the apt-get, version is: 3.4.1
My procedure is this:
1. I remove the /usr/lib/x86_64-linux-gnu/liblensfun.so.0.3.95 just so darktable can't use the installed shared object.
2. rm -rf .config/darktable/
2. Open darktable with liblens 0.3.2: LD_PRELOAD=~/git/lensfun1/build/libs/lensfun/liblensfun.so.0.3.2 darktable
2. Add Lens correction to one file and then paste the lens correction history stack on to multiple raw images
3. Close darktable
4. Open darktable with liblens 2.0.0: LD_PRELOAD=~/git/lensfun2/build/libs/lensfun/liblensfun.so.2.0.0 ./bin/darktable (this darktable binary is built from the master branch from my repo)
5. Upgrade the databases.
6. Open the images, can't see any artifacts on my pictures though.

Am I doing this right?

**Comment by parafin** [comment]
No, you have to rebuild against correct version. LD_PRELOADing a library with different ABI version will result in undefined behaviour.

**Comment by payano** [comment]
Before I compiled darktable I installed the 2.0.0 apt libraries that I've built:
dpkg -i liblensfun1_2.0.0_amd64.deb liblensfun-bin_2.0.0_amd64.deb liblensfun-data-v1_2.0.0_all.deb liblensfun-dev_2.0.0_amd64.deb python3-lensfun_2.0.0_amd64.deb

if I start my compiled version without LD_PRELOAD:
./bin/darktable
[iop_load_module] failed to open `lens': liblensfun.so.2: cannot open shared object file: No such file or directory

And if i start my darktable version from apt-repo:
[iop_load_module] failed to open operation `lens': liblensfun.so.1: cannot open shared object file: No such file or directory

**Comment by payano** [comment]
My built version was using the latest lensfun.h file.

**Comment by payano** [comment]
Should the artifacts be shown on every raw file with lens correction enabled on a 0.3.2 release and then migrate to the latest lensfun version?

**Comment by payano** [comment]
my lensfun1 git repo shows that i'm on commit:
commit ef537313ff5a2c977f60f10bd09fd155a85535a7 (HEAD, tag: v0.3.2)
my lensfun2 git repo shows:
commit 5383e8593ee6570baf08f12554b1934d14e3bfbd (HEAD -> bump_ver, origin/bump_ver)

~/git$ find -type f -name "liblensfun*"
./lensfun2/build/libs/lensfun/liblensfun.so.2.0.0
./lensfun1/build/libs/lensfun/liblensfun.so.0.3.2

/git$ find -type l -name "liblensfun*"
./lensfun2/build/libs/lensfun/liblensfun.so.2
./lensfun2/build/libs/lensfun/liblensfun.so
./lensfun1/build/libs/lensfun/liblensfun.so
./lensfun1/build/libs/lensfun/liblensfun.so.1

**Comment by payano** [comment]
> No, you have to rebuild against correct version. LD_PRELOADing a library with different ABI version will result in undefined behaviour.

I think I have done that.

**Comment by parafin** [comment]
OK, I've missed that it was different builds. Still better to use `LD_LIBRARY_PATH=~/git/lensfun1/build/libs/lensfun/` instead of `LD_PRELOAD=~/git/lensfun1/build/libs/lensfun/liblensfun.so.0.3.2` - first one is standard way to point to a library, making sure correct ABI version is picked, second one is basically a hack for very specific purposes and this dangerous.

**Comment by payano** [comment]
> OK, I've missed that it was different builds. Still better to use `LD_LIBRARY_PATH=~/git/lensfun1/build/libs/lensfun/` instead of `LD_PRELOAD=~/git/lensfun1/build/libs/lensfun/liblensfun.so.0.3.2` - first one is standard way to point to a library, making sure correct ABI version is picked, second one is basically a hack for very specific purposes and thus dangerous.

Thanks for the tip!
I still can't see any artifacts on my test pictures. I don't know how to reproduce this error though.
Any suggestions?

**Comment by payano** [comment]
I can see that another scale is calculated, the scale I have on my prime lens (Sony E, 35 f/1.8 OSS):
lensfun-0.3.2 : 1.002
lensfun-2.0.0: 0.983
But no artifacts are shown.

**Comment by payano** [comment]
My dt build is based on the commit: edb19dead8a597e63b1e1b2f86cab8bd924f8a18

**Comment by jakubfi** [comment]
If the scale parameter changes in lens correction module by itself, between dt versions compiled against different lensfun versions, you won't see any artifacts, because correct scaling is applied depending on lensfun version. That means something has changed in the meantime in the lens correction module, and instead of using the scale stored in the sidecar file, module now reapplies the correction for a given lens and uses new scaling factor instead. It is also possible that now the module doesn't store the scaling factor at all, if it hasn't been touched by the user.

**Comment by elstoc** [comment]
My understanding is that if the user doesn't touch any of the parameters (just switches it on), the module just auto-calculates based on Exif data. As soon as a user touches a single parameter they're all saved to the database and used for subsequent calculations.

**Comment by payano** [comment]
> If the scale parameter changes in lens correction module by itself, between dt versions compiled against different lensfun versions, you won't see any artifacts, because correct scaling is applied depending on lensfun version. That means something has changed in the meantime in the lens correction module, and instead of using the scale stored in the sidecar file, module now reapplies the correction for a given lens and uses new scaling factor instead. It is also possible that now the module doesn't store the scaling factor at all, if it hasn't been touched by the user.

Good point there, I'll dig around and investigate and also I will also look for the commit that changed the behaviour of the correction module.

**Comment by payano** [comment]
> My understanding is that if the user doesn't touch any of the parameters (just switches it on), the module just auto-calculates based on Exif data. As soon as a user touches a single parameter they're all saved to the database and used for subsequent calculations.

This is the first step to reproduce the bug in the issue:
Make an edit in dt compiled against lensfun 0.3.2 by enabling lens correction with automatic lens detection and setting focal length, f-number and distance.

How I interpret that text is that the user doesn't do any manual settings in the module, or have I misunderstood something? 😀

**Comment by elstoc** [comment]
No idea sorry. I've not tried it

**Comment by payano** [comment]
@jakubfi: I checked out the commit 4b77a5410f9e6ac7f3a8668c2a219767b1230f4a because that was a commit close to where you created the issue. I made two builds, the first is using lensfun-0.3.2 and the second one is using lensfun-2.0.0
I enabled lens correction with the lensfun-0.3.2 version and manually changed the scale to ~1.5, then I closed dt.

I then opened up dt that was built against lensfun-2.0.0 and saw that the scale has changed to 0.983.

I'll test against the lensfun version 0.3.95 to see if I can reproduce it.

**Comment by payano** [comment]
Is it needed to serialize the scale value, why not instead get the correct value from the library, then the edits shouldn't break? I know that can be a performance penalty to always check with the lensfun library though.

**Comment by jakubfi** [comment]
> I enabled lens correction with the lensfun-0.3.2 version and manually changed the scale to ~1.5, then I closed dt.
> I then opened up dt that was built against lensfun-2.0.0 and didn't see any artifacts.
I assume the scale stayed the same between versions?
I don't rememer testing it with scale set manually, btw.
Also: artifacts were appearing because the scale was set too low for the new scaling algorithm, allowing the image distortion to be seen on the edges instead of being cut by the scaling factor.
> I'll test against the lensfun version 0.3.95 to see if I can reproduce it.
That's what I would do. There were some some changes in lensfun in the meantime too, I guess.

**Comment by payano** [comment]
I built 0.3.2, 0.3.95 and 2.0.0
I'm using ubuntu and the packages the package version installed is: 0.3.2
To start 0.3.2: ./bin/darktable --configdir /home/johan/darktable-config
To start 0.3.95: LD_PRELOAD=/home/johan/git/lensfun-0.3.95/build/libs/lensfun/liblensfun.so.2 ./bin/darktable --configdir /home/johan/darktable-config
To start 2.0.0: LD_PRELOAD=/home/johan/git/lensfun-2.0.0/build/libs/lensfun/liblensfun.so.2 ./bin/darktable --configdir /home/johan/darktable-config

I tested on three pictures DSC00084.ARW, DSC00115.ARW and DSC02013.ARW

0.3.2:
|Picture | setting | scale|
| DSC00084.ARW | auto      | 1.006 |
| DSC00115.ARW | manual | 1.062 |
| DSC02013.ARW | auto      | 1.011 |

0.3.95:
|Picture | setting | scale|
| DSC00084.ARW | auto      | 1.013 |
| DSC00115.ARW | manual | 1.062 |
| DSC02013.ARW | auto      | 1.011 |

2.0.0:
|Picture | setting | scale|
| DSC00084.ARW | auto      | 1.013 |
| DSC00115.ARW | manual | 1.062 |
| DSC02013.ARW | auto      | 1.011 |

**Comment by jakubfi** [comment]
> First I started the 0.3.2 version, removed the xmp files and the config dir, then I started 0.3.95 and last the 2.0.0 version.

Do I understand correctly, that you removed sidecar and config after testing with dt+0.3.2 and before running dt+0.3.95? If that's the case, this is not the correct testcase.

**Comment by payano** [comment]
This is how i did the test.
1. remove .xmp and config dir ( rm -rf /home/johan/darktable-config && cd ~/Pictures/test/ && rm *.xmp )
2. start dt with 0.3.2 version, enable lens correction, and wrote down the results, closed dt
3. open dt with version 0.3.95, and wrote down the results, closed dt
4. open dt with version 2.0.0.0 and wrote down the results, closed dt

**Comment by payano** [comment]
I don't know what I'm doing wrong though ;(

**Comment by payano** [comment]
If the user manually set the scaling to something else, I think that we need to get the new scaling value when using the lensfun library >= 0.3.95?

**Comment by johnny-bit** [comment]
Here's how I see it, due to the fact that some distros (ekhm arch ekhm) packaged and stabilized and built dt with lensfun 0.3.95 alpha...

0.3.2 -> 2.0.0

1. Open up image and customize lens correction using lensfun 0.3.2. export it
2. open same image with not-changed xmp, in darktable compiled with lensfun 0.3.95 and export it
3. compare images from pt 1 and 2 - you'll notice difference
4. open same image with not-canged xmp in darktable compiled using lensfun 2.0.0 and export it
5. compare images from pt 1 and 4 - there should be no difference

0.3.95 -> 2.0.0

1. Open up image and customize lens correction using lensfun 0.3.95. export it
2. open same image with not-changed xmp, in darktable compiled with lensfun 0.3.2 and export it
3. compare images from pt 1 and 2 - you'll notice difference
4. open same image with not-canged xmp in darktable compiled using lensfun 2.0.0 and export it
5. compare images from pt 1 and 4 - there should be no difference

0.3.95 "broke" corrections made with 0.3.2. Ideally it'd be great if 2.0.0 wouldn't break either. However if I were to choose which one to break I'd opt for breaking backwards compatibility with 0.3.95 rather than 0.3.2 since most maintainers didn't stabilize apha package :)

**Comment by payano** [comment]
Got it. I will not care about the 0.3.95 alpha release, my goal is to make 0.2.3 -> 2.0.0 working.
I might have something working in dt. but I also need to modify the lensfun library, which I'm looking in to right now.

**Comment by payano** [comment]
- Okay, I have something working now, I

**Comment by payano** [comment]
Okay, I can get the old and the new scale value, I divide the new scale by the old scale and get the scale factor. I can see if I export one image from lensfun 0.3.2 and 2.0.0 but i think that is a rounding error. Is it critical that the two pictures are identical or is it sufficient that artifacts doesn't show up?

My working branches are here:
https://github.com/payano/lensfun/tree/working_branch (2.0.0)
https://github.com/payano/darktable/tree/working_branch (3.4.1.1)

**Comment by jakubfi** [comment]
Your proposed workaround is basically an implementation of what was mentioned in https://github.com/lensfun/lensfun/issues/945, but done on dt side. This approach is wrong. We shouldn't be working around a broken API of a development snapshot of a library. It's the library that needs to fix a known bug before the next stabe release.

What happens when scaling factor is fixed in the next release of lensfun while dt is being shipped with your scaling factor applied on top of the lensfun scaling factor?

**Comment by payano** [comment]
Thanks for your feedback @jakubfi . I  agree with you, that the problem with scaling between lensfun versions should be owned by the lensfun library, not the application that uses it. I'll move the scaling implementation to lensfun instead.

**Comment by payano** [comment]
I've built both lensfun 2.0.0 and darktable 3.4.1.1 for Ubuntu 20, the deb packages can be found here:
https://exclude.se/dt/

**Comment by janfri** [comment]
@payano Thanks for your commitment 👍

Just my 2 cents:
>     1. Keep as is, and use an outdated, stalled library.
This is no option for me.

>     2. Fork the project and start developing and update the database and code base reguarly.
A lot of work to do and I doubt we will find other developers to support this.

>     3. Develop a lens calibration module which is tightly integrated with the DT code base.
This is my prefered approach. If possible I think it would be the best way to use the lensfun database and implement the functionality in darktable (maybe as a submodul).

> I don't think that the PR I made on Lensfun repo will ever be merged, it perhaps wasn't the best implementation but it was at least a start to try to fix what was wrong...
> 
> I think that we should have a way forward, and try to future proof this module in DT.
👍

**Comment by janfri** [comment]
> 
> 
> > > ```
> > > 1. Keep as is, and use an outdated, stalled library.
> > > ```
> > 
> > 
> > Keep in mind that the library is not updated but the database of lens is updated and you can get support for new lens by updating your database locally. Not that bad.
> 
> I agree, it's awesome and I should have mentioned that the database is still updated, good point there.

Does the database update work for you? I use Ubuntu and ```lensfun-update-data``` only updates the database in the lensfun database version 1 (not 2). So I don't get the newest changes of the database. :-(

**Comment by payano** [comment]
> Pop over IRC or whatever, chat with lensfun project peeps. Lensfun is used not only in darktable but across the os land so landing fixes in lensfun is net benefit to all.

I totally agree with you. My main contact point with the project has been via Github, I also noticed that they have a mailing list, haven't tried it yet though. But my impression is that the maintainers are busy with other things nowadays. 
I don't have time to be a maintainer of the project, I can instead be a contributor when I have the time to help out.

**Comment by payano** [comment]
> Does the database update work for you? I use Ubuntu and the `lensfun-update-data` script of the Ubuntu package (0.3.2) only updates the database in the lensfun database version 1 (not 2). So I don't get the newest changes of the database. :-(

Yes sir!
If you update the database version 1 you are fine, you can't use the updated database version because you need to use a later version of liblensfun. You can use the version 0.3.95 if you want to use version 2.

**Pull request closed without merging**
