### PR TITLE
fix support for libavif 0.11.1

### PR DESCRIPTION
**Pull request by ralfbrown**
#17177 broke building with libavif 0.11.1.  This PR fixes that.

### CODE REVIEW

**Comment by wpferguson** [comment]
doesn't work for Ubuntu 22.04 with libavif 0.9.3-3

**Comment by wpferguson** [comment]
Works on Ubuntu 22.04 with libavif 0.9.3-3

**Comment by KarlMagnusLarsson** [comment]
Works on Debian stable Bookworm 12.6.

There are three PRs related to https://github.com/darktable-org/darktable/pull/17177 and issue https://github.com/darktable-org/darktable/issues/17182

- https://github.com/darktable-org/darktable/pull/17183
- https://github.com/darktable-org/darktable/pull/17184
- https://github.com/darktable-org/darktable/pull/17195

**Comment by ralfbrown** [comment]
Should have checked for PRs, but I needed the fix so I could work on dt....

**Comment by ralfbrown** [comment]
Since Hanno withdrew his PR and mine is effectively identical to @victoryforce's, I withdraw mine as well to avoid conflicting PRs.

**Pull request closed without merging**
