### PR TITLE
Generate preferences dialog for in module preference support.

### PR DESCRIPTION
**Pull request by TurboGit**
This adds a new attribute dialog which can be set to generate the needed
preference dialog for a specific module.

The current version supports dialog="collect" and generate the routine:

   static void
   init_dialog_collect (GtkWidget *dialog);

The user has to create a dialog and call this routine to populate
the dialog with all corresponding options.

Part of #7530.

### CODE REVIEW

**Comment by phweyland** [comment]
Trying to build collect set_preference() based on this.

The first issue is that
```
static void
init_dialog_collect (GtkWidget *dialog);
```

is not exposed (unless I include preference_gen.h in collect.c) . Perhaps `static` should be removed too.

If I include reference_gen.h in collect.c I can compile and run dt.

I get this:

image

and this:
`(darktable:16437): Gtk-CRITICAL **: 09:37:52.020: gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed`

This structure allows indeed to add other stuff in the dialog if needed. Sounds good.

But if we need to trig an event on one of the setting (g_signal_connect()) (to enable or disable part of the "other stuff") how can I access and recognize the right widget ?

**Comment by phweyland** [comment]
Another point I've met. If there are only standard preferences, the "done" button is enough.
But due to "other stuff" you may want to cancel the dialog (like in import pref dialog). In that case we need the possibility to undo the changes made on preferences.

**Comment by TurboGit** [comment]
> Perhaps `static` should be removed too.

Sure, will do.

**Comment by TurboGit** [comment]
> and this:
> `(darktable:16437): Gtk-CRITICAL **: 09:37:52.020: gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed`

I can look at this if you want. Just publish your PR based on mine here.

**Comment by TurboGit** [comment]
Done for static and I have renamed the routine `dt_prefs_init_dialog_collect()` as part of dev API.

**Comment by TurboGit** [comment]
BTW, the dialog code is a copy/paste of pref code and is using a scrolled window which is certainly not necessary here. Again I can have a look if you push the current PR state here. I'm sure the code need some clean-up as reported by the  Gtk-CRITICAL issue.

**Comment by TurboGit** [comment]
> This structure allows indeed to add other stuff in the dialog if needed. Sounds good.

Right, we can manage the prefs very easily by just adding `dialog="collect"` to other preferences and that's all. It would be as easy to also remove preferences from dialog if needed.

**Comment by phweyland** [comment]
> dt_prefs_init_dialog_collect()

That's but the name was not an is issue. But is it right to include the full preference_gen.h whenever we need to setup a pref dialog ? Shouldn't we have a light include file with
`void dt_prefs_init_dialog_collect (GtkWidget *dialog);`
declaration ?

**Comment by TurboGit** [comment]
> That's ok but the name was not an is issue. But is it right to include the full preference_gen.h whenever we need to setup a pref dialog ?

No that's not ok indeed. We can just create manually the header file preference_dialogs.h. This can be static and committed as anyway each dialog need some rules in the XSL.

**Comment by TurboGit** [comment]
Added ; gui/preferences_dialogs.h

**Comment by TurboGit** [comment]
@phweyland  : I have done some clean-up on the generated code.

**Comment by phweyland** [comment]
if I remove these lines:
```
  GtkWidget *scroll = gtk_scrolled_window_new(NULL, NULL);
  gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW(scroll), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  viewport = gtk_viewport_new(NULL, NULL);
  gtk_viewport_set_shadow_type(GTK_VIEWPORT(viewport), GTK_SHADOW_NONE); // doesn't seem to work from gtkrc
  gtk_container_add(GTK_CONTAINER(scroll), viewport);
  gtk_container_add(GTK_CONTAINER(viewport), grid);
```

I get it right:
image

if I replace area by scroll in 
`  gtk_box_pack_start(GTK_BOX(area), grid, FALSE, FALSE, 0);`
I get a one line window.

**Comment by phweyland** [comment]
> I have done some clean-up on the generated code.

:+1: 

I'll update #7530

**Pull request merged**
