### PR TITLE
Fix overlays icons size for HiDPI Windows 10

### PR DESCRIPTION
**Pull request by Mark-64**
Hi, this tries to fix the wrong size of some thumbnail overlay icons in the new Lightable for HiDPI displays in Windows 10.

Cattura24

It does not affect non-HiDPI displays.
However it's a workaround. The problem of icons scaling incorrectly cannot be solved if we keep a mix of Cairo drawing icons and simple text icons like "G" or "?". They will always scale differently with DPI and proportions cannot be kept accurately.
For a proper solution we should replace completely text icons.

### CODE REVIEW

**Comment by parafin** [comment]
Why are they scaled differently?..

**Comment by TurboGit** [comment]
The patch which is very specific looks wrong to me.

**Comment by Mark-64** [comment]
Here are the samples on three systems, please look only at size of icons, not to colors.
This is without the patch:

Windows 10, LoDPI screen
Cattura_2w_lodpi__wo

Windows 10, HiDPI screen
Cattura_2w_hidpi__wo
(this looks plain wrong as you can see, text and graphics icons scale differently, proportions are not kept)

Linux Ubuntu, HiDPI screen
Cattura_2l_hidpi__wo
(Linux and Windows scaling mechanisms are different)

and this is with the patch:

Windows 10, LoDPI screen
Cattura_2w_lodpi__w

Windows 10, HiDPI screen
Cattura_2w_hidpi__w

Linux Ubuntu, HiDPI screen
Cattura_2l_hidpi__w

The patch has no effect on low dpi screens and in Linux, only affects Windows HiDPI screens.
Yes it is very specific correction, althoug the code is similar to function _button_draw() in button.c, but as I said it is a workaround. Proper fix would be replace text icons like "G" and "?" with Cairo drawings

**Comment by TurboGit** [comment]
> For a proper solution we should replace completely text icons.

Then I vote for this.

**Comment by Nilvus** [comment]
@Mark-64: I agree with @TurboGit. Having a proper solution would be better. And HiDPI icons with you patch on Linux is not really great: altered icon is a little bigger (and cropped) in regards to the group icon.

**Comment by TurboGit** [comment]
@Mark-64: are you ok to work on creating Cairo based 'G' and '?' ?

**Comment by Mark-64** [comment]
new Cairo icons for Group and Help. I still have to do some tests on different OS / screen.

**Comment by TurboGit** [comment]
@Mark-64 : Perfect ! Ping me when testing done. I'll do some testing on my side too.

**Comment by Nilvus** [comment]
Will test that also (Linux Ubuntu 20.04 and lodpi screen). Thanks for that work.

**Comment by TurboGit** [comment]
I like the new grouped icon and the ? looks ok to me.

image

**Comment by Mark-64** [comment]
The icons look ok on the three systems I have access to (Win10 lowdpi/hidpi and Ubuntu 19.10 hidpi).
Scaling is pixel accurate now, for example
Cattura26
Cattura27
Had to slightly retouch the "altered" icon too. So this is ready for review.

BUT...
I consider this a first step. I still don't like how DT looks in Win10 HiDPI. Some icons look too small with respect to Ubuntu, same screen. 
Different OSs have different scaling mechanisms and we are still far from having a seamless GUI experience across all.
Digging into paint.c and the button draw routines in various parts of the code, I realized there are still some gui elements where size is hardcoded in pixels. The Cairo icons do not always have the same size natively and are adjusted ad-hoc.
To have a truly proportional scaling there is quite a lot of work to do. Before starting a time consuming tasks, I would like to know if you support the idea.

**Comment by parafin** [comment]
Maybe you should first outline the problem - how scaling is different on different OSes and what DT does wrong right now. It's not obvious for me at least.

**Comment by Mark-64** [comment]
I added one last commit, removing an ad-hoc HDPI fix which I did some time ago, no longer needed

**Comment by Mark-64** [comment]
@parafin I will, but not now. I have to switch to lua, as one of my scripts is broken after the LT rewrite

**Comment by TurboGit** [comment]
Looks good to me! @Nilvus, ok to you ?

**Comment by Nilvus** [comment]
> Looks good to me! @Nilvus, ok to you ?

Not test by now, lack of time today. Will try to check tonight.

**Comment by Nilvus** [comment]
This looks good but I've test with some tricks as your branch is not rebased on recent master (you don't have my recent CSS work on overlays mode). I've test with my work but and all seems good.

Thanks for that work, like the new icons and especially the new groups icons (at first, just strange to not see the ugly old G icon!).

**Comment by Nilvus** [comment]
Just an update: tested rebased on master. All good for me. @TurboGit: I think this could be merged.

**Comment by TurboGit** [comment]
Merging then, Thanks.

**Pull request merged**
