### PR TITLE
refactor: deduplicate Log2, Log2Thresh, fastlog, fastlog2

### PR DESCRIPTION
**Pull request by ralfbrown**

### CODE REVIEW

**Comment by johnny-bit** [comment]
Huh, how could this change create missing header problem in `blend_gui.c` (causing undefined `M_LN10`)...

**Comment by ralfbrown** [comment]
Bizarre.  Can't reproduce that with clang-8 (though I also have  to use --disable-openmp to get it to build at all).

I had the thought that maybe the `#include <math.h>` in blend_gui.c is somehow getting common/math.h instead of the system header, but common/math.h includes the system header itself....

**Comment by TurboGit** [comment]
Looks good to me !

**Comment by TurboGit** [comment]
Also merged in master for the M_LN10 change in #7379 to apply properly.

**Pull request merged**
