### PR TITLE
Spanish user manual translation update

### PR DESCRIPTION
**Pull request by EdgarLux**
Updating and correcting some typos

### CODE REVIEW

**Comment by TurboGit** [comment]
Thanks.

**Comment by EdgarLux** [comment]
Bonjour @TurboGit! I have noticed that since this update, there is no pdf online or at https://www.darktable.org/resources/
Could it be added before continuing to update it for version 3.0?

**Comment by TurboGit** [comment]
@EdgarLux : The manuals are built only when the release is done. This is because it is not a trivial work and so we do not update the doc regularly. If at some point I'm able to have a script doing all the work for me it may change :)

**Comment by EdgarLux** [comment]
Ok, I understand. So, for the next version 3.0, when should the manual be ready? after or before the final release?

**Pull request merged**
