### PR TITLE
retouch backward comp

### LINKED ISSUE #2238: DB conversion mess up retouch in iop order
**Describe the bug**
after database conversion 2.6.1 --> 2.7.0 the module retouch is misordered:

[dt_ioppr_transform_image_colorspace] module retouch must be between input color profile and output color profile

**To Reproduce**
1. clean .config/darktable
2. open file in darkroom and apply retouch in dt.2.6.1
3. click display wavelet scale --> fine
4. close dt2.6.1. open dt 2.7.0, confirm db conversion
5. open file in darkroom expand module retouch, click display wavelet scale
4. messed up display

**Platform (please complete the following information):**
 - OS: OSX
 - Version:
`this is darktable 2.7.0+753~gb320074dc
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.1
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled
`

### PR DESCRIPTION
**Pull request by edgardoh**
Fixes #2238

### CODE REVIEW

**Comment by TurboGit** [comment]
Looks good to me. One minor comment, please be sure to add a little description into the comment message to what was done. It may be useful when reading log message. Of course the ref to the issue is important, just that a little description too may help especially for me reading log message to check against the release-notes and looking for potential commit to merge, etc. Thanks.

**Comment by edgardoh** [comment]
Do you mean in the first post or in the commit?

**Comment by TurboGit** [comment]
In the commit log of each commit. The first line should be a short description, followed by an empty line then a longer description when needed and then the issue ref if it exists. See for example: 38006e5f

**Comment by edgardoh** [comment]
I'm trying to do it for the search box but I have no idea where I can edit
the commit message...

**Comment by TurboGit** [comment]
You cannot do that on GitHub. This must be done at commit time for each commit. You can also do an interactive rebase and reword each commit if necessary in your topic branch (this is advanced, but I do that all the time).

**Pull request merged**
