### PR TITLE
move lut 3d after filmic

### PR DESCRIPTION
**Pull request by blitzgneisserin**
See discussion here https://github.com/darktable-org/darktable/issues/9873

The main purpose of this module is applying creative looks such as film simulations - the module expects a "correct" neutral image  (correct lower contrast/chroma, correct exposure and white balance). This is not the case if it is before filmicrgb.

For now, I moved the module right after filmicrgb, but maybe it should be even after bilat (local contrast) - however, in practice, there is no to very little difference according to my tests. So right after filmic should be ok.

### CODE REVIEW

**Comment by TurboGit** [comment]
This works, but... We have today 3 implemented pipe orders named legacy, v3.0 jpeg and v3.0 raw.

Old edits using the `3D-Lut` will be flagged now has having a  "**custom**" order as if the `3D-Lut` had been moved before Filmic. Maybe not a big problem, it is only a display issue but I wanted to raise this point.

If we want to avoid that we need to introduce a new pipe-order. That is, not modifying the current one, but creating a new order for all modules. Not sure it is worth the pain here.

@phweyland : What do you think ?

**Comment by phweyland** [comment]
> Old edits using the `3D-Lut` will be flagged now has having a "**custom**" order as if the `3D-Lut` had been moved before Filmic.

If modifying the lut3d position has no other effect (history issue, ...) that seems ok to me. At least people are warned that something has changed.

> That is, not modifying the current one, but creating a new order for all modules. Not sure it is worth the pain here.

Agreed. For me it is not worth to create a new order. Lut3d position is a small detail compared to scene-referred  / modern workflow stuff.

**Review by TurboGit — CHANGES_REQUESTED** [review]
Looking more at it, since `tonecurve` may be used instead of filmic or basecure (we have even a legacy tool to create camera specific curve for tonecurve) I would move the lut3D module even after `tonecurve` module. TIA.

**Comment by blitzgneisserin** [comment]
So do you want me to do something?

**Comment by TurboGit** [comment]
> So do you want me to do something?

Yes please, moving it after `tonecurve` so a bit later in the pipe.

**Comment by phweyland** [comment]
But in that case, colisa (I don't know this one) should be moved after tonecurve and lut3d, shouldn't it ?

**Comment by TurboGit** [comment]
Ok, so I'll only merge first commit (moving after filmic) as indeed colisa won't be at the right place. I'll merge manually.

**Comment by johnny-bit** [comment]
I REALLY think lut 3D needs more documentation about whys of LUTs and about placement of module depending on LUT use/intent. Sure, there are bunch of free LUTs that expect already done image, just to add some color shifts, but then there are pro-grade luts for grading films that expect eg film cLOG input (which looks like RAW but with adjusted exposure)... Users need to be informed about those intricacies imo.

**Comment by elstoc** [comment]
Agreed. I took most of the info in the manual from the previous manual and the blog post, but it needs more from someone who understands it all.

**Comment by blitzgneisserin** [comment]
Thanks for merging!

**Comment by johnny-bit** [comment]
@elstoc - https://github.com/darktable-org/dtdocs/issues/340 - not my best one tho...

@blitzgneisserin - congratulations on your first merge!

**Comment by blitzgneisserin** [comment]
@johnny-bit thanks!

**Pull request closed without merging**
