### PR TITLE
Fixing local contrast issue #5643

### LINKED ISSUE #5643: darktable crashes when adding a second instance of local contrast
darktable crashes when adding a second instance of local contrast
**Describe the bug**

Hi, I observed an issue with the  last build current master darktable-3.1.0+2374. 
Issue: Open a RAW NEF file with processing: scene referred; apply local contrast; apply new instance of local contrast and dt a crashes.

**To Reproduce**

I am on a Mac with OS 10.13.6. OpenCL not activated. Here is the report following the crash

Process: darktable [30918]
Path: /Applications/darktable.app/Contents/MacOS/darktable
Identifier: org.darktable
Version: 3.1.0 (3.1.0.2374)
Code Type: X86-64 (Native)
Parent Process: ??? [1]
Responsible: darktable [30918]
User ID: 501

Date/Time: 2020-06-26 11:49:22.308 +0200
OS Version: Mac OS X 10.13.6 (17G11023)
Report Version: 12
Anonymous UUID: 16A87C5B-EBC9-AE14-A1B5-38F493419B78

Sleep/Wake UUID: C434A1B1-9A89-44F5-89C2-85B6A23DCBE8

Time Awake Since Boot: 210000 seconds
Time Since Wake: 130 seconds

System Integrity Protection: enabled

Crashed Thread: 0 Dispatch queue: com.apple.main-thread

Exception Type: EXC_BAD_ACCESS (SIGABRT)
Exception Codes: KERN_INVALID_ADDRESS at 0x0000000000000028
Exception Note: EXC_CORPSE_NOTIFY

VM Regions Near 0x28:
–>
__TEXT 0000000103e55000-0000000103e62000 [ 52K] r-x/r-x SM=COW /Applications/darktable.app/Contents/MacOS/darktable

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0 libsystem_kernel.dylib 0x00007fff674aab66 __pthread_kill + 10
1 libsystem_pthread.dylib 0x00007fff67675080 pthread_kill + 333
2 libsystem_c.dylib 0x00007fff6740624d __abort + 144
3 libsystem_c.dylib 0x00007fff674061bd abort + 142
4 libGraphicsMagick.3.dylib 0x0000000105c783bf MagickPanicSignalHandler.cold.1 + 32
5 libGraphicsMagick.3.dylib 0x0000000105b7fbed MagickPanicSignalHandler + 29
6 libsystem_platform.dylib 0x00007fff67668f5a _sigtramp + 26
7 ??? 0x000000010eab4950 initialPoolContent + 17776
8 libbilat.so 0x0000000110761e09 gui_changed + 153 (bilat.c:378)
9 libdarktable.dylib 0x0000000103f62f28 generic_combobox_enum_callback + 120 (imageop_gui.c:88)
10 libgobject-2.0.0.dylib 0x0000000104e6529f g_closure_invoke + 192
11 libgobject-2.0.0.dylib 0x0000000104e7871b signal_emit_unlocked_R + 2315
12 libgobject-2.0.0.dylib 0x0000000104e790a7 g_signal_emit_valist + 1809
13 libgobject-2.0.0.dylib 0x0000000104e7989c g_signal_emit_by_name + 258
14 libbilat.so 0x0000000110761dfa gui_changed + 138 (bilat.c:383)
15 libdarktable.dylib 0x0000000103f62b31 generic_slider_float_callback + 113 (imageop_gui.c:63)
16 libgobject-2.0.0.dylib 0x0000000104e6529f g_closure_invoke + 192
17 libgobject-2.0.0.dylib 0x0000000104e7871b signal_emit_unlocked_R + 2315
18 libgobject-2.0.0.dylib 0x0000000104e790a7 g_signal_emit_valist + 1809
19 libgobject-2.0.0.dylib 0x0000000104e7989c g_signal_emit_by_name + 258
20 libdarktable.dylib 0x0000000103e7e184 dt_bauhaus_slider_set_normalized + 324 (bauhaus.c:2343)
21 libbilat.so 0x0000000110762079 gui_init + 249 (bilat.c:441)
22 libdarktable.dylib 0x0000000103f5d14b dt_iop_gui_duplicate + 235 (imageop.c:897)
23 libdarktable.dylib 0x0000000103f61f73 dt_iop_gui_copy_callback + 19 (imageop.c:968)
24 libgobject-2.0.0.dylib 0x0000000104e6529f g_closure_invoke + 192
25 libgobject-2.0.0.dylib 0x0000000104e7871b signal_emit_unlocked_R + 2315
26 libgobject-2.0.0.dylib 0x0000000104e790a7 g_signal_emit_valist + 1809
27 libgobject-2.0.0.dylib 0x0000000104e7977c g_signal_emit + 120
28 libgtk-3.0.dylib 0x000000010466a8f1 gtk_widget_activate + 71
29 libgtk-3.0.dylib 0x000000010455cece gtk_menu_shell_activate_item + 252
30 libgtk-3.0.dylib 0x000000010455e5eb gtk_menu_shell_button_release + 473
31 libgtk-3.0.dylib 0x00000001046a66a8 _gtk_marshal_BOOLEAN__BOXEDv + 183
32 libgobject-2.0.0.dylib 0x0000000104e65468 _g_closure_invoke_va + 205
33 libgobject-2.0.0.dylib 0x0000000104e78df8 g_signal_emit_valist + 1122
34 libgobject-2.0.0.dylib 0x0000000104e7977c g_signal_emit + 120
35 libgtk-3.0.dylib 0x000000010466a054 gtk_widget_event_internal + 253
36 libgtk-3.0.dylib 0x000000010454c801 propagate_event + 364
37 libgtk-3.0.dylib 0x000000010454bbde gtk_main_do_event + 958
38 libgdk-3.0.dylib 0x0000000104ab1bf9 _gdk_event_emit + 49
39 libgdk-3.0.dylib 0x0000000104ad6756 gdk_event_dispatch + 50
40 libglib-2.0.0.dylib 0x00000001042fee8b g_main_context_dispatch + 258
41 libglib-2.0.0.dylib 0x00000001042ff186 g_main_context_iterate + 426
42 libglib-2.0.0.dylib 0x00000001042ff3b7 g_main_loop_run + 191
43 libgtk-3.0.dylib 0x000000010454b6ec gtk_main + 74
44 libdarktable.dylib 0x0000000103fe135a dt_gui_gtk_run + 202 (gtk.c:1475)
45 org.darktable 0x0000000103e61f4e main + 62 (main.c:106)
46 libdyld.dylib 0x00007fff6735a015 start + 1

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: 
 - 
 - 

**Additional context**

The issue was not observed with previous versions of dt
The issue was observed with a fresh edit
dt was compiled by MStraeten. He reproduced the issue and included a debugger output

https://discuss.pixls.us/t/current-osx-build/13213/109

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
In #5643 there are two identified problems.

1. Setting bauhaus sliders min/max values should be done after full initialising

In gui_init we should set the sliders hard_min/max **after** the full widget is initialised.
@dterrahe and @TurboGit is this analyses correct?

2. At least the bilateral cl path dislikes sigma_s smaller than 3

@TurboGit or other "CL people", i am not sure about the cl maths of the bilateral filter, i checked for accepted values and 3 is safe. Is this the right place to fix or is this a bug in cl kernel?

Fixes #5643

### CODE REVIEW

**Comment by dterrahe** [comment]
This is a workaround and I don't think a desirable one.

As I pointed out in https://github.com/darktable-org/darktable/issues/5643#issuecomment-650593437 I think this should be fixed in dt_iop_gui_duplicate, with a ++darktable.gui->reset, as that would also benefit other modules that might have similar issues, even if they maybe don't crash. But since this could have side effects, I would want the most knowledgeable person (@Turbogit ?) to look at it.

If he doesn't want to touch such a global routine at this point in the release, then you could simply put a
++darktable.gui->reset;
at the beginning of bilat.c gui_init, and a matching
--darktable.gui->reset;
at the end, but please also add a TODO comment that this should be reviewed for next release and possibly moved to dt_iop_gui_duplicate.

**Comment by jenshannoschwalm** [comment]
> This is a workaround and I don't think a desirable one.

Yes and of course your suggestion works fine and is probably the better/proper fix. Although that still leaves the question: Are the `dt_bauhaus_slider_set_hard...` functions safe as they are defined now?

**Comment by dterrahe** [comment]
Yes, because they respect darktable.gui->reset, which should have been set in this situation.

**Comment by MStraeten** [comment]
fix works on osx with and without opencl enabled

**Comment by TurboGit** [comment]
I also think that adding the fix in dt_iop_gui_duplicate is the way to go. As this is a fix we can certainly still do that for the release. We will need to be careful that when copying with the params (copy instance) we still want the sliders to be properly set to the corresponding value.

@jenshannoschwalm : Can you test this ? Thanks.

**Comment by jenshannoschwalm** [comment]
Will do ...

**Comment by johnny-bit** [comment]
Just a note - I remember fixing issue where duplicated instance wasn't activated due to reset being in place. I hope it won't reintroduce problem :)

**Comment by dterrahe** [comment]
If just gui_init is bracketed with ++/--darktable.gui->reset then the impact should be very limited and I would be surprised if it had such consequences. But then, gui->reset can be surprising.

I'm sorry I didn't have time to try this today. I could look at it tomorrow if @jenshannoschwalm hasn't already taken care of it. 

@johnny-bit if you remember more specifically what the issue was (or what fixed it) that would definitely help testing. An issue or PR number would be a god send.

**Comment by jenshannoschwalm** [comment]
> I remember fixing issue where duplicated instance wasn't activated due to reset being in place

Is you memory more precise :-)

**Comment by jenshannoschwalm** [comment]
Bracketing in dt_iop_gui_duplicate is indeed fixing **this** issue as we know. **But** i immediately ran into pretty weird history problems when reimporting developed images. Will have to do more testing to see what's going on...

**Comment by dterrahe** [comment]
Hopefully I can help tomorrow. Did you bracket the whole of dt_iop_gui_duplicate or just a section (maybe only the gui_init call)?

**Comment by jenshannoschwalm** [comment]
Just the section with gui_init and defaults.

**Comment by jenshannoschwalm** [comment]
Ok, i did a lot more testing and indeed this works correct.

My comment about history corruption was not related to this. There is indeed another issue, an "old duplicate friend" hitting again. I will open another report.

**Comment by TurboGit** [comment]
Works for me! Thanks.

**Comment by dterrahe** [comment]
After the second, gui->reset, commit, the first, 6c9b2fada41440904b99996853e08a933ce5efaf, wasn't really required anymore? Apart from the change of the hard limit for spatial to 3.0 to fix the second issue.

**Comment by jenshannoschwalm** [comment]
Indeed, I tested of course with **gui.reset only** and committed the new stuff. Could have reverted the first.

**Pull request merged**
