### PR TITLE
FCxtrans rework

### PR DESCRIPTION
**Pull request by dtorop**
This overlaps with (and is a superset of) PR #1155 but am putting it up for the sake of discussion/comparison. I'd been sitting on this until PR #1123 went up, but should have put it out there earlier, so as not to duplicate @pedrocr's work. I'd be happy to modify it appropriately to do make it complement PR1155, as mentioned.

Changes:

- as with #1155, use a higher negative guard in FCxtrans() so caller doesn't have to do same (+18 is high enough for all current code, though as pedrocr says, this may be famous last words)
- take advantage of pedrocr adding roi to FCxtrans() to simplify calls to it in xtrans_markesteijn_interpolate()
- fcol() doesn't need a negative guard, as FCxtrans() handles this
- inspired by the useful FCxtrans(), make a macro internal to xtrans_markesteijn_interpolate() which does something similar for allhex[] lookups

### CODE REVIEW

**Comment by pedrocr** [comment]
Sounds good to me. I've closed the other PR then. A few comments that may be helpful:

  * You mention +18 is enough but there was at least one location in your code that did +24
  * I recently changed FCxtrans() to take size_t for row/col. Since that's unsigned you need to change those back to int or maybe int32_t
  * I didn't add roi to FCxtrans() it was just defined that way in other places so when I consolidated I used the API with the most features and adjusted the other places

**Comment by houz** [comment]
> Since that's unsigned you need to change those back to int or maybe int32_t

Or use ssize_t.

**Comment by pedrocr** [comment]
> @houz Or use ssize_t.

That would work too but why use size_t for something that isn't a memory offset? row/col are image dimensions and we even use int for them (should probably be int32_t) in our internal pipe structures.

**Comment by dtorop** [comment]
This is now rebased onto master (I hadn't pulled df97cb1), and hence one more commit to change size_t back to int, using int accord with @pedrocr's suggestion that int is currently generally used.

Regarding the maximum offset being +18 now rather than +24, I reduced the offset in https://github.com/darktable-org/darktable/commit/6ca063a61fa7053dda35792b4ab0391c1680cbb6#diff-a001a1125b3a87d818accabc8b2f2751L602 because the the row/col in that loop will never be less than -17. Way back in https://github.com/darktable-org/darktable/commit/525183b185ab7d42625f17df2c405afa6bf6422e#diff-a001a1125b3a87d818accabc8b2f2751R548 I'd set the negative guard 6 higher than needed. No harm in the higher value, but seemed right to finally fix it.

I tested this PR by putting some code in FCxtrans() to report the minimum input row/col, and hence feel secure both experimentally and from examining the code that +18 is enough.

**Comment by pedrocr** [comment]
@dtorop good to know you've checked that 18 was enough but it would seem safer to just set 36 or even the 600 I set before to be *really* safe and not have a weird bug in the future, no? Is there any disadvantage to having larger values?

**Comment by dtorop** [comment]
@pedrocr It's a good point about not hardcoding 18, to not invite future bugs. I do worry that adding an larger number would include an arbitrary constant into the code and still risk FCxtrans() failing in some unexpected future case.

An alternative would be to define a modulo function which returned a positive result (so long as the divisor is positive), such as:

```c
static inline int umod(const int a, const int n)
{
  const int r = a % n;
  return (r >= 0) ? r : n + r;
}
```

As FCxtrans() seems to be a bit of a hot spot, such a solution tests about 4% slower on my machine than adding in an offset (whether +18 or +600). I'll check in a commit with an unsigned modulo function, for the purposes of discussion/review, but do worry that none of these choices are ideal.

**Comment by dtorop** [comment]
Checked in cac2a5c which has a more generalized mod function. Still feel very uncertain about this, as not only is it slower, but the unsigned mod function will produce unexpected results if called with a negative divisor (not that this would happen in foreseeable code), so it still is code which could produce unwelcome surprises. Would be very grateful for thoughts!

**Comment by upegelow** [comment]
I'd go for 600 and add a comment why we have that offset. This will make clear that there are no magics involved in case some other developer requires an adjustment at some later point in time.

**Comment by dtorop** [comment]
Offset at 600, as per @pedrocr's original plan, with asserts and comments added. Also made allhex[] lookup a function rather than macro. Thank you for the thoughts!

**Comment by upegelow** [comment]
I stumbled over a minor syntax issue in function hexmap(). At least for me gcc complaints about a type mismatch of the third argument. Defining the function as 

`static inline const short *const hexmap(const int row, const int col,short (*const allhex)[3][8])`

fixes the problem.

**Comment by dtorop** [comment]
@upegelow: The allhex declaration should be fixed now... Not sure why my gcc (Debian's 5.3.1-8) doesn't mind...

**Comment by upegelow** [comment]
Looks good now. I'll merge.

**Pull request merged**
