### PR TITLE
po/lens clean up - use generic auto-init

### PR DESCRIPTION
**Pull request by TurboGit**
lens: Remove old code to be able to copy/paste lens correction.
    
This was a hack in this specific module to be able to copy/paste the
module and yet let it auto-initialized based on the picture camera
and lens. It is preferable to now use the generic auto-init support
which is available for all modules.

+ support for modifying more presets fields

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
> Won't this break existing presets and styles utilizing lens-specific auto-init?

Was also my concern ... twisting head

**Comment by TurboGit** [comment]
> Won't this break existing presets and styles utilizing lens-specific auto-init?

Yes, but updating a preset or recreating a style is certainly the price to pay for a removal of a hack in a specific module I would say. We'll need to document that in the release notes if this PR works as expected after more testing.

**Comment by parafin** [comment]
Maybe something more visible? How exactly those old presets will apply? With some wrong settings (different camera and lens)? Then it's quite bad. Maybe display a BIG FAT WARNING inside lens iop if modified flag is set to 0? Though it will probably be displayed than on a lot of old histories with correct settings...

**Comment by jenshannoschwalm** [comment]
> With some wrong settings (different camera and lens)?

There are two places in lens code where we currently test for "never changed gui", at both places we ensure default parameters instead of data given otherwise.

That's not looking like an easy one.

**Comment by TurboGit** [comment]
New version which is updating lens version and doing the right things in `legacy_params()` to use an auto-init module when old modified was 0.

**Comment by jenshannoschwalm** [comment]
latest commit looks good for me. It seems we have to keep the modified in the struct for later?

Just may i ask - if you are bumping version here, could we agree you include
```
  float cor_scale;    // $DEFAULT: 1 $MIN: 0.9 $MAX: 1.1 $DESCRIPTION: "scale fine-tune"
```

in the params struct so we don't have to bump again in a day or two? :-)

**Comment by TurboGit** [comment]
@jenshannoschwalm : This is done in this new version. I have also added support for style legacy params with old auto-init hack in lens. So now the old hack is removed, we do migrate the presets & styles to the new auto-init support. There is no more need for a warning or whatever.

Note, this is built on top of #13492.

**Comment by jenshannoschwalm** [comment]
That's HUGE

**Pull request merged**
