### PR TITLE
Fix: correct name for Canon EOS M50 Mark II in adobe_coeff.c

### PR DESCRIPTION
**Pull request by cytrinox**

### CODE REVIEW

**Comment by cytrinox** [comment]
@TurboGit required for #10332 as the mapping will use the correct name.

**Comment by kmilos** [comment]
AFAICT, "Canon EOS M50m2" was already correct?

**Comment by MStraeten** [comment]
Canons DPP reports "Canon EOS M50m2"

**Comment by kmilos** [comment]
OTOH, after Adobe DNG Converter "Canon EOS M50 Mark II" is indeed present in the DNG `UniqueCameraModel` tag (the regular Exif `Model` tag is still "Canon EOS M50m2")... Hmmm, what to do, what to do... ;)

**Comment by cytrinox** [comment]
@kmilos Depends... :smile: 
The offical name is **EOS M50 Mark II** and something like M50m2 is nothing that will fit in typical Canon naming scheme. I know this is the hardcoded model name in CR3 internals but I assume this was just as mistake by Canon devs. The M6 Mark II is not named M6m2 in internals. There is only a single definition for the D65 matrix in adobe_coeff.c per camera model and this is usually the cleaned-up model name. So any name reported by raw file, different brand names etc. are mapped to clean_model and then the lookup in adobe_coeff.c is done. So I would go with EOS M50 Mark II, but there is no 100% solution or answer, until a Canon dev confirms this was a mistake :wink:

**Comment by kmilos** [comment]
`Exif.Photo.Model` seems far from "Canon internal" ;) But it is indeed an outlier... Agreed, since the cleanup is fully under our control, it's a toss-up...

**Review by TurboGit — APPROVED** [review]
Thanks !

**Pull request merged**
