### PR TITLE
Map locations: add polygon shape (kind of)

### PR DESCRIPTION
**Pull request by phweyland**
In "find location" module OpenStreetMap is able to provide country and city shapes (in "map settings", set "max polygon points" large enough to receive these data, 150.000 was enough for my tests).

When such a shape is displayed on the map (the red one), a new shape symbol is available in "locations" module (polygon).
Adding a new location with this polygon shape, associates the polygon to the new location.
Such a polygon of location is not modifiable... but records all images inside the polygon.

These locations are also available in collect module (under geotagging).

image

### CODE REVIEW

**Comment by gadolf66** [comment]
Thanks for working on this.
I'm currently building this release and intend to test it later.
Meanwhile, I'm puzzled by the image you've posted above, because there are Brazil states where you have images (Rio de Janeiro, São Paulo, Rio Grande do Sul) that don't show counts on the map. Am I missing something?

**Comment by phweyland** [comment]
> I'm puzzled by the image you've posted above, because there are Brazil states where you have images (Rio de Janeiro, São Paulo, Rio Grande do Sul) that don't show counts on the map. Am I missing something?

Yes... That's an effect of the images clustering. By principle it doesn't give an exact position... But zooming in the details come up and positions are more accurate.

**Comment by gadolf66** [comment]
Is this git command right?

git clone https://github.com/phweyland/darktable.git

After that git clone command, darktable shows the following version information

2.5.0+9778~g1231c9713

The thing is that I'm not able to find the "max polygon points" setting:
image

**Comment by gadolf66** [comment]
I'm having issues when I try to edit _max polygon points_ in map settings.
Immediately after changing any value, darktable seems to enter a loop.
At first, I used the backspace key to delete the default value digit by digit, but as soon as I deleted the first digit, darktable seemed to have entered some kind of looping.
I also tried selecting the whole field value and typing the new one, but as soon as I entered the number "1" it froze in that loop.
image

Ubuntu 20.04
no opencl

**Comment by phweyland** [comment]
This message seems to be normal if you launch the darktable with -d all option.
Now the preference parameters are not related to that and is only used when you search for a location in find location...
I cannot reproduce this issue:
image

What about the other map settings  ? numerical ? boolean ? 
Can you change this value in darktablerc (it's named there "plugins/map/max_outline_nodes")  and see it in map settings ?

**Comment by phweyland** [comment]
I've removed an action on this preference update which is useless. That may help. But even useless it should not hurt.
Thanks for having tried :)

**Comment by gadolf66** [comment]
> EDIT: did you start from an existing db or a clean empty one ?

From an existing one.
Now I started from scratch, and still have trouble editing the field.
Delete and backspace work normally, but all other keys don't.
But I was able to put a new value by right-clicking and choosing paste - after deleting all digits inside. But after pasting, there's a trailing zero that's inserted and that I have to delete.
EDIT: Now I tried changing again the field like this:
1 - Clicked on the field -> cursor shows up, blinking;
2 - Deleted content using backspace -> ok
3 - Typed "l" -> darktable got back to lightroom
Shouldn't shortcuts be disabled when editing a field? Now I suspect that the numbers I try to put down are being understood as image ratings, thus

**Comment by phweyland** [comment]
> Shouldn't shortcuts be disabled when editing a field? Now I suspect that the numbers I try to put down are being understood as image ratings, which would explain why the field isn't properly filled with what I type.

You are right. This is related to shortcut. I've never got this issue with this type of preference... There is a beginning for everthing. 
My last change will not solve this.

**Comment by phweyland** [comment]
I've just rebased on current master and got the same issue as yourself.
There is an enhancement/fix/regression somewhere ...

**Comment by phweyland** [comment]
I've tried to bisect but I've made an error and did not go anywhere.
I can just say that 1fde6536912a543722805f062cb1b1398e0e0ff6 still works.

I've pushed a fix to grab focus on the widget  and it should work for you @gadolf66. Sorry for that I should have tested on the rebased version before.

@TurboGit but this fix is not completely good. Every time I leave the map view I get this error:
`(darktable:190023): Gtk-CRITICAL **: 22:26:15.909: _gtk_accel_group_attach: assertion 'g_slist_find (accel_group->priv->acceleratables, object) == NULL' failed`
only once despite there are several dt_gui_preferences_int() in that view.

I think I should put a (some) "dt_gui_key_accel_block_on_focus_disconnect()" somewhere. But I'm unsure where I have to put it. Should I create a kind of "dt_gui_preferences_int_disconnect()" and call them on the view cleanup ?
Do you see a better way ?

**Comment by gadolf66** [comment]
> Sorry for that I should have tested on the rebased version before.

I may have built the binary in an inappropriate way for you.
I did it this way:

```
git clone https://github.com/phweyland/darktable.git
cd darktable/
git checkout map-polygon
git submodule init
git submodule update
./build.sh --prefix /opt/darktable --build-type Release
sudo cmake --build "/home/gustavo/darktable/build" --target install -- -j4

```
Should I have done it in another way? If so, I'm sorry, but I have this recipe for buiding darktable lying around that I blindly follow, since I'm not well versed on git.

**Comment by gadolf66** [comment]
I rebuilt the binary and now everything seems to work well, thanks.
I will do some more tests.
Btw, this is great!

**Comment by gadolf66** [comment]
For a give set of existent pictures, I was able to nest polygons, so I could easily get something like Country -> State -> City, National Park, etc.
As for dynamically updating things, I have an issue.
I took a geo-tagged picture with my cell phone and added it to the folder I was working on before.
The pinned count on the image was updated but the others didn't:

image

This should be showing the following counts:
Brasil - 9
Estado do Rio de Janeiro - 9
Cidade do Rio de Janeiro - 2

Am I missing something?

**Comment by phweyland** [comment]
> I took a geo-tagged picture with my cell phone just now and added it to the folder I was working on before.
> The pinned count on the image was updated but the others weren't:

That's a case I've not tested. For sure something is missing. I'll check that.

**Comment by phweyland** [comment]
> Should I have done it in another way?

Your way is correct but rely on my repository. You may prefer do the equivalent from darktable.org.
On my local git I do this (for PR #7201 tag-fix) (assuming master is rebased :)):

$ git fetch https://github.com/darktable-org/darktable pull/7201/head:tag-fix
$ git checkout master
$ git merge head:tag-fix2
... some test
$ git reset --hard upstream/master

**Comment by gadolf66** [comment]
> You may prefer to do the equivalent from darktable.org.

Sorry about my ignorance on git, but could you write down all steps to get a new build when you update the code?

**Comment by phweyland** [comment]
> > You may prefer to do the equivalent from darktable.org.
> 
> Sorry about my ignorance on git, but could you write down all steps to get a new build when you update the code?

if you build regularly from master you do something like:
```
$ git checkout master
$ git fetch upstream
$ git rebase upstream/master
$ git submodule init
$ git submodule update
$ ./build.sh --prefix /opt/darktable --build-type Release
$ sudo cmake --build "/home/gustavo/darktable/build" --target install -- -j4 (I've copied you text here)
```

In case you want to test a PR:
```
$ git fetch upstream
$ git rebase upstream/master
$ git fetch https://github.com/darktable-org/darktable pull/7201/head:tag-fix
$ git checkout master
$ git merge head:tag-fix2
$ git submodule init
$ git submodule update
$ ./build.sh --prefix /opt/darktable --build-type Release
$ sudo cmake --build "/home/gustavo/darktable/build" --target install -- -j4 (I've copied you text here)
#... your tests
$ git reset --hard upstream/master
#... your regular build ...
```

**Comment by phweyland** [comment]
> @TurboGit [] 
> I think I should put a (some) "dt_gui_key_accel_block_on_focus_disconnect()" somewhere. But I'm unsure where I have to put it. Should I create a kind of "dt_gui_preferences_int_disconnect()" and call them on the view cleanup ?

I did this. But map_setting.c/gui_cleanup() is not called when map view is left (only on dt exit). I still get the above error message. :(

**Comment by phweyland** [comment]
> > I took a geo-tagged picture with my cell phone just now and added it to the folder I was working on before.
> > The pinned count on the image was updated but the others weren't:
> 
> That's a case I've not tested. For sure something is missing. I'll check that.

Good catch.
Should be fixed now.

**Comment by TurboGit** [comment]
I have crash when doing:
1. go to map view
2. select polygon
3. click on new localisation
4. enter a name
5. hit enter => CRASH

```
#0  0x00007ffff76e4940 in g_list_length ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff7c89fc4 in dt_map_location_convert_polygons
    (polygons=0x6469776f72, bbox=bbox@entry=0x7fffffffc240, nb_pts=nb_pts@entry=0x7fffffffc290)
    at /home/obry/dev/builds/darktable/build/src/src/common/map_locations.c:599
#2  0x00007fffbc0f6e8e in _view_map_add_location
    (view=0x555557bc91e0, g=<optimized out>, locid=<optimized out>)
    at /home/obry/dev/builds/darktable/build/src/src/views/map.c:2389
#3  0x00007fff79411d73 in _name_editing_done
    (editable=<optimized out>, self=0x55555935c500)
    at /home/obry/dev/builds/darktable/build/src/src/libs/map_locations.c:551
```

**Comment by phweyland** [comment]
> I have not use search location nor changed the number of polygon yet the polygon shape was present and in the backtrace above I suppose the polygon pointer was null.

Yes, ... regression of mine. Good catch.
Thanks for testing.

**Comment by phweyland** [comment]
If the PR gets merged ...
I'm trying to find a way to transform a track into a polygon (f(distance)). When this is done we should be able to create locations which represent tracks using the same code as proposed in that PR.
This feature will allow the user to create collections of images associated to tracks ...

**Comment by gadolf66** [comment]
I did some more tests:
**Issues?**
1 - In _geotagging_ section, I added a gpx file, then ticked all tracks and also _preview images_.  The tracks show up in cyan (great!), and thumbnails of images spread along the tracks. When I hover the mouse over the thumbnails and scroll the mouse wheel, the images don't change, only the zoom. If I change _thumbnail display_ in _map settings_ from _count_ to _thumbnails_, then it works. IMHO, maybe there shouldn't be an option in _geotagging_ to _preview images_, because you already have that option in _map settings_.

Passed:
1 - Select gpx file with multiple tracks -> file opens and tracks are shown
2 - Apply offset - Despite darktable having already geotagged all images during import because I had previously saved the gpx file alongside the raw files, I applied an offset of 2 seconds. Offset was applied, but I wan unable to see if there was any shift in location (probably not due to the small offset ammount)

**Comment by phweyland** [comment]
>  can't show four lines of locations I've previously added.

Just to be sure. Are you aware you can change the height of the list using ctrl-scroll ?



> When I hover the mouse over the thumbnails and scroll the mouse wheel, the images don't change, only the zoom. If I change _thumbnail display_ in _map settings_ from _count_ to _thumbnails_, then it works

...
Thumbnails (preview) for geotagging module, in red, (images which have not yet geotags) are only shown if "preview images" is checked.
In map settings, "thumbnail display" affects only the already geottagged images on the map.
I haven't not reported the count/thumbnail option for geottaging module (preview, the red ones) because I haven't seen the benefit. However I'm missing the scrolling over the preview thumbnails (to see hidden ones if necessary).
Does that answer your concern or I still miss something ?

And again, thank you for these careful tests.

**Comment by gadolf66** [comment]
> Are you aware you can change the height of the list using ctrl-scroll ?

Ooops, nope, I'm not. I missed that somewhere. Checked.

> Thumbnails (preview) for geotagging module, in red, (images which have not yet geotags) are only shown if "preview images" is checked.
Ah, now I understand. I didn't put the proper weight on the word preview, in this case, images that are potentailly about to be tagged. Cool!


> However I'm missing the scrolling over the preview thumbnails (to see hidden ones if necessary)

Fully agreed, that's when I started to think about this preview functionality.

That's all, thanks!

**Comment by phweyland** [comment]
>  images that are potentially about to be tagged.

When you change the date/time (scrolling over seconds or minutes) you can see the red previews moving along the track. That's a visual way to adjust date/time (if you have some landmarks on you track).

**Comment by TurboGit** [comment]
One more issue, on Google Satelite the polygon is visible but on Google Map, or OpenStreetMap it is not distinguishable (thin yellow line). Maybe use different colors depending on the map ?

**Comment by phweyland** [comment]
>  on Google Satelite the polygon is visible but on Google Map, or OpenStreetMap it is not distinguishable (thin yellow line). Maybe use different colors depending on the map ?

Good idea. I'll try to do something for that.

**Review by TurboGit — APPROVED** [review]
Works for me ! Merging now to ensure a bit of field testing for 3.6. Thanks for the nice addition.

**Comment by supertobi** [comment]
This looks like an interesting borderline for testings:
https://www.google.de/maps/@51.4252611,4.9162169,13z

**Comment by phweyland** [comment]
> This looks like an interesting borderline for testings:
> https://www.google.de/maps/@51.4252611,4.9162169,13z

Interesting indeed ! did you test ?
However, don't expect too much. Multi polygons and holes are not supported. 
So I would expect to get only the largest contour ...

**Comment by supertobi** [comment]
> Interesting indeed ! did you test ?
No, I haven't. I just remembered this border an thought it would be a niche test.

**Pull request merged**
