### PR TITLE
filmic defaults

### PR DESCRIPTION
**Pull request by TurboGit**
just adding a commit to @flannelhead PR #12882.

- Fix legacy params setup.
- New default to reconstruction threshold as discussed.

### CODE REVIEW

**Comment by jorismak** [comment]
I don't know of another place to ask this.

Why the move by default to 'power norm' ? Is this discussed somewhere?

**Comment by TurboGit** [comment]
Yes, follow https://github.com/darktable-org/darktable/pull/12882 linked in this message and then https://github.com/darktable-org/darktable/issues/12847 (linked in the linked message :).

**Comment by Nilvus** [comment]
@TurboGit: I don't understand why you put treshold to -2. I hope it's just an error. In most images, it's to important and make hard transitions and even touch part not wanted. This setting should not be inferior to 0. Probably 0.25IL as suggested by @flannelhead or even 2IL for safety and smooth transitions by default.

**Comment by TurboGit** [comment]
-2EV is the threshold, the 0.25 was for the transition as was not changed.

**Comment by Nilvus** [comment]
Oups, for 0.25 setting, I indeed make confusion between lines but my comment remains about treshold. That doesn't change my comment. -2EV is really too much. This is a serious issue by default. On most images, If I have those default settings, some images are just quite washed. Just an example with -2EV setting:

image

With treshold to 0EV (or any setting between 0 to 3EV on that image, I then have:

image

And regarding comments on FR from @flannelhead and related PR here, except you, I see nobody asking for such default. This is definitely a bad move. Need change. If needed, I could create an issue. I would definitely not set this setting by default lower than 0.

**Comment by TurboGit** [comment]
Is your image with default Filmic? I have never seen so much noise added and I have almost always used the threshold below -2EV!

**Comment by Nilvus** [comment]
It's not with default settings (only default highlight reconstruction) but if I start with all tabs with default filmic, I could quickly have such noise by moving a little (1EV) white slider in first tab to the left. I'm not the only one regarding comments here and on @flannelhead PR to think that -2EV is not a good default setting. I really think this should be changed by default. -2EV include too much zones and is too hard. See mask image on that image (with all on default filmic settings):

image

I have no highlights on that images and mask, with -2EV in treshold, confirm there's too much areas included. And I could reproduce with a lot of my images.

I suggest 0EV as default.

**Comment by jorismak** [comment]
On pixls I saw flannelhead saying the threshold 'right around 0ev' (slightly below / slightly above depending on the image) is often what he picks. But that might be out of context or outdated already, of course.

I never had to go below something like -0.15ev. When you set it to -2ev you dive into your normal data right? The highlights sit around 0ev at that point in the pipe, so setting the threshold to -2ev basically means 'reconstruct everything between -2ev and 0ev' which seems disastrous to me?

Maybe the use case is different, but reconstruct-in-filmic is used these days I think only to smoothen transition issues, and those happen around the extreme highlight area at 0ev.

The only times I used values that low, were when the highlight-reconstruction module was unusable on an image. So I had to use filmic-reconstruct to get rid of magenta. But those days are over now we have a better algorithm then 'reconstruct color' and we actually have a working algorithm that works on demosaiced data (inpaint opposed works on sraw / linear-rgb now).

**Comment by SoupyGit** [comment]
I agree with @nilvus and @jorismak 
Didn't say anything previously as I'd already suggested 0ev threshold in the other thread and assumed it had been considered.

With the checkbox, default transition does not need to be different from previous default (as in 4.0.1).

**Comment by Nilvus** [comment]
@TurboGit: I see the commit pushed to put treshold to 0. Thanks.

**Pull request merged**
