### PR TITLE
CSS rework from new overlays modes and some cleaning

### LINKED ISSUE #4748: lighttable: can't change border around image in CSS
Pull request #4660 introduced the ability to set the thumbnail margins by entering the margin percentage using a pixel value in css as follows:

```
#thumb_image
{
  border: none;
  margin : 4px; /* not real pixels, but percentage of the thumb size */
}
```
However, when I modify that 4px to 20px in darktable.css it has no effect on the lighttable.

Clean build of darktable master on ArchLinux (7dc9f8f)

### PR DESCRIPTION
**Pull request by Nilvus**
CSS lighttable rework since new overlays modes and some more:
- Improve star icon popover menu (hover effect, padding)
- Cleaning some unuseful lines and making CSS more readable by adding/improve some comments
- Bottom metadata text on thumbnails image is now normal size instead of bold (more consistent I think to the lighter darktable 3 UI)
- Remove gradient part (even if commented). Just tested with changes I made, stars are better without gradient, even on brighter images as gradient only appear under images. @AlicVB and @aurelienpierre: is it ok for you with this PR?
- Merging and renaming some things to simplify and help having a more consistent UI by tweaking just one things for similar ones (like all bottom infos and extension name or altered, group icons on thumbnails).

If someone use local copies, could he test if rendering is ok on all themes? And post here screenshot if it's not ok or suggest CSS tweak (lines 1646 to 1667)

@TurboGit: It's actually a WIP as I would like to have some feedback about that work and if all overlays modes are readable and consistent on all modes, and especially from @elstoc, @AlicVB and @aurelienpierre.. I've made some tests but that's just me and my environment.

And more on that, I'm waiting for @AlicVB feedback on that and  #4748 discussion as I removed the following lines but seems to be a bug:

```
.dt_thumbnails_2 #thumb_image
{
  margin : 2px;
}
```

Should fix #4748

### CODE REVIEW

**Comment by AlicVB** [comment]
@Nilvus : about the .dt_thumbnails_2 class : that was a bug (a stupid forgot). I have fixed that here, I'll do a PR in a couple of minutes...

**Comment by Nilvus** [comment]
> @Nilvus : about the .dt_thumbnails_2 class : that was a bug (a stupid forgot). I have fixed that here, I'll do a PR in a couple of minutes...

Ok, ping me when pushed

**Comment by AlicVB** [comment]
@Nilvus : ping :) see PR #4763 (this fix some bugs you've found recently. Thanks for that)

**Comment by AlicVB** [comment]
>     * Remove gradient part (even if commented). Just tested with changes I made, stars are better without gradient, even on brighter images as gradient only appear under images.

Just tested, and the gradient is on top of the image. overlay = normal hover. But anyway, I don't really care. I've just put that commented to simplify putting the gradient back for those who want it as it's somehow controversial.



>     * Bottom metadata text on thumbnails image is now normal size instead of bold (more consistent I think to the lighter darktable 3 UI)

agree, aesthetically it's better like that imho

Overall, it's a very good job. Thanks !

**Comment by Nilvus** [comment]
> @Nilvus : ping :) see PR #4763 (this fix some bugs you've found recently. Thanks for that)

Ok, .dt_thumbnails now ok. Just update the CSS.

**Comment by TurboGit** [comment]
Just tested for me:
- grey the extended data are readable
- dark difficult to read (maybe with bold font) the extended data, not readable on mouse over
- darker, extended readable but extended on mouse over hard to read (as for dark)

For dark and darker the picture format with mouse over is really readable, I think the text for extended data should use the same color (darker).

**Comment by TurboGit** [comment]
I have tested this which makes extended data more readable on my side:

```
diff --git a/data/themes/darktable-elegant-dark.css b/data/themes/darktable-elegant-dark.css
index b689a9d09..e1e39fbca 100644
--- a/data/themes/darktable-elegant-dark.css
+++ b/data/themes/darktable-elegant-dark.css
@@ -87,7 +87,7 @@
 /* Lighttable and film-strip */
 @define-color thumbnail_font_color @grey_30;
 @define-color thumbnail_bg_color @grey_55;
-@define-color thumbnail_infos_color @grey_75;
+@define-color thumbnail_infos_color @grey_35;
 @define-color thumbnail_selected_bg_color @grey_85;
 @define-color thumbnail_hover_bg_color @grey_95;
 @define-color thumbnail_hover_fg_color @grey_75;
diff --git a/data/themes/darktable.css b/data/themes/darktable.css
index 48257a26f..ba7582c83 100644
--- a/data/themes/darktable.css
+++ b/data/themes/darktable.css
@@ -1561,6 +1561,7 @@ radiobutton
 .dt_overlays_hover_extended #thumb_main:hover #thumb_bottom_label,
 .dt_overlays_always_extended #thumb_bottom_label
 {
+  font-weight: bold;
   color: @thumbnail_infos_color;
 }

```

**Comment by Nilvus** [comment]
@TurboGit: I don't have what you describe on my side...  except indeed selected (but not hover) that could be improved.
Anyway, bold is not an option, as I write on my thread post here.

Could you post some screenshots (partial ones) about the three lines you write to see what you have.

**Comment by TurboGit** [comment]
Sure, here it is:

- grey, to me all readable:
grey

- dark, selected (left) and standard (right) not really readable, especially the standard
dark

- darker, like dark maybe a bit more  readable, but selected and standard have not much contrast:
darker

**Comment by Nilvus** [comment]
> For dark and darker the picture format with mouse over is really readable, I think the text for extended data should use the same color (darker).

They already are on same colors. Extension name and bottom metadata use both thumbnail_infos_color. Extension name is bold not metadata (but metadata are too big and ugly in bold).

**Comment by Nilvus** [comment]
> Sure, here it is:
> 
>     * grey, to me all readable:
>       grey
> 
>     * dark, selected (left) and standard (right) not really readable, especially the standard
>       dark
> 
>     * darker, like dark maybe a bit more  readable, but selected and standard have not much contrast:
>       darker

Ok, thanks. Seems something I have done and missed when updating theme here for dark and darker ones... It's indeed not what I've done yesterday for dark and darker modes... Will fix that.

**Comment by Nilvus** [comment]
@TurboGit: this last commit should fix issues you report. I also make themes more consistent between them. Should be good now. @AlicVB: I change some things since you approved this PR. If you want to check before merging (as you want!).

No more WIP for me.

**Comment by TurboGit** [comment]
Very good to me now ! I'll wait a bit for @AlicVB to test.

**Comment by TurboGit** [comment]
Merging then !

**Pull request merged**
