### PR TITLE
po/fix box filter

### PR DESCRIPTION
**Pull request by TurboGit**

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
Thanks!

**Comment by TurboGit** [comment]
All 81 integration tests are passing.

**Comment by ralfbrown** [comment]
Boy is my face red....

**Comment by TurboGit** [comment]
@ralfbrown : no problem, we are all doing that, the worst thing is that I have been looking for some error in code ordering or whatever, I have seen those definitions many time and it didn't get my attention...

**Pull request merged**
