### PR TITLE
Colorequal 3

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
1. likely it's better to disable guiding by default for now ...
2. do downscaling by fixed ratios and thus enforce bluuring via the gaussian part

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
BTW - i know now the reason for some hue shift close to black areas. In `dt_XYZ_to_xyY` we **must** use a valid white point, in UCS it's ~D50, in other parts it's D65. PR with some refactoring pending.

**Comment by TurboGit** [comment]
So maybe we must wait before merging this as if I understand correctly the coming PR will fix issues with the guided filter.

**Comment by jenshannoschwalm** [comment]
I think this pr is good as is so a go from my side.

I think the fallback conversion to D65 xy is not correct, D50 is certainly much better.

I am trying to find out how to check for the correct white point inside the pixel pipe. Does it really change or is it at D50 all the time?

**Comment by jenshannoschwalm** [comment]
@TurboGit there was another - critical for this module - bug while calculating the lut.

Seems good now ...

**Comment by TurboGit** [comment]
> Seems good now ...

You've not pushed anything new... :)

**Comment by jenshannoschwalm** [comment]
Uups, pushed it my branch master ... will do asap.

**Comment by jenshannoschwalm** [comment]
@TurboGit that's - and it's worth - it :-)

**Comment by TurboGit** [comment]
Now it works very well with the guided filter activated on my side. So probably better to keep it on by default, no? Did I missed something?

**Comment by todd-prior** [comment]
Its a bit of a separate issue but can you play with desaturation and see what you think.... I feel like red and green behave as you might expect but for blue in a few of the color charts and test images seems to not desaturate as strongly and yet lavendar does work on blue more like the red and green sliders do on their respective hues... maybe its just the images I chose??

**Comment by jenshannoschwalm** [comment]
@TurboGit force-pushed without disabling guiding by default.

**Review by TurboGit — APPROVED** [review]
Thanks! Really great job.

**Comment by jenshannoschwalm** [comment]
BTW: we have a very large range for "effect radius", would you comment on the required range in your experience? I think that restricting it to 50 or even 20 would be enough. Asking that because of stability/performance issues with tiling ...

**Comment by todd-prior** [comment]
It does seem to have a pretty big impact... I was just looking at the color patches on a colorchecker and playing with it as a rough guage of the effect and slider actions....

**Comment by jenshannoschwalm** [comment]
> It does seem to have a pretty big impact.

It does for sure. The question for me is: "Do we need such big radii"?

**Comment by aurelienpierre** [comment]
The code you just merged was nowhere production-ready, and HSB is not HSL, which you would know if you did more reading and less  copy-pasting stuff you don't understand, but heh… since this project is now all about doing massive amounts of shit ASAP, I hope you had your saturday fun.

Just warn users it's a big turd before getting them all excited about new stuff.

**Pull request merged**
