### PR TITLE
po/fix wb modern old

### LINKED ISSUE #7145: white balance set to camera reference in old edits
**Describe the bug**
Set auto apply chromatic adaptation defaults to modern then open a film roll of old edits (display referred from 2017).  Open an image in darkroom and check the white balance and notice it's now set to camera reference.  The color calibration module is not applied.  If you set auto apply chromatic adaptation defaults back to legacy and open another film roll of old edits the white balance is still set to the original edit.  

**To Reproduce**

1. Go to settings and set auto apply chromatic adaptation defaults to modern
2. Go to collect images and open an old film roll 
3. Open an image and check the white balance
4. See that it's set to camera reference  It should have been as shot or user defined.
-->

**Expected behavior**
Old edits should retain the white balance settings they were processed with.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0+1925~g5eba7b2d2
 - OS: Ubuntu 18.04
 - OpenCL activated 
 - Nvidia 970m 455.38

### PR DESCRIPTION
**Pull request by TurboGit**
Fix handling of white-balance in old edits.
    
    Old edits had no white-balance written when the params where all defaults.
    For those edits we need to recover the legacy white-balance default (pre
    modern chromatic adaptation).
    
    Fixes #7145.

### CODE REVIEW

**Comment by elstoc** [comment]
@TurboGit as I mentioned in the initial bug you need to find a way to actually detect old edits. @wpferguson has suggested a way that might work. Here is a scenario in which this fix fails:

Open a fresh edit. Switch the white balance module on and off. Compress the stack. Now white balance is at the top of the stack. Choose the module below it in the history and compress the stack again. White balance is re-added to the stack automatically but incorrectly set to "as shot".

The same happens if you choose any module above "original" but below "white balance" in the stack.

**Comment by wpferguson** [comment]
The edits look fine.  A lot of the images generate output such as 

```
[_dev_auto_apply_presets] missing mandatory module rawprepare
[_dev_auto_apply_presets] missing mandatory module temperature
[_dev_auto_apply_presets] missing mandatory module highlights
[_dev_auto_apply_presets] missing mandatory module demosaic
[_dev_auto_apply_presets] missing mandatory module colorin
[_dev_auto_apply_presets] missing mandatory module colorout
[_dev_auto_apply_presets] missing mandatory module gamma
[_ioppr_check_rules] found rule flip clipping module clipping (16) is before flip (20) image 3935 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule flip clipping module flip (20) is after clipping (16) image 3935 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule flip clipping module clipping (16) is before flip (20) image 0 (dt_dev_pop_history_items_ext begin)
[_ioppr_check_rules] found rule flip clipping module flip (20) is after clipping (16) image 0 (dt_dev_pop_history_items_ext begin)
[_ioppr_check_rules] found rule flip clipping module clipping (16) is before flip (20) image 0 (dt_dev_pop_history_items_ext end)
[_ioppr_check_rules] found rule flip clipping module flip (20) is after clipping (16) image 0 (dt_dev_pop_history_items_ext end)
[_ioppr_check_rules] found rule flip clipping module clipping (16) is before flip (20) image 0 (dt_dev_modules_update_multishow)
[_ioppr_check_rules] found rule flip clipping module flip (20) is after clipping (16) image 0 (dt_dev_modules_update_multishow)

```

but it doesn't appear to hurt anything.

**Comment by TurboGit** [comment]
> @TurboGit as I mentioned in the initial bug you need to find a way to actually detect old edits. @wpferguson has suggested a way that might work. Here is a scenario in which this fix fails:

Yes, I'll look at this. I wanted to be sure that the current fix at least works in standard scenario.

**Comment by elstoc** [comment]
Also, am I right in thinking that this is a darkroom-only fix - the only way to fix them is to identify the issue and open them in the darkroom manually? If that's the case, if I have a collection of 100 images and 10 of them exhibit the issue, the lighttable previews will be wrong. If I choose to export them all in bulk, the exports will also be wrong.

**Comment by leclercj** [comment]
@elstoc In my case vast majority of lighttable previews remain correct. Lighttable previews are broken in the following scenarios:
1) at time I open a picture in darkroom and switch back to lighttable.
2) If I select an unusual zoom factor such as the lighttable preview is not available in the cache and is re-generated
3) I clone a picture in lighttable
At the end, when the bug is fixed, I'm afraid we will have to launch a large lighttable preview cache refresh to clean this up

**Comment by elstoc** [comment]
Agreed - this problem occurs on all affected images that have had the lighttable preview refreshed since the installation of darktable 3.x - which for me is all of them, since they're old edits and so are no longer in the cache. But unless we can fix it without the user having to go into the darkroom, it will also affect new exports of old images.

**Comment by TurboGit** [comment]
> I wonder if the fix might work better in the reload_defaults function to handle these scenarios?

Sounds like it is too late in reload_defaults() The condition for this trick is that NO white-balance module should be present in the history. In old edits, if one has changed the wb settings there is one instance and we don't want to reset to default legacy params.

**Comment by TurboGit** [comment]
@leclercj : You can test this PR which should fix the issue. Let me know.

**Comment by elstoc** [comment]
> The condition for this trick is that NO white-balance module should be present in the history.

That's one way to solve this. The other way is to detect that it's an old history stack. If you can do this reliably, then you _can_ fix it in reload_defaults, though you'd probably have to do this in addition to the fix you've already defined. This _might_ solve the issue with previews and exports where the image hasn't been reopened in the darkroom.

This may not be _fully_ fixable though, so I'm just throwing out ideas at the moment, and I'm not sure whether my assumption (that the fix requires the user to go into the darkroom) is true or not.

**Comment by TurboGit** [comment]
> That's one way to solve this. The other way is to detect that it's an old history stack. If you can do this reliably, then you _can_ fix it in reload_defaults,

Maybe I don't understand you, but this is not ok. We need old history AND that there is no white-balance in history. We may have one if the old edit has changed some settings in white-balance. And in this later case we don't want to reset to default params in reload_defaults(). So I don't see a way to solve this....

**Comment by elstoc** [comment]
> We may have one if the old edit has changed some settings in white-balance

So I'm saying keep your fix in place to resolve the issue (add the module back in with the correct params) when the user loads the image in the darkroom. But if they don't re-enter the darkroom, presumably the pixelpipe processing still has to already handle this (missing WB module) scenario when it's doing an export or regenerating previews. Right now I'm assuming that this pixelpipe processing uses reload_defaults, which incorrectly loads the D65 setting. It must be adding a WB module in somehow or the previews and exports would look very obviously wrong.

In this case, the latest value of the blendop_version in the history will be 7 or lower, so reload_defaults can detect this and use legacy params. Once they've opened in image in the darkroom the latest value of blendop_version will be higher than 7 so this code can be ignored (and revert to using your fix in this PR).

I've made a lot of assumptions here, and I'm not even sure how to replicate all of these things in my development version (I'm seeing this in my working copy of 3.4.1 only at the moment and don't want to risk disturbing my old work).

**Comment by TurboGit** [comment]
@elstoc : A new version with a patch on reload_defaults(). I'm not fond of checking the database for the legacy version in an iop module but it seems to do the trick. A better idea is welcome and some testing really needed.

@wpferguson @leclercj : do not hesitate to test this PR on your db (backup before) and report any issue. TIA.

**Comment by elstoc** [comment]
> I'm not fond of checking the database for the legacy version in an iop module but it seems to do the trick

I completely agree but we've made some major changes in this area and TBH I'm amazed we've managed to find a solution at all.

I've tested and it looks good to me. I repeated the following tests, in master and then in a build containing this PR

1. Found a set of images exhibiting the problem from my 3.4.1 installation  (pre-3.0 edits where there was no reference to "temperature" in the xmp file, and where the lighttable previews obviously had the wrong white balance) and copied the images and xmps to a new folder
2. Imported the folder
3. Checked lighttable previews (D65 WB in master, "as shot" WB with PR)
4. Exported the images (D65 WB in master, "as shot" WB with this PR)
5. Loaded the images in the darkroom (D65 WB in master, "as shot" WB with this PR)

Step 5 was the first time I opened the images in the darkroom. For any of these images, if I remove (discard) the white balance module from the stack it pops back on with D65 as the default. While that's not ideal, it is possible to get into the same situation with new edits as well.

All-in-all a massive improvement over the current situation.

**Comment by wpferguson** [comment]
I'm having issues with white balance being non-responsive, but I need to sort it out.   As soon as I figure out how I got here, I'll post a better description.

**Comment by leclercj** [comment]
To test this PR, I had to start with a fresh install of dt 2.6, then imported  and edited few pictures (no change in WB).

After upgrade to dt 3/5/master and activation of "scene-refered" workflow + modern chromatic adaptation :
1) lighttable preview remains OK
2) If I export a picture, the exported jpg has wrong  white balance (issue reproduced)
3) If I open a picture in darkroom, I can observe the wrong white balance (issue reproduced)
4) If I change the zooming factor in the lighttable, some previews got wrong  white balance (issue reproduced)

My first observations  when I apply this PR:
1) lighttable previews are unchanged. What was right is still right, the wrong ones are still there (and I was not expecting something else)
2) If I open for the first time in dt 3.5 an image edited from dt 2.6, I now have correct white balance (this use case is fixed)
3) If I export a picture never edited in dt 3.5 an image edited in dt 2.6, the exported jpg still has wrong  white balance (this use case seems NOT fixed)
4) If I open again a picture that was open in dt 3.5 without this PR after an edit from dt2.6, the white balance remains wrong (this use case seems NOT fixed)
5) If I clone an image edited from dt 2.6 and never edited in dt 3.5 then open the darkroom, this clone still has wrong white balance (this use case seems NOT fixed)

**Comment by wpferguson** [comment]
Disregard my non-responsive issue.  Fixed with a restart.

**Comment by TurboGit** [comment]
@leclercj : I'm really confused now as @elstoc did test most of the things you report and got no issue.

Let's try with:
> If I export a picture, the exported jpg has wrong white balance (issue reproduced)

Which version of 2.6 was the XMP created? The 2.6.3 had all the modules written and so not bugged. For having modules with default params not written you need 2.6.2 or older.

Also when you say "wrong white balance" can you precise what you are seeing and what you expect? This may clarify the report. TIA.

**Comment by elstoc** [comment]
For some reason the import changes the blendop version to 10, so some of my results are probably the result of your first fix.

**Comment by leclercj** [comment]
@TurboGit Sorry, my text was probably not precise enough.
A first step was for me to reproduce the issue in dt 3.5/master WITHOUT your PR. See my edits in my previous message. (I'm a bit reluctant to use my production environment to test this PR, and I'm still using dt 3.4 while this PR is built for dt 3.5/master)
I used the latest 2.6.3 as of today from github, but imported my pictures with their old XMP files from 2018 and 2019 (probably some with dt older than dt 2.6.3)

**Comment by elstoc** [comment]
Yeah I don't know what to do with this now. I have an image whose XMP (in my 3.4.1 working version) says blendop v7, and doesn't contain the temperature module. However, when I examine the database I see temperature at blendop v10 in the history table, and when I load it in the darkroom and change something the XMP updates accordingly. If this is the case, then we might be back to concluding that the issue can't be fixed. I'm a little concerned that the XMP and the database could be so different.

**Comment by wpferguson** [comment]
My testing methodology:

I have a copy of 2.6.3 laying around with a script to run it pointing to .config/darktable263 and .cache/darktable263

created a directory and populated with pics

fired up 2.6.3 and imported the directory.  Opened some files to check

Modified the start script to use my current git build (without the patch), with the darktable263 config and cache dir

open images and got white balance of camera reference

Changed the start script again to use the patched git version with darktable263 config and cache

Files I had opened in current git still had with balance set to camera reference

Files that hadn't been opened showed correct white balance with user modified as the setting

Didn't try an export, but I think it would be the same as @leclercj

**Comment by elstoc** [comment]
@wpferguson might be worth looking at the database and XMP files during your testing to see if you can work out when the temperature module is getting added to the history table.

**Comment by wpferguson** [comment]
I can do that.

**Comment by wpferguson** [comment]
Here we go.....

Wiped everything out and started with 9 images.  Opened 2.6.3, left it at the defaults (except I hid the timeline because I hate it).  Imported the 9 images then exited darktable.  Check the history in the database and there are 0 entries.  The images do show up in the database.  I had thumbnails, but since I was at default I they were the embedded jpegs.  Looked at one of the xmp's and it's empty except for the filename and creator.

Started 263 and changed from embedded jpeg preview to half size raw.  Stopped and checked the DB, no change.

Started 263 and opened the first image and then space bar'ed through them.  Stopped darktable and checked the db.  Each image had a flip and basecurve entry with blendop of 8.

Started current git.  Changed preferences to scene referred and modern.  Didn't touch any of the images.  Exited and checked the database.  History for each image is still flip and basecurve with blendop of 8.

Started git master and opened the first image.  White balance went to camera reference.   Closed darktable.  The following errors were on the console:
```
[_ioppr_check_rules] found rule flip clipping module clipping (16) is before flip (20) image 1 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule flip clipping module flip (20) is after clipping (16) image 1 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule flip clipping module clipping (16) is before flip (20) image 0 (dt_dev_pop_history_items_ext begin)
[_ioppr_check_rules] found rule flip clipping module flip (20) is after clipping (16) image 0 (dt_dev_pop_history_items_ext begin)
[_ioppr_check_rules] found rule flip clipping module clipping (16) is before flip (20) image 0 (dt_dev_pop_history_items_ext end)
[_ioppr_check_rules] found rule flip clipping module flip (20) is after clipping (16) image 0 (dt_dev_pop_history_items_ext end)
[_ioppr_check_rules] found rule flip clipping module clipping (16) is before flip (20) image 0 (dt_dev_modules_update_multishow)
[_ioppr_check_rules] found rule flip clipping module flip (20) is after clipping (16) image 0 (dt_dev_modules_update_multishow)
[_ioppr_check_rules] found rule flip clipping module clipping (16) is before flip (20) image 0 (dt_dev_modules_update_multishow)
[_ioppr_check_rules] found rule flip clipping module flip (20) is after clipping (16) image 0 (dt_dev_modules_update_multishow)
[_ioppr_check_rules] found rule flip clipping module clipping (16) is before flip (20) image 0 (dt_dev_modules_update_multishow)
[_ioppr_check_rules] found rule flip clipping module flip (20) is after clipping (16) image 0 (dt_dev_modules_update_multishow)

```

Checked the database.  Images 2-9 where still the same (flip, basecurve, blendop_version 8).  Image 1, the one I opened, had rawprepare, demosaic, colorin, colorout, gamma, temperature, highlights, flip and basecurve in that order.  Blendop version was 10 for modules for image 1

Started the patched version.  Opened image 2. Temperature was user defined and the same values as it was in 2.6.3.  Closed darktable.  The following messages were on the console:
```
[_dev_auto_apply_presets] missing mandatory module rawprepare for image 2
[_dev_auto_apply_presets] missing mandatory module temperature for image 2
[_dev_auto_apply_presets] missing mandatory module highlights for image 2
[_dev_auto_apply_presets] missing mandatory module demosaic for image 2
[_dev_auto_apply_presets] missing mandatory module colorin for image 2
[_dev_auto_apply_presets] missing mandatory module colorout for image 2
[_dev_auto_apply_presets] missing mandatory module gamma for image 2
[_ioppr_check_rules] found rule flip clipping module clipping (16) is before flip (20) image 2 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule flip clipping module flip (20) is after clipping (16) image 2 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule flip clipping module clipping (16) is before flip (20) image 0 (dt_dev_pop_history_items_ext begin)
[_ioppr_check_rules] found rule flip clipping module flip (20) is after clipping (16) image 0 (dt_dev_pop_history_items_ext begin)
[_ioppr_check_rules] found rule flip clipping module clipping (16) is before flip (20) image 0 (dt_dev_pop_history_items_ext end)
[_ioppr_check_rules] found rule flip clipping module flip (20) is after clipping (16) image 0 (dt_dev_pop_history_items_ext end)
[_ioppr_check_rules] found rule flip clipping module clipping (16) is before flip (20) image 0 (dt_dev_modules_update_multishow)
[_ioppr_check_rules] found rule flip clipping module flip (20) is after clipping (16) image 0 (dt_dev_modules_update_multishow)
[_ioppr_check_rules] found rule flip clipping module clipping (16) is before flip (20) image 0 (dt_dev_modules_update_multishow)
[_ioppr_check_rules] found rule flip clipping module flip (20) is after clipping (16) image 0 (dt_dev_modules_update_multishow)

```

Checked the DB.  For image 2 the modules were rawprepare, demosaic, colorin, colorout, gamma, temperature, highlights, flip and basecurve in that order.  Blendop version was 10 for modules for image 2.  Images 3 - 9 were still at flip and basecurve with blendop version 8.

Started the patched version and imported the directory again.  Checked the DB and images 3-9 were still flip and basecurve with blendop version 8.

If you can think of any more tests, let me know.

An observation:  The image I imported with current git was still a display referred workflow with just an incorrect color balance.  It would seem to me that if there is a basecurve, and there isn't a channelmixerrgb, then the temperature should not be set to camera reference and if it is it should probably be set as shot or user defined with the camera values.

**Comment by elstoc** [comment]
@wpferguson I think perhaps the step missed there is doing something to rerun the pipe after upgrading to current master but before applying the patch. I still want to work out how my database got misaligned from my XMPs (presumably without entering the darkroom) and the only thing I can think is that my cache became invalid (or I forced a recompute by previewing at a higher resolution) and the regeneration of the preview images updated the db. Of course this could have happened in any version between 3.0 and 3.4 and we might never work it out. Either way I think the vast majority of my images are probably now unfixable without manual intervention.

> if there is a basecurve, and there isn't a channelmixerrgb, then the temperature should not be set to camera reference and if it is it should probably be set as shot or user defined with the camera values.

It's hard to distinguish this, because it could still be intentional. There's no obligation to have scene referred with modern and the user could choose to manually set up this scenario, however badly advised we might think it is. We're in this mess because of inter-module dependencies that didn't properly respect old behaviour, and we should be careful about creating more automatic behaviour like this.

**Comment by wpferguson** [comment]
@elstoc I'll run again and remove the cache between runs and see what that gets me.

**Comment by wpferguson** [comment]
Figured it out.  Imported my test dir with 2.6.3.  Imported another image to change off of the collection.  "Upgraded" to current git and set thumbnails to always use raw.  Accepted the invalidate cache.  Switched to test data collection.  Thumbnails regenerated.  Exited.  Checked history and it was updated.  Checked xmp and is was not.

**Comment by elstoc** [comment]
Thanks @wpferguson so in that case (correct me if I'm wrong), if the cache has ever been regenerated post-upgrade, we can assume that the image is already "broken" in the database (or at least indistinguishable from new edits). The only possible solution I can see is to drop the images from the database and re-import them using the first patch provided in this PR. If that's the case, I'm not sure it's worth it.

**Comment by wpferguson** [comment]
@elstoc correct.  The only images the patch will help is old edits that have not had the cache regenerated.  So the patch would help not "break" any more old edits, but the broken ones need  fixed by hand and that fix is setting the white balance back to as shot.

So, I would still recommend the patch, so we don't make things any worse than they are.

If I had a way to manipulate white balance from lua, which I don't because that crosses the boundary, then I could write a script and the user could select the images they want fixed and fix them with the click of a button (reset the white balance to as shot and regenerate the thumbnail).

**Comment by TurboGit** [comment]
>  I have an image whose XMP (in my 3.4.1 working version) says blendop v7, and doesn't contain the temperature module. However, when I examine the database I see temperature at blendop v10

Probably because while refreshing the thumbs the db gets updated but the XMP is not written on this case. AFAIR the XMP is only written when editing in darkroom.

**Comment by elstoc** [comment]
> Probably because while refreshing the thumbs the db gets updated but the XMP is not written on this case. AFAIR the XMP is only written when editing in darkroom.

Yes if you see the subsequent comments @wpferguson has proven that is indeed the case

**Comment by TurboGit** [comment]
At least we can improve this I suppose, currently I'm doing the fix in temperature module for blendop_version between 1 and 4. But looking at the comment this needs to be between 1 and 8. Right?

Second, I'm only looking at the blendop_version for the temperature module. But if there is no temperature we may check for blendop_version of any module as what we need is to detect old edits. I suppose this could fix some more issues.

What do you think ?

**Comment by TurboGit** [comment]
I confirm that we need to check for blendop_version <= 8. The commit introducing the write of all modules (f665e206c Sep 6 2019) is not in darktable 2.6.x and in this version the blendop version is 8. I should have checked that more carefully, sorry.

**Comment by elstoc** [comment]
> this needs to be between 1 and 8. Right?

Looks like it, but the chances of coming across an image where the db is still at an old blendop version and without temp are probably pretty small now. Remember that the database entries could have been replaced any time after v3.0, so we're going to have that code in there forever for a really small number of cases.

> But if there is no temperature we may check for blendop_version of any module as what we need is to detect old edits. I suppose this could fix some more issues.

You need both conditions for the fix (no temperature module exists in history **and** max blendop_version is less than 9) If there's a temperature module at blendop 8 or earlier, that probably means that the temp has been user-amended anyway, so we should just leave it unchanged. If the user left it at default it will either be absent entirely, or will have a blendop version of 9 or 10.

I'm no longer entirely sure how the thumb generation is adding modules though - the reload_defaults fix might not be needed at all (I was assuming that thumb generation wouldn't update the db when I suggested it).

**Comment by TurboGit** [comment]
> You need both conditions for the fix (no temperature module exists

You cannot use "no temperature module exists" (I tried that at first) as this happens when you select /original/ in the history stack and you compress the stack.

**Comment by TurboGit** [comment]
> I'm no longer entirely sure how the thumb generation is adding modules though - the reload_defaults fix might not be needed at all

That's becoming also my thinking at the moment...

**Comment by elstoc** [comment]
> You cannot use "no temperature module exists"

That's why I suggested you combine it with the additional condition that the maximum blendop_version in the history is 8 or less. This will never happen when compressing or resetting history.

**Comment by TurboGit** [comment]
> (no temperature module exists in history **and** max blendop_version is less than 9)

And history of another module then ?

At least I just found a case for an old edit back in 2012 had been properly handled by the circuitry in temperature module.

**Comment by elstoc** [comment]
> And history of another module then ?

Yes I mean the max blendop_version in the history table (which can't be the temperature module because it doesn't exist). It's just a way of detecting that the pipe was last executed pre-3.0.

**Comment by TurboGit** [comment]
On my side I have double checked that **exporting**, **updating lt thumbs** or **entering** into the **darkrroom** does trigger the code in develop.c so there is no point of modifying reload_defaults() in temperature. I'll remove that.

**Comment by TurboGit** [comment]
At this stage we know that this is not perfect but already fixes a bad issue.

**Comment by leclercj** [comment]
I see this fix working when exporting or entering into the darkroom. That's great
But I see the following use cases not covered: Clone then export the clone, or Clone then edit the clone in the darkroom
I'm doing this frequently to keep my old edits made with the legacy display-refered workflow, but rework the picture with the new scene-refered workflow

**Pull request merged**
