### PR TITLE
preview & culling: zoom fixes

### LINKED ISSUE #6481: Culling mode zooms to the top left corner of image
**Describe the bug**

- Open an image in darkroom mode
- Zoom the image by scrolling the mouse wheel
- Observe that the image is zoomed centering on the mouse
- Open an image in lighttable mode
- Zoom the image by scrolling the mouse wheel with the `CTRL` button pressed
- Observe that the image zooms to the top left corner

I would expect the zooming functionality to behave identically.

**Platform (please complete the following information):**

darktable from `7631e70a8437f9e73f60b56f51801d0a36c1a076`

```
$ darktable --version
this is darktable unknown-version
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```

- OS: NixOS
- OpenCL: enabled
- GPU: Nvidia 2080Ti
- Driver Version: 450.66

**Additional context**

 - Can you reproduce with a RAW or Jpeg or both?
  - Have only tried RAW (Sony AWR format)
 - Are the steps above reproduce with a fresh edit (removing history)?
  - Yes
 - Did you compile Darktable yourself? If so which compiler was used, with what options?
  - gcc 9.3.0 `    `-DBUILD_USERMANUAL=False`

### LINKED ISSUE #6676: Improved zoom in culling mode
**Problem**
It is very difficult to zoom to a specific area in culling mode:
Even if the mouse cursor is positioned in the bottom-right corner of the image, the centre gets zoomed.
So I have to pan to the area I want to inspect.

**Solution**
Use the existing zoom functionality of darkroom also for culling mode:
The area where the mouse cursor is positioned gets zoomed.

**Alternative**
Draw a rectangle over the area to be zoomed in darkroom + culling mode
(similar to the new zooming functionality in Adobe Lightroom 10)

### PR DESCRIPTION
**Pull request by xfh**
Hi

After using darktable for some years I've finally got around to fix some issues that have been annoying me in sticky preview und culling mode regarding zoom handling:

1. added zooming to 100% at mouse pointer position, fixes #6676
2. position shifts when switching to the next image, fixes #6481

This is the first time I am doing anything in C & darktable and I've realised while debugging that there is a lot happening when generating the actual thumbnails, so I've kept the changes minimal.

The 1st commit for zooming to mouse pointer should be very safe, as it only impacts single image preview & culling. It does NOT add zooming to mouse pointer when culling with multiple images (that would require a more complicated change).

The 2nd commit fixes the image position shifts that happen when opening sticky preview and scrolling through different images. When zoomed, every change to the next/previous image also added some seemingly random position shift. This is most notable when looking at multiple similar images to pick the best one (e.g. in terms of facial expressions or sharpness in a specific area).

My solution for the position shift is trivial, but I guess it requires a bit of an explanation. I've been debugging the code for a while and discovered that when changing images, a small 40x40 thumbnail is created, which is eventually scaled up fill the screen.
In the draw method, there is some logic to translate the zoom position:
https://github.com/darktable-org/darktable/blob/374f7b377014dbba5150086e8a24e615174f21e3/src/dtgtk/thumbnail.c#L486-L499

My understanding is, that it should only be applied when an actual zoom happens. When starting with a newly created thumbnail, the position of the first selected image is re-applied using it's dimensions/coordinates (not the ones of the newly generated thumbnail):
https://github.com/darktable-org/darktable/blob/374f7b377014dbba5150086e8a24e615174f21e3/src/dtgtk/culling.c#L1486-L1498

Essentially, the values of `hh` and `ww` are <= 40 px when dealing with a newly created thumbnail, and result in the seemingly random position shift. My change is to NOT change the zoom position when dealing with such a small thumbnail.

I find in practice these changes work very well. @AlicVB do you see any cases I've missed?

### CODE REVIEW

**Comment by xfh** [comment]
Regarding #6676, it does fix it when culling with 1 fixed zoom image (which is kind of the same as using sticky preview).
When multiple images are shown, then 100% zoom (still) always highlights the images' center.

I was thinking that the zooming logic might become easier to deal with when instead of the absolute (zoomx, zoomy) position a percentage offset is stored, e.g. (0%, 0%) top-left, (50%, 50%) center, (100%, 100%) bottom-right etc. of the image's dimension.
That would make the image position independent of the actual zoom factor and would help to get rid of the translations.

**Comment by AlicVB** [comment]
@xfh : Can you test #7719 by any chance ?
it should remove the 40x40 initial image, and in my quick test, I think that this would fix the zooming issue of your second commit...

**Comment by xfh** [comment]
@AlicVB Nice! I'll start testing with PR #7719 and will let report soon.

**Comment by xfh** [comment]
@AlicVB  There is still a problem with position shifts when moving from one image to the next. The changes in #7719 also break my workaround, because the thumbnail is now initialised to a much larger value.

The problem is that `dt_thumbnail_create_widget` creates the thumbnail without taking into account the zoom factor (or rather, it does a "fit to screen" scaling). Thus, when you switch images with dimensions > view size zoomed-in, the thumbnail's initial width or height is wrong.

An example:
In my test I use a portrait image of 3456 x 4608 px. My preview area is 1900 x 1085 px (screen size minus some darktable window margins).
The new thumbnail is generated for 759 x 1085 px (fit to screen, limited through the height).

I can try to take the zoom factor and image dimensions into account when creating the thumbnail, such that it gets always initialised with the correct final size. I'll let you know by tomorrow evening if my attempts are getting anywhere.

**Comment by xfh** [comment]
Hi @AlicVB, it took may way longer than I hoped, but I think I found a solution to generate the correct initial image_w widget size to avoid position shifts. Basically I am distinguishing whether the thumbnail is created in zoomed or fit to screen mode. When zoomed, to widget size is now increased up to the maximum allowed size.

I've merged your PR #7719 into mine, since my latest changes don't make sense without your adjustments.

The flickering issue is still there. As I've mentioned, I think it's due to the fact, that the initial image_w is created without taking into account the margins. Do you see any way to get the correct margin values before the widget is drawn?

**Comment by TurboGit** [comment]
So I suppose after merging #7719 this should be closed, right?

**Comment by AlicVB** [comment]
well, I think that at least the first commit is still needed...
@xfh : I'm sorry for the mess that my PR (now merged) has done in your work, but that was really complex to fix...

**Comment by xfh** [comment]
Hi both of you

Actually, both issues are still there, even after merging #7719. I've been working on adjusting my changes on top of #7719, but it seems that now the zoom to mouse pointer function produces a slight offset. I'll rebase and investigate some more on the weekend.

**Comment by xfh** [comment]
Hi @AlicVB, I had to deal with a lot of flickering images until I figured out how to solve the problem properly ^ ^
It is really important to initialise that image_w widget correctly...

I changed how the "zoom" is propagated while moving in preview/culling. It used to simply apply the zoom of the 1st thumbnail.
I've instead introduced a new variable in the culling table, to store the zoom ratio from 0% "image to fit" to 100%. I think that makes more sense when browsing through images with different resolution.
 
Zoom to mouse pointer is only fixed in preview or culling with 1 image. So #6676 is only partially fixed.

**Comment by xfh** [comment]
I just realised that the aspect ratio is no longer needed to calculate the image_w widget size.
I've kept the access of the mipmaps to determine the dimensions, but maybe it is no longer needed. Instead, we could extract the dimensions from the image cache.

@AlicVB How reliable (available) are img->final_width and img->final_height at that stage?

**Comment by AlicVB** [comment]
> @AlicVB How reliable (available) are img->final_width and img->final_height at that stage?

not really reliable, except after the call of `dt_thumbnail_get_zoom100` where we explicitly trigger the size computation. As you try to fix the zoomed case, maybe we can do the stuff in 2 path : the actual for `IMG_TO_FIT` and another one for zoom, where we can call `dt_thumbnail_get_zoom100` at the beginning, to be sure to have reliable values (in fact we could even skip completely the size retrieval from smaller mipmap in this case so we have more precise values)

Other than that, I think you've done a great work, I was afraid for cases where one would have set a different zoom and position values for each thumb (with ctrl-shift-scroll) but it seems to works as well :)

**Comment by xfh** [comment]
Hm, that means we would not get rid of the mipmaps access completely.

Is the performance difference significant to add yet another code path? If not, I would rather keep it simple.


________________________________

**Comment by AlicVB** [comment]
if I'm not mistaken, you don't get ride of mipmap retrieval, currently...
What I have in mind is something like : 
```
if (zomm_ratio == ZOOM_TO_FIT)
{
  ...old stuff...
}
else
{
  dt_thumbnail_get_zoom100(thumb);
  ... your new stuff, but directly with img->final_width/height no need to ask for mipmaps...
}
```

Sadly, `dt_thumbnail_get_zoom100` is quite time consuming and so should be avoided ofr "classic" thumbnails

**Comment by xfh** [comment]
My implementation already takes care of that. zoom_100 is only calculated when it's necessary: when zoom_ratio != IMG_TO_FIT.

**Comment by AlicVB** [comment]
yes, I know, this is just to answer to your question : 
> Is the performance difference significant to add yet another code path? If not, I would rather keep it simple.

But now I wonder if I've understand it correctly... the reason why I've done the proposal above is : 
- img->final_width/height aren't reliable except once you have called dt_thumbnail_get_zoom100
- dt_thumbnail_get_zoom100 should only be called for zoomed images (that's what you have done)
- img->final_width/height (if available and reliable) are way more accurate that some computation from smaller mipmaps

**Comment by xfh** [comment]
I see. My question about getting rid of mipmaps and just use img_>final_widht/height was just because I assumed that accessing `dt_image_cache_get` is faster than loading mipmaps. I assumed that, because it was the original implementation, before you added the mipmaps path to get a better aspect ratio. I never tested it though.

I haven't noticed any flickering with the mipmaps' width/height. AFAIK, your code gets a mipmap that's larger than the screen (larger than `image_w` and `image_h`). I then use that get `scale_to_fit`, such that width and height of the screen matches a "img to fit". It doesn't really matter how much larger the mipmap (or the actual image) is. It should just be some scaled dimension of the image, that is shown in the end.
I think the accuracy is equal to what we had before, with the aspect ratio. Since `aspect ratio = width / height`, the values are clearly correlated.

I see one case, that might be different: when there is no mipmap available and img->final_width/height are 0. In that case, my implementation simply allocates the entire imagebox size, whereas before one side was scaled by the image's aspect ratio. Would you like me to restore that behaviour if you like?

**Comment by xfh** [comment]
@AlicVB I've rebased and refactored the code to have the original IMG_TO_FIT code and the new zoomed case:
```
if(zoom_ratio == IMG_TO_FIT)
  _get_dimensions_for_img_to_fit(thumb, image_w, image_h, &iw, &ih);
else
  _get_dimensions_for_zoomed_img(thumb, image_w, image_h, zoom_ratio, &iw, &ih);
``` 

Please let me know if there is anything else you would like me to change.

**Review by AlicVB — APPROVED** [review]
Sorry for the delay, I have difficulties to follow everything this days...
Yes I think your last solution is better. Thanks for the changes and for this hard work !

**Comment by AlicVB** [comment]
@xfh : just for the record, to answer to your previous post, we have to try to allocate the right size for the image from the beginning, otherwise we have some flickering effects due to some gtk glitches. That's why we want the aspect ratio at thumb creation (so we have a base to compute the size once we know the full area)
But that works for IMG_TO_FIT, not zoom. Now with your work, we have all cases covered !

**Comment by TurboGit** [comment]
I need help testing this. On my side I see that the zoom fix is working on the sticky preview but not on the culling mode. Can you double check this part ? Or tell me more about the fix ? TIA.

**Comment by AlicVB** [comment]
@TurboGit : If you speak about the center on pointer part, there's no change for culling with more than 1 images. For the rest, it's more about avoid flickering and unwanted movements when you scroll through zoomed images.

**Comment by xfh** [comment]
I've I may: I have one last commit to support zooming to mouse pointer (by pressing scroll wheel / mouse button 2) in culling mode with more than 1 image. That would in my opinion be good enough to close #6676 for good.

I've implemented the following:
- When clicking scroll wheel while the mouse pointer is hovered over an image, the image is zoomed to 100%. All other images in the culling view are zoomed using the same offset.
- If the mouse pointer is NOT hovered over an image while clicking, then the images are zoomed to 100% in the center (as before)

ctrl + shift + 2nd mouse button affects only the selected image as before. However, with ctrl + shift + 2nd mouse button, you only get to 100% and not back. IMHO, it would be nice to also be able to go directly back to "img to fit" mode. I didn't dare to change this without asking first. Let me know what you think. It should be a simple change.

**Comment by xfh** [comment]
I rebased, hoping that it will make the CI builds pass...

To test #6481:
1. Select any image
2. Create a duplicate
3. Change e.g. white balance of one of the images (just go make it obvious which image is shown)
4. Open preview for the first image and zoom to 100%
5. Move to the next image -> notice how the position is exactly the same

To test  #6676:
1. Open culling with e.g. 2 images
2. Press 2nd mouse button (scroll wheel) on a distinct part of one of the images -> notice how you zoom to 100% at pointer position
3. Press 2nd mouse button and ctrl + shift on a distinct part of one of the images  -> notice how  you zoom just that image to 100% at pointer position
4. Press 2nd mouse button on the background of culling view (such that no image has the white border) -> notice how you zoom to 100% at the image's center
5. click again, to get back to "img to fit" mode

**Comment by AlicVB** [comment]
> it would be nice to also be able to go directly back to "img to fit" mode. I didn't dare to change this without asking first. Let me know what you think. It should be a simple change.

yes, go for that. I don't see any drawbacks...

I've just done some test, and it works very well ! well done. I'll try to take a moment to review the code tomorrow...

**Comment by TurboGit** [comment]
> @TurboGit : If you speak about the center on pointer part, there's no change for culling with more than 1 images. For the rest, it's more about avoid flickering and unwanted movements when you scroll through zoomed images.

Yes, I was speaking about this. So I see now that there is hope to have this fixed too. I'll wait then before testing again.

**Comment by xfh** [comment]
> > it would be nice to also be able to go directly back to "img to fit" mode. I didn't dare to change this without asking first. Let me know what you think. It should be a simple change.
> 
> yes, go for that. I don't see any drawbacks...

I've implemented that with the last commit. 

My refactoring went a bit further than anticipated, but it allowed me reduce calls to `dt_control_get_mouse_over_id` and several loops over table->list.

**Comment by TurboGit** [comment]
Ok, I confirm that there is a big improvement in the zoom placement in the scenario described. This is ok on my side, I'll let @AlicVB have a final review before merging. Thanks.

**Review by AlicVB — APPROVED** [review]
All good for me !
Thanks again...

**Comment by TurboGit** [comment]
Thanks !

**Comment by Nilvus** [comment]
Just a BIG THANKS to both of you, @xfh and @AlicVB for you combine hard work on that. Just tested on few images and culling is just much better now.Really great.

As this fix some culling issues, I would just see that in 3.4.1 too, not only waiting for 3.6.

**Comment by xfh** [comment]
It has been my pleasure working with you and being able to help out with a small contribution.

I am very impressed by cour continuous engagement in the development of darktable. I realise, that even tiny improvements are often very time consuming. Thank you, members of the dev & docs team, very very much for finding that time, besides job, family and other things in life!

**Pull request merged**
