### PR TITLE
Enable the metadata editor in darkroom view

### LINKED ISSUE #17261: Metadata Editor module in Darkroom (next to the Tagging module)
Currently, in darkroom mode, on the left-side modules, we have the Tagging module where we can create/assign tags as we browse/edit each pic. In my workflow, I do a first pass/reject type scan of new photo sets directly on the Darkroom. Having tagging is great but we are currently missing all other metadata. I am mainly seeking to have Title and Description.

**Describe the solution you'd like**
Adding the Metadata editor module in the left pane next to the Tagging module in the Darkroom

**Alternatives**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by victoryforce**
Resolves #17261.

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
OOps, don't know how the change from `master` to the `30bit` branch happened at all. Awfully sorry!

**Comment by victoryforce** [comment]
> OOps, don't know how the change from `master` to the `30bit` branch happened at all.

no problem, it's reversible :)

**Comment by zisoft** [comment]
> Add a tick in utility modules (listed above) preferences dialog to select whether it must be shown in darkroom or not.
> So we let the user the full control of whether a module should be in darkroom.

@victoryforce: Are you currently working on this? If not, I would like to take over.

**Comment by victoryforce** [comment]
> @victoryforce: Are you currently working on this? If not, I would like to take over.

Thank you, Mario, for offering to help!

I, however, actually worked on it, and now I'm finalizing the code, testing it and thinking about the text of the comment-rationale for why I did it in a slightly different way than suggested (not _inside_ the module's local preferences).

I hope to force-push the updated code tomorrow (today we had 2 hours of electricity after 7 hours of absence, so there was little opportunity to work).

**Comment by dterrahe** [comment]
https://github.com/dterrahe/darktable/commits/ancil/
[hide/add utility modules in side panels]

**Comment by victoryforce** [comment]
> No please, we have worked hard to remove entries from the main preferences to avoid having too much entries. So, better having the selection into the module's preference dialog.

I will try to summarize possible interface solutions and their inherent drawbacks.

An excessive number of settings in the program's global settings dialog psychologically discourages the user, he feels overwhelmed and tends to consider the program difficult. And it does not depend on how difficult the program is to use. People just don't like having to choose.

In practice, we need to find a balance between the demands of advanced users to have certain options and the desire of the majority not to see many options in front of them (which will have to be read, understood and thought about which choice to make). In part, the problem is solved by intelligent structuring of the settings, which slightly reduces the mental load on the user.

It is important that darktable, unlike many other programs, has a convenient and understandable interface for certain settings of a specific module - this is the "local menu of the module", a hamburger in the header of the module. This menu is typically used to create and select module presets, but may also contain other menu items. In some cases, through this menu, you can open a dialog for setting options specific to the module. Having these local preferences makes it possible to offload the global settings from everything that only applies to one particular module.

I first tried adding the module darkroom visibility option to the local preferences dialog as suggested by @TurboGit. Or rather, I just made a quick mockup and started to see how it looks. Unfortunately, such a solution also does not look optimal.

The setting of whether the module is visible in darkroom mode looks alien among the actual module settings. Because this, in fact, is not a setting of the module itself, it does not determine the behavior of the module itself. In the preferences interface of the export module, for example, adding such a parameter looks extremely artificial and alien. The group in the darkroom section of the global settings looks at least logical, although we want to avoid such a solution.

In addition, moving module visibility toggle to any settings dialog does not have the highest discoverability, because some users have a habit of not opening any settings, working only with what they see in front of them.

In fact, the ideal place for this toggle is a menu item in the module's local menu itself, without pushing it inside the module's "preferences...". In a similar way, "show guides" are implemented in the processing modules.

This is what I will propose in the next PR. I am closing this PR so as not to mix the discussion of the first simple solution (adding visibility for a specific module) and the new one, which adds general support for the toggle in the utility modules menu.

**Pull request closed without merging**
