### PR TITLE
Visualize clipped photosites in highlights module

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
While working on another highlights reconstruction algorithm - work is still going on - i came across the problem to see what photosites are clipped right in the module and depending on the setting of the clipping threshold.

There is now a single button, if switched on a false color image is shown (every photosite clipped gives a full value of 1, otherwise 0)

I found it very helpful, not absolutely sure whether other folks think so too. So - a suggestion.

### CODE REVIEW

**Comment by TurboGit** [comment]
Why not ! Tested quickly and found that the display is not refreshed when changing the highlight recovery method.

**Comment by TurboGit** [comment]
Have you tried fading out the display instead of full back where there is no clipped pixels? It seems a bit awkward to me like this. Again that's from a quick testing. Would be nice to have more feedback on this (but to me this is a really good added feature).

**Comment by jenshannoschwalm** [comment]
As the visualizing show photosites above clipping threshold the shown image does not depend on the algorithm.

**Comment by jandren** [comment]
Awesome :) Exactly what I meant in my comment over at https://github.com/darktable-org/darktable/pull/11391
The mask used by the reconstruction method is not coupled to the raw sensor clipping.

How about putting the mask icon right after the clipping threshold slider?

Screenshot from 2022-04-18 11-02-55

The mask was also processed by later modules for me. That should not happen, right?
Any reason for not having a pass-through of unclipped areas and drawing the mask on top?

Finally, isn't the "Guided Laplacian" option white balance invariant? I.e. it should be different in what is clipped compared to the other available methods. The "clip", "Lch", and "color" options should indeed be the same and not change between each other.

**Comment by jenshannoschwalm** [comment]
> Have you tried fading out the display instead of full back where there is no clipped pixels?

Should be better now.



> Any reason for not having a pass-through of unclipped areas and drawing the mask on top?

Masks are only "one color" ...


> How about putting the mask icon right after the clipping threshold slider?

There **are** people knowing to write correct Gtk code :-)



> I.e. it should be different in what is clipped compared to the other available methods

I really didn't want to fiddle around what the differrent algos might do. This is only about "what data do we find at the sensor above clipping threshold"

**Review by TurboGit — APPROVED** [review]
Looks ok, I'll handle the Gtk part :)

**Comment by jenshannoschwalm** [comment]
@TurboGit thanks for the Gtk stuff :-) I will learn from how you do it ...

**Comment by TurboGit** [comment]
@jenshannoschwalm : Done for the Gtk part. I have also used a lighter washed out for the non clipped area changing from 0.1 to 0.2. Let me know if ok to you otherwise I'll revert.

**Pull request merged**
