### PR TITLE
Made compression/quality sliders insensitive when uncompressed is selected

### LINKED ISSUE #3557: UI → Export to lossless WebP
Lossless settings in export to WebP should hide quality slider because it makes zero difference for the end result.

### PR DESCRIPTION
**Pull request by sams96**
Fixes #3557, I did also just kind of assume that uncompressed TIFFs aren't affected by the compression level but I can remove that change if I'm wrong.

### CODE REVIEW

**Comment by sams96** [comment]
I have alternatives in another branch that hide the sliders instead at the request @timur-davletshin

**Comment by cryptomilk** [comment]
I would just hide/show them, I also have this in my AVIF branch and it works well.

**Comment by sams96** [comment]
I personally prefer making them inactive, it stops the rest of the module jumping around for a small change, but if everyone else prefers hiding them I can make that PR instead.

**Comment by TurboGit** [comment]
I prefer them being inactive. I have asked @Nilvus  to help for the CSS part to ensure the state is well visible.

**Comment by timur-davletshin** [comment]
@TurboGit I'm not saying that I'm against it. But dt in all other places hides irrelevant options. E.g. demosaic settings 😃

**Comment by TurboGit** [comment]
With @Nilvus work on #3579 I will merge this as it really improve the user's experience and this looks quite safe. Thanks!

**Pull request merged**
