### PR TITLE
local laplacians: optimize and remove SSE code

### PR DESCRIPTION
**Pull request by ralfbrown**
One of the optimizations added in the third commit also substantially sped up the SSE code path, because there was a bug in the existing code which caused it to call a scalar function in nearly all cases instead of only for the unaligned start/end of a row.  This does slightly change the output since we are now using the approximate but much faster `dt_fast_expf` instead of `expf`, but the SSE code used the equivalent of dt_fast_expf, which is why I tried it in the first place.  If the maxDE of 2.1 for test 0002 is unacceptable, I can roll back the third and fourth commits or have you cherry-pick the first two.
```
Thr     OrigSSE   SSE      AutoVec
1       1246.08   935.91  918.65
2        677.79   523.58  515.15
4        379.16   301.11  297.18
8        231.58   194.54  193.32
16       156.24   141.36  138.08
32       131.39   121.41  120.80
```

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
All good to me, again a really nice work and the dE of 2.1 still let the tests pass OK. Thanks.

**Comment by TurboGit** [comment]
For the record, this commit has introduce a regression in test 

commit 28ba887e1be24612769775383642997209869c02
Author: ralfbrown <ralfbrown@users.noreply.github.com>
Date:   Sun Mar 5 02:34:01 2023 -0500

    replace expf by dt_fast_expf, remove apply_curve_sse
    
    This makes the scalar code match the SSE code, and substantially speeds up *both*,
    as there was a bug in apply_curve_sse which meant that it basically just used
    the scalar curve function instead of the vectorized one.
    
    Since the non-SSE codepath is now substantially faster than the original SSE,
    remove the remainder of the SSE code in locallaplacian.c.
    
    Thr     OrigSSE   SSE      AutoVec
    1       1246.08   935.91  918.65
    2        677.79   523.58  515.15
    4        379.16   301.11  297.18
    8        231.58   194.54  193.32
    16       156.24   141.36  138.08
    32       131.39   121.41  120.80

 src/common/locallaplacian.c | 115 +-------------------------------------------
 src/common/locallaplacian.h |   7 ++-
 2 files changed, 5 insertions(+), 117 deletions(-)

**Comment by TurboGit** [comment]
For the record this commit has introduced a regression in test 0090-mask-combine.

```
commit 28ba887e1be24612769775383642997209869c02
Author: ralfbrown <ralfbrown@users.noreply.github.com>
Date:   Sun Mar 5 02:34:01 2023 -0500

    replace expf by dt_fast_expf, remove apply_curve_sse
    
    This makes the scalar code match the SSE code, and substantially speeds up *both*,
    as there was a bug in apply_curve_sse which meant that it basically just used
    the scalar curve function instead of the vectorized one.
    
    Since the non-SSE codepath is now substantially faster than the original SSE,
    remove the remainder of the SSE code in locallaplacian.c.
    
    Thr     OrigSSE   SSE      AutoVec
    1       1246.08   935.91  918.65
    2        677.79   523.58  515.15
    4        379.16   301.11  297.18
    8        231.58   194.54  193.32
    16       156.24   141.36  138.08
    32       131.39   121.41  120.80

 src/common/locallaplacian.c | 115 +-------------------------------------------
 src/common/locallaplacian.h |   7 ++-
 2 files changed, 5 insertions(+), 117 deletions(-)
```

```
Test 0090-mask-combine
      Image mire1.cr2
      CPU & GPU version differ by 82139 pixels
      CPU vs. GPU report :
      ----------------------------------
      Max dE                   : 5.28643
      Avg dE                   : 0.01888
      Std dE                   : 0.12591
      ----------------------------------
      Pixels below avg + 0 std : 97.06 %
      Pixels below avg + 1 std : 97.07 %
      Pixels below avg + 3 std : 97.79 %
      Pixels below avg + 6 std : 99.22 %
      Pixels below avg + 9 std : 99.79 %
      ----------------------------------
      Pixels above tolerance   : 0.02 %
 
      Expected CPU vs. current CPU report :
      ----------------------------------
      Max dE                   : 5.28643
      Avg dE                   : 0.01598
      Std dE                   : 0.11949
      ----------------------------------
      Pixels below avg + 0 std : 97.64 %
      Pixels below avg + 1 std : 97.64 %
      Pixels below avg + 3 std : 98.11 %
      Pixels below avg + 6 std : 99.22 %
      Pixels below avg + 9 std : 99.73 %
      ----------------------------------
      Pixels above tolerance   : 0.02 %
 
  FAILS: image visually changed
         see diff.png for visual difference
         (65986 pixels changed)
```

The diff is:

diff

Looking at the area where the diff is I cannot see a visual difference (dE 5.2 is still in the small difference). And the area corresponds to a local contrast (laplanian method) applied on this area. So I'll update the expected output.

**Comment by TurboGit** [comment]
@ralfbrown : Still one point. I see that the OpenCL is now differing from CPU more than before, so maybe we have the same bug on OpenCL? The Max dE GPU/CPU was around 1.1 and is now 5.28 following the exact same pattern we have between the old CPU and new CPU code.

**Comment by ralfbrown** [comment]
I'm pretty sure it's due to changing from`expf` to `dt_fast_expf`.  We can take a look at what reverting just that single-line change in `curve_scalar` does (I just checked, and the corresponding OpenCL code calls native_exp).

**Comment by TurboGit** [comment]
You're right. So better use `dt_fast_expf()` in OpenCL code to have closer output with CPU path. See  #13843.

**Pull request merged**
