### PR TITLE
tagging: add drag & drop actions

### LINKED ISSUE #6019: Drag & drop tags
**Is your feature request related to a problem? Please describe.**

Tag management in light table is very  stiff, 
drag and drop would allow us to arrange and move tags, to build meaningful tag trees, as assigning tags is often a work in progress. Adding tags one by one is a waste of time and cumbersome 

**Describe the solution you'd like**

A) select a tag in the list view, to deselect the same tag 
B) if a tag in the list view is selected and you are gonna adding a new tag, then  transform the selected tag automatically into a category and add the new tag to it 
C) remove a tag or multiple tags from a category to transform the category into a tag 
D) if no tag is selected, add a new tag to the list 
E) a button to delete tags, right click is cumbersome 
F) ability to export - rename files using 
Category | category | tag - counter. File Extension

### PR DESCRIPTION
**Pull request by phweyland**
Fixes #6019

With this PR the user can drag and drop:
- tags in the hierarchical dictionary to reorganize them
- images to dictionary view

~~Current limitation: the user cannot drop a tag to root ... and I haven't yet found a way to do it ? Ideas ?
EDIT: this is always possible with <right-click>rename path of course.~~

I've left some FIXME(s) in the code in case someone has a great idea(s).

### CODE REVIEW

**Comment by johnny-bit** [comment]
I haven't checked yet but it looks like it fixes #6019?

**Comment by phweyland** [comment]
> I haven't checked yet but it looks like it fixes #6019?

Should ! :smile:

**Comment by phweyland** [comment]
Found a solution to drop to root. 
Can somebody check if that's discoverable enough ?

**Comment by johnny-bit** [comment]
Discoverable or not, a PR to https://github.com/darktable-org/dtdocs with explanation/instructions would be great to have :)

**Comment by phweyland** [comment]
> Discoverable or not, a PR to https://github.com/darktable-org/dtdocs with explanation/instructions would be great to have :)

Of course! That goes without saying (if this gets merged :smile: ).

**Comment by phweyland** [comment]
@TurboGit , That's ok for review when you can.

**Comment by TurboGit** [comment]
Works for me. Merged to master and queued for 3.4.1.

**Comment by johnny-bit** [comment]
@phweyland now you HAVE to maek a PR to https://github.com/darktable-org/dtdocs :wink:

**Comment by phweyland** [comment]
> now you HAVE to maek a PR to https://github.com/darktable-org/dtdocs wink

Done ! :wink:

**Comment by cjelgin** [comment]
@elstoc it looks like the documentation has already been completed https://github.com/darktable-org/dtdocs/pull/182. Is there anything else needed here?

**Comment by elstoc** [comment]
@cjelgin indeed you are correct. Thanks

**Pull request merged**
