### PR TITLE
tagging: some UI improvements as suggested on dev.

### PR DESCRIPTION
**Pull request by phweyland**
- when filtered by entry text, down arrow gives focus to the first corresponding tag
- when tag is selected in dictionary view, pressing Enter attaches it
- right/left arrows expand/collapse the selected row (Shift+right full expands the row)

See [here](https://www.mail-archive.com/darktable-dev@lists.darktable.org/msg06542.html)

### CODE REVIEW

**Comment by phweyland** [comment]
So far here is my interpretation of @ChristianBirzer suggestions:
- Tab key move forward attached view -> entry -> dictionary view
  - From entry, selects the first matching tag in dictionary view if any
- Shift+Tab same backward
  - From entry, selects the first user tag in attached view
- Enter on dictionary view attaches the selected tag if any
  - Keeps focus on the attached tag (as for tag attached with the mouse)
- Delete / BackSpace on attached view detaches the selected tag
  - Selects the next user tag, if not selects the first user tag, if not gives focus to entry (this behavior is also implemented when a tag is detached with the mouse)
  - darktable tags cannot be selected any more in attached view
- Built-in search on treeview deactivated

Missing button shortcuts added.

**Comment by phweyland** [comment]
@elstoc Chris, I've been interested by your suggestions about the spelling standardization of actions like Shift+click, etc... Is it worth to try to align the code (I've some candidate tooltips here) ? Where could we store/check the references ?

**Comment by elstoc** [comment]
@phweyland for dtdocs it should go to the [contributing page](https://darktable-org.github.io/dtdocs/en/special-topics/contributing/). I'm not sure about for darktable.

One thing to consider is that the only reason (IIRC) that darktable used uppercase before was because it's how Gtk describes the key presses, and that currently the general 'style' of darktable is for everything to be lower case (because hanatos hates capital letters). So right now my convention in dtdocs is just something I've used when writing/editing and not explicitly defined (yet). It's just what looked good to me at the time.

Of course moving the user interface to Title Case is something that has been discussed before (and likely a very big job). Personally I don't have a big problem with lower case, except where we are constructing sentences that don't start with a capital letter (so mostly tooltips), and especially where a sentence follows a full stop (IMO that looks unprofessional).

**Comment by phweyland** [comment]
> If we're going to work on a mixed-case convention I think that should be a separate activity and we should agree rules before doing it.

:+1:

**Comment by ChristianBirzer** [comment]
@phweyland Thank you very much for your work. I just played around with your implementation. Feels good.
Only three tiny things to remark so far (ähm, sorry for that 🤷‍♂️):
1. While using the tab key to switch between the entry field and the dictionary view is consistent with the overall gui, my muscle memory wants to press cursor down to select the entry from the list. This would be consistent to the entry completion in the popup tagging (or other drop down list completion stuff). I don't really know which one is the better of both or if it would also be ok to support both (the cursor down does nothing anyway when focus is in the entry field).
2. After adding a keyword with enter, I cleared the entry field and put focus back in it. So you can immediately begin typing the next keyword. This could be better if there is only one hit per filter expression most of the time while your approach is better when the filter keeps the same for a number of tags (my implementation used shift-enter to keep the focus in the dictionary list).
3. When deleting the last (bottom-most) keyword from the attached list, the focus jumps to the top-most entry. This looks a bit nervous because when deleting other entries, the focus keeps "in place". My approach was to focus the bottom-most entry in this case (while I did not care about internal tags so far)

**Comment by phweyland** [comment]
> it would also be ok to support both (the cursor down does nothing anyway when focus is in the entry field)

I agree.

> After adding a keyword with enter, I cleared the entry field and put focus back in it. So you can immediately begin typing the next keyword. 

I understand but this is not consistent with the mouse action.
This said, press Shift-Tab to have the content of entry selected, press Delete to clear it and you are done to start to type the new one. But you can also keep its content if you want. I think that's fair.

>  My approach was to focus the bottom-most entry

If I understand properly, you prefer to select the last user tag instead of the first one, correct ? I agree with that too.

**Comment by phweyland** [comment]
Added the above agreed points + keep new selected tag visible in a small attached view.

**Comment by elstoc** [comment]
I have added some suggestions regarding mixed-case conventions to the existing issue #2078

**Comment by phweyland** [comment]
> After adding a keyword with enter, I cleared the entry field and put focus back in it. So you can immediately begin typing the next keyword

I'll let normal Enter consistent with the mouse attach and I'll add Shift-Enter to do what you wanted. OK ?

**Comment by ChristianBirzer** [comment]
> I'll let normal Enter consistent with the mouse attach and I'll add Shift-Enter to do what you wanted. OK ?
That sounds great. Thank you!
I already tested the other things. Everything works perfect!

**Comment by ChristianBirzer** [comment]
Ah, one more thing:
Whats about the completion that pops up when dictionary is in list view? The one that can be disabled in preferences?
On my last test it wasn't working like expected anyway (at least when using cursor and enter keys - see https://github.com/darktable-org/darktable/pull/10789#issuecomment-1005091726 ).
Seems it is still there but imo makes no sense anymore because the filtering in the dictionary list/tree is way better.

**Comment by phweyland** [comment]
Thanks a lot for testing.

> On my last test it wasn't working like expected anyway

For me it does. When completion is activated, Down key allows to get go the desired tag, Enter moves this tag into entry and Enter again to attach the tag. Do I miss anything ?

**Comment by ChristianBirzer** [comment]
> For me it does. When completion is activated, Down key allows to go to the desired tag, Enter moves this tag into entry and Enter again to attach the tag. Do I miss anything ?

Hmm. strange. Did another test with the 3.8.0 and it works fine. Played around a bit and it's broken again. 🤔
Please try the following:
1. start dt with the tags dictionary in list view and completion not disabled
2. enter the beginning of one tag in the entry field until the completion pops up, cursor down to one tag with hierarchy, enter. -> tag is set into the entry field, enter again attaches it. works fine.
3. switch the dictionary to tree view and back to list view (without doing anything other in between)
4. enter the beginning of an other tag in the entry field until the completion pops up, cursor down to one tag, enter -> the typed beginning of the tag is attached and added to the dictionary like it was entered in the entry field. 
Seem not to be 100% reproducible (or other behaviour, see below) when the selected tag is at the top level (i.e. without an | in the path)
grafik

When entering the beginning of a tag that is on the top level, the completion already adds the rest of the tag in the entry field. This is an other case, I guess. 
In that case, the tag will be added like it is in the entry, even if you select an other tag from the drop down:
grafik
(entered "pen" which gets expanded to "pentax" in the entry, selected "pentaxian" in the drop down list and enter attaches the "pentax" tag. 
This is also only reproducible after switching the directory view to tree and back to list once.

All tests done with the 3.8.0 official build on a win10 machine.

> With this PR I agree, but as this is one of the first tags feature, I would like to get some feedback from the team before scrapping it.

I absolutely agree. Since you can turn it off already when you don't like the completion its totally ok to keep it for a while and wait for more user response.

**Comment by phweyland** [comment]
@dterrahe, on the same subject we can add keyboard commands for contextual menus.
Should we add hard-coded keys or should we create new shortcuts for that ? What do you think ?
Another detail. I've seen that, by some magic, shortcuts keys were added to buttons' tooltips. Not sure this can/should be done for contextual menus.  Thoughts ?

**Comment by phweyland** [comment]
> Did another test with the 3.8.0 and it works fine. Played around a bit and it's broken again.

You are right. I think there is a long standing bug behind this. See my comment for signal connect on entry.
The fact to switch back and forth between listview and treeview, disables and enables again entry completion. Doing this, completion doesn't get back the control of keys (Down key in particular). The selection by mouse click still works.
Not sure I want to try to fix this however.

**Comment by ChristianBirzer** [comment]
> Not sure I want to try to fix this however.

I'm not in the position to decide anything here but personally I'd leave it like it is. Seems nobody had a problem so far with it and there are chances that the function gets kicked out in the future anyway (and can already be deactivated).

**Comment by dterrahe** [comment]
> Since you can turn it off already when you don't like the completion its totally ok to keep it for a while and wait for more user response.

Maybe. Mixing gtk features and doing things yourself "manually" often leads to conflicts and unexpected interactions so sometimes you're better off doing it all yourself because at least then it is predictable. But you may lose some features that gtk gives you for free. Which is a pity, if they work...

> shortcuts keys were added to buttons' tooltips

Any action related to a visual element/widget that has a configurable shortcut attached should be showing it in its tooltip, thanks to the inputng framework. This also means you can use visual shortcut mapping to define new shortcuts. If any widgets are not showing their shortcuts, this should be considered a bug.

> Not sure this can/should be done for contextual menus. Thoughts ?

As far as I can tell, we don't have a HIG for dt and we are _definitely_ not following the Gnome HIG, so some things fall in the cracks. We define shortcuts at the view level, with in the past some _very_ few being enabled only when their module had focus. This doesn't really combine too well with context menu shortcuts, like gtk supports them, which really are linked to individual widgets having focus. Context menus as such are second rate citizens in dt, as far as I can tell. They are used in _some_ places (where there is no better alternative) but they are definitely not used everywhere where they _could_ be or _possibly_ would make things simpler. My preference would be to not let context menus organically grow too much without having a clear vision of how they fit in the wider picture. Having a separate infrastructure to support and define shortcuts for them (or using gnome features to do that for us) could lead to a hodgepodge of duplicate/conflicting/inconsistent/unintuitive controls. And might require band-aids like the disabling of all global shortcuts whenever an Entry got focus, like we had in the past and I just removed for inputng.

So yeah, for now hardcoding a few essential, obvious shortcuts (of the Del/Ins variety) can be done in the key-press-event handlers; inputng first allows the focused widget to handle whatever it wants and only picks up unhandled keypresses afterwards. We've used the explicit widget tooltips to list those contextual "shortcuts" and their functions for the user.

**Comment by phweyland** [comment]
@TurboGit Pascal, I think this PR is good for your review.
Keyboard shortcuts (hard-coded) for contextual menus will be for another PR as it requires some work on the popups as well.
As @ChristianBirzer said, with this PR, the entry completion (only available on treelist) is not necessary/useful any more.
Do you think we should remove it (but we keep ctrl-t and its popup)?
TIA.

**Review by TurboGit — APPROVED** [review]
Works for me, nice improvements. Thanks.

**Comment by TurboGit** [comment]
Merged in master and darktable-3.8.x branch.

**Comment by TurboGit** [comment]
Sorry, missed to say that we can work the completion issue discussed here in a separate PR if needed.

**Comment by phweyland** [comment]
Yes, that will be simpler to analyze the case. :)

**Comment by ChristianBirzer** [comment]
> I'm not sure about what we are talking about here. "treelist"? We have a list or tree view, and I see entry completion only when using the list view. Certainly I would keep it. Is there some other completion that I have missed?

There are two types of "completion" I was talking about.
The first one was the gtk own search functionality of the treeview that pops up when you start typing while the focus is inside the tree. That's already disabled with this PR.
The second one is the completion that pops up when you start typing in the tag entry field and which can be switched off in the preferences. I think it is redundant now since the dictionary tree (in tree and list mode) is now filtered while you enter the tag in the entry field. But as it can be switched off, I agree that it can be kept because than you can decide which one you like more. 

btw: thanks a lot for adding my suggestion about the tagging workflow!

**Comment by dterrahe** [comment]
> it can be kept because than you can decide which one you like more.

Often we add preferences to be able to switch off features that haven't been implemented well and can't be fixed. If they _can_ be fixed, like here, we should get rid of the preferences Imho and not have two ways to do the same thing.

Just to list a few of the drawbacks of redundant functionality:
1. multiple codepaths to maintain (and test). Things will get broken because a developer doesn't (know how to) use a preference. Especially when the impact is _really_ subtle and there is no actual benefit, people will not use (and therefore test) both modes.
2. many preferences to try out. Ideally we'd want each user to configure dt to suit them best, but when there are so many options and it takes some time to even figure out what they mean (or _why_ they are there in the first place) we discourage experimentation. Which means they may never find useful functionality (that may be disabled by default only because that made for simpler documentation). Again, leading to less testing, more bugs.
3. all options need documentation.

So I'd suggest the completion and preference could be removed in a second PR and reverted if someone complains with a reasonable argument that can't otherwise be addressed.

**Comment by phweyland** [comment]
I'll issue another PR for this. Thanks for comments.

**Pull request merged**
