### PR TITLE
Improve preset checkbox

### LINKED ISSUE #9624: FR: Lower Contrast Preset Menu Checkboxes
I find the checkboxes that now appear in the preset menu to be a little too high contrast for my taste. The boxes currently have the same colour as those on the body of the modules but against a darker background.

Current:

Screenshot_2021-07-25_00-09-41

With `@plugin_bg_color;`:

Screenshot_2021-07-25_00-10-09

Given that the only intention here is to highlight the selected option (with a tick) my preference would be to make the checkbox entirely blend into the background:

Screenshot_2021-07-25_00-13-18

### PR DESCRIPTION
**Pull request by Nilvus**
As requested by @elstoc. So fixes #9624.

### CODE REVIEW

**Comment by elstoc** [comment]
This doesn't really work with the "show guides" option, which really should be an actual checkbox. Perhaps we should add a class to the menu items to be sure that it only affects presets and blend menus.

**Comment by Nilvus** [comment]
> This doesn't really work with the "show guides" option, which really should be an actual checkbox. Perhaps we should add a class to the menu items to be sure that it only affects presets and blend menus.
> 
> [elstoc@d22723f](https://github.com/elstoc/darktable/commit/d22723f04e18f0b3d49af44850e939b194934a71) should allow you to target both menus with classes "blend-colorspace" and "preset-menu-item"

Shit, I was quite sure there were another part were this wouldn't work but without being able to remember which one...

**Comment by Nilvus** [comment]
@elstoc: I had answered too quickly. Was thinking of new guide lines when reading "show guides" option but can't find any checkbox. To which precise part you talk about?

I read your commit and I think we need to have same name for blend and preset menus. Those don't need to have any different setting and we need to be sure to have same settings in both menus AND not overwhelming CSS code.

**Comment by elstoc** [comment]
> Was thinking of new guide lines when reading "show guides" option but can't find any checkbox. To which precise part you talk about?

The new option that appears in the preset menu for distort modules to switch guide lines on /off.

Screenshot_2021-07-25_17-25-54

> I read your commit and I think we need to have same name for blend and preset menus.

That's fine. You could use "check-menu-item" or something.

**Comment by Nilvus** [comment]
> > Was thinking of new guide lines when reading "show guides" option but can't find any checkbox. To which precise part you talk about?
> 
> The new option that appears in the preset menu for distort modules to switch guide lines on /off.
> 
> Screenshot_2021-07-25_17-25-54

Oh, ok. This one should soon disappear anyway when following PR will be merged: #9495
Anyway, it's safer to set a specific name.

> > I read your commit and I think we need to have same name for blend and preset menus.
> 
> That's fine. You could use "check-menu-item" or something.

So I understand that I could implement directly your code in my PR.

**Comment by elstoc** [comment]
> I could implement directly your code in my PR

Sure. Just change the name to whatever you like.

**Comment by TurboGit** [comment]
I agree that without the box being visible it looks cleaner.

**Comment by Nilvus** [comment]
Should be good now for review.

**Review by elstoc — APPROVED** [review]
Works for me. Thanks @Nilvus.

**Review by johnny-bit — APPROVED** [review]
I temembered one thing - for presets and blending modes I initially wanted to use radio instead of check item but for some reason radio didn't display anything... so it only just now occured to me that it might've been some css shenenigans?

if we'd use radio instead of check for presets/blending and be able to controll check mark that would probably be a bit "cleaner" than check-menu-item in the long run?

However the style and code as-is looks good to me.

**Comment by elstoc** [comment]
Nah I think it's fine with a tick.

**Review by TurboGit — APPROVED** [review]
Thanks, looks better now.

**Pull request merged**
