### PR TITLE
 po/print layouts

### PR DESCRIPTION
**Pull request by TurboGit**
Allow multiple images on the print module.

This was something that was itching me since long time. I get this started.

What is working ?
- [x] draw box areas
- [x] resize/move box areas
- [x] display box areas on screen/page
- [x] export PDF with multiple areas
- [x] drag&drop images into box area from filmstrip
- [x] grid display
- [x] snap to grid  

The hardest part is done I suppose now but it remains quite some polishing:
- [x] highlight the control being selected/dragged
- [x] allow entering area pos with entry widget to adjust precisely
- [x]  allow to store the areas into the preset
- [x] check/fix that changing page size keeps the area in right places
- [x] make sure the box areas are not outside the print area (or possibly page to allow for border-less printing)

### CODE REVIEW

**Comment by TurboGit** [comment]
@Nilvus : I'll need the full log as above there is nothing wrong displayed.

**Comment by TurboGit** [comment]
@Nilvus : of found an issue, a new file was missing in my patch-set.

**Comment by Nilvus** [comment]
Better, as I go some percent further. But not good. See what I have:
```

[ 51%] Building C object lib/darktable/plugins/lighttable/CMakeFiles/module_toolbox.dir/tools/module_toolbox.c.o
[ 51%] Building C object lib/darktable/plugins/lighttable/CMakeFiles/global_toolbox.dir/tools/global_toolbox.c.o
[ 51%] Building C object lib/darktable/plugins/lighttable/CMakeFiles/timeline.dir/tools/timeline.c.o
[ 51%] Building C object lib/darktable/plugins/lighttable/CMakeFiles/location.dir/location.c.o
[ 51%] Building C object lib/darktable/plugins/lighttable/CMakeFiles/filmstrip.dir/tools/filmstrip.c.o
[ 52%] Building C object lib/darktable/plugins/lighttable/CMakeFiles/view_toolbox.dir/tools/view_toolbox.c.o
[ 52%] Building C object lib/darktable/plugins/lighttable/CMakeFiles/image.dir/image.c.o
[ 52%] Building C object lib/darktable/plugins/lighttable/CMakeFiles/ioporder.dir/ioporder.c.o
[ 52%] Building C object lib/darktable/plugins/lighttable/CMakeFiles/snapshots.dir/snapshots.c.o
[ 53%] Building C object lib/darktable/plugins/lighttable/CMakeFiles/metadata.dir/metadata.c.o
[ 53%] Building C object lib/darktable/plugins/lighttable/CMakeFiles/collect.dir/collect.c.o
/home/nilvus/Projets/dttg/src/libs/print_settings.c: In function ‘button_released’:
/home/nilvus/Projets/dttg/src/libs/print_settings.c:1553:39: error: ‘true’ undeclared (first use in this function)
 1553 |     gtk_widget_set_sensitive(ps->del, true);
      |                                       ^~~~
compilation terminated due to -Wfatal-errors.
gmake[2]: *** [lib/darktable/plugins/lighttable/CMakeFiles/print_settings.dir/build.make:82 : lib/darktable/plugins/lighttable/CMakeFiles/print_settings.dir/print_settings.c.o] Erreur 1
gmake[1]: *** [CMakeFiles/Makefile2:3014 : lib/darktable/plugins/lighttable/CMakeFiles/print_settings.dir/all] Erreur 2
gmake[1]: *** Attente des tâches non terminées....
[ 53%] Linking C shared module libfilmstrip.so
[ 53%] Linking C shared module libview_toolbox.so
[ 53%] Linking C shared module libmodule_toolbox.so
[ 53%] Linking C shared module libioporder.so
[ 53%] Linking C shared module libsnapshots.so
[ 53%] Linking C shared module libglobal_toolbox.so
[ 53%] Linking C shared module liblocation.so
[ 53%] Linking C shared module libimage.so
[ 53%] Built target module_toolbox
[ 53%] Built target filmstrip
[ 53%] Built target view_toolbox
[ 54%] Linking C shared module libmetadata.so
[ 54%] Built target ioporder
[ 54%] Built target global_toolbox
[ 54%] Built target location
[ 54%] Built target image
[ 54%] Built target snapshots
[ 54%] Built target metadata
[ 54%] Linking C shared module libtimeline.so
[ 54%] Built target timeline
[ 54%] Linking C shared module libcollect.so
[ 54%] Built target collect
gmake: *** [Makefile:171 : all] Erreur 2
```

If you need more, just ask for it!

**Comment by TurboGit** [comment]
@Nilvus : try again :)

**Comment by Nilvus** [comment]
@TurboGit: all good now. Thanks. Testing now!

**Comment by Nilvus** [comment]
Some first feedback:

- It's not possible to change height and length size at the same time. And so, box area doesn't fit always image (and on what I understand, one box area = one image). So would be good to have 2 things:
    - possibility to have box area always fit the image
    - so when changing box size in diagonal (height and length at same time), all box (height and length) should update at same time
- I spent some time (about 1 to 2 minutes) to find where those new options were hidden. I find the "auto-fit" option not intuitive. On what I understand, auto-fit check is just for one image and so auto-fit it on the page. And uncheck allow to show and add more images. If so, I suggest to simply invert that checkbox and so rename to something like: "add multiple images" here. By checking this box, the multiples area images will appear and uncheck will hide that and auto-fit the main image.
- some tooltips are needed, especially in "new image area" to explain how it works ("create new image area then drag and drop an image from filmstrip on it. then move/resize image area where you want" ; or something like that)/ Probably more needed but this is first thoughts.

Thanks for working on that. I don't often use multiple images on same pages, but already used it sometimes. And it's great to see that on darktable and avoid using another software.

**Comment by TurboGit** [comment]
@Nilvus : I agree with all your points. There is still quite some work to do.

Just to be clear, first point is that you want to change box size by keeping the aspect ratio, right? If so this is planned.

**Comment by TurboGit** [comment]
The latest version is a bit better in many respects even is there is still some bugs and missing tooltips.

**Comment by TurboGit** [comment]
@Nilvus : Not anymore a wip PR you can test again. I have reworked a lot the GUI and there is no more a specific auto-fit mode now than the new code to handle layout is stable and fully functional and so used for all modes. Anyway nothing urgent as this is for 3.8.

**Comment by Nilvus** [comment]
Thanks @TurboGit for that. I will test that ASAP. Just a thing: about guides you add, if I understand well, you set a color hardcoded. If I'm not wrong, why not use actual guide options (colors, etc.) and especially link that to #8891 PR from @AlicVB? That would be more consistent.

**Comment by AlicVB** [comment]
well, not sure : here we want the grid to be mostly visible on a blank background, while on image, you want it to be visible on a "darker" background. Not to speak that here, contrary to images, the distractions is not so an issue !
that said, maybe we can come with a "color" setting per view...

**Comment by TurboGit** [comment]
@Nilvus : As @AlicVB replied this is because we always have a blank/grey page and so want the line to be visible. And since the colors are known for the page we can select the more visible color. So not sure we want to have this configurable but we may want to adjust of course. This is just a first implementation.

**Comment by johnny-bit** [comment]
Would you say that this essentially fixes #6562?

**Comment by TurboGit** [comment]
> Would you say that this essentially fixes #6562?

Yes, except for the support of multiple sheet. But this is not for the print module. Maybe will have a specific module supporting multiple sheet to create books.

**Comment by TurboGit** [comment]
@all, feel free to start testing as I'd like to merge this sooner than later.

**Comment by johnny-bit** [comment]
I've been testing it for a bit and I see couple things off that would be nice to "correct" (in no particular order)

- Initially the numbers display above the initial area is sliced in half because it exceeds the view area - wouldn't putting the numbers inside the area like crop module be "better" visually?
  - Also - the numbers: what do they mean?
- When clicking "new image area" nothing happens and no indication that user ought to click on the "canvas" - changing the cursor image to "+" sign might be good indication (if possible)
- when placing boxes one inside anoter you can't move "selected" area but the one that has the priority (seems like - it's order of adding areas tothe canvas)
- similar thing is with images inside areas - they can be displayed one on top of another, but their order is in their adding order... so if you first add couple image areas and then couple images in different order than areas, you can place image that obstructs another image, but it's area wouldn't obstruct other image area...
- i've got very accustomed to the notion that right click removes items in masks - i thought that would be the case with images/areas but it's only possible via delete image area
- you cannot "clear" image area. once image area has image, you can only replace the image inside area with another image.
- the module clearly hates thin side panels ;)
- the "current unit" combo has no label
- resizing image area doesn't keep constant AR when resizing with the square in the area corner
- speaking of resizing/moving - changing cursor as is seen in crop module would be great ;)
- when trying to move image area outside of the canvas - it's getting progressively smaller and smaller till it reaches 0 in some dimmension
- when trying to open up print view without image selected, there's an error "no image to open" and print view stays selected in views menu (so if you do select image you have to first go to different view first to be able to go with print later)
- there's just one grid, is red. would you consider adding other "overlay" grids, like eg the ones in crop module?

I think that's all for small testing...

**Comment by TurboGit** [comment]
Thanks a lot ! Quite a bit of work to do :)

**Comment by TurboGit** [comment]
I cannot reproduce 9. You can reproduce 12 on master, so will not be fixed in this PR.

Now implemented : 2, 5, 6, 10.

All numbers are using the unit as selected in the dialog. This is true for the margin and also the position of the box.

Point 8, indeed there has never been a label since first module implementation. The label seems quite superfluous to be with the combo having values (mm, cm, inch). But clearly this is not new.

For point 13 I don't think we want that. This is not a composition mode, you cannot change the crop or rotate here. The grid is only to help aligning the images and placing them on the page at the proper location.

**Comment by johnny-bit** [comment]
re1 is really weird:
Zrzut ekranu z 2021-06-29 16-13-01
that's why I suggested putting numbers in the area centre. And regarding context of point 8 - since numbers are using the units, and it's dynamic number - printing units there would be imo great :) would help understand a bit more about the numbers ;)

re3&4 - it would be better if images followed "priority" of areas so if area is "on top" so should be the area image. So in terms of "layering" it, you could sometime in the future allow reordering. But that's probably getting too much into minute detail...
re 8: tooltips and other stuff refers to it and I was at first confused with the lack of label... I'd put it just for completness sake, but if people using it are not complaining then I'm ok... still - noting it :)
re 9: I should've done screencast of that :/ it "tries" to keep AR but manages to get out of ar of initial image. try resize up/down couple times - at some point it won't be the same as the image inside (despite being the same at the start)
re 12: sure, but it looks off when you don't have to have single image selected. But it's fine as is.
re 13: true, but maaaaybe one would want to arrange images according to defined grids? anyway it's fine

**Comment by TurboGit** [comment]
3 and 4 done.

You can select an area even when fully inside another one. The selected box corresponds to the one with a control closest to current mouse position.

Using middle click or ctrl+click it is possible to move a picture below another one.

**Comment by TurboGit** [comment]
@johnny-bit  : For 1 : I keep the data on top to avoid having them over the image (better readability over white page) and put it on the center if there is not enough space on top. Let me know how it feels for you.

**Comment by TurboGit** [comment]
BTW, I think at this stage I have fixed all issues you reported expect 12 which should be part of another PR. Thanks for the review!

**Comment by johnny-bit** [comment]
Yep - tested and confirmed all:)

However... point 9 stands AFAIK. here's the vid:

https://user-images.githubusercontent.com/10687765/123933514-be887a80-d992-11eb-8ac5-3d9e5f468404.mp4

So - when starting image area has tiny space above/below image (so it's taller than image) and then rezising down - it gets wider than taller... and when resizing back up it gets taller than wider. That's wat I meant by not keeping AR.

While I don't think it's a big issue in any case it's still a bit surprising.

**Comment by TurboGit** [comment]
@johnny-bit : Ok,  thanks for the video, should be fixed now.

**Comment by johnny-bit** [comment]
Yep, Point 9 fixed :)

However... the point 11 is still interesting - the area shrinks when moved right or down, but not when moved up or left.

https://user-images.githubusercontent.com/10687765/123944287-47a4af00-d99d-11eb-8719-ba7d399c45b5.mp4

And I think that would be it for my testing :)

**Comment by TurboGit** [comment]
@johnny-bit : point 9 should be fixed now. Thanks for the review.

**Comment by johnny-bit** [comment]
I now consider all of the issues raised by me here as fixed :) thanks!

**Comment by TurboGit** [comment]
Manually merged.

**Comment by elstoc** [comment]
@TurboGit would you mind proposing some documentation for this please as it's not a view I really know much about. TIA

**Comment by TurboGit** [comment]
@elstoc : sure will do.

**Pull request closed without merging**
