### PR TITLE
metadata_view:  add default button to prefs dialog

### PR DESCRIPTION
**Pull request by phweyland**
to make it consistent with metadata module.

### CODE REVIEW

**Comment by TurboGit** [comment]
Well... You'll say I'm not clear... Maybe :) But in this case I find the use of reset-button ok as it actually change the display of the view at the same level. All the metadata are visible by clicking the reset button. I agree that it also change the status of an sub level dialog but it does change the view at the same level. In this case I would keep the reset button and will keep the reset also into the dialog. I do have a very limited number of metadata displayed (a preset) and I do use the reset-button to display all of them when needed and then back to the preset.

**Comment by johnny-bit** [comment]
Please, do not remove gui_reset. It's VERY convenient and makes sense there.

**Comment by phweyland** [comment]
I'll put the reset back :smiley:

**Comment by phweyland** [comment]
Reset is back ! :smiley:

**Review by TurboGit — APPROVED** [review]
All good to me now, thanks!

**Comment by TurboGit** [comment]
I have also made the pref dialog higher as there is lot of rows displayed and so there is now less scrolling.

**Pull request merged**
