### PR TITLE
channelmixerrgb: declare cat on pipe when processing

### LINKED ISSUE #8371: "double CAT" not shown when changing image in darkroom
**Describe the bug**
When a CAT is selected in two Color Calibration modules, the "double CAT" warning and the red triangle in module header is shown when opening the image from lighttable, but it is not when switching to the same image while in darkroom

**To Reproduce**

1. Start with a test folder with one image, create a duplicate
2. For the duplicate, create a second instance of color calibration and intentionally apply a second CAT. The red warning sign will appear
3. Go back to lighttable, open the second image, the red sign is shown correctly in the header of the second color calibration module
4. Now, while in darkroom, go back and forth between the first and the second image using the filmstrip
5. When switching to the second image, the red sign will flash briefly and then disappear
6. Also clicking the header to the second color calibration model to expand it will not show the warning. It takes clicking to the first module and back to the second to make the warning come back

**Expected behavior**
The warning is shown in the second module in all circumstances

**Screenshots**

When changing image in darkroom
image

When opening from lighttable
image

**Platform (please complete the following information):**
 - Darktable Version: git master
 - OS: Both Windows 10 and Linux
 - OpenCL activated
 - nVidia 1060

### PR DESCRIPTION
**Pull request by elstoc**
Resolves #8371

### CODE REVIEW

**Comment by elstoc** [comment]
@aurelienpierre this seems to fix the issue and I can't see any side-effects. Please can you review.

**Comment by Mark-64** [comment]
works for me, thanks

**Review by TurboGit — APPROVED** [review]
Looks ok, I'll let @aurelienpierre validate and merge.

**Comment by aurelienpierre** [comment]
It's harmless anyway. Thanks !

**Pull request merged**
