### PR TITLE
OpenCL kernel compilation does multiple runs if building failed

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
There were some flaws in the design of `dt_opencl_build_program()` leading to incorrect returns of an error condition.

1. Refactored, somewhat less verbose in normal `-d opencl` run.
2. Each kernel allows up to 5 runs for compilation.

@parafin and @MStraeten could you check if this helps for the mac compilation problems?

### CODE REVIEW

**Comment by MStraeten** [comment]
i haven't encountered kernel compilation issues with my m1 and also with the intel mac since a longer time - maybe macos13 fixed something ...
all kernels are compiled without issues

**Comment by TurboGit** [comment]
> 2\. Each kernel allows up to 5 runs for compilation.

I'm not sure about this. It probably does not hurt if it is compiled ok first time, but what is the point? I have not seen report about compilation issue. Did I missed some report?

**Comment by jenshannoschwalm** [comment]
> Did I missed some report?

I think parafin had mentioned this but is that's gone, not problem and i'll close.

**Comment by MStraeten** [comment]
Just because it’s not on my MacBooks with latest macOS version doesn’t imply that there aren’t older configurations showing that behaviour…
Latest reference to my issue was about Oct 22 and macos12 so the fix might be relevant for others …

**Comment by parafin** [comment]
I didn’t test, but I doubt it will help. My feeling is that retrying fails until the whole dt process is restarted (or at least OpenCL runtime is somehow fully cleanly reloaded). So most likely with this change it will just take longer to fail the same way.

**Comment by leanderhutton** [comment]
Same here no issue on macOS 13. I can test on my older box at the house if needed.

**Comment by jenshannoschwalm** [comment]
Thanks for feedback. As this issue seems to be fixed elsewhere just closing this ...

**Pull request closed without merging**
