### PR TITLE
vectorscope: fix visibility of primary sample

### PR DESCRIPTION
**Pull request by Mark-64**
With merge of #9866, in one of the last commits (fb08c346beeaa0134abc2a340020b152680510b4) I realized I broke the connection between the gui "restrict scope to selection" and the visualization of the primary sample dot in the vectorscope.
The result is that the primary sample is always visualized.
This is because `d->vectorscope_pt[0]` was used not only to store the x coordinate of the primary sample, but also to trigger the visualization on/off.
When I changed the calculation of primary sample coordinates, starting from the color conversion, this mechanism was overriden.
With this PR I replace the old mechanism with usage of  `darktable.lib->proxy.colorpicker.restrict_histogram` and `darktable.lib->proxy.colorpicker.primary_sample->size` for triggering the visualization, which is more clear.

### CODE REVIEW

**Comment by phweyland** [comment]
Rebased after 8441948

**Comment by TurboGit** [comment]
> With merge of #9866, in one of the last commits ([fb08c34](https://github.com/darktable-org/darktable/commit/fb08c346beeaa0134abc2a340020b152680510b4)) I realized I broke the connection between the gui "restrict scope to selection" and the visualization of the primary sample dot in the vectorscope.

On my side I thought it was a feature. Indeed the samples are the ones that have been explicitly added. Having the current color picker point being displayed seemed ok to me. No ?

**Comment by Mark-64** [comment]
> On my side I thought it was a feature. Indeed the samples are the ones that have been explicitly added. Having the current color picker point being displayed seemed ok to me. No ?

Well, that was not the intention of the original designer. In #9835, @dtorop set the primary sample visualized in vectorscope only when "restrict scope to selection" is enabled.
We can always rediscuss that, having it visualized at all times, or (as I would prefer) connect it to "display samples on image / vectorscope", as long as it is a conscious decision and not a bug...
So I suggest to fix the bug first and then we can always change the behavior.
Also consider that visualization of the primary sample is a bit more computationally expensive as it requires `dt_dev_invalidate()` to reprocess the vectorscope.

**Comment by TurboGit** [comment]
@Mark-64 : Fine by me but now even with the option selected to display the area on the scope there is nothing displayed.

**Review by TurboGit — CHANGES_REQUESTED** [review]
Something broken the other way around now.

**Comment by Mark-64** [comment]
Strange, it works perfectly for me in both Windows and Ubuntu.
Are you sure you checked "restrict scope to selection" ?
I known it sound counterintuitive, but "display samples on image/vectorscope" is only to show the live samples, not the primary one.

**Review by TurboGit — APPROVED** [review]
Ok, quite non-intuitive indeed ! Let's go with that now, but we will probably want to rework this part!

**Comment by Mark-64** [comment]
Ok, thanks.
I can open an issue to rework this, so we can discuss

**Pull request merged**
