### PR TITLE
better alignement of duplicates & fix navigation lib when snapshot active

### PR DESCRIPTION
**Pull request by TurboGit**
Rework duplicate display with newly added darkroom like dev pipe. This ensure proper alignment.

It has also been able to do a large clean-up.

@AlicVB : Can you have a look? TIA.

This latest version, after some code refactoring, also share code with the snapshots lib.

### CODE REVIEW

**Comment by elstoc** [comment]
Please could you update the title with a more detailed description. I'll try to test this evening.

**Comment by elstoc** [comment]
Quick drive-by testing with a spare five minutes again, but I think there's some regression of the snapshot functionality here. Even on a basic edit with only the default modules the performance is worse than master when zooming and panning. Both feel quite jerky and unresponsive. When panning it looks like there is a brief offset update of the snapshot side before it then updates and aligns correctly.

**Comment by TurboGit** [comment]
> Even on a basic edit with only the default modules the performance is worse than master when zooming and panning.

I cannot reproduce this.

> When panning it looks like there is a brief offset update of the snapshot side before it then updates and aligns correctly.

I can reproduce this. I'll see if I can fix it, it is a side effect of the context check change I did.

**Comment by TurboGit** [comment]
> When panning it looks like there is a brief offset update of the snapshot side before it then updates and aligns correctly.

This is now fixed.

**Comment by elstoc** [comment]
> I cannot reproduce this

Hmm I don't know what to do with this. I've tried building both master and this PR in the same environment and examined with the same image. The difference is noticeable for me.

**Comment by TurboGit** [comment]
@elstoc : I have pushed an attempt to fix the slow/jerky refresh. Can you test?

**Comment by TurboGit** [comment]
@elstoc : In the latest version just pushed I believe I have fixed both issues.

**Comment by TurboGit** [comment]
@elstoc : I can't reproduce, maybe because the computer is slower than mine. Do you reproduce this failing update on master?

**Comment by TurboGit** [comment]
@elstoc : I'll merge tomorrow if ok to you to gain more field testing. I really don't want this to land at the last minute.

**Comment by elstoc** [comment]
> Do you reproduce this failing update on master?

No

> maybe because the computer is slower than mine

Maybe. 11th gen i5 with 16GB ram and an 8GB Nvidia 1080 GPU.

**Comment by TurboGit** [comment]
> Maybe. 11th gen i5 with 16GB ram and an 8GB Nvidia 1080 GPU.

Yes, mine is Intel® Core™ i9-9980HK × 16 - 16GB ram and a Quadro T1000.

**Comment by elstoc** [comment]
You could try turning off opencl

**Comment by TurboGit** [comment]
> You could try turning off opencl

All good on my side with OpenCL off, it is much slower but I have not been able to trigger a display issue by zooming/panning.

**Comment by TurboGit** [comment]
Ok let's bit the bullet and see if somebody else can reproduce and provide a way to reproduce.

@elstoc : Thanks for all the testing as usual!

**Pull request merged**
