### PR TITLE
Highlights reconstruction bugfix and code cleanup

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
While again investigating a known issue (i finally could an issue looking slightly as reported in #12913) i

1. did a code cleanup splitting main file into algo specific files for readability and improved maintenance
2. made ` float dt_image_distance_transform()` available for other modules
3. fixed the old clip code both in cpu and gpu code to make sure there a no NaN in the pipe
4. cleaned & fixed the `tiling_callback` code
5. fixed the roi_in changing code to be independent of pixelpipe
6. BUGFIXED the mask visualizing code for the cpu path. That was clearly a bug as it could possibly coud read/write out-of-legal-bounds data.
7. Some reformatting to agreed code style

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
@MStraeten another try on the old-and-bad stuff?

**Comment by jenshannoschwalm** [comment]
Release note maybe: Fixed the highlights overexposed mask visualizing

**Comment by MStraeten** [comment]
remains strange ...

https://user-images.githubusercontent.com/39386816/227760837-ada39569-ef60-4a06-ac7c-93a78b472f5e.mp4


https://user-images.githubusercontent.com/39386816/227760843-ad226409-4313-4f1d-b3f6-3b38f5b7507a.mp4

[IMG_6158.CR3.xmp](https://mega.nz/file/fSwgSS6C#ZP4CxcmwXncrFOfkUgmlwhqhzYUVlMc8UBP6rR3-ADE)
[IMG_6158.CR3](https://mega.nz/file/jXxA2ZZK#gJzBfQuaug__6Ik8gXSOWvp_f-J1m8x3u2w_1fEYuJE)

**Comment by jenshannoschwalm** [comment]
> remains strange ...

Indeed :-( Nevertheless another fixed bug in another part of the code ...

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Pull request merged**
