### PR TITLE
Keep modules in place or fully visible when opening or expanding

### LINKED ISSUE #12087: Improvement: Update module vertical position upon expanding "mask" section
**Is your feature request related to a problem? Please describe.**
When opening a module, its vertical position is updated so that module makes ideal use of the available vertical space:

Here, "denoise" is about 3/4 down the list (left image) but after clicking on it, it is moved up to the top to display as much content as possible (green arrow, right image)
image image

However, the position is not recalculated the same way when a module needs more space by e.g. expanding the mask section:

Left image: before clicking on "drawn mask". Right image: after expanding "drawn mask". The position of the exposure module is not updated and moved to the top of the list. So only limited space (green arrow) is available for the module.

image image

**Describe the solution you'd like**
If the size of a module changes (grows or shrinks), the position of it should be updated so that available space is used as efficiently as possible and that manual scrolling is avoided.

Here: ideal location of "exposure" module after clicking on "drawn mask"
image

**Additional context**
I don't think that it makes a difference but I use these settings:
*  "only expand one module at a time"
* display-referred workflow

### PR DESCRIPTION
**Pull request by dterrahe**
When you open a module by clicking on its header, or when you expand it, by opening a collapsible section or adding a mask type, it can end up being partly obscured; at the bottom when it is too large or at the top if simultaneously another module above it was closed (because of "expand a single processing module at a time" or because shift was held). The latter also often unnecessarily causes the module to jump.

This PR solves both issues. It keeps the header at the same location, when possible, unless the module needs more space, in which case it moves it upward.

The move can be made smoothly, as well as the opening (and closing) itself, also of collapsible sections, using the same technique as #11408 (thanks @Sacules for the idea). The speed of the smooth transitions and scrolls can be configured in preferences/misc/duration of ui transitions, all the way down to 0/instantaneous/normal/as before. With smooth moves it easier to see where the module ended up, but there can be bit of flickering when simultaneously closing another module.

This also "fixes" a bug in master where "scroll processing modules to the top when expanded" would not work if the total height of all modules did not change when switching between two of them, i.e. if they had the same height, like, for example, multiple instances of the same module.

But tbh I wonder if "scroll to top" is as useful as it was before, since this already "guarantees" you'll be able to see the whole module (unless of course you are trying to draw a parametric mask for colorbalance rgb).

Feedback welcome!

Fixes #12087

### CODE REVIEW

**Comment by dterrahe** [comment]
A remaining existing issue that I'm trying to fix, is that if you have "expand a single processing module at a time" and you expand a module _below_ the currently expanded one, the previous one will collapse, dragging the "new" one upwards. If the old one was very large and all the way up out of sight, the new module might even disappear as well (if you have a long list, say all modules).

This PR makes the situation _slightly_ less bad, because at least you can somewhat see the direction it disappeared in because of the transitioning, but it is still inconvenient.

Fixing this, by moving the whole list down, is tricky because it has to be done continuously while the closing module is slowly collapsing and the new module might _have_ to move upward a little if it doesn't completely fit at the bottom.

**Comment by dterrahe** [comment]
I pushed a fix for the issue I mentioned above. It keeps the header of the opening module in its place (under the mouse cursor) even if at the same time there is a module collapsing above it (which normally would cause it to scroll up). Except, logically, when there are not enough modules above it to keep it scrolled down, or when the module is too large to fit so it is moved up intentionally.

If you have transitioning switched on there is some annoying jittering while the lower module is fighting to not get scrolled up while the other one is closing.

**Comment by TurboGit** [comment]
One point to enhance: 

- When you open a blend section, the module move up to make the whole section visible (which is working ok).
- When you close the blend section by clicking on the same button the module will move down to be back on its what seems to its original location.

I would expect the module to not move when closing a section, this will avoid an unneeded move.

If possible I would also make the opening/closing of the blend section smooth. No big deal if not possible in this PR or not possible at all. Just a consistency UI behavior that could be nice to have. Thoughts?

**Comment by dterrahe** [comment]
> * When you close the blend section by clicking on the same button the module will move down

This only happens when there are not enough modules below it to fill the space. Gtk Scrollable Windows don't allow you to scroll the content further up if there's a gap below it.

Similarly, if you have a module open near the top and then expand another module below it (and have "expand a single..."), we might not be able to prevent the new one from being dragged upwards, if there's not enough "filler" above it.

> I would also make the opening/closing of the blend section smooth.

I was thinking of that, but worried that replacing all of those show/hides with revealers might cause problems with shortcuts to their content no longer working because of the extra layer in between (I now realised that I hadn't checked if this PR broke shortcuts to the content of collapsible sections! But it seems like they are OK). Also, everywhere else where some parts are shown or hidden based on a combobox selection, for example, we also use show/hide, so those are all instantaneous (and too much work to change and bugfix). But now that I think of it again, I agree with you that definitely mask sections are worth looking into transitioning. Haven't examined that code at all yet, so let's see. Two or three sections could be expanding at the same time (blend+drawn+parametric) so that could look "interesting" (but probably ok).

Thanks for testing this!

**Comment by dterrahe** [comment]
Added revealers to the blending boxes with a bit of refactoring (of which more could be done) and little testing (idem).

**Review by TurboGit — APPROVED** [review]
Works ok for me! A nice UI improvement. Thanks.

I'll let some more days before merging to be sure it is tested by others. I'm thinking about @Nilvus especially.

**Comment by dterrahe** [comment]
It would be useful to get feedback on the default speed as well. 250ms may be "too slow" already. 150ms would be just noticeable and then people could decide to switch it off or increase. Or it could be switched off by default, but then many would never realise the feature was added.  Nilvus may have an opinion?

**Comment by Nilvus** [comment]
Really nice UI improvement. Thanks @dterrahe. This makes the UI smoother (I would not put that faster. This could even be smoother by putting 400ms (or 350ms) but 250ms seems a good default setting).

So, I'm totally on for letting that active by default with 250ms setting.

**Review by Nilvus — APPROVED** [review]

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by dterrahe** [comment]
Sorry!! Initially this didn't have any configuration aspects to it that needed documenting, but then that was added later...

**Pull request merged**
