### PR TITLE
Spanish translation update

### PR DESCRIPTION
**Pull request by EdgarLux**
Updated latest new strings.

### CODE REVIEW

**Comment by TurboGit** [comment]
Thanks!

**Comment by EdgarLux** [comment]
> Thanks!

Thanks to you too! Apropos, I noticed that in the past pre-releases the Spanish language is not listed. I'm missing something? Do I have to do something else?

**Comment by TurboGit** [comment]
No just that I did not updated the release-notes translator sections properly. Fixed.

**Comment by EdgarLux** [comment]
> No just that I did not updated the release-notes translator sections properly. Fixed.
Thank you!

**Pull request merged**
