### PR TITLE
Transition negadoctor, colorbalance and retouch to introspection framework

### PR DESCRIPTION
**Pull request by dterrahe**
with corresponding cleanup
add basic support for array fields to dt_bauhaus_slider_from_params

also add option for notebook tabs to colorbalance to make full module fit on screen

### CODE REVIEW

**Comment by TurboGit** [comment]
@dterrahe : testing this, all seems good, I don't see the tab in colorbalance as described in your comment? Was this removed?

**Comment by dterrahe** [comment]
In colorbalance, tabs can be used instead of section labels by setting
`plugins/darkroom/colorbalance/use_notebook=TRUE`
in darktablerc

**Comment by dterrahe** [comment]
> Thanks ! Not sure I would use the tab version though.

I wouldn't either, but I thought it could be useful for people with low resolution screens or who need larger font sizes. Color balance is a _huge_ (vertically) module.

Also, as you can see, it was very easy to add, so nice to give people the option. But no need to add a configuration option in settings, as it is so niche.

**Comment by johnny-bit** [comment]
as for niche setting - can you add it somewhere in wiki as a trick in order to get color balance to be "smaller" module? it's cool exactly for reasons you mention!

**Comment by MStraeten** [comment]
This pr causes a crash on OSX when opening a raw file in darkroom:

lldb output:
```
Process 91388 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fff6983233a libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill:
->  0x7fff6983233a <+10>: jae    0x7fff69832344            ; <+20>
    0x7fff6983233c <+12>: movq   %rax, %rdi
    0x7fff6983233f <+15>: jmp    0x7fff6982c629            ; cerror_nocancel
    0x7fff69832344 <+20>: retq
Target 0: (darktable) stopped.
(lldb) thread backtrace
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff6983233a libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff698eee60 libsystem_pthread.dylib`pthread_kill + 430
    frame #2: 0x00007fff697b98a2 libsystem_c.dylib`__abort + 139
    frame #3: 0x00007fff69793d7b libsystem_c.dylib`__stack_chk_fail + 100
    frame #4: 0x000000010020c7ff libdarktable.dylib`dt_bauhaus_slider_from_params(self=<unavailable>, param=<unavailable>) at imageop_gui.c:0:3 [opt]
    frame #5: 0x0000000119608f99 libfilmicrgb.so`gui_init(self=0x000000010ad40800) at filmicrgb.c:2381:41 [opt]
    frame #6: 0x000000011894a5b6 libdarkroom.so`enter(self=0x00000001179081f0) at darkroom.c:2800:7 [opt]
    frame #7: 0x00000001002bb885 libdarktable.dylib`dt_view_manager_switch_by_view(vm=<unavailable>, nv=0x00000001179081f0) at view.c:451:23 [opt]
    frame #8: 0x000000010027d662 libdarktable.dylib`_event_button_press(widget=<unavailable>, event=0x0000000109e48710, user_data=0x000000010a080f00) at thumbtable.c:953:5 [opt]
    frame #9: 0x0000000100947162 libgtk-3.0.dylib`_gtk_marshal_BOOLEAN__BOXED + 97
    frame #10: 0x00000001010de29f libgobject-2.0.0.dylib`g_closure_invoke + 192
    frame #11: 0x00000001010f171b libgobject-2.0.0.dylib`signal_emit_unlocked_R + 2315
    frame #12: 0x00000001010f20f0 libgobject-2.0.0.dylib`g_signal_emit_valist + 1882
    frame #13: 0x00000001010f277c libgobject-2.0.0.dylib`g_signal_emit + 120
    frame #14: 0x000000010090aba0 libgtk-3.0.dylib`gtk_widget_event_internal + 253
    frame #15: 0x00000001007ecdc0 libgtk-3.0.dylib`propagate_event + 364
    frame #16: 0x00000001007ec19a libgtk-3.0.dylib`gtk_main_do_event + 958
    frame #17: 0x0000000100d4d1e1 libgdk-3.0.dylib`_gdk_event_emit + 49
    frame #18: 0x0000000100d7257a libgdk-3.0.dylib`gdk_event_dispatch + 50
    frame #19: 0x00000001005a0e8b libglib-2.0.0.dylib`g_main_context_dispatch + 258
    frame #20: 0x00000001005a1186 libglib-2.0.0.dylib`g_main_context_iterate + 426
    frame #21: 0x00000001005a13b7 libglib-2.0.0.dylib`g_main_loop_run + 191
    frame #22: 0x00000001007ebca8 libgtk-3.0.dylib`gtk_main + 74
    frame #23: 0x000000010028bfaa libdarktable.dylib`dt_gui_gtk_run(gui=<unavailable>) at gtk.c:1473:3 [opt]
    frame #24: 0x000000010000cf4e darktable`main(argc=<unavailable>, argv=<unavailable>) at main.c:93:3 [opt]
    frame #25: 0x00007fff696eacc9 libdyld.dylib`start + 1
    frame #26: 0x00007fff696eacc9 libdyld.dylib`start + 1
```

**Comment by dterrahe** [comment]
Looking into it. That PR didn't touch filmicrgb, but it is of course possible that the stack got messed up in the gui_init of a previous module. But just to be sure, because cross platform debugging is a challenge anyway, have you definitely traced this crash back to this PR? (bisect or otherwise)

Are you aware of any differences between OSX and linux/Windows that could have an impact on stack use that I should be aware of?

Many thanks!

**Comment by MStraeten** [comment]
`git checkout ab65074169d518f527a600e98d291b50bbce506c` was the last commit that is fine; `git checkout c60835e4fccf88599127bcc1cc2d8185b55b0799` causes the crash

**Comment by dterrahe** [comment]
That commit doesn't seem to be in this PR though (and looks trivial/innocuous). Did bisect not drill down into individual commits?

**Comment by MStraeten** [comment]
sorry checked it, wrong line copied: it was: `git checkout dbf422a48408df11cdfbd7227381d88a9d5ad55d`

**Comment by MStraeten** [comment]
crash is not reproducible with my current windows compilation.

**Comment by dterrahe** [comment]
Doesn't bisect drill into the individual commits within the PR? None of them look suspicious to me, but...

The patch hasn't caused problems for me under linux or windows. I've now recompiled under linux using clang 10.0 and that's also fine.

Have you tried opencl on/off on OSX? I'm not sure what else I can do to debug.

**Comment by dterrahe** [comment]
> can you add it somewhere in wiki as a trick in order to get color balance to be "smaller" module? 

@johnny-bit The logical place for it would be the "User's Portal" on the wiki, but since that is currently completely empty, I'm hesitant to give it much more prominence than it deserves...

**Comment by MStraeten** [comment]
i don't have an idea how to bisect something - i'm not used to development stuff ... just as an user of build instructions and sometimes trying stuff i was told ;)

the crash occurs with and without opencl beeing activated

**Comment by dterrahe** [comment]
@parafin would you be able to help to confirm this crash and possibly bisect to an individual commit within the PR?

**Comment by MStraeten** [comment]
after a tutorial on bisecting i tried: 
selecting ab65074169d518f527a600e98d291b50bbce506c as good and dbf422a48408df11cdfbd7227381d88a9d5ad55d as bad.
after a few steps with bad results i got:

```
533e9a326785084f153556b624447e4eb4e11ff0 is the first bad commit
commit 533e9a326785084f153556b624447e4eb4e11ff0
Author: Diederik ter Rahe <dterrahe@yahoo.com>
Date:   Wed Jul 1 17:33:24 2020 +0100

    support simple arrays in dt_bauhaus_slider_from_params

 src/develop/imageop_gui.c | 19 ++++++++++++++++---
 1 file changed, 16 insertions(+), 3 deletions(-)
```

and lldb tells me:
```
Process 5936 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fff6983233a libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill:
->  0x7fff6983233a <+10>: jae    0x7fff69832344            ; <+20>
    0x7fff6983233c <+12>: movq   %rax, %rdi
    0x7fff6983233f <+15>: jmp    0x7fff6982c629            ; cerror_nocancel
    0x7fff69832344 <+20>: retq
Target 0: (darktable) stopped.
(lldb) thread backtrace
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff6983233a libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff698eee60 libsystem_pthread.dylib`pthread_kill + 430
    frame #2: 0x00007fff697b98a2 libsystem_c.dylib`__abort + 139
    frame #3: 0x00007fff69793d7b libsystem_c.dylib`__stack_chk_fail + 100
    frame #4: 0x000000010023513d libdarktable.dylib`dt_bauhaus_slider_from_params + 1229
    frame #5: 0x000000011bb90f4c libfilmicrgb.so`gui_init + 1548
    frame #6: 0x000000011afd6516 libdarkroom.so`enter + 470
    frame #7: 0x00000001002f8896 libdarktable.dylib`dt_view_manager_switch_by_view + 5462
    frame #8: 0x00000001002b0638 libdarktable.dylib`_event_button_press.llvm.6343411885686663692 + 264
    frame #9: 0x0000000100991162 libgtk-3.0.dylib`_gtk_marshal_BOOLEAN__BOXED + 97
    frame #10: 0x000000010112829f libgobject-2.0.0.dylib`g_closure_invoke + 192
    frame #11: 0x000000010113b71b libgobject-2.0.0.dylib`signal_emit_unlocked_R + 2315
    frame #12: 0x000000010113c0f0 libgobject-2.0.0.dylib`g_signal_emit_valist + 1882
    frame #13: 0x000000010113c77c libgobject-2.0.0.dylib`g_signal_emit + 120
    frame #14: 0x0000000100954ba0 libgtk-3.0.dylib`gtk_widget_event_internal + 253
    frame #15: 0x0000000100836dc0 libgtk-3.0.dylib`propagate_event + 364
    frame #16: 0x000000010083619a libgtk-3.0.dylib`gtk_main_do_event + 958
    frame #17: 0x0000000100d971e1 libgdk-3.0.dylib`_gdk_event_emit + 49
    frame #18: 0x0000000100dbc57a libgdk-3.0.dylib`gdk_event_dispatch + 50
    frame #19: 0x00000001005eae8b libglib-2.0.0.dylib`g_main_context_dispatch + 258
    frame #20: 0x00000001005eb186 libglib-2.0.0.dylib`g_main_context_iterate + 426
    frame #21: 0x00000001005eb3b7 libglib-2.0.0.dylib`g_main_loop_run + 191
    frame #22: 0x0000000100835ca8 libgtk-3.0.dylib`gtk_main + 74
    frame #23: 0x00000001002c2b8f libdarktable.dylib`dt_gui_gtk_run + 255
    frame #24: 0x000000010000cf4e darktable`main + 62
    frame #25: 0x00007fff696eacc9 libdyld.dylib`start + 1
    frame #26: 0x00007fff696eacc9 libdyld.dylib`start + 1
```

hope this is the right way to bisect ;)

**Comment by johnny-bit** [comment]
@MStraeten - bisect looks good :) I've added mini-bisect-tutorial here: https://github.com/darktable-org/darktable/wiki#finding-bug-causes

**Comment by codingdave** [comment]
533e9a326785084f153556b624447e4eb4e11ff0 is the first bad commit
commit 533e9a326785084f153556b624447e4eb4e11ff0
Author: Diederik ter Rahe <dterrahe@yahoo.com>
Date:   Wed Jul 1 17:33:24 2020 +0100

    support simple arrays in dt_bauhaus_slider_from_params

 src/develop/imageop_gui.c | 19 ++++++++++++++++---
 1 file changed, 16 insertions(+), 3 deletions(-)

I can confirm the findings of @MStraeten .

**Comment by dterrahe** [comment]
I'm a bit mystified how 533e9a3 on its own can cause a problem. It just supports calling dt_bauhaus_slider_from_params with an array parameter, but only the next commits start using that functionality. Maybe sscanf behaves differently on osx? 

Let's exclude that possibility by replacing the following line in imageop_gui.c
`if(sscanf(param, "%[^[][%d]", param_name, &param_index) == 2)`
with
`if(FALSE)`
 
Please let me know if it still crashes. Thanks!

**Comment by dterrahe** [comment]
@MStraeten @codingdave should be fixed in latest master. Please test, thanks!

**Comment by codingdave** [comment]
@dterrahe I can confirm that the reported issue is fixed with the latest commit

GSETTINGS_SCHEMA_DIR=/opt/local/share/glib-2.0/schemas/ XDG_DATA_DIRS=/opt/local/share darktable --version
this is darktable 3.3.0+86~g9ac7a0392
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.0.0
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

**Pull request merged**
