### PR TITLE
Add option to change darkroom background color around the image

### PR DESCRIPTION
**Pull request by cryptomilk**
This implements the suggestions from:

https://discuss.pixls.us/t/neutral-theme-for-darktable-and-gimp/9504/27

### CODE REVIEW

**Comment by TurboGit** [comment]
I'm not sure about this one. We don't have a single color option in the preference actually. And the solution is to change the CSS to setup a color. So can you clarify why this is needed here? Why not change from a CSS? I can't imagine a preference entry for every single configurable color :)

**Comment by cryptomilk** [comment]
The background color changes how you perceive the colors in the image. A darker background and your image is brighter, a white background and your image is less colorful. Depending what you are developing for you want to change that background color.

It would be better to have directly as a small button in the darkroom ui to switch it without requiring a restart or editing a file. However my darktable skills are not the best :-)

**Comment by aurelienpierre** [comment]
I have already thought about that, but I think it would be better to ship 2 or 3 different CSS templates (dark, neutral, light), and be able to select them from the preferences, rather than to hack just the background color value from the code. Last year, the hardcoded GTK colors were specifically removed from the source code.

**Comment by maf** [comment]
@cryptomilk thank you for this PR.

I opt for having the configuration in the CSS and choosing theme from UI. However making own theme or ability to modify exiting one using UI (like using GTK+ color picker) is in my opinion *must have*.

@TurboGit Why? Dakrtable falls into color critical category and sits in the color management workfow. This starts with environment preparation (walls, desktop, lightning and so on) and later with calibration and profiling of the devices. Thus one can have custom workplace with specific lightning and may need to adjust background accordingly.  I myself modified theme because I print. Scan the linked thread for details.

**Comment by TurboGit** [comment]
@maf : exactly what I said, it is so important than having preference for a single color is not a good solution. We can do that properly in CSS, or we need to provide a full preference tab to be able to change ALL colors.

**Comment by cryptomilk** [comment]
Closing as this needs to be implemented differently. I'm happy to work on this but I need a helping hand or some pair-programming.

**Pull request closed without merging**
