### PR TITLE
history_hash fix

### LINKED ISSUE #4400: Windows fragility
version 3.1.0_777~gbd7c89a0b-dirty, Windows 10, seems very fragile.
Crashes happen in very unpredictable ways... sometimes going to the darkroom, sometimes to the lighttable, sometimes on changing images, very often (but not always) on attempting to apply a style.

Sometimes the lock files are left active, sometimes not. Problems seem equally likely for any image, original or duplicate.

If I recover my DB from back-up and return to v708, all is well again.

So what should I look for in the -d log? It seems just to record ordinary daily life, then stops as though I'd closed the program.

### PR DESCRIPTION
**Pull request by phweyland**
- malloc size !!
- avoid ON CONFLICT where possible
- ~~make sqlite3 2.40 mandatory~~

Should fix #4400 - Sorry for all this time lost :(

### CODE REVIEW

**Comment by phweyland** [comment]
I've removed the constraint about sqlite version as I find this a bit harsh for those who cannot easily update sqlite.
I'll prepare another PR, making 2.15 mandatory, and providing a backup way for versions below 2.40.

**Comment by GrahamByrnes** [comment]
A massive thanks for sorting this. Will download and leave it to build while I'm at work...

**Comment by TurboGit** [comment]
Thanks !

**Comment by GrahamByrnes** [comment]
Works like a charm :-)

**Pull request merged**
