### PR TITLE
Getting rid of DT_DEBUG_IOPORDER

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Another residule of times with ioporder problems can go imho.
No bug involved, just code cleanup.

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
@Nilvus, thanks for reminding me about this old one :-)

**Review by TurboGit — COMMENTED** [review]
Maybe I misremember something, but why removing this? I mean iop-order is a tricky part of darktable and at any time we may want to check this for possible issue. No?

**Comment by jenshannoschwalm** [comment]
> I mean iop-order is a tricky part of darktable and at any time we may want to check this for possible issue. No?

ok, no problem. I can't remember such an issue since you did the proper fix with lists but so let's keep it until we run into a new issue and want this option.

**Comment by TurboGit** [comment]
I also cross the fingers to not have another iop-order issues. I have fixed a lot and this is not easy. But if another issue arise I'm sure those debug info will be really welcomed.

**Pull request closed without merging**
