### PR TITLE
Allow user to choose to keep delete button on last object in duplicate module

### LINKED ISSUE #4950: Add delete to duplicate manager for unduplicated files
It would be nice to be able to delete from the darkroom without having yet another keyboard short-cut I can't remember, or more buttons.

At present, if I create a duplicate image, each has a little "X" to delete inside the duplicate manager. It disappears once only one version is left.

Why not keep it? It would be a very lightweight way to add the delete function.

### PR DESCRIPTION
**Pull request by GrahamByrnes**
A very small PR: I'd like to be able to delete directly from dr, but the delete button disappears from the duplicate module once only a single image remains.
Since some might be nervous about this causing unintended deletions, it's enabled by a choice in the "security" section of prefs. The default is FALSE, ie current behaviour.

Would close #4950.

### CODE REVIEW

**Comment by TurboGit** [comment]
But when you delete the last duplicate what is remaining on the darkroom ? You have to switch to another picture either from filmstrip, but what if there is no more picture on the collection ? I kind of remember some corner cases not really easy to support that's why we have put this limitation to stay on the safe side.

**Comment by GrahamByrnes** [comment]
I just reminded my self:

- If there are other images on the filmstrip, the deleted image remains at the centre until you shift, then it is gone.
- If it is the only image, you are obliged to return to the lt, and then you find yourself with the same empty-folder display as if you had used "selected images" to remove it.

So those cases don't bother me more than they would in another view. 
It's really just an option for doing a cull within dr
"I tried that, I tried the other, no it's still crap, let's get rid of it and move on".

I could live without it. I could also live with the option hidden in the undisplayed darktablerc.
See what the crowd says?

**Comment by TurboGit** [comment]
Yes, but that being said the darkrroom handle edits and so clone. Removing the last is really removing the master RAW (or Jpeg) image and I really think this belongs to the lighttable and will avoid the mentioned issues. Frankly I'd prefer no doing that and closing this PR.

**Comment by Nilvus** [comment]
> I just reminded my self:
> 
>     * If there are other images on the filmstrip, the deleted image remains at the centre until you shift, then it is gone.
> 
>     * If it is the only image, you are obliged to return to the lt, and then you find yourself with the same empty-folder display as if you had used "selected images" to remove it.
> 
> 
> So those cases don't bother me more than they would in another view.
> It's really just an option for doing a cull within dr
> "I tried that, I tried the other, no it's still crap, let's get rid of it and move on".
> 
> I could live without it. I could also live with the option hidden in the undisplayed darktablerc.
> See what the crowd says?

Just to add to that, see what's this user says in this issue (#5042) about the fact that when an image gone away from filmstrip mode, he complains that this image still remains on darkroom. Something similar in some way. So not easy to find a good compromise for main users on remaining last duplicate (or removing an image with actions from filmstrip). So not so easy and probably this has to be consistent on both case. If an image disappear by removing it (or change ratings on filmstrip and have some filter to not display it anymore), we have to see same behavior I think on darkroom. And not so easy.

**Comment by GrahamByrnes** [comment]
Ok, I'll close...

**Pull request closed without merging**
