### PR TITLE
collect: use time info from image taken instead of image imported

### PR DESCRIPTION
**Pull request by codingdave**
The collect module offers some presets (las 24h, last 30days, today) that should work on the date the image was taken afaik but instead uses the time of the import. This PR changes these presets to use the time the image was taken at.

### CODE REVIEW

**Comment by TurboGit** [comment]
Not sure, the idea was to be able to quickly find the latest import as those are the one you probably want to handle. So to me this change is not OK.

**Comment by phweyland** [comment]
> the idea was to be able to quickly find the latest import as those are the one you probably want to handle

Which usually is not very different from original time stamp.

I would support the @codingdave direction as I don't find the import time stamp useful.

BTW, import time stamp is not a neutral information. It interferes with re-import operations forcing the rewrite of xmp files (see #9748). But that's another topic.

**Comment by TurboGit** [comment]
> Which usually is not very different from original time stamp.

Depending on your workflow. I do not necessary import my pictures in the order they were taken.

> I would support the @codingdave direction as I don't find the import time stamp useful.

So why not add 3 PR with picture time stamp and rename the current presets to "imported today", "imported last 24h" and "imported last 30 days" ?

**Comment by codingdave** [comment]
I understand it makes sense for you @TurboGit as it is but for me it often leads to confusion because due to the short preset names I expect it to be what I need ;-)

I usually import the pictures of the last month at once and then wonder why they all show up under the three presets.

I will add three presets and make clear wording such that both workflows are met.

**Comment by arntanguy** [comment]
> So why not add 3 PR with picture time stamp and rename the current presets to "imported today", "imported last 24h" and "imported last 30 days" ?

Sounds good. As a relatively new user I assumed that the current that the `last ***` filters would indeed be based on image timestamp and not import timestamp.

**Comment by codingdave** [comment]
@TurboGit please have another look. We now have 

* ...
* imported last 24h
* imported last 30 days
* imported today
* ...
* taken last 24h
* taken last 30 days
* taken today
* ...

**Comment by janfri** [comment]
Just my 2 cents: Do we really want/need so much standard presets? It could become not so handy if someone define more own presets as standard presets could not be deleted by the user if not needed. I would prefer not to add more standard presets and rename the three existing to "imported *".

**Comment by wpferguson** [comment]
Or remove the presets in question, and let the user define the presets that works for them

**Comment by codingdave** [comment]
So sad ... wanting to fix my author details I broke the repo with filter-branch. Sorry for the pinging. Instead of trying to fix this I will reopen another case and close this one.

**Comment by codingdave** [comment]
See #10058

**Pull request closed without merging**
