### PR TITLE
Allow building on macOS with Homebrew and independent of architecture

### PR DESCRIPTION
**Pull request by apfelkraut**
Following https://github.com/darktable-org/darktable/issues/10583 this commit should enable to build darktable on macOS using homebrew and independent of the chip architecture.

_Notes:_
- If Homebrew is found, its specific library paths will be used, otherwise the existing configuration for "macports and/or user-installed libraries" is being used to not break existing build procedure/support.
- On M1 the packages installed via Homebrew reside in `/opt/homebrew`, on Intel this would be `/usr/local`. You can automatically get this path by running `brew --prefix` or reading the environment variable `HOMEBREW_PREFIX`.
- The packages `llvm`, `icu4c` and `libsoup@2` have not been automatically found during configuration (probably due to the non-standard path of Homebrew) and so needed to be explicitly added to the prefix path

### CODE REVIEW

**Comment by parafin** [comment]
Could you please also add a commit reverting #10701 to this PR?

**Comment by apfelkraut** [comment]
Reverting https://github.com/darktable-org/darktable/pull/10701 as it is not required anymore due to the included changes to explicitly define the prefix path for icu4c and libsoup@2.

**Comment by parafin** [comment]
At least in GitHub CI HOMEBREW_PREFIX is not defined. So I guess it's not always present and another homebrew detection code should be coded. Or we should investigate why it's not there in CI.

**Comment by apfelkraut** [comment]
I am not familiar with GitHub CI, but I assume that Homebrew's shell environment might not have been properly initialized. The required export statements are provided with `brew shellenv` (https://docs.brew.sh/Manpage#shellenv). 

As example on my mac I am doing this specific to the chip architecture so that I am able to build for both architectures on the same machine ([source](https://stackoverflow.com/questions/64951024/how-can-i-run-two-isolated-installations-of-homebrew/68443301#68443301)):
```
if [ "$(arch)" = "arm64" ]; then
    echo "Configure homebrew to use arm ..."
    eval "$(/opt/homebrew/bin/brew shellenv)"
else
    echo "Configure homebrew to use i386 ..."
    eval "$(/usr/local/bin/brew shellenv)"
fi
```

**Comment by apfelkraut** [comment]
Thanks for the reviewing! Please see my latest commits. In addition I changed  the libsoup version to 2.x (currently 2.74.1). To my understanding this is what is required by darktable?

**Comment by parafin** [comment]
I'm not sure about compatibility with libsoup-3. It's a recent release and I suspect nobody yet looked into it. So yes, let's stick with libsoup-2 for CI builds for now. I've started the CI, let's see its results.

**Comment by parafin** [comment]
OK, all fine, merging.

**Pull request merged**
