### PR TITLE
New module: filmulate

### PR DESCRIPTION
**Pull request by CarVac**
Adds a new module, filmulate, to the pipeline.

filmulate is based on the core algorithm of [Filmulator](https://github.com/CarVac/filmulator-gui).

Recommended use:
1. Start with filmulate disabled.
2. Disable base curve.
3. Use the exposure module to adjust the input brightness to filmulate.
4. Enable filmulate, adjust it to taste.
5. Use levels and/or curves to adjust the output brightness.

The color space selector lets you manage high-saturation, high-brightness regions well, such as flowers. The module converts Lab into RGB before processing, then converts it back to Lab.

### CODE REVIEW

**Comment by TurboGit** [comment]
This PR has lot of conflicts. Do you plan to update it or should it be closed?

**Comment by jeffersonfr** [comment]
Hello,

I removed all conflicts and dependencies from c++ of the module filmulate.c. The version without conflicts is available in:

https://www.dropbox.com/s/qpid3hux1o3zmlr/filmulate.c?dl=0

Best regards.

**Comment by CarVac** [comment]
Last time I tried to compile darktable it didn't work. I'll try fixing this up and getting it into a mergable state.

**Comment by TurboGit** [comment]
Should we close this PR then?

**Comment by CarVac** [comment]
Yeah, I'll close it.

**Comment by aurelienpierre** [comment]
That's a bummer, I discovered your soft today, I love the idea of using PDE of chemical diffusion to process digital RAW. What was your problem ?

**Comment by CarVac** [comment]
I'm not sure why it didn't result in the same appearance.

The filmulation process in Filmulator takes in linear data and spits out data that's intended to be interpreted with the sRGB tone curve, but even though I tried to make it behave that way in the darktable pipeline, it always looked dramatically different.

**Comment by aurelienpierre** [comment]
Why do you use sRGB ? Also where in the pixelpipe did you squeeze it ?

I will see if I can help.

**Comment by CarVac** [comment]
I use sRGB out of convenience in Filmulator but in the darktable module I think I used Rec.2020.

The narrower the color space, the more the algorithm accentuates colors (within the color space).

**Pull request closed without merging**
