### PR TITLE
lut3d - fix GTK warning

### LINKED ISSUE #3753: dt3.0: lut 3D: Gtk-WARNING drawing failure for widget 'GtkWindow' & 'GtkDrawingArea'
**Describe the bug**
The combobox at first line of lut 3D module is producing two Gtk warnings when the "lut file" selection icon is not used before.
100% reproducible in this context

**To Reproduce**
1. Select an image and Go to 'darkroom'
2. Open the 'lut 3D' module
3. At the first parameter line, do not use the "lut file" icon on the left, but directly Click on the combobox on the right.
4. No choice proposed (no file listed), but See the following 2 Gtk warnings in the console:
```
(darktable:26403): Gtk-WARNING **: 17:03:45.033: drawing failure for widget 'GtkDrawingArea': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(darktable:26403): Gtk-WARNING **: 17:03:45.033: drawing failure for widget 'GtkWindow': invalid value (typically too big) for the size of the input (surface, pattern, etc.)
```
**Expected behavior**
No Gtk warning

**Platform (please complete the following information):**
 - OS: Ubuntu 19.10 / Gtk 3.24.12-1ubuntu1
 - darktable 3.0.0rc2+97~gb26d5128f

**Additional context**
When the "lut file" icon on the left is used before, and a lut file selected, then the list of choices on the combobox is not empty, and no Gtk warning reported

dt compiled by myself from latest git master using standard build instruction. No specific option added

**Side comment**
I do not fully understand the logic to have two different widgets (the "lut file" icon, and then the combobox) on the same line to select the lut file

### PR DESCRIPTION
**Pull request by phweyland**
Should fix #3753 
Doesn't cover the issue related to a reset of preference folder.

### CODE REVIEW

**Comment by TurboGit** [comment]
I still have some warnings:
`(darktable:33985): Gtk-WARNING **: 13:39:19.680: drawing failure for widget 'GtkDrawingArea': invalid value (typically too big) for the size of the input (surface, pattern, etc.)`

**Comment by phweyland** [comment]
Sorry, I've treated a particular case and not the general one. Should be better now.

**Comment by TurboGit** [comment]
No more warning, but now when selecting a .cube or .png in a directory it is not possible to select another one listed in the combobox. It was possible before to move through all of them.

**Comment by phweyland** [comment]
My bad ! Hoping this time that's ok ... :(

**Comment by TurboGit** [comment]
Looks good now! Thanks.

**Pull request merged**
