### PR TITLE
imageio_exr: handle APP1 prefix on exif import

### PR DESCRIPTION
**Pull request by kmilos**
Partially addresses https://github.com/darktable-org/darktable/issues/12580

### CODE REVIEW

**Comment by TurboGit** [comment]
Partly addresses #12580, do you plan any improvement on this or it is ready to merge as a first step?

**Comment by kmilos** [comment]
No further plans, thanks.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by TurboGit** [comment]
@kmilos : Can you help me formulate this in the RELEASE_NOTES file?

**Comment by kmilos** [comment]
@TurboGit I would simply say "Fix reading of EXIF metadata when importing EXRs (if desired, existing files must be re-imported, refreshing metadata is not an option)"?

**Pull request merged**
