### PR TITLE
center iop module tooltip across side panel

### PR DESCRIPTION
**Pull request by dterrahe**
A further "refinement" to #13963, this time only for the iop module description tooltip. It is now always centered across the whole header of the module (and the whole header is sensitive to "tooltip hover"), except when it doesn't fit to the right. So they don't unnecessarily stick out over the center image anymore when hovering the mouse close to the edge. And they'll end up neatly below each other. But overall I'm not sure people will find this an improvement.
image

This PR in itself would be sufficient (using `GDK_ANCHOR_SLIDE_X`) to solve the main original issue, but the previous PR avoids some other tooltips ending up off screen as well. In theory this solution using `gdk_window_move_to_rect` could be applied everywhere (i.e. be implemented in `dt_shortcut_tooltip_callback`) but it could cause problems in some cases (one of them being thumbnails in the lighttable). It seems the default is that the tooltip appears close to the mouse location rather than a fixed anchor point of the widget.

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Getting better and better... This works fine for me.

**Comment by dterrahe** [comment]
So... personally I am not sure if maybe I like 
`gdk_window_move_to_rect(window, allocation, GDK_GRAVITY_SOUTH_WEST, GDK_GRAVITY_NORTH_WEST, GDK_ANCHOR_FLIP_Y | GDK_ANCHOR_SLIDE_X, 0, 0);`
better.

That means the popups would align on the left of the panel (and only jut out if they don't fit, as before).

A vote may not be worth it (because people probably won't care) but @turbogit if you have a preference let me know.

**Comment by TurboGit** [comment]
I have no preference really. The current PR works for me, I have tested the other move_to_rect value and it also feels ok to me. So your call.

**Comment by dterrahe** [comment]
OK, please merge as is then. Thanks!

**Review by TurboGit — APPROVED** [review]
Merging... Last merge for today :)

**Pull request merged**
