### PR TITLE
Better spacing for filter-box area and collections arrow

### LINKED ISSUE #10348: top panel alignment
The buttons and dropdowns in the top panel should all be aligned to one another but they are not. In addition, the reverse-sort icon should be larger to distinguish it from the arrows on the dropdown lists.

Screenshot_2021-11-07_11-35-05

@Nilvus I've assigned this to you but I'm not entirely sure if it can be done with just CSS.

### PR DESCRIPTION
**Pull request by Nilvus**
Fix #10348 and also fix a little wrong spacing of the arrow next to filter entry in collections module. Make also little cleanup of some no more useful lines.

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Looks good to me, thanks !

**Comment by elstoc** [comment]
Better indeed. Thanks @Nilvus.

**Comment by Nilvus** [comment]
I am finally wondering if 0.14em instead of 0.28em for filter-box padding would maybe be better. What's your view on that? 

Quick test possible with that:
```
#filter-box
{
  padding-top: 0.14em;
}
```

**Comment by Nilvus** [comment]
It's better to hide main header part and only see top panel to check that. I have tested this PR without hiding header part above that panel and the impression is not the same. With 0.14em, I found that more vertical centered.

**Comment by elstoc** [comment]
I agree: 0.14em is better. I test it by setting the font to be large (15pt) and taking a screenshot of just the panel.

**Pull request merged**
