### PR TITLE
Afrikaans

### PR DESCRIPTION
**Pull request by thisnamewasnottaken**
Updates to Afrikaans translation. Testing new workflow.
Further work to come.

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Thanks !

**Comment by TurboGit** [comment]
I will have to merge manually as there is conflicts !

Please be sure to update the .POT file as it has been modified. Thanks.

**Comment by thisnamewasnottaken** [comment]
Will do, sorry.

**Comment by TurboGit** [comment]
Manually merged. So now be sure to take new POT and new PO from repository as described in the WiKi. 

https://github.com/darktable-org/darktable/wiki/Translations

Thanks.

**Pull request closed without merging**
