### PR TITLE
develop: Fix single instance module & auto-presets.

### LINKED ISSUE #14491: auto-apply preset creates second instance of single-instance module
### Describe the bug

If an auto-apply preset is defined for a module which does not support multiple instances, an new instance is created anyway, causing problems.

### Steps to reproduce

1. Create an auto-apply preset for Demosaic (the one which triggered it for me is conditional on camera and high ISO) with non-default values,e.g. VNG demosaicing
2. Import a photo which matches those criteria and open in it darkroom
3. Notice corrupted display and log messages on console:
>    324.0120 [_transform_matrix] invalid conversion from IOP_CS_RGB to IOP_CS_RAW
>    324.0120 [dt_ioppr_transform_image_colorspace] in \`demosaic', profile \`Linear Rec2020 RGB', invalid conversion from IOP_CS_RGB to IOP_CS_RAW
4. Switch tabs to Active modules tab and notice two instances of Demosaic
5. 

### Expected behavior

The preset should be applied to the existing instance of a single-instance module.

### Logfile | Screenshot | Screencast

_No response_

### Commit

presumably one of the auto/multiple preset PRs like #13149, #13432, or #13998

### Where did you install darktable from?

self compiled

### darktable version

master (today's, then I rolled back just a bit to 4.3.0+2244 since I hadn't seen the corrupted display in darkroom yesterday).  Not a problem in 4.3.0+12 (i.e 4.2.0) which I still have installed.

### What OS are you using?

Linux

### What is the version of your OS?

Mageia 8

### Describe your system?

_No response_

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by TurboGit**
If multiple user's presets are defined (and selected) for a module with a single instance we need to merged the presets into the same dev instance.

Fixes #14491.

### CODE REVIEW

**Comment by ralfbrown** [comment]
The code looks reasonable, but I won't have a chance to test until evening.

**Comment by TurboGit** [comment]
@ralfbrown : No problem, test when you have time. TIA.

**Review by ralfbrown — APPROVED** [review]
Works for me.

**Comment by TurboGit** [comment]
Thanks for testing.

**Pull request merged**
