### PR TITLE
handle simultaneous shortcut presses and improve responsiveness

### LINKED ISSUE #10871: Input NG: Improve responsiveness
In darktable 3.8.0, I currently have keyboard shortcuts in place to toggle the left and right panels. Often I will keep the right-hand panel open while I'm editing and the left-hand panel collapsed, allowing me to keep my image as large as I can while I'm editing. If I want to briefly do something in the left-hand panel I will often use both of these shortcuts to toggle both panels at the same time. However, the second shortcut is often swallowed by Input NG and I need to press it again, or remember to do it more slowly. This was instantaneous in darktable 3.6.x (I could press both keys at essentially the same time).

There have been other cases where I have noted a slight delay between initiating a shortcut and it being executed (or where I couldn't execute multiple shortcuts one-after-another as quickly as I'd like). 

I assume this delay is there to allow for additional clicks and/or key-presses (I haven't delved into the code yet). If so, I suppose there might be a few ways to handle this:

- Provide some configuration options to disallow multiple key-presses and multiple mouse-clicks. Myself, I could probably live without these options if it made shortcuts more responsive.
- If a key combination is used, for which no double-click/press/etc. action has been defined, do not wait for a second/third click/press. If multiple actions are defined for a combination, wait for them before executing.
- While waiting for subsequent presses/clicks, store any further key presses in a queue and process them after the wait has finished.

@dterrahe can you advise? I'm happy to work on implementation if you can point me in the right direction.

### LINKED ISSUE #10898: key shortcut - bad persistent state?
**Describe the bug/issue**

Define a shortcut for 'e' + horizontal-mouse move to control exposure. Use it and move up/down, the horizontal move is not working anymore.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go 'darkroom'
2. Click on 'e' + mouse-move-horizontal
3. All good this increase the exposure, do not release 'e' key
4. Move mouse up, message on top 'e, left-click, vertical, up' not assigned, OK that's the case, do not release 'e' key
3. Move mouse horizontally again
4. See error, 'e, horizontal, up not assigned'

**Expected behavior**

The Last step should increase the exposure. The issue is that as soon as the mouse is not move correctly you have to release everything and try again.

To me it looks like some state are not reset, in point 6 above the message is having the 'up' info which is suspicious.

**Platform**

* darktable version : master
* OS                : GNU/Linux
* Linux - Distro    : GNU/Debian - sid

### PR DESCRIPTION
**Pull request by dterrahe**
This was a journey (fixes #10871 and fixes #10898).

Input NG was designed to allow a move (scroll wheel etc) to apply to multiple sliders/actions at the same time by pressing and holding all assigned keys together. It also allows double and triple presses of keys and mouse buttons (clicks). In order to not make things _too_ complicated and unpredictable (increasing likelihood of mistakes) any situation where multiple keys where pressed together disabled the individual actions of those keys i.e. what you would get by (double/triple/long) pressing those keys.

This was a simplification/asssumption that the rest of the code relied on. Dealing with a key press while a delayed action (a key or mouse release that might be part of a double/triple press) was waiting, simply meant _cancelling_ that action "to be safe".

However, it turns out people _do_ press keys together, or very quickly after each other, and they do expect all the mapped actions to take place. Also, they don't like to wait for potential double and triple clicks when they haven't mapped any.

So the code is now smarter (tries to be, at least) and executes delayed actions early if another event happens in the mean time (which indicates that the user isn't intending to finish a double/triple press/click). If no doubles or triples are mapped, there won't be a delay after the first or second one. And if multiple keys are pressed and released "at the same time" _all_ their actions are triggered (unless between press and release too long a time has passed, double-click-delay*number of key presses, or another event has interceded, like a mouse click or scroll/move).

With this PR, if no double or triple press shortcuts are defined anywhere, key releases will immediately trigger an action. And pressing and releasing multiple keys "at the same time" should work as expected (independent of whether the pattern is AaBb, ABab or ABba). A user might notice a slowdown in a shortcut if they map a variant that requires double or triple presses, so they should only overload less frequently used keys.

Actions are still triggered on _release_, not on _press_ (apart from _hold_ shortcuts, like `h`, `w` and emulated modifiers). To change this fundamental behavior would need a non-trivial check on key press to determine if any extended shortcuts exist that combine with the key. This would be a duplication and a complicated code path. My fear is that it would not get enough testing (given the split userbase created by the ability to disable fallbacks and the many different usage patterns) to weed out all the corner case bugs. Even in the current simpler implementation fundamental objections were raised after it was in master for the better part of a year.

### CODE REVIEW

**Comment by elstoc** [comment]
Certainly fixes my most common use cases for this. Thanks @dterrahe!

**Comment by TurboGit** [comment]
Tested, that's a big improvement to me. I have able to map e+horizontal (change exposure) and ctrl+e+horizontal (change exposure slowly changing value from 1.0 to 0.5) and live over the image I can keep e pressed, move the mouse horizontally and press ctrl from to to time (without releasing e) to do smaller steps... All this without any slowdown. Thanks a lot for this fantastic Input-NG work.

**Comment by dterrahe** [comment]
I'm glad you like it! But TBH what you describe ("dynamic shortcuts"/move shortcuts) should already have worked before. With fallbacks, you could just assign a letter to a slider and automatically have letter+horizontal do small moves and ctrl+letter+horizontal do extra small moves. And you can switch while holding the letter by just pressing or releasing ctrl (or changing direction from horizontal to vertical). But ctrl+e can cause problems because it is already mapped to export.

Try mapping double press of each of the numbers 1-9 to the sliders in Tone Equalizer. Then, if you want to change just -6EV & -5EV & -4EV, you can do +3-3+3+4+5 and continue to hold those three numbers and now scroll or move horizontally or move vertically to adjust that section of the graph.

But anyway, this PR is only improving press/click shortcuts (i.e. without scroll/moves). And especially using more than one quickly. The example that Chris pointed out, pressing CTRL-SHIFT+L and CTRL-SHIFT+R to toggle both side panels would previously ignore one of those key presses unless you paused in between. Now that should work reliably. Or assigning a letter to a module and then pressing that letter and left-clicking to enable/disable it (using fallbacks) would work _unless_ you released the letter too quickly after the click. Then the click would just be ignored (because the code was still waiting to see if you were going to do a double click). Now it executes the single click as soon as you release the key.

If you have a bunch of modules assigned to letters (xyz) you can toggle all of them by doing XYZclickxyz

I'm still working on adding a fix for #10898 here.

**Comment by elstoc** [comment]
I assume this is too big/intrusive to be considered for 3.8.1?

**Comment by dterrahe** [comment]
> I assume this is too big/intrusive to be considered for 3.8.1?

I think so, unless we can get some serious testing organised. My own testing is somewhat useless in that regards because I've developed these massive blind spots...

**Comment by dterrahe** [comment]
Now also fixing #10898

Pressing and releasing a key normally only triggers an action if it is done within the "long press delay" interval (i.e. double the double-press interval). When holding (mulitple) keys (for example to apply move shortcuts to all at the same time), pressing and releasing an additional key doesn't do anything; it is interpreted as "adding another key to the set of keys already held and then removing it from that set again". So this PR uses that useless action, if it is done quickly, to clear the set of held keys. This can be useful, because there are some reports of people that get into a stuck state where the system received a "key" press, but never received the key release (and therefore thinks the key is still being held).

The previous solution to this problem was to clear state when invalid shortcuts were received, but that was sometimes unintentional. Hopefully this is more intuitive and also naturally clears a stuck-key-at-startup situation when a user types their first shortcut.

**Comment by TurboGit** [comment]
> I'm glad you like it! But TBH what you describe ("dynamic shortcuts"/move shortcuts) should already have worked before.

Yes probably, but indeed not easy to setup as it needs fallbacks and as I said they was some delay on handling shortcuts. As you said the new implementation does not wait anymore if there is ambiguity about the possible shortcut. Today, even quitting darktable with `ctrl+q` you feel some delay, likewise for selecting all images `ctrl+a`. So again to me this PR is a huge progress and I really thanks you for working hard on this delicate stuff!

**Comment by TurboGit** [comment]
> > I'm glad you like it! But TBH what you describe ("dynamic shortcuts"/move shortcuts) should already have worked before.
> 
> Yes probably, but indeed not easy to setup as it needs fallbacks and as I said they was some delay on handling shortcuts. As you said the new implementation does not wait anymore if there is no ambiguity about the possible shortcut. Today, even quitting darktable with `ctrl+q` you feel some delay, likewise for selecting all images `ctrl+a`. So again to me this PR is a huge progress and I really thanks you for working hard on this delicate stuff!

**Comment by elstoc** [comment]
I just want control and I don't want any auto-magic stuff setup on my behalf. I want to set up the shortcuts I want to set up and disable everything else. I use maybe a dozen keyboard shortcuts and I want to know what will happen when I accidentally mash the wrong key combination (i.e. nothing). For example, too many times have I inadvertently started the slideshow (S) instead of searching a module (Ctrl+S).

It was very nice of you to give me the ability to disable fallbacks and I'm very happy now that I have them disabled (I honestly had no use for most of them). Though I do see how others might prefer auto-magic.

**Comment by dterrahe** [comment]
> I just want control and I don't want any auto-magic stuff setup on my behalf.

And I'm glad to have at least one person that actually speaks up on behalf of the thousands of others that just quietly curse me!! Can you imagine the sh.tst.rm if 3.8 had been released with fallbacks enabled?

But on the other hand, there also might be some people that really would like fallbacks if they understood how it works. I'm secretly suspecting Pascal might be one of them ;-)

And also, if _nobody_  likes the current fallbacks, would be nice to know what could be done to make them more likeable... But I believe I've had literally zero feedback on the feature. Maybe nobody sees any potential benefit. Which is also fine; _I_ like having them!

**Comment by elstoc** [comment]
> But I believe I've had literally zero feedback on the feature. Maybe nobody sees any potential benefit.

As we've discussed before, I left this a long time to test thoroughly because I didn't understand it and I was simply overwhelmed by the extent/complexity -- I only eventually bit the bullet because I needed to write the user manual content. I suspect a lot of people left it longer (or haven't even looked at it yet). So I'd say more likely people are not using it to anywhere near the extent that you are, or haven't enabled fallbacks as they can already make it do what it did before.

**Comment by elstoc** [comment]
@TurboGit I'm not sure this requires explicit documentation unless there's something I've missed. Is there anything specific you had in mind when you tagged it?

**Comment by TurboGit** [comment]
@elstoc : No, nothing specific in mind, I must say that I haven't looked at the new documentation so I don't know what are the level of details here :) I'm putting the "documentation-pending" tag more as "please elstoc see if there is something to add in there" :) Feel free to close, then. Thanks.

**Comment by elstoc** [comment]
Ok no problem. Better to be tag than not.

**Pull request merged**
