### PR TITLE
Pollish Input NG buttons

### PR DESCRIPTION
**Pull request by dterrahe**
Button shows shortcut in tooltip and can be assigned by point-and-press mapping mode.

truncate history uses same shortcut as compress history but with ctrl pressed (via fallback definition). Or you can explicitly assign it to its own key by using the ctrl-activate effect.

### CODE REVIEW

**Comment by TurboGit** [comment]
BTW: I have many lines like this on the console:

```
[dt_accel_register_shortcut] expected to find a key in group 0 with only shift
[dt_accel_register_shortcut] expected to find a key in group 0 with only shift
```

**Comment by dterrahe** [comment]
Seems to be related to French keyboard. Will look into it tomorrow.

**Comment by dterrahe** [comment]
There are a few more cases, but I'll change this from Draft now for testing/merging, as I might not have time to complete the others for a bit.

**Review by TurboGit — APPROVED** [review]
Works for me, thanks !

**Pull request merged**
