### PR TITLE
histogram: restrict waveform to selection via global colorpicker

### LINKED ISSUE #8008: global color picker "restrict histogram to selection" doesnt affect waveform histogram
color picker checkbox "restrict histogram to selection" doesn't affect waveform histogram.
when standard histogram is active the histogram is reduced, but not if waveform (or vectorscope) histogram enabled

1. open image in darkroom
2. select an unicolor area with global color picker
3. enable checkbox "restrict histogram to selection" 
4. switch between standard and waveform histogram

**Expected behavior**
even waveform (and further) histogram mode should be supported

**Platform (please complete the following information):**
 - Darktable Version: darktable 3.5.0+861~g5885bff7e-dirty 
 - OS: osx

### PR DESCRIPTION
**Pull request by dtorop**
This matches behavior of the "regular" histogram. The waveform is displayed as if it were processing the image cropped to the colorpicker area. This does result in scaling of the x-axis, but the result seems intelligible.

At quick testing, this change makes `_lib_histogram_process_waveform()` ~10% slower in the non-restricted case. I haven't been able to figure out a good way around this. This may be an OK slowdown, as waveform process on this computer is now 0.011 vs 0.010 secs. And the 2nd stage (draw) code continues to be about 0.008 secs. Hence ~5% slowdown altogether.

Fixes #8008.

### CODE REVIEW

**Comment by dtorop** [comment]
I clocked this better. It appears that there's actually no slowdown between this version and the code in git master. It's just hard to measure time down to 0.001 sec. when lots of other threads are working.

**Comment by TurboGit** [comment]
There is one issue, to reproduce:
- set histogram to waveform
- select area with global color picker
- check : `restrict histogram to selection`
- release color picker
- select it again but with a simple click (point)

See "working..." message and dt being frozen.

**Review by TurboGit — CHANGES_REQUESTED** [review]
Fix bug with point color picker and restrict histogram to area.

**Comment by TurboGit** [comment]
I suppose we just want to not take into account the restrict histogram to area when the the picker is a point.

**Comment by dtorop** [comment]
> Fix bug with point color picker and restrict histogram to area.

I can reproduce this with a JPEG but not a raw file. It may relate to image dimensions. To be honest, I don't totally get the `dt_histogram_roi_t` type, but am going with it to keep histogram and scope code consistent.

A simple fix is just guarding against an infinite loop on a 0x0 crop -- probably helpful regardless. I did that.

> I suppose we just want to not take into account the restrict histogram to area when the the picker is a point.

The output of a 1x1 scope is a bit absurd whether it's histogram or waveform. But there could be some interest in seeing where the RGB waveform lines sit on the graph for a single point. I'm inclined to leave things as is, just to give people the option of that information, and to make the "restrict" checkbox do something in all cases.

Here's a 1x1 sample for histogram:

image

And in waveform:

image

An alternative would be to disable the checkbox in the GUI unless there's an area selection. But as it's already hard to discover that control-click makes an area selection, I worry people would be confused about why there is an insensitive checkbox there in most cases.

I also noticed that for a 1x1 sample, the RGB parade draws a bit funny, presumably due to interpolation:

image

Again, I'm inclined to leave this rather than spend a lot of time on very corner cases. One could even argue that the faded overlapping lines make things more legible.

Question: right now the global color picker says `restrict histogram to selection`. Should this change to `restrict scope to selection`? Or is that a slippery slope of changes...

**Comment by TurboGit** [comment]
> Question: right now the global color picker says `restrict histogram to selection`. Should this change to `restrict scope to selection`? Or is that a slippery slope of changes...

Good question ! But I really don't have an idea about this. I read histogram as a very generic term and to me it looks ok but I'm not a native English speaker. Do you think scope would also cover all displays (histogram, vector scope, waveform...) ?

**Review by TurboGit — APPROVED** [review]
Works for me, thanks! I'm merging this. The label change should be anyway in another PR if needed. Thanks.

**Comment by dtorop** [comment]
> > Question: right now the global color picker says `restrict histogram to selection`. Should this change to `restrict scope to selection`? Or is that a slippery slope of changes...
> 
> I read histogram as a very generic term and to me it looks ok but I'm not a native English speaker. Do you think scope would also cover all displays (histogram, vector scope, waveform...) ?

I'm finding it awkward to refer to histogram as "regular histogram" (vs. waveform, etc.), so introducing another term ("scope") to cover all the plot-like descriptions of images might be helpful. I'm not sure if there's already a convention for this, but it's possible to set one for darktable...

The slippery slope, is changing UI text, documentation, name of src/libs/histogram.c, etc...

**Pull request merged**
