### PR TITLE
Updated uk translation

### PR DESCRIPTION
**Pull request by alkhimmikk**

### CODE REVIEW

**Comment by LebedevRI** [comment]
`po/uk.mo` should not be here.

**Comment by alkhimmikk** [comment]
how to remove it? another pull request?

**Comment by LebedevRI** [comment]
no, just remove it as a new commit in this branch

**Comment by alkhimmikk** [comment]
I hope now is ok.

**Comment by LebedevRI** [comment]
@alkhimmikk thanks, squash-merged in order to avoid that `.mo` from appearing in history...

**Pull request merged**
