### PR TITLE
applies preview_downsampling correcting to crop in ashift.c

### PR DESCRIPTION
**Pull request by GrahamByrnes**
This appears to fix issues (not: #5225) #5226 
Finally, my early diagnosis was correct (undersized bounding box wasn't allowing most of the image to be considered), but it took me a long time to find the "obvious" cure.

I still don't think this works as well with the lower resolution: if you rattle it around a few times with the different transformation options it eventually gets close, but at 1/1 it jumps there right away.
Or, there may still be errors... but it seems ok.

### CODE REVIEW

**Comment by GrahamByrnes** [comment]
PS: tested it on a more "natural" setting, ie  a building with rectangular windows, and it works just fine. A colour-checker in a black box is really a challenge!

**Comment by MStraeten** [comment]
auto cropping is ok now, but the rotation issue is remaining (even with a much simpler image)

**Comment by GrahamByrnes** [comment]
@MStraeten : yes, working on #5225, but completely lost just now.

**Comment by GrahamByrnes** [comment]
I've found the scaling constant that fixes the transformation :-)

The bad news is that in fixing that, there are a bunch of UI things gone to...

Anyway, best not to look at this until I find out how to bring it all together.

**Comment by TurboGit** [comment]
@GrahamByrnes : Good progress !

**Comment by GrahamByrnes** [comment]
Current status: scaling `g_buf->scale` by prev_downsample enables the simplex algorithm to fit a correct transform... the parameters are with about 2% and it looks right. The cropping works.

What doesn't work is the display of edges on the screen: they appear to reflect rotations, but not shift or shear. However, this *seems* to relate only to the display, and not to the transforms. Given a photo with very little rotation and a *lot* of angle, the final image picks up the angle just as you'd like. 

The crop box and its manual adjustment works. The "bounding box" for picking out important lines sort of works, but the circle over here picks up a line over there. In this case it's not simple affine transforms (I thought I was on the way for a moment there), there is a homography command that isn't working properly. Thing is, it's called 11 times, and presumably the calls responsible for shifting images up & down the pipe are correct, and the call that works in tandem with simplex() to calculate the fit quality is correct (since the results are pretty good). But it's the same function...

Ok, back to it.

PS ashift works remarkably well btw, much better than I would have expected.

**Comment by GrahamByrnes** [comment]
I think this works now. As you'd expect from the comment about rotations being correctly mapped but not lens angles, it was an issue of scaling the lines before they were transformed: rotations are invariant wrt vector length :-)

Last night there was a complaint related to OpenMP not opening. I made a change, it was still there, I changed it back, it wasn't. In any case, there is a small change in `process_cl` which I haven't been able to test.

With @MStraeten window image, when p/d is set to 1/4 there is a warning of insufficient structure. However using ctrl-click to get more lines does the trick

20200530-IMG_8649

**Comment by TurboGit** [comment]
Finally works for me too. Great work! I have tested with all down-sampling values and without down-sampling. No issue, merging.

**Comment by GrahamByrnes** [comment]
Quick review! Thanks.

**Pull request merged**
