### PR TITLE
[GUI] More correct text about ICC files in color profile widget tooltips

### PR DESCRIPTION
**Pull request by victoryforce**
Fixed location of ICC files for input color profile. Some descriptions of profile purpose have also been made more correct, namely:
when referring to the ICC file for the input profile, we call it external to emphasize that the ICC profile can be embedded in the image, so the input profile in a separate file is an external profile to the image. The word "external" is inappropriate in the tooltip of the working and export profile, this has been fixed.

### CODE REVIEW

**Comment by TurboGit** [comment]
> Not introduced by this PR but maybe `dt_ioppr_get_location_tooltip` should use `g_markup_printf_escaped` instead of `g_strdup_printf`?

 I don't think so as we want the markup to be kept as-is (and not escaped) to be able to have them handled later by the `gtk_widget_set_tooltip_markup` calls.

**Comment by dterrahe** [comment]
`g_markup_printf_escaped` doesn't escape the format string (which intentionally contains markup) but if any of the strings inserted in the format string contain accidental markup characters they could cause the interpretation of the combined string to fail as invalid markup and no tooltip would appear, so _those_ would need to be escaped. g_build_filename on Windows produces /'s so I'd imagine that could have unintended consequences, but I'm away from my development machine so can't test.

**Comment by dterrahe** [comment]
Now tested and as expected, starting dt with a configdir that contains characters that confuse markup, like
`darktable --configdir ~/.config/darktable\&`
causes the tooltip not to appear and a warning in the log:
```
(darktable:4642): Gtk-WARNING **: xxx:xxx:xxx.xxx: Failed to set text 'darktable loads export ICC profiles from
<b>/home/diederik/.config/darktable&/color/out</b>
or, if this directory does not exist, from
<b>/home/diederik/darktable.master/build/share/darktable/color/out</b>' from markup due to error parsing markup: Error on line 2: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;
```

Using `g_markup_printf_escaped` as suggested above fixes the problem: 
image

This won't matter in 99% of cases so no real need to use the correct function.

**Comment by victoryforce** [comment]
> Now tested and as expected, starting dt with a configdir that contains characters that confuse markup, like
darktable --configdir ~/.config/darktable\&
causes the tooltip not to appear and a warning in the log

Thank you for testing!

> This won't matter in 99% of cases so no real need to use the correct function.

You're right. But since the fix is trivial and safe, I'll propose a PR.

**Pull request merged**
