### PR TITLE
lighttable : hide scrollbar in preview/expose/culling

### PR DESCRIPTION
**Pull request by AlicVB**
@edgardoh : can you confirm scrollbars are not needed/wanted in culling layout (to be sure I've not missed some functionality)

### CODE REVIEW

**Comment by TurboGit** [comment]
I have the scrollbar activated only on the lighttable but do not see them on exposé or culling mode. Is that only me?

**Comment by TurboGit** [comment]
Of course I agree that they should not be present on those mode.

**Comment by edgardoh** [comment]
I have never used scrollbars on culling or expose, so this is ok with me.

**Comment by AlicVB** [comment]
In fact there's 2 different scrollbars : one for showing the position at the extrem left and right : read only
and one just on the right, which is not read only. It's visible status is determined by the "scrollbars" pref entry.
We can show the 2 right scrollbars on the screenshot above (take in filemanager layout, but that was exactly the same in preview)
Capture d’écran_2019-04-10_19-08-38

**Comment by TurboGit** [comment]
In full preview I see the scrollbars, yes but not on culling or exposé.

**Comment by TurboGit** [comment]
And indeed this hides the scrollbars from full preview. So merging. Thanks.

**Pull request merged**
