### PR TITLE
colorbalancergb: make the mask preview checkerboard parametric

### PR DESCRIPTION
**Pull request by aurelienpierre**
enable users to chose colors and size of the background checkerboard. Ex : 
Screenshot_20210409_231216
(default colors are white and grey)

### CODE REVIEW

**Comment by todd-prior** [comment]
@aurelienpierre Sorry to be thick...have you explained the mask display yet??  I tried to interpret it by moving the sliders to extremes but I wasn't sure how to use the displayed mask. I was assuming they are to illustrate the region being defined as either highlights, shadows or midtones??

**Review by TurboGit — APPROVED** [review]
Works for me!

**Comment by Nilvus** [comment]
@todd-prior: see #8620

**Comment by todd-prior** [comment]
Thanks I did see that ...but tried it on some of my images and it really was hard to clearly see the areas esp when moving the sliders to extremes to try and follow how that would map...





Get Outlook for Android

**Pull request merged**
