### PR TITLE
move slider popup if off screen

### LINKED ISSUE #6255: FR: bauhaus slider popup
Where a bauhaus slider is located near the bottom of the screen, the right-click popup is not entirely visible. This is particularly noticeable in the overexposed/clipping indicator setting

Screenshot_2020-09-09_23-31-58

but also occurs in iop modules

Screenshot_2020-09-09_23-32-39

It would be great if darktable could detect this situation and have the popup appear above the slider instead of below it.

### PR DESCRIPTION
**Pull request by dterrahe**
fixes #6255

Similar to bauhaus combos, if the popup for a bauhaus slider appears partially off-screen, when the mouse moves towards the screen edge, more of the popup is moved into view.

The popup isn't repositioned immediately and fully placed into view, because that would cause the mouse cursor to start somewhere in the middle or outside the popup and either immediately close or immediately cause the value to jump.

### CODE REVIEW

**Comment by dterrahe** [comment]
@TurboGit diff is mostly whitespace due to unindenting as differences between combo and slider removed.

**Comment by TurboGit** [comment]
> @TurboGit diff is mostly whitespace due to unindenting as differences between combo and slider removed.

Indeed, the diff without the spaces is less intimidating :) To me this is safe for 4.2.1, do you agree?

**Review by TurboGit — APPROVED** [review]
Works on my side. Thanks!

**Comment by dterrahe** [comment]
> To me this is safe for 4.2.1

Probably...

But on the other hand I don't think there's a need to step onto the slippery slope; 4.4 with a lot more testing is fine for me too. Maybe @elstoc can opine?

**Comment by TurboGit** [comment]
@elstoc : That's more a fix than a new feature to me.

**Comment by TurboGit** [comment]
Ok, let's go with 4.4 only finally.

**Pull request merged**
