### PR TITLE
Import camera

### PR DESCRIPTION
**Pull request by phweyland**
move "import from camera" dialog to merge it with other import dialogs.

remove "mass storage camera" from "import from camera".

### CODE REVIEW

**Comment by phweyland** [comment]
I've tried to check under windows 10 but I have been unable to unmount the camera to let dt use it.

So far I've let the import "parameters" in import module, but we could move them into a dialog tab. 

@jenshannoschwalm, as I've cut the original "import from camera" code into pieces and glued them in a different way, it would be kind of you if you could review this with an informed eye. Thank in advance.
Note: I haven't tried to reused the previews if already prefetched.

image
I find the new dialog  window a bit too big (800x900)...

**Comment by jenshannoschwalm** [comment]
> I've tried to check under windows 10 but I have been unable to unmount the camera to let dt use it.

That's the same as we had for long from reports.

Otherwise, i tested here and could not find any issues. The critical point was to keep the device in place and import images again and that indeed keeps working. Seems good to me.

**Comment by phweyland** [comment]
This PR follows the #8372 (to ping the participants). Maybe @AxelG-DE wants to have a look too.

**Comment by phweyland** [comment]
Thank you @jenshannoschwalm for testing !

**Review by TurboGit — APPROVED** [review]
Looks good and works fine on my side. Merging now as this will certainly need more field testing.

**Pull request merged**
