### PR TITLE
fix history undo/redo in darkroom

### PR DESCRIPTION
**Pull request by TurboGit**

### CODE REVIEW

**Comment by elstoc** [comment]
Works fine for the history stack 'reset parameters' button but the other way of doing it (click original and compress) still seems to need an extra 'undo'. I think somehow it's splitting the rebuilding of a 'default' stack into (1) Build the default_enabled modules; then (2) Add any modules enabled by workflow/presets.

I don't know if this is expected but I suspect not.

**Comment by TurboGit** [comment]
> but the other way of doing it (click original and compress) still seems to need an extra 'undo'

In my latest version it needs only 2 undo: one for restoring history and one for replacing the history end.

**Comment by elstoc** [comment]
Yes that looks better. All good for me.

**Comment by TurboGit** [comment]
Thanks for testing !

**Comment by TurboGit** [comment]
Manually rebased and merged.

**Pull request closed without merging**
