### PR TITLE
rawspeed: parse and pass on per-channel black (RAF files)

### PR DESCRIPTION
**Pull request by hanatos**
this is probably an issue with all *Decoder classes and potentially may be
solved better (and for all other ones, too, while at it).

not sure which way is the preferred way?

### CODE REVIEW

**Comment by hanatos** [comment]
i should probably add some context:

http://permalink.gmane.org/gmane.comp.graphics.darktable.devel/7472

i know nothing about the different needs of the different decoders. maybe it would be a good idea to let the CameraSensorInfo struct fill whatever it has to the raw struct with a small member function? so we don't have to copy around the code to fill in the blacks in all the individual decoders.

**Comment by pedrocr** [comment]
This is probably not the correct fix. If these files really have different black levels per channel those are probably encoded in the metadata itself and just need to be read. Specifying blackpoints in cameras.xml is only for formats that don't have it in metadata. We had a report in the past of a file that needed blackpoint as 0 in a very high-iso and low light shot but normal blackpoints for normal shots. That was in my backlog somewhere.

If there is a format that actually does this (having fixed blackpoints that are different per channel) it can just be implemented the same place where the rest of <Sensor> is done to apply to all formats. The only reason RAF fiddles with these at all is that because of the rotation code it ended up not using the normal code path and having to reimplement these bits.

**Comment by hanatos** [comment]
hm. there seems to be indeed a tag with the black levels in the file:

exiftool -n -D DSCF3831.RAF | grep Black
61450 Black Level                     : 253 258 258 253

**Comment by hanatos** [comment]
hm. i'm now reading the metadata from the raw file.

just a note on this specific raw (x100): it's a bayer pattern (non-rotated,
non-xtrans, no-bs). i still don't know what you mean by the regular place
where this should be done, i'm just grabbing the exif tag entry where the
black point is set (also gave it a probably nonsensical name in the list of
tags).

i was noting some issue with the blackpoint not being picked up in the
preview pipeline though. so the navigation view still has the green cast :/

**Comment by LebedevRI** [comment]
>i was noting some issue with the blackpoint not being picked up in the
preview pipeline though. so the navigation view still has the green cast :/

Because preview pipeline is demosaiced, https://redmine.darktable.org/issues/10978, so that is totally expected.
One more pin into the coffin of pre-demosaicing, should be gone in my wip MIP_F rework branch.

**Comment by pedrocr** [comment]
On Wed, May 18, 2016 at 9:05 AM, hanatos <notifications@github.com> wrote:
>
> hm. i'm now reading the metadata from the raw file.
>
> just a note on this specific raw (x100): it's a bayer pattern (non-rotated,
> non-xtrans, no-bs). i still don't know what you mean by the regular place
> where this should be done, i'm just grabbing the exif tag entry where the
> black point is set (also gave it a probably nonsensical name in the list of
> tags).

Almost all decoders call RawDecoder::setMetadata() at the end of
XDecoder::decodeMetaDataInternal(). As is documented in RAF that's not
possible because we often need to rotate the image:

```cpp
  // This is where we'd normally call setMetaData but since we may still need
  // to rotate the image for SuperCCD cameras we do everything ourselves
```

> i was noting some issue with the blackpoint not being picked up in the
> preview pipeline though. so the navigation view still has the green cast :/

Probably this bug:

https://redmine.darktable.org/issues/10978

To fully fix it the preview pipe needs to demosaic into
RGGB/CYGM/RGBE, which according to discussions during the CYGM stuff
is not allowed because the fourth channel is for alpha.

Pedro

**Comment by hanatos** [comment]
On Wed, May 18, 2016 at 8:22 PM, Roman Lebedev <notifications@github.com>
wrote:

> i was noting some issue with the blackpoint not being picked up in the
> preview pipeline though. so the navigation view still has the green cast :/
>
> Because preview pipeline is demosaiced,
> https://redmine.darktable.org/issues/10978, so that is totally expected.
> One more pin into the coffin of pre-demosaicing, should be gone in my wip
> MIP_F rework branch.
>

yeah, that's what i thought too. i did merge your branch and try with that,
but for whatever reason it still didn't work (may have been me doing it
wrong though, i was in a rush..)

**Comment by hanatos** [comment]
> The code looks fine to me, pretty much what I'd have written too.

cool, thanks for checking. so we merge and let's take care of the mipf pipeline madness separately?

**Comment by pedrocr** [comment]
It's ok to merge as long as rawprepare is already saving the blackpoints to the history stack for all images, even old ones, which I'm not sure is the case. If not this will break history stacks although hopefully by not much. Actually for old history stacks before rawprepare we will definitely regress them as there's nothing there.

Running the regression testing scripting would show the differences although it will show differences even if rawprepare is already doing the right thing (as it's not reusing the xmps from one run to the next). To run it:

```sh
$ cd tools/regression_tests/
$ ./fetch-samples
# Go get your favorite beverage while it downloads the full rawsamples.ch archive for the first time (the next times are incremental)
$ ./compare master rawspeed-raf-blacks Fujifilm
# Drink your beverage as it compiles both versions and then runs each file through darktable-cli from both versions and compares them
# I added Fujifilm as an argument so it doesn't run through the whole collection
$ cd comparison/
$ firefox index.html # or whichever browser you prefer
# This will show you a nice summary of the run like the ones at http://darktable.pedrocr.pt/
```

**Comment by hanatos** [comment]
those regression tests are cool!

and yes, there will be differences (at least to files that were imported before rawprepare even existed..), i don't see how we can do anything about it. unless we want to run rawspeed with a legacy-mode timestamp that dynamically checks out old code and recompiles it as needed :)

so i'd say this is a bugfix and affected users will be surprised in a good way when looking at old shots.

**Pull request merged**
