### PR TITLE
drawn masks: rework of shape rendering

### PR DESCRIPTION
**Pull request by upegelow**
This work is mostly performance related. We optimize rendering performance and mask combination for the different shapes.

Part of the performance gain is re-invested into better rendering of circle/ellipse/gradient in cases of high scale factors (addressing #3547).

### CODE REVIEW

**Comment by upegelow** [comment]
Rework on omp is needed.

**Comment by TurboGit** [comment]
Can you fix the conflict ? Thanks!

**Comment by upegelow** [comment]
> Can you fix the conflict ? Thanks!

Rebased.

**Comment by TurboGit** [comment]
I have rescheduled this for 3.2 as it is quite impacting. Is that ok with you? Or do you feel this to be ready for 3.0.1?

**Comment by TurboGit** [comment]
Merged in master.

**Pull request merged**
