### PR TITLE
[safe copy] mark deprecateed modules as unsafe too

### LINKED ISSUE #7249: Copy History of a b/w image with channelmixer as part of edit and paste it onto an image which does not turn B/W
Current master.

Old edit with channel mixer that has converted the image to b/w.
CTRL+C to copy history.
History copy  mode is in overwrite mode.
ctrl+v on an image edited in DT with channelmixer deprecated.

Image does not turn b/w as channelmixer is not pasted.

### PR DESCRIPTION
**Pull request by johnny-bit**
copy parts dialog by default as unsafe module unchecked. However
it doesn't have deprecated modules unchecked.

This change marks deprecated modules as deprecated too.

Fixes #7249

### CODE REVIEW

**Comment by parafin** [comment]
Could you provide some motivation for this change? It's not obvious to me, that it's needed or a good thing.

**Comment by johnny-bit** [comment]
Sure!

Pascal made "safe copy" functionality and then matched safe flag behaviour in copy parts dialog match by default what happens when you copy via copy operation. However as it turns out deprecated modules are also not copied in safe copy mechanism, so this change only makes copy parts dialog match by default full safe copy functionality.

**Comment by parafin** [comment]
OK. Next question is then why not copy deprecated modules?

**Comment by johnny-bit** [comment]
hmmm... Fair point.

It's decided in `_is_module_to_skip`

Which I should've been using instead of directly checking flags as it's unnecessary copy...

TBH - I'd consider deprecated modules still "safe to copy"...
and "unsafe" modules in most cases depend on whether:
- source and destination images have the same camera maker & model (white balance, rotate pixels)
- same camera maker, model, iso (black point... also imo denoise profiled should be marked unsafe but it isn't as damaging as black point )
- same camera maker, model, lens, focal, aperture... (lens correction)

orientation can still be unsafe to copy imo.

the problem then becomes - in copy parts dialog you don't know "destination" so you can't make checks with iops... and I have no idea how would the source<->dest checks work ;)

Or... maybe make "safeness" configureable. EG in my normal case I have one camera and in times before color calibration i copied white balance often, so I would be tempted to say "yeah, white balance is safe, no prob, i know what I'm doing" :P

**Comment by TurboGit** [comment]
To me this sounds ok. We discourage copying deprecated modules, seems fine. No big deal since the module can still be selected manually, we are just speaking of the default selection. If this is ready (I see some discussion started) let me know I'll merge.

**Comment by johnny-bit** [comment]
This is (IMO) completely ready then :)

**Comment by TurboGit** [comment]
So merging now. Thanks for all your work.

**Pull request merged**
