### PR TITLE
lens: fix transform routines.

### PR DESCRIPTION
**Pull request by TurboGit**
This fixes the position "jump" when for example adding a circle
mask in exposure module while the lens correction one is activated. Yet,
the circle and the actual area of the effect are not fully overlapping.

### CODE REVIEW

**Comment by TurboGit** [comment]
Note that to me, the effect (on exposure module) is correct as it does keeps the same position on the image with and without the lens correction applied.

But the mask is wrong as it keeps the screen position but not the image position and then goes out of sync with the actual position of the effect.

**Comment by TurboGit** [comment]
Ok, inverting transform and backtransform seems to fix the issue.

**Comment by jenshannoschwalm** [comment]
Yeah! Almost done :-)
There is one minor problem remaining, the displayed circle and borders are not always circles but sometimes are like this
maskshot

I guess the reason for this is that you approximate for closeness on the horizontal dist1 only. Maybe
do another iteration on dist2 and take the middle?
(The direction of the shift depends on the position in the picture btw and might jump.) 

Otherwise, perfect!

**Comment by TurboGit** [comment]
@jenshannoschwalm : Indeed, I have been able to reproduce. should be fixed now. can you test the new version? Thanks.

**Comment by jenshannoschwalm** [comment]
Done! Congratulations. (Surprised this works btw)

**Comment by TurboGit** [comment]
Thanks for testing.

**Pull request merged**
