### PR TITLE
Fix expand/collapse when using reset/presets lib buttons.

### PR DESCRIPTION
**Pull request by TurboGit**

### CODE REVIEW

**Comment by elstoc** [comment]
Are you going to fix the iop modules (on/off button) under a separate PR?

I won't have time to test this until this evening

**Comment by todd-prior** [comment]
@kofa73 pointed me to this thread... I have an issue with the diffuse or sharpen module in Windows...no other module that I have tried but clicking the hamburger selects directly a preset...its like the pop-up menu does not behave as it should.... That module has a long list of presets and it seems most times to land on deblur medium or one that is close rather than just bringing up the list... I will have to dig deeper to see what is up on my end...but I don't recall any thing that i changed...THis is behaving this way on my previous build from a few days ago and lat night which was 5.1.0

**Comment by dterrahe** [comment]
This would happen if the preset list were so long that it could not fit completely either below or above the button. It would then end up obscuring the button and be underneath the mouse immediately after it was pressed. When you then _release_ the mouse, this is interpreted as selecting the preset immediately underneath it. If you _don't_ want to select that one you can continue to hold the mouse button and move to the preset you want before releasing it.

I'll try to think if there's a clean way to detect this situation and avoid having the button release act as a selection if the mouse hasn't moved since pressing the button.

Related, it would be nice if presets could be grouped, like styles, using |, and put in multi-level submenus so that the top level doesn't get too long. Probably not high priority for most and needing support in multiple places (preferences dialog for example).

**Comment by todd-prior** [comment]
I think you are spot on...I also didn't know about holding the click so I can do that for now and I agree that being able to group things wherever it makes sense would be a nice addition....thanks for taking the time to rationalize this for me... I appreciate it as always....

**Pull request closed without merging**
