### PR TITLE
ashift : various small fix

### LINKED ISSUE #10102: rotation and perspective: clicking buttons should enable module
If you try to click on one of the structure buttons in the "rotation and perspective" module without first enabling it, the message "data pending - please repeat" appears on the screen.

Clicking on any of the structure buttons in the "rotation and perspective" module should activate the module and give it focus (the same as clicking on a slider/combo does) and then engage the appropriate edit mode.

### LINKED ISSUE #10103: rotation and perspective: remember auto-crop setting (or default to "largest area")
I suspect most people will use the rotation/perspective module with similar settings each time. For example, I will probably want automatic cropping to always be set to "largest area". 

Could we set this to always default to the last user-chosen value, or to "largest area".

I believe auto-crop is set to "yes" by default in crop & rotate.

### LINKED ISSUE #10104: rotation and perspective: auto-crop failure
1. Discard history
2. Expand rotation & perspective module
2. Choose auto-cropping = "largest area"
3. Choose the "rectangle" structure definition button and define keystone correction
4. Click on the "correct horizontal & vertical" button
5. Collapse the module

Auto-cropping doesn't work - acts the same as if auto-cropping = "off"

The above is a consistent reproducer for me, but I have seen it working both correctly and incorrectly using this and other structure buttons.

### PR DESCRIPTION
**Pull request by AlicVB**
this fix #10102, this fix #10103, this fix #10104

@TurboGit : sorry for this messy PR : that's just to avoid too many rebasing...
This contain : 
1. fix direct click on structure buttons when module is disabled
2. ensure auto-crop area is saved after auto-fit
3. default auto-crop parameter to "largest area" to mimic c&r and save last choice for next use.

Note that with point 1, I've done a little cleaning and removed an unused parameter. This mean that the parameter structure has changed.
Considering the very short delay between the ashift rework merge and this PR, I've thought it was not worth the pain to update param version. So early tester may see a "version mismatch" message...
@TurboGit : if it's not ok for you, I can also update module version... just ask :)

### CODE REVIEW

**Comment by AlicVB** [comment]
thanks to @elstoc suggestion, the last autocrop value is also save and reused as default params for next images.
This "last state" default is override by any auto-applied preset (for those who absolutely want to always have the same default value, whatever their last choice)

**Comment by elstoc** [comment]
Autocrop still has an issue when used with right-click-drag to set the angle.

1. Discard history
2. Expand rotate/perspective
3. Right-click-drag to set horizon
4. Collapse module
5. Rotate is applied but auto-crop is not

Same thing happens when using the slider, but not if you manually enable the module first.

**Comment by TurboGit** [comment]
> @TurboGit : if it's not ok for you, I can also update module version... just ask :)

Ok for me! We've done that for others new modules. Users of the dev versions are  aware of such possible little breakage.

**Comment by elstoc** [comment]
While you're working on ashift, would you mind changing the "rotation" alias to read "rotate" instead. It should already be possible to search on "rotation" because it's part of the module name.

**Comment by TurboGit** [comment]
> While you're working on ashift, would you mind changing the "rotation" alias to read "rotate" instead. It should already be possible to search on "rotation" because it's part of the module name. I keep searching for rotate and wondering why it's not there!

Done, plus added crop and reframe in aliases too.

**Comment by AlicVB** [comment]
@elstoc : good catch. This should be fixed by last commit. Thanks for your tests

**Comment by elstoc** [comment]
Thanks @AlicVB I _think_ I've run out of ways to break it now.

**Comment by johnny-bit** [comment]
The CI failure is just packages, re-kick it and it should be fine

**Review by TurboGit — APPROVED** [review]
All good to me, thanks !

**Pull request merged**
