### PR TITLE
variables: add the vairable $(DARKTABLE_VERSION)

### LINKED ISSUE #10440: [FR] able to add darktable version in the export metadata
**Is your feature request related to a problem? Please describe.**

When exporting, I have highly reduced the number of information I would like to let people see in metadata:
- copyright
- who has created the picture
- ...
- for creatorTool, I would like to put "darkable" + <version>
because so many information are shared I do not want to let in the export metadata.
But it is not proposed to get the darktable version as a variable for export as I can see in the manual, while you allow so many possibilities ...
If I need/want to export again the picture and see differences with the current one, it will be difficult to understand why.
And, I want to let people see what is possible to get with darktable by keeping this in metadata.
**Describe the solution you'd like**

Proposing a variable to expose the current darktable version would be helpful.

**Alternatives**

Exposing the darktable version with an export variable.

**Additional context**

thank you,
regards,
Yvan Radenac

### PR DESCRIPTION
**Pull request by phweyland**
fixes #10440

### CODE REVIEW

**Comment by ralfbrown** [comment]
There's already a variable DARKTABLE.VERSION for watermark text (src/iop/watermark.c line 404).  Should we be consistent?

**Comment by phweyland** [comment]
> There's already a variable DARKTABLE.VERSION for watermark text (src/iop/watermark.c line 404).

Correct. However this information is not available for metadata export.

> Should we be consistent?

For me the consistency would be to refactor watermark to use only standard variables (and not its own interpreter). If that's what you mean, I would answer yes, but it's not an easy task if we want to avoid breaking old edits. If not, please elaborate a bit more.

**Comment by ralfbrown** [comment]
I was thinking only about the variable name, but agree that ultimately a deduplication of the code would be best.

**Comment by phweyland** [comment]
Maybe for 3.8.1 ?

**Review by TurboGit — APPROVED** [review]
Can't be safer :) Looks good and ok for 3.8.1. Thanks.

**Comment by elstoc** [comment]
We'd be better to avoid anything that requires documentation in a fix release - this was one of the reasons that I suggested only putting features in the main releases. Either way this won't be documented until version 4.0.

**Comment by TurboGit** [comment]
@elstoc : Good point indeed, we can revert if you like, such "feature" can really wait to me. Let me know.

**Comment by elstoc** [comment]
IMO we should keep features (even small ones) out of point releases. The main issue for me is that dtdocs doesn't have the facility to maintain two translation branches so it's impossible to provide new translated documentation outside of the normal release cycle. Though it's nice to be consistent too

**Comment by phweyland** [comment]
For me both ways are OK.
This kind of change doesn't break the doc. It is just undocumented, which is fine to me.

**Pull request merged**
