### PR TITLE
import: move preferences to module parameters (under expander)

### LINKED ISSUE #7707: [import dialog] please partially revert #7435 or enhance it
[edit] corrected issue number to #7435 
**Is your feature request related to a problem? Please describe.**

To a wide extend I like the idea behind #7050 
What happened now with import dialog, to me is _like throwing the baby out with the bathwater_

I think the former situation with import dialogue worked for years and was pretty logic.

Especially for this frequently used setting, hiding it in the hamburger menu, is not a good thing.

**Describe the solution you'd like**
@phweyland please bring back the settings to where they have been before #7435 

I understand, it might brake the ability for presets, hence pls. see "Alternatives", which is more an enhancement rather than alternative.

**Alternatives**
From discussions on IRC:
Dialogue-Preferences could/should be one-time override of the  saved preferences.

Means: setting the options from the preferences dialogue (now from the hamburger menu) would store the import options as preferences (that persist from one session to the next). The same options in the import dialogue should allow you to override those defaults just for that import without overriding the saved prefs.

### PR DESCRIPTION
**Pull request by phweyland**
fixes #7707

Following discussion on #7717

### CODE REVIEW

**Comment by TurboGit** [comment]
Now that I have change the label to be shorter I see that the dialog does not look good, I would expect the label to be aligned on the left and the box or entry to be on the right. Here is what we have:

image

**Comment by phweyland** [comment]
I look at this.

**Comment by phweyland** [comment]
Looks better ?

image

**Comment by TurboGit** [comment]
Yes, looks better to me, but I don't have the "from xmp" on my side.

**Comment by phweyland** [comment]
> I don't have the "from xmp" on my side.

You get it when you disable "write xmp"
I'll push a PR.

**Comment by TurboGit** [comment]
Indeed, but this should be dynamic. You need to restart dt to see/hide this. Probably worth another PR :)

**Comment by AxelG-DE** [comment]
I am VERY happy and o.k. with final result
@phweyland **thank you!**

**Comment by phweyland** [comment]
> I am VERY happy and o.k. with final resul

Thanks for the feedback ! :smiley:

**Pull request merged**
