### PR TITLE
preferences: make the changed preferences with a little tick character.

### PR DESCRIPTION
**Pull request by TurboGit**
After using the text in italic/bold I find it a bit disturbing. The bold looks a bit like the section labels.

I find this proposal nice and less disturbing.

### CODE REVIEW

**Comment by johnny-bit** [comment]
I think you can do that with css... Also css would allow dynamic stuff I'm working on.

**Comment by TurboGit** [comment]
Perfect, closing this then.

**Comment by johnny-bit** [comment]
Question - how best to indicate changed preference? @Nilvus ?

**Comment by Nilvus** [comment]
No idea actually but yes your update was in good direction but too disturbing. I will think about that ASAP.

**Pull request closed without merging**
