### PR TITLE
qap : ensure to have the right widget label

### LINKED ISSUE #8908: Inconsistent text for filmicrgb in quick access panel
**Describe the bug/issue**

Simple one but don't know where to update that. See screenshot below:

image

Should be so shadows/highlights balance and middle tones saturation if using v4 or v5 (that's the case here). About middle tones saturation and extreme luminance, even if I use v4 or v5, I don't see middle tones saturation in quick access panel choices.

### PR DESCRIPTION
**Pull request by AlicVB**
fix #8908 

the root cause is that some module (here filmic) register automatically the widget with the default name of the parameter and then change the label afterward. So we can't rely on the accel name anymore...

@dterrahe : I wonder if you have take that in account in your new shortcuts work ?? (not tested)

### CODE REVIEW

**Comment by Nilvus** [comment]
I will not have time to test this this week. I hope that fix too the text about middle tone saturation and extreme saturation (first is for filmic v4 and v5 and second for filmic v3). Only last (filmic v3) appear in quick access panel list. See my issue if needed.

**Comment by dterrahe** [comment]
> @dterrahe : I wonder if you have take that in account in your new shortcuts work ?? (not tested)

No, I've just ported the bug forward :-)

Reason being, that I think this requires support in bauhaus (or each module that changes labels dynamically) for a correct fix and/or can't be fixed completely.

The problem that I think this PR doesn't solve (I haven't tested it!), is that the color science combo can also be added to the qap (or accessed via a shortcut while the qap is active). When the value is changed from v3 <-> v4 or v5, the module directly changes the label (also in qap). When we now switch away from qap, the old label, that was stored when the qap was activated, gets put back on the widget, but this is now outdated. Possibly same thing would happen when changing images with different color science versions while in the qap?

As part of the bauhaus overhaul (following merging of Input NG) we could have bauhaus directly support two "label-modes" one  _with_ section (for the qap) and one _without_ (in normal module). Then the qap setup and breakdown code would not have to mess with the labels at all and this issue would go away.

Separately, there's the issue of what to call a widget that has two modes in the qap add-widget menu. I do not think it would be correct to change the label there depending on which the active image happens to have selected. Since adding it to the qap would mean adding both "variants". Just listing a few possibilities:
1. change the "default" (introspection etc) name in filmicrgb to the name in the latest/default version (now wrong in hopefully < 50% of the time).
2. change the original name (in introspection) to be a combination of both meanings "mid-tones/extreme luminance saturation". The widget label itself will still be one or the other as per the bauhaus approach described above. Can also apply to section names. dt_bauhaus_widget_set_label is only used to link widgets to actions (inputng) in gui_init, so later changes don't break this association.
3. split into two widgets (both can be linked to the same params field) and instead of changing the label, hide one or the other. Both widgets could be added to qap, but at any time one of them would be inactive.

Depending on whether both meanings are equally likely or whether the newer meaning in most cases supplants the older (v5?) my preference would be 2 or 1.

After merging Input NG, it will not be too hard to add an extra functionality to the "define shortcuts" mode to directly add a widget to the qap by ctrl-left clicking on it. That would make the name in the add widget menu less important.

**Comment by AlicVB** [comment]
I put this PR as WIP for the reasons above : 

> The problem that I think this PR doesn't solve (I haven't tested it!), is that the color science combo can also be added to the qap (or accessed via a shortcut while the qap is active). When the value is changed from v3 <-> v4 or v5, the module directly changes the label (also in qap). When we now switch away from qap, the old label, that was stored when the qap was activated, gets put back on the widget, but this is now outdated. Possibly same thing would happen when changing images with different color science versions while in the qap?

you're right... and I agree that it should better be solved directly inside bauhaus. I don't think it will be too difficult. I'll have a look...



> Separately, there's the issue of what to call a widget that has two modes in the qap add-widget menu

true too... currently, what is shown in the menu, is the text corresponding of the current image filmic version. This may not be the version used for other images...
The main problem we have here is that "alternative" labels can't be guessed from the beginning, so the only solution I can see would be to extend the introspection thing to include alternative name here (but I absolutely don't know how introspection work, so I've no idea how hard this can be...)

For the record alternative names are not only used in filmicrgb, but in may other modules (ahift, bilat, channelmixerrgb, ...) So that need to be solved "globally"

I'll give a try to the bauhaus change for the first point...

**Comment by aurelienpierre** [comment]
Alternatively, it might be more simple to use 2 differents sliders for filmic, and hide/display each on on-demand when relevant. That way, one slider only has one label.

**Comment by AlicVB** [comment]
@aurelienpierre : no, there's other modules that also change the lable on the fly : ashift, bilat, ... so that would only be a temporary fix.
Better try to fix that cleanly ;)

**Comment by AlicVB** [comment]
Last commit slightly extend bauhaus structure to handle here directly extended widget labels (section + label).
This is way more clean and fix @dterrahe issue with widgets labels.

The second point is not modified : in the list of available widget, you see the label as it is in *current* module configuration. Fixing that would require way more work, and it would be better to fix it along with @dterrahe work.
Anyway, this PR enhance this point because imho we can imagine that the current module configuration will be the one the user use in most cases... Previously you always see the initial widget name (so in the filmic case, the one used with old color sciences)

**Comment by dterrahe** [comment]
Why not simply save the _section_ (and use it to build the "extended label" when needed) rather than storing the extended label?Having the section might have other uses too in future, whereas extended label is very specific.

**Comment by AlicVB** [comment]
> Why not simply save the _section_ (and use it to build the "extended label" when needed)

to avoid some computation which would be done on each widget redraw event (possibly a lot). if needed by other parts of the code, I would even prefer to store both : section *and* extended_label...

**Comment by dterrahe** [comment]
Compared to drawing the slider and printing the (floating point) number, all the font generation, concatenating two strings...

**Comment by dterrahe** [comment]
Remember, most widgets have section == NULL, so you'll basically have two copies of the same _label_ everywhere.

**Comment by AlicVB** [comment]
@dterrahe : right, let save little bit of memory... and offer the section text for future use ;)

**Review by TurboGit — APPROVED** [review]
Works for me, testing ok. Code seems safe enough. Thanks.

**Pull request merged**
