### PR TITLE
control_jobs: fix macos build for import time

### PR DESCRIPTION
**Pull request by kmilos**
Attempted fix for https://github.com/darktable-org/darktable/issues/12446

@MStraeten @phweyland Please test

### CODE REVIEW

**Comment by MStraeten** [comment]
thanks, now build is successful

**Comment by TurboGit** [comment]
I'll let @phweyland double check and validate as the Linux code has also been changed (albeit slightly but yet :).

**Comment by kmilos** [comment]
Yep, I took advantage of some backward compatible defines that, judging from the docs and header files, should be available on both macOS and Linux ;)

**Comment by phweyland** [comment]
I haven't the knowledge to check the code details, but I've tested on debian and this still works !
Thanks

**Review by phweyland — APPROVED** [review]
Looks OK for me! Thanks

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
