### PR TITLE
left & right panels resizing

### LINKED ISSUE #3710: Asymmetric side panels
**Is your feature request related to a problem? Please describe.**
I'd like to maximise the amount of space available for the image while editing and often end up hiding the left panel while editing and then having to unhide it to work with my history stack/snapshots. 

**Describe the solution you'd like**
It would be great if we could set the left and right panel widths independently. This would allow me to keep my left panel narrow and my right panel wide and give as much space as possible to the image, while reducing unnecessary clicks.

**Describe alternatives you've considered**
I've reduced my font size and reduced the width of the panels as much as I can.

### PR DESCRIPTION
**Pull request by AlicVB**
This fix #3710 
- this allow user to change the width of left & right panels with the mouse.
- there's no change to the ui.
- sizes are store per panel, views & layout, like panels state.
- default size is set in the code to 350.

### CODE REVIEW

**Comment by GLLM** [comment]
Fantastic @AlicVB : one more thing we can do with the mouse in DT :)
Thanks a lot !

**Comment by Nilvus** [comment]
Good work @AlicVB. Just two things :
- Panel size setting on preferences seems to be now not more useful. Maybe this setting could be removed as your PR overwrite this setting.
- Is it easily possible to not have minimum setting to let hide a panel with this resizing option. For example, moving the right panel to the maximum right will hide the panel (like the Maj+Ctrl+r shortcut) ?

**Comment by AlicVB** [comment]
> Panel size setting on preferences seems to be now not more useful. Maybe this setting could be removed as your PR overwrite this setting.

good catch, i'll remove that from rc file

> Is it easily possible to not have minimum setting to let hide a panel with this resizing option. For example, moving the right panel to the maximum right will hide the panel (like the Maj+Ctrl+r shortcut) ?

No, currently, the panel width are forced to stay between 150 and 500, I've tried to set the lower bound to 0, but it's not really good, as the "dragging" zone is inside the panel...
But I'll try another approach : hiding the panel by double click on the dragging zone. It'll be less discoverable, thought...

**Comment by AlicVB** [comment]
@Nilvus : I've added what is mentioned in my last post, with configurable min-max values for panels width

**Comment by Nilvus** [comment]
@AlicVB : Thanks for that. I find a bug : after double-clicking a panel to hide it, you have to press two times the need to shortcut to show again the panel. That's not wanted as when we use the shortcut, we just have to press it one time to hide or show the panel.

**Comment by ptilopteri** [comment]
I see the same on openSUSE Tumbleweed 
git84.c19d69fe3

**Comment by AlicVB** [comment]
yep, it's not directly related to this PR and there's other "small" problems like this one with panels shortcut...
I plan to fix them here asap...

**Comment by TurboGit** [comment]
Really nice and working good. I'm now eagerly waiting for 3.0.1 to be out :) Thanks!

**Comment by Nilvus** [comment]
> Really nice and working good. I'm now eagerly waiting for 3.0.1 to be out :) Thanks!

Me too. We now have no more than 31 PR waiting for 3.0.1 and quite some exciting ones (like this one). Just huge on 10 days to 3.0 release.

**Comment by AlicVB** [comment]
So I've fix some bugs and done some small changes : 
- refactor lot of code to ensure that everything about panel states work per view / layout
- so now borders (the ones with arrow) are toggle per view/layout (accel 'B' as before)
- by default lighttable full preview didn't show them.
- fix some small ui glitch (arrow sizes, borders needed 2 clicks, ...)
- make the top panels works the same way as bottom panels. Successive clicks on border arrow show : header/filmstrip + toolbar > header/filmstrip > nothing > toolbar > header/filmstrip + toolbar. So every possibility is accessible without shortcuts.
- rework the "toggle all panels" (TAB) to fix corner cases : when one either hide all panels manually or show manually panels after TAB press

@TurboGit : I just see that you have already review this PR (github mails doesn't seem to mention reviews). I've requested you to review it again, but if you prefer, I can remove this last commits and do another PR after this one is merged... Just ask (and sorry for the mess)

**Comment by TurboGit** [comment]
@AlicVB : No problem, I'll review again.

**Comment by Nilvus** [comment]
@AlicVB : with next branch (for 3.0.1), using all 3.0.1 PR, some personal states are lost. For example, I have deactivated borders on all views. When launching next branch, on first launch, borders are here on all views. I suppose it is related to this PR so is it possible to keep our personal configuration when updating to next 3.0.1 release ?

**Comment by Nilvus** [comment]
I also have some not wanted behaviour with two shortcuts : top and bottom ones.Bottom one need to be pressed two times to be enabled or disabled. Top one have a different behavior : press it switch between disable top panel, disable header one (usual Ctrl+h still works) and then enable header then top panel. Why not for this last one but will need to change again the manual.

**Comment by TurboGit** [comment]
> I also have some not wanted behaviour with two shortcuts : top and bottom ones.Bottom one need to be pressed two times to be enabled or disabled. Top one have a different behavior : press it switch between disable top panel, disable header one (usual Ctrl+h still works) and then enable header then top panel. Why not for this last one but will need to change again the manual.

Should be better now on next branch Can you test again?

**Comment by Nilvus** [comment]
> > I also have some not wanted behaviour with two shortcuts : top and bottom ones.Bottom one need to be pressed two times to be enabled or disabled. Top one have a different behavior : press it switch between disable top panel, disable header one (usual Ctrl+h still works) and then enable header then top panel. Why not for this last one but will need to change again the manual.
> 
> Should be better now on next branch Can you test again?

Still have same not wanted behavior. Tested on last commit d201613657e6fc88f9a9819f13a526d708d2bd73. Nothing changed. Anyway, I tested with a new default darktablerc file and two times press is solved. So, something need to be updated on darktablerc that are not actually. After some search, find these lines to be removed from darktablerc with this new PR:

plugins/lighttable/timeline/visible=TRUE

Having this line cause the two press shortcut behavior. Removing it make all works ok and even if the timeline view is hidden or visible, this line is not anymore written.

I've also found (but didn't search at this time) that I was not having the overlay vertical gradient on lighttable thumbnails. WIth a new darktablerc file, this gradient appear.

So, it will be really necessary to find a way to make a real good cleanup on darktablerc existing files for obsolete lines. This cause some bugs. I will search for this overlay gradient, which line and propose an issue.

Now, I have same behaviour (new one but good one) on top and bottom : the shortcut disable panel, then disable the second panel (filmstrip/timeline view or header bar), then enable this one, then enable bottom. Quite circular and logical behavior.

**Comment by AlicVB** [comment]
@Nilvus @TurboGit : I'll have a look tomorrow. I want to include a fix to #3838 there too (btw, I suspect the last mentioned problem is closely related to #3838 ...)

**Comment by TurboGit** [comment]
@AlicVB : Thanks! Please can you do the fix on top of my next branch I'm currently preparing? This is important as I have fixed some issues related to this.

**Comment by AlicVB** [comment]
no pb, just indicate which branch it is, once it's ready !

**Comment by TurboGit** [comment]
It is ready, the branch is called "next" and is pushed on origin (so in the main repository).

**Comment by AlicVB** [comment]
@TurboGit : 
As this PR is merged in 'next' branch, I've done a new branch on top of this 'next' branch (btw, for my curiosity, why don't you have used the master branch, as before ?)
The new branch is here : https://github.com/AlicVB/darktable/tree/panels_2
(I'm not sure if it's possible/how to do a PR on a specific branch)

The branch include following change/additions : 
### rework/enhance your change about filmstrip hide/show : 
- save filmstrip/timeline state per view/layouts
- for all view except lighttable, show/hide filmstrip by toggling bottom panel visibility (bottom panel contains only filmstrip there). This avoid strange behavior when clicking on border button if filmstrip has been hidden (I've removed your routine in lib.c/h as this is as 2 lines code, and it's not universal)
- for all lighttable layouts except culling and preview : same as other views, but with timeline
- for lighttable culling and preview, it's a bit more tricky, as we can have both timeline and filmstrip. So consecutive CTRL-F show : filmstrip+timeline => timeline => bottom panel hidden => filmstrip => filmstrip+timeline
- due to this last change, rename lighttable CTRL-F shortcut to show that it act on filmstrip and timeline.
- fix some part of of code where timeline or filmstrip has been forgotten.

### rework filmstrip/timeline resizing : 
- refactor to use same routine as for left/right panels resizing
- this allow to set heights per view/layouts
- ensure that timeline and filmstrip keep same sizes when used together

### partially revert your commit 048971a06f506639d2a0b2f4d7f11eb78dfbe0f4
- when restoring panels in "all collapsed" state, we want to keep old panel state values to recover them after exiting this state (by another TAB)
- with your commit, if you have all panels shown, you press TAB, exiting dt and relaunch, if you click another time on TAB, you don't recover your panels state...

I hope you'll agree with this changes, even if I've rework some of your work...

**Comment by AlicVB** [comment]
@Nilvus :
> with next branch (for 3.0.1), using all 3.0.1 PR, some personal states are lost. For example, I have deactivated borders on all views. When launching next branch, on first launch, borders are here on all views. I suppose it is related to this PR so is it possible to keep our personal configuration when updating to next 3.0.1 release ?

Yep, it's due to the fact that all states/sizes are now stored per view/layouts, so their path have changed. It should be possible to add some code to "recover" old settings and start from there. The problem is that it would result in a big amount of added code in many places...
I'm not sure it's worth the pain, considering that : 
- it doesn't concern lot of settings
- all of them are easily recoverable
- you'll have to retweak most of them anyway considering the new features that is allowed...
- it'll add lot of complexity and maintenance hazards...

here are all the setting that will be "lost" (not sure to be exhaustive) : 
- side panels + filmstrip/timeline sizes
- border arrows visibility
- (to be confirm) header hiding

**Comment by TurboGit** [comment]
@AlicVB: next branch is needed as this will be merged in master and 3.0.1 and so I've been preparing this since some time and this branch is created from release-3.1.0.

**Comment by TurboGit** [comment]
@AlicVB: fine to rework my work, improving on top other's work is what we all do.

**Comment by TurboGit** [comment]
@AlicVB: btw where is your new branch?

**Comment by AlicVB** [comment]
@TurboGit : here https://github.com/AlicVB/darktable/tree/panels_2
you can look at the 4 last commits

I've also tried to do a PR or the 'next' branch here : #3864 it should be easier to review

**Comment by Nilvus** [comment]
> @Nilvus :
> 
> > with next branch (for 3.0.1), using all 3.0.1 PR, some personal states are lost. For example, I have deactivated borders on all views. When launching next branch, on first launch, borders are here on all views. I suppose it is related to this PR so is it possible to keep our personal configuration when updating to next 3.0.1 release ?
> 
> Yep, it's due to the fact that all states/sizes are now stored per view/layouts, so their path have changed. It should be possible to add some code to "recover" old settings and start from there. The problem is that it would result in a big amount of added code in many places...
> I'm not sure it's worth the pain, considering that :
> 
>     * it doesn't concern lot of settings
> 
>     * all of them are easily recoverable
> 
>     * you'll have to retweak most of them anyway considering the new features that is allowed...
> 
>     * it'll add lot of complexity and maintenance hazards...
> 
> 
> here are all the setting that will be "lost" (not sure to be exhaustive) :
> 
>     * side panels + filmstrip/timeline sizes
> 
>     * border arrows visibility
> 
>     * (to be confirm) header hiding

Ok, indeed, you're right. Better to lost them and reactivate them than spent time to make code (and one use).

**Pull request merged**
