### PR TITLE
tackle GCC10 problems with build warning flags

### LINKED ISSUE #5377: GCC10.1 (probably) compilation spams warnings
When using build.sh as described in the README.md or the manual Windows build instructions on an updated MSYS2 environment on Windows 10 using GCC 10.1, the initial build process spams a lot of warnings such as the following (excerpt). ~~I have not tested this with a manual compilation, but the same warnings may appear there.~~
Edit: this also happens on Fedora 32 with GCC 10.1.

```
[ 16%] Built target rawspeed
Scanning dependencies of target rawspeed_get_number_of_processor_cores
[ 16%] Building CXX object src/external/rawspeed/src/librawspeed/common/CMakeFiles/rawspeed_get_number_of_processor_cores.dir/GetNumberOfProcessorCores.cpp.obj
cc1plus.exe: warning: command-line option '-Wold-style-declaration' is valid for C/ObjC but not for C++
cc1plus.exe: warning: command-line option '-Wmissing-prototypes' is valid for C/ObjC but not for C++
cc1plus.exe: warning: command-line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
cc1plus.exe: warning: command-line option '-Wtraditional' is valid for C/ObjC but not for C++
[ 16%] Linking CXX static library librawspeed_get_number_of_processor_cores.a
[ 16%] Built target rawspeed_get_number_of_processor_cores
Scanning dependencies of target darktable-rs-identify
[ 16%] Building CXX object src/external/rawspeed/src/utilities/identify/CMakeFiles/darktable-rs-identify.dir/rawspeed-identify.cpp.obj
cc1plus.exe: warning: command-line option '-Wold-style-declaration' is valid for C/ObjC but not for C++
cc1plus.exe: warning: command-line option '-Wmissing-prototypes' is valid for C/ObjC but not for C++
cc1plus.exe: warning: command-line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
cc1plus.exe: warning: command-line option '-Wtraditional' is valid for C/ObjC but not for C++
[ 16%] Linking CXX executable darktable-rs-identify.exe
[ 16%] Built target darktable-rs-identify
```

This seems to apply mostly to the building of rawspeed, but occasionally there is a similar warning later on:

```
[ 26%] Building CXX object src/CMakeFiles/lib_darktable.dir/common/splines.cpp.obj
cc1plus.exe: warning: command-line option '-Wold-style-declaration' is valid for C/ObjC but not for C++
...
[ 35%] Building C object src/CMakeFiles/lib_darktable.dir/common/imageio_j2k.c.obj
cc1plus.exe: warning: command-line option '-Wold-style-declaration' is valid for C/ObjC but not for C++
...
Scanning dependencies of target tonemap
[ 67%] Building CXX object src/iop/CMakeFiles/tonemap.dir/introspection_tonemap.cc.obj
[ 67%] Linking C shared module libtonecurve.dll
cc1plus.exe: warning: command-line option '-Wold-style-declaration' is valid for C/ObjC but not for C++

```

There seems to be something wrong with the compiler warning suppression. It would be preferable to have a warning-free compilation.

### PR DESCRIPTION
**Pull request by johnny-bit**
This fixes in part #5377 - warnings in darktable building are removed for c++ files (meaning unnecessary flag is not enabled for c++ compilation, only for c)

2nd part would be to fix cmake flags in rawspeed.
since darktable-org/rawspeed#235 is marged this fixes #5377 :)

### CODE REVIEW

**Comment by rabauke** [comment]
Needs to be fix in rawspeed as well. (In a separate pull request.)

**Comment by johnny-bit** [comment]
Yup :) https://github.com/darktable-org/rawspeed/pull/235

**Comment by coffeeandspaceships** [comment]
This works for me for the "-Wold-style-declaration" case... will this pattern work if extended to:
```
-Wmissing-prototypes
-Wstrict-prototypes
-Wtraditional
```
cases?

**Comment by johnny-bit** [comment]
those only affect rawspeed library and my PR was merged there so the only thing needed now is to update referenced submodule and it'll work.

**Comment by TurboGit** [comment]
@johnny-bit : this has been merged in rawspeed develop branch but not yet in stable branch which is the one tracked by darktable. Roman will do the necessary on darktable repo when ready.

**Comment by TurboGit** [comment]
Anyway, this is good to go.

**Pull request merged**
