### PR TITLE
[GUI] Fixes to Piwigo export tooltips

### PR DESCRIPTION
**Pull request by victoryforce**
English does not have a separate word `non`. When correcting, I reworded the idea more clearly, because the mention of server "insecurity" may sound intimidating to those who are not tech-savvy.

I also removed the tooltip from the username input field where it was due to a copy and paste error.

### CODE REVIEW

**Comment by TurboGit** [comment]
> because the mention of server "insecurity" may sound intimidating to those who are not tech-savvy.

I'm not sure this is a good move and I do challenge the fact that this is only for tech-savvy people. At least here in France we have campaign to explain what a secure or insecure server is and how to find out about this by looking at the lock in the URL for example. So all in all I find the fact that http:// is tagged as insecure in the tooltip a good thing.

**What do others think about this?**

**Comment by victoryforce** [comment]
> So all in all I find the fact that http:// is tagged as insecure in the tooltip a good thing.

Let me put it this way: all I want is to remove the shortcomings of the current wording:

- There is no such word as "non".
- The wording about the insecurity of the server is a mistake, the protocol is insecure (in the sense of "not protected against interception"), not the server.

These are the facts. It is not so important how the text will be reworded, as long as it corrects these errors (grammatical and factual).

To this I can add my _subjective_ views:

- I don't see the value in the mention of http insecurity in the Piwigo export tooltip. It is hard to imagine that this will be the first place from which the user learns about the insecurity (insecurity in what sense? because nothing is explained here) of the http protocol.

- It is hard to imagine that this characteristic from the tooltip motivates the user to learn more and eventually add https support to his server.

And most importantly:

-  _Actually, if the user has installed a self-hosted piwigo instance, the user probably understands what http and https are without our reminder_.

**Comment by TurboGit** [comment]
> Let me put it this way: all I want is to remove the shortcomings of the current wording:

Ok, so what about:

`specify insecure protocol http:// explicitly if that protocol is required`

**Comment by victoryforce** [comment]
> Ok, so what about:
> 
> `specify insecure protocol http:// explicitly if that protocol is required`

Sure. Done!

**Review by TurboGit — APPROVED** [review]
Good to me now, thanks!

**Pull request merged**
