### PR TITLE
colorbalance: refactor SSE, remove SSE version of legacy mode

### PR DESCRIPTION
**Pull request by ralfbrown**
Finishing up work on the old Color Balance module.  Also cleaned out colorspace conversion functions whose SSE versions are no longer called from anywhere.

Passes tests 0000, 0105, and 0106 for the three different modes.  I notice that you accidentally named 0106 the same as 0105, when it's actually colorbalance-lgg.

### CODE REVIEW

**Comment by TurboGit** [comment]
> when it's actually colorbalance-lgg.

I thought it was a typo for legacy... but now I see that it is lift/gamma/gain... So maybe `colorbalance-legacy-lgg`? Ok for you?

**Comment by ralfbrown** [comment]
The Legacy mode is also lift/gamma/gain, but in nonlinear sRGB space instead of linear ProphotoRGB (and without the saturation/contrast adjustments).  The UI doesn't refer to it as legacy, but that's the actual enum used in the code.

**Comment by TurboGit** [comment]
> The Legacy mode is also lift/gamma/gain, but in nonlinear sRGB space instead of linear ProphotoRGB (and without the saturation/contrast adjustments). The UI doesn't refer to it as legacy, but that's the actual enum used in the code.

Ok, will revert to lgg then and will add a readme.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
