### PR TITLE
Fix build of AddressSanitzer with gcc

### PR DESCRIPTION
**Pull request by cryptomilk**
Fix build of AddressSanitzer with gcc

### CODE REVIEW

**Comment by upegelow** [comment]
You might also have a look at compiler-warnings.cmake:

`# should be < 64Kb`
`math(EXPR MAX_MEANINGFUL_SIZE 32*1024)`
`CHECK_COMPILER_FLAG_AND_ENABLE_IT(-Wframe-larger-than=${MAX_MEANINGFUL_SIZE})`
`CHECK_COMPILER_FLAG_AND_ENABLE_IT(-Wstack-usage=${MAX_MEANINGFUL_SIZE})`

Compiling with AddressSanitizer once would hit the stack usage limit and therefore fail. Probably due to the additional stack overhead of asan. Best would be to remove those limits in these cases. IIRC they were introduced to make darktable run on some arcane system which practically had no stack.

**Comment by cryptomilk** [comment]
@upegelow I think that is something for another PR. I think we should correctly detect if those flags are needed or not. It looks like you only need them for musl libc. Which means we should probably try to compile the wb_presets.c in a configure check and if it fails retry with those values.

However for that cmake should be modernized completely. So that those flags are also only set for .c files where they are needed and not for the complete source code.

**Comment by TurboGit** [comment]
Building with:

`./build.sh --asan`

After removing my build directory completely, I still have:

```
/home/obry/dev/repositories/git/darktable/src/common/cache.c:378:25: error: ‘struct __pthread_rwlock_arch_t’ has no member named ‘__nr_readers’; did you mean ‘__readers’?
  378 |   if(entry->lock.__data.__nr_readers <= 1)
      |                         ^~~~~~~~~~~~
      |                         __readers
```

```
$ gcc --version
gcc (Debian 9.2.1-21) 9.2.1 20191130
```

Any idea?

**Comment by cryptomilk** [comment]
Can you post the relevant cmake configure parts. As it checks if the member exist in the header files.

**Comment by TurboGit** [comment]
This ?

```
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test HAVE_OMP_FIRSTPRIVATE_WITH_CONST
-- Performing Test HAVE_OMP_FIRSTPRIVATE_WITH_CONST - Success
-- Performing Test HAVE_THREAD_RWLOCK_ARCH_T_READERS
-- Performing Test HAVE_THREAD_RWLOCK_ARCH_T_READERS - Success
-- Performing Test HAVE_THREAD_RWLOCK_ARCH_T_NR_READERS
-- Performing Test HAVE_THREAD_RWLOCK_ARCH_T_NR_READERS - Failed
```
Something else?

**Comment by TurboGit** [comment]
So the code is trying to use "__nr_readers" even though HAVE_THREAD_RWLOCK_ARCH_T_NR_READERS failed.

**Comment by cryptomilk** [comment]
This looks like something went wrong when pulling this branch. Let me rebase.

**Comment by cryptomilk** [comment]
The top commit addresses concerns from @upegelow 

I've discussed it with musl libc developers and they advised to set it only using pthread_attr_setstacksize()

**Comment by TurboGit** [comment]
Some conflicts to be resolved now.

**Comment by cryptomilk** [comment]
Rebased :-)

**Comment by TurboGit** [comment]
Still same error on my side. I have removed build directory and started clean with:

`./build.sh --asan`

And I still see this:
```

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for cpuid.h
-- Looking for cpuid.h - found
-- Looking for __get_cpuid
-- Looking for __get_cpuid - found
-- Performing Test HAVE_OMP_FIRSTPRIVATE_WITH_CONST
-- Performing Test HAVE_OMP_FIRSTPRIVATE_WITH_CONST - Success
-- Performing Test HAVE_THREAD_RWLOCK_ARCH_T_READERS
-- Performing Test HAVE_THREAD_RWLOCK_ARCH_T_READERS - Success
-- Performing Test HAVE_THREAD_RWLOCK_ARCH_T_NR_READERS
-- Performing Test HAVE_THREAD_RWLOCK_ARCH_T_NR_READERS - Failed
-- Performing Test IS_SUPPORTED_PLATFORM
-- Performing Test IS_SUPPORTED_PLATFORM - Success
```

**Comment by cryptomilk** [comment]
Hopefully fixed now, if not please paste the generated config.h file. Thanks

**Comment by TurboGit** [comment]
Still the same issue, the config.h seems ok (attached). But I found that the wrong option is still passed to the compiler with -D... : 

```
grep -R HAVE_THREAD_RWLOCK_ARCH_T_NR_READERS build/.
build/./CMakeFiles/CMakeError.log:Performing C SOURCE FILE Test HAVE_THREAD_RWLOCK_ARCH_T_NR_READERS failed with the following output:
build/./CMakeFiles/CMakeError.log:/usr/bin/cc   -fsanitize=address -fno-omit-frame-pointer -DHAVE_THREAD_RWLOCK_ARCH_T_NR_READERS   -o CMakeFiles/cmTC_9c203.dir/src.c.o   -c /home/obry/dev/repositories/git/darktable/build/CMakeFiles/CMakeTmp/src.c
build/./src/config.h:/* #undef HAVE_THREAD_RWLOCK_ARCH_T_NR_READERS */
build/./CMakeCache.txt://Test HAVE_THREAD_RWLOCK_ARCH_T_NR_READERS
build/./CMakeCache.txt:HAVE_THREAD_RWLOCK_ARCH_T_NR_READERS:INTERNAL=
```
[config.h.txt](https://github.com/darktable-org/darktable/files/4009351/config.h.txt)

**Comment by cryptomilk** [comment]
In the build directory, could you please do:

```
cd src
make common/cache.i
```

And then attach the generated `CMakeFiles/lib_darktable.dir/common/cache.c.i` file here?

**Comment by TurboGit** [comment]
Done and attached.

[cache.c.i.bz2.txt](https://github.com/darktable-org/darktable/files/4009442/cache.c.i.bz2.txt)

**Comment by cryptomilk** [comment]
According to that file, your `/home/obry/dev/repositories/git/darktable/build/src/config.h` doesn't have any of the `#define` values. I don't even see `HAVE_CPUID_H`!

**Comment by cryptomilk** [comment]
I think I found it.

**Comment by TurboGit** [comment]
Yes ! Compiling fine now. Thanks.

**Pull request merged**
