### PR TITLE
Bugfix: cacorrect avoid colorshift

### LINKED ISSUE #15121: Green tint with the RAW Chromatic Aberrations module
### Describe the bug

Enabling the RAW Chromatic Aberrations module brings a green tint on ARW files from Sony ILCE-7.

Reportedly the implementation comes from RawTherapee. Thus it is possible to compare them both.

The _avoid colorshift_ flag reduces the introduced tint in RawTherapee although it does nothing in Darktable.

### Steps to reproduce

1. Open an ARW file containing a portion of earthy tones
2. Enable the _raw chromatic aberrations_ module
3. Compare on/off colors

### Expected behavior

Darktable should remove the green tint as RawTherapee does.

### Logfile | Screenshot | Screencast

raw_ca_off
raw_ca_on

### Commit

_No response_

### Where did you install darktable from?

distro packaging

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Gentoo

### Describe your system?

_No response_

### Are you using OpenCL GPU in darktable?

No

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
1. correct algo making use of input data scaled to a range of 0->1
2. fix colorshift correction

Fixes #15121

Improves results in #15505

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
Fixes a very old one :-)

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by jenshannoschwalm** [comment]
@TurboGit a release note

Fixed 'avoid colorshift' in raw chromatic aberration

**Comment by TurboGit** [comment]
Thanks!

**Pull request merged**
