### PR TITLE
Reviewed italian translations

### PR DESCRIPTION
**Pull request by fabiosirna**
Reviewed Italian translations and fixed grammar errors

### CODE REVIEW

**Comment by TurboGit** [comment]
Has this been validated with Matteo and synchronized with the repository used by the Italian translator team ?

**Comment by fabiosirna** [comment]
Yes, this is the final result of all italian contributions.

**Comment by cigno5** [comment]
@TurboGit yes! @mmardegan is a bit busy rn but we agreed on @fabiosirna work!

**Comment by TurboGit** [comment]
@cigno5 : Thanks a lot for the quick reply, I'm extra cautious so close of the release. Thanks.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by mmardegan** [comment]
Il 14 dicembre 2023 13:59:38 CET, Pascal Obry ***@***.***> ha scritto:
>@TurboGit approved this pull request.
>
>Thanks!
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/darktable-org/darktable/pull/15877#pullrequestreview-1781763521
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
Thank you all! 
-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Pull request merged**
