### PR TITLE
Writing and wording fixes for RELEASE_NOTES.md

### PR DESCRIPTION
**Pull request by victoryforce**

### CODE REVIEW

**Comment by TurboGit** [comment]
I'll let @elstoc review. Just saw a typo fix that I have spotted to.

**Review by elstoc — APPROVED** [review]
Looks good to me. One commit probably would have been plenty though.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by TurboGit** [comment]
Thanks to both of you!

**Pull request merged**
