### PR TITLE
Update DE translations

### PR DESCRIPTION
**Pull request by Sturmflut**

### CODE REVIEW

**Comment by TurboGit** [comment]
Can you comment about why this is needed? A DE update was integrated this morning. Thanks.

**Comment by Sturmflut** [comment]
If I didn't do anything wrong (this is my first take at translations for darktable), there where still lots of fuzzy/untranslated strings after commit e9b4ecc4831081d8cfd7f03fc93951c0d7304cec:

$ intltool-update de
........................................................................................................................................................................................................................................................................................................................................................ done.
2473 translated messages, 59 fuzzy translations, 65 untranslated messages.

This pull request should fix most of them.

**Comment by Sturmflut** [comment]
Looks like this pull request messes up some of the improved translations in commit  e9b4ecc4831081d8cfd7f03fc93951c0d7304cec. I'll close this pull request and try to merge both versions.

**Comment by TurboGit** [comment]
Ok, thanks. Note that I didn't say that you've done something wrong, I'm not speaking German so I cannot tell that's why I've been asking.

**Comment by Sturmflut** [comment]
It was an unfortunate coincidence. I'm already half-through with the merge and will submit a new pull request soon.

**Pull request closed without merging**
