### PR TITLE
Finally prepare OpenCl related stuff for dt 4.0

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Over the last months a large number of OpenCl related bugs have been identified and fixed
a) some were very likely AMD driver specific
b) we now have a more predictable and tested device memory
c) a number of important modules badly miscalculated the required device memory and thus lead to errors, instability and performance drops on low memory devices as found on-CPU

The OpenCl code should now concidered to be stable and usable even on old and small graphics cards. So i think we can and should remove the hidden "opencl_memory_requirement" option and accept everything above 512MB to be ok. If the performance is bad or the device seems to be unstable, we can disable it in the device specific option.

There is one more thing i would like to discuss before adding code to this pr,
**Can we enable on-CPU devices nowadays by default?**

I would suggest to enable all on-CPU devices by default at least on Linux systems. (As a reminder, a user can later disable any device specifically ...)

@parafin and @MStraeten what do you think about the macs?

Windows seems to be a different story here, so many issues reported here and on pixls.us because of bad drivers or incompatible libraries ...

### CODE REVIEW

**Comment by MStraeten** [comment]
i never had issues with on-CPU devices on my intel based MacBooks with intel gpu and also dedicated using both. I don’t have the `opencl_disable_drivers_blacklist=FALSE` setting in my OS X darktablerc and never changed `opencl_use_cpu_devices=false`
On my win10 intel machine I changed `opencl_disable_drivers_blacklist` to true and it was fine

**Comment by parafin** [comment]
I’ve seen issues (bad output) with on-CPU GPU OpenCL on macOS, it seems dependent on exact hardware and macOS version (and dt code). They might no longer be reproducible. But as @MStraeten noted, no changes to configuration is required for this OpenCL configuration, one just have to enable OpenCL in preferences (it’s off by default on macOS exactly because of these issues).

**Comment by jenshannoschwalm** [comment]
@parafin and @MStraeten thanks for feedback. I forgot about 'DEFCONFIG_OPENCL' disabling opencl by default so we are safe.

**Comment by jenshannoschwalm** [comment]
Some comments here as a report and reminder of what is missing or possible remaining problems related to OpenCL in dt 4.0

1. We have `event_handles` in opencl.h `dt_opencl_device_t` at least helping a lot by regular checks&flush on the cl events. Unfortunately this is not absolutely safe as the maximum number of cl events that can be handled by the device&driver combination until cleared by might be restricted. Checking this to be absolutely sure requires OpenCL V2.0 at least. The minimum provided by drivers is 1024, in dt this could be reached only on very small devices, certain modules and pinned transfer on. At least we keep track on the maximum number of events now (available via -d opencl). Should get a fix post 4.0
2. We still have the global option `opencl_mandatory_timeout`, the timeout should likely be per-device too depending on the performance ratio gpu vs cpu
3. We currently have the policy "tiled opencl is faster than untiled cpu". This is not necessarily true, we should be able to approximate the performance using processed overall data (including tiling overlaps) and the performance ratio and do an early cpu-fallback instead of tiled opencl code. Don't know, if the benchmark we do is good enough for such a decision. At least we can ask users for -d opencl output to get some data to think about. 
4. No idea yet about a safe way to handle windows neo drivers issues.
5. Can we have better cl compiler options per default depending on vendor?

**Comment by jenshannoschwalm** [comment]
@TurboGit for me this is ready for merging. Another pr will follow integrating the blacklisting into the per-device en/disabling.

**Review by TurboGit — APPROVED** [review]
Looks good, thanks for this clean-up. The hard work and complete revamp of the OpenCL handling you've done make it possible to remove some preferences that were needed to tweak/workaround some dt limitations/bugs. Really nice. Thanks again.

**Comment by semperit89** [comment]
Hey, 
today I tried the latest darktable master on my mac. Deletet the darktablerc, cached Kernels and started the app. 
But there seems to be an issue with opencl. In the past the cpu device was switched off by default. I tried it once some time ago, but there were failures, it didn´t build kernels, which also caused the whole opencl darktable system not to function. But with only the gpu everything worked fine (eg in the Version darktable-3.9.0+739~g226abdefa which I had installed before).

In the latest darktable-3.9.0+1219~ga27b430f9 it tries to build kernels on the cpu device first [dt_opencl_device_init] device 0: 'Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz' and then on my old nvdia. But no kernels are built at all and opencl stays disabled.

Maybe I´m blind, where could I disable the cpu device for opencl usage now?
I tried 
cldevice_v3_intelrcoretmi54570cpu320ghz=false
cldevice_v3_intelrcoretmi54570cpu320ghz_building=false
in the darktablerc, but it didn´t work.

**Comment by jenshannoschwalm** [comment]
Thanks for your detailed report!

1) I think I understand why it's going wrong
2) the conf keys are changed in a wrong way and the docs must be updated asap.

Will fix that later today.

**Comment by MStraeten** [comment]
It doesn’t matter ( at least with my system configuration - mbp pro) the kernel for CPU are compiled but never used. So even it’s detecting 3 gpu devices, it continues using just the ‚real‘ gpus.
After deleting darktablerc to get a clean configuration I just had to switch to default GPU Usage and retype my custom priority settings.

**Comment by parafin** [comment]
@jenshannoschwalm, I think removal of opencl_use_cpu_devices was a mistake. As me and @MStraeten noted it didn't affect embedded on-CPU GPU OpenCL implementation. Instead, as was stated in documentation, it was about CPU OpenCL, that is OpenCL code running on CPU itself. That we still don't want to have enabled by default, it's only useful for experiments and debugging. There are reports on IRC about much degraded performance of DT after this merge due to that change.

**Comment by jenshannoschwalm** [comment]
> As me and @MStraeten noted it didn't affect embedded on-CPU GPU OpenCL implementation. Instead, as was stated in documentation, it was about CPU OpenCL, that is OpenCL code running on CPU itself. That we still don't want to have enabled by default,

@parafin. Thanks for making this so clear. Indeed i understood your comments wrongly and what we have now is clearly a bug.
I will fix that asap, i would propose to check for cpu-emulated devices and mark them as disabled.

**Pull request merged**
