### PR TITLE
Spanish translation update: some fixes

### PR DESCRIPTION
**Pull request by EdgarLux**

### CODE REVIEW

**Comment by TurboGit** [comment]
@EdgarLux : Thanks, a question though do you want this to be in 4.6.1 also?

**Comment by EdgarLux** [comment]
> Thanks, a question though do you want this to be in 4.6.1 also?

@TurboGit: Yes, please. Thank you in advance.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by TurboGit** [comment]
Merged in master & 4.6.x branch.

**Pull request merged**
