### PR TITLE
po/collect update visible

### PR DESCRIPTION
**Pull request by TurboGit**
Check for file accessibility only on visible items.
    
    The check for accessibility of a file is slow and so we do it only
    once after entering the collect module and only for the visible
    items. This makes the collect module far more responsive when
    changing the filters for example.
    
    Note that this is done only for the list-view as there is issues
    to do the same with the tree-view. Another implementation is
    done for the later.
    
    Part of #9042.

### CODE REVIEW

**Comment by phweyland** [comment]
That works for me, except on the first display of the list, as already commented.

This said, I'm not happy with the current behavior of collect and this attempt to make work this feature (folder/film roll reachable) which doesn't produce great code (more workarounds than effective solutions). I include here my own workaround but not the rationalization of events signaling which is more promising.
I would vote to remove that not critical feature and keep the code cleaner.

**Review by phweyland — APPROVED** [review]
All good with my comments on the main thread.

**Comment by phweyland** [comment]
Thoughts.
The fact that a folder is reachable or not should not be calculated every time the view (folder or film_roll) is displayed; probably once at the start of dt and then updated in background job. This info should be stored in film_roll table.

**Comment by TurboGit** [comment]
@phweyland : I'm not fond of using background job for this. We cannot poll all the time to check for accessibility. Also I don't think the accessibility status should be stored in film_roll directly, it could be in a memory table.

The tricky part in your proposal is to answer : when should it be updated ?

At any time a network drive or USB storage can be disconnected. So the current approach to set the accessibility of visible part is better, and of course it would be a really good option if it was working ok for tree-view.

All in all, I do think this feature is important. And I do think, as you, that the current implementation is far from perfect. My current thinking is to go with that for 3.6 as a "safe" fix as the current very slow situation makes bad UI experience.

**Comment by phweyland** [comment]
>  it could be in a memory table.

Agreed.

> when should it be updated ?

I'm not an expert but there should be some gdk event about drive mounting. 

> My current thinking is to go with that for 3.6 as a "safe" fix as the current very slow situation makes bad UI experience.

:+1:

**Comment by TurboGit** [comment]
@phweyland : After merging the works on signals from @AlicVB the issue #9042 I reported is not so bad. Most of the common use case seems to be covered, stars, color label, filter, etc...

So maybe we should just closes our PR for now and see if we can improve things another way. Maybe updating a memory table each time we enter the collection widget using a background job ? Or any other better idea?

Thoughts?

**Comment by phweyland** [comment]
> So maybe we should just closes our PR for now and see if we can improve things another way.

Yes, with some time to think about it we should find a smarter solution.

**Comment by TurboGit** [comment]
Closing to come with a smarter solution.

**Comment by phweyland** [comment]
Thinking about the spec ...

1. at dt start set up 2 lists:
 - mounted volumes (could be common with import places).
 - status of film_rolls => memory table (data available in collect's queries).
2. periodic job scanning the mounted volumes.
 - if change:
   - update mounted volumes list
   - update film_rolls' status
   - reload collect query if necessary
 
Notes:
- I haven't found any volumes status change event. If exists, would be better.
- folders renaming or deletion in parallel of dt are not detected. Would that be an issue ?

**Pull request closed without merging**
