### PR TITLE
Rcd maintenance 6

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
As we know of finite_math in rcd demosaicer code we can use the compiler option here.

Use standard FC( function instead of the rcd specific one

Together this gives a subtle but measurable performance gain of ~2%

### CODE REVIEW

**Comment by TurboGit** [comment]
I'll change schedule to 3.8. Changing compiler options has proved to be somewhat risky in the past with some unexpected results.

**Comment by TurboGit** [comment]
BTW, have you run the regression tests on this?

**Comment by jenshannoschwalm** [comment]
No, again the python stuff is not working here. I tested via gimp-layer-subtract-amplify and that was completely black so no pixel different.

**Review by TurboGit — APPROVED** [review]
Regression test ok. Thanks!

**Pull request merged**
