### PR TITLE
watermark: remove top most section.

### PR DESCRIPTION
**Pull request by TurboGit**
Another one !

### CODE REVIEW

**Comment by dterrahe** [comment]
You are right; I thought "content" at least wasn't "watermark settings", but it is still pretty meaningless.

This could be reordered/grouped better? How about:

marker
text
font
color
opacity

--placement--
rotation
scale
scale on
alignment
x offset
y offset

**Comment by TurboGit** [comment]
That's the output:

image

**Review by dterrahe — APPROVED** [review]
Looks good! Imho the right amount of visual guidance to quickly find everything.

With rotation and scale included, maybe "position" should be renamed though?

**Comment by TurboGit** [comment]
> With rotation and scale included, maybe "position" should be renamed though?

Yes, your proposal was **placement**, I kept **position** but I have no string opinion and I'm not a native English speaker. Let's go with placement.

**Comment by TurboGit** [comment]
Done.

**Pull request merged**
