### PR TITLE
Dynamicly updating buttons on selected images module

### PR DESCRIPTION
**Pull request by johnny-bit**
Working of off code and inspiration from #5257 (and @TurboGit ) this is making buttons in selected images module very dynamic.

Although I do have a question: How to best get `DT_IMAGE_LOCAL_COPY` flag out of active images? the code I tried causes nasty busy spin when there's a group in collection.

Otherwise this works quite nicelly.

### CODE REVIEW

**Comment by TurboGit** [comment]
> Although I do have a question: How to best get `DT_IMAGE_LOCAL_COPY` flag out of active images? the code I tried causes nasty busy spin when there's a group in collection.

You need to lock the image and look at the flags. But this should not be done for a collection as it is probably too CPU intensive. I would simplify by activating the local copy or resync if there is at leas one image selected.

**Comment by johnny-bit** [comment]
Done and matches what module requests of job control :)

Next on the menu: selection module :)

**Comment by TurboGit** [comment]
On small glitch, the [group] button should be activated only if there is at least 2 selected images. For the [ungroup] button that's good as-is, we can un-group a single picture.

Apart from that all good! Again it feels as if dt is really alive.

@Nilvus as for #5257, I'd like you take on this one, Thanks.

**Comment by Nilvus** [comment]
Will test this one this week-end.

**Comment by johnny-bit** [comment]
> [group] button should be activated only if there is at least 2 selected images

Done! :)

**Comment by TurboGit** [comment]
Looks good to me. Thanks! I'll wait @Nilvus review before merging.

**Comment by Nilvus** [comment]
Good for me and the group button add is a good idea. Each day actually the UI is more and more polish (and much more "sexy"). Thanks @johnny-bit.

**Comment by TurboGit** [comment]
Merging then. Thanks!

**Pull request merged**
