### PR TITLE
preference dialogs: remove dialog parameter

### PR DESCRIPTION
**Pull request by phweyland**

### CODE REVIEW

**Comment by phweyland** [comment]
Following discussion in #7707 & #7717.

In local pref dialog preferences are saved on the fly (no cancel button).
This is consistent with the future integration in the modules.

**Comment by phweyland** [comment]
Maybe another question.
As is that mimic the global preferences layout (with the indicator changed / default).
That makes sense in local preferences dialog.
Is that ok too for modules ? (other modules don't have this layout and use reset button instead).

**Comment by phweyland** [comment]
Here is an attempt to have the possibility not to have the reset mechanism. 

If we would apply this to collect local pref we would get this (without reset button):

image
I don't find my changes in the code very smart. If you have a better option please tell me. 
But I think we need this option.

**Comment by TurboGit** [comment]
I would keep those dialog with a way to reset the changes and with the default status indicator. This will be more consistent to me.

**Pull request closed without merging**
