### PR TITLE
history: optimize listing modules used

### PR DESCRIPTION
**Pull request by HansBull**
Instead of calling dozens of times consecutively `dt_history_check_module_exists` with its locking and query, get once a list of all the modules in the history of a image and lock only once.

### CODE REVIEW

**Comment by TurboGit** [comment]
Kind of a trade off, note that the table is cached in memory by SQLLite and that the SQL index ensure that the check is very fast. Now you have a list of operation which is searched sequentially !

**Comment by HansBull** [comment]
True, but the list is short. 
Sqlite queries seem cheap, but they sum up, with all that preparing, parsing, binding. Just opening darktable with a tiny filmroll needs already 844 queries...

You are the boss. Not offended if you close it without merging.

**Comment by TurboGit** [comment]
> Just opening darktable with a tiny filmroll needs already 844 queries...

Sure but at the end the important is the time to process the image.

Now I have a question, why not only remove the lock in side dt_history_get_module_operations() there is a single SELECT and only returning TRUE/FALSE. I'm really not sure this is needed here and we may gain quite a bit of time removing the lock.

**Comment by HansBull** [comment]
Good question...

**Pull request closed without merging**
