### PR TITLE
preferences: add lua tab to new layout

### LINKED ISSUE #4868: Lua tab disappeared in the new options dialog
In the new options dialog with vertical tabs, the "lua options" is no longer present (was last tab in the old layout).
Lua scripts work and Options->Shortcuts-> lua is there, but "lua option" just disappeared.

Cattura30

DT 3.1 git master on Windows 10

### PR DESCRIPTION
**Pull request by elstoc**
Resolves #4868

### CODE REVIEW

**Comment by elstoc** [comment]
Don't merge this yet. I've just spotted another change.

**Comment by elstoc** [comment]
I've checked that this compiles and @Mark-64 kindly tested that the new option appears but I've not been able to test that it still works correctly, as I don't use Lua. I'm fairly sure it should be ok though.

**Comment by Mark-64** [comment]
I also did some test that lua options work and they do, at least with the scripts I use

**Comment by elstoc** [comment]
Cool thanks again @Mark-64

**Comment by TurboGit** [comment]
So this seems all good ! Thanks to both of you for restoring this.

**Pull request merged**
