### PR TITLE
po/libraw submodule

### PR DESCRIPTION
**Pull request by TurboGit**

### CODE REVIEW

**Comment by MStraeten** [comment]
just checked this on osx 
cmake fails with:
```
CMake Warning (dev) at src/CMakeLists.txt:1043 (set):
  implicitly converting 'BOOLEAN' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at src/external/LibRaw-cmake/CMakeLists.txt:47 (file):
  file failed to open for reading (No such file or directory):

    /Users/martinstraeten/src/darktable/src/external/LibRaw/libraw/libraw_version.h


CMake Error at src/external/LibRaw-cmake/CMakeLists.txt:50 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.


CMake Error at src/external/LibRaw-cmake/CMakeLists.txt:53 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.


CMake Error at src/external/LibRaw-cmake/CMakeLists.txt:56 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.


CMake Error at src/external/LibRaw-cmake/CMakeLists.txt:61 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.


CMake Error at src/external/LibRaw-cmake/CMakeLists.txt:64 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.


CMake Error at src/external/LibRaw-cmake/CMakeLists.txt:67 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.


-- LibRaw string version: 1.1.1
-- LibRaw ID version:     0x111
-- LibRaw SO version:     1.1.1
-- Check for LCMS2 availability...
-- Checking for module 'lcms2'
--   Found lcms2, version 2.12
-- Found lcms version 2.12, /opt/local/lib/liblcms2.dylib
-- Found LCMS2 : /opt/local/lib/liblcms2.dylib /opt/local/include
-- Found OpenMP_C: -Xclang -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -Xclang -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Found Jasper: /opt/local/lib/libjasper.dylib (found version "2.0.33")
--
-- ----------------------------------------------------------------------------------
--  Libraw 1.1.1 configuration            <http://www.libraw.org>
--
--  Libraw will be compiled with OpenMP support .................. YES
--  Libraw will be compiled with LCMS support .................... YES
--  Libraw will be compiled with example command-line programs ... NO
--  Libraw will be compiled with RedCine codec support ........... YES
--  Libraw will be compiled with DNG deflate codec support ....... YES
--  Libraw will be compiled with DNG lossy codec support ......... YES
--  Libraw will be compiled with RawSpeed support ................ NO
--  Libraw will be compiled with debug message from dcraw ........ NO
--  Libraw will be compiled with Foveon X3F support .............. NO
--  Libraw will be compiled with Raspberry Pi RAW support ........ NO
--  Libraw will be compiled as a shared library
-- ----------------------------------------------------------------------------------
```

**Comment by MStraeten** [comment]
osx build fails:
```
[  5%] Building CXX object bin/external/LibRaw-cmake/CMakeFiles/raw.dir/__/LibRaw/src/decoders/canon_600.cpp.o
fatal error: unknown warning option '-Wno-restrict' [-Wunknown-warning-option]
make[2]: *** [bin/external/LibRaw-cmake/CMakeFiles/raw.dir/__/LibRaw/src/decoders/canon_600.cpp.o] Error 1
make[1]: *** [bin/external/LibRaw-cmake/CMakeFiles/raw.dir/all] Error 2
make: *** [all] Error 2
martinstraeten@Martins-MBP build %
```

**Comment by TurboGit** [comment]
> fatal error: unknown warning option '-Wno-restrict' [-Wunknown-warning-option]

Probably because MacOS is using CLang and this option is GCC only.

**Comment by TurboGit** [comment]
@MStraeten can you test this:

```
$ diff --git a/src/external/LibRaw-cmake/CMakeLists.txt b/src/external/LibRaw-cmake/CMakeLists.txt
index 73268f283..5e621bcd3 100644
--- a/src/external/LibRaw-cmake/CMakeLists.txt
+++ b/src/external/LibRaw-cmake/CMakeLists.txt
@@ -452,7 +452,7 @@ else()
       ${libraw_LIB_SRCS}
       PROPERTIES
       COMPILE_FLAGS
-      "-Wno-type-limits -Wno-sign-compare -Wno-restrict -Wno-shadow -Wno-maybe-uninitialized -Wno-stringop-truncation -Wno-unused-variable -Wno-format-overflow")
+      "-Wno-unknown-warning-option -Wno-type-limits -Wno-sign-compare -Wno-restrict -Wno-shadow -Wno-maybe-uninitialized -Wno-stringop-truncation -Wno-unused-variable -Wno-format-overflow")
 
     # Exclude placeholder (stub) implementations
     file(GLOB_RECURSE exclude_libraw_LIB_SRCS CONFIGURE_DEPENDS "${LIBRAW_PATH}/src/*_ph.cpp")

```

Basically that's adding `-Wno-unknown-warning-option` option.

**Comment by TurboGit** [comment]
@MStraeten : I (we) really need help as the time is very short for the integration. This is becoming urgent to get right.

@wpferguson : I know you are building on Windows... Would be nice to have this tested on Windows too,

To everyone reading this, if you think you can help do so... I don't have Canon camera and I'm no expert in CMake so all help is welcomed if we want CR3 support in 3.8. Thanks.

**Comment by TurboGit** [comment]
@MStraeten : I have pushed a new version where I kill all warnings in LibRaw (-w).

**Comment by MStraeten** [comment]
the patch works, libraw compiles fine, but the imageio_libraw fails:
```
/Users/martinstraeten/src/darktable/src/common/imageio_libraw.c:111:6: fatal error: variable 'err' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
  if(libraw_err != LIBRAW_SUCCESS) goto error;
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/martinstraeten/src/darktable/src/common/imageio_libraw.c:192:10: note: uninitialized use occurs here
  return err;
         ^~~
/Users/martinstraeten/src/darktable/src/common/imageio_libraw.c:111:3: note: remove the 'if' if its condition is always false
  if(libraw_err != LIBRAW_SUCCESS) goto error;
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/common/imageio_libraw.c.o] Error 1
make[1]: *** [bin/CMakeFiles/lib_darktable.dir/all] Error 2
make: *** [all] Error 2
```

btw: i can spend time over the weekend for builds and tests on osx

**Comment by TurboGit** [comment]
> the patch works, libraw compiles fine, but the imageio_libraw fails:

Should be fixed. And yes thanks for the testing !

**Comment by TurboGit** [comment]
Note that at this stage we expect things to not work properly until @cytrinox next update. At least if if compiles and can import a CR3 we are not so bad but the rendering may be wrong for some camera.

**Comment by MStraeten** [comment]
not yet fixed - it seems imageio_libraw.c  line 86 needs an initialization like in the following line 

```
[ 41%] Building C object bin/CMakeFiles/lib_darktable.dir/common/imageio_libraw.c.o
/Users/martinstraeten/src/darktable/src/common/imageio_libraw.c:111:6: fatal error: variable 'err' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
  if(libraw_err != LIBRAW_SUCCESS) goto error;
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/martinstraeten/src/darktable/src/common/imageio_libraw.c:192:10: note: uninitialized use occurs here
  return err;
         ^~~
/Users/martinstraeten/src/darktable/src/common/imageio_libraw.c:111:3: note: remove the 'if' if its condition is always false
  if(libraw_err != LIBRAW_SUCCESS) goto error;
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by MStraeten** [comment]
with imageio_libraw.c line 86 changed to `   int err = 0;` it builds fine.
but i need to hardcode     `set(HAVE_EXV_ENABLE_BMFF 1)` in src/CMakeLists.txt since     `check_cxx_symbol_exists(EXV_ENABLE_BMFF "exiv2/exiv2.hpp" HAVE_EXV_ENABLE_BMFF)` doesn't seem to detect BMFF support on osx

Canon EOS R cr3 is rendered successfully, M6markII, R5 and R6 are rendered but with "color matrix not found!"

**Comment by wpferguson** [comment]
@TurboGit I'll test on windows

**Comment by TurboGit** [comment]
@MStraeten : I have added `set(HAVE_EXV_ENABLE_BMFF 1)` only for APPLE target. Probably wrong as we force BMFF, we'll see if someone can fix the MacOSX check. And I have fixed imageio_libraw.c.

> Canon EOS R cr3 is rendered successfully, M6markII, R5 and R6 are rendered but with "color matrix not found!"

That's expected for now. Let's wait for @cytrinox final work.

Thanks.

**Comment by piratenpanda** [comment]
Works fine on Arch and with few lines added to imageio_libraw.c also works fine for the R5. Thanks for the work!

**Comment by MStraeten** [comment]
yep changing dt_libraw_lookup-makermodell to
```
int dt_libraw_lookup_makermodel(const char *maker, const char *model,
                                   char *mk, int mk_len, char *md, int md_len,
                                   char *al, int al_len)
{
  int got_it_done = FALSE;

  if(g_str_equal(maker, "Canon"))
  {
    g_strlcpy(mk, "Canon", mk_len);
    
    if(g_str_equal(model, "Canon EOS M50") ||
    g_str_equal(model, "Canon EOS M50m2") ||
    g_str_equal(model, "Canon EOS M200") ||
    g_str_equal(model, "Canon EOS R") ||
    g_str_equal(model, "Canon EOS RP") ||
    g_str_equal(model, "Canon EOS 250D") ||
    g_str_equal(model, "Canon EOS 90D") ||
    g_str_equal(model, "Canon EOS 850D") |
    g_str_equal(model, "Canon EOS M6 Mark II") ||
    g_str_equal(model, "Canon PowerShot G7 X Mark III") ||
    g_str_equal(model, "Canon PowerShot G5 X Mark II") ||
    g_str_equal(model, "Canon EOS-1D X Mark III") ||
    g_str_equal(model, "Canon EOS R5") ||
    g_str_equal(model, "Canon EOS R6") ||
    g_str_equal(model, "Canon PowerShot SX70 HS"))
    {
      g_strlcpy(md, g_strjoinv("", g_strsplit(model, "Canon ", -1)), md_len);
      g_strlcpy(al, g_strjoinv("", g_strsplit(model, "Canon ", -1)), al_len);
    }
    got_it_done = TRUE;
  }

  return got_it_done;
}
```
is fine (checked with some available cr3 files from raw.pixls.us) except for Powershot SX70 HS

**Comment by TurboGit** [comment]
Closing as this is now part of #10332

**Pull request closed without merging**
