### PR TITLE
force thumbtable refresh when creating HDR

### PR DESCRIPTION
**Pull request by Mark-64**
Fix for #4929, similar to #4904

### CODE REVIEW

**Comment by Mark-64** [comment]
Travis CI failed, reason being the use of an uninitialized variable in case HDR creation is aborted.
This is easy to fix, however in that case DT also segfaults, even without this PR.
I will have to investigate more

**Comment by Mark-64** [comment]
The segfault is a more general issue, not related to this part of the code, I will open a specific bug report

**Comment by Mark-64** [comment]
By the way, I could not replicate the segfault. It happens whe you lauch whatever job queue, for example exporting several images and then you click twice on the progress bar abort "X".
But it happens only with the Debug build, never with the Release.
It doesn't seem to be a real issue and in any case nothig related to this PR

**Comment by TurboGit** [comment]
Looks good to me. Thanks!

**Pull request merged**
