### PR TITLE
RFC: Hide/show masks using right mouse button on canvas.

### PR DESCRIPTION
**Pull request by TurboGit**
Now that all masks have control points to change the size, feathering, segments, control nodes... It is easier to stay over the canvas and be able to show/hide the masks instead of having to click on the blending gui button.

This makes the general masks handling consistent with the liquify masks where it is already possible to use the right mouse button to show/hide masks.

Long time ago this idea was rejected because a right mouse button would remove the forms. But we need to be over it (or a nodes for the path) and when it is displayed to actually remove the mask. Yet it seems perfectly usable and not error prone, and if this happens we still have the undo to recover the masks (undo a mask at the time this idea was rejected was not implemented).

### CODE REVIEW

**Comment by dterrahe** [comment]
I think it would be an improvement for me. The only reservation I would have is if you actually _want_ to remove a shape, you may think you succeeded if there was only one, but you may just have hidden it. Same happens in liquify, where you actually have to right-click _on the control point_ to remove it. I've clicked within the circle expecting it to be deleted like a mask circle would, but it wasn't.

**Comment by s7habo** [comment]
I am also for it. And I also share the remarks of @dterrahe .

I can think of two possible solutions:

I don't know if this has been discussed yet, but would it be possible to have a menu with the _right  click_ like for example in Inkscape, where you can choose if you want to _delete_ or _hide_ mask ?

image


There you can then choose the options and there would be no confusion whether mask is deleted or hidden.

Other simpler option would be _right click_ to hide the mask and _shift + right click_ to delete it.

In principle I would be for reserving the combination _shift + right click_ for the delete operation _for all elements_ (control points, segments) and the mask itself.  Then the _right click_ can be used to _hide_ the mask.

**Comment by TurboGit** [comment]
> The only reservation I would have is if you actually _want_ to remove a shape

What about a **toast message** when removing a shape?

**Comment by elstoc** [comment]
> What about a toast message when removing a shape?

I think this would work best if there was also a toast message when hiding shapes. _Not_ seeing a message when hiding shapes wouldn't make me sure I hadn't deleted the shape. But if I saw a message saying what I actually did, that would probably be more reassuring.

**Comment by TurboGit** [comment]
> I think this would work best if there was also a toast message when hiding shapes.

This won't work well to me. The goal here is to be able to quickly and show/hide shapes to see then result without the shapes drawn. So it means (at least to me) that we hide/show lot of time between small adjustments. Having a toast message each time will be bad UI wise to me.

**Comment by elstoc** [comment]
> This won't work well to me

Then this should be assignable as a shortcut in the normal way and not set by default IMO

**Comment by TurboGit** [comment]
> I don't know if this has been discussed yet, but would it be possible to have a menu with the _right click_ like for example in Inkscape, where you can choose if you want to _delete_ or _hide_ mask ?

I don't think we can at this stage, remember that right-click + drag is used to straighten the picture and simple right-click to end a path (I had already the need for a little hack in this PR).

**Comment by elstoc** [comment]
> Note also that a visual feedback is already there as soon as you have more than one shape

For me, using a single shape is much more common than multiple shapes and I think this is the use case that needs to be clear (since it's the one where the action is most likely to be ambiguous).

**Comment by TurboGit** [comment]
Toast message added in the last version.

**Comment by elstoc** [comment]
> This can already be done using iop/blend/tools/show and edit mask elements (shortcut mapping mode is your friend).

I thought this was the case, just hadn't got around to testing it. IMO if this action can already be assigned to a shortcut, there's no need for another way to do the same thing. Leave it up to the user.

**Comment by TurboGit** [comment]
Ok, we'll see if we can come up with something better later. Thanks for all who commented.

**Pull request closed without merging**
