### PR TITLE
Nikon D7200 support

### PR DESCRIPTION
**Pull request by ralfbrown**
This replaces pull request #881.  I've changed the standard color matrix from a copy of the D7100 matrix to a copy of the D5500 matrix, and have added updated noise profiles, including profiles for additional ISOs (the half-stop values in addition to the 1/3 stop values).

### CODE REVIEW

**Comment by pmjdebruijn** [comment]
Please see: http://www.darktable.org/redmine/issues/10382

**Comment by piorekf** [comment]
What is blocking this? I would really love to see support for this camera in the next release.

**Comment by pmjdebruijn** [comment]
Nothing, all critical parts are already in our development version.

**Comment by piorekf** [comment]
Great to hear that. I'll try to build developer version then.

**Comment by boucman** [comment]
can the PR be closed then ?

**Comment by pmjdebruijn** [comment]
I'd recommend against hopping on master "just like that" as your database will be upgraded, and there will be no way back. Almost everything will be available fairly soon in a new point release.

**Comment by ralfbrown** [comment]
I just discovered that the noise profiles have not been included in master.  Is there a problem with them?

**Comment by houz** [comment]
Indeed, I added it to the stable branch but somehow forgot master. Fixed.

**Pull request closed without merging**
