### PR TITLE
Adding a .travis.yml file to use the travis-ci.org

### PR DESCRIPTION
**Pull request by sieben**
From wikipedia:

Travis CI is a hosted, distributed continuous integration service used
to build and test projects hosted at GitHub.

Travis CI is configured by adding a file named .travis.yml, which is a
YAML format text file, to the root directory of the GitHub repository.

Travis CI automatically detects when a commit has been made and pushed
to a GitHub repository that is using Travis CI, and each time this
happens, it will try to build the project and run tests. This includes
commits to all branches, not just to the master branch. When that
process has completed, it will notify a developer in the way it has been
configured to do so — for example, by sending an email containing the
test results (showing success or failure), or by posting a message on an
IRC channel. It can be configured to run the tests on a range of
different machines, with different software installed (such as older
versions of a programming language, to test for compatibility).

### CODE REVIEW

**Comment by LebedevRI** [comment]
Yeah, not sure about that.
I have previously looked into travis-ci.org, and i wasn't convinced about doing it.
Plus, they have rather old compiler versions, so it really wasn't interesting.

**Comment by sieben** [comment]
You can install new packages. I think it could be useful to have the status
of a pull requests right on the github interface. If you have a Jenkins or
other CI tools it can work as well.

2015-03-22 17:38 GMT+01:00 Roman Lebedev <notifications@github.com>:

**Comment by sieben** [comment]
@LebedevRI What's the current status of continuous integration with lighttable?

**Comment by LebedevRI** [comment]
@sieben lighttable?
On a *local* jenkins instance, i do a semi-daily builds of master and current stable branch (darktable-1.6.x ATM) with gcc-4.6 through gcc-4.9 and clang-3.4 through clang-3.7 in all 3 build types (release, relwithdebinfo, debug)
(and, there is git master build by [openSUSE OBS](http://download.opensuse.org/repositories/home:/toganm:/photography/))
So locally, we're more or less covered...

**Comment by sieben** [comment]
Ah ok so yes travis-ci might not be the best option here. That said maybe
testing the pull requests with this jenkins could be great
http://blog.clinkerhq.com/automatically-building-github-pull-requests/

2015-03-27 11:34 GMT+01:00 Roman Lebedev <notifications@github.com>:

**Comment by LebedevRI** [comment]
Just wanted to point out that in the end it was implemented.
Do not know whether we will keep it or not, but **so far** looks okay-ish.

**Pull request closed without merging**
