### PR TITLE
[CI] Enhance CI run and make mac ci less likely to fail

### PR DESCRIPTION
**Pull request by johnny-bit**
I tried here to work around the CI issues with mac on gh actions workers - turns out it's recent python 3.9 change :/ For some it's automagically fixed, for others not... So i had to use a workaround

Additionally:

- Adds GCC 7 builds - since we kinda support Ubuntu LTS 18.04 & 20.04, right?
- Adds `nofeatures_nosse` target to check whether something won't blow up if there's no SSE
- with `Linux-minimal` checking "basic compilers" all probable failures are checked early and so Linux, Windows & Mac targets are checked in parallel.

This should make it easier to catch if PR is failing due to code rather than OS/Packaging problems

sidenote: msys2 still can fail with weird stuff. No workarounds for that except "try to restart action every 2-4 hours" :/

### CODE REVIEW

**Comment by MStraeten** [comment]
did set up the homebrew way of build according to the ci description in https://github.com/darktable-org/darktable/issues/7564#issuecomment-752679349 in a osx virtual machine (mojave, sdk 10.14) and darktable-3.4.x branch was built fine ...

**Comment by johnny-bit** [comment]
Yeah. That's why I needed to make a workaround for gh actions - this is workaround + beefing up ;)

**Comment by TurboGit** [comment]
@johnny-bit : the windows failures are transients or really something to look at ? Some packages not updated...

**Comment by johnny-bit** [comment]
> the windows failures are transients or really something to look at?

According to msys2 folks - "sync issues on mirrors, usually gone in 15-30 mins, sometimes more"

**Comment by TurboGit** [comment]
Ok, let's merge then. Thanks a lot for looking into this.

**Comment by johnny-bit** [comment]
"Current" msys2 issues are in this ticket: https://github.com/msys2/setup-msys2/issues/99

**Comment by parafin** [comment]
Probably worth merging into 3.4 branch too.

**Pull request merged**
