### PR TITLE
Darktable 2.4.x

### PR DESCRIPTION
**Pull request by ramuntcho**
Hi,

Is there a planned version for Mac ?

Thanks in advance

:-))

### CODE REVIEW

**Comment by houz** [comment]
Is this supposed to be a pull request? Or just chatting?

**Comment by ramuntcho** [comment]
Hello,

Sorry if I did not follow the rules, I didn't know how to ask about a Mac version.

Best regards

Christian

________________________________
Christian Oïhénart
SEM-Logistique
Etat de Genève - Service Ecoles-Médias
Rue des Gazomètres 3 - CP 241 - 1211 Genève 8
Tél. 022 388 63 76
christian.oihenart@edu.ge.ch<mailto:christian.oihenart@edu.ge.ch>





Le 8 janv. 2018 à 15:31, Tobias Ellinghaus <notifications@github.com<mailto:notifications@github.com>> a écrit :


Is this supposed to be a pull request? Or just chatting?

**Comment by houz** [comment]
No worries. The Mac dmg will be done when it's done. All I can tell you is that there is only a single contributor that even uses a Mac, and we have to rely on him making the package. Until then there is nothing we can do to speed things up. Sorry.

**Comment by ramuntcho** [comment]
Thanks for your answer.

:-)) Christian

________________________________
Christian Oïhénart
SEM-Logistique
Etat de Genève - Service Ecoles-Médias
Rue des Gazomètres 3 - CP 241 - 1211 Genève 8
Tél. 022 388 63 76
christian.oihenart@edu.ge.ch<mailto:christian.oihenart@edu.ge.ch>





Le 8 janv. 2018 à 16:32, Tobias Ellinghaus <notifications@github.com<mailto:notifications@github.com>> a écrit :


No worries. The Mac dmg will be done when it's done. All I can tell you is that there is only a single contributor that even uses a Mac, and we have to rely on him making the package. Until then there is nothing we can do to speed things up. Sorry.

**Pull request closed without merging**
