### PR TITLE
Prune optimization flags

### PR DESCRIPTION
**Pull request by flannelhead**
Some minor pruning of optimization flags. Should not have any effect on generated code because this only removes some additional flags that are already set by default, see commit messages.

### CODE REVIEW

**Comment by flannelhead** [comment]
As far as I can tell, this should be safe for v4.0. This is practically no-op since the flags removed here are actually already enabled by other flags or by default. The intent here is mainly to clear some clutter.

**Comment by TurboGit** [comment]
@flannelhead : Have you run the regression tests with this to ensure some options are not missing? In the past we had issues with changing the math options. TIA.

**Comment by flannelhead** [comment]
No, I'm going only be the [GCC manuals](https://gcc.gnu.org/onlinedocs/gcc-8.1.0/gcc/Optimize-Options.html#Optimize-Options) here.

* `-fexpensive-optimizations` is enabled as part of `-O2` already in `8.1.0` which is the oldest GCC supported by darktable
* on `Release` build `-ffast-math` is enabled project-wide so it's unnecessary to set it locally
* `-ffast-math` in turn enables `-fno-math-errno` so it's unnecessary to set it separately locally
* `fp-contract=fast` is GCC's default

**Comment by flannelhead** [comment]
But on the other hand I think it's a good idea to run those tests anyway, especially on the demosaicing methods, with both `Release` and `RelWithDebInfo` builds. I'll report back when I've done that.

**Comment by TurboGit** [comment]
> But on the other hand I think it's a good idea to run those tests anyway, especially on the demosaicing methods, with both `Release` and `RelWithDebInfo` builds. I'll report back when I've done that.

Any news about this?

**Comment by ralfbrown** [comment]
> Note that recently we had found that removing some optimization options actually let the compiler doing better job (see [2b8922a](https://github.com/darktable-org/darktable/commit/2b8922ab144caa598713f11263c1d85bfd5b5f95)).

In that particular case, some flag or combination of flags set locally kept the compiler from inlining one of the function calls in the inner loop.  I did not try to figure out which it was out of the long list.

**Comment by flannelhead** [comment]
> In that particular case, some flag or combination of flags set locally kept the compiler from inlining one of the function calls in the inner loop. I did not try to figure out which it was out of the long list.

I've seen this happen also before - diffuse and sharpen had a severe performance regression last year caused by moving a single `#include` of a particular header to a different row. It caused `sqf()` not to be inlined due to different optimization flags.

Having those local flags around, especially in headers, can be very fragile in terms of optimization. In my opinion, it would be best to get rid of those (and, well, plenty of the flags in that huge list are already enabled by the global flags for the `Release` build).

@TurboGit I think pursuing this is still worthwhile, but testing is laborious - one needs to assert unchanged output as well as choose a suitable set of flags to enable globally in order to avoid any (severe) perf regressions.

As for the merge conflicts, those shouldn't be too hard to fix. I would prefer to keep this draft around for now, and probably will some day finish it. If someone feels like working on this, please feel free to do so. Last summer I introduced functionality for benchmarking individual modules easily with `darktable-bench`. That should help a lot with the testing.

**Pull request closed without merging**
