### PR TITLE
Remove esc handler quitting fullscreen to enable quit-slideshow

### LINKED ISSUE #7197: ESC does not quit slideshow anymore
**Describe the bug**
Since #7139 it's not possible to quit the slideshow by pressing ESC anymore

**To Reproduce**
1. Start slideshow
2. Press 'ESC'
3. Nothing happens

**Expected behavior**
- ESC does not (only) quit fullscreen but (also) quits the slideshow
- this behavior is intuitive and necessary because the top-menu is not shown in the slideshow
- even the old user manual says 'ESC :  leave slideshow mode and return to lighttable view'

### PR DESCRIPTION
**Pull request by quovadit**
fixes #7197 as suggested by @AlicVB

### CODE REVIEW

**Review by AlicVB — CHANGES_REQUESTED** [review]
Great ! this is needed.
Some comment, though : 
1. the solution you propose, completely remove the "exit fullscreen" shortcut, which is already handled by the "toggle fullscreen" one. I just fear that we can break some old users workflow (Is it a problem ?) we can also just remove the default key attached to the shortcut (but that won't solve the issue for old users...)
2. Shouldn't we add a new "exit slideshow" shortcut with ESC key by default ? Even if we don't use it explicitly in slideshow code, that would prevent one to re-affect ESC to something else, and reproduce the issue...

**Comment by quovadit** [comment]
The old user manual says 'Fullscreen view can be toggled by pressing F11.'
Every user going to fullscreen with F11 knows how to exit fullscreen again without Esc.

BUT:
Not every user who starts slideshow via top-menu knows how to exit it again without Esc.

So I don't think that it's a problem for old users (or at least it's better than before this PR).

Adding a new "exit slideshow" shortcut with ESC key by default is a good idea in my opinion.

**Comment by quovadit** [comment]
the "exit slideshow" shortcut would introduce a new string. Is this ok even after string freeze?
How can I contribute to translation? Should I just include the changed .po files in the PR?

**Review by AlicVB — APPROVED** [review]
@quovadit : yes, you're right about the string freeze. Maybe better wait for 3.4.1 to add the shortcut then. It's not really critical : if we merge this, we'll have the wanted behavior (ESC to exit slideshow). The new shortcut is more to do things cleanly...

So all good for me :)

**Comment by TurboGit** [comment]
Works for me, thanks and this respect the documentation where ESC is described as leaving the slideshow.

**Comment by TurboGit** [comment]
Fell free to create the PR for the new shortcut for 3.4.1. TIA.

**Pull request merged**
