### PR TITLE
desktop file mime types redux

### PR DESCRIPTION
**Pull request by kmilos**
A small follow-up to https://github.com/darktable-org/darktable/pull/12218

@AndrewKvalheim @TurboGit Still not convinced we should be adding raw types: the next step would be to really add all the ones supported by rawspeed, which will turn into a very long list...

### CODE REVIEW

**Comment by AndrewKvalheim** [comment]
Can’t speak for the maintenance burden but at least the [.desktop spec](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-0.9.5.html#mime-types) gives a go-ahead:

> The `MimeType` key is used to indicate the MIME Types that an application knows how to handle. […] It is expected that for some applications this list could become long.

**Comment by kmilos** [comment]
See this as the very long sausage example: https://doc.ubuntu-fr.org/raw

Let me know if you feel like we need to start incorporating those...

FYI, [IANA doesn't recommend using private "x-" subtypes at all for some time now, and those are not really registered anywhere](https://en.wikipedia.org/wiki/Media_type#Unregistered_tree).

**Comment by TurboGit** [comment]
> Let me know if you feel like we need to start incorporating those...

Why not, at least all those RAW file format supported.

**Comment by kmilos** [comment]
I have now added some major types from https://gitlab.freedesktop.org/xdg/shared-mime-info/-/blob/master/data/freedesktop.org.xml.in

**Review by TurboGit — APPROVED** [review]
Works for me. I can't comment whether it is necessary or not but we are not the only one to do that :)

**Comment by kmilos** [comment]
Ok, so good to go then IMO, those are all the raw types known by freedektop.org (apart from image/x-sigma-x3f we don't support yet).

**Pull request merged**
