### PR TITLE
colorchecker: fix -Werror=stringop-overflow=

### PR DESCRIPTION
**Pull request by kmilos**
Thanks @parafin it doesn't seem to complain when looping over A w/ N4 indeed... @victoryforce Shall we try this instead of https://github.com/darktable-org/darktable/pull/14317?

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Looks good and better as no option need to be temporarily set.

**Comment by victoryforce** [comment]
> @victoryforce Shall we try this instead of #14317?

Sorry for the late comment, couldn't read the github earlier, but this fix doesn't affect the gcc 13 warnings. Of course, there's nothing wrong with it, no need to revert, we just removed the redundant operation, although we saved not so many CPU clocks. But the compiler continues to issue misleading warning:
```
In file included from /home/git/darktable/build/lib/darktable/plugins/introspection_colorchecker.c:47:
/home/git/darktable/src/iop/colorchecker.c: In function ‘commit_params’:
/home/git/darktable/src/iop/colorchecker.c:724:34: error: ‘__builtin_memset’ writing 32 bytes into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
  724 |       for(int i=N;i<N4;i++) b[i] = 0;
      |                             ~~~~~^~~
compilation terminated due to -Wfatal-errors.
```

**Comment by kmilos** [comment]
Argh, that's right. There are no errors on Rawhide or Tumbleweed builds since they somehow turn -Werror off it seems... The rest of the message:
```
[  472s] /home/abuild/rpmbuild/BUILD/darktable-4.3.0~git1960.bfe46075/src/iop/colorchecker.c:704:17: note: at offset [-17179869184, -8] into destination object of size [0, 9223372036854775807] allocated by 'malloc'
[  472s]   704 |     double *b = malloc(sizeof(*b) * N4);
[  472s]       |                 ^~~~~~~~~~~~~~~~~~~~~~~
```

No idea why it doesn't complain about writing into buffer A with a similar pattern... @parafin

**Comment by kmilos** [comment]
To make things worse, the next similar (cryptic) warning is in xtrans.c @jenshannoschwalm 
```
[  356s] In function 'memset',
[  356s]     inlined from 'xtrans_markesteijn_interpolate._omp_fn.0' at /home/abuild/rpmbuild/BUILD/darktable-4.3.0~git1956.dea93671/src/iop/demosaicing/xtrans.c:452:7:
[  356s] /usr/include/bits/string_fortified.h:59:10: warning: '__builtin_memset' specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
[  356s]    59 |   return __builtin___memset_chk (__dest, __ch, __len,
[  356s]       |          ^
[  356s] /usr/include/bits/string_fortified.h:59:10: warning: '__builtin_memset' specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
```

**Comment by kmilos** [comment]
Those 18446744073709551615 vs 9223372036854775807 numbers are UINT64_MAX and INT64_MAX. Perhaps this really complains about using `int` instead of `size_t` for allocating and accessing buffers?

**Comment by parafin** [comment]
Maybe. Or maybe it's about what compiler thinks are possible values for N and N+4:
```
d->num_patches = MIN(MAX_PATCHES, p->num_patches);
const int N = d->num_patches, N4 = N + 4;
```

num_patches is signed, so IMHO it considers the case where N is negative. I would suggest to try to make sure it's >=0 (e.g. by making it unsigned, yes).

**Comment by kmilos** [comment]
Something like that... But what I don't get is, why it doesn't complain about buffer A for the similar access pattern?
```
    double *A = malloc(sizeof(*A) * N4 * N4);
    double *b = malloc(sizeof(*b) * N4);

```
Because it is so smart and knows `N4 * N4` is non-negative?

**Comment by parafin** [comment]
No, because for A there are no loops starting with N.

**Comment by parafin** [comment]
Scratch that, there is...

**Comment by parafin** [comment]
Yeah, I dunno, maybe because indexes for A are too complex for it to validate... Only way to find out is to try different things...

**Comment by parafin** [comment]
To clarify - malloc argument is unsigned, so for negative size you get a very big buffer. So it's not about buffer being too small (on the contrary - one of the warnings is about it being too large), but about array access with negative offset. This confirms that compiler considers negative N.

**Comment by kmilos** [comment]
From the original error message, I still think it considers the malloc w/ size of 0...

**Comment by parafin** [comment]
I guess it considers ranges of possible values of N. Zero size also is only possible with negative N.

**Comment by kmilos** [comment]
> I guess it considers ranges of possible values of N. Zero size also is only possible with negative N.

Precisely.

**Pull request merged**
