### PR TITLE
BUGFIX: highlights reconstruction visualize indicator

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
The false color indicator for clipped color planes was plain wrong for xtrans sensors.
Fixed for cpu and opencl code.

### CODE REVIEW

**Comment by TurboGit** [comment]
You mean the mask display button next to the highlight reconstruction threshold?

Here is what I see, on this picture:

image

We had (looks wrong):

image

We now have (looks better):

image

So if I'm not mistaken this is indeed better.

**Comment by jenshannoschwalm** [comment]
Yes I simply missed to use the correct xtrans "filter" for xtrans sensors.

**Comment by jenshannoschwalm** [comment]
Tune the clip value to appreciate the data. 😀

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
