### PR TITLE
deprecates levels & contrast brightness saturation

### PR DESCRIPTION
**Pull request by TurboGit**
- levels use rgblevels instead
- ~~tonecurve use rgbcuvre instead~~
- contrast brightness saturation use colorbalance rgb instead

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
What about these

1. color correction
2. color contrast
3. shadows & highlights
4. contrast brightness saturation

Questionable (as we have better options) but probably not "deprecated" ?

**Comment by Nilvus** [comment]
I agree with you @jenshannoschwalm. Anyway, less simple as I'm quite sure we have some old users still use them (and want to use them, even if they have too much limits and issues). So a little more controversial but for new users, deprecated them would be really better. One of the critics for new users is that darktable have too much modules and not easy to know which ones to use, even if workflows helps.

**Comment by ralfbrown** [comment]
I think C-B-S can be deprecated.   We already have exposure and the global saturation slider from colorbalanceRGB on the QAP by default,  Adding the contrast slider from colorbalanceRGB would provide the equivalent of C-B-S right on the QAP.

For the other three, I'd be in favor of a soft deprecation at this time - don't move them to the deprecated group, but have them display a message along the lines of "consider using X module instead".  I find color correction easier to use than doing the equivalent in the 4-ways tab on CB RGB.

**Comment by AlicVB** [comment]
for the record, initial goal of QAP was to deprecate "color brightness saturation" which has weird side effects in some cases...

**Comment by TurboGit** [comment]
I'll add CBS in the deprecated list.

For the others I'd vote for `color contrast` to be deprecated and keep the remaining in standard status.

NOTE: I've added `tone curve` in deprecated list, but that one of the last module which make it possible to directly work on the Lab canal separately. I was expecting some remark on this :)

**Comment by MStraeten** [comment]
until darktable-chart istn't modified to use rgbcurve instead of tonecurve tonecurve should not be deprecated

**Comment by TurboGit** [comment]
@MStraeten : Indeed, forgot about this, we cannot deprecate this module.

**Comment by RawConvert** [comment]
Re. Lab in tonecurve module and "I was expecting some remark on this :)" above.
Yes, just saw this following the post in pixls.us.
I use tonecurve in Lab mode so vote for it to remain even if darktable-chart were to be modified.

**Comment by HSUfineprint** [comment]
I also use tonecurve for L*a*b* curve adjustment. Please don't deprecate this module.

**Comment by TurboGit** [comment]
I've removed tonecurve from deprecation for all the reasons exposed above.

**Comment by bastibe** [comment]
Came here to vote against removing tone curve, but that has already been resolved. Thank you.

**Comment by TurboGit** [comment]
Let's go with this one. We may add some other deprecated later if needed.

**Pull request merged**
