### PR TITLE
Lens IOP: enhance UI. Fixes #9273, Fixes #10425

### PR DESCRIPTION
**Pull request by LebedevRI**
This implements "more understandable" UI and better interaction between autodetection and user-set params for lens correction IOP.

I'm sure there is a couple of bugs left here, and the code it rather unpretty...

Most importantly, check legacy history stack entry handling!!!
(I have checked 5->6, and i believe it is working)

@bronger please take a look.

### CODE REVIEW

**Comment by rwh86** [comment]
I've done a few tests.  Let me know if there's anything else specific you'd like me to try.

Test methodology:
 * Take some folders of photos shot at different times in the past on different cameras
 * Find some previously corrected photos if possible
 * Open in DT 1.6.6 and DT 1.7+pr892
 * Compare UI
 * Export image with both versions and compare
 * Make some comments.  These are just observations, not requests for changes or value judgements; these need to be evaluated by someone more qualified.

Lensfun version 0.2.8-2 is installed.

RWH_0936.CR2
 * Canon 5d3 with 24-105 f/4 L
 * original xmp created on March 4th 2015 in dt 1.6.3
 * See screenshots of the two versions of the module
 * Old lens correction module shows camera, lens, focal length, f stop, and distance to subject
 * New lens correction module shows everything simply as "auto" 
   * Can't immediately tell if the camera/lens have been successfully detected or any of the parameters
   * However, eventually discovered that mouseover text identifies camera and lens
 * New module claims to be correcting both distortion and scale, old module only claims distortion
 * The output images appear the same but have slightly different file sizes so are not identical
   * compare RWH_0936_1.6.6.jpg RWH_0936_1.7+pr892.jpg -compose src diff.png
     * shows extensive pixel-level differences
 * Setting each option to "manual" results in display of the same values as from dt1.6.6
 * Mouseover of the option labels and values in 1.6.6 shows descriptive tooltips, however you can only mouseover the values in 1.7+pr892: the labels (mm, f/ and d) no longer have a tooltip
 * geometry claims to be "rectilinear" in 1.6.6 and "off" in 1.7+pr892 by default

RWH_7706.CR2
 * Canon 5d3 with 16-35 f/2.8 L II
 * Camera/Lens combo not found (despite me submitting samples to bronger over a year ago and it being listed as supported in http://lensfun.sourceforge.net/lenslist/).  Assume old lensfun or something.
 * In 1.7pr892, mouseover tooltip shows the camera/lens info that's displayed in the drop down list in 1.6.6.
 * Both versions have most options greyed out.  Therefore, to discover that there's a new mode "distort" you'd have to select a lens supported by lensfun first.

IMG_2821.CR2
 * Canon 60D with 70-200 f/4 L IS USM
 * Also not detected despite being in supported list.

IMG_0574.CR2
 * Canon 350D with 18-55 f/3.5-5.6 IS II
 * Lens/body combo not detected, lens listed as 65535 in mouseover text, perhaps due to the lens being newer than the body and thus the body being unable to identify it.  EXIF of CR2 lists "Lens Type" as "(65535)" but "Lens" as "18.0 - 55.0 mm".  Perhaps this slightly more informative value could be used in the tooltip?
 * Manually selecting the lens seems to work fine in both 1.7+pr892 and 1.6.6
 * Once manually selected, the tooltips for mm, f and d list show their values with six digits after the decimal point: 18.000000, 7.100000 and 1000.000000 in the tooltips in 1.7+pr892.  In 1.6.6 these are listed as 18, 7.1 and 1000, respectively.

**Comment by bronger** [comment]
- The new module is too wide for my screen.  I see a horizontal scroll bar.
- I actually don't like all those "auto" all over the place very much.  They provide no information.  I prefer having the camera model and lens model, and the EXIF parameters in the fields instead.  Besides, manual selection of EXIF values looks rather cumbersome with the two dropdowns per parameter.
- Also, if automatic correction is unavailable, the respective selection should be "off" instead of "auto".  This way, the information provided by the very last line is already contained in the selection menus above.
- If you switch scaling to "manual", the starting value is 1 (or the latest manual factor) instead of the latest autoscaling value.  I think it is more comfortable to have the latter.

**Comment by LebedevRI** [comment]
@bronger
>I actually don't like all those "auto" all over the place very much. They provide no information.
I partially agree, but unfortunately, i do not see any other meaningful way to represent "use autodetected or manually set value" (redmine 10425), which is widely requested feature and actually is the biggest goal here...

>Also, if automatic correction is unavailable, the respective selection should be "off" instead of "auto". 
Hmm, not sure.
Though, it guess it can be done with simply checking that e.g. lens->CalibTCA is not NULL in reload_defaults()

>If you switch scaling to "manual", the starting value is 1 (or the latest manual factor) instead of the
>latest autoscaling value. I think it is more comfortable to have the latter.
Makes sense, will bring back old functionality.

**Comment by bronger** [comment]
I cannot see the issue report #10425 at the moment (Redmine is down) but doesn't adding "auto" to the selection lists (camera, lens, focal length etc) make it unambiguous?

**Comment by LebedevRI** [comment]
@bronger yes, it does, that is the point.
Without explicit "auto/manual" switch, there is no way for a user to say: i want to use autodetected camera, but e.g. lens = $(manual samyang lens that does not show up in EXIF) and focal = 24.

Maybe i have misunderstood your initial comment, weren't you talking about all of the "auto", but only for TCA/etc?

**Comment by bronger** [comment]
I think I see the problem now.  We have three possible states: "auto", "manually selected", and "detection failed".  Is this correct?

**Comment by LebedevRI** [comment]
Some other time.
I guess it will be more of `cp src/iop/lens.c src/iop/lensfun.c`, and then adding support for all the lensfun's new shiny features (perspective correction, rotation).
And then rewriting scary `src/iop/clipping.c` as just cropping.c (i.e. with just the crop tool)

**Pull request closed without merging**
