### PR TITLE
filters : fix pin icon when adding/removing filters

### LINKED ISSUE #14009: Crash when removing and adding filters (lighttable)
**Introduction**

Hello.

**Did you buy darktable from an application store ?**

No. From OBS.

**Describe the bug/issue**

My version is not exactly up to date (OBS is a little behind), but I couldn't see a commit that probably fixed this. 

_**Update:** OBS has been updated, crash still there in git1399._

I can 100% reproduce a crash by first removing some of the initial filters in the lighttable and then add a new "date-based" (eg. capture date, import date etc.)

**To Reproduce**

- open DT
- in lighttable remove some or all of the filters that are set up
- add one of the "date-based" criteria
- if it hasn't already crashed, add another one

I couldn't get it to crash when I did not remove existing filters before I add new ones. Also not with adding other, not "date-based" filters.

**Expected behavior**

Not to crash.

**Screencast**

https://user-images.githubusercontent.com/96216629/227542418-5bf8762d-d1e8-4bd0-a075-f2dd7f087001.mp4

**Which commit introduced the error**

At least since 4.2.1.

**Platform**

DT-Version:  4.2.1 stable / 4.3.0 git995.a468c256-9339.1 / 4.3.0 git1399.2e0a7bdc-9548.1
Operating System: openSUSE Tumbleweed 20230319
KDE Plasma Version: 5.27.3
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.6-1-default (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6600
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: B450 I AORUS PRO WIFI

**Additional**

This is console output of darktable -d all from start to crash. The mentioned BT at the end is empty.

[console.txt](https://github.com/darktable-org/darktable/files/11063053/console.txt)

### PR DESCRIPTION
**Pull request by AlicVB**
this fix #14009 
this close #14470

### CODE REVIEW

**Comment by Nilvus** [comment]
Just a thing @AlicVB. #14470 is not linked to be closed by Github.

**Comment by AlicVB** [comment]
> Just a thing @AlicVB. #14470 is not linked to be closed by Github.

yep, I know, but no idea why... I've also tried to add it manually, without success...

**Review by TurboGit — APPROVED** [review]
I was not able to reproduce on my side but OP said it works. So I'll merge. Code looks good. Thanks @AlicVB for fixing and nice to see you back onboard :)

**Comment by TurboGit** [comment]
@AlicVB : Can you send me a little text for the release notes?

**Comment by AlicVB** [comment]
@TurboGit : 
" Fix pin icon update in filtering module with some specific filter combination" (sorry for the english, as usual ;))

**Comment by TurboGit** [comment]
Thanks!

**Pull request merged**
