### PR TITLE
dt conf : avoid race condition when getting var

### LINKED ISSUE #8659: Segfault in culling mode
**Describe the bug/issue**

Sometimes when working in culling mode and rapidly switching between zoomed/non-zoomed mode (with middle mouse click), switching between images and changing the number of images shown in culling mode, darktable segfaults.

It is not 100% reproducible, so I suspect a race condition. Thread dump is included below.

**To Reproduce**

1. Open a directory with raw images (I used Fujifilm RAF files)
2. Switch to culling mode, with 1 image shown
3. Middle-click on the image to zoom in
4. While it's still processing the image data, change the number of images shown in culling mode with the mouse wheel
5. Do this a few times, with different images, maybe switch back and forth between different images

With these steps, I could get Darktable to segfault multiple times.

**Platform**

* darktable version : darktable 3.5.0+1640~gdb5d23932
* OS                : Linux
* Linux - Distro    : Arch Linux
* Memory            : 32 GiB
* Graphics card     : Nvidia GTX 760
* Graphics driver   : nvidia-460.6⁻5
* OpenCL installed  : Yes (opencl-nvidia)
* OpenCL activated  : Yes
* Xorg              : Yes
* Desktop           : dwm
* GTK+              : ?
* gcc               : 10.2.0
* cflags            : ?
* CMAKE_BUILD_TYPE  : RelWithDebInfo

**Additional context**

I think this did not happen with 3.5.0.r557.g713fac470 (but can't say for sure, quite some changes in between).

Here's the thread dump: [darktable_bt_BBLP10.txt](https://github.com/darktable-org/darktable/files/6292510/darktable_bt_BBLP10.txt)

### PR DESCRIPTION
**Pull request by AlicVB**
fix #8659
"blindly" fix done thanks to @wpferguson tests :)
@wpferguson , @dbrgn : can you confirm that it fix it on your side (can't reproduce the issue here)

### CODE REVIEW

**Comment by wpferguson** [comment]
Tested.  First image I zoomed into it crashed

```
(gdb) bt
#0  0x0000000000000000 in  ()
#1  0x00007f23acbb2b7a in _dt_sigsegv_handler (param=11) at /home/bill/src/darktable/darktable/src/common/system_signal_handling.c:140
#2  0x00007f23ac6d5040 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f23ac824d9e in __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:533
#4  0x00007f23acb9e936 in memcpy (__len=<optimized out>, __src=<optimized out>, __dest=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34
#5  0x00007f23acb9e936 in _write_image (data=<optimized out>, filename=<optimized out>, in=<optimized out>, over_type=<optimized out>, over_filename=<optimized out>, exif=<optimized out>, exif_len=0, imgid=590, num=1, total=1, pipe=0x7f238486f1a0, export_masks=0) at /home/bill/src/darktable/darktable/src/common/mipmap_cache.c:1154
#6  0x00007f23acb88167 in dt_imageio_export_with_flags (imgid=<optimized out>, 
    imgid@entry=590, filename=filename@entry=0x7f23ace44a20 "unused", format=format@entry=0x7f2384871430, format_params=format_params@entry=0x7f2384871390, ignore_exif=ignore_exif@entry=1, display_byteorder=display_byteorder@entry=0, high_quality=<optimized out>, upscale=0, thumbnail_export=1, filter=<optimized out>, copy_metadata=0, export_masks=0, icc_type=DT_COLORSPACE_NONE, icc_filename=0x0, icc_intent=DT_INTENT_LAST, storage=0x0, storage_params=0x0, num=1, total=1, metadata=0x0) at /home/bill/src/darktable/darktable/src/common/imageio.c:1032
#7  0x00007f23acba1607 in _init_8 (size=DT_MIPMAP_8, imgid=590, color_space=0x26e, iscale=0x7f22a614e048, height=0x7f22a614e044, width=0x7f22a614e040, buf=0x7f22a614e080 "")
    at /home/bill/src/darktable/darktable/src/common/mipmap_cache.c:1280
#8  0x00007f23acba1607 in dt_mipmap_cache_get_with_caller (cache=0x55a3c4d92ee0, buf=buf@entry=0x7f23848729f0, imgid=590, mip=DT_MIPMAP_8, flags=flags@entry=DT_MIPMAP_BLOCKING, mode=mode@entry=114 'r', file=0x7f23ace55b60 "/home/bill/src/darktable/darktable/src/control/jobs/image_jobs.c", line=35) at /home/bill/src/darktable/darktable/src/common/mipmap_cache.c:822
#9  0x00007f23acbeb4c2 in dt_image_load_job_run (job=<optimized out>) at /home/bill/src/darktable/darktable/src/control/jobs/image_jobs.c:35
#10 0x00007f23acbe35b5 in dt_control_job_execute (job=job@entry=0x55a3c6e93a90) at /home/bill/src/darktable/darktable/src/control/jobs.c:300
#11 0x00007f23acbe3db8 in dt_control_run_job (control=0x55a3c2b18a80) at /home/bill/src/darktable/darktable/src/control/jobs.c:319
#12 0x00007f23acbe3db8 in dt_control_work (ptr=<optimized out>) at /home/bill/src/darktable/darktable/src/control/jobs.c:564
#13 0x00007f23ac47e6db in start_thread (arg=0x7f2384881700) at pthread_create.c:463
#14 0x00007f23ac7b771f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

Tried again.  As soon as I zoom into an image it crashes

**Comment by wpferguson** [comment]
I went back to master, recompiled and it's also crashing as soon as I zoom.  I had just loaded a set of images I shot today so they didn't exist in cache or anywhere else.

**Comment by AlicVB** [comment]
:(
and you confirm that with master, if you revert manually https://github.com/darktable-org/darktable/commit/5f28899c9a910c2af9fa0c801f47c739b8d3e41f you don't get any crash ?
Then, I'm out of ideas of what is the root cause of the problem :(

We always can revert https://github.com/darktable-org/darktable/commit/5f28899c9a910c2af9fa0c801f47c739b8d3e41f, that won't do any harm, but I would prefer to find the root cause, as `dt_conf_is_equal` is used in lot of other places and if it's buggy, we may have issues there too...

@TurboGit : if you have time, maybe you can have a look too... thanks !

**Comment by wpferguson** [comment]
After a night to sleep on this :-)

I think what happened last night might be a new/different bug.  I applied the patch and had a bunch of images I had just shot so I figured I'd kill 2 birds with one stone and test the fix while seeing how my images turned out.  So I imported the fresh images and immediately went into full preview layout.  At this point the images don't even have thumbnails, just a database entry.  I start scrolling through looking at the images and see something I want to get a better look at so I middle click to zoom.  I get the working... message on the screen then a crash.  I didn't have to pan the image or click multiple times.  This was also repeatable.  I could crash it every time I middle clicked an image.  @AlicVB when I middle click to zoom what function gets called?

My plan is this.

* I'm going to go back to the set of images I've been testing with and test the fix.
* I'm going to set up a couple of test environments to do a more comprehensive set of tests to check out the possible second bug

**Comment by jenshannoschwalm** [comment]
Just to make sure, this is not related to demosaicers algo, this also has changed recently?

**Comment by wpferguson** [comment]
@jenshannoschwalm I don't think so, but I'll keep it in mind while I'm testing

**Comment by wpferguson** [comment]
Wrote some scripts so that I can create, clean, and destroy test environments so that I can keep things straight in my on head...

Created dttestbad, with commit 5f28899c9a910c2af9fa0c801f47c739b8d3e41f

Tested and got the same behavior we had been seeing, i.e. middle click to zoom, pan image, middle click, sometimes crash.  If I just middle clicked to zoom and then middle clicked back out, no crash.  So what I saw last night is probably a new bug.

Created dttestbadwpatch with commit 5f28899c9a910c2af9fa0c801f47c739b8d3e41f and @AlicVB patch

Tested and managed to make it crash just the same.  So, we don't understand the problem well enough.

I'll see what I can figure out...

And, I'll chase the other bug....

**Comment by TurboGit** [comment]
So should we close this PR and continue the discussion on the issue?

**Comment by wpferguson** [comment]
I checked out the bad commit and added the code from the last good commit back in.  I printed the value from the old code and used the value from the new code.

It crashed and this is what I got

old_use_raw is false
use_raw is true

Somehow they ended up with different answers

**Comment by wpferguson** [comment]
Figured it out

The original code was 

```
  char *min = dt_conf_get_string("plugins/lighttable/thumbnail_raw_min_level");
  const gboolean use_raw = g_strcmp0(min, "never");
  g_free(min);

```
So, if min was "never" then g_strcmp0 returned 0, which is false.

`dt_conf_is_equal` reverses the result by returning the result of g_strcmp0() == 0, so in this case we want dt_conf_is_not_equal or !dt_conf_is_equal()

**Comment by AlicVB** [comment]
it was so simple... great that you spot it :)

**Pull request closed without merging**
