### PR TITLE
Add a "tune OpenCLperformance" button

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Some users might fear worse performance with the new "darktable resources" runtime
checks (or have experienced so after the first merged pr's) and wanted ways to tune
the system as they did with "cl headroom".

a small reminder
 - headroom was global and didn't work good with several devices
 - you might be running other opencl apps when starting dt so the static headroom
   was too small and you ended up with cl errors and fallback to cpu code.

The "tuned cl" mode is preset to the same values for cpu related stuff.

For OpenCL is does a test for available graphics memory for every device **once** when
starting darltable and returns the found free memory from now on whenever we want to know
via `dt_opencl_get_device_available(const int devid)`
(It keeps a safety headroom margin of 128MB)

Found free memory and old-style headroom are reported via -d opencl if you are curious.

### CODE REVIEW

**Comment by elstoc** [comment]
> For OpenCL is does a test for available graphics memory for every device once when starting darltable and returns the found free memory from now on whenever we want to know [...] (It keeps a safety headroom margin of 128MB)

So you're saying that it discovers the amount of free GPU memory at start, subtracts 128MB from it and uses that calculated value throughout the remainder of the session?

**Comment by jenshannoschwalm** [comment]
Almost, there is in fact a safety margin between 128 and 256 MB

**Comment by elstoc** [comment]
Hmm. I liked headroom because I understood what it was doing and it was predictable - once I set it to a safe value (for my system) I could forget about it. I'm not sure I know how to predict this.

**Comment by TurboGit** [comment]
> once I set it to a safe value (for my system) I could forget about it. I'm not sure I know how to predict this.

Agreed, but how many people where able to understand this and properly set it?

To me all those efforts to come up with a simple and single setting is a nice goal. Not perfect today as seen with different feedback but I'm sure this will settle as a good if not perfect solution.

**Review by TurboGit — COMMENTED** [review]
A question, I see that "tune cl" is equivalent to "large" with opencl being auto-tuned. Would it makes sense to separate the tune cl from others to be able to have a "small tune cl" or "reference tune cl"... ?

**Comment by jenshannoschwalm** [comment]
> A question, I see that "tune cl" is equivalent to "large" with opencl being auto-tuned. Would it makes sense to separate the tune cl from others to be able to have a "small tune cl" or "reference tune cl"... ?

I am not sure what you mean here exactly? In principle, testing for available graphics mem is done only once because every such testing **might** hurt other apps, parafin pointed at this problem. And - yes we could offer such a tuning for every mode.

Could you explain in a bit more detail what you suggest?

**Comment by TurboGit** [comment]
@jenshannoschwalm : My idea was to separate the OpenCL setting from the CPU one or at least since those settings are orthogonal I think that we should be able to have opencl auto-tune for more modes. My thinking was to add this at least for medium and large with two new mode `medium (opencl auto-tune)` and `large (opencl auto-tune)` (this is the one you're are proposing in this PR).

But this may be a wrong idea, at this stage you certainly know far more than me on this area. If it is the case, just tell me :)

**Comment by elstoc** [comment]
Certainly separating OpenCL from normal system RAM usage would make sense to me. I usually have very little using my GPU and quite a lot using my normal system memory so I would want different settings for each.

**Comment by jenshannoschwalm** [comment]
I though about above ideas for some time before answering.

In the end - besides technical things - it comes to down to what a user does on the machine.
a) dt "power user" wanting most of the resources for dt
b) "generic  user" leaving room for 1) a few or 2) many other apps taking system ram

I am happy with static settings insofar as they give sensible suggestions as default and can be tuned by nerds later. Although there should be no reason to do so if our defaults are good.
Here a first question: are setting names as "default" "small" and "large" good or should they better describe what you are doing like "take it all", "default" and "stay defensive" ?

For the dt power user we could offer a setting like "tune your cl system but leave more system stuff." - technically implemented via smaller fractions but tune cl. Although again, if we do all processing via cl (either tiled or not) dt would not use much of system ram anyway (at least if mem-hungry modules have cl implementations).

I would prefer to keep it all in one preference menu (but that's a personal opinion as i hate it to get confronted with lots of options that are just technical).

**Comment by TurboGit** [comment]
For me it makes no sense to try to have dt take into account too much others apps. Do we really expect a guy wanting to work on a 50 mpix image, using "diffuse or sharpen" module and others like retouch or liquify which are really demanding on machine power be able to start a game? I would say no.

The only scenario is starting hugin or other image oriented processing tool which may also ask for large resources.

> I am happy with static settings insofar as they give sensible suggestions as default and can be tuned by nerds later.

Agreed, this makes full control over the resources and it is good.

> I would prefer to keep it all in one preference menu (but that's a personal opinion as i hate it to get confronted with lots of options that are just technical).

This os what I had suggested with some more entries in the combobox. But I'm not sure if it is the best.

> Here a first question: are setting names as "default" "small" and "large" good

This is ok by me.

My only point is having more control on OpenCL stuff and one can have a large main memory but a small GPU or the reverse. So large for both is maybe not the best.

I see two options:

1. having more entries in the current combobox:

- large / medium
- medium / large
- ...

First string being for the CPU and the second for GPU.

2. having a second combobox specific for GPU:

- small
- medium
- large

Just for tuning the amount of GPU memory to take.

I would really lean toward this second solution as trying to solve two settings in a single combobox seems like a dead-end at this point.

**Comment by TurboGit** [comment]
Responding to myself.

> My only point is having more control on OpenCL stuff and one can have a large main memory but a small GPU or the reverse.

I understand that here we are talking about percentage of resource taken from memory or GPU. So I would have said that we want to take more resources from GPU than CPU and so control more finely both percentages. Hope this makes it clearer, does it makes sense?

**Comment by TurboGit** [comment]
I have hard time to set my mind on this actually. Maybe just leave as it is today on master and see how it works before going further?

And later maybe just add another option to use less or more from the GPU? As proposed above using a second combobox but which would tune the GPU fraction by adding or subtracting 10% ?

```
For large it would be : 810 | 900 | 990
For default           : 630 | 700 | 770
for small             : 360 | 400 | 440
```

This will be easier for all users instead of hand coding ratio in darktablerc. Again power users will have full control anyway. How does that sounds?

Just trying to put different options on the table...

**Comment by jenshannoschwalm** [comment]
Another option on my table would be to add a bool in opencl preference "tune for cl performance", this would mean: override given cl fraction via the resources menu and use checked available memory instead? This would be switchable at runtime too.

**Comment by TurboGit** [comment]
> Another option on my table would be to add a bool in opencl preference "tune for cl performance", this would mean: override given cl fraction via the resources menu and use checked available memory instead? This would be switchable at runtime too.

I see, but you said it was difficult to `tune for cl performance` given that others app may be using resources and that opencl always says OK when you request memory, right? Or are you proposing that when this option is set we don't care about other apps? Or again maybe I'm missing a point :)

**Comment by jenshannoschwalm** [comment]
> Or are you proposing that when this option is set we don't care about other apps? Or again maybe I'm missing a point :)

Well, in this pr; if you set to" tune for cl" the available memory is checked via "allocate & test by copy" (see code in ` _opencl_get_tuned_available` this calculation is required to test for memory in-fact available instead of the wrongful err code returned from alloc. The problem - as parafin pinpointed me into - we can't do that all the time when we process a pipeline as this brute force test (while being comletely valid) might interfere badly with other apps if we do it so often.

So we do this test only once in a darkroom session and find out about "true headroom". We have to leave some safety margin here btw.

One thing i ran into while working on headroom was: i carefully checked headroom via nvidia-smi and there was never more than ~400MB of cl memory taken by xorg ... everything was fine. Opening firefox - dt fall back to cpu because cl failed in kernels (This is not an uncommon case. some gnome apps also take some memory like those using a camera with effect , hugin is just the most extreme example) But if a nerd tuned for perfect headroom - bang.

So - yes we can add such an option "tune for performance" leading to performance as good as what we had with tuned headroom but in a better way.

**Comment by TurboGit** [comment]
> So - yes we can add such an option "tune for performance" leading to performance as good as what we had with tuned headroom but in a better way.

Ok, so let's go with that.

**Comment by jenshannoschwalm** [comment]
> Ok, so let's go with that.

will do very soon

**Comment by todd-prior** [comment]
Thanks for working on this. When the headroom discussions came up recently on pixls.us and the opencl optimization I was thinking it would be great to have an optimizer as the potential to improve performace could be so dramatic. So once again thank you. I would vote for a solution the prioritizes using DT. I purposely try to run as little as possible when I am using it to try and give it all available resources. I know there are some niche cases and allowing manual tweaking should cover that. I prefer names that imply the benefit or the action over something like small medium large that has to be described but that could just be me. Finally if there was a fairly easy way to add this to the command line to generate a log people could run through all the options on some typical images and see what gives the best results...this might also in the end aid with coming up with manual selections if someone did want to tweak it....I am waiting for a PC to replace my expired one...it will have a 3070ti and 12th gen intel with onboard graphics...it will be nice to have options to test the performance. My gut says just keep the intel stuff out of it and make the 3070 do all the work........

**Comment by jenshannoschwalm** [comment]
Latest commits:
1. switch from a menu entry to a bool button that allows tuning graphics memory what we know as "best" headroom
2. the singlebuffer fraction has been changed to smaller values
3. please note, as the default fractions have changed you should remove the data from darktablerc before checking performance

**Comment by wpferguson** [comment]
>  It just would hurt performance as tiled cl will definitely be worse than cpu code

I think this would depend on the CPU.  Maybe if you have an 11th or 12th generation i7/i9 this is true.  With a 6th generation i7, tiled GPU code is ~600% faster than the CPU.

**Comment by jenshannoschwalm** [comment]
> I think this would depend on the CPU. Maybe if you have an 11th or 12th generation i7/i9 this is true. With a 6th generation i7, tiled GPU code is ~600% faster than the CPU.

Maybe we misunderstood (or i wrote just too badly) i was referring to an integrated intel cl device, they have maybe 500MB free cl memory available and you might have 8 or 16BG of ram, this would be a pretty common system. (I have something like that on my ~5yrs old notebook btw). On such a device diff&sharpen would be bad in the cl path because of very heavy tiling. Such situations can't be solved atm unfortunately, we just have to rely on the "cl is always better" rule.

**Comment by todd-prior** [comment]
> Maybe we misunderstood (or i wrote just too badly) i was referring to an integrated intel cl device, they have maybe 500MB free cl memory available and you might have 8 or 16BG of ram, this would be a pretty common system. (I have something like that on my ~5yrs old notebook btw). On such a device diff&sharpen would be bad in the cl path because of very heavy tiling. Such situations can't be solved atm unfortunately, we just have to rely on the "cl is always better" rule.

You are right at least in my experience. My PC died and I got fed up waiting for the new one to arrive so I put DT on a small Dell PC I had connected to my TV. It used intel graphics. Reported using about 478 MB of memory. Any images with diffuse never completed and tons of artifacts when using some modules...When I disabled the opencl everything worked...it was slow but even the images with diffuse activated would render whereas they would not even after a few minutes with opencl enabled... So dealing correctly with integrated graphics and the derived opencl settings will be important...

**Comment by wpferguson** [comment]
@jenshannoschwalm, I thought you were talking about a "real" GPU.  My mistake, I didn't read carefully.

**Review by TurboGit — APPROVED** [review]
Looks good and better than what we have in master. I believe this will give better performances for most users and will still give the ability for power users to tune all settings. Thanks!

**Comment by jenshannoschwalm** [comment]
@TurboGit i worked on this slightly more early today, i would suggest (besides some cleanup and added comments)
1. to remove the "debugging modes" from the ui as it might confuse common users and we only want them while testing & debugging and know how to start via --conf ...
2. these debugging mode should have fixed values for all parameters we discussed here, so we can use a const table for these modes
3. i would add a "notebook" mode 16GB & integrated graphics 400GB available graphics ram.

All in the hope, devs can easily test how modules behave performancewise on common systems

**Comment by kofa73** [comment]
Thanks for this.

    [memory] cur used memory   (vmrss ):      364788 kB
    8.890342 [dev_pixelpipe] took 0.004 secs (0.036 CPU) initing base buffer [export]
    8.915825 [dt_opencl_get_unused_device_mem] 5581MB available, 495MB of 6077MB on device 0 already used
    8.915832 [dt_opencl_get_device_available] use 5453MB (tune=ON) as available on device 0

    $ nvidia-smi -q -d MEMORY
    
    ==============NVSMI LOG==============
    
    Timestamp                                 : Thu Mar  3 20:13:12 2022
    Driver Version                            : 470.103.01
    CUDA Version                              : 11.4
    
    Attached GPUs                             : 1
    GPU 00000000:09:00.0
        FB Memory Usage
            Total                             : 6077 MiB
            Used                              : 495 MiB
            Free                              : 5582 MiB
        BAR1 Memory Usage
            Total                             : 256 MiB
            Used                              : 7 MiB
            Free                              : 249 MiB

**Comment by todd-prior** [comment]
I tried this last night. My new PC arrived. I took a look at the Darktablerc file to see what it looked like...Headroom is there but shows no value so Headroom=   and then farther down were small default large unrestricted...each referred to a group of numbers....I wasn't 100% sure what those numbers were.... I thing the first was the old memory set aside for DT....were the others tiling and thumb cache, ie all the older paramaters that used to be in preferences....

**Pull request merged**
