### PR TITLE
CMake: small libjxl search improvements

### PR DESCRIPTION
**Pull request by kmilos**
Switched to full signature of the find function to get standard version handling and messages.

### CODE REVIEW

**Review by TurboGit — COMMENTED** [review]
This is beyond my knowledge, it seems safe and simple... Would this fit into 4.2 branch?

**Comment by kmilos** [comment]
Yes, this is almost a cosmetic change.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by TurboGit** [comment]
Merged in master & 4.2 branch.

**Pull request merged**
