### PR TITLE
filmicrgb: add new color science and Euclidean norm with proper scaling

### PR DESCRIPTION
**Pull request by flannelhead**
This one is perceptually a better match with the other norms than the current Euclidean norm because it gives the same values for greys as the other norms. Also implements spherical linear interpolation of saturation like https://github.com/darktable-org/darktable/pull/8254.

Here's a video demonstrating first the RGB power norm, then the existing RGB euclidean norm (v1) and then the newly added Euclidean norm (v2). You can observe the change of luminance and quite weird behaviour with the Euclidean v1 one.

https://user-images.githubusercontent.com/5001906/108592661-9d29d900-7377-11eb-922a-df5cd4c7f51f.mp4

### CODE REVIEW

**Comment by flannelhead** [comment]
I think this is ready for review now :) Added a video demonstrating the behaviour of the different norms when changing the saturation.

**Comment by aurelienpierre** [comment]
I don't understand the reasoning behind the division by √3

**Comment by flannelhead** [comment]
> I don't understand the reasoning behind the division by √3

Please consider the values of the various norms for a grey pixel (which would not be affected by the chroma preservation / saturation code): `(R, G, B) = (x, x, x)`:

* `max(R, G, B) = x`
* `Y(x, x, x) = x` (as far as I can tell the RGB to XYZ matrices are normalized to give `Y = 1` at the medium peak luminosity, `(R, G, B) = (1, 1, 1)`
* Power norm: `(x^3 + x^3 + x^3) / (x^2 + x^2 + x^2)` = (3x^3) / (3x^2) = x`
* Euclidean norm: `sqrt(x^2 + x^2 + x^2) = sqrt(3x^2) = sqrt(3) * x`

So the Euclidean norm is the only one which differs here, hence changing to that alters the Filmic curve reponse because the norm is `sqrt(3)` times greater than with the other norms (considering grey pixels, anyway).

Another side effect is that for a grey pixel, the color component ratios get the value `1 / sqrt(3)`. The desaturation code in the v4 color science pulls these towards the value 1 (by linear interpolation), thus lightening the pixels in deep shadows and highlights. I believe this is an unintended side effect.

Please also see the video, the difference of the current Euclidean norm compared to the other norms is quite drastic especially if the midtone saturation is altered.

**Comment by aurelienpierre** [comment]
> (as far as I can tell the RGB to XYZ matrices are normalized to give Y = 1 at the medium peak luminosity, 

Yeah but we don't care about medium at that step and `x` is unbounded there, so `Y(x, x, x) = a x + b x + c x` in general.

> So the Euclidean norm is the only one which differs here, hence changing to that alters the Filmic curve reponse because the norm is sqrt(3) times greater than with the other norms (considering grey pixels, anyway).

Ok.

On another note, please separate that new norm from the new color science. The spherical interpolation can go in a new "color science v (n+1)" for all available norms, and the new norm can go with the others and be handled in an uniform fashion. Both settings are orthogonal anyway.

**Comment by flannelhead** [comment]
> On another note, please separate that new norm from the new color science. The spherical interpolation can go in a new "color science v (n+1)" for all available norms, and the new norm can go with the others and be handled in an uniform fashion.

I'm not quite sure about this. The idea behind using spherical linear interpolation is specifically to preserve the Euclidean norm at all points under the (de)saturation operations, and as such doesn't directly apply to the other norms. For example, if the ratios are normalized to `max(R, G, B)`, at least one component of the ratios is 1 and doesn't change under the current desaturation code. I think the same applies to at least the luminance Y norm (the ratios are normalized to have Y = 1, and we linearly interpolate toward `(R, G, B) = (1, 1, 1)` which also should have Y = 1, so the luminance Y norm is preserved under the desaturation). If we apply the spherical linear interpolation in conjunction with these norms, the chosen norm might not necessarily be preserved.

I'm not so sure about the power norm, it might be more difficult to implement a norm-preserving (de)saturation operation. Perhaps it can be derived, or perhaps it would suffice to normalize the ratios again after applying desaturation. That doesn't necessarily give a uniform response to the slider (like the spherical linear interpolation gives with the Euclidean norm), but that might not be too noticeable.

So indeed, perhaps it could be good to introduce a new color science version (v5, then?) which ensures the preservation of the chosen norm after the desaturation.

**Comment by flannelhead** [comment]
@aurelienpierre updated this now with the following changes:

* the existing Euclidean norm is named "RGB euclidean norm (legacy)" and moved to the bottom of the combobox
* introduced color science version 5 which preserves the norm after applying desaturation. I decided the special case of spherical linear interpolation is probably not worth the additional complexity. Instead, apply desaturation as it used to be and normalize after that.

**Comment by flannelhead** [comment]
The difference between the current and new color science is subtle and should make a difference only with power norm and Euclidean norm. The difference is mostly visible in highlights with saturated colors (e.g. sunsets).

**Comment by aurelienpierre** [comment]
I'm going to review that this week.

**Review by aurelienpierre — APPROVED** [review]
Good to go, thanks !

**Pull request merged**
