### PR TITLE
vibrancergb: new module.

### PR DESCRIPTION
**Pull request by TurboGit**
This module computes vibrance with the same formulae used in the basic
adjustment module which will be deprecated as superseded by the new
quick access module group.

At the same time this vibrance module works in RGB whereas the old
vibrance module was working in Lab.

Continued work for #8168.

### CODE REVIEW

**Comment by elstoc** [comment]
Should we deprecate the Lab vibrance module too?

**Comment by TurboGit** [comment]
@elstoc : Yes, I'll do that later in another commit in this PR. No more time tonight.

**Comment by TurboGit** [comment]
Modules deprecations are now done.

I think that next step is to propose a default quick access module that correspond as close as possible to what basic adjustment was doing:

image

Note that one feature that we won't be able to have is the [auto] feature.

**Comment by johnny-bit** [comment]
> Note that one feature that we won't be able to have is the [auto] feature.

I don't think we need the `[auto]` feature. It's too close to the promise of the most evil creation of `[make my image pretty]` button. :wink:

**Comment by parafin** [comment]
> > Note that one feature that we won't be able to have is the [auto] feature.
> 
> I don't think we need the `[auto]` feature. It's too close to the promise of the most evil creation of `[make my image pretty]` button.

Well, we could integrate with a device like this: https://www.youtube.com/watch?v=nZtfW2e2Cp0
Then `[make my image pretty]` button would make perfect sense;)

**Comment by TurboGit** [comment]
> I don't think we need the `[auto]` feature.

I fully agree, my point was just to be sure all consequences are on the table and discussed.

**Comment by Mark-64** [comment]
Does this replaces Velvia too?

**Comment by TurboGit** [comment]
No, velvia is quite different processing.

**Comment by TurboGit** [comment]
This should cover issues discussed in #8168 now.

**Comment by Nilvus** [comment]
> This should cover issues discussed in #8168 now.

Maybe link the issue on that PR to close it automatically?

**Comment by Mark-64** [comment]
Tested this PR (in windows) and I noticed is something strange.
If I open an old edit, there is no way to show the new module. I can add to / remove from a group, but it doesn't show up in the gui.
Also, typing "vibrance" (or part of it) in the module search box does not show the new module (nor the old, as it is deprecated).
With a new edit everything is normal.
Is that OK?

**Comment by MStraeten** [comment]
seems to be an issue with it iop_order - you can check if there's a message in the console output

**Comment by Mark-64** [comment]
Yes, I get the message `cannot get iop-order for vibrancergb instance 0`

**Comment by TurboGit** [comment]
@Mark-64 : should be fixed, a stupid mistake. can you check again ? TIA.

**Comment by Mark-64** [comment]
@TurboGit Issue solved now!

**Comment by elstoc** [comment]
@TurboGit: Should we have deprecation messages on the old vibrance and basic adjustments modules like we have on the others (to point the user to alternatives)?

**Pull request merged**
