### PR TITLE
Add some darkening of the rejected thumb's background.

### PR DESCRIPTION
**Pull request by TurboGit**
Following our discussion on #10107

### CODE REVIEW

**Review by Nilvus — CHANGES_REQUESTED** [review]
This darken too much background, especially in grey theme. And thus, this make themes between them less coherent.

As background color is set once, it's better to use shade CSS setting. I suggest to use this code:

```
.dt_thumbnail_rating_6 #thumb_back
{
  background-color: shade(@thumbnail_bg_color,0.9); /* also fade the thumb background */
}
```

**Comment by Nilvus** [comment]
Oups, error in previous comment. It's 0.95 not 0.9, so CSS code to apply:

```
.dt_thumbnail_rating_6 #thumb_back
{
  background-color: shade(@thumbnail_bg_color,0.95); /* also fade the thumb background */
}
```

**Comment by TurboGit** [comment]
@Nilvus : Indeed using a `shade()` is better to ensure uniform rendering for all the theming! For me the background does not stand out, those are rejected images and I think they should be easily distinguishable from others, what works for me is:

```
.dt_thumbnail_rating_6 #thumb_back
{
  background-color: shade(@thumbnail_bg_color,0.8); /* also fade the thumb background */
}
```
Ok for you?

**Comment by Nilvus** [comment]
It stand out, maybe not too much for you. 0.8 is too much (particularly in grey theme) so I'm not ok. 0.9 should be a better compromise. Or at worse, 0.85 for darker and dark theme and so add in grey theme css file same CSS code but with 0.9.

**Review by Nilvus — APPROVED** [review]
All good for me. Thanks!

**Comment by TurboGit** [comment]
Thanks !

**Pull request merged**
