### PR TITLE
Bump OpenCL to version 1.2

### PR DESCRIPTION
**Pull request by aurelienpierre**
Can give a slight performance boost. All hardware since 2012 should be supported now.

### CODE REVIEW

**Comment by TurboGit** [comment]
As far as I know this is only for testing CL kernels for the CI builder. It is not used by dt itself.

The kernels are compile in src/common/opencl.c

**Comment by TurboGit** [comment]
I'll merge this anyway. It won't bring speed, but at least we will check the kernel against OpenCL 1.2.

**Comment by upegelow** [comment]
> Can give a slight performance boost. All hardware since 2012 should be supported now.

Any proof for that? I am interested to see. If not this is just a deliberate reduction of interoperability.

**Comment by aurelienpierre** [comment]
> > Can give a slight performance boost. All hardware since 2012 should be supported now.
> 
> Any proof for that? I am interested to see. If not this is just a deliberate reduction of interoperability.

I have just benchmarked it on my system with a development history using intensive GPU IOPs (denoise profile, retouch, wavelets, local laplacian). OpenCL 2.0 is the slowest, OpenCL 1.1 is average, OpenCL 1.2 is the best, and OpenCL 2.2 is not compatible since it relies on C++.

**Comment by upegelow** [comment]
Am 21.02.19 um 20:45 schrieb Aurélien PIERRE:
>         Can give a slight performance boost. All hardware since 2012
>         should be supported now.
> 
>     Any proof for that? I am interested to see. If not this is just a
>     deliberate reduction of interoperability.
> 
> I have just benchmarked it on my system with a development history using 
> intensive GPU IOPs (denoise profile, retouch, wavelets, local 
> laplacian). OpenCL 2.0 is the slowest, OpenCL 1.1 is average, OpenCL 1.2 
> is the best, and OpenCL 2.2 is not compatible since it relies on C++.
Any numbers?

**Comment by aurelienpierre** [comment]
It's up to 5 % speed-up. Nothing dramatic.

**Comment by aurelienpierre** [comment]
Actually, my bad… It seems that this particular option does not affect the real kernel building, and without `cl-std` argument, the compiler just takes the higher version available. The ± 5 % should just be natural variability.

**Pull request merged**
