### PR TITLE
import preferences: fix position of set_preferences() inside USE_LUA clauses

### PR DESCRIPTION
**Pull request by phweyland**

### CODE REVIEW

**Comment by johnny-bit** [comment]
In builds without LUA this is not needed:

```c
dt_lib_import_t *d = (dt_lib_import_t *)self->data;
```

So should be moved to
```c
#ifdef USE_LUA
  dt_lib_import_t *d = (dt_lib_import_t *)self->data;
  gtk_box_pack_start(GTK_BOX(main_box), d->extra_lua_widgets , FALSE, FALSE, 0);
  gtk_container_foreach(GTK_CONTAINER(d->extra_lua_widgets), reset_child, NULL);
#endif
```

(I for example build without lua enabled :) )

**Comment by phweyland** [comment]
Right ! Thanks @johnny-bit !

**Comment by TurboGit** [comment]
Thanks !

**Comment by Nilvus** [comment]
Just updated master with last import fix and so that PR. I confirm that I now have preferences in import module. So issue fix, thanks for your work again @phweyland.

**Pull request merged**
