### PR TITLE
Introduce dt_action_process to execute any action from LUA

### PR DESCRIPTION
**Pull request by dterrahe**
@wpferguson this one is for you!

The new function `dt_action_process` is meant to be called from lua with three strings, describing the `action `node, the `element `and the `effect`, an integer for `instance `(in case of iop widgets) and a `size `variable (for moves or setting a direct value). The function returns a float, which can indicate the resulting on/off position of toggles, the relative position for a slider (with different encodings to determine what light pattern should be used around a knob like on the x-touch mini) _or_ a direct value (if used with the "set" effect on a slider).

If the size parameter is set to NAN, no action is performed; this can be used to just read values. For any "action" like toggling a button etc, make sure to set it to a value (for example 0) and not NAN.

examples:
```
  dt_action_process("lib/colorpicker/add sample", 0, NULL, NULL, 0);
  dt_action_process("lib/export/high quality resampling", 0, NULL, "next", 1);
  dt_action_process("views/thumbtable/rating", 0, "three", NULL, 0);
  dt_action_process("iop/colorbalance/mid-tones/blue", 0, NULL, "set", 0.3333);
  float val = dt_action_process("iop/colorbalance/mid-tones/red", 0, NULL, "set", NAN);
  dt_action_process("iop/colorbalance/highlights/red", 0, NULL, "set", val);
  dt_action_process("iop/colorbalance/highlights/factor", 0, "button", NULL, 0);
```
obviously, some of these already have dedicated lua interfaces, which is the better approach for standard library functions.

For a complete list of all available actions, press CTRL-SHIFT-ALT-I, which besides reinitialising inputs also writes a file `all_actions` to the config directory.

BTW I tried to look at implementing the lua call myself (and add a simple library module with just three Entries for the strings, a drop down for the instance, a spinbox for the value, a checkbox to set value to NAN and an execute button. But I couldn't figure out how lua interfaces work :-) 
@wpferguson if you don't have time for a while, let me know and I'll give it another go. But it looks _complicated_. :-)

### CODE REVIEW

**Comment by wpferguson** [comment]
@dterrahe I will try and get to this during the upcoming week.

**Comment by wpferguson** [comment]
Played with dt_action_process a little bit.  Created a lua call, darktable.gui.action() which takes the same arguments as dt_action_process() and just passes them.  Wrote a quick lua script to toggle the bottom panel to the next state every time it runs.  I've attached the script and a modified src/lua/gui.c file.
[test.zip](https://github.com/darktable-org/darktable/files/7149101/test.zip)
[gui.zip](https://github.com/darktable-org/darktable/files/7149103/gui.zip)

**Comment by dterrahe** [comment]
Thank you!

I've merged your glue function into my PR (with some simplification after const correcting the dt_action_process function).

Also submitted an example lua module to lua-scripts. 
https://github.com/darktable-org/lua-scripts/pull/362
This is one of my first attempts at lua; I'm not yet succeeding in showing the return value in the gui...

**Comment by wpferguson** [comment]
Here's a corrected gui.c.  The reason you couldn't see the return argument was I returned 0 instead of 1.  You can either use this one, or just change the return statement to `return 1;`  I would also take out the stack dump and any other debugging statements.

[gui.zip](https://github.com/darktable-org/darktable/files/7150956/gui.zip)

**Comment by dterrahe** [comment]
Thanks! Now the return value is indeed shown.

Which made it easier to see that passing the NaN doesn't work; it gets caught here
`  float move_size = luaL_checknumber(L, 5);
`
Any ideas how I might resolve this? I'm looking at `lua_atpanic` and related stuff, but it all looks a little daunting and likely to interfere with the whole lua system, so I'm not even going to try and mess with it without your guidance...

**Comment by wpferguson** [comment]
Can you paste the output?  It works fine for me but I have a guess as to what might be happening

**Comment by dterrahe** [comment]
When  I'm trying to pass NaN as 5th parameter (by unticking "perform action"), I get this:
```
lua stack at action_cb:109(size 5),
        1:string lib/filter/view
        2:string 0
        3:string 
        4:string next
        5:nil nil
```
and `dt_action_process` isn't called (so no return is shown).
If I _do_ activate "perform action", I get this, as expected:

```
lua stack at action_cb:109(size 5),
        1:string lib/filter/view
        2:string 0
        3:string 
        4:string next
        5:string 1
```
and the current position of the dropdown is returned, as it should.

**Comment by wpferguson** [comment]
I think the problem is the way the lua 5.4 library is built.  There is a flag to build with lua 5.3 compatibility.  5.3 compatibility causes tables to work as before, but it seems it doesn't like NaN.  Without 5.3 compatibility, NaN is acceptable, but table usage changes.

I propose that instead of passing NaN from the lua script, we just pass an empty string or nil.  I'll trap it on the back end and convert it to a NaN as necessary to pass to the C function.

**Comment by dterrahe** [comment]
That sounds like a good solution!

**Comment by wpferguson** [comment]
I'll code it up this evening and send it to you

**Comment by wpferguson** [comment]
Here's the latest version.  You can pass nil or "" and it will get converted to NAN.

[gui.zip](https://github.com/darktable-org/darktable/files/7166380/gui.zip)

**Comment by dterrahe** [comment]
Thanks for this. I have a couple of questions:
- you are `strdup`ing the results of `luaL_checkstring`. I assumed this was needed because my original version of dt_action_process was taking `gchar *`s, not `const gchar *`s. I've changed that now, so I think it is no longer needed?
- I'm new to the lua type system, but I guess it should also be possible to directly pass a _float_ to darktable.gui.action (without converting it to a string first)?

The below seems to work for me;  any reason why it wouldn't?
```
static int action_cb(lua_State *L)
{
  const gchar *action = luaL_checkstring(L, 1);
  int instance = luaL_checkinteger(L, 2);
  const gchar *element = lua_type(L, 3) == LUA_TSTRING ? luaL_checkstring(L, 3) : NULL;
  const gchar *effect = lua_type(L, 4) == LUA_TSTRING ? luaL_checkstring(L, 4) : NULL;

  float move_size = NAN;

  if(lua_type(L, 5) == LUA_TNUMBER ||
     (lua_type(L, 5) == LUA_TSTRING && strlen(luaL_checkstring(L, 5)) > 0))
  {
    move_size = luaL_checknumber(L, 5);
  }

  float ret_val = dt_action_process(action, instance, element, effect, move_size);

  lua_pushnumber(L, ret_val);

  return 1;
}
```

**Comment by wpferguson** [comment]
On Wed, Sep 15, 2021 at 5:00 AM dterrahe ***@***.***> wrote:

> Thanks for this. I have a couple of questions:
>
>    - you are strduping the results of luaL_checkstring. I assumed this
>    was needed because my original version of dt_action_process was taking gchar
>    *s, not const gchar *s. I've changed that now, so I think it is no
>    longer needed?
>
>
Yes, that's why I did strdup.  I'll fix it

>
>    - I'm new to the lua type system, but I guess it should also be
>    possible to directly pass a *float* to darktable.gui.action (without
>    converting it to a string first)?
>
> luaL_checknumber() will take a float directly, or if a string contains a
number it will be converted to a float.  In the script, the number is
entered into an entry field, so the entry field returns a string.  It can
be converted to a float using tonumber().  I coded the function to check
for a string and then to check if it was empty to allow passing an empty
string instead of NaN, since that may be a problem if lua 5.4 is built with
lua 5.3 compatibility.  I'll play with it some more this evening when I fix
the strdup just to make sure.

**Comment by dterrahe** [comment]
> In the script, the number is entered into an entry field, so the entry field returns a string.

But that's just an example script (and possibly a useful one for testing). The _real_ goal of `darktable.gui.action` is to allow any lua script to trigger any series of actions (on widgets or otherwise) in the gui. And in those cases it would be much more convenient if _speed_ could directly receive a number without having to convert it to a string first. But strings could still be supported as well and anything that is not a number (or a string containing a number) would be treated as NaN.

> I'll play with it some more this evening when I fix the strdup just to make sure.

I already updated my PR with the changed function I'm showing above and it seems to be working for me, so possibly this is just a matter of you testing/reviewing...

**Comment by wpferguson** [comment]
K, thanks.  I'll check it out.

**Comment by wpferguson** [comment]
This looks good.  I tried it with and without lua 5.3 compatibility and it worked fine.  Tested with nil and empty string and it worked fine.  I think it's good to go.

**Review by wpferguson — APPROVED** [review]

**Review by TurboGit — APPROVED** [review]
Thanks for the team work ! Good to me.

**Pull request merged**
