### PR TITLE
Module highlights must only be activated for RAW.

### PR DESCRIPTION
**Pull request by TurboGit**
Refine previous fix as we don't want to add the highlights module for non RAW files.

Continued work for #14050.

### CODE REVIEW

**Comment by TurboGit** [comment]
@jenshannoschwalm : I thought about this over the night.

**Comment by jenshannoschwalm** [comment]
We want hlr for sraw images!

**Review by jenshannoschwalm — COMMENTED** [review]
I would suggest to add a comment about the "magic string parameters"

**Comment by TurboGit** [comment]
> I would suggest to add a comment about the "magic string parameters"

Comments added now.

**Comment by jenshannoschwalm** [comment]
Perfect

**Pull request merged**
