### PR TITLE
[RFC] eliminate NAN as marker value (part 1)

### PR DESCRIPTION
**Pull request by ralfbrown**
This PR consolidates all setting and testing of the "non-matrix" flag value for color profiles into a pair of inline functions, and then switches the actual marker value from NAN to -FLT_MAX.  It is a more general fix for #14100 and contributes to eventually being able to apply the -ffinite-math-only optimization globally.

Although the PR passes the integration tests, it needs more testing before merge as all of the integration tests use matrix color profiles.  The few ICC profiles I have which aren't matrix profiles cause the installed version of lcms2 to issue an error message and substitute a built-in matrix profile for sRGB....  So if anybody has LUT-based ICC profiles, I would appreciate test runs with various settings of input and output color profile modules.

### CODE REVIEW

**Comment by TurboGit** [comment]
Is that still a draft? Should this be integrated at the same tome as part 2?

**Comment by ralfbrown** [comment]
It doesn't need to be integrated at the same time, and I'd prefer having confirmation that this PR doesn't break non-LUT color profiles before merging.

**Comment by TurboGit** [comment]
> that this PR doesn't break non-LUT color profiles before merging.

And how to test such beast? Do you have a non-LUT color profiles? I'm no expert at all about this :)

**Comment by ralfbrown** [comment]
Oops, I meant non-matrix (i.e. LUT) profiles.  I asked for testers originally because I don't have any LUT profiles that actually the version of LCMS2 I have will actually accept....

**Comment by parafin** [comment]
you could probably generate one with a color checker target and dcamprof

**Comment by ralfbrown** [comment]
I can't figure out the failure - it may be another false positive from the compiler:
> /home/runner/work/darktable/darktable/src/src/common/iop_profile.c:778:8: error: ‘dt_colorspaces_get_matrix_from_input_profile’ accessing 64 bytes in a region of size 16 [-Werror=stringop-overflow=]

At that point, a function expecting a dt_colormatrix_t as second parameter is getting a dt_colormatrix_t as second parameter....  The only thing I can conjecture is that the compiler is confused by the fact that that type is defined as a two-d array: float[4][4].  If it's only considering the first element of the first dimension, x[0] on the calling side is 16 bytes compared to the type's overall 64 bytes, which matches the error message.

Will try rebasing in case something else is causing confusion since I originally opened the PR, even though there are no merge conflicts.

**Comment by ralfbrown** [comment]
Squashed the multiple attempts to please the compiler

**Comment by ralfbrown** [comment]
Trying the type-punning first, as that's a smaller change.  It compiles fine in RelWithDebInfo on my machine, and I'm expecting it to pass CI like the previous version did, so you'll need to also try it on your build machine.

**Comment by ralfbrown** [comment]
Looks like CI is having problems.  First one of the LLVM runs fails almost immediately with no output whatsoever, then after kicking it into another run I get the same on Windows and XCode14....

**Comment by TurboGit** [comment]
Some more issues:

```
/home/obry/dev/builds/c-darktable/x86_64-linux-gnu-default/src/src/iop/colorout.c:734:9: error: ‘dt_colorspaces_get_matrix_from_output_profile’ accessing 64 bytes in a region of size 16 [-Werror=stringop-overflow=]
  734 |      || dt_colorspaces_get_matrix_from_output_profile(output, *((dt_colormatrix_t*)&d->cmatrix),
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  735 |                                                       d->lut[0], d->lut[1], d->lut[2], LUT_SAMPLES))
      |                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```

```
/home/obry/dev/builds/c-darktable/x86_64-linux-gnu-default/src/src/iop/colorin.c: In function ‘commit_params’:
/home/obry/dev/builds/c-darktable/x86_64-linux-gnu-default/src/src/iop/colorin.c:1436:8: error: ‘dt_colorspaces_get_matrix_from_input_profile’ accessing 64 bytes in a region of size 16 [-Werror=stringop-overflow=]
 1436 |     if(dt_colorspaces_get_matrix_from_input_profile(d->input, *matrix_ptr,
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1437 |                                                     d->lut[0], d->lut[1], d->lut[2], LUT_SAMPLES))
      |                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```

**Comment by ralfbrown** [comment]
OK, so the type-punning dance doesn't work,  we need a separate local copy....  Will get on it tonight.

**Comment by ralfbrown** [comment]
On second thought, the most elegant solution is simply to conditionally suppress the erroneous warning with a preprocessor macro.
@TurboGit you'll need to compile on your machine again since the problem doesn't manifest with the GCC used by CI.

**Review by TurboGit — APPROVED** [review]
Works for me now, thanks!

**Comment by parafin** [comment]
> I can't figure out the failure - it may be another false positive from the compiler:
> 
> > /home/runner/work/darktable/darktable/src/src/common/iop_profile.c:778:8: error: ‘dt_colorspaces_get_matrix_from_input_profile’ accessing 64 bytes in a region of size 16 [-Werror=stringop-overflow=]
> 
> At that point, a function expecting a dt_colormatrix_t as second parameter is getting a dt_colormatrix_t as second parameter.... The only thing I can conjecture is that the compiler is confused by the fact that that type is defined as a two-d array: float[4][4]. If it's only considering the first element of the first dimension, x[0] on the calling side is 16 bytes compared to the type's overall 64 bytes, which matches the error message.

My guess would be that compiler loses information (which is a bug indeed) about dt_colormatrix_t size when float[4][4] is decayed to *(float[4]) when passing as function parameter. Maybe it wants `memcpy(matrix, matrix_tmp, sizeof(dt_colormatrix_t));` to become a loop writing just 16 bytes 4 times. I suspect changing argument type from dt_colormatrix_t to dt_colormatrix_t* could solve it (also it would make it explicit when argument is used for output, and will force compiler to check all array dimensions).

**Comment by kmilos** [comment]
Btw, I couldn't get the following snippet to trigger the error on [godbolt ](https://godbolt.org/) with any recent GCC 12.x/13.x version (nor my local MinGW GCC 12.2) when adding `-Werror`:
```
#include <string.h>

#define DT_ALIGNED_ARRAY __attribute__((aligned(64)))

typedef float DT_ALIGNED_ARRAY dt_colormatrix_t[4][4];

void bar(dt_colormatrix_t matrix) {
  dt_colormatrix_t matrix_tmp = {0};

  memcpy(matrix, matrix_tmp, sizeof(dt_colormatrix_t));
}

void foo() {
  dt_colormatrix_t matrix = {0};

  bar(matrix);
}
```

**Comment by ralfbrown** [comment]
It seems to require quite specific circumstances to trigger.  There are lots of places where a dt_colormatrix_t is an output parameter.

The particular functions calls on which I had to suppress the warning were to trivial wrappers which pass down their arguments plus one additional one to another function.  They all happen to be for a pair of functions which delegate to the same underlying function.

**Comment by kmilos** [comment]
> I'd go with `dt_colormatrix_t`

That doesn't workaround the said bug (it really has to do w/ GCC trying to figure out what is in the struct), so it'll have to be either `float*` or `dt_colormatrix_t*` for now...

**Comment by parafin** [comment]
> > I'd go with `dt_colormatrix_t`
> 
> That doesn't workaround the said bug (it really has to do w/ GCC trying to figure out what is in the struct), so it'll have to be either `float*` or `dt_colormatrix_t*` for now...

How so? If we change `dt_mark_colormatrix_invalid` to take `dt_colormatrix_t` it will get rid of this warning/error. I've found though two problems to be resolved with this approach:

1. Most places set NaN to just the first element, but in couple of places more elements are marked with NaN also. Not sure if it's required/needed. Or maybe mark all elements always?
2. There is a couple of calls `dt_mark_colormatrix_invalid(img->d65_color_matrix)`, while `d65_color_matrix` is `float[9]` and not `dt_colormatrix_t`. Probably should be converted to `dt_colormatrix_t`?..

**Comment by parafin** [comment]
If you remove a call to bar1 you won't get a failure. I'm also trying a different thing, maybe we came up with the same idea, let's see:)

**Comment by kmilos** [comment]
Ah, the one I have in mind works (in terms of compiler being ok with it), but then realized breaks ABI wrt to stored serialized parameters in the database or sidecars...

The idea was to just change the order of the struct fields and put `dt_colormatrix_t` first due to [the last comment sentence](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105689#c2)...

**Pull request merged**
