### PR TITLE
LibRaw: update submodule for CR3 decoding fix

### PR DESCRIPTION
**Pull request by kmilos**
Fixes https://github.com/darktable-org/darktable/issues/15955

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Double checked, all good on my side. Thanks!

**Comment by kmilos** [comment]
Should probably go for 4.6.1...

**Comment by TurboGit** [comment]
> Should probably go for 4.6.1...

Ok, merging there too.

**Comment by TurboGit** [comment]
Done, just need a release note entry. TIA.

**Comment by TurboGit** [comment]
It is a user visible issue on dt, don't hurt to have an entry in the release notes. Thanks!

**Pull request merged**
