### PR TITLE
manage-module-groups: Move to tabbed interface

### LINKED ISSUE #8562: manage module layouts: convert side menu to combobox
The manage module layouts screen often has module groups that disappear off the right-hand-side of the dialog.

I would like to suggest that the left-hand menu pane be converted to a combobox at the top of the dialog so that more horizontal space can be given over to the module group manipulation pane.

This could even be combined into the existing "preset name" entry field.

### PR DESCRIPTION
**Pull request by elstoc**
Resolves #8562

Tabbed interface for managing module groups. Click on the + sign to create a new group. Drag-and-drop the tabs to reorder them. Drag-and-drop the + sign to create and drop a new group in one go (actually a side-effect of how I've had to build this to work around Gtk issues, but not a bad one).

Screenshot_2021-03-29_12-14-01

FYI if you want to test it, I haven't finalised the CSS yet - add the following to preference tweaks for more spaced-out tabs:

```
#modulegroups-groups-box tab
{
  padding-left: 1em;
  padding-right: 1em;
  padding-bottom: 0.5em;
  padding-top: 0.5em;
}
```

### CODE REVIEW

**Comment by TurboGit** [comment]
But the point of the non tabbed view is that you have a full view of the modules and can quickly see if and where such or such module is used. This is really important to build quickly a new group.

**Comment by elstoc** [comment]
This would be fine but practically speaking with the current interface, if you have the quick access panel enabled, you can generally only see two groups at once anyway.

**Comment by elstoc** [comment]
Mostly functional now but falls over when there aren't any module groups. I'll fix the last of the bugs if there's any appetite for the PR generally.

**Comment by AlicVB** [comment]
I've just tested. That's great, I find it better that what we have currently...
...but I've some remarks/suggestions now that you manage gtk :)
- I find the new size of the dialog not very well balanced, maybe we can make it a little more wide by default ?
- the "tabs" will need some refinements. I would make the selection more obvious (grey background like in the module ?) and bigger in width
- I agree with @TurboGit that sometime having more column could be great. Maybe we can allow multiple tab selection with ctrl or shift click ? Yes, I know that means abandoning gtknotebook and doing all by hand. But now that you are used to gtk -D More seriously, if you start from master, you may be able to add a gtkbox with all the "tabs" and show/hide the column manually...

**Comment by elstoc** [comment]
> Maybe we can allow multiple tab selection with ctrl or shift click ?

I'll admit that part of my reluctance with this is not wanting to have to code all this stuff by hand - apart from a couple of minor issues GtkNotebook handles all of this fairly nicely. But I'm also trying to reduce the visual complexity a little and having the ability to partially un-tab a tabbed interface seems to be going in the other direction, especially given that most users will probably set this up once and only make minor adjustments thereafter.

Obviously the other comments about size and style are all pretty simple bells-and-whistles that I can add later.

**Comment by elstoc** [comment]
> EDIT : maybe a solution for the dialog size : in the right part, we may put the "options" and the modulegroups side by side.

So three columns - the preset list, the preset options, then the module groups. Maybe, but that feels like it might look a little cluttered. If we turned the preset list into a combobox and kept it to two columns though... :)

**Comment by dterrahe** [comment]
> This PR also has the advantage of looking like it does in the darkroom so it's obvious how it works.

What does the "manage module layouts" dialog add to the functionality to add/remove modules to/from groups directly in the darkroom? And could those functions be added to the hamburger menu instead, like they are for other modules (so more consistency)? 
I'm seeing:
- create new; "store new preset..."
- remove; "delete this preset..."
- rename; could go in "edit" dialog
- search line on/off; "edit" 
- quick access panel on/off; "edit"
- reorder groups; drag-and-drop module group headers directly in the darkroom
- add/remove groups; could be top two items in right-click menu on group

So to make a slightly devils advocaty suggestion (I know this would throw away a lot of work. but we are not trying to add more and more stuff, we're trying to create a logical and efficient interface) what about adding all the house keeping functions to the hamburger, so it is consistent with all the other presets menus, and then having the "manage layout" dialog show up when selecting "edit" and _just_ show the _current layout (so no tabs on the left) and then make all the columns fit by reducing the width of each column if the dialog is too narrow (with ellipsizing). Then you'll have the complete overview that Pascal wants (and that would be the added value of this dialog). There would still be duplication/two ways in how to manage the _current_ layout, but at least preset creation/deletion would be consistent.

**Comment by AlicVB** [comment]
@dterrahe : no problem at all for dropping my work, it's always a pleasure to remove lines of code :)
In fact, you make a point here : with this PR, the benefit of the dialog over an "in-place" is not so evident... So I tend to agree with you. (That said, I wouldn't keep any dialog, as you propose. otherwise we better keep it completely as it is now)

We have to be careful of one thing : we don't want modulegroups to be changed by "error" during editing. This is esp. true for tab reordering... right-click drag-drop ?

I see 3 solutions : 
1. implement all the "in-place" editing AND keep the dialog as it is now
2. implement all the "in-place" editing and drop the dialog.
3. go with this PR

@elstoc @TurboGit : any opinion here ?

**Comment by dterrahe** [comment]
> 2\. implement all the "in-place" editing and drop the dialog.

You'll need an "edit" dialog at least to be able to edit the name. And for the checkboxes for quick access and search? Main point would be edit is just for 1 preset, not to manage all of them. Whether seeing all lists side-by-side is really useful... It is sort of pretty, so it would feel like a waste of your work not to keep it...

Bikeshedding: I hate drag-dropping with right button; ctrl-left please! ;-)

**Comment by AlicVB** [comment]
> You'll need an "edit" dialog at least to be able to edit the name

we have the standard preset dialog for that



> And for the checkboxes for quick access and search

preset menu ?

To be honest, I'm not sure what is the best here esp. has we are speaking of something that won't be used too often, hence my try of different proposals :)

**Comment by elstoc** [comment]
Some things to consider, though I don't fundamentally object to any of @dterrahe's proposals.

- I think we might end up with a clunky solution if we have some of the preset settings (name and options) maintained in a separate dialog and some maintained via point-and-click on the existing group tabs, especially when setting up a new preset from scratch. It also won't be very flexible if we want to add stuff in the future.
- As mentioned in #8587 the right-click menu is great for adding the occasional option but setting up module groups from scratch using it is pretty tedious. I've put a proposal in #8587 for a way to use the extra space that this PR gives.
- We also should consider my proposals in #8155.

**Comment by AlicVB** [comment]
>     * I think we might end up with a clunky solution if we have some of the preset settings (name and options) maintained in a separate dialog and some maintained via point-and-click on the existing group tabs

Completely agree. That's why I'm not fan of @dterrahe "new" dialog solution without the "global" presets management...

**Comment by dterrahe** [comment]
> Completely agree. That's why I'm not fan of @dterrahe "new" dialog solution without the "global" presets management...

Is "global" presets management the presets tab in the preferences dialog box?

It would be good to consider the best solution _here_ together with the best solution for other places where presets exist. The image information lib, for example, needs to fundamentally solve the same problems (though less complex).

**Comment by AlicVB** [comment]
@dterrahe : here's a quick summary of the current situation for presets in utility modules : 
- import : params are set inside the ui. last params store inside dt rc file
- collect : params are set inside the ui. last params store inside dt rc file
- metadata view : params set in external dialog via the "preference" menuitem. last params store inside dt rc file
- metadata editor : params are set inside the ui. what is set in preference meuitem dialog is not for presets. last params not saved (no need has it's drive by selected image metadata)
- tagging : params are set inside the ui. last params store inside dt rc file
- export : params are set inside the ui + inside preference dialog. last params store inside dt rc file
- modulegroups : params + presets management set in external dialog. possibility of small change directly in the ui. last params store inside a temporary preset (too big for rc file)

tbh, considering the complexity of the possibilities of modulegroups (you may spend lot of time to finetune it) I prefer to have a more clear vision of what I do on presets management side (copy/update/delete/...) We are not in the simple case of "save the ui params"

@elstoc : after some more thought, I wonder if all this is worth the pain : I have the feeling that we try to solve "I don't see all the tab at the same time" by "just show one tab at once"...
imho we should keep the dialog as it is now. But maybe we can add your work as "in-place" editing (point-and-click as you said) So user can use one way or the other depending of their needs. And if they need full control, they will use the dialog (like for setting a layout from scratch)

**Comment by elstoc** [comment]
> I have the feeling that we try to solve "I don't see all the tab at the same time" by "just show one tab at once"

That wasn't the problem I was trying to solve - I don't feel the need to see all of the tabs at the same time. I was trying to solve the fact that I don't really like the current interface, with the half-shown module lists and the scrolling, for example with the "correct" group in the screenshot below

Screenshot_2021-04-02_12-12-38

Even with my tiny fonts, this issue occurs with only three groups plus the QA panel. With more _normal_ fonts (10pt here) it's worse:

Screenshot_2021-04-02_12-18-12

My suggestion of getting rid of the preset list on the left, to give a bit more space, was a possible partial solution to this, and the tabbed control was another idea. I'm happy to consider other ideas but I'm still not a fan of the status quo. If we're going to have the dedicated screen for "from-scratch" setting up, the popup menu is still a bit of a pain point for me. There are a lot of clicks involved in adding lots of modules, and the tabbed setup allows for an extra panel to hold the module list.

**Comment by AlicVB** [comment]
First I'm a bit ashamed to have push you to do all this work and then finally come back with a "finally I don't like"...
reading your last post, I'm mitigated about the horizontal scrolling problem, but definitively, if we manage to be able to show all the available module and just add/remove them by drag-and-drop, that would be a real enhancement !

So, we may better explore your other proposal about getting rid of the preset list and put it inside a combobox ? do you have any clear idea how it would looks ?
Another "easy" thing to do : in your screenshot above, we can see that lot of horizontal place is wasted in each tab : they could be reduced in width, maybe with some ellipsis of very long iop names if needed. Based on your screenshots, a gain of 1/3 seems possible...

**Comment by dterrahe** [comment]
Do we really _need_ the horizontal scrollbar (and the corresponding layer of scrolledwindow) at all?  I'd prefer narrower columns (ellipsized of course) if there are a lot of them and the dialog size can't be increased.
To me this looks perfectly useable.
image

That's just changing
`gtk_widget_set_halign(d->preset_groups_box, GTK_ALIGN_CENTER);`
to
`gtk_widget_set_halign(d->preset_groups_box, GTK_ALIGN_FILL);`
and 
```
  GtkWidget *sw = gtk_scrolled_window_new(NULL, NULL);
  gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW(sw), GTK_POLICY_AUTOMATIC, GTK_POLICY_NEVER);
  gtk_container_add(GTK_CONTAINER(sw), d->preset_groups_box);
  gtk_box_pack_start(GTK_BOX(vb), sw, TRUE, TRUE, 0);
```
to
`  gtk_box_pack_start(GTK_BOX(vb), d->preset_groups_box, TRUE, TRUE, 0);`

plus adding
```
        gtk_label_set_ellipsize(GTK_LABEL(lb), PANGO_ELLIPSIZE_END);
        gtk_label_set_xalign(GTK_LABEL(lb), 0.0);
```
after 
`GtkWidget *lb = gtk_label_new(module->name());`

`gtk_entry_set_width_chars(GTK_ENTRY(tb), 5);`
after
`GtkWidget *tb = gtk_entry_new();`

**Comment by elstoc** [comment]
@dterrahe bear in mind you've chosen a read-only preset in your example. The editable ones are widened by additional controls.

**Comment by dterrahe** [comment]
I also reduced the width of the dialog and picked the default layout with the most columns.

If you _do_ find the below unusable while editing, you could increase the size of the dialog. The advantage would still be an immediate overview showing all columns (and specifically; the _number_ of columns, which can be very helpful in recognising the layout).

image

**Comment by AlicVB** [comment]
@dterrahe : I quite like what you propose, but I would have let the scrollwindow together with a minimum width of column. The width you show are good as a minimum, but if, for example, you add the quick control column, that will become hard to read, not to speak about folks who have 6 groups or more... Enlarging the window is not always an option for some with small screens.

btw, maybe use master as starting point, as there's more controls now (like the quick access column) ;)

**Comment by dterrahe** [comment]
Ah! I had thrown this quickly together as an experiment in a working tree where I'd been testing a PR; didn't notice it was so far behind, sorry.

Anyway, the idea of having the columns scale narrower automatically when there are more of them is incompatible with having them sit within a scrolledwindow (where there is unlimited space). So then they would _always_ be that minimum width, even for people with decent screens. And you would again have the problem of showing half-columns.

Unless... you want to go down the route of dynamically resizing the (homogenous) column widths within the scrolled box based on the width of the scrolled window (using the "size-allocate" signal) and fit it within a min-max range so that a multiple exactly fits the window... (allow a smaller minimum if it means you can fit _all_ columns, but as soon as you need horizontal scrolling _anyway_ then keep to a more comfortable minimum width).

**Comment by elstoc** [comment]
> First I'm a bit ashamed to have push you to do all this work and then finally come back with a "finally I don't like"

Don't worry about that. It was a nice challenge (I enjoy problem-solving) and the goal is to get the best possible solution. If this PR isn't it, that's not a problem.

> So, we may better explore your other proposal about getting rid of the preset list and put it inside a combobox ? do you have any clear idea how it would looks?

Some combination of my idea (getting rid of the side panel to free up horizontal space) and @dterrahe's (to efficiently use that space) should work quite well. 

I would envisage the existing entry box (where you can change the name) being replaced with a combined entry/combobox, in which you would either type to rename the current preset or select a new one to edit. The duplicate/delete/add buttons would sit alongside the entry/combobox, and the other options would be laid out below (in two columns to save vertical space?). I would also move the reset button to the top-right, again, to better use the available space.

In terms of making it easy to add multiple modules/widgets, could we make the popup menu only disappear when the user clicks away from it, so they could multi-select?

**Comment by AlicVB** [comment]
I fear that renaming inside the combobox might be confusing, so I would prefer separate widget... And yes, we can use multiple column for that too...

> In terms of making it easy to add multiple modules/widgets, could we make the popup menu only disappear when the user clicks away from it, so they could multi-select?

hmm... not sure : either we will need another action to validate the multi-selection, either we will have to click on another column to validate, which is counter-intuitive (either I've not understand what you've in mind :))
We can also use your proposal of a "permanent" list of all available modules which can be drag-drop inside the columns... The challenge then is to propose a clear ui to differentiate the "groups" column from this one... otherwise it would be really handy !

**Comment by elstoc** [comment]
> either we will need another action to validate the multi-selection, either we will have to click on another column to validate, which is counter-intuitive (either I've not understand what you've in mind :))

Click on an item in the menu, and it disappears from the menu and updates the group list in the background, but the menu remains open (not sure if this is even possible). If done by accident it's one-click (on the X) to remove the added module/widget after the menu closes.

> proposal of a "permanent" list of all available modules

This would have worked well with the tabbed interface, because we had plenty of space, and the list could have been context sensitive (it could have been absent for read-only presets, a widget menu for the QA panel, and a module list for the rest). With a "full view" interface it's more challenging. It can't be context sensitive any more, and it would eat up yet more of the horizontal space we're trying to get back.

**Comment by AlicVB** [comment]
OK, I should have some time to work on this now. Here is a mockup proposal of what @elstoc propose initially combined with the "never scroll" of @dterrahe (not visible in the screenshot). What do you think ?
capture_tmp

**Comment by elstoc** [comment]
Yeah that looks tons better

**Comment by AlicVB** [comment]
> could you perhaps make those autoapply/autofilter settings into greyed-out checkboxes? We've space on the right-hand-side for that now.

Yes putting that on the right, why not, that would gain 1 line in height :)
But we can't really make them checkboxes, as in fact the settings are way more complex (having a autoapply checkbox without all the autoapply filtering will cause more confusion than anything imho). The text is just here as a reminder ;)

**Comment by elstoc** [comment]
> But we can't really make them checkboxes

we can't make them obviously-unselectable greyed-out textboxes? I don't really like the one-line text-only thing but if it can be improved another way that's fine.

**Comment by AlicVB** [comment]
In fact, I've just seen that filter is not implemented for libs, only for iops... (or at least doesn't works for libs)
Other than that, I agree that having a checkbox would be more consistent with the rest of the ui... Will try to do something...

**Pull request closed without merging**
