### PR TITLE
clicking on slider "header" focuses or pops up

### LINKED ISSUE #10478: Click on slider label should give the focus and not change the value
Currently, if you click anywhere inside the rectangular bounding box of a Bauhaus slider, the value will get changed using the x coordinate of your click, even though you are very far from the sliding bar (including a click on its label).

At the same time, the only way of giving focus to a slider is to click on it. Which means you can't give the focus without changing the value. 

But you may want to give only the focus to the slider in order to use arrows and MIDI controllers to actually change the value.

I propose that : 

1. any click outside of the sliding bar ± a safety margin does not record a value change, but only gives focus to the slider for later interaction,
2. a click on the numeric value directly opens the keyboard input/accurate selection widget (touch interfaces may not have right click),
3. in-focus sliders get a style hint, for example a different background & text color,
4. dynamic shortcuts (allowing to access directly a slider through a key) also give the focus to the slider.

### PR DESCRIPTION
**Pull request by dterrahe**
partially fixes #10478

Clicking on the text line of a bauhaus slider does not move the slider anymore, but instead only grabs focus (if  clicked on the left side) or pops up the editor (if clicked on the right side). Ideally, we'd test if the value text is being clicked on (as suggested in #10478) but that would mean redoing the whole cairo context setup just to figure out the length of the text). Splitting the header in left/right works equally well for me.

Styling the focused widget differently needs some careful fixes and probably some CSS. The are 9 calls to `gtk_widget_set_state_flags` some of which indiscriminately set it back to `GTK_STATE_FLAG_NORMAL` independent of focused state. Accepting a value in the popup _does_ result in the label+value being drawn in bold.

### CODE REVIEW

**Comment by AlicVB** [comment]
This can also be handy if one want to adjust the value with arrow keys.
Main drawback is of course that one will need to be more precise with the pointer. Not sure if it's an issue or not but worth mentioning it ;)
last, I would not have split the width in 2, but just used the last 1/4 or 1/6 area for the numeric pad. imho, usually, the text for the value is quite short, compared to the description...

**Comment by dterrahe** [comment]
> This can also be handy if one want to adjust the value with arrow keys.

I think that's the main reason to assign focus to the widget. Previously it wasn't possible to do this without changing the value or opening and closing the popup.

> one will need to be more precise with the pointer.

Yes, but only when clicking. In which case it makes sense to aim for the slider itself anyway. Scrolling still works on the whole widget. And once dragging, you also don't have to stay on the slider.

> usually, the text for the value is quite short, compared to the description...

Unless the panel is narrow, in which case the description gets truncated. I think left/right (split in the middle) is easier to explain and to figure out experimentally.

**Review by TurboGit — APPROVED** [review]
Tests, works for me. Thanks!

**Comment by elstoc** [comment]
> one will need to be more precise with the pointer.

Sorry I only just came across this in master (been a while since I rebuilt). I preferred the greater scope for clicking+dragging anywhere on the slider (including the header) and personally wouldn't use the "click to focus" much if at all. IMO it was better before this change and I'm missing my click+drag quite often at the moment.

**Comment by Jiyone** [comment]
I just wanted to comment that I second what @elstoc says. It's hard to dragg in that small space while looking at the picture. Before, it was difficult because other parameters where modified if the mouse was overlapping those parameters while click+dragging, althought the space for click+dragging was good.

**Comment by dterrahe** [comment]
I'll look at this again, because the drag was meant to work as before; only the initial click was meant to differentiate between the header and the slider.

**Comment by elstoc** [comment]
This will also affect people who click somewhere on the slider to set the value as well though, which I have been known to do in the past.

**Comment by dterrahe** [comment]
> This will also affect people who click somewhere on the slider to set the value as well though, which I have been known to do in the past (i.e. my issue _is_ with the initial click).

I was going to propose to @Jiyone to see if I could move the action to button-release so that a click&drag would work anywhere on the widget, but just a click would only focus (or popup) if it was not on the slider and not followed by a drag.

But this would not satisfy you. I myself find just clicking on the slider for an immediate change not very useful, because there is no indication _before_ the click what value you'll get. Obviously if you intended to drag but hit exactly the value you wanted, you could then skip the drag after all and it would look like just a click... Maybe a _long click_ could be treated like a drag (even if outside the slider). I _think_ that would be implementable, but finicky. Do you think it would be worth trying? I know we are used to the old behavior, but as a newcomer it took me a while to get over the expectation that a click on the label should just focus.

**Comment by Jiyone** [comment]
>  I myself find just clicking on the slider for an immediate change not very useful
I do that sometimes : If I want to see like a before/after of one parameter, I put the mouse on the setting, then I double-click to reset, and one clic to set. I find that useful :)

**Comment by Jiyone** [comment]
Actually the most of the time I need to drag, I right-click and use the curve thing. 
The problem with dragging the cursor directly on the setting is that cancel (ctrl+z) is not usable ...

**Comment by dterrahe** [comment]
There might also be a bit of an issue with darktable.bauhaus->line_height vs get_line_height() which multiplies the former by 1.33. A mix of both is used and I assumed the accessor function was the more correct way, but seems I guessed wrong.

I've pushed a fix in #11257; the clickable width of the slider line should feel more comfortable now. Feedback welcome (also on the rest of the PR...)

**Comment by elstoc** [comment]
Hmm it does appear a little less bad on #11257.

**Comment by RawConvert** [comment]
I think you should consider reversing this change.  It was apparent to me as a problem within 10 mins of using a recent build.  I think lots of people will dislike this change if it goes live.

Looking at the original rationale in #10478 I wonder how many people would benefit.  I imagine the percentage of users using a MIDI surface is small. Surely the overwhelming majority are using the mouse rather than arrow keys or MIDI.

For users needing the revised behaviour, would a preferences setting be possible?

I think you should also consider users who are <100% regarding hand-eye coordination, eyesight, dexterity etc.  This change would make using dt rather harder.

**Comment by aurelienpierre** [comment]
I'm also for a revert. This new behaviour is really annoying, especially since right click still works on the label/header.

**Comment by elstoc** [comment]
Agreed. I've used this for a while and I still can't get used to it. I'm forever clicking and dragging without realising I've missed the control because I've moved my eyes to the image so I can see the effect.

**Comment by elstoc** [comment]
> fixing things becomes impossible

Or people have different ideas of what constitutes a bug

**Comment by elstoc** [comment]
On the whole I don't disagree with your main complaints

> there's no way to focus it to do so without either changing the value

I agree that this is useful to have but I'd prefer a modified click (Ctrl+click, say) to do this (which could similarly operate on the whole widget height). Working this way would allow a consistent action to be used with more complex sliders like those in the parametric masks (though here, we'd need a more precise Ctrl+clickable area to distinguish between the individual sliders).

> The fact that there was no boundary between impacting one slider and the one below similarly felt unpolished

I don't have a problem with only 80-90% of the widget height being clickable, to enforce some border between sliders, but the current PR is much less than that in order to provide the new left-click functionality, and the required slider click for value change is too fiddly.

**Comment by RawConvert** [comment]
@dterrahe , I was just (briefly) trying arrow keys with a slider, and can see they work and have a fine and coarse (shift) mode.  However Tab doesn't seem to do anything useful here, and I can appreciate that if you are a keyboard person, you probably don't want to use the mouse to select the control.  So how about using Tab (or a user assigned key) to move between controls? E.g. I open Exposure then "logical tab" a couple of times to get me to the Exp. slider, then use the arrow keys, then if I really wanted, "tab" to black level correction, etc.  Just a thought, probably breaks the design!

**Comment by dterrahe** [comment]
> probably breaks the design

Indeed. People are used to TAB (un)hiding the panels. Except when in a text entry box; then (shift+)TAB works as "normal".

**Comment by RawConvert** [comment]
User-assigned key/combo then?

**Comment by TurboGit** [comment]
Just a thought, could using a lager padding for the sliders help here to gain a larger active area?

**Comment by TurboGit** [comment]
Not necessary the slider bu the area around it. The padding is part of the widget so we maybe can make it bigger and use less margin to compensate if necessary. That's just a thought, but now that sliders are themable using CSS maybe there is hope...

**Comment by TurboGit** [comment]
Try this for example, it makes the clickable area a bit larger below the slider, maybe this will help:

```
#bauhaus_slider
{
  background-color: @plugin_bg_color;
  padding-bottom: 0.2em;
}
```

**Comment by AlicVB** [comment]
I would add that the "space" above the slider is better for click and drag than the space below. The problem is that there's very few space between text and slider (esp. between text and the triangle).
Note that as we draw everything ourselves, we can do what we want and we can only reserve the top half part of the text for focus, and the rest for "classic" value modification... but I fear that will be worse...

**Pull request merged**
