### PR TITLE
Escape key will cancel history dialog (bug #11317)

### PR DESCRIPTION
**Pull request by catlee**

### CODE REVIEW

**Comment by catlee** [comment]
How do I get to that dialog from the UI?

**Comment by LebedevRI** [comment]
By default, https://github.com/darktable-org/darktable/blob/48fae49e683f0fc1141677f07059796c6cd30984/src/libs/tools/filmstrip.c#L180-L181, while some image is selected and/or highlighted in filmstrip. And, it is always a good idea to test all the changes :)

**Comment by shoffmeister** [comment]
Just a random note: 

    if(dt_gui_hist_dialog_new(&(strip->dg), strip->history_copy_imgid, TRUE) == GTK_RESPONSE_CANCEL)
      return FALSE;

is not a good pattern in general for a call site. The better approach for these dialogs is to monitor strictly for only the "positive" items, e.g.

    if(dt_gui_hist_dialog_new(&(strip->dg), strip->history_copy_imgid, TRUE) == GTK_RESPONSE_OK)
      return TRUE;

This pattern is much more robust towards change such as introducing handling of the Esc key. I personally would be tempted to (also) rewrite that specific call site to

  gboolean result = FALSE;

  if(_lib_filmstrip_copy_history_key_accel_callback(accel_group, aceeleratable, keyval, modifier, data))
  {
    dt_lib_filmstrip_t *strip = (dt_lib_filmstrip_t *)data;
    if(dt_gui_hist_dialog_new(&(strip->dg), strip->history_copy_imgid, TRUE) == GTK_RESPONSE_OK)
      result = TRUE;
  }

  return result;

but that then is a matter of personal preference, too (and it consumes sizeof(gboolean) on the stack).

**Comment by houz** [comment]
Even if the compiler doesn't optimize the gboolean away (I would be surprised if it didn't) it shouldn't matter. We allocate gigabytes of memory, 4 bytes on the stack should be fine. Especially in code that isn't used recursively.

**Comment by shoffmeister** [comment]
I have been watching @LebedevRI diligently chopping away stack usage ;) (Granted, he converted from stack to heap)

The compiler cannot optimize the gboolean away, because of the call, with C calling convention; IIRC, C calling convention on Linux does not make any guarantees on the state of registers on return, so the gboolean would have to be pushed before invocation. But my memory is ... what was the word again? (Yeah, and it's an academic discussion)

**Comment by LebedevRI** [comment]
@shoffmeister anything up to ~64bytes i'd consider to be really ok :)
More specifically, i agree with the `GTK_RESPONSE_OK` part.
I've been meaning to post that myself, but did't

**Comment by catlee** [comment]
Yeah, it makes sense to make the return value of this function clearer. I'll rework the patch.

**Comment by catlee** [comment]
Huh, I think cancelling this dialog is broken already. If I select an image and press Shift-Ctrl-C, and then click Cancel, and then select another image and press Ctrl-V, the stack from the initial image is copied.

**Comment by houz** [comment]
What is the state of this PR? The changes I can see look suspiciously minimal ...

**Pull request merged**
