### PR TITLE
Make the cairo rendering quality option visible

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
There are issues around like #5947, the cairo rendering quality is at least
one part of the problem. I think we should make the existing hidden option
visible.

### CODE REVIEW

**Comment by parafin** [comment]
I really feel that amount of options in preferences being added to dt is excessive. This is especially the kind of stuff that should work out-of-the-box without any fiddling in settings. Exposing it as combobox isn't a solution IMHO. Not a good one at least.

**Comment by jenshannoschwalm** [comment]
> I really feel that amount of options in preferences being added to dt is excessive. This is especially the kind of stuff that should work out-of-the-box without any fiddling in settings

I absolutely agree here. Personally i think there are already too many options. 

Let's just have this dirty option available while debugging #5947 and revert after fully understanding whether this does really matter.

**Comment by rgo** [comment]
> > I really feel that amount of options in preferences being added to dt is excessive. This is especially the kind of stuff that should work out-of-the-box without any fiddling in settings
> 
> I absolutely agree here. Personally i think there are already too many options.
> 
> Let's just have this dirty option available while debugging #5947 and revert after fully understanding whether this does really matter.

Maybe, it's a good a idea to hide the option in darktablerc without exposing it in preferences.
At the end, it's only for debugging purposes.

**Comment by jenshannoschwalm** [comment]
ok, i drop this. Will have to find another way to discuss results on other peoples machines...

**Pull request closed without merging**
