### PR TITLE
Fix session parameters on Windows Fixes #11850

### PR DESCRIPTION
**Pull request by peterbud**
Two aspects are handled here: 
* Session parameters (`session/base_directory_pattern` and `session/sub_directory_pattern`) can contain `'/'` which would be a problem on Windows path handling. The change below replaces all `'/'` with `'\\'` before using them later
* Then *after* concatenating base directory and sub directory, we need to escape `'\\'` characters, in order not to clash with variable name resolution which comes after that

### CODE REVIEW

**Comment by houz** [comment]
Why do `/` pose problems on Windows?

**Comment by peterbud** [comment]
IIRC we discussed that we should strive to have uniform path delimiters always on each platform to avoid surprises.

**Comment by houz** [comment]
Well, yes, but that string isn't shown to the user, right? Besides the text box in prefs.

**Comment by peterbud** [comment]
Yes, these parameters are shown only in the preferences, and users are free t overwrite whatever they want.

I was thinking further, and I realized that this is not a perfect solution yet. 

Consider this: the default value for `session/base_directory_pattern` is `$(PICTURES_FOLDER)/Darktable`, but user can overwrite to `$(PICTURES_FOLDER)\Darktable` or `$(PICTURES_FOLDER)\$(YEAR)` or `$(PICTURES_FOLDER)\$(YEAR/19/)` or `$(PICTURES_FOLDER)\\($(YEAR/19/)\)` or even `$(PICTURES_FOLDER)\$(YEAR:-2)` or even more crazy stuff.

Now we have to accomplish the following things after reading these parameters:
* Step 1: On Windows we need to replace directory separator '/' characters while preserving variable related '/' characters both in `base_directory_pattern` and in `sub_directory_pattern`
* Step 2: We need to concatenate `base_directory_pattern` with `sub_directory_pattern` using platform specific directory separator character
* Step 3: We need to escape directory separator '\' characters, otherwise variable expansion fails
* Step 4: we need to do the variable expansion

Am I reading it correctly? What would be the best way to achieve Step 1? Cases like `$(PICTURES_FOLDER)\\($(YEAR/19/)\)` looks difficult to solve. Or rather skip step 1, do step 2-4, and do the replacement of '/' to '\' at the very end?

**Comment by houz** [comment]
I'd say we expect users to deal with escaping correctly when entering anything. We'd still need to use `\\` to join the parts. Alternatively we can tell users to use `/` even on Windows when they don't want to deal with escaping. Everything else sounds like too much work, extremely error prone and hard to get right.

**Comment by peterbud** [comment]
So based on the discussions on IRC:
* `session/base_directory_pattern` and `session/sub_directory_pattern` are now concatenated with `\\`
* Therefore subsequent variable expansion works fine
* Added `dt_util_normalize_path()` but as the files are not existing a that time, this function cannot fix the filename if those are containing '/'. I'd remove those line TBH. Please advise.
* In `dt_import_session_path()` added a section for WIN32 platform to replace remaining '/' with '\' before creating the new filmrolls

**Comment by peterbud** [comment]
I have another idea: What if we would move the variable expansion to the `_import_session_path_pattern()`?

We would do separate variable expansion on `session/base_directory_pattern` and `session/sub_directory_pattern` directly in `_import_session_path_pattern()`, then we can safely join them with the `G_DIR_SEPARATOR_S`, and finally before returning we could replace any '/' (which might come from the original session parameter) with `G_DIR_SEPARATOR_S` (which would not change anything on Linux, but would work on Windows.

**Comment by houz** [comment]
We can't replace `/` with `\`, at least not with a simple string replace.

Having the variable replacement on the individual parts sounds good, but we don't have the required values in `_import_session_path_pattern` to expand the variables, but as it's only called in one place and doing only minimal stuff we can probably get away with inlining it into the parent function and doing all the magic there.

**Comment by peterbud** [comment]
> We can't replace `/` with `\`, at least not with a simple string replace.

What is the danger in replacing `/` with `G_DIR_SEPARATOR_S` **after** variable expansion and `g_build_path()`?

**Comment by houz** [comment]
How sure are we that no file system allows `/` in a file name? I'd prefer if we fixed this properly by keeping the path the way it is and stop doing silly things like creating an empty film roll. Can't we just copy the file to the computed destination and the use the regular import functions to open it? That way we should get filmrolls created automatically and paths get normalized.

**Comment by peterbud** [comment]
That would mean a more substantial change in the whole import process and philosophy, right?

**Comment by houz** [comment]
I suppose yes. I'd have to look through the code to get some understanding of what it's doing and why. It's old code, longer with the project than me (I think). And since I never used that feature I never felt the need to look at the code so far.

**Pull request closed without merging**
