### PR TITLE
lua: fix horizontal box child widgets not expanding and filling

### LINKED ISSUE #7208: lua: horizontal box child widgets don't fill the width of the box.
**Describe the bug**
When a lua box widget is created with orientation = "horizontal", the widgets contained in the box don't fill the box, but are just packed as far to the left as possible.  If the box widget is created with orientation = "vertical", then widgets contained in the box expand to fill the width of the box.  The problem is that the default for horizontal boxes is the expand and fill parameters are set to false when packing a box.

**To Reproduce**
1. Start darktable with lua scripts installed and script_manager enabled.
2. Open script_manager and select Configure from the Action combobox
3. Notice the update and reset buttons are packed to left.

**Expected behavior**
The widgets should expand and fill the horizontal space in order to be consistent with the behavior of vertical boxes and other box widgets with horizontal widgets used in darktable. 

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: current git, but this has existed since the box widget was implemented
 - OS: Ubuntu 18.04
 - OpenCL activated: yes

### PR DESCRIPTION
**Pull request by wpferguson**
Set expand and fill child properties to TRUE when orientation  set to horizontal.

Fixes #7208

### CODE REVIEW

**Comment by dterrahe** [comment]
Is it not be simpler/faster from the outset to add widgets to boxes in `container_numindex` using
```
      if(GTK_IS_BOX(container->widget))
        gtk_box_pack_start(GTK_BOX(container->widget), widget->widget, TRUE, TRUE, 0);
      else
        gtk_container_add(GTK_CONTAINER(container->widget),widget->widget);

``` 
This does not usually create problems for vertical boxes either since they don't tend to allocate extra space anyway. Unless you have multiple tabs, but even then `expand` might be the right thing to do.

I've only tried with the example you gave in #7208 and it works there.

**Comment by wpferguson** [comment]
Thanks @dterrahe.  It seems that I was so focused on fixing a box problem that I forgot to think outside the box :).  I agree that is a better fix.

**Comment by wpferguson** [comment]
@dterrahe tried your solution.  It works for the taking care of the horizontal button problem, but if you change to enable/disable scripts in script_manager and select tools as the category you see all the buttons expanded to fill the space that's set by the contrib category since it's the biggest.  Will check and see if I can check the orientation and change gtk_box_pack_start to not expand (or fill, whichever is the problem) vertical layout.

**Comment by dterrahe** [comment]
Oops...

**Comment by wpferguson** [comment]
Ok, I can do the orientation check in the container.  I set expand to false for the vertical and that fixed it.  Thanks again for making me think outside the box.

**Comment by wpferguson** [comment]
Ok, I was wrong about the orientation check during the widget add.  It appears that orientation is set after the box is populated, so it turns out that this is the correct fix.

**Comment by dterrahe** [comment]
Sorry for sending you on a wild goose chase...

**Comment by wpferguson** [comment]
@dterrahe that's ok.  I learned several things, so it was good.

**Comment by TurboGit** [comment]
@wpferguson : this is ready now, right ?

**Review by TurboGit — APPROVED** [review]
Looks good to me.

**Comment by wpferguson** [comment]
@TurboGit this is ready.

**Comment by TurboGit** [comment]
Thanks, merging then.

**Pull request merged**
