### PR TITLE
Collection more filters

### PR DESCRIPTION
**Pull request by edgomez**
Some people expressed on G+ the will to collect images by at least focal length.

This is a legit feature request.

I crafted this PR not to forget about the request. **It can't be merged as it breaks the string freeze**

### CODE REVIEW

**Comment by TurboGit** [comment]
What the status about this? Is there some progress from AlicVB? Should this be closed? Does it still apply to master after all the changes since then?

**Comment by edgomez** [comment]
Well, the branch has been regularly master rebased, i just checked and the added filters do work.

So unless @AlicVB objects, this is good for merge from my POV. Then up to @AlicVB to maintain the feature in the new implementation.

**Comment by AlicVB** [comment]
Well, I was waiting for gtk3 to land to propose my collect rework. I'm currently rebasing the branch, and I think it will be ready today or tomorow.
So, if you don't mind, I would prefer you to wait a little before merging (of course, I'll help you rebasing the PR, if needed) thks

**Comment by AlicVB** [comment]
ok, rebasing finished (was painfull). you can find it here : https://github.com/AlicVB/darktable/tree/collect_rework2
There's still one gui point point to discuss with devs, esp. @houz before doing the PR, thought...

**Comment by boucman** [comment]
so, is it OK to close this PR and open one on your  new branch ?

**Comment by edgomez** [comment]
I'll be rebasing these changes on the new branch

**Pull request closed without merging**
