### PR TITLE
accels : ask before replacing accels

### PR DESCRIPTION
**Pull request by AlicVB**
currently, when you record an already mapped accel, the old one is silently deleted to avoid conflict.
This add a confirmation box in this case to let the user choose.

### CODE REVIEW

**Comment by AlicVB** [comment]
should be fixed now

**Comment by TurboGit** [comment]
Something strange:
- open the pref
- select global options
- in slideshow I have "S" currently
- I try to use S for "change view" (no accel at the moment)

dt says to me that S accel is already registered for "views/darkroom/brush layer".

But when I go into this section I see that there is no accel for "brush larger" !

**Comment by AlicVB** [comment]
oh... that's strange indeed. I can't reproduce on my side...
just to be sure : 
- it says "views/darkroom/brush la**rg**er" (suppose a typo in your previous msg)
- did it say that in english or in translated path (like "vue/chambre noire/augmenter la taille du pinceau" for you) ?
- can you reproduce, or does it appears just 1 time ?
- did you have some other accel registered for "views/darkroom/brush larger"

**Comment by TurboGit** [comment]
> oh... that's strange indeed. I can't reproduce on my side...
> just to be sure :
> 
>     * it says "views/darkroom/brush la**rg**er" (suppose a typo in your previous msg)

Right, a typo.

>     * did it say that in english or in translated path (like "vue/chambre noire/augmenter la taille du pinceau" for you) ?

In English, but all my dt is in french. So that's strange to.
 
>     * can you reproduce, or does it appears just 1 time ?

It reproduces all the time.

>     * did you have some other accel registered for "views/darkroom/brush larger"

```
$ grep "\"s\"" ~/.config/darktable/keyboardrc
; (gtk_accel_path "<Darktable>/global/slideshow view" "s")
(gtk_accel_path "<Darktable>/views/darkroom/brush larger" "s")
```

So it looks like S (default for slideshow) is the one displayed in the accel pref but actually the one set is "brush larger" which is not displayed as being set in the accel pref!

Something fishy...

**Comment by AlicVB** [comment]
> $ grep "\"s\"" ~/.config/darktable/keyboardrc
> ; (gtk_accel_path "<Darktable>/global/slideshow view" "s")
> (gtk_accel_path "<Darktable>/views/darkroom/brush larger" "s")

Those lines means that you have manually set 's' for brush larger, while slideshow has not been touch...
- This should not have happen at all with the current master behavior, as it should have silently reset slideshow accel ! (same behavior with this PR, except the confirmation box)
- The path should have been translated
- The accel for brush larger should have been displayed in the prefs

So yes something is fishy...

There's some other strange things in this areas, thought, like the fact that you can have several same default shortcuts in different views, but if you change one, you reset the other, ...
If you agree, I propose to close this PR for the moment and to prepare a larger one.

**Pull request closed without merging**
