### PR TITLE
Fixing opposed & segmentaiion HLR issues

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
- keeps calculated chroma_correction data for later processing in gui_data. Improves performance for full and previews pixelpipes as the morphological operations and looking for valid data can be avoided.

  I also tested saving calculated data in parameters but that lead to issues while doing presets or copy&paste of history.

- leaves thumbnail creation having to do the full calculation of chroma correction data.

- no mask displaced problems.

Replacing #12702

Some additional comments: I currently don't see a good way to improve thumbnail generation performance. While investigating this i was somewhat surprised that even for small thumbs we take the whole data to be processed until the demosaic stage. That might be something interesting for further investigation.

### CODE REVIEW

**Comment by TurboGit** [comment]
@dterrahe : I suppose you want to test this to check that the issue on your side is fixed. TIA.

**Comment by jenshannoschwalm** [comment]
There a a few thoughts i'd like to discuss here. A short reminder how opposed and segmentation algos work.

1. Basically we can do the fundamental opposed algo "photositewise".
2. to improve issues at borders of blown out image parts we do a "chroma_correction" step. This is time costly (~75%) of the whole opposed algo but leads to much better and most important "stable" output results. For this step we certainly need the whole image area.
3. segmentation is a further postprocessing step refining colors depending on a "best candidate". This definitely requires full image data to be taken into account. If we pre-downscale data like in previews the results might not look the same as for full or export pipe.

This has some consequences.
1. preview pipes can't show results of segmentaion in a good (stable) way but show only result of the opposed stage (2). That's good for me.
2. What to do with thumbnails? Should we use the better, slower and more memory using step2 output or would it be better to use just step1, results would be pretty good for ~75% of the images but the rest failing to look like darkroom.

**Comment by TurboGit** [comment]
> 2\. What to do with thumbnails? Should we use the better, slower and more memory using step2 output or would it be better to use just step1, results would be pretty good for ~75% of the images but the rest failing to look like darkroom.

That's a good question. I would lean toward a better view of the thumbnail as it is really helpful for triaging pictures.

Now how much slower one can accept!

By thumbnails you also speak about the culling view? Here definitely having a better preview is important. Maybe we need to have some kind of threshold for the best vs fast thumbnail preview? For very small one use the fast version, for a downscale of say 1/4 (or less) use the best preview. Is that something that is possible? Does it makes sense?

**Comment by jenshannoschwalm** [comment]
Yes. Low quality if size is <400 or something like that?

**Comment by jenshannoschwalm** [comment]
Or we take the thumb quality conf entry?

**Comment by AlicVB** [comment]
> Or we take the thumb quality conf entry?

I was about to propose the same ;) iirc, this setting "force" the use of the "full" raw datas, and not the downscale ones... this is your step 3, right ?
One problem may be that currently default value is set to "720p" which may be too high for what we need here...

**Comment by dterrahe** [comment]
> @dterrahe : I suppose you want to test this to check that the issue on your side is fixed. TIA.

I don't think it impacts my issue, except for maybe an overall speedup.

My issue is that _while_ a calculation is ongoing, collapsing a module that _could_ impact the pipe dimensions means the ui has to wait for the calculation to finish completely before it can continue. So in the mean time, it hangs. This PR may shorten the wait time, but it doesn't seem to circumvent the mutex or release it at intermediate stages of the calculation or move the dimensions update to a signal or use a different way to determine the final size without calculating all pixels or something like that.

**Comment by jenshannoschwalm** [comment]
> One problem may be that currently default value is set to "720p" which may be too high for what we need here...

I currently struggle with finding out the dimensions of the final thumbnail while being in the middle of pipeline processing. Ony clue on this?

**Comment by jenshannoschwalm** [comment]
> My issue is that _while_ a calculation is ongoing, collapsing a module that _could_ impact the pipe dimensions means the ui has to wait for the calculation to finish completely before it can continue. So in the mean time, it hangs. This PR may shorten the wait time, but it doesn't seem to circumvent the mutex or release it at intermediate stages of the calculation or move the dimensions update to a signal or use a different way to determine the final size without calculating all pixels or something like that.

Yes the performance problem is in `dt_dev_pixelpipe_get_dimensions()`

Why do we need a mutex here at all? For me the only data that possibly require a protection are access via the gui. Shouldn't a gui lock be enough here? What do i oversee?

**Comment by dterrahe** [comment]
> Why do we need a mutex here at all?

Because we don't want to let the magic black smoke get out? I know too little about this stuff to say anything sensible.

But if you only way to find the final dimensions is by running the pipeline to completion, then shouldn't we update the dimensions once complete (i.e. via the signal sent to flag this)? No reason to wait for this unless we need it _now_, but I get the impression this was added to be able to update info tags, so not _too_ urgent I would think.

Caveat: I may very well be (am, probably) missing something.

**Comment by jenshannoschwalm** [comment]
We don't want black smoke for sure :-)

**Comment by TurboGit** [comment]
> Why do we need a mutex here at all?

My immediate reaction would be that I don't see why it won't be needed. The pixelpipe is run by multiple threads. The routine `dt_dev_pixelpipe_get_dimensions()` may also be called from the GUI thread. So it seems safer with a mutex...

**Comment by jenshannoschwalm** [comment]
> may also be called from the GUI thread

Thats why i thought of a gui lock.

BTW this is ready for merge now. Significant performance gain can be felt...

**Review by TurboGit — APPROVED** [review]
Works for me! Integration tests OK:

```
Test 0094-highlight-segmentation
      Image hlrecovery.arw
      CPU & GPU version differ by 25467 pixels
      CPU vs. GPU report :
      ----------------------------------
      Max dE                   : 2.09759
      Avg dE                   : 0.00350
      Std dE                   : 0.04681
      ----------------------------------
      Pixels below avg + 0 std : 99.39 %
      Pixels below avg + 1 std : 99.39 %
      Pixels below avg + 3 std : 99.39 %
      Pixels below avg + 6 std : 99.40 %
      Pixels below avg + 9 std : 99.46 %
      ----------------------------------
      Pixels above tolerance   : 0.00 %
 
      Expected CPU vs. current CPU report :
      ----------------------------------
      Max dE                   : 0.00000
      Avg dE                   : 0.00000
      Std dE                   : 0.00000
      ----------------------------------
      Pixels below avg + 0 std : 100.00 %
      Pixels below avg + 1 std : 100.00 %
      Pixels below avg + 3 std : 100.00 %
      Pixels below avg + 6 std : 100.00 %
      Pixels below avg + 9 std : 100.00 %
      ----------------------------------
      Pixels above tolerance   : 0.00 %
 
  OK

Test 0095-highlight-opposed
      Image hlrecovery.arw
      CPU & GPU version differ by 25262 pixels
      CPU vs. GPU report :
      ----------------------------------
      Max dE                   : 2.09759
      Avg dE                   : 0.00353
      Std dE                   : 0.04733
      ----------------------------------
      Pixels below avg + 0 std : 99.40 %
      Pixels below avg + 1 std : 99.40 %
      Pixels below avg + 3 std : 99.40 %
      Pixels below avg + 6 std : 99.40 %
      Pixels below avg + 9 std : 99.46 %
      ----------------------------------
      Pixels above tolerance   : 0.00 %
 
      Expected CPU vs. current CPU report :
      ----------------------------------
      Max dE                   : 0.00000
      Avg dE                   : 0.00000
      Std dE                   : 0.00000
      ----------------------------------
      Pixels below avg + 0 std : 100.00 %
      Pixels below avg + 1 std : 100.00 %
      Pixels below avg + 3 std : 100.00 %
      Pixels below avg + 6 std : 100.00 %
      Pixels below avg + 9 std : 100.00 %
      ----------------------------------
      Pixels above tolerance   : 0.00 %
 
  OK

Total test 2
Errors     0
see test-20221105-202158.log
```

**Pull request merged**
