### PR TITLE
Fix libheif build on mac osx

### PR DESCRIPTION
**Pull request by cytrinox**
Hopefully fixes osx issues on https://github.com/darktable-org/darktable/pull/8800#issuecomment-945015429

### CODE REVIEW

**Comment by cytrinox** [comment]
@MStraeten Can you verify if this works for you?

**Comment by TurboGit** [comment]
@cytrinox : All tests have passed (so all builds on MacOS) so I suppose this is Ok and fixes the issue.

**Comment by TurboGit** [comment]
> Not sure, the last time I checked the build systems are too old and don't have libheif available, so never compiles the code.

You may well be right ! Let's wait for somebody to test with proper libheif installed.

**Comment by MStraeten** [comment]
next issue: 
```
[ 20%] Building C object bin/CMakeFiles/lib_darktable.dir/common/imageio_heif.c.o
/Users/martinstraeten/src/darktable/src/common/imageio_heif.c:211:6: fatal error: variable 'profile_info_nclx' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
  if(!ctx)
     ^~~~
/Users/martinstraeten/src/darktable/src/common/imageio_heif.c:312:6: note: uninitialized use occurs here
  if(profile_info_nclx)
     ^~~~~~~~~~~~~~~~~
/Users/martinstraeten/src/darktable/src/common/imageio_heif.c:211:3: note: remove the 'if' if its condition is always false
  if(!ctx)
  ^~~~~~~~
/Users/martinstraeten/src/darktable/src/common/imageio_heif.c:219:3: note: variable 'profile_info_nclx' is declared here
  struct heif_color_profile_nclx *profile_info_nclx = NULL;
  ^
1 error generated.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/common/imageio_heif.c.o] Error 1
make[1]: *** [bin/CMakeFiles/lib_darktable.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by cytrinox** [comment]
Well, all these messages make sense, wonder why it is not reported by the Linux pipelines. Combination of compiler+version+error-defaults...
I've fixed the other issue, please try again.

**Comment by cytrinox** [comment]
This one seems osx specific. No idea how to fix this (and no osx available for testing).

**Comment by MStraeten** [comment]
i think @parafin needs have a look on this ...

**Comment by parafin** [comment]
Take a look at OpenEXR cmake code a little bit above heif one and notice how it uses OpenEXR_LIBRARIES. Do the same for libheif (libheif_LIBRARIES).

**Comment by parafin** [comment]
Merged as part of #10311

**Pull request closed without merging**
