### PR TITLE
iop_order: new version that ensures all orders have room for insertion.

### PR DESCRIPTION
**Pull request by TurboGit**
What about this to relax the iop-order list ?

### CODE REVIEW

**Comment by parafin** [comment]
What does iop_order look like for fresh image? Because here I see only conversion from previous version.

**Comment by TurboGit** [comment]
I'll close, it looks like this "simple" idea just does not fly.... Sorry for the noise.

**Comment by TurboGit** [comment]
In fact I did not test correctly. This new version helps a lot:

With previous version (v3):
```
0|rawprepare|1.0
1|temperature|3.0
2|highlights|4.0
3|demosaic|7.50003051757812
4|colorin|37.5
5|colorout|63.5
6|gamma|71.0
7|flip|8.0078125
8|basecurve|38.9999389648437
9|exposure|8.25
10|toneequal|21.5
11|clipping|8.015625
12|clipping|8.015625
13|invert|2.0
14|ashift|8.00390625
15|lens|8.0009765625
16|sharpen|38.96875
17|hazeremoval|8.001953125
18|cacorrect|5.0
```

With this new version (v4 new edit):
```
iop order for 332:
0|rawprepare|1.0
1|temperature|3.0
2|highlights|4.0
3|demosaic|8.0
4|colorin|29.0
5|colorout|69.0
6|gamma|77.0
7|flip|16.0
8|basecurve|45.0
9|exposure|21.0
10|toneequal|24.0
11|shadhi|51.0
12|colorreconstruct|68.0
13|clipping|17.0
14|clipping|17.0
15|basecurve|45.0
16|invert|2.0
17|spots|19.0
18|defringe|31.0
19|sharpen|35.0
20|lens|13.0
21|hazeremoval|14.0
22|ashift|15.0
```
So as you see, when only activating modules you get all iop_order evenly spaced with a distance of 1. This leaves room for lot of insertions and multi-instance between any modules. 

This is not perfect but will let me more confident that we won't break edits on v3.

**Comment by TurboGit** [comment]
Fact is that we won't re-implement the pipe order algorithm for v3.0. This should help avoiding most if not all issues.

**Comment by aurelienpierre** [comment]
Why not just rewrite statically the pipe order as a flat list, like the legacy one (as of 2.6) was defined ? I think we are trying to avoid the drawbacks of the priority computations by over-engineering it.

**Comment by TurboGit** [comment]
Because every time you'll add a new module you'll have to list the 70 or more modules again and again. Here you'll just have to do:

```
  else if(old_version == <N>)
  {
    _ioppr_move_iop_after(_iop_order_list, "new_module", "some_module", dont_move);
    _rewrite_order(*_iop_order_list);
    new_version = <N+1>;
  }
```
A trade-off !

**Comment by TurboGit** [comment]
Let's reopen.

**Comment by aurelienpierre** [comment]
> Because every time you'll add a new module you'll have to list the 70 or more modules again and again. Here you'll just have to do:

Sure, but it's not what I mean. I mean let's flatten the v3, since it's such a big rewrite, to make sure at least it starts clean, then start building again on top of it with dynamic insertions when new modules are added.

**Comment by jenshannoschwalm** [comment]
> Fact is that we won't re-implement the pipe order algorithm for v3.0. This should help avoiding most if not all issues.

Agreed. 

Maybe also checks for delta iop_order beeing less than used precision resulting in a warning box ?

**Comment by TurboGit** [comment]
> Sure, but it's not what I mean. I mean let's flatten the v3

What do you mean by flatten? I fear that we can't change v3 now as it will break the current edits using it.

**Comment by aurelienpierre** [comment]
> What do you mean by flatten? I fear that we can't change v3 now as it will break the current edits using it.

Write it as a simple static list of iop names with no dynamic insertions, as in `static GList *_ioppr_get_iop_order_v1()`

**Comment by TurboGit** [comment]
I see, let's do that indeed. Then v3 will be readable as a first clean step.

**Comment by jenshannoschwalm** [comment]
Any problems with current edits this way?

**Comment by TurboGit** [comment]
Current edits will have the issue but this will only affect current users of the dev version which is far less that the user code base on 2.6.2 who will be migrating.

**Comment by jenshannoschwalm** [comment]
I thought -- we need a warning about this isuue then or open an Issue describing the modifications and what to do to be in a clean state for an Image. Otherwise we will see many issues popping up :-)

**Comment by TurboGit** [comment]
> I thought -- we need a warning about this isuue then or open an Issue describing the modifications and what to do to be in a clean state for an Image.

Well, I'm not sure about that. People using the dev versions are prepared for this and this will be very rare issue (need many reordering and/or some multi-instances). So the probability is low!

And as I said people migrating from 2.6.2 will be immuned to this issue with my patch on this PR.

**Comment by jenshannoschwalm** [comment]
There is one thing i am suspicious about.

The data in `const dt_iop_order_entry_t iop_v3[]` -- i guess you took that from some log.

I don't understand the full code path while upgrading from v3->v4, do you have to compare those values with data from the pre-existing database?

If so, there might be subtle differences / rounding errors as data from the old database/xmp files. Is this properly checked?

**Comment by TurboGit** [comment]
> The data in `const dt_iop_order_entry_t iop_v3[]` -- i guess you took that from some log.

Yes.

> I don't understand the full code path while upgrading from v3->v4, do you have to compare those values with data from the pre-existing database?

No. The new values are creating a new iop_version. The current edits on v3 will use the v3 ordering and only the new edits will be using v4.

**Comment by TurboGit** [comment]
Ok, wrong, I'm wrong! The iop-order MUST BE CONSTANT from one version to another. The comments seems misleading or there is really something I don't understand.

@edgardoh : can you shed some light please? this is a quite critical issue for the next release. thanks.

**Comment by jenshannoschwalm** [comment]
WHY do they have to be constant? I thought in earlier versions we had a defined pipeline order.

Has this order really changed?
1. If not, can't we read the used iop_orders in history and sort them in to current default ranges on_the_fly?
2. If yes, can't we define a simple matrix telling us in which order the modules must be included?

**Comment by TurboGit** [comment]
Good question! I don't have the clue at the moment but iop-order must be constant from one version to another it seems and we can only insert new module in successive version. Just try the first commit on this patch set and you'll see that it breaks current edit by displaying errors about gamma not being the last in the pipe for example. Strange as the first commit only a version 4 that I thought would not be used, but it is.... Which somehow makes sense since if there is a new module in v4 it must be known and positioned in the pipe.

And so, my v4 which is just re-aranging the iop-order values to have a distance of one is breaking current edit (gamma was 71 on v3) and finalscale module is set to 71 after the call to _rewrite_order().

So my conclusion is that v3 edit on the db must be kept AS-IS and not changed in any way. Maybe there is a missing call somewhere when reading an edit? Don't know...

I've asked @edgardoh to help.

**Comment by TurboGit** [comment]
I may have a new version working see #3053.

Closing this one.

**Pull request closed without merging**
