### PR TITLE
[imageio] implement export to email on macOS

### LINKED ISSUE #15402: [macOS] [imageio] Emailing exported images does not work on macOS
Same reason as in #15363: The code is not implemented for macOS.

Implementation is quite trivial though. 
I will provide a PR as soon as PR #15377 is merged.

### PR DESCRIPTION
**Pull request by zisoft**
fixes #15402 

My proposal for a release notes entry (if needed):
Added missing functionality for export to email on Windows and macOS.

### CODE REVIEW

**Comment by zisoft** [comment]
@TurboGit: argh - I accidentally merged

**Comment by TurboGit** [comment]
Nothing we can do at this point :) Hopefully this CI would have been fully green. I'll check right away on my computer.

**Comment by TurboGit** [comment]
Ok, compiling fine here.

**Comment by zisoft** [comment]
ok, thanks and sorry!

**Pull request merged**
