### PR TITLE
po/fix translation

### PR DESCRIPTION
**Pull request by TurboGit**

### CODE REVIEW

**Comment by BathoryPeter** [comment]
One more untranslated string in:
https://github.com/darktable-org/darktable/blob/master/src/iop/colorreconstruction.c#L1288

**Comment by TurboGit** [comment]
> One more untranslated string in:
> https://github.com/darktable-org/darktable/blob/master/src/iop/colorreconstruction.c#L1288

I don't think so, the parameters to dt_bauhaus_combobox_from_params() should not be translated.

**Comment by BathoryPeter** [comment]
Maybe I found a wrong code line, but "precedence" in color reconstruction modul is not translatable.

**Comment by TurboGit** [comment]
> Maybe I found a wrong code line, but "precedence" in color reconstruction modul is not translatable.

I see, this is the only occurrences of this string so we need to record it for translation with `N_("...")`. I'll fix that, thanks for catching!

**Comment by BathoryPeter** [comment]
Thanks!

I have one more problem, namely the ambiguity of the word "color". In the new dt version you have introduced new terms: color and monochrome (photography). In this context, color would have different translation in Hungarian, something similar to "colored". Can you please add gettext context for these "color" occurrences?

**Comment by TurboGit** [comment]
Manually merged and queued for 3.4.1.

**Pull request closed without merging**
