### PR TITLE
French version of filmic part on 2.6 manual and minor corrections on original part

### PR DESCRIPTION
**Pull request by Nilvus**
Hi there,

Here it is the final version of the filmic part of the user manual in French. I also find minor corrections on filmic.xml original part that I submit.

Of course, don't hesitate to read again and propose corrections before submitting. And please don't submit without review of the original author.

### CODE REVIEW

**Comment by TurboGit** [comment]
Looks good thanks.

**Comment by Nilvus** [comment]
I see that you put the 2.8 milestone. As it is about the filmic 2.6 version and not the master one, why not put this on 2.6.1 milestone ? The usermanual is always on 2.4 version on darktable.org. 2.6.1 could be the good version to submit the 2.6 updating version of the manual, both in english and french version (other languages if ready to go).

**Comment by TurboGit** [comment]
Indeed, let's plan that for 2.6.1.

**Comment by TurboGit** [comment]
Now merged in 2.6.

**Comment by Nilvus** [comment]
Great !

**Pull request merged**
