### PR TITLE
make sure copy_history module buttons get updated

### LINKED ISSUE #5188: "paste" and "paste all" remain grayed out, not active
openSUSE Tumbleweed 20200520
NVIDIA GF106 [GeForce GTS 450], 390.132
darktable-3.1.0~git1749.593f29a92-3096.1.x86_64
OpenCL on 
i7 12-core 36GB

after copying any or all of the history stack, "paste" and "paste all" do not indicate active state, remain light gray but mouse clicking on either performs expect action as do the hot keys

### PR DESCRIPTION
**Pull request by johnny-bit**
if history gets copied outside of copy_history module the module wouldn't know.

thanks to this change, module has greater chance of knowing.

fixes #5188

### CODE REVIEW

**Comment by TurboGit** [comment]
> if history gets copied outside of copy_history module the module wouldn't know.

You mean copied how ? With a key accel ?

**Comment by johnny-bit** [comment]
Exactly. With alic's code you can copy from every where tumbtable is (ego
filmstrip)

wt., 2 cze 2020, 19:46 użytkownik Pascal Obry <notifications@github.com>
napisał:

**Comment by TurboGit** [comment]
> Exactly. With alic's code you can copy from every where tumbtable is (ego filmstrip)

Ok, but updating by catching a signal when over a picture is not clean. You probably achieve what you want with dt_control_queue_redraw();.

**Comment by johnny-bit** [comment]
hmmm...

I tried with:
- `DT_SIGNAL_CONTROL_REDRAW_ALL` - no luck.
- `DT_SIGNAL_CONTROL_REDRAW_CENTER` - no luck
- `DT_SIGNAL_SELECTION_CHANGED` - good result, status changes when another image is clicked!

would this be clear enough? I could also add check to see if current != pasted from in case single image is selected, so user can't even try to paste on image copied from :) (it wouldn't work anyway)

**Comment by TurboGit** [comment]
Are you sure that dt_control_queue_redraw();. does not call gui_post_export() ? I think that the metadata module does update the GUI using this hook.

**Comment by johnny-bit** [comment]
metadata module uses `DT_SIGNAL_MOUSE_OVER_IMAGE_CHANGE` (i know, I copied code from there ;)) This selection change signal is imo a bit better. metadata needs mouse over image though.

**Comment by TurboGit** [comment]
> metadata module uses `DT_SIGNAL_MOUSE_OVER_IMAGE_CHANGE`

Because it needs to change the content of the entries each time a new image is under the mouse cursor. But here you just need to refresh the module button (status) on some action. And I suppose using gui_post_expose() (you need to add it as not defined in the copy_history lib at the moment) would work in your case.

**Comment by johnny-bit** [comment]
Tested and works. Interestingly `gui_post_expose` is called with same frequency as `DT_SIGNAL_MOUSE_OVER_IMAGE_CHANGE`. That would mean selection change would fire less frequently. additionally I could use `dt_view_get_images_to_act_on` with updates to make sure paste/paste parts are only enabled in case it makes sense to call them (have paste & selected image != source)

What do you think?

**Comment by TurboGit** [comment]
Works for me as-is.

> What do you think?

This improvement would be welcome indeed. No need to paste over the source image.

**Comment by johnny-bit** [comment]
OK, I'll work on it and push once it's working nicely :)

**Comment by TurboGit** [comment]
Testing more it seems that this slow down the thumbs display. Starting dt the thumbs are slow to be displayed and each time you move up or down in lt it is slow to refresh.

**Comment by TurboGit** [comment]
Hum... Maybe not due to this patch...

**Comment by johnny-bit** [comment]
TBH I think using selection changed signal would be better for it, since it's called way less often and history-related things only work on selected items. This way it couldn't mess with slowing down thumbnails ;)

So what do you think? Leave as-is (do updates on `gui_post_expose`) or rather go with `DT_SIGNAL_SELECTION_CHANGED` since it'll be called less often yet more predictable?

I'll obviously update code to only enable/disable buttons to make them work only in meaningful situations.

**Comment by TurboGit** [comment]
> So what do you think? Leave as-is (do updates on `gui_post_expose`) or rather go with `DT_SIGNAL_SELECTION_CHANGED` since it'll be called less often yet more predictable?

I see, let's try the signal `DT_SIGNAL_SELECTION_CHANGED` as it would lead to less update.

**Comment by TurboGit** [comment]
Looks better and better. Yet a minor issue, you can copy and fly over with the mouse to paste on any given image without selecting it. Do you think this case can be covered ? We need to enable paste when not over the image where copy happened.

**Comment by johnny-bit** [comment]
The only clear way to do that (IMO) then is to use `DT_SIGNAL_MOUSE_OVER_IMAGE_CHANGE` :)
But since `_update` does a bit of soul searchin with checking active image etc, why not add nice little timeout, so that it ignores you when you fly over but updates once you hover over image?

I'll try it and see if I like it.

**Comment by TurboGit** [comment]
> But since `_update` does a bit of soul searchin with checking active image etc, why not add nice little timeout, so that it ignores you when you fly over but updates once you hover over image?

Very little one I suppose it would work.

**Comment by johnny-bit** [comment]
wow, now this feels nice :) It really gives nice visual indication of what's currently possible in copy_history module :)

timeout is nicely clamped and is based of average delay in develop mode, so probably should be fine :) max delay is 0.250s so still neglible and start delay is 0.125 so "long enough to give breathing time and short enough not to be noticeable". If someone has beefy rig and average delay gets low, it's clamped at 0.01s, so enough of a delay imo.

What do you think?

**Comment by TurboGit** [comment]
That's perfect this way! It feels like darktable is alive :) Very nice. I'd like @Nilvus feedback on this as it is really a somewhat deep GUI change.

BTW, I'm sure something identical can be done for the module "selected images" and "export selected". If you have some spare cycles :)

**Comment by johnny-bit** [comment]
Huh, I started working on styles one, but no problem in doing rest 😅

czw., 4 cze 2020, 23:06 użytkownik Pascal Obry <notifications@github.com>
napisał:

**Comment by Nilvus** [comment]
Oh yes, really nice effect. That's also opens new possibilities when copy/paste on a lot of images. Thanks, I like that.

So indeed, implement that on other parts cited would be good.

**Comment by johnny-bit** [comment]
I need to a small code correction to match the better way done in #5323 and it'll be ready to roll

**Comment by johnny-bit** [comment]
This is now ready for review!

**Comment by TurboGit** [comment]
All good now. Thanks!

**Pull request merged**
