### PR TITLE
Watermark with scale-to-height option

### LINKED ISSUE #12813: Absolute font text size for Watermark module
I think it would be useful to have an absolute sizing option for fonts in watermark's module text. By now, it can be scaled in relation to the image size, but this makes it unhandy to repeat a text watermark format in different pictures with different text on it.

i.e. if you edit photos of different authors, and you need to watermark their names in the same fashion for each of them, you could apply a text watermark and just write down the photographers name, but, at the same scale value, a shorter name like would look bigger than a longer name, having thus to resize it each time.

If there was an abolute font sizing, you could just choose a font size and position, save the values as a preset, and then just changing the text input.

### PR DESCRIPTION
**Pull request by m-p-y**
This PR addresses the issue "Absolute font text size for Watermark module" (closes #12813), where the goal is to have the same font size regardless of the text content.

Therefor I implemented four additional option to the "scale on" option of the watermark module, which are:
- marker (width) : border (large)
- marker (width) : border (small)
- marker (height) : border (large)
- marker (height) : border (small)

With those the watermark's width or height can be scaled to the image's larger or smaller border.
Especially the latter two came in handy for scaling the font height, as discussed by @parafin in the original issue.

Although I rewrote the code, the current options "image", "larger border" and "smaller border" are still in their old positions, so I think this extension will not break any old edits and therefore there's no need for incrementing the module version.

However, one issue remains with this solution. If you have two texts with different heights because of different letters like p and b (called descender & ascender), the font rendering will be different, because it is scaled to the text's bounding box. One hacky solution (also used this in LaTeX) is to include two transparent letters, one with a high ascender ($) and one with a low descender (p), as proposed in the text-fixedsize.svg watermark template.

In this image the new "scale on" options are shown as well as a comparison of "simple-text.svg" with "text-fixedsize.svg":

demo_annot

### CODE REVIEW

**Comment by TurboGit** [comment]
> Therefor I implemented four additional option to the "scale on" option of the watermark module, which are:

This is too much for a normal human :) Please add a tooltip description for the now 7 scaling options. What is important to described is the intended used (like keep font size uniform across different picture size). TIA.

**Comment by TurboGit** [comment]
BTW, the tooltip description could be the base of the release notes that is also needed.

**Comment by m-p-y** [comment]
I'll take care of the tooltip and release notes. To be honest I just forget about those, sorry.

And I totally agree to your remark, the options are really crowded now. I wanted to be as versatile as possible. However, for the issue with the constant font height, one single new option should be enough, maybe called "scale to height".

Are there some opinions, which solution would be preferred?
- just one new option "scale to height" (to keep it simple)
- four new options as mentioned above (to also satisfy some special cases)

**Comment by TurboGit** [comment]
> Are there some opinions, which solution would be preferred?

If I'm not mistaken this new option is to be able to keep font overall size constant and independent of the image size. So I would be more in favor of:

"constant font size".

Based on that the other options can be removed as all are just a different scaling which can be controlled in the module itself.

How does that sounds to you?

**Comment by parafin** [comment]
there is no relation to font size, it’s all just relative scalings

**Comment by TurboGit** [comment]
> there is no relation to font size, it’s all just relative scalings

Yes, but to quote the PR first line:

`This PR addresses the issue "Absolute font text size for Watermark module" `

The goal for end-user was really for font but I understand that it is actually a scaling issue since we are talking about SVG.

**Comment by parafin** [comment]
You’ll just confuse everyone about how it actually works IMHO.

**Comment by TurboGit** [comment]
> You’ll just confuse everyone about how it actually works IMHO.

Maybe, what name would you propose?

**Comment by parafin** [comment]
If I understand correctly:
* “marker (width) : border (large)” is the same as existing “larger border”
* “marker (width) : border (small)” is the same as existing “smaller border”
* “marker (height) : border (large)” - this is new
* “marker (height) : border (small)” - this is new

Maybe more logical would not be to extend this list, but instead to add another combobox regarding if scale is set relative to marker width (default and used for legacy params) or height. IMHO it would be simpler, more to the point, and easier to understand.

Old combobox could be named smth like “scale image reference” and new one “scale marker reference”. While at it “image” option can be changed to “width”. Then of course it becomes obvious that height is missing, and we’re back to my original proposal to have all 8 options.

**Comment by m-p-y** [comment]
> Yes, but to quote the PR first line:
> `This PR addresses the issue "Absolute font text size for Watermark module" `
> The goal for end-user was really for font but I understand that it is actually a scaling issue since we are talking about SVG.
I didn't want to claim that I have a solution for the "absolute font size", but just implemented the scaling of the SVG's height as proposed by parafin in this issue.

> If I understand correctly:
> “marker (width) : border (large)” is the same as existing “larger border”
> “marker (width) : border (small)” is the same as existing “smaller border”
Not exactly, although in some cases the behavior is identical. "Larger border" scales the larger border of the SVG to the larger border of the image. So, if the SVG is in portrait orientation and the image is landscape, this would scale the SVG's height to the image's width.
Screenshot_20230321_190710
7d93c9.png)
It will sure be some special cases where this will be useful. But, why not?

My summery would be, that the current options include more logic, to do it "just right", but the new proposed options are more systematic and give the user more control. That's why I really like the suggestion to split it into two options:
> Old combobox could be named smth like “scale image reference” and new one “scale marker reference”. 

That would make these options, both for **scale image reference** and **scale marker reference**
- width
- height
- larger border
- smaller border

I think, we need larger and smaller border, to keep compatible to the current module.

If I'm not wrong, that would mean that the module version must be increased and an extended `legacy_params` function to map the old option to the correct new ones. (I'll have to think a little bit, to what image will map)?

**Comment by parafin** [comment]
> > If I understand correctly:
> > “marker (width) : border (large)” is the same as existing “larger border”
> > “marker (width) : border (small)” is the same as existing “smaller border”
> 
> Not exactly, although in some cases the behavior is identical. "Larger border" scales the larger border of the SVG to the larger border of the image. So, if the SVG is in portrait orientation and the image is landscape, this would scale the SVG's height to the image's width.

OK, didn’t know that, then indeed we have to do 4x4 options. I think it just highlights, that current situation of available options is, let’s say, strange. No idea what was the logic behind providing these particular 3 options…

**Comment by m-p-y** [comment]
After some further thinking and while implementing the discussed things, I came up with some other thoughts. I try to structure it in four topics:

1) **existing options**

I assume a lot of people like the "image", larger border" and "smaller border" options. So after reconsidering, I'd say, they should stay as-is, if possible.

2) **larger / smaller border options**

When the existing three options are kept, I think separate entries for larger/smaller borders can be omitted, definitively for the marker. The use cases should be very limited and the marker SVG is not changed from portrait to landscape mode when copying the edit to another image. If you choose a different marker you'll probably be prepared to reposition the watermark anyhow.

3) **use multiple comboboxes**

In order to be tidy, divide the options into multiple comboboxes. I played with two alternatives, because after implementing option a) I was not completely satisfied, looks still a bit messy.

  a) Two comboboxes:

```
scale marker to		image
			larger border
			smaller border
			image width
			image height
```
and only visible in "image width" or "image height" mode:
```
scale marker reference	marker width
			marker height
```
b) Three comboboxes, the least deviation to accustomed users:
```
scale to		image
			larger border
			smaller border
			advanced			<- only one additional option compared to today
```		
and the following lists are only visible in "advanced" mode:
```		
scale marker to		image width
			image height
			image larger border
			image smaller border

scale marker reference	marker width
			marker height
			marker larger border     <- I'd sugest to omit these
			marker smaller border    <- two options, as reasoned under point 2.
```

My favorite is option b) with up to three comboboxes. The user may need two clicks more, but it's systematic,  flexible but also consistent to today's options.

4) **fixed scaling**

When I tried different things, I realized that also a "fixed" scaling would be possible, i.e. a SVG watermark would change it's size only with the scale slider but not if the image size changes. Might be handy to transfer some ruler from a (e.g. microscopic) reference picture to another.

That option would also be suitable to keep the text size constant, maybe this is as close to "absolute font size" as we get?!

However, one big caveat is, that the preview images are messed up, see the screenshot below. I unfortunately don't know if there are some tricks from preventing this. Maybe not, as also the "grain" module shows similar behavior.

I this a worthy addition? Would add another entry "fixed" to the first combobox I suppose...

**Comment by TurboGit** [comment]
In b) - first section we have:

```
scale to		image
			larger border
			smaller border
			advanced			<- only one additional option compared to today
```

Here the legacy `larger border` & `smaller border` are image based. So that's really `image larger border` & `image smaller border`. Then my question what are the same named option in the next block:

```
scale marker to		image width
			image height
			image larger border
			image smaller border
```

To me all this is becoming a bit too complex... I'm not sure how many people will be able to say I want to do that and immediately see that option o1 in first combo, o2 in second one and o3 in third must be used to achieve the goal.

So even if all those options are technically correct I would probably prefer to have in the combo only some sane options described with a user oriented text.   That being said, you indeed have an advanced option that hide the complexity in the default GUI which is good. So maybe that's ok... I have no strong opinion on this just trying to ensure we have explored all options.

The current single combobox has 3 options:

- image : scale the marker using the overall image size
- larger border : scale the marker using the image larger border
- smaller border : scale the marker using the image smaller border

Your initial point was to have a new option to get "marker/font fixed size accros picture". Can't we add this visible in the first combo and then add the advanced for more exotic scaling? Or maybe what I'm saying is wrong and I'm missing the point :)

**Comment by m-p-y** [comment]
The interface shouldn't get too complex, I fully agree and that's why I preferred the variant with the "advanced" entry. But to put an easy option in the first menu for constant text height seems a good idea, too. 

> Can't we add this visible in the first combo and then add the advanced for more exotic scaling? 

Sounds good, so I'll make the first combobox like so

```
scale to		image
			larger border
			smaller border
			fixed size
			advanced
```


> Then my question what are the same named option in the next block:

I duplicated the "image larger border" / "image smaller border" in the advanced options, because I had the following scenario in mind: Say you have two image, one in landscape and one in portrait orientation and want the watermark referenced to the marker height (i.e. you need the advanced options). Then, if you copy the watermark to different images, the "image height" and "image width" reference will have the opposite meaning, which seems inconvenient. But maybe I'm overthinking this point. 

Apart from that the reasoning for the two additional advanced options is a follows, which I probably should have explained in more detail in the first place:

_scale marker to_: defines to which size the watermark should be scaled

_scale marker reference_: defines which measure of the watermark is used as the metric

So whatever combination is selected, the scaling is computed in such a way that these both measures will have the identical size. I hope this is rather intuitive when using, because there are no hidden logics and the result is straight forward.

As you said you don't have a strong opinion and think that hiding the complexity in the advanced menus sound reasonable, I'll try to make everything ready the next days, incl. code, tooltips, documentation, and release notes.
Then everybody who is interested can test the extended watermark module and experience how it "feels" in the usage (at least I'm quite fond of "playing" with new options). Then you can decide if it's worth adding this to master. 

I hope this proceeding sounds good to you.

**Comment by parafin** [comment]
What is “fixed size” option? How would it work?

Larger/smaller border is useful for image reference due to mentioned orientation issue. It’s not relevant for watermark, because you know its orientation and can choose width/height explicitly. But if larger/smaller are already used in existing implementation we have to keep it. Maybe we could hide them for new edits.

**Comment by m-p-y** [comment]
> What is “fixed size” option? How would it work?

The SVG watermark changes its size only with the scale slider, but is not affected by relative changes between image size and watermark bounding box. If you have a 100x100px watermark it stays this (absolute) size.

This solves the constant-font-height issue within one picture. One (big?) drawback is, that the preview in the navigation pane and in the film strip is wrong. (At the lighttable it's fine!) Also the "grain" module suffers from this. Do you know if there's a possibility that the module knows, if it's working on the main image preview or the "thumbnails"?



>  But if larger/smaller are already used in existing implementation we have to keep it.

I think so, too.

> Maybe we could hide them for new edits.

Maybe some people like these options, because they got used to them? Or do I misunderstand you and you don't mean that these options should not be offered for fresh edits?

**Comment by parafin** [comment]
> > What is “fixed size” option? How would it work?
> 
> The SVG watermark changes its size only with the scale slider, but is not affected by relative changes between image size and watermark bounding box. If you have a 100x100px watermark it stays this (absolute) size.
> 
> This solves the constant-font-height issue within one picture. One (big?) drawback is, that the preview in the navigation pane and in the film strip is wrong. (At the lighttable it's fine!) Also the "grain" module suffers from this. Do you know if there's a possibility that the module knows, if it's working on the main image preview or the "thumbnails"?
> 
> 

That’s my point - it won’t work, input to the iop can come scaled-down, so size in pixels is a bad idea (and IMHO not useful).

> > But if larger/smaller are already used in existing implementation we have to keep it.
> 
> I think so, too.
> 
> > Maybe we could hide them for new edits.
> 
> Maybe some people like these options, because they got used to them? Or do I misunderstand you and you don't mean that these options should not be offered for fresh edits?

I don’t see how it’s useful. Larger/smaller is exactly either width/height or height/width for any given watermark (well, there are corner cases when text is involved, but I think it’s irrelevant). It’s useful with reference to the image, because it’s common to copy history stacks across pictures. So I don’t think absence of these options will break anyone’s workflow, especially since old presets and styles will still work as before.

**Comment by TurboGit** [comment]
> One (big?) drawback is, that the preview in the navigation pane and in the film strip is wrong. (At the lighttable it's fine!)

You are probably missing a scaling for the preview pipe somewhere.

**Comment by m-p-y** [comment]
Ok, we want
- an easy option for correct text scaling in the first menu
- but don't use a fixed pixel size because of unwanted side-effects

Maybe we can use a single entry "marker height" which will scale the marker's height to the image's height?! I suppose this should cover most cases for a "constant" font height.

For finer control, there is still the "advanced" option.

```
scale to		image
			larger border
			smaller border
			marker height
			advanced
```

> I don’t see how it’s useful. Larger/smaller is exactly either width/height or height/width for any given watermark (well, there are corner cases when text is involved, but I think it’s irrelevant). It’s useful with reference to the image, because it’s common to copy history stacks across pictures. 

This is also what I meant, larger/smaller border only makes sense for "image", not for "marker". 

> You are probably missing a scaling for the preview pipe somewhere.

Alright, so it's my mistake -- I'm glad, that it's not a general limitation. I try to understand the preview pipe better, just out of curiosity, as the "fixed" option seems to be no good idea.

**Review by TurboGit — APPROVED** [review]
Thanks! I have manually merged this with conflict resolution for the release notes.

**Comment by TurboGit** [comment]
> Here is my suggestion for the updated dt manual for which I'll send a PR to dt-docs as soon as this PR is final:

Looks ok to me.

**Comment by m-p-y** [comment]
> I have manually merged this with conflict resolution for the release notes.

Thanks, I didn't knew which way you prefer to receive the release notes. (As commit to RELEASE_NOTES.md or just as a text here in the discussion -- I've found both variants used in previous PR.)

And thanks for fixing my amateurish (compiler) errors :disappointed: -- unfortunately I usually can only react in the evening.

> > Here is my suggestion for the updated dt manual (...)

> Looks ok to me.

PR to dt-docs on its way...

**Pull request merged**
