### PR TITLE
Update preferences manual for performance mode and monochrome previews

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
1. Image and description should reflect the new `performance mode`

2. Add docs about `detect monochrome previews`

### CODE REVIEW

**Review by TurboGit — CHANGES_REQUESTED** [review]
Please ensure the comment in the CSS Window is in English ! 

Should be:

/* Enter CSS theme tweaks here */

Thanks.

**Comment by jenshannoschwalm** [comment]
Aah, i missed that. It's probably a bug as dt preferences interface language is set to english.

**Comment by TurboGit** [comment]
Not a bug really. This gets written the first time dt is started into the user's CSS and after that is is not translated as it is only the content of the file which is displayed.

**Comment by jenshannoschwalm** [comment]
uploaded.

**Review by TurboGit — APPROVED** [review]
Thanks !

**Pull request merged**
