### PR TITLE
Tagging dictionary: remove entry completion

### PR DESCRIPTION
**Pull request by phweyland**
Remove entry completion as the feature is now redundant as commented [here](https://github.com/darktable-org/darktable/pull/10784#issuecomment-1016790668).
Completion on popup entry remains.

In fact, was missing the automatic scrolling to the first matching tag in dictionary while typing in entry, point I've added.

@ChristianBirzer, would you be kind enough to check I haven't broken anything since #10784.
While typing in entry, the scrolling happens but without selection in dictionary. Hitting the Down key the first (already) visible matching tag is selected (highlighted).

### CODE REVIEW

**Review by ChristianBirzer — COMMENTED** [review]
I did a brief comparison between the current master and this PR.

I found one thing that changed: (I'm not sure if that's what you wrote about in your first comment?)

When the tag dictionary is in tree mode and I enter the beginning of a tag that is inside the hierarchy, the master version expands all nodes and shows the full hierarchy at once.
With this PR nothing is expanded during input and on cursor-down only the first item is expanded. The following items have to be expanded with cursor-right.

Master:
grafik

PR:
grafik
After Cursor-down:
grafik

Additionally, but not related to this PR: I could reproduce a crash when the dictionary is in tree view, navigating to a Tag inside the hierarchy (just focussing it, not pressing enter) and then switch the dictionary to list mode...
Segfault in tagging.c: _update_layout, line 2610 in th call to gtk_tree_store_clear. This happens at master too. I'll either add an issue about this or try to find the problem by myself when I find some time the next days....

**Comment by phweyland** [comment]
Thanks for testing!
Without the PR I had a problem when the list long, for example color contains a lot of them. If I enter color, the tte

**Comment by phweyland** [comment]
There was an issue when entry was containing upper case. This should work now.

However I cannot reproduce the crash. 
Could you try to give me more contextual information ? TIA.

**Comment by ChristianBirzer** [comment]
Hi, its me again... 🙄
I'm not sure if I should add this comment to that ticket or create a new one. Did more testing to reproduce the crash and noticed that it has nothing to do with the entry or filter but only with the tree/list view of the dictionary.

A minimal setting to reproduce:
- Start with a fresh database and no tags at all
- Create the following tag hierarchy:
```
1
  2
    3
      4
```
(no category, no private, no synonyms)
grafik
grafik
- switch to tree mode
- expand levels up to 3
grafik
- Switch to list mode
grafik
- crash 
grafik


BTW: The official 3.8.1 does not crash in this situation.

**Comment by phweyland** [comment]
Not yet caught ...
image 
image
and I can see the special characters in synonyms.

BTW, what is your locale ? Mine is here:

```
$ localectl status
   System Locale: LANG=en_US.UTF-8
                  LC_NUMERIC=fr_FR.UTF-8
                  LC_TIME=fr_FR.UTF-8
                  LC_MONETARY=fr_FR.UTF-8
                  LC_PAPER=fr_FR.UTF-8
                  LC_NAME=fr_FR.UTF-8
                  LC_ADDRESS=fr_FR.UTF-8
                  LC_TELEPHONE=fr_FR.UTF-8
                  LC_MEASUREMENT=fr_FR.UTF-8
                  LC_IDENTIFICATION=fr_FR.UTF-8
       VC Keymap: fr
      X11 Layout: fr
       X11 Model: pc105
```

**Comment by phweyland** [comment]
OK, So please ignore the locale question, if that happens with numerical characters.
But I still not get the crash.

> 'm not sure if I should add this comment to that ticket or create a new one.

As it seems harder to reproduce than expected it would be better to open a new issue.
As it may be related to the system itself, please mention the associated info, including gtk version.
Thanks !

**Comment by TurboGit** [comment]
Tested and cannot reproduce the crash either and even when run under gdb there is no memory error detected. So I'll merge this and we will work on the fix if needed in a separate PR. Thanks.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
