### PR TITLE
localcopy : fix icon position in block overlay

### LINKED ISSUE #11247: local copy icon status and culling / full view
**Describe the bug/issue**

The local status icon gets displayed when in culling or full view on the top-left corner of the image area.

**To Reproduce**
1. Go to 'lighttable'
2. Select an image
3. Click on 'copy locally'
4. Click on x for culling - see wrong local copy status icon displayed
5. Click on w for full view - see wrong local copy status icon displayed

**Expected behavior**

I believe the local status icon should be skipped on those views. But to be discussed.

**Screenshots**

Full-view:

Capture d’écran de 2022-03-01 18-56-16

Culling:

Capture d’écran de 2022-03-01 18-56-32

### PR DESCRIPTION
**Pull request by AlicVB**
this fix #11247 
@Nilvus : can you have a look, please, I've simplified the css, as the localcopy part was not used anymore if I've not missed something... Thanks !

### CODE REVIEW

**Review by TurboGit — COMMENTED** [review]
The local copy icon has been design to be on the corner of a thumb. Here on the block overlay it looks strange to me. We may need another icon or put it on the corner of the block maybe?

**Comment by AlicVB** [comment]
agree.
the problem is that if in the top-right corner of the block will need to enlarge image name margin, and the block will be larger, even if there's no local copy...
Maybe we can put it in the top-right corner of the image, like what is done for smaller thumbnails ? but it will be less visible...

Or we can go with another icon... do you have some ideas ?

**Comment by AlicVB** [comment]
Last version put the localcopy indicator on the top right of the image.
That said, I may also propose this icon 
Capture d’écran_2022-03-02_16-06-13
personally, I prefer the icon, as it remind the localcopy indicator used with small thumbs, but is at the same place as other indicators, but I don't really care if we go with the current version either !

**Comment by TurboGit** [comment]
Ok, I also prefer the icon. You've done a really good job with it.

**Comment by AlicVB** [comment]
pushed :)

**Comment by TurboGit** [comment]
@AlicVB  : Just a little GUI adjustment, I'm proposing this:

```
diff --git a/src/dtgtk/paint.c b/src/dtgtk/paint.c
index 54354c977..252f0626d 100755
--- a/src/dtgtk/paint.c
+++ b/src/dtgtk/paint.c
@@ -1671,9 +1671,9 @@ void dtgtk_cairo_paint_local_copy(cairo_t *cr, gint x, gint y, gint w, gint h, g
 
   if(flags & CPF_ACTIVE)
   {
-    cairo_move_to(cr, 0.50, 0);
+    cairo_move_to(cr, 0.40, 0);
     cairo_line_to(cr, 0.85, 0);
-    cairo_line_to(cr, 0.85, 0.35);
+    cairo_line_to(cr, 0.85, 0.45);
     cairo_close_path(cr);
     cairo_fill_preserve(cr);
     cairo_stroke(cr);
```

Which makes the local-copy indicator standing out a bit more:

Before:

Capture d’écran de 2022-03-03 08-11-20

With my change:

Capture d’écran de 2022-03-03 08-10-15

If you're ok can you just integrate this into your PR? I can do that after merging if you prefer.

**Comment by Nilvus** [comment]
I will test tonight but on what you suggest @TurboGit, on your screenshot I find that this stand out to much. So maybe something between @AlicVB proposal and yours would be better (if possible).

**Comment by AlicVB** [comment]
@Nilvus : of course it's possible... Maybe the simplest solution is that you set the value to exactly what you want... See @TurboGit diff in previous msg. And if you need help, just ping me ;)

**Comment by Nilvus** [comment]
I would suggest so a little adjustment. See diff below:

```
diff --git a/src/dtgtk/paint.c b/src/dtgtk/paint.c
index 54354c977..a0efa2d29 100755
--- a/src/dtgtk/paint.c
+++ b/src/dtgtk/paint.c
@@ -1671,9 +1671,9 @@ void dtgtk_cairo_paint_local_copy(cairo_t *cr, gint x, gint y, gint w, gint h, g
 
   if(flags & CPF_ACTIVE)
   {
-    cairo_move_to(cr, 0.50, 0);
+    cairo_move_to(cr, 0.45, 0);
     cairo_line_to(cr, 0.85, 0);
-    cairo_line_to(cr, 0.85, 0.35);
+    cairo_line_to(cr, 0.85, 0.40);
     cairo_close_path(cr);
     cairo_fill_preserve(cr);
     cairo_stroke(cr);
```

And, I would also suggest to add a simple tooltip when moving mouse cursor hover the icon with just: "local copy". That will help users.

Last thing, not completely related to that PR but a little: we don't display local icon copy on other overlays in preview and culling modes, that's not really consistent. But said that, I really think the 2 other overlays need to be redesigned completely (I personally would suggest to even removed them but I can understand that kept them is needed). See what we actually have:

image

**Comment by AlicVB** [comment]
@Nilvus : your diff proposal + the local copy tooltip have been included.
For your remark about the other overlays, Then clearly need some love, but I'm not sure how to do that... That certainly need more thinking and need to be done in a separate PR. In fact the local copy in the only "top" icon shown in this cases... not really consistent... but the absence of the other icons is not good either...

**Comment by Nilvus** [comment]
> > we don't display local icon copy on other overlays in preview and culling modes
> 
> But in this case we have the local-copy on the corner of the thumb so no need for this new icon.

I even didn't notice that on first displays when I done my feedback few minutes ago. Not so visible I think. But as I said the 2 related overlays would need a complete redesign for culling and preview modes. I don't have any ideas by now though.

**Pull request merged**
