### PR TITLE
some new css fixes

### LINKED ISSUE #11976: preferences: inconsistent padding
The padding is not consistent between items in the preference dialog. For example, the modules section of the processing tab shows different spacing between checkboxes and comboboxes.

Screenshot_2022-06-04_16-53-46

### PR DESCRIPTION
**Pull request by Nilvus**
Fix #11976

Also fix some forgotten id name change. Needed to be consistent naming between id and classes.

### CODE REVIEW

**Comment by elstoc** [comment]
Not entirely sure we're there yet (maybe the font size matters here?). I'm looking at the spacing between the labels here - the labels for the comboboxes still seem closer together.

Screenshot_2022-06-04_23-53-56 
Screenshot_2022-06-04_23-54-19

I'm not necessarily advocating this as the fix but I find that the following improves matters slightly:
```
#preferences-box .combo,
#preferences-box entry,
#preferences-box spinbutton,
#preferences-box textview  { margin: 0.1em 0 }
```

Screenshot_2022-06-05_00-09-01

Something else I noticed while testing is that the text alignment between textviews/entries and comboboxes isn't entirely consistent (comboboxes seem to have a slight extra padding before the text)

**Comment by Nilvus** [comment]
> I'm not necessarily advocating this as the fix but I find that the following improves matters slightly (though perhaps it would be better to reduce the margin around the checkboxes - I can't work out how to do this though):

As I said, there's absolutely no margin around checkboxes.

**Comment by Nilvus** [comment]
> Not entirely sure we're there yet (maybe the font size matters here?). I'm looking at the spacing between the labels here - the labels for the comboboxes still seem closer together.
> 
> Screenshot_2022-06-04_23-53-56 Screenshot_2022-06-04_23-54-19

Checkboxes and combobox don't have same use. It's not a problem for me. We have more infos on comboboxes so it's normal. We can't reduce comboboxes and if we increase checkboxes height, they will be too big.

**Comment by Nilvus** [comment]
Last commit should be much better and should fix all issues pointed there by you @elstoc. It also simplify CSS (a good thing!) and make sure all items here have same settings.

**Review by elstoc — APPROVED** [review]
Looks more consistent now, thanks.

**Comment by Nilvus** [comment]
Thanks again @elstoc for your help and "nit-picking". That helps again to have better CSS/UI.

**Comment by Nilvus** [comment]
@elstoc: I finally made a little change since your approval. I think with last commit, that should be even better (I found that previous commit add too much space between combo, especially visible on collapsible section in import module) AND remove too much padding inside textview, entries.

**Comment by elstoc** [comment]
Looks good

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
