### PR TITLE
cacorrect: performance optimization

### PR DESCRIPTION
**Pull request by ralfbrown**
Some optimization I hadn't entirely finished for 4.4 (I think there's still a few percent additional improvement possible).  Making it a PR now because I'm about to enter my busy half-year and probably won't have a chance to do more with it until spring.

Passes integration test 0084, maxDE = 1.25 (from rounding going the other way on 237 pixels compared to reference)
```
Thr	Master	Current
1	2662.51	2410.70	 -9.4%
2	1398.31	1273.36	 -8.9%
4	 767.99	 702.38	 -8.5%
8	 452.60	 405.07	-10.5%
16	 303.99	 268.73	-11.6%
32	 262.92	 224.81	-14.4%
64	 341.99	 301.35	-11.8%
```

### CODE REVIEW

**Comment by TurboGit** [comment]
CI reports:

```
In file included from /home/runner/work/darktable/darktable/build/lib/darktable/plugins/introspection_cacorrect.c:27:
/home/runner/work/darktable/darktable/src/src/iop/cacorrect.c:854:38: fatal error: variable 'caautostrength' must have explicitly specified data sharing attributes
                if(sqrf(bstemp[0]) > caautostrength * blockvar[0][c]
                                     ^~~~~~~~~~~~~~
/home/runner/work/darktable/darktable/src/src/iop/cacorrect.c:379:30: note: explicit data sharing attribute requested here
#pragma omp parallel default(none) \
                             ^
1 error generated.
```

**Comment by TurboGit** [comment]
Another one:

```
In file included from /home/runner/work/darktable/darktable/build/lib/darktable/plugins/introspection_cacorrect.c:27:
/home/runner/work/darktable/darktable/src/src/iop/cacorrect.c:438:7: fatal error: variable 'border' must have explicitly specified data sharing attributes
      for(int top = -border; top < height; top += ts - border2)
      ^~~
/home/runner/work/darktable/darktable/src/src/iop/cacorrect.c:379:30: note: explicit data sharing attribute requested here
#pragma omp parallel default(none) \
                             ^
1 error generated.
```

**Comment by ralfbrown** [comment]
Argh.  Looks like GCC10 doesn't care when the variable is a compile-time constant but newer versions do.  I think I've got all of them now.

**Comment by TurboGit** [comment]
On more :)

```
In file included from /home/runner/work/darktable/darktable/build/lib/darktable/plugins/introspection_cacorrect.c:27:
/home/runner/work/darktable/darktable/src/src/iop/cacorrect.c:568:79: fatal error: variable 'v3' must have explicitly specified data sharing attributes
                                    + fabsf(rgb[1][indx - v1] - rgb[1][indx - v3]));
                                                                              ^~
/home/runner/work/darktable/darktable/src/src/iop/cacorrect.c:379:30: note: explicit data sharing attribute requested here
#pragma omp parallel default(none) \
                             ^
1 error generated.
```

**Comment by ralfbrown** [comment]
Sigh....

**Comment by da-phil** [comment]
Did you also have a look at the recent changes to [this part of the code in the RT repo](https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/CA_correct_RT.cc)?
Seems that there have been many optimizations ever since the code was copied into the DT repo.

**Review by TurboGit — APPROVED** [review]
Indeed 0084 passes. Though 0103-almost-all is failing. It was :

```
      Expected CPU vs. current CPU report :
      ----------------------------------
      Max dE                   : 1.64799
      Avg dE                   : 0.05771
      Std dE                   : 0.16929
      ----------------------------------
      Pixels below avg + 0 std : 88.69 %
      Pixels below avg + 1 std : 89.01 %
      Pixels below avg + 3 std : 97.52 %
      Pixels below avg + 6 std : 99.99 %
      Pixels below avg + 9 std : 100.00 %
      ----------------------------------
      Pixels above tolerance   : 0.00 %
```

And with this PR:

```
      Expected CPU vs. current CPU report :
      ----------------------------------
      Max dE                   : 2.58134
      Avg dE                   : 0.11110
      Std dE                   : 0.22518
      ----------------------------------
      Pixels below avg + 0 std : 78.65 %
      Pixels below avg + 1 std : 81.17 %
      Pixels below avg + 3 std : 98.13 %
      Pixels below avg + 6 std : 100.00 %
      Pixels below avg + 9 std : 100.00 %
      ----------------------------------
      Pixels above tolerance   : 0.00 %
```

This diff was already 1.68, with the change we go to 2.58 (just above the limit). I'll update the expected output for almost all as this cannot be considered as a regression to me.

Thanks!

**Comment by ralfbrown** [comment]
> Did you also have a look at the recent changes to [this part of the code in the RT repo](https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/CA_correct_RT.cc)? Seems that there have been many optimizations ever since the code was copied into the DT repo.

It's on my TODO list, but I don't expect to get to it until Spring.

**Pull request merged**
