### PR TITLE
Continue CSS optimization

### LINKED ISSUE #11404: FR: Make the grid button lines grey instead of red and green
The red and green lines are really hard on my brain as the colours create some strange contrast where the lines intersect. Is there a reasoning why this icon is not grey like all (except the ones where colours are necessary) the others?

### LINKED ISSUE #11577: Increase min size of sliders
**Is your feature request related to a problem? Please describe.**
The slider icon automatically shrinks the more elements are displayed. This goes to a point where the slider becomes very small compared to the mouse cursor - making it very hard to select. 

I found that this has the most impact on the file manager layout and the import module but others might be impacted as well.:

image
image

**Describe the solution you'd like**
Increase the min slider size to something more reasonable.

image

### PR DESCRIPTION
**Pull request by Nilvus**
Started to rewrite new parts of CSS:
- nearly all buttons
- all dialog window
- starting mask part (remains some icons to improve)
- improve a lot (and harmonize) basics widgets part
Screenshot from 2022-04-18 00-07-26
- improve also (a little) duplicate manager
Screenshot from 2022-04-18 00-07-39

And some other minor things improved (spacing...)

To do:
- some masks icons
- menuitems to rewrite
- continue to simplify CSS code!

And fixes #11577
Fixes  #11404 too

### CODE REVIEW

**Comment by Nilvus** [comment]
@wpferguson: I need your help here (should be quick and simple). I am on changing some CSS id to CSS class as it would be a better code. I am actually updating to change all `#section_label` to class, so will be `.section_label`. You could see change on last commit here.

I've seen that on `lua/widget/section_label.c`, line 24, I see:
`.name = "section_label",`
Do this need to be changed or not to set that it's now class name and no more id name? If yes, to which code?

I precise that I don't use Lua.

**Comment by wpferguson** [comment]
@Nilvus all widgets get their name set in the `name_member` function of `src/lua/widget/widget.c` (line 216).  If the widget has a name, then it's set otherwise it's set to NULL.  Does this answer your question?

**Comment by Nilvus** [comment]
> @Nilvus all widgets get their name set in the `name_member` function of `src/lua/widget/widget.c` (line 216). If the widget has a name, then it's set otherwise it's set to NULL. Does this answer your question?

Thanks for your answer. My question was just to know if Lua need to be changed as "section_label" is no more set by "gtk_widget_set_name" but by setting a class in Gtk. And I was not sure how this name in lua file was set. After checking (and finally install lua scripts), I check that no change is need in lua file. This Lua function take the name even if it's set by a class (or a name, so id as before). So all good.

**Comment by Nilvus** [comment]
Last commit improve range new filters tooltip. Thanks to @quovadit suggestion here: https://github.com/darktable-org/darktable/pull/11066#issuecomment-1103155358 (@AxelG-DE: this should help more than actual tooltip)

@AlicVB: when you will be back, your review is of course welcomed as this commit change your work (and other things in this PR).

**Comment by Nilvus** [comment]
Better with a little screenshot:

image

**Comment by Nilvus** [comment]
And now some fine-tuning and simplification on modulegroups manager:

image

**Comment by Nilvus** [comment]
I'm please now to provide some improvements in new filters by @AlicVB (and with more lines removed on that part too). See below:

**collections filters module**
Before:
Capture d’écran du 2022-04-21 13-37-53

After:
Capture d’écran du 2022-04-21 13-36-12

**quick filters on header toolbar**
Before:
Capture d’écran du 2022-04-21 13-37-27

After:
Capture d’écran du 2022-04-21 13-36-32

**range popup when right-clicking on date range widgets**
Before:
Capture d’écran du 2022-04-21 13-38-14

After:
Capture d’écran du 2022-04-21 13-38-47

**Comment by Nilvus** [comment]
I finally set a little more contrast on filters range (in last commit, so after screenshot above have a little less contrast that what this PR propose now).

**Comment by TurboGit** [comment]
Last screenshots are nice, looking forward for this to be ready and land in master. Great work @Nilvus !

**Comment by Nilvus** [comment]
> Last screenshots are nice, looking forward for this to be ready and land in master. Great work @Nilvus !

Remains some work on menuitem (will try to set all same way with bauhaus popup if possible) and improve some things in blending tabs. I can also make another PR for those 2 things and make that one ready to review. As you want.

**Comment by Nilvus** [comment]
Oh, and @elstoc: as I've made a lot of changes again here, your "nit-picking" is welcomed ;-)

**Comment by TurboGit** [comment]
@Nilvus : There is no urgency so let's keep this PR for all the CSS work.

**Comment by Nilvus** [comment]
Last commits end this PR with some icons update (and better overlay popover for spinbutton when disabled).

Here the before/after screenshots for icons:
Capture d’écran du 2022-04-24 21-29-14
Capture d’écran du 2022-04-24 21-27-30

Capture d’écran du 2022-04-24 21-29-27
100-149e6b

Capture d’écran du 2022-04-24 21-54-58
5f-0c3f-4a05-8053-2028b
Capture d’écran du 2022-04-24 20-03-36
6cc5455.png)

**Comment by Nilvus** [comment]
For mask part, it's minor things : better eye icon (same in import module) and fix + icon issue when the + inside the circle was filled when hovering and not visible, like for minus icon.

Main work is new icons in right part of footer in darkroom. darktable UI is about having less distractions as possible, so we want to avoid colors as much as possible. This follow at first this issue from @piratepanda: #11404. And as I change grid lines icon, I so also change raw over exposed. It's the same icon just with greyscale "colors" instead of bayer color. I hope it will be good for most of you. I also make some rounded icons and especially improve focus peaking size. I kept @aurelienpierre idea as much as possible.

Reviews from @elstoc, @AlicVB and @aurelienpierre are welcomed

**Comment by elstoc** [comment]
> better eye icon

Just based on your screenshots I'm not sure about the eye icon changes. IMO the new version looks a bit less eye-like than the old. The ones in the selectable part of the interface look like the ellipse is slightly truncated at the edges; these ones...

Screenshot_2022-04-24_21-25-46

The one at the top is better. Also, if the inside circle is supposed to be the iris it probably _should_ be filled.  The other icon changes in your screenshots look better though - more consistent.

**Comment by Nilvus** [comment]
> Just based on your screenshots I'm not sure about the eye icon changes. IMO the new version looks a bit less eye-like than the old. The ones in the selectable part of the interface look like the ellipse is slightly truncated at the edges; these ones...

It's same icon on all part. I just tested to remove all margin/padding inside treeview, and this doesn't change anything, so probably a Gtk limit here. I understand now why radius was set to 0.45 and not 0.5. I set it to 0.5 to take all width on those screenshots. It would have been better to take all width (with same height) to have a better eye look but seems that we need to decrease height with such limit!

> The one at the top is better. Also, if the inside circle is supposed to be the iris it probably _should_ be filled (Edit: the github eye icon in the above "marked for review" comment looks good, perhaps we should copy that!).

The one at the top is the icon I set. But finally, it's maybe too big now. So I update it with that:

image

I do not push commit for this filled icon, waiting before for feedback.

**Comment by elstoc** [comment]
> I do not push commit for this filled icon, waiting before for feedback

looks better to me

**Comment by elstoc** [comment]
Looks like the outline around the slider marker has gone missing again:

Master:
Screenshot_2022-04-25_08-11-23

This PR:
Screenshot_2022-04-25_08-13-02

**Comment by Nilvus** [comment]
Argh again sliders. Will fix that... and put a comment on code to avoid breaking it again.

About spacing in collections modules (it's the same on tagging module), it's also on master. I didn't succeed to fix it with CSS. So will not be for that PR. Seems to be some Gtk issue for such buttons following some treeview without header bar.

**Comment by Nilvus** [comment]
All things are fixed now, even spacing on collections module (and tagging). Spacing could be applied only on scrolledwindow and not on treeview. Last commit also simplifies other parts I see when fixing issues and harmonize all darktable classes naming. If no other issue is shown, this is ready to be merged.

**Review by TurboGit — APPROVED** [review]
Let's move forward, I have tested many things no issue and I really like what I've seen. The icon revamp is really nice. Thanks a lot!

**Comment by MStraeten** [comment]
commit 27702fbf857d54c73eeffb9593347202c62675ab breaks UI built on osx
lighttable view:
image
darkroom view:
image

**Comment by Nilvus** [comment]
It can't be CSS issue that way. It works great on my side and on changes I made, I don't see why my code would do that. This seems more CSS you had on your side that do not work now with my code. I change names and simplify codes, so if you have set on your side old names ,removed by this commit, that could break CSS and so your UI.

Or is it possible that comment line 1570 could break CSS in MacOS just because of ";" inside? Could you test by removing it on your side if you have no personal specific CSS that could be the cause of this?

Line 1570 is that one : `/* History currently selected button ; they don't need to set background */`

**Comment by Nilvus** [comment]
@MStraeten: oh, and if you have no personal CSS set on your side and it's not the semi-colon on line 1570, you will have to test on your side as I don't have MacOS and CSS code works great on Linux. But I really don't see why it would not work on other OS. It's simple code changes and I don't understand how this could break that way CSS.

**Comment by MStraeten** [comment]
fortunately no longer reproducible after a clean build with current master

**Comment by Nilvus** [comment]
> fortunately no longer reproducible after a clean build with current master

Happy to read that!

**Pull request merged**
