### PR TITLE
speed up highpass iop

### PR DESCRIPTION
**Pull request by ralfbrown**
A recent benchmarking .xmp (posted in #6654) revealed some timing anomalies, one of which was that the highpass iop
was almost entirely running single-threaded.  This PR reorganizes the code to improve cache behavior (40% speedup),
adds an SSE codepath (in total more than doubling single-threaded performance), and parallelizes the passes of the
box filter.

Verified to produce pixel-identical results.

Timings on mire1.cr2 using Threadripper 3970X:
Threads  Old    New
1        0.663  0.324  (-51%, 2.04x)
32       0.663  0.034  (-95%, 19.5x)

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Thanks !

**Comment by TurboGit** [comment]
For the record, before/after:

```
$ ./run.sh 0028-highpass-overlay
Test 0028-highpass-overlay
      Image mire1.cr2
      CPU & GPU version differ by 596935 pixels
      Max  dE         0.0000
  OK


Total test 1
Errors     0
```

**Comment by johnny-bit** [comment]
This might've break my builds I'm testing in #6603

problem found:
```
In file included from lib/darktable/plugins/introspection_highpass.c:23:
/Users/runner/work/darktable/darktable/src/src/iop/highpass.c:337:3: error: use of undeclared identifier '__m128'
  __m128 L = { 0, 0, 0, 0 };
  ^
/Users/runner/work/darktable/darktable/src/src/iop/highpass.c:338:3: error: use of undeclared identifier '__m128'
  __m128 hits = { 0, 0, 0, 0 };
  ^
/Users/runner/work/darktable/darktable/src/src/iop/highpass.c:339:9: error: unknown type name '__m128'
  const __m128 one = { 1.0f, 1.0f, 1.0f, 1.0f };
        ^
/Users/runner/work/darktable/darktable/src/src/iop/highpass.c:344:5: error: use of undeclared identifier 'L'
    L += _mm_load_ps(buf + index);
    ^
/Users/runner/work/darktable/darktable/src/src/iop/highpass.c:344:10: error: implicit declaration of function '_mm_load_ps' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    L += _mm_load_ps(buf + index);
         ^
/Users/runner/work/darktable/darktable/src/src/iop/highpass.c:345:5: error: use of undeclared identifier 'hits'
    hits += one;
    ^
/Users/runner/work/darktable/darktable/src/src/iop/highpass.c:353:7: error: use of undeclared identifier 'L'
      L += _mm_load_ps(buf+np*width);
      ^
/Users/runner/work/darktable/darktable/src/src/iop/highpass.c:353:12: error: implicit declaration of function '_mm_load_ps' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      L += _mm_load_ps(buf+np*width);
           ^
/Users/runner/work/darktable/darktable/src/src/iop/highpass.c:354:7: error: use of undeclared identifier 'hits'
      hits += one;
      ^
/Users/runner/work/darktable/darktable/src/src/iop/highpass.c:356:5: error: implicit declaration of function '_mm_store_ps' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    _mm_store_ps(scanline+4*y, L / hits);
    ^
/Users/runner/work/darktable/darktable/src/src/iop/highpass.c:356:32: error: use of undeclared identifier 'L'
    _mm_store_ps(scanline+4*y, L / hits);
                               ^
/Users/runner/work/darktable/darktable/src/src/iop/highpass.c:356:36: error: use of undeclared identifier 'hits'
    _mm_store_ps(scanline+4*y, L / hits);
                                   ^
/Users/runner/work/darktable/darktable/src/src/iop/highpass.c:363:5: error: use of undeclared identifier 'L'
    L -= _mm_load_ps(buf+op*width);
    ^
/Users/runner/work/darktable/darktable/src/src/iop/highpass.c:363:10: error: implicit declaration of function '_mm_load_ps' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    L -= _mm_load_ps(buf+op*width);
         ^
/Users/runner/work/darktable/darktable/src/src/iop/highpass.c:364:5: error: use of undeclared identifier 'hits'
    hits -= one;
    ^
/Users/runner/work/darktable/darktable/src/src/iop/highpass.c:367:7: error: use of undeclared identifier 'L'
      L += _mm_load_ps(buf+np*width);
      ^
/Users/runner/work/darktable/darktable/src/src/iop/highpass.c:368:7: error: use of undeclared identifier 'hits'
      hits += one;
      ^
/Users/runner/work/darktable/darktable/src/src/iop/highpass.c:370:5: error: implicit declaration of function '_mm_store_ps' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    _mm_store_ps(scanline+4*y, L / hits);
    ^
/Users/runner/work/darktable/darktable/src/src/iop/highpass.c:370:32: error: use of undeclared identifier 'L'
    _mm_store_ps(scanline+4*y, L / hits);
                               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```
probably missing include or whatever :)

**Comment by ralfbrown** [comment]
@johnny-bit The needed include would be xmmintrin.h.   Other iops which use SSE have

```
#if defined(__SSE__)
#include <xmmintrin.h>
#endif
```
at the top, following the other includes.  I don't know which other header being pulled in by highpass (directly or indirectly) is including xmmintrin.h for me, Pascal, and the current Travis builds, so maybe safest to add the above three lines.

**Comment by johnny-bit** [comment]
current travis build doesn't have minimalistic build (eg everything off, except for sse), so probably can't catch missing header ;)

**Pull request merged**
