### PR TITLE
fix retina scaling mismatch while pan/zooming

### PR DESCRIPTION
**Pull request by dterrahe**
fixes https://github.com/darktable-org/darktable/pull/15084#issuecomment-1694608419

@zurdo-10 would you be able to test if this corrects your issue on Mac?

### CODE REVIEW

**Comment by zurdo-10** [comment]
Yes I will as soon as we have the build with the commit

**Comment by dterrahe** [comment]
This won't be included in nightly builds until it has been merged into master, which would normally require confirmation that it fixes the actual problem. So ideally somebody would build this PR from source to test. If you have no experience doing so, maybe @MStraeten would be able to assist?

Or @TurboGit could consider merging this based on:
* my testing on windows and linux that shows no regressions
* that I've managed to reproduce the issue by hardcoding ppd to 2 and this PR fixes it
* that this is actually a simplification

Having said that, I realise Pascal is hopefully still enjoying a holiday, so he may not be in a position to test and merge immediately and @MStraeten might want to release a mac build with this cherrypicked anyway (if it actually works) to fix the regression caused by #15084 there.

**Comment by MStraeten** [comment]
[darktable-4.5.0+380~g9fab6bd1_x86_64.dmg](https://mega.nz/file/fSBEWKBC#xt_DF-qAU_WyziTqMhJ_Pe16riR6bESMYJwXI23bPow)

**Comment by dterrahe** [comment]
Wow, thanks!

**Comment by zurdo-10** [comment]
I think that now it is behaving as expected on both iMac (screen capture below) and secondary display. Thank you to both of you !

https://github.com/darktable-org/darktable/assets/67486942/93ab13e7-21f3-4b80-9a7e-65c76b0cc390

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
