### PR TITLE
crawler fix - update write timestamp in db if required but do not write back the xmp file

### LINKED ISSUE #5847: All XMP are rewriting when "update database from selected xmp files"
I am editing the same shots on Windows or Linux computers. When I migrate my collection from Linux to Windows (or vice vers) all XMPs are overwritten (I use the "check xmp on start" option and click "update database from selected xmp files" in the crawler dialog).
But this only changes the values "import_timestamp" and "change_timestamp". And this values for each individual snapshot are always the same.
For example:
on Linux
```
   darktable:import_timestamp="1594311247"
   darktable:change_timestamp="1594311413"
```
on Windows
```
   darktable:import_timestamp="1594233276"
   darktable:change_timestamp="1594233508"
```

Darktable Version: master
OS: Debian 10 and Windows 7

### PR DESCRIPTION
**Pull request by phweyland**
attempt to fix #5847 

If xmp timestamp is newer than db write timestamp, and the user requests "update database from selected xmp files", db is updated with xmp data (as today) but:

- db write time stamp is updated with the xmp file timestamp
 - the xmp file is not updated (as now db data = xmp data) even if "write sidecar file for each image" is set.

A g_free() is also added, which should avoid a memory leak. Would that help #5722 ?

EDIT: as pinpointed by @esq4 fixes also the wrong update of import_timestamp in dt_image_cache_write_release()

### CODE REVIEW

**Comment by phweyland** [comment]
Pascal, I think there are 2 fixes you could add directly to 3.2:
- g_free() in crawler.c
- import_timestamp in image_cache.c

**Comment by TurboGit** [comment]
It is too late for 3.2, the tarball is already created (two times already). And we need to let time to packagers of the WIndows and MacOS version. This is really annoying issue but not critical. I'll add a note on the release notes about this possible issue.

Can you help me describe the more precisely in which context it happens and how to avoid it?

Thanks.

**Comment by phweyland** [comment]
> Can you help me describe the more precisely in which context it happens and how to avoid it?

#5722 & #5847 are related to the usage of a stock of images + xmp from two different systems and/or databases with "update database from selected xmp files" (that means that both "write sidecar file for each image" and "check xmp on start" are set).

In that case, the current system sees the xmp timestamps left by the other system and show up the corresponding list of images. If the user  click on "update database from selected xmp files" dt updates the current database but also the xmp files, changing again the xmp timestamps. So each time the user switches to the other system and/or database, dt triggers again the change detection.

Workaround ? Not really but the effect can be limited. Before "update database from selected xmp files" only select the modified images. Or re-import manually these modified images or folders. That will limit the issue to those modified folders or images (instead of all images).

This PR aligns the timestamps of the current database with the current xmp timestamps and removes the re-write of the xmp files (which is not needed as the database has just been aligned on them). So the detection does not occur again on both system and/or database as long as no change is made by the user.

The bug on dt_image_cache_write_release() has no workaround. The import timestamp can be wrong (overwritten by change timestamp).

**Comment by esq4** [comment]
> In that case, the current system sees the xmp timestamps left by the other system and show up the corresponding list of images. If the user click on "update database from selected xmp files" dt updates the current database but also the xmp files, changing again the xmp timestamps. So each time the user switches to the other system and/or database, dt triggers again the change detection.

Exactly!

> Workaround ? Not really but the effect can be limited. Before "update database from selected xmp files" only select the modified images. Or re-import manually these modified images or folders. That will limit the issue to those modified folders or images (instead of all images).

That is, I must have to manually do the work that should (and used to be) done automatically. I must remember what I edited and try to ignore the rest.

**Comment by phweyland** [comment]
> That is, I must have to manually do the work that should (and used to be) done automatically. I must remember what I edited and try to ignore the rest. Regression.

My comments there are related to 3.2 for which the PR is not applicable anymore.

Now it would be great if you could build the current master with that PR and tell us if that solves your issue or not.
And if not what are the remaining issues.
Thanks

**Comment by esq4** [comment]
I built the current master with your PR. It solves my issue but there is a couple of flaws.
1. Import timestamp and change timestamp are different in different db (I have no other timestamps). Was it intended?
2. No timestamps are displayed on Windows (they are present in the db)

timestaps in windows 7

**Comment by phweyland** [comment]
> I built the current master with your PR. It solves my issue but there is a couple of flaws.

Thanks a lot for testing.

Could you share the values of timestamps you in db and xmp file for that image ?

**Comment by phweyland** [comment]
>     2\. No timestamps are displayed on Windows (but they are present in the db)

Does that means they are displayed on Linux ?

**Comment by esq4** [comment]
> Could you share the values of timestamps you have in db and xmp file for that image ?

When I changed the image in Linux, the change_timestamp values in XMP and db became equal 1596659390.

After transferring collection to Windows, the change_timestamp value was -1 in the db.

When I changed the image in Windows the change_timestamp values in XMP and db became equal 1596732261.



> Does that means they are displayed on Linux ?

Yes of course.

**Comment by phweyland** [comment]
>     1. Import timestamp and change timestamp are different in different db (I have no other timestamps). Was it intended?

Import and change are two different events so that seems normal to have them different.

>     2\. No timestamps are displayed on Windows (but they are present in the db)

> After transferring collection to Windows, the change_timestamp value was -1 in the db.

Seems these issues are specific to windows. I don't reproduce them on linux.

Replaying this my finding is the following: timestamps are updated in db, but in cache. Then when the cache is written, timestamps (all) are lost.
If I succeed in fixing this I'll issue another PR.

**Comment by phweyland** [comment]
@TurboGit Pascal, I'm fine with PR. You can review it when you want.

**Comment by esq4** [comment]
> > ```
> > 1. Import timestamp and change timestamp are different in different db (I have no other timestamps). Was it intended?
> > ```
> 
> 
> Import and change are two different events so that seems normal to have them different.

No, not like that. I mean:
import timestamps are different in different db;
change timestamps are different in different db.

Was it intended?

**Comment by phweyland** [comment]
> > > ```
> > > 1. Import timestamp and change timestamp are different in different db (I have no other timestamps). Was it intended?
> > > ```
> > 
> > 
> > Import and change are two different events so that seems normal to have them different.
> 
> No, not like that. I mean:
> import timestamps are different in different db (on Linux and Windows in my case);
> change timestamps are different in different db (on Linux and Windows in my case).
> 
> Was it intended?

Sorry for the misunderstanding.
As explained in #5879, the timestamps are not copied (imported) for the time being. This explains (at least partly) what you see.
This said, import_timestamp is not copied intentionally and I haven't changed this.
So import_timestamp remains specific to each database.

**Comment by esq4** [comment]
> As explained in #5879, the timestamps are not copied (imported) for the time being.

"For the time being" is good.

> This said, import_timestamp is not copied intentionally and I haven't changed this.
> So import_timestamp remains specific to each database.

I do not understand the reason for this decision and I think it is not correct. Let me explain.
I suppose we can assume that the db is an image of all changes made to the collection, a kind of hash. Since the collection can change on different computers or systems, the hashes must be the same. Otherwise, the meaning of such a convenient Darktable function is blurred.

**Comment by esq4** [comment]
> @TurboGit Pascal, I'm fine with PR. You can review it when you want.

It did not help.

**Comment by ptilopteri** [comment]
@esq4 
> > This said, import_timestamp is not copied intentionally and I haven't changed this.
> > So import_timestamp remains specific to each database.
> 
> I do not understand the reason for this decision and I think it is not correct. Let me explain.
> I suppose we can assume that the db is an image of all changes made to the collection, a kind of hash. Since the collection can change on different computers or systems, the hashes must be the same. Otherwise, the meaning of such a convenient Darktable function is blurred.
> 
> In other words, it doesn't matter to me when I imported the image on this particular computer. It is important for me when I imported a picture from the camera.

I would not expect two different library db's on different computers to have the save information unless subject image was just imported and had the same xmp as the "other" computer/database.

You are LOOKING for trouble trying to work images on different computers with different databases.  Better workflow having images on shared drive and main computer with library.  Other computer(s) utilize "darktable --library :memory:" and write xmp files on.  When on main computer, reimport images to update database, or set dt to look for changed xmp files and have them saved to your library.

**Comment by esq4** [comment]
> You are LOOKING for trouble trying to work images on different computers with different databases. Better workflow having images on shared drive and main computer with library. Other computer(s) utilize "darktable --library :memory:" and write xmp files on. When on main computer, reimport images to update database, or set dt to look for changed xmp files and have them saved to your library.

I'm not LOOKING for problems, I just want to work FAST and EFFICIENTLY. A process that requires additional tweaks, actions and time could not be the best.

I will explain. I use tags to quickly find images. And I want to do this on all my computers.
Right now I just need to connect the disk and update the db at the start of dt. Now, thanks to you, this operation takes seconds.

According to the methodology you proposed, as a simple user, I first need to make special settings for launching dt (i. e. at first study and understand the documentation, and most importantly, then INVENT this method). And after that, every time I have to import the ENTIRE collection. But in collection, for example, I already have more than 10 thousand images. It's even scary to think about the waiting time.

**Comment by esq4** [comment]
> I would not expect two different library db's on different computers to have the save information unless subject image was just imported and had the same xmp as the "other" computer/database.

If it is forbidden to transfer "import timestamp" from one db to XMP and to another db (although I still do not understand the reason for this prohibition), then maybe you will introduce a new parameter to display the time of import from the camera, for example, "from camera timestamp"?

**Comment by phweyland** [comment]
> I would not expect two different library db's on different computers to have the save information unless subject image was just imported and had the same xmp as the "other" computer/database.

I can agree this is not the basic usage of dt.
But this function (xmp detection) should work properly even in that case (it seems that various people (try to) work this way).

I don't use xmp, except manually when I have a specific transfer to do. I prefer counting on a solid backup of the database.
If I had to work (alone) on several computers (same OS) I would share the db. If I had to use several computers with different OS, I would implement a kind of switch updating film_rolls table accordingly (If I remember well digikam has some mechanism which turn this quite easy). It is what I do manually when I need to run some tests on windows.

**Comment by ptilopteri** [comment]
> According to the methodology you proposed, as a simple user, I first need to make special settings for launching dt (i. e. at first study and understand the documentation, and most importantly, then INVENT this method). 

No, you do not, just start dt as:  "darktable --library :memory:"
really not that difficult.

> And after that, every time I have to import the ENTIRE collection. But in collection, for example, I already have more than 10 thousand images. It's even scary to think about the waiting time.

guess you failed to read what I proposed.  I follow this and it is fairly fast and not difficult.  But you continue to struggle and find problems and then complain when there is a workflow that just works.

I will bother you no more!

**Comment by esq4** [comment]
@phweyland 
> If I had to use several computers with different OS, I would implement a kind of switch updating film_rolls table accordingly (If I remember well digikam has some mechanism which turns this quite easy). It is what I do manually when I need to run some tests on windows.

Please write in more detail how to implement this. What if it can be implemented in the dt? ;)

https://github.com/darktable-org/darktable/pull/5879
This didn't resolve the issue in Windows.

But still
> If it is forbidden to transfer "import timestamp" from one db to XMP and to another db (although I still do not understand the reason for this prohibition; _explain it, please_), _then maybe you will introduce a new parameter_ to display the time of import from the camera, for example, "from camera timestamp"?

**Comment by phweyland** [comment]
> This didn't resolve the issue in Windows.

I am not surprised. That's probably another bug which would need some debug on windows itself.



> But still

As already said please open a specific issue for this.
On my side I won't do more before these 2 PR are merged (if accepted of course).

**Comment by esq4** [comment]
@phweyland Well. Thank you.

**Comment by TurboGit** [comment]
@phweyland : can you do a quick review of #5896 ?

**Pull request merged**
