### PR TITLE
filmicrgb: improve slightly the default parameters

### PR DESCRIPTION
**Pull request by aurelienpierre**
Just some fine-tuning of default parameters based on further experimentation.

### CODE REVIEW

**Comment by TurboGit** [comment]
Really too late for 3.0, I don't have time to test. This will for sure be in 3.0.1.

**Comment by TurboGit** [comment]
Of course there is no issue with stability. But I cannot merge code without at least testing it and see if there is no shortcoming. And I short on time at the moment. If you tested it and there is more positive feedback I can indeed merge it.

**Comment by MStraeten** [comment]
i tested these new settings - these are more convincing and in the appearance more similar (less flat) to the already defined presets. Since these are only parameters and does not exceed the range  sed in already defined presets in the module, the functionality itself is not touched, so there's no risk for the stability of 3.0.0 in my opinion

**Comment by Nilvus** [comment]
Great adjustments. Tested and it's better. Quite complementary to bilat (contrast module) PR. I really think they need to be merge on 3.0 to avoid people making habits with less better default params (see my comment on bilat PR).

**Comment by TurboGit** [comment]
Ok, let's this in 3.0 then. Looks ok to me too.

**Pull request merged**
