### PR TITLE
Remove adobe_coeff matching in Exif parser

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by johnny-bit** [comment]
wait... did it ever work correctly or what's goin on here?

**Comment by kmilos** [comment]
It seems to me it never worked!?

If fixed, we can really start overriding DNG matrices, which I'm not sure if it's the best idea, for example:

Pro: both Pentax PEF and DNG output get the same (Adobe) matrix
Con: maybe you can't process the DNG w/ Pentax intended color science any longer?

**Comment by kmilos** [comment]
Maybe it worked 5 years ago when partial matching was performed, see e.g. be41aceafb640b6d08f29630f1cb0879c904aeca

**Comment by parafin** [comment]
Yeah, I'm not sure we should overwrite the DNG matrix, especially if there is no way to select it later in colorin module.

**Comment by jenshannoschwalm** [comment]
DNG matrix is the one we want for those images, btw i think i am the one who introduced this in #2755.

The algo assumes, the specified parameters via dng exif tags are correct as the manufacturer should know best and only for the special cases defined in the list it will be overridden. At least, thats what i remember. I don't remember why falling back at all.

**Comment by kmilos** [comment]
So maybe the logic just needs to be adjusted slightly, two options come to mind:

1. We only use this fallback if `illu == -1` (i.e. there is no matrix in DNG), and we never overwrite the DNG one then (even if we end up with one that is not D65)?

2. We move this fallback into the default case of the switch (removing the `if(illum != -1)` first), and then:
  a. If 21 (D65) found in DNG, use that
  b. If not 21 or -1 (nothing in DNG), check adobe_coeffs and use that if there is match
  c. Use whatever is in DNG

Thoughts?

**Comment by jenshannoschwalm** [comment]
Option 2 is not good as there are totally valid non-D65 illuminants for dng files. So i would favor option-1 and accept a possibly "wrong" adobe_coeff derived matrix.

**Comment by kmilos** [comment]
> Option 2 is not good as there are totally valid non-D65 illuminants for dng files.

Yes, but the question is: are you worse off with an uncorrected matrix (even though it is valid) or the Adobe D65 one? I don't know ATM, and I'm fine with both options currently...

Also, I think there is the assumption that the second illuminant will always be higher temperature than the first one in the preceding code. Although that is indeed recommended by the DNG spec, it is a recommendation only, I don't think one should count on it to be always true...

**Comment by johnny-bit** [comment]
I *think* that we could recalculate most matrices to D65 via some CAT.

**Comment by kmilos** [comment]
> I _think_ that we could recalculate most matrices to D65 via some CAT

We're talking about the case where you don't know the illuminant (i.e. either 0 or not covered by existing CAT matrices yet in the Exif parser). 

Unless, of course, you're talking about trying to figure it out later in the pipeline, which I'm not currently factoring in. If that's already happening, then I agree, we probably shouldn't touch a valid vendor matrix and option 1 is preferable. (Btw, how does the Exif parser signal this unknown illuminant, it seems just a valid `img->d65_color_matrix` is set regardless? One just figures out from the wrong initial colors?)

**Comment by kmilos** [comment]
How's option 1 looking now? I also updated the comments as they were not really matching the logic...

I'm still bothered by "prefer Illuminant2", but don't see an easy way to check which is the higher one - unfortunately the enumeration is not sorted by CCT :(

> I think this is handled in colorin->commit_params where an undefined color matrix generates a visible feedback

But even today it's not undefined. We put an uncorrected one in `d65_color_matrix` for an unknown illuminant, if it exists, so it gingerly passes the check on L1585, there is no feedback AFAICT?

**Comment by kmilos** [comment]
Furthermore, it looks like `colorin` already checks adobe_coeff so this could actually be removed from here?

**Comment by kmilos** [comment]
Speaking of the devil, OnePlus puts tungsten in Illuminant2 and higher D55 in Illuminant1, so the adaptation is not great: https://github.com/darktable-org/darktable/issues/9223

**Comment by jenshannoschwalm** [comment]
Well, that's nothing we can do here i fear. MANY dngs generated by soft or mobiles are just crap.

For this part of dt i would keep DNG "standard". Maybe have some sort of presets for colorin?

**Comment by kmilos** [comment]
> Well, that's nothing we can do here i fear.

We could try figuring out the actual higher illuminant.

**Comment by jenshannoschwalm** [comment]
Just from my memory, Doesn't the dng specs also recommend to prefer the first illu? I maybe wrong here. BTW what is the rationale to use the higher illuminant?

**Comment by kmilos** [comment]
No, if you have two, DNG spec say you interpolate, there is no preference... If you're outside the range, you take the closest one.

I thought the rationale for using the higher one came from your commit and this comment:

```c++
// If we have D65 in Illuminant1 we use it; otherwise we prefer Illuminant2 because it's the higher
// color temperature and thus closer to D65
```

I guess using the higher (i.e. closest to D65) w/ CAT is still better than using lower w/ CAT?

**Comment by kmilos** [comment]
From the DNG spec:

> DNG provides for one or two sets of color calibration tags, each set optimized for a different illuminant. If both sets of color calibration tags are included, then the raw converter should interpolate between the calibrations based on the white balance selected by the user.
> If two calibrations are included, then it is recommended that one of the calibrations be for a low color temperature illuminant (e.g., Standard-A) and the second calibration illuminant be for a higher color temperature illuminant (e.g., D55 or D65). This combination has been found to work well for a wide range of real-world digital camera images.
> DNG versions earlier than 1.2.0.0 allow the raw converter to choose the interpolation algorithm. DNG 1.2.0.0 and later requires a specific interpolation algorithm: linear interpolation using inverse correlated color temperature.
> To find the interpolation weighting factor between the two tag sets, find the correlated color temperature for the user-selected white balance and the two calibration illuminants. If the white balance temperature is between two calibration illuminant temperatures, then invert all the temperatures and use linear interpolation. Otherwise, use the closest calibration tag set.

AFAIK dt does not leverage two matrices when the user is changing the white balance; not for the DNGs, nor for the raws - in adobe_coeff we keep only the D65 calibration

P.S. Adobe is upgrading to 3 illuminant calibration in [DNG 1.6](https://helpx.adobe.com/photoshop/kb/dng-specification-tags.html#TripleIlluminantColorProfile), fun!

**Comment by johnny-bit** [comment]
WTF ADOBE??

So... for WB temp lower than low illuminant use coeff calculations from low illuminant, for wb temp hiher than high illuminant use cueff calculations from high illuminant and for those between - "do linear interpretation". WTF adobe.

And with 3 illiuminants - the 3rd one is "as shot"! FFS...

what are they on?

**Comment by jenshannoschwalm** [comment]
I missed the suggested interpolation - or i can't remember. Changing the matrix calculation would break existing edits ...

**Comment by johnny-bit** [comment]
soo... that would have to be versioned off?

**Comment by jenshannoschwalm** [comment]
I looked up the code and it seems pretty difficult as the code is. If i understand this correctly the matrix is read in while import and is kept in the image struct. Colorin always uses that in commit_params but does not seem to keep that in the xmp so reimporting with a new calculation sheme would break edit. At least that's what i think / understand.

At least it seems to be not an easy 3.6 fix ...

**Comment by kmilos** [comment]
Dropping this PR as it has no affect on 3.6 behaviour. I think future discussion is best continued in the related issue.

**Pull request closed without merging**
