### PR TITLE
white balance presets: Sony RX0

### PR DESCRIPTION
**Pull request by macrat**

### CODE REVIEW

**Comment by LebedevRI** [comment]
Please don't touch the submodule, and don't use `git commit -a` :)

**Comment by LebedevRI** [comment]
Also, do open the issue in the redmine, please, so it can be referenced.

**Comment by macrat** [comment]
Sorry my mistake. I made revert commit, please squash merge it. I'm sorry.

I made an issue in the redmine ( https://redmine.darktable.org/issues/12081 ). Please check.

**Comment by TurboGit** [comment]
Merged manually.

**Pull request closed without merging**
