### PR TITLE
modulegroups : no right-click for deprecated group

### PR DESCRIPTION
**Pull request by AlicVB**
@TurboGit : you mentioned that in your original review, but I completely forgot to fix that point... Sorry !

### CODE REVIEW

**Comment by Nilvus** [comment]
To avoid a PR from me for a little CSS hack on your work, maybe adding to that PR (or a specific commit @TurboGit) to improve padding in popup menu in modulegroups:

```
#modulegroups_iop_title,
#modulegroups-iop-popup-name
{
   padding: 0.2em 0.5em;
}
```

About a border suggested by @TurboGit, I've answered on PR #6970.

**Comment by Nilvus** [comment]
Another thing I just thought and related to modulegroups presets. In all modules the preset order have been improved to first display users preset, then after a separator, display default darktable presets. This is not implemented in modulegroups presets. I consider that as an issue as it's not consistent. Let me know if I should create an issue for that or if that could be easily implemented to correct that issue in 3.4?

**Comment by TurboGit** [comment]
> Let me know if I should create an issue for that or if that could be easily implemented to correct that issue in 3.4?

Yes, please would be nice to indeed do that for consistency.

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Pull request merged**
