### PR TITLE
add dynamic accelerators to comboboxes

### PR DESCRIPTION
**Pull request by elstoc**
adds ability to assign a keyboard shortcut to dynamically change
comboboxes. Hold the key and scroll up/down to change to the
next/previous combobox value.

### CODE REVIEW

**Comment by johnny-bit** [comment]
OMG YAAAASSS!!!

**Comment by dterrahe** [comment]
With this in place it should be straightforward to implement this in my MIDI module as well (with a similar if(w->type == DT_BAUHAUS_SLIDER) conditional).

On the x-touch mini, I'll try to map each option in a combobox to a different LED on the ring around the rotator. So I should map 1-> 127/13, 2-> 2*127/13 etc, or something like that. The BCF2000 has 15 lights in the LED ring, so Yeah, another configuration option! ;-)

That would be _another_ place where I'd need to use the dt_control_log code to generate a toast. Maybe we should get @houz opinion again on adding a dt_bauhaus_combobox_set_notify call in bauhaus as you suggested in https://github.com/darktable-org/darktable/issues/4528#issuecomment-602270639

**Comment by houz** [comment]
Absolutely not. If MIDI support gets added then not ontop the accelerators, wrapping layers over layers. It needs a clean rewrite of the whole control system in dt. All that code is basically unmaintainable already, I will not agree to monkey patching more stuff in.

**Comment by johnny-bit** [comment]
So... This PR is OK to integrate? It very well works for my usecase and UI stuff, speeds up some ops :smiley: It's not yet so complicated, but goes into "right" direction usability-wise.

I understand that MIDI system is too big to monkey-patch in, but this small change looks nice...

As for whole control system rewrite: I'm very interested in it and I see that @elstoc and @dterrahe too, so where can we discuss design of it?

**Comment by elstoc** [comment]
Leaving aside the MIDI support though, it might still be better to have a function dt_bauhaus_combobox_set_notify to replace the three places I now have the same combobox toast message (just to remove some of the duplication).

**Comment by johnny-bit** [comment]
(just a note - @houz is OK with merging this PR, just expressed that the changes ned to be taken into account when doing new input system for darktable, that could handle all the things and be very much resilient to random breakages. that work though is long and hard. I'll post later on in the wiki wat was the discussion about)

**Comment by TurboGit** [comment]
Works for me. Thanks!

**Pull request merged**
