### PR TITLE
Implement overwrite dialog when importing style[s].

### PR DESCRIPTION
**Pull request by darkelectron**
This adds a dialog when importing styles, similar to the one when exporting(#6670).

Adds a toast message when unable to read a file on import.

### CODE REVIEW

**Review by TurboGit — CHANGES_REQUESTED** [review]
If I try to import two styes already imported I get the dialog asking for confirmation. I select the tick to apply my choice to all styles and click overwrite. Still I get the message "style ... already present.", seems like the option to use the choice for all styles is not properly used.

**Comment by darkelectron** [comment]
@TurboGit I can't seem to reproduce on my side.

One scenario I suspect is that the filename may not be the same as the style name. Meaning `style_name.dtstyle` and the name in the xml(`<info><name>stylename<name>...`) file are different. That will produce the "already exist" message, since primarily what I use to check, is the filename instead the name in the xml or both(haven't found a way, yet).

**Comment by johnny-bit** [comment]
styles can use hierarchy searator `|` which isn't really liked character for filenames, so style can have name `B&W|high contrast`, which will be in xml written as `B&amp;W|high contrast`, but will probably have name like `B_W_high_contrast.dtstyle`. Obviously what needs to be unique is name that will land in the DB :)

**Comment by darkelectron** [comment]
@TurboGit could you check if its okay now. Pushed this a while back.

What's happening now is: I get the name from the xml file.

**Comment by TurboGit** [comment]
Ok, works for me now.

**Review by TurboGit — APPROVED** [review]

**Pull request merged**
