### PR TITLE
utility: correctly handle SVG scale with librsvg 2.52

### LINKED ISSUE #10449: darktable logo cropped with hidpi-screen
**Describe the bug/issue**

The darktable logo in the top-left corner is too big and therefor cropped (see screenshot)

**To Reproduce**
1. hidpi-screen (screen resolution 3840x2160)
2. scale factor 200%
3. start darktable 3.7.x
4. see cropped logo

**Expected behavior**
Adjust logo size according to the rest of the screen

**Screenshots**
image

**Which commit introduced the error**
I tried bisecting but could not find a version without the issue

**Platform**
* darktable version : 3.7.0+1503~gae523b769
* OS                : Linux - kernel 5.10.70
* Linux - Distro    : Manjaro, Gnome 40.4.0, X11
* screen resolution 3840x2160
* scale factor 200%

**Additional context**
No issue with 3.7.0 and scale factor 100%
No issue with 3.6.1 and scale factor 200%
I've seen the cropped logo in two youtube-videos using 3.7

### LINKED ISSUE #10489: watermark: adding simple text (svg) is broken with librsvg 2.52.x
when adding a watermark "simple text (svg)" the rendering is fine if darktable is built with librsvg 2.50.7 but broken with librsvg 2.52.4

seems to be a sibbling to #10449 

**Screenshots**
rendering with librsvg 2.52.4:
image

**Which commit introduced the error**
no darktable change introduced this, just updating librsvg from 2.50 to 2.52

**Platform**
* darktable version : darktable 3.7.0+1550~g0a3aab0cc-dirty
* OS                : OSx

Workaround:
build packages using librsvg 2.50.x (at least for win or osx builds)

### PR DESCRIPTION
**Pull request by parafin**
Fixes #10449
Fixes #10489

### CODE REVIEW

**Comment by parafin** [comment]
Fix for #10449 is simple (first change of the diff), but #10489 is not completely fixed - specifically simple-text watermark renders differently compared to librsvg 2.50. To reproduce use "test" as text and see that with default scale and position last letter "t" gets trimmed on the right side. With librsvg 2.50 the whole string fits inside the image. This will break history stacks that use such watermarks (with no defined global dimensions). That's why I marked this as draft for now.

The issue is that I can't find a way to reproduce what rsvg_handle_get_dimensions returned in librsvg 2.50. rsvg_handle_get_intrinsic_size_in_pixels doesn't work for SVG without global dimensions defined (like simple-text watermark), and rsvg_handle_get_geometry_for_layer seems to return different value for some reason.

**Comment by piratenpanda** [comment]
Can't we just "update" simple-text svg with dimensions or is there a reason for it to have none?

**Comment by parafin** [comment]
Its dimensions depend on text specified by user in watermark iop itself.

**Comment by piratenpanda** [comment]
Sure, makes sense

**Comment by parafin** [comment]
OK, found the issue, it was a rounding error (or rather a lack of rounding). This PR is ready.

**Comment by Mark-64** [comment]
> Fix for #10449 is simple (first change of the diff), but #10489 is not completely fixed - specifically simple-text watermark renders differently compared to librsvg 2.50. To reproduce use "test" as text and see that with default scale and position last letter "t" gets trimmed on the right side. With librsvg 2.50 the whole string fits inside the image.

Tested in Windows 10 
I confirm #10449 is fixed, but the watermark text still clips on the right with some letters at the end

immagine

**Comment by TurboGit** [comment]
IIRC the clipping on the right is because of the SVG has some margins. It was long time ago when I looked at this and I found no solution back then.

**Review by TurboGit — APPROVED** [review]
Thanks @parafin for looking at this! Looks good to me. Tested on current master.

**Comment by parafin** [comment]
> > Fix for #10449 is simple (first change of the diff), but #10489 is not completely fixed - specifically simple-text watermark renders differently compared to librsvg 2.50. To reproduce use "test" as text and see that with default scale and position last letter "t" gets trimmed on the right side. With librsvg 2.50 the whole string fits inside the image.
> 
> Tested in Windows 10 With librsvg 2.52 I confirm #10449 is fixed, but the watermark text still clips on the right with some letters at the end
> 
> immagine

Main thing is that it should be consistent with librsvg 2.50 result, not that it clips or not (though it may be considered as a separate bug).

**Comment by Mark-64** [comment]
Indeed it is different from 2.50

immagine

**Comment by parafin** [comment]
That's not what I'm seeing on macOS. Here is old librsvg:
librsvg-2 50
Here is new librsvg:
librsvg-2 52
Notice how they are different from both of your screenshots regarding right border. IMHO both of your screenshots look wrong - old one has too big margin, new one clips. It would be interesting to compare to how it looks on Linux. @TurboGit, could you make a screenshot of this text with simple-text watermark and default settings? We should consider Linux render with old librsvg as a reference one.

Also, here are relevant library versions on my system currently:
librsvg-2.52.4
cairo-1.17.4

**Comment by parafin** [comment]
Also font is different, it might be related to how fonts are rendered on different OSes. I won't be able to solve this for Windows, since I don't build darktable on Windows...

**Comment by parafin** [comment]
I’ve asked on IRC and got screenshot from Linux with old librsvg. It looks more or less like my macOS screenshots. It’s hard to find someone on Linux with new librsvg. @piratenpanda, could you help out with that to confirm this fix works?

@Mark-64, I think Windows issue is something different, so maybe create a new bug report for it?

**Comment by piratenpanda** [comment]
For me it also clips on the right side when scale is at 100%

**Comment by parafin** [comment]
Could you please try with the same exact text? But I guess in any case I don’t have anything better to suggest than this PR…

**Comment by piratenpanda** [comment]
It looks the same. Also I notice that when using top positions in the position selector, the top is also clipped. 

watermark2

**Comment by parafin** [comment]
top is cropped with top position for me too on macOS, both with old and new librsvg. That part is consistent. This discrepancy I suspect is due to font subsystem differences…

**Pull request merged**
