### PR TITLE
Macos fixes

### PR DESCRIPTION
**Pull request by parafin**
Let's check CI status.

### CODE REVIEW

**Comment by MStraeten** [comment]
ii get a build error:
```
[ 17%] Building C object bin/CMakeFiles/lib_darktable.dir/common/dynload.c.o
/Users/martinstraeten/src/darktable_debug/src/common/dynload.c:98:30: error: implicitly declaring library function
      'malloc' with type 'void *(unsigned long)' [-Werror,-Wimplicit-function-declaration]
    module = (dt_gmodule_t *)malloc(sizeof(dt_gmodule_t));
                             ^
/Users/martinstraeten/src/darktable_debug/src/common/dynload.c:98:30: note: include the header <stdlib.h> or
      explicitly provide a declaration for 'malloc'
1 error generated.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/common/dynload.c.o] Error 1
make[1]: *** [bin/CMakeFiles/lib_darktable.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by parafin** [comment]
Just force-pushed a fix, please re-try (`git fetch` and `git reset --hard origin/macos_fixes`).

**Comment by MStraeten** [comment]
seems to be fine
`./bin/darktable-cltest`

```
0.029090 [opencl_init]
0.029337 [opencl_init] found opencl runtime library '/System/Library/Frameworks/OpenCL.framework/Versions/Current/OpenCL'
0.029370 [opencl_init] opencl library '/System/Library/Frameworks/OpenCL.framework/Versions/Current/OpenCL' found on your system and loaded
0.031560 [opencl_init] found 1 platform
0.053456 [opencl_init] found 3 devices
0.053504 [opencl_init] discarding CPU device 0 `Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz'.
```

**Comment by parafin** [comment]
Cool, thanx for testing. Will merge manually after CI shows green light.

**Pull request closed without merging**
