### PR TITLE
po/performance mode

### PR DESCRIPTION
**Pull request by TurboGit**

### CODE REVIEW

**Comment by parafin** [comment]
Looks correct, but one thing to check is how PPD affects this code. With PPD == 2, 100% zoom is 1:1 real pixels or 1:1 dots sized 2x2 pixels? I mean FAST should be used only when scale is more than 1:1 real pixels.

**Comment by jenshannoschwalm** [comment]
Can't test but i think that for PPD==2 100% zoom we will have 1:1 real pixels for thumbs, not sure about darkroom though. Otherwise yes. BTW for current linux cairo FAST is the same as NEAREST.

**Comment by parafin** [comment]
Another question would be is how should 100% zoom work on HighDPI. Probably it should be 1:1 real pixels.

**Comment by TurboGit** [comment]
@parafin : you have a point here, we want to disable any cairo filter when above 1:1 and so taking into account the ppd.

New patch set pushed which works for ppd == 1 and ppd = 2 (tested).

**Comment by TurboGit** [comment]
For HiDPI screen I suppose my last patch does cover this case too. I can't test as I don't have an HiDPI screen.

**Comment by jenshannoschwalm** [comment]
I you are working under gnome there is the system setting available doing exactly this, switch to system ppd==2

**Comment by TurboGit** [comment]
> I you are working under gnome there is the system setting available doing exactly this, switch to system ppd==2

Where is this setting ? Is that the scale 200% in the screen preferences ?

**Comment by matt-maguire** [comment]
Just below the navigation inage at the top left of the darkroom view, there is a little dropdown menu where you can set the scale factor for the preview image -- setting this to 200% provkes the sluggish behaviour.

**Comment by jenshannoschwalm** [comment]
Yes.

**Comment by TurboGit** [comment]
Perfect! Tested and all seems ok for HiDPI. I'll merge. Thanks.

**Pull request merged**
