### PR TITLE
Bugfix #12913 (HLR segmentation masks)

### LINKED ISSUE #12913: HLR segmentation based: weird segmentation masks in combination with waveform/parade mode histogram
depending on the combination settings the masks shows different colored artifacts:
image
switching mask on off several times can change those strange artifacts; sometimes no artifacts, sometimes the color changes

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. open segmentation based hlr
2. Click on mask for segments
3. see artifacts; if not do it some further times

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version :  darktable 4.1.0+1016~g0a9aca6b7-dirty
* OS                : OSx

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
As constantly reported and checked by @MStraeten (thanks for the keeping me on the track btw)!) there was a "somewhat strange" issue that seemed to be OSX specific. In fact that has not been true.

Basically it comes down to accessing not-initialized data, mostly obvious in the mask visualizing mode but possibly also in normal processing code. (That got unnoticed because the algorithms keeps stable, just not optimal segments)

So a complete & in-depth review of the complete code

- making sure by safe tests and proper housekeeping we don't get wrong data
- some functions simplified as we can use data from segment structs instead of passed parameters
- some functions perform better
- the morphing operations have been improved

So - no significant maths modifications (so no version bump required), visible output might be different marginally.

Fixes #12913

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
@MStraeten could you check this a last time please to confirm the issue has been finally fixed?

**Comment by MStraeten** [comment]
keeps fine, so seems to be finally fixed

**Comment by jenshannoschwalm** [comment]
Release note: "Various fixes in highlights reconstruction segmentation mode" ?

**Comment by TurboGit** [comment]
A bit of diff, but still pass:

**Pull request merged**
