### PR TITLE
Hdr8043

### LINKED ISSUE #8043: modern chromatic adaptation clashes with HDR DNG
The defaults settings for colorin.c, upon which the ones of temperature.c and channelmixerrgb.c depend for the white balance, always use the embedded color profile for DNG files. This was changed last december to properly support DNG files. Previously, if available, colorin.c would default to the standard matrix if available first.

When darktable creates an HDR by merging pictures, it doesn't embed the input profile in the resulting DNG. When opening the DNG, the white balance is off, as well as the input profile.

To do :
force the DNG merging to copy and embed the white balance coeffs and the input profile, from the source images, then deal with DNG in an uniform way.

### PR DESCRIPTION
**Pull request by Cobert0**
Fix #8043 
Suppress ColorMatrix tag in Hdr dng exif header to get standard color matrix,
Add camera white balance in  dng exif header to get it in rawspedd decoder.

### CODE REVIEW

**Comment by parafin** [comment]
ColorMatrix1 and CalibrationIlluminant1 DNG tags are mandatory, so you have to write the values you want to be applied explicitly, there is no “standard color matrix” concept in DNG specification.

**Comment by Cobert0** [comment]
Ok, 
does it mean whe have to put camera color matrix (adobe_coeff.c) in ColorMatrix1 and CalibrationIlluminant1 =21?

**Comment by parafin** [comment]
Yes

**Comment by parafin** [comment]
I mean I think so, I have no idea how HDR creation works in darktable.

**Pull request closed without merging**
