### PR TITLE
Add a search box in presets perferences and shortcuts fixes

### LINKED ISSUE #10039: shortcuts: wrong tree expanded
In 3.7.0+1077~g3f81d9547.

Open the preferences dialog, select the "shortcuts" tab and then attempt to expand either the "other views" or the "fallbacks" tree. Instead, the "active view" tree is expanded.

This is not usually an issue when reaching this dialog via the "define shortcuts" button, since the appropriate tree is usually expanded when entering this dialog.

@dterrahe I seem to recall a similar issue with the "actions" tab but I don't remember what you did to fix it.

### LINKED ISSUE #10040: Input NG: Consider swapping the shortcuts and actions panes
In the shortcuts setup window, clicking on the lower (actions) pane causes the contents of the upper (shortcuts) pane to update. This feels slightly unnatural to me and that the panes should be swapped around.

@dterrahe what was the reason these were put this way around? Perhaps I'm missing something important.

### LINKED ISSUE #10046: Input NG: Default actions seem to show a blank effect
When assigning simple shortcuts to widgets, the default action appears to show an element but without an effect in the shortcuts pane of the setup window.

For example, if I assign the `#` key to a processing module, the default action shows as a blank effect on the show element (should show "toggle"?):

Screenshot_2021-09-21_08-27-48

Similarly, if I assign the `#` key to a slider, the default action shows as a blank effect on the value element (should show "edit"?):

Screenshot_2021-09-21_08-29-13

### PR DESCRIPTION
**Pull request by dterrahe**
This adds a permanent search box in the presets tab of preferences and moves the export/import buttons to the right, so the look is consistent with the shortcuts tab. The search function itself is also improved so that it does case insensitive search into the modules (it expands them when needed).

The search boxes in both tabs are improved so that pressing Enter takes you to the tree view with the found entry selected (and another Enter opens the edit box or starts defining a shortcut).

The shortcut list for the active view is now expanded when the preferences dialog was just openen. Also fixes #10039.

In the shortcuts dialog (or tab in preferences) the shortcuts and actions lists (and their corresponding search boxes) have been swapped; fixes #10040.

Edit: #10046 needs more thought (and a separate PR). Removed commit from this PR.

### CODE REVIEW

**Comment by elstoc** [comment]
> to me this still looks unnecessarily cluttered and often the selected default is irrelevant because most of the time the fallback effects are used (sliders with scroll wheel for example). But what do I know; I'm just the .ssh.l. who wrote this sh.t. :-) 

So you _know_ what it does by default and you've built the fallbacks to make it work how you want it to. The rest of us have to look it up and the dialog is the best way to do that. I don't mind putting explanations in the manual but we should at least give a clue as to what things do in the dialog.

**Comment by dterrahe** [comment]
> The rest of us have to look it up and the dialog is the best way to do that.

You'd find that in the fallback definitions for slider, not in the (default) effect of the shortcut you set up.

What we wouldn't want people to do is to start defining "key+scroll" shortcuts for each slider. _Normally_ they would just use "key" and depend on the fallbacks (get move left/right *.1 and up/down *10 for free and be able to use double click to reset).

Unless of course they want to map "key+scroll", "key+horizontal" and "key+vertical" to different sliders.

**Comment by elstoc** [comment]
Thanks @dterrahe I think it looks much clearer with the default defined in the setup window.

It looks like there's some style issue with the search boxes/buttons at the bottom of the screen with this PR:

Screenshot_2021-09-21_14-36-21

**Review by TurboGit — APPROVED** [review]
Works for me, thanks !

**Pull request merged**
