### PR TITLE
po/progress meters for history actions (compress/copy/discard)

### PR DESCRIPTION
**Pull request by TurboGit**
On top of #17207 and add safety checks.

@ralfbrown : This is what I had in mind, can you review/comment? TIA.

### CODE REVIEW

**Comment by ralfbrown** [comment]
Will test it out in the morning.

**Comment by jenshannoschwalm** [comment]
We might also want to use `dt_set_backthumb_time(5.0)` while we do some modify-history-action for an image, that would defer thumbs updating until jobs are done.

**Comment by ralfbrown** [comment]
@TurboGit I've updated 17207 with your suggested changes as well as others.

@jenshannoschwalm Will experiment with that later.

**Comment by deekayhd** [comment]
please remove documentation-pending label as this PR has been closed. Maybe it should be added to PR #17207 then?

**Pull request closed without merging**
