### PR TITLE
import: fix lua filter regression due to ee9ac74

### LINKED ISSUE #8525: Lua import filters are not being called when importing images
**Describe the bug/issue**
Lua can add import filters to control what images are imported.  Tried the "prefer raw over jpeg" filter and both the raw and the jpeg got imported.  Added debugging statements to the filter and they never printed so it looks like the filter was never called.

**To Reproduce**
1. Have a folder of images with raws and jpgs (same basename, different extension)
2. Start the import_filter_manager lua script, then the import_filters lua script
3. In the import parameters drop down select the import filter drop down and select "prefer raw over jpeg"
4. Import the folder
5. Notice jpgs and raws are both imported

**Expected behavior**
Only raws should have been imported

***Which commit intruduced the error**
ee9ac742f1fa0ac7d5ca2e8c39743934652df6a0

**Additional context**
The lua filter was called from dt_film_import1() in src/control/jobs/film_jobs.c from dt_film_import in src/common/film.c which was called from src/libs/import.c.  It appears that the new import process orphaned all of that code, but lua still uses the dt_film_import to import a film roll from a script.

I've attached a version of import_filters with debugging messages.  Replace import_filters.lua in official/, start darktable with -d lua, start import_filter_manager, start import_filters.  Go to the import settings and enable "prefer raw over jpeg"

In 7ef0d44c545536b39e43ac3fa0782bcddc1da654 you'll see a line for every image plus a few more if there are raws and jpegs.

In ee9ac742f1fa0ac7d5ca2e8c39743934652df6a0 there is nothing.

### PR DESCRIPTION
**Pull request by phweyland**
fix #8525

### CODE REVIEW

**Comment by TurboGit** [comment]
@wpferguson : can you test & approve this PR ? TIA.

**Comment by wpferguson** [comment]
I'll do that in just a few...

**Comment by wpferguson** [comment]
@TurboGit Works fine.  Thanks @phweyland

**Comment by TurboGit** [comment]
Thanks for both of you !

**Pull request merged**
