### PR TITLE
change icon display for 'always-on' and 'always-off' iop module header buttons

### PR DESCRIPTION
**Pull request by elstoc**
Makes the displayed shade of the 'always-on' module closer to that of the 'on' module (to match the display in the history module), though it is still made slightly darker by gtk because the button is insensitive.

Also adds an 'always-off' icon. Examples of all possible states below (ignoring the potential 'focus highlighting' in #5091), in order:

- Off (can be switched on)
- Forced Off (cannot be switched on for this image)
- Forced On (cannot be switched off for this image)
- On (can be switched off)

Screenshot_2020-05-17_12-38-38

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
imho the old icon was better. Something always on should need no further amplification.

**Comment by elstoc** [comment]
First of all I should have mentioned that the code right now is inconsistent: ``dt_iop_gui_set_enable_button`` runs     ``gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(module->off), FALSE)`` but ``dt_iop_gui_get_expander`` has ``  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(hw[IOP_MODULE_SWITCH]), module->enabled)``

Second - the icon image already tells you whether you can interact with a module but the colour should tell you whether it is currently switched on to be consistent with the rest of the UI. The module panel is currently inconsistent with the history module, which displays 'always on' and 'manually switched on' in the same shade:

Screenshot_2020-05-17_09-01-11
Screenshot_2020-05-17_09-01-38

**Comment by parafin** [comment]
I would prefer always-on icon be as visible (bright) as simple on icon. I often look over the list of iops to get a sense of what's currently in the pipe (yes, I know there's "active" group).

**Comment by elstoc** [comment]
For comparison, if you don't want to compile, here's what it looks like after this PR:

Screenshot_2020-05-17_10-22-01

Still not quite as bright as the on/off icon in its on state (because it's darkened by gtk when making it insensitive) but better, I think.

**Comment by parafin** [comment]
indeed it's better

**Comment by elstoc** [comment]
I wonder also if it might be better to have an always-off icon as well as an always-on icon, perhaps:

Screenshot_2020-05-17_12-13-34

As opposed to the current:

Screenshot_2020-05-17_12-15-02

**Comment by Nilvus** [comment]
An always-off doesn't make sense for me but I never use them, so as you want. There's no really always-off module, only modules that's applies only some specific (rare) cases. So, I would let them as they are. But hope the module will switch to on and off icons on the specific cases they will be used. We also have to think of potential future modules...

It's ok for other ones, your last proposal of always on module is ok. Your first one was not ok. Always on icon should be less brighter than on icon. But of course it's a good idea to have it brighter than off one.

**Comment by elstoc** [comment]
> There's no really always-off module, only modules that's applies only some specific (rare) cases

Agreed, same is mostly true of the always-on modules (except input and output profiles). Most of them are forced on or off based on whether it's a raw file or a jpeg.

**Comment by Nilvus** [comment]
> > There's no really always-off module, only modules that's applies only some specific (rare) cases
> 
> Agreed, same is mostly true of the always-on modules (except input and output profiles). Most of them are forced on or off based on whether it's a raw file or a jpeg.

I disagree for always-on modules as they are more used than "always-off" one. You forgot demosaic (it's not used in jpg but darktable is at first a raw). For me, we can't compare "always-off" and "always-on". First are rarely used, second are most of the times used. Quite a big difference.

**Comment by elstoc** [comment]
> You forgot demosaic (it's not used in jpg but darktable is at first a raw).

I used it in one of my examples. I still think we're confusing matters by using the terms 'always off' and 'always on'. Demosaic is 'always on' for a raw and 'always off' for a jpeg - I only use the terms because that's how the names are defined in the code.

Better to say 'forced on for this image' and 'forced off for this image'. There are no modules that are truly 'always off' and only two that are truly 'always on' and displayed in the left-hand-side of the screen as interactive iop modules (input/output profile).

So the icon examples in the OP (repeated below) are, in order 

- Off (can be switched on)
- Forced Off (cannot be switched on for this image)
- Forced On (cannot be switched off for this image)
- On (can be switched off)

Screenshot_2020-05-17_12-38-38

**Comment by TurboGit** [comment]
For me the always on/off buttons should be very easy to distinguish between other standard buttons. So I prefer the current version.

**Comment by elstoc** [comment]
If we're just worried about the color/shade, that can be tweaked later with CSS (I've made sure that the two buttons have different CSS names). I was just (initially) concerned with making sure gtk considered the 'enabled/disabled' modules as toggled/not-toggled respectively.

**Comment by parafin** [comment]
This GUI element serves 2 purposes:

1. it's a button to enable/disable the module
2. it's an indicator of whether module is enabled or disabled

For first purpose it should be distinguishable if button is (inter-)active or not. But it shouldn't hurt the second purpose. So I don't like current design - it looks like always-on module is actually off.

**Comment by Nilvus** [comment]
I agree with @parafin arguments here. But maybe the always-on icon remains a little bit too bright. So I would suggest just a compromise by reducing just a little bit the icon. By of course, let this icon brighter than actual current master.

**Comment by elstoc** [comment]
I haven't changed the brightness of the icon, just forced it to 'toggled-on' state in gtk. The colour can be changed in CSS.

**Comment by Nilvus** [comment]
Ok, so I will see that after this is merge and @Mark-64 work on icons.

**Comment by TurboGit** [comment]
Ok, so let's go for it. Thanks all !

**Comment by todd-prior** [comment]
Likely its been discussed but really to scan the list the icons are nice but I would bold the text of any module currently impacting the image as well...the button would further indicate a force or un-forced status...visually then no mistake......

**Comment by Nilvus** [comment]
@todd-prior: bold text is not good seeing (tested and confirm by another developer) but I've added a more white text on focus modules recently. It's less visible on grey theme by now and will check if I can improve it without breaking anything else. Contrast is a little bit harder on grey theme.

But if you want bold text, you can set it with CSS for your personal user one, so directly on preferences. For focus module, just change settings of this:
```
.dt_module_focus #iop-panel-label /* set focus mode */
{
  color: @plugin_focus_color;
}
```

Just replace color line by `font-weight: bold;`

**Comment by todd-prior** [comment]
Thanks for the tip…its fine for me….we highlight the buttons of the active modules vs inactive so why not the text or have them in a background (there is likely a way to tweak the css. I would like the active text to look as it does when you select it ie to have the filled background…to me that jumps out and then I would go bold when selected…)…I think there must be a solution to do it better…esp given the focus on accessibility in software design…not everyone can squint to decipher the buttons.. personally I think there is still a better way to make this completely obvious….the lack of contrast makes the buttons notoriously difficult to see at a glance….although I essentially know what modules fall in to what class so again its np but you have made me think about going away from the grey theme back to a darker one as I think the buttons are white there and so have more contrast…

**Comment by Nilvus** [comment]
Please make efforts on writing, and aerate text. It will be easier to read it and understand it. I just need 3 times to read and be sure to understand you correctly (english is not my native language).

> Thanks for the tip…its fine for me….we highlight the buttons of the active modules vs inactive so why not the text or have them in a background (there is likely a way to tweak the css).

Because we do it. You visibly don't read correctly my answer and I said that I will check how to improve that. But that will not be bold text.

> I would like the active text to look as it does when you select it ie to have the filled background…to me that jumps out and then I would go bold when selected…

On which selected text and filled background? I don't see any filled background there. An example would help and be more precise... Bold will not be a solution. It's not better, it's weird.

> I think there must be a solution to do it better…

Even when it's better, it's always possible to do better...

> esp given the focus on accessibility in software design…not everyone can squint to decipher the buttons.. 

Which focus given on accessibility? The UI is now there since more than a year and I don't see anyone (except you now, so one year after) complain about that for a button and label just changed few days ago and on a development version.
And of course, yes, we search to make people squint to decipher the buttons. That's my specific goal: make people blind... Such an usefulness (and quite accusative one) sentence. Please be more constructive.
So helping you with my last answer is the way to receive such answers... Good to learn!

> the lack of contrast makes the buttons notoriously difficult to see at a glance….

Which buttons? There's a lot on darktable? Do you talk on those buttons? Again, more constructive and precise things will help to improve the UI.

> although I essentially know what modules fall in to what class so again its np but you have made me think about going away from the grey theme back to a darker one as I think the buttons are white there and so have more contrast… 

And now, you interpret wrongly what I said. About grey theme, it's just harder to set good contrast between all elements, not that it's not possible. It's not theme or anything else but just range of colors. A black theme is a the opposite of the color range regardless of white, grey theme is near the middle... 
And grey theme have a lot of benefits to correctly process an image and avoid some optics illusions side-effects that we could have on a 

Last thing, if you reply by mail, think that answer are less readable on Github...

**Comment by Nilvus** [comment]
@todd-prior: just a little tweak on CSS. That's seems for me quite contrasted and not need to "squint to decipher":

image

**Comment by Nilvus** [comment]
Another proposal (near the icon focus highlight):

**Comment by todd-prior** [comment]
That looks nicer to me





Sent from Outlook Mobile

**Comment by todd-prior** [comment]
Your way too serious. Sorry for the brevity I was likely on my phone.. I will supply some examples to clarify. Honestly the comments were simplyeant my opinion which is worthless...





Sent from Outlook Mobile

**Comment by todd-prior** [comment]
This looks really nice to me but again it just my eyes...for me that looks really nice





Sent from Outlook Mobile

**Pull request merged**
