### PR TITLE
small fixes for spydercheckr and spydercheckr 24

### PR DESCRIPTION
**Pull request by Mark-64**
Small Lab values fixes, for Datacolor targets, according to the following source:
[https://www.datacolor.com/wp-content/uploads/2018/01/SpyderCheckr_Color_Data_V2.pdf](https://www.datacolor.com/wp-content/uploads/2018/01/SpyderCheckr_Color_Data_V2.pdf)

### CODE REVIEW

**Comment by TurboGit** [comment]
@Mark-64 : I see that your data color chart spec are from 2018. The one in dt are tagged 2016, maybe those are old charts ?

To be sure before changing I'd like @aurelienpierre confirmation on this.

**Comment by aurelienpierre** [comment]
Here is the reference I used for the current values : 
[SpyderCheckr Color Data.pdf](https://github.com/darktable-org/darktable/files/5952593/SpyderCheckr.Color.Data.pdf)
This file was retrieved circa 2015-2016, which is older than the link you provide (which file is called v2).

I suggest to duplicate the color checker and create pre/post-2018 versions, similarly to the X-Rite one.

**Review by aurelienpierre — CHANGES_REQUESTED** [review]
Please create another v2/post-2018 Spyder Checkr reference instead.

**Comment by paolodepetrillo** [comment]
I just compared both chart pdf's to the Darktable source, I'm not sure if this really is a case where there needs to be two different charts.

There is only one typo in the Darktable source where it does not match the 2016 PDF: patch 5H b* is 18.68 in both the 2016 and 2018 PDFs, but is 16.68 in colorchecker.h.

Other than that, all of the other differences are in either a* or b*, magnitude <= 0.05. It looks like some of them were just rounded to the nearest 0.1 in the 2016 PDF and not rounded in the 2018 PDF.

**Comment by TurboGit** [comment]
@paolodepetrillo : I agree with you looking more at both PDFs, in fact the Adobe coef are exactly the same so the Lab* one seems just to be a rounding.

**Comment by aurelienpierre** [comment]
> Other than that, all of the other differences are in either a* or b*, magnitude <= 0.05. It looks like some of them were just rounded to the nearest 0.1 in the 2016 PDF and not rounded in the 2018 PDF.

So why did they not round all the other values then ? Some values are given with 1 decimal, other with 2. My belief is they gave 1 decimal when the second was 0.

I'm not sure what they did with the RGB coeffs, but anyway spectrometers output Lab coordinates, not RGB so these are necessarily computed from Lab. But the fact that the PDF is called `*-V2.pdf` is concerning enough to me.

Let's be clear : there is no point in doing calibration on top of wrong reference values.

**Comment by paolodepetrillo** [comment]
I think the issue is actually the width of the spreadsheet column in the older pdf!
All of the rounded values are negative and < 10, so only those values of the form -xx.xx wouldn't fit in the narrow column without rounding off a digit.

**Comment by aurelienpierre** [comment]
No, the original file has values like -23.08 (4H) and the v2 also rounds some values to 1 digit, so I really don't think it's a problem of layout.

**Comment by Mark-64** [comment]
ok, I can create 2 versions, no pb.
Even if the difference is small, that doesn't hurt. And of course fix the typo

**Comment by Mark-64** [comment]
Done.
With my brand new  spydercheckr 24, there is a very small difference in calibration output coefficients, but no perceivable difference in the image

**Review by aurelienpierre — APPROVED** [review]

**Pull request merged**
