### PR TITLE
assign focus to center view when clicking on thumbtable

### LINKED ISSUE #5535: Lighttable (file manager) mode → Scrolling by keys
Linux x64, master snapshot:

It looks that scrolling by up and down keys was broken recently (no more than couple days). To reproduce it just click on random image in file manager mode and try using up/down keys to scroll. It does nothing.

### PR DESCRIPTION
**Pull request by elstoc**
Resolves #5535

### CODE REVIEW

**Comment by aurelienpierre** [comment]
Thanks !

**Comment by elstoc** [comment]
Do you mean ``// make sure any edition field loses the focus``? This comment is still appropriate.

**Comment by phweyland** [comment]
> Do you mean `// make sure any edition field loses the focus`? This comment is still appropriate.

Yes, it is not false. But the original code was already doing that, wasn't it ?
Your change directs keys to this specific window widget (and the scrolling bars).
BTW your change is twofold. set_focus -> grab_focus and dt_ui_main_window(darktable.gui->ui) -> dt_ui_center(darktable.gui->ui). 
I think that is the second one which solves #5535. I'm unsure about the first one, but that should be easy to verify.

**Comment by elstoc** [comment]
Possibly so, though there are quite a few that do the same thing and my understanding (based on the docs) is that set_focus is only available for the window as a whole (gtk_window_set_focus) and not for individual widgets. Indeed the gtk documentation for gtk_window_set_focus states "To set the focus to a particular widget in the toplevel, it is usually more convenient to use gtk_widget_grab_focus() instead of this function" suggesting they are equivalent in functionality

**Comment by phweyland** [comment]
Great. Thanks for the clarification. My initial comment seems to me still valid, but obviously it's an infinitesimal detail.

**Pull request merged**
