### PR TITLE
Add Spanish Translation 

### PR DESCRIPTION
**Pull request by EdgarLux**
Adding Spanish translation for version 2.6.x

### CODE REVIEW

**Comment by TurboGit** [comment]
Thanks!

**Comment by TurboGit** [comment]
In fact it was based on 2.6.1 branch. Can you do a PR for master? Thanks.

**Comment by EdgarLux** [comment]
Of course.

**Comment by TurboGit** [comment]
Thanks. Note that you should have only proposed a PR against the current master as the translations in master are copied as-is in the release branches. All strings in the 2.6.x branch are compatible with master. I have a script to do that before the release.

**Pull request merged**
