### PR TITLE
Color Balance: set different soft ranges for shadows midtones highlights

### PR DESCRIPTION
**Pull request by Mark-64**
With the aim to improve usability of Color Balance module and in reply to my own #5227 I propose this PR, where the soft range are differentiated per channel, instead of being all equal.

**lift / offset (shadows)**
factor: -5% -> +5% (instead of -50% -> +50%)
saturation: 0% -> 5% (instead of 0% -> 25%)
R/G/B: -0.05 -> +0.05 (instead of -0.5 -> +0.5)

**gamma / power (midtones)**
factor: -20% -> +20% (instead of -50% -> +50%)
saturation: 0% -> 20% (instead of 0% -> 25%)
R/G/B: -0.2 -> +0.2 (instead of -0.5 -> +0.5)

**gamma / power (highlights)**
factor: -50% -> +50% (instead of -50% -> +50%, unchanged)
saturation: 0% -> 50% (instead of 0% -> 25%)
R/G/B: -0.5 -> +0.5 (instead of -0.5 -> +0.5, unchanged)

The rationale is to have a span of control in each channel which perceptually produces a comparable change on the image and increase accuracy of setting, especially for shadows.
Yes the lift/gamma/gain method is less sensitive and needs less this change, but overall the usability looks pretty good to me with all methods.
Of course this is just a default soft range, you can always push it further if more adjustment power is needed.

### CODE REVIEW

**Comment by dterrahe** [comment]
If this gets merged first, I'll update 3ba47c7278d1b8f0d206a3778779df7117ca6055 with the changes.

**Comment by Nilvus** [comment]
I agree with those changes, except midtones factor that I would let it unchanged (or setting -40%/+40%)

**Comment by Mark-64** [comment]
We can tune the numbers, I used a logic shadows < midtones < highlights: the weaker the signal, the smaller the correction capability need to be. 
I used a shadows -> x4 -> midtones and midtones -> x2.5 highlights. for sure there are more scientific ways to do it.
With this I can adjust the shadows sliders concentrating on the effect on the image, rather that trying to move the mouse one pixel more or less.

**Comment by dterrahe** [comment]
So #5335 was merged first.. @Mark-64 please let me know if you want advice on how to fix the resulting merge conflicts.

**Comment by Mark-64** [comment]
Messed up with rebase, closing here.
I will open another PR

**Comment by dterrahe** [comment]
Why not force push? We've all been there!

**Comment by Mark-64** [comment]
I still have to lean egit in eclipse... :-(

**Pull request closed without merging**
