### PR TITLE
enhance code readability

### PR DESCRIPTION
**Pull request by rabauke**
My static code analysis tool indicated (falsely) some errors here and I also had some difficulties to understand the code. The revised version is technically equivalent to the former but more explicit and therefore more easy to understand.

### CODE REVIEW

**Comment by cryptomilk** [comment]
In those cases I normally use brackets.

`int *ip = &(lookup[row][col][1]);`

Which makes sure that the array element is referenced and makes it clearer to the reader.

**Comment by rabauke** [comment]
> Can you take @cryptomilk comment into account? Thanks.

@TurboGit This has been incorporated into my recent revision of this pull request.

**Comment by rabauke** [comment]
I think, it is safe to merge this now.

**Comment by TurboGit** [comment]
Ok, merging now. Thanks.

**Pull request merged**
