### PR TITLE
show selected shortcut action in treeview

### PR DESCRIPTION
**Pull request by dterrahe**
In the shortcuts dialog/preference tab, whenever a shortcut is selected in the bottom list, highlight the action it triggers (and its parents) in the top list of actions. Don't select it, because selecting an action causes the list of shortcuts to be filtered. 

To scroll to the action (expanding all parents if necessary) right click on the actions list.

This makes it somewhat easier to assign shortcuts to related actions without having to look them up.

Edit: taken @elstoc comments below into account

### CODE REVIEW

**Comment by elstoc** [comment]
Unless you can highlight the top entry in some way (without selecting) it just feels a bit random IMO, especially if the selected entry ends up scrolled to the middle of the screen. I kept searching around the top panel to try and find out why the screen was scrolled to that point.

**Comment by dterrahe** [comment]
Didn't notice your last edit, but implemented highlighting in bold the action and it's parents up the tree and scrolling to it, but _not_ expanding.

I'm leaning to, as you suggest, strip out the whole expanding/scrolling bit; feels like too much hassle to even document.

**Comment by dterrahe** [comment]
Rebased. @TurboGit As far as I'm concerned this is ready to merge.

Shows a highlight in the action list for the action corresponding to the currently selected shortcut and allows to expand and jump there (by right clicking) but otherwise no change to existing behavior so should not be controversial.

**Comment by dterrahe** [comment]
@TurboGit please let me know if you plan to consider this for merging at some point otherwise I'll close. Thanks!

**Review by TurboGit — APPROVED** [review]
Looks good, thanks! And sorry for the long delay, in fact I had forgotten about this one.

**Comment by dterrahe** [comment]
Thank you!

**Pull request merged**
