### PR TITLE
exif: special handling of Nikon F lenses on recent bodies

### LINKED ISSUE #10053: lens correction module cannot detect lens from EXIF data in RAW.NEF from Nikon z6
**Describe the bug/issue**
**lens correction module** cannot detect lens from EXIF data in RAW.NEF from Nikon z6

**To Reproduce**
1. Go to lighttable
2. Click on add to catalog
3. choose a NEF from Nikon z6
4. open picture in darktable
5. access lens correction module
6. camera found: Nikon, Z6
7. camera/lens not found... please select manually

**Expected behavior**
camera/lens found.
The same lens on a Nikon d5300 is found from the EXIF data correctly

**Platform**
Win10x64
Z6 firmware 3.31

* darktable version : latest release 3.6.0.1
* OS                : Win10 20H2 x64

**Additional context**
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

**Additional information**
_correctly detected lens from a RAW made on a d5300:
```
Filename - DSC_1542.NEF
ImageWidth - 160
ImageLength - 120
BitsPerSample - 8 8 8 
Compression - 1 (None)
PhotometricInterpretation - 2
Make - NIKON CORPORATION
Model - NIKON D5300
StripOffset - 176640
Orientation - Top left
SamplesPerPixel - 3
RowsPerStrip - 120
StripByteCount - 57600
XResolution - 300
YResolution - 300
PlanarConfiguration - 1
ResolutionUnit - Inch
Software - Ver.1.03
DateTime - 2021:07:05 09:27:29
ReferenceBlackWhite - 0
ExifOffset - 2544
DateTimeOriginal - 2021:07:05 09:27:29
ExposureTime - 1/350 seconds
FNumber - 9.50
ExposureProgram - Normal program
ISOSpeedRatings - 200
DateTimeOriginal - 2021:07:05 09:27:29
DateTimeDigitized - 2021:07:05 09:27:29
ExposureBiasValue - 0.00
MaxApertureValue - F 3.48
MeteringMode - Multi-segment
LightSource - Auto
Flash - Not fired
FocalLength - 18.00 mm
UserComment - 
SubsecTime - 80
SubsecTimeOriginal - 80
SubsecTimeDigitized - 80
SensingMethod - One-chip color area sensor
FileSource - DSC - Digital still camera
SceneType - A directly photographed image
CustomRendered - Normal process
ExposureMode - Auto
White Balance - Auto
DigitalZoomRatio - 1 x
FocalLengthIn35mmFilm - 27 mm
SceneCaptureType - Standard
GainControl - None
Contrast - Normal
Saturation - Normal
Sharpness - Hard
SubjectDistanceRange - Unknown

GPS information: - 
GPSVersionID - 2.3.0.0

Maker Note (Vendor): - 
Data version - 1120 (825307696)
ISO Setting - 200
Image Quality - RAW
White Balance - AUTO
Focus Mode - AF-A
Flash Setting - 
Flash Mode - 
White Balance Adjustment - 0
White Balance RB - 838
Exposure Difference - 0.0
Thumbnail IFD offset - 23954
Flash Compensation - 393472
ISO 2 - 200
Serial number - 2845530
Colorspace - Adobe RGB
Active D-Lighting - Extra High
Picture control - Version - 0100
Picture control - Name - VIVID
Picture control - Base - VIVID
Picture control - Adjust - Full Control
Picture control - Quick Adjust - Not available
Picture control - Sharpness - +8
Picture control - Contrast - Normal
Picture control - Brightness - Normal
Picture control - Saturation - +1
Picture control - Hue Adjustment - Normal
ISO 3 - 200
ISO Expansion - Off
Lens type - G VR
Lens - 18.00
Flash Used - Not fired
Shooting Mode - 33
Contrast Curve - I0
Noise Reduction - OFF
Lens info - 0204
Total pictures - 6620
Vari Program - Not defined
AF info 2 - version - 0100
Contrast Detect AF - Off
```

_same lens, undetected, EXIF in a RAW from a Z6:
```
Filename - 20210917_0001_100.NEF
ImageWidth - 160
ImageLength - 120
BitsPerSample - 8 8 8 
Compression - 1 (None)
PhotometricInterpretation - 2
Make - NIKON CORPORATION
Model - NIKON Z 6
StripOffset - 166812
Orientation - Top left
SamplesPerPixel - 3
RowsPerStrip - 120
StripByteCount - 57600
XResolution - 300
YResolution - 300
PlanarConfiguration - 1
ResolutionUnit - Inch
Software - Ver.03.31
DateTime - 2021:09:17 12:33:09
Artist - Eric DeLaRewonko
ReferenceBlackWhite - 0
Copyright - DeLaRewonko Photography
ExifOffset - 12916
DateTimeOriginal - 2021:09:17 12:33:09
ExposureTime - 1/250 seconds
FNumber - 5.60
ExposureProgram - Normal program
ISOSpeedRatings - 200
Recommended Exposure Index - 200
DateTimeOriginal - 2021:09:17 12:33:09
DateTimeDigitized - 2021:09:17 12:33:09
OffsetTime - -07:00
OffsetTimeOriginal - -07:00
OffsetTimeDigitized - -07:00
ExposureBiasValue - 0.00
MeteringMode - Multi-segment
LightSource - Auto
Flash - Not fired
FocalLength - 140.00 mm
UserComment - 
SubsecTime - 00
SubsecTimeOriginal - 00
SubsecTimeDigitized - 00
SensingMethod - One-chip color area sensor
FileSource - DSC - Digital still camera
SceneType - A directly photographed image
CustomRendered - Custom process
ExposureMode - Auto
White Balance - Auto
FocalLengthIn35mmFilm - 210 mm
SceneCaptureType - Standard
GainControl - None
Contrast - Normal
Saturation - Normal
Sharpness - Normal
SubjectDistanceRange - Unknown
Serial Number - 3037808
Lens Info - 18.00  140.00  3.50  5.60
Lens Make - 
Lens Model - 
Lens Serial Number - 

GPS information: - 
GPSVersionID - 2.3.0.0

Maker Note (Vendor): - 
Data version - 1120 (825307696)
Image Quality - RAW
White Balance - AUTO1
Focus Mode - FSHIFT
Flash Setting - 
Flash Mode - 
White Balance Adjustment - 0
White Balance RB - 994
Exposure Difference - 0.0
Thumbnail IFD offset - 62490
Serial number - 3037808
Colorspace - Adobe RGB
Active D-Lighting - Extra High
Picture control - Version - 0300
Picture control - Name - 0300AUTO
Picture control - Base - 
Picture control - Adjust - Default
Picture control - Quick Adjust - +-126
Picture control - Sharpness - Auto
Picture control - Contrast - Auto
Picture control - Brightness - Auto
Picture control - Saturation - Normal
Picture control - Hue Adjustment - +-127
ISO 3 - 200
ISO Expansion - Off
Lens type - G VR
Lens - 18.00
Flash Used - Not fired
Shooting Mode - 32
Contrast Curve - I0
Noise Reduction - OFF
Lens info - 0801
Total pictures - 18151
Vari Program - Not defined
AF info 2 - version - 0300
Contrast Detect AF - On
AF ImageWidth - 0
AF ImageHeight - 0
AF Area X-Position - 0
AF Area Y-Position - 0
AF AreaWidth - 0
AF AreaHeight - 0
```

### PR DESCRIPTION
**Pull request by kmilos**
Fixes #10053

### CODE REVIEW

**Comment by kmilos** [comment]
Actually, it's not just the LensIDNumber that identifies the F-mount lens, more fields ([all legacy ones that are used for lookup](https://exiftool.org/TagNames/Nikon.html#LensID)) need to be checked... or alternatively check if new LensID field (native Z lens) is equal to 0...

**Review by TurboGit — COMMENTED** [review]
Why the capitalization of the exif_lens ? Is that really only UI ?

**Comment by kmilos** [comment]
Pretty much, think so. Lensfun string matching case insensitive anyway...

**Review by TurboGit — APPROVED** [review]
Thanks !

**Pull request merged**
