### PR TITLE
Fixing #13120

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Can confirm the issue @kofa73 reported in #13120

Could track down the problem to bee deep in gaussian blur, to get into this i plainly added debugging messages all done via -d opencl.

So far i couldn't see the problem with the kernel. For me it seems the switching between 1/4 channels might be going wrong.

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
@TurboGit and @dterrahe At least the second commit fixes the dysfunctional gaussian cl code,  the reason was the different size of CLARG() macro parameter wrongfully passed to the kernel.

You might a) just cherrypick the problematic part in gaussian.c b) maybe introduce a better macro ???

**Comment by dterrahe** [comment]
> b) maybe introduce a better macro ???

CLARRAY would work here?

**Comment by jenshannoschwalm** [comment]
> CLARRAY would work here?

Nope. (i tested that and after `not working` i looked up the code.) Both macros take the sizeof parameter which is dt_aligned_pixel in this case, a 4float in cl speak. The problem is, for 1 channel we want to pass a float and for 4 channels a 4float. We might add a CLFLOATARRAY() macro ?

**Comment by jenshannoschwalm** [comment]
Latest commit introduces such a CLFLARRAY() macro tested and works for me...

**Comment by dterrahe** [comment]
what I meant is `CLARRAY(channels, &Labmax[0])`

**Comment by jenshannoschwalm** [comment]
> what I meant is `CLARRAY(channels, &Labmax[0])`

Stupid me :-) Go ahead ... I'll close this

**Comment by dterrahe** [comment]
> Stupid me :-)

I wouldn't say that; you're the one that tracked down this bug (that stupid me introduced; sorry!)

**Comment by jenshannoschwalm** [comment]
Unfortunately your suggestion doesn't work due to unary * vs float check in compiler. I don't see a better way than to define a CLFLARRAY here.

**Comment by dterrahe** [comment]
Don't know if I understand that. How about adding an explicit cast to `(float *)` as well? But by then a dedicated macro might be a cleaner solution.

**Comment by jenshannoschwalm** [comment]
Yes a cast works too. I would prefer the dedicated macro as suggested.

**Comment by dterrahe** [comment]
OK, only now looking at what really is going on here and that actually two distinct kernel modules (with different prototype) are being called. It might be more obvious to leave out the intermediate `kernel_gaussian_column` pointer and within an `if` call `kernel_gaussian_column_4c` with `CLARG(Labmin/max)` or `_1c` with `CLARG(Labmin/max[0])`. Or, but I have no idea what consequences this has on the cl side, merge those two kernels, taking the full Labmin/max and pass an additional variable "channels" explicitly.

But maybe this happens all over the place? In which case the CLFLARRAY approach _could_ be the least painful.

**Comment by dterrahe** [comment]
> The alternative could be explicit CL kernel calls depending on channels.

Is what I meant. I guess it depends on whether you think this is a good pattern that should be easily repeatable (then provide macros) or rather to be avoided (then restructure). Not for me to opine on, obviously, since I'm not a CL coder; I'm just a janitor.

**Comment by jenshannoschwalm** [comment]
I leave this decision for Pascal.
1. take this pr as is - adding some debugging info that has be helping ...
2. do another pr only with the new macro and usage
3. modify the gaussian code making it using the explicit kernel calls.

Just let me know ...

**Comment by TurboGit** [comment]
I'll check again tomorrow but I lean toward 1 for now. The new macro looks good and make it clear about what is being done to me.

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Pull request merged**
