### PR TITLE
import: in filechooser, show folders only

### PR DESCRIPTION
**Pull request by elstoc**
Closes #8517

### CODE REVIEW

**Comment by elstoc** [comment]
If this works (and people are happy with it) there are a bunch of other places we can put this too

**Comment by Nilvus** [comment]
> If this works (and people are happy with it) there are a bunch of other places we can put this too

Disturbing at first when you have selected last folder and nothing the view is empty but it works. Probably better but would help to have other feedback here. The real good way would be to have the possibility to not have hover effect in disabled items but as it's not possible, that way seems to be the best remaining one.

In which other places would you see that?

**Comment by elstoc** [comment]
> Disturbing at first when you have selected last folder and nothing the view is empty but it works

Yes that was the only thing I thought. I wondered if we could make the dialog smaller horizontally to make it clear that it's a non-standard dialog. Most 'folder selection' dialogs I've seen are taller than they are wide.

The ones I can think of are

- copy/move images
- choosing a moved folder in collect
- style export
- image export
- preferences/preset export
- preferences/3d lut folder

**Comment by elstoc** [comment]
It has been mentioned that the function I'm relying upon (`gtk_file_filter_add_custom`) is removed in Gtk4 and _may_ be deprecated in a future version of Gtk3. I have checked on the Gtk gitlab repo and I can't find anything suggesting it will be removed soon but thought it worth mentioning for if/when we intend to move to Gtk4. BTW this function is also already used in `geotagging.c`.

**Comment by phweyland** [comment]
> BTW this function is also already used in `geotagging.c`.

In geotagging it seems it should be easy to remove it, as it tests file extension and mime, which are both standard filters.

**Comment by TurboGit** [comment]
I'm not fond of this as browsing the directories to find the right to import it is sometime important to see the files in it with the timestamp and the name. Also it is goof to see that there is or not XMP in the folder. All in all, I prefer the view of files. Would be good to have more feedback on this one.

**Comment by EC1000** [comment]
> I'm not fond of this as browsing the directories to find the right to import it is sometime important to see the files in it with the timestamp and the name. Also it is goof to see that there is or not XMP in the folder. All in all, I prefer the view of files. 

Same opinion here

**Pull request closed without merging**
