### PR TITLE
Pentax k1

### PR DESCRIPTION
**Pull request by mazhe**
Hello, I'd like to submit for review/inclusion some patches related to work I did to add support for the Pentax K-1 camera.

Mostly, it consists of :
* adding a color matrix (taken from DNG raw file)
* updates in the noise tools (using sh instead of bash, allowing to use different exif tags to get iso levels > 65536)

Thanks in advance,

### CODE REVIEW

**Comment by LebedevRI** [comment]
@mazhe i assume this still is an issue. Let's try this again...

I guess this is related to https://redmine.darktable.org/issues/11022

Was the sample sent to rawspamples.ch too?

**Comment by mazhe** [comment]
In fact, I closed the request (silently) to take time to understand a few issues (I was getting black images from PEF format, DNG was fine).

I'll send two samples to rawsamples.ch indeed, that could be helpful.

I still have noise profiles ready, that I did not found to be faulty in my everyday usage, but I did not formally test every iso setting yet...

**Comment by mazhe** [comment]
Ok, I have cleared up my issue with black PEF : it seems to be a regression in rawspeed when build with clang 3.8 and -O3, not something coming from this patchset. I'll investigate this later.

Samples were sent to  rawsamples.ch (both PEF and DNG).

I still have to extract whitebalance presets and check the noiseprofiles.

**Comment by LebedevRI** [comment]
> Ok, I have cleared up my issue with black PEF

What exactly was the issue?
There is some kind of race condition when entering darkroom when image is not loaded yet, so darkroom opens, but the image is displayed black.
Re-entering darkroom fixes that.

**Comment by LebedevRI** [comment]
The only questionable thing here is crop, so please take a fully clipped (!) image - fully open aperture, iso100, 30 sec exposure, and upload it somewhere.

**Comment by mazhe** [comment]
Thanks for the info about the race condition, I'll check that a bit later.

I'll do the sample picture when I'm back home (the crop was obtained from information in the DNG if I remember, and set because there was garbage lines at the begining of the PEF pictures).

**Comment by mazhe** [comment]
Here are the samples, PEF & DNG:
- http://dl.free.fr/iommjlg1L
- http://dl.free.fr/im9v4GQA8

**Comment by LebedevRI** [comment]
Can you upload that to some sane location, like dropbox?
That one is blocked for me, and i do not understand how to download from
there.

**Comment by mazhe** [comment]
gdrive should serve you better:

- https://drive.google.com/open?id=0B0J6-mibfIUEVjdjMXZuZnhZUTQ
- https://drive.google.com/open?id=0B0J6-mibfIUEZlBSZ1kzSFlvNEk

**Comment by LebedevRI** [comment]
Thanks, merged manually.
Please do send a sample to rawsamples.ch

**Comment by LebedevRI** [comment]
@mazhe Hi!
Could you please help us with raw samples for this camera?

There are total of 4 samples. The camera needs to be stable (tripod), and the scene needs to be as static as possible (so some daylight nature landscape would be best):
* PEF, pixelshift OFF
* DNG, pixelshift OFF
* PEF, pixelshift ON (motion correction either ON or OFF)
* DNG, pixelshift ON (motion correction either OFF or ON)

**Comment by LebedevRI** [comment]
@mazhe Hi!
Could you please help us with raw samples for this camera for https://raw.pixls.us/?

There are total of 6 samples. The camera needs to be stable (tripod), and the scene needs to be as static as possible (so some daylight nature landscape would be best), and all the samples **must** have the same content/scene:

* 35mm Full-Frame:
  * PEF, pixelshift OFF
  * DNG, pixelshift OFF
  * PEF, pixelshift ON (motion correction either ON or OFF)
  * DNG, pixelshift ON (motion correction either OFF or ON)
* APS-C crop
  * PEF, pixelshift OFF
  * DNG, pixelshift OFF

**Comment by LebedevRI** [comment]
@mazhe Hi!
Could you please help us with raw samples for this camera for https://raw.pixls.us/?

There are total of 6 samples. The camera needs to be stable (tripod), and the scene needs to be as static as possible (so some daylight nature landscape would be best), and all the samples **must** have the same content/scene:

* 35mm Full-Frame:
  * pixelshift OFF
    * PEF
    * DNG
  * pixelshift ON
    (i.e. one with motion correction and one without)
    * PEF (motion correction either ON or OFF)
    * DNG (motion correction either OFF or ON)
* APS-C crop, pixelshift OFF
  * PEF
  * DNG

**Comment by mazhe** [comment]
Yes, I can and will do ASAP (tried from my appartment, but view is a bit trouble and light is changing too much due to cloud moving in and out).

I'll also put some 1:1 crop raw for good measure.

(I'm also working on providing better noise profiles, but high ISOs are really hard to calibrate... I've been working on smoothing the data with interpolation with good results in my eye...)

**Comment by LebedevRI** [comment]
So far we've failed to find any 645D/645Z owner willing to contribute the samples.
Perhaps someone with K1 could still help.

**Comment by mazhe** [comment]
Sorry, I was a bit overwhelmed by events last weeks (moving to another town, new job), I'll get back on this ASAP

**Comment by mazhe** [comment]
Ok, sorry for the delay, but at least a bright and nice day. I took PEF/DNG with all FF/APSC and PS variations.

There are already entries for the K1, but not all variations, should I fill or overwrite all images?

**Comment by LebedevRI** [comment]
(In the mean time, the 645[zd] samples were received)

> There are already entries for the K1

Just upload *all* of those your shot.

**Comment by glsarto** [comment]
I still read that K1 files are needed... is that correct?
I posted the RAWs from my K1-II.

**Comment by kmilos** [comment]
> I still read that K1 files are needed... is that correct?

Where? Have you checked RPU?

Screenshot_20231225_200700

**Pull request closed without merging**
