### PR TITLE
select area color picker with right-click

### LINKED ISSUE #7525: Remove the need for ctrl click to create an area using the color picker....
Just a comment and I am not sure that others will agree or feel it is worth the effort. I suspect it was an attempt to simplify the color picker by removing the second selection picker and forcing the user to use ctrl to create an area however I just find this a more clumsy way to select that option. I have to look away and find the ctrl key and then look back and click the small picker icon. 

Would it be hard to a) insert a preference setting that would allow area as the default and not point. Essentially if you don't draw anything after you click you would have a point anyway. or b) recode so that after selecting the picker within the color picker module that you would single click on the image to leave a point or click hold and begin to draw to create an area selection??  Either of these methods would be easier IMO than having to introduce a ctrl click to create an area. Even using the old way you didn't have to slow down just select which picker mode from the small picker icon and go....its a small thing but I think it gets used a lot certainly I do and so using it in one of the two ways above that I suggested would seem more fluid to me....again its coming from my viewpoint and others may disagree.......

### PR DESCRIPTION
**Pull request by dterrahe**
Also allow right click on a color picker button to select area mode (in additon to ctrl-click). Does not work on bauhaus quads.

I have not updated tooltips all over the place, just in the lib, because it is a non-essential feature and those who like it can probably extrapolate.

fixes #7525

### CODE REVIEW

**Comment by TurboGit** [comment]
Shouldn't we also deactivate the color-picker with a right-click when already activated ? It feels strange to have to right-click to activate the color picker in area mode and have to do a click to disable color picker.

**Comment by dterrahe** [comment]
@TurboGit thanks for the reminder to fix this as well.

I changed the behavior to allow toggling between modes directly and to switch on/off with same button. Let me know if you disagree that this is the most logical.

ctrl or right click when not in area mode (off or point) switches to area mode. If in area mode, switch off.
just left click if not in point mode (off or area) switch to point mode. If in point mode, switch off.

Previously, if you want to switch from area to point, you had to switch off first, but not in the other direction. Now you can toggle.

**Review by TurboGit — APPROVED** [review]
All good to me now, thanks !

**Comment by todd-prior** [comment]
Thanks for considering this. I suspect it was a lot of work. It is nice not to have to go hunting for keystrokes to complete a task....

**Pull request merged**
