### PR TITLE
fix rating discard issue

### LINKED ISSUE #3971: switch back to 2.6.x order of pixelpipe
**Is your feature request related to a problem? Please describe.**
In  #3761 i have describe the problem with the new (3.0) order of the using vignette and splittoning.
Now I have the next problem:
I use the module monochrome to convert a picture into black and white. If I use a red or green filter the image gets darker. So I use the module levels to compensate the loss of light. In version 2.6.x it was executed **after** the monochrome module. Now with 3.0.0 it is run before, which leads to some problems. 
darktable_113
darktable_114
darktable_115
darktable_116

All other modules for tonecurve manipulation are also executed before monochrome. The only solution is moving the module in the pixelpipe and this has be done after each usage.

**Describe the solution you'd like**
I have the impression that the arrangement of the pixelpipe in version 2.6.x was very well thought out. I never missed the order change function.
In 3.0.0 more theoretical aspects (monochrome is a creative module) were considered. This is not good.

Is it possible to use the Version 2.6.x order of the pixelpipe in version 3.0.0 by default? Perhaps via an option like 'auto-appy sharpen' .

### LINKED ISSUE #3972: Reject tag does not toggle anymore as it's only rejecting.
**Describe the bug**
Hitting the R keystroke or the dedicated icon on a hovered/selected picture will first mark it as discarded with the message "rejecting 1 image". However hitting the R keystroke once more (or using the dedicated icon) will not revert that state, and will also display the same message. 
Version 3.0.0 is fine with that (and does not display any message whatsoever).

**To Reproduce**
1. Go to the lighttable
2. Click on any picture you like (or dislike in this case)
3. Hit the R keystroke or use the dedicated icon to mark it as discarded
4. See that it's been marked correctly
5. Hit R once more or use the dedicated icon
6. See that the image is still marked as discarded

**Expected behavior**
The discarded state should be a toggle or a flag, not an irreversible state.

**Platform (please complete the following information):**
 - Darktable Version: 3.1.0+263 - 349fe88b419bbc7d87ee50382e8edac69a8a553f
 - OS: MacOS 10.15
 - OpenCL activated

**Additional context**
3.0.0 does not exhibit this behaviour and does not display any message upon mark an image as discarded.

### PR DESCRIPTION
**Pull request by phweyland**
Should fix #3972 .
Note: on 3.0.0 the message was only displayed for selection. Now it's displayed both when hovering or for selection, which is more consistent.
Note2: Discard symbol is absent from the bottom view:
image
Is that intentional ?

### CODE REVIEW

**Comment by ptilopteri** [comment]
does this restore the toggle effect of the "r" key or is it a "work-a-round"

**Comment by phweyland** [comment]
> does this restore the toggle effect of the "r" key

should restore it.

**Comment by ptilopteri** [comment]
> > does this restore the toggle effect of the "r" key
> 
> should restore it.

tks, part of my remembered keys

**Comment by TurboGit** [comment]
> Note: on 3.0.0 the message was only displayed for selection. Now it's displayed both when hovering or for selection, which is more consistent.

I don't feel this is right. For selection it makes sense, but when hovering on a single picture it is clear that it is applied or not the start or color label changes. In this case the message is more noise than necessary to me.

**Comment by phweyland** [comment]
> > Note: on 3.0.0 the message was only displayed for selection. Now it's displayed both when hovering or for selection, which is more consistent.
> 
> I don't feel this is right. For selection it makes sense, but when hovering on a single picture it is clear that it is applied or not the start or color label changes. In this case the message is more noise than necessary to me.

Not sure ... Applying to grouped images it make sense to display the number of modified images.

**Comment by TurboGit** [comment]
So maybe just kill the message if the number of image is 1 ? I really find it too disturbing to have this message pop-up all the time! Maybe just me... Let's see what others think.

**Comment by phweyland** [comment]
> So maybe just kill the message if the number of image is 1 ?

Agreed. I do that.

**Comment by phweyland** [comment]
BTW, only rating and geotags issue messages. Color labels, metadata and tagging don't.

**Comment by TurboGit** [comment]
Thanks, looks good now.

**Pull request merged**
