### PR TITLE
[presets] add option to hide built-in presets of iops

### LINKED ISSUE #1994: Capability to disable/hide hard-coded presets
**Is your feature request related to a problem? Please describe.**
Hard-coded presets cannot be removed. Lately, a lot of such presets have been added to the master branch that make the presets list of some iops lengthy, specially when someone has also a bunch of personal presets. I personally prefer my own presets and almost never use those hard-coded ones.

**Describe the solution you'd like**
Add capability to hide/disable hard-coded presets. I think the presets section of preferences is a good place for this feature, so that a user can selectively hide the presets (s)he doesn't use.

### PR DESCRIPTION
**Pull request by johnny-bit**
Adds capability to hide/disable hard-coded presets. The option is shown in darkroom section since it hides only presets for darkroom modules :)

This fixes #1994

@msdm - I hope this would work for you :)

### CODE REVIEW

**Comment by TurboGit** [comment]
Well I'm not really convinced by this... Another option for this? What's wrong we default presets? Anyway let's see what others think about this.

**Comment by johnny-bit** [comment]
Well, the request in #1994 is a request, @msdm and I thik @junkyardsparkle seemed interested in it... I think this option could be hidden so it doesn't spam the preferences win... And the only thing "wrong" with default presets expressed in #1994 was the list is long/too long and makes it hard to reach user's presets.

**Comment by TurboGit** [comment]
> the list is long/too long and makes it hard to reach user's presets.

So what about add the user's presets first ? Also it could be nice to have a separator between user and system presets and also before the actions like (store new preset, favorite...). What do you think?

**Comment by johnny-bit** [comment]
Separators would be OK imo, sorting user presets firs... Dunno really, because it's subjective - user's presets are now close to actions with them and more connected... Would have to be an option IMO :/ but obviously both sorting and hiding could be hidden options. I wouldn't mind having separators in menu though...

**Comment by TurboGit** [comment]
Ok, let's try separators between user & system presets and before the actions at the bottom. I think this would be a nice usability fix and will continue our GUI revamp.

**Comment by johnny-bit** [comment]
I found out something interesting: separators are hidden :) this necessitates css change if you want to show separators :)

**Comment by junkyardsparkle** [comment]
Some visual separation seems like a good idea in any case, especially for the actions (the way the presets run right into those has always been a little bit weird). Sorting is complicated because the lists don't always "drop down", depending on the screen position. The only other thing I can think of would be allowing for nested submenus, which some users might find useful for organization in general... but I have no idea how difficult GTK3 would make this.

**Comment by johnny-bit** [comment]
Submenus? It's possible and not "too bad" but how to reliably organize it is totally different problem.

as for separators - @Nilvus - if you have time, can you look into css setup for separator? currently it's disabled/hidden everywhere, but a small item with padding wouldn't be too bad, would it?

**Comment by junkyardsparkle** [comment]
If there's a strong push against separators for whatever reason, then a subtle distinction such as a slightly lighter background color might be enough (or better than nothing, at least).

**Comment by TurboGit** [comment]
In fact separators are implemented but not visible, to have them:

```
menu separator 
{
background: @selected_bg_color;
padding: 1px;
}
```

@Nilvus : can you validate this CSS snippet ? TIA.

**Comment by johnny-bit** [comment]
tbh after playing with this - I'm not so fond of separators in form of light line in menu... or a very visible line... i tried following and it imo creates nice visual separation without going overboard:

```css
/* Separator */
menu separator 
{
padding: 1.5px 0px;
}
```

**Comment by junkyardsparkle** [comment]
This is my preference, after trying a few things in elegant-dark theme:

menu separator 
{
  padding: 0.1em;
  background-color: @bauhaus_indicator_border;
}

I'm assuming that this color is defined in an equally subtle way in the other themes, but haven't checked... and I guess it makes more sense for it to be scaled to text rather than hardcoded pixels? Anyway, thanks for pointing out that the separators were actually there! :-)

**Comment by TurboGit** [comment]
Thanks for all contributions on the CSS, @Nilvus will have the last word :)

**Comment by Nilvus** [comment]
I don't see any separators with CSS added between users and built-in presets. Something missing in code?

I have tested all proposals and the best one is the last one by @junkyardsparkle I think. I just improve it as I prefer really thin separators.

Here's my proposal:

```
menu separator 
{
  margin-left: 2em;
  margin-right: 2em;
  margin-top: 0.6em;
  margin-bottom: 0.3em;
  padding-top: 0.05em;
  background-color: @bauhaus_indicator_border;
}
```

And what it's look like (with the issue about no separator between my user preset "GX8..." and built-in ones):

**Comment by Nilvus** [comment]
> EDIT: I found `@bauhaus_indicator_border` to be visible in the other themes, but very subtle in some cases. :-)

Too subtle. Or need, to include in shade() and 1.4 for darker themes. Better if possible to have one ok in all themes. And selected is near bauhaus indicator color.

**Comment by TurboGit** [comment]
> I don't see any separators with CSS added between users and built-in presets. Something missing in code?

It is not there, I will certainly work on that after this PR except if done by @johnny-bit .

@johnny-bit : can you rework this PR with @Nilvus proposal based on @junkyardsparkle one?

**Comment by Nilvus** [comment]
@johnny-bit: just a little update on CSS to have better vertical alignement. And allow to simplify the code:

```
menu separator 
{
  margin: 0.6em 2em;
  padding-bottom: 1px;
  background-color: @selected_bg_color;
}
```

**Comment by johnny-bit** [comment]
Done. If it's to everybody's linking? :)

**Comment by TurboGit** [comment]
That's really really nice... Yes a very nice polishing of this preset menu. At the same time we also get the separator in the multi-instance menu. Thanks to all involved in this PR!

**Comment by junkyardsparkle** [comment]
Looks great, thanks for the work!

**Comment by msdm** [comment]
@johnny-bit, sorry for the late response, and thanks a lot for implementing this. Actually I had a different approach in mind to have finer control over built-in presets. It would be handy to be able to hide individual presets from the presets group in the preferences (maybe by adding a column of show/hide checkbox before the name column). This is because I do use some of the built-in presets in regular-basis.

**Comment by johnny-bit** [comment]
Recent change from @AlicVB introduced very finegrained selection of presets in favourite modules presets menu, which alows one to build that list from scratch. Showing/hiding built-in presets in module presets menu would require additional sql magic I wasn't (and still am not) comfortable introducing due to how built-in preset are handled in db (they are re-created on every start afaik)

**Comment by junkyardsparkle** [comment]
I get around this by simply making user presets from the few built-ins that I sometimes use. Maybe there could be added a quick and simple method for doing this.

**Pull request merged**
