### PR TITLE
import: option to use exif date/time

### PR DESCRIPTION
**Pull request by quovadit**
Adds the option to show exif date/time instead of modified date/time in import dialog.

See discussion in [8372](https://github.com/darktable-org/darktable/pull/8372#issuecomment-796938380)

### CODE REVIEW

**Comment by wpferguson** [comment]
@quovadit did you do any comparison timings to see just how big a performance hit this is?

**Comment by quovadit** [comment]
211 images took 14 seconds, so 1000 would be over a minute

It's slow, but I have the same issue with 'recursive' (e.g. if i click on the top folder of my NAS with 'recursive' checked)

**Comment by quovadit** [comment]
I know that performance is not perfect with this feature, but I think it would be great to offer this option to the user.

Without it you still need a third party app to rename images from different cameras in a chronological order.

Is there a chance that this PR gets merged, or is there a way to implement it as a lua-script?

**Comment by Nilvus** [comment]
I agree that this is a good option but not with such slowdown. Difference is not small!

**Comment by wpferguson** [comment]
> Is there a chance that this PR gets merged, or is there a way to implement it as a lua-script?

There is already a rename script that lets you rename with variable substitution.  Using that, you could sort your images by capture time, then select them and rename them using the script.  The rename changes the name in the database without affecting the raw files, so their names will remain unchanged.  If there is some feature that the rename script doesn't provide, then changes could be made.

**Comment by quovadit** [comment]
Renaming files after import would be a very good alternative to this PR!
This way there would not be any performance-issues, and you could even correct date/time before renaming.

Unfortunately I did not find the mentioned lua-script, and I failed using the dt_image_rename function (see [#2247](https://github.com/darktable-org/darktable/issues/2247#issuecomment-968348849))

**Comment by quovadit** [comment]
thanks to the lua-script by @wpferguson (#2247) this PR is not necessary anymore, so I'm closing it

**Pull request closed without merging**
