### PR TITLE
RMB+scroll to use dt_dev_jump_image

### PR DESCRIPTION
**Pull request by esq4**
Solution for _[FR] image navigation by mouse_ #9662

### CODE REVIEW

**Comment by esq4** [comment]
https://github.com/darktable-org/darktable/pull/9891#issuecomment-907681465

> Just a few thoughts:
> 
> button pressed / released are called for each individual button you press or release. Your code doesn't really deal with sequences of buttons being pressed/released. For example, pressing right and left button, then releasing left would reset _button_pressed even though you still have the right one pressed.
> 
> GdkEventScroll contains a state field, which should have GDK_BUTTON3_MASK set if the right mouse button is pressed while scrolling. So you probably don't need to do any of the bookkeeping of which buttons are pressed/released anyway.
> 
> dt_view_manager_scrolled already receives most of this state variable, so you may not need to add any parameters to it either, except that only the first 8 bits are passed through, which filters out GDK_BUTTON3_MASK, so you would have to change `event->state & 0xf` into something more suitable. I can't immediately think of anything that would break if you did this, but some arbitrary bits might come through if you're not careful that could cause matches to fail.
> 
> So it looks like you might be able to do this in 6 lines, if you use:
> 
> ```
>     if(state & GDK_BUTTON3_MASK)
>     {
>       dt_dev_jump_image(dev, up ? -1 :  1, TRUE);
>       return;
>     }
> ```
> 
> I have not tested this! It may not work for whatever reason...

Unfortunately, the _state_ does not contain useful information about the buttons. It is always 0 (according to my observations)

**Comment by dterrahe** [comment]
> Unfortunately, the _state_ does not contain useful information about the buttons. It is always 0 (according to my observations)

You are right! Maybe they only get set in the button press/release events. That is very unfortunate indeed.

I believe this does what you want with fewer changes:
```
  if(dt_key_modifier_state() & GDK_BUTTON3_MASK)
  {
    dt_dev_jump_image(dev, up ? -1 :  1, TRUE);
    return;
  }
```
It works for me (but would have to be checked for cross-platform compatibility.

**Comment by esq4** [comment]
I tried it. The result is the same, only a value of _dt_key_modifier_state()_ equal to 16.

**Comment by dterrahe** [comment]
> I tried it. The result is the same, only a value of _dt_key_modifier_state()_ equal to 16.

On which platform is that? For me on Debian with xorg I _do_ get GDK_BUTTON3_MASK (=1024) from dt_key_modifier_state.

If it really is necessary to track button presses and releases yourself, to support other platforms, I would still really prefer to keep these changes as localised as possible. Your patch touches 5 files when this is really only useful/used in darkroom (and probably for a very select group of users). So I would suggest storing the button state in the button_pressed/button_released methods in darkroom.c itself.  That would make it unnecessary to change the definition of `scrolled` to pass the extra parameter around and make changes in several files.

**Comment by dterrahe** [comment]
I also wanted to point out that right click in darkroom is already used, at least, to reset an area color picker to _full image_.

So you could get unwanted interactions there; right-click resets picker and changes slider and then scroll moves to next image before you see the effect of that change (that still did get saved in the image).

**Comment by esq4** [comment]
> On which platform is that? For me on Debian with xorg I _do_ get GDK_BUTTON3_MASK (=1024) from dt_key_modifier_state.

Hmm... It seems that it was a joke of the debugger. It work fine when I removed the breakpoints. 


> I also wanted to point out that right click in darkroom is already used, at least, to reset an area color picker to _full image_.

But this is already a problem...

**Comment by esq4** [comment]
@dterrahe Maybe there is a ready method to filter the "color picker" in the procedure "scrolled"?

**Comment by dterrahe** [comment]
@esq4 let me be honest with you; I don't particularly like this feature. Imho it doesn't fit in with the meanings normal assigned to RMB clicks and is likely to cause conflicts. I pointed out before that mask editing responds to RMB clicks and now that color pickers do. However if you find a clean way to avoid conflicts and not cause unpredictable or unexpected behavior (where a feature _only_ works under very specific conditions, which might lead people to file bug reports because they think it is broken and cause others to spend a lot of time debugging/reverse engineering) then I guess I wouldn't object to it being merged.

My other main interest here is to avoid something getting merged that significantly complicates the code and makes it hard to maintain or make changes or add other, more useful to more users, features in feature without breaking stuff. So apologies if I'm not being _helpful_, but only pointing out problems. I'm afraid it is up to you to find satisfactory solutions to those problems and there is no guarantee that they exist or that you can convince others that they are worth it. In direct answer to your question; I'm not aware of a reliable way to detect conflicts with color pickers (or masks, or other iop modules using right click) in the scrolled method and I have no interest at this point to dig in deeper and find out.

Sorry.

**Comment by elstoc** [comment]
I have to agree. I'm not a fan of this idea either.

**Comment by grubernd** [comment]
-1

Way too specialized, does not work (well) with touchpads, touchscreens, graphic tablets or any other interface device.

My suggestion would be: get a decent mouse with extra buttons and assign hotkeys.

**Comment by esq4** [comment]
> @esq4 let me be honest with you; I don't particularly like this feature. Imho it doesn't fit in with the meanings normal assigned to RMB clicks and is likely to cause conflicts. I pointed out before that mask editing responds to RMB clicks and now that color pickers do. However if you find a clean way to avoid conflicts and not cause unpredictable or unexpected behavior (where a feature _only_ works under very specific conditions, which might lead people to file bug reports because they think it is broken and cause others to spend a lot of time debugging/reverse engineering) then I guess I wouldn't object to it being merged.
> 
> My other main interest here is to avoid something getting merged that significantly complicates the code and makes it hard to maintain or make changes or add other, more useful to more users, features in feature without breaking stuff. So apologies if I'm not being _helpful_, but only pointing out problems. I'm afraid it is up to you to find satisfactory solutions to those problems and there is no guarantee that they exist or that you can convince others that they are worth it. In direct answer to your question; I'm not aware of a reliable way to detect conflicts with color pickers (or masks, or other iop modules using right click) in the scrolled method and I have no interest at this point to dig in deeper and find out.
> 
> Sorry.

It seems to me that with your help I have found a simple solution. 

Because the change affects only one procedure in one module, and the selected check is already being used in the same module to create an exception in the processing of mouse clicks, I do not see any problems with the development of the code in the future.

**Comment by TurboGit** [comment]
So following last comment I'm closing this PR.

**Comment by esq4** [comment]
@TurboGit  Explain, please, what did you dislike so much in the last comment?

**Comment by TurboGit** [comment]
@esq4 : Nothing, sorry for not being clear. But to me reading the last comment I thought that this won't be pursued.

**Pull request closed without merging**
