### PR TITLE
Don't call __builtin_cpu_supports on OSX.

### PR DESCRIPTION
**Pull request by pope**
Add an exclusion condition to calling `__builtin_cpu_supports` for OSX. clang-3.[78] from macports claims that `__has_builtin(__builtin_cpu_supports)` is true and will compile; however,
when linking the darktable library, I see the following error:

    Undefined symbols for architecture x86_64:
      "___cpu_model", referenced from:
          _dt_init in darktable.c.o
    ld: symbol(s) not found for architecture x86_64

By excluding this and using the fallback, DT can then be built with clang-mp-3.7 or clang-mp-3.8, and OpenMP will work for C and C++. As a bonus, this method doesn't require modifications to `/opt/local/var/macports/macports.conf` as per the building instructions in `packaging/macosx/BUILD.txt`. If someone wants to test this and is using macports, add this line to `/opt/local/etc/macports/variants.conf`:

    +ld64_xcode +openmp +no_gnome +no_x11 +quartz -x11 -gnome

Make the build directory and from the build directory type:

    CC=clang-mp-3.7 CXX=clang++-mp-3.7 cmake ..

### CODE REVIEW

**Comment by LebedevRI** [comment]
BTW, have you reported this upstream (probably to llvm)?
What do they say?
This is most likely the same as with FreeBSD, though.

**Comment by parafin** [comment]
What about clang from Xcode? Does it support __builtin_cpu_supports or __has_builtin(__builtin_cpu_supports) is false there?
Wouldn't it make more sense to guard against compiler version and not platform? To me current PR looks a little bit too generic (same with FreeBSD probably). On the other hand this check is probably pointless on OS X, since I guess all Apple hardware supports SSE3.

**Comment by pope** [comment]
@LebedevRI - I have not reported this upstream. Let me do that.

@parafin - Xcode's clang returns false for __has_builtin(__builtin_cpu_supports). You're probably right about doing this check. I would need to get other versions of clang to try to make sure it's not borked across the board. I also like you're idea of just skipping this check if __i386__ and __x86_64__ and __APPLE__. Which one do you dig the most?

Lastly, I know the modifications in macports.conf are for backwards compatibility. With this setup, the earliest version I was able to compile with was 10.9 (without digging in much more). But I'm not doing releases :). For me, this is nice because I don't need to make the modifications because I use macports for more than just this. I also want to be able to use OpenMP. GCC49 didn't work for me because it wants all of the libraries compiled with libstdc++ and not libc++ (hence the cxx_stdlib settings to make that work). So I don't see this as a replacement, but a complement to the existing build instructions at the cost of supporting fewer OS versions.

**Comment by parafin** [comment]
I like compiler check better because it's more to the point - #ifdef is needed because of compiler bug, not because we just decided to skip the check on OS X. Also let's not forget about Hackintoshes - there are people running OS X on non-standard hardware even with CPUs that don't support all the necessary features.

**Comment by pope** [comment]
Just got done testing clang-3.4, clang-3.5, and clang-3.6. All of those return false for `__has_builtin(__builtin_cpu_supports)`. So I'm not sure if we're going to add much by checking for version since none of them support. And we would only want to check the version once it is supported.

And yeah, this is the same problem that https://github.com/darktable-org/darktable/commit/081bc5823870918160fdd93d0157d56263add7d5 tried to solve. It's all donkus.

**Comment by pope** [comment]
LLVM bug: https://llvm.org/bugs/show_bug.cgi?id=25510

**Comment by parafin** [comment]
By compiler version I didn't necessary mean specific clang version, it may as well be as simple as gcc vs clang. If latest clang is 3.8 and it still doesn't support this feature, then maybe just check for clang with no specific version.

**Comment by pope** [comment]
I think we have GCC vs clang in that if cond already as we check for `__GNUC_PREREQ(4, 8)` first, and if that's false we check the __has_builtin (Clang only I believe), excluding FreeBSD and Apple from that. Granted, the check for clang is a bit indirect.

Added an explicit check and some context around this.

**Comment by parafin** [comment]
Is it specific to FreeBSD and OS X? Did someone test clang-3.[78] on Linux for this bug?

**Comment by pope** [comment]
My linux box doesn't have clang-3.7 or 3.8. And clang-3.6 doesn't report to support it. Presumably it must work for some systems as it was added!

Looks like @LebedevRI commited https://github.com/darktable-org/darktable/commit/e237027cfa1879a4629cba459f899441960dd8b8 that added this call.

**Comment by pope** [comment]
I have just confirmed that this works on Linux. I tested on Ubuntu Trusty with the latest LLVM builds for 3.7. So FreeBSD and OSX do appear to be the ones left behind at this moment.

**Comment by parafin** [comment]
OK, so if no one has a problem with current version, I'm for merging it.

**Comment by LebedevRI** [comment]
@parafin yes, i'm pretty sure that with all standard clang's from Debian, this works just fine.
Probably, as that upstream bug suggests, because they link to (use) libgcc, so this is even worse than just simple "disable if apple or freebsd"...
Something for ./configure to check i'd say, but no idea if CMake can do it.

**Comment by parafin** [comment]
They mentioned libgcc, I think, because GCC implemented it, I don't think they meant clang would/should use it. So what's your point?

**Comment by LebedevRI** [comment]
I can be totally wrong, but:
```
$ ldd /usr/local/bin/darktable | grep gcc
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f86456ca000)
$ nm -D /lib/x86_64-linux-gnu/libgcc_s.so.1 | grep -i cpu
0000000000002c30 T __cpu_indicator_init
0000000000215910 B __cpu_model
```
My though:
On FreeBSD and OSX, i think, clang does not use gcc, thus does not link to libgcc_s.so.1.
And since [the required runtime support isn't currently in compiler-rt, it only exists in libgcc right now for the appropriate platforms, ](https://llvm.org/bugs/show_bug.cgi?id=25510#c1) when clang is self-contained, we have that issue.

I.e. if we compile self-contained clang on linux, we will get the same issue, AFAIU.

**Comment by parafin** [comment]
Ah, OK, didn't know that clang can use libgcc in some configurations. So do we do here then? It's probably impossible to tell if libgcc is used using just macros.

**Comment by LebedevRI** [comment]
My idea would be to add some obscure check to cmake that would compile [that](https://llvm.org/bugs/show_bug.cgi?id=25510#c0) testcase, run it, and see whether we get Undefined symbols when running it.
And based on that, add some define and check that define similarly to proposed changes.
But this might be too obscure.

**Comment by LebedevRI** [comment]
I'm not seeing any critique to my cmake suggestion, so.
@pope if you want, please try to implement the approach i have suggested in previous comment.
That stupid `defined(__clang__) && (defined(__FreeBSD__) || defined(__APPLE__))`, while it works, is not cool and does not all cases.

**Comment by pope** [comment]
Yup. I'm working on adding a check_c_source_compiles to check that this works. My prototype proves it does, and now I'm just porting it over to DT.

**Comment by pope** [comment]
Alright, done.

**Comment by LebedevRI** [comment]
@dumbbell please check whether this works for you.

**Comment by dumbbell** [comment]
Hi!

This works perfectly on FreeBSD. Thanks for this patch, it's much better!

**Pull request merged**
