### PR TITLE
added Lumix DMC-FZ300 noise profile. fixes #11608

### PR DESCRIPTION
**Pull request by thorenx**

### CODE REVIEW

**Comment by LebedevRI** [comment]
The pdf graphs will be needed anyway, to be able to actually review the profile.

**Comment by thorenx** [comment]
You can find the complete .tar.gz with the pdf graphs at this adress https://thoren.freeboxos.fr:30611/share/e5WY8aemtgwweMVW/dt-noiseprofile-20170511.tar.gz

**Comment by LebedevRI** [comment]
Best to open new redmine issue, and attach it there
Will not get deleted after some time, too

**Comment by schenlap** [comment]
graphs looks ok, i think it can be merged
#11608

**Comment by LebedevRI** [comment]
@thorenx in future, it is much better to branch, and submit a pr not from master branch.
@schenlap thank you.

**Pull request merged**
