### PR TITLE
 Update Italian translation

### PR DESCRIPTION
**Pull request by mmardegan**

### CODE REVIEW

**Comment by TurboGit** [comment]
Please review your procedure! I'll try to update the file manually but this is huge mess! 48 commits with many merge from upstream/master and mpaglia0/master branches! In a topic branch pushed here there should be no merging, you should use a rebase workflow.

I'll let you know if I can do something with all this !

**Comment by TurboGit** [comment]
Closing after all as it.po has no modification since last version in master!

**Comment by mmardegan** [comment]
Ok. Unfortunately, all my commits was been lost.

**Comment by TurboGit** [comment]
If you have your last and correct it.po just send it to me.

**Pull request closed without merging**
