### PR TITLE
Extend a color picker area by picking up a corner

### PR DESCRIPTION
**Pull request by dterrahe**
When selecting an area for a color picker, the first mouse click always sets one corner of the area. So after releasing the button, it is not possible to just extend the existing selection a little bit; you have to go back to the same starting point again.

This change allows to extend an existing selection by clicking sufficiently close to one of its corners (probably where the button was just released) and continue to have the area extend to the existing opposite corner (probably where the last selection started).

### CODE REVIEW

**Comment by TurboGit** [comment]
That's really nice ! Could we have a visual indicator when we are in the area with the resize can be done ? At least this will help advertising this feature.

**Comment by dterrahe** [comment]
Don't forget that none of this will be remembered in the module data; go out and back into darkroom and you have to start from scratch. So I don't feel there is too much point advertising a nice little almost free feature that then doesn't live up to the new (higher) expectations. Also, you can't drag the edges, only corner points (like it used to be before, but unlike crop/rotate). Unless there is functionality in crop/rotate that can be directly borrowed for this, I wouldn't really want to over engineer, to be honest. Also because I have no idea how to go about adding indicators in the color picker code.

And new users would find this anyway, just because they would expect it to work and try :-) Existing users can read the changelog ;-)

Unless you are saying we should beef up color pickers and make them rotatable, different shapes etc. ? That would be a nice, bigger, future, project. Maybe an integration with the masking code?

**Comment by TurboGit** [comment]
> Unless you are saying we should beef up color pickers and make them rotatable, different shapes etc. ? That would be a nice, bigger, future, project. Maybe an integration with the masking code?

No, no rotation or anything fancy. I just wanted have a discoverable GUI hint about this feature. Maybe a hint message at least ?

**Comment by dterrahe** [comment]
The size of the little square doesn't necessarily exactly match the zone of sensitivity because one is defined in pixels and the other, in button_pressed, in relative size. But at least there is an indication that the corner can be dragged.

**Comment by TurboGit** [comment]
Well, I like that, at least those handles are really a hint. Let's merge this to get more feedback.

**Pull request merged**
