### PR TITLE
WIP : add masks toolbar

### PR DESCRIPTION
**Pull request by aurelienpierre**
Screenshot_20210520_235531

Setting size, opacity, hardness, etc. of masks currently relies on hidden shortcuts + mouse scroll while hovering masks which is usuitable for Wacom pens, touch screens and mouses without wheel. Also, the opacity and hardness info are hidden unless the header panel is collapsed. All that makes masks cumbersome to work with.

This aims at enabling a contextual toolbar which enables the relevant control depending on the masks, when using the mask editing mode.

For now, opacity is functional and hardness is wired for circles only. Weird bugs affect brushes.

We might need to change some circuitery of the masking to make this work, but I believe the usability improvement is well worth it, especially considered dt is the only RAW editor with such masking.

### CODE REVIEW

**Comment by ralfbrown** [comment]
I was thinking about doing some additional refactoring related to handling mouse events in the mask code once InputNG is merged, so we should probably coordinate.

When I refactored the code to enable separate compilation, I gave each shape a table of function pointers, but didn't refactor the actual handling of mouse events, so the main masks.c code basically just dispatches the events to the selected mask shape which then has to parse whatever interests it.  My idea was to have the main masks.c code parse the events into the appropriate action(s) and dispatch on a set of simpler, lower-level function pointers for things like "change selected node", "move node", "adjust size/feather/rotation/opacity".  That would then also permit the top-level code to export entry points for InputNG shortcuts, allowing everything that could be done with the mouse to be done via keyboard/MIDI as well (obviously some things would be much slower with a regular keyboard, but a dial/slider on a MIDI controller could be just as fast and easier to handle than a mouse).

**Comment by AlicVB** [comment]
I like the idea of the toolbar.
We need refactoring here, but I'm not sure the way you propose @ralfbrown is the good one : each masks as it's own specificity, and so don't need/want to expose same parameters, with same names. So imho, what could be great is to have a way for each masks types to expose either the parameters themself (with name, types, bounds, ...) or better expose directly a list of widgets.
This widgets could be construct using actual bauhaus facilities, so they can nicely (and without efforts) been integrated in @dterrahe work...

I only speak of parameters here, but if we want to include something about nodes that become even more mask type specific !

@aurelienpierre : no test or code review yet, will do it asap

**Comment by ralfbrown** [comment]
ISTM that having a set of widgets per shape is functionally equivalent to the function-pointer table, it merely hides the function pointer as the widget's callback handler.  Using the widgets would be closer in spirit to the way things are done elsewhere in dt, and probably fits better with the toolbar this PR introduces, though I bet it will actually take more code to manipulate the widgets to cause the callbacks to be invoked than just calling through the function-pointer table.

**Comment by dterrahe** [comment]
This will be great!

The only little thing needed to tie this into Input NG is to connect the bauhaus sliders to the "masks toolbar" module (use the new `dt_bauhaus_slider_new_action(DT_ACTION(self), ...)` instead of `dt_bauhaus_slider_new_with_range(NULL, ...)`). Then you'll get the visual mapping, midi support, tooltips etc. and the current accelerators for increase/decrease opacity/etc can be retired.

What Input NG does _not_ yet do is replace any of the dedicated mouse/tablet handling code in the center area (masks/c&r/graduated density/color picker/filmstrip). That's a phase 2 of undetermined scope. At a minimum we'd need some way to use ctrl/shift/alt from a midi controller (via dt_modifier_is). At the maximum, all the interaction would be funneled through a new super configurable input layer that would allow you to manipulate brushes with your VR goggles. I'm not at all convinced that doing a massive amount of work in this area will be worth it.

That could mean that ctrl+scroll etc (without combining with any other keys, that would turn it into a shortcut) would not be configurable at all. So the intermediate path would be to implement some of the move and fallback system from Input NG so that it also is used for "the widget under the cursor" (either central area or for example bauhaus sliders; this would allow specifying per-widget scroll speeds or shift/ctrl speed increases/decreases). The center-area-in-mask-mode would be converted to an Action with several Elements (size/opacity/feather/rotation) each assignable shortcut combinations (modifiers/mouse double&triple clicks/moves/midi rotors). Still a very sizeable amount of work that depends on the level of acceptance and success of Input NG.

But tying wacom tablets into InputNG needs to be looked at first. Meaning so that they can be applied usefully as part of shortcuts _outside of_ the center area, for example to manipulate the bauhaus sliders introduced here.

That would all be orthogonal to any work done here/further refactoring by @ralfbrown.

**Comment by johnny-bit** [comment]
> But tying wacom tablets into InputNG needs to be looked at first. Meaning so that they can be applied usefully as part of shortcuts outside of the center area, for example to manipulate the bauhaus sliders introduced here.

There are other graphic tablet makers that are quite nice for the price and have surprisingly good support on linux. I own one with 8 buttons but looking at the manufacturer's site - they have bonkers models with stuff like dials and half of a keyboard even so those would be even better suited in combination with input NG :)

**Comment by dterrahe** [comment]
With "wacom" i mean any graphics tablet supported by X/gtk. I have access to a Huion (but not even played with yet).

Anything needing manufacturer specific support is unlikely. Although some stuff may eventually be routeable via lua...

**Comment by dterrahe** [comment]
Now that #12561 is merged, any further efforts to make it less sub par, for example by optionally showing the sliders in the header bar if preferred, should probably be based off the framework built there. So I would suggest closing this PR.

**Comment by dterrahe** [comment]
I believe it is time to close this PR and take further discussion to #12705, which implements this idea.

It also adds a popup menu as an alternative (as was suggested elsewhere) for when all side and top/bottom panels are hidden. It has now arrived at the absolute final stage; somebody needs to come up with a design! Mainly for what the right mouse button should do in dt; correspond to what users expect from other software (i.e. pop up a menu) or stay idiosyncratic in that it ends shape creation or deletes finished ones. If the first (or optional) an alternative way to finalise/delete shapes must be provided.

**Pull request closed without merging**
