### PR TITLE
channelmixerrgb: invalidate only preview pipe when extracting or validating profile

### PR DESCRIPTION
**Pull request by flannelhead**
This makes obtaining the profile faster. Noticed when debugging https://github.com/darktable-org/darktable/issues/7732. It seems this PR makes it harder to trigger that issue, however it also probably means there still is a race condition lurking somewhere in the pipe computation code (not sure, but looks like it could be) since this commit doesn't fix any race condition per se as far as I can tell.

Also contains a change which makes `channelmixerrgb` run the rest of `process()` after obtaining the profile. This fixes the shifting of the histogram mentioned in https://github.com/darktable-org/darktable/issues/7732#issuecomment-756239876.

Finally, fix flashing of the trouble message - `dt_iop_have_required_input_format()` in the beginning of `process()` clears the trouble message if successful, so reset it if necessary.

### CODE REVIEW

**Comment by TurboGit** [comment]
Works for me. Thanks!

**Comment by AxelG-DE** [comment]
something is likely buggy with this PR

when I go to darkroom and click duplicate manager --> original, I get:
grafik

This did not happen prior this PR, so 3.5.0-763-ge4a11ef7e is clean

**Comment by flannelhead** [comment]
Thanks for the report. It seems at a quick glance that this error is arising if `declare_cat_on_pipe()` hasn't been called for this instance. I'll have to try to reproduce, but probably will take me a couple of days to get back to this.

**Comment by flannelhead** [comment]
@AxelG-DE Could you please try if reverting the "fix flashing of trouble message" commit resolves this for you?

**Comment by AxelG-DE** [comment]
@flannelhead you mean I checkout one commit earlier than "fix flashing of trouble message" (myself not able to merge and unmerge on my side, I just follow master and can checkout at certain stages in between)

**Comment by TurboGit** [comment]
@AxelG-DE @flannelhead : should be fixed now, see a47ba20615db0aa96d19302021d49a37cfd5c294.

**Comment by AxelG-DE** [comment]
Very quick check confirmed (just one run duplicate on one pic), it is fixed.
Private issues prevent me from doing more, sorry

**Pull request merged**
