### PR TITLE
More segmentation and hlr masking fixes

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
There are some things that still can be fixed/improved in the segmentation based highlights reconstruction code
for dt v4.2. I am awfully sorry to do another pr so late ...  

1. For bayer sensors segmentation we can improve the resistance to some chroma noise while averaging
   the photosite data in the 3x3 box by ensuring a 5:2:2 ratio for green:red:blue
   
2. To avoid oversegmentation in the preview pipes - that would mean missing some segment's reconstruction and
   keeping data generated by opposed means - we calculate the allowed number of segments from input/scale
   instead of roi size.
 
3. While calculating the best candidate for each segment we make sure the weight is not calculated
   from border data.

4. While doing the segmentize internals we avoid having mini-segments and also make sure the maskplane state
   changes for the tested segment are reverted (improved border check for so far untested segments)

5. Improve visual output mask of combining

6. The masking mode state is now kept in the parameter struct and is updated via commit_parameters
   from the UI mask buttons only here.
   This ensures a valid hash for the pixelpipe cache so we don't need the dirty workaround of
   clearing the cache any more.

@MStraeten please test this again :-)

### CODE REVIEW

**Comment by MStraeten** [comment]
here the result: initial rendering is fine but subsequent renderings fails:

https://user-images.githubusercontent.com/39386816/203855221-422193e0-19d0-47b1-8c1f-5975d205df69.mp4


https://user-images.githubusercontent.com/39386816/203855232-f65620b5-07b5-4802-83ac-d1f6777bc834.mp4

darktable -t 0 (reports just one thread for openmp parallel sections:


https://user-images.githubusercontent.com/39386816/203855798-fbd452cb-186c-4093-8ab3-81b43a4ecf0b.mp4

**Comment by jenshannoschwalm** [comment]
@TurboGit a note about this pr being for 4.2; if you are not fine with the changes related to the iop cache handling, the first commit are "safe fixes".

@MStraeten i looked again at the current videos, i still can't really make any sense of it. The structural data seem to be there, and i have absolutely no explanation for a) dependency on histogram setting or b) focus in/out of the darktable window. I looked into view/darkroom code and couldn't find any tricky osx specific part yet. Some ideas for you to check

1. Unfortunately we don't have a debug switch for "disable the pixelpipe cache" yet. But what happens if you keep the visualizing mask active and change any setting of the sliders? That should make sure you get a new cacheline.
2. Disabling omp for masking output code would be: comment the `#ifdef ... #endif` declararations L 701-706 in hlrecovery_v2.c

**Comment by MStraeten** [comment]
with #if defined(_OPENMP) && !defined(__APPLE__) in Line 701 just changing slider values:

https://user-images.githubusercontent.com/39386816/203917857-eecebf54-7dc6-4991-a71e-e08f4a8fdcc2.mp4

**Comment by TurboGit** [comment]
@jenshannoschwalm : I'll cherry pick only the first commit indeed. The second is a bit too complex especially since it does not fix OP issue and we don't have the issue reproduced on Windows & GNU/Linux.

**Comment by TurboGit** [comment]
First commit merged. You may want to rebase this PR. Thanks.

**Comment by jenshannoschwalm** [comment]
I am absolutely fine with the cherry pick.

**Comment by MStraeten** [comment]
tested it with an older mac with different system configuration (older macos version, nvidia gpu instead of amd): issue not reproducible. 
Then i tried some further constellations:  disabling openmp, opencl, forcing use of integrated gpu, forcing dedicated gpu with my usual system - no reproducible fine result, no reproducible bad result - quite arbitrary...

**Comment by TurboGit** [comment]
> tested it with an older mac with different system configuration (older macos version, nvidia gpu instead of amd): issue not reproducible.

So maybe an issue with the Mac? Have you done a memory check? The NVIDIA vs AMD could be an issue as common, but as you have tested with and without OpenCL activated it rules out this.

**Comment by MStraeten** [comment]
system diagnostic didn't find issues

**Comment by MStraeten** [comment]
now I’ve been able to get an arbitrary result even with the older MacBook when using the Tall unicycle image … but less frequently

**Comment by jenshannoschwalm** [comment]
Closing because of a correct replacement #13066

**Pull request closed without merging**
