### PR TITLE
CMake: drop custom FindICU

### PR DESCRIPTION
**Pull request by kmilos**
Provided by CMake since v3.7 @phweyland

### CODE REVIEW

**Comment by phweyland** [comment]
Hi Pascal, this seems to be a nice simplification. But I cannot test before some weeks...

**Comment by TurboGit** [comment]
Hi @phweyland , no problem, no urgency. I'll wait for you testing. Thanks.

**Comment by TurboGit** [comment]
@phweyland : This is becoming a bit urgent as we are approaching feature freeze, can you have a look? TIA.

**Review by phweyland — APPROVED** [review]
I've tried and this seems to work perfectly on debian

cmake:
-- Found the following ICU libraries:
--   i18n (required): /usr/lib/x86_64-linux-gnu/libicui18n.so
--   data (required): /usr/lib/x86_64-linux-gnu/libicudata.so
--   uc (required): /usr/lib/x86_64-linux-gnu/libicuuc.so
-- Found ICU: /usr/include (found version "71.1")

and I've tested that dt still can work sensitive / insensitive with non ascii letters (ICU does work).

**Comment by phweyland** [comment]
Sorry for the late answer ...

**Review by TurboGit — APPROVED** [review]
Thanks!

@phweyland : thanks for checking.

**Pull request merged**
