### PR TITLE
map fix: don't drag if click and release with no mouse move

### PR DESCRIPTION
**Pull request by phweyland**
Fixes one defect pinpointed in #7020.
Solved issue: if the user clicks on an image (or a location) and release without moving the mouse, the drag remains active and an unexpected drag occurs.

@quovadit , could you confirm this solves the accidental image geo position changes ?

### CODE REVIEW

**Comment by TurboGit** [comment]
Is there some threshold here ? Not moving should probably mean around 10 pixels around or something like that no ? This is what we do for dragging the masks for example and just not moving is almost impossible.

**Comment by phweyland** [comment]
> Is there some threshold here ?

I've started by the threshold, but have found the most boring issue was the one fixed here.
I'll put it back.

**Comment by quovadit** [comment]
@phweyland : for me it works perfect with your fix, thanks!

**Comment by phweyland** [comment]
Added movement threshold (same as in thumbtable.c)

**Comment by quovadit** [comment]
works with movement-threshold as well

**Comment by phweyland** [comment]
@quovadit thanks for testing. 

last commit to try to fix travis error.

**Review by TurboGit — APPROVED** [review]
Works for me !

**Pull request merged**
