### PR TITLE
borders: Fix rounding issues when computing width/height.

### PR DESCRIPTION
**Pull request by TurboGit**
Fixes #13329.

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
This works for me too. One issue remaining is "borders to be symmetrical", if we want to have a border of n, the displacements like roi->x should be corrected by n and roi->width by 2*n

**Comment by TurboGit** [comment]
> This works for me too. One issue remaining is "borders to be symmetrical", if we want to have a border of n, the displacements like roi->x should be corrected by n and roi->width by 2*n

How to reproduce the symmetrical border issue? It seems ok on my side...

**Comment by jenshannoschwalm** [comment]
I think we must make sure both width and height must be decreased in steps of 2 to allow symmetric borders.

**Comment by TurboGit** [comment]
> I think we must make sure both width and height must be decreased in steps of 2 to allow symmetric borders.

Hum... I'm a bit lost :)

**Comment by TurboGit** [comment]
I'm confused because as I see it there is not much we can do. The borders is expressed in % of the width / height. The aspect ratio is kept in all cases and last the image can be displaced on the frame. All this means that the borders are not necessary the same size on all side. The only case where we really want the borders to be the exact same size is when the image is centered, but this seems hard to do as the borders hare calculated based on the roi_in vs roi_out and the scale:

```
  const int bw = roundf(piece->buf_out.width - piece->buf_in.width) * roi_out->scale;
  const int bh = roundf(piece->buf_out.height - piece->buf_in.height) * roi_out->scale;
```

Or maybe I missed your point? Or you have a better idea to achieve that?

**Comment by jenshannoschwalm** [comment]
I don't have a perfect solution either right now.

**Comment by TurboGit** [comment]
Ok, so I'll test this again and will merge if it still fix the 0030 test. At least with my changes here there is less chance for accumulated errors and at worst we should have one pixel more on one side.

**Pull request merged**
