### PR TITLE
Piwigo

### PR DESCRIPTION
**Pull request by TurboGit**
A Piwigo new storage plug-in. Supports:
- multi-servers
- create album and set parent album if needed
- upload to album
- publish with tags or not 
- select the privacy level

### CODE REVIEW

**Comment by TurboGit** [comment]
Please go ahead! I've been using a lot recently as I have moved to Piwigo :)

**Comment by TurboGit** [comment]
Yes, I expect this to be in a minor release, maybe 2.6.1.. For the tree I understand, but the combo box does not support trees AFAIK. I'm no expert in Gtk! Maybe just by adding padding in front of the album names?

**Comment by leclercj** [comment]
Yes, a left-alignement in the list with indents reflecting Piwigo album hierarchy could be a good alternative.
One very great value of this module is the option to also export the tags to Piwigo.

**Comment by TurboGit** [comment]
Hierarchical display of albums now implemented. Do not hesitate to test, it should help a lot when lot of albums are displayed.

**Comment by leclercj** [comment]
Yes, that's much better indeed
One observation: When the target storage of expot module is changed to anything else and back to piwigo, the latest used album is proposed again (and that's good), but text and combo boxes specific to new album creation are also shown (and should not).
capture d ecran du 2018-12-05 23-45-05

**Comment by TurboGit** [comment]
I don't know how to fix your last report as it seems we have no callback when the actual storage kind is changed. What I have done is that after an upload is done the new album section is hidden. Hope it will somewhat makes the issue bearable :)

**Comment by TurboGit** [comment]
manually merged.

**Comment by upegelow** [comment]
I get a lot of compile errors. Any special curl version requirements?

/home/pegelow/darktable/src/imageio/storage/piwigo.c: In Funktion »_piwigo_api_post_internal«:
/home/pegelow/darktable/src/imageio/storage/piwigo.c:272:3: Fehler: Unbekannter Typname »curl_mime«; meinten Sie »curliocmd«?
   curl_mime *form = NULL;
   ^~~~~~~~~
   curliocmd
/home/pegelow/darktable/src/imageio/storage/piwigo.c:309:5: Fehler: Unbekannter Typname »curl_mimepart«; meinten Sie »curl_TimeCond«?
     curl_mimepart *field = NULL;
     ^~~~~~~~~~~~~
     curl_TimeCond
/home/pegelow/darktable/src/imageio/storage/piwigo.c:311:12: Fehler: Implizite Deklaration der Funktion »curl_mime_init«; meinten Sie »curl_multi_init«? [-Werror=implicit-function-declaration]
     form = curl_mime_init(ctx->curl_ctx);
            ^~~~~~~~~~~~~~
            curl_multi_init
/home/pegelow/darktable/src/imageio/storage/piwigo.c:311:10: Fehler: Zuweisung an »int *« von »int« wandelt eine Zahl in einen Zeiger um, ohne explizite Typkonvertierung [-Werror=int-conversion]
     form = curl_mime_init(ctx->curl_ctx);
          ^
/home/pegelow/darktable/src/imageio/storage/piwigo.c:318:15: Fehler: Implizite Deklaration der Funktion »curl_mime_addpart«; meinten Sie »curl_write_data_cb«? [-Werror=implicit-function-declaration]
       field = curl_mime_addpart(form);
               ^~~~~~~~~~~~~~~~~
               curl_write_data_cb
/home/pegelow/darktable/src/imageio/storage/piwigo.c:318:13: Fehler: Zuweisung an »int *« von »int« wandelt eine Zahl in einen Zeiger um, ohne explizite Typkonvertierung [-Werror=int-conversion]
       field = curl_mime_addpart(form);
             ^
/home/pegelow/darktable/src/imageio/storage/piwigo.c:319:7: Fehler: Implizite Deklaration der Funktion »curl_mime_name«; meinten Sie »curl_getdate«? [-Werror=implicit-function-declaration]
       curl_mime_name(field, ca->name);
       ^~~~~~~~~~~~~~
       curl_getdate
/home/pegelow/darktable/src/imageio/storage/piwigo.c:320:7: Fehler: Implizite Deklaration der Funktion »curl_mime_data«; meinten Sie »curl_getdate«? [-Werror=implicit-function-declaration]
       curl_mime_data(field, ca->value, CURL_ZERO_TERMINATED);
       ^~~~~~~~~~~~~~
       curl_getdate
/home/pegelow/darktable/src/imageio/storage/piwigo.c:320:40: Fehler: »CURL_ZERO_TERMINATED« nicht deklariert (erstmalige Verwendung in dieser Funktion); meinten Sie »CURLINFO_PRIVATE«?
       curl_mime_data(field, ca->value, CURL_ZERO_TERMINATED);
                                        ^~~~~~~~~~~~~~~~~~~~
                                        CURLINFO_PRIVATE
/home/pegelow/darktable/src/imageio/storage/piwigo.c:320:40: Anmerkung: jeder nicht deklarierte Bezeichner wird nur einmal für jede Funktion, in der er vorkommt, gemeldet
/home/pegelow/darktable/src/imageio/storage/piwigo.c:324:11: Fehler: Zuweisung an »int *« von »int« wandelt eine Zahl in einen Zeiger um, ohne explizite Typkonvertierung [-Werror=int-conversion]
     field = curl_mime_addpart(form);
           ^
/home/pegelow/darktable/src/imageio/storage/piwigo.c:326:5: Fehler: Implizite Deklaration der Funktion »curl_mime_filedata«; meinten Sie »_curl_is_cb_data«? [-Werror=implicit-function-declaration]
     curl_mime_filedata(field, filename);
     ^~~~~~~~~~~~~~~~~~
     _curl_is_cb_data
In file included from /usr/include/curl/curl.h:2305,
                 from /home/pegelow/darktable/src/imageio/storage/piwigo.c:33:
/home/pegelow/darktable/src/imageio/storage/piwigo.c:328:37: Fehler: »CURLOPT_MIMEPOST« nicht deklariert (erstmalige Verwendung in dieser Funktion); meinten Sie »CURLOPT_TIMEOUT«?
     curl_easy_setopt(ctx->curl_ctx, CURLOPT_MIMEPOST, form);
                                     ^~~~~~~~~~~~~~~~
/home/pegelow/darktable/src/imageio/storage/piwigo.c:357:16: Fehler: Implizite Deklaration der Funktion »curl_mime_free«; meinten Sie »curl_free«? [-Werror=implicit-function-declaration]
   if(filename) curl_mime_free(form);
                ^~~~~~~~~~~~~~
                curl_free
cc1: Alle Warnungen werden als Fehler behandelt
src/imageio/storage/CMakeFiles/piwigo.dir/build.make:62: recipe for target 'src/imageio/storage/CMakeFiles/piwigo.dir/piwigo.c.o' failed

**Comment by TurboGit** [comment]
I have libcurl4 installed on my machine and have no warnings.

**Comment by upegelow** [comment]
Here on my system:

> rpm -q libcurl4
libcurl4-7.37.0-42.1.x86_64

> rpm -q libcurl-devel
libcurl-devel-7.37.0-42.1.x86_64

**Comment by TurboGit** [comment]
Really strange! Maybe you also have libcurl3 and this is the one picked during build?

**Comment by upegelow** [comment]
There doesn't seem to be any other version of libcurl around here. The problem seems to be linked to curl_mime related features. Could it be that this is an optional part of the curl library and some implementations leave it out?

**Comment by TurboGit** [comment]
I have libcurl4 7.62 on my machine. So maybe a more recent version is needed.

**Comment by upegelow** [comment]
> I have libcurl4 7.62 on my machine. So maybe a more recent version is needed.

That might be an issue on some systems, mine included. If there is no workaround for older versions of that library you may need to make piwigo support optional at compile time.

**Comment by TurboGit** [comment]
Yes,, I working on that indeed, we cannot break builds on old machines.

**Comment by TurboGit** [comment]
@upegelow : can you test this https://github.com/darktable-org/darktable/pull/1940

**Comment by upegelow** [comment]
It does the job!

**Pull request closed without merging**
