### PR TITLE
Support for darkroom visibility of utility modules toggle

### PR DESCRIPTION
**Pull request by victoryforce**
This PR supersedes #17263.

Yet to be discussed the toggle label ("hide in darkroom", "show in darkroom", or maybe one or the other depending on the default) and which of the utility modules we want to show by default.

### CODE REVIEW

**Comment by victoryforce** [comment]
> I still have a preference for having this label into the module's preferences

I'm definitely not going to implement this as it's really ugly, illogical and by no means a quality UX.

But in the end, you decide what to accept and what not to accept, and you or someone else can implement it.

Should I close this PR?

**Comment by victoryforce** [comment]
> Can we discuss that? I mean this option is going to be used probably once by a user. Once you've decided to have such utility module visible in darkroom it is certainly a choice you won't revisit (or very rarely).

I don't agree, because I would use this switch more often myself.

I'm currently working on a notebook with a 14 inch screen and 2x scaling. Accordingly, the height of the darktable window leaves something to be desired, to put it mildly. But from time to time I connect it to a large external monitor where there is enough vertical space for the program.

When working with a large screen, I would gladly keep in the left panel in the darkroom a maximum of utility modules that would be of use from time to time. But on a notebook screen, even the title bars of closed modules take up a significant amount of screen real estate, so you just want to remove them.

This is an absolutely real use case. Not all users will use this switch only once.

In addition, there is an exact analogy with the "show guides" switch in the local menus of some processing modules. We added this switch as a first-level item in the module menu. OK, I guess there may be users who toggle it frequently. But, personally, I just always show guides in these modules and don't toggle it. Moreover, the menu item duplicates the parameter inside the module, so there was no need for this menu item at all.

Why then do we keep the redundant "show guides" item in the processing modules menu, but do not want to add a menu item to the utility modules?

**Comment by jenshannoschwalm** [comment]
There is also @dterrahe proposal to be remembered.

**Comment by dterrahe** [comment]
https://github.com/user-attachments/assets/aa9d3829-7767-4bf8-a75d-77017c6674a4

**Comment by victoryforce** [comment]
> @victoryforce : What about dterrahe proposal?

The idea seems appealing. Will be happy to test @dterrahe's PR. The only thing is that the discoverability of such a solution is somewhat less. Not all users will come to the idea that double-clicking on an empty space should do something.

**Comment by dterrahe** [comment]
> if you hid everything, via an innocuous _Tab_, you'll have a hard time finding _preferences_ in the first place

image

**Comment by victoryforce** [comment]
Closing this PR because there is a better solution in #17425.

**Pull request closed without merging**
