### PR TITLE
imageop: make the always-on button distinguishable.

### PR DESCRIPTION
**Pull request by TurboGit**

### CODE REVIEW

**Comment by TurboGit** [comment]
This makes the always-on modules stand out.

@Nilvus : how does that sounds to you ?

**Comment by Nilvus** [comment]
That sounds really great, except the color. It would be great to have possibility to change that with CSS. I could then propose you a color (of course in a shade of grey) for each theme.

**Comment by TurboGit** [comment]
@Nilvus : Great, I have added a name to the always on module button:

`module-always-enabled-button`

**Comment by Nilvus** [comment]
@TurboGit : to avoid another PR from me for just that tweak, and after testing, I suggest you to add my proposal. Here it is :
```
#module-always-enabled-button /* Button on always activated module */
{
  color: @plugin_label_color;
}
```
Just add these lines on darktable.css theme, line 381

A screen capture to see the result (on grey theme) :
Capture-20191111221748-321x459

**Comment by TurboGit** [comment]
Thanks, done and merged.

**Comment by Nilvus** [comment]
@TurboGit : good team job today on UI ! Thanks to you.

**Pull request merged**
