### PR TITLE
introduce universal toast message for sliders and comboboxes

### PR DESCRIPTION
**Pull request by johnny-bit**
this should univerally cover toasts for sliders and comboboxes
when called from either normal or dynamic accel keys in a way
that won't trigger any reverts. also avoids code duplication
and covers multi-instance cases :)

This merges functionality provided by @dterrahe and @elstoc in single point, away from `bauhaus.c`

### CODE REVIEW

**Comment by dterrahe** [comment]
https://github.com/darktable-org/darktable/pull/4424#issuecomment-601846551

**Comment by elstoc** [comment]
@dterrahe oh yes I forgot about that. We should incorporate that functionality too.

**Comment by johnny-bit** [comment]
@dterrahe - done in bca3558 hope it's fine :)

**Comment by dterrahe** [comment]
The slider code used to have:
```
else
        dt_control_log(_("%s: %s"), w->label, text);
```
You'd have to check if that works for comboboxes.

**Comment by elstoc** [comment]
When I did the work for comboboxes I went through them all - I couldn't find any comboboxes where the name of the combobox also exists in the name of the module, and there are only a handful of sliders that do. 

The complete statement should probably add another ``else if (w->label) dt_control_log(_("%s: %s"), w->label, text);`` and then finish with the existing ``else``

**Comment by dterrahe** [comment]
The rest of the code assumes that w->label != NULL, so if you feel the need to test it, you might want to wrap everything that's currently within if(show) with it. The original test was `if (*w->label)`. Can't remember if that was a mistake or if there's always a pointer, but sometimes to an empty string. And again, that might be different between sliders and combos. Something else to test...

**Comment by elstoc** [comment]
Yes I wasn't sure how that last else could ever be reached. I think we can treat it like the default case - unlikely to ever be triggered but nice to catch things we haven't thought of.

I haven't been able to test it (apart from the early preview I looked at last night) but looks good to me now.

**Comment by dterrahe** [comment]
Actually, the `if (*w->label)` test is still there, at the top. I overlooked, sorry.

**Comment by elstoc** [comment]
Yes it should be removed from that top if statement. As previously stated it's probably vanishingly unlikely to ever occur.

**Comment by johnny-bit** [comment]
OK, I'll fix build and test it in a bit.

at the start test is for 2 things:
1. we can't see widget
2. gui isn't resettting

once we're clear with that there's text preparation.

show is by default true and for sliders it CAN be false only if dragging is true, and it's impossible to set dragging via key accell, right? so this is just superflous test, just to make sure ;)

so now choosing the right format...
is it safe to assume all combos/sliders have label? most formats assume that.

**Comment by elstoc** [comment]
I couldn't work out what the 'dragging' bit was used for. Perhaps it is superfluous for accels. 

I think it is safe to assume that all comboboxes *with keyboard shortcuts* have a label, because I added them myself, and they do.

**Comment by johnny-bit** [comment]
well `label` is a static char array so if `w` is valid pointer to widget structure, it's guaranteeed to be ok... so... test if it's empty?

**Comment by elstoc** [comment]
I suppose.

**Comment by johnny-bit** [comment]
OK, this logic should cover all the corner cases ;)

**Comment by elstoc** [comment]
If the label is empty ``strstr(w->module->name(), w->label)`` doesn't make sense. Just have ``dt_control_log(_("%s"), text);``. No need to make it more complicated than that, since it'll never happen anyway.

**Comment by johnny-bit** [comment]
OK, so now this should cover all possible codepaths, even impossible/impossilby stupid ones ;) (I think)

**Comment by elstoc** [comment]
Fine for me now.

**Comment by TurboGit** [comment]
Works for me, thanks !

**Comment by houz** [comment]
> When I did the work for comboboxes I went through them all - I couldn't find any comboboxes where the name of the combobox also exists in the name of the module, and there are only a handful of sliders that do.

When writing code for the dt core you shouldn't assume that the modules using it are only doing some subset of possible things. Modules might change and people might have modules that are not in our code.

**Comment by elstoc** [comment]
Fair enough

**Pull request merged**
