### PR TITLE
rgbcurve: cleanup parallel loop

### PR DESCRIPTION
**Pull request by ralfbrown**

### CODE REVIEW

**Comment by TurboGit** [comment]
This makes rgbcurve crash as soon as you touch the curve:

```
(gdb) bt
#0  process._omp_fn.0 ()
    at /home/obry/dev/builds/darktable/build/src/src/iop/rgbcurve.c:1816
#1  0x00007ffff77fade6 in  () at /lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007ffff796dea7 in start_thread (arg=<optimized out>)
    at pthread_create.c:477
#3  0x00007ffff7a84d8f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Review by TurboGit — CHANGES_REQUESTED** [review]
Fix crash.

**Comment by ralfbrown** [comment]
Silly me - multiply the loop index by four or step it by four, don't do both :-).

**Comment by TurboGit** [comment]
All good now, thanks!

**Comment by TurboGit** [comment]
Merged in master, queued for 3.4.1.

**Pull request merged**
