### PR TITLE
add noise profiles canon eos rp

### PR DESCRIPTION
**Pull request by aadm**
Noise profiles for Canon EOS RP, thanks to @piratenpanda for executing the script (I have only made the required photographs).

[darktable-noiseprofile-20210520.tar.gz](https://github.com/darktable-org/darktable/files/6521753/darktable-noiseprofile-20210520.tar.gz)

[noise_result.pdf](https://github.com/darktable-org/darktable/files/6521755/noise_result.pdf)

### CODE REVIEW

**Comment by aadm** [comment]
Added WB presets with finetuning the PR, again with the help of @piratenpanda.

**Comment by johnny-bit** [comment]
Now those wb presets look NICE!

**Comment by rawfiner** [comment]
Noise profiles look ok for me

**Comment by aadm** [comment]
> Now those wb presets look NICE!

I'm confused and curious -- how can you tell? 

anyway glad I have finally helped the dt's team!

**Comment by johnny-bit** [comment]
> I'm confused and curious -- how can you tell?

finetuning @ -9 has less red that @ 9 and inverse is true for blue. and the movement along what should be normal to plackian locus looks ok-ish from cursory glance.

**Review by TurboGit — APPROVED** [review]
Thanks !

**Pull request merged**
