### PR TITLE
opencl implementation of Markesteijn demosaicing algorithm for x-trans sensors

### PR DESCRIPTION
**Pull request by upegelow**
As the title says. It's already mostly functional. Some work to be done for a better border handling.

The Markesteijn algorithm is a real memory hog. Take the slow global memory accesses of the typical OpenCL device, then it's clear that the speed-up versus CPU is not too impressive - maybe a factor of 2 versus CPU with a rather fast GPU. Slow GPUs might easily be slower than the CPU. Finally there should be a config variable so that users can activate the OpenCL codepath for Markesteijn after doing some benchmarking.

### CODE REVIEW

**Comment by houz** [comment]
Roman is currently working on adding more `process_*()` variants and we thought about some automated benchmarking and picking the fastest code path on an IOP level. Maybe that can be used for OpenCL, too?

**Comment by upegelow** [comment]
There are modules where benchmarking results would vary a lot depending on module parameters. demosaic is an example. For some demosaicing methods OpenCL typically performs ahead of the CPU, for others it might drop behind.

**Comment by upegelow** [comment]
My tests on AMD and NVIDIA hardware reveals that the code is working as expected. In terms of performance evaluation I need some benchmarking data from more users.

**Comment by LebedevRI** [comment]
@upegelow 
(yes, i have looked at this only now :)

This block is bothering me: https://github.com/darktable-org/darktable/blob/385801d7e6643790f3fddf437856e8c759b41dd2/src/iop/demosaic.c#L3256-LL3263

https://github.com/darktable-org/darktable/blob/385801d7e6643790f3fddf437856e8c759b41dd2/src/iop/demosaic.c#L3527-L3532

Shouldn't those 2 cases in`commit_params()` also check `darktable.opencl->enable_markesteijn`, and if it is `0`, do `piece->process_cl_ready = 0;` ?

Else i think we are risking to see that `"[opencl_demosaic] Markesteijn demosaicing with OpenCL not enabled (see 'opencl_enable_markesteijn')\n"` when user zooms-in close-enough, no?

**Comment by upegelow** [comment]
> This block is bothering me:
> https://github.com/darktable-org/darktable/blob/385801d7e6643790f3fddf437856e8c759b41dd2/src/iop/demosaic.c#L3256-LL3263
>
> https://github.com/darktable-org/darktable/blob/385801d7e6643790f3fddf437856e8c759b41dd2/src/iop/demosaic.c#L3527-L3532
>
> Shouldn't those 2 cases in|commit_params()| also check
> |darktable.opencl->enable_markesteijn|, and if it is |0|, do
> |piece->process_cl_ready = 0;| ?
>
> Else i think we are risking to see that |"[opencl_demosaic] Markesteijn
> demosaicing with OpenCL not enabled (see
> 'opencl_enable_markesteijn')\n"| when user zooms-in close-enough, no?

That's in fact intended. Markesteijn is still slow, even on GPU. 
Therefore we use VNG (or even linear interpolation) if we are zoomed-out 
enough. The zoom status is not known in commit_params, so we can either 
go or not go the OpenCL route. Not going the OpenCL route while we could 
take advantage of the fast VNG interpolation would be a pitty.

Worst thing that could happen: user has decided to de-activate the 
opencl_enable_markesteijn option (it's enabled by default). Then when 
zoomed in darktable falls transparently back to CPU code: besides of the 
speed no user visible difference. Only if the user decides to run with 
-d opencl and then inspects the output he will be reminded that he 
switched off the opencl_enable_markesteijn option. An informative 
message, so the user might reconsider his decision. Nothing to worry about.

IMHO it should stay like this. Alternative: we completely skip the 
opencl_enable_markesteijn option. However, I am not yet 100% sure if 
there might be users who will then suffer a lot from a processing speed 
that is even slower than the CPU. For them it would be a good relief to 
have this option other than completely switching off OpenCL.

Ulrich

**Comment by LebedevRI** [comment]
> Then when zoomed in darktable falls transparently back to CPU code: besides of the speed no user visible difference.

Ah, that was the piece i was missing.
Then it is ok indeed.

**Pull request merged**
