### PR TITLE
Revert part of a00f9d30.

### PR DESCRIPTION
**Pull request by TurboGit**
This makes all integration tests to pass.

### CODE REVIEW

**Comment by TurboGit** [comment]
@elstoc : Can you have a look at this one ? It fixes the integration tests which were really broken after a00f9d30.

Also, please make sure you run the integration tests when dealing with any develop part of code. Let me know if you need help running those tests. TIA.

**Comment by elstoc** [comment]
Unfortunately the functionality introduced within #5449 does not work correctly with this fix added. The idea is that if I select a step prior to (for example) white balance in the history stack and compress history then (a) The module no longer shows in the stack (PASS); (b) The module shows as disabled on the right-hand-panel (PASS); and (c) The preview image shows the effect of disabling the module (FAIL).

So it looks like the UI thinks the module is disabled when in fact it is not.

Regarding the integration tests, I was vaguely aware of them but I didn't know how to run them. I see someone has added some documentation to the wiki now though (https://github.com/darktable-org/darktable/wiki/Dev-guide---darktable-testing-tools) so I'll consult that and let you know if I have any questions.

I'm not sure how to proceed with this one though given that it fails my testing.

**Comment by TurboGit** [comment]
@elstoc : This new feature is certainly complex and may have some huge drawback (copy history ? in style ? support for module order ?). I don't think this should have been merge this fast... What about reverting this for now until we have a clear idea and more testing about all the points above ? Note that we are only at 3 months or so of next code freeze !

**Comment by elstoc** [comment]
I'm ok with that if you think it's best. It was only a 'nice to have' from my point of view and I can live without it. It's just a pain to have to remember re-disable things when going back to earlier points in the stack. Please can you reopen the bug and the PR when you revert.

I'll probably need some support if it gets much more complex though.

**Comment by TurboGit** [comment]
Ok, I'll revert and will reopen the bug but I cannot reopen a PR when merged.

**Comment by TurboGit** [comment]
Revert done and issue reopened. Closing this PR.

**Pull request closed without merging**
