### PR TITLE
camera: use correct libgphoto2 translation domain

### PR DESCRIPTION
**Pull request by kmilos**
SOVERSION of libgphoto2 has been 6 since 2.5.0

### CODE REVIEW

**Comment by kmilos** [comment]
Could potentially also remove < 2.5 support throughout, there's hardly anyone using it: https://repology.org/project/libgphoto2/versions

**Comment by kmilos** [comment]
Removed also "libraw", it is not a file extension...

**Comment by kmilos** [comment]
@parafin You might want to add libphoto2-6 (as well as glib20?) to your bundle...

**Comment by parafin** [comment]
What user-visible strings are translated in those domains?

**Comment by johnny-bit** [comment]
Removing support for lower than 2.5 is imo OK - we have currently minimum of ubuntu 18.04 LTS as a base and on it there's 2.5.16 so we're good ;)

**Comment by kmilos** [comment]
> What user-visible strings are translated in those domains?

Don't know exactly but dt is explicitly using it.

**Comment by parafin** [comment]
I like to see changes when I change smth:)) I will check it out some time maybe...

**Comment by kmilos** [comment]
I have no camera connected to check, but it should be related to "Add  a new property of camera to the gui"...

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by parafin** [comment]
> @parafin You might want to add libgphoto2-6 (as well as glib20?) to your bundle...

I've added libgphoto2-6 as you suggested. But as for glib20 - I checked and presence of its translations doesn't seem to affect date formatting on macOS. There's something strange going on with time format on macOS, but glib20 translations sadly are not a solution. Someone will have to do a deep dive on that to understand the issue and fix it, I'm not too motivated to do that. To summarize - I don't see an effect of glib20 translations, so I'm not going to add them at this time.

**Comment by kmilos** [comment]
Fair enough, that date issue might have been Windows specific. I debugged and found it was falling through to GLib when missing some POSIX function that is presumably available on macOS.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
