### PR TITLE
Add different timeouts depending on the importance of the view.

### PR DESCRIPTION
**Pull request by TurboGit**
May help having a more responsive UI.

I'd like @aurelienpierre and @edgardoh point of view on this. Thanks.

### CODE REVIEW

**Comment by aurelienpierre** [comment]
Seems fine by me. I will need to test.

**Comment by aurelienpierre** [comment]
Tested. The label "working…" is not displayed anymore after zooming, when the preview is recomputed.

**Comment by edgardoh** [comment]
Some modules use the preview pipe to do some calculations, as they need the entire image, so preview must run before the full pipe, I'm not sure if this can create some conflict, it has to be tested.

**Comment by TurboGit** [comment]
> Tested. The label "working…" is not displayed anymore after zooming, when the preview is recomputed.

Isn't this related to the removal of the dt_control_queue_redraw() call removed in previously?

**Comment by TurboGit** [comment]
> Some modules use the preview pipe to do some calculations, as they need the entire image, so preview must run before the full pipe, I'm not sure if this can create some conflict, it has to be tested.

I see, but my idea was to give the priority to the full preview (or working space) as this one must be recomputed as fast as possible. Too bad, I'll put the preview first and we'll see.

**Comment by TurboGit** [comment]
Ok, so I have set preview timeout to 400, main view to 500 and second preview to 600.

**Comment by TurboGit** [comment]
Any objection to push that now?

**Comment by edgardoh** [comment]
None on my side.

**Comment by TurboGit** [comment]
Ok, so let's see how this works.

**Pull request merged**
