### PR TITLE
fix color pick

### PR DESCRIPTION
**Pull request by edgardoh**
Color picker do not return the right values, as reported in [1]

This fix the rgb and lab values on the colorpicker and the final histogram and gamma module.

[1] https://www.mail-archive.com/darktable-user@lists.darktable.org/msg06952.html

### CODE REVIEW

**Comment by aurelienpierre** [comment]
So at which stage of the pipe do you pick the color now ?

**Comment by edgardoh** [comment]
The same, but I use the input image instead of the output one.

**Comment by aurelienpierre** [comment]
Ok. Ideally, we would like to pick before the output color profile is applied too.

**Comment by TurboGit** [comment]
Looks good and a nice code refactoring! Thanks.

**Pull request merged**
