### PR TITLE
HLR segmentation maintenance

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Due to late reports still reporting "oversegmentation" i reinvestigated segmentation algorithm, the likely reason is not-fully initialized segmentation plane data.

- the plane data should be specified as uint32_t so we can safely do masking
- we properly initialize segmentation data and test for wrongful allocation, in that case we don't do the segmentation postprocessing
- the tmp handling stuff has been removed as we always use one of the morphs
- while doing the morphological operations we always return either 1 or 0 in case the initial data were not correct so avoid possibly wrong segment ids
- testing for a proper segment id makes sure that non-initialized data can't be accessed.

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
@MStraeten "your sailing bug" is still daunting me. Especially your logfile reporting an "oversegmentation" worried me.
This basically means there is an unidentified problem ...
Could never reproduce but in some places i found possible problems (might be os/compiler dependent).

Would you have a look again ?
Do you still see the oversegmentation report ("number of segments exceeds maximum")?
Do you also see this without using the mask visualizing buttons?

@TurboGit whatever the result of Martins report looks like, there is no performance penalty but some stability improvements ...

**Comment by TurboGit** [comment]
Thanks, the diff for 0094 looks like something fixed recently, see the top-left borders... Maybe the issue is back?

diff

**Comment by jenshannoschwalm** [comment]
Arrgh! Absolutely right and fixed.

**Comment by MStraeten** [comment]
at least  `number of segments exceeds maximum=4711` doesn't occur now but behaviour keeps weird:
darktable -d pipe: [pr14165.txt](https://github.com/darktable-org/darktable/files/11193866/pr14165.txt)


https://user-images.githubusercontent.com/39386816/230994387-fcb09fca-7920-437f-824f-84d174ce327e.mp4

but - switching images seems to keep the masking:

[norefresh.txt](https://github.com/darktable-org/darktable/files/11193912/norefresh.txt)


https://user-images.githubusercontent.com/39386816/230996366-26920f5a-cf6e-479a-ba07-14a1ee843d0b.mp4

**Comment by jenshannoschwalm** [comment]
Thanks. So this pr does what it should :-) Still don't understand the issue you constantly report, btw i can't see the video ???

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
