### PR TITLE
Add raw overexposure indication

### PR DESCRIPTION
**Pull request by LebedevRI**
I wanted this for a while...

Has 3 modes of operation:
1. **mark with CFA color**
If the clipped pixel was red (according to `FC()` / `FCxtrans()`), a red pixel will be displayed.
If the clipped pixel was green (according to `FC()` / `FCxtrans()`), a green pixel will be displayed.
2. **mark with solid color**
If the raw pixel  was clipped, it will be displayed in a given color (one of: reg, green, blue, black)
3. **false color**
If the clipped pixel was red (according to `FC()` / `FCxtrans()`), the red channel for current pixel will be set to _0.0_
window

Sample output with **mark with CFA color** for X-Trans.
There are some Blue, Green and Red pixels clipped (counting to the centre)
x-trans

Same area, but with **mark with solid color**, with **solid color** = **black**
x-trans-solid-color
The more black dots the are contains, the more clipped there are in that area.

Same area, but with **false color**
x-trans-false-color
Not sure if this last mode has any use case, but this was the initial mode i implemented.

Bayer  **mark with CFA color**. With sufficiently exposed image and **threshold** = 0.0, produces familiar-looking pattern :)
bayer-downsampling-artefacts

The same, but with `lens correction`, can be used to create art.
Oo visualize the the lens distortions :)
bayer-downsampling-artefacts-isolines

### CODE REVIEW

**Comment by LebedevRI** [comment]
Note that this works with Bayer and X-Trans, for `uint16_t` buffers.
It does not work as of now for 4COLOR sensors, and for non-`uint16_t` buffers (pre-demosaiced s/m-RAW, PFM, EXR)

**Comment by hanatos** [comment]
this looks so cool. the last two images, what are we seeing there? is it just due to aliasing that this pattern emerges at a different scale? or is it zoomed in a lot?

**Comment by LebedevRI** [comment]
Those 2 images are fully zoomed-out, "fit to screen", with all sidepanels collapsed, on 1920x1080 monitor.

**Comment by LebedevRI** [comment]
Added iop_deps and POTFILES stuff, should be ready to go.

**Comment by LebedevRI** [comment]
Added blind attempt at opencl kernels for rawoverexposed. Do not know whether opencl is right since i have no opencl setup working.
Also, not sure about `tiling_callback()`

**Pull request merged**
