### PR TITLE
Changing RCD demosaicer also in the darkroom preferences

### LINKED ISSUE #8600: How to select the default bayer demosaicer
**The problem**
For bayer raw files the default demosaicer is PPG for performance and historical reasons. We have RCD in dt 3.6 which is comparably fast both on cpu and cl code paths and gives much better output for almost all images.

**Possible Solutions**
1. We expect the user to define camera specific demosaicer presets - a generic preset would require the demosaicer module to check for bayer vs fuji files which it does not atm.
2. We define RCD as the default demosaicer for bayer raws.
3. We define RCD as the default demosaicer for bayer raws only in non "performance over quality" settings as at least on machines with clang compilers and no cl available RCD is slower.

Before i am going in any pr i would like to hear your opinion about this.

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
As hinted by @elstoc this was missing.

Fixes #8600

### CODE REVIEW

**Comment by elstoc** [comment]
We're not having PPG as an option? What will happen with users' existing setting (if it's currently set to PPG)? Will it automatically be reset to RCD by this PR?

**Comment by jenshannoschwalm** [comment]
> Will it automatically be reset to RCD by this PR?

Yes, you might not see it *immediately* in the preferences but for the quality flag we have 3 options and RCD falls back to medium instead of PPG. Don't you think that is ok?

**Comment by elstoc** [comment]
> Don't you think that is ok?

No idea - just trying to clarify how it will work. I set it to "full" anyway, and it's only for zoomed-out mode, in which case I assume it probably doesn't matter all that much.

**Comment by jenshannoschwalm** [comment]
It falls back to RCD if PPG was formerly set. Maybe we should increase the `DT_CURRENT_PERFORMANCE_CONFIGURE_VERSION` anyway for 3.6 and check for more recent hardware in `dt_configure_performance`

**Comment by johnny-bit** [comment]
> Maybe we should increase the `DT_CURRENT_PERFORMANCE_CONFIGURE_VERSION` anyway for 3.6 and check for more recent hardware in `dt_configure_performance`

That would be a great idea tbh :) and "more sane defaults" as requested in #5328 if you may ;)

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by elstoc** [comment]
@jenshannoschwalm: A note for the future - please can you avoid tagging people in a commit because it results in quite a lot of notification spam from github (every time that commit gets included in someone's fork)

**Pull request merged**
