### PR TITLE
Update zh_CN.po

### PR DESCRIPTION
**Pull request by Nameless-J**
I can't program, and not good at English, but I try to translated.
I found a bug: when I finished translating and set the language to Chinese, then I encountered sort disorder when change keyboard shortcut.
This bug doesn't exist in previous translation versions. I don't know why.
Maybe I didn't describe it clearly enough. I'm sorry.

### CODE REVIEW

**Comment by TurboGit** [comment]
Indeed there is some issues:

```
.../git/darktable/po/zh_CN.po:13: nplurals = 1...
.../git/darktable/po/zh_CN.po:16504: ...but some messages have 2 plural forms
.../git/darktable/po/zh_CN.po:1747: number of format specifications in 'msgid' and 'msgstr' does not match
.../git/darktable/po/zh_CN.po:2810: number of format specifications in 'msgid' and 'msgstr' does not match
...s/git/darktable/po/zh_CN.po:2826: number of format specifications in 'msgid' and 'msgstr' does not match
.../git/darktable/po/zh_CN.po:2847: number of format specifications in 'msgid' and 'msgstr' does not match
/usr/bin/msgfmt: found 5 fatal errors
```

This is because the original string has some `%s` that you do not have into your translated string. The number and kind (%d or %d or %.2f for example) of substitutions must match.

**Review by TurboGit — CHANGES_REQUESTED** [review]
Fix string format.

**Comment by TurboGit** [comment]
As an example, the string in 1747 is:

```
#: ../src/control/jobs/control_jobs.c:743
#, c-format
msgid "could not send %s to trash%s%s"
msgstr "无法把 %s 放到回收站"
```

As you see the English strings has to trailing `%s` whereas the translated string has only a single middle `%s`. The final translated string must have 3 `%s`.

**Comment by Nameless-J** [comment]
Thanks, I get it.
I didn't understand the meaning of the two%s, so I ignored them directly. My bad.

**Review by TurboGit — APPROVED** [review]
Looks good now, thanks!

**Comment by Nameless-J** [comment]
It is my pleasure.

**Pull request merged**
