### PR TITLE
Save and restore CMAKE_REQUIRED_FLAGS when trying compiler flags

### PR DESCRIPTION
**Pull request by mazhe**
Language specific flags can then pollute CMAKE_REQUIRED_FLAGS when
CHECK_C(XX)_COMPILER_FLAG is called to test C99/CXX11 support in src/CMakeLists.txt

My use case is that I was trying to make g++ use libc++ runtime (for freebsd/darwin purposes), since darktable internal macro do not reset CMAKE_REQUIRED_FLAGS, it would stay untouch when darktable finaly use the basic CHECK_C_COMPILER_FLAG macro to test C99 support.

I imagine there's a lot of other similar cases (beginning by doing the reverse: having clang++ using the GNU C++ runtime).

### CODE REVIEW

**Comment by LebedevRI** [comment]
Can you show some actual errors that happen without this?
Because i'm mostly sure that `CMAKE_REQUIRED_FLAGS` is internal to that specific macros, and should not overlap between C/C++.

**Comment by mazhe** [comment]
Ok, here is my case, so I have to run g++ with (llvm) c++ runtime to link against the rest of my dependencies that are also linked against it, basicly, I have to set CXXFLAGS and C++ library by hand:

```
CC=gcc6
CXX=g++6
INCLUDES=
CFLAGS=
CXXFLAGS="-nostdinc++ -I/usr/include/c++/v1"
LINKER_FLAGS="-Wl,-rpath,/usr/local/lib/gcc6 -lc++ -lm -lc -lgcc_s -lgcc"

cmake \
    -DCMAKE_REQUIRED_INCLUDES="$INCLUDES" -DCMAKE_REQUIRED_LIBRARIES="$LINKER_FLAGS" \
    -DCMAKE_C_COMPILER="$CC" -DCMAKE_C_FLAGS="$CFLAGS" -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_CXX_FLAGS="$CXXFLAGS" \
    -DCMAKE_EXE_LINKER_FLAGS="$LINKER_FLAGS" -DCMAKE_MODULE_LINKER_FLAGS="$LINKER_FLAGS" -DCMAKE_SHARED_LINKER_FLAGS="$LINKER_FLAGS" \
    [...]   ..
```

This gives me the following cmake output:

```
-- The CXX compiler identification is GNU 6.2.0
-- The C compiler identification is GNU 6.2.0
-- Check for working CXX compiler: /usr/local/bin/g++6
-- Check for working CXX compiler: /usr/local/bin/g++6 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/local/bin/gcc6
-- Check for working C compiler: /usr/local/bin/gcc6 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test _MSSE2
-- Performing Test _MSSE2 - Success
-- Building SSE2-optimized codepaths: ON
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Found little endian system. Good.
-- Performing Test IS_SUPPORTED_PLATFORM
-- Performing Test IS_SUPPORTED_PLATFORM - Success
-- Is the target platform supported: 1
-- Performing Test C_COMPILER_UNDERSTANDS_-Wall
-- Performing Test C_COMPILER_UNDERSTANDS_-Wall - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wall
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wall - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-fno-strict-aliasing
-- Performing Test C_COMPILER_UNDERSTANDS_-fno-strict-aliasing - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-fno-strict-aliasing
-- Performing Test CXX_COMPILER_UNDERSTANDS_-fno-strict-aliasing - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wformat
-- Performing Test C_COMPILER_UNDERSTANDS_-Wformat - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wformat
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wformat - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wformat-security
-- Performing Test C_COMPILER_UNDERSTANDS_-Wformat-security - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wformat-security
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wformat-security - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wshadow
-- Performing Test C_COMPILER_UNDERSTANDS_-Wshadow - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wshadow
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wshadow - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wtype-limits
-- Performing Test C_COMPILER_UNDERSTANDS_-Wtype-limits - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wtype-limits
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wtype-limits - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wvla
-- Performing Test C_COMPILER_UNDERSTANDS_-Wvla - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wvla
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wvla - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wold-style-declaration
-- Performing Test C_COMPILER_UNDERSTANDS_-Wold-style-declaration - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wold-style-declaration
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wold-style-declaration - Failed
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-error=varargs
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-error=varargs - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-error=varargs
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-error=varargs - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-error=address-of-packed-member
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-error=address-of-packed-member - Failed
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-error=address-of-packed-member
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-error=address-of-packed-member - Failed
-- Performing Test C_COMPILER_UNDERSTANDS_-Wframe-larger-than=32768
-- Performing Test C_COMPILER_UNDERSTANDS_-Wframe-larger-than=32768 - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wframe-larger-than=32768
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wframe-larger-than=32768 - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wstack-usage=32768
-- Performing Test C_COMPILER_UNDERSTANDS_-Wstack-usage=32768 - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wstack-usage=32768
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wstack-usage=32768 - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wlarger-than=1048576
-- Performing Test C_COMPILER_UNDERSTANDS_-Wlarger-than=1048576 - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wlarger-than=1048576
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wlarger-than=1048576 - Success
-- Looking for external programs
-- Found perl
-- Found intltool-merge
-- Found desktop-file-validate
-- Missing appstream-util, problems in darktable.appdata.xml might go unnoticed
-- Missing jsonschema, problems in noiseprofiles.json might go unnoticed
-- Found xsltproc
-- Found xmllint
-- All external programs found
-- Performing Test COMPILER_SUPPORTS_C99
-- Performing Test COMPILER_SUPPORTS_C99 - Failed
CMake Error at src/CMakeLists.txt:122 (message):
  The compiler /usr/local/bin/gcc6 has no C99 support.  Please use a
  different C compiler.


-- Configuring incomplete, errors occurred!
See also "/home/mazhe/Devel/graphics/darktable/build/CMakeFiles/CMakeOutput.log".
See also "/home/mazhe/Devel/graphics/darktable/build/CMakeFiles/CMakeError.log".
```

And here's the end of CMakeError.log:

```
Performing C SOURCE FILE Test COMPILER_SUPPORTS_C99 failed with the following output:
Change Dir: /home/mazhe/Devel/graphics/darktable/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_f31d6/fast"
/usr/bin/make -f CMakeFiles/cmTC_f31d6.dir/build.make CMakeFiles/cmTC_f31d6.dir/build
Building C object CMakeFiles/cmTC_f31d6.dir/src.c.o
/usr/local/bin/gcc6    -Wall -fno-strict-aliasing -Wformat -Wformat-security -Wshadow -Wtype-limits -Wvla -Wold-style-declaration -Wno-error=varargs -Wframe-larger-than=32768 -Wstack-usage=32768 -Wlarger-than=1048576 -DCOMPILER_SUPPORTS_C99 -nostdinc++ -I/usr/include/c++/v1 -Wall -fno-strict-aliasing -Wformat -Wformat-security -Wshadow -Wtype-limits -Wvla -Wno-error=varargs -Wframe-larger-than=32768 -Wstack-usage=32768   -std=c99 -o CMakeFiles/cmTC_f31d6.dir/src.c.o   -c /home/mazhe/Devel/graphics/darktable/build/CMakeFiles/CMakeTmp/src.c
cc1: warning: command line option '-nostdinc++' is valid for C++/ObjC++ but not for C
Linking C executable cmTC_f31d6
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_f31d6.dir/link.txt --verbose=1
/usr/local/bin/gcc6   -Wall -fno-strict-aliasing -Wformat -Wformat-security -Wshadow -Wtype-limits -Wvla -Wold-style-declaration -Wno-error=varargs -Wframe-larger-than=32768 -Wstack-usage=32768 -Wlarger-than=1048576 -DCOMPILER_SUPPORTS_C99 -nostdinc++ -I/usr/include/c++/v1 -Wall -fno-strict-aliasing -Wformat -Wformat-security -Wshadow -Wtype-limits -Wvla -Wno-error=varargs -Wframe-larger-than=32768 -Wstack-usage=32768    CMakeFiles/cmTC_f31d6.dir/src.c.o  -o cmTC_f31d6  -Wl,-rpath,/usr/local/lib/gcc6 -lc++ -lm -lc -lgcc_s -lgcc

Source file was:
int main(void) { return 0; }
```

So this fails at `CHECK_C_COMPILER_FLAG("-std=c99" COMPILER_SUPPORTS_C99)` in src/CMakeLists.txt because `cc1: warning: command line option '-nostdinc++' is valid for C++/ObjC++ but not for C`. 

This is because a previous call to CHECK_COMPILER_FLAG_AND_ENABLE_IT() set CMAKE_REQUIRED_FLAGS from CMAKE_CXX_FLAGS, and CHECK_C_COMPILER_FLAG that is called afterwards inherit it.

Hope it helps clarify? The use case is not very friendly, but basically, it may happen each time a C++ only flag is set in CMAKE_CXX_FLAGS

**Comment by LebedevRI** [comment]
> This is because a previous call to CHECK_COMPILER_FLAG_AND_ENABLE_IT() set CMAKE_REQUIRED_FLAGS from CMAKE_CXX_FLAGS, and CHECK_C_COMPILER_FLAG that is called afterwards inherit it.

Does it? I'm sorry, but i do not see where that happens.
Also, which cmake version is that?

**Comment by mazhe** [comment]
In the toplevel CMakeLists.txt (line 256), there's an include to compiler-warnings.cmake which use a darktable _CHECK_COMPILER_FLAG_AND_ENABLE_IT()_ macro. The sub-macro it uses leave the **CMAKE_REQUIRED_FLAGS** either set to **CMAKE_C_FLAGS** or **CMAKE_CXX_FLAGS**.

Later, in src/CMakeList.txt (line 120), the cmake provided _CHECK_C_COMPILER_FLAG()_ macro is used to test if the C compiler supports `-std=c99` argument. This macro inherits **CMAKE_REQUIRED_FLAGS** from the previous _CHECK_COMPILER_FLAG_AND_ENABLE_IT()_.

Another solution would be to reset this variable before testing if the C/CXX compilers accept -std=c99/c++11...

**Comment by LebedevRI** [comment]
Right, sorry, initial explanation was not obvious.
Tested, reproduced, seems to work.

**Pull request merged**
