### PR TITLE
Possibly avoid OpenCL available memory checks [sortof bugfix]

### LINKED ISSUE #12001: OpenCL tuning for memory issue in _opencl_get_unused_device_mem
**Introduction**
Since nvidia 515 driver series becoming available on some distributions there have been some users reporting crashing OpenCL if the tune-for-memory option is active.

I started investigating the changelog of the driver plus again OpenCL docs, not sure if we can have a correct and immediate fix for the problem.

**Describe the bug/issue**
This seems to be directly related to the algorithm that checks the available memory for a device.

Also at least @aurelienpierre reported occasional crashes with 510 driver series, so far not analysed enough to know for sure if this is the checking algorithm or modules taking more cl memory than allowed, wrongly setting parameters in the module's tiling_callback.

**To Reproduce**
Switchin on the tune memory option

**Expected behavior**

stable system

**Platform**

* darktable version : master
* Graphics card     : nvidia
* Graphics driver   : 515 series ???
* OpenCL installed  : yes
* OpenCL activated  : yes

 @TurboGit will further investigate tonight and see what can be done here ...

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Partly fixes #12001 

Since nvidia 515 driver series becoming available on some distributions there have been some users reporting darktable crashes related to OpenCL if the tune-for-memory option is active.

So far investigating the changelog of the driver plus bug reports, there seems to be no fast and best fix here. As the driver is very new (a major redesign so there might be bugs there) and the tuning for memory option had been used by many users without hassle for some time i would like to keep the code as is for 4.0 possibly requiring further fixes. 

In addition to the tuning CL existing options in the tuning CL performance there are 4 new entries offering common "fixed headrooms" plus transfer option.

As before this can be applied at runtime...

### CODE REVIEW

**Comment by AxelG-DE** [comment]
prior testing this, do I need to manually configure the headroomsetting?

**Comment by AxelG-DE** [comment]
Could not resist, tested

I confirm, for me it fixes (but I only provoked that one freeze, did not test more atm)

**Comment by elstoc** [comment]
For me it still fails on the default "memory size" option but works ok on the 400Mb and 600Mb options.

**Comment by AxelG-DE** [comment]
> For me it still fails on the default "memory size" option but works ok on the 400Mb and 600Mb options.

Maybe for me works, because I render full pic on my RTX2070super, but monitors are connected to GTX1060 OC, where Firefox and Thunderbird will sit in memory and 2070 is dt allone

**Comment by jenshannoschwalm** [comment]
> I merely downgraded nvidia-drivers to 470.129.06 and back to 515.48.07

It might very well be the new 515 stuff is yet not perfectly working with modules rebuilding in the different distros. Anyway this pr can't hurt at all ...

**Comment by TurboGit** [comment]
So finally (given the comments above, working for some and still not working for others) should we wait for a more mature NVidia driver or should this be considered for 4.0?

**Comment by AxelG-DE** [comment]
I am not competent enough to judge, this code really comes with no draw backs, or not.
Given my experience, as being not merely representative, I would theoretically prefer to tell 515 users, downgrade and then upgrade again, prior bug reporting.

But that is just me, feel free to dismiss this opinion.

**Comment by TurboGit** [comment]
@jenshannoschwalm : Ok, so I'll test this tomorrow and will merge if it works on my side.

**Comment by elstoc** [comment]
Won't this impact string freeze?

**Comment by TurboGit** [comment]
> Won't this impact string freeze?

Don't know I haven't looked at the PR, but if it changes some strings it sure will break the string freeze and so won't be merged.

**Comment by elstoc** [comment]
It adds new stuff to darktablerc (config enum names and tooltip)

**Comment by jenshannoschwalm** [comment]
Yes it breaks strings... So for 4.01 maybe

**Comment by jenshannoschwalm** [comment]
Closing as #12030 is a far better solution backported from stuff already planned for 4.2

**Pull request closed without merging**
