### PR TITLE
RFC : Initial version - capitalize strings for darktable

### PR DESCRIPTION
**Pull request by TurboGit**
This is the first version of a program to capitalize darktable strings.

This introduced only 26 fuzzy strings in French translation. Some of them are already in current master, so I think this only let ~20 strings to be translated (corner cases that I don't fell important to support as easy to clear manually).

If you want to try you need to:
- `$ rm build`
- install an Ada compiler, on GNU/Debian : `$ apt install gnat`
- run the script : `$ ./doit-run`

This certainly needs more testing on my side, but as this feature has been requested quite some time here it is.

Note that this only change the default English text. The translations are not touched and so it will be to each translator to decide what to do. I may adapt the program to capitalize the translations if needed.

**EDIT: This won't be merged, that's only temp tools to convert the code.**

### CODE REVIEW

**Comment by parafin** [comment]
Could you please clarify what you mean by CamelCase? CamelCase is about capital letters inside one word, where would it be applicable in darktable?..

**Comment by TurboGit** [comment]
Indeed, wrong term I meant capitalize the first letter of a sentence.

**Comment by TurboGit** [comment]
image

image

image

**Comment by TurboGit** [comment]
I have pushed a commit with the translated English UI for testing purpose.

@dterrahe : If you have some spare cycle you can help me... I don't understand why I had to lowercase the "zoom" in `navigation.c`. Without this dt crash at startup looking for an action for zoom and it fails to get it.

In my conversion script I have added this to workaround the problem:

`$ sed -i 's/N_("Zoom"), _("Image zoom level")/N_("zoom"), _("Image zoom level")/g' src/libs/navigation.c`

The code changed is:

```
  DT_BAUHAUS_COMBOBOX_NEW_FULL(d->zoom, darktable.view_manager->proxy.darkroom.view,
                               NULL, N_("zoom"), _("Image zoom level"),
                               -1, _zoom_changed, NULL,
                               N_("Small"),
                               N_("Fit"),
                               N_("Fill"),
                               N_("50%"),
                               N_("100%"),
                               N_("200%"),
                               N_("400%"),
                               N_("800%"),
                               N_("1600%"));
```

But "zoom" in DT_BAUHAUS_COMBOBOX_NEW_FULL is a label and should be translated as for all others call to   DT_BAUHAUS_COMBOBOX_NEW_FULL. Not sure why this one is causing trouble!!!!

**Comment by TurboGit** [comment]
@dterrahe : I think I found the issue actually, the section is created as "Zoom" instead of N_("Zoom").

`ac = dt_action_section(&darktable.view_manager->proxy.darkroom.view->actions, "zoom");`

**Comment by TurboGit** [comment]
Will fix this on master.

**Comment by dterrahe** [comment]
Yes, as we saw in #12281 a change like this will cause pain for the inputng framework.

I've already started working on making the pre-change code more resilient to your script. In this case marking
`  ac = dt_action_section(&darktable.view_manager->proxy.darkroom.view->actions, N_("zoom"));`
with the N_() brackets, so it also gets upcased. Some of the comparisons in accelerators.c would need to be case insensitive for people's existing shortcutsrc files to survive the transition and even some strings that will never be translated (because they only go into the config file) shall be marked with N_() so that your script upcases them, otherwise shortcutsrc will forever be a mixture of cases.

I'll likely submit a PR in the next few days.

I'm OK with the problems that cause crashes, because they are easy to detect and fix. Some others won't but there are at least classes of issues I've started looking for. It is more the unexpected idiosyncratic issues that I fear will haunt us for a while. Stuff that might stop working and people not noticing for a while and only much later realising that an untranslated string was being compared to an untranslated string from somewhere else where only one of the two was marked with N_() and therefore got picked up by your script. But maybe I'm too pessimistic about this.

**Comment by TurboGit** [comment]
New version pushed.

@dterrahe : Our messages/work crossed... I see that now all the shortcuts are broken on my version. Probably related to what you described...

**Comment by ptilopteri** [comment]
If you are going to change to using upper case for names and labels, wouldn't "Metadata Editor" suit better than "Metadata editor"

personally, I didn't mind all lower case, or for that matter, all upper case.

I believe proper "English" usage would have both words start with upper case (capitalized).

**Comment by TurboGit** [comment]
> If you are going to change to using upper case for names and labels, wouldn't "Metadata Editor" suit better than "Metadata editor"

The question is how to make this automatic? What is the rule? For long sentence you certainly don't want to upper case all first letter?

**Comment by TurboGit** [comment]
BTW, I think if we go this way my Ada program could also always update RGB, if you look above the module name for filmic is : **Filmic rgb**, easy to replace by **Filmic RGB**.

**Comment by dterrahe** [comment]
A random example of the kind of thing I'm worried about, in mapsettings.c:
```
static void _thumbnail_change(dt_action_t *action)
{
  dt_lib_map_settings_t *d = dt_action_lib(action)->data;;

  const char *str = dt_conf_get_string_const("plugins/map/images_thumbnail");
  if(!g_strcmp0(str, "thumbnail"))
    dt_conf_set_string("plugins/map/images_thumbnail", "count");
  else if(!g_strcmp0(str, "count"))
    dt_conf_set_string("plugins/map/images_thumbnail", "none");
  else
    dt_conf_set_string("plugins/map/images_thumbnail", "thumbnail");
  dt_gui_preferences_enum_update(d->images_thumb);
}
```

**Comment by TurboGit** [comment]
> A random example of the kind of thing I'm worried about, in mapsettings.c:

Indeed, all `dt_conf_set/get_string` must be reviewed to ensure that if it is an option (in XML) it must be capitalized.

**Comment by dterrahe** [comment]
As you can probably tell I picked up on this one because a similar thing can happen when selecting an action based on `dt_action_t` ids. But this is unrelated to inputng really and will likely be all over the place. There may be cases where the comparison is only vs a substring (the start) of a selection, so I think this will require really careful manual reviewing. And it is the kind of thing that silently fails, could ruin peoples configurations and maybe their past edits and libraries. (Yes, I'm fear mongering, but would you rather be _too_ careful or _too_ relaxed?)

**Comment by TurboGit** [comment]
For this specific case there is no many occurrences or non-empty value:

```
src/common/collection.c:    dt_conf_set_string(confname, "%");
src/common/collection.c:        dt_conf_set_string(confname, "%");
src/common/darktable.c:    dt_conf_set_string("resourcelevel", (sufficient) ? "default" : "small");
src/common/darktable.c:    dt_conf_set_string("plugins/darkroom/demosaic/quality", (sufficient) ? "default" : "always bilinear (fast)");
src/common/darktable.c:      dt_conf_set_string("plugins/darkroom/demosaic/quality", "default");
src/common/darktable.c:      dt_conf_set_string("plugins/darkroom/demosaic/quality", "default");
src/common/database.c:        dt_conf_set_string("database", "library.db");
src/common/image.c:      dt_conf_set_string("write_sidecar_files", "on import");
src/common/image.c:    dt_conf_set_string("write_sidecar_files", "on import");
src/common/opencl.c:        dt_conf_set_string("opencl_scheduling_profile", "multiple GPUs");
src/common/opencl.c:        dt_conf_set_string("opencl_scheduling_profile", "very fast GPU");
src/common/opencl.c:        dt_conf_set_string("opencl_scheduling_profile", "default");
src/common/pwstorage/pwstorage.c:      dt_conf_set_string("plugins/pwstorage/pwstorage_backend", "none");
src/common/pwstorage/pwstorage.c:      dt_conf_set_string("plugins/pwstorage/pwstorage_backend", "libsecret");
src/common/pwstorage/pwstorage.c:      dt_conf_set_string("plugins/pwstorage/pwstorage_backend", "kwallet");
src/develop/develop.c:            dt_conf_set_string("plugins/darkroom/workflow", "display-referred (legacy)");
src/develop/develop.c:            dt_conf_set_string("plugins/darkroom/workflow", "scene-referred (filmic)");
src/gui/gtk.c:      dt_conf_set_string("ui_last/theme", "darktable");
src/gui/guides.c:  dt_conf_set_string(key, guide ? guide->name : "rule of thirds");
src/iop/temperature.c:    dt_conf_set_string("plugins/darkroom/temperature/colored_sliders", "illuminant color");
src/iop/temperature.c:    dt_conf_set_string("plugins/darkroom/temperature/colored_sliders", "effect emulation");
src/iop/temperature.c:    dt_conf_set_string("plugins/darkroom/temperature/colored_sliders", "no color");
src/libs/export.c:    dt_conf_set_string(CONFIG_PREFIX "resizing_factor", "1");
src/libs/geotagging.c:  dt_conf_set_string("plugins/lighttable/geotagging/tz", name ? name : "UTC");
src/libs/map_settings.c:    dt_conf_set_string("plugins/map/images_thumbnail", "count");
src/libs/map_settings.c:    dt_conf_set_string("plugins/map/images_thumbnail", "none");
src/libs/map_settings.c:    dt_conf_set_string("plugins/map/images_thumbnail", "thumbnail");
```

I know also that I have capitalized some URL & others like `darktable.Com` and `library.Db`. As you say we need to be extra careful to not break something. BTW, that's why I have a full automatic script, we can update on the code base as we like and don't have to worry about merge conflicts... So there is no urgency, and we can even close this PR. Personally I don't care :) All lower-case is fine by me.

**Comment by dterrahe** [comment]
> For this specific case there is no many occurrences or non-empty value:

I don't know what your regexp was, but you also need to catch `dt_conf_set_string(..., s)` where the s is set earlier (maybe based on an `g_object_get_data` where the source takes more time to trace). You could fix `dt_conf_set_string` centrally (by using a case insensitive compare against enum values) at just the price of some performance loss. But the `g_strcmp0` is where the real problem lies.

Similarly I can fix action name comparisons in accelerators.c, but you'll still likely lose some of your modulegroups configurations unless it supports both cases during the transition.

**Comment by dterrahe** [comment]
All cases of `g->contrast = dt_bauhaus_slider_from_params(self, N_("Contrast"));` etc will need to have an explicit name specified in the params introspection comments because the variable name and slider label will by definition _never_ be the same. Notice the "is not a" labels in several modules:
image

This _is_ all fixable, I'm just not sure its worth the effort. Yes, people have been asking about upper case. Most adamantly in tooltips/other "texts", where the risk is much lower and the main problem I would see now is that some are dynamically built using strings that are _also_ used for riskier purposes (think of the recent tooltip changes in the histogram module). Besides of course the bigger challenge of correctly identifying all tooltips. But this could be done conservatively by script and then manually if and when found; again this shouldn't break anything. But I think if we do this, you'll get complaints from people who preferred the lower case, either for historical reasons/just got used to it/liked it or because maybe they feel it actually looks less cluttered/more roomy. Sure @Nilvus could _fix_ that (and the Germans might thank him for it) but the reason you don't see those people complaining now is because they already _have_ what they want. Wait until you take it away.

If people _really_ want _everything_ uppercased, I personally would much _much_ prefer #12243. Yes, that's not the path we would have chosen had we started now, but 

- I think it is zero risk code wise, 
- just adds one translation (unless maintainers of other languages besides English want to offer both options as well) and
- is much easier to automatically generate with a script (run on just one file) than what is needed here. 
- even if the new translation file is not perfect, nobody _has_ to use it and it will get fixed eventually

The main drawbacks are that 
- the code will always need to keep the lower case version (and if most devs were to change to the upper case "translation" they may not notice any lapses) and that 
- for English users we'd introduce a small slowdown that others have dealt with all along. Plus obviously 
- we'd need an english->English translator. 

But it might be thought of as an advantage that English devs would then be better able to notice any missing translation markings that previously didn't affect them.

So I'm now reconsidering the PR with just inputng script-resiliency "fixes" I "promised" earlier. Its not going to be very useful in itself and I'm not going to take on all the other work. I'll wait for where this is going.

**Comment by TurboGit** [comment]
> If people _really_ want _everything_ uppercased, I personally would much _much_ prefer #12243. Yes, that's not the path we would have chosen had we started now, but

But this requires to re-translate the whole UI in any language !

**Comment by dterrahe** [comment]
> > If people _really_ want _everything_ uppercased, I personally would much _much_ prefer #12243. Yes, that's not the path we would have chosen had we started now, but
> 
> But this requires to re-translate the whole UI in any language !

I'm afraid I don't understand what you are saying.

The code (and translation markers) won't change under #12243 so no translator _has_ to do anything. If they decide they _also_ want to switch to uppercase, they can do that (and a script could be run on just their language possibly requiring some manual corrections). Or they could decide to add a new translation with uppercase and maintain both going forward. But as far as I'm aware there are already a few languages that never followed the dt lowercase policy (German for example) and always used upper case in their translation. There is nothing for them to do.

**Comment by elstoc** [comment]
I am going to (again) reiterate my strong objections to this change.

Firstly, it's simply not needed. The only place where this is absolutely necessary is in the tooltips. Here, we're actively going against the rules of grammar (in English anyway) especially where we're putting a lower case letter after a full stop. I guess the only other place where we should really change it are where we're using proper nouns (the names of people or places). "Exposure", for example, is not a proper noun, though you might say it's a title and so "Title Case" might be preferred. For me the use of lower case in the UI is a stylistic decision and I don't greatly object to it. Changing it is not an improvement, just a different alternative.

> The question is how to make this automatic? What is the rule? For long sentence you certainly don't want to upper case all first letter?

Here we hit the main problem I have with this change. There is simply no way to easily and reliably apply this change to the dtdocs repository. Even if we could, the fact that we use weblate means manual work for translators. I think we would spend the next year and very many man-hours updating dtdocs (and still miss stuff) and as a result I currently do not intend to reflect the change in the documentation. Even if someone does the work and submits a PR, I would still remain reluctant to merge

**Comment by Nilvus** [comment]
I agree with @dterrahe and @elstoc. This is not so easy and obvious to do such change. And more important, we need to avoid adding too much work that's not so important. Most users are not used to how languages are written. And dtdocs is already something that need work as it is. No need to add more.

Thus, if we could also avoid changing CSS to fix what this will "break" regarding UI (cluttering noticed by @dterrahe above), it will be better. I prefer avoid working on such thing.

I understand of course that capitalize first letter would be more natural, but work this will need and things this will break, this really not worth the effort.

**Comment by victoryforce** [comment]
> But as far as I'm aware there are already a few languages that never followed the dt lowercase policy (German for example) and always used upper case in their translation. There is nothing for them to do.

Yeah, you are right! I will add to this list of not lowercased languages for completeness:
- Finnish
- Italian
- Russian
- Spanish (looks like they choose to not capitalize GUI widget labels, but make all other texts grammatically correct)

Soon I will also start changing the Ukrainian translation to the correct grammar. I mean correct capitalization in tooltips, or rather in all places where there are periods that end sentences.

In #12243 I chose "Sentence case" for widget labels, but now I'm getting more and more arguments that "Title Case" seems more familiar or natural looking to many. By the way, another advantage of correcting the case with the help of gettext translation is that if the user feedback shows that they are more used to a different style, it is extremely easy to change it without interfering with the source code - just make changes to the translation.

**Comment by paperdigits** [comment]
Speaking as a user, I tried this some time ago (I had thought I did it with CSS but maybe I just changed the strings file or something of the like) and I did not care of it at all. We're too far down this path at this point and it doesn't add anything in terms of usability for me at this point. The capital letter in the module names just looks annoying.

As someone who contributes a little bit to docs, this will just be more and more work, and the docs for 4.2 aren't even finished because nobody really wanted to help. This will also introduce work for our translators, which we try pretty hard to minimize because we have few enough people doing that as well.

**Comment by dterrahe** [comment]
As a fun experiment, insert the following after https://github.com/darktable-org/darktable/blob/80a8d09775d7c8836a794f56d7fddb2b7e0278f7/src/bauhaus/bauhaus.c#L182
```
  attr = pango_attr_text_transform_new(PANGO_TEXT_TRANSFORM_CAPITALIZE);
  pango_attr_list_insert(attrlist, attr);
```

(this does the _opposite_ of what we want; it Title Cases bauhaus but _not_ tooltips).

**Comment by elstoc** [comment]
> I believe proper "English" usage would have both words start with upper case (capitalized).

Yes, sentence case is _worse_. If you're going to do it (please don't) then it needs to be Title Case, but then there are some words you can't change (e.g. "Diffuse or Sharpen" is correct, but "Diffuse Or Sharpen" is not).

**Comment by TurboGit** [comment]
I surrender....

**Comment by dterrahe** [comment]
I think there is _some_ consensus that it would be beneficial (and low risk) to Sentence case tooltips that contain actual sentences. I don't know what the specific rules would be; we have a lot of "sentences" without full stops, where capitals might look wrong but arbitrarily other tooltips _do_ have full stops (and commas, sometimes, especially when multi-line) so maybe a lot of that would need cleaning up before adding capitals would be an improvement.

Do you think that this script could at all be adjusted to process just tooltips or would that be a much more complex proposition (because the translation files would only be partially processed, for one thing)? Not for you to start working on now, but for people to keep in mind when they formulate their "rules" for fixing tooltips.

**Comment by elstoc** [comment]
Agreed, tooltips would be pretty safe and sentence case would be more "correct" and easier to apply. There would still be a bunch of manual work as well, for those cases where a simple rule couldn't be reasonably applied, but I guess that would be lower priority.

**Pull request closed without merging**
