### PR TITLE
adobe_coeff: Fujifilm X-T30 II support

### PR DESCRIPTION
**Pull request by kmilos**
Partly addresses https://github.com/darktable-org/darktable/issues/10755

### CODE REVIEW

**Comment by kmilos** [comment]
@TurboGit Please also tag this one for 4.0

**Comment by TurboGit** [comment]
Done!

**Comment by LebedevRI** [comment]
I will not be reviewing any further changes to the `src/external/adobe_coeff.c`
Please just fix #10635.

**Comment by kmilos** [comment]
Dropping in favor of https://github.com/darktable-org/darktable/pull/11221

**Pull request closed without merging**
