### PR TITLE
po/fix workflow none

### LINKED ISSUE #13746: White preset balance not saved correctly
**Describe the bug/issue**

I do not use any workflow and prefer personal auto presets ones. Since this month (probably since some updates on presets in darktable), I see my white balance preset not applied as it should.

As I use presets with scene referred, I have saved a preset to auto-apply white balance to D65, bulb. But now, preset is applied to manual, not D65 (bulb icon).

I tested 2 times to delete preset and create it again. Each time, same thing. Anyway, this preset works as expected until I restart darktable.

@TurboGit: probably for you.

**Expected behavior**

Keep preset on white balance as it was saved.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : master

### PR DESCRIPTION
**Pull request by TurboGit**
temperature: Check for scene-referred mode when using None workflow.
    
When using a workflow None one can still auto-enable modules
white balance & color calibration using presets. In this situation
the white balance module defaults must be scene-referred.
    
Fixes #13746.

### CODE REVIEW

**Comment by Nilvus** [comment]
It's better, my white balance remains as it is (with no more manual set instead of D65 that I've saved). But if I have my auto-preset on white balance (to D65) and on color calibration set, if I compress by clicking on Original on darkroom, my white balance preset is not auto-applied.

I also have sometimes some red warning, even if white balance is ok regarding color calibration (on both modules) when updating some settings on other modules. But it's a quick refresh issue. This don't happen if I use filmic workflow.

**Comment by TurboGit** [comment]
> my white balance preset is not auto-applied.

I cannot reproduce that. I have tried to compress the history at least 20 times.

> I also have sometimes some red warning, even if white balance is ok regarding color calibration (on both modules) when updating some settings on other modules. But it's a quick refresh issue. This don't happen if I use filmic workflow.

Cannot reproduce this either.

I have made some improvements in last version. I don't think it will improve things there but we never know.

**Comment by TurboGit** [comment]
@Nilvus : This PR is for me a good move. Not perfect as you have issues but I think those are separate issues as I cannot reproduce. But at least I have reproduced the original issue and this works for me now. Maybe we should handle the other problem in another issue?

**Comment by Nilvus** [comment]
I agree. I didn't test your last update of that PR but I will not be able until probably next week. So ok to merge that. WIll be better to test that more in following days/weeks on master. If I found a better way to reproduce, I will post another issue. Or will continue with workflow filmic (it works great). Thanks for your work.

**Pull request merged**
