### PR TITLE
Fix filmicrgb highlights cpu code

### LINKED ISSUE #15203: Without OpenCL, filmic's hl-reconstruction produces artifacts.
### Describe the bug

Without OpenCL, filmic's hl-reconstruction seems to produce artifacts.

### Steps to reproduce

Find a RAW with (some seriously) blown out highlights.
Enable HL reconstruct in filmic, play with some values. 
Moste visible when lower the treshold a bit, raise iterations of hq-rec., and lower the bloom<->reconstruct slider.

### Expected behavior

_No response_

### Logfile | Screenshot | Screencast

OpenCL on:

Screenshot_20230906_235027

OpenCL off:

Screenshot_20230906_235116

### Commit

_No response_

### Where did you install darktable from?

OBS

### darktable version

4.5.0~git328.1aca07c6-10447.5

### What OS are you using?

Linux

### What is the version of your OS?

Tumbleweed

### Describe your system?

Operating System: openSUSE Tumbleweed 20230902
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.4.12-1-default (64-bit)
Graphics Platform: X11
Processors: 12 × 12th Gen Intel® Core™ i5-12500T
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 770

### Are you using OpenCL GPU in darktable?

No

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

RAW + XMP:

[000.tar.gz](https://github.com/darktable-org/darktable/files/12542895/000.tar.gz)

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Fix filmicrgb highlights cpu code

1. The wavelet calculating code has been fixed
2. per thread float arrays use common code now
3. some gboolean and const fixes.
4. while being here also minor opencl improvements

Fixes #15203

### CODE REVIEW

**Comment by ralfbrown** [comment]
I've been looking at this PR to see how I broke things during my optimization in the spring, and the only thing I can see is that you reverted my interleaving of the details calculation with the blurring for better cache hits and one less OpenMP loop's setup overhead.  But I just can't figure out how that might have caused the problem...

BTW, the bug report points out that we probably need an additional Filmic-HLR regression test, since the existing one passed.

**Comment by jenshannoschwalm** [comment]
> But I just can't figure out how that might have caused the problem...

I also stared at the code and finally "reverted" your optimizing commit and that interleaving stuff just did not click-in here :-) For the loop, as we need it again immediately no special cache-bypassing code.

**Comment by TurboGit** [comment]
Reproduced, before this PR:

image

After:

image

Test added.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
