### PR TITLE
database: Allow nested transaction.

### PR DESCRIPTION
**Pull request by TurboGit**
The transaction is only done at the top level and an error message is reported when a nested transaction is detected.

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
The long description is wrong now after default change,I missed that.

**Comment by TurboGit** [comment]
> The long description is wrong now after default change,I missed that.

Fixed now.

**Comment by TurboGit** [comment]
I have reviewed the idea of merging the auto-save & undo and don't find this appealing as both are having different goal and delay and I find it clearer to have both clearly separated.

**Comment by jenshannoschwalm** [comment]
I'm fine with that of course. Just let me know if you want me to reopen the saving pr.

**Comment by TurboGit** [comment]
@jenshannoschwalm : BTW, why remove the save of XMP altogether. This is not needed for recovering after a crash if the DB have been updated (auto-saved)?

**Comment by jenshannoschwalm** [comment]
Yes, being glad you stepped in and fixed the database thing.

Removing xmp saving would just leave dB and xmp not synchronized incase of a crash, right?

Using dB in memory would then fail?

**Comment by TurboGit** [comment]
> Using dB in memory would then fail?

Good point, missed that indeed.

**Comment by TurboGit** [comment]
Let me know if it looks good to you and then I'll merge.

**Comment by jenshannoschwalm** [comment]
It does 😊 but I have no idea what the dB code changes mean so can't help.

**Comment by dterrahe** [comment]
I happened to come across `dt_dev_write_history_ext` and `_dev_write_history` in a different context. They seem to do very similar things, so I wonder why they couldn't be merged? `_dev_write_history` is only called from `dt_dev_read_history_ext` and I _think_ it would benefit from transactions as well, both for the safety and the speed improvements.

The other optimisation that could be done here is to integrate the loop over the individual history items into `dt_dev_read_history_ext`. This would allow the three prepared sqlite statements to be reused instead of having to be parsed and destroyed for every single item.

**Pull request merged**
