### PR TITLE
Remove deprecated properties.

### PR DESCRIPTION
**Pull request by Christian-Kr**
Hello everyone,

both properties are deprecated. I just removed them, or replaced them with other methods. The only thing I see as a result, is the bigger checkbox here on a high definition display. I would say, they now have the right size, like the other checkboxes. I cannot test how this looks on different displays or scales.

Maybe someone else can test this code.

Thanks in advance.
Greetings

### CODE REVIEW

**Comment by TurboGit** [comment]
When you see a diff on the UI it would be nice to have some screenshots. Easier for everyone to understand the actual change. TIA.

**Comment by Christian-Kr** [comment]
> When you see a diff on the UI it would be nice to have some screenshots. Easier for everyone to understand the actual change. TIA.

I will keep that in mind for the next time.

Thanks.

**Comment by zisoft** [comment]
> The only thing I see as a result, is the bigger checkbox here on a high definition display. 

I tested this PR on macOS and Windows and I cannot see any difference in the checkboxes.

**Comment by Christian-Kr** [comment]
In order to make the whole migration inside a single branch, close this one and merge the branch Christian-Kr:krippendorf/gtk4_prepare_001 into Christian-Kr:krippendorf/gtk4.

This PR is not needed anymore.

Greetings

**Pull request closed without merging**
