### PR TITLE
basics : allow colorpickers to work as intended

### LINKED ISSUE #7730: Basic adjustments list: color pickers don't work
DT git master on Windows 10
When adding sliders with associate color picker to the new basic adjustments list
immagine
the color pickers don't work. trying to use one of the wil result in making also the global color picker non functional, even when going back and forth to lightable or even restarting DT. 
Only going to the full module and using the color picker from there unlocks the global color picker

### PR DESCRIPTION
**Pull request by AlicVB**
this fix #7730

colorpicker that comes with widgets needs the module focus to work correctly. So we don't prevent modules to have focus when working with basics widgets but we desactivate one by one all all "on canvas" actions and expose, except colorpicker.

### CODE REVIEW

**Comment by Mark-64** [comment]
Tested and it works ok for me

**Comment by TurboGit** [comment]
A small issue with the color picker on the basic module:
1. activate the color picker
2. select an area
3. select another module group (tonnng for example)
4. and see that the color picker area is still displayed on the canvas

**Review by TurboGit — CHANGES_REQUESTED** [review]
need to deactivate color pickers when leaving the basic module group

**Comment by AlicVB** [comment]
@TurboGit : it was not specific to basics group, it was for all groups : 
1. select base group
2. open filmic (for example)
2. activate a color picker
3. switch to another group

Should be fixed by last commit

**Comment by TurboGit** [comment]
Looks good now! Thanks.

**Pull request merged**
