### PR TITLE
preferences: remember previous dialog size

### PR DESCRIPTION
**Pull request by elstoc**

### CODE REVIEW

**Comment by elstoc** [comment]
Something seems to be enforcing a minimum width and I can't work out what. Anyone got any ideas?

**Comment by TurboGit** [comment]
> Something seems to be enforcing a minimum width and I can't work out what. Anyone got any ideas?

The content of the widest tab? There is no ellipsis for the labels. Just a guess.

**Comment by elstoc** [comment]
It looks like it's the textview fields. If you expand the window the textview fields will grow but refuse to shrink again. I can amend it so that when you reduce the size, the tabs with the textview fields get a horizontal scroll bar. At least that way you can reduce the size. Then the next time you open the window it all displays correctly.

**Comment by elstoc** [comment]
I can't find an alternative - it's possible it might be a gtk bug (https://gitlab.gnome.org/GNOME/gtk/-/issues/1030).

As I say it resolves once you close and reopen the dialog so I think this is probably as good as it gets (barring further inspiration).

**Comment by TurboGit** [comment]
Far better this way, so merging now. Thanks.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
