### PR TITLE
Bugfix: Harden pixelpipe cache

### LINKED ISSUE #12798: crash when editing an old image and disabling 'crop and rotate'
**Describe the bug/issue**
I get a crash when I disable 'crop and rotate' (the only optional module I have enabled).

**To Reproduce**

1. Get the files from https://tech.kovacs-telekes.org/files/dt-crash-2022-10-06/
2. Open the raw
3. Disable 'crop and rotate'
4. See error (see log I uploaded).

**Expected behavior**
No crash

**Which commit introduced the error**
I don't know. I can bisect if I must, but I hope the logs are enough.

**Platform**

* darktable version : e.g. 4.1.0+865~g70da6dcc8
* OS                : `Linux 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Linux - Distro    : Ubuntu 22.04
* Memory            : 64 GB
* Graphics card     : N/A
* Graphics driver   : N/A (happens with and without OpenCL)
* OpenCL installed  : yes
* OpenCL activated  : yes, no (happens both ways)
* Xorg              : 7.7+23ubuntu2
* Desktop           : KDE 5.24.6-0ubuntu0.1 
* GTK+              : 3.24.33-1ubuntu2  
* gcc               : 11.3.0
* cflags            : N/A
* CMAKE_BUILD_TYPE  : Release, RelWithDebInfo, Debug (happens with all)

**Additional context**
The image was initially edited using some old version, whatever was current in May 2020.
The crash happens also if I reset 'crop and rotate', instead of disabling it.
There is no issue if I discard the history, the image can be loaded.

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
The central function geting a cacheline buffer in the pixelpipe is `dt_dev_pixelpipe_cache_get()`.

A valid cacheline is defined by equality of hash, this seems to be not correct in all cases, we might have a remaining buffer with less size than requested but identical hash.

This pr does some hardening
- fully resetting pointers in `dt_dev_pixelpipe_cache_cleanup()` - probably not necessary but not hurting
- make an additional check for requested buffer size in `dt_dev_pixelpipe_cache_get()` and possibly write a debug message to console.

Likely this only happens if there is some problem calculating the hash in some module - at least we might be able to track this via the debugging message.

Fixes #12798

Might also be the root cause of #12120 as the cache-line-hit check worked the same way in pre-4.2 versions.

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
Some additional analysis after carefully checking roi issues. While processing the pipeline we possibly extend roi, this changed size is not reflected by the hash!

**Comment by kofa73** [comment]
Looks great, I can no longer reproduce #12798 with this applied. Thanks!

**Comment by jenshannoschwalm** [comment]
@TurboGit this in fact is a very old problem in the cache code just rarely seen as the cache was hit in so few cases.
There are a few more places to be checked & fixed for such rare cases. Will do tonight.

Currently I think this bug might be the root cause of some strange crashes reported...

**Comment by TurboGit** [comment]
> @TurboGit this in fact is a very old problem in the cache code just rarely seen as the cache was hit in so few cases. There are a few more places to be checked & fixed for such rare cases. Will do tonight.
> 
> Currently I think this bug might be the root cause of some strange crashes reported...

I'm really impressed! Thanks a lot for tracking this down.

**Comment by jenshannoschwalm** [comment]
@TurboGit done; added code to disable an invalid cacheline due to not meeting size requirements, also for testing an available cacheline.

BTW, if you stumble across an issue you think being related to OpenCL or the pixelpipe feel free to assign me. (can't do that myself)

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
