### PR TITLE
thumbnail: gtk-critical fix

### LINKED ISSUE #7397: console message Gtk-CRITICAL
**Describe the bug**
Number of console messages selecting a folder in collect:
(darktable:34744): Gtk-CRITICAL **: 10:48:06.530: gtk_widget_set_size_request: assertion 'height >= -1' failed

Here is the backtrace:

```
Thread 1 "darktable" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff7719202 in g_logv () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff7719202 in g_logv () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff771946f in g_log () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff7dd64fe in dt_thumbnail_create_widget
    (thumb=thumb@entry=0x555559385bc0)
    at /home/philippe/git/dt/src/dtgtk/thumbnail.c:1106
#3  0x00007ffff7dd737e in dt_thumbnail_new
    (width=102, height=102, imgid=imgid@entry=44482, rowid=rowid@entry=17, over=DT_THUMBNAIL_OVERLAYS_NONE, zoomable=zoomable@entry=0, tooltip=1)
    at /home/philippe/git/dt/src/dtgtk/thumbnail.c:1299
#4  0x00007ffff7de087e in dt_thumbtable_full_redraw
    (force=<optimized out>, table=<optimized out>)
    at /home/philippe/git/dt/src/dtgtk/thumbtable.c:1818
#5  dt_thumbtable_full_redraw (table=0x555557791a80, force=1)
    at /home/philippe/git/dt/src/dtgtk/thumbtable.c:1713
#6  0x00007ffff7de1a03 in _dt_collection_changed_callback
    (instance=<optimized out>, query_change=<optimized out>, imgs=<optimized out>, next=<optimized out>, user_data=0x555557791a80)
    at /home/philippe/git/dt/src/dtgtk/thumbtable.c:1406
#7  0x00007ffff3b29d1d in  () at /lib/x86_64-linux-gnu/libffi.so.7
#8  0x00007ffff3b29289 in  () at /lib/x86_64-linux-gnu/libffi.so.7
#9  0x00007ffff6a388ec in g_cclosure_marshal_generic ()
    at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff6a38092 in g_closure_invoke ()

```

**To Reproduce**
When I double click on folder in collect module to select it, I often (but not always) get several console messages 

Please let me know if other tests need to be done.

**Platform:**
 - Darktable Version: current master
 - OS: debian 10

### PR DESCRIPTION
**Pull request by phweyland**
fixes #7397 
This is a proposal, it works for me and I don't see any side effect, except maybe some speedup as the image cache is not required.

### CODE REVIEW

**Comment by TurboGit** [comment]
This reverts part of 794782791588f0b0762db0dc8f7d63e31275f971 which is a recent change from @AlicVB to avoid flickering. I doubt this change is correct. Let's get feedback from @AlicVB .

**Comment by phweyland** [comment]
> This reverts part of 7947827 which is a recent change from @AlicVB to avoid flickering. I doubt this change is correct. Let's get feedback from @AlicVB .

If the sizing is really necessary the fix could be (instead of the former test):

      if(ar > 0.0001)
      {
        if(ar < 1.0)
          iw = ih * ar;
        else
          ih = iw / ar;
      }

**Comment by johnny-bit** [comment]
@phweyland - you forgot "#" before issue ID and so it won't autoclose nor autolink issue...

anyway - it seems like the issue here is that aspect_ratio isn't filled immediatelly when importing image, but it is later filled. The image import routine seems to read as little as possible and release as quickly as possible, so i'd vote for 

`if ar > epsilon do smart_stuff else do default_stuff`

epsilon being small enough value. eg `FLT_EPSILON` or used in curve tools `2 * FLT_MIN` or something similar ;)

**Comment by TurboGit** [comment]
> If the sizing is really necessary the fix could be (instead of the former test):

Sounds like this was the intended code indeed!

**Comment by phweyland** [comment]
> you forgot "#" before issue ID and so it won't autoclose nor autolink issue...

Indeed ... Thanks !

**Comment by TurboGit** [comment]
This latest version looks good to me. Thanks.

**Comment by AlicVB** [comment]
indeed, it's my fault :( I'll review and test tomorrow.

**Review by AlicVB — APPROVED** [review]
Agree with the code and tests are ok on my side... so : perfect !
Thanks a lot for fixing my errors ;)

**Comment by TurboGit** [comment]
Thanks!

**Comment by TurboGit** [comment]
Merged on master and 3.4.1.

**Pull request merged**
