### PR TITLE
Print upscale

### PR DESCRIPTION
**Pull request by TurboGit**
This allow to upscale a picture to fit in the selected page. The information about the scale factor and the equivalent DPI is displayed.

### CODE REVIEW

**Comment by houz** [comment]
Since this will allow exporting upscaled images it's not ready for merge until we came to a conclusion if we want to allow that. We should keep this open and once we decided if we want to allow normal upscaled exports I will merge this PR and fix according to the intended mode of operation.

**Comment by TurboGit** [comment]
Ok, le me know if there is anything I need to fix or need to do for this to be merged. Thanks.

**Comment by TurboGit** [comment]
Note also that one option could be to allow upscaling only for the print module.

**Comment by houz** [comment]
For the time being I am adding a new option to allow upscaling to the export lib. Provided hanatos agrees I will push that. You don't have to do anything.

**Comment by TurboGit** [comment]
Thanks a lot Tobias!

**Comment by houz** [comment]
Merged manually.

**Pull request closed without merging**
