### PR TITLE
Align always-on icon

### LINKED ISSUE #5543: always on button size, again
I thought that after #5445 and cc0bc1d the alignment of icons/labels in module headers was solved, but apparently it's not

icons

no_icons
 
current master, Windows 10

### PR DESCRIPTION
**Pull request by Nilvus**
fix #5543 

Was just a forgotten update since last cairo rewrite of this icon.

### CODE REVIEW

**Comment by Nilvus** [comment]
Just see that would be good to also have same space between state icon/module icon than between module icon/label text.

**Comment by aurelienpierre** [comment]
Maybe a bit more space at the left of icons ?
Capture d’écran du 2020-06-18 20-09-54

**Comment by Nilvus** [comment]
> Maybe a bit more space at the left of icons ?

Yes, that was just my comment at nearly same time as yours. I see that you will also need to add new channel reboot mixer on darktable-icons.css file to add at least default round icon.

**Comment by Nilvus** [comment]
@Mark-64: could you test this on Windows and HiDPI.

For all, I test that with 2 different font size to be sure space remains nearly the same. Font-size used : 11 px and 16px.

**Comment by Nilvus** [comment]
So ready for review now.

**Comment by TurboGit** [comment]
I never use the icons theme, for testing this PR I had activated it. The vertical alignment is fixed, but horizontal alignment seems broken (was also before, not a regression):

image

Maybe fixing this as part of the PR would be good!

**Comment by TurboGit** [comment]
I don't have an HiDPI sceen, maybe that explains the difference with Aurélien's screenshot ?

**Comment by Nilvus** [comment]
@TurboGit: I don't have that issue on my side. Be sure I tested horizontal and vertical alignment carefully yesterday by many screenshots taken and zoomed precisely on Gimp to check, and all is good. So probably something else on your side.

The only thing remaining on my side is that some module icons are just 1 pixel less in height than always on. But space is in the top not in bottom like your screenshots. And it's just because some svg icons do not have exactly same size. Some modules icons are at the opposite, 2 or 3 pixels more in height (like contrast equalizer or white balance), so adjusting that pixel space on top will make higher icons more icons. But I only show that when zooming screenshot on Gimp. When I just see darktable view, this pixel space on top of the icons is hard to see. As you can see what I have:

**Comment by Nilvus** [comment]
> I don't have an HiDPI sceen, maybe that explains the difference with Aurélien's screenshot ?

As I don't have HiDPI screen too, I don't think that explains the difference.

**Comment by Nilvus** [comment]
I just understand why you not misalignement. You have a small font size. I've just tested with 10pt font size and I see your alignment issue. I'm not sure it will be possible to fix with CSS as it works great if you use 11pt or 12pt or even 16pt (that was tests I use).

I never use those icons and I hate them...

**Comment by TurboGit** [comment]
Ok, as I don't use icons either I'll merge this and if a fix is possible will do that in another PR. Thanks for the investigation.

**Comment by TurboGit** [comment]
Oh ! That was the last scheduled for 3.2 :) The milestone is now 100% achieved. Of course will certainly have some more fix under the final release !

**Comment by Nilvus** [comment]
Starting from 10.8 pt on preferences window font size make all icons correctly aligned on my side...

I've tested to change margin-top in darktable-icons.css. When increase it a little (0.17 or 0.18em), alignment is good on 10 pt but became broken on higher sizes. For me, that confirm that CSS would not be the good way (or not alone) to be sure alignment is preserved regarding font-size. Or would need to change em to px but that would cause here other issues (especially I think between HiDPI and LoDPI screens.

So I agree with you: better to merge that and we will see if one day someone complain about that alignment (or if someone want to spent time and rework Gtk/cairo code.

**Pull request merged**
