### PR TITLE
RFC: Masks manager: Change order (hierarchy) of shapes

### LINKED ISSUE #14154: Mask manager: Change the order (hierarchy) of shapes in group from bottom to top
Hierarchy of drawn masks is important for boolean operators. 

The mask groups in the mask manager follow the hierarchy of pixel-pipe's modules with the order from bottom to top as expected:

grafik

However, the order of the shapes in the group goes in the opposite direction, from top to bottom:

grafik

Although the shapes are numbered, if you subsequently change the order to properly apply boolean operators to some shapes, the hierarchy is counterintuitive because the lowest-ranking shape is at the top of the list. 

**Describe the solution you'd like**

 The order of the shapes in the group should be from bottom to top, according to their creation.

### PR DESCRIPTION
**Pull request by zisoft**
fixes #14154 

At first I was unsure if it makes sense to reverse the order of the shapes but I must admit that I get used to it after a few minutes of use.

So please test and decide.

Proposal for the release notes text:
Reverse the sort order of the shapes in mask manager groups so that the lowest ranking shape is at the bottom of the group.

### CODE REVIEW

**Comment by TurboGit** [comment]
> So please test and decide.

Looks ok to me, it is a bit like the GIMP layers, probably a better choice indeed.

Now, wondering about the order for the masks outside of a group. Shouldn't they be reordered too? Really no strong opinion, just raising possible choices to ensure we agree on this or not.

**Comment by zisoft** [comment]
Agreed.
I have now reversed the sort order of shapes outside groups as well. So we are consistent everywhere.

**Review by Nilvus — COMMENTED** [review]
I do not use a lot of masks and so never care about order. That change seems good and make sense. And more important, seems that consistency is improved and that's great. But I didn't test (and will not for this one). Thanks for your work @zisoft

**Review by TurboGit — CHANGES_REQUESTED** [review]
Tested and the UI part is ok, the order looks ok to me as I said previously. One issue, when moving a shape up/down as set of error message are sent to the console:

```
(darktable:3732915): Gtk-CRITICAL **: 18:37:06.515: gtk_tree_store_iter_has_child: assertion 'VALID_ITER (iter, tree_model)' failed

(darktable:3732915): Gtk-CRITICAL **: 18:37:13.361: gtk_tree_store_iter_has_child: assertion 'VALID_ITER (iter, tree_model)' failed

(darktable:3732915): Gtk-CRITICAL **: 18:37:36.414: gtk_tree_store_iter_has_child: assertion 'VALID_ITER (iter, tree_model)' failed

(darktable:3732915): Gtk-CRITICAL **: 18:37:52.409: gtk_tree_store_iter_has_child: assertion 'VALID_ITER (iter, tree_model)' failed

(darktable:3732915): Gtk-CRITICAL **: 18:38:03.973: gtk_tree_store_iter_has_child: assertion 'VALID_ITER (iter, tree_model)' failed

(darktable:3732915): Gtk-CRITICAL **: 18:38:25.234: gtk_tree_store_iter_has_child: assertion 'VALID_ITER (iter, tree_model)' failed
```

**Comment by zisoft** [comment]
@TurboGit help :-(
something is messed up, I only want to commit 84e43ed937bf788f4e5ca0b627e317720131359c

**Comment by TurboGit** [comment]
I'll try to squash the needed changes, I'll let you know.

**Comment by TurboGit** [comment]
Ok, no problem, all changes squashed and merged now. Closing. Thanks.

**Pull request closed without merging**
