### PR TITLE
drawn masks: make composition vectorizable

### PR DESCRIPTION
**Pull request by ralfbrown**
Verified pixel-identical on the new 0081 this PR also adds (since we didn't have an integration test which exercises the compositing of drawn shapes in the blend mask).  And I verified by looking at the generated code that GCC8 does indeed vectorize now.  The splitting into separate loops instead of the conditional inside the loop was to enable that vectorization.

### CODE REVIEW

**Comment by TurboGit** [comment]
A conflict to resolve here too! TIA.

**Comment by ralfbrown** [comment]
Rebased and resolved.

**Comment by TurboGit** [comment]
This doesn't compile on my side:

```
[ 24%] Building C object bin/CMakeFiles/lib_darktable.dir/develop/masks/masks.c.o
In file included from /home/obry/dev/builds/darktable/build/src/src/common/opencl.h:34,
                 from /home/obry/dev/builds/darktable/build/src/src/develop/masks.h:21,
                 from /home/obry/dev/builds/darktable/build/src/src/develop/masks/masks.c:18:
/home/obry/dev/builds/darktable/build/src/src/develop/masks/group.c: In function ‘_combine_masks_union’:
/home/obry/dev/builds/darktable/build/src/src/develop/masks/group.c:456:22: error: ‘buffer’ undeclared (first use in this function)
  456 |   dt_omp_sharedconst(buffer, bufs) aligned(dest, newmask : 64) \
      |                      ^~~~~~
/home/obry/dev/builds/darktable/build/src/src/common/darktable.h:98:41: note: in definition of macro ‘dt_omp_sharedconst’
   98 | # define dt_omp_sharedconst(...) shared(__VA_ARGS__)
      |                                         ^~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/build.make:1414: bin/CMakeFiles/lib_darktable.dir/develop/masks/masks.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2358: bin/CMakeFiles/lib_darktable.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
2020/12/26 17:09:35 : darktable (FAILED) build failed with error 2
```

**Comment by ralfbrown** [comment]
Corrected.  I hope, as there were multiple occurrences and I might have missed one.  Can we please revert the -Wfatal-errors?  It's sooo annoying to have to recompile for each compiler message instead of fixing multiple at once.

**Comment by TurboGit** [comment]
Still issues to compile.

**Comment by TurboGit** [comment]
> Can we please revert the -Wfatal-errors? It's sooo annoying to have to recompile for each compiler message instead of fixing multiple at once.

I'm on two mind here. In a way sure it would help have fixing all issues at once but anyway one should build the change and so detect/discover the issues even if one by one. But also, by removing the issue you have a bunch of output before the compilation fails especially when using lot of core to compile and then it becomes hard to find all of them.

**Comment by TurboGit** [comment]
Bad news, still issues:


```
/home/obry/dev/builds/darktable/build/src/src/develop/masks/group.c: In function ‘dt_group_get_mask_roi’:
/home/obry/dev/builds/darktable/build/src/src/develop/masks/group.c:695:44: error: ‘inverted’ not specified in enclosing ‘parallel’
  695 |             buffer[index] = op * (inverted ? (1.0f - bufs[index]) : bufs[index]);
      |                                            ^
compilation terminated due to -Wfatal-errors.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/build.make:1414: bin/CMakeFiles/lib_darktable.dir/develop/masks/masks.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:2358: bin/CMakeFiles/lib_darktable.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
2020/12/26 18:30:16 : darktable (FAILED) build failed with error 2
```

**Comment by ralfbrown** [comment]
Hopefully the last go-around....  (At least this was in the last OpenMP directive in the file.)

**Comment by TurboGit** [comment]
All good now, manually merged into master and 3.4.1.

**Pull request closed without merging**
