### PR TITLE
Laplacian cleanup

### PR DESCRIPTION
**Pull request by ralfbrown**
Combine SSE and scalar alternative functions such that common code only occurs once.  Why would we ever *not* want to run the faster vectorized code if the target supports it?

### CODE REVIEW

**Comment by TurboGit** [comment]
I'm wondering if the best would not be to use clone-targets. Look at the toneequal.c implementation, you'll see the use of __DT_CLONE_TARGETS__ in declaration. This is defined in common/darktable.h as:

`#define __DT_CLONE_TARGETS__ __attribute__((target_clones("default", "sse2", "sse3", "sse4.1", "sse4.2", "popcnt", "avx", "avx2", "avx512f", "fma4")))`

The idea is that only the main std CPU version is implemented and we let the compiler create the sse, avx... versions which will be called depending on the support on the target hardware.

**Comment by parafin** [comment]
> Why would we ever _not_ want to run the faster vectorized code if the target supports it?

To validate both codepaths against each other. It's not used right now I think, but let's not remove this possibility.

**Comment by parafin** [comment]
> I'm wondering if the best would not be to use clone-targets. Look at the toneequal.c implementation, you'll see the use of **DT_CLONE_TARGETS** in declaration. This is defined in common/darktable.h as:
> 
> `#define __DT_CLONE_TARGETS__ __attribute__((target_clones("default", "sse2", "sse3", "sse4.1", "sse4.2", "popcnt", "avx", "avx2", "avx512f", "fma4")))`
> 
> The idea is that only the main std CPU version is implemented and we let the compiler create the sse, avx... versions which will be called depending on the support on the target hardware.

I wouldn't just throw away hand-optimized code in favour of compiler-optimized without some benchmarking first. And even then one has to consider that different compilers are used by users, so results might be unpredictable in real life.

**Comment by parafin** [comment]
Overall I'm don't think this PR should be merged. I'm not sure if it's the case now for all iops, but probably process() shouldn't use SSE intrinsics and #ifdef __SSE2__.

**Comment by aurelienpierre** [comment]
I agree with @parafin, having SSE and plain C intricated like that and branching internally doesn't make the code easier to manage and risks degrading performance in subtle ways. Please keep the SSE and C paths separated, so the branching happens at an high level.

**Comment by TurboGit** [comment]
Since we three devs agree about the bad idea to interleave SSE and standard code I'll close this PR.

**Pull request closed without merging**
