### PR TITLE
Support for regional date and time format in thumbnail tooltips.

### LINKED ISSUE #10763: Date and time format for images are inconsistent
**Describe the bug/issue**
Version 3.8 Windows.
In lighttable mode, the format of the date and time is inconsistent. See attached screen shot.  I'm in the USA, so I prefer month/day/year and 12h time.  The date / time format in the image information window is right.  When you hover over an image, it is wrong.

**To Reproduce**
1. Go to lighttable mode
2. Click on an image
3. observe the image information - fields with a date and time.  For me they are consistent with Windows.
4. Hover over the same image.
5. Note that the date and time format are different.  Not matching the same format as the image information.  Not matching Windows default.

**Expected behavior**
1. date and time format for software should follow the system default.
2. date and time format should be consistent for different operations within a software.

**Screenshots**
2022-01-02 00_51_57-darktable

Windows Date Time Format

**Platform**
* darktable version : 3.8.0
* OS                : Windows 10 21H2 x64
* Memory            :  32 GB
* Graphics card     :  NVidia GTX 1660
* Graphics driver   :  472.12
* OpenCL installed  :  not sure
* OpenCL activated  : not sure
* CMAKE_BUILD_TYPE  :  installed from official .exe

### PR DESCRIPTION
**Pull request by victoryforce**
Resolves #10763.

I'm not sticking to my choice of variable name here and I won't claim that I chose the best option. This is a case where I will not insist on my version, but will gladly make corrections if they make more sense.

The word "localized" in the name seems quite suitable to me, the only thing is that this word itself has a double spelling. On the other hand, spelling with -ize is also acceptable in British English, except that it is used less often.

### CODE REVIEW

**Review by TurboGit — COMMENTED** [review]
Given the definition for %x and %X:

```
%x | The preferred date representation for the current locale without the time.

%X | The preferred time representation for the current locale without the date.
```

So `LOCALIZED` seems ok to me.

We may also want to simply use LOCALE.

```
EXIF.DATE.LOCALE
EXIT.TIME.LOCALE
```

@elstoc : Any preference here?

Also, I suppose those new variables must be added into `src/gui/gtkentry.c`.

**Comment by TurboGit** [comment]
@victoryforce : Thanks, indeed I agree with you.

**Review by TurboGit — APPROVED** [review]
Works for me, just waiting for @elstoc feedback on the naming before merging. Thanks!

**Comment by elstoc** [comment]
I guess I might prefer to go for `EXIF.DATE.LOCAL` and `EXIF.TIME.LOCAL` rather than LOCALE or LOCALIZED. In terms of the spelling, if you did choose the latter, LOCALIZED is the American spelling and we target American English in darktable so it is preferred (even if I may not personally prefer it).

**Comment by kmilos** [comment]
Yes, "local" could be interpreted as time zone adjusted... How about "region(al)", as the title intuitively states?

**Comment by victoryforce** [comment]
I agree with the devil's advocate. Yes, LOCAL is simple and short, but I didn't choose it initially for fear of misunderstanding, as the user might think it means the time in the local time zone. Here's my take on the options:

- EXIF.DATE.LOCALE <--- "locale" is a noun, so this seems illogical, because the last word is better to be a qualifier
- EXIF.DATE.REGION <--- the same as above, an adjective instead of a noun would be better
- EXIF.DATE.LOCALIZED <--- pro: logical, clear; contra: double spelling word, and this spelling less often used in British English
- EXIF.DATE.REGIONAL <--- in my opinion, this is a very good option, but I'm not ready to say that I like it more than the previous one

I hesitate to choose between the last two options... @TurboGit, I want to ask you to make a decision. 🙂

**Comment by elstoc** [comment]
Just to throw another thing in here, while this is governed by LOCALE settings (so I have some sympathy with the suggested use of LOCALE) it's not necessarily regional but more of a user preference. For example there's nothing stopping a (weird) GB user preferring US date formats. So maybe something like FORMATTED might be better?

**Comment by kmilos** [comment]
FWIW, Windows settings call these "Regional format data". Similarly, on macOS, these fall under "Language & Region" settings. Haven't used GNOME/KDE in a while, but I guess it's similar terminology...

**Comment by victoryforce** [comment]
> > So maybe something like FORMATTED might be better?
> 
> Not a bad option either...

👍

**Comment by TurboGit** [comment]
I'll go with REGIONAL given the above comments. FORMATTED is not conveying the information to me, all strings are formatted somehow.

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
