### PR TITLE
Small Bash Improvement

### PR DESCRIPTION
**Pull request by roumano**
Small Bash Improvement : 
- avoid creating uselle subshell
- remove bash depretaced ` `  , replacing them via $( )

### CODE REVIEW

**Comment by houz** [comment]
Just a small remark: that script is not bash but sh! I didn't try your changes and don't know if they are portable.

**Comment by rabauke** [comment]
According to https://www.shellcheck.net the $(...) syntax for command substitution should be supported by every POSIX compatible shell. However, there are subtle differences between the back-quotes syntax and the $(...) syntax, see http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html
Here strings and the <<< syntax are not defined in the POSIX standard. 

Thus, the proposed changes will break/reduce POSIX compatibility. Note that  https://www.shellcheck.net hints to further issues, which are also present in the original script.

**Comment by graudeejs** [comment]
I can confirm, that <<< will break on FreeBSD where /bin/sh is not bash

**Comment by houz** [comment]
The portable part of this had been added in a2231149c467ce9ed19e305de2b236cc9d89b08e already so there is nothing left here it seems. Thank you anyway.

**Pull request closed without merging**
