### PR TITLE
Minor language fixes (se, Swedish)

### PR DESCRIPTION
**Pull request by gernberg**
Fixed some minor issues in the Swedish language file.
Will take a better look at all of the translations when I have the time :)

### CODE REVIEW

**Comment by houz** [comment]
Before merging this we have to get the OK from Richard as he "owns" the Swedish translation. The reason being that it sucks when you have big changes to a .po file that are not committed and someone else changes the file. It's extremely hard to merge those back together.

**Comment by gernberg** [comment]
Thanks for the info :)
Do you often have big uncommitted changes to the .po files / is there an easier way to contribute translation fixes than via a PR?

**Comment by houz** [comment]
I don't know about Richard, but I (responsible for de.po) so have local changes all the time. I am not aware of any easy way to work on translations with several people with a consistent result, but in darktable every language team is free to organize as they want.

**Comment by levitte** [comment]
I'll merge it in manually.  The reason is not so much merge issues like @houz is talking about, but I'd rather avoid the header changes that Poedit made...

**Comment by levitte** [comment]
Changed my mind, automerge was fine.

**Comment by levitte** [comment]
Thank you @gernberg

**Pull request merged**
