### PR TITLE
How to get into a joinable pthread state?

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
EDIT after latest commits, see commit message about it ...

1. Currently the job dispatcher might have pending jobs. These are not processed any more if we test for dt_control_running() in job.c
2. We continue dispatching even in DT_CONTROL_STATE_CLEANUP to get all things done.

3. But how can we know if all jobs are finalized? This might be a way, we increase `pending_jobs` jobs-to-be-done and decrease for finalized jobs.

4. In control_shutdown we have to wait until everything is done.

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
@TurboGit @ralfbrown @dterrahe @zisoft i really need help here.

Is this the way to go? 
Any other ideas?
The up/down-counter doesn't work correctly, can you have a look?

Anyway, see #17961 #17978 for existing problems.

**Comment by ralfbrown** [comment]
Looks reasonable, but I'm not sure it will actually fix the problems, because the way things are currently setup the shutdown should be working (provided dt_control_shutdown isn't called multiple times) - pthread_join blocks until the given thread exits (if it hasn't yet), and each worker thread exits as it finishes its current job or sleep and finds that an exit was requested before we called pthread_join.

**Comment by jenshannoschwalm** [comment]
Er just werde Not aware of this as the joining Part was Not processed. Thus Late errors as @zisoft demonstrated.

**Comment by jenshannoschwalm** [comment]
@zisoft this is exactly the issue I was referring to.

**Comment by dterrahe** [comment]
In `dt_cleanup` `dt_image_cache_cleanup` is called before `dt_control_shutdown`, so there might still be threads wanting to use the caches? If properly mutexed, that might/should not be a problem, but at least when I move the `dt_image_cache_cleanup` and `dt_mipmap_cache_cleanup` calls to _after_ the `if(init_gui)` surrounding `dt_control_shutdown`, the above crash is not (as easily) reproducable here. Hopefully you got this far, or further, already.

**Comment by jenshannoschwalm** [comment]
This has been very hard work the last days. Some things (debug logs or the finalized flags) are not necessary, @TurboGit let me know if you want a stripped down version.

As it is possible that working jobs are continuing in the background after user-request to close darktable we could possibly avoid to quit for UI usability as we could use the pending jobs counter ...

@dterrahe thanks for your hint!

**Comment by jenshannoschwalm** [comment]
Stripping down? No problem for me ...
1. You could just ignore the pending_jobs counter commit for now (Use that in 5.2 for UI feedback ...)
2. I would remove added dt_print() stuff for less code to review although not really relevant
3. I would prefer to keep the 's' to 'control' renaming in the first commit for readability and making stuff static also seems good&safe

**Comment by jenshannoschwalm** [comment]
Just re-force-pushed with extra checks and debug logs removed as not required any more while being very verbose ...

**Comment by jenshannoschwalm** [comment]
> I have a lock when I quit early and can reproduce 100% of the time.

Fixed with last commit ...

**Comment by jenshannoschwalm** [comment]
Hmm, couldn't reproduce one. Could be a race condition so use atomics now.

Also added a simple commit for dtpthreads adding textual output for pthread creation and joining.

**Comment by zisoft** [comment]
Some tests on macOS:

- Splash screen disabled:
- - quit after GUI came up fully: no issues
- - early quit as soon as the main window comes up: no issues
- Splash screen enabled
- - quit immediately after splash screen comes up: some strange effects with the main window but dt quits without issues
- GUI fully started, quit, no issues
- GUI fully started, quit while running the *rotate 10 images* test: This gives a 100% reproducible hard crash with `EXC_BAD_ACCESS` while accessing `gui_module->flags` in line `1374` of `develop/pixelpipe_hb.c`:

https://github.com/darktable-org/darktable/blob/50f0e50ccf0c1dd2534e1f89d54a68e1d6c09576/src/develop/pixelpipe_hb.c#L1348-L1378

**Comment by jenshannoschwalm** [comment]
1. At some places in lua code there are `darktable.control->` with checking for control not being NULL. Ok as only use while control is up and running?

**Comment by jenshannoschwalm** [comment]
@TurboGit the last commit might add some extra safety

**Comment by zisoft** [comment]
Unfortunately not better.
Same crash, same position

Or it crashes with `EXC_BAD_ACCESS` in `control/progress.c`, line `149`:

Bildschirmfoto 2024-12-14 um 22 10 40

**Comment by jenshannoschwalm** [comment]
I got a crash while images exporting after ctrl-q

**Comment by jenshannoschwalm** [comment]
@TurboGit it's sort of a mess i/we all were not aware of the implications of all the things we now do in the background and wanting a safe darktable exit ...

I just force-pushed:
1. in https://github.com/darktable-org/darktable/pull/17984/commits/8891c6c26656834895fc08173b268e4014afb652 there is an additional safety check prohibiting to create a new job if control isnot running any more
2. https://github.com/darktable-org/darktable/pull/17984/commits/b064f9e8bba22f06f63f4504a3a9cff420194093 is just plain renaming maintenance done while analyse and understand ...
3. https://github.com/darktable-org/darktable/pull/17984/commits/7c5b153b8ab4bb75ec3c1fd8372006b981ba22a2 fixes image file I/O problems in background jobs.

**Comment by jenshannoschwalm** [comment]
Just added a fix for not waiting on image import if control is not running any more.

**Comment by jenshannoschwalm** [comment]
@TurboGit One of the first PR's i will do for 5.2 is "Only accept Ctrl-q if no jobs are pending" :-)

**Comment by zisoft** [comment]
It crashes in the first loop

```
  /* wait for kick_on_workers_thread */
  dt_pthread_join(control->kick_on_workers_thread);

  for(int k = 0; k < control->num_threads-1; k++)
    dt_pthread_join(control->thread[k]);          // <-- breakpoint here

  for(int k = 0; k < DT_CTL_WORKER_RESERVED; k++)
    dt_pthread_join(control->thread_res[k]);
```

If I set a breakpoint and single-step through the loop, most of the steps gives no log output. The it comes to a step with lots of log output and that is the step which crashes. The last lines of the log:

```

59.7676 [iop_validate_params] `flip' validated data for type "dt_image_orientation_t", field: orientation (5)
59.7676 [iop_validate_params] `flip' validated data for type "dt_iop_flip_params_t"
59.7676 committed                     [thumbnail]      flip                   1700  enabled  piece hash=9df07eab6adab321
59.7676 synch all modules done        [thumbnail]                                   defaults 0.1505s, history 0.0106s
59.7676 [dt_imageio_export_with_flags]  modules: rawprepare temperature highlights demosaic flip exposure colorin channelmixerrgb sigmoid colorout gamma
59.7676 modify roi OUT                [thumbnail]      rawprepare              100 (   0/   0) 5344x3516 scale=1.0000 --> (   0/   0) 5184x3456 scale=1.0000  ID=37
59.7676 modify roi OUT                [thumbnail]      flip                   1700 (   0/   0) 5184x3456 scale=1.0000 --> (   0/   0) 3456x5184 scale=1.0000  ID=37
59.7676 [export] creating pixelpipe took 0.168 secs (0.330 CPU)
59.7677 [dt_imageio_export] thumbnail imgid 37, 3456x5184 --> 73x110 (scale=0.0212, maxscale=1.0000). upscale=no, hq=no
59.7677 pipe starting             CL1 [thumbnail]                                  (   0/   0)   73x 110 scale=0.0212 --> (   0/   0)   73x 110 scale=0.0212  ID=37, appleamdradeonpro5500mcomputeengine
59.7677 [memory] before pixelpipe process
        max address space (vmpeak):         unknown
        cur address space (vmsize):     41845448 kB
        max used memory   (vmhwm ):         unknown
        cur used memory   (vmrss ):      2067612 kB
```

**Comment by jenshannoschwalm** [comment]
> If I set a breakpoint and single-step through the loop, most of the steps gives no log output. Then it comes to a step with lots of log output and that is the step which crashes. The last lines of the log (started with `-d all`):

@zisoft As there is just one of the threads involved it's random in what position in the loop it "happens", but as there is no imageio system running any more the flip might fail here. So this has been added to the jobs where ctrl-q is understood as "skip-the-rest'

BTW you run ARM or intel? I am absolutely not sure if there are some peculiar things in the _DEBUG mode, even less on MACs. 

Could you re-test?

**Comment by zisoft** [comment]
First try, same crash :(

I'm on an Intel Mac.

> As there is just one of the threads involved it's random in what position in the loop it "happens"

ah, ok. That's my experience here, the crash position in the loop is indeed random.

**Comment by ralfbrown** [comment]
A Lua hang on very early exit is probably the same underlying issue that I encountered while writing the splash screen code, and kept me from displaying any further progress updates after starting up Lua.  I have since been able to trace that hang to the async processing of the Lua startup script.  No luarc, no hang....  Once the script finishes, it is again OK to call dt_gui_process_events().

**Comment by zisoft** [comment]
ok, some things have changed.
I now get two different crashes randomly. **And successful quits as well.**

I send screenshots here with log at the bottom and stacktrace on the left.

The first type is again an  assertion failure:

Bildschirmfoto 2024-12-15 um 16 51 55

And the second type is a `EXC_BAD_ACCESS` in the dbus routines:

Bildschirmfoto 2024-12-15 um 16 53 29

I also removed my luarc but that does not make a difference as these are no early quit attempts.

**Comment by jenshannoschwalm** [comment]
Making this draft for now, as there will be PR's doing maintenance and safety checks to be merged first and this will have to be rebased afterwards.

**Pull request closed without merging**
