### PR TITLE
po/fix colorzones picker

### PR DESCRIPTION
**Pull request by TurboGit**
- Fix color-picker in color zones when module is reset and picker is active
- Also disable color-picker when loosing focus.

### CODE REVIEW

**Comment by Nilvus** [comment]
@TurboGit: seems that a commit here referenced #12311 issue but this PR is not linked. Is this PR fix #12311 issue?

**Comment by TurboGit** [comment]
Yes, two commits are referencing https://github.com/darktable-org/darktable/issues/12311.

**Comment by Nilvus** [comment]
> Yes, two commits are referencing #12311.

Ok, but seems that this PR will not close automatically the issue. Github show no link between them for that.

**Comment by TurboGit** [comment]
@Nilvus : The issue was actually closed when merging. I suppose that at this point GitHub looks at each commit for links with issues.

**Comment by Nilvus** [comment]
> @Nilvus : The issue was actually closed when merging. I suppose that at this point GitHub looks at each commit for links with issues.

Good to know! Thanks for the report.

**Pull request merged**
