### PR TITLE
po/copy dialog

### PR DESCRIPTION
**Pull request by TurboGit**

### CODE REVIEW

**Comment by elstoc** [comment]
Now it feels like the "copy..." and "paste..." buttons need renaming though. Perhaps they could be "copy selected" and "paste selected"

**Comment by TurboGit** [comment]
Why? Don't the ... Is not clear enough? This is a common GUI indication that a dialog will be used, no?

**Comment by elstoc** [comment]
Is it? ok

**Comment by parafin** [comment]
It is indeed a common thing, but having buttons that differ only by these dots is still probably not the best idea. Maybe "copy partially"? "copy selected" sounds like it's referring to selected images (after all when you press, you haven't selected any iops, so they are not "selected" at that point).

**Comment by elstoc** [comment]
"copy/paste parts"? 

"copy partially" doesn't read well.

**Comment by johnny-bit** [comment]
While having pre-selected "safe" modules in dialog is ok, it's very funny to see "copy ... / copy " buttons next to each other (similar to paste)

(i still think wb + lens should be considered "safe" but thats for other PR)
and now I think about something else - you know you can enter copy... dialog, then press cancel, yet it still marks image as copy source and preselected modules are selected for copying... form me more and more @parafin's #6586 makes loads of sense...

**Comment by junkyardsparkle** [comment]
My thought with the naming was that "copy..." would be ok if "copy" was renamed to indicate that it was a "quick" action with no intervening dialog. In any case, it seems like distinguishing the action names clearly would be good not only for buttons, but for clarity in places like keyboard shortcut assignment and maybe even within the code.

**Comment by TurboGit** [comment]
@elstoc : I'll go with "copy/past parts".

**Pull request merged**
