### PR TITLE
minimize copying of configuration/preference strings

### PR DESCRIPTION
**Pull request by ralfbrown**
Add a new utility function `dt_conf_get_conststring` and replace uses of `dt_conf_get_string` by the new function where possible.  This fixes a few memory leaks and eliminates lots of instances of string copying and the associated memory allocation/deallocation.

### CODE REVIEW

**Comment by dterrahe** [comment]
Very nice cleanup again!

Have you considered `dt_conf_get_string_const` instead of `dt_conf_get_conststring`? It would make catchall searches slightly more convenient (without having to resort to regexp), but probably searches for the actual configuration string will be more frequent anyway.

**Comment by elstoc** [comment]
> Have you considered dt_conf_get_string_const instead of dt_conf_get_conststring

I was just about to make exactly the same suggestion

**Comment by dterrahe** [comment]
Slightly/complete OT/tangential I was wondering if you use any tools to find code duplication? Out of curiosity I ran CPD (https://pmd.github.io/latest/index.html) and the output is kind of interesting. Many false positives (it gets confused by lctype.c and knight.c) but it could be useful for @TurboGit to run before merging large PRs. Refactoring (or spotting the need in simple ways like this) is easier _before_ copied code starts to diverge. What do you think?

One of the frequent reasons for duplication of large functions is SSE variants that only diverge in the inner loop. Could possibly be addressed by putting the whole function in a macro and feeding those (non-)SSE bits as arguments. How would you feel about that?

**Comment by ralfbrown** [comment]
OK, I'll rename the new function.

@dterrahe, I had run some duplicate detector last year (forget which one) when looking for code to refactor, but it simply wasn't accurate enough to be worth the trouble.  The story may be different for PRs than for the code base as a whole.  Re: using macros for big functions differing only in the inner loop - big macros are an absolute PITA to edit....  Better to abstract out the common bits as separate functions to be called.

**Comment by dterrahe** [comment]
There are a bunch of things like this:
```
Found a 87 line (635 tokens) duplication in the following files: 
Starting at line 3568 of /home/diederik/darktable.input_system/src/views/darkroom.c
Starting at line 4207 of /home/diederik/darktable.input_system/src/views/darkroom.c
```
which suggest some restructuring would be beneficial

> The story may be different for PRs than for the code base as a whole.

Especially in PRs that introduce new modules. When seeing something like this:
```
Found a 102 line (694 tokens) duplication in the following files: 
Starting at line 1533 of /home/diederik/darktable.input_system/src/iop/clipping.c
Starting at line 584 of /home/diederik/darktable.input_system/src/iop/crop.c
```
that should maybe trigger an agreement on a (possibly post-merge) remediation plan. Either these modules continue in parallel, in which case they should use a `common` file for shared functionality, or one is intended to be much simplified and a lot of the overlap could be simply removed. If there's no plan at inception, what is likely to happen is that fixes will be applied in one, but not the other, module, they start to diverge and duplication is harder to fix (or detect). There will be less testing in the path left behind and more bugs will accumulate. While we still depend on some of the not-refactored functionality, the module should not be allowed to sink in the mud.

The kind of deep cleaning that you do, replacing patterns of a few lines with simplified versions, is probably not something a tool could help much with.

> Better to abstract out the common bits as separate functions to be called.

You are right. The loops themselves presumably will still need to be duplicated because otherwise the compiler can't optimise them differently for OpenMP/SSE/..., right? That's where I thought macros could help, but if it overcomplicates stuff and makes everything unreadable, the maintenance burden just increases.

**Comment by elstoc** [comment]
@dterrahe I know it was just an example, but with that one the intent is to deprecate clipping.c so duplication is Ok here.

**Comment by dterrahe** [comment]
> @dterrahe I know it was just an example, but with that one the intent is to deprecate clipping.c so duplication is Ok here.

I know, but I haven't followed the discussion and am not sure if there is a documented plan somewhere. Given how central clipping is/was, it will need to "supported" "forever" to be able to load/convert old xmps. Bitrotting old modules like that are a real worry to me.

**Comment by elstoc** [comment]
@dterrahe there's an open issue for this (#8834), so we should continue the discussion there, but suffice it to say we do not want to have to change clipping.c since every time we do something else breaks, so we have to accept duplication here or risk breaking a to-be-deprecated module, which is possibly the worst of all worlds.

**Review by TurboGit — APPROVED** [review]
Again a nice and extensive clean-up. Thanks a lot !

**Pull request merged**
