### PR TITLE
c&r : fix double crop with crop module

### LINKED ISSUE #8942: unwanted crop is introduced when crop / crop & rotate are combined
With latest master, a common use case will be to crop with the crop module and do rotation with the crop & rotate module. However, there seems to be some sort of interplay between the two modules meaning that cropping gets messed up when both are enabled.

To reproduce, on a fresh edit:

1. Open the crop module and crop the image (a fairly severe crop to make it more obvious)
2. Open the crop & rotate module and enable it without cropping the image further
3. Collapse the crop & rotate module
4. An additional crop is introduced without request

darktable 3.5.0+2197~g0ee2e87be on ArchLinux

### PR DESCRIPTION
**Pull request by AlicVB**
fix #8942 

this avoid the "double crop" issue when a crop is done and the c&r module has had the focus : 
- in c&r : be sure to disable the crop module, located later in the pipe, when the module has the focus (otherwise gui handles are confused as they can't go outside the visible image)
- in c&r : ensure right transformation when loosing focus. The problem is that when we have the focus, the gui_data values are computed with a transforms that exclude filtered modules. When we loose the focus, we save them to the module params, but at this point, the module is not anymore the "gui_module" so transformations are wrong... That hasn't cause any problem until now because there was no filtered module after c&r in the pipe (except borders, but that only enlarge image, so the clamping take care of that) I've solved that by temporary put back the gui_module and revert once the computation is done...

Note : due to how cropping values are stored (percentage of input image size) if you change crop area in c&r, that will also change the previously defined crop area in crop...

### CODE REVIEW

**Comment by AlicVB** [comment]
same hack done for for crop module, to avoid bugs later or if crop module is moved elsewhere in the pipe

**Comment by elstoc** [comment]
This fix stops C&R rotation from working until the module parameters are committed. Start with a fresh image, open C&R, attempt to rotate. Preview doesn't change. Collapse the module and the angle changes.

**Comment by TurboGit** [comment]
This does not fix the issue for me. The scenario described in #8942 is still reproducible.

**Review by TurboGit — CHANGES_REQUESTED** [review]
Fix not working on my side.

**Comment by AlicVB** [comment]
> The fact that it temporarily disables the crop module while using C&R is really odd too and feels like a fault.

that's unavoidable... imagine the contrary : 
1. crop the image using crop module. say cropx = 10%, cropy = 5% (whatever height and width for the example) this values are applied on the image in entry of the module
2. open c&r and activate it. What you see on screen is the cropped image. But c&r deals with the full image (as placed before in the pipe) so handles should be drawn outside the image on screen...

Note that this is already the case for borders...

**Comment by elstoc** [comment]
> that's unavoidable... imagine the contrary

Perhaps a toast message might help to avoid confusion.

**Comment by AlicVB** [comment]
@elstoc @TurboGit : are you sure this PR doesn't fix the scenario described in #8942 : 

> To reproduce, on a fresh edit:
    1. Open the crop module and crop the image (a fairly severe crop to make it more obvious)
    2. Open the crop & rotate module and enable it without cropping the image further
    3. Collapse the crop & rotate module
    4. An additional crop is introduced without request

because here it seems to fix it...

@elstoc : last commit should fix the rotation issue...

**Comment by elstoc** [comment]
Thanks that does fit the rotation issue and, as far as I can tell, the original issue #8942. However... 

1. Add a crop in the crop module and double-click to commit
2. Expand crop & rotate but don't make any changes
3. Expand crop again
4. Crop disappears (you have to collapse the crop module to get it back again)

**Comment by AlicVB** [comment]
@elstoc : ok, I reproduce your "focus" issue. Sadly, I will be out for few days... so this will have to wait a little...

**Comment by TurboGit** [comment]
> @TurboGit : are you sure this PR doesn't fix the scenario described in #8942 :

Strange, seems to work now :( Don't know what is happening!

**Review by TurboGit — APPROVED** [review]
Good to go then, thanks !

**Comment by elstoc** [comment]
We're going to deal with the remaining issue in another PR then?

**Comment by TurboGit** [comment]
> We're going to deal with the remaining issue in another PR then? I'll raise another issue.

Yes, that's how I see this. The current fix is one step forward.

**Pull request merged**
