### PR TITLE
dt_opencl_init(): use new dt_opencl_get_device_info()

### PR DESCRIPTION
**Pull request by LebedevRI**
@upegelow 
Okay, second part.

It the diff does look big, but mostly due to the fact that i had to factor out into new function.
Everything except dynamic memory allocation should be the same.

This successfully decreases stack usage below the threshold (32K) i set, for this function anyway:

```
/home/lebedevri/darktable/src/common/opencl.c: In function ‘dt_opencl_device_init’:
/home/lebedevri/darktable/src/common/opencl.c:473:1: warning: the frame size of 30064 bytes is larger than 0 bytes [-Wframe-larger-than=]
```

Later, `char array[PATH_MAX] = { 0 };` may need to be thought about, but right now this is good-enough.

### CODE REVIEW

**Comment by upegelow** [comment]
Hmm. Doesn't seem to work. I get this:

[http://pastebin.com/H5wpEw6e](url)

While I would expect to get:

[http://pastebin.com/xYPzLPLf](url)

**Comment by LebedevRI** [comment]
Oops, a bit too much error handling :)

```
diff --git a/src/common/opencl.c b/src/common/opencl.c
index 2da6688..e199fcf 100644
--- a/src/common/opencl.c
+++ b/src/common/opencl.c
@@ -373,49 +373,58 @@ static int dt_opencl_device_init(dt_opencl_t *cl, const int dev, cl_device_id *d
   {
 
     while(!feof(f))
     {
       int prog = -1;
       gchar *confline_pattern = g_strdup_printf("%%%zu[^\n]\n", sizeof(confentry) - 1);
       int rd = fscanf(f, confline_pattern, confentry);
       g_free(confline_pattern);
-      if(rd != 1) continue;
+      if(rd != 1)
+      {
+        res = -1;
+        goto end;
+      }
       // remove comments:
       size_t end = strlen(confentry);
       for(size_t pos = 0; pos < end; pos++)
         if(confentry[pos] == '#')
         {
           confentry[pos] = '\0';
           for(int l = pos - 1; l >= 0; l--)
           {
             if(confentry[l] == ' ')
               confentry[l] = '\0';
             else
               break;
           }
           break;
         }
-      if(confentry[0] == '\0') continue;
+      if(confentry[0] == '\0')
+      {
+        res = -1;
+        goto end;
+      }
 
       const char *programname = NULL, *programnumber = NULL;
       gchar **tokens = g_strsplit_set(confentry, " \t", 2);
       if(tokens)
       {
         programname = tokens[0];
         if(tokens[0])
           programnumber = tokens[1]; // if the 0st wasn't NULL then we have at least the terminating NULL in [1]
       }
 
       prog = programnumber ? strtol(programnumber, NULL, 10) : -1;
 
       if(!programname || programname[0] == '\0' || prog < 0)
       {
         dt_print(DT_DEBUG_OPENCL, "[opencl_init] malformed entry in programs.conf `%s'; ignoring it!\n", confentry);
-        continue;
+        res = -1;
+        goto end;
       }
 
       snprintf(filename, sizeof(filename), "%s/kernels/%s", dtpath, programname);
       snprintf(binname, sizeof(binname), "%s/%s.bin", cachedir, programname);
       dt_print(DT_DEBUG_OPENCL, "[opencl_init] compiling program `%s' ..\n", programname);
       int loaded_cached;
       char md5sum[33];
       if(dt_opencl_load_program(dev, prog, filename, binname, cachedir, md5sum, includemd5, &loaded_cached)

```

**Comment by LebedevRI** [comment]
Thankfully, at least for this, pocl works.

**Comment by upegelow** [comment]
Looks good here.

**Comment by LebedevRI** [comment]
Like with #1281, i'm obviously leaving it up to you to decide and merge it.

**Comment by upegelow** [comment]
I don't see any issues.

**Comment by LebedevRI** [comment]
@upegelow 
While i'm near opencl code, i have observed a very painful pattern:
```
if(dev_mem != NULL) dt_opencl_release_mem_object(dev_mem);
```
It is painful because practically all `free()` functions take `NULL` ptrs, and handle them internally just fine.
So having one that does not, is error prone.

What do you think about extending `dt_opencl_release_mem_object()` to just immediately return if `NULL` is passed, and maybe automatically brush the calls to `dt_opencl_release_mem_object()` (dropping null check, where it is just the null check)?

Or is there a deeper reason for this?

**Comment by LebedevRI** [comment]
@upegelow just checking that last comment was not lost

**Comment by upegelow** [comment]
Interestingly the opencl specs don't define explicitely what happens for 
clReleaseMemObject(NULL). So in any case we should catch that case in 
dt_opencl_release_mem_object(). I'll take care.

**Comment by LebedevRI** [comment]
In either case, after `dt_opencl_release_mem_object()` learns to handle `null`, i'll follow-up with a clean-up patch to not check for `null`.
Thankfully, we use C and such semantic patch is trivial.

**Pull request merged**
