### PR TITLE
culling : fix if zoom == 1 and image is removed

### LINKED ISSUE #2951: [Culling] Auto advance fails in unstarred only mode
**Describe the bug**
Auto advance with culling mode and "unstarred only" is broken as it auto advance to an empty screen that we cannot leave.

**To Reproduce**
1. From lightable, filter "unstarred only"
2. press "x" to enable culling mode
3. press 0-5 / r, the picture correctly take the note, but it auto advance on an empty screen.
4. I'm stuck, the only way to be back in culling mode is to press x again to quit culling mode and start again. 

FYI, no problem with "w" mode.

**Expected behavior**
it autoadvance, as with "w" mode.

**Platform (please complete the following information):**
 - OS: ubuntu
 - master

**Additional context**

When not on "unstarred only", there is no auto advance, but there i can rate a photo and navigate to next/previous one with right/left.

### PR DESCRIPTION
**Pull request by AlicVB**
This can happen for example if you have set filtering to "unstarred only" and apply a star to the current image.
this fix #2951

### CODE REVIEW

**Comment by bastnic** [comment]
thanks @AlicVB.

**Comment by TurboGit** [comment]
@bastnic : do not hesitate to give feedback if you have tested the PR. This helps me assessing if it can be merged safely. I do test all PR but I must say that there is so many those days that I have hard time to follow...

**Comment by bastnic** [comment]
@TurboGit I absolutely plan to do it ;).

**Comment by bastnic** [comment]
@TurboGit I just tested it and it's ok.

**Comment by TurboGit** [comment]
Looks good to me too. Thanks for testing.

**Pull request merged**
