### PR TITLE
style history merge

### LINKED ISSUE #15806: Applying multiple styles with multiple module instances produces order-dependent result
### Describe the bug

This is from https://discuss.pixls.us/t/how-to-add-two-watermarks-on-a-image-in-darktable/40653/10. The OP asked about multiple watermarks. To demonstrate the use of multiple instances, I created two styles, one with watermarks in the top/bottom left corners, one with watermarks in the top left/right corners.

Applying them in "top", then "left" displays 3 watermarks (top left, top right, bottom left).
Applying them in "left", then "top" order displays only the top 2; bottom left is removed.

### Steps to reproduce

1. Import the styles
2. Apply them in the order "top", then "left" -> 3 watermarks
3. Apply them in the order "left", then "top" -> 2 watermarks

### Expected behavior

Combine the styles and display 3 watermarks (module instance names are distinct)

### Logfile | Screenshot | Screencast

First "top", then "left":
top-then-left

First "left", then "top":
left-then-top

[left watermarks.dtstyle.txt](https://github.com/darktable-org/darktable/files/13533808/left.watermarks.dtstyle.txt)
[top watermarks.dtstyle.txt](https://github.com/darktable-org/darktable/files/13533809/top.watermarks.dtstyle.txt)

The "left" style:
```xml
        <plugin>
            <num>9</num>
            <module>6</module>
            <operation>watermark</operation>
            <!-- ... -->
            <multi_priority>1</multi_priority>
            <multi_name>top left</multi_name>
            <multi_name_hand_edited>1</multi_name_hand_edited>
        </plugin>
        <plugin>
            <num>8</num>
            <module>6</module>
            <operation>watermark</operation>
            <!-- ... -->
            <multi_priority>0</multi_priority>
            <multi_name>bottom left</multi_name>
            <multi_name_hand_edited>1</multi_name_hand_edited>
        </plugin>
```

The "top" style
```xml
        <plugin>
            <num>10</num>
            <module>6</module>
            <operation>watermark</operation>
            <!-- ... -->
            <multi_priority>1</multi_priority>
            <multi_name>top right</multi_name>
            <multi_name_hand_edited>1</multi_name_hand_edited>
        </plugin>
        <plugin>
            <num>9</num>
            <module>6</module>
            <operation>watermark</operation>
            <!-- ... -->
            <multi_priority>0</multi_priority>
            <multi_name>top left</multi_name>
            <multi_name_hand_edited>1</multi_name_hand_edited>
        </plugin>
```

### Commit

_No response_

### Where did you obtain darktable from?

self compiled

### darktable version

4.5.0+1391~g0a39901aa5-dirty (because of the tone-eq experiment from https://github.com/darktable-org/darktable/issues/15743#issuecomment-1828292364)

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.10

### Describe your system?

_No response_

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by TurboGit**
history: never set the multi_priority.
    
This is either the one from the module we replace or the new
multi-priority we got when duplicating the base module.
    
Fixes #15806.

### CODE REVIEW

**Comment by TurboGit** [comment]
@kofa73 : Fixes your issue, but if you can test with many different scenario of applying styles and copy/paste history it would be nice. I have tested many scenario myself but this is a very delicate area... TIA.

**Comment by kofa73** [comment]
Thanks for the quick fix, I'll try to test this extensively during the weekend.

**Comment by TurboGit** [comment]
@kofa73 : I'll merge now to ensure we get a bit of field testing as we are approaching the full freeze. Be sure to test master, a second testing round would be nice. TIA.

**Comment by kofa73** [comment]
I can confirm that the fix works -- thank you!
Any particular situations you think may be edge cases that need to be tested? I have little time during the week, but I can try.

**Pull request merged**
