### PR TITLE
po/undo duplicate

### PR DESCRIPTION
**Pull request by TurboGit**
Add support for undo/redo for the duplicate of images (ctrl-d). Undo will remove the duplicate, redo will add back the duplicate.

### CODE REVIEW

**Comment by elstoc** [comment]
@TurboGit: would you mind adding a brief description to the start of your PRs please, so we don't have to look through the commit list to see what it does.

**Comment by TurboGit** [comment]
> @TurboGit: would you mind adding a brief description to the start of your PRs please, so we don't have to look through the commit list to see what it does.

Done.

**Comment by elstoc** [comment]
@TurboGit does this need documentation? I think it probably falls inside the generic "undo/redo" documentation we already have, unless you can think of anything specific you want to add.

**Comment by TurboGit** [comment]
I thought that we just wanted to add the duplicate as supporting undo/redo in the list here:
https://www.darktable.org/usermanual/en/lighttable/undo-redo/

**Comment by elstoc** [comment]
ok will do. I forgot we'd listed the supported modules.

**Pull request merged**
