### PR TITLE
improve styling of module section expander button

### PR DESCRIPTION
**Pull request by elstoc**
improves the styling of the section expander buttons in the import and white balance modules

### CODE REVIEW

**Comment by johnny-bit** [comment]
before/after screenshots? :)

**Comment by elstoc** [comment]
> before/after screenshots? :)

I could but it's quite subtle unless you hover over and click on the button. Basically the button was much taller than it was wide, changed width when it was selected and padding meant that the icon was a bit small.

**Comment by elstoc** [comment]
Try this...

before:

Screenshot_2021-01-14_13-52-35
Screenshot_2021-01-14_13-53-04

after:

Screenshot_2021-01-14_13-53-28
Screenshot_2021-01-14_13-53-55

**Comment by Nilvus** [comment]
@elstoc: not tested but seems good. Thanks for doing my usual work (except Gtk code!). Will test and post feedback ASAP.

**Comment by Nilvus** [comment]
All good. Thanks @elstoc. @TurboGit: this could be merged. After that, I will work on some things in the UI.

**Comment by TurboGit** [comment]
Thanks to all !

**Pull request merged**
