### PR TITLE
[performance] rewrite DWT in rawdenoise

### PR DESCRIPTION
**Pull request by ralfbrown**
Yields a 3x performance gain for 1-2 threads, decreasing to ~10% at 32 threads (memory bandwith limits) for Bayer-filtered sensors.  I haven't touched the X-Trans version yet, as I'll need to set up correctness tests.

Use integration test 0049-rawdenoise from #7082 to verify correctness.

Once #7075 is merged, a good chunk of the code can be moved to src/common/dwt.c which will allow elimination of some code I needed to duplicate while that PR was still pending.

### CODE REVIEW

**Comment by ralfbrown** [comment]
@TurboGit Regarding X-Trans sensors, it would be good to have an X-Trans image for the integration test suite (though we wouldn't want to run on it for every test and double the test suite's run time).  That will allow checks of X-Trans demosaicing algorithms as well as the X-Trans version of the raw denoising.

**Comment by TurboGit** [comment]
>  it would be good to have an X-Trans image for the integration test suite

Sure would be nice to have one in the images directory. Do you have one to share ? I don't have an X-Trans camera, but I'm sure we can find a free sample somewhere. Let me know.

**Comment by TurboGit** [comment]
And yes I agree we certainly don't want to run every test with it, but a test for the demosaic is really welcome.

**Comment by johnny-bit** [comment]
@TurboGit - raw.pixls.us are no.1. source for all raws, including XTrans and all are CC0 licenced so can be freely included.

**Comment by ralfbrown** [comment]
Just found something really strange -- the integration test fails with a bad strip at the right edge, but during dev I had been testing with the same image and .xmp and getting pixel-identical results.  The difference: integration test downsamples to 2048px wide, I had been using full-size output.  Will have to track that down....

**Review by TurboGit — APPROVED** [review]
Looks good to me, thanks !

**Comment by TurboGit** [comment]
@johnny-bit : I'd like to have an **X-Trans with at least a color checker** in it. I'm not able to find one. I have found that the color checker in the Bayer sample we have in dt is very useful to do some checking when we encounter issues.

**Pull request merged**
