### PR TITLE
Add noise profile for the Canon EOS R5

### PR DESCRIPTION
**Pull request by piratenpanda**
As discussed on IRC here goes the PR for the R5 noise profile

### CODE REVIEW

**Comment by rawfiner** [comment]
I checked the noise curves, piratenpanda sent them to me on IRC, I am ok with the result

**Comment by piratenpanda** [comment]
There is a bug still, will fix asap

**Comment by piratenpanda** [comment]
Sorry I missed that

**Review by TurboGit — APPROVED** [review]
Thanks !

**Pull request merged**
