### PR TITLE
Add Sony A7rV noise profile

### PR DESCRIPTION
**Pull request by da-phil**
Use same noise profile as Sony A7rIV due to same sensor.

I did a manual test to confirm that the results look as good as for A7rIV files.

### CODE REVIEW

**Comment by rawfiner** [comment]
Just to be sure, this is a copy paste from ilce-7rm4, right?
Even when cameras share same sensors, I prefer to recompute noise profile, as firmware differences could invalidate the noise profile.
Though, read noise curves on photons to photo show almost equal curves for both cameras, so I think we are good here (https://www.photonstophotos.net/Charts/RN_ADU.htm#Sony%20ILCE-7RM4_14,Sony%20ILCE-7RM5_14).

**Comment by rawfiner** [comment]
Yet, if you have the camera and you are able to compute the profile, that would be the safest IMO.

**Comment by da-phil** [comment]
@rawfiner I do have the camera, that's why I'm very interested in this feature and I've been locally working with this noise profile for a while now. I need to see when I have time to do the noise profile from scratch, but it should be definitely possible.
IMHO we could merge what we have now and improve the profile later, when we have created a profile from scratch.

**Comment by rawfiner** [comment]
@da-phil that would be great if you can create a profile from scratch thanks!
Unfortunately, once a profile is merged, we cannot update it because it would break backward compatibility. I think it is safer then to wait for the computed profile. Meanwhile, you can use the copy-pasted profile using the `--noiseprofiles` commandline option of darktable to give it the current json file.
Thanks

**Comment by da-phil** [comment]
@rawfiner  Fair enough, I didn't consider backwards-compatibility, but it's indeed a valid point.
Then let's wait until I was able to create a profile from scratch.

**Comment by da-phil** [comment]
@rawfiner I was finally able to create a noise profile myself, see results: [darktable-noiseprofile-20230529.tar.gz](https://github.com/darktable-org/darktable/files/11594162/darktable-noiseprofile-20230529.tar.gz)
what do you think?
I find it weird that the converted pictures contain this greenish color cast, although it might not matter for the overall noise estimation, right?
Maybe the conversion profile is weird?

**Comment by rawfiner** [comment]
@da-phil your profile looks great thanks! You can integrate it in the PR as is, no need to try another time. Also, the green cast is expected, it is due to the absence of white balance.

**Comment by da-phil** [comment]
@rawfiner done, then the PR should be ready to be merged

Regarding the ``profiling-shot.xmp`` : it contains a whitebalance instance in the history, see 
``darktable:operation="temperature"``
Do you think it makes sense to update this profile to "set camera white balance to reference point (D65)", or get rid of it completely?

**Review by rawfiner — APPROVED** [review]

**Comment by rawfiner** [comment]
IIRC, the whitebalance there is a no-op, all channels are multiplied by 1. I'd say we could get rid of it, but better keep things as is to avoid breaking anything.

@TurboGit ready to merge for me

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
