### PR TITLE
OpenCL double platforms safety check

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
In some situations darktable is confronted with some buggy OpenCL ICD setup with multiple driver versions of the same driver architecture presented as multiple platforms that all would like to access a device.

Such a situation is never correct, this pr adds a test for all platforms if there has already been another platform with the same name found and if so, it will disable opencl and will report the user to clean up the situation.

See https://discuss.pixls.us/t/cltest-result-help/40775 as an example for such a situation. Of course this is not a dt issue per se but a problem of the user or distribution/OS but we can at least make aware of the problem.

### CODE REVIEW

**Comment by TurboGit** [comment]
Would be nice to have this in 4.6, but there is a new string to translate in this PR. So either for 4.6.1 or maybe we could reuse a string already present in 4.6 even if not 100% accurate. Last option no string at all except the one on the console and we will add the GUI message in 4.6.1. How do you feel about this @jenshannoschwalm?

**Comment by jenshannoschwalm** [comment]
There is a gui string that is "not bad" we could use. Will do another commit.

This is not a common case but I also think it would be good for 4.6

**Comment by jenshannoschwalm** [comment]
@TurboGit i just removed that specific logerror, the one found in L 1185 is still valid here and is good-enough for me. Left a note in the commit message about "this should be improved" in 4.8

**Review by TurboGit — APPROVED** [review]
Thanks!

**Pull request merged**
