### PR TITLE
po/record harmony guide xmp

### PR DESCRIPTION
**Pull request by TurboGit**
The goal here is to store the color harmony guide into the DB & XMP to be able to restore the color harmony layout per image.

For #15115.

EDIT: Not tested enough at this stage, so setting to draft.

### CODE REVIEW

**Comment by TurboGit** [comment]
Not anymore a draft, can be reviewed/tested.

**Comment by TurboGit** [comment]
Merging now to get for field testing.

**Comment by s7habo** [comment]
How does it work? Do you have to switch something on first? I don't see any change:


https://github.com/darktable-org/darktable/assets/38165484/df92805b-0557-4270-99bf-af895858243f

dt 4.5.0+1176~gd4b5d7b5e

**Comment by TurboGit** [comment]
I probably broke things with my last change... Let me have a look!

**Comment by TurboGit** [comment]
Should be fixed now. It was in fact just a missing GUI refresh when first entering darkroom. When switching image in the filmstrip while in darkroom was working as expected.

**Comment by TurboGit** [comment]
@s7habo : Thanks for testing!

**Comment by s7habo** [comment]
Yes, it works now. Thank you for this extension!

**Pull request merged**
