### PR TITLE
improve bauhaus popup behaviour

### PR DESCRIPTION
**Pull request by dterrahe**
I wasn't _really_ happy with my fix for https://github.com/darktable-org/darktable/pull/14991#pullrequestreview-1560391240 and also still annoyed by a bunch of other inconsistent behaviors of sliders and combos, so here is another final round of bauhaus fixes.

Basically this removes a bunch of duplications and merges more of mouse handling in the popup for sliders and combos. Most of the actual value changes are now dealt with in `motion_notify`; `button_press` hands over to it and `button_release` just closes the popup if appropriate. 
* you can now "scroll" through all the values in a combo with a left mouse drag (and see the effect while you do so, just like you would when scrolling through the list of an open popup). May be especially useful for tablet/pen users.
* This also works if you immediately keep dragging after clicking on the combo widget to open the popup. So for example an on/off combo can be very quickly flipped by clicking and flicking the mouse down or up. Again tablet users may like that it requires only one click instead of two.
* The "mute scrolling mode" that is used for the collect module dropdowns is now more consistent in that the selected value always gets activated when the popup closes. It used to be that when you change the selection by scrolling and then close the popup by moving the mouse away from it, the shown selection wasn't consistent with what was in the list view below it.  
This mode may now be more useful for combos that trigger lengthy refreshes; I've set it for the sort order drop down as well.
* when the value of a combo changes while the popup is open, it gets correctly updated and shifted. This could happen when (midi) shortcuts are used, but also for example in "color calibration" when scrolling through the list of "illuminant" modes and hitting "detect from image"; it would select another entry but not move the popup so you'd end up scrolling off it.
* The slider popup will now switch to dragging mode when left-clicking, so you can see what value you'll get when you release the mouse. You can drag around before you do.
* colorpicker etc buttons now get a highlight when they are hovered over
* some general code quality improvements; `dt_bauhaus_widget_hide_label` instead of directly changing the field, standard function naming and using class handlers instead of separately setting different ones for each created combo or slider.
* Collapsible sections now open/close on mouse button _press_, rather than _release_ so they don't get inadvertently triggered when a bauhaus popup was closed after a press but before release.

### CODE REVIEW

**Comment by TurboGit** [comment]
> * colorpicker etc buttons now get a highlight when they are hovered over

Can you explain a bit more, to me this is already the case, no?

**Comment by Nilvus** [comment]
> > * colorpicker etc buttons now get a highlight when they are hovered over
> 
> Can you explain a bit more, to me this is already the case, no?

Those linkedcto à bauhaus do not have hover effect. You could check on ton équilibre or filmic

**Comment by dterrahe** [comment]
> Can you explain a bit more, to me this is already the case, no?

The least consequential part of this PR :-) As @Nilvus says.

How do you feel about the other behavioral changes? Are they clear?

**Comment by TurboGit** [comment]
> The least consequential part of this PR :-) As @Nilvus says.

Sorry about missing that. Yes the other parts are clear. I'm always trying to make sense of the comments in a PR before testing and reviewing it. Things that seems obvious to some may well be not so obvious for others :)

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Pull request merged**
