### PR TITLE
Update de.po

### PR DESCRIPTION
**Pull request by MStraeten**
update to new pot file

### CODE REVIEW

**Comment by johnny-bit** [comment]
This also fixes https://github.com/darktable-org/darktable/issues/7979 (or that is already fixed), right?

**Comment by TurboGit** [comment]
@johnny-bit : Already or not yet but this is not part of the PR as it is only for some changes done to use American spelling.

**Review by TurboGit — APPROVED** [review]
Thanks !

**Comment by TurboGit** [comment]
Translation is 100% complete.

**Pull request merged**
