### PR TITLE
imageio_tiff: use Imath for 16-bit half float export

### PR DESCRIPTION
**Pull request by kmilos**
[Imath is available for most distros and platforms](https://repology.org/project/imath/versions), apart from MacPorts (still on OpenEXR < 3 @parafin @mascguy; edit: I just saw [this is tracked already](https://trac.macports.org/ticket/65662)).

The UI should behave similarly to the one in the PR for JPEG XL export: only show integer/float switch for 16b case (if Imath is available); 32b is always float, 8b is only integer.

### CODE REVIEW

**Comment by TurboGit** [comment]
I have add **wip** + **macos** tag for this PR.

**Comment by kmilos** [comment]
Don't think we need to do anything special re macOS: Homebrew has it, and it will just be silently disabled on MacPorts builds until the package is available.

**Comment by TurboGit** [comment]
Well all MacOS CI are broken by this PR.

**Comment by TurboGit** [comment]
```
/Users/runner/work/darktable/darktable/src/src/common/imageio_tiff.c:58:21: fatal error: unused function '_half_to_float' [-Wunused-function]
static inline float _half_to_float(uint16_t h)
```

**Comment by kmilos** [comment]
Ah, ok, will put it behind #ifdef then.

Didn't hit on Linux LLVM since 'ubuntu-latest' is still 20.04 😯 and Imath comes only w/ 22.04 (available in GHA but not default yet).

**Comment by HansBull** [comment]
Should be in `libilmbase24` on Ubuntu 20.04.

**Comment by kmilos** [comment]
Has to be at least Imath 3.1

**Comment by kmilos** [comment]
@mascguy Thanks for working on [updating MacPorts to openexr3](https://trac.macports.org/ticket/65662#comment:10). However, Imath needs to be debundled in a separate package - [it is now an individual project with its own cadence](https://github.com/AcademySoftwareFoundation/Imath/blob/main/docs/PortingGuide.rst).

**Comment by mascguy** [comment]
> @mascguy Thanks for working on [updating MacPorts to openexr3](https://trac.macports.org/ticket/65662#comment:10). However, Imath needs to be debundled in a separate package - [it is now an individual project with its own cadence](https://github.com/AcademySoftwareFoundation/Imath/blob/main/docs/PortingGuide.rst).

Sounds good, I'll add that to my to-do list. Thanks for the heads-up Milos!

**Comment by kmilos** [comment]
Btw, in e.g. MSYS2 we went straight for a replacement instead of a new package, so [OpenEXR 3.x conflicts and replaces the old IlmBase 2.x package as well](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-openexr/PKGBUILD#L19-L26), so the upgrade is seamless...

**Pull request merged**
