### PR TITLE
styles_dialog: disable signal propagation.

### LINKED ISSUE #12962: macos: style preview causes to crash darktable
after getting rid of #12727 i found the style preview seems to cause a crash.
(not reproducible with my builds up to Oct 29th, but reproducible with my build Nov. 3rd) need to confirm that by bisecting
 
**To Reproduce**
screnario 1 - lighttable (repoduced with older builds): 
1. select mire2.cr2 from test images 
2. move mouse over some styles and wait for the preview to be displayed
3. move to several another styles
after a while doing that
4. darktable crashes

screnario 2 - darkroom (selecting a style from upward style dropdown menu via bottom left button): 
1. select mire2.cr2 from test images 
2. move mouse over some styles and wait for the preview to be displayed
4. darktable crashes

[bt.txt](https://github.com/darktable-org/darktable/files/10060146/bt.txt)
[lldb_out.txt](https://github.com/darktable-org/darktable/files/10060196/lldb_out.txt)

**Which commit introduced the error**
bisect t.b.d. 

**Platform**
* darktable version : darktable-4.1.0+860~g64a61e52e_x86_64 and later
* OS                :  OSx

### PR DESCRIPTION
**Pull request by TurboGit**
Attempt to fix #12962.

### CODE REVIEW

**Comment by MStraeten** [comment]
crash after the preview image is displayed
[bt_13007.txt](https://github.com/darktable-org/darktable/files/10097197/bt_13007.txt)

**Comment by TurboGit** [comment]
@MStraeten : Thanks, that's a new crash. I have made an attempt to fix it in a second commit. Can you please test again this PR? TIA.

**Comment by MStraeten** [comment]
keeps crashing after preview is shown:
[bt_13007_2.txt](https://github.com/darktable-org/darktable/files/10098325/bt_13007_2.txt)

**Comment by TurboGit** [comment]
@MStraeten : Is that with some specific image format? sRAW? Same that are "crashing" segmentation code? Or do you reproduce with all format? JPEG? NEF? CR2?

**Comment by TurboGit** [comment]
I've pushed another fix (similar to previous one) but in another place. Can you check again? TIA.

**Comment by dterrahe** [comment]
In general, why would you expect stopping the draw signal from propagating to be a good thing? This is different from, say, a button-pressed signal, where you would only want it dealt with once and if a widget doesn't capture it, you want to give the next one a try. The draw signal is normally only dealt with by the widget and containers, but it is possible to connect additional handlers to it explicitly. Returning TRUE would block those from being triggered. This _could_ be useful in very specific cases, but it is not generally what you want to do. In most cases, it probably shouldn't make any difference. If in this case returning TRUE gives a different result from returning FALSE, what handler is responsible for that, why does it fail, and is it needed in the first place? Or is it more likely that this is some side effect of earlier memory corruption?

**Comment by TurboGit** [comment]
> In general, why would you expect stopping the draw signal from propagating to be a good thing?

I don't, we have an issue with MacOS that I (and no one) understand and I'm trying to see what could help by analyzing the back trace. As I can't reproduce for now the issue, this commit has at least made the issue moved to somewhere else... But I'm now wondering if I'm not on a fully wrong track... All those crash are really strange!

**Comment by MStraeten** [comment]
i'm testing with mire1.cr2. latest commit also fails:
[bt_13007_3.txt](https://github.com/darktable-org/darktable/files/10099088/bt_13007_3.txt)

**Comment by jenshannoschwalm** [comment]
@MStraeten to make sure, did you also test with highlights reconstruction disabled or set to clip?

**Comment by TurboGit** [comment]
@MStraeten : 

Something very wrong with all those backtrace, it fails again after a call to dt_image_cache_get() returning NULL pointer. I have already added two defensive check in this PR:

```
  const dt_image_t *image = dt_image_cache_get(darktable.image_cache, imgid, 'r');
  dev->image_storage = *image;
  dt_image_cache_read_release(darktable.image_cache, image);
```

But this cannot really be the problem I think, it looks like the memory is fully corrupted or you have a broken dt cache.

**Comment by TurboGit** [comment]
Wait... on you backtrace you have imgid == 0, do you confirm that the image you are trying to use has an image id of 0? This is not possible as the first image imported should have an imgid of 1.

And the crash is explained as dt_image_cache_get() is:

```
dt_image_t *dt_image_cache_get(dt_image_cache_t *cache, const int32_t imgid, char mode)
{
  if(imgid <= 0) return NULL;
  dt_cache_entry_t *entry = dt_cache_get(&cache->cache, (uint32_t)imgid, mode);
  ASAN_UNPOISON_MEMORY_REGION(entry->data, sizeof(dt_image_t));
  dt_image_t *img = (dt_image_t *)entry->data;
  img->cache_entry = entry;
  return img;
}
```

That is returning NULL for imgid == 0.

**Comment by TurboGit** [comment]
@MStraeten : I have pushed a fix on master to skip imgid <= 0. It should fix all your crashes but maybe now you don't have the preview displayed. Anyway, can you try new master? TIA.

**Comment by MStraeten** [comment]
current master, mire1.cr2 (image_id: 22735): 
[bt_13007_4.txt](https://github.com/darktable-org/darktable/files/10105793/bt_13007_4.txt)
after deleting .cache/darktable directory:
[bt_13007_5.txt](https://github.com/darktable-org/darktable/files/10105891/bt_13007_5.txt)

one of the dtstyles: [Canon Default.dtstyle.txt](https://github.com/darktable-org/darktable/files/10105826/Canon.Default.dtstyle.txt)

**Comment by TurboGit** [comment]
Fix should be in #13039, closing this.

**Pull request closed without merging**
