### PR TITLE
[GUI] Redesign ISO matching widget for presets

### PR DESCRIPTION
**Pull request by victoryforce**
To put it in context, the first attempt to improve this widget was in #10811, later it was discussed in #13414 where I promised to find a better solution. Сontinuing from that discussion:

> > Let's keep things as-is until a Gtk guru come with a clean solution.
> 
> To change that, I'll even declare myself a GTK guru (yes, I'm an impostor). I have an idea how to implement it.

To be honest, all I knew about GTK were fairly basic things, and I have no experience of writing something full-fledged from scratch. However, the desire to improve this widget made me start looking for a solution.

What's wrong with the current interface?

It has not very good UI and UX. In terms of UX, spin buttons for a range of non-linear values are unusable. They are simply inappropriate here.

As for the UI, showing an absurdly long textual representation of the FLT_MAX number doesn't look good. This number is stored in the database when we do not want to limit the upper ISO range, as it is the largest possible value of the data type used to store the input values. But in this case, it would be best to replace it by a text placeholder such as `unlimited` or `unbounded` in the input field.

The problem is that this is not possible for spin button widgets. So, this will need to be done through GTK text entry fields. But then we face the problem of the possibility of entering non-numeric values into such fields. Input verification functions at the stage of saving values are already too late, it is preferable to simply prevent the user from entering invalid characters. Fortunately, this is possible because we can process the text insertion signal.

@elstoc May I ask you to comment on which word here is better as a placeholder? I chose UNBOUNDED, but perhaps UNLIMITED would seem like a more appropriate word in this context?

### CODE REVIEW

**Comment by elstoc** [comment]
It would be good to show some screenshots of what you're doing so people don't have to build in order to comment. I haven't built it so I'm not 100% sure of context. But what's wrong with ∞ (infinity symbol)?

**Comment by elstoc** [comment]
> Somehow it is a bit strange to imagine the infinite value of ISO. Yes, I agree that infinity in this field should not be taken literally, but still... If the widget allows you to write a more understandable placeholder word here, then why not.

UNBOUNDED and UNLIMITED don't really feel all that different to infinite (or any more understandable) to me, and I'm not particularly comfortable with words in a numeric field. I guess if you insist on words, maybe "MAX" might be an alternative, but really, infinity is not hard to understand. I think we can safely assume everyone who went through high school knows what the symbol for infinity is. Or some "all 9s" number maybe? (is 999999 high enough)

**Comment by victoryforce** [comment]
@elstoc Thanks for the review! Since I'm not sure which option is is better to choose (although you're probably right about the infinity symbol), it's probably better to let @TurboGit decide.

**Comment by difrkaguilar** [comment]
The changes all of you are making to darktable are great, what worries me is the perception by others who use the program about the consistency in the presentation of the information, even more so now that thanks to your work many of the data displayed are extracted from the EXIF contained in the images.

For example, in the filtering system of the collections, the ISO, exposure, focal length, and aperture data, besides having the possibility of defining a minimum and maximum range of selection using the mouse, also has numerical entries of minimum and maximum values. However, the representation of these values in the creation and edition of a new preset has several ways of representing the same values mentioned above, in some cases with popup with predefined values and in others with value entries followed by - and + signs.

Question. If the values shown both in the filtering module and in the preset creation window are values known in advance when the images with their EXIF are imported into the collections, why are these same values not used to display the information.

Example. I have not yet seen a camera that generates as minimum ISO value "0" or focal length "0" even, if these values exist but are not present in the images previously imported into the collections, then they should not be present either in a box, window or popup to be selected. These values should appear to be selected in both filtering and preset creation at the time the image is imported into the program and not before, plus for that you have knowledge of the cameras and lenses that are supported by the program. I do not refer to manual lenses because they do not show EXIF information and their values must be entered by hand if you want to create filtering or presets with them, but that would be through the tags.

If you consider that an FR should be opened specifically to deal with this subject, it would be even better, in order to find a coherence in the presentation of the information, because now in the way it is shown there is quite inconsistency. Please, don't hate me.... ;-)

**Screenshots**

Screenshot from 2023-03-29 20-47-46

Screenshot from 2023-03-29 18-55-27

Screenshot from 2023-03-29 18-57-22

Screenshot from 2023-03-29 18-56-21

**Comment by HSUfineprint** [comment]
Vote for `UNLIMITED`. It could be use in ISO, shutter speed, aperture and so on. And it could be use in either side of them in case anybody need to use it in the future.

**Comment by parafin** [comment]
> The changes all of you are making to darktable are great, what worries me is the perception by others who use the program about the consistency in the presentation of the information, even more so now that thanks to your work many of the data displayed are extracted from the EXIF contained in the images.
> 
> For example, in the filtering system of the collections, ISO, exposure, focal length, and aperture data, besides having the possibility of defining a minimum and maximum range of selection using the mouse, also has numerical entries of minimum and maximum values. However, the representation of these values in the creation and edition of a new preset has several ways of representing the same values mentioned above, in some cases with popup with predefined values and in others with value entries followed by - and + signs.
> 
> Question. If the values shown both in the filtering module and in the preset creation window are values known in advance when the images with their EXIF are imported into the collections, why are these same values not used to display the information?
> 
> Example. I have not yet seen a camera that generates as minimum ISO value "0" or focal length "0" even, if these values exist but are not present in the images previously imported into the collections, then they should not be present either in a box, window or popup to be selected. These values should appear to be selected in both filtering and preset creation at the time the image is imported into the program and not before, plus for that you have knowledge of the cameras and lenses that are supported by the program. I do not refer to manual lenses because they do not show EXIF information and their values must be entered by hand if you want to create filtering or presets with them, but that would be through the tags.
> 
> If you consider that an FR should be opened specifically to deal with this subject, it would be even better, in order to find a coherence in the presentation of the information, because now in the way it is shown there is quite inconsistency. Please, don't hate me.... ;-)

This is a bad idea, since auto-applied presets are more about pictures that will be imported in the future, not already present in the database. The whole point of using infinity is to create a future-proof preset, because maximum ISO values tend to rise over time. As for zero as a minimum - this is quite common value when metadata is missing.

**Comment by zisoft** [comment]
Can we use a dropdown list here with the well known ISO steps having the last value named "UNLIMITED"?

        ...
        6400
        12800
        25600
        51200
        102400
        204800
        UNLIMITED

And slightly off-topic: Increase the value for max focal length. 1000 is a bit small for people using tele extenders or for the professional sports photographer with their 20000$ super telephoto lens with 1250mm focal length

**Comment by victoryforce** [comment]
> Can we use a dropdown list here with the well known ISO steps having the last value named "UNLIMITED"?
> 
> ```
>     ...
>     6400
>     12800
>     25600
>     51200
>     102400
>     204800
>     UNLIMITED
> ```

Then, thanks to the development of technology, camera manufacturers will release models with ISO 409600, then 819200, and so on. There is already a specialized, not for the general public, camera with an ISO of about 3 million. Such a dropdown list will become obsolete and will not allow the user to precisely set the upper limit.

**Comment by zisoft** [comment]
If someone really needs a higher setting, UNLIMITED can be chosen. But the majority of serious photographers will always chose one of the well known steps. I find this much more convenient than to manually type in a number.

**Comment by TurboGit** [comment]
For ISO I would tend to use combo to be consistent with Exposure & Aperture. The combo (as already described) would list the set of commonly used ISO values. I'm also ok for adding 409600 if needed. For the max I would certainly prefer the infinity symbol than 0. If the max value become obsolete will amend the list in the future, no big deal to me.

**Comment by EC1000** [comment]
> ...
>     6400
>     12800
>     25600
>     51200
>     102400
>     204800

I use lot of presets with intermediate values, that are different than these values. It would break lots of presets for me. 
What is the added value of having a drop down list compare to the current solution?

**Comment by difrkaguilar** [comment]
> I use lot of presets with intermediate values, that are different than these values.

I've this ISO chart and know that ISO values can be set as 0 if the are not any value, or UNLIMITED can be set to values over the chart for futures ISO values. Just to learn and gain knowledge. Which supported cameras by darktable gives you those intermediate values?

Screenshot from 2023-03-30 20-12-52

For instance SONY have some of those predefined ISO values, but not values as 387 or 1233

Screenshot from 2023-03-30 20-23-38

**Comment by TurboGit** [comment]
> It would break lots of presets for me.

I don't think so. The values recorded into the db will stay the same. Only the new preset won't have those possible _insane_ values :) We are speaking a auto-applied preset and I've hard time to imagine a preset that would be good in the `[100..867]` ISO range but not in `[100...1000]`.

**Comment by EC1000** [comment]
Maybe I misunderstood, but I was reacting to:

> Can we use a dropdown list here with the **well known ISO steps** 

followed by a list of values, where intermediate values like 16000 and 20000 (between 12800 and 25600) were missing.

**Comment by zisoft** [comment]
> where intermediate values like 16000 and 20000 (between 12800 and 25600) were missing

That are half stop or third stop values. My list above only show the full stop values, like the lists for aperture and shutter speed.

**Comment by elstoc** [comment]
I wonder if it might be worth taking a step back and taking a look at the preset dialog as a whole to see if there might be a better and more consistent way of doing things, rather than tackling just this one field.

**Comment by difrkaguilar** [comment]
> I wonder if it might be worth taking a step back and taking a look at the preset dialog as a whole to see if there might be a better and more consistent way of doing things, rather than tackling just this one field.

That was the idea in my first post in this thread, I was showing you that there are inconsistencies in the way the information is displayed, in the collection filtering module it is displayed one way, and in this preset creation and editing window it is displayed another, that doesn't help the content to be displayed homogeneously. That's why I put them that it would not be bad to create a separate thread to address the issue more globally. 

There are many ISO, aperture, focal length and exposure values that manufacturers handle as standard and many of these values are present in the data of the cameras supported by darktable. Of course, there are exceptions and these should also be taken into account. But the information should be presented in the same way in all applicable parts of the program.

**Comment by elstoc** [comment]
Indeed, as a simple example (not to hijack this thread) but I recently wanted to setup one preset for images from my FujiFilm camera and another preset for "everything else" (i.e. "not FujiFilm") but I'm not sure that's possible. I hacked a workaround in this case.

I do wonder, though, whether I'll ever need to do this again, so we should be careful to avoid overengineering for too many corner cases.

**Comment by TurboGit** [comment]
> I do wonder, though, whether I'll ever need to do this

It seems strange to me to apply a preset on everything but a camera (or but whatever). If new cameras are out this may not be good and the preset become obe... To me it seems better to keep a preset selected for some specific values and so no `not` operator.

**Comment by elstoc** [comment]
> It seems strange to me to apply a preset on everything but a camera

Mostly because I want to do different things for x-trans (FujiFilm) and bayer (everything else) sensors

**Comment by victoryforce** [comment]
Sorry for the pause. However, even though I've spent time on other things, I kept coming back to thinking about which is better: my proposal with two input fields or the two dropdowns suggested here in the comments:

> Can we use a dropdown list here with the well known ISO steps

and

> The combo (as already described) would list the set of commonly used ISO values.

I recently got back into processing my travel photos, where I took most of photos on my smartphone... and saw that many of the photos had ISOs that were in no way determined by any standard steps. Like 76, 156, 190, 300, 350...
Well, this is how mobile photography is implemented. They are not limited to standard steps, and it looks like they are free to set the optimal signal gain factor (which is what ISO actually is), rather than just choosing it from a fixed list of values.

>  I've hard time to imagine a preset that would be good in the [100..867] ISO range but not in [100...1000].

In my opinion, the whole idea of auto-applying presets is that the user can determine for which specific images they will be applied. I'm not sure that limiting the user in this is a better interface.

We can argue that this is a very small difference between photos at, for example, ISO 867 and ISO 1000 (in terms of noise and dynamic range), but if users see this difference, they should not be prevented from setting preset limits where users need it.

I will not continue to insist that my proposed interface is the best. But it is good enough and definitely miles better than the very problematic current one. Instead of continuing the debate, I propose to accept this PR first. Let's go through step-by-step improvements. After that, we can continue to discuss it. And, perhaps, with the next PRs, the interface will be improved even more. Otherwise, I'm afraid we run the risk of repeating the situation with the vignette module controls, where the slider label is clearly wrong, but we've never agreed on the best way to rename it.

**Comment by HSUfineprint** [comment]
Could we use a drop-down list for most regular ISO steps, and keep the key-in capability in the same time? Something like sliders in some processing modules, users could choose numbers easily and also key-in parameters manually.

I agree with @victoryforce , if no consensus is reached on the best approach,  `UNLIMITED` or `UNBOUNDED` is an improvement.

**Comment by TurboGit** [comment]
@victoryforce : I agree with you, this is certainly a good step in the right direction. As you know I'm ok with small steps with incremental changes as otherwise it is hard to move forward as we all have different point of view (which is good). Personally I would probably have preferred the infinity symbol, let me know if this is ok to do the change here before I merge, but that's not blocking at all. Thanks.

**Review by TurboGit — APPROVED** [review]
Merging!

**Comment by TurboGit** [comment]
A little text for release notes please.

**Comment by victoryforce** [comment]
Maybe omething like:
"Improved the ISO range selection widget for the auto apply presets dialog."

**Comment by TurboGit** [comment]
> Improved the ISO range selection widget for the auto apply presets dialog.

Done, just fixed Improved to Improve. Thanks.

**Pull request merged**
